Repository milvus-io/milvus, pull requests merged in 2019-12, with the labels that each got.

#629 Issue 548
  CHANGELOG.md
  core/src/index/knowhere/knowhere/index/vector_index/IndexGPUIDMAP.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexGPUIDMAP.h
  core/src/index/knowhere/knowhere/index/vector_index/IndexIDMAP.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexIDMAP.h
  core/src/index/knowhere/knowhere/index/vector_index/IndexIVF.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexIVF.h
  core/src/index/knowhere/knowhere/index/vector_index/IndexNSG.cpp
  core/src/index/knowhere/knowhere/index/vector_index/nsg/NSG.cpp
  core/src/index/knowhere/knowhere/index/vector_index/nsg/NSG.h
  core/src/index/unittest/test_nsg/test_nsg.cpp
  core/src/index/unittest/utils.cpp
  core/src/index/unittest/utils.h
  core/src/wrapper/ConfAdapter.cpp
Labels: type/bug

#645 Add a new rpc command to get milvus build version whether cpu or gpu …
  CHANGELOG.md
  core/src/server/grpc_impl/request/CmdRequest.cpp
Labels: type/enhancement

#653 Typo "partiton" should be "partition"
  CHANGELOG.md
  core/src/db/DB.h
  core/src/db/DBImpl.cpp
  core/src/db/DBImpl.h
  core/src/db/meta/Meta.h
  core/src/db/meta/MySQLMetaImpl.cpp
  core/src/db/meta/MySQLMetaImpl.h
  core/src/db/meta/SqliteMetaImpl.cpp
  core/src/db/meta/SqliteMetaImpl.h
  core/src/sdk/examples/partition/src/ClientTest.cpp
  core/src/sdk/examples/simple/src/ClientTest.cpp
  core/src/sdk/examples/utils/Utils.cpp
  core/src/sdk/examples/utils/Utils.h
  core/src/sdk/grpc/ClientProxy.cpp
  core/src/sdk/grpc/ClientProxy.h
  core/src/sdk/include/MilvusApi.h
  core/src/sdk/interface/ConnectionImpl.cpp
  core/src/sdk/interface/ConnectionImpl.h
  core/unittest/db/test_db.cpp
  core/unittest/db/test_db_mysql.cpp
Labels: type/bug

#601 [skip ci] Add compilation in docker
  install.md
Labels: type/docs

#662 [skip ci] Update install.md
  install.md
Labels: type/docs

#655 #654 Random crash when frequently insert vector one by one
  CHANGELOG.md
  core/src/db/DBImpl.cpp
  core/src/db/insert/MemManagerImpl.cpp
  core/src/server/grpc_impl/request/CmdRequest.cpp
  core/src/server/grpc_impl/request/CountTableRequest.cpp
  core/src/server/grpc_impl/request/CreateIndexRequest.cpp
  core/src/server/grpc_impl/request/CreatePartitionRequest.cpp
  core/src/server/grpc_impl/request/CreateTableRequest.cpp
  core/src/server/grpc_impl/request/DeleteByDateRequest.cpp
  core/src/server/grpc_impl/request/DescribeIndexRequest.cpp
  core/src/server/grpc_impl/request/DescribeTableRequest.cpp
  core/src/server/grpc_impl/request/DropIndexRequest.cpp
  core/src/server/grpc_impl/request/DropPartitionRequest.cpp
  core/src/server/grpc_impl/request/DropTableRequest.cpp
  core/src/server/grpc_impl/request/HasTableRequest.cpp
  core/src/server/grpc_impl/request/InsertRequest.cpp
  core/src/server/grpc_impl/request/PreloadTableRequest.cpp
  core/src/server/grpc_impl/request/ShowPartitionsRequest.cpp
  core/src/server/grpc_impl/request/ShowTablesRequest.cpp
Labels: type/bug

#659 Change milvus deploy path to /var/lib/milvus
  ci/jenkins/Jenkinsfile
  ci/jenkins/internalJenkinsfile.groovy
  ci/jenkins/step/build.groovy
  ci/jenkins/step/coverage.groovy
  ci/jenkins/step/internalCoverage.groovy
  ci/jenkins/step/package.groovy
  ci/jenkins/yaml/update_server_config.yaml
  ci/scripts/build.sh
  ci/scripts/coverage.sh
  ci/travis/travis_build.sh
  ci/travis/travis_env_common.sh
  docker/build_env/cpu/ubuntu16.04/Dockerfile
  docker/build_env/cpu/ubuntu18.04/Dockerfile
  docker/build_env/gpu/ubuntu16.04/Dockerfile
  docker/build_env/gpu/ubuntu18.04/Dockerfile
  docker/deploy/cpu/ubuntu16.04/Dockerfile
  docker/deploy/cpu/ubuntu16.04/docker-entrypoint.sh
  docker/deploy/cpu/ubuntu18.04/Dockerfile
  docker/deploy/cpu/ubuntu18.04/docker-entrypoint.sh
  docker/deploy/gpu/ubuntu16.04/Dockerfile
  docker/deploy/gpu/ubuntu16.04/docker-entrypoint.sh
  docker/deploy/gpu/ubuntu18.04/Dockerfile
  docker/deploy/gpu/ubuntu18.04/docker-entrypoint.sh
  docker/docker-compose-monitor.yml
Labels: type/new-feature

#650 IP search metric_type shouldn't be supported by IVF_PQ index on GPU v…
  CHANGELOG.md
  core/src/server/grpc_impl/request/CreateIndexRequest.cpp
  core/src/wrapper/ConfAdapter.cpp
Labels: type/bug

#671 #670 Random failure of unittest db_test::SEARCH_TEST
  CHANGELOG.md
  core/unittest/db/test_db.cpp
Labels: type/bug

#669 [skip ci] #668 - Update badge of README
  CHANGELOG.md
  README.md
  README_CN.md
  README_JP.md
Labels: type/bug

#688 [skip ci] update install.md
  install.md
Labels: type/docs

#697 [skip ci] Update README.md.
  README.md
Labels: type/docs

#699 [skip ci] Update Chinese and Japanese readme
  README_CN.md
  README_JP.md
Labels: type/docs

#693 add code coverage rate and fix #670
  core/src/index/knowhere/knowhere/index/vector_index/IndexIVFSQHybrid.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexIVFSQHybrid.h
  core/src/index/knowhere/knowhere/index/vector_index/helpers/Cloner.cpp
  core/src/index/unittest/Helper.h
  core/src/wrapper/gpu/GPUVecImpl.cpp
  core/unittest/db/test_db.cpp
Labels: type/bug

#708 #674 server down in stability test
  CHANGELOG.md
  core/src/db/engine/ExecutionEngineImpl.cpp
  core/src/scheduler/task/BuildIndexTask.cpp
  core/src/scheduler/task/SearchTask.cpp
  core/src/wrapper/VecImpl.h
Labels: type/bug

#710 #696 metric_type changed from IP to L2
  CHANGELOG.md
  core/src/db/meta/MySQLMetaImpl.cpp
  core/src/db/meta/SqliteMetaImpl.cpp
Labels: type/bug

#741 [skip ci] Update the number of contributors.
  README.md
Labels: type/docs

#733 Add log to debug #678
  core/src/index/knowhere/knowhere/index/vector_index/FaissBaseIndex.cpp
  core/src/index/thirdparty/faiss/gpu/impl/IVFFlat.cu
  core/src/sdk/examples/utils/Utils.cpp
  core/src/sdk/include/MilvusApi.h
Labels: type/bug

#752 Add Github Actions and remove Travis CI
  .env
  .github/workflows/core.yml
  .gitignore
  .travis.yml
  ci/docker/ubuntu-18.04-core.dockerfile
  ci/jenkins/step/build.groovy
  ci/scripts/before-install.sh
  ci/scripts/build.sh
  ci/travis/before-install.sh
  ci/travis/install_dependency.sh
  ci/travis/travis_build.sh
  ci/travis/travis_env_common.sh
  docker-compose.yml
Labels: type/new-feature

#761 update github actions core.yml
  .github/workflows/core.yml
Labels: type/new-feature

#769 enable build milvus on centos7
  .env
  .github/workflows/core.yml
  ci/docker/centos-7-core.dockerfile
  core/centos7_build_deps.sh
  core/src/index/cmake/ThirdPartyPackagesCore.cmake
  core/unittest/server/test_config.cpp
  docker-compose.yml
  docker/build_env/cpu/centos7/Dockerfile
  docker/build_env/cpu/centos7/docker-entrypoint.sh
  docker/build_env/gpu/centos7/Dockerfile
  docker/build_env/gpu/centos7/docker-entrypoint.sh
  docker/deploy/cpu/centos7/Dockerfile
  docker/deploy/cpu/centos7/docker-entrypoint.sh
  docker/deploy/gpu/centos7/Dockerfile
  docker/deploy/gpu/centos7/docker-entrypoint.sh
Labels: type/new-feature

#774 Add CentOS 7 build case on Jenkins CI
  ci/jenkins/Jenkinsfile
  ci/jenkins/pod/milvus-cpu-version-centos7-build-env-pod.yaml
  ci/jenkins/pod/milvus-cpu-version-ubuntu18.04-build-env-pod.yaml
  ci/jenkins/pod/milvus-gpu-version-centos7-build-env-pod.yaml
  ci/jenkins/pod/milvus-gpu-version-ubuntu18.04-build-env-pod.yaml
  ci/jenkins/step/build.groovy
  ci/jenkins/step/deploySingle2Dev.groovy
  ci/jenkins/step/publishImages.groovy
  ci/jenkins/step/singleDevNightlyTest.groovy
  ci/jenkins/step/singleDevTest.groovy
  ci/scripts/check_ccache.sh
  ci/scripts/coverage.sh
  ci/scripts/update_ccache.sh
  core/cmake/ThirdPartyPackages.cmake
  docker-compose.yml
Labels: type/new-feature

#786 add customization option in build.sh
  ci/jenkins/step/build.groovy
  ci/scripts/build.sh
Labels: Awaiting dev feedback, type/bug

#790 Add Codecov on Github Actions
  .github/workflows/core.yml
  ci/jenkins/Jenkinsfile
  ci/jenkins/step/build.groovy
  ci/jenkins/step/deploySingle2Dev.groovy
  ci/jenkins/step/publishImages.groovy
  ci/jenkins/step/singleDevNightlyTest.groovy
  ci/jenkins/step/singleDevTest.groovy
  ci/jenkins/yaml/update_server_config.yaml
  ci/scripts/check_ccache.sh
  core/cmake/ThirdPartyPackages.cmake
  core/src/index/CMakeLists.txt
Labels: type/new-feature

#798 Use Helm version 3 on Jenkins CI
  ci/jenkins/Jenkinsfile
  ci/jenkins/pod/testEnvironment.yaml
  ci/jenkins/step/cleanupSingleDev.groovy
  ci/jenkins/step/deploySingle2Dev.groovy
  ci/jenkins/step/singleDevNightlyTest.groovy
  ci/jenkins/step/singleDevTest.groovy
  docker/test_env/Dockerfile
  docker/test_env/docker-entrypoint.sh
Labels: type/new-feature

#803 Add Test Framework resource limit on Jenkins CI
  ci/jenkins/pod/milvus-cpu-version-centos7-build-env-pod.yaml
  ci/jenkins/pod/milvus-cpu-version-ubuntu18.04-build-env-pod.yaml
  ci/jenkins/pod/milvus-gpu-version-centos7-build-env-pod.yaml
  ci/jenkins/pod/milvus-gpu-version-ubuntu18.04-build-env-pod.yaml
  ci/jenkins/pod/testEnvironment.yaml
Labels: type/enhancement

#739 Use openblas / lapack from apt install
  CHANGELOG.md
  ci/docker/centos-7-core.dockerfile
  ci/jenkins/pod/milvus-cpu-version-centos7-build-env-pod.yaml
  ci/jenkins/pod/milvus-gpu-version-centos7-build-env-pod.yaml
  core/centos7_build_deps.sh
  core/src/index/cmake/DefineOptionsCore.cmake
  core/src/index/cmake/FindFAISS.cmake
  core/src/index/cmake/ThirdPartyPackagesCore.cmake
  core/src/index/knowhere/CMakeLists.txt
  core/src/index/unittest/CMakeLists.txt
  core/src/index/unittest/faiss_benchmark/CMakeLists.txt
  core/src/index/unittest/faiss_ori/CMakeLists.txt
  core/ubuntu_build_deps.sh
  docker/build_env/cpu/centos7/Dockerfile
  docker/build_env/cpu/ubuntu16.04/Dockerfile
  docker/build_env/cpu/ubuntu18.04/Dockerfile
  docker/build_env/gpu/centos7/Dockerfile
  docker/build_env/gpu/ubuntu16.04/Dockerfile
  docker/build_env/gpu/ubuntu18.04/Dockerfile
  docker/deploy/cpu/centos7/Dockerfile
  docker/deploy/cpu/ubuntu16.04/Dockerfile
  docker/deploy/cpu/ubuntu18.04/Dockerfile
  docker/deploy/gpu/centos7/Dockerfile
  docker/deploy/gpu/ubuntu16.04/Dockerfile
  docker/deploy/gpu/ubuntu18.04/Dockerfile
Labels: type/enhancement

#817 Remove Arrow
  CHANGELOG.md
  ci/jenkins/step/build.groovy
  core/src/index/cmake/DefineOptionsCore.cmake
  core/src/index/knowhere/CMakeLists.txt
  core/src/index/knowhere/knowhere/adapter/ArrowAdapter.cpp
  core/src/index/knowhere/knowhere/adapter/ArrowAdapter.h
  core/src/index/knowhere/knowhere/adapter/SptagAdapter.cpp
  core/src/index/knowhere/knowhere/adapter/SptagAdapter.h
  core/src/index/knowhere/knowhere/adapter/Structure.cpp
  core/src/index/knowhere/knowhere/adapter/VectorAdapter.cpp
  core/src/index/knowhere/knowhere/adapter/VectorAdapter.h
  core/src/index/knowhere/knowhere/common/Array.h
  core/src/index/knowhere/knowhere/common/Buffer.h
  core/src/index/knowhere/knowhere/common/Dataset.h
  core/src/index/knowhere/knowhere/common/Schema.h
  core/src/index/knowhere/knowhere/common/Tensor.h
  core/src/index/knowhere/knowhere/index/vector_index/IndexGPUIDMAP.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexGPUIDMAP.h
  core/src/index/knowhere/knowhere/index/vector_index/IndexIDMAP.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexIDMAP.h
  core/src/index/knowhere/knowhere/index/vector_index/IndexIVF.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexIVF.h
  core/src/index/knowhere/knowhere/index/vector_index/IndexNSG.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexSPTAG.cpp
  core/src/index/unittest/CMakeLists.txt
  core/src/index/unittest/faiss_benchmark/CMakeLists.txt
  core/src/index/unittest/faiss_ori/CMakeLists.txt
  core/src/index/unittest/test_idmap.cpp
  core/src/index/unittest/test_ivf.cpp
  core/src/index/unittest/test_sptag.cpp
  core/src/index/unittest/utils.cpp
  core/src/index/unittest/utils.h
  core/src/wrapper/DataTransfer.cpp
  core/src/wrapper/DataTransfer.h
  core/src/wrapper/VecImpl.cpp
  core/src/wrapper/VecImpl.h
Labels: type/enhancement

#832 Define interface
  CHANGELOG.md
  core/src/index/knowhere/CMakeLists.txt
  core/src/index/knowhere/knowhere/index/vector_index/FaissBaseBinaryIndex.cpp
  core/src/index/knowhere/knowhere/index/vector_index/FaissBaseBinaryIndex.h
  core/src/index/knowhere/knowhere/index/vector_index/IndexBinaryIDMAP.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexBinaryIDMAP.h
  core/src/index/knowhere/knowhere/index/vector_index/IndexBinaryIVF.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexBinaryIVF.h
  core/src/utils/StringHelpFunctions.cpp
Labels: type/new-feature

#827 Remove Jfrog Cache on Jenkins CI
  ci/jenkins/Jenkinsfile
  ci/jenkins/pod/milvus-cpu-version-centos7-build-env-pod.yaml
  ci/jenkins/pod/milvus-cpu-version-ubuntu18.04-build-env-pod.yaml
  ci/jenkins/pod/milvus-gpu-version-centos7-build-env-pod.yaml
  ci/jenkins/pod/milvus-gpu-version-ubuntu18.04-build-env-pod.yaml
  ci/scripts/build.sh
  ci/scripts/check_ccache.sh
  core/build.sh
  core/cmake/ThirdPartyPackages.cmake
  core/src/index/build.sh
  core/src/index/cmake/ThirdPartyPackagesCore.cmake
  core/src/index/thirdparty/faiss/ci/jenkins/Jenkinsfile
  core/src/index/thirdparty/faiss/ci/jenkins/step/build.groovy
  core/src/index/thirdparty/faiss/ci/jenkins/step/coverage.groovy
  core/src/index/thirdparty/faiss/ci/scripts/build.sh
  sdk/cmake/ThirdPartyPackages.cmake
Labels: type/new-feature

#842 faiss & knowhere
  core/src/index/knowhere/knowhere/adapter/VectorAdapter.h
  core/src/index/knowhere/knowhere/common/Config.h
  core/src/index/knowhere/knowhere/index/vector_index/FaissBaseBinaryIndex.cpp
  core/src/index/knowhere/knowhere/index/vector_index/FaissBaseBinaryIndex.h
  core/src/index/knowhere/knowhere/index/vector_index/IndexBinaryIDMAP.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexBinaryIDMAP.h
  core/src/index/knowhere/knowhere/index/vector_index/IndexBinaryIVF.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexBinaryIVF.h
  core/src/index/knowhere/knowhere/index/vector_index/helpers/IndexParameter.cpp
  core/src/index/knowhere/knowhere/index/vector_index/helpers/IndexParameter.h
  core/src/index/thirdparty/faiss/Index.h
  core/src/index/thirdparty/faiss/IndexBinaryFlat.cpp
  core/src/index/thirdparty/faiss/IndexBinaryFlat.h
  core/src/index/thirdparty/faiss/IndexBinaryIVF.cpp
  core/src/index/thirdparty/faiss/IndexBinaryIVF.h
  core/src/index/thirdparty/faiss/IndexFlat.cpp
  core/src/index/thirdparty/faiss/index_factory.cpp
  core/src/index/thirdparty/faiss/index_factory.h
  core/src/index/thirdparty/faiss/utils/distances.cpp
  core/src/index/thirdparty/faiss/utils/distances.h
  core/src/index/thirdparty/faiss/utils/extra_distances.cpp
  core/src/index/thirdparty/faiss/utils/jaccard-inl.h
  core/src/index/thirdparty/faiss/utils/jaccard.cpp
  core/src/index/thirdparty/faiss/utils/jaccard.h
Labels: type/new-feature

#840 Custom defined name for the upload on Codecov
  .github/workflows/core.yml
  ci/jenkins/step/coverage.groovy
Labels: type/enhancement

#871 #823 Support binary vector tanimoto metric
  CHANGELOG.md
  core/src/scheduler/task/SearchTask.cpp
  core/src/scheduler/task/SearchTask.h
  sdk/examples/binary_vector/src/ClientTest.cpp
  sdk/examples/utils/Utils.cpp
  sdk/include/MilvusApi.h
Labels: type/new-feature

#879 [skip ci] Fix some broken links in the readme files
  README.md
  README_CN.md
  README_JP.md
Labels: type/docs
