Repository milvus-io/milvus, pull requests merged in 2019-11, with the labels that each got.

#162 Fix ivfsqh crash
  CHANGELOG.md
  core/src/db/engine/ExecutionEngineImpl.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexIVFSQHybrid.cpp
  core/src/index/unittest/test_ivf.cpp
Labels: bug

#129 [skip ci] Create README_CN.md
  README_CN.md
Labels: documentation

#165 #164 - Add CPU version for building index
  CHANGELOG.md
  core/src/scheduler/JobMgr.cpp
  core/src/scheduler/SchedInst.cpp
  core/src/scheduler/SchedInst.h
  core/src/scheduler/TaskCreator.cpp
  core/src/scheduler/action/PushTaskToNeighbour.cpp
  core/src/scheduler/optimizer/OnlyGPUPass.cpp
  core/src/server/Config.cpp
  core/src/server/Config.h
Labels: enhancement

#171 #169 - IVF_FLAT search out of memory
  CHANGELOG.md
  core/src/db/engine/ExecutionEngineImpl.cpp
Labels: bug

#172 #168 improve result reduce
  CHANGELOG.md
  core/src/db/DB.h
  core/src/db/DBImpl.cpp
  core/src/db/DBImpl.h
  core/src/db/Types.h
  core/src/scheduler/job/SearchJob.cpp
  core/src/scheduler/job/SearchJob.h
  core/src/scheduler/task/SearchTask.cpp
  core/src/scheduler/task/SearchTask.h
  core/src/server/grpc_impl/GrpcRequestTask.cpp
  core/unittest/db/test_db.cpp
  core/unittest/db/test_db_mysql.cpp
  core/unittest/db/test_mem.cpp
  core/unittest/db/test_search.cpp
  core/unittest/metrics/test_metrics.cpp
Labels: enhancement

#147 [skip ci] Update Python example code link
  CONTRIBUTING.md
  NOTICE.md
  README.md
  install.md
Labels: documentation

#187 Update README.md
  README.md
Labels: documentation

#189 Update default config and server version printout
  CHANGELOG.md
  NOTICE.md
  core/CMakeLists.txt
  core/conf/server_config.template
  core/src/cache/Cache.h
  core/src/cache/CacheMgr.h
Labels: enhancement

#198 Update server configure file on packing stage
  ci/jenkins/scripts/requirements.txt
  ci/jenkins/scripts/yaml_processor.py
  ci/jenkins/step/package.groovy
  ci/jenkins/yaml/update_server_config.yaml
  docker/build_env/ubuntu16.04/Dockerfile
  docker/build_env/ubuntu18.04/Dockerfile
Labels: enhancement

#214 git ignore config.h
  core/.gitignore
  core/src/config.h
Labels: bug

#234 [skip ci] Update README
  README.md
  README_CN.md
Labels: documentation

#251 Delete unittest binary on jenkins ci packaging stage
  ci/jenkins/step/packaging.groovy
  ci/jenkinsfile/packaged_milvus.groovy
Labels: enhancement

#253 #246 Exclude src/external folder from code coverage for jenkin ci
  CHANGELOG.md
  ci/jenkins/scripts/coverage.sh
  core/coverage.sh
Labels: bug

#239 improve grpc performance in search
  CHANGELOG.md
  ci/jenkins/step/deploySingle2Dev.groovy
  ci/jenkins/step/singleDevNightlyTest.groovy
  ci/jenkins/step/singleDevTest.groovy
  core/CMakeLists.txt
  core/src/grpc/README.md
  core/src/grpc/gen-milvus/milvus.grpc.pb.cc
  core/src/grpc/gen-milvus/milvus.grpc.pb.h
  core/src/grpc/gen-milvus/milvus.pb.cc
  core/src/grpc/gen-milvus/milvus.pb.h
  core/src/grpc/milvus.proto
  core/src/sdk/examples/grpcsimple/src/ClientTest.cpp
  core/src/sdk/grpc/ClientProxy.cpp
  core/src/sdk/grpc/ClientProxy.h
  core/src/sdk/grpc/GrpcClient.cpp
  core/src/sdk/grpc/GrpcClient.h
  core/src/sdk/include/MilvusApi.h
  core/src/sdk/interface/ConnectionImpl.cpp
  core/src/sdk/interface/ConnectionImpl.h
  core/src/server/grpc_impl/GrpcRequestHandler.cpp
  core/src/server/grpc_impl/GrpcRequestHandler.h
  core/src/server/grpc_impl/GrpcRequestTask.cpp
  core/src/server/grpc_impl/GrpcRequestTask.h
  core/src/server/grpc_impl/GrpcServer.cpp
  core/unittest/server/test_rpc.cpp
Labels: enhancement

#259 Bytes type in proto cause big-endian/little-endian problem
  CHANGELOG.md
  core/src/grpc/README.md
  core/src/grpc/gen-milvus/milvus.pb.cc
  core/src/grpc/gen-milvus/milvus.pb.h
  core/src/grpc/milvus.proto
  core/src/sdk/examples/grpcsimple/src/ClientTest.cpp
  core/src/sdk/grpc/ClientProxy.cpp
  core/src/sdk/include/MilvusApi.h
  core/src/server/grpc_impl/GrpcRequestTask.cpp
Labels: enhancement

#279 Add JP version of README
  README.md
Labels: documentation

#285 #284 Change C++ SDK to shared library
  CHANGELOG.md
  core/src/sdk/CMakeLists.txt
Labels: enhancement

#286 #284 Change C++ SDK to shared library
  CHANGELOG.md
  core/src/sdk/CMakeLists.txt
Labels: enhancement

#291 [skip ci] Add C++ SDK link
  README.md
Labels: documentation

#290 [skip ci] Updated the Japanese readme
  README_JP.md
Labels: documentation

#298 Add Mishards README
  shards/README.md
  shards/README_CN.md
  shards/Tutorial_CN.md
Labels: documentation

#304 Add Travis CI for Milvus
  .travis.yml
  ci/scripts/build.sh
  ci/travis/before-install.sh
  ci/travis/install_dependency.sh
  ci/travis/travis_build.sh
  ci/travis/travis_env_common.sh
  core/CMakeLists.txt
  core/cmake/DefineOptions.cmake
  core/cmake/ThirdPartyPackages.cmake
  core/src/index/CMakeLists.txt
  core/src/index/cmake/DefineOptionsCore.cmake
  core/src/index/cmake/FindArrow.cmake
  core/src/index/cmake/ThirdPartyPackagesCore.cmake
  core/src/index/knowhere/CMakeLists.txt
  core/src/index/thirdparty/versions.txt
  core/src/index/unittest/CMakeLists.txt
  core/src/index/unittest/faiss_benchmark/CMakeLists.txt
  core/src/index/unittest/faiss_ori/CMakeLists.txt
  core/thirdparty/versions.txt
Labels: enhancement

#300 #260 C++ SDK README
  CHANGELOG.md
  core/src/sdk/README.md
Labels: documentation

#299 #260 C++ SDK README
  CHANGELOG.md
  core/src/sdk/README.md
Labels: documentation

#311 Add server_gpu_config.templete for generate server_config.yaml
  ci/jenkins/scripts/build.sh
  ci/jenkins/step/build.groovy
  ci/jenkins/step/coverage.groovy
  ci/scripts/build.sh
  ci/scripts/coverage.sh
  core/CMakeLists.txt
  core/conf/server_cpu_config.template
  core/conf/server_gpu_config.template
Labels: enhancement

#317 add Find FAISS in CMake
  CHANGELOG.md
  ci/scripts/build.sh
  core/build.sh
  core/src/CMakeLists.txt
  core/src/index/build.sh
  core/src/index/cmake/DefineOptionsCore.cmake
  core/src/index/cmake/FindFAISS.cmake
  core/src/index/cmake/ThirdPartyPackagesCore.cmake
  core/src/index/knowhere/CMakeLists.txt
  core/src/index/thirdparty/versions.txt
  core/src/index/unittest/CMakeLists.txt
  core/src/index/unittest/faiss_benchmark/CMakeLists.txt
  core/src/index/unittest/faiss_ori/CMakeLists.txt
  core/src/index/unittest/test_nsg/CMakeLists.txt
Labels: enhancement

#320 Fix determine Milvus version from git branch name bug
  core/CMakeLists.txt
Labels: bug

#339 Update server_version to 0.6.0 & add CPU version run image
  tests/milvus-java-test/pom.xml
  tests/milvus_python_test/test_ping.py
Labels: bug

#332 Add option to enable / disable prometheus
  CHANGELOG.md
  core/CMakeLists.txt
  core/build.sh
  core/src/CMakeLists.txt
  core/src/metrics/Metrics.cpp
  core/src/metrics/prometheus/PrometheusMetrics.cpp
  core/src/metrics/prometheus/PrometheusMetrics.h
  core/unittest/CMakeLists.txt
  core/unittest/metrics/CMakeLists.txt
  core/unittest/metrics/test_prometheus.cpp
Labels: enhancement

#335 memory usage increased slowly during searching vectors
  CHANGELOG.md
  core/src/index/knowhere/knowhere/adapter/SptagAdapter.cpp
  core/src/index/knowhere/knowhere/common/Dataset.h
  core/src/index/knowhere/knowhere/index/vector_index/IndexIDMAP.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexIVF.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexNSG.cpp
  core/src/index/unittest/test_ivf.cpp
  core/src/index/unittest/test_kdt.cpp
  core/src/index/unittest/utils.cpp
  core/src/wrapper/VecImpl.cpp
Labels: bug

#334 #316 Some files not merged after vectors added
  CHANGELOG.md
  core/src/db/DBImpl.cpp
  core/src/db/meta/MySQLMetaImpl.cpp
  core/src/db/meta/SqliteMetaImpl.cpp
Labels: bug

#347 #340 Test cases run failed on 0.6.0
  CHANGELOG.md
  core/src/db/DBImpl.cpp
  core/src/db/DBImpl.h
Labels: bug

#359 Update build.sh and install.md
  CHANGELOG.md
  core/build.sh
  install.md
Labels: enhancement

#351 Update Jenkins CI and Docker to 0.6.0
  ci/jenkins/Jenkinsfile
  ci/jenkins/pod/milvus-cpu-version-build-env-pod.yaml
  ci/jenkins/pod/milvus-gpu-version-build-env-pod.yaml
  ci/jenkins/step/build.groovy
  ci/jenkins/step/cleanupSingleDev.groovy
  ci/jenkins/step/deploySingle2Dev.groovy
  ci/jenkins/step/publishImages.groovy
  ci/jenkins/step/singleDevNightlyTest.groovy
  ci/jenkins/step/singleDevTest.groovy
  docker/build_env/cpu/ubuntu16.04/Dockerfile
  docker/build_env/cpu/ubuntu16.04/docker-entrypoint.sh
  docker/build_env/cpu/ubuntu18.04/Dockerfile
  docker/build_env/cpu/ubuntu18.04/docker-entrypoint.sh
  docker/build_env/gpu/ubuntu16.04/Dockerfile
  docker/build_env/gpu/ubuntu16.04/docker-entrypoint.sh
  docker/build_env/gpu/ubuntu18.04/Dockerfile
  docker/build_env/gpu/ubuntu18.04/docker-entrypoint.sh
  docker/deploy/cpu/ubuntu16.04/Dockerfile
  docker/deploy/cpu/ubuntu16.04/docker-entrypoint.sh
  docker/deploy/cpu/ubuntu18.04/Dockerfile
  docker/deploy/cpu/ubuntu18.04/docker-entrypoint.sh
  docker/deploy/gpu/ubuntu16.04/Dockerfile
  docker/deploy/gpu/ubuntu16.04/docker-entrypoint.sh
  docker/deploy/gpu/ubuntu18.04/Dockerfile
  docker/deploy/gpu/ubuntu18.04/docker-entrypoint.sh
Labels: enhancement

#365 #327 fix flat doesn't use gpu bug
  CHANGELOG.md
  core/src/scheduler/interface/interfaces.h
  core/src/scheduler/optimizer/OnlyGPUPass.cpp
Labels: bug

#379 Update case
  tests/milvus_python_test/conftest.py
  tests/milvus_python_test/test_connect.py
Labels: bug

#376 sdk_simple return empty result
  CHANGELOG.md
  core/src/grpc/gen-milvus/milvus.pb.h
  core/src/sdk/grpc/ClientProxy.cpp
  core/src/server/grpc_impl/GrpcRequestTask.cpp
Labels: bug

#381 fix by reduce knng size
  core/src/index/CMakeLists.txt
  core/src/index/knowhere/knowhere/common/Config.h
  core/src/index/knowhere/knowhere/index/vector_index/helpers/IndexParameter.cpp
  core/src/index/knowhere/knowhere/index/vector_index/helpers/IndexParameter.h
  core/src/wrapper/ConfAdapter.cpp
  core/src/wrapper/ConfAdapter.h
  core/unittest/wrapper/test_wrapper.cpp
  core/unittest/wrapper/utils.cpp
  core/unittest/wrapper/utils.h
Labels: bug

#398 #397 sdk_simple return incorrect result
  CHANGELOG.md
  core/src/sdk/examples/utils/Utils.cpp
Labels: bug

#406 [skip ci] Change ivfsq8 test report detailed version #255
  docs/test_report/milvus_ivfsq8_test_report_detailed_version.md
  docs/test_report/milvus_ivfsq8_test_report_detailed_version_cn.md
Labels: documentation

#402 [skip ci] Add note about using unbuntu docker
  install.md
Labels: documentation

#405 Add virtual method Init() in Pass abstract class close #404
  CHANGELOG.md
  core/src/scheduler/SchedInst.cpp
  core/src/scheduler/optimizer/HybridPass.cpp
  core/src/scheduler/optimizer/HybridPass.h
  core/src/scheduler/optimizer/LargeSQ8HPass.cpp
  core/src/scheduler/optimizer/LargeSQ8HPass.h
  core/src/scheduler/optimizer/OnlyCPUPass.cpp
  core/src/scheduler/optimizer/OnlyCPUPass.h
  core/src/scheduler/optimizer/OnlyGPUPass.cpp
  core/src/scheduler/optimizer/OnlyGPUPass.h
  core/src/scheduler/optimizer/Optimizer.cpp
  core/src/scheduler/optimizer/Optimizer.h
  core/src/scheduler/optimizer/Pass.h
Labels: enhancement

#407 Fix Deployed GPU-version docker failed in CI
  ci/jenkins/step/deploySingle2Dev.groovy
  ci/jenkins/step/singleDevNightlyTest.groovy
  ci/jenkins/step/singleDevTest.groovy
Labels: enhancement

#410 Add a Fallback pass in optimizer close #409
  CHANGELOG.md
  core/src/scheduler/SchedInst.h
  core/src/scheduler/optimizer/FallbackPass.cpp
  core/src/scheduler/optimizer/FallbackPass.h
Labels: enhancement

#411 [skip ci] Change ivfsq8 test report detailed version #255
  docs/test_report/milvus_ivfsq8_test_report_detailed_version.md
  docs/test_report/milvus_ivfsq8_test_report_detailed_version_cn.md
Labels: documentation

#428 CI code coverage log disappeared
  ci/jenkins/Jenkinsfile
  ci/scripts/build.sh
Labels: bug

#431 [skip ci] Add README for docs file
  docs/README.md
Labels: documentation

#432 [skip ci] add ivfsq8h test report detailed version #255
  docs/test_report/milvus_ivfsq8h_test_report_detailed_version.md
  docs/test_report/milvus_ivfsq8h_test_report_detailed_version_cn.md
Labels: documentation

#438 0.6.0 #227
  CHANGELOG.md
  core/src/db/engine/ExecutionEngine.h
  core/src/db/engine/ExecutionEngineImpl.cpp
  core/src/index/knowhere/CMakeLists.txt
  core/src/index/knowhere/knowhere/index/vector_index/IndexKDT.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexSPTAG.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexSPTAG.h
  core/src/index/knowhere/knowhere/index/vector_index/helpers/IndexParameter.h
  core/src/index/knowhere/knowhere/index/vector_index/helpers/KDTParameterMgr.cpp
  core/src/index/knowhere/knowhere/index/vector_index/helpers/SPTAGParameterMgr.cpp
  core/src/index/knowhere/knowhere/index/vector_index/helpers/SPTAGParameterMgr.h
  core/src/index/thirdparty/SPTAG/AnnService/inc/Core/Common/Dataset.h
  core/src/index/unittest/CMakeLists.txt
  core/src/index/unittest/test_kdt.cpp
  core/src/index/unittest/test_sptag.cpp
  core/src/index/unittest/utils.cpp
  core/src/wrapper/ConfAdapter.cpp
  core/src/wrapper/ConfAdapter.h
  core/src/wrapper/ConfAdapterMgr.cpp
  core/src/wrapper/VecImpl.cpp
  core/src/wrapper/VecIndex.cpp
  core/src/wrapper/VecIndex.h
  core/unittest/wrapper/test_wrapper.cpp
Labels: enhancement

#441 fix
  core/src/wrapper/VecImpl.cpp
Labels: bug

#442 #433 C++ SDK query result is not easy to use
  CHANGELOG.md
  core/scripts/migration/README.md
  core/scripts/migration/mysql_4_to_6.sql
  core/scripts/migration/mysql_6_to_4.sql
  core/scripts/migration/sqlite_4_to_6.sql
  core/scripts/migration/sqlite_6_to_4.sql
  core/src/sdk/examples/partition/src/ClientTest.cpp
  core/src/sdk/examples/simple/src/ClientTest.cpp
  core/src/sdk/examples/utils/Utils.cpp
  core/src/sdk/grpc/ClientProxy.cpp
  core/src/sdk/include/MilvusApi.h
Labels: enhancement

#445 mark off faiss version
  ci/jenkins/Jenkinsfile
  ci/scripts/coverage.sh
  core/src/index/cmake/ThirdPartyPackagesCore.cmake
Labels: bug

#454 Format Jenkins CI
  ci/jenkins/step/singleDevNightlyTest.groovy
  ci/jenkins/step/singleDevTest.groovy
Labels: enhancement

#461 Fix Domain host set not correct in CI bug
  ci/jenkins/step/singleDevNightlyTest.groovy
  ci/jenkins/step/singleDevTest.groovy
Labels: type/bug

#451 #449 Add ShowPartitions example for C++ SDK
  CHANGELOG.md
  core/src/sdk/examples/partition/src/ClientTest.cpp
Labels: enhancement

#463 move seal to Load
  CHANGELOG.md
  core/src/index/knowhere/knowhere/index/vector_index/FaissBaseIndex.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexGPUIVF.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexIVF.cpp
Labels: type/bug

#448 [skip ci] Add link to test reports
  README.md
  README_CN.md
  README_JP.md
Labels: type/docs

#464 format Jenkinsfile
  ci/jenkins/Jenkinsfile
  ci/jenkins/pod/milvus-cpu-version-build-env-pod.yaml
  ci/jenkins/pod/milvus-gpu-version-build-env-pod.yaml
  ci/jenkins/step/cleanupSingleDev.groovy
  ci/jenkins/step/deploySingle2Dev.groovy
  ci/jenkins/step/publishImages.groovy
  ci/jenkins/step/singleDevNightlyTest.groovy
  ci/jenkins/step/singleDevTest.groovy
Labels: type/enhancement

#482 clean up old jenkins ci
  ci/function/file_transfer.groovy
  ci/jenkins/step/package.groovy
  ci/jenkinsfile/cleanup_dev.groovy
  ci/jenkinsfile/cleanup_staging.groovy
  ci/jenkinsfile/cluster_cleanup_dev.groovy
  ci/jenkinsfile/cluster_deploy2dev.groovy
  ci/jenkinsfile/cluster_dev_test.groovy
  ci/jenkinsfile/deploy2dev.groovy
  ci/jenkinsfile/deploy2staging.groovy
  ci/jenkinsfile/dev_test.groovy
  ci/jenkinsfile/dev_test_all.groovy
  ci/jenkinsfile/milvus_build.groovy
  ci/jenkinsfile/milvus_build_no_ut.groovy
  ci/jenkinsfile/nightly_publish_docker.groovy
  ci/jenkinsfile/notify.groovy
  ci/jenkinsfile/packaged_milvus.groovy
  ci/jenkinsfile/packaged_milvus_no_ut.groovy
  ci/jenkinsfile/publish_docker.groovy
  ci/jenkinsfile/staging_test.groovy
  ci/jenkinsfile/upload_dev_cluster_test_out.groovy
  ci/jenkinsfile/upload_dev_test_out.groovy
  ci/jenkinsfile/upload_staging_test_out.groovy
  ci/main_jenkinsfile
  ci/main_jenkinsfile_no_ut
  ci/nightly_main_jenkinsfile
  ci/pod_containers/milvus-engine-build.yaml
  ci/pod_containers/milvus-testframework.yaml
  ci/pod_containers/publish-docker.yaml
  core/cmake/BuildUtils.cmake
Labels: type/enhancement

#469 Read gpu config only gpu_resource_config.enable=true fix #467
  CHANGELOG.md
  core/src/scheduler/SchedInst.cpp
  core/src/scheduler/SchedInst.h
  core/src/server/Config.cpp
  core/src/wrapper/KnowhereResource.cpp
Labels: type/bug

#478 Update cases to 0.6.0
  tests/milvus_ann_acc/ci/function/file_transfer.groovy
  tests/milvus_ann_acc/ci/jenkinsfile/acc_test.groovy
  tests/milvus_ann_acc/ci/jenkinsfile/cleanup.groovy
  tests/milvus_ann_acc/ci/jenkinsfile/deploy_default_server.groovy
  tests/milvus_ann_acc/ci/jenkinsfile/notify.groovy
  tests/milvus_ann_acc/ci/main_jenkinsfile
  tests/milvus_ann_acc/ci/pod_containers/milvus-testframework.yaml
  tests/milvus_ann_acc/client.py
  tests/milvus_ann_acc/main.py
  tests/milvus_ann_acc/requirements.txt
  tests/milvus_ann_acc/runner.py
  tests/milvus_ann_acc/suite.yaml
  tests/milvus_ann_acc/suite.yaml.bak
  tests/milvus_ann_acc/suite_czr.yaml
  tests/milvus_ann_acc/suite_debug.yaml
  tests/milvus_ann_acc/test.py
  tests/milvus_python_test/test_connect.py
  tests/milvus_python_test/test_mix.py
Labels: type/enhancement

#474 #470 raw files should not be build index
  CHANGELOG.md
  core/src/db/DBImpl.cpp
  core/src/db/DBImpl.h
  core/src/db/meta/Meta.h
  core/src/db/meta/MetaConsts.h
  core/src/db/meta/MySQLMetaImpl.cpp
  core/src/db/meta/MySQLMetaImpl.h
  core/src/db/meta/SqliteMetaImpl.cpp
  core/src/db/meta/SqliteMetaImpl.h
  core/unittest/db/test_meta.cpp
  core/unittest/db/test_meta_mysql.cpp
Labels: type/bug

#489 log path update to default '/opt'
  ci/jenkins/step/package.groovy
Labels: type/enhancement

#490 fixed Helm Release Name bug
  ci/jenkins/Jenkinsfile
Labels: type/bug

#495 [skip ci] Small change on test report
  docs/test_report/milvus_ivfsq8_test_report_detailed_version_cn.md
  docs/test_report/milvus_ivfsq8h_test_report_detailed_version_cn.md
Labels: type/docs

#496 #485 Increase code coverage rate
  core/src/cache/GpuCacheMgr.cpp
  core/src/cache/GpuCacheMgr.h
  core/src/db/engine/ExecutionEngineImpl.cpp
  core/src/main.cpp
  core/src/scheduler/optimizer/BuildIndexPass.cpp
  core/src/scheduler/optimizer/FaissFlatPass.cpp
  core/src/scheduler/optimizer/FaissIVFFlatPass.cpp
  core/src/scheduler/optimizer/FaissIVFSQ8HPass.cpp
  core/src/scheduler/optimizer/FaissIVFSQ8Pass.cpp
  core/src/server/Config.cpp
  core/src/server/Config.h
  core/src/server/Server.cpp
  core/src/utils/StringHelpFunctions.h
  core/src/utils/ValidationUtil.cpp
  core/src/utils/ValidationUtil.h
  core/unittest/db/utils.cpp
  core/unittest/scheduler/test_scheduler.cpp
  core/unittest/server/test_cache.cpp
  core/unittest/server/test_config.cpp
  core/unittest/server/test_rpc.cpp
  core/unittest/server/test_util.cpp
Labels: type/bug

#501 fixed Helm Release Name bug
  ci/jenkins/Jenkinsfile
Labels: type/bug

#503 #502 C++ SDK support IVFPQ and SPTAG
  CHANGELOG.md
  core/src/sdk/examples/utils/Utils.cpp
  core/src/sdk/include/MilvusApi.h
Labels: type/new-feature

#507 fixed Helm Release Name bug
  ci/jenkins/Jenkinsfile
Labels: type/bug

#510 Remove unittest file from docker image
  ci/jenkins/step/package.groovy
Labels: type/enhancement

#519 disable untar verbose
  core/CMakeLists.txt
  core/src/index/cmake/BuildUtilsCore.cmake
Labels: type/bug

#514 Add codecov badge in README.md
  README.md
  README_CN.md
Labels: type/enhancement

#524 #513 DELETE_BY_RANGE sometimes failed
  CHANGELOG.md
  core/src/db/DBImpl.cpp
  core/src/db/DBImpl.h
Labels: type/bug

#521 Fix Issue 465
  CHANGELOG.md
  core/build.sh
  core/src/index/knowhere/knowhere/common/Timer.cpp
  core/src/index/knowhere/knowhere/index/vector_index/nsg/NSG.cpp
Labels: type/bug

#522 fix issue-509
  CHANGELOG.md
  core/src/wrapper/ConfAdapter.cpp
Labels: type/bug

#540 Add ccache in Jenkins CI
  ci/jenkins/step/build.groovy
  ci/scripts/before-install.sh
  ci/scripts/check_ccache.sh
  ci/scripts/update_ccache.sh
  docker/build_env/cpu/ubuntu16.04/Dockerfile
  docker/build_env/cpu/ubuntu18.04/Dockerfile
  docker/build_env/gpu/ubuntu16.04/Dockerfile
  docker/build_env/gpu/ubuntu18.04/Dockerfile
Labels: type/enhancement

#546 update update_ccache.sh
  ci/scripts/update_ccache.sh
  core/CMakeLists.txt
Labels: type/enhancement

#549 update update_ccache.sh
  ci/scripts/update_ccache.sh
Labels: type/enhancement

#551 add BUILD_ENV_IMAGE_ID environment values
  ci/jenkins/pod/milvus-cpu-version-build-env-pod.yaml
  ci/jenkins/pod/milvus-gpu-version-build-env-pod.yaml
  ci/scripts/check_ccache.sh
  ci/scripts/update_ccache.sh
Labels: type/enhancement

#553 add ccache in build stage
  ci/jenkins/step/build.groovy
Labels: type/enhancement

#536 (shards): python sdk test failed when test method add_vectors with partition
  CHANGELOG.md
  shards/mishards/service_handler.py
  tests/milvus_python_test/test_add_vectors.py
  tests/milvus_python_test/utils.py
Labels: type/bug

#555 #530 BuildIndex stop when do build index and search simultaneously
  CHANGELOG.md
  core/src/cache/Cache.inl
  core/src/db/DBImpl.cpp
  core/src/db/engine/ExecutionEngineImpl.cpp
  core/src/db/meta/Meta.h
  core/src/db/meta/MySQLMetaImpl.cpp
  core/src/db/meta/MySQLMetaImpl.h
  core/src/db/meta/SqliteMetaImpl.cpp
  core/src/db/meta/SqliteMetaImpl.h
  core/src/utils/CommonUtil.cpp
  core/src/utils/CommonUtil.h
  core/unittest/db/test_meta.cpp
Labels: type/bug

#558 update update_ccache.sh
  ci/scripts/check_ccache.sh
  ci/scripts/update_ccache.sh
Labels: type/enhancement

#559 change milvus db_path to CMAKE_INSTALL_PREFIX
  ci/scripts/check_ccache.sh
  ci/scripts/update_ccache.sh
  core/CMakeLists.txt
Labels: type/enhancement

#572 #504 The code coverage rate of core/src/scheduler/optimizer is too low
  CHANGELOG.md
  core/src/db/engine/ExecutionEngine.h
  core/src/db/engine/ExecutionEngineImpl.cpp
  core/src/db/engine/ExecutionEngineImpl.h
  core/src/index/knowhere/knowhere/index/vector_index/IndexGPUIDMAP.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexGPUIDMAP.h
  core/src/index/knowhere/knowhere/index/vector_index/IndexGPUIVF.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexGPUIVF.h
  core/src/index/knowhere/knowhere/index/vector_index/IndexIDMAP.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexIDMAP.h
  core/src/index/knowhere/knowhere/index/vector_index/IndexIVF.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexIVF.h
  core/src/index/knowhere/knowhere/index/vector_index/IndexIVFPQ.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexIVFPQ.h
  core/src/index/knowhere/knowhere/index/vector_index/IndexIVFSQ.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexIVFSQ.h
  core/src/index/knowhere/knowhere/index/vector_index/IndexNSG.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexNSG.h
  core/src/index/knowhere/knowhere/index/vector_index/IndexSPTAG.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexSPTAG.h
  core/src/index/knowhere/knowhere/index/vector_index/VectorIndex.h
  core/src/index/knowhere/knowhere/index/vector_index/helpers/IndexParameter.h
  core/src/index/unittest/test_idmap.cpp
  core/src/index/unittest/test_ivf.cpp
  core/src/index/unittest/test_nsg/test_nsg.cpp
  core/src/scheduler/optimizer/BuildIndexPass.cpp
  core/src/scheduler/optimizer/BuildIndexPass.h
  core/src/scheduler/optimizer/FaissFlatPass.cpp
  core/src/scheduler/optimizer/FaissFlatPass.h
  core/src/scheduler/optimizer/FaissIVFFlatPass.cpp
  core/src/scheduler/optimizer/FaissIVFFlatPass.h
  core/src/scheduler/optimizer/FaissIVFSQ8HPass.cpp
  core/src/scheduler/optimizer/FaissIVFSQ8HPass.h
  core/src/scheduler/optimizer/FaissIVFSQ8Pass.cpp
  core/src/scheduler/optimizer/FaissIVFSQ8Pass.h
  core/src/wrapper/VecImpl.cpp
  core/src/wrapper/VecImpl.h
  core/src/wrapper/VecIndex.h
  core/unittest/db/test_db.cpp
  core/unittest/db/test_engine.cpp
  core/unittest/scheduler/test_scheduler.cpp
  core/unittest/server/test_cache.cpp
  core/unittest/wrapper/test_wrapper.cpp
Labels: type/bug

#562 #354 Build migration scripts into milvus docker image
  CHANGELOG.md
  core/CMakeLists.txt
  core/unittest/db/test_db.cpp
Labels: type/enhancement

#581 Add ivfflat test report
  docs/test_report/ivfflat_test_report_cn.md
  docs/test_report/ivfflat_test_report_en.md
Labels: type/docs

#577 [skip ci] Added a link to the FAQ topic.
  README.md
  README_CN.md
  README_JP.md
Labels: type/docs

#580 #545 Avoid dead circle of build index thread when error occurs
  CHANGELOG.md
  core/src/db/DBImpl.cpp
  core/src/db/DBImpl.h
  core/src/db/Utils.cpp
  core/src/db/meta/MySQLMetaImpl.cpp
  core/src/db/meta/SqliteMetaImpl.cpp
  core/src/utils/CommonUtil.cpp
Labels: type/bug

#571 Add regex cases to test search partition tags in 0.6.0
  tests/milvus_python_test/test_search_vectors.py
Labels: type/enhancement

#586 #561 Milvus server should report exception/error message or terminate
  CHANGELOG.md
  core/src/db/meta/MySQLMetaImpl.cpp
Labels: type/bug

#594 Intergrate internal FAISS
  ci/jenkins/Jenkinsfile
  ci/jenkins/internalJenkinsfile.groovy
Labels: type/new-feature

#588 #552 Server down during building index_type: IVF_PQ using GPU-edition
  CHANGELOG.md
  core/src/index/unittest/test_nsg/test_nsg.cpp
  core/src/wrapper/ConfAdapter.cpp
  core/unittest/wrapper/test_wrapper.cpp
Labels: type/bug

#593 #274 logger the time cost during preloading data
  CHANGELOG.md
  core/src/db/DBImpl.cpp
  core/src/utils/TimeRecorder.cpp
  core/src/utils/TimeRecorder.h
Labels: type/enhancement

#597 Update Jenkinsfile
  ci/jenkins/Jenkinsfile
  ci/jenkins/internalJenkinsfile.groovy
Labels: type/new-feature

#600 #599 Build index log is incorrect
  CHANGELOG.md
  core/src/db/meta/MySQLMetaImpl.cpp
  core/src/db/meta/SqliteMetaImpl.cpp
Labels: type/bug

#610 #606 No log generated during building index with CPU
  CHANGELOG.md
  core/src/db/DBImpl.cpp
Labels: type/bug

#613 update build environment images resources limits
  ci/jenkins/pod/milvus-cpu-version-build-env-pod.yaml
  ci/jenkins/pod/milvus-gpu-version-build-env-pod.yaml
Labels: type/enhancement

#617 format check_ccache.sh
  ci/scripts/check_ccache.sh
Labels: type/enhancement

#620 Add pq cases
  tests/milvus_python_test/test_index.py
  tests/milvus_python_test/utils.py
Labels: type/enhancement
