Repository milvus-io/milvus, pull requests merged in 2019-10, with the labels that each got.

#70 Improvement dump function in scheduler
  CHANGELOG.md
  NOTICE.md
  core/src/external/nlohmann/json.hpp
  core/src/scheduler/TaskTable.cpp
  core/src/scheduler/TaskTable.h
  core/src/scheduler/interface/interfaces.h
  core/src/utils/Json.h
Labels: enhancement

#91 Improvement dump function in scheduler
  core/src/scheduler/JobMgr.cpp
  core/src/scheduler/JobMgr.h
  core/src/scheduler/ResourceMgr.cpp
  core/src/scheduler/ResourceMgr.h
  core/src/scheduler/Scheduler.cpp
  core/src/scheduler/Scheduler.h
  core/src/scheduler/TaskTable.cpp
  core/src/scheduler/TaskTable.h
  core/src/scheduler/interface/interfaces.h
  core/src/scheduler/job/BuildIndexJob.cpp
  core/src/scheduler/job/BuildIndexJob.h
  core/src/scheduler/job/DeleteJob.cpp
  core/src/scheduler/job/DeleteJob.h
  core/src/scheduler/job/Job.h
  core/src/scheduler/job/SearchJob.cpp
  core/src/scheduler/job/SearchJob.h
  core/src/scheduler/resource/CpuResource.cpp
  core/src/scheduler/resource/CpuResource.h
  core/src/scheduler/resource/DiskResource.h
  core/src/scheduler/resource/GpuResource.cpp
  core/src/scheduler/resource/GpuResource.h
  core/src/scheduler/resource/Node.cpp
  core/src/scheduler/resource/Node.h
  core/src/scheduler/resource/Resource.cpp
  core/src/scheduler/resource/Resource.h
  core/src/scheduler/resource/TestResource.h
Labels: enhancement

#103 Remove .a file in milvus/lib for docker-version
  CHANGELOG.md
  core/src/index/knowhere/CMakeLists.txt
Labels: dependencies

#102 [skip ci] Correct the release note link and update minor changes in Install dependencies
  README.md
Labels: documentation

#116 Using new structure for tasktable
  CHANGELOG.md
  core/src/scheduler/BuildMgr.h
  core/src/scheduler/CircleQueue.h
  core/src/scheduler/TaskTable.cpp
  core/src/scheduler/TaskTable.h
  core/src/scheduler/resource/Resource.cpp
  core/unittest/scheduler/test_tasktable.cpp
Labels: enhancement

#121 #90 The server start error messages could be improved to enhance user experience
  CHANGELOG.md
  core/conf/server_config.template
  core/src/scheduler/job/Job.cpp
  core/src/server/Config.cpp
  core/src/server/DBWrapper.cpp
  core/unittest/db/utils.cpp
  core/unittest/wrapper/utils.cpp
Labels: bug

#117 [skip ci] Add a Thanks section in README
  README.md
Labels: documentation

#131 Set task state MOVED after resource copy it completed
  CHANGELOG.md
  core/src/scheduler/JobMgr.cpp
  core/src/scheduler/Scheduler.cpp
  core/src/scheduler/TaskTable.cpp
  core/src/scheduler/TaskTable.h
  core/src/scheduler/action/Action.h
  core/src/scheduler/action/PushTaskToNeighbour.cpp
  core/src/scheduler/resource/Resource.cpp
  core/unittest/scheduler/test_tasktable.cpp
Labels: enhancement

#140 New config opion use_gpu_threshold
  CHANGELOG.md
  core/conf/server_config.template
  core/src/scheduler/optimizer/LargeSQ8HPass.cpp
  core/src/scheduler/optimizer/LargeSQ8HPass.h
  core/src/server/Config.cpp
  core/src/server/Config.h
Labels: enhancement

#145 Update from internal milvus
  core/CMakeLists.txt
  core/src/index/cmake/ThirdPartyPackagesCore.cmake
Labels: enhancement

#150 Improve large query optimizer pass
  CHANGELOG.md
  core/src/db/engine/ExecutionEngineImpl.cpp
  core/src/scheduler/optimizer/LargeSQ8HPass.cpp
  core/src/scheduler/optimizer/LargeSQ8HPass.h
Labels: enhancement

#157 Not return error when search_resources and index_build_device set cpu
  CHANGELOG.md
  core/src/server/Config.cpp
Labels: enhancement
