Repository milvus-io/milvus, pull requests merged in 2020-09, with the labels that each got.

#3529 split insert data accordding to segment row count
  core/src/db/DBImpl.cpp
  core/src/db/SnapshotUtils.cpp
  core/src/db/SnapshotUtils.h
  core/src/db/Utils.cpp
  core/src/db/Utils.h
  core/src/db/insert/MemCollection.cpp
  core/src/db/insert/MemCollection.h
  core/src/db/insert/MemSegment.cpp
  core/src/db/insert/MemSegment.h
  core/src/db/wal/WalManager.cpp
  core/src/db/wal/WalManager.h
  core/src/db/wal/WalProxy.cpp
  core/src/server/Server.cpp
  core/src/server/delivery/request/InsertReq.cpp
  core/unittest/db/test_db.cpp
  core/unittest/db/test_wal.cpp
  core/unittest/db/utils.cpp
  core/unittest/db/utils.h
  tests/milvus_python_test/collection/test_collection_stats.py
  tests/milvus_python_test/test_compact.py
Labels: automerge

#3540 Opt delete logic
  core/src/db/insert/MemCollection.cpp
Labels: Bug, automerge, type/enhancement

#3542 fix layer merge bug
  core/src/db/merge/MergeLayerStrategy.cpp
Labels: automerge

#3548 Fix field_name duplicate problem
  core/src/scheduler/task/SearchTask.cpp
  core/src/server/grpc_impl/GrpcRequestHandler.cpp
  core/src/server/web_impl/handler/WebRequestHandler.cpp
Labels: automerge

#3547 fix layer merge bug
  core/src/db/merge/MergeLayerStrategy.cpp
Labels: automerge

#3549 fix size meta to unsigned int (#3482)
  CHANGELOG.md
  core/src/db/meta/MetaSession.h
  core/src/db/meta/backend/MySqlEngine.cpp
  core/src/db/meta/backend/SqliteEngine.cpp
Labels: automerge

#3550 fix size meta to unsigned big int
  CHANGELOG.md
  core/src/db/meta/MetaSession.h
  core/src/db/meta/backend/MySqlEngine.cpp
  core/src/db/meta/backend/SqliteEngine.cpp
Labels: automerge

#3559 Fix SearchTask::nq()
  core/src/db/engine/ExecutionEngineImpl.cpp
  core/src/query/BinaryQuery.cpp
  core/src/query/GeneralQuery.h
  core/src/scheduler/task/SearchTask.cpp
Labels: automerge

#3570 [skip ci] update testcase
  tests/milvus-java-test/src/main/java/com/TestCollectionCount_v2.java
  tests/milvus-java-test/src/main/java/com/TestCollectionInfo.java
  tests/milvus-java-test/src/main/java/com/TestCollectionInfo_v2.java
Labels: automerge

#3558 add test case: flat search with metric_type
  tests/milvus_python_test/entity/test_search.py
Labels: automerge

#3571 [skip ci]remove cherry-pick section in PULL REQUEST TEMPLATE
  .github/PULL_REQUEST_TEMPLATE.md
Labels: automerge, hotfix, skip-ci

#3545 Fix #3515: error should be raised if tag name as params of `has_partition` is set invalid
  core/src/db/CMakeLists.txt
  core/src/db/DBImpl.cpp
  core/src/server/ValidationUtil.cpp
  tests/milvus_python_test/collection/test_collection_stats.py
  tests/milvus_python_test/entity/test_delete.py
  tests/milvus_python_test/entity/test_get_entity_by_id.py
  tests/milvus_python_test/entity/test_insert.py
  tests/milvus_python_test/entity/test_list_id_in_segment.py
  tests/milvus_python_test/entity/test_search.py
  tests/milvus_python_test/stability/test_mysql.py
  tests/milvus_python_test/stability/test_restart.py
  tests/milvus_python_test/test_compact.py
  tests/milvus_python_test/test_config.py
  tests/milvus_python_test/test_flush.py
  tests/milvus_python_test/test_index.py
  tests/milvus_python_test/test_partition.py
  tests/milvus_python_test/test_wal.py
Labels: hotfix

#3578 free moved tasks and executed tasks
  core/src/scheduler/resource/Resource.cpp
Labels: automerge, hotfix

#3575 Fix build milvus images error
  ci/jenkins/Jenkinsfile
Labels: Bug | Severity | S3, automerge, skip-ci, stability

#3585 [skip ci] add enhancement issue template
  .github/ISSUE_TEMPLATE/enhancement.md
Labels: automerge, skip-ci

#3587 remove set config case
  tests/milvus_python_test/collection/test_create_collection.py
  tests/milvus_python_test/entity/test_get_entity_by_id.py
  tests/milvus_python_test/entity/test_insert.py
  tests/milvus_python_test/entity/test_list_id_in_segment.py
  tests/milvus_python_test/test_flush.py
Labels: automerge

#3589 Fix ut DeleteEntitiesTest where delete entity failed
  CHANGELOG.md
  core/src/db/insert/MemCollection.cpp
  core/src/server/Server.cpp
Labels: Bug, automerge, hotfix

#3591 [skip ci] Add some binary search case and update index builder
  tests/milvus-java-test/src/main/java/com/Constants.java
  tests/milvus-java-test/src/main/java/com/MainClass.java
  tests/milvus-java-test/src/main/java/com/TestCollection.java
  tests/milvus-java-test/src/main/java/com/TestConnect.java
  tests/milvus-java-test/src/main/java/com/TestIndex.java
  tests/milvus-java-test/src/main/java/com/TestIndex_v2.java
  tests/milvus-java-test/src/main/java/com/TestSearchEntities.java
  tests/milvus-java-test/src/main/java/com/Utils.java
Labels: automerge, skip-ci

#3541 rewrite codecs implementation
  core/src/codecs/BlockFormat.cpp
  core/src/codecs/CMakeLists.txt
  core/src/codecs/DeletedDocsFormat.cpp
  core/src/codecs/ExtraFileInfo.cpp
  core/src/codecs/ExtraFileInfo.h
  core/src/codecs/ExtraFileInfoTest.cpp
  core/src/codecs/StructuredIndexFormat.cpp
  core/src/codecs/VectorCompressFormat.cpp
  core/src/codecs/VectorIndexFormat.cpp
  core/src/scheduler/TaskTable.cpp
  core/src/server/delivery/request/CmdReq.cpp
  core/src/storage/CMakeLists.txt
  core/src/storage/ExtraFileInfo.cpp
  core/src/storage/ExtraFileInfo.h
  core/src/storage/IOReader.h
  core/src/storage/IOWriter.h
  core/src/storage/disk/DiskIOReader.cpp
  core/src/storage/disk/DiskIOReader.h
  core/src/storage/disk/DiskIOWriter.cpp
  core/src/storage/disk/DiskIOWriter.h
  core/src/utils/Status.cpp
  core/src/utils/Status.h
Labels: automerge, hotfix

#3546 Update ConfigMgr::Set behavior
  core/src/config/CMakeLists.txt
  core/src/config/ConfigInit.cpp
  core/src/config/ConfigMgr.cpp
  core/src/config/ConfigMgr.h
  core/src/config/ConfigMgrTest.cpp
  core/src/config/ConfigType.cpp
  core/src/config/ConfigType.h
  core/src/config/ConfigTypeTest1.cpp
  core/src/config/ConfigTypeTest2.cpp
  core/src/config/ServerConfig.h
  core/src/db/DB.h
  core/src/db/DBImpl.cpp
  core/src/db/DBImpl.h
  core/src/db/DBProxy.cpp
  core/src/db/DBProxy.h
  core/src/main.cpp
  core/src/server/CMakeLists.txt
  core/src/server/Server.cpp
  core/src/server/Server.h
  core/src/server/delivery/request/CmdReq.cpp
  core/src/server/delivery/request/CmdReq.h
  core/src/server/init/CMakeLists.txt
  core/src/server/init/Timezone.cpp
  core/src/server/init/TimezoneTest.cpp
  core/src/server/web_impl/controller/WebController.hpp
  core/src/server/web_impl/handler/WebRequestHandler.cpp
  core/src/server/web_impl/handler/WebRequestHandler.h
  core/unittest/server/test_web.cpp
  tests/milvus_python_test/test_config.py
  tests/milvus_python_test/test_ping.py
Labels: automerge

#3593 refine code for insert mem
  core/src/db/DBImpl.cpp
  core/src/db/insert/MemManagerImpl.cpp
  core/src/db/insert/MemManagerImpl.h
Labels: automerge

#3598 update output message if collection is not existed fix #3427
  CHANGELOG.md
  core/src/db/snapshot/Snapshots.cpp
Labels: automerge, hotfix

#3594 GPU search turn into CPU search when nprobe >2048
  CHANGELOG.md
  core/src/scheduler/selector/FaissIVFFlatPass.cpp
  core/src/scheduler/selector/FaissIVFPQPass.cpp
  core/src/scheduler/selector/FaissIVFSQ8HPass.cpp
  core/src/scheduler/selector/FaissIVFSQ8Pass.cpp
Labels: type/new-feature

#3586 GPU search turn into CPU search when nprobe >gpu_max_k
  CHANGELOG.md
  core/src/query/GeneralQuery.h
  core/src/scheduler/selector/FaissFlatPass.cpp
  core/src/scheduler/selector/FaissIVFFlatPass.cpp
  core/src/scheduler/selector/FaissIVFPQPass.cpp
  core/src/scheduler/selector/FaissIVFSQ8HPass.cpp
  core/src/scheduler/selector/FaissIVFSQ8Pass.cpp
  core/src/scheduler/task/SearchTask.cpp
  core/src/scheduler/task/SearchTask.h
  core/src/server/web_impl/handler/WebRequestHandler.cpp
Labels: type/new-feature

#3584 Cherry pick 0.11.0 20200904
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
  core/src/codecs/BlockFormat.cpp
  core/src/codecs/CMakeLists.txt
  core/src/codecs/DeletedDocsFormat.cpp
  core/src/codecs/ExtraFileInfo.cpp
  core/src/codecs/ExtraFileInfo.h
  core/src/codecs/ExtraFileInfoTest.cpp
  core/src/codecs/StructuredIndexFormat.cpp
  core/src/codecs/VectorCompressFormat.cpp
  core/src/codecs/VectorIndexFormat.cpp
  core/src/db/CMakeLists.txt
  core/src/db/DBImpl.cpp
  core/src/db/insert/MemCollection.cpp
  core/src/scheduler/TaskTable.cpp
  core/src/scheduler/resource/Resource.cpp
  core/src/server/Server.cpp
  core/src/server/ValidationUtil.cpp
  core/src/server/delivery/request/CmdReq.cpp
  core/src/storage/CMakeLists.txt
  core/src/storage/ExtraFileInfo.cpp
  core/src/storage/ExtraFileInfo.h
  core/src/storage/IOReader.h
  core/src/storage/IOWriter.h
  core/src/storage/disk/DiskIOReader.cpp
  core/src/storage/disk/DiskIOReader.h
  core/src/storage/disk/DiskIOWriter.cpp
  core/src/storage/disk/DiskIOWriter.h
  core/src/utils/Status.cpp
  core/src/utils/Status.h
  tests/milvus_python_test/collection/test_collection_stats.py
  tests/milvus_python_test/entity/test_delete.py
  tests/milvus_python_test/entity/test_get_entity_by_id.py
  tests/milvus_python_test/entity/test_insert.py
  tests/milvus_python_test/entity/test_list_id_in_segment.py
  tests/milvus_python_test/entity/test_search.py
  tests/milvus_python_test/stability/test_mysql.py
  tests/milvus_python_test/stability/test_restart.py
  tests/milvus_python_test/test_compact.py
  tests/milvus_python_test/test_config.py
  tests/milvus_python_test/test_flush.py
  tests/milvus_python_test/test_index.py
  tests/milvus_python_test/test_partition.py
  tests/milvus_python_test/test_wal.py
Labels: cherry-pick

#3600 Fix getEntity when no query_params and payload is provided in webserver
  core/src/server/web_impl/handler/WebRequestHandler.cpp
  core/unittest/server/test_web.cpp
Labels: automerge, hotfix

#3595 fix cache not clear bug in ut
  core/src/codecs/ExtraFileInfo.cpp
  core/unittest/db/utils.cpp
Labels: automerge, hotfix

#3609 release search task in time
  CHANGELOG.md
  core/src/scheduler/resource/Resource.cpp
  core/src/scheduler/task/FinishedTask.cpp
  core/src/scheduler/task/FinishedTask.h
  core/src/scheduler/task/SearchTask.cpp
Labels: Bug

#3604 Update Milvus Dev Test environment
  ci/jenkins/pod/testEnvironment.yaml
  docker/test_env/Dockerfile
  docker/test_env/docker-entrypoint.sh
  docker/test_env/requirements.txt
Labels: automerge, skip-ci

#3613 [skip ci] add case for dsl search vectors
  tests/milvus-java-test/src/main/java/com/TestIndex.java
  tests/milvus-java-test/src/main/java/com/TestIndex_v2.java
  tests/milvus-java-test/src/main/java/com/TestSearchEntities.java
Labels: automerge, skip-ci

#3607 fix aws build error
  core/src/db/CMakeLists.txt
  core/src/storage/CMakeLists.txt
  core/thirdparty/aws/CMakeLists.txt
Labels: automerge, hotfix

#3618 [skip ci] add test for compactAsync callback
  tests/milvus-java-test/src/main/java/com/TestCompact.java
Labels: automerge, skip-ci

#3622 [skip ci] use List<List<Byte>> for binary searchParam
  tests/milvus-java-test/src/main/java/com/Constants.java
  tests/milvus-java-test/src/main/java/com/TestCollectionCount.java
  tests/milvus-java-test/src/main/java/com/TestCollectionCount_v2.java
  tests/milvus-java-test/src/main/java/com/TestCollectionInfo_v2.java
  tests/milvus-java-test/src/main/java/com/TestCollection_v2.java
  tests/milvus-java-test/src/main/java/com/TestCompact.java
  tests/milvus-java-test/src/main/java/com/TestDeleteEntities_v2.java
  tests/milvus-java-test/src/main/java/com/TestFlush.java
  tests/milvus-java-test/src/main/java/com/TestGetEntityByID.java
  tests/milvus-java-test/src/main/java/com/TestIndex_v2.java
  tests/milvus-java-test/src/main/java/com/TestInsertEntities.java
  tests/milvus-java-test/src/main/java/com/TestInsertEntities_v2.java
  tests/milvus-java-test/src/main/java/com/TestSearchEntities.java
  tests/milvus-java-test/src/main/java/com/Utils.java
Labels: automerge, skip-ci

#3620 add to check query dim
  core/src/query/GeneralQuery.h
  core/src/server/delivery/request/SearchReq.cpp
  core/src/server/grpc_impl/GrpcRequestHandler.cpp
  core/src/server/web_impl/handler/WebRequestHandler.cpp
Labels: automerge, hotfix

#3611 (db/snapshot): fix InActiveResourcesGCEvent bug
  core/src/db/snapshot/InActiveResourcesGCEvent.h
Labels: Bug | Severity | S2, automerge, hotfix

#3625 Fix crash where getting octets information
  CHANGELOG.md
  core/src/metrics/SystemInfo.cpp
Labels: PR | hotfix

#3628 fix building index check
  core/src/config/ConfigInit.cpp
  core/src/db/DBImpl.cpp
Labels: PR | automerge, PR | hotfix

#3629 rewrite dabloom
  core/src/codecs/IdBloomFilterFormat.cpp
  core/src/codecs/IdBloomFilterFormat.h
  core/src/db/insert/MemCollection.cpp
  core/src/segment/IdBloomFilter.cpp
  core/src/segment/IdBloomFilter.h
  core/src/segment/SegmentReader.cpp
  core/src/segment/SegmentWriter.cpp
  core/src/segment/SegmentWriter.h
  core/thirdparty/dablooms/dablooms.cpp
  core/thirdparty/dablooms/dablooms.h
  core/unittest/db/test_segment.cpp
Labels: PR | automerge, PR | hotfix

#3632 add build option -rdynamic in CMakeList.txt
  CHANGELOG.md
  core/CMakeLists.txt
Labels: PR | automerge, PR | hotfix

#3657 [skip ci] update callback test and binary search test
  tests/milvus-java-test/src/main/java/com/TestCompact.java
  tests/milvus-java-test/src/main/java/com/TestIndex.java
  tests/milvus-java-test/src/main/java/com/TestInsertEntities.java
  tests/milvus-java-test/src/main/java/com/TestSearchEntities.java
  tests/milvus-java-test/src/main/java/com/Utils.java
Labels: PR | automerge, PR | skip-ci

#3654 Proto of C++ sdk is different from milvus server
  CHANGELOG.md
  core/src/server/web_impl/handler/WebRequestHandler.cpp
  sdk/examples/simple/src/ClientTest.cpp
  sdk/grpc-gen/gen-milvus/milvus.grpc.pb.cc
  sdk/grpc-gen/gen-milvus/milvus.grpc.pb.h
  sdk/grpc-gen/gen-milvus/milvus.pb.cc
  sdk/grpc-gen/gen-milvus/milvus.pb.h
  sdk/grpc/ClientProxy.cpp
  sdk/grpc/ClientProxy.h
  sdk/grpc/GrpcClient.cpp
  sdk/grpc/GrpcClient.h
  sdk/include/MilvusApi.h
  sdk/interface/ConnectionImpl.cpp
  sdk/interface/ConnectionImpl.h
Labels: PR | automerge, PR | hotfix, sdk/c++

#3645 Clear cache after merge
  core/src/db/DBImpl.cpp
  core/src/db/SnapshotUtils.cpp
  core/src/db/SnapshotUtils.h
  core/src/index/unittest/test_rhnsw_sq8.cpp
  core/src/segment/Segment.cpp
  core/src/segment/Segment.h
  core/src/segment/SegmentReader.cpp
  core/src/segment/SegmentReader.h
  core/src/segment/SegmentWriter.cpp
Labels: PR | automerge, PR | hotfix

#3638 set wal lsn to meta
  core/src/db/insert/MemSegment.cpp
  core/src/db/insert/MemSegment.h
  core/src/db/wal/WalManager.cpp
  core/src/db/wal/WalManager.h
  core/src/db/wal/WalProxy.cpp
  core/src/db/wal/WalProxy.h
  core/unittest/db/test_wal.cpp
Labels: PR | automerge, PR | hotfix

#3658 #3656 Search with nprobe=0 should be invalid for BIN_IVF_FLAT index
  core/src/index/knowhere/knowhere/index/vector_index/ConfAdapterMgr.cpp
  tests/milvus_python_test/entity/test_search.py
Labels: PR | automerge, PR | hotfix

#3660 fix to check search param of BIN_IVF_FLAT
  CHANGELOG.md
  core/src/index/knowhere/knowhere/index/vector_index/ConfAdapterMgr.cpp
Labels: Bug

#3661 Fix insert with disable flush and add get entity by deleted id
  tests/milvus_python_test/entity/test_get_entity_by_id.py
  tests/milvus_python_test/entity/test_insert.py
Labels: PR | automerge

#3665 [skip ci] update case for get entity by with invalid ids
  tests/milvus-java-test/src/main/java/com/TestDeleteEntities.java
  tests/milvus-java-test/src/main/java/com/TestDeleteEntities_v2.java
  tests/milvus-java-test/src/main/java/com/TestGetEntityByID.java
  tests/milvus-java-test/src/main/java/com/Utils.java
Labels: PR | automerge, PR | skip-ci

#3664 Fix loadcollection memory usage is one times larger than expect
  core/src/index/knowhere/knowhere/index/vector_offset_index/IndexIVF_NM.cpp
  core/src/index/knowhere/knowhere/index/vector_offset_index/IndexIVF_NM.h
Labels: PR | automerge, PR | hotfix

#3669 add memory limit check
  CHANGELOG.md
  core/src/config/ConfigInit.cpp
Labels: PR | automerge, PR | hotfix

#3674 avoid dabloom warning
  core/src/segment/IdBloomFilter.cpp
  core/src/segment/IdBloomFilter.h
  core/thirdparty/dablooms/dablooms.cpp
  core/unittest/db/test_segment.cpp
Labels: PR | automerge, PR | hotfix

#3687 [skip ci] update milvus_python_test/README.md
  tests/milvus_python_test/README.md
Labels: PR | automerge, PR | skip-ci

#3686 fix #3672 0.11.0 docker image is 200M larger due to the un-expected installation of openblas
  CHANGELOG.md
  docker/deploy/cpu/centos7/Dockerfile
  docker/deploy/cpu/ubuntu18.04/Dockerfile
  docker/deploy/gpu/centos7/Dockerfile
  docker/deploy/gpu/ubuntu18.04/Dockerfile
Labels: PR | automerge, PR | hotfix, PR | skip-ci

#3682 (db/snapshot): update LSN logic
  core/src/db/snapshot/CompoundOperations.cpp
  core/src/db/snapshot/CompoundOperations.h
  core/src/db/snapshot/Operations.cpp
  core/unittest/db/test_snapshot.cpp
Labels: PR | automerge, PR | hotfix, type/enhancement

#3699 fix#3626 server crash during search due to MergeResult operation is unlocked
  CHANGELOG.md
  core/src/scheduler/job/SearchJob.h
  core/src/scheduler/task/SearchTask.cpp
Labels: PR | automerge, PR | hotfix

#3680 add wal file open log
  core/src/db/wal/WalFile.cpp
Labels: PR | automerge, PR | hotfix

#3710 Remove check for topk in mishards (fix #3709)
  CHANGELOG.md
  shards/mishards/service_handler.py
Labels: Bug, PR | automerge, PR | hotfix, PR | skip-ci, mishards

#3708 fix snapshot not release bug
  core/src/db/insert/MemManagerImpl.cpp
  core/src/db/snapshot/Snapshot.h
  core/src/db/snapshot/SnapshotHolder.cpp
Labels: Bug | Severity | S1, PR | automerge, PR | hotfix

#3714 Fix#3689 Client get stuck if drop collection during creating index
  CHANGELOG.md
  core/src/index/thirdparty/faiss/utils/distances.cpp
Labels: PR | automerge, PR | hotfix

#3655 (db/snapshot): Implement FlushableMappingField for better metadata snapshot
  core/src/db/Utils.cpp
  core/src/db/Utils.h
  core/src/db/meta/MetaResourceAttrs.h
  core/src/db/meta/MetaSession.h
  core/src/db/snapshot/CompoundOperations.cpp
  core/src/db/snapshot/ResourceHelper.h
  core/src/db/snapshot/ResourceOperations.cpp
  core/src/db/snapshot/Resources.cpp
  core/src/db/snapshot/Resources.h
  core/src/db/snapshot/Snapshot.cpp
  core/src/db/snapshot/Store.h
  core/unittest/db/test_db.cpp
  core/unittest/db/test_snapshot.cpp
  core/unittest/db/utils.h
Labels: PR | automerge, PR | hotfix, type/enhancement, type/performance

#3667 fix delete entity performance issue
  core/src/db/DBImpl.cpp
  core/src/db/DBImpl.h
  core/src/db/SnapshotHandlers.cpp
  core/src/db/SnapshotHandlers.h
  core/src/db/SnapshotUtils.cpp
  core/src/db/SnapshotUtils.h
  core/src/db/SnapshotVisitor.cpp
  core/src/db/SnapshotVisitor.h
  core/src/db/insert/MemCollection.cpp
  core/src/db/insert/MemCollection.h
  core/src/db/insert/MemManager.h
  core/src/db/insert/MemManagerImpl.cpp
  core/src/db/insert/MemManagerImpl.h
  core/src/db/insert/MemSegment.cpp
  core/src/db/merge/MergeManagerImpl.cpp
  core/src/db/wal/WalManager.cpp
  core/src/segment/Segment.cpp
  core/src/segment/SegmentWriter.cpp
  core/src/segment/Utils.cpp
  core/src/segment/Utils.h
  core/src/server/ValidationUtil.cpp
  core/unittest/db/test_segment.cpp
  tests/milvus_python_test/utils.py
Labels: PR | automerge, PR | hotfix

#3715 add some check to avoid server crash
  core/src/server/grpc_impl/GrpcRequestHandler.cpp
Labels: PR | automerge, PR | hotfix

#3564 scale nb in test case
  .jenkins/modules/DevTest/SingleNodeDevTest.groovy
  tests/milvus_python_test/collection/test_collection_count.py
  tests/milvus_python_test/collection/test_collection_logic.py
  tests/milvus_python_test/collection/test_collection_stats.py
  tests/milvus_python_test/collection/test_create_collection.py
  tests/milvus_python_test/collection/test_drop_collection.py
  tests/milvus_python_test/collection/test_get_collection_info.py
  tests/milvus_python_test/collection/test_load_collection.py
  tests/milvus_python_test/conftest.py
  tests/milvus_python_test/entity/test_delete.py
  tests/milvus_python_test/entity/test_get_entity_by_id.py
  tests/milvus_python_test/entity/test_insert.py
  tests/milvus_python_test/entity/test_list_id_in_segment.py
  tests/milvus_python_test/entity/test_search.py
  tests/milvus_python_test/stability/test_restart.py
  tests/milvus_python_test/test_compact.py
  tests/milvus_python_test/test_config.py
  tests/milvus_python_test/test_flush.py
  tests/milvus_python_test/test_index.py
  tests/milvus_python_test/test_mix.py
  tests/milvus_python_test/test_partition.py
  tests/milvus_python_test/test_wal.py
  tests/milvus_python_test/utils.py
Labels: PR | automerge

#3735 GET_PAGE_ENTITY sometimes failed in test_web
  CHANGELOG.md
  core/src/db/engine/ExecutionEngineImpl.cpp
  core/unittest/server/test_web.cpp
  sdk/examples/binary_vector/src/ClientTest.cpp
  sdk/examples/simple/src/ClientTest.cpp
Labels: PR | automerge, PR | hotfix

#3724 #3722 rename segment_row_count to segment_row_limit
  core/src/db/Types.cpp
  core/src/db/wal/WalFile.cpp
  core/src/db/wal/WalManager.cpp
  core/src/segment/IdBloomFilter.cpp
  core/src/segment/SegmentReader.cpp
  core/src/segment/SegmentWriter.cpp
  core/unittest/db/utils.cpp
  tests/milvus_python_test/collection/test_create_collection.py
  tests/milvus_python_test/collection/test_get_collection_info.py
  tests/milvus_python_test/entity/test_insert.py
  tests/milvus_python_test/entity/test_list_id_in_segment.py
  tests/milvus_python_test/test_flush.py
  tests/milvus_python_test/utils.py
Labels: PR | automerge, PR | hotfix

#3721 Apply more stale check rules for Operations
  core/src/db/snapshot/Operations.cpp
  core/src/db/snapshot/ResourceOperations.cpp
  core/src/utils/Error.h
  core/unittest/db/test_db.cpp
  core/unittest/db/test_snapshot.cpp
Labels: type/enhancement

#3694 Improve code of dabloom
  core/thirdparty/dablooms/dablooms.cpp
  core/thirdparty/dablooms/dablooms.h
Labels: PR | automerge, PR | hotfix, type/enhancement

#3750 (db/snapshot): fix GC PartitionCommit
  core/src/db/snapshot/ResourceHelper.h
Labels: Bug | Severity | S2, PR | automerge, PR | hotfix

#3745 Set a timeout for a whole job on Github action pipeline
  .github/workflows/core.yml
  core/centos7_build_deps.sh
Labels: PR | automerge, PR | skip-ci, type/enhancement

#3746 Set a timeout for a whole job on Github action pipeline
  .github/workflows/core.yml
Labels: PR | automerge, PR | skip-ci, type/enhancement

#3747 Fix config item access in codes which may cause unexpected error
  core/src/db/SnapshotVisitor.cpp
  core/src/db/Utils.cpp
  core/src/server/ValidationUtil.cpp
Labels: PR | automerge, PR | hotfix

#3738 raise the limitation of hnsw ef parameter to 32768
  core/src/index/knowhere/knowhere/index/vector_index/ConfAdapter.cpp
  core/src/utils/ValidationUtil.cpp
Labels: PR | automerge

#3733 New operation named MultiSegmentsOperation support multi-segments during flush
  CHANGELOG.md
  core/src/db/meta/backend/MetaContext.h
  core/src/db/snapshot/CompoundOperations.cpp
  core/src/db/snapshot/CompoundOperations.h
  core/src/db/snapshot/Context.h
  core/unittest/db/test_snapshot.cpp
  core/unittest/db/utils.h
Labels: PR | automerge, PR | hotfix, type/enhancement

#3761 [skip ci] fix the change log
  CHANGELOG.md
Labels: PR | automerge, PR | skip-ci

#3769 Fix trace level log files missing
  core/src/log/LogMgr.cpp
Labels: Bug, Bug | Severity | S3, PR | automerge, PR | hotfix

#3766 #3756 ignore deleted docs file if it doesnt exist
  core/src/db/SnapshotUtils.cpp
Labels: PR | automerge, PR | hotfix

#3737 close lockfile when server stop
  core/src/server/Server.cpp
  core/src/server/Server.h
  core/src/server/init/Directory.cpp
  core/src/server/init/Directory.h
Labels: PR | work in progress

#3757 modify merge strategy
  core/src/db/SnapshotHandlers.cpp
  core/src/db/SnapshotHandlers.h
  core/src/db/SnapshotUtils.cpp
  core/src/db/SnapshotVisitor.cpp
  core/src/db/SnapshotVisitor.h
  core/src/db/merge/MergeLayerStrategy.cpp
  core/src/db/merge/MergeManagerImpl.cpp
Labels: PR | automerge, PR | hotfix

#3770 hold FaissIVFQuantizerPtr in IVFSQHybrid
  core/src/db/engine/ExecutionEngineImpl.cpp
  core/src/index/knowhere/knowhere/index/vector_index/gpu/IndexIVFSQHybrid.cpp
  core/src/index/knowhere/knowhere/index/vector_index/gpu/IndexIVFSQHybrid.h
  core/src/index/knowhere/knowhere/index/vector_index/gpu/Quantizer.h
  core/src/index/thirdparty/faiss/gpu/GpuIndexIVF.cu
Labels: PR | hotfix

#3755 segment_row_limit
  tests/milvus_python_test/collection/test_collection_logic.py
  tests/milvus_python_test/collection/test_create_collection.py
  tests/milvus_python_test/collection/test_get_collection_info.py
  tests/milvus_python_test/entity/test_insert.py
  tests/milvus_python_test/entity/test_list_id_in_segment.py
  tests/milvus_python_test/test_flush.py
  tests/milvus_python_test/utils.py
Labels: PR | automerge

#3765 Fix webserver readme for 0.11.0
  CHANGELOG.md
  core/src/server/web_impl/README.md
  core/src/server/web_impl/handler/WebRequestHandler.cpp
Labels: PR | automerge, PR | hotfix

#3780 add adaptive merge strategy
  core/src/db/DBImpl.cpp
  core/src/db/DBImpl.h
  core/src/db/merge/MergeAdaptiveStrategy.cpp
  core/src/db/merge/MergeAdaptiveStrategy.h
  core/src/db/merge/MergeManager.h
  core/src/db/merge/MergeManagerImpl.cpp
  core/unittest/db/test_db.cpp
  tests/milvus_python_test/entity/test_insert.py
Labels: PR | automerge, PR | hotfix

#3787 avoid dead circle when merge failed
  core/src/db/merge/MergeAdaptiveStrategy.cpp
  core/src/db/merge/MergeManagerImpl.cpp
Labels: PR | automerge, PR | hotfix

#3785 Upgrade mishards up to v0.10.3
  CHANGELOG.md
  shards/README.md
  shards/README_CN.md
  shards/all_in_one/all_in_one.yml
  shards/all_in_one_with_mysql/all_in_one.yml
Labels: PR | automerge, mishards

#3798 avoid snapshot warning during deleting entity
  core/src/db/insert/MemCollection.cpp
Labels: PR | automerge, PR | hotfix

#3788 Improve MergeTopkToResultSet performance
  core/src/scheduler/task/SearchTask.cpp
  core/src/scheduler/task/SearchTask.h
  core/src/server/web_impl/README.md
Labels: PR | automerge, PR | hotfix

#3797 fix the limit of nprobe and nlist
  core/src/db/snapshot/CompoundOperations.cpp
  core/src/index/knowhere/knowhere/index/vector_index/ConfAdapter.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexIVF.cpp
  core/src/index/knowhere/knowhere/index/vector_index/gpu/IndexGPUIVF.cpp
  core/src/index/thirdparty/faiss/utils/distances.cpp
  core/src/server/ValidationUtil.cpp
Labels: PR | automerge, PR | hotfix

#3803 Fix the crash caused by empty index param
  core/src/server/delivery/request/CreateIndexReq.cpp
  sdk/examples/binary_vector/src/ClientTest.cpp
  sdk/examples/simple/src/ClientTest.cpp
  sdk/examples/utils/Utils.cpp
  sdk/examples/utils/Utils.h
Labels: PR | automerge, PR | hotfix

#3778 Fix web start fail for IP family
  core/thirdparty/oatpp/CMakeLists.txt
  core/thirdparty/versions.txt
  core/unittest/db/test_snapshot.cpp
Labels: Bug, PR | automerge, PR | hotfix

#3804 use multi-segments operation to flush
  core/src/db/DBImpl.cpp
  core/src/db/SnapshotHandlers.cpp
  core/src/db/insert/MemCollection.cpp
  core/src/db/insert/MemCollection.h
  core/src/db/insert/MemSegment.cpp
  core/src/db/insert/MemSegment.h
  core/src/segment/SegmentReader.cpp
Labels: PR | automerge, PR | hotfix

#3817 add hidden config engine.max_partition_num
  core/src/config/ConfigInit.cpp
  core/src/config/ServerConfig.h
  core/src/server/delivery/request/CreatePartitionReq.cpp
  core/src/server/delivery/request/CreatePartitionReq.h
Labels: PR | automerge, PR | hotfix

#3826 [skip ci] update milvus_python_test/README.md
  tests/milvus_python_test/README.md
Labels: PR | automerge, PR | skip-ci

#3818 fix wal recovery issue
  core/src/db/insert/MemCollection.cpp
  core/src/db/wal/WalManager.cpp
  core/src/segment/SegmentWriter.cpp
Labels: PR | automerge, PR | hotfix

#3827 set blacklist a NULL pointer if no item deleted
  CHANGELOG.md
  core/src/db/DBImpl.cpp
  core/src/db/engine/ExecutionEngine.h
  core/src/db/engine/ExecutionEngineImpl.cpp
  core/src/db/engine/ExecutionEngineImpl.h
  core/src/db/insert/MemTable.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexBinaryIDMAP.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexBinaryIVF.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexIDMAP.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexIVF.cpp
  core/src/index/knowhere/knowhere/index/vector_index/VecIndex.h
  core/src/index/knowhere/knowhere/index/vector_index/gpu/IndexGPUIDMAP.cpp
  core/src/index/knowhere/knowhere/index/vector_index/gpu/IndexGPUIVF.cpp
  core/src/scheduler/task/SearchTask.cpp
  core/unittest/db/test_hybrid_db.cpp
  core/unittest/server/test_rpc.cpp
  core/unittest/server/test_web.cpp
Labels: type/enhancement

#3833 optimize pytest
  tests/milvus_python_test/collection/test_collection_count.py
  tests/milvus_python_test/collection/test_collection_logic.py
  tests/milvus_python_test/collection/test_collection_stats.py
  tests/milvus_python_test/collection/test_create_collection.py
  tests/milvus_python_test/collection/test_drop_collection.py
  tests/milvus_python_test/collection/test_get_collection_info.py
  tests/milvus_python_test/collection/test_has_collection.py
  tests/milvus_python_test/collection/test_list_collections.py
  tests/milvus_python_test/collection/test_load_collection.py
  tests/milvus_python_test/constants.py
  tests/milvus_python_test/entity/test_delete.py
  tests/milvus_python_test/entity/test_get_entity_by_id.py
  tests/milvus_python_test/entity/test_insert.py
  tests/milvus_python_test/entity/test_list_id_in_segment.py
  tests/milvus_python_test/entity/test_search.py
  tests/milvus_python_test/stability/test_mysql.py
  tests/milvus_python_test/stability/test_restart.py
  tests/milvus_python_test/test_compact.py
  tests/milvus_python_test/test_config.py
  tests/milvus_python_test/test_flush.py
  tests/milvus_python_test/test_index.py
  tests/milvus_python_test/test_mix.py
  tests/milvus_python_test/test_partition.py
  tests/milvus_python_test/utils.py
Labels: PR | automerge

#3832 Thirdparty oatpp md5 update
  core/thirdparty/oatpp/CMakeLists.txt
Labels: Bug, PR | automerge, PR | hotfix

#3820 Fix the error message should be updated if search on index IVF_SQ8_HYBRID with CPU
  core/src/scheduler/selector/FaissIVFSQ8HPass.cpp
  core/src/server/ValidationUtil.cpp
  core/src/server/delivery/request/SearchReq.cpp
Labels: PR | hotfix, PR | work in progress

#3840 remove the flush step in drop collection request processing
  core/src/server/delivery/request/DropCollectionReq.cpp
Labels: PR | automerge, PR | hotfix

#3841 avoid insert hangs
  core/src/db/insert/MemCollection.cpp
Labels: PR | automerge, PR | hotfix

#3848 validate structured index type
  core/src/server/ValidationUtil.cpp
  core/src/server/ValidationUtil.h
  core/src/server/delivery/request/CreateIndexReq.cpp
  core/src/server/delivery/request/SearchReq.cpp
Labels: PR | automerge, PR | hotfix

#3850 add more wal log
  core/src/db/wal/WalManager.cpp
  core/src/db/wal/WalOperationCodec.cpp
Labels: PR | automerge, PR | hotfix

#3801 remove persistence
  .jenkins/modules/DevTest/SingleNodeDevTest.groovy
Labels: PR | automerge

#3855 [skip ci] update install from code
  INSTALL.md
Labels: PR | automerge, PR | skip-ci

#3857 Catch exception on loading configuration file
  core/src/config/ConfigMgr.cpp
  core/src/config/ConfigMgr.h
  core/src/main.cpp
Labels: PR | automerge, PR | hotfix

#3842 reduce insert memory copy
  core/src/db/DBImpl.cpp
  core/src/db/Utils.cpp
  core/src/db/insert/MemCollection.cpp
  core/src/db/wal/WalProxy.cpp
  core/src/server/ValidationUtil.cpp
  core/src/server/ValidationUtil.h
  core/src/server/delivery/ReqHandler.cpp
  core/src/server/delivery/ReqHandler.h
  core/src/server/delivery/request/InsertReq.cpp
  core/src/server/delivery/request/InsertReq.h
  core/src/server/delivery/request/Types.h
  core/src/server/grpc_impl/GrpcRequestHandler.cpp
  core/src/server/web_impl/handler/WebRequestHandler.cpp
Labels: PR | automerge, PR | hotfix

#3858 Set the bitset of searching
  core/src/db/engine/ExecutionEngineImpl.cpp
  core/src/db/engine/ExecutionEngineImpl.h
  core/src/index/knowhere/knowhere/index/vector_index/IndexAnnoy.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexAnnoy.h
  core/src/index/knowhere/knowhere/index/vector_index/IndexBinaryIDMAP.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexBinaryIDMAP.h
  core/src/index/knowhere/knowhere/index/vector_index/IndexBinaryIVF.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexBinaryIVF.h
  core/src/index/knowhere/knowhere/index/vector_index/IndexHNSW.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexHNSW.h
  core/src/index/knowhere/knowhere/index/vector_index/IndexIDMAP.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexIDMAP.h
  core/src/index/knowhere/knowhere/index/vector_index/IndexIVF.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexIVF.h
  core/src/index/knowhere/knowhere/index/vector_index/IndexNSG.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexNSG.h
  core/src/index/knowhere/knowhere/index/vector_index/IndexRHNSW.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexRHNSW.h
  core/src/index/knowhere/knowhere/index/vector_index/IndexSPTAG.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexSPTAG.h
  core/src/index/knowhere/knowhere/index/vector_index/VecIndex.h
  core/src/index/knowhere/knowhere/index/vector_index/gpu/IndexGPUIDMAP.cpp
  core/src/index/knowhere/knowhere/index/vector_index/gpu/IndexGPUIDMAP.h
  core/src/index/knowhere/knowhere/index/vector_index/gpu/IndexGPUIVF.cpp
  core/src/index/knowhere/knowhere/index/vector_index/gpu/IndexGPUIVF.h
  core/src/index/knowhere/knowhere/index/vector_index/gpu/IndexIVFSQHybrid.cpp
  core/src/index/knowhere/knowhere/index/vector_index/gpu/IndexIVFSQHybrid.h
  core/src/index/knowhere/knowhere/index/vector_offset_index/IndexIVF_NM.cpp
  core/src/index/knowhere/knowhere/index/vector_offset_index/IndexIVF_NM.h
  core/src/index/knowhere/knowhere/index/vector_offset_index/IndexNSG_NM.cpp
  core/src/index/knowhere/knowhere/index/vector_offset_index/IndexNSG_NM.h
  core/src/index/knowhere/knowhere/index/vector_offset_index/gpu/IndexGPUIVF_NM.cpp
  core/src/index/knowhere/knowhere/index/vector_offset_index/gpu/IndexGPUIVF_NM.h
  core/src/index/unittest/test_annoy.cpp
  core/src/index/unittest/test_binaryidmap.cpp
  core/src/index/unittest/test_binaryivf.cpp
  core/src/index/unittest/test_customized_index.cpp
  core/src/index/unittest/test_gpuresource.cpp
  core/src/index/unittest/test_hnsw.cpp
  core/src/index/unittest/test_idmap.cpp
  core/src/index/unittest/test_ivf.cpp
  core/src/index/unittest/test_ivf_cpu_nm.cpp
  core/src/index/unittest/test_ivf_gpu_nm.cpp
  core/src/index/unittest/test_nsg.cpp
  core/src/index/unittest/test_rhnsw_flat.cpp
  core/src/index/unittest/test_rhnsw_pq.cpp
  core/src/index/unittest/test_rhnsw_sq8.cpp
  core/src/index/unittest/test_sptag.cpp
  core/src/index/unittest/test_vecindex.cpp
Labels: PR | hotfix

#3867 reduce uid copy during search
  core/src/segment/SegmentReader.cpp
  core/src/segment/SegmentReader.h
Labels: PR | automerge, PR | hotfix

#3864 (db/snapshot): fix bug in metadata snapshot that handling CollectionC…
  core/src/db/snapshot/ResourceOperations.cpp
Labels: PR | automerge, PR | hotfix, Priority | P1

#3869 validate binary index type
  core/src/db/SnapshotHandlers.cpp
  core/src/db/SnapshotUtils.cpp
  core/src/db/SnapshotUtils.h
  core/src/server/ValidationUtil.cpp
  core/src/server/ValidationUtil.h
  core/src/server/delivery/request/CreateIndexReq.cpp
  core/src/server/delivery/request/SearchReq.cpp
Labels: PR | automerge, PR | hotfix

#3872 let bitset nullptr it no deletion and no filter
  core/src/db/engine/ExecutionEngineImpl.cpp
  core/src/index/thirdparty/faiss/utils/ConcurrentBitset.cpp
  core/src/index/thirdparty/faiss/utils/ConcurrentBitset.h
  core/src/segment/SegmentReader.cpp
Labels: PR | hotfix

#3876 fix#3626 PQ distance calculation out of range
  core/src/index/thirdparty/faiss/gpu/impl/PQCodeDistances-inl.cuh
Labels: PR | automerge, PR | hotfix

#3879 Use bash by default in the build environment Docker container
  .github/workflows/core.yml
  .github/workflows/cpplint.yml
  docker-compose.yml
  docker/build_env/cpu/centos7/Dockerfile
  docker/build_env/cpu/ubuntu16.04/Dockerfile
  docker/build_env/cpu/ubuntu18.04/Dockerfile
  docker/build_env/docker-compose.yaml
  docker/build_env/entrypoint.sh
  docker/build_env/gpu/centos7/Dockerfile
  docker/build_env/gpu/ubuntu16.04/Dockerfile
  docker/build_env/gpu/ubuntu18.04/Dockerfile
Labels: PR | automerge, type/enhancement

#3881 If the number of tasks to be executed great equal than 1, stop loading
  core/src/scheduler/TaskTable.cpp
Labels: PR | automerge, PR | hotfix

#3875 reduce uid copy
  core/src/db/SnapshotHandlers.cpp
  core/src/db/insert/MemCollection.cpp
  core/src/segment/SegmentReader.cpp
  core/src/segment/SegmentReader.h
  core/src/segment/SegmentWriter.cpp
  core/src/segment/SegmentWriter.h
Labels: PR | automerge, PR | hotfix

#3856 c++ sdk segmentation fault
  CHANGELOG.md
  sdk/grpc/ClientProxy.cpp
Labels: PR | automerge, PR | hotfix

#3885 code Refactoring
  core/src/db/engine/ExecutionEngineImpl.cpp
  core/src/db/insert/MemCollection.cpp
  core/src/scheduler/task/SearchTask.cpp
  core/src/server/web_impl/handler/WebRequestHandler.cpp
Labels: PR | hotfix

#3888 fix gpu check bug
  core/src/server/init/GpuChecker.cpp
Labels: PR | automerge, PR | hotfix

#3892 knowhere unittest add to check CPU instruction set
  core/src/index/unittest/utils.h
Labels: PR | hotfix

#3890 Fix C++ sdk for search extra params
  sdk/examples/binary_vector/src/ClientTest.cpp
  sdk/examples/simple/src/ClientTest.cpp
  sdk/examples/utils/Utils.cpp
  sdk/grpc/ClientProxy.cpp
  sdk/grpc/ClientProxy.h
  sdk/include/MilvusApi.h
  sdk/interface/ConnectionImpl.cpp
  sdk/interface/ConnectionImpl.h
Labels: PR | automerge, PR | hotfix

#3887 rewrite ListIdInSegment
  core/src/db/DBImpl.cpp
  core/src/db/insert/MemCollection.cpp
  core/src/segment/Utils.cpp
  core/src/segment/Utils.h
  core/unittest/db/test_segment.cpp
Labels: PR | automerge, PR | hotfix

#3895 return build index error message to client
  core/src/db/DBImpl.cpp
  core/src/db/DBImpl.h
  core/src/db/SegmentTaskTracker.cpp
  core/src/db/SegmentTaskTracker.h
  core/src/db/SnapshotHandlers.cpp
  core/src/db/SnapshotUtils.cpp
  core/src/db/SnapshotUtils.h
  core/src/db/Utils.cpp
  core/src/db/Utils.h
  core/src/db/engine/ExecutionEngineImpl.cpp
  core/src/scheduler/job/BuildIndexJob.cpp
  core/src/scheduler/job/BuildIndexJob.h
  core/src/scheduler/task/BuildIndexTask.cpp
  core/src/segment/SegmentReader.cpp
  core/src/segment/SegmentWriter.cpp
  core/src/server/ValidationUtil.cpp
  core/unittest/db/test_db.cpp
Labels: PR | automerge, PR | hotfix

#3899 add wal sync config
  core/src/config/ConfigInit.cpp
  core/src/config/ServerConfig.h
  core/src/db/wal/WalFile.cpp
  core/src/db/wal/WalFile.h
  core/src/db/wal/WalManager.cpp
  core/src/db/wal/WalManager.h
Labels: PR | automerge, PR | hotfix

#3893 Modify faiss files to reduce the usage of GPU in 0.10.4
  core/src/index/thirdparty/faiss/gpu/GpuIndexIVFFlat.cu
  core/src/index/thirdparty/faiss/gpu/impl/Distance.cu
  core/src/index/thirdparty/faiss/gpu/impl/Distance.cuh
  core/src/index/thirdparty/faiss/gpu/impl/FlatIndex.cu
  core/src/index/thirdparty/faiss/gpu/impl/FlatIndex.cuh
  core/src/index/thirdparty/faiss/gpu/impl/IVFFlat.cu
  core/src/index/thirdparty/faiss/gpu/impl/IVFFlat.cuh
  core/src/index/thirdparty/faiss/gpu/impl/L2Select.cu
  core/src/index/thirdparty/faiss/gpu/impl/L2Select.cuh
Labels: type/new-feature

#3904 Let Bitset all functions inline
  core/src/index/thirdparty/faiss/utils/ConcurrentBitset.cpp
  core/src/index/thirdparty/faiss/utils/ConcurrentBitset.h
Labels: PR | hotfix

#3907 Hnsw case
  tests/milvus_python_test/utils.py
Labels: PR | automerge, PR | skip-ci

#3908 [skip ci] Http case
  tests/milvus_http_test/.dockerignore
  tests/milvus_http_test/.gitignore
  tests/milvus_http_test/Dockerfile
  tests/milvus_http_test/README.md
  tests/milvus_http_test/client.py
  tests/milvus_http_test/conftest.py
  tests/milvus_http_test/constants.py
  tests/milvus_http_test/docker-entrypoint.sh
  tests/milvus_http_test/pytest.ini
  tests/milvus_http_test/requirements.txt
  tests/milvus_http_test/requirements_cluster.txt
  tests/milvus_http_test/requirements_no_pymilvus.txt
  tests/milvus_http_test/run.sh
  tests/milvus_http_test/test_ping.py
  tests/milvus_http_test/utils.py
Labels: PR | automerge
