Repository milvus-io/milvus, pull requests merged in 2020-11, with the labels that each got.

#4155 #4154 Incorrect collection data size when row count larger than 2610000
  core/src/db/snapshot/ResourceOperations.cpp
Labels: PR | automerge, PR | hotfix

#4165 tuning nbits
  core/src/index/knowhere/knowhere/index/vector_index/ConfAdapter.cpp
Labels: PR | automerge

#4164 [skip ci]Update C++ sdk search interface
  CHANGELOG.md
  core/src/db/engine/ExecutionEngineImpl.cpp
  core/src/query/BinaryQuery.cpp
  sdk/examples/simple/src/ClientTest.cpp
  sdk/examples/utils/Utils.cpp
  sdk/examples/utils/Utils.h
  sdk/grpc/ClientProxy.cpp
  sdk/grpc/ClientProxy.h
  sdk/include/MilvusApi.h
  sdk/interface/ConnectionImpl.cpp
  sdk/interface/ConnectionImpl.h
Labels: PR | automerge, PR | hotfix

#4171 cancel 0.11.0 ci nightly
  ci/jenkins/Jenkinsfile
Labels: PR | automerge, PR | skip-ci

#4176 add bulk_insert case
  ci/jenkins/pod/testEnvironment.yaml
  tests/milvus_python_test/collection/test_collection_count.py
  tests/milvus_python_test/collection/test_collection_stats.py
  tests/milvus_python_test/collection/test_create_collection.py
  tests/milvus_python_test/collection/test_get_collection_info.py
  tests/milvus_python_test/collection/test_load_collection.py
  tests/milvus_python_test/constants.py
  tests/milvus_python_test/entity/test_delete.py
  tests/milvus_python_test/entity/test_get_entity_by_id.py
  tests/milvus_python_test/entity/test_insert.py
  tests/milvus_python_test/entity/test_list_id_in_segment.py
  tests/milvus_python_test/entity/test_search.py
  tests/milvus_python_test/requirements.txt
  tests/milvus_python_test/stability/test_mysql.py
  tests/milvus_python_test/stability/test_restart.py
  tests/milvus_python_test/test_compact.py
  tests/milvus_python_test/test_flush.py
  tests/milvus_python_test/test_index.py
  tests/milvus_python_test/test_mix.py
  tests/milvus_python_test/test_partition.py
  tests/milvus_python_test/utils.py
Labels: PR | automerge

#4166 Rename optimizer to selector
  core/src/scheduler/JobMgr.cpp
  core/src/scheduler/SchedInst.cpp
  core/src/scheduler/SchedInst.h
  core/src/scheduler/Scheduler.cpp
  core/src/scheduler/Scheduler.h
  core/src/scheduler/action/Action.h
  core/src/scheduler/action/PushTaskToNeighbour.cpp
  core/src/scheduler/resource/CpuResource.cpp
  core/src/scheduler/resource/CpuResource.h
  core/src/scheduler/resource/DiskResource.cpp
  core/src/scheduler/resource/DiskResource.h
  core/src/scheduler/resource/GpuResource.cpp
  core/src/scheduler/resource/GpuResource.h
  core/src/scheduler/resource/Resource.cpp
  core/src/scheduler/resource/Resource.h
  core/src/scheduler/resource/TestResource.cpp
  core/src/scheduler/resource/TestResource.h
  core/src/scheduler/selector/Selector.cpp
  core/src/scheduler/selector/Selector.h
Labels: PR | automerge, PR | improvement

#4178 #4174 Search out of memory: CPU2GPU1 with index flat
  CHANGELOG.md
  core/src/scheduler/TaskTable.cpp
  core/unittest/scheduler/test_resource.cpp
Labels: PR | automerge

#4190 Anchor bugfix
  core/src/server/web_impl/README.md
Labels: PR | automerge, PR | skip-ci

#4194 [skip ci] Modify changelog
  CHANGELOG.md
Labels: PR | automerge, PR | skip-ci

#4187 add insert case
  tests/milvus_python_test/constants.py
  tests/milvus_python_test/entity/test_bulk_insert.py
  tests/milvus_python_test/entity/test_insert.py
  tests/milvus_python_test/requirements_no_pymilvus.txt
  tests/milvus_python_test/utils.py
Labels: PR | automerge

#4199 #4193 Milvus hangs after continually insert to non-exist partition
  core/src/server/grpc_impl/GrpcRequestHandler.cpp
  core/src/server/grpc_impl/GrpcRequestHandler.h
Labels: PR | automerge, PR | hotfix

#4198 Fix some compatibility issues on ArchLinux
  core/src/db/CMakeLists.txt
  core/thirdparty/nlohmann/json.hpp
Labels: PR | automerge

#4117 ResfulApi Search return null
  CHANGELOG.md
  core/src/server/grpc_impl/GrpcRequestHandler.cpp
  core/src/server/web_impl/handler/WebRequestHandler.cpp
  core/unittest/server/test_web.cpp
Labels: PR | automerge, PR | hotfix

#4206 Restful API error: When the specified partition is retrieved, the par…
  CHANGELOG.md
  core/src/server/web_impl/handler/WebRequestHandler.cpp
Labels: PR | automerge, PR | hotfix

#4215 merge segments at startup
  core/src/db/DBImpl.cpp
Labels: PR | automerge, PR | hotfix

#4192 go-sdk interface Mapping update
  tests/milvus_go_test/collection_test.go
  tests/milvus_go_test/main_test.go
  tests/milvus_go_test/utils/utils.go
Labels: PR | automerge, sdk/go

#4218 In GPU mode, faiss::LOG should be set though GPU is disabled
  core/src/index/archive/KnowhereResource.cpp
  core/src/index/knowhere/knowhere/index/vector_index/VecIndex.h
Labels: PR | automerge, PR | hotfix

#4217 Remove Hacktoberfest from README.md
  README.md
Labels: PR | automerge, PR | skip-ci

#4230 [skip ci] add case for client initialization in go-sdk
  tests/milvus_go_test/connect_test.go
  tests/milvus_go_test/main_test.go
Labels: PR | automerge, PR | skip-ci, sdk/go

#4228 Update Mergify config
  .mergify/config.yml
Labels: PR | skip-ci

#4216 add service search case in java-sdk and add case of get entity with field in go-sdk
  tests/milvus-java-test/src/main/java/com/Constants.java
  tests/milvus-java-test/src/main/java/com/MainClass.java
  tests/milvus-java-test/src/main/java/com/TestGetEntityByID.java
  tests/milvus-java-test/src/main/java/com/TestSearchByService.java
  tests/milvus-java-test/src/main/java/com/TestSearchEntities.java
  tests/milvus-java-test/src/main/java/com/Utils.java
  tests/milvus_go_test/get_test.go
Labels: PR | automerge, PR | skip-ci, sdk/java

#4214 Phase 1 of implementation of read-write seperation
  core/src/db/snapshot/ResourceOperations.cpp
  core/src/db/snapshot/SnapshotHolder.cpp
  core/src/db/snapshot/SnapshotHolder.h
  core/src/db/snapshot/SnapshotPolicy.cpp
  core/src/db/snapshot/SnapshotPolicy.h
  core/src/db/snapshot/SnapshotPolicyFactory.cpp
  core/src/db/snapshot/SnapshotPolicyFactory.h
  core/src/db/snapshot/Snapshots.cpp
  core/src/db/snapshot/Snapshots.h
  core/src/value/config/ConfigInit.cpp
  core/src/value/config/ServerConfig.h
  core/unittest/db/test_snapshot.cpp
  core/unittest/db/utils.cpp
Labels: type/new-feature

#4209 The scalar field value of search result is wrong after deleted
  CHANGELOG.md
  core/src/db/engine/ExecutionEngineImpl.cpp
  core/src/server/delivery/request/SearchReq.cpp
  core/unittest/db/test_db.cpp
  tests/milvus_python_test/entity/test_search.py
Labels: Bug, PR | automerge, PR | hotfix, PR | skip-ci

#4235 add case for search with partition and binary collection
  tests/milvus_http_test/client.py
  tests/milvus_http_test/collections/test_create.py
  tests/milvus_http_test/entities/test_insert.py
  tests/milvus_http_test/entities/test_search.py
  tests/milvus_http_test/utils.py
Labels: PR | automerge, PR | skip-ci, sdk/http

#4237 Fix metrics
  CHANGELOG.md
  core/src/config/ConfigInit.cpp
  core/src/db/DBImpl.cpp
  core/src/db/SnapshotUtils.cpp
  core/src/db/SnapshotUtils.h
Labels: PR | automerge, PR | hotfix

#4238 Optimize SegmentsToSearchCollector
  core/src/db/SnapshotHandlers.cpp
  core/src/db/SnapshotHandlers.h
  core/src/db/snapshot/CompoundOperations.cpp
  core/src/db/snapshot/IterateHandler.h
  core/src/db/snapshot/Operations.h
  core/src/db/snapshot/ResourceContext.h
  core/src/db/snapshot/Store.h
  core/unittest/db/test_meta.cpp
Labels: PR | automerge, PR | hotfix

#4244 remove set omp thread num
  core/src/index/archive/KnowhereResource.cpp
Labels: PR | automerge, PR | hotfix

#4239 Remove blacklist index from VecIndex
  CHANGELOG.md
  ci/scripts/run_unittest.sh
  core/.gitignore
  core/coverage.sh
  core/src/db/CMakeLists.txt
  core/src/db/Types.h
  core/src/db/engine/ExecutionEngineImpl.cpp
  core/src/index/knowhere/knowhere/index/vector_index/VecIndex.h
  core/src/index/knowhere/knowhere/index/vector_index/helpers/Cloner.cpp
  core/src/index/unittest/test_annoy.cpp
  core/src/index/unittest/test_hnsw.cpp
  core/src/metrics/Metrics.h
  core/src/query/GeneralQuery.h
  core/src/segment/DeletedDocs.cpp
  core/src/segment/DeletedDocs.h
  core/src/segment/SegmentReader.cpp
  core/src/storage/CMakeLists.txt
  core/src/utils/Error.h
  core/unittest/CMakeLists.txt
  core/unittest/db/CMakeLists.txt
  core/unittest/db/test_db.cpp
  core/unittest/storage/CMakeLists.txt
Labels: PR | automerge, PR | hotfix, PR | improvement

#4247 improve QueryUtil code
  core/src/query/BinaryQuery.h
  core/src/query/QueryUtil.cpp
  core/src/query/QueryUtil.h
  core/src/server/grpc_impl/GrpcRequestHandler.cpp
  core/src/server/web_impl/handler/WebRequestHandler.cpp
Labels: PR | automerge, PR | hotfix

#4257 Use single-quotes instead of double-quotes in jenkinsfile
  .jenkins/modules/Build/MilvusBuild.groovy
  .jenkins/modules/Build/PackageBuild.groovy
  .jenkins/modules/Publish/Publish.groovy
Labels: PR | automerge, type/enhancement

#4255 It should raise InvalidDsl exception when search with multi vectors
  CHANGELOG.md
  core/src/config/ConfigInit.cpp
  core/src/server/grpc_impl/GrpcRequestHandler.cpp
  core/src/server/web_impl/README.md
Labels: PR | automerge, PR | hotfix

#4253 [skip ci] fix search case in java-sdk
  tests/milvus-java-test/pom.xml
  tests/milvus-java-test/src/main/java/com/TestSearchByService.java
  tests/milvus-java-test/src/main/java/com/TestSearchEntities.java
  tests/milvus-java-test/src/main/java/com/Utils.java
Labels: PR | automerge, PR | skip-ci, sdk/java

#4261 add case: delete & flush during searching
  tests/milvus_python_test/test_flush.py
Labels: PR | automerge

#4249 Rewrite the metrics module
  ci/jenkins/Jenkinsfile
  core/conf/demo/milvus.yaml
  core/conf/milvus.template
  core/src/CMakeLists.txt
  core/src/cache/CMakeLists.txt
  core/src/cache/CacheMgr.h
  core/src/cache/CacheMgr.inl
  core/src/cache/CpuCacheMgr.cpp
  core/src/cache/CpuCacheMgr.h
  core/src/db/DBImpl.cpp
  core/src/db/DBImpl.h
  core/src/db/insert/MemSegment.cpp
  core/src/db/merge/MergeTask.cpp
  core/src/metrics/CMakeLists.txt
  core/src/metrics/MetricBase.h
  core/src/metrics/Prometheus.cpp
  core/src/metrics/Prometheus.h
  core/src/metrics/SystemInfo.cpp
  core/src/metrics/SystemInfo.h
  core/src/metrics/SystemInfoCollector.cpp
  core/src/metrics/SystemInfoCollector.h
  core/src/metrics/prometheus/PrometheusMetrics.cpp
  core/src/metrics/prometheus/PrometheusMetrics.h
  core/src/segment/CMakeLists.txt
  core/src/server/CMakeLists.txt
  core/src/server/DBWrapper.cpp
  core/src/server/Server.cpp
  core/src/server/delivery/request/CmdReq.cpp
  core/src/server/grpc_impl/GrpcRequestHandler.cpp
  core/src/server/grpc_impl/GrpcRequestHandler.h
  core/src/server/web_impl/controller/WebController.hpp
  core/src/server/web_impl/handler/WebRequestHandler.cpp
  core/src/server/web_impl/handler/WebRequestHandler.h
  core/src/value/config/ConfigInit.cpp
  core/src/value/config/ServerConfig.h
  core/unittest/db/CMakeLists.txt
  core/unittest/server/CMakeLists.txt
  core/unittest/server/test_web.cpp
  core/unittest/storage/CMakeLists.txt
  sdk/examples/simple/src/ClientTest.cpp
  tests/milvus_python_test/test_config.py
Labels: PR | automerge

#4275 Program exit abnormally
  CHANGELOG.md
  core/src/server/grpc_impl/GrpcRequestHandler.cpp
  core/src/server/grpc_impl/GrpcRequestHandler.h
  core/src/server/web_impl/handler/WebRequestHandler.cpp
  core/src/server/web_impl/handler/WebRequestHandler.h
Labels: PR | automerge, PR | hotfix

#4281 fix multi thread case by override join method
  tests/milvus_python_test/collection/test_create_collection.py
  tests/milvus_python_test/collection/test_drop_collection.py
  tests/milvus_python_test/collection/test_get_collection_info.py
  tests/milvus_python_test/collection/test_has_collection.py
  tests/milvus_python_test/collection/test_list_collections.py
  tests/milvus_python_test/entity/test_bulk_insert.py
  tests/milvus_python_test/entity/test_search.py
  tests/milvus_python_test/test_flush.py
  tests/milvus_python_test/test_index.py
  tests/milvus_python_test/utils.py
Labels: PR | automerge

#4288 [skip ci] update milvus_benchmark
  tests/milvus_benchmark/README.md
  tests/milvus_benchmark/main.py
Labels: PR | automerge

#4260 Reduce the size of docker images
  docker/build_env/cpu/centos7/Dockerfile
  docker/build_env/cpu/ubuntu16.04/Dockerfile
  docker/build_env/cpu/ubuntu18.04/Dockerfile
  docker/build_env/gpu/centos7/Dockerfile
  docker/build_env/gpu/ubuntu16.04/Dockerfile
  docker/build_env/gpu/ubuntu18.04/Dockerfile
Labels: PR | automerge, type/enhancement

#4278 add read-write mode in CI
  .jenkins/modules/DevTest/SingleNodeDevTest.groovy
Labels: PR | automerge

#4294 Fix 'Illegal instruction' when running index tests at GitHub action
  CHANGELOG.md
  core/src/index/CMakeLists.txt
  core/src/index/knowhere/CMakeLists.txt
  core/src/index/unittest/CMakeLists.txt
  core/src/log/CMakeLists.txt
  core/src/main.cpp
Labels: Bug, PR | automerge, PR | hotfix

#4304 fix virtual destructor
  core/src/cache/DataObj.h
Labels: PR | automerge, PR | hotfix

#4308 fix memcheck leak issue
  core/src/db/snapshot/ReferenceProxy.h
  core/src/db/snapshot/ResourceHolder.h
  core/unittest/db/test_snapshot.cpp
Labels: Bug | Severity | S1, PR | automerge, PR | hotfix

#4312 Setting DSL fields is invalid in restful api, fields are not returned
  CHANGELOG.md
  core/src/server/web_impl/handler/WebRequestHandler.cpp
Labels: PR | automerge, PR | hotfix

#4324 Fix memory leak in IVF indexes
  core/src/db/snapshot/CompoundOperations.h
  core/src/db/snapshot/Operations.h
  core/src/db/snapshot/ReferenceProxy.h
  core/src/db/snapshot/Snapshot.h
  core/src/index/knowhere/knowhere/index/vector_index/IndexBinaryIVF.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexIVF.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexIVFPQ.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexIVFSQ.cpp
  core/src/index/knowhere/knowhere/index/vector_offset_index/IndexIVF_NM.cpp
Labels: PR | automerge, PR | hotfix

#4319 [skip ci]Delete removed api doc in webserver readme.md
  core/src/server/web_impl/README.md
Labels: PR | automerge, PR | hotfix
