Repository milvus-io/milvus, pull requests merged in 2020-08, with the labels that each got.

#3087 (db/snapshot): Update DropAllIndexOperation and some small changes
  core/src/db/SnapshotHandlers.h
  core/src/db/engine/ExecutionEngineImpl.cpp
  core/src/db/snapshot/CompoundOperations.cpp
  core/src/db/snapshot/Context.h
  core/src/db/snapshot/IterateHandler.h
  core/src/db/snapshot/Snapshot.cpp
  core/src/db/snapshot/Snapshot.h
  core/unittest/db/test_snapshot.cpp
Labels: automerge, type/new-feature

#3101 (db/snapshot) implement Delete
  core/src/codecs/DeletedDocsFormat.cpp
  core/src/db/insert/MemCollection.cpp
  core/src/db/meta/backend/MySqlEngine.cpp
  core/src/segment/SegmentWriter.cpp
  core/src/segment/SegmentWriter.h
  core/src/server/delivery/request/FlushReq.cpp
  core/src/server/delivery/request/ListIDInSegmentReq.cpp
Labels: automerge, type/enhancement

#3100 (db/snapshot): Add new TypeNameField and update some ut
  core/src/db/meta/MetaNames.h
  core/src/db/meta/MetaResourceAttrs.cpp
  core/src/db/meta/MetaResourceAttrs.h
  core/src/db/meta/MetaSession.h
  core/src/db/meta/backend/MySqlEngine.cpp
  core/src/db/meta/backend/SqliteEngine.cpp
  core/src/db/snapshot/CompoundOperations.cpp
  core/src/db/snapshot/Resources.cpp
  core/src/db/snapshot/Resources.h
  core/src/db/snapshot/Snapshot.cpp
  core/unittest/db/test_snapshot.cpp
  core/unittest/db/utils.h
Labels: automerge, type/new-feature

#3095 (db/snapshot) Optimize mysql
  core/src/db/meta/backend/MySQLConnectionPool.cpp
  core/src/db/meta/backend/MySQLConnectionPool.h
  core/src/db/meta/backend/MySqlEngine.cpp
  core/src/db/meta/backend/MySqlEngine.h
Labels: automerge, type/enhancement

#3110 [skip ci]copy dablooms' license file from origin repository
  core/thirdparty/dablooms/LICENSE
Labels: automerge

#3113 fix segment dependency sqlite
  core/src/segment/CMakeLists.txt
Labels: Bug

#3112 Optimize DeletedDocsFormat class file I/O
  core/src/codecs/DeletedDocsFormat.cpp
Labels: automerge, type/enhancement

#3107 (scalar) Debug delete request
  core/src/db/DB.h
  core/src/db/DBImpl.cpp
  core/src/db/DBImpl.h
  core/src/db/insert/MemCollection.cpp
  core/src/db/snapshot/CompoundOperations.cpp
  core/src/db/snapshot/CompoundOperations.h
  core/src/db/snapshot/ResourceOperations.cpp
  core/src/segment/SegmentWriter.cpp
  core/unittest/db/test_db.cpp
  tests/milvus_python_test/entity/test_delete.py
Labels: Bug, automerge, type/enhancement

#3147 [skip ci]change test case level
  tests/milvus_python_test/entity/test_delete.py
  tests/milvus_python_test/entity/test_insert.py
Labels: automerge

#3151 disable test_config and some cases in test_ping
  tests/milvus_python_test/test_config.py
  tests/milvus_python_test/test_ping.py
Labels: automerge

#3165 (db/snapshot): fix DeleteEntity bug
  core/src/segment/Segment.cpp
Labels: Bug

#3164 Use ccache with Make
  ci/scripts/build.sh
  core/CMakeLists.txt
  core/src/index/CMakeLists.txt
  core/src/index/cmake/BuildUtilsCore.cmake
  core/src/index/cmake/DefineOptionsCore.cmake
  core/src/index/cmake/ThirdPartyPackagesCore.cmake
Labels: type/enhancement

#3174 Tell ccache to relax some checks in order to increase the hit rat
  ci/scripts/before-install.sh
  ci/scripts/build.sh
  ci/scripts/update_ccache.sh
Labels: type/enhancement

#3166 (db/snapshot): replace boost::filesystem with c++17 filesystem
  core/src/codecs/DeletedDocsFormat.cpp
  core/src/db/CMakeLists.txt
  core/src/db/snapshot/InActiveResourcesGCEvent.h
  core/src/db/snapshot/MetaEvent.h
  core/src/db/snapshot/ResourceGCEvent.h
  core/src/segment/SegmentReader.cpp
  core/src/storage/disk/DiskOperation.cpp
  core/unittest/CMakeLists.txt
  core/unittest/db/test_db.cpp
  core/unittest/db/utils.cpp
Labels: automerge, type/enhancement

#3181 Make Memsegment class create segment explicitly
  core/src/db/insert/MemCollection.cpp
  core/src/db/insert/MemSegment.cpp
  core/src/db/insert/MemSegment.h
  core/src/db/meta/backend/SqliteEngine.cpp
Labels: automerge

#3187 (db/snapshot): retry remove if remove_all fails due to bug in filesystem remove_all
  core/src/db/snapshot/ResourceGCEvent.h
Labels: automerge

#3186 Modefied CCACHE_SLOPPINESS options in order to increase the ccache hit rat
  ci/jenkins/step/coverage.groovy
  ci/scripts/before-install.sh
  ci/scripts/build.sh
Labels: type/enhancement

#3183 add getEntity unittest
  core/src/segment/SegmentReader.cpp
  core/unittest/db/test_db.cpp
Labels: automerge

#3192 [skip ci]fix test bug in whether user defined id
  tests/milvus_python_test/conftest.py
  tests/milvus_python_test/utils.py
Labels: automerge

#3191 Fix sqlite insert error
  core/src/db/meta/MetaAdapter.h
  core/src/db/meta/MetaFactory.cpp
  core/src/db/meta/backend/MetaHelper.cpp
  core/src/db/meta/backend/MetaSchema.cpp
  core/src/db/meta/backend/MetaSchema.h
  core/src/db/meta/backend/SqliteEngine.cpp
  core/src/db/snapshot/Store.h
  core/unittest/db/utils.cpp
Labels: automerge

#3188 Disable ccache in nightly test, bypassing the cache completely
  ci/jenkins/Jenkinsfile
  ci/jenkins/step/nightlyBuild.groovy
  ci/scripts/before-install.sh
Labels: automerge, type/enhancement

#3196 Fix compact function pass parameters error
  core/src/server/grpc_impl/GrpcRequestHandler.cpp
  core/src/server/grpc_impl/GrpcRequestHandler.h
Labels: Bug, automerge

#3200 fix GetEntityBug and part of test case bug
  core/src/db/engine/ExecutionEngineImpl.cpp
  core/src/server/delivery/request/GetEntityByIDReq.cpp
  core/src/server/grpc_impl/GrpcRequestHandler.cpp
  tests/milvus_python_test/entity/test_delete.py
  tests/milvus_python_test/entity/test_get_entity_by_id.py
  tests/milvus_python_test/entity/test_insert.py
  tests/milvus_python_test/test_compact.py
  tests/milvus_python_test/test_flush.py
  tests/milvus_python_test/test_partition.py
  tests/milvus_python_test/test_wal.py
Labels: automerge

#3214 Enable/Disable output of compile commands for clang-tidy
  .clang-tidy
  core/CMakeLists.txt
  core/build-support/run_clang_tidy.py
Labels: automerge, type/enhancement

#3216 Fix CreateIndex bug in C++ sdk
  core/src/grpc/milvus.proto
  core/src/scheduler/task/SearchTask.cpp
  sdk/examples/simple/src/ClientTest.cpp
  sdk/examples/utils/Utils.cpp
  sdk/grpc/ClientProxy.cpp
  sdk/include/MilvusApi.h
  tests/milvus_python_test/entity/test_search.py
Labels: automerge

#3221 enable -Werror to improve code quality
  CHANGELOG.md
  core/CMakeLists.txt
  core/src/index/cmake/ThirdPartyPackagesCore.cmake
  core/src/index/knowhere/knowhere/index/vector_index/IndexHNSW.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexRHNSW.cpp
  core/src/index/knowhere/knowhere/index/vector_index/impl/nsg/Distance.h
  core/src/index/knowhere/knowhere/index/vector_index/impl/nsg/NSG.cpp
  core/src/index/thirdparty/faiss/utils/instruction_set.h
  core/src/index/thirdparty/hnswlib/hnswalg.h
  core/src/index/unittest/test_structured_index_sort.cpp
  core/thirdparty/dablooms/dablooms.cpp
Labels: automerge, type/enhancement

#3219 fix compact bug and change some test case level from 2 to 1
  core/src/db/DBImpl.cpp
  tests/milvus_python_test/collection/test_collection_count.py
  tests/milvus_python_test/collection/test_collection_stats.py
  tests/milvus_python_test/collection/test_create_collection.py
  tests/milvus_python_test/collection/test_drop_collection.py
  tests/milvus_python_test/collection/test_get_collection_info.py
  tests/milvus_python_test/entity/test_delete.py
  tests/milvus_python_test/entity/test_get_entity_by_id.py
  tests/milvus_python_test/entity/test_insert.py
  tests/milvus_python_test/entity/test_list_id_in_segment.py
  tests/milvus_python_test/test_compact.py
  tests/milvus_python_test/test_flush.py
  tests/milvus_python_test/test_index.py
  tests/milvus_python_test/test_partition.py
  tests/milvus_python_test/test_ping.py
Labels: automerge

#3227 Improve MysqlEngine
  core/src/db/meta/MetaAdapter.h
  core/src/db/meta/MetaFactory.h
  core/src/db/meta/backend/MySQLConnectionPool.cpp
  core/src/db/meta/backend/MySQLConnectionPool.h
  core/src/db/meta/backend/MySqlEngine.cpp
  core/src/db/snapshot/ResourceContext.h
  core/src/db/snapshot/Store.h
  core/unittest/db/CMakeLists.txt
  core/unittest/db/test_meta.cpp
  core/unittest/db/utils.cpp
Labels: automerge, type/enhancement

#3207 Optimize grpc download & build in CMakeLists
  core/CMakeLists.txt
  core/cmake/ThirdPartyPackages.cmake
  core/src/db/CMakeLists.txt
  core/src/grpc/cpp_gen.sh
  core/src/index/cmake/ThirdPartyPackagesCore.cmake
  core/thirdparty/CMakeLists.txt
  core/thirdparty/grpc/CMakeLists.txt
  core/thirdparty/gtest/CMakeLists.txt
Labels: automerge

#3235 fix annoy l2
  core/src/index/thirdparty/annoy/src/annoylib.h
Labels: automerge

#3223 Upgrade build environment image version to 0.10.2
  ci/jenkins/pod/milvus-cpu-version-centos7-build-env-pod.yaml
  ci/jenkins/pod/milvus-cpu-version-ubuntu18.04-build-env-pod.yaml
  ci/jenkins/pod/milvus-gpu-version-centos7-build-env-pod.yaml
  ci/jenkins/pod/milvus-gpu-version-ubuntu18.04-build-env-pod.yaml
  docker/build_env/cpu/centos7/Dockerfile
  docker/build_env/cpu/ubuntu16.04/Dockerfile
  docker/build_env/cpu/ubuntu18.04/Dockerfile
  docker/build_env/gpu/centos7/Dockerfile
  docker/build_env/gpu/ubuntu16.04/Dockerfile
  docker/build_env/gpu/ubuntu18.04/Dockerfile
Labels: automerge, type/enhancement

#3229 implement loadcollection
  core/src/cache/CpuCacheMgr.cpp
  core/src/cache/GpuCacheMgr.cpp
  core/src/cache/GpuCacheMgr.h
  core/src/db/Constants.h
  core/src/db/DBImpl.cpp
  core/src/db/SnapshotHandlers.cpp
  core/src/db/SnapshotHandlers.h
  core/src/db/SnapshotUtils.cpp
  core/src/db/SnapshotUtils.h
  core/src/db/Types.h
  core/src/db/insert/MemSegment.cpp
  core/src/segment/SegmentReader.cpp
  core/src/segment/SegmentReader.h
  core/unittest/db/test_db.cpp
Labels: automerge

#3242 Rm find faiss
  core/build.sh
  core/src/index/cmake/FindFAISS.cmake
Labels: automerge

#3239 [skip ci]update clang-tidy rules
  .clang-tidy
  ci/scripts/build.sh
  core/build.sh
Labels: automerge, type/enhancement

#3228 Update Jenkinsfile for improve workflow
  ci/jenkins/Jenkinsfile
  ci/jenkins/step/build.groovy
  ci/jenkins/step/cleanupShardsDev.groovy
  ci/jenkins/step/cleanupShardsDevTest.groovy
  ci/jenkins/step/cleanupSingleDev.groovy
  ci/jenkins/step/cleanupSingleDevTest.groovy
  ci/jenkins/step/coverage.groovy
  ci/jenkins/step/nightlyBuild.groovy
  ci/jenkins/step/shardsDevTest.groovy
  ci/jenkins/step/singleDevNightlyTest.groovy
  ci/jenkins/step/singleDevTest.groovy
Labels: automerge, type/enhancement

#3241 fix cmd req bug and fix test case bug
  core/src/config/ConfigMgr.cpp
  core/src/server/delivery/request/CmdReq.cpp
  tests/milvus_python_test/collection/test_collection_stats.py
  tests/milvus_python_test/collection/test_load_collection.py
  tests/milvus_python_test/entity/test_list_id_in_segment.py
  tests/milvus_python_test/entity/test_search.py
  tests/milvus_python_test/test_config.py
  tests/milvus_python_test/test_flush.py
  tests/milvus_python_test/test_index.py
Labels: automerge

#3246 Fix compile option of thirdparty libs
  core/CMakeLists.txt
  core/build.sh
  core/thirdparty/CMakeLists.txt
  core/thirdparty/grpc/CMakeLists.txt
  core/thirdparty/gtest/CMakeLists.txt
  core/thirdparty/gtest/CMakeLists.txt.in
Labels: automerge

#3247 fix wrong arguments check of hnsw-pq
  core/src/index/knowhere/knowhere/index/vector_index/ConfAdapter.cpp
Labels: automerge

#3225 update dsl search case
  tests/milvus_python_test/entity/test_search.py
  tests/milvus_python_test/utils.py
Labels: automerge

#3256 (mishards) Fix mishards query result reduce error
  shards/mishards/service_handler.py
Labels: Bug, automerge, mishards

#3252 Optimize yaml-cpp download and build process
  core/CMakeLists.txt
  core/cmake/ThirdPartyPackages.cmake
  core/src/config/CMakeLists.txt
  core/thirdparty/CMakeLists.txt
  core/thirdparty/grpc/CMakeLists.txt
  core/thirdparty/gtest/CMakeLists.txt
  core/thirdparty/versions.txt
  core/thirdparty/yaml-cpp/CMakeLists.txt
Labels: automerge

#3257 Add http interfaces
  core/src/server/grpc_impl/GrpcRequestHandler.cpp
  core/src/server/web_impl/Types.h
  core/src/server/web_impl/controller/WebController.hpp
  core/src/server/web_impl/handler/WebRequestHandler.cpp
  core/src/server/web_impl/handler/WebRequestHandler.h
  sdk/examples/simple/src/ClientTest.cpp
Labels: automerge

#3244 [skip ci] disable ubuntu && update case
  ci/jenkins/step/singleDevTest.groovy
  tests/milvus_python_test/collection/test_collection_stats.py
  tests/milvus_python_test/collection/test_get_collection_info.py
  tests/milvus_python_test/collection/test_list_collections.py
  tests/milvus_python_test/collection/test_load_collection.py
  tests/milvus_python_test/entity/test_delete.py
  tests/milvus_python_test/entity/test_get_entity_by_id.py
  tests/milvus_python_test/entity/test_insert.py
  tests/milvus_python_test/entity/test_list_id_in_segment.py
  tests/milvus_python_test/entity/test_search.py
  tests/milvus_python_test/test_compact.py
  tests/milvus_python_test/test_index.py
  tests/milvus_python_test/utils.py
Labels: automerge

#3260 rm multiple url for yaml-cpp
  core/thirdparty/CMakeLists.txt
  core/thirdparty/grpc/CMakeLists.txt
  core/thirdparty/gtest/CMakeLists.txt
  core/thirdparty/yaml-cpp/CMakeLists.txt
Labels: automerge

#3264 remove ZLIB from our build tree
  core/cmake/ThirdPartyPackages.cmake
  core/src/db/CMakeLists.txt
Labels: automerge

#3270 [GPU Flat] assign the metric type when query
  core/src/index/knowhere/knowhere/index/vector_index/gpu/IndexGPUIDMAP.cpp
Labels: automerge, type/new-feature

#3272 Upgrade third-party oatpp up to v1.1.0
  CHANGELOG.md
  core/cmake/ThirdPartyPackages.cmake
  core/src/server/web_impl/controller/WebController.hpp
  core/src/server/web_impl/dto/CollectionDto.hpp
  core/src/server/web_impl/dto/ConfigDto.hpp
  core/src/server/web_impl/dto/DevicesDto.hpp
  core/src/server/web_impl/dto/Dto.h
  core/src/server/web_impl/dto/IndexDto.hpp
  core/src/server/web_impl/dto/PartitionDto.hpp
  core/src/server/web_impl/dto/StatusDto.hpp
  core/src/server/web_impl/dto/VectorDto.hpp
  core/src/server/web_impl/handler/WebRequestHandler.cpp
  core/src/server/web_impl/handler/WebRequestHandler.h
  core/thirdparty/versions.txt
Labels: automerge, type/enhancement

#3275 [skip ci]fix typo
  core/src/server/Server.cpp
Labels: automerge

#3276 Optimize download&compilation of opentracing
  core/cmake/ThirdPartyPackages.cmake
  core/src/CMakeLists.txt
  core/src/db/CMakeLists.txt
  core/src/tracing/CMakeLists.txt
  core/thirdparty/CMakeLists.txt
  core/thirdparty/opentracing/CMakeLists.txt
  core/unittest/CMakeLists.txt
Labels: automerge

#3273 Specifying distance type at runtime for Flat index
  CHANGELOG.md
  core/src/db/engine/ExecutionEngineImpl.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexBinaryIDMAP.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexIDMAP.cpp
  core/src/index/knowhere/knowhere/index/vector_index/gpu/IndexGPUIDMAP.cpp
  core/src/scheduler/task/SearchTask.cpp
Labels: type/new-feature

#3279 Master fix
  core/src/db/DBImpl.cpp
  core/src/db/insert/MemCollection.cpp
  core/src/db/insert/MemManagerImpl.cpp
  core/src/db/insert/MemSegment.cpp
  core/src/db/snapshot/ResourceGCEvent.h
  core/src/db/snapshot/Snapshot.h
  core/src/db/wal/WalFileHandler.cpp
  core/src/index/knowhere/knowhere/common/Exception.cpp
  core/src/index/knowhere/knowhere/index/structured_index/StructuredIndexSort-inl.h
  core/src/index/knowhere/knowhere/index/vector_index/IndexHNSW.cpp
  core/src/index/thirdparty/annoy/src/annoylib.h
  core/src/index/thirdparty/hnswlib/hnswlib.h
  core/src/log/Log.cpp
  core/src/segment/Segment.cpp
  core/src/segment/SegmentWriter.cpp
  core/src/server/grpc_impl/GrpcRequestHandler.cpp
  core/src/server/web_impl/handler/WebRequestHandler.cpp
  core/src/tracing/TraceContext.cpp
Labels: automerge

#3283 Check stale segment file when flush delete ids
  core/src/db/insert/MemCollection.cpp
  core/src/db/snapshot/CompoundOperations.cpp
  core/src/db/snapshot/CompoundOperations.h
  core/unittest/db/test_db.cpp
Labels: Bug, automerge

#3285 fix storage clang tidy warnings
  core/src/codecs/BlockFormat.cpp
  core/src/codecs/DeletedDocsFormat.cpp
  core/src/codecs/IdBloomFilterFormat.cpp
  core/src/codecs/StructuredIndexFormat.cpp
  core/src/codecs/VectorCompressFormat.cpp
  core/src/codecs/VectorIndexFormat.cpp
  core/src/storage/CMakeLists.txt
  core/src/storage/IOReader.h
  core/src/storage/IOWriter.h
  core/src/storage/disk/DiskIOReader.cpp
  core/src/storage/disk/DiskIOReader.h
  core/src/storage/disk/DiskIOWriter.cpp
  core/src/storage/disk/DiskIOWriter.h
  core/src/storage/disk/DiskOperation.cpp
  core/src/storage/s3/S3IOReader.cpp
  core/src/storage/s3/S3IOReader.h
  core/src/storage/s3/S3IOWriter.h
  core/src/utils/Error.h
  core/src/utils/Exception.h
  core/unittest/CMakeLists.txt
  core/unittest/storage/CMakeLists.txt
  core/unittest/storage/test_disk.cpp
  core/unittest/storage/utils.cpp
Labels: automerge, type/enhancement

#3284 conf build_index_threshold
  core/src/config/ConfigMgr.cpp
  core/src/config/ServerConfig.h
  core/src/db/Constants.h
  core/src/db/SnapshotHandlers.cpp
  core/src/db/SnapshotHandlers.h
Labels: automerge

#3290 [skip ci] disable cron test on 0.10.2
  ci/jenkins/Jenkinsfile
Labels: automerge

#3255 Fix generate codecov file error
  ci/scripts/coverage.sh
Labels: Bug | Severity | S3, automerge

#3282 Developing a modular pipeline library to improve DevOps collaboration
  .codacy.yaml
  .gitignore
  .jenkins/modules/Build/MilvusBuild.groovy
  .jenkins/modules/Build/PackageBuild.groovy
  .jenkins/modules/Coverage/Coverage.groovy
  .jenkins/modules/DevTest/CleanupMishardsDevTest.groovy
  .jenkins/modules/DevTest/CleanupSingleNodeDevTest.groovy
  .jenkins/modules/DevTest/MishardsDevTest.groovy
  .jenkins/modules/DevTest/SingleNodeDevTest.groovy
  .jenkins/modules/Publish/Publish.groovy
  .jenkins/modules/Unittest/Unittest.groovy
  .jenkinsignore
  ci/jenkins/Jenkinsfile
  ci/jenkins/scripts/mail.py
  ci/jenkins/scripts/requirements.txt
  ci/jenkins/scripts/yaml_processor.py
  ci/jenkins/step/build.groovy
  ci/jenkins/step/cleanupShardsDevTest.groovy
  ci/jenkins/step/shardsDevTest.groovy
Labels: automerge, type/enhancement

#3304 [skip ci] Fixed images in README.
  README.md
  README_CN.md
Labels: Documentation

#3303 Fix invalid ranges and delete logging
  tests/milvus_python_test/entity/test_search.py
  tests/milvus_python_test/utils.py
Labels: automerge

#3305 Optimize thirdparty libunwind and gperftools download & compile processes
  core/CMakeLists.txt
  core/cmake/ThirdPartyPackages.cmake
  core/src/CMakeLists.txt
  core/src/db/CMakeLists.txt
  core/thirdparty/CMakeLists.txt
  core/thirdparty/grpc/CMakeLists.txt
  core/thirdparty/gtest/CMakeLists.txt
  core/thirdparty/opentracing/CMakeLists.txt
  core/thirdparty/profilers/CMakeLists.txt
  core/thirdparty/yaml-cpp/CMakeLists.txt
Labels: automerge

#3308 fix codacy warnings
  core/src/db/engine/ExecutionEngineImpl.cpp
  core/src/db/insert/MemSegment.cpp
  core/src/db/meta/backend/MockEngine.cpp
  core/src/db/snapshot/CompoundOperations.cpp
  core/src/index/knowhere/knowhere/common/Log.cpp
  core/src/index/unittest/CMakeLists.txt
  core/src/index/unittest/faiss_benchmark/faiss_benchmark_test.cpp
  core/src/index/unittest/faiss_benchmark/faiss_bitset_test.cpp
  core/src/index/unittest/faiss_ori/CMakeLists.txt
  core/src/index/unittest/faiss_ori/gpuresource_test.cpp
  core/src/index/unittest/metric_alg_benchmark/metric_benchmark_test.cpp
  core/src/index/unittest/test_wrapper.cpp
  core/src/metrics/SystemInfo.cpp
  core/src/scheduler/selector/FaissFlatPass.cpp
  core/src/scheduler/selector/FaissIVFFlatPass.cpp
  core/src/scheduler/selector/FaissIVFPQPass.cpp
  core/src/scheduler/selector/FaissIVFSQ8HPass.cpp
  core/src/scheduler/selector/FaissIVFSQ8Pass.cpp
  core/src/server/delivery/request/CompactReq.cpp
  core/src/server/delivery/request/CountEntitiesReq.cpp
  core/src/server/delivery/request/CreatePartitionReq.cpp
  core/src/server/delivery/request/DeleteEntityByIDReq.cpp
  core/src/server/delivery/request/DescribeIndexReq.cpp
  core/src/server/delivery/request/DropCollectionReq.cpp
  core/src/server/delivery/request/DropIndexReq.cpp
  core/src/server/delivery/request/DropPartitionReq.cpp
  core/src/server/delivery/request/FlushReq.cpp
  core/src/server/delivery/request/GetCollectionStatsReq.cpp
  core/src/server/delivery/request/InsertReq.cpp
  core/src/server/delivery/request/ListPartitionsReq.cpp
  core/src/server/grpc_impl/GrpcRequestHandler.cpp
  core/src/utils/CommonUtil.cpp
  core/src/utils/StringHelpFunctions.cpp
  core/unittest/db/test_db.cpp
  core/unittest/db/test_snapshot.cpp
  sdk/examples/partition/src/ClientTest.cpp
  sdk/examples/qps/src/ClientTest.cpp
Labels: automerge, type/enhancement

#3312 enable binary search cases
  tests/milvus_python_test/collection/test_load_collection.py
  tests/milvus_python_test/entity/test_search.py
  tests/milvus_python_test/utils.py
Labels: automerge

#3313 refactor LogMgr init in Server::Start
  core/src/log/LogMgr.cpp
  core/src/log/LogMgr.h
  core/src/main.cpp
  core/src/server/Server.cpp
  core/src/server/Server.h
Labels: automerge

#3324 Fix clang-tidy bug
  core/CMakeLists.txt
  core/src/index/cmake/DefineOptionsCore.cmake
Labels: Bug | Severity | S2, automerge

#3325 enable some cases
  tests/milvus_python_test/entity/test_search.py
  tests/milvus_python_test/test_flush.py
  tests/milvus_python_test/test_index.py
  tests/milvus_python_test/test_partition.py
  tests/milvus_python_test/utils.py
Labels: automerge

#3307 #3295 Server crashed during creating index
  core/src/scheduler/task/BuildIndexTask.cpp
  core/src/server/ValidationUtil.cpp
  core/src/server/ValidationUtil.h
  core/src/server/delivery/request/CreateIndexReq.cpp
  tests/milvus_python_test/collection/test_load_collection.py
Labels: automerge

#3316 add file header and tail implementation
  core/src/codecs/BlockFormat.cpp
  core/src/codecs/DeletedDocsFormat.cpp
  core/src/codecs/StructuredIndexFormat.cpp
  core/src/codecs/VectorCompressFormat.cpp
  core/src/codecs/VectorIndexFormat.cpp
  core/src/db/CMakeLists.txt
  core/src/storage/CMakeLists.txt
  core/src/storage/ExtraFileInfo.cpp
  core/src/storage/ExtraFileInfo.h
  core/src/storage/ExtraFileInfoTest.cpp
  core/src/storage/FSHandler.h
  core/src/storage/IOReader.h
  core/src/storage/IOWriter.h
  core/src/storage/disk/DiskIOReader.cpp
  core/src/storage/disk/DiskIOReader.h
  core/src/storage/disk/DiskIOWriter.cpp
  core/src/storage/disk/DiskIOWriter.h
  core/src/utils/Error.h
  core/thirdparty/CMakeLists.txt
  core/thirdparty/crc32c/CMakeLists.txt
  core/thirdparty/versions.txt
Labels: automerge

#3323 fix include directories not find bug
  core/thirdparty/profilers/CMakeLists.txt
Labels: automerge

#3326 reduce grpc download file size from 380M to 130M
  core/thirdparty/grpc/CMakeLists.txt
  core/thirdparty/versions.txt
Labels: automerge

#3314 update clang-tidy config
  .clang-tidy
  ci/scripts/build.sh
  core/build-support/lint_exclusions.txt
  core/build.sh
Labels: automerge

#3322 Master codacy v3
  core/src/index/knowhere/knowhere/index/vector_index/IndexBinaryIDMAP.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexBinaryIVF.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexNSG.cpp
  core/src/index/knowhere/knowhere/index/vector_index/VecIndexFactory.cpp
  core/src/index/knowhere/knowhere/index/vector_index/gpu/IndexGPUIVF.cpp
  core/src/index/knowhere/knowhere/index/vector_offset_index/gpu/IndexGPUIVF_NM.cpp
  core/src/index/unittest/faiss_benchmark/faiss_benchmark_test.cpp
Labels: automerge

#3340 fix clang tidy warnings
  .clang-tidy
  core/src/config/ConfigMgr.cpp
  core/src/config/ConfigType.cpp
  core/src/index/knowhere/knowhere/common/Exception.cpp
  core/src/index/knowhere/knowhere/common/Exception.h
  core/src/index/knowhere/knowhere/common/Timer.cpp
  core/src/index/knowhere/knowhere/common/Timer.h
  core/src/metrics/SystemInfo.cpp
  core/src/server/context/Context.cpp
  core/src/server/context/Context.h
  core/src/server/delivery/ReqQueue.cpp
  core/src/server/delivery/ReqQueue.h
  core/src/server/delivery/request/Types.cpp
  core/src/server/grpc_impl/GrpcRequestHandler.cpp
  core/src/server/grpc_impl/GrpcRequestHandler.h
  core/src/server/init/InstanceLockCheck.cpp
  core/src/storage/ExtraFileInfo.cpp
  core/src/tracing/TraceContext.h
  core/src/utils/ConfigUtils.cpp
  core/src/utils/Exception.h
  core/src/utils/Status.cpp
  core/src/utils/TimeRecorder.cpp
  core/src/utils/TimeRecorder.h
Labels: automerge, type/enhancement

#3333 Fix milvus crash when exiting
  core/cmake/ThirdPartyPackages.cmake
  core/src/scheduler/SchedInst.cpp
  core/src/scheduler/selector/Optimizer.cpp
  core/src/scheduler/selector/Optimizer.h
  core/src/server/web_impl/WebServer.cpp
Labels: automerge

#3337 Optimize download & compile of mysqlpp
  core/cmake/ThirdPartyPackages.cmake
  core/src/CMakeLists.txt
  core/thirdparty/CMakeLists.txt
  core/thirdparty/crc32c/CMakeLists.txt
  core/thirdparty/mysqlpp/CMakeLists.txt
  core/thirdparty/profilers/CMakeLists.txt
Labels: automerge

#3344 fix clang-tidy warnings
  core/src/index/knowhere/knowhere/common/Timer.cpp
  core/src/index/knowhere/knowhere/index/Index.h
  core/src/index/knowhere/knowhere/index/vector_index/ConfAdapter.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexAnnoy.h
  core/src/index/knowhere/knowhere/index/vector_index/IndexBinaryIDMAP.h
  core/src/index/knowhere/knowhere/index/vector_index/IndexBinaryIVF.h
  core/src/index/knowhere/knowhere/index/vector_index/IndexHNSW.h
  core/src/index/knowhere/knowhere/index/vector_index/IndexIDMAP.h
  core/src/index/knowhere/knowhere/index/vector_index/IndexIVF.h
  core/src/index/knowhere/knowhere/index/vector_index/IndexNSG.h
  core/src/index/knowhere/knowhere/index/vector_index/IndexRHNSWFlat.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexRHNSWFlat.h
  core/src/index/knowhere/knowhere/index/vector_index/IndexRHNSWPQ.h
  core/src/index/knowhere/knowhere/index/vector_index/IndexRHNSWSQ.h
  core/src/index/knowhere/knowhere/index/vector_index/IndexSPTAG.h
  core/src/index/knowhere/knowhere/index/vector_index/gpu/IndexIVFSQHybrid.cpp
  core/src/index/unittest/test_annoy.cpp
  core/src/index/unittest/test_binaryidmap.cpp
  core/src/index/unittest/test_binaryivf.cpp
  core/src/index/unittest/test_customized_index.cpp
  core/src/index/unittest/test_hnsw.cpp
  core/src/index/unittest/test_idmap.cpp
  core/src/index/unittest/test_ivf.cpp
  core/src/index/unittest/test_rhnsw_flat.cpp
  core/src/index/unittest/test_rhnsw_pq.cpp
  core/src/index/unittest/test_rhnsw_sq8.cpp
  core/src/main.cpp
  core/src/scheduler/Scheduler.cpp
  core/src/scheduler/Scheduler.h
  core/src/segment/SegmentWriter.cpp
  core/src/utils/ConfigUtils.cpp
  core/src/utils/SignalHandler.cpp
  core/src/utils/Status.cpp
  core/src/utils/Status.h
  core/src/utils/TimeRecorder.cpp
Labels: automerge, type/enhancement

#3343 refactor Server::Start()
  core/src/server/Server.cpp
  core/src/server/Server.h
  core/src/server/init/Directory.cpp
  core/src/server/init/Directory.h
  core/src/server/init/InstanceLockCheck.cpp
  core/src/server/init/Timezone.cpp
  core/src/server/init/Timezone.h
Labels: automerge

#3338 fix hamming
  core/src/index/knowhere/knowhere/index/vector_index/IndexBinaryIDMAP.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexBinaryIDMAP.h
  core/src/index/knowhere/knowhere/index/vector_index/IndexBinaryIVF.cpp
  sdk/examples/binary_vector/src/ClientTest.cpp
  sdk/examples/utils/Utils.cpp
  sdk/examples/utils/Utils.h
  sdk/include/MilvusApi.h
Labels: Bug

#3342 fix hamming
  core/src/index/knowhere/knowhere/index/vector_index/IndexBinaryIDMAP.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexBinaryIDMAP.h
  core/src/index/knowhere/knowhere/index/vector_index/IndexBinaryIVF.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexBinaryIVF.h
  sdk/examples/binary_vector/src/ClientTest.cpp
Labels: automerge

#3350 Download path can be configured
  core/build.sh
  core/thirdparty/CMakeLists.txt
  core/thirdparty/crc32c/CMakeLists.txt
  core/thirdparty/grpc/CMakeLists.txt
  core/thirdparty/gtest/CMakeLists.txt
  core/thirdparty/mysqlpp/CMakeLists.txt
  core/thirdparty/opentracing/CMakeLists.txt
  core/thirdparty/profilers/CMakeLists.txt
  core/thirdparty/yaml-cpp/CMakeLists.txt
Labels: automerge

#3345 Implement wal
  core/src/db/Constants.h
  core/src/db/DB.h
  core/src/db/DBImpl.cpp
  core/src/db/DBImpl.h
  core/src/db/DBProxy.cpp
  core/src/db/DBProxy.h
  core/src/db/IDGenerator.cpp
  core/src/db/IDGenerator.h
  core/src/db/Types.h
  core/src/db/Utils.cpp
  core/src/db/engine/ExecutionEngineImpl.cpp
  core/src/db/insert/MemCollection.cpp
  core/src/db/insert/MemCollection.h
  core/src/db/insert/MemManager.h
  core/src/db/insert/MemManagerImpl.cpp
  core/src/db/insert/MemManagerImpl.h
  core/src/db/insert/MemSegment.cpp
  core/src/db/insert/MemSegment.h
  core/src/db/transcript/TranscriptProxy.cpp
  core/src/db/transcript/TranscriptProxy.h
  core/src/db/wal/WalFile.cpp
  core/src/db/wal/WalFile.h
  core/src/db/wal/WalManager.cpp
  core/src/db/wal/WalManager.h
  core/src/db/wal/WalOperation.h
  core/src/db/wal/WalOperationCodec.cpp
  core/src/db/wal/WalOperationCodec.h
  core/src/db/wal/WalProxy.cpp
  core/src/db/wal/WalProxy.h
  core/src/segment/IdBloomFilter.cpp
  core/src/segment/IdBloomFilter.h
  core/src/segment/SegmentReader.cpp
  core/src/segment/SegmentReader.h
  core/src/segment/SegmentWriter.cpp
  core/src/segment/SegmentWriter.h
  core/unittest/db/CMakeLists.txt
  core/unittest/db/test_db.cpp
  core/unittest/db/test_segment.cpp
  core/unittest/db/test_wal.cpp
  core/unittest/db/utils.cpp
  core/unittest/db/utils.h
Labels: automerge

#3339 Insert entities before search
  tests/milvus_python_test/entity/test_search.py
Labels: automerge

#3354 Refactor directory access check and add config system.lock.enable
  core/src/config/ConfigMgr.cpp
  core/src/config/ConfigMgr.h
  core/src/config/ServerConfig.h
  core/src/server/Server.cpp
  core/src/server/Server.h
  core/src/server/init/Directory.cpp
  core/src/server/init/Directory.h
  core/src/server/init/StorageChecker.cpp
  core/src/server/init/StorageChecker.h
Labels: automerge

#3360 #3265 clear finished task to release some resource
  core/src/scheduler/TaskTable.cpp
  core/src/scheduler/TaskTable.h
  core/src/scheduler/task/FinishedTask.cpp
  core/src/scheduler/task/FinishedTask.h
Labels: automerge

#3349 #3309 Error should be raised if search binary collection with metric_type: L2
  core/src/server/ValidationUtil.cpp
  core/src/server/ValidationUtil.h
  core/src/server/delivery/request/SearchReq.cpp
  tests/milvus_python_test/test_index.py
Labels: automerge

#3357 Optimize download & compile of Prometheus
  core/cmake/ThirdPartyPackages.cmake
  core/src/CMakeLists.txt
  core/src/db/CMakeLists.txt
  core/src/metrics/CMakeLists.txt
  core/thirdparty/CMakeLists.txt
  core/thirdparty/prometheus/CMakeLists.txt
Labels: automerge

#3355 #3301 rename configure file
  core/.gitignore
  core/CMakeLists.txt
  core/conf/demo/milvus.yaml
  core/conf/milvus.template
  core/scripts/start_server.sh
  core/src/server/DBWrapper.cpp
  core/start_server.sh
  core/unittest/storage/utils.h
  docker/deploy/cpu/centos7/Dockerfile
  docker/deploy/cpu/ubuntu16.04/Dockerfile
  docker/deploy/cpu/ubuntu18.04/Dockerfile
  docker/deploy/gpu/centos7/Dockerfile
  docker/deploy/gpu/ubuntu16.04/Dockerfile
  docker/deploy/gpu/ubuntu18.04/Dockerfile
  docker/docker-compose-monitor.yml
Labels: automerge

#3371 fix clang tidy warnings
  core/src/db/SnapshotUtils.cpp
  core/src/db/Utils.cpp
  core/src/db/engine/ExecutionEngineImpl.cpp
  core/src/db/insert/MemManagerImpl.cpp
  core/src/db/insert/MemSegment.cpp
  core/src/db/merge/MergeManagerImpl.cpp
  core/src/db/meta/backend/MySQLConnectionPool.cpp
  core/src/db/snapshot/Operations.h
  core/src/db/snapshot/ResourceOperations.cpp
  core/src/db/snapshot/SnapshotHolder.cpp
  core/src/db/snapshot/Snapshots.cpp
  core/src/scheduler/TaskTable.cpp
  core/src/scheduler/action/PushTaskToNeighbour.cpp
  core/src/scheduler/job/BuildIndexJob.cpp
  core/src/scheduler/job/Job.cpp
  core/src/scheduler/resource/Resource.cpp
  core/src/scheduler/selector/BuildIndexPass.cpp
  core/src/scheduler/selector/FaissFlatPass.cpp
  core/src/scheduler/selector/FaissIVFFlatPass.cpp
  core/src/scheduler/selector/FaissIVFPQPass.cpp
  core/src/scheduler/selector/FaissIVFSQ8HPass.cpp
  core/src/scheduler/selector/FaissIVFSQ8Pass.cpp
Labels: automerge

#3369 fix param check
  core/src/index/knowhere/knowhere/index/vector_index/ConfAdapter.cpp
Labels: automerge

#3372 refactor LogMgr
  core/src/log/LogMgr.cpp
  core/src/log/LogMgr.h
Labels: automerge

#3364 Find system headers with cmake and clang-tidy
  .clang-tidy
  core/CMakeLists.txt
Labels: automerge, type/enhancement

#3373 [skip ci]add google/crc32c into NOTICE.md
  NOTICE.md
Labels: automerge

#3376 prepare change memmanager for wal
  core/src/db/DBImpl.cpp
  core/src/db/insert/MemCollection.cpp
  core/src/db/insert/MemCollection.h
  core/src/db/insert/MemManager.h
  core/src/db/insert/MemManagerImpl.cpp
  core/src/db/insert/MemManagerImpl.h
  core/src/db/insert/MemSegment.cpp
  core/src/db/insert/MemSegment.h
  core/src/db/insert/VectorSource.cpp
  core/src/db/insert/VectorSource.h
  core/src/db/wal/WalManager.cpp
  core/unittest/db/test_wal.cpp
Labels: automerge

#3379 [skip ci]update issue template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: automerge

#3375 [skip ci] fix java sdk test case
  tests/milvus-java-test/pom.xml
  tests/milvus-java-test/src/main/java/com/MainClass.java
  tests/milvus-java-test/src/main/java/com/TestCollection.java
  tests/milvus-java-test/src/main/java/com/TestCollectionCount.java
  tests/milvus-java-test/src/main/java/com/TestCollectionInfo.java
  tests/milvus-java-test/src/main/java/com/TestCompact.java
  tests/milvus-java-test/src/main/java/com/TestConnect.java
  tests/milvus-java-test/src/main/java/com/TestDeleteVectors.java
  tests/milvus-java-test/src/main/java/com/TestFlush.java
  tests/milvus-java-test/src/main/java/com/TestGetEntityByID.java
  tests/milvus-java-test/src/main/java/com/TestGetVectorByID.java
  tests/milvus-java-test/src/main/java/com/TestIndex.java
  tests/milvus-java-test/src/main/java/com/TestInsertEntities.java
  tests/milvus-java-test/src/main/java/com/TestMix.java
  tests/milvus-java-test/src/main/java/com/TestPS.java
  tests/milvus-java-test/src/main/java/com/TestPartition.java
  tests/milvus-java-test/src/main/java/com/TestPing.java
  tests/milvus-java-test/src/main/java/com/TestSearchVectors.java
  tests/milvus-java-test/src/main/java/com/Utils.java
Labels: automerge

#3361 optimize download & compile of sqlite
  core/cmake/ThirdPartyPackages.cmake
  core/thirdparty/CMakeLists.txt
  core/thirdparty/sqlite/CMakeLists.txt
Labels: automerge

#3382 [skip ci] fix generate default entities
  tests/milvus-java-test/src/main/java/com/TestCollectionCount.java
  tests/milvus-java-test/src/main/java/com/TestCollectionInfo.java
  tests/milvus-java-test/src/main/java/com/TestGetEntityByID.java
  tests/milvus-java-test/src/main/java/com/TestInsertEntities.java
  tests/milvus-java-test/src/main/java/com/Utils.java
Labels: automerge

#3386 [skip ci] update clang-tidy rules
  .clang-tidy
  core/CMakeLists.txt
  core/build-support/lint_exclusions.txt
Labels: automerge

#3384 Optimize download & compile of Aws
  core/cmake/ThirdPartyPackages.cmake
  core/thirdparty/CMakeLists.txt
  core/thirdparty/aws/CMakeLists.txt
Labels: automerge

#3409 [skip ci] Java sdk test: add testIndex.java
  tests/milvus-java-test/src/main/java/com/TestDeleteEntities.java
  tests/milvus-java-test/src/main/java/com/TestDeleteVectors.java
  tests/milvus-java-test/src/main/java/com/TestIndex.java
  tests/milvus-java-test/src/main/java/com/Utils.java
Labels: automerge

#3416 update clang-tidy rules
  .clang-tidy
  core/src/metrics/SystemInfo.cpp
  core/src/server/grpc_impl/GrpcRequestHandler.cpp
  core/src/utils/Status.cpp
  core/src/utils/Status.h
Labels: automerge

#3414 remove the _id fileld when get collection info
  core/src/server/grpc_impl/GrpcRequestHandler.cpp
  tests/milvus_python_test/collection/test_get_collection_info.py
Labels: automerge

#3423 Milvus build stage parallel processing
  .github/workflows/cpplint.yml
  .jenkins/modules/Build/MilvusBuild.groovy
  ci/scripts/build.sh
  docker-compose.yml
Labels: automerge, type/enhancement

#3424 fix faiss cannot build gpu bug
  core/src/index/cmake/ThirdPartyPackagesCore.cmake
Labels: automerge

#3413 #3265 fix memory leak
  core/src/scheduler/CircleQueue.h
  core/src/scheduler/ResourceMgr.cpp
  core/src/scheduler/TaskTable.cpp
  core/src/scheduler/resource/Resource.cpp
  core/src/scheduler/resource/Resource.h
  core/src/storage/ExtraFileInfo.cpp
Labels: automerge

#3425 Fix webserver set_config bug
  core/src/server/web_impl/handler/WebRequestHandler.cpp
  core/unittest/server/test_web.cpp
Labels: automerge

#3428 Fix Server get stuck if create index with invalide metric types after entities inserted
  CHANGELOG.md
  core/src/server/ValidationUtil.cpp
  tests/milvus_python_test/test_index.py
Labels: automerge

#3434 Add partition_tag in GetPageEntities
  core/src/server/web_impl/dto/VectorDto.hpp
  core/src/server/web_impl/handler/WebRequestHandler.cpp
  core/src/server/web_impl/handler/WebRequestHandler.h
  core/unittest/server/test_web.cpp
Labels: automerge

#3436 Fix server crashed during random test
  core/src/segment/SegmentReader.cpp
Labels: Bug, automerge

#3432 Optimize clang-tidy workflow for code static analysis
  core/CMakeLists.txt
  core/build-support/ignore_checks.txt
  core/build-support/run_clang_tidy.py
  sdk/build-support/ignore_checks.txt
  sdk/build-support/run_clang_tidy.py
Labels: automerge

#3442 Fix no debug and info log generated after server started
  CHANGELOG.md
  core/src/log/LogMgr.cpp
Labels: automerge

#3440 clear task from tasktable
  CHANGELOG.md
  core/src/scheduler/resource/Resource.cpp
Labels: automerge

#3451 Fix rhnsw flat ut error
  CHANGELOG.md
  core/src/index/unittest/test_rhnsw_flat.cpp
Labels: automerge

#3455 change the data type of crc32c
  core/src/storage/ExtraFileInfo.cpp
  core/src/storage/ExtraFileInfo.h
  core/src/storage/ExtraFileInfoTest.cpp
Labels: automerge

#3454 Update version
  tests/milvus_python_test/test_ping.py
Labels: automerge

#3452 update coverity.sh
  .github/workflows/core.yml
  .jenkins/modules/Unittest/Unittest.groovy
  ci/jenkins/pod/milvus-cpu-version-centos7-build-env-pod.yaml
  ci/jenkins/pod/milvus-cpu-version-ubuntu18.04-build-env-pod.yaml
  ci/jenkins/pod/milvus-gpu-version-centos7-build-env-pod.yaml
  ci/jenkins/pod/milvus-gpu-version-ubuntu18.04-build-env-pod.yaml
  ci/scripts/coverage.sh
  ci/scripts/run_unittest.sh
  core/coverage.sh
  docker-compose.yml
Labels: automerge

#3391 rewrite insert memmanager for wal
  core/src/db/Constants.h
  core/src/db/DBImpl.cpp
  core/src/db/DBImpl.h
  core/src/db/SnapshotHandlers.cpp
  core/src/db/SnapshotHandlers.h
  core/src/db/Types.h
  core/src/db/engine/ExecutionEngineImpl.cpp
  core/src/db/insert/MemCollection.cpp
  core/src/db/insert/MemCollection.h
  core/src/db/insert/MemManagerImpl.cpp
  core/src/db/insert/MemManagerImpl.h
  core/src/db/insert/MemSegment.cpp
  core/src/db/insert/MemSegment.h
  core/src/db/insert/VectorSource.cpp
  core/src/db/insert/VectorSource.h
  core/src/db/merge/MergeManager.h
  core/src/db/merge/MergeManagerImpl.cpp
  core/src/db/merge/MergeManagerImpl.h
  core/src/db/wal/WalFile.h
  core/src/db/wal/WalManager.cpp
  core/src/db/wal/WalManager.h
  core/src/db/wal/WalOperationCodec.cpp
  core/src/scheduler/job/BuildIndexJob.h
  core/src/scheduler/task/BuildIndexTask.cpp
  core/src/segment/Segment.cpp
  core/src/segment/Segment.h
  core/src/segment/SegmentWriter.cpp
  core/src/server/DBWrapper.cpp
  core/src/server/ValidationUtil.cpp
  core/unittest/db/test_db.cpp
  core/unittest/db/test_wal.cpp
  core/unittest/db/utils.cpp
Labels: automerge

#3462 [skip ci] update cron time on master
  ci/jenkins/Jenkinsfile
Labels: automerge

#3456 fix the data type of crc32c
  core/src/storage/ExtraFileInfo.cpp
  core/src/storage/ExtraFileInfo.h
  core/src/storage/ExtraFileInfoTest.cpp
Labels: automerge

#3458 stop AssertAnns in test_rhnsw_flat because of occasionally failure
  core/src/index/unittest/test_rhnsw_flat.cpp
Labels: automerge

#3471 [skip ci] update shards install cmd
  .jenkins/modules/DevTest/MishardsDevTest.groovy
Labels: automerge

#3470 [skip ci] update shards install cmd
  ci/jenkins/step/shardsDevNightlyTest.groovy
Labels: automerge

#3468 #3459 Index metric type SUBSTRUCTURE does not match index type BIN_FLAT
  core/src/server/ValidationUtil.cpp
  tests/milvus_python_test/test_index.py
Labels: automerge

#3467 fix hnswsq index bug
  core/conf/milvus.template
  core/src/codecs/VectorIndexFormat.cpp
  core/src/db/Constants.h
  core/src/db/SnapshotUtils.cpp
  core/src/db/Types.h
  core/src/db/Utils.cpp
  core/src/db/Utils.h
  core/src/db/engine/ExecutionEngineImpl.cpp
  core/src/index/knowhere/knowhere/index/vector_index/VecIndex.h
  core/src/segment/SegmentReader.cpp
  core/src/segment/SegmentWriter.cpp
  core/src/server/delivery/request/DescribeIndexReq.cpp
  sdk/examples/simple/src/ClientTest.cpp
  tests/milvus_python_test/collection/test_create_collection.py
Labels: automerge

#3476 Fix no degub and info log generated after server started #3406
  CHANGELOG.md
  core/src/log/LogMgr.cpp
Labels: automerge

#3461 merge coverage.sh with run_unittest.sh
  .github/workflows/core.yml
  .jenkins/modules/Coverage/Coverage.groovy
  .jenkins/modules/Unittest/Unittest.groovy
  CONTRIBUTING.md
  ci/jenkins/Jenkinsfile
  ci/scripts/coverage.sh
  ci/scripts/run_unittest.sh
  core/coverage.sh
  docker-compose.yml
Labels: automerge

#3478 #3459 Index metric type SUBSTRUCTURE does not match index type BIN_FLAT
  core/src/server/ValidationUtil.cpp
  tests/milvus_python_test/test_index.py
Labels: automerge

#3481 merge pr3467 to 0.11
  core/conf/milvus.template
  core/src/codecs/VectorIndexFormat.cpp
  core/src/db/Constants.h
  core/src/db/SnapshotUtils.cpp
  core/src/db/Types.h
  core/src/db/Utils.cpp
  core/src/db/Utils.h
  core/src/db/engine/ExecutionEngineImpl.cpp
  core/src/index/knowhere/knowhere/index/vector_index/VecIndex.h
  core/src/segment/SegmentReader.cpp
  core/src/segment/SegmentWriter.cpp
  core/src/server/delivery/request/DescribeIndexReq.cpp
  sdk/examples/simple/src/ClientTest.cpp
  tests/milvus_python_test/collection/test_create_collection.py
Labels: automerge

#3483 refine segment reader/writer
  core/src/codecs/BlockFormat.cpp
  core/src/codecs/BlockFormat.h
  core/src/codecs/DeletedDocsFormat.cpp
  core/src/codecs/DeletedDocsFormat.h
  core/src/codecs/IdBloomFilterFormat.cpp
  core/src/codecs/IdBloomFilterFormat.h
  core/src/codecs/StructuredIndexFormat.cpp
  core/src/codecs/StructuredIndexFormat.h
  core/src/codecs/VectorCompressFormat.cpp
  core/src/codecs/VectorCompressFormat.h
  core/src/codecs/VectorIndexFormat.cpp
  core/src/codecs/VectorIndexFormat.h
  core/src/index/knowhere/knowhere/index/vector_index/VecIndex.h
  core/src/segment/SegmentReader.cpp
  core/src/segment/SegmentWriter.cpp
Labels: automerge

#3484 refine segment reader/writer
  core/src/codecs/BlockFormat.cpp
  core/src/codecs/BlockFormat.h
  core/src/codecs/DeletedDocsFormat.cpp
  core/src/codecs/DeletedDocsFormat.h
  core/src/codecs/IdBloomFilterFormat.cpp
  core/src/codecs/IdBloomFilterFormat.h
  core/src/codecs/StructuredIndexFormat.cpp
  core/src/codecs/StructuredIndexFormat.h
  core/src/codecs/VectorCompressFormat.cpp
  core/src/codecs/VectorCompressFormat.h
  core/src/codecs/VectorIndexFormat.cpp
  core/src/codecs/VectorIndexFormat.h
  core/src/index/knowhere/knowhere/index/vector_index/VecIndex.h
  core/src/segment/SegmentReader.cpp
  core/src/segment/SegmentWriter.cpp
Labels: automerge

#3474 ListIDInSegment get wrong result when delete more than one ids
  CHANGELOG.md
  core/src/db/DBImpl.cpp
Labels: automerge

#3495 validate compact threshold
  core/src/server/ValidationUtil.cpp
  core/src/server/ValidationUtil.h
  core/src/server/delivery/request/CompactReq.cpp
Labels: automerge

#3496 validate compact threshold
  core/src/server/ValidationUtil.cpp
  core/src/server/ValidationUtil.h
  core/src/server/delivery/request/CompactReq.cpp
Labels: automerge

#3473 Restrict the content of partition_tag
  CHANGELOG.md
  core/src/server/ValidationUtil.cpp
  tests/milvus_python_test/test_partition.py
Labels: automerge

#3497 allow modify build_index_threshold
  core/src/config/ConfigMgr.cpp
Labels: automerge

#3508 Allow more choices for the parameter ‘m’ of CPU IVF_PQ #3254
  core/src/db/engine/ExecutionEngineImpl.cpp
  core/src/db/engine/ExecutionEngineImpl.h
  core/src/index/knowhere/knowhere/index/vector_index/ConfAdapter.cpp
  core/src/index/knowhere/knowhere/index/vector_index/ConfAdapter.h
  core/src/index/knowhere/knowhere/index/vector_index/IndexIVFPQ.cpp
  core/src/index/knowhere/knowhere/index/vector_index/helpers/Cloner.cpp
  core/src/index/unittest/CMakeLists.txt
  core/src/server/ValidationUtil.cpp
Labels: automerge

#3489 Add kmeans++ algorithm to improve the clustering effect
  core/src/index/thirdparty/faiss/Clustering.cpp
  core/src/index/thirdparty/faiss/Clustering.h
Labels: automerge

#3498 allow modify build_index_threshold
  core/src/config/ConfigMgr.cpp
Labels: automerge

#3512 [skip ci] add case with invalid threshold and update mainclass
  tests/milvus-java-test/src/main/java/com/MainClass.java
  tests/milvus-java-test/src/main/java/com/TestCompact.java
Labels: automerge

#3513 [skip ci] update restart policy to Never
  .jenkins/modules/DevTest/SingleNodeDevTest.groovy
Labels: automerge

#3517 add cases
  .jenkins/modules/DevTest/SingleNodeDevTest.groovy
  tests/milvus_python_test/collection/test_create_collection.py
  tests/milvus_python_test/collection/test_drop_collection.py
  tests/milvus_python_test/entity/test_get_entity_by_id.py
  tests/milvus_python_test/entity/test_search.py
  tests/milvus_python_test/test_compact.py
  tests/milvus_python_test/utils.py
Labels: automerge

#3519 add clustering configuration item
  core/src/config/ConfigMgr.cpp
  core/src/config/ServerConfig.h
  core/src/index/thirdparty/faiss/Clustering.cpp
  core/src/index/thirdparty/faiss/Clustering.h
  core/src/server/DBWrapper.cpp
Labels: automerge

#3504 Normalize http method in web sever
  CHANGELOG.md
  core/src/server/web_impl/controller/WebController.hpp
  core/src/server/web_impl/handler/WebRequestHandler.cpp
  core/src/server/web_impl/handler/WebRequestHandler.h
  core/unittest/db/test_db.cpp
  core/unittest/server/test_web.cpp
Labels: automerge

#3523 #3472 fix the crash caused by Task::label() is null
  core/src/codecs/DeletedDocsFormat.cpp
  core/src/scheduler/resource/Resource.cpp
  core/src/scheduler/task/FinishedTask.cpp
  core/src/scheduler/task/FinishedTask.h
Labels: automerge

#3526 fix only fetal log file is created error on 0.11.0 #3406
  core/src/log/LogMgr.cpp
Labels: automerge
