Repository milvus-io/milvus, pull requests merged in 2020-04, with the labels that each got.

#1809 Caiyd 1655 gpu ivfflat delete
  CHANGELOG.md
  core/src/index/knowhere/knowhere/index/vector_index/gpu/IndexGPUIVF.cpp
  core/src/index/thirdparty/faiss/gpu/GpuIndexIVFPQ.cu
  core/src/index/thirdparty/faiss/gpu/GpuIndexIVFScalarQuantizer.cu
  core/src/index/thirdparty/faiss/gpu/impl/IVFFlat.cu
  core/src/index/thirdparty/faiss/gpu/impl/IVFFlatScan.cu
  core/src/index/thirdparty/faiss/gpu/impl/IVFFlatScan.cuh
  core/src/index/thirdparty/faiss/gpu/impl/IVFPQ.cu
  core/src/index/thirdparty/faiss/gpu/impl/IVFPQ.cuh
  core/src/index/thirdparty/faiss/gpu/impl/IVFUtils.cuh
  core/src/index/thirdparty/faiss/gpu/impl/IVFUtilsSelect1.cu
  core/src/index/thirdparty/faiss/gpu/impl/IVFUtilsSelect2.cu
  core/src/index/thirdparty/faiss/gpu/impl/PQScanMultiPassNoPrecomputed.cu
  core/src/index/thirdparty/faiss/gpu/impl/PQScanMultiPassNoPrecomputed.cuh
  core/src/index/thirdparty/faiss/gpu/impl/PQScanMultiPassPrecomputed.cu
  core/src/index/thirdparty/faiss/gpu/impl/PQScanMultiPassPrecomputed.cuh
  core/src/index/thirdparty/faiss/makefile.inc.in
  core/src/index/unittest/test_ivf.cpp
Labels: type/new-feature

#1830 #1659 Support gpu ivfsq8h deletion
  core/src/index/thirdparty/faiss/gpu/GpuIndexIVFSQHybrid.cu
  core/src/index/unittest/test_ivf.cpp
  core/src/server/delivery/request/DeleteByIDRequest.cpp
Labels: type/new-feature

#1846 1845 no UT log
  core/CMakeLists.txt
  core/src/index/CMakeLists.txt
Labels: type/enhancement

#1850 Reorganize readme (update cn & en; delete jp)
  README.md
  README_CN.md
  README_JP.md
Labels: Documentation

#1839 #1849 Support NSG Deletion
  CHANGELOG.md
  core/src/index/knowhere/knowhere/index/vector_index/IndexNSG.cpp
  core/src/index/knowhere/knowhere/index/vector_index/impl/nsg/NSG.cpp
  core/src/index/knowhere/knowhere/index/vector_index/impl/nsg/NSG.h
  core/src/index/unittest/test_nsg/test_nsg.cpp
  core/src/server/delivery/request/DeleteByIDRequest.cpp
Labels: type/new-feature

#1860 Caiyd 1858 disable s3 build
  CHANGELOG.md
  core/cmake/DefineOptions.cmake
  core/src/CMakeLists.txt
  core/src/config/Config.cpp
  core/src/db/Utils.cpp
  core/src/server/Server.cpp
  core/unittest/CMakeLists.txt
Labels: type/enhancement

#1874 #1873 fix index file serialize to incorrect path
  CHANGELOG.md
  core/src/codecs/VectorIndexFormat.h
  core/src/codecs/default/DefaultVectorIndexFormat.cpp
  core/src/codecs/default/DefaultVectorIndexFormat.h
  core/src/db/engine/ExecutionEngineImpl.cpp
  core/src/index/knowhere/knowhere/index/vector_index/ConfAdapterMgr.cpp
  core/src/index/knowhere/knowhere/index/vector_index/VecIndexFactory.cpp
  core/src/segment/SegmentReader.cpp
  core/src/segment/SegmentReader.h
  core/src/segment/SegmentWriter.cpp
  core/src/segment/SegmentWriter.h
  core/src/segment/VectorIndex.h
Labels: Bug

#1878 [skip ci] Fix incorrect information in http readme (fix #1812)
  CHANGELOG.md
  core/src/server/web_impl/README.md
Labels: Bug, Documentation, P2

#1877 code revert
  core/src/index/knowhere/knowhere/index/vector_index/VecIndexFactory.cpp
Labels: Bug

#1892 Caiyd 1881 bad alloc
  CHANGELOG.md
  core/src/codecs/default/DefaultVectorIndexFormat.cpp
  core/src/storage/IOReader.h
  core/src/storage/IOWriter.h
  core/src/storage/disk/DiskIOReader.cpp
  core/src/storage/disk/DiskIOReader.h
  core/src/storage/disk/DiskIOWriter.cpp
  core/src/storage/disk/DiskIOWriter.h
  core/src/storage/s3/S3IOReader.cpp
  core/src/storage/s3/S3IOReader.h
  core/src/storage/s3/S3IOWriter.cpp
  core/src/storage/s3/S3IOWriter.h
  core/unittest/CMakeLists.txt
  core/unittest/storage/CMakeLists.txt
  core/unittest/storage/test_disk.cpp
Labels: Bug

#1889 Caiyd 1885 optimize knowhere ut
  CHANGELOG.md
  core/src/index/knowhere/knowhere/index/vector_index/helpers/FaissIO.h
  core/src/index/unittest/CMakeLists.txt
  core/src/index/unittest/Helper.h
  core/src/index/unittest/test_binaryidmap.cpp
  core/src/index/unittest/test_binaryivf.cpp
  core/src/index/unittest/test_nsg.cpp
  core/src/index/unittest/test_nsg/CMakeLists.txt
  core/src/index/unittest/utils.cpp
  core/src/index/unittest/utils.h
Labels: type/enhancement

#1908 [skip ci] Add auto-merge action
  .github/workflows/automerge.yml
Labels: automerge

#1904 Change to 0.8.0 and rename from preload_table to preload_collection
  CHANGELOG.md
  ci/jenkins/step/singleDevNightlyTest.groovy
  ci/jenkins/step/singleDevTest.groovy
  core/CMakeLists.txt
  core/conf/demo/server_config.yaml
  core/conf/server_cpu_config.template
  core/conf/server_gpu_config.template
  core/src/config/Config.cpp
  core/src/config/Config.h
  core/src/server/DBWrapper.cpp
  core/src/server/DBWrapper.h
  core/src/server/web_impl/README.md
  core/unittest/server/test_config.cpp
  core/unittest/server/test_web.cpp
  core/unittest/server/utils.cpp
  sdk/grpc/ClientProxy.cpp
  tests/milvus_benchmark/conf/server_config.yaml
  tests/milvus_benchmark/conf/server_config.yaml.cpu
  tests/milvus_benchmark/conf/server_config.yaml.multi
  tests/milvus_benchmark/conf/server_config.yaml.single
  tests/milvus_python_test/test_config.py
  tests/milvus_python_test/test_ping.py
Labels: automerge

#1915 #1914: Partition max size should be 4096
  core/src/server/delivery/request/CreatePartitionRequest.cpp
Labels: type/enhancement

#1926 Caiyd 1883 fix rw
  CHANGELOG.md
  core/src/codecs/default/DefaultVectorsFormat.cpp
  core/src/codecs/default/DefaultVectorsFormat.h
  core/src/utils/Error.h
Labels: Bug

#1958 Mishards k8s fix
  shards/Makefile
  shards/discovery/plugins/kubernetes_provider.py
  shards/kubernetes_demo/milvus_stateful_servers.yaml
  shards/kubernetes_demo/mishards_auxiliary.yaml
  shards/kubernetes_demo/mishards_configmap.yaml
  shards/kubernetes_demo/mishards_data_pvc.yaml
  shards/kubernetes_demo/mishards_proxy.yaml
  shards/kubernetes_demo/mishards_rbac.yaml
  shards/kubernetes_demo/mishards_stateful_servers.yaml
  shards/kubernetes_demo/mishards_write_servers.yaml
  shards/kubernetes_demo/start.sh
  shards/mishards/topology.py
Labels: P2, S2

#1963 [skip ci] update change log
  CHANGELOG.md
Labels: automerge

#1983 [skip ci] update mergify
  .mergify/config.yml
Labels: automerge

#1986 code optimize
  core/src/db/Constants.h
  core/src/db/DBImpl.cpp
  core/src/db/Options.h
  core/src/db/insert/MemManagerImpl.cpp
  core/src/db/meta/MetaTypes.h
  core/src/db/meta/MySQLMetaImpl.cpp
  core/src/db/meta/SqliteMetaImpl.cpp
  core/unittest/db/test_db.cpp
  core/unittest/db/test_db_mysql.cpp
  core/unittest/db/test_delete.cpp
  core/unittest/db/test_meta.cpp
  core/unittest/db/test_meta_mysql.cpp
Labels: automerge

#1979 replace metaOptions with meta_options
  core/src/db/meta/MetaFactory.cpp
  core/src/db/meta/MetaFactory.h
Labels: automerge

#1989 use TimeRecorder instead of chrono
  core/src/db/insert/MemTable.cpp
Labels: automerge

#1994 move const char* to .cpp file
  core/src/config/Config.cpp
  core/src/config/Config.h
Labels: type/enhancement

#1984 Automerge1
  .github/workflows/automerge.yml
  CHANGELOG.md
  core/build.sh
  core/src/main.cpp
  core/src/server/grpc_impl/GrpcRequestHandler.cpp
  core/src/server/grpc_impl/GrpcRequestHandler.h
  sdk/build.sh
Labels: automerge

#1996 Modify data type in CommonUtil.cpp
  core/src/utils/CommonUtil.cpp
Labels: automerge

#1968 Set case level
  ci/jenkins/Jenkinsfile
  tests/milvus_python_test/conftest.py
  tests/milvus_python_test/requirements.txt
  tests/milvus_python_test/test_add_vectors.py
  tests/milvus_python_test/test_collection.py
  tests/milvus_python_test/test_collection_count.py
  tests/milvus_python_test/test_connect.py
  tests/milvus_python_test/test_index.py
  tests/milvus_python_test/test_partition.py
  tests/milvus_python_test/test_search_vectors.py
  tests/milvus_python_test/utils.py
Labels: automerge

#2004 keep bitset naming consistent
  core/src/index/thirdparty/faiss/gpu/impl/L2Select.cu
  core/src/index/thirdparty/faiss/gpu/utils/BlockSelectKernel.cuh
Labels: automerge

#2010 [skip ci] Update README.md
  README.md
Labels: automerge

#2003 create index notify
  core/src/db/DBImpl.cpp
  core/src/db/DBImpl.h
Labels: automerge

#2008 Caiyd 1965 unify metric cal
  CHANGELOG.md
  core/src/index/knowhere/knowhere/index/vector_index/IndexAnnoy.cpp
  core/src/index/knowhere/knowhere/index/vector_index/impl/nsg/Distance.cpp
  core/src/index/thirdparty/annoy/src/annoylib.h
  core/src/index/thirdparty/faiss/FaissHook.cpp
  core/src/index/thirdparty/hnswlib/space_ip.h
  core/src/index/thirdparty/hnswlib/space_l2.h
  core/src/index/unittest/CMakeLists.txt
  core/src/index/unittest/metric_alg_benchmark/CMakeLists.txt
  core/src/index/unittest/metric_alg_benchmark/metric_benchmark_test.cpp
Labels: type/new-feature

#2000 Update timeout strategy in CI
  ci/jenkins/Jenkinsfile
  ci/jenkins/step/build.groovy
  ci/jenkins/step/coverage.groovy
  ci/jenkins/step/shardsDevNightlyTest.groovy
  ci/jenkins/step/singleDevNightlyTest.groovy
  ci/jenkins/step/singleDevTest.groovy
  ci/jenkins/step/unittest.groovy
Labels: automerge

#2021 Context-head-file
  core/src/server/grpc_impl/GrpcRequestHandler.h
Labels: automerge

#2016 rename table_info into collection_info
  core/src/server/delivery/hybrid_request/CreateHybridCollectionRequest.cpp
Labels: automerge

#2020 use #include "segment/SegmentWriter.h" instead
  core/src/db/insert/MemTableFile.h
Labels: automerge

#2022 add reference to bitset
  core/src/index/thirdparty/annoy/src/annoylib.h
Labels: automerge

#2026 Fix unused code and clarify params
  core/src/index/unittest/test_idmap.cpp
  core/src/index/unittest/test_nsg.cpp
Labels: automerge

#2027 Move NULL to nullptr
  core/src/index/thirdparty/SPTAG/AnnService/inc/Core/Common/CommonUtils.h
  core/src/index/thirdparty/annoy/src/annoygomodule.h
  core/src/index/thirdparty/annoy/src/annoylib.h
  core/src/index/thirdparty/annoy/src/annoyluamodule.cc
  core/src/index/thirdparty/annoy/src/annoymodule.cc
  core/src/index/thirdparty/faiss/gpu/utils/DeviceMemory.cpp
  core/src/index/unittest/faiss_benchmark/faiss_benchmark_test.cpp
  core/src/index/unittest/faiss_benchmark/faiss_bitset_test.cpp
  core/src/index/unittest/test_annoy.cpp
  core/src/index/unittest/test_hnsw.cpp
  core/src/index/unittest/test_knowhere.cpp
  core/src/index/unittest/test_wrapper.cpp
Labels: automerge

#2049 fix case bug
  tests/milvus_python_test/test_add_vectors.py
  tests/milvus_python_test/test_collection.py
  tests/milvus_python_test/test_collection_count.py
  tests/milvus_python_test/test_flush.py
  tests/milvus_python_test/test_index.py
Labels: automerge

#2065 warn when use sqlite as metadata management
  CHANGELOG.md
  core/src/db/meta/SqliteMetaImpl.cpp
Labels: automerge, type/enhancement

#2071 add log 4 annoy if index has been built when BuildAll interface invoked
  core/src/index/knowhere/knowhere/index/vector_index/IndexAnnoy.cpp
Labels: automerge

#2067 rename optimizer to selector
  core/src/CMakeLists.txt
  core/src/scheduler/JobMgr.cpp
  core/src/scheduler/SchedInst.h
  core/src/scheduler/selector/BuildIndexPass.cpp
  core/src/scheduler/selector/BuildIndexPass.h
  core/src/scheduler/selector/FaissFlatPass.cpp
  core/src/scheduler/selector/FaissFlatPass.h
  core/src/scheduler/selector/FaissIVFFlatPass.cpp
  core/src/scheduler/selector/FaissIVFFlatPass.h
  core/src/scheduler/selector/FaissIVFPQPass.cpp
  core/src/scheduler/selector/FaissIVFPQPass.h
  core/src/scheduler/selector/FaissIVFSQ8HPass.cpp
  core/src/scheduler/selector/FaissIVFSQ8HPass.h
  core/src/scheduler/selector/FaissIVFSQ8Pass.cpp
  core/src/scheduler/selector/FaissIVFSQ8Pass.h
  core/src/scheduler/selector/FallbackPass.cpp
  core/src/scheduler/selector/FallbackPass.h
  core/src/scheduler/selector/Optimizer.cpp
  core/src/scheduler/selector/Optimizer.h
  core/src/scheduler/selector/Pass.h
  core/unittest/CMakeLists.txt
  core/unittest/scheduler/CMakeLists.txt
  core/unittest/scheduler/test_selector.cpp
Labels: automerge

#2074 #2073 Fix CheckDBConfigBackendUrl error message
  CHANGELOG.md
  core/src/config/Config.cpp
Labels: automerge

#2077 #2076 CheckMetricConfigAddress error message
  CHANGELOG.md
  core/src/config/Config.cpp
Labels: automerge

#2109 Values of type 'const size_t' may not fit into the receiver type 'int'
  core/src/index/thirdparty/annoy/src/annoylib.h
Labels: automerge

#2035 Move http query parser
  core/src/server/web_impl/handler/WebRequestHandler.cpp
  core/src/server/web_impl/handler/WebRequestHandler.h
  core/src/server/web_impl/utils/Util.cpp
  core/src/server/web_impl/utils/Util.h
Labels: automerge

#2108 #1997 index file missed after compact
  CHANGELOG.md
  core/src/db/DBImpl.cpp
  core/src/server/delivery/request/SearchByIDRequest.cpp
  core/unittest/db/test_search_by_id.cpp
  sdk/examples/simple/src/ClientTest.cpp
Labels: automerge

#2055 Add cpu instruction sets check
  CHANGELOG.md
  core/src/CMakeLists.txt
  core/src/main.cpp
  core/src/server/Server.cpp
  core/src/server/init/CpuChecker.cpp
  core/src/server/init/CpuChecker.h
  core/src/utils/CommonUtil.h
  core/unittest/CMakeLists.txt
Labels: automerge, type/new-feature

#2126 rename the variable name collection_schema
  core/unittest/db/test_meta_mysql.cpp
Labels: automerge

#2060 Add instance lock
  CHANGELOG.md
  core/conf/log_config.template
  core/src/CMakeLists.txt
  core/src/main.cpp
  core/src/server/Server.cpp
  core/src/server/init/InstanceLockCheck.cpp
  core/src/server/init/InstanceLockCheck.h
  core/unittest/server/CMakeLists.txt
Labels: automerge

#2124 Caiyd 1946 cpu2gpu getres
  core/src/index/knowhere/CMakeLists.txt
  core/src/index/knowhere/knowhere/common/Log.cpp
  core/src/index/knowhere/knowhere/common/Log.h
  core/src/index/knowhere/knowhere/common/Timer.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexAnnoy.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexBinaryIVF.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexIVF.cpp
  core/src/index/knowhere/knowhere/index/vector_index/helpers/FaissGpuResourceMgr.cpp
  core/src/index/knowhere/knowhere/index/vector_index/helpers/FaissGpuResourceMgr.h
  core/src/index/knowhere/knowhere/index/vector_index/impl/nsg/NSG.cpp
  core/src/index/unittest/CMakeLists.txt
  sdk/examples/simple/src/ClientTest.cpp
Labels: Bug

#2130 When helm deploy failed, print the milvus container logs
  ci/jenkins/step/shardsDevNightlyTest.groovy
  ci/jenkins/step/singleDevNightlyTest.groovy
  ci/jenkins/step/singleDevTest.groovy
Labels: automerge

#2140 replace int with size_t
  core/src/index/thirdparty/hnswlib/bruteforce.h
Labels: automerge

#2142 Wait for helm uninstall chart
  ci/jenkins/step/shardsDevNightlyTest.groovy
  ci/jenkins/step/singleDevNightlyTest.groovy
  ci/jenkins/step/singleDevTest.groovy
Labels: automerge

#2139 delete unused file
  core/src/server/web_impl/utils/Util.cpp
  core/src/server/web_impl/utils/Util.h
Labels: automerge

#2150 merge server_cpu_config.template and server_gpu_config.template
  CHANGELOG.md
  core/CMakeLists.txt
  core/conf/server_config.template
  core/conf/server_gpu_config.template
Labels: automerge, type/enhancement

#2144 fix server start failed if wal directory exist
  CHANGELOG.md
  core/src/server/Server.cpp
Labels: automerge

#2137 Add config to switch off web server
  CHANGELOG.md
  core/cmake/ThirdPartyPackages.cmake
  core/conf/demo/server_config.yaml
  core/conf/server_config.template
  core/src/config/Config.cpp
  core/src/config/Config.h
  core/src/server/web_impl/WebServer.cpp
  core/src/server/web_impl/component/AppComponent.hpp
  core/src/utils/LogUtil.cpp
  core/unittest/server/test_web.cpp
Labels: automerge, type/new-feature

#2159 skip ubuntu-ci in regression
  ci/jenkins/Jenkinsfile
Labels: automerge

#2168 Merge config file
  CHANGELOG.md
  core/conf/server_config.template
  core/src/config/Config.cpp
  core/src/config/Config.h
  core/src/server/Server.cpp
  core/src/utils/LogUtil.cpp
  core/src/utils/LogUtil.h
  core/unittest/server/test_util.cpp
Labels: automerge

#2138 Fix failed to open file
  CHANGELOG.md
  core/src/db/DBImpl.cpp
  core/src/db/DBImpl.h
  core/src/db/IndexFailedChecker.cpp
  core/src/db/IndexFailedChecker.h
  core/src/db/OngoingFileChecker.cpp
  core/src/db/OngoingFileChecker.h
  core/src/db/Types.h
  core/src/db/insert/MemTable.cpp
  core/src/db/meta/FilesHolder.cpp
  core/src/db/meta/FilesHolder.h
  core/src/db/meta/Meta.h
  core/src/db/meta/MetaTypes.h
  core/src/db/meta/MySQLMetaImpl.cpp
  core/src/db/meta/MySQLMetaImpl.h
  core/src/db/meta/SqliteMetaImpl.cpp
  core/src/db/meta/SqliteMetaImpl.h
  core/src/metrics/SystemInfo.cpp
  core/src/metrics/prometheus/PrometheusMetrics.cpp
  core/src/server/delivery/request/HasPartitionRequest.cpp
  core/unittest/db/test_db.cpp
  core/unittest/db/test_meta.cpp
  core/unittest/db/test_meta_mysql.cpp
  core/unittest/db/test_misc.cpp
  core/unittest/db/test_search_by_id.cpp
Labels: automerge

#2157 Upgrade http thirdparty oatpp to v1.0.0 (fix #2153)
  CHANGELOG.md
  core/cmake/ThirdPartyPackages.cmake
  core/src/server/web_impl/component/AppComponent.hpp
  core/src/server/web_impl/dto/PartitionDto.hpp
  core/src/server/web_impl/dto/StatusDto.hpp
  core/src/server/web_impl/dto/TableDto.hpp
  core/thirdparty/versions.txt
Labels: automerge, type/enhancement

#2177 Fix #2175
  ci/jenkins/step/shardsDevNightlyTest.groovy
  ci/jenkins/step/singleDevNightlyTest.groovy
  ci/jenkins/step/singleDevTest.groovy
Labels: automerge

#2180 #2178 Using elkan K-Means to improve IVF
  CHANGELOG.md
  core/src/index/thirdparty/faiss/utils/distances.cpp
Labels: automerge

#2182 #1946 fix load index file CPU2GPU fail during searching
  CHANGELOG.md
  core/src/index/knowhere/knowhere/index/vector_index/helpers/FaissGpuResourceMgr.cpp
  core/src/index/knowhere/knowhere/index/vector_index/helpers/FaissGpuResourceMgr.h
Labels: automerge

#2183 remove disconnect test case
  ci/jenkins/step/build.groovy
  tests/milvus_python_test/conftest.py
  tests/milvus_python_test/test_add_vectors.py
  tests/milvus_python_test/test_collection.py
  tests/milvus_python_test/test_collection_count.py
  tests/milvus_python_test/test_connect.py
  tests/milvus_python_test/test_flush.py
  tests/milvus_python_test/test_get_vectors_by_ids.py
  tests/milvus_python_test/test_index.py
  tests/milvus_python_test/test_ping.py
  tests/milvus_python_test/test_search_by_ids.py
  tests/milvus_python_test/test_search_vectors.py
Labels: automerge

#2174 Check Storage permission
  CHANGELOG.md
  core/src/server/Server.cpp
  core/src/server/init/StorageChecker.cpp
  core/src/server/init/StorageChecker.h
  core/src/utils/LogUtil.cpp
  core/unittest/server/test_check.cpp
  core/unittest/server/test_web.cpp
Labels: P3, S3, automerge, type/enhancement

#2193 Remove connect
  tests/milvus_python_test/test_add_vectors.py
  tests/milvus_python_test/test_connect.py
  tests/milvus_python_test/test_mix.py
  tests/milvus_python_test/test_ping.py
Labels: automerge

#2191 Feisiyicl 2190 memory usage
  CHANGELOG.md
  core/src/CMakeLists.txt
  core/src/index/knowhere/knowhere/index/vector_index/IndexIVF.cpp
  core/src/index/knowhere/knowhere/index/vector_index/helpers/FaissGpuResourceMgr.cpp
  core/src/index/thirdparty/faiss/InvertedLists.cpp
  core/src/server/delivery/hybrid_request/HybridSearchRequest.cpp
  core/src/server/delivery/hybrid_request/InsertEntityRequest.cpp
  core/src/server/delivery/request/InsertRequest.cpp
  core/src/server/delivery/request/SearchByIDRequest.cpp
  core/src/server/delivery/request/SearchRequest.cpp
  core/src/utils/CommonUtil.cpp
  core/src/utils/CommonUtil.h
Labels: automerge, type/enhancement

#2192 Log with request id
  core/src/server/context/Context.h
  core/src/server/grpc_impl/GrpcRequestHandler.cpp
Labels: automerge

#2195 add head file to fix two build warnings
  core/src/index/thirdparty/hnswlib/hnswlib.h
Labels: automerge

#2198 Fix fail to access WAL storage path (#2196)
  CHANGELOG.md
  core/src/server/init/StorageChecker.cpp
Labels: Bug, P1, S1, automerge

#2204 Error out when index SQ8H run in CPU mode
  CHANGELOG.md
  core/CMakeLists.txt
  core/build.sh
  core/cmake/DefineOptions.cmake
  core/src/CMakeLists.txt
  core/src/db/DBImpl.cpp
  core/src/db/engine/ExecutionEngineImpl.cpp
Labels: Bug, automerge
