Repository milvus-io/milvus, pull requests merged in 2020-02, with the labels that each got.

#1121 Set default sending to Milvus Dev mail group
  ci/jenkins/Jenkinsfile
Labels: type/enhancement

#1131 Support hnsw
  core/src/db/engine/ExecutionEngine.h
  core/src/db/engine/ExecutionEngineImpl.cpp
  core/src/index/knowhere/CMakeLists.txt
  core/src/index/knowhere/knowhere/index/vector_index/IndexHNSW.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexHNSW.h
  core/src/index/knowhere/knowhere/index/vector_index/helpers/FaissIO.h
  core/src/index/knowhere/knowhere/index/vector_index/helpers/IndexParameter.h
  core/src/index/thirdparty/hnswlib/bruteforce.h
  core/src/index/thirdparty/hnswlib/hnswalg.h
  core/src/index/thirdparty/hnswlib/hnswlib.h
  core/src/index/thirdparty/hnswlib/space_ip.h
  core/src/index/thirdparty/hnswlib/space_l2.h
  core/src/index/thirdparty/hnswlib/visited_list_pool.h
  core/src/wrapper/ConfAdapter.cpp
  core/src/wrapper/ConfAdapter.h
  core/src/wrapper/ConfAdapterMgr.cpp
  core/src/wrapper/VecIndex.cpp
  core/src/wrapper/VecIndex.h
Labels: type/new-feature

#1100 Add doc for the RESTful API / Update contributor number in Milvus readme
  README.md
  core/src/server/web_impl/README.md
Labels: type/docs

#1117 update error message when creating IVFSQ8H index without GPU resources
  CHANGELOG.md
  core/src/db/DBImpl.cpp
  core/src/db/IndexFailedChecker.cpp
  core/src/db/IndexFailedChecker.h
  core/src/db/OngoingFileChecker.h
  core/src/db/Types.h
  core/unittest/db/test_misc.cpp
Labels: type/enhancement

#1104 [skip ci] Update README
  README.md
Labels: type/docs

#1163 Update the email address in CODE_OF_CONDUCT.md per LFAI request
  CODE_OF_CONDUCT.md
Labels: type/docs

#1116 Support run dev test with http handler in python SDK
  CHANGELOG.md
  core/src/server/web_impl/controller/WebController.hpp
  core/src/server/web_impl/dto/CmdDto.hpp
  core/src/server/web_impl/dto/VectorDto.hpp
  core/src/server/web_impl/handler/WebRequestHandler.cpp
  core/src/server/web_impl/handler/WebRequestHandler.h
  core/unittest/server/test_web.cpp
  tests/milvus_python_test/test_add_vectors.py
  tests/milvus_python_test/test_connect.py
  tests/milvus_python_test/test_index.py
  tests/milvus_python_test/test_mix.py
  tests/milvus_python_test/test_search_vectors.py
  tests/milvus_python_test/test_table.py
  tests/milvus_python_test/test_table_count.py
Labels: type/bug, type/enhancement

#1162 Fix #1140
  CHANGELOG.md
  core/src/index/knowhere/knowhere/index/vector_index/IndexHNSW.cpp
  sdk/include/MilvusApi.h
Labels: type/bug

#1175 Update INSTALL.md
  INSTALL.md
Labels: type/docs

#1206 Add LFAI mailing lists to the readme
  README.md
Labels: type/docs

#1219 Add design.md to store links to design docs
  README.md
  design.md
Labels: type/docs

#1225 Add troubleshooting info about libmysqlpp.so.3 error
  INSTALL.md
Labels: type/docs

#1233 Add link to Milvus node.js client to the readme
  README.md
Labels: type/docs

#1258 Add Jenkins master badge.
  README.md
Labels: type/docs

#1265 Update INSTALL.md to fix an indentation issue
  INSTALL.md
Labels: type/docs

#1267 Add Compact Test Case
  tests/milvus_python_test/requirements.txt
  tests/milvus_python_test/test_compact.py
Labels: Awaiting dev feedback

#1274 Add troubleshooting information for INSTALL.md and enhance readability
  INSTALL.md
Labels: type/docs

#1292 Create COMMUNITY.md
  COMMUNITY.md
Labels: type/docs

#1283 Update INSTALL.md
  INSTALL.md
Labels: type/docs

#1305 Update CN/JPN readme per the latest EN readme
  CHANGELOG.md
  README_CN.md
  README_JP.md
Labels: type/docs

#1321 remove debug logging from faiss
  CHANGELOG.md
  core/src/index/thirdparty/faiss/gpu/impl/IVFFlat.cu
Labels: type/enhancement

#1342 Update badges for EN/CN/JP readme
  CHANGELOG.md
  README.md
  README_CN.md
  README_JP.md
Labels: type/docs

#1357 Disable filtering for specific paths in Jenkins CI
  ci/jenkins/Jenkinsfile
  ci/jenkins/pod/milvus-cpu-version-centos7-build-env-pod.yaml
  ci/jenkins/pod/milvus-gpu-version-centos7-build-env-pod.yaml
  ci/jenkins/step/singleDevNightlyTest.groovy
Labels: type/bug

#1378 Add Git as a requirement for compilation
  CHANGELOG.md
  INSTALL.md
Labels: type/docs

#1389 In INSTALL.md, compilation in docker images should be confined to the Linux platform
  CHANGELOG.md
  INSTALL.md
Labels: type/docs

#1404 #1234 do service check when Milvus startup
  CHANGELOG.md
  core/src/server/Server.cpp
  core/src/server/Server.h
  core/src/storage/s3/S3ClientWrapper.cpp
Labels: type/enhancement

#1383 support ip
  CHANGELOG.md
  core/src/index/knowhere/knowhere/index/vector_index/IndexHNSW.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexHNSW.h
  core/src/index/thirdparty/hnswlib/hnswalg.h
  core/src/wrapper/ConfAdapter.cpp
  core/src/wrapper/ConfAdapter.h
Labels: type/bug

#1195 support avx512
  CHANGELOG.md
  core/src/index/thirdparty/faiss/FaissHook.cpp
  core/src/index/thirdparty/faiss/FaissHook.h
  core/src/index/thirdparty/faiss/Index.cpp
  core/src/index/thirdparty/faiss/Index2Layer.cpp
  core/src/index/thirdparty/faiss/IndexFlat.cpp
  core/src/index/thirdparty/faiss/IndexHNSW.cpp
  core/src/index/thirdparty/faiss/IndexHNSW.h
  core/src/index/thirdparty/faiss/IndexIVFFlat.cpp
  core/src/index/thirdparty/faiss/IndexIVFPQ.cpp
  core/src/index/thirdparty/faiss/IndexIVFPQR.cpp
  core/src/index/thirdparty/faiss/IndexSQHybrid.cpp
  core/src/index/thirdparty/faiss/IndexSQHybrid.h
  core/src/index/thirdparty/faiss/IndexScalarQuantizer.cpp
  core/src/index/thirdparty/faiss/IndexScalarQuantizer.h
  core/src/index/thirdparty/faiss/Makefile
  core/src/index/thirdparty/faiss/VectorTransform.cpp
  core/src/index/thirdparty/faiss/gpu/GpuIndexIVFSQHybrid.cu
  core/src/index/thirdparty/faiss/gpu/GpuIndexIVFSQHybrid.h
  core/src/index/thirdparty/faiss/gpu/GpuIndexIVFScalarQuantizer.cu
  core/src/index/thirdparty/faiss/gpu/GpuIndexIVFScalarQuantizer.h
  core/src/index/thirdparty/faiss/gpu/impl/GpuScalarQuantizer.cuh
  core/src/index/thirdparty/faiss/gpu/impl/IVFAppend.cu
  core/src/index/thirdparty/faiss/gpu/impl/IVFFlatScan.cu
  core/src/index/thirdparty/faiss/impl/PolysemousTraining.cpp
  core/src/index/thirdparty/faiss/impl/ScalarQuantizer.cpp
  core/src/index/thirdparty/faiss/impl/ScalarQuantizer.h
  core/src/index/thirdparty/faiss/impl/ScalarQuantizerCodec.h
  core/src/index/thirdparty/faiss/impl/ScalarQuantizerCodec_avx512.h
  core/src/index/thirdparty/faiss/impl/ScalarQuantizerDC.cpp
  core/src/index/thirdparty/faiss/impl/ScalarQuantizerDC.h
  core/src/index/thirdparty/faiss/impl/ScalarQuantizerDC_avx512.cpp
  core/src/index/thirdparty/faiss/impl/ScalarQuantizerDC_avx512.h
  core/src/index/thirdparty/faiss/impl/ScalarQuantizerOp.cpp
  core/src/index/thirdparty/faiss/impl/ScalarQuantizerOp.h
  core/src/index/thirdparty/faiss/impl/lattice_Zn.cpp
  core/src/index/thirdparty/faiss/index_factory.cpp
  core/src/index/thirdparty/faiss/utils/distances.cpp
  core/src/index/thirdparty/faiss/utils/distances.h
  core/src/index/thirdparty/faiss/utils/distances_avx512.h
  core/src/index/thirdparty/faiss/utils/distances_simd.cpp
  core/src/index/thirdparty/faiss/utils/distances_simd_avx512.cpp
  core/src/index/thirdparty/faiss/utils/extra_distances.cpp
  core/src/index/thirdparty/faiss/utils/instruction_set.h
  core/src/index/unittest/CMakeLists.txt
  core/src/index/unittest/test_instructionset.cpp
  core/src/server/Config.cpp
  core/src/server/Config.h
  core/src/wrapper/KnowhereResource.cpp
  core/unittest/server/test_config.cpp
Labels: type/enhancement

#1453 Increase memory limit in Jenkins CI
  ci/jenkins/pod/milvus-cpu-version-centos7-build-env-pod.yaml
  ci/jenkins/pod/milvus-cpu-version-ubuntu18.04-build-env-pod.yaml
  ci/jenkins/pod/milvus-gpu-version-centos7-build-env-pod.yaml
  ci/jenkins/pod/milvus-gpu-version-ubuntu18.04-build-env-pod.yaml
  ci/scripts/build.sh
Labels: type/enhancement
