Repository milvus-io/milvus, pull requests merged in 2020-10, with the labels that each got.

#3913 refine DBImpl::Query code
  core/src/db/DBImpl.cpp
  core/src/db/SnapshotHandlers.cpp
  core/src/db/SnapshotHandlers.h
  core/src/db/SnapshotUtils.cpp
  core/src/db/SnapshotVisitor.cpp
  core/src/db/SnapshotVisitor.h
Labels: PR | automerge, PR | hotfix

#3925 fix pq distance calculation outofrange according to faiss suggests
  core/src/index/thirdparty/faiss/gpu/impl/PQCodeDistances-inl.cuh
Labels: PR | automerge, PR | hotfix

#3928 fix build index log error
  core/src/db/engine/ExecutionEngineImpl.cpp
  core/src/segment/SegmentReader.cpp
  core/src/segment/SegmentWriter.cpp
  core/src/server/delivery/request/CreateIndexReq.cpp
Labels: PR | automerge, PR | hotfix

#3939 Fix build bug
  core/src/index/thirdparty/faiss/gpu/impl/PQCodeDistances-inl.cuh
Labels: PR | hotfix

#3914 Update README.md
  README.md
Labels: PR | automerge, PR | skip-ci

#3926 Params in Restful-api is different from the params in other SDKs
  CHANGELOG.md
  core/src/server/web_impl/README.md
  core/src/server/web_impl/controller/WebController.hpp
  core/src/server/web_impl/handler/WebRequestHandler.cpp
  core/src/server/web_impl/handler/WebRequestHandler.h
  core/unittest/server/test_web.cpp
  sdk/examples/simple/src/ClientTest.cpp
Labels: PR | automerge, PR | hotfix

#3941 [skip ci] update ci/jenkinsfile to 0.10.4
  ci/jenkins/Jenkinsfile
Labels: PR | automerge, PR | skip-ci

#3940 fix wal bug for delete entity
  core/src/db/insert/MemCollection.cpp
  core/src/db/insert/MemCollection.h
  core/src/db/wal/WalManager.cpp
  core/src/db/wal/WalManager.h
  core/unittest/db/test_wal.cpp
Labels: PR | automerge, PR | hotfix

#3932 improve GetEntityByID performance
  core/src/codecs/BlockFormat.cpp
  core/src/codecs/DeletedDocsFormat.cpp
  core/src/codecs/IdBloomFilterFormat.cpp
  core/src/codecs/StructuredIndexFormat.cpp
  core/src/codecs/VectorCompressFormat.cpp
  core/src/codecs/VectorIndexFormat.cpp
  core/src/segment/SegmentReader.cpp
  core/src/segment/SegmentWriter.cpp
  core/unittest/db/test_db.cpp
Labels: PR | automerge, PR | hotfix

#3944 improve file read speed
  core/src/codecs/BlockFormat.cpp
  core/src/codecs/DeletedDocsFormat.cpp
  core/src/codecs/ExtraFileInfo.cpp
  core/src/codecs/ExtraFileInfo.h
  core/src/codecs/ExtraFileInfoTest.cpp
  core/src/codecs/StructuredIndexFormat.cpp
  core/src/codecs/VectorCompressFormat.cpp
  core/src/codecs/VectorIndexFormat.cpp
Labels: PR | automerge, PR | hotfix

#3936 Support topk up to 16384 on GPU
  core/src/index/thirdparty/faiss/gpu/impl/IVFFlat.cu
  core/src/index/thirdparty/faiss/gpu/impl/IVFFlat.cuh
  core/src/index/thirdparty/faiss/gpu/impl/IVFFlatScanLargeK.cu
  core/src/index/thirdparty/faiss/gpu/impl/IVFFlatScanLargeK.cuh
  core/src/index/thirdparty/faiss/gpu/impl/IVFUtils.cuh
  core/src/index/thirdparty/faiss/gpu/impl/IVFUtilsSelect1.cu
  core/src/index/thirdparty/faiss/gpu/utils/DeviceDefs.cuh
  core/src/utils/ValidationUtil.h
Labels: type/new-feature

#3956 improve checksum performance
  core/src/codecs/ExtraFileInfo.cpp
Labels: PR | automerge, PR | hotfix

#3958 the search time increase when using sq8h
  core/src/index/thirdparty/faiss/gpu/GpuIndexIVF.cu
Labels: PR | automerge, PR | hotfix

#3966 [skip ci]Update field name
  tests/milvus_python_test/collection/test_collection_stats.py
  tests/milvus_python_test/collection/test_create_collection.py
  tests/milvus_python_test/collection/test_get_collection_info.py
  tests/milvus_python_test/entity/test_insert.py
  tests/milvus_python_test/utils.py
Labels: PR | automerge

#3967 [skip ci] update version in test case
  tests/milvus_python_test/test_ping.py
Labels: PR | automerge, PR | skip-ci

#3970 Update field name
  tests/milvus_python_test/entity/test_get_entity_by_id.py
  tests/milvus_python_test/entity/test_search.py
  tests/milvus_python_test/test_config.py
  tests/milvus_python_test/utils.py
Labels: PR | automerge

#3972 rename segment_row_count to segment_row_limit
  core/src/db/Constants.h
  core/src/db/DBImpl.cpp
  core/src/db/SnapshotUtils.cpp
  core/src/db/SnapshotUtils.h
  core/src/db/SnapshotVisitor.cpp
  core/src/db/Types.cpp
  core/src/db/Types.h
  core/src/db/Utils.cpp
  core/src/db/Utils.h
  core/src/db/insert/MemCollection.cpp
  core/src/db/insert/MemCollection.h
  core/src/db/merge/MergeManager.h
  core/src/db/merge/MergeManagerImpl.cpp
  core/src/db/wal/WalProxy.cpp
  core/src/server/ValidationUtil.cpp
  core/src/server/ValidationUtil.h
  core/src/server/delivery/request/CreateCollectionReq.cpp
  core/src/server/web_impl/handler/WebRequestHandler.cpp
  core/unittest/db/test_meta.cpp
  core/unittest/db/test_transcript.cpp
  core/unittest/db/test_wal.cpp
  core/unittest/server/test_web.cpp
Labels: PR | automerge, PR | hotfix

#3974 avoid unnecessery waiting for build index
  core/src/db/DBImpl.cpp
Labels: PR | automerge, PR | hotfix

#3975 The 'num' in return of search is incorrect when use http-api
  CHANGELOG.md
  core/src/server/delivery/request/GetCollectionInfoReq.cpp
  core/src/server/web_impl/handler/WebRequestHandler.cpp
  core/unittest/server/test_web.cpp
Labels: PR | automerge, PR | hotfix

#3960 Add data wrapper in the result of getEntity
  core/src/server/web_impl/README.md
  core/src/server/web_impl/handler/WebRequestHandler.cpp
Labels: PR | automerge, PR | hotfix

#3982 stop build index thread when server is shutdown
  core/src/db/DBImpl.cpp
  core/src/db/DBImpl.h
  core/src/server/Server.cpp
Labels: PR | automerge, PR | hotfix

#3986 add conf stat_optimizer_enable
  core/src/config/ConfigInit.cpp
  core/src/config/ServerConfig.h
  core/src/db/DBImpl.cpp
  core/src/index/archive/KnowhereResource.cpp
  core/src/server/web_impl/dto/ConfigDto.hpp
Labels: PR | automerge, PR | hotfix

#3983 Web_impl restful doc bugs
  CHANGELOG.md
  core/src/server/web_impl/README.md
Labels: PR | automerge, PR | hotfix

#3984 cache structured field index
  core/src/db/engine/ExecutionEngineImpl.cpp
  core/src/db/engine/ExecutionEngineImpl.h
  core/src/index/knowhere/knowhere/index/structured_index/StructuredIndexSort.h
  core/src/index/unittest/test_structured_index_sort.cpp
  core/src/segment/SegmentReader.cpp
  core/src/segment/SegmentReader.h
Labels: PR | automerge, PR | hotfix

#3985 remove surplus class import in dev case
  tests/milvus_python_test/stability/test_restart.py
  tests/milvus_python_test/test_mix.py
Labels: PR | hotfix

#3991 refine log
  core/src/db/DBImpl.cpp
  core/src/db/insert/MemSegment.cpp
  core/src/scheduler/JobMgr.cpp
  core/src/scheduler/selector/FaissIVFPass.cpp
  core/src/server/delivery/request/CountEntitiesReq.cpp
  core/src/server/delivery/request/CreateCollectionReq.cpp
  core/src/server/delivery/request/CreateIndexReq.cpp
  core/src/server/delivery/request/CreatePartitionReq.cpp
  core/src/server/delivery/request/DeleteEntityByIDReq.cpp
  core/src/server/delivery/request/DescribeIndexReq.cpp
  core/src/server/delivery/request/DropCollectionReq.cpp
  core/src/server/delivery/request/DropIndexReq.cpp
  core/src/server/delivery/request/DropPartitionReq.cpp
  core/src/server/delivery/request/GetCollectionInfoReq.cpp
  core/src/server/delivery/request/GetCollectionStatsReq.cpp
  core/src/server/delivery/request/GetEntityByIDReq.cpp
  core/src/server/delivery/request/HasCollectionReq.cpp
  core/src/server/delivery/request/HasPartitionReq.cpp
  core/src/server/delivery/request/InsertReq.cpp
  core/src/server/delivery/request/ListCollectionsReq.cpp
  core/src/server/delivery/request/ListIDInSegmentReq.cpp
  core/src/server/delivery/request/ListPartitionsReq.cpp
  core/src/server/delivery/request/LoadCollectionReq.cpp
  core/src/server/delivery/request/SearchReq.cpp
Labels: PR | automerge, PR | hotfix

#3993 support log to stdout
  CHANGELOG.md
  core/conf/milvus.template
  core/src/config/ConfigInit.cpp
  core/src/config/ServerConfig.h
  core/src/log/LogMgr.cpp
  core/src/log/LogMgr.h
  core/src/server/Server.cpp
Labels: PR | automerge, PR | hotfix

#3994 Server crashed when search using java-sdk
  CHANGELOG.md
  core/src/server/delivery/request/SearchReq.cpp
Labels: PR | automerge, PR | hotfix

#4002 withdraw pr2467 on branch 0.11.0
  core/src/index/thirdparty/faiss/gpu/utils/Select.cuh
Labels: PR | automerge, PR | hotfix

#4003 Return wrong entities when real result number is less than topk
  core/src/server/grpc_impl/GrpcRequestHandler.cpp
Labels: PR | automerge, PR | hotfix

#3997 [skip ci] update http case
  tests/milvus_http_test/client.py
  tests/milvus_http_test/collections/test_create.py
  tests/milvus_http_test/collections/test_drop.py
  tests/milvus_http_test/collections/test_get_info.py
  tests/milvus_http_test/collections/test_get_stats.py
  tests/milvus_http_test/collections/test_list.py
  tests/milvus_http_test/conftest.py
  tests/milvus_http_test/constants.py
  tests/milvus_http_test/entities/test_delete.py
  tests/milvus_http_test/entities/test_get.py
  tests/milvus_http_test/entities/test_insert.py
  tests/milvus_http_test/entities/test_search.py
  tests/milvus_http_test/locust_file.py
  tests/milvus_http_test/locust_task.py
  tests/milvus_http_test/test_index.py
  tests/milvus_http_test/test_partition.py
  tests/milvus_http_test/utils.py
Labels: PR | automerge, PR | skip-ci

#4006 Change config version to 0.6
  ci/jenkins/Jenkinsfile
  core/conf/demo/milvus.yaml
  core/conf/milvus.template
  core/src/config/ConfigInit.cpp
  core/unittest/server/test_web.cpp
Labels: PR | automerge, PR | hotfix

#4010 [skip ci] Don't get cache when CI is manually triggered
  .jenkins/modules/Build/MilvusBuild.groovy
  .jenkins/modules/DevTest/SingleNodeDevTest.groovy
Labels: type/enhancement

#3954 Fix server crashed during search with index pq
  CHANGELOG.md
  core/src/index/thirdparty/faiss/gpu/impl/PQCodeDistances-inl.cuh
Labels: PR | cherry-pick

#4015 [skip ci] Update cron time on 0.10.3 branch
  ci/jenkins/Jenkinsfile
Labels: PR | automerge, type/enhancement

#4025 use more CPUs and memory to build image
  ci/jenkins/pod/milvus-cpu-version-centos7-build-env-pod.yaml
  ci/jenkins/pod/milvus-cpu-version-ubuntu18.04-build-env-pod.yaml
  ci/jenkins/pod/milvus-gpu-version-centos7-build-env-pod.yaml
  ci/jenkins/pod/milvus-gpu-version-ubuntu18.04-build-env-pod.yaml
Labels: PR | automerge

#4034 update devtest groovy
  .jenkins/modules/DevTest/SingleNodeDevTest.groovy
Labels: PR | automerge

#4037 Fix #4030. Change wrong config name
  CHANGELOG.md
  core/src/config/ConfigInit.cpp
Labels: PR | automerge, PR | hotfix

#4056 Let uid be shared pointer to not copy really
  core/src/db/engine/ExecutionEngineImpl.cpp
  core/src/index/knowhere/knowhere/index/vector_index/VecIndex.h
  core/src/index/knowhere/knowhere/index/vector_index/helpers/Cloner.cpp
  core/src/segment/SegmentReader.cpp
Labels: PR | automerge, PR | hotfix

#4061 #4053 fix partition tag regex match
  core/src/db/DBImpl.cpp
  core/src/scheduler/selector/FaissIVFSQ8HPass.cpp
  core/src/server/ValidationUtil.cpp
  core/src/server/ValidationUtil.h
  core/src/server/delivery/request/CreatePartitionReq.cpp
  core/src/server/delivery/request/HasPartitionReq.cpp
  core/src/server/delivery/request/SearchReq.cpp
  core/src/utils/StringHelpFunctions.cpp
Labels: PR | automerge

#4063 milvus raise exception when passing a complex dsl during searching
  CHANGELOG.md
  core/src/query/BinaryQuery.cpp
Labels: PR | automerge, PR | hotfix

#4058 Fix #3793. Solve the resource allocation problem
  CHANGELOG.md
  core/src/scheduler/TaskTable.cpp
  core/src/scheduler/selector/BuildIndexPass.cpp
  core/src/scheduler/selector/BuildIndexPass.h
  core/src/scheduler/task/BuildIndexTask.cpp
  core/src/scheduler/task/BuildIndexTask.h
Labels: PR | automerge, PR | hotfix

#4065 #4051 Improvement Job::Dump to get more information from snapshot
  core/src/scheduler/job/BuildIndexJob.h
  core/src/scheduler/job/Job.cpp
  core/src/scheduler/job/SearchJob.h
  core/src/scheduler/task/BuildIndexTask.cpp
  core/src/scheduler/task/BuildIndexTask.h
  core/src/scheduler/task/SearchTask.cpp
  core/src/scheduler/task/SearchTask.h
Labels: PR | automerge

#4078 Fix #3793. A supplementary fix for the bug caused by CPU resource sus…
  core/src/db/DBImpl.cpp
  core/src/scheduler/resource/CpuResource.cpp
Labels: PR | automerge, PR | hotfix

#4080 Add config macro
  core/src/config/ConfigInit.cpp
Labels: PR | automerge, type/enhancement

#4084 [skip ci] update cmake version
  CONTRIBUTING.md
  INSTALL.md
Labels: PR | automerge, PR | skip-ci

#4085 Improve config codes
  core/src/config/ServerConfig.h
Labels: PR | automerge

#4087 modify the log warning
  core/src/index/archive/KnowhereResource.cpp
  core/src/index/knowhere/knowhere/index/vector_index/helpers/FaissIO.cpp
  core/src/index/knowhere/knowhere/index/vector_index/helpers/FaissIO.h
  core/src/index/thirdparty/faiss/gpu/utils/StackDeviceMemory.cpp
  sdk/examples/simple/src/ClientTest.cpp
Labels: PR | automerge, PR | hotfix

#4097 Remove update_fn in config parameters
  core/src/config/ConfigInit.cpp
  core/src/config/ConfigType.cpp
  core/src/config/ConfigType.h
  core/src/config/ConfigTypeTest1.cpp
  core/src/config/ConfigTypeTest2.cpp
Labels: PR | Improvement, PR | automerge

#4100 Remove scheduler task label
  core/src/scheduler/JobMgr.cpp
  core/src/scheduler/Scheduler.cpp
  core/src/scheduler/action/PushTaskToNeighbour.cpp
  core/src/scheduler/job/BuildIndexJob.cpp
  core/src/scheduler/job/SearchJob.cpp
  core/src/scheduler/resource/Resource.cpp
  core/src/scheduler/selector/BuildIndexPass.cpp
  core/src/scheduler/selector/FaissFlatPass.cpp
  core/src/scheduler/selector/FaissIVFPass.cpp
  core/src/scheduler/selector/FaissIVFSQ8HPass.cpp
  core/src/scheduler/selector/FallbackPass.cpp
  core/src/scheduler/task/BuildIndexTask.cpp
  core/src/scheduler/task/BuildIndexTask.h
  core/src/scheduler/task/FinishedTask.cpp
  core/src/scheduler/task/SearchTask.cpp
  core/src/scheduler/task/SearchTask.h
  core/src/scheduler/task/Task.h
  core/src/scheduler/task/TestTask.cpp
  core/src/scheduler/task/TestTask.h
  core/src/scheduler/tasklabel/BroadcastLabel.h
  core/src/scheduler/tasklabel/SpecResLabel.h
  core/src/scheduler/tasklabel/TaskLabel.h
  core/unittest/scheduler/CMakeLists.txt
  core/unittest/scheduler/test_task.cpp
Labels: PR | Improvement

#4081 parallel case on 0.11.1
  .jenkins/modules/DevTest/SingleNodeDevTest.groovy
  tests/milvus_python_test/conftest.py
  tests/milvus_python_test/entity/test_insert.py
  tests/milvus_python_test/test_flush.py
Labels: PR | automerge, PR | skip-ci

#4103 add search case
  tests/milvus-java-test/pom.xml
  tests/milvus-java-test/src/main/java/com/Constants.java
  tests/milvus-java-test/src/main/java/com/MainClass.java
  tests/milvus-java-test/src/main/java/com/TestSearchEntities.java
Labels: PR | automerge

#4108 Use tini for Docker quicker exit.
  docker/deploy/cpu/centos7/Dockerfile
  docker/deploy/cpu/ubuntu16.04/Dockerfile
  docker/deploy/cpu/ubuntu18.04/Dockerfile
  docker/deploy/gpu/centos7/Dockerfile
  docker/deploy/gpu/ubuntu16.04/Dockerfile
  docker/deploy/gpu/ubuntu18.04/Dockerfile
Labels: PR | cherry-pick, type/enhancement

#4106 Reduce lock granularity in Config
  core/src/config/CMakeLists.txt
  core/src/config/ConfigInit.cpp
  core/src/config/ConfigMgr.cpp
  core/src/config/ConfigType.cpp
  core/src/config/ConfigType.h
  core/src/config/ConfigTypeTest1.cpp
  core/src/config/ConfigTypeTest2.cpp
  core/src/config/ServerConfig.cpp
  core/src/config/ServerConfig.h
  core/src/config/Value.h
Labels: PR | Improvement

#4110 Fix Java Test Format
  tests/milvus-java-test/MilvusSDkJavaTest.iml
  tests/milvus-java-test/src/main/java/com/Constants.java
  tests/milvus-java-test/src/main/java/com/MainClass.java
  tests/milvus-java-test/src/main/java/com/TestCollection.java
  tests/milvus-java-test/src/main/java/com/TestCollectionCount.java
  tests/milvus-java-test/src/main/java/com/TestCollectionStats.java
  tests/milvus-java-test/src/main/java/com/TestCompact.java
  tests/milvus-java-test/src/main/java/com/TestConnect.java
  tests/milvus-java-test/src/main/java/com/TestDeleteEntities.java
  tests/milvus-java-test/src/main/java/com/TestFlush.java
  tests/milvus-java-test/src/main/java/com/TestGetEntityByID.java
  tests/milvus-java-test/src/main/java/com/TestIndex.java
  tests/milvus-java-test/src/main/java/com/TestInsertEntities.java
  tests/milvus-java-test/src/main/java/com/TestMix.java
  tests/milvus-java-test/src/main/java/com/TestPS.java
  tests/milvus-java-test/src/main/java/com/TestPartition.java
  tests/milvus-java-test/src/main/java/com/TestPing.java
  tests/milvus-java-test/src/main/java/com/TestSearchByIds.java
  tests/milvus-java-test/src/main/java/com/TestSearchEntities.java
  tests/milvus-java-test/src/main/java/com/Utils.java
Labels: PR | automerge, java

#4111 [skip ci] Go case
  tests/milvus_go_test/.gitignore
  tests/milvus_go_test/Readme.md
  tests/milvus_go_test/client_test.go
  tests/milvus_go_test/create_collection_test.go
  tests/milvus_go_test/go.mod
  tests/milvus_go_test/insert_test.go
  tests/milvus_go_test/main_test.go
  tests/milvus_go_test/utils/utils.go
Labels: PR | automerge, PR | skip-ci

#4115 After milvus 0.11.0 version vector data is misaligned
  CHANGELOG.md
  core/src/server/web_impl/handler/WebRequestHandler.cpp
Labels: PR | automerge, PR | hotfix

#4109 Pass "nbits" as an argument to IVF_PQ create_index
  core/src/db/engine/ExecutionEngineImpl.cpp
  core/src/index/knowhere/knowhere/index/vector_index/ConfAdapter.cpp
  core/src/index/knowhere/knowhere/index/vector_index/ConfAdapter.h
  core/src/index/knowhere/knowhere/index/vector_index/IndexIVFPQ.cpp
  core/src/index/thirdparty/faiss/IndexIVFPQ.cpp
  core/src/server/ValidationUtil.cpp
  tests/milvus_python_test/utils.py
Labels: PR | automerge, type/new-feature

#4129 remove dependency of sqlite_orm
  core/cmake/DefineOptions.cmake
  core/cmake/ThirdPartyPackages.cmake
  core/src/db/meta/MetaSchema.h
  core/src/db/meta/SqliteMetaImpl.cpp
Labels: PR | automerge

#4121 Unify exception in config module
  core/src/config/ConfigMgr.cpp
  core/src/config/ConfigMgr.h
  core/src/config/ConfigType.cpp
  core/src/config/ConfigType.h
  core/src/config/ConfigTypeTest1.cpp
  core/src/config/ConfigTypeTest2.cpp
Labels: PR | automerge, PR | improvement

#4127 #4101 Trim blank space for collection name, partition name and field …
  core/src/server/ValidationUtil.cpp
  core/src/server/ValidationUtil.h
  core/src/server/delivery/request/CompactReq.cpp
  core/src/server/delivery/request/CompactReq.h
  core/src/server/delivery/request/CountEntitiesReq.cpp
  core/src/server/delivery/request/CountEntitiesReq.h
  core/src/server/delivery/request/CreateCollectionReq.cpp
  core/src/server/delivery/request/CreateCollectionReq.h
  core/src/server/delivery/request/CreateIndexReq.cpp
  core/src/server/delivery/request/CreateIndexReq.h
  core/src/server/delivery/request/CreatePartitionReq.cpp
  core/src/server/delivery/request/CreatePartitionReq.h
  core/src/server/delivery/request/DeleteEntityByIDReq.cpp
  core/src/server/delivery/request/DeleteEntityByIDReq.h
  core/src/server/delivery/request/DescribeIndexReq.h
  core/src/server/delivery/request/DropIndexReq.cpp
  core/src/server/delivery/request/DropIndexReq.h
  core/src/server/delivery/request/DropPartitionReq.cpp
  core/src/server/delivery/request/DropPartitionReq.h
  core/src/server/delivery/request/FlushReq.cpp
  core/src/server/delivery/request/GetCollectionInfoReq.h
  core/src/server/delivery/request/GetCollectionStatsReq.h
  core/src/server/delivery/request/HasPartitionReq.cpp
  core/src/server/delivery/request/InsertReq.cpp
  core/src/server/delivery/request/InsertReq.h
  core/src/server/delivery/request/ListIDInSegmentReq.cpp
  core/src/server/delivery/request/ListPartitionsReq.cpp
  core/src/server/delivery/request/ListPartitionsReq.h
  core/src/server/delivery/request/LoadCollectionReq.cpp
  core/src/server/delivery/request/LoadCollectionReq.h
  core/src/server/delivery/request/SearchReq.cpp
  tests/milvus_python_test/utils.py
Labels: PR | automerge

#4142 #4135 Error should be raised if field not exised in collection during…
  core/src/db/SnapshotUtils.cpp
Labels: PR | automerge, PR | hotfix

#4141 #4101 Trim blank space for collection name, partition name and field name
  core/src/server/ValidationUtil.cpp
  core/src/server/ValidationUtil.h
  core/src/server/delivery/request/CompactReq.cpp
  core/src/server/delivery/request/CompactReq.h
  core/src/server/delivery/request/CountEntitiesReq.cpp
  core/src/server/delivery/request/CountEntitiesReq.h
  core/src/server/delivery/request/CreateCollectionReq.cpp
  core/src/server/delivery/request/CreateCollectionReq.h
  core/src/server/delivery/request/CreateIndexReq.cpp
  core/src/server/delivery/request/CreateIndexReq.h
  core/src/server/delivery/request/CreatePartitionReq.cpp
  core/src/server/delivery/request/CreatePartitionReq.h
  core/src/server/delivery/request/DeleteEntityByIDReq.cpp
  core/src/server/delivery/request/DeleteEntityByIDReq.h
  core/src/server/delivery/request/DescribeIndexReq.h
  core/src/server/delivery/request/DropIndexReq.cpp
  core/src/server/delivery/request/DropIndexReq.h
  core/src/server/delivery/request/DropPartitionReq.cpp
  core/src/server/delivery/request/DropPartitionReq.h
  core/src/server/delivery/request/FlushReq.cpp
  core/src/server/delivery/request/GetCollectionInfoReq.h
  core/src/server/delivery/request/GetCollectionStatsReq.h
  core/src/server/delivery/request/HasPartitionReq.cpp
  core/src/server/delivery/request/InsertReq.cpp
  core/src/server/delivery/request/InsertReq.h
  core/src/server/delivery/request/ListIDInSegmentReq.cpp
  core/src/server/delivery/request/ListPartitionsReq.cpp
  core/src/server/delivery/request/ListPartitionsReq.h
  core/src/server/delivery/request/LoadCollectionReq.cpp
  core/src/server/delivery/request/LoadCollectionReq.h
  core/src/server/delivery/request/SearchReq.cpp
  tests/milvus_python_test/utils.py
Labels: PR | automerge

#4140 When execute a multiple vectors request, if the result of somerow is not enough, the query data field will be disorder.
  CHANGELOG.md
  core/src/server/grpc_impl/GrpcRequestHandler.cpp
  sdk/CMakeLists.txt
  sdk/examples/simple/src/ClientTest.cpp
  sdk/examples/simple/src/ClientTest.h
  sdk/examples/utils/Utils.cpp
  sdk/examples/utils/Utils.h
  sdk/grpc/ClientProxy.cpp
  sdk/grpc/ClientProxy.h
  sdk/include/Field.h
  sdk/include/MilvusApi.h
  sdk/interface/ConnectionImpl.cpp
  sdk/interface/ConnectionImpl.h
Labels: PR | automerge, PR | hotfix

#4139 Go case
  tests/milvus_go_test/cmd_test.go
  tests/milvus_go_test/collection_test.go
  tests/milvus_go_test/connect_test.go
  tests/milvus_go_test/count_test.go
  tests/milvus_go_test/create_collection_test.go
  tests/milvus_go_test/delete_test.go
  tests/milvus_go_test/get_test.go
  tests/milvus_go_test/go.mod
  tests/milvus_go_test/index_test.go
  tests/milvus_go_test/insert_test.go
  tests/milvus_go_test/main_test.go
  tests/milvus_go_test/partition_test.go
  tests/milvus_go_test/search_test.go
  tests/milvus_go_test/stats_test.go
  tests/milvus_go_test/utils/constants.go
  tests/milvus_go_test/utils/utils.go
Labels: PR | automerge, PR | skip-ci

#4120 Speed sqlite execution time
  CHANGELOG.md
  core/src/db/meta/backend/SqliteEngine.cpp
Labels: PR | automerge, PR | hotfix, type/enhancement, type/performance

#4138 #4082 Expose MAX_PARTITION_LIMIT to config
  core/src/config/Config.cpp
  core/src/config/Config.h
  core/src/db/meta/MySQLMetaImpl.cpp
  core/src/db/meta/SqliteMetaImpl.cpp
  core/src/server/delivery/request/CreatePartitionRequest.cpp
  core/unittest/server/test_config.cpp
Labels: PR | automerge
