Repository milvus-io/milvus, pull requests merged in 2020-01, with the labels that each got.

#888 IVFTest.gpu_seal_test unittest failed #805
  CHANGELOG.md
  core/src/index/knowhere/knowhere/index/vector_index/FaissBaseIndex.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexGPUIVFPQ.cpp
  core/src/index/unittest/test_ivf.cpp
  core/unittest/server/test_util.cpp
Labels: type/bug

#903 fix #886
  core/src/index/thirdparty/faiss/IndexBinaryIVF.cpp
Labels: type/bug

#909 move primary_path and secondary_path to storage config
  CHANGELOG.md
  core/conf/demo/server_config.yaml
  core/conf/server_cpu_config.template
  core/conf/server_gpu_config.template
  core/src/server/Config.cpp
  core/src/server/Config.h
  core/src/server/DBWrapper.cpp
  core/unittest/db/utils.cpp
  core/unittest/server/test_config.cpp
  core/unittest/server/test_rpc.cpp
  core/unittest/server/utils.cpp
  core/unittest/storage/utils.cpp
  core/unittest/wrapper/utils.cpp
Labels: type/enhancement

#911 Change C++ standard to c++17
  CHANGELOG.md
  core/CMakeLists.txt
  core/src/index/CMakeLists.txt
  core/src/main.cpp
Labels: type/enhancement

#929 Change milvus helm version to master
  ci/jenkins/step/deploySingle2Dev.groovy
  ci/jenkins/step/singleDevNightlyTest.groovy
  ci/jenkins/step/singleDevTest.groovy
Labels: type/new-feature

#939 remove collector from config
  CHANGELOG.md
  core/conf/demo/server_config.yaml
  core/conf/server_cpu_config.template
  core/conf/server_gpu_config.template
  core/src/metrics/Metrics.cpp
  core/src/metrics/prometheus/PrometheusMetrics.cpp
  core/src/server/Config.cpp
  core/src/server/Config.h
  core/unittest/db/utils.cpp
  core/unittest/metrics/test_metrics.cpp
  core/unittest/server/test_config.cpp
  core/unittest/server/utils.cpp
  core/unittest/wrapper/utils.cpp
Labels: type/enhancement

#937 add s3 mock for unittest
  ci/jenkins/step/build.groovy
  ci/scripts/build.sh
  core/src/db/Utils.cpp
  core/src/storage/s3/S3ClientMock.h
  core/src/storage/s3/S3ClientWrapper.cpp
  core/src/storage/s3/S3ClientWrapper.h
  core/unittest/storage/CMakeLists.txt
  core/unittest/storage/test_s3_client.cpp
  core/unittest/storage/utils.cpp
  docker-compose.yml
Labels: type/new-feature

#950 [skip ci] Create SUPPORT.md and RELEASE.md
  RELEASE.md
  SUPPORT.md
Labels: type/docs

#960 [skip ci] Fix some broken links
  README.md
  README_CN.md
  README_JP.md
  docs/README.md
Labels: type/docs

#989 Setting image pullPolicy to Always on Deploy stage
  ci/jenkins/step/deploySingle2Dev.groovy
  ci/jenkins/step/singleDevNightlyTest.groovy
  ci/jenkins/step/singleDevTest.groovy
Labels: type/enhancement

#973 [skip ci] Update C++ SDK readme.
  sdk/README.md
Labels: type/docs

#1025 Fix cleanupSingleDev groovy file bug
  ci/jenkins/step/singleDevNightlyTest.groovy
  ci/jenkins/step/singleDevTest.groovy
Labels: type/bug

#1040 Flag the upload to group coverage metrics
  .github/workflows/core.yml
  ci/jenkins/step/coverage.groovy
  ci/scripts/check_ccache.sh
  ci/scripts/update_ccache.sh
  codecov.yaml
  docker/build_env/cpu/centos7/Dockerfile
  docker/build_env/cpu/ubuntu16.04/Dockerfile
  docker/build_env/cpu/ubuntu18.04/Dockerfile
  docker/build_env/gpu/centos7/Dockerfile
  docker/build_env/gpu/ubuntu16.04/Dockerfile
  docker/build_env/gpu/ubuntu18.04/Dockerfile
  docker/test_env/Dockerfile
Labels: type/enhancement

#1060 run hadolint with reviewdog
  .github/workflows/core.yml
  .hadolint.yaml
  core/src/index/thirdparty/SPTAG/Dockerfile
  core/src/index/thirdparty/faiss/Dockerfile
  docker/build_env/cpu/centos7/Dockerfile
  docker/build_env/cpu/ubuntu16.04/Dockerfile
  docker/build_env/cpu/ubuntu18.04/Dockerfile
  docker/build_env/gpu/centos7/Dockerfile
  docker/build_env/gpu/ubuntu16.04/Dockerfile
  docker/build_env/gpu/ubuntu18.04/Dockerfile
  docker/deploy/cpu/centos7/Dockerfile
  docker/deploy/cpu/ubuntu16.04/Dockerfile
  docker/deploy/cpu/ubuntu18.04/Dockerfile
  docker/deploy/gpu/centos7/Dockerfile
  docker/deploy/gpu/ubuntu16.04/Dockerfile
  docker/deploy/gpu/ubuntu18.04/Dockerfile
  docker/test_env/Dockerfile
  shards/Dockerfile
  tests/milvus_python_test/Dockerfile
Labels: type/new-feature

#1087 Clean up old docker images
  ci/jenkins/step/publishImages.groovy
Labels: type/enhancement

#1088 rename 'minio' to 's3' in Storage Config section
  CHANGELOG.md
  core/conf/demo/server_config.yaml
  core/conf/server_cpu_config.template
  core/conf/server_gpu_config.template
  core/src/db/Utils.cpp
  core/src/server/Config.cpp
  core/src/server/Config.h
  core/src/storage/s3/S3ClientWrapper.cpp
  core/src/storage/s3/S3ClientWrapper.h
  core/src/wrapper/VecIndex.cpp
  core/unittest/server/test_config.cpp
  core/unittest/storage/test_s3_client.cpp
  core/unittest/storage/utils.cpp
Labels: type/enhancement

#1102 Add GPU sharing solution on native Kubernetes
  ci/jenkins/Jenkinsfile
  ci/jenkins/pod/milvus-gpu-version-centos7-build-env-pod.yaml
  ci/jenkins/pod/milvus-gpu-version-ubuntu18.04-build-env-pod.yaml
Labels: type/enhancement

#1107 Filtering for specific paths in Jenkins CI
  .github/workflows/core.yml
  ci/jenkins/Jenkinsfile
Labels: type/enhancement

#1109 Fix Filtering for specific paths in Jenkins CI bug
  .github/workflows/core.yml
  ci/jenkins/Jenkinsfile
Labels: type/bug

#1110 Fix Filtering for specific paths in Jenkins CI bug
  ci/jenkins/Jenkinsfile
Labels: type/bug

#1113 Don't skip ci when triggered by a time
  ci/jenkins/Jenkinsfile
Labels: type/bug
