Repository milvus-io/milvus, pull requests merged in 2020-07, with the labels that each got.

#2701 #2642 Create index failed caused by server crashed.
  CHANGELOG.md
  core/src/index/knowhere/knowhere/index/vector_index/IndexBinaryIDMAP.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexBinaryIDMAP.h
  core/src/index/knowhere/knowhere/index/vector_index/IndexBinaryIVF.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexBinaryIVF.h
  core/src/index/knowhere/knowhere/index/vector_index/IndexIDMAP.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexIDMAP.h
  core/src/index/knowhere/knowhere/index/vector_index/IndexIVF.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexIVF.h
  core/src/index/knowhere/knowhere/index/vector_index/IndexNSG.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexSPTAG.cpp
Labels: automerge

#2711 [skip ci] disable cron on 0.8.1
  ci/jenkins/Jenkinsfile
Labels: automerge

#2716 snapshot integration
  core/src/db/DB.h
  core/src/db/DBImpl.h
  core/src/db/SSDBImpl.cpp
  core/src/db/SSDBImpl.h
  core/src/db/SimpleWaitNotify.h
  core/src/db/snapshot/ResourceTypes.h
Labels: automerge, type/new-feature

#2691 Web fix 2690
  CHANGELOG.md
  core/src/server/web_impl/controller/WebController.hpp
  core/src/server/web_impl/handler/WebRequestHandler.cpp
  core/src/server/web_impl/handler/WebRequestHandler.h
  core/unittest/db/test_web.cpp
  tests/milvus_python_test/entity/test_delete.py
Labels: automerge

#2718 (db/snapshot): Code Integration
  core/src/db/SSDBImpl.cpp
  core/src/db/SSDBImpl.h
  core/src/db/snapshot/CompoundOperations.cpp
  core/src/db/snapshot/CompoundOperations.h
  core/src/db/snapshot/EventExecutor.h
  core/src/db/snapshot/ResourceHolder.h
  core/src/db/snapshot/ResourceOperations.cpp
  core/src/db/snapshot/ResourceTypes.h
  core/src/db/snapshot/Resources.cpp
  core/src/db/snapshot/Resources.h
  core/src/db/snapshot/Snapshots.cpp
  core/src/db/snapshot/Store.h
  core/unittest/ssdb/test_db.cpp
  core/unittest/ssdb/test_snapshot.cpp
Labels: automerge, type/new-feature

#2730 Add pipeline step to print/get the container logs
  ci/jenkins/Jenkinsfile
Labels: automerge, type/enhancement

#2736 Create index failed caused by server crashed.
  CHANGELOG.md
  core/src/index/knowhere/knowhere/index/vector_index/IndexBinaryIDMAP.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexBinaryIDMAP.h
  core/src/index/knowhere/knowhere/index/vector_index/IndexBinaryIVF.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexBinaryIVF.h
  core/src/index/knowhere/knowhere/index/vector_index/IndexIDMAP.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexIDMAP.h
  core/src/index/knowhere/knowhere/index/vector_index/IndexIVF.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexIVF.h
  core/src/index/knowhere/knowhere/index/vector_index/IndexNSG.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexSPTAG.cpp
  core/src/index/knowhere/knowhere/index/vector_offset_index/IndexIVF_NM.cpp
  core/src/index/knowhere/knowhere/index/vector_offset_index/IndexIVF_NM.h
  core/src/index/knowhere/knowhere/index/vector_offset_index/IndexNSG_NM.cpp
  core/src/index/thirdparty/hnswlib/hnswalg_nm.h
Labels: automerge

#2737 (db/snapshot): Add DropAllIndexOperation and related UT
  core/src/db/snapshot/CompoundOperations.cpp
  core/src/db/snapshot/CompoundOperations.h
  core/src/db/snapshot/Context.h
  core/src/db/snapshot/ResourceOperations.cpp
  core/src/db/snapshot/Snapshot.h
  core/unittest/ssdb/test_snapshot.cpp
Labels: automerge, type/new-feature

#2742 Let codec singleton
  core/src/codecs/Codec.h
  core/src/codecs/VectorIndexFormat.h
  core/src/codecs/default/DefaultAttrsFormat.cpp
  core/src/codecs/default/DefaultAttrsFormat.h
  core/src/codecs/default/DefaultAttrsIndexFormat.cpp
  core/src/codecs/default/DefaultAttrsIndexFormat.h
  core/src/codecs/default/DefaultCodec.cpp
  core/src/codecs/default/DefaultCodec.h
  core/src/codecs/default/DefaultDeletedDocsFormat.cpp
  core/src/codecs/default/DefaultDeletedDocsFormat.h
  core/src/codecs/default/DefaultIdBloomFilterFormat.cpp
  core/src/codecs/default/DefaultIdBloomFilterFormat.h
  core/src/codecs/default/DefaultVectorIndexFormat.cpp
  core/src/codecs/default/DefaultVectorIndexFormat.h
  core/src/codecs/default/DefaultVectorsFormat.cpp
  core/src/codecs/default/DefaultVectorsFormat.h
  core/src/segment/SegmentReader.cpp
  core/src/segment/SegmentWriter.cpp
Labels: automerge

#2744 (db/snapshot): Bug fix in operations and unittest
  core/src/db/SSDBImpl.cpp
  core/src/db/SSDBImpl.h
  core/src/db/snapshot/CompoundOperations.cpp
  core/src/db/snapshot/Context.h
  core/src/db/snapshot/ResourceOperations.cpp
  core/src/db/snapshot/ResourceOperations.h
  core/src/db/snapshot/Snapshot.cpp
  core/src/db/snapshot/Store.h
  core/unittest/ssdb/test_db.cpp
  core/unittest/ssdb/test_snapshot.cpp
  core/unittest/ssdb/utils.h
Labels: automerge, type/new-feature

#2748 [skip ci]update config gpu_search_threshold description
  core/conf/demo/server_config.yaml
  core/conf/server_config.template
Labels: Documentation

#2747 (db/snapshot): add more APIs for Snapshot
  core/src/db/SSDBImpl.cpp
  core/src/db/snapshot/ResourceOperations.cpp
  core/src/db/snapshot/Snapshot.cpp
  core/src/db/snapshot/Snapshot.h
  core/unittest/ssdb/test_db.cpp
  core/unittest/ssdb/test_snapshot.cpp
Labels: automerge, type/new-feature

#2751 add background threads to SSDBImpl
  core/src/db/SSDBImpl.cpp
  core/src/db/SSDBImpl.h
  core/src/db/wal/WalManager.cpp
  core/src/db/wal/WalManager.h
Labels: automerge

#2753 snapshot integrate GetEntityByID
  core/src/db/SSDBImpl.cpp
  core/src/db/SSDBImpl.h
  core/src/db/SnapshotHandlers.cpp
  core/src/db/SnapshotHandlers.h
  core/src/db/Types.h
  core/src/db/meta/MetaTypes.h
  core/src/db/snapshot/Event.h
  core/src/db/snapshot/ResourceHelper.h
  core/src/db/snapshot/Resources.cpp
  core/src/db/snapshot/Resources.h
  core/src/db/snapshot/Snapshot.cpp
  core/src/db/snapshot/Snapshot.h
  core/src/grpc/gen-milvus/milvus.pb.cc
  core/src/grpc/gen-milvus/milvus.pb.h
  core/src/grpc/milvus.proto
  core/unittest/ssdb/test_snapshot.cpp
Labels: automerge, type/new-feature

#2746 fix #2739
  CHANGELOG.md
  ci/jenkins/step/shardsDevNightlyTest.groovy
Labels: automerge

#2758 Remove docker-entrypoint.sh in Dockerfile
  docker/deploy/cpu/centos7/Dockerfile
  docker/deploy/cpu/centos7/docker-entrypoint.sh
  docker/deploy/cpu/ubuntu16.04/Dockerfile
  docker/deploy/cpu/ubuntu16.04/docker-entrypoint.sh
  docker/deploy/cpu/ubuntu18.04/Dockerfile
  docker/deploy/cpu/ubuntu18.04/docker-entrypoint.sh
  docker/deploy/gpu/centos7/Dockerfile
  docker/deploy/gpu/centos7/docker-entrypoint.sh
  docker/deploy/gpu/ubuntu16.04/Dockerfile
  docker/deploy/gpu/ubuntu16.04/docker-entrypoint.sh
  docker/deploy/gpu/ubuntu18.04/Dockerfile
  docker/deploy/gpu/ubuntu18.04/docker-entrypoint.sh
Labels: type/enhancement

#2760 (db/snapshot): Implement operation rollback
  core/src/db/snapshot/EventExecutor.h
  core/src/db/snapshot/Operations.cpp
  core/src/db/snapshot/Operations.h
  core/src/db/snapshot/Resources.h
  core/src/db/snapshot/Store.h
Labels: automerge, type/new-feature

#2770 (db/snapshot) snapshot integrate
  core/src/db/SSDBImpl.cpp
  core/src/db/SSDBImpl.h
  core/src/db/SnapshotHandlers.cpp
  core/src/db/meta/MetaTypes.h
  core/src/db/snapshot/ResourceTypes.h
  core/src/db/snapshot/Store.h
  core/unittest/ssdb/utils.h
Labels: automerge, type/new-feature

#2777 (db/snapshot): Add some helper visitors
  core/src/db/SnapshotVisitor.cpp
  core/src/db/SnapshotVisitor.h
  core/src/db/snapshot/Operations.h
  core/src/db/snapshot/Snapshot.cpp
  core/src/db/snapshot/Snapshot.h
  core/unittest/ssdb/test_db.cpp
  core/unittest/ssdb/utils.h
Labels: automerge, type/new-feature

#2782 snapshot integrate
  core/src/db/SSDBImpl.cpp
  core/src/db/SSDBImpl.h
  core/src/db/SnapshotHandlers.cpp
  core/src/db/SnapshotHandlers.h
  core/src/db/snapshot/IterateHandler.h
  core/src/db/snapshot/Snapshot.h
  core/unittest/ssdb/test_db.cpp
  core/unittest/ssdb/utils.h
Labels: automerge, type/new-feature

#2784 fix too many data copies
  CHANGELOG.md
  core/src/index/knowhere/knowhere/index/vector_index/IndexIVF.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexIVFPQ.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexIVFSQ.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexNSG.cpp
Labels: automerge

#2762 rewrite mem manager 1
  core/src/db/SSDBImpl.cpp
  core/src/db/SSDBImpl.h
  core/src/db/Utils.cpp
  core/src/db/Utils.h
  core/src/db/insert/MemManagerFactory.cpp
  core/src/db/insert/MemManagerFactory.h
  core/src/db/insert/SSMemCollection.cpp
  core/src/db/insert/SSMemCollection.h
  core/src/db/insert/SSMemManager.h
  core/src/db/insert/SSMemManagerImpl.cpp
  core/src/db/insert/SSMemManagerImpl.h
  core/src/db/insert/SSMemSegment.cpp
  core/src/db/insert/SSMemSegment.h
  core/src/db/insert/SSVectorSource.cpp
  core/src/db/insert/SSVectorSource.h
  core/src/db/snapshot/Resources.h
  core/src/segment/SegmentWriter.cpp
  core/src/segment/SegmentWriter.h
Labels: automerge

#2788 fix a bug of getting wrong nprobe limitation in knowhere on GPU version
  CHANGELOG.md
  core/src/index/knowhere/knowhere/index/vector_index/ConfAdapter.cpp
Labels: automerge

#2786 Add log to check search result structure
  core/src/scheduler/task/SearchTask.cpp
  core/src/server/grpc_impl/GrpcRequestHandler.cpp
Labels: automerge

#2800 (db/snapshot): Add some visitors
  core/src/db/SnapshotVisitor.cpp
  core/src/db/SnapshotVisitor.h
  core/src/db/snapshot/IterateHandler.h
  core/src/db/snapshot/Snapshot.cpp
  core/src/db/snapshot/Snapshot.h
  core/unittest/ssdb/test_db.cpp
  core/unittest/ssdb/utils.h
Labels: automerge, type/new-feature

#2789 fix #2752
  CHANGELOG.md
  core/src/server/web_impl/handler/WebRequestHandler.cpp
Labels: automerge

#2808 fix task_search
  core/src/scheduler/task/SearchTask.cpp
  core/unittest/db/test_hybrid_db.cpp
  core/unittest/db/test_web.cpp
Labels: automerge

#2819 add unittest 4 hnsw_sq8nr and fix some bug in passing
  core/src/index/knowhere/knowhere/index/vector_offset_index/IndexHNSW_SQ8NR.cpp
  core/src/index/thirdparty/hnswlib/hnswalg_nm.h
  core/src/index/unittest/CMakeLists.txt
  core/src/index/unittest/test_hnsw_sq8nr.cpp
Labels: automerge

#2809 fix #2768
  CHANGELOG.md
  core/src/db/DBImpl.cpp
Labels: automerge

#2821 Add SDK support for IVFSQ8NR
  core/src/db/engine/ExecutionEngine.h
  core/src/db/engine/ExecutionEngineImpl.cpp
  core/src/server/ValidationUtil.cpp
  core/src/server/web_impl/Constants.h
  sdk/examples/utils/Utils.cpp
  sdk/include/MilvusApi.h
Labels: automerge, type/new-feature

#2815 (db/snapshot): LSN logic change and design EventHandlerFactory
  core/src/db/SSDBImpl.cpp
  core/src/db/snapshot/CompoundOperations.cpp
  core/src/db/snapshot/CompoundOperations.h
  core/src/db/snapshot/Event.h
  core/src/db/snapshot/HandlerFactory.h
  core/src/db/snapshot/Operations.h
  core/src/db/snapshot/Store.h
  core/unittest/ssdb/test_snapshot.cpp
Labels: automerge, type/new-feature

#2829 Fix dev test artifacts path error
  ci/jenkins/Jenkinsfile
Labels: Bug

#2830 snapshot integrate
  core/src/db/SSDBImpl.h
  core/src/db/Types.cpp
  core/src/db/Types.h
  core/src/db/snapshot/CompoundOperations.cpp
  core/unittest/ssdb/CMakeLists.txt
  core/unittest/ssdb/test_db.cpp
  core/unittest/ssdb/test_segment.cpp
  core/unittest/ssdb/utils.cpp
  core/unittest/ssdb/utils.h
Labels: automerge, type/new-feature

#2837 (db/snapshot): update visitors
  core/src/db/SnapshotVisitor.cpp
  core/src/db/SnapshotVisitor.h
  core/src/db/snapshot/Operations.h
  core/unittest/ssdb/test_db.cpp
  core/unittest/ssdb/test_snapshot.cpp
Labels: automerge, type/enhancement

#2831 Fix rnsg master
  CHANGELOG.md
  core/src/index/knowhere/knowhere/index/vector_index/IndexNSG.cpp
  core/src/index/knowhere/knowhere/index/vector_index/impl/nsg/Distance.cpp
  core/src/index/knowhere/knowhere/index/vector_index/impl/nsg/NSG.cpp
  core/src/index/knowhere/knowhere/index/vector_index/impl/nsg/NSG.h
  core/src/index/knowhere/knowhere/index/vector_index/impl/nsg/NSGIO.cpp
  core/src/index/knowhere/knowhere/index/vector_offset_index/IndexNSG_NM.cpp
Labels: automerge

#2835 Hnsw sq8 support
  CHANGELOG.md
  core/src/codecs/default/DefaultVectorCompressFormat.cpp
  core/src/db/engine/ExecutionEngine.h
  core/src/db/engine/ExecutionEngineImpl.cpp
  core/src/index/knowhere/knowhere/index/vector_offset_index/IndexHNSW_SQ8NR.h
  core/src/server/ValidationUtil.cpp
  core/src/server/web_impl/Constants.h
  sdk/examples/utils/Utils.cpp
  sdk/include/MilvusApi.h
Labels: automerge

#2833 remove old api
  core/src/db/SSDBImpl.cpp
  core/src/db/insert/SSMemCollection.cpp
  core/src/db/insert/SSMemCollection.h
  core/src/db/insert/SSMemManager.h
  core/src/db/insert/SSMemManagerImpl.cpp
  core/src/db/insert/SSMemManagerImpl.h
  core/src/db/insert/SSMemSegment.cpp
  core/src/db/insert/SSMemSegment.h
  core/src/db/insert/SSVectorSource.cpp
  core/src/db/insert/SSVectorSource.h
Labels: automerge

#2832 Simplify the SQL statement
  core/scripts/migration/sqlite_6_to_4.sql
Labels: automerge

#2851 (db/snapshot) Add snapshot DB module
  core/src/CMakeLists.txt
  core/src/db/meta/MetaAdapter.h
  core/src/db/meta/MetaFields.h
  core/src/db/meta/MetaResourceAttrs.cpp
  core/src/db/meta/MetaResourceAttrs.h
  core/src/db/meta/MetaSession.h
  core/src/db/meta/MySQLConnectionPool.h
  core/src/db/meta/backend/MetaContext.h
  core/src/db/meta/backend/MetaEngine.h
  core/src/db/meta/backend/MetaHelper.cpp
  core/src/db/meta/backend/MetaHelper.h
  core/src/db/meta/backend/MockMetaEngine.cpp
  core/src/db/meta/backend/MockMetaEngine.h
  core/src/db/meta/backend/MySqlEngine.cpp
  core/src/db/meta/backend/MySqlEngine.h
  core/src/db/snapshot/CompoundOperations.cpp
  core/src/db/snapshot/Operations.cpp
  core/src/db/snapshot/Operations.h
  core/src/db/snapshot/ResourceContext.h
  core/src/db/snapshot/ResourceHelper.h
  core/src/db/snapshot/ResourceOperations.cpp
  core/src/db/snapshot/Resources.h
  core/src/db/snapshot/Snapshots.cpp
  core/src/db/snapshot/Store.h
  core/src/server/context/MetaContext.cpp
  core/unittest/CMakeLists.txt
  core/unittest/ssdb/test_snapshot.cpp
  core/unittest/ssdb/utils.cpp
Labels: automerge

#2853 redefine SegmentWriter
  core/src/codecs/snapshot/SSBlockFormat.cpp
  core/src/codecs/snapshot/SSBlockFormat.h
  core/src/codecs/snapshot/SSCodec.cpp
  core/src/codecs/snapshot/SSCodec.h
  core/src/db/SSDBImpl.cpp
  core/src/db/insert/SSMemManager.h
  core/src/db/insert/SSMemManagerImpl.cpp
  core/src/db/insert/SSMemSegment.cpp
  core/src/db/insert/SSMemSegment.h
  core/src/db/insert/SSVectorSource.cpp
  core/src/db/insert/SSVectorSource.h
  core/src/segment/SSSegmentWriter.cpp
  core/src/segment/SSSegmentWriter.h
  core/src/segment/Segment.cpp
  core/src/segment/Segment.h
  core/unittest/ssdb/test_segment.cpp
Labels: automerge

#2860 move index type try2
  CHANGELOG.md
  core/src/db/engine/ExecutionEngine.h
  core/src/db/engine/ExecutionEngineImpl.cpp
  core/src/db/engine/ExecutionEngineImpl.h
  core/src/db/meta/MetaTypes.h
  core/src/index/knowhere/CMakeLists.txt
  core/src/index/knowhere/knowhere/index/IndexType.cpp
  core/src/index/knowhere/knowhere/index/IndexType.h
  core/src/index/knowhere/knowhere/index/vector_index/ConfAdapter.h
  core/src/index/knowhere/knowhere/index/vector_index/ConfAdapterMgr.h
  core/src/index/knowhere/knowhere/index/vector_index/FaissBaseBinaryIndex.h
  core/src/index/knowhere/knowhere/index/vector_index/FaissBaseIndex.cpp
  core/src/index/knowhere/knowhere/index/vector_index/FaissBaseIndex.h
  core/src/index/knowhere/knowhere/index/vector_index/IndexNSG.cpp
  core/src/index/knowhere/knowhere/index/vector_index/VecIndex.h
  core/src/index/knowhere/knowhere/index/vector_index/VecIndexFactory.h
  core/src/index/knowhere/knowhere/index/vector_index/gpu/IndexGPUIDMAP.cpp
  core/src/index/knowhere/knowhere/index/vector_offset_index/IndexNSG_NM.cpp
  core/src/index/knowhere/knowhere/index/vector_offset_index/OffsetBaseIndex.cpp
  core/src/index/knowhere/knowhere/index/vector_offset_index/OffsetBaseIndex.h
  core/src/index/unittest/CMakeLists.txt
  core/src/index/unittest/Helper.h
  core/src/index/unittest/test_customized_index.cpp
  core/src/index/unittest/test_gpuresource.cpp
  core/src/index/unittest/test_idmap.cpp
  core/src/index/unittest/test_ivf.cpp
  core/src/index/unittest/test_ivf_cpu_nm.cpp
  core/src/index/unittest/test_ivf_gpu_nm.cpp
  core/src/index/unittest/test_vecindex.cpp
  core/src/scheduler/Definition.h
  core/src/scheduler/task/SearchTask.cpp
Labels: automerge, type/enhancement

#2854 snapshot integrate
  CHANGELOG.md
  core/src/db/SSDBImpl.cpp
  core/src/db/SnapshotHandlers.cpp
  core/src/db/SnapshotHandlers.h
  core/src/db/insert/SSMemManagerImpl.cpp
  core/src/db/insert/SSMemSegment.cpp
  core/src/db/snapshot/CompoundOperations.cpp
  core/src/db/snapshot/Event.h
  core/src/db/snapshot/ResourceHelper.h
  core/src/db/snapshot/Snapshot.cpp
  core/src/segment/SSSegmentReader.cpp
  core/src/segment/SSSegmentReader.h
  core/src/segment/SSSegmentWriter.cpp
  core/src/segment/SSSegmentWriter.h
  core/src/segment/Segment.cpp
  core/src/segment/Segment.h
  core/src/storage/disk/DiskOperation.cpp
  core/unittest/ssdb/test_segment.cpp
  core/unittest/ssdb/utils.h
Labels: automerge, type/new-feature

#2793 Add python functional tests about timeout
  core/src/index/cmake/ThirdPartyPackagesCore.cmake
  tests/milvus_python_test/test_ping.py
Labels: automerge

#2849 enable rnsg case
  tests/milvus_python_test/entity/test_search.py
Labels: automerge

#2862 (db/snapshot): Update row count related logic
  core/src/db/snapshot/CompoundOperations.cpp
  core/src/db/snapshot/CompoundOperations.h
  core/src/db/snapshot/ResourceOperations.cpp
  core/src/db/snapshot/Snapshot.cpp
  core/unittest/ssdb/test_db.cpp
  core/unittest/ssdb/test_snapshot.cpp
  core/unittest/ssdb/utils.h
Labels: automerge, type/new-feature

#2866 add MILVUS_SUPPORT_SPTAG for some code
  CHANGELOG.md
  core/src/db/Utils.cpp
  core/src/db/meta/MetaTypes.h
  core/src/server/delivery/request/DeleteByIDRequest.cpp
  core/unittest/db/test_engine.cpp
Labels: type/enhancement

#2855 # 2828 opt faiss build
  core/src/index/knowhere/knowhere/index/vector_index/ConfAdapter.cpp
  core/src/index/thirdparty/faiss/gpu/impl/BroadcastSum.cu
  core/src/index/thirdparty/faiss/gpu/impl/BroadcastSum.cuh
  core/src/index/thirdparty/faiss/gpu/impl/Distance.cu
  core/src/index/thirdparty/faiss/gpu/impl/FlatIndex.cu
  core/src/index/thirdparty/faiss/gpu/impl/FlatIndex.cuh
  core/src/index/thirdparty/faiss/gpu/impl/IVFPQ.cu
  core/src/index/thirdparty/faiss/gpu/impl/IVFPQ.cuh
  core/src/index/thirdparty/faiss/gpu/impl/L2Norm.cu
  core/src/index/thirdparty/faiss/gpu/impl/L2Norm.cuh
  core/src/index/thirdparty/faiss/gpu/impl/PQCodeDistances-inl.cuh
  core/src/index/thirdparty/faiss/gpu/impl/PQCodeDistances.cu
  core/src/index/thirdparty/faiss/gpu/impl/PQScanMultiPassNoPrecomputed-inl.cuh
  core/src/index/thirdparty/faiss/gpu/impl/PQScanMultiPassNoPrecomputed.cu
  core/src/index/thirdparty/faiss/gpu/impl/PQScanMultiPassPrecomputed.cu
  core/src/index/thirdparty/faiss/gpu/impl/VectorResidual.cu
  core/src/index/thirdparty/faiss/gpu/impl/VectorResidual.cuh
  core/src/index/thirdparty/faiss/gpu/utils/BlockSelectHalf.cu
  core/src/index/thirdparty/faiss/gpu/utils/BlockSelectKernel.cuh
  core/src/index/thirdparty/faiss/gpu/utils/ConversionOperators.cuh
  core/src/index/thirdparty/faiss/gpu/utils/Float16.cu
  core/src/index/thirdparty/faiss/gpu/utils/Float16.cuh
  core/src/index/thirdparty/faiss/gpu/utils/LoadStoreOperators.cuh
  core/src/index/thirdparty/faiss/gpu/utils/MathOperators.cuh
  core/src/index/thirdparty/faiss/gpu/utils/WarpSelectHalf.cu
  core/src/index/thirdparty/faiss/gpu/utils/WarpSelectKernel.cuh
  core/src/index/thirdparty/faiss/gpu/utils/WarpShuffles.cuh
  core/src/index/thirdparty/faiss/gpu/utils/blockselect/BlockSelectHalf128.cu
  core/src/index/thirdparty/faiss/gpu/utils/blockselect/BlockSelectHalf256.cu
  core/src/index/thirdparty/faiss/gpu/utils/blockselect/BlockSelectHalf64.cu
  core/src/index/thirdparty/faiss/gpu/utils/blockselect/BlockSelectHalfF1024.cu
  core/src/index/thirdparty/faiss/gpu/utils/blockselect/BlockSelectHalfF2048.cu
  core/src/index/thirdparty/faiss/gpu/utils/blockselect/BlockSelectHalfF512.cu
  core/src/index/thirdparty/faiss/gpu/utils/blockselect/BlockSelectHalfT1024.cu
  core/src/index/thirdparty/faiss/gpu/utils/blockselect/BlockSelectHalfT2048.cu
  core/src/index/thirdparty/faiss/gpu/utils/blockselect/BlockSelectHalfT512.cu
Labels: automerge, type/enhancement

#2850 add testcase of empty vector insert
  tests/milvus_python_test/entity/test_insert.py
Labels: automerge

#2877 (db/snapshot): update size related logic
  core/src/db/snapshot/CompoundOperations.cpp
  core/src/db/snapshot/Operations.cpp
  core/src/db/snapshot/Operations.h
  core/src/db/snapshot/ResourceOperations.cpp
  core/src/db/snapshot/Snapshot.cpp
  core/src/db/snapshot/Store.h
  core/unittest/ssdb/CMakeLists.txt
  core/unittest/ssdb/test_snapshot.cpp
  core/unittest/ssdb/utils.h
Labels: automerge, type/new-feature

#2856 (db/snapshot) Add snapshot DB unittest
  core/src/db/meta/MetaAdapter.h
  core/src/db/meta/backend/MockMetaEngine.cpp
  core/src/db/meta/backend/MockMetaEngine.h
  core/src/db/snapshot/ResourceContext.h
  core/src/server/context/Context.cpp
  core/unittest/ssdb/CMakeLists.txt
  core/unittest/ssdb/test_ss_meta.cpp
  core/unittest/ssdb/utils.cpp
  core/unittest/ssdb/utils.h
Labels: automerge

#2878 Fix Prometheus rebuild problem
  .gitignore
  CHANGELOG.md
  core/build.sh
  core/cmake/ThirdPartyPackages.cmake
  core/thirdparty/versions.txt
Labels: automerge

#2888 Add some cpp unittests about scheduler algorithm
  core/unittest/scheduler/test_algorithm.cpp
Labels: automerge

#2885 use BlockingQueue in JobMgr
  CHANGELOG.md
  core/src/scheduler/JobMgr.cpp
  core/src/scheduler/JobMgr.h
  core/src/utils/BlockingQueue.h
Labels: automerge, type/enhancement

#2873 segment writer
  core/src/codecs/snapshot/SSAttrsFormat.cpp
  core/src/codecs/snapshot/SSAttrsFormat.h
  core/src/codecs/snapshot/SSBlockFormat.cpp
  core/src/codecs/snapshot/SSBlockFormat.h
  core/src/codecs/snapshot/SSCodec.cpp
  core/src/codecs/snapshot/SSCodec.h
  core/src/codecs/snapshot/SSIdBloomFilterFormat.cpp
  core/src/codecs/snapshot/SSIdBloomFilterFormat.h
  core/src/codecs/snapshot/SSStructuredIndexFormat.cpp
  core/src/codecs/snapshot/SSStructuredIndexFormat.h
  core/src/codecs/snapshot/SSVectorIndexFormat.cpp
  core/src/codecs/snapshot/SSVectorIndexFormat.h
  core/src/codecs/snapshot/SSVectorsFormat.cpp
  core/src/codecs/snapshot/SSVectorsFormat.h
  core/src/db/SSDBImpl.cpp
  core/src/db/SSDBImpl.h
  core/src/db/SnapshotHandlers.cpp
  core/src/db/SnapshotHandlers.h
  core/src/db/Types.h
  core/src/db/Utils.cpp
  core/src/db/Utils.h
  core/src/db/insert/SSMemCollection.cpp
  core/src/db/insert/SSMemSegment.cpp
  core/src/db/insert/SSMemSegment.h
  core/src/db/insert/SSVectorSource.cpp
  core/src/db/insert/SSVectorSource.h
  core/src/db/merge/SSMergeManagerImpl.cpp
  core/src/db/merge/SSMergeSimpleStrategy.cpp
  core/src/db/merge/SSMergeTask.cpp
  core/src/db/snapshot/Snapshot.h
  core/src/db/wal/WalDefinations.h
  core/src/index/knowhere/knowhere/index/vector_index/VecIndex.h
  core/src/segment/SSSegmentReader.cpp
  core/src/segment/SSSegmentReader.h
  core/src/segment/SSSegmentWriter.cpp
  core/src/segment/SSSegmentWriter.h
  core/src/segment/Segment.cpp
  core/src/segment/Segment.h
  core/unittest/ssdb/test_db.cpp
  core/unittest/ssdb/utils.cpp
  core/unittest/ssdb/utils.h
Labels: automerge

#2899 add config value gpu.cache.enable
  core/src/config/Config.cpp
  core/src/config/Config.h
  core/src/db/engine/ExecutionEngineImpl.cpp
  core/src/db/engine/ExecutionEngineImpl.h
Labels: automerge

#2905 Set MySQL host ip to 127.0.0.1 in jenkins unittest step
  ci/jenkins/step/unittest.groovy
Labels: automerge, type/enhancement

#2886 add web_impl util unittest
  core/src/server/web_impl/utils/Util.cpp
  core/unittest/server/test_web.cpp
Labels: automerge

#2894 Fix warning master
  CHANGELOG.md
  core/src/index/knowhere/knowhere/index/vector_index/IndexAnnoy.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexBinaryIDMAP.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexBinaryIVF.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexHNSW.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexIDMAP.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexIVF.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexIVFPQ.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexIVFSQ.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexNSG.cpp
  core/src/index/knowhere/knowhere/index/vector_index/adapter/SptagAdapter.cpp
  core/src/index/knowhere/knowhere/index/vector_index/adapter/VectorAdapter.h
  core/src/index/knowhere/knowhere/index/vector_index/gpu/IndexGPUIVF.cpp
  core/src/index/knowhere/knowhere/index/vector_index/gpu/IndexGPUIVFPQ.cpp
  core/src/index/knowhere/knowhere/index/vector_index/gpu/IndexGPUIVFSQ.cpp
  core/src/index/knowhere/knowhere/index/vector_index/gpu/IndexGPUIVFSQNR.cpp
  core/src/index/knowhere/knowhere/index/vector_index/gpu/IndexIVFSQHybrid.cpp
  core/src/index/knowhere/knowhere/index/vector_offset_index/IndexHNSW_NM.cpp
  core/src/index/knowhere/knowhere/index/vector_offset_index/IndexHNSW_SQ8NR.cpp
  core/src/index/knowhere/knowhere/index/vector_offset_index/IndexIVFSQNR_NM.cpp
  core/src/index/knowhere/knowhere/index/vector_offset_index/IndexIVF_NM.cpp
  core/src/index/knowhere/knowhere/index/vector_offset_index/IndexNSG_NM.cpp
  core/src/index/knowhere/knowhere/index/vector_offset_index/gpu/IndexGPUIVFSQNR_NM.cpp
  core/src/index/knowhere/knowhere/index/vector_offset_index/gpu/IndexGPUIVF_NM.cpp
Labels: automerge

#2897 (db/snapshot): Update Store
  core/src/db/meta/MetaAdapter.h
  core/src/db/meta/backend/MySqlEngine.cpp
  core/src/db/snapshot/CompoundOperations.cpp
  core/src/db/snapshot/CompoundOperations.h
  core/src/db/snapshot/Event.h
  core/src/db/snapshot/EventExecutor.h
  core/src/db/snapshot/OperationExecutor.h
  core/src/db/snapshot/Operations.cpp
  core/src/db/snapshot/Operations.h
  core/src/db/snapshot/ResourceHolder.h
  core/src/db/snapshot/ResourceOperations.cpp
  core/src/db/snapshot/ResourceOperations.h
  core/src/db/snapshot/Snapshot.cpp
  core/src/db/snapshot/Snapshot.h
  core/src/db/snapshot/SnapshotHolder.cpp
  core/src/db/snapshot/SnapshotHolder.h
  core/src/db/snapshot/Snapshots.cpp
  core/src/db/snapshot/Snapshots.h
  core/src/db/snapshot/Store.h
  core/unittest/ssdb/test_snapshot.cpp
  core/unittest/ssdb/test_ss_meta.cpp
  core/unittest/ssdb/utils.cpp
  core/unittest/ssdb/utils.h
Labels: automerge, type/enhancement

#2906 add case index nprobe
  tests/milvus_python_test/entity/test_search.py
Labels: automerge

#2924 (db/snapshot): add AddSegmentFileOperation
  core/src/db/snapshot/CompoundOperations.cpp
  core/src/db/snapshot/CompoundOperations.h
  core/unittest/ssdb/test_snapshot.cpp
  core/unittest/ssdb/utils.h
Labels: automerge, type/new-feature

#2896 (db/snapshot) Optimize snapshot mock db
  core/src/db/meta/MetaAdapter.h
  core/src/db/meta/MetaSession.h
  core/src/db/meta/backend/MockMetaEngine.cpp
  core/src/db/meta/backend/MySqlEngine.cpp
  core/unittest/ssdb/test_ss_meta.cpp
Labels: automerge, type/enhancement

#2900 Rearrange core cmakelists
  core/CMakeLists.txt
  core/cmake/BuildUtils.cmake
  core/cmake/Utils.cmake
  core/src/version.h.in
Labels: automerge

#2920 add web_impl testcase
  core/src/server/web_impl/utils/Util.cpp
  core/unittest/db/test_web.cpp
Labels: automerge

#2927 refine code
  core/src/codecs/snapshot/SSStructuredIndexFormat.cpp
  core/src/codecs/snapshot/SSStructuredIndexFormat.h
  core/src/codecs/snapshot/SSVectorIndexFormat.h
  core/src/db/SSDBImpl.cpp
  core/src/db/SSDBImpl.h
  core/src/db/engine/SSExecutionEngine.h
  core/src/db/engine/SSExecutionEngineImpl.cpp
  core/src/db/engine/SSExecutionEngineImpl.h
  core/src/query/GeneralQuery.h
  core/src/segment/SSSegmentReader.cpp
  core/src/segment/SSSegmentReader.h
  core/src/segment/SSSegmentWriter.cpp
  core/src/segment/SSSegmentWriter.h
  core/src/segment/Segment.cpp
  core/src/segment/Segment.h
Labels: automerge

#2926 (db/snapshot): add GC event and implement crtp for base resource
  core/src/db/snapshot/BaseResource.h
  core/src/db/snapshot/Event.h
  core/src/db/snapshot/InActiveResourcesGCEvent.h
  core/src/db/snapshot/Resources.h
  core/src/db/snapshot/Snapshots.cpp
  core/src/db/snapshot/Store.h
  core/unittest/ssdb/test_snapshot.cpp
Labels: automerge, type/new-feature

#2936 (db/snapshot) Add root path for snapshot GC
  core/src/db/Utils.cpp
  core/src/db/Utils.h
  core/src/db/snapshot/Event.h
  core/src/db/snapshot/Operations.cpp
  core/src/db/snapshot/ResourceHelper.h
  core/src/db/snapshot/ResourceHolder.h
  core/src/utils/StringHelpFunctions.cpp
  core/src/utils/StringHelpFunctions.h
  core/unittest/server/test_util.cpp
Labels: automerge, type/enhancement

#2930 #2890 Fix wrong index size
  CHANGELOG.md
  core/src/codecs/default/DefaultVectorIndexFormat.cpp
  core/src/codecs/snapshot/SSVectorIndexFormat.cpp
  core/src/db/Utils.cpp
  core/src/db/engine/ExecutionEngineImpl.cpp
  core/src/db/meta/MetaTypes.h
  core/src/index/knowhere/CMakeLists.txt
  core/src/index/knowhere/knowhere/index/IndexType.cpp
  core/src/index/knowhere/knowhere/index/IndexType.h
  core/src/index/knowhere/knowhere/index/vector_index/ConfAdapterMgr.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexAnnoy.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexAnnoy.h
  core/src/index/knowhere/knowhere/index/vector_index/IndexBinaryIVF.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexBinaryIVF.h
  core/src/index/knowhere/knowhere/index/vector_index/IndexHNSW.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexHNSW.h
  core/src/index/knowhere/knowhere/index/vector_index/IndexIVF.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexIVF.h
  core/src/index/knowhere/knowhere/index/vector_index/IndexIVFPQ.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexIVFPQ.h
  core/src/index/knowhere/knowhere/index/vector_index/IndexIVFSQ.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexIVFSQ.h
  core/src/index/knowhere/knowhere/index/vector_index/IndexNSG.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexSPTAG.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexSPTAG.h
  core/src/index/knowhere/knowhere/index/vector_index/VecIndex.h
  core/src/index/knowhere/knowhere/index/vector_index/VecIndexFactory.cpp
  core/src/index/knowhere/knowhere/index/vector_index/gpu/IndexIVFSQHybrid.cpp
  core/src/index/knowhere/knowhere/index/vector_index/gpu/IndexIVFSQHybrid.h
  core/src/index/knowhere/knowhere/index/vector_index/impl/nsg/NSG.cpp
  core/src/index/knowhere/knowhere/index/vector_index/impl/nsg/NSG.h
  core/src/index/knowhere/knowhere/index/vector_offset_index/IndexHNSW_NM.cpp
  core/src/index/knowhere/knowhere/index/vector_offset_index/IndexHNSW_NM.h
  core/src/index/knowhere/knowhere/index/vector_offset_index/IndexHNSW_SQ8NM.cpp
  core/src/index/knowhere/knowhere/index/vector_offset_index/IndexHNSW_SQ8NM.h
  core/src/index/knowhere/knowhere/index/vector_offset_index/IndexIVFSQNR_NM.cpp
  core/src/index/knowhere/knowhere/index/vector_offset_index/IndexIVFSQNR_NM.h
  core/src/index/knowhere/knowhere/index/vector_offset_index/IndexIVF_NM.cpp
  core/src/index/knowhere/knowhere/index/vector_offset_index/IndexIVF_NM.h
  core/src/index/knowhere/knowhere/index/vector_offset_index/IndexNSG_NM.cpp
  core/src/index/knowhere/knowhere/index/vector_offset_index/IndexNSG_NM.h
  core/src/index/thirdparty/SPTAG/AnnService/inc/Core/BKT/Index.h
  core/src/index/thirdparty/SPTAG/AnnService/inc/Core/KDT/Index.h
  core/src/index/thirdparty/SPTAG/AnnService/inc/Core/VectorIndex.h
  core/src/index/thirdparty/annoy/src/annoylib.h
  core/src/index/thirdparty/hnswlib/hnswalg.h
  core/src/index/thirdparty/hnswlib/hnswalg_nm.h
  core/src/index/thirdparty/hnswlib/visited_list_pool.h
  core/src/index/unittest/CMakeLists.txt
  core/src/index/unittest/test_hnsw_sq8nm.cpp
  core/src/index/unittest/test_ivf.cpp
  core/src/server/ValidationUtil.cpp
  core/src/server/web_impl/Constants.cpp
  core/src/server/web_impl/Constants.h
  core/unittest/server/test_cache.cpp
  sdk/examples/simple/src/ClientTest.cpp
  sdk/examples/utils/Utils.cpp
  sdk/include/MilvusApi.h
Labels: automerge, type/enhancement

#2942 #2890 Fix wrong index size
  core/src/index/knowhere/knowhere/index/vector_offset_index/IndexHNSW_NM.cpp
  core/src/index/knowhere/knowhere/index/vector_offset_index/IndexIVFSQNR_NM.cpp
  core/src/index/knowhere/knowhere/index/vector_offset_index/IndexIVF_NM.cpp
  core/src/index/knowhere/knowhere/index/vector_offset_index/IndexNSG_NM.cpp
Labels: automerge

#2946 [skip-ci] Minor editorial updates.
  README.md
  README_CN.md
Labels: Documentation

#2909 [skip ci]fix cuda version requirement
  INSTALL.md
Labels: automerge

#2961 snapshot scheduler
  core/src/db/SSDBImpl.cpp
  core/src/db/SSDBImpl.h
  core/src/db/Types.h
  core/src/scheduler/TaskCreator.cpp
  core/src/scheduler/job/SSBuildIndexJob.cpp
  core/src/scheduler/job/SSBuildIndexJob.h
  core/src/scheduler/job/SSSearchJob.cpp
  core/src/scheduler/job/SSSearchJob.h
  core/src/scheduler/task/SSBuildIndexTask.cpp
  core/src/scheduler/task/SSBuildIndexTask.h
  core/src/scheduler/task/SSSearchTask.cpp
  core/src/scheduler/task/SSSearchTask.h
  core/src/scheduler/task/SSTestTask.cpp
  core/unittest/ssdb/test_db.cpp
  core/unittest/ssdb/test_ss_job.cpp
  core/unittest/ssdb/test_ss_task.cpp
  core/unittest/ssdb/utils.cpp
  core/unittest/ssdb/utils.h
Labels: automerge, type/new-feature

#2947 (db/snapshot): Update DropAllIndexOperation
  core/src/db/SSDBImpl.cpp
  core/src/db/snapshot/CompoundOperations.cpp
  core/src/db/snapshot/Context.cpp
  core/src/db/snapshot/Context.h
  core/src/db/snapshot/ResourceOperations.cpp
  core/unittest/ssdb/test_snapshot.cpp
Labels: automerge, type/new-feature

#2958 fix a bug of annoy search parameter exisitence check
  CHANGELOG.md
  core/src/index/knowhere/knowhere/index/vector_index/ConfAdapter.cpp
Labels: automerge

#2945 (db/snapshot) Add root path for snapshot store
  core/src/db/Utils.cpp
  core/src/db/Utils.h
  core/src/db/snapshot/Event.h
  core/src/db/snapshot/Operations.cpp
  core/src/db/snapshot/ResourceHelper.h
  core/src/db/snapshot/ResourceHolder.h
  core/src/db/snapshot/Snapshot.h
  core/src/db/snapshot/Store.h
  core/src/utils/StringHelpFunctions.cpp
  core/src/utils/StringHelpFunctions.h
  core/unittest/server/test_util.cpp
  core/unittest/ssdb/utils.cpp
Labels: automerge, type/enhancement

#2955 Fix the result merging of IVF_PQ IP
  CHANGELOG.md
  core/src/scheduler/task/SearchTask.cpp
Labels: automerge

#2960 (db/snapshot) Inactivate gc event
  core/src/config/Utils.cpp
  core/src/db/SSDBImpl.cpp
  core/src/db/meta/MetaAdapter.h
  core/src/db/meta/MetaSession.h
  core/src/db/meta/backend/MetaContext.h
  core/src/db/meta/backend/MetaHelper.cpp
  core/src/db/meta/backend/MockMetaEngine.cpp
  core/src/db/snapshot/InActiveResourcesGCEvent.h
  core/src/db/snapshot/Store.h
  core/unittest/ssdb/CMakeLists.txt
  core/unittest/ssdb/test_ss_event.cpp
  core/unittest/ssdb/test_ss_meta.cpp
  core/unittest/ssdb/utils.cpp
  core/unittest/ssdb/utils.h
Labels: automerge, type/new-feature

#2972 add Macro MILVUS_USE_SNAPSHOT
  core/CMakeLists.txt
  core/src/db/DB.h
  core/src/db/DBFactory.cpp
  core/src/db/DBImpl.h
  core/src/db/SSDBImpl.h
Labels: type/new-feature

#2979 build snapshot index
  core/src/codecs/snapshot/SSVectorIndexFormat.cpp
  core/src/db/DB.h
  core/src/db/DBFactory.cpp
  core/src/db/DBFactory.h
  core/src/db/DBImpl.h
  core/src/db/SSDB.h
  core/src/db/SSDBImpl.cpp
  core/src/db/SSDBImpl.h
  core/src/db/SnapshotUtils.cpp
  core/src/db/SnapshotUtils.h
  core/src/db/SnapshotVisitor.cpp
  core/src/db/SnapshotVisitor.h
  core/src/db/attr/InstanceStructuredIndex.cpp
  core/src/db/engine/SSExecutionEngineImpl.cpp
  core/src/db/engine/SSExecutionEngineImpl.h
  core/src/segment/SSSegmentReader.cpp
  core/src/segment/SSSegmentWriter.cpp
  core/src/segment/Segment.cpp
  core/src/segment/Segment.h
  core/src/server/DBWrapper.cpp
  core/src/server/DBWrapper.h
  core/unittest/CMakeLists.txt
  core/unittest/ssdb/CMakeLists.txt
  core/unittest/ssdb/test_ss_job.cpp
  core/unittest/ssdb/test_ss_task.cpp
  core/unittest/ssdb/utils.cpp
Labels: automerge

#2981 Fix #2975
  CHANGELOG.md
  core/src/config/Config.cpp
Labels: automerge

#2982 grpc partition related APIs use snapshot
  core/CMakeLists.txt
  core/src/db/DBFactory.cpp
  core/src/db/DBImpl.cpp
  core/src/db/DBImpl.h
  core/src/db/SSDB.h
  core/src/db/SSDBImpl.cpp
  core/src/db/SSDBImpl.h
  core/src/server/delivery/RequestHandler.cpp
  core/src/server/delivery/RequestHandler.h
  core/src/server/delivery/request/BaseRequest.h
  core/src/server/delivery/request/CreatePartitionRequest.cpp
  core/src/server/delivery/request/CreatePartitionRequest.h
  core/src/server/delivery/request/DropPartitionRequest.cpp
  core/src/server/delivery/request/ShowPartitionsRequest.cpp
  core/src/server/delivery/request/ShowPartitionsRequest.h
  core/src/server/grpc_impl/GrpcRequestHandler.cpp
  core/src/server/web_impl/handler/WebRequestHandler.cpp
Labels: automerge, type/new-feature

#2983 Rearrange CMakeLists of lib query and lib search
  core/build.sh
  core/src/CMakeLists.txt
  core/src/index/build.sh
  core/src/index/knowhere/CMakeLists.txt
  core/src/query/CMakeLists.txt
  core/src/search/CMakeLists.txt
Labels: automerge

#2986 Rearrange CMakeLists.txt of lib tracing
  core/src/CMakeLists.txt
  core/src/tracing/CMakeLists.txt
Labels: automerge

#2987 insert entity request
  core/src/db/SSDB.h
  core/src/db/SSDBImpl.cpp
  core/src/db/SSDBImpl.h
  core/src/db/SnapshotUtils.cpp
  core/src/db/engine/SSExecutionEngineImpl.cpp
  core/src/db/insert/SSMemSegment.cpp
  core/src/db/meta/MetaTypes.h
  core/src/db/snapshot/Context.h
  core/src/db/snapshot/Store.h
  core/src/segment/Segment.cpp
  core/src/server/delivery/RequestHandler.cpp
  core/src/server/delivery/RequestHandler.h
  core/src/server/delivery/hybrid_request/InsertEntityRequest.cpp
  core/src/server/delivery/hybrid_request/InsertEntityRequest.h
  core/src/server/grpc_impl/GrpcRequestHandler.cpp
  core/src/server/web_impl/handler/WebRequestHandler.cpp
  core/unittest/ssdb/test_db.cpp
Labels: automerge

#2978 (db/snapshot): fix GC behavior
  core/src/db/SSDBImpl.cpp
  core/src/db/snapshot/Event.h
  core/src/db/snapshot/Store.h
  core/unittest/ssdb/utils.cpp
  core/unittest/ssdb/utils.h
Labels: automerge, type/enhancement

#2996 optimize config code
  .github/PULL_REQUEST_TEMPLATE.md
  core/src/config/ServerConfig.h
Labels: automerge

#2997 (scalar | db/snapshot) Fix HasPartition()
  core/src/db/SSDB.h
  core/src/db/SSDBImpl.cpp
  core/src/db/SSDBImpl.h
  core/src/server/delivery/request/HasPartitionRequest.cpp
Labels: Bug, automerge

#3002 refine code
  core/src/db/DBImpl.cpp
  core/src/db/SSDBImpl.cpp
  core/src/db/SnapshotUtils.cpp
  core/src/db/Types.h
  core/src/db/Utils.cpp
  core/src/db/Utils.h
  core/src/db/meta/MetaTypes.h
  core/src/db/meta/MySQLMetaImpl.cpp
  core/src/db/meta/SqliteMetaImpl.cpp
  core/src/grpc/gen-milvus/milvus.grpc.pb.cc
  core/src/grpc/gen-milvus/milvus.grpc.pb.h
  core/src/grpc/gen-milvus/milvus.pb.cc
  core/src/grpc/gen-milvus/milvus.pb.h
  core/src/grpc/milvus.proto
  core/src/server/ValidationUtil.cpp
  core/src/server/ValidationUtil.h
  core/src/server/delivery/request/CreateIndexRequest.cpp
  core/src/server/delivery/request/DescribeIndexRequest.cpp
  core/src/server/grpc_impl/GrpcRequestHandler.cpp
  core/src/server/grpc_impl/GrpcRequestHandler.h
Labels: automerge

#3006 [skip ci] Up to v0.10.2
  core/CMakeLists.txt
Labels: automerge

#3008 [skip ci] update pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: automerge

#3005 Rearrange CMlists dir db
  core/CMakeLists.txt
  core/src/CMakeLists.txt
  core/src/db/CMakeLists.txt
  core/src/tracing/CMakeLists.txt
Labels: automerge

#3010 Rearrange CMLists for dir Metrics
  core/src/CMakeLists.txt
  core/src/metrics/CMakeLists.txt
Labels: automerge

#3020 add dependency for log module
  core/src/log/CMakeLists.txt
Labels: automerge

#3024 remove unused code
  core/src/CMakeLists.txt
  core/unittest/CMakeLists.txt
Labels: automerge

#3030 (scalar) Rename dimension to dim in dev test case
  tests/milvus_python_test/collection/test_create_collection.py
  tests/milvus_python_test/conftest.py
  tests/milvus_python_test/utils.py
Labels: Bug, automerge

#3028 (db/snapshot) Remove sqlite-orm
  CHANGELOG.md
  core/cmake/DefineOptions.cmake
  core/cmake/ThirdPartyPackages.cmake
  core/src/db/DBFactory.cpp
  core/src/db/Options.cpp
  core/src/db/meta/MetaFactory.cpp
  core/src/db/meta/MetaFactory.h
  core/src/db/meta/MySQLMetaImpl.cpp
  core/src/db/meta/SqliteMetaImpl.cpp
  core/src/db/meta/SqliteMetaImpl.h
  core/src/db/snapshot/Store.h
  core/thirdparty/versions.txt
  core/unittest/db/test_ss_task.cpp
  core/unittest/scheduler/test_task.cpp
Labels: automerge, type/enhancement

#3031 (scalar | snapshot) Add return value status fixing case test_add_entity_and_compact crash
  core/src/db/SnapshotHandlers.cpp
Labels: Bug, automerge

#3034 (scalar) [skip ci] Remove milvus IndexType,MetricType import operation
  tests/milvus_python_test/collection/test_collection_count.py
  tests/milvus_python_test/collection/test_collection_logic.py
  tests/milvus_python_test/collection/test_create_collection.py
  tests/milvus_python_test/collection/test_drop_collection.py
  tests/milvus_python_test/collection/test_has_collection.py
  tests/milvus_python_test/collection/test_list_collections.py
  tests/milvus_python_test/collection/test_load_collection.py
  tests/milvus_python_test/conftest.py
  tests/milvus_python_test/entity/test_list_id_in_segment.py
  tests/milvus_python_test/stability/test_mysql.py
  tests/milvus_python_test/test_compact.py
  tests/milvus_python_test/test_flush.py
  tests/milvus_python_test/utils.py
Labels: Bug, automerge

#3025 update sdk version on 0.10.2
  tests/milvus_python_test/requirements.txt
Labels: automerge

#3040 remove SS
  .github/PULL_REQUEST_TEMPLATE.md
  core/src/db/DBImpl.cpp
  core/src/db/engine/EngineFactory.cpp
  core/src/db/engine/EngineFactory.h
  core/src/db/engine/ExecutionEngine.h
  core/src/db/insert/MemCollection.h
  core/src/db/insert/MemManagerImpl.cpp
  core/src/db/insert/MemManagerImpl.h
  core/src/scheduler/Definition.h
  core/src/scheduler/TaskCreator.cpp
  core/src/scheduler/TaskCreator.h
  core/src/scheduler/job/BuildIndexJob.h
  core/src/scheduler/job/SearchJob.h
  core/src/scheduler/task/BuildIndexTask.h
  core/src/scheduler/task/SearchTask.h
  core/unittest/db/test_ss_job.cpp
Labels: automerge

#3038 (db/snapshot) Fix sqlite start fail
  core/CMakeLists.txt
  core/src/db/meta/MetaFactory.cpp
  core/src/index/thirdparty/faiss/IndexBinaryIVF.cpp
  core/src/index/thirdparty/faiss/InvertedLists.cpp
  core/src/index/thirdparty/faiss/gpu/GpuCloner.cpp
  core/src/index/thirdparty/faiss/impl/ScalarQuantizer.cpp
  core/src/scheduler/task/SearchTask.cpp
Labels: Bug, automerge

#3035 (snapshot/db): fix GC bug and some enhancement
  core/src/codecs/Codec.cpp
  core/src/codecs/Codec.h
  core/src/db/DBImpl.cpp
  core/src/db/meta/MetaResourceAttrs.cpp
  core/src/db/meta/backend/MySqlEngine.cpp
  core/src/db/meta/backend/SqliteEngine.cpp
  core/src/db/snapshot/EventExecutor.h
  core/src/db/snapshot/HandlerFactory.h
  core/src/db/snapshot/InActiveResourcesGCEvent.h
  core/src/db/snapshot/MetaEvent.h
  core/src/db/snapshot/Operations.cpp
  core/src/db/snapshot/ResourceGCEvent.h
  core/src/db/snapshot/ResourceHelper.h
  core/src/db/snapshot/ResourceHolder.h
  core/src/db/snapshot/ResourceOperations.cpp
  core/src/db/snapshot/Resources.cpp
  core/src/db/snapshot/Resources.h
  core/src/db/snapshot/Snapshot.cpp
  core/src/db/snapshot/Store.h
  core/unittest/db/test_db.cpp
  core/unittest/db/test_snapshot.cpp
  core/unittest/db/test_ss_event.cpp
  core/unittest/db/utils.cpp
  core/unittest/db/utils.h
Labels: Bug, automerge, type/enhancement

#3044 refine scheduler job task
  core/src/db/CMakeLists.txt
  core/src/db/DBImpl.cpp
  core/src/db/DBImpl.h
  core/src/db/engine/ExecutionEngine.h
  core/src/scheduler/JobMgr.cpp
  core/src/scheduler/TaskCreator.cpp
  core/src/scheduler/job/BuildIndexJob.cpp
  core/src/scheduler/job/BuildIndexJob.h
  core/src/scheduler/job/DeleteJob.cpp
  core/src/scheduler/job/DeleteJob.h
  core/src/scheduler/job/Job.cpp
  core/src/scheduler/job/Job.h
  core/src/scheduler/job/SearchJob.cpp
  core/src/scheduler/job/SearchJob.h
  core/src/scheduler/selector/FaissFlatPass.cpp
  core/src/scheduler/selector/FaissIVFFlatPass.cpp
  core/src/scheduler/selector/FaissIVFPQPass.cpp
  core/src/scheduler/selector/FaissIVFSQ8HPass.cpp
  core/src/scheduler/selector/FaissIVFSQ8Pass.cpp
  core/src/scheduler/task/BuildIndexTask.cpp
  core/src/scheduler/task/BuildIndexTask.h
  core/src/scheduler/task/SearchTask.cpp
  core/src/scheduler/task/SearchTask.h
  core/src/scheduler/task/Task.cpp
  core/src/scheduler/task/Task.h
  core/src/scheduler/task/TestTask.cpp
  core/src/scheduler/task/TestTask.h
  core/src/segment/SegmentWriter.cpp
  core/unittest/CMakeLists.txt
  core/unittest/db/CMakeLists.txt
  core/unittest/scheduler/CMakeLists.txt
  core/unittest/scheduler/test_job.cpp
  core/unittest/scheduler/test_resource.cpp
  core/unittest/scheduler/test_resource_mgr.cpp
  core/unittest/scheduler/test_selector.cpp
  core/unittest/scheduler/test_task.cpp
  core/unittest/scheduler/test_tasktable.cpp
Labels: automerge

#3048 [skip ci] remove wrong file
  sdk/include/MilvusApi.h.0726
Labels: automerge

#3047 Remove repeated built src files in unittest/CMakeLists
  core/src/CMakeLists.txt
  core/src/db/CMakeLists.txt
  core/src/utils/CMakeLists.txt
  core/unittest/CMakeLists.txt
  core/unittest/db/CMakeLists.txt
Labels: automerge

#3052 clean code
  core/src/CMakeLists.txt
  core/src/codecs/StructuredIndexFormat.cpp
  core/src/codecs/VectorCompressFormat.cpp
  core/src/codecs/VectorIndexFormat.cpp
  core/src/context/SearchContext.h
  core/src/db/DBImpl.cpp
  core/src/db/SnapshotHandlers.h
  core/src/db/SnapshotVisitor.h
  core/src/db/Utils.cpp
  core/src/db/Utils.h
  core/src/db/engine/EngineFactory.cpp
  core/src/db/engine/EngineFactory.h
  core/src/db/engine/ExecutionEngine.h
  core/src/db/engine/ExecutionEngineImpl.cpp
  core/src/db/engine/ExecutionEngineImpl.h
  core/src/db/insert/MemCollection.cpp
  core/src/db/insert/MemManagerFactory.h
  core/src/db/insert/MemSegment.cpp
  core/src/db/merge/MergeManager.h
  core/src/db/merge/MergeTask.cpp
  core/src/db/meta/FilesHolder.cpp
  core/src/db/meta/FilesHolder.h
  core/src/db/meta/Meta.cpp
  core/src/db/meta/Meta.h
  core/src/db/meta/MetaTypes.h
  core/src/db/meta/MySQLMetaImpl.cpp
  core/src/db/meta/MySQLMetaImpl.h
  core/src/db/wal/WalDefinations.h
  core/src/db/wal/WalManager.cpp
  core/src/db/wal/WalManager.h
  core/src/db/wal/WalMetaHandler.h
  core/src/metrics/Metrics.h
  core/src/scheduler/Definition.h
  core/src/scheduler/job/BuildIndexJob.cpp
  core/src/scheduler/job/SearchJob.h
  core/src/scheduler/task/BuildIndexTask.cpp
  core/src/scheduler/task/BuildIndexTask.h
  core/src/search/CMakeLists.txt
  core/src/search/Task.cpp
  core/src/search/Task.h
  core/src/search/TaskInst.cpp
  core/src/search/TaskInst.h
  core/src/segment/SegmentReader.cpp
  core/src/segment/SegmentWriter.cpp
  core/src/server/Server.cpp
  core/src/server/ValidationUtil.cpp
  core/src/server/ValidationUtil.h
  core/src/server/delivery/request/CreateCollectionReq.cpp
  core/src/server/delivery/request/GetCollectionInfoReq.cpp
  core/unittest/metrics/test_metrics.cpp
  core/unittest/scheduler/test_resource.cpp
  core/unittest/scheduler/test_resource_mgr.cpp
  core/unittest/scheduler/test_scheduler.cpp
  core/unittest/scheduler/test_task.cpp
  core/unittest/scheduler/test_tasktable.cpp
Labels: automerge

#3051 (db/snapshot) Update InactiveResourceGCEvent
  core/src/db/snapshot/InActiveResourcesGCEvent.h
  core/src/db/snapshot/MetaEvent.h
  core/src/db/snapshot/ResourceGCEvent.h
Labels: Bug, automerge, type/enhancement

#3050 (snapshot/db): add ChangeSegmentFileOperation and related test
  core/src/db/engine/ExecutionEngineImpl.cpp
  core/src/db/snapshot/CompoundOperations.cpp
  core/src/db/snapshot/CompoundOperations.h
  core/src/db/snapshot/Context.cpp
  core/src/db/snapshot/Context.h
  core/src/db/snapshot/ResourceOperations.cpp
  core/unittest/db/test_snapshot.cpp
  core/unittest/db/utils.h
Labels: automerge, type/enhancement

#3054 refine code
  core/src/db/engine/ExecutionEngineImpl.cpp
  core/src/db/engine/ExecutionEngineImpl.h
  core/src/segment/SegmentReader.h
Labels: automerge

#3056 build index
  core/src/codecs/StructuredIndexFormat.cpp
  core/src/codecs/StructuredIndexFormat.h
  core/src/db/DBImpl.cpp
  core/src/db/SnapshotUtils.cpp
  core/src/db/Types.cpp
  core/src/db/Types.h
  core/src/db/engine/EngineFactory.cpp
  core/src/db/engine/ExecutionEngineImpl.cpp
  core/src/db/engine/ExecutionEngineImpl.h
  core/src/db/insert/MemManagerImpl.cpp
  core/src/db/insert/MemSegment.cpp
  core/src/db/meta/MetaTypes.h
  core/src/scheduler/Definition.h
  core/src/segment/Segment.h
  core/src/segment/SegmentReader.cpp
  core/src/server/delivery/ReqHandler.cpp
  core/src/server/delivery/ReqHandler.h
  core/src/server/delivery/request/BaseReq.h
  core/src/server/delivery/request/CreateCollectionReq.cpp
  core/src/server/delivery/request/CreateCollectionReq.h
  core/src/server/delivery/request/GetCollectionInfoReq.cpp
  core/src/server/delivery/request/GetEntityByIDReq.cpp
  core/src/server/delivery/request/SearchReq.cpp
  core/src/server/grpc_impl/GrpcRequestHandler.cpp
  core/src/server/grpc_impl/GrpcRequestHandler.h
  core/src/server/web_impl/handler/WebRequestHandler.cpp
  core/src/server/web_impl/handler/WebRequestHandler.h
  core/unittest/db/test_db.cpp
  core/unittest/db/utils.cpp
  core/unittest/db/utils.h
Labels: automerge

#3057 (db/snapshot): add CompoundSegmentsOperation and related test
  core/src/db/snapshot/CompoundOperations.cpp
  core/src/db/snapshot/CompoundOperations.h
  core/src/db/snapshot/ResourceOperations.cpp
  core/unittest/db/test_snapshot.cpp
  core/unittest/db/utils.h
Labels: automerge, type/new-feature

#3061 fix collection ci
  core/src/config/ConfigMgr.cpp
  core/src/config/ConfigMgr.h
  core/src/db/DBImpl.cpp
  core/src/db/DBImpl.h
  core/src/db/Types.cpp
  core/src/db/Types.h
  core/src/segment/SegmentReader.cpp
  core/src/server/delivery/ReqHandler.cpp
  core/src/server/delivery/ReqHandler.h
  core/src/server/delivery/request/BaseReq.h
  core/src/server/delivery/request/CreateCollectionReq.cpp
  core/src/server/delivery/request/CreateCollectionReq.h
  core/src/server/delivery/request/GetCollectionInfoReq.cpp
  core/src/server/grpc_impl/GrpcRequestHandler.cpp
  core/src/server/grpc_impl/GrpcRequestHandler.h
  core/src/server/web_impl/handler/WebRequestHandler.cpp
Labels: automerge, type/new-feature

#3058 build index
  core/CMakeLists.txt
  core/src/codecs/DeletedDocsFormat.h
  core/src/codecs/IdBloomFilterFormat.h
  core/src/codecs/StructuredIndexFormat.h
  core/src/codecs/VectorCompressFormat.h
  core/src/codecs/VectorIndexFormat.h
  core/src/db/DBImpl.cpp
  core/src/db/engine/EngineFactory.cpp
  core/src/db/engine/EngineFactory.h
  core/src/db/engine/ExecutionEngine.h
  core/src/db/engine/ExecutionEngineImpl.cpp
  core/src/scheduler/job/BuildIndexJob.cpp
  core/src/scheduler/job/BuildIndexJob.h
  core/src/scheduler/job/Job.cpp
  core/src/scheduler/job/Job.h
  core/src/scheduler/job/SearchJob.cpp
  core/src/scheduler/job/SearchJob.h
  core/src/scheduler/task/BuildIndexTask.cpp
  core/src/scheduler/task/BuildIndexTask.h
  core/src/scheduler/task/SearchTask.cpp
  core/src/segment/SegmentReader.cpp
  core/src/segment/SegmentReader.h
  core/src/segment/SegmentWriter.cpp
  core/src/segment/SegmentWriter.h
  core/unittest/db/test_db.cpp
  core/unittest/db/utils.cpp
Labels: automerge

#3066 fix build index bug
  core/src/db/DBImpl.cpp
  core/src/db/SnapshotUtils.cpp
  core/src/db/Types.cpp
  core/src/db/Types.h
  core/src/db/Utils.cpp
  core/src/db/Utils.h
  core/src/db/engine/ExecutionEngineImpl.cpp
  core/src/db/meta/MetaTypes.h
  core/src/scheduler/job/BuildIndexJob.cpp
  core/src/segment/SegmentWriter.cpp
  core/src/server/ValidationUtil.cpp
  core/src/server/ValidationUtil.h
  core/src/server/delivery/request/CreateCollectionReq.cpp
  core/src/server/delivery/request/CreateIndexReq.cpp
  core/src/server/delivery/request/SearchReq.cpp
  core/src/server/grpc_impl/GrpcRequestHandler.cpp
  core/src/server/web_impl/handler/WebRequestHandler.cpp
  core/src/utils/Error.h
  core/unittest/db/test_db.cpp
  core/unittest/db/test_segment.cpp
Labels: automerge

#3059 ThirdParty libs won't be re-downloaded after make clean
  core/CMakeLists.txt
  core/cmake/ThirdPartyPackages.cmake
  core/src/CMakeLists.txt
  core/src/config/CMakeLists.txt
  core/src/db/CMakeLists.txt
  core/src/log/CMakeLists.txt
  core/src/metrics/CMakeLists.txt
  core/src/query/CMakeLists.txt
  core/src/tracing/CMakeLists.txt
  core/src/utils/CMakeLists.txt
  core/unittest/CMakeLists.txt
  core/unittest/db/CMakeLists.txt
Labels: automerge

#3069 get collection stats
  core/src/db/DB.h
  core/src/db/DBImpl.cpp
  core/src/db/DBImpl.h
  core/src/db/SnapshotUtils.cpp
  core/src/db/SnapshotUtils.h
  core/src/db/Types.h
  core/src/db/merge/MergeSimpleStrategy.cpp
  core/src/db/merge/MergeStrategy.h
  core/src/db/meta/MetaTypes.h
  core/src/scheduler/Definition.h
  core/src/scheduler/selector/FaissFlatPass.cpp
  core/src/scheduler/selector/FaissIVFFlatPass.cpp
  core/src/scheduler/selector/FaissIVFPQPass.cpp
  core/src/scheduler/selector/FaissIVFSQ8HPass.cpp
  core/src/scheduler/selector/FaissIVFSQ8Pass.cpp
  core/src/server/delivery/request/CreateCollectionReq.cpp
  core/src/server/delivery/request/DeleteEntityByIDReq.cpp
  core/src/server/delivery/request/GetCollectionStatsReq.cpp
  core/src/server/web_impl/handler/WebRequestHandler.cpp
  core/unittest/db/test_db.cpp
Labels: automerge

#3065 add field name and segment size validation check when create collection
  core/src/db/DBImpl.cpp
  core/src/db/Types.h
  core/src/db/snapshot/ReferenceProxy.h
  core/src/server/ValidationUtil.cpp
  core/src/server/ValidationUtil.h
  core/src/server/delivery/request/CreateCollectionReq.cpp
  core/src/server/delivery/request/CreateCollectionReq.h
  core/src/server/delivery/request/DropCollectionReq.cpp
  core/src/server/delivery/request/GetCollectionInfoReq.cpp
  core/src/server/delivery/request/GetCollectionInfoReq.h
  core/src/server/delivery/request/GetCollectionStatsReq.cpp
  core/src/server/delivery/request/GetCollectionStatsReq.h
  core/src/server/delivery/request/HasCollectionReq.cpp
  core/src/server/delivery/request/ListCollectionsReq.cpp
Labels: automerge, type/new-feature

#3075 (db/snapshot): Handle timeout with external metastore
  core/src/db/snapshot/Operations.cpp
  core/src/db/snapshot/Operations.h
  core/src/db/snapshot/Store.h
  core/src/utils/Error.h
  core/unittest/db/utils.cpp
Labels: automerge, type/new-feature

#3072 remove MetaTypes.h
  core/src/codecs/StructuredIndexFormat.cpp
  core/src/codecs/StructuredIndexFormat.h
  core/src/db/DBImpl.cpp
  core/src/db/SnapshotHandlers.cpp
  core/src/db/SnapshotVisitor.cpp
  core/src/db/Types.h
  core/src/db/Utils.cpp
  core/src/db/Utils.h
  core/src/db/engine/ExecutionEngine.h
  core/src/db/engine/ExecutionEngineImpl.cpp
  core/src/db/engine/ExecutionEngineImpl.h
  core/src/db/insert/MemManagerImpl.cpp
  core/src/db/insert/MemSegment.cpp
  core/src/db/merge/MergeTask.h
  core/src/db/meta/MetaConsts.h
  core/src/db/meta/MetaTypes.h
  core/src/db/snapshot/Context.h
  core/src/db/snapshot/ResourceTypes.h
  core/src/db/snapshot/Store.h
  core/src/db/wal/WalDefinations.h
  core/src/db/wal/WalMetaHandler.h
  core/src/metrics/Metrics.h
  core/src/query/GeneralQuery.h
  core/src/scheduler/Definition.h
  core/src/segment/Segment.h
  core/src/segment/SegmentWriter.h
  core/src/server/ValidationUtil.h
  core/src/server/delivery/request/BaseReq.h
  core/src/server/delivery/request/CmdReq.cpp
  core/src/server/delivery/request/CreateCollectionReq.cpp
  core/src/server/delivery/request/GetCollectionInfoReq.cpp
  core/src/server/delivery/request/GetEntityByIDReq.cpp
  core/src/server/delivery/request/SearchReq.cpp
  core/src/server/grpc_impl/GrpcRequestHandler.cpp
  core/src/server/web_impl/handler/WebRequestHandler.cpp
  core/src/server/web_impl/handler/WebRequestHandler.h
  core/unittest/db/test_db.cpp
  core/unittest/db/test_segment.cpp
  core/unittest/db/test_ss_event.cpp
  core/unittest/db/test_ss_meta.cpp
  core/unittest/db/utils.h
Labels: automerge

#3060 (scalar) Update list-id-in-segment case
  core/src/db/DBImpl.cpp
  tests/milvus_python_test/entity/test_list_id_in_segment.py
Labels: Bug, automerge, type/enhancement

#3078 fix bug
  core/src/codecs/IdBloomFilterFormat.cpp
  core/src/db/DBImpl.cpp
  core/src/db/SnapshotUtils.cpp
  core/src/db/engine/ExecutionEngineImpl.cpp
  core/src/db/merge/MergeManager.h
  core/src/db/merge/MergeManagerFactory.cpp
  core/src/db/merge/MergeManagerImpl.cpp
  core/src/db/merge/MergeManagerImpl.h
  core/src/index/knowhere/knowhere/index/Index.h
  core/src/segment/SegmentWriter.cpp
  core/src/segment/SegmentWriter.h
  core/unittest/db/test_db.cpp
Labels: automerge

#3080 fix ci
  core/src/db/SnapshotUtils.cpp
  core/src/server/context/Context.cpp
  core/src/server/context/Context.h
  core/src/server/delivery/ReqQueue.cpp
  core/src/server/delivery/request/BaseReq.cpp
  core/src/server/delivery/request/BaseReq.h
  core/src/server/delivery/request/CmdReq.cpp
  core/src/server/delivery/request/CmdReq.h
  core/src/server/delivery/request/CompactReq.cpp
  core/src/server/delivery/request/CompactReq.h
  core/src/server/delivery/request/CountEntitiesReq.cpp
  core/src/server/delivery/request/CountEntitiesReq.h
  core/src/server/delivery/request/CreateCollectionReq.cpp
  core/src/server/delivery/request/CreateCollectionReq.h
  core/src/server/delivery/request/CreateIndexReq.cpp
  core/src/server/delivery/request/CreateIndexReq.h
  core/src/server/delivery/request/CreatePartitionReq.cpp
  core/src/server/delivery/request/CreatePartitionReq.h
  core/src/server/delivery/request/DeleteEntityByIDReq.cpp
  core/src/server/delivery/request/DeleteEntityByIDReq.h
  core/src/server/delivery/request/DropCollectionReq.cpp
  core/src/server/delivery/request/DropCollectionReq.h
  core/src/server/delivery/request/DropIndexReq.cpp
  core/src/server/delivery/request/DropIndexReq.h
  core/src/server/delivery/request/DropPartitionReq.cpp
  core/src/server/delivery/request/DropPartitionReq.h
  core/src/server/delivery/request/FlushReq.cpp
  core/src/server/delivery/request/FlushReq.h
  core/src/server/delivery/request/GetCollectionInfoReq.cpp
  core/src/server/delivery/request/GetCollectionInfoReq.h
  core/src/server/delivery/request/GetCollectionStatsReq.cpp
  core/src/server/delivery/request/GetCollectionStatsReq.h
  core/src/server/delivery/request/GetEntityByIDReq.cpp
  core/src/server/delivery/request/GetEntityByIDReq.h
  core/src/server/delivery/request/HasCollectionReq.cpp
  core/src/server/delivery/request/HasCollectionReq.h
  core/src/server/delivery/request/HasPartitionReq.cpp
  core/src/server/delivery/request/HasPartitionReq.h
  core/src/server/delivery/request/InsertReq.cpp
  core/src/server/delivery/request/InsertReq.h
  core/src/server/delivery/request/ListCollectionsReq.cpp
  core/src/server/delivery/request/ListCollectionsReq.h
  core/src/server/delivery/request/ListIDInSegmentReq.cpp
  core/src/server/delivery/request/ListIDInSegmentReq.h
  core/src/server/delivery/request/ListPartitionsReq.cpp
  core/src/server/delivery/request/ListPartitionsReq.h
  core/src/server/delivery/request/LoadCollectionReq.cpp
  core/src/server/delivery/request/LoadCollectionReq.h
  core/src/server/delivery/request/SearchReq.cpp
  core/src/server/delivery/request/SearchReq.h
  core/src/server/delivery/request/Types.cpp
  core/src/server/delivery/request/Types.h
  core/src/server/delivery/strategy/SearchReqStrategy.cpp
  core/src/server/grpc_impl/GrpcRequestHandler.cpp
Labels: automerge, type/enhancement
