Repository milvus-io/milvus, pull requests merged in 2020-03, with the labels that each got.

#1460 Add DCO content to CONTRIBUTING.md
  CHANGELOG.md
  CONTRIBUTING.md
Labels: type/docs

#1465 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: type/docs

#1470 Fix #839 and improve the code quality
  .codacy.yaml
  ci/scripts/build.sh
  core/src/db/DBImpl.cpp
  core/src/db/DBImpl.h
  core/src/db/meta/MySQLConnectionPool.h
  core/src/db/wal/WalManager.cpp
  core/src/db/wal/WalManager.h
Labels: type/bug, type/enhancement

#1469 Update NOTICE.md
  NOTICE.md
Labels: type/docs

#1473 Add pod tolerations to Jenkins slave pods
  ci/jenkins/pod/docker-pod.yaml
  ci/jenkins/pod/milvus-cpu-version-centos7-build-env-pod.yaml
  ci/jenkins/pod/milvus-cpu-version-ubuntu18.04-build-env-pod.yaml
  ci/jenkins/pod/milvus-gpu-version-centos7-build-env-pod.yaml
  ci/jenkins/pod/milvus-gpu-version-ubuntu18.04-build-env-pod.yaml
  ci/jenkins/pod/testEnvironment.yaml
Labels: type/performance

#1478 Update DESIGN.md
  DESIGN.md
Labels: type/docs

#1508 Fix duplicate vector ID issue
  CHANGELOG.md
  core/src/db/DBImpl.cpp
  core/src/db/IDGenerator.cpp
  core/src/db/IDGenerator.h
  core/src/db/insert/VectorSource.cpp
  core/src/db/insert/VectorSource.h
  core/src/db/meta/MySQLMetaImpl.cpp
  core/src/db/meta/SqliteMetaImpl.cpp
  core/unittest/db/test_db.cpp
  core/unittest/db/test_db_mysql.cpp
  core/unittest/db/test_misc.cpp
Labels: type/bug

#1543 [skip ci] update config preload_table description
  CHANGELOG.md
  core/conf/demo/server_config.yaml
  core/conf/server_cpu_config.template
  core/conf/server_gpu_config.template
Labels: type/enhancement

#1541 #1529 fix server crash when cache_insert_data enabled
  CHANGELOG.md
  core/src/db/engine/ExecutionEngineImpl.cpp
  core/src/index/knowhere/knowhere/index/vector_index/helpers/Cloner.cpp
Labels: type/bug

#1568 Caiyd 1567 update yaml description
  CHANGELOG.md
  core/conf/demo/server_config.yaml
  core/conf/server_cpu_config.template
  core/conf/server_gpu_config.template
Labels: type/docs

#1593 Update HTTP API doc for 0.7.0.
  core/src/server/web_impl/README.md
Labels: type/docs

#1602 fix link error in http doc
  CHANGELOG.md
  core/src/server/web_impl/README.md
  core/src/server/web_impl/controller/WebController.hpp
Labels: type/docs

#1621 Update docs for 0.7.0
  INSTALL.md
  README.md
  README_CN.md
  README_JP.md
Labels: type/docs

#1538 Caiyd codec opt
  CHANGELOG.md
  core/src/codecs/default/DefaultVectorsFormat.cpp
  core/src/codecs/default/DefaultVectorsFormat.h
Labels: type/enhancement

#1550 Caiyd 1546 move config
  CHANGELOG.md
  core/src/cache/CpuCacheMgr.cpp
  core/src/cache/GpuCacheMgr.cpp
  core/src/config/Config.cpp
  core/src/config/Config.h
  core/src/config/handler/CacheConfigHandler.cpp
  core/src/config/handler/ConfigHandler.h
  core/src/config/handler/GpuConfigHandler.h
  core/src/config/handler/GpuSearchConfigHandler.cpp
  core/src/db/Utils.cpp
  core/src/db/engine/ExecutionEngineImpl.cpp
  core/src/db/insert/MemManagerImpl.h
  core/src/db/wal/WalManager.cpp
  core/src/index/knowhere/knowhere/index/vector_index/helpers/FaissGpuResourceMgr.h
  core/src/metrics/Metrics.cpp
  core/src/metrics/prometheus/PrometheusMetrics.cpp
  core/src/scheduler/SchedInst.cpp
  core/src/scheduler/SchedInst.h
  core/src/scheduler/action/PushTaskToNeighbour.cpp
  core/src/scheduler/optimizer/FaissFlatPass.cpp
  core/src/scheduler/optimizer/FaissIVFFlatPass.cpp
  core/src/scheduler/optimizer/FaissIVFPQPass.cpp
  core/src/scheduler/optimizer/FaissIVFSQ8HPass.cpp
  core/src/scheduler/optimizer/FaissIVFSQ8Pass.cpp
  core/src/server/DBWrapper.cpp
  core/src/server/Server.cpp
  core/src/server/delivery/request/CmdRequest.cpp
  core/src/server/delivery/request/CreateIndexRequest.cpp
  core/src/server/delivery/request/SearchByIDRequest.cpp
  core/src/server/grpc_impl/GrpcRequestHandler.cpp
  core/src/server/grpc_impl/GrpcServer.cpp
  core/src/server/web_impl/WebServer.cpp
  core/src/server/web_impl/handler/WebRequestHandler.cpp
  core/src/storage/s3/S3ClientWrapper.cpp
  core/src/utils/CommonUtil.cpp
  core/src/wrapper/ConfAdapter.cpp
  core/src/wrapper/KnowhereResource.cpp
  core/src/wrapper/VecIndex.cpp
  core/unittest/CMakeLists.txt
  core/unittest/db/test_db.cpp
  core/unittest/metrics/test_metrics.cpp
  core/unittest/metrics/test_prometheus.cpp
  core/unittest/server/test_config.cpp
  core/unittest/server/test_rpc.cpp
  core/unittest/server/test_web.cpp
  core/unittest/storage/test_s3_client.cpp
  core/unittest/storage/utils.cpp
  core/unittest/wrapper/test_knowhere.cpp
Labels: type/enhancement

#1626 Fix some broken links
  README.md
  README_CN.md
  README_JP.md
  core/src/server/web_impl/README.md
Labels: type/docs

#1570 [skip ci] (shards) Upgrade Mishards for #1569
  .gitignore
  shards/all_in_one/all_in_one.yml
  shards/conftest.py
  shards/discovery/factory.py
  shards/discovery/plugins/kubernetes_provider.py
  shards/discovery/plugins/static_provider.py
  shards/mishards/.env.example
  shards/mishards/__init__.py
  shards/mishards/connections.py
  shards/mishards/router/__init__.py
  shards/mishards/router/plugins/file_based_hash_ring_router.py
  shards/mishards/server.py
  shards/mishards/settings.py
  shards/mishards/test_connections.py
  shards/mishards/test_server.py
  shards/mishards/topology.py
  shards/tracer/plugins/jaeger_factory.py
Labels: type/new-feature

#1652 #1649 fix Milvus crash on old cpu
  CHANGELOG.md
  core/src/index/thirdparty/faiss/FaissHook.cpp
  core/src/index/thirdparty/faiss/FaissHook.h
  core/src/wrapper/KnowhereResource.cpp
Labels: type/bug

#1657 Refactor CI workflow
  .github/workflows/core.yml
  ci/docker/centos-7-core.dockerfile
  ci/docker/ubuntu-18.04-core.dockerfile
  ci/jenkins/Jenkinsfile
  ci/jenkins/step/build.groovy
  ci/jenkins/step/coverage.groovy
  ci/jenkins/step/unittest.groovy
  ci/scripts/build.sh
  ci/scripts/check_ccache.sh
  ci/scripts/coverage.sh
  ci/scripts/run_unittest.sh
  docker-compose.yml
Labels: type/enhancement

#1669 Add GUI link to readme
  README.md
  README_CN.md
  README_JP.md
Labels: type/docs

#1672 fix #1671
  shards/mishards/connections.py
  shards/mishards/router/__init__.py
  shards/mishards/service_handler.py
  shards/mishards/test_server.py
  shards/requirements.txt
Labels: type/bug

#1676 #1656 Add timeout for whole Jenkins job
  ci/jenkins/Jenkinsfile
  ci/jenkins/step/build.groovy
  ci/jenkins/step/coverage.groovy
  ci/jenkins/step/internalCoverage.groovy
  ci/jenkins/step/package.groovy
  ci/jenkins/step/publishImages.groovy
  ci/jenkins/step/singleDevNightlyTest.groovy
  ci/jenkins/step/singleDevTest.groovy
  ci/jenkins/step/unittest.groovy
  docker/deploy/gpu/centos7/Dockerfile
Labels: type/enhancement

#1681 Mishards fix bug for partition handling
  shards/mishards/router/plugins/file_based_hash_ring_router.py
  shards/mishards/service_handler.py
Labels: type/bug

#1684 [skip ci] Update README_CN.md
  README_CN.md
Labels: type/docs

#1629 Optimize config cpu_cache_capacity / gpu_cache_capacity setter (#1572)
  CHANGELOG.md
  core/cmake/ThirdPartyPackages.cmake
  core/src/cache/CpuCacheMgr.cpp
  core/src/cache/CpuCacheMgr.h
  core/src/cache/GpuCacheMgr.cpp
  core/src/cache/GpuCacheMgr.h
  core/src/config/Config.cpp
  core/src/config/handler/CacheConfigHandler.cpp
  core/src/config/handler/CacheConfigHandler.h
  core/src/config/handler/ConfigHandler.h
  core/src/config/handler/EngineConfigHandler.cpp
  core/src/config/handler/EngineConfigHandler.h
  core/src/config/handler/GpuBuildConfigHandler.cpp
  core/src/config/handler/GpuConfigHandler.cpp
  core/src/config/handler/GpuConfigHandler.h
  core/src/config/handler/GpuResourceConfigHandler.cpp
  core/src/config/handler/GpuResourceConfigHandler.h
  core/src/config/handler/GpuSearchConfigHandler.cpp
  core/src/config/handler/GpuSearchConfigHandler.h
  core/src/db/DBImpl.cpp
  core/src/db/DBImpl.h
  core/src/db/insert/MemTable.cpp
  core/src/db/insert/MemTableFile.cpp
  core/src/db/insert/MemTableFile.h
  core/src/scheduler/job/BuildIndexJob.cpp
  core/src/scheduler/job/BuildIndexJob.h
  core/src/scheduler/optimizer/BuildIndexPass.cpp
  core/src/scheduler/optimizer/BuildIndexPass.h
  core/src/scheduler/optimizer/FaissFlatPass.cpp
  core/src/scheduler/optimizer/FaissFlatPass.h
  core/src/scheduler/optimizer/FaissIVFFlatPass.cpp
  core/src/scheduler/optimizer/FaissIVFFlatPass.h
  core/src/scheduler/optimizer/FaissIVFPQPass.cpp
  core/src/scheduler/optimizer/FaissIVFPQPass.h
  core/src/scheduler/optimizer/FaissIVFSQ8HPass.cpp
  core/src/scheduler/optimizer/FaissIVFSQ8HPass.h
  core/src/scheduler/optimizer/FaissIVFSQ8Pass.cpp
  core/src/scheduler/optimizer/FaissIVFSQ8Pass.h
  core/src/server/DBWrapper.cpp
  core/src/server/web_impl/README.md
  core/src/server/web_impl/handler/WebRequestHandler.cpp
  core/src/server/web_impl/handler/WebRequestHandler.h
  core/unittest/server/test_config.cpp
  core/unittest/server/test_web.cpp
Labels: type/enhancement

#1707 #1678 remove CUSTOMIZATION macro
  CHANGELOG.md
  core/CMakeLists.txt
  core/cmake/DefineOptions.cmake
  core/src/db/engine/ExecutionEngineImpl.cpp
  core/src/index/CMakeLists.txt
  core/src/index/cmake/DefineOptionsCore.cmake
  core/src/index/knowhere/knowhere/index/vector_index/IndexIVF.cpp
  core/src/index/knowhere/knowhere/index/vector_index/gpu/IndexIVFSQHybrid.cpp
  core/src/index/knowhere/knowhere/index/vector_index/gpu/IndexIVFSQHybrid.h
  core/src/index/knowhere/knowhere/index/vector_index/helpers/Cloner.cpp
  core/src/index/unittest/faiss_benchmark/faiss_benchmark_test.cpp
  core/src/index/unittest/faiss_benchmark/faiss_bitset_test.cpp
  core/src/index/unittest/test_customized_index.cpp
  core/src/index/unittest/test_ivf.cpp
  core/src/index/unittest/test_vecindex.cpp
  core/src/scheduler/SchedInst.h
  core/src/scheduler/optimizer/FaissIVFSQ8HPass.cpp
  core/src/utils/ValidationUtil.cpp
  core/unittest/db/test_db.cpp
  core/unittest/server/test_util.cpp
Labels: type/enhancement

#1699 Mishards 070
  CHANGELOG.md
  shards/all_in_one/all_in_one.yml
  shards/all_in_one/ro_server.yml
  shards/all_in_one/wr_server.yml
  shards/all_in_one_with_mysql/all_in_one.yml
  shards/all_in_one_with_mysql/ro_server.yml
  shards/all_in_one_with_mysql/wr_server.yml
  shards/mishards/exception_codes.py
  shards/mishards/exceptions.py
  shards/mishards/grpc_utils/grpc_args_parser.py
  shards/mishards/models.py
  shards/mishards/service_handler.py
  shards/mishards/settings.py
  shards/requirements.txt
Labels: type/enhancement

#1720 #1719 Remove unused log
  CHANGELOG.md
  core/src/db/engine/ExecutionEngineImpl.cpp
Labels: type/enhancement

#1717 #267 Improve search performance: reduce delay
  CHANGELOG.md
  core/src/cache/Cache.inl
  core/src/index/knowhere/knowhere/index/vector_index/IndexIVF.cpp
  core/src/scheduler/JobMgr.cpp
  core/src/scheduler/TaskTable.cpp
  core/src/scheduler/task/SearchTask.cpp
  core/src/utils/TimeRecorder.h
Labels: type/enhancement

#1723 Caiyd 1689 fix sq8h fail
  CHANGELOG.md
  core/src/db/engine/ExecutionEngineImpl.cpp
  core/src/db/meta/SqliteMetaImpl.cpp
  core/src/index/archive/VecIndex.cpp
  core/src/index/knowhere/knowhere/index/Index.h
  core/src/index/knowhere/knowhere/index/vector_index/IndexBinaryIDMAP.h
  core/src/index/knowhere/knowhere/index/vector_index/IndexBinaryIVF.h
  core/src/index/knowhere/knowhere/index/vector_index/IndexIDMAP.h
  core/src/index/knowhere/knowhere/index/vector_index/VecIndex.h
  core/src/index/knowhere/knowhere/index/vector_index/helpers/Cloner.cpp
  core/src/index/thirdparty/faiss/utils/ConcurrentBitset.cpp
  core/src/index/thirdparty/faiss/utils/ConcurrentBitset.h
  core/src/index/unittest/test_gpuresource.cpp
  core/src/index/unittest/test_ivf.cpp
  core/unittest/server/test_cache.cpp
Labels: type/bug

#1716 #1656 Update ccache script file
  ci/scripts/check_ccache.sh
  ci/scripts/update_ccache.sh
Labels: type/enhancement

#1732 #1656 Limit the resources of publish docker container
  ci/jenkins/pod/docker-pod.yaml
Labels: type/enhancement

#1748 #1735 fix search fail with gpu out of memory using ivf_flag
  CHANGELOG.md
  core/src/cache/Cache.h
  core/src/cache/Cache.inl
  core/src/cache/CpuCacheMgr.cpp
  core/src/cache/GpuCacheMgr.cpp
  core/src/cache/GpuCacheMgr.h
  core/src/config/Config.h
  core/src/db/engine/ExecutionEngineImpl.cpp
  core/src/scheduler/task/SearchTask.cpp
Labels: type/bug

#1755 Optimize behavior to get file ids from metadata in mishards (#1754)
  CHANGELOG.md
  shards/mishards/router/plugins/file_based_hash_ring_router.py
  shards/mishards/service_handler.py
Labels: type/enhancement

#1758 #1756 fix memory exhausted during searching
  CHANGELOG.md
  core/src/cache/Cache.inl
Labels: type/bug

#1783 #1781 fix search hang with SQ8H
  CHANGELOG.md
  core/src/db/engine/ExecutionEngineImpl.cpp
Labels: Bug

#1801 remove unnecessary lock
  core/src/cache/CacheMgr.h
  core/src/cache/CacheMgr.inl
  core/src/cache/GpuCacheMgr.cpp
  core/src/db/engine/ExecutionEngineImpl.cpp
Labels: type/enhancement

#1811 [skip ci](shards): support server 0.7.1
  shards/mishards/settings.py
Labels: Priority 1

#1782 Refactor CI workflow
  ci/jenkins/Jenkinsfile
  ci/jenkins/pod/milvus-cpu-version-centos7-build-env-pod.yaml
  ci/jenkins/pod/milvus-cpu-version-ubuntu18.04-build-env-pod.yaml
  ci/jenkins/pod/milvus-gpu-version-centos7-build-env-pod.yaml
  ci/jenkins/pod/milvus-gpu-version-ubuntu18.04-build-env-pod.yaml
  ci/jenkins/step/deploySingle2Dev.groovy
  ci/jenkins/step/singleDevNightlyTest.groovy
  ci/jenkins/step/singleDevTest.groovy
Labels: type/enhancement
