Repository milvus-io/milvus, pull requests merged in 2021-09, with the labels that each got.

#7177 Expose metrics of data cluster
  internal/datacoord/errors.go
  internal/datacoord/errors_test.go
  internal/datacoord/grpc_services.go
  internal/datacoord/metrics_info.go
  internal/datacoord/mock_test.go
  internal/datacoord/server_test.go
  internal/datanode/data_node.go
  internal/datanode/data_node_test.go
  internal/datanode/errors.go
  internal/datanode/errors_test.go
  internal/datanode/metrics_info.go
  internal/distributed/datacoord/client/client.go
  internal/distributed/datacoord/service.go
  internal/distributed/datanode/client/client.go
  internal/distributed/datanode/service.go
  internal/proto/data_coord.proto
  internal/proto/datapb/data_coord.pb.go
  internal/types/types.go
  internal/util/metricsinfo/metrics_info.go
  internal/util/metricsinfo/metrics_info_test.go
  internal/util/metricsinfo/topology.go
  internal/util/metricsinfo/topology_test.go
Labels: size/XXL, approved

#7382 Fix go.mod missing atomic library error
  go.mod
Labels: size/XS, approved, lgtm, ci-passed

#7393 Fix rocksmq retention panic when delete by message size
  internal/util/rocksmq/server/rocksmq/rocksmq_retention.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed

#7395 Update main.yaml for github action
  .github/workflows/main.yaml
Labels: size/XS, approved, lgtm, ci-passed

#7400 Proxy metrics integrate with other coordinators
  internal/datacoord/metrics_info.go
  internal/datacoord/mock_test.go
  internal/indexcoord/metrics_info.go
  internal/proxy/metrics_info.go
  internal/querycoord/metrics_info.go
  internal/rootcoord/metrics_info.go
  internal/types/types.go
  internal/util/metricsinfo/topology.go
  internal/util/metricsinfo/topology_test.go
Labels: size/L, approved, lgtm

#7407 Improve tso codecov
  internal/tso/global_allocator_test.go
  internal/tso/tso.go
Labels: size/M, approved, lgtm, ci-passed

#7414 Merge collection test cases from pymilvus and orm
  build/README.md
  build/ci/jenkins/Jenkinsfile
  build/ci/jenkins/NightlyCI.groovy
  tests/python_client/conftest.py
  tests/python_client/pytest.ini
  tests/python_client/requirements.txt
  tests/python_client/testcases/collection/test_collection_count.py
  tests/python_client/testcases/collection/test_collection_logic.py
  tests/python_client/testcases/collection/test_collection_stats.py
  tests/python_client/testcases/collection/test_create_collection.py
  tests/python_client/testcases/collection/test_describe_collection.py
  tests/python_client/testcases/collection/test_drop_collection.py
  tests/python_client/testcases/collection/test_has_collection.py
  tests/python_client/testcases/collection/test_list_collections.py
  tests/python_client/testcases/collection/test_load_collection.py
  tests/python_client/testcases/entity/test_insert.py
  tests/python_client/testcases/entity/test_query.py
  tests/python_client/testcases/entity/test_search.py
  tests/python_client/testcases/stability/test_mysql.py
  tests/python_client/testcases/stability/test_restart.py
  tests/python_client/testcases/test_collection.py
  tests/python_client/testcases/test_collection_20.py
  tests/python_client/testcases/test_connect.py
  tests/python_client/testcases/test_flush.py
  tests/python_client/testcases/test_index.py
  tests/python_client/testcases/test_mix.py
  tests/python_client/testcases/test_partition.py
  tests/python_client/utils/utils.py
  tests/scripts/e2e.sh
Labels: sig/testing, size/XXL, approved, lgtm, area/test, ci-passed

#7426 Merge pymilvus and orm connection tests
  tests/python_client/testcases/test_connect.py
  tests/python_client/testcases/test_connection_20.py
  tests/python_client/testcases/test_e2e_20.py
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed

#7431 Update tests owner list
  OWNERS
  tests-deprecating/OWNERS
  tests/OWNERS
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed

#7442 enable contributor action dco check
  .github/workflows/all-contributors.yaml
Labels: size/M, approved, lgtm, ci-passed

#7403 Add some logs in rocksmq retention
  internal/util/rocksmq/server/rocksmq/rocksmq_retention.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed

#7418 [automated] Bumped milvus verison to 2.0.0-rc.5-hotfix1
  deployments/docker/cluster/docker-compose.yml
  deployments/docker/standalone/docker-compose.yml
Labels: size/S, approved, lgtm, ci-passed

#7440 Add id allocator ut
  internal/allocator/id.go
  internal/allocator/id_test.go
  internal/proxy/proxy.go
Labels: size/L, approved, lgtm, ci-passed

#7444 Fix deadlock of channels time ticker
  internal/proxy/channels_time_ticker.go
Labels: size/S, approved, lgtm

#7457 Add logs in rootcoord
  internal/rootcoord/root_coord.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#7464 Unittest for indexparamcheck
  internal/util/indexparamcheck/conf_adapter_test.go
Labels: kind/improvement, size/L, approved, lgtm, do-not-merge/missing-related-issue

#7463 Update all-contributors.yaml
  .github/workflows/all-contributors.yaml
Labels: size/XS

#7445 Add trace ut
  internal/util/trace/util.go
  internal/util/trace/util_test.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed

#7386 Support query by expression
  internal/core/src/common/Types.h
  internal/core/src/pb/plan.pb.cc
  internal/core/src/pb/plan.pb.h
  internal/core/src/pb/segcore.pb.cc
  internal/core/src/pb/segcore.pb.h
  internal/core/src/query/Plan.cpp
  internal/core/src/query/Plan.h
  internal/core/src/query/PlanImpl.h
  internal/core/src/query/PlanNode.h
  internal/core/src/query/PlanProto.cpp
  internal/core/src/query/PlanProto.h
  internal/core/src/query/generated/ExecPlanNodeVisitor.h
  internal/core/src/query/generated/ExtractInfoPlanNodeVisitor.h
  internal/core/src/query/generated/PlanNode.cpp
  internal/core/src/query/generated/PlanNodeVisitor.h
  internal/core/src/query/generated/ShowPlanNodeVisitor.h
  internal/core/src/query/generated/VerifyPlanNodeVisitor.h
  internal/core/src/query/visitors/ExecPlanNodeVisitor.cpp
  internal/core/src/query/visitors/ExtractInfoPlanNodeVisitor.cpp
  internal/core/src/query/visitors/ShowPlanNodeVisitor.cpp
  internal/core/src/query/visitors/VerifyPlanNodeVisitor.cpp
  internal/core/src/segcore/SegmentGrowingImpl.cpp
  internal/core/src/segcore/SegmentGrowingImpl.h
  internal/core/src/segcore/SegmentInterface.cpp
  internal/core/src/segcore/SegmentInterface.h
  internal/core/src/segcore/SegmentSealedImpl.cpp
  internal/core/src/segcore/SegmentSealedImpl.h
  internal/core/src/segcore/plan_c.cpp
  internal/core/src/segcore/plan_c.h
  internal/core/src/segcore/segment_c.cpp
  internal/core/src/segcore/segment_c.h
  internal/core/unittest/test_get_entity_by_ids.cpp
  internal/core/unittest/test_utils/DataGen.h
  internal/proto/internal.proto
  internal/proto/internalpb/internal.pb.go
  internal/proto/plan.proto
  internal/proto/planpb/plan.pb.go
  internal/proto/segcore.proto
  internal/proto/segcorepb/segcore.pb.go
  internal/proxy/impl.go
  internal/proxy/plan_parser.go
  internal/proxy/task.go
  internal/querynode/plan.go
  internal/querynode/query_collection.go
  internal/querynode/query_node_test.go
  internal/querynode/segment.go
  internal/querynode/segment_test.go
  tests/python_client/testcases/entity/test_query.py
  tests/python_client/testcases/test_query_20.py
Labels: kind/enhancement, sig/testing, size/XXL, approved, lgtm, area/test, ci-passed

#7436 Cache the system information metrics
  go.mod
  internal/datacoord/grpc_services.go
  internal/datacoord/server.go
  internal/indexcoord/index_coord.go
  internal/proxy/impl.go
  internal/proxy/proxy.go
  internal/querycoord/impl.go
  internal/querycoord/query_coord.go
  internal/rootcoord/root_coord.go
  internal/util/metricsinfo/cache.go
  internal/util/metricsinfo/cache_test.go
  internal/util/metricsinfo/err.go
Labels: size/L, approved, lgtm, ci-passed

#7448 Add scripts to test deployment by docker-compose
  tests/python_client/.gitignore
  tests/python_client/deploy/README.md
  tests/python_client/deploy/run.sh
  tests/python_client/deploy/scripts/action_after_upgrade.py
  tests/python_client/deploy/scripts/action_before_upgrade.py
  tests/python_client/deploy/scripts/action_reinstall.py
  tests/python_client/deploy/scripts/utils.py
  tests/python_client/deploy/test.sh
Labels: kind/improvement, sig/testing, size/L, approved, lgtm, area/test, ci-passed

#7472 Support more detailed metrics information
  cmd/main.go
  cmd/roles/roles.go
  go.mod
  go.sum
  internal/datacoord/metrics_info.go
  internal/datanode/metrics_info.go
  internal/indexcoord/metrics_info.go
  internal/indexnode/metrics_info.go
  internal/kv/etcd/embed_etcd_config_test.go
  internal/kv/etcd/embed_etcd_kv_test.go
  internal/kv/etcd/embed_etcd_restart_test.go
  internal/proxy/impl.go
  internal/proxy/metrics_info.go
  internal/querycoord/metrics_info.go
  internal/querynode/metrics_info.go
  internal/rootcoord/metrics_info.go
  internal/util/metricsinfo/hardware_info.go
  internal/util/metricsinfo/hardware_info_test.go
  internal/util/metricsinfo/metrics_info.go
  internal/util/metricsinfo/metrics_info_test.go
  internal/util/paramtable/param.go
  internal/util/paramtable/param_test.go
Labels: size/XL, approved, lgtm

#7471 Improve codecov for paramtable and typeutil
  internal/tso/global_allocator_test.go
  internal/util/typeutil/conversion_test.go
  internal/util/typeutil/index.go
  internal/util/typeutil/schema_test.go
  internal/util/typeutil/time_test.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed

#7473 Unittest for funcutil
  internal/util/funcutil/func_test.go
  internal/util/funcutil/parallel_test.go
  internal/util/funcutil/random_test.go
  internal/util/funcutil/slice_test.go
Labels: kind/improvement, size/L, approved, lgtm

#7467 Add datacoord services related unit tests
  internal/datacoord/cluster.go
  internal/datacoord/cluster_test.go
  internal/datacoord/server_test.go
  internal/datacoord/services.go
Labels: size/L, approved, lgtm, ci-passed

#7488 Update unittest for calc_distance
  internal/util/distance/calc_distance_test.go
Labels: size/M, approved, lgtm

#7490 Fix rootcoord unittest, should filter out timetick msg first
  internal/rootcoord/root_coord_test.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed

#7477 Add unittest for mq_factory
  internal/msgstream/mq_factory_test.go
Labels: kind/improvement, lgtm

#7492 Add log unit tests
  internal/log/log.go
  internal/log/log_test.go
  internal/log/zap_log_test.go
  internal/log/zap_test_logger.go
  internal/log/zap_text_encoder.go
Labels: size/L, approved, lgtm, ci-passed

#7499 Add datacoord server unit tests
  internal/datacoord/segment_manager.go
  internal/datacoord/server.go
  internal/datacoord/server_test.go
Labels: kind/improvement, size/XL, approved, lgtm, ci-passed

#7475 Add unittest for index component
  internal/distributed/indexcoord/client/client_test.go
  internal/distributed/indexcoord/service.go
  internal/distributed/indexcoord/service_test.go
  internal/distributed/indexnode/client/client_test.go
  internal/distributed/indexnode/service.go
  internal/distributed/indexnode/service_test.go
  internal/indexcoord/index_coord.go
  internal/indexcoord/index_coord_mock.go
  internal/indexcoord/index_coord_mock_test.go
  internal/indexcoord/index_coord_test.go
  internal/indexcoord/task_scheduler.go
  internal/indexnode/indexnode.go
  internal/indexnode/indexnode_mock.go
  internal/indexnode/indexnode_mock_test.go
  internal/types/types.go
Labels: size/XXL, approved, lgtm, ci-passed

#7498 Increase nightly ci ephemeral-storage
  build/ci/jenkins/pod/krte.yaml
Labels: kind/improvement, size/XS, approved, lgtm, area/test, ci-passed

#7483 Improve rocksmq code coverage
  internal/util/rocksmq/server/rocksmq/global_rmq.go
  internal/util/rocksmq/server/rocksmq/rocksmq_impl.go
  internal/util/rocksmq/server/rocksmq/rocksmq_impl_test.go
  internal/util/rocksmq/server/rocksmq/rocksmq_retention.go
  internal/util/rocksmq/server/rocksmq/rocksmq_retention_test.go
Labels: size/L, approved, lgtm, ci-passed

#7512 Add unittest for flowgraph
  internal/util/flowgraph/flow_graph_test.go
  internal/util/flowgraph/input_node_test.go
  internal/util/flowgraph/message_test.go
  internal/util/flowgraph/node_test.go
Labels: size/L, approved, lgtm

#7502 Update all-contributors.yaml
  .github/workflows/all-contributors.yaml
Labels: size/S, lgtm, ci-passed

#7518 Improve rootcoord codecov
  internal/distributed/rootcoord/service_test.go
  internal/rootcoord/param_table.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
Labels: size/L, approved, lgtm, ci-passed

#7434 Load failed if collection beyonds the memory limit
  internal/datacoord/services.go
  internal/proto/data_coord.proto
  internal/proto/datapb/data_coord.pb.go
  internal/proto/query_coord.proto
  internal/proto/querypb/query_coord.pb.go
  internal/querycoord/task.go
  internal/querynode/segment_loader.go
  internal/querynode/segment_loader_test.go
Labels: kind/improvement, size/XL, approved, lgtm, ci-passed

#7515 Enable and modify test case
  tests/python_client/testcases/entity/test_insert.py
  tests/python_client/testcases/test_search_20.py
Labels: kind/improvement, sig/testing, size/S, approved, lgtm, area/test, ci-passed

#7525 Add segment manager unit tests
  internal/datacoord/mock_test.go
  internal/datacoord/segment_allocation_policy.go
  internal/datacoord/segment_manager.go
  internal/datacoord/segment_manager_test.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed

#7527 Fix dataset's memory leak in knowWhere when search
  internal/core/src/index/knowhere/knowhere/common/Dataset.h
  internal/core/src/index/unittest/test_annoy.cpp
  internal/core/src/index/unittest/test_binaryidmap.cpp
  internal/core/src/index/unittest/test_binaryivf.cpp
  internal/core/src/index/unittest/test_customized_index.cpp
  internal/core/src/index/unittest/test_gpuresource.cpp
  internal/core/src/index/unittest/test_hnsw.cpp
  internal/core/src/index/unittest/test_idmap.cpp
  internal/core/src/index/unittest/test_ivf.cpp
  internal/core/src/index/unittest/test_ivf_cpu_nm.cpp
  internal/core/src/index/unittest/test_ivf_gpu_nm.cpp
  internal/core/src/index/unittest/test_ivf_hnsw.cpp
  internal/core/src/index/unittest/test_ngtonng.cpp
  internal/core/src/index/unittest/test_ngtpanng.cpp
  internal/core/src/index/unittest/test_nsg.cpp
  internal/core/src/index/unittest/test_rhnsw_flat.cpp
  internal/core/src/index/unittest/test_rhnsw_pq.cpp
  internal/core/src/index/unittest/test_rhnsw_sq8.cpp
  internal/core/src/index/unittest/test_sptag.cpp
  internal/core/src/index/unittest/test_vecindex.cpp
  internal/core/src/query/SearchOnSealed.cpp
Labels: size/L, approved, lgtm, ci-passed

#7526 Update unittest name of paramtable
  internal/util/paramtable/basetable_test.go
  internal/util/paramtable/param_test.go
Labels: size/S, approved, lgtm

#7531 Add binary test cases
  build/ci/jenkins/NightlyCI.groovy
  tests/python_client/testcases/test_search_20.py
Labels: sig/testing, size/S, approved, lgtm, area/test, ci-passed

#7511 Add ut for flow_graph_dd_node to 100%
  internal/datanode/flow_graph_dd_node.go
  internal/datanode/flow_graph_dd_node_test.go
Labels: size/L, approved, lgtm, ci-passed

#7510 Add unittests for querynode
  internal/querynode/collection.go
  internal/querynode/collection_replica_test.go
  internal/querynode/collection_test.go
  internal/querynode/data_sync_service.go
  internal/querynode/data_sync_service_test.go
  internal/querynode/flow_graph_dd_node.go
  internal/querynode/flow_graph_filter_dm_node.go
  internal/querynode/flow_graph_filter_dm_node_test.go
  internal/querynode/flow_graph_gc_node.go
  internal/querynode/flow_graph_key2seg_node.go
  internal/querynode/flow_graph_message.go
  internal/querynode/impl_test.go
  internal/querynode/index_loader.go
  internal/querynode/mock_test.go
  internal/querynode/query_collection.go
  internal/querynode/query_collection_test.go
  internal/querynode/query_node_test.go
  internal/querynode/query_service_test.go
  internal/querynode/segment.go
  internal/querynode/segment_loader_test.go
  internal/querynode/segment_test.go
  internal/querynode/streaming_test.go
  internal/querynode/task_test.go
  internal/querynode/type_def.go
Labels: test/ut, size/XXL, approved, lgtm, ci-passed

#7524 Add log unit tests
  internal/log/log.go
  internal/log/log_test.go
  internal/log/zap_log_test.go
  internal/log/zap_text_encoder.go
Labels: size/L, approved, lgtm, ci-passed

#7501 Remove stats watcher
  internal/kv/etcd/etcd_stats_watcher.go
  internal/kv/etcd/etcd_stats_watcher_test.go
  internal/kv/minio/minio_stats_wacher.go
  internal/kv/minio/minio_stats_wacher_test.go
Labels: size/L, approved, lgtm, ci-passed

#7536 Fix MqMsgStream Seek logic
  internal/msgstream/mq_msgstream.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed

#7542 PR with imporvement label can merge without linking a issue
  .github/mergify.yml
Labels: kind/improvement, size/S, approved, lgtm, ci-passed

#7550 Add ut for flowgraph_delete_node to 100%
  internal/datanode/data_sync_service.go
  internal/datanode/flow_graph_delete_node.go
  internal/datanode/flow_graph_delete_node_test.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed

#7551 Remove time-consuming test
  internal/log/zap_log_test.go
Labels: size/XS, approved, lgtm

#7552 Fix Arrow unable to find Boost error
  internal/storage/cwrapper/CMakeLists.txt
Labels: kind/bug, size/XS, approved, lgtm, ci-passed

#7540 Improve rocksmq client code coverage
  internal/util/rocksmq/client/rocksmq/client.go
  internal/util/rocksmq/client/rocksmq/client_impl_test.go
  internal/util/rocksmq/client/rocksmq/consumer_impl_test.go
  internal/util/rocksmq/client/rocksmq/test_helper.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed

#7537 Update unittest name of distance
  internal/util/distance/calc_distance_test.go
Labels: kind/improvement, size/S, lgtm

#7560 Add ut and comments for datacoord meta
  internal/datacoord/meta.go
  internal/datacoord/meta_test.go
  internal/datacoord/mock_test.go
  internal/datacoord/move_binlog_path_helper.go
  internal/datacoord/segment_info.go
  internal/datacoord/segment_manager_test.go
  internal/datacoord/server.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed

#7557 Fix search result is wrong when the term is not in order
  internal/core/src/query/visitors/ExecExprVisitor.cpp
Labels: kind/bug, size/XS, approved, lgtm, ci-passed

#7554 Add cases for term not in and query non-primary field
  tests/python_client/chaos/chaos_objects/chaos_etcd_podkill.yaml
  tests/python_client/chaos/chaos_objects/chaos_pulsar_podkill.yaml
  tests/python_client/chaos/chaos_objects/testcases.yaml
  tests/python_client/common/common_func.py
  tests/python_client/common/common_type.py
  tests/python_client/testcases/test_collection.py
  tests/python_client/testcases/test_insert_20.py
  tests/python_client/testcases/test_query_20.py
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed

#7558 Increase indexcoord component code coverage
  .gitignore
  internal/indexcoord/index_coord_test.go
  internal/indexcoord/meta_table.go
  internal/indexcoord/meta_table_test.go
  internal/indexcoord/metrics_info_test.go
  internal/indexnode/indexnode_mock.go
  internal/indexnode/indexnode_mock_test.go
Labels: size/XL, approved, lgtm, ci-passed

#7482 Support specified shard number when create collection
  Makefile
  configs/advanced/proxy.yaml
  configs/advanced/root_coord.yaml
  internal/core/src/pb/etcd_meta.pb.cc
  internal/core/src/pb/etcd_meta.pb.h
  internal/core/src/pb/milvus.pb.cc
  internal/core/src/pb/milvus.pb.h
  internal/proto/etcd_meta.proto
  internal/proto/etcdpb/etcd_meta.pb.go
  internal/proto/milvus.proto
  internal/proto/milvuspb/milvus.pb.go
  internal/proxy/paramtable.go
  internal/proxy/paramtable_test.go
  internal/proxy/task.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
  internal/rootcoord/task.go
Labels: size/XXL, approved, lgtm, ci-passed

#7561 Add log unit tests
  internal/log/config.go
  internal/log/log_test.go
  internal/log/zap_log_test.go
Labels: size/M, approved, lgtm, ci-passed

#7559 Add ci-passed label when pr only changes golang unit test code
  .github/mergify.yml
Labels: size/S, approved, lgtm, ci-passed

#7584 [skip ci]fix make clean error
  Makefile
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#7581 Rename unittest for funcutil
  internal/util/funcutil/func_test.go
  internal/util/funcutil/parallel_test.go
  internal/util/funcutil/random_test.go
  internal/util/funcutil/set_test.go
  internal/util/funcutil/slice_test.go
Labels: kind/improvement, size/S, ci-passed

#7577 Add unit tests for msg.go
  internal/msgstream/msg.go
  internal/msgstream/msg_test.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed

#7565 Remove useless message and add message unittest
  internal/querynode/flow_graph_insert_node.go
  internal/querynode/flow_graph_message.go
  internal/querynode/flow_graph_message_test.go
  internal/querynode/flow_graph_service_time_node.go
  internal/querynode/flow_graph_service_time_node_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed

#7570 [skip ci]Update data coordinator doc
  docs/developer_guides/chap09_data_coord.md
Labels: kind/documentation, size/XS, approved, lgtm, ci-passed

#7571 [skip ci]Update links in schema doc
  docs/developer_guides/chap02_schema.md
Labels: kind/documentation, kind/improvement, size/XS, approved, lgtm, ci-passed

#7572 [skip ci]update index coordinator interface type in docs
  docs/developer_guides/chap03_index_service.md
Labels: kind/documentation, size/XS, approved, lgtm, ci-passed

#7582 [skip ci] Update README FAQ page link
  README.md
Labels: kind/documentation, kind/improvement, size/XS, approved, lgtm, ci-passed

#7580 Rename unittest for indexparamcheck
  internal/util/indexparamcheck/conf_adapter_mgr_test.go
  internal/util/indexparamcheck/utils_test.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#7593 Add ut for dmstream_input_node to 100%
  internal/datanode/flow_graph_dmstream_input_node_test.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed

#7587 Add tSafeReplica and task scheduler unittests
  internal/querynode/flow_graph_query_node_test.go
  internal/querynode/task_queue_test.go
  internal/querynode/task_scheduler_test.go
  internal/querynode/tsafe_replica_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed

#7596 Add rmq consumer close
  internal/util/mqclient/rmq_client.go
  internal/util/mqclient/rmq_consumer.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed

#7604 [skip ci] Increase nightly execution timeout
  build/ci/jenkins/NightlyCI.groovy
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#7563 Initialize test framework of proxy
  internal/datacoord/server.go
  internal/distributed/indexnode/service.go
  internal/indexcoord/index_coord.go
  internal/indexnode/indexnode.go
  internal/proxy/channels_mgr.go
  internal/proxy/channels_mgr_test.go
  internal/proxy/channels_time_ticker_test.go
  internal/proxy/impl.go
  internal/proxy/metrics_info.go
  internal/proxy/mock.go
  internal/proxy/msgstream_mock.go
  internal/proxy/proxy.go
  internal/proxy/proxy_test.go
  internal/proxy/task_scheduler_test.go
  internal/proxy/test_utils.go
  internal/proxy/timestamp_test.go
  internal/proxy/validate_util_test.go
  internal/util/funcutil/random.go
  internal/util/funcutil/random_test.go
  internal/util/sessionutil/session_util.go
  internal/util/trace/util.go
  internal/util/uniquegenerator/unique_int_generator.go
  internal/util/uniquegenerator/unique_int_generator_test.go
Labels: size/XL, approved, lgtm

#7608 [skip ci] Update grafana dashboard title
  deployments/monitor/grafana/milvus-dashboard.json
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#7599 Add task unittest for query node
  internal/querynode/mock_test.go
  internal/querynode/task_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed

#7589 Add ut for segmentReplica to 100%
  internal/datanode/flow_graph_message_test.go
  internal/datanode/meta_service_test.go
  internal/datanode/mock_test.go
  internal/datanode/segment_replica.go
  internal/datanode/segment_replica_test.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed

#7595 Add datacoord metricsinfo unit test
  internal/datacoord/metrics_info.go
  internal/datacoord/metrics_info_test.go
  internal/datacoord/mock_test.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed

#7601 Update binary install README
  deployments/binary/README.md
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#7605 Deep copy rocksdb data to byte slice
  internal/util/rocksmq/server/rocksmq/rocksmq_impl.go
  internal/util/rocksmq/server/rocksmq/rocksmq_impl_test.go
Labels: kind/bug, priority/critical-urgent, size/M, approved, lgtm, ci-passed

#7539 Add github action for deploy test
  .github/workflows/deploy_test.yaml
  tests/python_client/deploy/requirements.txt
  tests/python_client/deploy/run.sh
  tests/python_client/deploy/scripts/get_tag.py
  tests/python_client/deploy/scripts/utils.py
  tests/python_client/deploy/test.sh
Labels: kind/improvement, sig/testing, size/L, approved, lgtm, area/test, ci-passed

#7610 Add unittest for VectorChunkManager
  internal/storage/vector_chunk_manager_test.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed

#7621 Refactor insertBufferNode and add unit tests
  internal/datanode/flow_graph_insert_buffer_node.go
  internal/datanode/flow_graph_insert_buffer_node_test.go
Labels: kind/improvement, size/XL, approved, lgtm, ci-passed

#7615 Add ut in datasync service to 88%
  internal/datanode/data_sync_service.go
  internal/datanode/data_sync_service_test.go
  internal/datanode/flow_graph_delete_node.go
  internal/datanode/flow_graph_delete_node_test.go
  internal/datanode/flow_graph_dmstream_input_node_test.go
  internal/datanode/mock_test.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed

#7634 Change deploy test trigger events
  .github/workflows/deploy-test.yaml
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#7626 Add daily release
  .github/workflows/daily-release.yml
  scripts/docker_image_find_tag.sh
Labels: kind/improvement, size/L, approved, lgtm, ci-passed

#7575 [skip ci] Modify inappropriate headings
  README.md
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#7609 [skip ci]Update 1.1 changelog
  CHANGELOG.md
Labels: kind/documentation, kind/improvement, size/M, approved, lgtm, ci-passed

#7622 Add data node unit tests
  internal/datanode/data_node.go
  internal/datanode/data_node_test.go
  internal/datanode/mock_test.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed

#7616 [skip ci]Use time.time to cal time cost
  tests/python_client/testcases/test_e2e_20.py
Labels: kind/improvement, sig/testing, size/M, approved, lgtm, area/test, ci-passed

#7520 Increase code coverage rate for indexnode component
  internal/indexnode/indexnode_test.go
  internal/indexnode/task_scheduler.go
Labels: size/L, approved, lgtm, ci-passed

#7628 Add unittest for chunk manager
  internal/storage/local_chunk_manager_test.go
  internal/storage/minio_chunk_manager_test.go
  internal/storage/vector_chunk_manager_test.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed

#7631 Make flowgraph Close only once
  internal/util/flowgraph/flow_graph.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed

#7637 Update storage unittest
  internal/storage/binlog_writer_test.go
  internal/storage/data_sorter_test.go
  internal/storage/event_writer_test.go
  internal/storage/stats_test.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed

#7643 [skip ci] update readme of benchmark
  tests/benchmark/README.md
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed

#7646 [skip ci]Add todo for chaos tests
  tests/python_client/chaos/README.md
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed

#7647 [skip ci] add new test case of benchmark
  tests/benchmark/milvus_benchmark/runners/locust_tasks.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed

#7648 [skip ci] Update chaos podkill config
  tests/python_client/chaos/chaos_objects/chaos_datacoord_podkill.yaml
  tests/python_client/chaos/chaos_objects/chaos_datanode_podkill.yaml
  tests/python_client/chaos/chaos_objects/chaos_indexcoord_podkill.yaml
  tests/python_client/chaos/chaos_objects/chaos_indexnode_podkill.yaml
  tests/python_client/chaos/chaos_objects/chaos_proxy_podkill.yaml
Labels: kind/improvement, sig/testing, size/S, approved, lgtm, area/test, ci-passed

#7651 [skip ci] Modify wrong word
  tests/python_client/testcases/test_index.py
Labels: kind/improvement, size/XS, approved, lgtm, area/test, ci-passed

#7654 [skip ci] Update grafana dashboard panel
  deployments/monitor/grafana/milvus-dashboard.json
Labels: kind/improvement, size/XXL, approved, lgtm, ci-passed

#7657 [skip ci]Remove useless commets
  tests/python_client/testcases/test_partition_20.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed

#7658 [skip ci] Fix word spelling error
  docs/design_docs/datanode_ddl_flush_design_0519_2021.md
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#7661 [skip ci] Fix proxy node metric name.
  deployments/monitor/grafana/milvus-dashboard.json
Labels: kind/improvement, size/XXL, approved, lgtm, ci-passed

#7632 Add segment unittests for query node
  internal/querynode/load_index_info_test.go
  internal/querynode/mock_test.go
  internal/querynode/segment.go
  internal/querynode/segment_test.go
  internal/querynode/type_def.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed

#7653 Fix unittest: timeout caused by excessive use of resources
  internal/rootcoord/root_coord_test.go
Labels: priority/critical-urgent, size/S, approved, lgtm, ci-passed

#7652 [skip ci] Update chaos cron
  tests/python_client/chaos/chaos_objects/chaos_pulsar_podkill.yaml
  tests/python_client/chaos/chaos_objects/chaos_querycoord_podkill.yaml
  tests/python_client/chaos/chaos_objects/chaos_querynode_podkill.yaml
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed

#7649 [skip ci] add annotation of benchmark test case
  tests/benchmark/milvus_benchmark/runners/locust_tasks.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed

#7650 [skip ci] Fix word spelling
  docs/developer_guides/chap01_system_overview.md
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#7627 [skip ci] Improve api reference doc
  docs/developer_guides/appendix_b_api_reference.md
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#7592 [skip ci] Improve the developer_guides
  docs/developer_guides/chap01_system_overview.md
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#7655 Fix dir name typo
  tests/benchmark/assets/dash.png
  tests/benchmark/assets/uml.jpg
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed

#7665 [skip ci]Update readme: pymilvus-orm => pymilvus
  README.md
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#7666 [skip ci]Update readme CN: pymilvus-orm => pymilvus
  README_CN.md
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#7667 [skip ci] Add node list chart for grafana
  deployments/monitor/grafana/milvus-dashboard.json
Labels: kind/improvement, size/XL, approved, lgtm, ci-passed

#7644 Let dml tolerant physical channels generated by old version
  internal/rootcoord/dml_channels.go
  internal/rootcoord/dml_channels_test.go
Labels: size/M, approved, lgtm, ci-passed

#7591 [skip ci] remove useless tag
  docs/design_docs/dataservice_recovery_design.md
Labels: kind/improvement, size/M, approved, lgtm, ci-passed

#7664 Update pymilvus version
  tests/python_client/requirements.txt
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed

#7614 [skip ci]Add comments to log in yaml
  configs/milvus.yaml
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#7675 [skip ci]Update readme: add milvus insight
  README.md
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#7623 Add more data definition test cases
  internal/proxy/channels_mgr_test.go
  internal/proxy/impl.go
  internal/proxy/mock_test.go
  internal/proxy/msgstream_mock.go
  internal/proxy/proxy_test.go
  internal/proxy/task.go
  internal/proxy/task_scheduler_test.go
  internal/util/flowgraph/node.go
Labels: kind/improvement, size/XXL, approved, lgtm, ci-passed

#7659 Add unit tests for msg.go
  internal/msgstream/msg_test.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed

#7673 Remove datacoord useless code
  internal/datacoord/meta_test.go
  internal/datacoord/segment_allocation_policy.go
  internal/datacoord/server.go
  internal/datacoord/server_test.go
Labels: size/S, approved, lgtm, ci-passed

#7612 Remove unused msg from msg.go
  internal/datacoord/server_test.go
  internal/distributed/rootcoord/service_test.go
  internal/msgstream/msg.go
  internal/msgstream/unmarshal.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed

#7588 [skip ci] Update README, number of stars
  README.md
Labels: size/XS, approved, lgtm, ci-passed

#7638 Add replica and insertNode unittests for query node
  internal/querynode/collection_replica_test.go
  internal/querynode/flow_graph_insert_node.go
  internal/querynode/flow_graph_insert_node_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed

#7590 Improve CreateCollectionRequest comment in milvus.proto
  internal/proto/milvus.proto
  internal/proto/milvuspb/milvus.pb.go
Labels: kind/documentation, kind/improvement, size/M, approved, lgtm, ci-passed

#7636 Add topic lock for DestroyConsumerGroup
  internal/util/rocksmq/server/rocksmq/rocksmq_impl.go
  internal/util/rocksmq/server/rocksmq/rocksmq_impl_test.go
  internal/util/rocksmq/server/rocksmq/rocksmq_retention.go
  internal/util/rocksmq/server/rocksmq/rocksmq_retention_test.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed

#7678 Fix rocksmq load with prefix
  internal/kv/rocksdb/rocksdb_kv.go
  internal/util/rocksmq/server/rocksmq/rocksmq_impl.go
  internal/util/rocksmq/server/rocksmq/rocksmq_retention.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed

#7682 Add cases for utility loading progress
  tests/python_client/base/utility_wrapper.py
  tests/python_client/testcases/test_query_20.py
  tests/python_client/testcases/test_utility_20.py
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed

#7639 Fix build version typo
  internal/core/CMakeLists.txt
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#7686 Comments unused msg from msg.go
  internal/msgstream/msg.go
  internal/msgstream/unmarshal.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#7692 [skip ci] Fix some writing problems
  docs/developer_guides/chap01_system_overview.md
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#7676 Add Comment for datacoord cluster
  internal/datacoord/allocator.go
  internal/datacoord/cluster.go
  internal/datacoord/cluster_store.go
  internal/datacoord/cluster_test.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed

#7687 Revert apply physical channels from pool (d5f7e358 and 3b960969)
  configs/advanced/channel.yaml
  internal/datanode/data_sync_service.go
  internal/datanode/flow_graph_dd_node.go
  internal/datanode/flow_graph_dmstream_input_node.go
  internal/datanode/flow_graph_dmstream_input_node_test.go
  internal/datanode/flow_graph_insert_buffer_node.go
  internal/querynode/flow_graph_filter_dm_node.go
  internal/querynode/flow_graph_query_node.go
  internal/rootcoord/dml_channels.go
  internal/rootcoord/dml_channels_test.go
  internal/rootcoord/meta_table.go
  internal/rootcoord/param_table.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
  internal/rootcoord/task.go
  internal/rootcoord/timeticksync.go
  internal/util/timerecord/time_recorder.go
Labels: size/L, approved, lgtm, ci-passed

#7683 Refine daily release
  .github/workflows/daily-release.yml
Labels: kind/improvement, size/S, approved, lgtm, ci-passed

#7698 [skip-ci]Fix images path in README
  tests/benchmark/README.md
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed

#7699 [skip ci]Update README for offline deployment
  deployments/offline/README.md
Labels: kind/improvement, size/L, approved, lgtm, ci-passed

#7696 [skip ci] Add requirements when build
  README.md
Labels: kind/improvement, size/S, approved, lgtm, ci-passed

#7691 Add unit tests for msg.go
  internal/msgstream/msg_test.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed

#7705 Change the title of the test framework
  tests/python_client/README.md
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed

#7695 Merge search case
  tests/python_client/testcases/entity/test_search.py
  tests/python_client/testcases/test_search_20.py
Labels: sig/testing, size/XXL, approved, lgtm, area/test, ci-passed

#7689 [skip-ci]Fix datanode comment typo
  internal/datanode/data_node.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed

#7715 Fix query request lost bug
  internal/querynode/query_collection.go
  internal/querynode/query_collection_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed

#7688 Add unittest for rootcoord util
  internal/rootcoord/util_test.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed

#7674 Add index unittests for query node
  internal/querynode/index_info_test.go
  internal/querynode/index_loader.go
  internal/querynode/index_loader_test.go
  internal/querynode/load_service_test.go
  internal/querynode/metrics_info_test.go
  internal/querynode/mock_components_test.go
  internal/querynode/mock_test.go
  internal/querynode/segment_loader.go
  internal/querynode/segment_loader_test.go
  internal/querynode/task_test.go
Labels: kind/improvement, size/XXL, approved, lgtm, ci-passed

#7710 [skip ci] fix api reference doc typo
  docs/developer_guides/appendix_b_api_reference.md
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#7714 [skip ci] sync Mergify label loop bug
  .github/mergify.yml
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#7720 [skip ci]Update query in test_e2e
  tests/python_client/testcases/test_e2e_20.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed

#7722 [skip ci] Add a timeout of 300 seconds to the get interface
  tests/benchmark/milvus_benchmark/runners/locust_tasks.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed

#7724 [skip ci] Add a timeout of 300 seconds to the insert interface
  tests/benchmark/milvus_benchmark/runners/locust_tasks.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed
