Repository milvus-io/milvus, pull requests merged in 2021-08, with the labels that each got.

#6926 Update pymilvus-orm version
  tests/python_test/requirements.txt
  tests20/python_client/requirements.txt
Labels: approved, area/test, ci-passed, lgtm, sig/testing, size/XS

#6928 Optimize building pytest image workflow
  .env
  .github/workflows/publish-builder.yaml
  .github/workflows/publish-test-images.yaml
  tests/docker/.env
  tests/docker/docker-compose.yml
  tests/scripts/e2e.sh
Labels: approved, area/test, ci-passed, lgtm, sig/testing, size/S

#6929 Update pymilvus-orm version
  tests/python_test/requirements.txt
  tests20/python_client/requirements.txt
Labels: approved, area/test, ci-passed, lgtm, sig/testing, size/XS

#6905 Use id to tell search result validation in proxy reduce stage
  internal/proxy/task.go
  internal/querynode/query_collection.go
  tests20/python_client/testcases/test_search.py
Labels: approved, area/test, ci-passed, component/proxy, component/querynode, kind/bug, lgtm, sig/testing, size/M

#6944 Fix minio object leaking goroutine
  internal/kv/minio/minio_kv.go
Labels: approved, ci-passed, lgtm, size/XS

#6947 Add the arguments of skip build Milvus image in e2e-k8s.sh
  tests/scripts/e2e-k8s.sh
Labels: approved, area/test, ci-passed, lgtm, sig/testing, size/S

#6935 Refactor showCollection/showPartition to get load state in memory
  internal/core/src/pb/milvus.pb.cc
  internal/core/src/pb/milvus.pb.h
  internal/proto/milvus.proto
  internal/proto/milvuspb/milvus.pb.go
  internal/proto/query_coord.proto
  internal/proto/querypb/query_coord.pb.go
  internal/proxy/impl.go
  internal/proxy/meta_cache.go
  internal/proxy/task.go
  internal/querycoord/cluster.go
  internal/querycoord/impl.go
  internal/querycoord/meta.go
  internal/querycoord/query_coord.go
  internal/querycoord/querynode.go
  internal/querycoord/task.go
  internal/querycoord/task_scheduler.go
  internal/querycoord/task_scheduler_test.go
  tests/python_test/requirements.txt
  tests20/python_client/requirements.txt
Labels: approved, area/test, ci-passed, component/proxy, component/querycoord, lgtm, sig/testing, size/XXL

#6957 Enhanced etcd resource QoS in e2e test
  build/ci/jenkins/Jenkinsfile
  build/ci/jenkins/NightlyCI.groovy
  build/ci/jenkins/pod/krte.yaml
Labels: approved, area/test, ci-passed, lgtm, sig/testing, size/S

#6551 Fix DataNode BackGroundGC not working problem
  internal/datanode/data_node.go
  internal/datanode/data_node_test.go
  internal/datanode/flow_graph_insert_buffer_node.go
  internal/rootcoord/dml_channels.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
Labels: approved, ci-passed, component/datanode, component/rootcoord, kind/bug, lgtm, size/S

#6950 Fix index parameters check of RHNSWPQ
  internal/core/src/index/knowhere/knowhere/index/vector_index/ConfAdapter.cpp
Labels: approved, ci-passed, lgtm, size/XS

#6807 Fix Msgstream exponential retry
  internal/msgstream/mq_msgstream.go
  internal/msgstream/retry.go
  internal/querynode/index_loader.go
  internal/util/retry/options.go
  internal/util/retry/retry.go
  internal/util/retry/retry_test.go
Labels: approved, ci-passed, component/msgstream, component/querynode, lgtm, size/M

#6945 Fix cases for query output support binary fields
  tests20/python_client/check/param_check.py
  tests20/python_client/pytest.ini
  tests20/python_client/testcases/test_query.py
Labels: approved, area/test, ci-passed, lgtm, sig/testing, size/M

#6961 Add timeout to 20s by default in ci test wrapper
  tests20/python_client/base/index_wrapper.py
  tests20/python_client/base/partition_wrapper.py
  tests20/python_client/base/utility_wrapper.py
  tests20/python_client/chaos/chaos_objects/chaos_standalone_container_kill.yaml
  tests20/python_client/chaos/checker.py
  tests20/python_client/load/test_workload.py
  tests20/python_client/testcases/test_partition.py
Labels: approved, area/test, ci-passed, lgtm, sig/testing, size/L

#6966 [skip ci] Jenkins badge down in README.md and README_CN.md
  README.md
  README_CN.md
Labels: approved, ci-passed, lgtm, size/XS

#6968 Wipe any etcd data when Jenkins CI cleanup stage
  build/ci/jenkins/Jenkinsfile
  build/ci/jenkins/NightlyCI.groovy
Labels: approved, ci-passed, lgtm, size/S

#6970 [skip ci] Fix img link
  README.md
  README_CN.md
Labels: approved, ci-passed, lgtm, size/S

#6972 Change flush way
  tests20/python_client/testcases/test_search.py
Labels: approved, area/test, ci-passed, lgtm, sig/testing, size/XS

#6978 rootcoord synchronous call querycoord releaseXXXX
  internal/rootcoord/task.go
Labels: approved, ci-passed, component/rootcoord, lgtm, size/S

#6974 Set etcd log level to debug in e2e test
  build/ci/jenkins/pod/krte.yaml
Labels: approved, ci-passed, lgtm, size/S

#6908 Return error message in grpc.LoadSegment in query node
  internal/querynode/collection_replica.go
  internal/querynode/impl.go
  internal/querynode/segment_loader.go
  internal/querynode/task.go
Labels: approved, ci-passed, component/querynode, kind/bug, lgtm, size/M

#6958 Use proto marshal instead of MarshalTextString in querycoord
  internal/querycoord/impl.go
  internal/querycoord/query_coord.go
  internal/querycoord/task.go
  internal/querycoord/task_scheduler.go
  internal/querycoord/task_scheduler_test.go
Labels: approved, ci-passed, component/querycoord, lgtm, size/L

#6946 Fix data race in flow graph
  internal/util/flowgraph/flow_graph.go
  internal/util/flowgraph/input_node.go
  internal/util/flowgraph/node.go
Labels: approved, ci-passed, kind/bug, lgtm, size/M

#6983 [skip ci] List all env properties within jenkins pipeline job
  build/ci/jenkins/Jenkinsfile
  build/ci/jenkins/NightlyCI.groovy
Labels: approved, ci-passed, lgtm, size/XS

#6985 Add unit test in datacoord
  internal/datacoord/server_test.go
Labels: approved, ci-passed, component/datacoord, lgtm, size/L

#7008 Set KinD pod anti-affinity to requiredDuringSchedulingIgnoredDuringExecution
  build/ci/jenkins/pod/krte.yaml
Labels: approved, ci-passed, lgtm, size/S

#7004 Fix pulsar consumer goroutine leakage
  internal/util/mqclient/pulsar_client.go
  internal/util/mqclient/pulsar_consumer.go
Labels: size/XS, approved, lgtm, ci-passed

#6982 Change client timeout
  go.mod
  internal/distributed/datacoord/client/client.go
  internal/distributed/datanode/client/client.go
  internal/distributed/indexcoord/client/client.go
  internal/distributed/indexnode/client/client.go
  internal/distributed/proxy/client/client.go
  internal/distributed/querycoord/client/client.go
  internal/distributed/querynode/client/client.go
  internal/distributed/rootcoord/client/client.go
  internal/querycoord/query_coord_test.go
  internal/querycoord/querynode_test.go
Labels: size/M, approved, lgtm, ci-passed, component/querycoord

#7026 Add Milvus offline installation README
  deployments/offline/README.md
  deployments/offline/save_image.py
Labels: size/M, approved, lgtm, ci-passed

#6976 Fix CalcDistance wrong result when fetting vectors from collection
  internal/proxy/impl.go
Labels: component/proxy, size/L, approved, lgtm, ci-passed

#7028 Update Milvus offline installation README
  deployments/offline/README.md
Labels: size/S, approved, lgtm, ci-passed

#7031 [skip ci]Add levels for pymilvus tests
  tests/python_test/collection/test_collection_count.py
  tests/python_test/collection/test_collection_logic.py
  tests/python_test/collection/test_collection_stats.py
  tests/python_test/collection/test_create_collection.py
  tests/python_test/collection/test_describe_collection.py
  tests/python_test/collection/test_drop_collection.py
  tests/python_test/collection/test_has_collection.py
  tests/python_test/collection/test_list_collections.py
  tests/python_test/collection/test_load_collection.py
  tests/python_test/entity/test_delete.py
  tests/python_test/entity/test_get_entity_by_id.py
  tests/python_test/entity/test_insert.py
  tests/python_test/entity/test_list_id_in_segment.py
  tests/python_test/entity/test_query.py
  tests/python_test/entity/test_search.py
  tests/python_test/stability/test_mysql.py
  tests/python_test/stability/test_restart.py
  tests/python_test/test_compact.py
  tests/python_test/test_config.py
  tests/python_test/test_connect.py
  tests/python_test/test_flush.py
  tests/python_test/test_index.py
  tests/python_test/test_mix.py
  tests/python_test/test_partition.py
  tests/python_test/test_ping.py
  tests/python_test/utils.py
Labels: sig/testing, size/XL, approved, lgtm, area/test, ci-passed

#7034 Update Milvus offline installation README
  deployments/offline/README.md
Labels: size/S, approved, lgtm, ci-passed

#6783 timesync doc
  docs/design_docs/graphs/time_stamp_struct.png
  docs/design_docs/graphs/timesync_msgstream.png
  docs/design_docs/graphs/timesync_msgtream_timetick.png
  docs/design_docs/graphs/timesync_proxy_insert_msg.png
  docs/design_docs/graphs/timesync_proxy_upload_time_tick.png
  docs/design_docs/milvus_timesync_en.md
Labels: kind/documentation, size/L, approved, lgtm, ci-passed

#6795 create_collection doc
  docs/design_docs/graphs/dml_create_collection.png
  docs/design_docs/milvus_create_collection_en.md
Labels: kind/documentation, size/L, approved, lgtm, ci-passed

#6802 drop collection doc
  docs/design_docs/graphs/dml_drop_collection.png
  docs/design_docs/graphs/dml_release_collection.png
  docs/design_docs/graphs/dml_release_flow_graph_on_data_node.png
  docs/design_docs/milvus_drop_collection_en.md
Labels: kind/documentation, approved, lgtm, ci-passed

#6816 create index doc
  docs/design_docs/graphs/milvus_create_index.png
  docs/design_docs/graphs/milvus_create_index_data_coord_flushed.png
  docs/design_docs/graphs/milvus_create_index_index_coord.png
  docs/design_docs/graphs/milvus_create_index_root_coord_check.png
  docs/design_docs/milvus_create_index_en.md
Labels: size/L, approved, lgtm, ci-passed

#6821 flush collection doc
  docs/design_docs/graphs/flush_data_coord.png
  docs/design_docs/milvus_flush_collections_en.md
Labels: kind/documentation, size/L, approved, lgtm, ci-passed

#7041 Upgrade ETCD version to 3.5.0
  build/ci/jenkins/pod/krte.yaml
  deployments/docker/cluster/docker-compose.yml
  deployments/docker/dev/docker-compose.yml
  deployments/docker/standalone/docker-compose.yml
  docker-compose.yml
Labels: size/S, approved, lgtm, ci-passed

#6862 Fix mem leak of flush cache in DataNode
  internal/datanode/cache.go
  internal/datanode/cache_test.go
  internal/datanode/data_node.go
  internal/datanode/flow_graph_insert_buffer_node.go
  internal/datanode/segment_replica.go
  internal/datanode/segment_replica_test.go
Labels: kind/bug, component/datanode, size/M, approved, lgtm, ci-passed

#7042 [automated] Bumped milvus verison to 2.0.0-rc.3
  deployments/docker/cluster/docker-compose.yml
  deployments/docker/standalone/docker-compose.yml
Labels: size/S, approved, lgtm, ci-passed

#7045 Fix etcd deployments bug with Docker compose
  deployments/docker/cluster/docker-compose.yml
  deployments/docker/standalone/docker-compose.yml
Labels: size/S, approved, lgtm, ci-passed

#7047 Design detail on meta snapshot
  docs/design_docs/graphs/snapshot_1.png
  docs/design_docs/graphs/snapshot_2.png
  docs/design_docs/milvus_meta_snapshot_en.md
Labels: size/L, approved, lgtm, ci-passed

#7044 Add vector data memroy existence check
  internal/querynode/query_collection.go
Labels: size/M, approved, lgtm, ci-passed, component/querynode

#7057 [automated] Bumped milvus verison to 2.0.0-rc.4
  deployments/docker/cluster/docker-compose.yml
  deployments/docker/standalone/docker-compose.yml
Labels: size/S, approved, lgtm, ci-passed

#7024 [skip ci] Add part chaos experment pod failure and container kill
  tests20/python_client/chaos/chaos_objects/chaos_datanode_container_kill.yaml
  tests20/python_client/chaos/chaos_objects/chaos_datanode_pod_failure.yaml
  tests20/python_client/chaos/chaos_objects/chaos_querynode_pod_failure.yaml
  tests20/python_client/chaos/chaos_objects/testcases.yaml
  tests20/python_client/chaos/checker.py
  tests20/python_client/chaos/test_chaos.py
  tests20/python_client/scale/constants.py
  tests20/python_client/scale/helm_env.py
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed

#7053 Fix expire allocation bug
  internal/datacoord/segment_manager.go
  internal/datacoord/segment_manager_test.go
Labels: component/datacoord, size/M, approved, lgtm, ci-passed

#7054 Change growing segment default value to -1
  internal/core/src/segcore/SegmentGrowingImpl.cpp
Labels: size/S, approved, lgtm, ci-passed

#7005 Return error when any failed is detected in loadSegment
  internal/querynode/segment.go
  internal/querynode/segment_loader.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, component/querynode

#7059 Fix querynode tt producer leak
  internal/querynode/flow_graph_service_time_node.go
Labels: size/XS, approved, lgtm, ci-passed, component/querynode

#6993 Fix 6990, enhance the log when parsing grpc recv/send parameters
  internal/distributed/datacoord/client/paramtable.go
  internal/distributed/datacoord/paramtable.go
  internal/distributed/datanode/client/paramtable.go
  internal/distributed/datanode/param_table.go
  internal/distributed/indexcoord/client/paramtable.go
  internal/distributed/indexcoord/paramtable.go
  internal/distributed/indexnode/client/paramtable.go
  internal/distributed/indexnode/paramtable.go
  internal/distributed/proxy/client/paramtable.go
  internal/distributed/proxy/paramtable.go
  internal/distributed/querycoord/client/paramtable.go
  internal/distributed/querycoord/param_table.go
  internal/distributed/querynode/client/paramtable.go
  internal/distributed/querynode/param_table.go
  internal/distributed/rootcoord/client/paramtable.go
  internal/distributed/rootcoord/param_table.go
  internal/util/paramtable/basetable.go
  internal/util/paramtable/basetable_test.go
Labels: size/XL, approved, lgtm, ci-passed

#7066 Optimize reduce logic
  internal/core/src/common/Types.h
  internal/core/src/query/Plan.cpp
  internal/core/src/segcore/SegmentInterface.cpp
  internal/core/src/segcore/reduce_c.cpp
  internal/core/src/segcore/reduce_c.h
  internal/core/src/segcore/segment_c.cpp
  internal/core/src/segcore/segment_c.h
  internal/core/unittest/test_c_api.cpp
  internal/querynode/query_collection.go
  internal/querynode/reduce.go
  internal/querynode/reduce_test.go
  internal/querynode/segment.go
  internal/querynode/segment_test.go
  internal/querynode/streaming.go
Labels: size/L, approved, lgtm, ci-passed, component/querynode

#7071 Add, enable and xfail test cases
  build/ci/jenkins/NightlyCI.groovy
  tests/python_test/entity/test_insert.py
  tests/python_test/pytest.ini
  tests/scripts/e2e.sh
  tests20/python_client/base/utility_wrapper.py
  tests20/python_client/check/func_check.py
  tests20/python_client/common/common_func.py
  tests20/python_client/common/common_type.py
  tests20/python_client/conftest.py
  tests20/python_client/pytest.ini
  tests20/python_client/testcases/test_search.py
  tests20/python_client/testcases/test_utility.py
Labels: sig/testing, size/XL, approved, lgtm, area/test, ci-passed

#7063 [skip ci]Update approvers
  .github/OWNERS
  OWNERS
  OWNERS_ALIASES
  build/OWNERS
  cmd/OWNERS
  configs/OWNERS
  deployments/OWNERS
  docs/OWNERS
  githooks/OWNERS
  internal/allocator/OWNERS
  internal/core/OWNERS
  internal/datacoord/OWNERS
  internal/datanode/OWNERS
  internal/distributed/OWNERS
  internal/indexcoord/OWNERS
  internal/indexnode/OWNERS
  internal/kv/OWNERS
  internal/log/OWNERS
  internal/msgstream/OWNERS
  internal/proto/OWNERS
  internal/proxy/OWNERS
  internal/querycoord/OWNERS
  internal/querynode/OWNERS
  internal/rootcoord/OWNERS
  internal/storage/OWNERS
  internal/tso/OWNERS
  internal/util/OWNERS
  scripts/OWNERS
  tests/OWNERS
  tests20/OWNERS
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed

#7061 Add a checker to listen for the timetick.
  internal/datacoord/server.go
  internal/datacoord/util.go
Labels: component/datacoord, size/M, approved, lgtm, ci-passed

#6965 Add Datanode watch etcd channel
  internal/datanode/data_node.go
  internal/datanode/data_node_test.go
  internal/proto/data_coord.proto
  internal/proto/datapb/data_coord.pb.go
Labels: component/datanode, size/L, approved, lgtm, ci-passed

#7083 Fix master branch unittest err
  internal/datanode/data_node.go
  internal/datanode/data_node_test.go
Labels: component/datanode, size/L, approved, lgtm, ci-passed

#7087 Disable test cases
  tests20/python_client/testcases/test_search.py
  tests20/python_client/testcases/test_utility.py
Labels: sig/testing, size/M, approved, lgtm, area/test, ci-passed

#7097 [skip ci]Add yanliang567 into pr-inspection
  OWNERS_ALIASES
Labels: size/XS, approved, lgtm, ci-passed

#7096 Set common var 'vectors' as a global var and add a search test case
  tests20/python_client/testcases/test_search.py
Labels: sig/testing, size/M, approved, lgtm, area/test, ci-passed

#7074 IndexNode dose not need to wait for IndexCoord to start to comlete
  go.mod
  internal/distributed/indexcoord/service.go
  internal/distributed/indexnode/service.go
  internal/indexcoord/index_coord.go
  internal/indexnode/indexnode.go
Labels: component/indexnode, component/indexcoord, size/M, approved, lgtm, ci-passed

#7102 Optimize retrieve output vector code structure
  internal/core/src/segcore/SegmentInterface.cpp
  internal/proxy/task.go
  internal/querynode/historical.go
  internal/querynode/query_collection.go
  internal/querynode/segment.go
  internal/querynode/streaming.go
  internal/storage/vector_chunk_manager.go
  internal/storage/vector_chunk_manager_test.go
Labels: size/L, approved, lgtm, ci-passed

#7085 Fix segment auto flush bug
  internal/datacoord/server.go
  internal/datacoord/server_test.go
Labels: size/L, approved, lgtm, ci-passed

#7094 [skip ci] add argo.yaml and update readme for benchmark
  tests/milvus_benchmark/Dockerfile
  tests/milvus_benchmark/README.md
  tests/milvus_benchmark/asserts/uml.jpg
  tests/milvus_benchmark/ci/argo.yaml
  tests/milvus_benchmark/milvus_benchmark/chaos/chaos_opt.py
  tests/milvus_benchmark/milvus_benchmark/chaos/utils.py
  tests/milvus_benchmark/milvus_benchmark/client.py
  tests/milvus_benchmark/milvus_benchmark/main.py
  tests/milvus_benchmark/milvus_benchmark/metrics/models/server.py
  tests/milvus_benchmark/milvus_benchmark/runners/__init__.py
  tests/milvus_benchmark/milvus_benchmark/runners/accuracy.py
  tests/milvus_benchmark/milvus_benchmark/runners/get.py
  tests/milvus_benchmark/milvus_benchmark/runners/insert.py
  tests/milvus_benchmark/milvus_benchmark/runners/locust.py
  tests/milvus_benchmark/milvus_benchmark/runners/locust_tasks.py
  tests/milvus_benchmark/milvus_benchmark/runners/search.py
  tests/milvus_benchmark/milvus_benchmark/runners/test.py
  tests/milvus_benchmark/milvus_benchmark/update.py
  tests/milvus_benchmark/requirements.txt
Labels: sig/testing, size/XL, approved, lgtm, area/test, ci-passed

#7104 Fix search hang when querynode only load sealed segment
  internal/querynode/query_collection.go
  internal/querynode/query_collection_test.go
  internal/querynode/query_node_test.go
Labels: size/L, approved, lgtm, ci-passed

#6848 Remove RetrieveRequest and RetrieveTask
  internal/core/src/pb/milvus.pb.cc
  internal/core/src/pb/milvus.pb.h
  internal/distributed/proxy/service.go
  internal/proto/milvus.proto
  internal/proto/milvuspb/milvus.pb.go
  internal/proxy/dummyreq.go
  internal/proxy/dummyreq_test.go
  internal/proxy/impl.go
  internal/proxy/task.go
  internal/proxy/task_scheduler.go
Labels: size/XXL, approved, lgtm, ci-passed

#6617 Rocksmq support retention
  cmd/roles/roles.go
  configs/milvus.yaml
  docs/developer_guides/chap05_proxy.md
  internal/kv/rocksdb/rocksdb_kv.go
  internal/kv/rocksdb/rocksdb_kv_test.go
  internal/msgstream/mq_factory.go
  internal/msgstream/mq_msgstream_test.go
  internal/rootcoord/param_table.go
  internal/util/mqclient/rmq_client_test.go
  internal/util/mqclient/rmq_producer.go
  internal/util/rocksmq/client/rocksmq/client_impl.go
  internal/util/rocksmq/client/rocksmq/consumer.go
  internal/util/rocksmq/client/rocksmq/consumer_impl.go
  internal/util/rocksmq/client/rocksmq/producer.go
  internal/util/rocksmq/client/rocksmq/producer_impl.go
  internal/util/rocksmq/server/rocksmq/global_rmq.go
  internal/util/rocksmq/server/rocksmq/rocksmq_impl.go
  internal/util/rocksmq/server/rocksmq/rocksmq_impl_test.go
  internal/util/rocksmq/server/rocksmq/rocksmq_retention.go
  internal/util/rocksmq/server/rocksmq/rocksmq_retention_test.go
Labels: size/XXL, approved, lgtm, ci-passed

#6971 Add ConfAdapter to check search
  internal/core/src/query/SearchOnSealed.cpp
Labels: size/XS, approved, lgtm, ci-passed

#7119 Add EarliestMessageID patch logic
  internal/util/mqclient/pulsar_consumer.go
  internal/util/mqclient/pulsar_consumer_test.go
Labels: size/M, approved, lgtm, ci-passed

#7113 Expose metrics of QueryCoord and QueryNodes
  internal/core/src/pb/milvus.pb.cc
  internal/core/src/pb/milvus.pb.h
  internal/distributed/querycoord/client/client.go
  internal/distributed/querycoord/service.go
  internal/distributed/querynode/client/client.go
  internal/distributed/querynode/service.go
  internal/proto/milvus.proto
  internal/proto/milvuspb/milvus.pb.go
  internal/proto/query_coord.proto
  internal/proto/querypb/query_coord.pb.go
  internal/querycoord/cluster.go
  internal/querycoord/cluster_test.go
  internal/querycoord/errors.go
  internal/querycoord/errors_test.go
  internal/querycoord/impl.go
  internal/querycoord/metrics_info.go
  internal/querycoord/metrics_info_test.go
  internal/querycoord/querynode.go
  internal/querycoord/querynode_test.go
  internal/querynode/errors.go
  internal/querynode/errors_test.go
  internal/querynode/impl.go
  internal/querynode/metrics_info.go
  internal/querynode/metrics_info_test.go
  internal/types/types.go
  internal/util/metricsinfo/err.go
  internal/util/metricsinfo/metric_type.go
  internal/util/metricsinfo/metric_type_test.go
  internal/util/metricsinfo/topology.go
  internal/util/metricsinfo/topology_test.go
Labels: size/XXL, approved, lgtm, ci-passed

#7124 Add yaml file of codecov
  codecov.yml
  internal/util/rocksmq/server/rocksmq/rocksmq_impl.go
Labels: size/M, approved, lgtm, ci-passed

#7136 Lock when writing meta instead of trying to connect to indexnode
  internal/indexcoord/node_manager.go
Labels: size/S, approved, lgtm, ci-passed

#7141 Adding indexnode should be processed asynchronously
  internal/indexcoord/index_coord.go
Labels: size/S, approved, lgtm, ci-passed

#7090 Send notification emails to contributors when publish Milvus images failed
  build/ci/jenkins/PublishImages.groovy
Labels: size/S, approved, lgtm, ci-passed

#7143 Let system panic if kv operation fail
  internal/rootcoord/meta_table.go
  internal/rootcoord/meta_table_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed

#7137 Expose system topology information by proxy
  internal/core/src/pb/milvus.pb.cc
  internal/distributed/proxy/service.go
  internal/proto/milvus.proto
  internal/proto/milvuspb/milvus.pb.go
  internal/proxy/error.go
  internal/proxy/error_test.go
  internal/proxy/impl.go
  internal/proxy/metrics_info.go
  internal/querycoord/metrics_info.go
  internal/querynode/metrics_info.go
  internal/util/metricsinfo/metrics_info.go
  internal/util/metricsinfo/metrics_info_test.go
  internal/util/metricsinfo/topology.go
  internal/util/metricsinfo/topology_test.go
Labels: size/XXL, approved, lgtm, ci-passed

#6910 [doc] Replace "JAVA" with "Java" in milvus20vs1x.md
  milvus20vs1x.md
Labels: kind/documentation, size/XS, approved, lgtm, ci-passed

#7140 Fix calc_distance TANIMOTO bug
  internal/util/distance/calc_distance.go
  internal/util/distance/calc_distance_test.go
Labels: size/XS, approved, lgtm, ci-passed

#7123 Fix timestamp go back issue
  internal/distributed/rootcoord/service_test.go
  internal/kv/kv.go
  internal/rootcoord/dml_channels.go
  internal/rootcoord/meta_snapshot.go
  internal/rootcoord/meta_snapshot_test.go
  internal/rootcoord/meta_table.go
  internal/rootcoord/meta_table_test.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/task.go
  internal/rootcoord/timeticksync.go
Labels: kind/bug, size/XL, approved, lgtm, ci-passed

#7144 Add ignore list in codecov
  codecov.yml
  internal/util/rocksmq/server/rocksmq/rocksmq_impl.go
Labels: size/M, approved, lgtm, ci-passed

#7152 [skip ci] Fix the failure count is always zero in chaos test
  tests20/python_client/chaos/checker.py
  tests20/python_client/check/func_check.py
Labels: sig/testing, size/S, approved, lgtm, area/test, ci-passed

#7134 Make users get vectors without using local storage
  configs/milvus.yaml
  internal/querynode/historical.go
  internal/querynode/query_collection.go
  internal/querynode/query_collection_test.go
  internal/querynode/query_service.go
  internal/querynode/segment.go
  internal/storage/minio_chunk_manager.go
  internal/storage/vector_chunk_manager.go
  internal/storage/vector_chunk_manager_test.go
Labels: size/L, approved, lgtm, ci-passed

#7157 Expose metrics of IndexCoord and IndexNodes
  internal/distributed/indexcoord/client/client.go
  internal/distributed/indexcoord/service.go
  internal/distributed/indexnode/client/client.go
  internal/distributed/indexnode/service.go
  internal/indexcoord/errors.go
  internal/indexcoord/errors_test.go
  internal/indexcoord/index_coord.go
  internal/indexcoord/index_coord_test.go
  internal/indexcoord/metrics_info.go
  internal/indexcoord/metrics_info_test.go
  internal/indexcoord/node_manager.go
  internal/indexcoord/node_manager_test.go
  internal/indexnode/errors.go
  internal/indexnode/errors_test.go
  internal/indexnode/indexnode.go
  internal/indexnode/indexnode_test.go
  internal/indexnode/metrics_info.go
  internal/indexnode/metrics_info_test.go
  internal/proto/index_coord.proto
  internal/proto/indexpb/index_coord.pb.go
  internal/types/types.go
  internal/util/metricsinfo/metric_type.go
  internal/util/metricsinfo/metric_type_test.go
  internal/util/metricsinfo/metrics_info.go
  internal/util/metricsinfo/metrics_info_test.go
  internal/util/metricsinfo/topology.go
  internal/util/metricsinfo/topology_test.go
Labels: size/XXL, approved, lgtm, ci-passed

#6590 Save binlog path in SegmentInfo
  internal/datacoord/binlog_helper.go
  internal/datacoord/datanode_helper.go
  internal/datacoord/grpc_services.go
  internal/datacoord/meta.go
  internal/datacoord/segment_info.go
  internal/datacoord/server.go
  internal/datacoord/server_test.go
  internal/datanode/data_node.go
  internal/datanode/data_sync_service.go
  internal/datanode/flow_graph_insert_buffer_node.go
  internal/datanode/flow_graph_insert_buffer_node_test.go
  internal/datanode/flow_graph_message.go
  internal/proto/data_coord.proto
  internal/proto/datapb/data_coord.pb.go
Labels: kind/enhancement, size/XXL, approved, lgtm, ci-passed

#6996 Add flush interval
  internal/datacoord/meta.go
  internal/datacoord/segment_allocation_policy.go
  internal/datacoord/segment_info.go
  internal/datacoord/segment_manager_test.go
  internal/datacoord/server.go
Labels: size/M, approved, lgtm, ci-passed

#7167 Fix IVF_FLAT index's wrong meta_data
  internal/core/src/index/knowhere/knowhere/common/Utils.cpp
  internal/core/unittest/test_index_wrapper.cpp
Labels: size/S, approved, lgtm, ci-passed

#7163 Increase the timeout for grpc connection when create index
  internal/indexcoord/index_coord.go
Labels: size/M, approved, lgtm, ci-passed

#7151 Fix DropCollection not processed by datanode
  internal/rootcoord/dml_channels.go
  internal/rootcoord/task.go
  internal/rootcoord/timeticksync.go
Labels: size/M, approved, lgtm, ci-passed

#7160 Enable 70% of delta condition judgment for codecov
  .github/mergify.yml
  codecov.yml
  internal/util/rocksmq/server/rocksmq/rocksmq_impl.go
Labels: size/XS, approved, lgtm, ci-passed

#7190 Comment non-exists tests/go path
  Makefile
Labels: size/XS, approved, lgtm, ci-passed

#7172 Add a seal policy which restricts the lifetime of a segment
  internal/datacoord/policy.go
  internal/datacoord/segment_allocation_policy.go
  internal/datacoord/segment_allocation_policy_test.go
  internal/datacoord/segment_manager.go
Labels: size/M, approved, lgtm, ci-passed

#7175 Improper error returned by calc_distance
  internal/proxy/impl.go
Labels: size/XS

#7194 Add README for Milvus installation through binary file
  deployments/binary/README.md
Labels: size/M, approved, lgtm, ci-passed

#7207 Add build-cpp as a dependency of verifiers
  Makefile
Labels: size/XS

#7200 Fix rocksdb not installed problem
  internal/kv/rocksdb/cwrapper/CMakeLists.txt
Labels: size/XS, approved, lgtm

#7188 Add sync logic in TestWatchChannel
  internal/datanode/data_node_test.go
Labels: size/XS, approved, lgtm, ci-passed

#7197 Add datacoord unit tests
  internal/datacoord/cluster.go
  internal/datacoord/policy.go
  internal/datacoord/policy_test.go
  internal/datacoord/segment_allocation_policy.go
  internal/datacoord/segment_allocation_policy_test.go
  internal/datacoord/server_test.go
  internal/datacoord/util.go
  internal/datacoord/util_test.go
Labels: size/L, approved, lgtm, ci-passed

#7203 Add connection timeout
  internal/distributed/datacoord/client/client.go
  internal/distributed/datanode/client/client.go
  internal/distributed/indexcoord/client/client.go
  internal/distributed/indexnode/client/client.go
  internal/distributed/proxy/client/client.go
  internal/distributed/querycoord/client/client.go
  internal/distributed/querynode/client/client.go
  internal/distributed/rootcoord/client/client.go
Labels: size/M, approved, lgtm, ci-passed

#7198 Increase ephemeral-storage for krte container
  build/ci/jenkins/pod/krte.yaml
Labels: size/XS, approved, lgtm, ci-passed

#7205 [skip ci] Update readme and requirements.txt in milvus_benchmark
  tests/benchmark/README.md
  tests/benchmark/asserts/dash.png
  tests/benchmark/requirements.txt
Labels: kind/documentation, size/M, approved, lgtm, ci-passed

#6867 Add connection manager
  internal/distributed/connection_manager.go
  internal/distributed/connection_manager_test.go
Labels: size/XL, approved, lgtm, ci-passed

#7204 [skip ci] Update architecture overview on readmes
  README.md
  README_CN.md
Labels: size/XS, approved, lgtm, ci-passed

#7227 Proxy add illegal check for search result
  internal/proxy/task.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/timeticksync.go
Labels: size/L, approved, lgtm, ci-passed

#7230 Add testcases for expression extend grammar
  tests/python_client/common/common_func.py
  tests/python_client/testcases/test_search_20.py
Labels: sig/testing, size/M, approved, lgtm, area/test, ci-passed

#7231 Add segment filter interface
  go.mod
  go.sum
  internal/util/segmentfilter/segment_filter.go
Labels: size/M, approved, lgtm, ci-passed

#7226 Refactor datacoord allocator
  internal/datacoord/allocator.go
  internal/datacoord/allocator_test.go
  internal/datacoord/datanode_helper.go
  internal/datacoord/meta_test.go
  internal/datacoord/mock_test.go
  internal/datacoord/segment_manager.go
  internal/datacoord/segment_manager_test.go
  internal/datacoord/server.go
Labels: size/L, approved, lgtm, ci-passed

#7248 Update script of run_go_codecov
  internal/util/rocksmq/server/rocksmq/rocksmq_impl.go
  scripts/run_go_codecov.sh
Labels: size/XS, approved, lgtm, ci-passed

#7239 Enable test cases after code fix
  build/ci/jenkins/NightlyCI.groovy
  build/ci/jenkins/pod/krte.yaml
  tests/python_client/common/common_func.py
  tests/python_client/requirements.txt
  tests/python_client/testcases/test_partition_20.py
  tests/python_client/testcases/test_search_20.py
  tests/python_client/testcases/test_utility_20.py
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed

#7244 Correct empty search result handle
  internal/proto/internal.proto
  internal/proto/internalpb/internal.pb.go
  internal/proxy/task.go
  internal/querynode/query_collection.go
Labels: size/L, approved, lgtm, ci-passed

#7257 Add */*.pb.go to codecov.yml
  codecov.yml
Labels: size/XS, approved, lgtm, ci-passed

#7253 Remove service time check in streaming search
  internal/querynode/streaming.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed

#7243 Add a method to move binlog path to SegmentInfo when datacoord startup
  Makefile
  cmd/tools/move_binlog_path_helper.go
  internal/datacoord/meta.go
  internal/datacoord/mock_test.go
  internal/datacoord/move_binlog_path_helper.go
  internal/datacoord/move_binlog_path_helper_test.go
  internal/datacoord/segment_info.go
  internal/datacoord/server.go
  internal/kv/mem/mem_kv.go
  internal/proto/data_coord.proto
  internal/proto/datapb/data_coord.pb.go
Labels: sig/testing, size/XL, approved, lgtm, area/test, ci-passed

#7263 [skip ci] Optimize helm deployment in scale test
  tests/python_client/scale/helm_env.py
  tests/python_client/scale/scale_common.py
  tests/python_client/scale/test_data_node_scale.py
  tests/python_client/scale/test_index_node_scale.py
  tests/python_client/scale/test_proxy_scale.py
  tests/python_client/scale/test_query_node_scale.py
Labels: sig/testing, size/M, approved, lgtm, area/test, ci-passed

#7271 Fix not exist milvus chart
  tests/python_client/scale/helm_env.py
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed

#7272 Fix 0 ts when build index
  internal/rootcoord/meta_table.go
  internal/rootcoord/meta_table_test.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/task.go
Labels: size/S, approved, lgtm, ci-passed

#7268 Construct bloom filter when inserting
  internal/datanode/flow_graph_insert_buffer_node.go
  internal/datanode/segment_replica.go
  internal/datanode/segment_replica_test.go
Labels: size/L, approved, lgtm, ci-passed

#6918 [skip ci] Add design doc for proxy
  docs/design_docs/graphs/collection_dm_channels.png
  docs/design_docs/graphs/decouple.jpeg
  docs/design_docs/graphs/proxy.png
  docs/design_docs/graphs/proxy_channels.png
  docs/design_docs/graphs/task_scheduler_1.png
  docs/design_docs/graphs/task_scheduler_2.png
  docs/design_docs/proxy.md
Labels: kind/documentation, size/XL, approved, lgtm, ci-passed

#7281 Increase execution time for nightly tests
  build/ci/jenkins/NightlyCI.groovy
  tests/scripts/e2e.sh
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed

#7278 Enable etcd auto compaction for every 1000 revision
  build/ci/jenkins/pod/krte.yaml
Labels: size/XS, approved, lgtm, ci-passed

#7279 Add prepare_e2e.sh
  tests/scripts/e2e-k8s.sh
  tests/scripts/e2e.sh
  tests/scripts/prepare_e2e.sh
Labels: sig/testing, size/M, approved, lgtm, area/test, ci-passed

#7276 Add unit test for 7150 fix
  internal/rootcoord/meta_snapshot.go
  internal/rootcoord/meta_snapshot_test.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
Labels: size/L, approved, lgtm, ci-passed

#7225 Closes abandoned issues after a period of inactivity
  .github/stale.yml
Labels: size/S, approved, lgtm, ci-passed

#7246 Integrate reportportal into nightly CI
  build/ci/jenkins/NightlyCI.groovy
  tests/python_client/pytest.ini
  tests/python_client/requirements.txt
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed

#7294 Update stale.yml
  .github/stale.yml
Labels: size/XS, approved, lgtm, ci-passed

#7298 Add ignore message of **/*.pb.go to codecov.yml
  codecov.yml
Labels: size/XS, approved, lgtm, ci-passed

#7303 add query node segment filter
  internal/datanode/flow_graph_delete_node.go
  internal/datanode/flow_graph_delete_node_test.go
  internal/querynode/query_collection.go
  internal/querynode/query_collection_test.go
  internal/querynode/segment.go
  internal/util/segmentfilter/segment_filter.go
Labels: size/L, approved, lgtm, ci-passed

#7339 Fix bug for expression boundary
  internal/core/src/query/PlanProto.cpp
Labels: size/XS, approved, lgtm, ci-passed

#7342 Add unittest for proxy
  internal/proxy/condition.go
  internal/proxy/segment.go
  internal/proxy/segment_test.go
Labels: size/L, approved, lgtm, ci-passed

#7346 Fix querycoord panic when stop nil conn of querynodeClient
  internal/distributed/querynode/client/client.go
  internal/distributed/querynode/client/client_test.go
Labels: size/S, approved, lgtm, ci-passed

#7335 Improve docker-compose config for Pulsar and fix graceful shutdown so that restart would work
  deployments/docker/cluster/docker-compose.yml
  deployments/docker/dev/docker-compose.yml
  docker-compose.yml
Labels: size/M, approved, lgtm, ci-passed

#6519 [skip ci] knowhere detail design
  docs/design_docs/graphs/create_index.png
  docs/design_docs/graphs/knn_query.png
  docs/design_docs/graphs/knowhere_framework.png
  docs/design_docs/knowhere_design.md
Labels: kind/documentation, size/M, approved, lgtm, ci-passed

#7336 Fix datanode corner cases
  internal/datanode/data_sync_service.go
  internal/datanode/flow_graph_insert_buffer_node.go
  internal/datanode/flow_graph_insert_buffer_node_test.go
  internal/datanode/meta_service.go
  internal/datanode/meta_service_test.go
Labels: size/L, approved, lgtm, ci-passed

#7352 Fix pulsar startup command
  deployments/docker/cluster/docker-compose.yml
  deployments/docker/dev/docker-compose.yml
Labels: size/S, approved, lgtm, ci-passed

#7355 Clean fmt.Println in util/flowgraph
  internal/util/flowgraph/node.go
  internal/util/flowgraph/type_def.go
  internal/util/sessionutil/session_util.go
Labels: size/S, approved, lgtm, ci-passed

#7368 [automated] Update docker compose files for deployments
  deployments/docker/cluster/docker-compose.yml
  deployments/docker/standalone/docker-compose.yml
Labels: size/S, approved, lgtm, ci-passed

#7363 Update search testcases
  tests/python_client/testcases/collection/test_load_collection.py
  tests/python_client/testcases/entity/test_search.py
  tests/python_client/testcases/test_search_20.py
Labels: sig/testing, size/S, approved, lgtm, area/test, ci-passed

#7371 Update test case
  tests/python_client/testcases/test_connect.py
  tests/scripts/e2e.sh
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed

#7323 Support to apply dml msgstream from pool
  configs/advanced/root_coord.yaml
  internal/datanode/data_sync_service.go
  internal/datanode/flow_graph_dd_node.go
  internal/datanode/flow_graph_dmstream_input_node.go
  internal/datanode/flow_graph_insert_buffer_node.go
  internal/querynode/flow_graph_filter_dm_node.go
  internal/querynode/flow_graph_query_node.go
  internal/rootcoord/dml_channels.go
  internal/rootcoord/dml_channels_test.go
  internal/rootcoord/param_table.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
  internal/rootcoord/task.go
  internal/rootcoord/timeticksync.go
  internal/util/timerecord/time_recorder.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed

#7364 Add unittest cases for proxy
  internal/distributed/proxy/service.go
  internal/proxy/channels_mgr.go
  internal/proxy/channels_mgr_test.go
  internal/proxy/channels_time_ticker.go
  internal/proxy/dummyreq_test.go
  internal/proxy/error_test.go
  internal/proxy/insert_channels.go
  internal/proxy/insert_channels_test.go
  internal/proxy/paramtable.go
  internal/proxy/paramtable_test.go
  internal/proxy/proxy.go
  internal/proxy/repack_func.go
  internal/proxy/repack_func_test.go
  internal/proxy/type_def.go
Labels: kind/improvement, size/XXL, approved, lgtm, ci-passed

#7367 Add unittest for timestamp allocator
  internal/proxy/mock.go
  internal/proxy/timestamp.go
  internal/proxy/timestamp_test.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed

#7376 Revert "Support to apply dml msgstream from pool"
  configs/advanced/root_coord.yaml
  internal/datanode/data_sync_service.go
  internal/datanode/flow_graph_dd_node.go
  internal/datanode/flow_graph_dmstream_input_node.go
  internal/datanode/flow_graph_insert_buffer_node.go
  internal/querynode/flow_graph_filter_dm_node.go
  internal/querynode/flow_graph_query_node.go
  internal/rootcoord/dml_channels.go
  internal/rootcoord/dml_channels_test.go
  internal/rootcoord/param_table.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
  internal/rootcoord/task.go
  internal/rootcoord/timeticksync.go
  internal/util/timerecord/time_recorder.go
Labels: size/L, approved, lgtm, ci-passed

#7369 Add log print in proxy
  internal/proxy/impl.go
Labels: size/S, approved, lgtm, ci-passed

#7228 Expose metrics of root coordinator
  internal/distributed/rootcoord/client/client.go
  internal/distributed/rootcoord/service.go
  internal/proto/root_coord.proto
  internal/proto/rootcoordpb/root_coord.pb.go
  internal/rootcoord/errors.go
  internal/rootcoord/errors_test.go
  internal/rootcoord/metrics_info.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
  internal/types/types.go
  internal/util/metricsinfo/metrics_info.go
  internal/util/metricsinfo/metrics_info_test.go
  internal/util/metricsinfo/topology.go
  internal/util/metricsinfo/topology_test.go
Labels: size/L, approved, lgtm, ci-passed

#7378 [skip ci] Replace ORM in Pytest readmes
  tests/python_client/README.md
  tests/python_client/README_CN.md
  tests/python_client/graphs/module_call_diagram.jpg
Labels: sig/testing, size/M, approved, lgtm, area/test, ci-passed

#7366 Change proxy log
  internal/proxy/impl.go
Labels: size/L, approved, lgtm, ci-passed

#7377 Apply for msgstream from pool when creating collection
  configs/advanced/channel.yaml
  configs/advanced/root_coord.yaml
  internal/datanode/data_sync_service.go
  internal/datanode/flow_graph_dd_node.go
  internal/datanode/flow_graph_dmstream_input_node.go
  internal/datanode/flow_graph_insert_buffer_node.go
  internal/querynode/flow_graph_filter_dm_node.go
  internal/querynode/flow_graph_query_node.go
  internal/rootcoord/dml_channels.go
  internal/rootcoord/dml_channels_test.go
  internal/rootcoord/meta_table.go
  internal/rootcoord/param_table.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
  internal/rootcoord/task.go
  internal/rootcoord/timeticksync.go
  internal/util/timerecord/time_recorder.go
Labels: size/L, approved, lgtm, ci-passed

#7385 [skip-ci]Fix pulsar retention configuration
  deployments/docker/cluster/docker-compose.yml
  deployments/docker/dev/docker-compose.yml
Labels: kind/bug, size/XS, approved, lgtm, ci-passed

#7383 Merge pymilvus and orm index cases
  tests/python_client/testcases/test_index.py
  tests/python_client/testcases/test_index_20.py
  tests/python_client/testcases/test_utility_20.py
Labels: sig/testing, size/XXL, approved, lgtm, area/test, ci-passed

#7388 Disable reportportal temporarily
  build/ci/jenkins/NightlyCI.groovy
Labels: size/XS, approved, lgtm, ci-passed
