Repository milvus-io/milvus, pull requests merged in 2021-02, with the labels that each got.

#4677 make metrics label configurable
  CHANGELOG.md
  ci/jenkins/Jenkinsfile
  core/CMakeLists.txt
  core/src/config/Config.cpp
  core/src/config/Config.h
  core/src/metrics/prometheus/PrometheusMetrics.cpp
  sdk/examples/simple/src/ClientTest.cpp
  tests/milvus_benchmark/ci/main_jenkinsfile
  tests/milvus_python_test/test_ping.py
Labels: PR | automerge

#4681 Fix binaryflat
  CHANGELOG.md
  core/src/index/thirdparty/faiss/IndexBinaryFlat.cpp
  core/src/index/thirdparty/faiss/IndexBinaryHNSW.cpp
  core/src/index/thirdparty/faiss/IndexBinaryHash.cpp
  core/src/index/thirdparty/faiss/IndexBinaryIVF.cpp
  core/src/index/thirdparty/faiss/IndexIVFPQ.cpp
  core/src/index/thirdparty/faiss/IndexIVFSpectralHash.cpp
  core/src/index/thirdparty/faiss/IndexLSH.cpp
  core/src/index/thirdparty/faiss/IndexPQ.cpp
  core/src/index/thirdparty/faiss/tests/test_binary_flat.cpp
  core/src/index/thirdparty/faiss/utils/BinaryDistance.cpp
  core/src/index/thirdparty/faiss/utils/BinaryDistance.h
  core/src/index/thirdparty/faiss/utils/distances.cpp
  core/src/index/thirdparty/faiss/utils/distances.h
  core/src/index/thirdparty/faiss/utils/hamming-inl.h
  core/src/index/thirdparty/faiss/utils/hamming.cpp
  core/src/index/thirdparty/faiss/utils/hamming.h
  core/src/index/thirdparty/faiss/utils/jaccard-inl.h
  core/src/index/thirdparty/faiss/utils/substructure-inl.h
  core/src/index/thirdparty/faiss/utils/superstructure-inl.h
Labels: Bug

#4694 BinaryFlat support AVX2
  CHANGELOG.md
  core/src/index/thirdparty/faiss/utils/BinaryDistance.cpp
  core/src/index/thirdparty/faiss/utils/distances_avx.h
  core/src/index/thirdparty/faiss/utils/distances_simd_avx.cpp
  core/src/index/thirdparty/faiss/utils/hamming-inl.h
  core/src/index/thirdparty/faiss/utils/hamming.h
  core/src/index/thirdparty/faiss/utils/jaccard-inl.h
Labels: PR | automerge, PR | improvement

#4698 [skip ci] update change log
  CHANGELOG.md
Labels: PR | automerge, PR | skip-ci

#4699 update knowhere conf
  core/src/index/archive/KnowhereConfig.cpp
  core/src/index/archive/KnowhereConfig.h
  core/src/index/archive/KnowhereResource.h
  core/src/index/unittest/test_knowhere.cpp
  core/src/server/Server.cpp
  core/src/value/config/ServerConfig.h
Labels: PR | automerge

#4705 change type of tps and qps from int64_t to double
  sdk/examples/qps/src/ClientTest.cpp
Labels: PR | automerge, PR | skip-ci

#4702 Code Refactoring
  core/src/db/engine/ExecutionEngineImpl.cpp
  core/src/db/engine/ExecutionEngineImpl.h
  core/src/index/knowhere/knowhere/index/vector_index/ConfAdapter.cpp
  core/src/index/knowhere/knowhere/index/vector_index/ConfAdapter.h
  core/src/index/knowhere/knowhere/index/vector_index/IndexIVFPQ.cpp
  core/src/utils/ValidationUtil.cpp
  core/unittest/db/test_engine.cpp
Labels: PR | automerge

#4720 The GPU cache holds much more data than the configured value
  CHANGELOG.md
  core/src/cache/CpuCacheMgr.cpp
  core/src/cache/GpuCacheMgr.cpp
Labels: Bug | Severity | S2, PR | hotfix

#4709 Add an optional parameter 'nbtis' for IVF_PQ
  CHANGELOG.md
  core/src/index/knowhere/knowhere/index/vector_index/ConfAdapter.cpp
  core/src/index/knowhere/knowhere/index/vector_index/ConfAdapter.h
  core/src/index/knowhere/knowhere/index/vector_index/IndexIVFPQ.cpp
  core/src/index/thirdparty/faiss/IndexIVFPQ.cpp
  core/src/utils/ValidationUtil.cpp
  tests/milvus_python_test/utils.py
Labels: PR | automerge

#4726 cherry-pick 0.10.6 20210219
  CHANGELOG.md
  core/src/cache/CpuCacheMgr.cpp
  core/src/cache/GpuCacheMgr.cpp
Labels: PR | cherry-pick

#4733 Upgrade mishards to v0.10.6
  shards/README.md
  shards/README_CN.md
  shards/all_in_one/all_in_one.yml
  shards/all_in_one_with_mysql/all_in_one.yml
  shards/mishards/service_handler.py
Labels: PR | automerge, PR | skip-ci, mishards

#4738 Support logging to stdout
  CHANGELOG.md
  core/conf/demo/server_config.yaml
  core/conf/server_config.template
  core/src/config/Config.cpp
  core/src/config/Config.h
  core/src/server/Server.cpp
  core/src/utils/LogUtil.cpp
  core/src/utils/LogUtil.h
  core/unittest/server/test_config.cpp
  core/unittest/server/test_util.cpp
Labels: PR | automerge, type/new-feature

#4737 update version to 1.0.0-beta
  ci/jenkins/Jenkinsfile
  core/CMakeLists.txt
  core/src/config/Config.cpp
  tests/milvus_python_test/test_ping.py
Labels: PR | automerge

#4744 Fix mishards probe test bug
  CHANGELOG.md
  shards/all_in_one/probe_test.py
  shards/all_in_one_with_mysql/probe_test.py
Labels: Bug, mishards

#4747 [skip ci] update code owners
  CODEOWNERS
Labels: PR | automerge

#4745 code refactoring
  core/src/index/thirdparty/hnswlib/hnswalg.h
  core/src/utils/Status.cpp
  sdk/cmake/ThirdPartyPackages.cmake
Labels: PR | automerge

#4750 Minor memory leak when building IVF_SQ8 on GPU
  CHANGELOG.md
  core/src/index/knowhere/knowhere/common/Exception.cpp
  core/src/index/knowhere/knowhere/index/vector_index/gpu/IndexGPUIVFPQ.cpp
  core/src/index/knowhere/knowhere/index/vector_index/gpu/IndexGPUIVFSQ.cpp
  core/src/index/knowhere/knowhere/index/vector_index/gpu/IndexIVFSQHybrid.cpp
  core/src/index/unittest/test_annoy.cpp
  core/src/index/unittest/test_binaryidmap.cpp
  core/src/index/unittest/test_binaryivf.cpp
  core/src/index/unittest/test_customized_index.cpp
  core/src/index/unittest/test_gpuresource.cpp
  core/src/index/unittest/test_hnsw.cpp
  core/src/index/unittest/test_idmap.cpp
  core/src/index/unittest/test_ivf.cpp
  core/src/index/unittest/test_nsg.cpp
  core/src/index/unittest/test_sptag.cpp
  core/src/index/unittest/test_vecindex.cpp
  core/src/index/unittest/utils.cpp
  core/src/index/unittest/utils.h
Labels: PR | automerge

#4751 Update version name
  CHANGELOG.md
  INSTALL.md
  ci/jenkins/Jenkinsfile
  core/CMakeLists.txt
  core/src/config/Config.cpp
  tests/milvus_python_test/test_ping.py
Labels: PR | automerge

#4755 [skip ci] add issue 4754 changlog
  CHANGELOG.md
Labels: PR | automerge, PR | skip-ci
