Repository milvus-io/milvus, pull requests merged in 2021-11, with the labels that each got.

#10970 [skip ci] Add comment foe getVecFieldIDsByCollectionID
  internal/querynode/collection_replica.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#10971 [skip ci] Add comment foe getPKFieldIDsByCollectionID
  internal/querynode/collection_replica.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#10972 [skip ci] Add comment foe addPartition
  internal/querynode/collection_replica.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#10974 [skip ci] Remove pr ci anti affinity limit
  build/ci/jenkins/pod/krte.yaml
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#10949 Use primary key only to check search result duplicate
  internal/core/src/segcore/reduce_c.cpp
  internal/proxy/task.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed

#10975 [skip ci] Add copyright for query_collection_test.go
  internal/querynode/query_collection_test.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed

#10903 Change etcdkv clientv3 into MetaKv interface
  internal/datanode/data_node.go
Labels: size/S, approved, lgtm, ci-passed

#10614 Remove knowhere config
  configs/advanced/knowhere.yaml
  configs/milvus.yaml
  internal/indexnode/param_table.go
  internal/proxy/proxy_test.go
  internal/querynode/param_table.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed

#10967 Remove primary key duplicated query result on proxy
  internal/proxy/task.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed

#10977 [skip ci]Deploy new milvus for data consist test if previous step failed
  .github/workflows/pod-kill-chaos-test.yaml
Labels: kind/improvement, size/S, approved, lgtm, ci-passed

#10885 Fix datanode ut using register bug
  internal/datanode/data_node.go
  internal/datanode/data_node_test.go
  internal/datanode/flow_graph_delete_node.go
  internal/datanode/flow_graph_insert_buffer_node.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed

#10983 Add uids and seg_offsets check in segcore
  internal/core/src/segcore/SegmentSealedImpl.cpp
  internal/core/unittest/test_index_wrapper.cpp
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#10982 Change LittleEndian to BigEndian in flow_graph_insert_node
  internal/querynode/flow_graph_insert_node.go
  internal/querynode/flow_graph_insert_node_test.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed

#10990 [skip ci] Add comment
  internal/util/distance/calc_distance_test.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#10991 [skip ci] Add comment
  internal/util/distance/calc_distance.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed

#10992 [skip ci] Typo
  internal/distributed/datanode/param_table.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#10973 [skip ci] Check grammar of index_design docs
  docs/design_docs/index_design.md
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#10978 [skip ci]Update comments in chap06_root_coordinator.md
  docs/developer_guides/chap06_root_coordinator.md
Labels: kind/improvement, size/S, approved, lgtm, ci-passed

#10979 [skip ci]Add comments in chap07_query_coordinator.md
  docs/developer_guides/chap07_query_coordinator.md
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#10980 [skip ci]Add comments in chap09_data_coord.md
  docs/developer_guides/chap09_data_coord.md
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#10986 [skip ci]Fix typo in chaos yaml
  tests/python_client/chaos/chaos_objects/pod_failure/chaos_proxy_pod_failure.yaml
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed

#10877 Improve error message in rootcoord
  internal/rootcoord/meta_table.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#10875 Improve error message in rootcoord
  internal/rootcoord/meta_table.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#10876 Improve error message in rootcoord
  internal/rootcoord/meta_table.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#10987 [skip ci] Fix typo in test comments
  tests/python_client/testcases/test_search_20.py
Labels: kind/improvement, sig/testing, size/S, approved, lgtm, area/test, ci-passed

#10988 [skip ci] Shorten long sentences
  tests/python_client/testcases/test_search_20.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed

#10989 [skip ci] Improve the description
  tests/benchmark/README.md
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed

#10995 [skip ci] Skip test case
  tests/python_client/testcases/test_search_20.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed

#10996 [skip ci]Fix allocator typo
  internal/datacoord/allocator.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#10997 [skip ci]Fix allocator typo
  internal/datacoord/allocator.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#10998 [skip ci]Fix allocator typo
  internal/datacoord/allocator.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#10999 [skip ci]Fix golint error for ShowPartitions in QueryCoord
  internal/distributed/querycoord/service.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#11000 [skip ci]Fix golint error for GetPartitionStates in QueryCoord
  internal/distributed/querycoord/service.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#11001 [skip ci]Fix golint error for LoadPartitions in QueryCoord
  internal/distributed/querycoord/service.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#11008 Bump milvus version to 2.0.0-rc8
  deployments/docker/cluster/docker-compose.yml
  deployments/docker/standalone/docker-compose.yml
Labels: kind/improvement, size/S, approved, lgtm, ci-passed

#11011 [skip ci] Refine binary deployments doc
  deployments/binary/README.md
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#10994 Fix bug for indexnode load balancing
  internal/indexcoord/node_manager.go
  internal/indexcoord/priority_queue.go
  internal/indexcoord/priority_queue_test.go
Labels: size/M, approved, lgtm, ci-passed

#11012 [skip ci] Add new func of benchmark
  tests/benchmark/milvus_benchmark/update.py
Labels: kind/improvement, sig/testing, size/S, approved, lgtm, area/test, ci-passed

#11015 [skip ci]Rename podkill to pod_kill and fix chaos_test.sh script
  tests/python_client/chaos/chaos_objects/pod_kill/chaos_datacoord_pod_kill.yaml
  tests/python_client/chaos/chaos_objects/pod_kill/chaos_datanode_pod_kill.yaml
  tests/python_client/chaos/chaos_objects/pod_kill/chaos_etcd_pod_kill.yaml
  tests/python_client/chaos/chaos_objects/pod_kill/chaos_indexcoord_pod_kill.yaml
  tests/python_client/chaos/chaos_objects/pod_kill/chaos_indexnode_pod_kill.yaml
  tests/python_client/chaos/chaos_objects/pod_kill/chaos_minio_pod_kill.yaml
  tests/python_client/chaos/chaos_objects/pod_kill/chaos_proxy_pod_kill.yaml
  tests/python_client/chaos/chaos_objects/pod_kill/chaos_pulsar_pod_kill.yaml
  tests/python_client/chaos/chaos_objects/pod_kill/chaos_querycoord_pod_kill.yaml
  tests/python_client/chaos/chaos_objects/pod_kill/chaos_querynode_pod_kill.yaml
  tests/python_client/chaos/chaos_objects/pod_kill/chaos_rootcoord_pod_kill.yaml
  tests/python_client/chaos/chaos_objects/pod_kill/testcases.yaml
  tests/python_client/chaos/chaos_test.sh
Labels: kind/improvement, sig/testing, size/M, approved, lgtm, area/test, ci-passed

#11018 [skip ci] Test chaos memory stress querynode
  tests/python_client/chaos/chaos_objects/memory_stress/chaos_querynode_memory_stress.yaml
  tests/python_client/chaos/test_chaos_memory_stress.py
Labels: kind/improvement, sig/testing, size/M, approved, lgtm, area/test, ci-passed

#11016 [skip ci] Update codes of benchmark
  tests/benchmark/milvus_benchmark/runners/accuracy.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed

#11017 [skip ci] Add comments of benchmark
  tests/benchmark/milvus_benchmark/runners/base.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed

#11002 [skip ci]Remove test code for milvus operator
  tests/python_client/customize/milvus_operator.py
Labels: kind/improvement, sig/testing, size/M, approved, lgtm, area/test, ci-passed

#11005 [skip ci]Update typo in create index md
  docs/design_docs/milvus_create_index_en.md
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, kind/developer-doc

#11006 [skip ci]Update drop collection md
  docs/design_docs/milvus_drop_collection_en.md
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#10981 Fix session util using the same context
  internal/util/sessionutil/session_util.go
Labels: size/S, approved, lgtm, ci-passed

#11019 Update test API CheckSearchResultDuplicate
  internal/core/unittest/test_c_api.cpp
Labels: kind/improvement, size/M, approved, lgtm, ci-passed

#11037 [skip ci]Update grafana panel
  deployments/monitor/grafana/milvus-dashboard.json
Labels: kind/improvement, size/L, approved, lgtm, ci-passed

#11029 Fix rocksmq SeekToLatest
  internal/msgstream/mq_msgstream_test.go
  internal/util/rocksmq/server/rocksmq/rocksmq_impl.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed

#11038 [skip ci] Comment out chaos test
  tests/python_client/chaos/test_chaos_memory_stress.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed

#11039 [skip ci]Update grafana panel description
  deployments/monitor/grafana/milvus-dashboard.json
Labels: kind/improvement, size/M, approved, lgtm, ci-passed

#11051 Fix stale segments selector
  internal/datacoord/server.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#11047 [skip ci] Add comments for AddQueryChannel
  internal/querynode/impl.go
Labels: kind/improvement, approved, lgtm, ci-passed

#11024 [skip ci] Fix golint warning of roles.go
  cmd/roles/roles.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#11020 [skip ci] Add comment for removePartition
  internal/querynode/collection_replica.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#11021 [skip ci] Add comment for getPartitionByID
  internal/querynode/collection_replica.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#11022 [skip ci] Add comment for hasPartition
  internal/querynode/collection_replica.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#11026 [skip ci] Fix golint warning of conf_adapter_mgr.go
  internal/util/indexparamcheck/conf_adapter_mgr.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#11028 [skip ci]Update license for in errors
  internal/indexnode/errors.go
  internal/indexnode/errors_test.go
  internal/indexnode/index.go
  internal/indexnode/index_test.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed

#11030 [skip ci]Update license for in in
  internal/indexnode/indexnode.go
  internal/indexnode/indexnode_mock.go
  internal/indexnode/indexnode_mock_test.go
  internal/indexnode/indexnode_test.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed

#11031 [skip ci]Update license for in pt
  internal/indexnode/metrics_info.go
  internal/indexnode/metrics_info_test.go
  internal/indexnode/param_table.go
  internal/indexnode/param_table_test.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed

#11032 [skip ci]Update in task
  internal/indexnode/task.go
  internal/indexnode/task_scheduler.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed

#11042 [skip ci]Update grafana panel
  deployments/monitor/grafana/milvus-dashboard.json
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#11044 [skip ci] Remove xfail tag for delte issue fix
  tests/python_client/testcases/test_delete_20.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed

#11048 [skip ci] Add comments for RemoveQueryChannel
  internal/querynode/impl.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#11049 [skip ci] Add comments for ReleasePartitions
  internal/querynode/impl.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#11052 [skip ci]Add rocksmq client comments
  internal/util/rocksmq/client/rocksmq/client_impl.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#11058 Reorder header files for segcore/AckResponder.h
  internal/core/src/segcore/AckResponder.h
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#11059 Reorder header files for segcore/Collection.h
  internal/core/src/segcore/Collection.h
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#11065 [skip ci]Fix chaos yaml name in github action
  .github/workflows/pod-kill-chaos-test.yaml
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#11063 Reorder header files for segcore/ConcurrentVector.h
  internal/core/src/segcore/ConcurrentVector.h
Labels: kind/improvement, size/S, approved, lgtm, ci-passed

#11066 Reorder header files for segcore/FieldIndexing.cpp
  internal/core/src/segcore/FieldIndexing.cpp
Labels: kind/improvement, size/S, approved, lgtm, ci-passed

#11067 Reorder header files for segcore/FieldIndexing.h
  internal/core/src/segcore/FieldIndexing.h
Labels: kind/improvement, size/S, approved, lgtm, ci-passed

#11057 Fix SeekToLatest memory leakage and remove redundant logic
  internal/util/rocksmq/server/rocksmq/rocksmq_impl.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed

#11064 Reorder header files for segcore/DeletedRecord.h
  internal/core/src/segcore/DeletedRecord.h
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#11077 [skip ci]Update OWNERS file
  internal/proto/OWNERS
Labels: kind/improvement, size/M, approved, lgtm, ci-passed

#11007 Update ListCollectionPhysicalChannels and ListCollectionVirtualChannels
  internal/rootcoord/meta_table.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed

#11072 Improve error message in rootcoord
  internal/rootcoord/task.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#11070 Improve error message in rootcoord
  internal/rootcoord/proxy_client_manager.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#11071 Improve error message in rootcoord
  internal/rootcoord/task.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#11082 [skip ci]Add timeout for pytest command
  .github/workflows/pod-kill-chaos-test.yaml
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#10625 Windows dummy metrics for container.
  internal/util/metricsinfo/container_linux.go
  internal/util/metricsinfo/container_windows.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed

#11081 Fix rocksdb retention ts not set
  internal/util/rocksmq/server/rocksmq/rocksmq_impl.go
  internal/util/rocksmq/server/rocksmq/rocksmq_retention.go
  internal/util/rocksmq/server/rocksmq/rocksmq_retention_test.go
Labels: size/XL, approved, lgtm, ci-passed

#11083 Add topic lock for rocksmq Seek
  internal/util/rocksmq/server/rocksmq/rocksmq_impl.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed

#11076 Move topic lock to the front of final delete in retention
  internal/util/rocksmq/server/rocksmq/rocksmq_retention.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed

#11088 Fix MB const size
  internal/util/rocksmq/server/rocksmq/rocksmq_retention.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed

#11092 Add common endian for global use
  internal/common/common.go
  internal/datanode/data_sync_service_test.go
  internal/datanode/flow_graph_delete_node.go
  internal/datanode/flow_graph_delete_node_test.go
  internal/datanode/flow_graph_insert_buffer_node.go
  internal/datanode/mock_test.go
  internal/datanode/segment_replica.go
  internal/datanode/segment_replica_test.go
  internal/proxy/proxy_test.go
  internal/proxy/task.go
  internal/proxy/task_test.go
  internal/querynode/data_sync_service_test.go
  internal/querynode/flow_graph_insert_node.go
  internal/querynode/flow_graph_insert_node_test.go
  internal/querynode/load_service_test.go
  internal/querynode/mock_test.go
  internal/querynode/plan_test.go
  internal/querynode/query_collection.go
  internal/querynode/query_collection_test.go
  internal/querynode/query_service_test.go
  internal/querynode/reduce_test.go
  internal/querynode/segment.go
  internal/querynode/segment_test.go
  internal/storage/binlog_test.go
  internal/storage/binlog_writer.go
  internal/storage/event_data.go
  internal/storage/event_header.go
  internal/storage/event_test.go
  internal/storage/event_writer.go
  internal/storage/event_writer_test.go
  internal/storage/stats.go
  internal/storage/stats_test.go
  internal/storage/utils_test.go
  internal/storage/vector_chunk_manager.go
  internal/util/mqclient/pulsar_client_test.go
  internal/util/mqclient/rmq_id.go
  internal/util/typeutil/convension.go
  internal/util/typeutil/hash.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed

#11105 Remove useless log
  internal/querynode/segment.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#11108 [skip ci]Update grafana panel description
  deployments/monitor/grafana/milvus-dashboard.json
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#11103 [skip ci] Refine comments in metrics
  internal/metrics/metrics.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed

#11095 [skip ci] Update comments of benchmark
  tests/benchmark/milvus_benchmark/runners/utils.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed

#11096 [skip ci] Add comments of benchmark
  tests/benchmark/milvus_benchmark/runners/utils.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed

#11104 [skip ci] Refine milvus index design doc
  docs/design_docs/index_design.md
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#11106 [skip ci] Refine section number in create collection design doc
  docs/design_docs/milvus_create_collection_en.md
Labels: kind/improvement, size/S, approved, lgtm, ci-passed

#11109 [skip ci]Update grafana description
  deployments/monitor/grafana/milvus-dashboard.json
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#11110 [skip ci]Fix grafana panel description
  deployments/monitor/grafana/milvus-dashboard.json
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#11094 [skip ci] Add new func of benchmark
  tests/benchmark/milvus_benchmark/update.py
Labels: kind/improvement, sig/testing, size/S, approved, lgtm, area/test, ci-passed

#11075 [skip ci]Fix helm reinstall in github action
  .github/workflows/pod-kill-chaos-test.yaml
  tests/python_client/chaos/chaos_test.sh
  tests/python_client/chaos/scripts/install_milvus.sh
  tests/python_client/chaos/scripts/uninstall_milvus.sh
Labels: kind/improvement, sig/testing, size/S, approved, lgtm, area/test, ci-passed

#11084 [skip ci] Rename delete test file
  tests/python_client/testcases/test_delete.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed

#11061 [skip ci]Fix golint error for CreateQueryChannel in QueryCoord
  internal/distributed/querycoord/service.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#11062 [skip ci]Fix golint error for GetSegmentInfo in QueryCoord
  internal/distributed/querycoord/service.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#11025 [skip ci] Fix golint warning of time.go
  internal/util/typeutil/time.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#10976 [skip ci]Improve flush collections doc
  docs/design_docs/milvus_flush_collections_en.md
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#11046 [skip ci]Fix golint error in indexparamcheck
  internal/util/indexparamcheck/index_type.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#11054 [skip ci]Add comments in chap07_query_coordinator.md
  docs/developer_guides/chap07_query_coordinator.md
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#11055 [skip ci]Add comments in chap09_data_coord.md
  docs/developer_guides/chap09_data_coord.md
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#11056 [skip ci]Add comments in chap03_index_service.md
  docs/developer_guides/chap03_index_service.md
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#11068 [skip ci]Fix meta snapshot doc typo
  docs/design_docs/milvus_meta_snapshot_en.md
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#11085 [skip ci] Reformat utility test file
  tests/python_client/testcases/test_utility.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed

#11087 [skip ci] Fix golint warning of kv
  internal/kv/kv.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#11089 [skip ci] Fix golint warning of validate_util.go
  internal/proxy/validate_util.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#11126 Enhance log of proxy and trigger build image
  internal/proxy/task.go
Labels: size/XS, approved

#11091 [skip ci] Fix golint warning of binlog_iterator.go
  internal/storage/binlog_iterator.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#11093 [skip ci] Check grammar of MEP docs
  docs/design_docs/MEP-Template.md
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#11099 [skip ci] Add comment for getPartitionNum
  internal/querynode/collection_replica.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#11100 [skip ci] Add comment for getSegmentIDs
  internal/querynode/collection_replica.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#11101 [skip ci] Add comment for getSegmentIDsByVChannel
  internal/querynode/collection_replica.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#11117 [skip ci] Add comments for GetSegmentInfo
  internal/querynode/impl.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#11118 [skip ci] Add comments for LoadSegments
  internal/querynode/impl.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#11119 [skip ci] Add comments for WatchDmChannels
  internal/querynode/impl.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#11120 [skip ci] Add skipped compact case
  tests/python_client/testcases/test_compaction.py
Labels: kind/improvement, sig/testing, size/S, approved, lgtm, area/test, ci-passed

#11122 [skip ci] Remove unused parameters
  tests/python_client/testcases/test_search_20.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed

#11123 [skip ci] Improve design description
  docs/design_docs/datanode_flowgraph_recovery_design_0604_2021.md
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#11125 [skip ci] Shorten long sentence
  tests/python_client/testcases/test_partition_20.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed

#11131 [skip ci]Add comments in chap07_query_coordinator.md
  docs/developer_guides/chap07_query_coordinator.md
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#11114 [skip ci]Add comments in milvus operator class
  tests/python_client/customize/milvus_operator.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed

#11060 [skip ci]Fix golint error for ReleasePartitions in QueryCoord
  internal/distributed/querycoord/service.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#11115 [skip ci]Update create index md
  docs/design_docs/milvus_create_index_en.md
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, kind/developer-doc

#11121 [skip ci]Fix typo issue
  docs/design_docs/milvus_flush_collections_en.md
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#11132 [skip ci]Add comments in chap09_data_coord.md
  docs/developer_guides/chap09_data_coord.md
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#11133 [skip ci] Check grammar of root-coord docs
  docs/design_docs/root_coordinator_recovery_on_power_failure.md
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#11134 [skip ci] Use volume for dev docker compose
  deployments/docker/dev/docker-compose.yml
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#11138 Remove redundant empty lines
  internal/core/src/segcore/InsertRecord.cpp
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#11139 Reorder header files for segcore/InsertRecord.h
  internal/core/src/segcore/InsertRecord.h
Labels: kind/improvement, size/S, approved, lgtm, ci-passed

#11140 Reorder header files for segcore/load_index_c.cpp
  internal/core/src/segcore/load_index_c.cpp
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#11143 Reorder header files for segcore/load_index_c.h
  internal/core/src/segcore/load_index_c.h
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#11152 Fix timetravel bug on sealed segment
  internal/core/src/query/visitors/ExecPlanNodeVisitor.cpp
  internal/core/unittest/test_c_api.cpp
Labels: size/L, approved, lgtm, ci-passed

#11130 Remove secretkey and accesskey log print for MinIO
  internal/kv/minio/minio_kv.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed

#11158 [skip ci]Fix doc error in design doc
  docs/design_docs/milvus_create_index_en.md
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#11141 [skip ci] Add comments of update file on benchmark
  tests/benchmark/milvus_benchmark/update.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed

#11144 [skip ci]Make sleep time greater than the pod kill time interval
  tests/python_client/chaos/test_chaos_data_consist.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed

#11145 [skip ci] Update code of client file on benchmark
  tests/benchmark/milvus_benchmark/client.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed

#11153 [skip ci] Add skipped compact case
  tests/python_client/testcases/test_compaction.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed

#11154 Update pymilvus version
  tests/python_client/requirements.txt
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed

#11159 [skip ci]Fix doc error
  docs/design_docs/datanode_flowgraph_recovery_design_0604_2021.md
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#11160 [skip ci]Fix doc error in MEP-Templates
  docs/design_docs/MEP-Template.md
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#11166 [skip ci] Fix nightly ci test timeout
  build/ci/jenkins/NightlyCI.groovy
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#11169 [skip ci] Ignore docker compose volumes
  .gitignore
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#7853 Improvements: Some adaptation for gcc-10.
  internal/core/CMakeLists.txt
  internal/core/src/index/knowhere/knowhere/index/vector_index/ConfAdapter.cpp
  internal/core/src/index/thirdparty/faiss/Clustering.cpp
  internal/core/src/index/thirdparty/faiss/utils/distances_simd.cpp
  internal/core/src/index/thirdparty/faiss/utils/hamming-inl.h
  internal/core/src/index/thirdparty/faiss/utils/utils.cpp
Labels: area/dependency, kind/improvement, size/S, approved, lgtm, ci-passed

#11107 Add unit test for pulsarClient Seek
  internal/util/mqclient/pulsar_client_test.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed
