Repository milvus-io/milvus, pull requests merged in 2021-04, with the labels that each got.

#4974 Add kv etcd unittest and remove useless code
  go.mod
  go.sum
  internal/kv/etcd/etcd_kv.go
  internal/kv/etcd/etcd_kv_test.go
  internal/kv/etcd/etcd_stats_watcher.go
  internal/kv/etcd/etcd_stats_watcher_test.go
Labels: PR | automerge

#4986 Delete load request's contex timeout in queryService
  internal/queryservice/impl.go
Labels: Bug

#4990 Remove unused configs
  configs/advanced/channel.yaml
  internal/dataservice/cluster_test.go
  internal/dataservice/server_test.go
  internal/proxynode/paramtable.go
  internal/proxynode/proxy_node.go
  internal/querynode/data_sync_service_test.go
  internal/querynode/load_service_test.go
  internal/querynode/param_table.go
  internal/querynode/param_table_test.go
  internal/querynode/query_node_test.go
  internal/querynode/search_service_test.go
  internal/util/paramtable/paramtable_test.go
Labels: PR | automerge

#4992 edit datanode config files
  configs/advanced/data_node.yaml
Labels: PR | automerge

#4972 update sdk-python source
  ci/jenkins/step/singleDevNightlyTest.groovy
  ci/jenkins/step/singleDevTest.groovy
  tests/milvus_python_test/requirements.txt
  tests/milvus_python_test/test_ping.py
Labels: PR | automerge

#4987 Remove unused params in query node
  configs/advanced/channel.yaml
  configs/advanced/query_node.yaml
  internal/proxynode/paramtable.go
  internal/querynode/param_table.go
  internal/querynode/param_table_test.go
  internal/querynode/query_node.go
  internal/querynode/query_node_test.go
  internal/querynode/search_service.go
  internal/querynode/search_service_test.go
  internal/queryservice/impl.go
  internal/queryservice/param_table.go
Labels: PR | automerge

#4997 Remove useless config
  docs/developer_guides/chap05_proxy.md
  internal/proxynode/paramtable.go
  internal/proxynode/proxy_node.go
Labels: PR | automerge

#4998 improve code coverage for data service
  internal/dataservice/allocator.go
  internal/dataservice/allocator_test.go
  internal/dataservice/meta_test.go
  internal/dataservice/mock_test.go
  internal/dataservice/segment_allocator.go
  internal/dataservice/watcher.go
  internal/dataservice/watcher_test.go
Labels: PR | automerge

#5002 Fix broken links in README.md and README_CN.md
  README.md
  README_CN.md
Labels: PR | automerge

#5012 Add search channels to query node
  internal/querynode/param_table.go
  internal/querynode/query_node.go
  internal/querynode/search_service.go
  internal/queryservice/impl.go
Labels: PR | automerge

#5015 [skip ci]Remove unused content in pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: PR | automerge

#5018 Support query node watch multiple search channels
  internal/querynode/param_table.go
  internal/querynode/query_node.go
  internal/querynode/search_service.go
  internal/queryservice/impl.go
  internal/queryservice/param_table.go
Labels: PR | automerge

#5020 improve data service code coverage
  internal/dataservice/mock_test.go
  internal/dataservice/server.go
  internal/dataservice/server_test.go
Labels: PR | automerge

#5025 Remove meaningless log test
  internal/log/log_test.go
Labels: PR | automerge

#5024 Add go code coverage script
  .gitignore
  Makefile
  scripts/run_go_codecov.sh
Labels: PR | automerge

#5014 Set search graceful time from config
  configs/advanced/data_node.yaml
  configs/advanced/data_service.yaml
  configs/milvus.yaml
  internal/querynode/search_collection.go
Labels: PR | automerge

#5026 [skip ci]Update codeowners
  .github/CODEOWNERS
Labels: PR | automerge

#5019 add unit test for master's grpc server
  internal/dataservice/mock_test.go
  internal/distributed/masterservice/masterservice_test.go
  internal/distributed/masterservice/server.go
  internal/types/types.go
Labels: PR | automerge

#4994 Remove `SetSegmentState` and seal segment in segment allocator
  internal/dataservice/meta.go
  internal/dataservice/meta_test.go
  internal/dataservice/segment_allocator.go
  internal/dataservice/watcher.go
Labels: PR | automerge, PR | message from pull request

#5029 update docker-compose configuration
  deployments/docker/.env
  deployments/docker/docker-compose.distributed.yml
  deployments/docker/docker-compose.standalone.yml
Labels: PR | automerge

#5033 Parse dsl and placeholder from search request in internal.proto
  internal/querynode/search_collection.go
Labels: PR | automerge

#5036 Updaing APIs in mishards
  shards/mishards/connections.py
  shards/mishards/grpc_utils/grpc_args_parser.py
  shards/mishards/service_handler.py
  shards/mishards/settings.py
  shards/mishards/test_connections.py
  shards/requirements.txt
Labels: mishards

#5037 fix flock, lock the pid file during the processing is running
  cmd/distributed/main.go
Labels: Bug, PR | automerge

#5041 add more testcase to improve code coverage for data service
  internal/dataservice/server.go
  internal/dataservice/server_test.go
Labels: PR | automerge

#5048 remove .env and update docker-compose yml
  deployments/docker/.env
  deployments/docker/distributed/docker-compose.yml
  deployments/docker/docker-compose.yml
  deployments/docker/singlenode/docker-compose.yml
Labels: PR | automerge

#5032 Update milvus project name
  .env
  .github/workflows/main.yaml
  .github/workflows/publish-builder.yaml
  .github/workflows/publish-test-images.yaml
  .jenkins/modules/Build/Build.groovy
  .jenkins/modules/Publish/Publish.groovy
  .jenkins/modules/Regression/PythonRegression.groovy
  build/ci/jenkins/Jenkinsfile
  build/ci/jenkins/pod/build-env.yaml
  build/ci/jenkins/pod/docker-pod.yaml
  build/docker/deploy/.env
  build/docker/deploy/docker-compose.yml
  build/docker/milvus/Dockerfile
  cmd/singlenode/main.go
  deployments/docker/distributed/docker-compose.yml
  deployments/docker/singlenode/docker-compose.yml
  docs/developer_guides/entrypoint.md
  docs/jaeger_guides/Opentracing User Guide.md
  scripts/run_docker.sh
  tests/python_test/docker-compose.yml
Labels: PR | automerge, type/enhancement

#5046 index name is unique in collection scope
  internal/distributed/masterservice/masterservice_test.go
  internal/masterservice/master_service_test.go
  internal/masterservice/meta_table.go
  internal/masterservice/meta_table_test.go
  internal/masterservice/task.go
Labels: PR | automerge

#5051 rename all singlenode to standalone
  Makefile
  build/ci/jenkins/Jenkinsfile
  cmd/distributed/roles/roles.go
  cmd/standalone/main.go
  deployments/docker/distributed/docker-compose.yml
  deployments/docker/standalone/docker-compose.yml
Labels: PR | automerge

#5054 Fix panic bug when server stop with alias
  cmd/distributed/main.go
Labels: Bug, PR | automerge, PR | message from pull request

#5057 remove tests/python
  tests/python/__init__.py
  tests/python/conftest.py
  tests/python/constants.py
  tests/python/factorys.py
  tests/python/pytest.ini
  tests/python/requirements.txt
  tests/python/test_create_collection.py
  tests/python/test_describe_collection.py
  tests/python/test_drop_collection.py
  tests/python/test_get_collection_info.py
  tests/python/test_has_collection.py
  tests/python/test_index.py
  tests/python/test_insert.py
  tests/python/test_list_collections.py
  tests/python/test_load_collection.py
  tests/python/test_load_partitions.py
  tests/python/test_partition.py
  tests/python/test_search.py
  tests/python/utils.py
Labels: PR | automerge

#5058 Update milvus builder image version
  .env
  build/ci/jenkins/pod/build-env.yaml
Labels: PR | automerge

#5055 the return struct of "DescribeIndex" should contain "field_name"
  internal/core/src/pb/milvus.pb.cc
  internal/core/src/pb/milvus.pb.h
  internal/distributed/masterservice/masterservice_test.go
  internal/masterservice/master_service_test.go
  internal/masterservice/meta_table.go
  internal/masterservice/meta_table_test.go
  internal/masterservice/task.go
  internal/masterservice/util.go
  internal/masterservice/util_test.go
  internal/proto/milvus.proto
  internal/proto/milvuspb/milvus.pb.go
Labels: PR | automerge

#5062 Update CODEOWNERS
  .github/CODEOWNERS
Labels: PR | automerge, PR | improvement

#5059 improve rhnsw
  internal/core/src/index/thirdparty/faiss/IndexRHNSW.cpp
  internal/core/src/index/thirdparty/faiss/impl/RHNSW.cpp
  internal/core/src/index/thirdparty/faiss/impl/RHNSW.h
  internal/core/src/index/thirdparty/faiss/impl/index_read.cpp
  internal/core/src/index/thirdparty/faiss/impl/index_write.cpp
Labels: PR | automerge

#5049 Add get index build progress proto
  internal/core/src/pb/common.pb.cc
  internal/core/src/pb/common.pb.h
  internal/core/src/pb/milvus.pb.cc
  internal/core/src/pb/milvus.pb.h
  internal/distributed/proxynode/service.go
  internal/proto/common.proto
  internal/proto/commonpb/common.pb.go
  internal/proto/milvus.proto
  internal/proto/milvuspb/milvus.pb.go
  internal/proxynode/impl.go
Labels: PR | automerge, PR | message from pull request

#5047 Fix the version of protobuf in go.mod not consistence with MakeFile
  go.mod
Labels: PR | automerge, PR | message from pull request

#5061 Used for local development or CI in Kubernetes in Docker
  .github/workflows/code-checker.yaml
  .github/workflows/publish-builder.yaml
  .github/workflows/publish-test-images.yaml
  build/builder.sh
  build/config/logging/cron-logging.yaml
  build/config/metallb.yaml
  build/config/metrics/aggregated-metrics-reader.yaml
  build/config/metrics/auth-delegator.yaml
  build/config/metrics/auth-reader.yaml
  build/config/metrics/metrics-apiservice.yaml
  build/config/metrics/metrics-server-deployment.yaml
  build/config/metrics/metrics-server-service.yaml
  build/config/metrics/resource-reader.yaml
  build/config/topology/multicluster.json
  build/config/topology/trustworthy-jwt.yaml
  build/docker/builder/cpu/ubuntu18.04/Dockerfile
  build/docker/builder/entrypoint.sh
  build/docker/krte/Dockerfile
  build/docker/krte/wrapper.sh
  build/docker/openblas/Dockerfile
  build/kind_provisioner.sh
  build/lib.sh
  docker-compose.yml
  tests/README.md
  tests/docker/.env
  tests/docker/Dockerfile
  tests/docker/docker-compose.yml
  tests/python_test/docker-compose.yml
  tests/scripts/e2e-k8s.sh
  tests/scripts/e2e.sh
  tests/scripts/install_milvus.sh
  tests/scripts/uninstall_milvus.sh
Labels: PR | automerge, type/new-feature

#5067 Add get index build progress interface implementation
  internal/proxynode/impl.go
  internal/proxynode/task.go
Labels: PR | automerge, PR | message from pull request

#5072 Fix trace unavailable on distributed version
  cmd/distributed/roles/roles.go
Labels: PR | automerge, PR | message from pull request

#5076 Provide install dependencies for Ubuntu and CentOS
  scripts/install_deps.sh
Labels: kind/enhancement

#5080 Remove field in desc index interface.
  internal/proxynode/task.go
Labels: PR | automerge

#5074 Update mergify
  .github/mergify.yml
  .github/workflows/code-checker.yaml
  .github/workflows/main.yaml
Labels: kind/improvement

#5084 Fix publish pytest image bug
  .github/workflows/publish-test-images.yaml
Labels: kind/bug

#5082 Update openblas images
  .env
  build/builder.sh
  build/docker/builder/cpu/ubuntu18.04/Dockerfile
  build/docker/milvus/Dockerfile
  build/docker/openblas/Dockerfile
  docker-compose.yml
  tests/docker/.env
  tests/docker/docker-compose.yml
Labels: kind/enhancement, manual-merge

#5090 Remove partition and segment ids properly in query node
  internal/querynode/collection.go
  internal/querynode/partition.go
Labels: kind/bug

#5085 Run KinD Inside A Kubernetes Cluster For Continuous Integration
  .jenkins/modules/Build/Build.groovy
  .jenkins/modules/Package/Package.groovy
  .jenkins/modules/Publish/Publish.groovy
  .jenkins/modules/Regression/CleanupPythonRegression.groovy
  .jenkins/modules/Regression/PythonRegression.groovy
  .jenkins/modules/UnitTest/UnitTest.groovy
  build/ci/jenkins/Jenkinsfile
  build/ci/jenkins/pod/build-env.yaml
  build/ci/jenkins/pod/docker-pod.yaml
  build/ci/jenkins/pod/krte.yaml
  build/ci/jenkins/pod/test-env.yaml
  build/config/topology/trustworthy-jwt.yaml
  cmd/standalone/main.go
  scripts/before-install.sh
  scripts/check_cache.sh
  scripts/update_cache.sh
  tests/scripts/e2e-k8s.sh
Labels: kind/enhancement

#5088 Add plan proto and support basic boolean expr parser
  go.mod
  go.sum
  internal/core/src/pb/CMakeLists.txt
  internal/core/src/pb/common.pb.cc
  internal/core/src/pb/common.pb.h
  internal/core/src/pb/index_builder.pb.cc
  internal/core/src/pb/index_builder.pb.h
  internal/core/src/pb/message.pb.cc
  internal/core/src/pb/message.pb.h
  internal/core/src/pb/milvus.pb.cc
  internal/core/src/pb/milvus.pb.h
  internal/core/src/pb/plan.pb.cc
  internal/core/src/pb/plan.pb.h
  internal/core/src/query/CMakeLists.txt
  internal/core/src/query/Expr.h
  internal/core/src/query/Plan.cpp
  internal/core/src/query/PlanImpl.h
  internal/core/src/query/PlanNode.h
  internal/core/src/query/PlanProto.cpp
  internal/core/src/query/PlanProto.h
  internal/core/src/query/visitors/ShowExprVisitor.cpp
  internal/core/unittest/CMakeLists.txt
  internal/core/unittest/test_plan_proto.cpp
  internal/proto/common.proto
  internal/proto/commonpb/common.pb.go
  internal/proto/milvus.proto
  internal/proto/milvuspb/milvus.pb.go
  internal/proto/plan.proto
  internal/proto/planpb/plan.pb.go
  internal/proxynode/plan_parser.go
  internal/proxynode/plan_parser_test.go
  internal/proxynode/task.go
  internal/proxynode/util.go
  internal/proxynode/util_test.go
  internal/querynode/plan.go
  internal/util/typeutil/schema.go
  scripts/proto_gen_go.sh
Labels: kind/feature

#5092 Upload Milvus images to internal mirror repository when Push triggered
  build/ci/jenkins/Jenkinsfile
Labels: kind/enhancement

#5097 fix crash when creating GPU index
  CHANGELOG.md
  core/src/index/thirdparty/faiss/gpu/utils/StackDeviceMemory.cpp
Labels: kind/bug

#5099 [skip ci]Fix webserver readme
  core/src/server/web_impl/README.md
Labels: kind/documentation

#5100 Zero size allocation in StackDeviceMemory
  internal/core/src/index/thirdparty/faiss/gpu/utils/StackDeviceMemory.cpp
Labels: kind/bug

#5094 Add simple test case to search_with_expression
  tests/python_test/entity/test_search.py
  tests/python_test/requirements.txt
  tests/python_test/utils.py
Labels: kind/improvement, manual-merge, test/ut
