Repository milvus-io/milvus, pull requests merged in 2021-05, with the labels that each got.

#5103 Update pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: kind/improvement, manual-merge

#5104 Update README.md
  README.md
Labels: kind/documentation

#5114 Update README.md
  README.md
Labels: kind/documentation

#5066 Fix querynode's port not set correctly when conflict with other node
  internal/distributed/querynode/service.go
Labels: kind/bug

#5098 upgrading shards
  shards/README.md
  shards/README_CN.md
  shards/all_in_one/all_in_one.yml
  shards/all_in_one_with_mysql/all_in_one.yml
  shards/kubernetes_demo/mishards_stateful_servers.yaml
  shards/kubernetes_demo/mishards_write_servers.yaml
Labels: kind/enhancement

#5125 Update hadolint to v1
  .github/workflows/code-checker.yaml
  .github/workflows/publish-builder.yaml
  .github/workflows/publish-test-images.yaml
Labels: kind/improvement

#5118 Distinguish the dsl and expr in proxy and query node
  internal/core/src/query/Plan.cpp
  internal/core/src/query/Plan.h
  internal/core/src/query/PlanProto.cpp
  internal/core/src/segcore/plan_c.cpp
  internal/core/src/segcore/plan_c.h
  internal/core/unittest/test_c_api.cpp
  internal/msgstream/mem_msgstream_test.go
  internal/msgstream/mq_msgstream_test.go
  internal/proto/internal.proto
  internal/proto/internalpb/internal.pb.go
  internal/proxynode/plan_parser_test.go
  internal/proxynode/task.go
  internal/querynode/plan.go
  internal/querynode/search_collection.go
  internal/querynode/search_service_test.go
  tests/python_test/utils.py
Labels: kind/enhancement, kind/improvement

#5128 Upgrade grpc version from 1.26 to 1.27
  go.mod
  go.sum
Labels: kind/improvement

#5129 Change the codec style of expr plan from text to binary
  internal/core/src/query/Plan.cpp
  internal/core/src/query/Plan.h
  internal/core/src/segcore/plan_c.cpp
  internal/core/src/segcore/plan_c.h
  internal/core/unittest/test_c_api.cpp
  internal/proto/internal.proto
  internal/proto/internalpb/internal.pb.go
  internal/proxynode/task.go
  internal/querynode/plan.go
Labels: kind/enhancement, kind/improvement

#5139 Merge knowhere unittests
  internal/core/src/index/CMakeLists.txt
  internal/core/src/index/unittest/CMakeLists.txt
  internal/core/src/index/unittest/Helper.h
  internal/core/src/index/unittest/test_structured_index_flat.cpp
Labels: kind/improvement

#5131 Change should_not to must_not in dsl
  internal/core/src/query/Plan.cpp
  internal/core/unittest/test_expr.cpp
  internal/core/unittest/test_plan_proto.cpp
Labels: kind/improvement

#5133 Improve code coverage for distributed/datanode
  cmd/distributed/components/data_node.go
  internal/datanode/data_sync_service.go
  internal/distributed/datanode/datanode_test.go
  internal/distributed/datanode/service.go
  internal/distributed/dataservice/dataservice_test.go
  internal/distributed/dataservice/service.go
Labels: kind/improvement

#5140 Add partition tag in new cases
  ci/jenkins/Jenkinsfile
  tests/milvus_python_test/collection/test_collection.py
  tests/milvus_python_test/entity/test_delete.py
  tests/milvus_python_test/entity/test_get_entity_by_id.py
Labels: kind/improvement

#5162 Add row_count to partition statistics
  internal/dataservice/server.go
  internal/proxynode/impl.go
  internal/proxynode/task.go
Labels: kind/enhancement, kind/feature, size/L

#5165 [skip ci] Add new tests directories
  tests20/README.md
  tests20/benchmark/README.md
  tests20/go_client/README.md
  tests20/java_client/README.md
  tests20/python_client/README.md
  tests20/python_client/collection/test_collection.py
  tests20/python_client/connection/test_connection.py
  tests20/python_client/index/test_index.py
  tests20/python_client/partition/test_partition.py
  tests20/python_client/utility/test_utility.py
Labels: sdk/python

#5170 [skip ci]Update mergify rules
  .github/mergify.yml
Labels: kind/improvement, manual-merge, size/XS

#5179 Add publish-krte-images.yaml
  .github/workflows/publish-krte-images.yaml
Labels: kind/feature, size/M

#5178 [skip ci] Change code owner for test folders
  .github/CODEOWNERS
Labels: manual-merge, sig/testing, size/XS

#5161 Enable gpu cache
  CHANGELOG.md
  core/conf/server_config.template
  core/src/db/engine/ExecutionEngineImpl.cpp
  core/src/scheduler/selector/FaissFlatPass.cpp
  core/src/scheduler/selector/FaissIVFPass.cpp
  core/src/scheduler/selector/FaissIVFSQ8HPass.cpp
  core/src/scheduler/selector/Pass.cpp
  core/src/scheduler/selector/Pass.h
  core/src/utils/CommonUtil.cpp
Labels: kind/feature, size/L

#5180 [skip ci]Update mergify
  .github/mergify.yml
Labels: kind/improvement, manual-merge, size/S

#5173 Save ddmsg info and type into ETCD
  internal/masterservice/master_service_test.go
  internal/masterservice/meta_table.go
  internal/masterservice/meta_table_test.go
  internal/masterservice/task.go
Labels: component/master, kind/feature, size/L

#5181 Remove daemonize code
  core/src/main.cpp
  core/src/server/Server.cpp
  core/src/server/Server.h
Labels: kind/improvement, size/L

#5188 Update install_milvus.sh
  tests/scripts/install_milvus.sh
Labels: size/XS

#5197 update test code
  tests20/python_client/base/client_request.py
  tests20/python_client/base/collection.py
  tests20/python_client/base/connections.py
  tests20/python_client/base/index.py
  tests20/python_client/base/partition.py
  tests20/python_client/base/utility.py
  tests20/python_client/check/func_check.py
  tests20/python_client/check/param_check.py
  tests20/python_client/common/common_func.py
  tests20/python_client/config/test_info.py
  tests20/python_client/conftest.py
  tests20/python_client/pytest.ini
  tests20/python_client/requirements.txt
  tests20/python_client/testcases/test_collection.py
  tests20/python_client/testcases/test_connection.py
  tests20/python_client/testcases/test_index.py
  tests20/python_client/testcases/test_params.py
  tests20/python_client/testcases/test_partition.py
  tests20/python_client/testcases/test_schema.py
  tests20/python_client/testcases/test_search.py
  tests20/python_client/testcases/test_utility.py
  tests20/python_client/utils/util_log.py
Labels: size/L

#5205 Update check function
  tests20/python_client/base/collection.py
  tests20/python_client/base/connections.py
  tests20/python_client/base/index.py
  tests20/python_client/base/partition.py
  tests20/python_client/base/utility.py
  tests20/python_client/check/func_check.py
  tests20/python_client/common/common_type.py
  tests20/python_client/testcases/test_connection.py
Labels: size/L

#5189 Add service registration
  internal/datanode/data_node.go
  internal/dataservice/server.go
  internal/indexnode/indexnode.go
  internal/indexnode/paramtable.go
  internal/indexservice/indexservice.go
  internal/kv/etcd/etcd_kv.go
  internal/masterservice/master_service.go
  internal/proxynode/paramtable.go
  internal/proxynode/proxy_node.go
  internal/querynode/meta_service.go
  internal/querynode/param_table.go
  internal/querynode/query_node.go
  internal/queryservice/param_table.go
  internal/queryservice/queryservice.go
Labels: kind/feature, size/XL

#5200 Add data sorter in storage
  internal/storage/data_codec.go
  internal/storage/data_sorter.go
  internal/storage/data_sorter_test.go
Labels: kind/feature, size/L

#5204 Improve IVF query on GPU if no entity deleted
  core/src/index/thirdparty/faiss/gpu/impl/IVFUtilsSelect1.cu
Labels: size/M

#5216 [skip-ci] master service recovery on power failure
  docs/design_docs/master_service_recovery_on_power_failure.md
Labels: component/master, kind/documentation, size/M

#5206 add datanode design doc
  docs/design_docs/datanode_recovery_design_0513_2021.md
  docs/design_docs/graphs/collection_flowgraph_1_1.jpg
  docs/design_docs/graphs/collection_flowgraph_1_n.png
  docs/design_docs/graphs/collection_flowgraph_n_1.jpg
  docs/design_docs/graphs/collection_flowgraph_n_n.jpg
  docs/design_docs/graphs/collection_flowgraph_relation.png
  docs/design_docs/graphs/datanode_design_01.jpg
Labels: component/datanode, kind/design, manual-merge

#5226 Remove not using dependence and proto
  internal/msgstream/msg.go
  internal/msgstream/unmarshal.go
  internal/proto/internal.proto
  internal/proto/internalpb/internal.pb.go
  internal/util/mqclient/pulsar_client_test.go
Labels: kind/improvement, size/L

#5229 Add session util doc
  docs/developer_guides/appendix_a_basic_components.md
Labels: kind/design, size/M

#5194 Disable cron testing
  ci/jenkins/Jenkinsfile
  ci/jenkins/step/shardsDevNightlyTest.groovy
Labels: size/XS

#5199 Specified Milvus Helm Chart path in E2E test
  tests/scripts/install_milvus.sh
Labels: kind/improvement, size/S

#5225 Deny jenkins slave pod to remain active for a while
  .github/workflows/code-checker.yaml
  .github/workflows/main.yaml
  build/ci/jenkins/Jenkinsfile
  build/config/topology/trustworthy-jwt.yaml
Labels: kind/improvement, size/S

#5214 Resend unsuccessful ddMsg when master start
  internal/distributed/masterservice/masterservice_test.go
  internal/masterservice/master_service.go
  internal/masterservice/master_service_test.go
  internal/masterservice/meta_table.go
  internal/masterservice/meta_table_test.go
  internal/masterservice/task.go
  internal/masterservice/util.go
Labels: kind/improvement, size/XL

#5232 Allow jenkins slave pod to remain active for a while
  build/ci/jenkins/Jenkinsfile
Labels: kind/improvement, size/XS

#5236 fix makefile
  Makefile
Labels: kind/bug, size/XS

#5235 Increase ephemeral storage size for jenkins slave
  build/ci/jenkins/Jenkinsfile
  build/ci/jenkins/pod/krte.yaml
  build/config/topology/trustworthy-jwt.yaml
  tests/scripts/e2e-k8s.sh
Labels: kind/improvement, size/S

#5237 [skip ci]Update mergify
  .github/mergify.yml
Labels: kind/improvement, manual-merge, size/XS

#5238 Optimize CreateIndex routine in master service
  internal/distributed/masterservice/masterservice_test.go
  internal/masterservice/master_service.go
  internal/masterservice/master_service_test.go
  internal/masterservice/meta_table.go
  internal/masterservice/meta_table_test.go
  internal/masterservice/task.go
  internal/masterservice/util.go
Labels: size/L

#5239 Add collection cases
  tests20/python_client/check/func_check.py
  tests20/python_client/common/common_func.py
  tests20/python_client/common/common_type.py
  tests20/python_client/testcases/test_collection.py
  tests20/python_client/testcases/test_connection.py
  tests20/python_client/utils/util_log.py
Labels: size/L

#5247 Change volumes with pytest docker-compose
  tests/docker/Dockerfile
  tests/docker/docker-compose.yml
Labels: kind/improvement, size/S

#5250 Fix run pytest bug
  tests/scripts/e2e.sh
Labels: kind/bug, size/XS

#5249 add collection cases level and change get_connection to create_collection
  tests20/python_client/base/client_request.py
  tests20/python_client/common/common_func.py
  tests20/python_client/common/common_type.py
  tests20/python_client/pytest.ini
  tests20/python_client/testcases/test_collection.py
Labels: size/M

#5245 Add ShardsNum when create collection
  internal/core/src/pb/etcd_meta.pb.cc
  internal/core/src/pb/etcd_meta.pb.h
  internal/core/src/pb/milvus.pb.cc
  internal/core/src/pb/milvus.pb.h
  internal/masterservice/master_service_test.go
  internal/masterservice/meta_table.go
  internal/masterservice/meta_table_test.go
  internal/masterservice/task.go
  internal/proto/etcd_meta.proto
  internal/proto/etcdpb/etcd_meta.pb.go
  internal/proto/internal.proto
  internal/proto/internalpb/internal.pb.go
  internal/proto/milvus.proto
  internal/proto/milvuspb/milvus.pb.go
Labels: size/XXL

#5252 Dirty BloomFilter is left in the cache
  core/src/cache/Cache.h
  core/src/cache/Cache.inl
  core/src/cache/CacheMgr.h
  core/src/cache/CacheMgr.inl
  core/src/db/DBImpl.cpp
  core/src/db/insert/MemTable.cpp
  core/src/scheduler/JobMgr.cpp
  core/src/segment/SegmentReader.cpp
  core/src/segment/SegmentReader.h
Labels: needs-cherry-pick-1.0, size/M

#5268 Update design about O1-1
  docs/design_docs/datanode_recovery_design_0513_2021.md
Labels: component/datanode, kind/design, size/M

#5269 Add session util
  docs/developer_guides/appendix_a_basic_components.md
  go.mod
  internal/kv/etcd/etcd_kv.go
  internal/kv/etcd/etcd_kv_test.go
  internal/util/session/session_util.go
  internal/util/session/session_util_test.go
  scripts/run_go_unittest.sh
Labels: kind/documentation, kind/feature, size/L

#5274 Add the design doc of retrieve entity
  docs/design_docs/retrieve_entity.md
Labels: kind/design, kind/documentation, size/L

#5275 query master service's with timestamp
  internal/distributed/masterservice/masterservice_test.go
  internal/kv/kv.go
  internal/masterservice/master_service.go
  internal/masterservice/master_service_test.go
  internal/masterservice/meta_snapshot.go
  internal/masterservice/meta_snapshot_test.go
  internal/masterservice/meta_table.go
  internal/masterservice/meta_table_test.go
  internal/masterservice/task.go
Labels: component/master, kind/feature, size/XXL

#5271 Add buffer function for auto flush
  go.mod
  internal/datanode/binlog_meta.go
  internal/datanode/collection_replica.go
  internal/datanode/collection_replica_test.go
  internal/datanode/param_table.go
Labels: component/datanode, component/dataservice, kind/feature, size/M

#5279 query base on timeline
  internal/core/src/pb/milvus.pb.cc
  internal/core/src/pb/milvus.pb.h
  internal/masterservice/meta_table.go
  internal/masterservice/meta_table_test.go
  internal/masterservice/task.go
  internal/proto/milvus.proto
  internal/proto/milvuspb/milvus.pb.go
Labels: component/master, kind/feature, size/XXL

#5272 Dirty blacklist is left in the cache
  CHANGELOG.md
  core/src/db/DBImpl.cpp
  core/src/db/engine/ExecutionEngineImpl.cpp
  core/src/db/engine/ExecutionEngineImpl.h
  core/src/db/insert/MemTable.cpp
  core/src/index/knowhere/knowhere/index/Index.h
  core/src/index/knowhere/knowhere/index/vector_index/ConfAdapter.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexAnnoy.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexAnnoy.h
  core/src/index/knowhere/knowhere/index/vector_index/IndexBinaryIDMAP.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexBinaryIDMAP.h
  core/src/index/knowhere/knowhere/index/vector_index/IndexBinaryIVF.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexBinaryIVF.h
  core/src/index/knowhere/knowhere/index/vector_index/IndexHNSW.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexHNSW.h
  core/src/index/knowhere/knowhere/index/vector_index/IndexIDMAP.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexIDMAP.h
  core/src/index/knowhere/knowhere/index/vector_index/IndexIVF.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexIVF.h
  core/src/index/knowhere/knowhere/index/vector_index/IndexNSG.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexNSG.h
  core/src/index/knowhere/knowhere/index/vector_index/IndexSPTAG.cpp
  core/src/index/knowhere/knowhere/index/vector_index/IndexSPTAG.h
  core/src/index/knowhere/knowhere/index/vector_index/VecIndex.h
  core/src/index/knowhere/knowhere/index/vector_index/gpu/IndexGPUIDMAP.cpp
  core/src/index/knowhere/knowhere/index/vector_index/gpu/IndexGPUIDMAP.h
  core/src/index/knowhere/knowhere/index/vector_index/gpu/IndexGPUIVF.cpp
  core/src/index/knowhere/knowhere/index/vector_index/gpu/IndexGPUIVF.h
  core/src/index/knowhere/knowhere/index/vector_index/gpu/IndexIVFSQHybrid.cpp
  core/src/index/knowhere/knowhere/index/vector_index/gpu/IndexIVFSQHybrid.h
  core/src/index/knowhere/knowhere/index/vector_index/helpers/Cloner.cpp
  core/src/index/unittest/test_annoy.cpp
  core/src/index/unittest/test_binaryidmap.cpp
  core/src/index/unittest/test_binaryivf.cpp
  core/src/index/unittest/test_customized_index.cpp
  core/src/index/unittest/test_gpuresource.cpp
  core/src/index/unittest/test_hnsw.cpp
  core/src/index/unittest/test_idmap.cpp
  core/src/index/unittest/test_ivf.cpp
  core/src/index/unittest/test_nsg.cpp
  core/src/index/unittest/test_sptag.cpp
  core/src/index/unittest/test_vecindex.cpp
  core/src/segment/SegmentReader.cpp
  core/src/segment/SegmentReader.h
  core/unittest/server/test_cache.cpp
Labels: size/L

#5278 Add exclusive parameter
  docs/developer_guides/appendix_a_basic_components.md
  internal/kv/etcd/etcd_kv.go
  internal/util/sessionutil/session_util.go
  internal/util/sessionutil/session_util_test.go
  scripts/run_go_unittest.sh
Labels: size/L

#5212 Add dataservice recover design docs
  docs/design_docs/dataservice_recovery_design.md
Labels: kind/documentation, size/M

#5282 Correct auto-flush behaviour
  internal/datanode/allocator.go
  internal/datanode/binlog_meta.go
  internal/datanode/binlog_meta_test.go
  internal/datanode/data_node_test.go
  internal/datanode/data_sync_service.go
  internal/datanode/flow_graph_insert_buffer_node.go
  internal/datanode/flow_graph_insert_buffer_node_test.go
  internal/datanode/mock_test.go
Labels: component/datanode, kind/improvement, size/L

#5286 Add cases for creating collections
  tests20/python_client/base/client_request.py
  tests20/python_client/common/common_func.py
  tests20/python_client/common/common_type.py
  tests20/python_client/pytest.ini
  tests20/python_client/testcases/test_collection.py
Labels: size/L

#5289 Add ddl flush design
  docs/design_docs/datanode_ddl_flush_design_0519_2021.md
  docs/design_docs/datanode_recovery_design_0513_2021.md
Labels: kind/design, size/M

#5284 Restore flush and stats stream pos
  configs/milvus.yaml
  internal/dataservice/param.go
  internal/dataservice/server.go
  internal/dataservice/server_test.go
  internal/dataservice/stream_pos.go
Labels: component/dataservice, size/L

#5295 Update cpp thirdparty source URL
  internal/core/thirdparty/gtest/CMakeLists.txt
Labels: kind/improvement, size/XS

#5288 Add SessionManager
  internal/datanode/data_node.go
  internal/dataservice/server.go
  internal/distributed/datanode/service.go
  internal/distributed/dataservice/service.go
  internal/distributed/indexnode/service.go
  internal/distributed/indexservice/service.go
  internal/distributed/masterservice/masterservice_test.go
  internal/distributed/masterservice/server.go
  internal/distributed/proxynode/service.go
  internal/distributed/querynode/service.go
  internal/distributed/queryservice/service.go
  internal/indexnode/indexnode.go
  internal/indexservice/indexservice.go
  internal/masterservice/master_service.go
  internal/proxynode/proxy_node.go
  internal/querynode/query_node.go
  internal/queryservice/queryservice.go
  internal/util/sessionutil/session_util.go
  internal/util/sessionutil/session_util_test.go
Labels: kind/feature, kind/improvement, size/XL

#5294 Add Retrieve method grpc definition
  internal/core/src/pb/milvus.pb.cc
  internal/core/src/pb/milvus.pb.h
  internal/core/src/pb/schema.pb.cc
  internal/core/src/pb/schema.pb.h
  internal/distributed/proxynode/service.go
  internal/proto/internal.proto
  internal/proto/internalpb/internal.pb.go
  internal/proto/milvus.proto
  internal/proto/milvuspb/milvus.pb.go
  internal/proto/schema.proto
  internal/proto/schemapb/schema.pb.go
  internal/proxynode/impl.go
  internal/proxynode/task.go
Labels: kind/feature, size/XXL

#5303 Refactor ddl binlog flush
  docs/design_docs/datanode_ddl_flush_design_0519_2021.md
  internal/datanode/binlog_meta.go
  internal/datanode/binlog_meta_test.go
  internal/datanode/data_sync_service.go
  internal/datanode/flow_graph_dd_node.go
  internal/datanode/flow_graph_dd_node_test.go
  internal/datanode/param_table.go
  internal/datanode/param_table_test.go
Labels: component/datanode, kind/enhancement, size/L

#5297 Add a timestamp to the blacklist and cache it
  core/src/cache/CpuCacheMgr.cpp
  core/src/cache/CpuCacheMgr.h
  core/src/db/DBImpl.cpp
  core/src/db/engine/EngineFactory.cpp
  core/src/db/engine/EngineFactory.h
  core/src/db/engine/ExecutionEngine.h
  core/src/db/engine/ExecutionEngineImpl.cpp
  core/src/db/engine/ExecutionEngineImpl.h
  core/src/db/insert/MemTable.cpp
  core/src/index/knowhere/knowhere/index/Index.h
  core/src/scheduler/task/BuildIndexTask.cpp
  core/src/scheduler/task/SearchTask.cpp
  core/src/utils/CommonUtil.cpp
  core/unittest/db/test_engine.cpp
  core/unittest/scheduler/test_task.cpp
Labels: size/L

#5306 Bugfix: fix local directory creating while using s3 storage.
  core/src/codecs/default/DefaultIdBloomFilterFormat.cpp
  core/src/storage/disk/DiskOperation.cpp
  core/unittest/storage/test_disk.cpp
Labels: size/XS

#5305 add cases for collection with data
  tests20/python_client/base/client_request.py
  tests20/python_client/common/common_func.py
  tests20/python_client/common/common_type.py
  tests20/python_client/testcases/test_collection.py
Labels: size/L

#5277 Add SaveBinlogPaths grpc in dataservice
  configs/milvus.yaml
  internal/dataservice/binlog_helper.go
  internal/dataservice/param.go
  internal/dataservice/server.go
  internal/dataservice/server_test.go
  internal/distributed/dataservice/service.go
  internal/proto/data_service.proto
  internal/proto/datapb/data_service.pb.go
Labels: component/dataservice, size/XL

#5298 set timestamp on dd requests
  configs/advanced/master.yaml
  internal/distributed/masterservice/masterservice_test.go
  internal/kv/kv.go
  internal/masterservice/master_service.go
  internal/masterservice/master_service_test.go
  internal/masterservice/meta_snapshot.go
  internal/masterservice/meta_snapshot_test.go
  internal/masterservice/meta_table.go
  internal/masterservice/meta_table_test.go
  internal/masterservice/param_table.go
  internal/masterservice/param_table_test.go
  internal/masterservice/task.go
Labels: component/master, kind/feature, size/XL

#5313 Add RetrieveTask implementation
  internal/core/src/pb/common.pb.cc
  internal/core/src/pb/common.pb.h
  internal/msgstream/msg.go
  internal/proto/common.proto
  internal/proto/commonpb/common.pb.go
  internal/proxynode/paramtable.go
  internal/proxynode/task.go
Labels: kind/feature, size/L

#5310 Improve session manager
  internal/util/sessionutil/session_util.go
  internal/util/sessionutil/session_util_test.go
Labels: kind/improvement, size/M

#5314 Fix issue #5191
  CHANGELOG.md
  shards/all_in_one_with_mysql/all_in_one.yml
  shards/all_in_one_with_mysql/ro_server.yml
  shards/all_in_one_with_mysql/wr_server.yml
  shards/mishards/service_handler.py
Labels: size/S

#5318 Flush statistics for all int64 fields
  internal/datanode/binlog_meta.go
  internal/datanode/flow_graph_insert_buffer_node.go
  internal/datanode/flow_graph_insert_buffer_node_test.go
  internal/datanode/param_table.go
  internal/querynode/load_service_test.go
  internal/storage/data_codec.go
  internal/storage/data_codec_test.go
  internal/storage/print_binglog_test.go
  internal/storage/stats.go
  internal/storage/stats_test.go
Labels: kind/feature, size/L

#5326 Partition existence check
  CHANGELOG.md
  core/src/db/DBImpl.cpp
  core/src/db/wal/WalManager.cpp
  core/src/db/wal/WalManager.h
  core/src/server/delivery/request/BaseRequest.cpp
  core/src/server/delivery/request/BaseRequest.h
  core/src/server/delivery/request/DeleteByIDRequest.cpp
  core/src/server/delivery/request/InsertRequest.cpp
Labels: size/M

#5323 Add channelsMgr to proxy
  internal/proxynode/channels_mgr.go
  internal/proxynode/channels_mgr_test.go
Labels: component/proxy, kind/feature, size/XL

#5328 Update describe_index in python tests
  tests/python_test/collection/test_collection_stats.py
  tests/python_test/collection/test_describe_collection.py
  tests/python_test/collection/test_load_collection.py
  tests/python_test/entity/test_insert.py
  tests/python_test/requirements.txt
  tests/python_test/test_index.py
  tests/python_test/test_mix.py
  tests/python_test/utils.py
Labels: size/L, test/stability

#5327 Cancel local timestamp caching logic
  go.mod
  go.sum
  internal/allocator/allocator.go
  internal/allocator/timestamp.go
  internal/proxynode/proxy_node.go
  internal/proxynode/task_scheduler.go
  internal/proxynode/timestamp.go
  internal/proxynode/timetick.go
Labels: kind/feature, size/L

#5280 Remove redundant fields in SegmentInfo and related structure
  internal/core/src/pb/milvus.pb.cc
  internal/core/src/pb/milvus.pb.h
  internal/dataservice/meta.go
  internal/dataservice/meta_test.go
  internal/dataservice/server.go
  internal/dataservice/server_test.go
  internal/dataservice/stats_handler.go
  internal/masterservice/master_service_test.go
  internal/proto/data_service.proto
  internal/proto/datapb/data_service.pb.go
  internal/proto/milvus.proto
  internal/proto/milvuspb/milvus.pb.go
  internal/proxynode/impl.go
  internal/querynode/meta_service_test.go
  internal/queryservice/mock.go
  tests/python_test/requirements.txt
Labels: component/dataservice, kind/enhancement, size/XXL

#5341 Add todo list to dataservice desgin doc
  docs/design_docs/dataservice_recovery_design.md
Labels: size/S

#5334 test collection with fields
  tests20/python_client/base/client_request.py
  tests20/python_client/common/common_func.py
  tests20/python_client/testcases/test_collection.py
Labels: size/L

#5321 Refactor timetick msg handling between proxy node and master
  internal/dataservice/mock_test.go
  internal/distributed/masterservice/client/client.go
  internal/distributed/masterservice/server.go
  internal/masterservice/master_service.go
  internal/masterservice/master_service_test.go
  internal/masterservice/timeticksync.go
  internal/proto/internal.proto
  internal/proto/internalpb/internal.pb.go
  internal/proto/master.proto
  internal/proto/masterpb/master.pb.go
  internal/types/types.go
Labels: kind/feature, size/XL

#5338 Fix issue 5333 uninitialized return value
  internal/datanode/flow_graph_insert_buffer_node.go
Labels: size/XS

#5336 Add RetrieveTask PostExecute function
  internal/proxynode/task.go
Labels: kind/feature, size/M

#5320 DataService publishes flush-completed message into its channel
  internal/dataservice/server.go
  internal/dataservice/server_test.go
Labels: component/dataservice, size/M

#5184 Save segment allocation status to meta
  internal/dataservice/meta.go
  internal/dataservice/meta_test.go
  internal/dataservice/segment_allocation_policy.go
  internal/dataservice/segment_allocation_stats.go
  internal/dataservice/segment_allocator.go
  internal/dataservice/segment_allocator_test.go
  internal/dataservice/server.go
  internal/dataservice/server_test.go
  internal/dataservice/watcher.go
  internal/dataservice/watcher_test.go
  internal/proto/data_service.proto
  internal/proto/datapb/data_service.pb.go
Labels: component/dataservice, kind/feature, size/XXL

#5346 Add DataNode scales flowgraph design docs
  docs/design_docs/datanode_ddl_flush_design_0519_2021.md
  docs/design_docs/datanode_recovery_design_0513_2021.md
Labels: component/datanode, kind/design, size/M

#5329 Change session
  internal/datanode/data_node.go
  internal/dataservice/param.go
  internal/dataservice/server.go
  internal/dataservice/server_test.go
  internal/distributed/datanode/service.go
  internal/distributed/dataservice/paramtable.go
  internal/distributed/dataservice/service.go
  internal/distributed/indexnode/service.go
  internal/distributed/indexservice/service.go
  internal/distributed/masterservice/masterservice_test.go
  internal/distributed/masterservice/server.go
  internal/distributed/proxynode/service.go
  internal/distributed/querynode/service.go
  internal/distributed/queryservice/service.go
  internal/indexnode/indexnode.go
  internal/indexservice/indexservice.go
  internal/masterservice/master_service.go
  internal/masterservice/master_service_test.go
  internal/masterservice/param_table.go
  internal/proxynode/proxy_node.go
  internal/querynode/query_node.go
  internal/queryservice/param_table.go
  internal/queryservice/queryservice.go
  internal/util/sessionutil/session_util.go
  internal/util/sessionutil/session_util_test.go
Labels: kind/improvement, size/XL

#5348 Dataservice use lastest grpc design and saves ddl/dml pos pair
  configs/milvus.yaml
  internal/dataservice/binlog_helper.go
  internal/dataservice/param.go
  internal/dataservice/server.go
  internal/dataservice/server_test.go
  internal/proto/data_service.proto
  internal/proto/datapb/data_service.pb.go
Labels: component/dataservice, size/L

#5342 Add prometheus metrics
  cmd/distributed/roles/roles.go
  go.mod
  internal/metrics/metrics.go
  internal/metrics/metrics_test.go
Labels: size/L

#5351 Update devcontainer.sh
  scripts/devcontainer.sh
Labels: kind/improvement, size/XS

#5352 Change pulsar version
  go.mod
  go.sum
  internal/util/mqclient/pulsar_client.go
Labels: size/XS

#5360 master client,reconnect if grpc failed
  internal/allocator/id.go
  internal/datanode/data_node.go
  internal/dataservice/server.go
  internal/dataservice/server_test.go
  internal/distributed/datanode/service.go
  internal/distributed/dataservice/service.go
  internal/distributed/masterservice/client/client.go
  internal/distributed/masterservice/masterservice_test.go
  internal/distributed/proxynode/service.go
  internal/distributed/querynode/service.go
  internal/distributed/queryservice/service.go
  internal/indexnode/indexnode.go
  internal/indexservice/indexservice.go
  internal/masterservice/master_service.go
  internal/masterservice/master_service_test.go
  internal/masterservice/timeticksync.go
  internal/proxynode/proxy_node.go
  internal/querynode/query_node.go
  internal/queryservice/queryservice.go
  internal/util/sessionutil/session_util.go
  internal/util/sessionutil/session_util_test.go
Labels: component/master, kind/enhancement, size/L

#5339 Add channelsTimeTicker to proxy
  internal/proxynode/channels_mgr_test.go
  internal/proxynode/channels_time_ticker.go
  internal/proxynode/channels_time_ticker_test.go
Labels: component/proxy, kind/feature, size/L

#5361 Fix bug: rand.Seed reset and generate duplicate number
  internal/util/funcutil/random.go
Labels: kind/bug, size/XS

#5355 Change session doc
  docs/developer_guides/appendix_a_basic_components.md
  internal/util/sessionutil/session_util.go
Labels: kind/documentation, kind/improvement, size/L

#5363 reduce unittest time
  internal/core/unittest/test_index_wrapper.cpp
Labels: kind/enhancement, size/XS

#5358 Save msg start position and end position when AddSegment and AddIndex
  internal/distributed/masterservice/masterservice_test.go
  internal/masterservice/master_service.go
  internal/masterservice/master_service_test.go
  internal/masterservice/meta_table.go
  internal/masterservice/meta_table_test.go
  internal/masterservice/task.go
Labels: kind/feature, size/XL

#5359 Improve IVF query on GPU when no entity deleted
  internal/core/src/index/thirdparty/faiss/gpu/impl/IVFUtilsSelect1.cu
Labels: size/M

#5364 Add ComputeProduceChannelIndexes for msgstream
  go.mod
  go.sum
  internal/msgstream/mem_msgstream.go
  internal/msgstream/mq_msgstream.go
  internal/msgstream/msgstream.go
  internal/msgstream/msgstream_mock.go
  internal/querynode/search_collection.go
Labels: kind/improvement, size/M

#5370 Fix session util error
  internal/util/sessionutil/session_util.go
Labels: size/XS

#5371 Add test cases for collection primary and data
  tests20/python_client/common/common_func.py
  tests20/python_client/common/common_type.py
  tests20/python_client/testcases/test_collection.py
Labels: size/L

#5369 Change pymilvus-distributed to pymilvus
  .gitignore
  tests/python_test/requirements.txt
Labels: kind/improvement, manual-merge, size/XS

#5353 Add retrieve taskscheduler implementation
  internal/proxynode/impl.go
  internal/proxynode/task_scheduler.go
Labels: kind/feature, size/L

#5388 Update the version of pymilvus to 2.0a1.dev2
  tests/python_test/requirements.txt
Labels: size/XS

#5372 update AddIndex not return error when fail
  internal/distributed/masterservice/masterservice_test.go
  internal/masterservice/master_service.go
  internal/masterservice/meta_table.go
  internal/masterservice/util.go
Labels: kind/enhancement, size/M

#5389 Rename some field names in master for better code readability
  internal/distributed/masterservice/masterservice_test.go
  internal/distributed/masterservice/server.go
  internal/masterservice/master_service.go
  internal/masterservice/master_service_test.go
  internal/masterservice/task.go
Labels: size/L

#5397 DataService stores flush msgstream pos at VChannel granularity
  configs/milvus.yaml
  internal/dataservice/binlog_helper.go
  internal/dataservice/param.go
  internal/dataservice/server.go
Labels: component/dataservice, size/M

#5376 Add dummy RPC
  internal/core/src/pb/milvus.pb.cc
  internal/core/src/pb/milvus.pb.h
  internal/distributed/proxynode/service.go
  internal/proto/milvus.proto
  internal/proto/milvuspb/milvus.pb.go
  internal/proxynode/impl.go
Labels: kind/feature, size/XXL

#5385 let master use session.ServerID as nodeID
  internal/datanode/data_node.go
  internal/dataservice/mock_test.go
  internal/dataservice/server.go
  internal/distributed/datanode/client/client.go
  internal/distributed/datanode/service.go
  internal/distributed/dataservice/client/client.go
  internal/distributed/dataservice/service.go
  internal/distributed/indexnode/client/client.go
  internal/distributed/indexnode/service.go
  internal/distributed/indexservice/client/client.go
  internal/distributed/indexservice/service.go
  internal/distributed/masterservice/client/client.go
  internal/distributed/masterservice/masterservice_test.go
  internal/distributed/masterservice/server.go
  internal/distributed/proxynode/client/client.go
  internal/distributed/proxynode/service.go
  internal/distributed/proxyservice/client/client.go
  internal/distributed/querynode/client/client.go
  internal/distributed/querynode/service.go
  internal/distributed/queryservice/client/client.go
  internal/distributed/queryservice/service.go
  internal/indexnode/indexnode.go
  internal/indexservice/indexservice.go
  internal/masterservice/master_service.go
  internal/masterservice/master_service_test.go
  internal/masterservice/param_table.go
  internal/masterservice/param_table_test.go
  internal/masterservice/timeticksync.go
  internal/proxynode/proxy_node.go
  internal/querynode/query_node.go
  internal/queryservice/queryservice.go
  internal/types/types.go
Labels: component/master, size/L

#5393 Bugfix: increase offset after read in s3 IO reader.
  core/src/storage/s3/S3IOReader.cpp
Labels: size/XS

#5400 Refactor dataservice
  internal/core/src/pb/common.pb.cc
  internal/core/src/pb/common.pb.h
  internal/dataservice/grpc_handler.go
  internal/dataservice/meta.go
  internal/dataservice/meta_test.go
  internal/dataservice/mock_test.go
  internal/dataservice/segment_allocation_stats.go
  internal/dataservice/segment_allocator.go
  internal/dataservice/server.go
  internal/dataservice/server_test.go
  internal/dataservice/watcher.go
  internal/dataservice/watcher_test.go
  internal/msgstream/msg.go
  internal/msgstream/unmarshal.go
  internal/proto/common.proto
  internal/proto/commonpb/common.pb.go
  internal/proto/data_service.proto
  internal/proto/datapb/data_service.pb.go
Labels: component/dataservice, kind/improvement, size/XXL

#5394 Add datanode client retry
  internal/dataservice/cluster_test.go
  internal/dataservice/mock_test.go
  internal/dataservice/server.go
  internal/dataservice/server_test.go
  internal/distributed/datanode/client/client.go
  internal/distributed/masterservice/client/client.go
Labels: size/L

#5387 Add persistency of datanode cluster
  internal/dataservice/cluster_data_manager.go
  internal/dataservice/cluster_session_manager.go
  internal/dataservice/cluster_v2.go
  internal/dataservice/cluster_v2_test.go
  internal/dataservice/mock_test.go
  internal/dataservice/policy.go
  internal/dataservice/server.go
  internal/dataservice/server_test.go
  internal/proto/data_service.proto
  internal/proto/datapb/data_service.pb.go
Labels: component/dataservice, kind/feature, size/XXL

#5410 Add test cases for Index in sdk-orm
  tests20/python_client/testcases/test_index.py
Labels: size/L

#5399 Refactor repack logic for insertion
  go.mod
  go.sum
  internal/msgstream/mem_msgstream.go
  internal/msgstream/mq_msgstream.go
  internal/msgstream/msgstream.go
  internal/msgstream/msgstream_mock.go
  internal/proxynode/impl.go
  internal/proxynode/insert_channels.go
  internal/proxynode/repack_func.go
  internal/proxynode/task.go
Labels: size/XL

#5403 Fix grpcio version incompatible error
  tests/milvus_python_test/requirements.txt
Labels: size/XS

#5417 Fix recovery
  internal/dataservice/cluster_session_manager.go
  internal/dataservice/server_test.go
Labels: size/S

#5409 DataNode scales flowgraph
  docs/design_docs/datanode_recovery_design_0513_2021.md
  internal/datanode/collection_replica.go
  internal/datanode/data_node.go
  internal/datanode/data_node_test.go
  internal/datanode/data_sync_service.go
  internal/datanode/data_sync_service_test.go
  internal/datanode/flow_graph_dd_node.go
  internal/datanode/flow_graph_dd_node_test.go
  internal/datanode/flow_graph_filter_dm_node.go
  internal/datanode/flow_graph_insert_buffer_node.go
  internal/datanode/flow_graph_insert_buffer_node_test.go
  internal/datanode/flow_graph_message.go
  internal/datanode/flow_graph_msg_stream_input_node.go
  internal/datanode/mock_test.go
  internal/dataservice/cluster.go
  internal/dataservice/cluster_v2.go
  internal/dataservice/grpc_handler.go
  internal/dataservice/server.go
  internal/dataservice/server_test.go
  internal/proto/data_service.proto
  internal/proto/datapb/data_service.pb.go
Labels: size/XXL

#5426 Add cases for invalid DataFrame data and binary collection
  tests20/python_client/common/common_func.py
  tests20/python_client/testcases/test_collection.py
  tests20/python_client/testcases/test_insert.py
Labels: size/L

#5430 Support to use json to construct dummy request
  internal/proxynode/dummyreq.go
  internal/proxynode/dummyreq_test.go
  internal/proxynode/impl.go
Labels: kind/feature, size/L

#5432 Fix rocksmq seek error
  internal/util/rocksmq/client/rocksmq/consumer_impl.go
  internal/util/rocksmq/server/rocksmq/rocksmq.go
  internal/util/rocksmq/server/rocksmq/rocksmq_impl.go
Labels: kind/bug, size/S

#5427 Remove datanode client code
  internal/dataservice/server.go
  internal/dataservice/server_test.go
  internal/distributed/datanode/client/client.go
Labels: size/M

#5435 Add dataservice register and discovery
  internal/dataservice/cluster.go
  internal/dataservice/cluster_session_manager.go
  internal/dataservice/cluster_test.go
  internal/dataservice/cluster_v2.go
  internal/dataservice/cluster_v2_test.go
  internal/dataservice/grpc_handler.go
  internal/dataservice/mock_test.go
  internal/dataservice/server.go
  internal/dataservice/server_test.go
  internal/distributed/datanode/client/client.go
Labels: size/XXL

#5428 Add querynode grpc retry
  internal/distributed/querynode/client/client.go
  internal/queryservice/impl.go
Labels: size/L

#5424 watch proxynode
  internal/allocator/id.go
  internal/datanode/data_node.go
  internal/dataservice/server.go
  internal/dataservice/server_test.go
  internal/distributed/datanode/datanode_test.go
  internal/distributed/datanode/service.go
  internal/distributed/dataservice/client/client.go
  internal/distributed/dataservice/service.go
  internal/distributed/masterservice/client/client.go
  internal/distributed/masterservice/masterservice_test.go
  internal/distributed/masterservice/server.go
  internal/distributed/proxynode/service.go
  internal/distributed/querynode/service.go
  internal/distributed/queryservice/service.go
  internal/indexnode/indexnode.go
  internal/indexservice/indexservice.go
  internal/masterservice/master_service.go
  internal/masterservice/master_service_test.go
  internal/masterservice/proxy_client_manager.go
  internal/masterservice/proxy_node_manager.go
  internal/masterservice/proxy_node_manager_test.go
  internal/masterservice/task.go
  internal/masterservice/timeticksync.go
  internal/proxynode/proxy_node.go
  internal/querynode/query_node.go
  internal/queryservice/queryservice.go
  internal/types/types.go
  internal/util/sessionutil/session_util.go
  internal/util/sessionutil/session_util_test.go
Labels: component/master, size/XXL

#5434 Extract Milvus log files from KinD logs
  build/ci/jenkins/Jenkinsfile
Labels: kind/improvement, size/XS

#5442 Adjust the directory structure for archived Logs
  build/ci/jenkins/Jenkinsfile
Labels: kind/improvement, size/XS

#5412 Add New Partition Tests
  tests20/python_client/base/client_request.py
  tests20/python_client/base/partition.py
  tests20/python_client/check/func_check.py
  tests20/python_client/common/common_func.py
  tests20/python_client/common/common_type.py
  tests20/python_client/testcases/test_collection.py
  tests20/python_client/testcases/test_load.py
  tests20/python_client/testcases/test_partition.py
Labels: sdk/python, size/XL

#5418 Add indexnode grpc retry
  internal/distributed/indexnode/client/client.go
  internal/indexservice/node_mgr.go
Labels: size/M

#5441 Fix receving wrong msg after seek
  internal/msgstream/mq_msgstream.go
  internal/msgstream/mq_msgstream_test.go
Labels: size/L

#5444 Fix recovery branch after rebasing master
  internal/datanode/data_node.go
  internal/dataservice/cluster_session_manager.go
  internal/dataservice/server.go
Labels: size/S

#5448 Update milvus system configuration
  docs/developer_guides/appendix_c_system_configurations.md
Labels: kind/enhancement, size/M

#5451 add server type of mixture, enable the services run on progress
  docs/developer_guides/appendix_c_system_configurations.md
Labels: size/S

#5447 Update WatchDmChannels signature
  internal/dataservice/binlog_helper.go
  internal/dataservice/cluster.go
  internal/dataservice/cluster_test.go
  internal/dataservice/datanode_helper.go
  internal/dataservice/param.go
  internal/dataservice/policy.go
  internal/dataservice/server.go
  internal/proto/data_service.proto
  internal/proto/datapb/data_service.pb.go
Labels: component/dataservice, size/L

#5431 Change proxy grpc retry
  internal/distributed/masterservice/server.go
  internal/distributed/proxynode/client/client.go
  internal/proxyservice/node_info.go
Labels: size/M

#5425 Add indexservice grpc retry
  internal/distributed/indexnode/service.go
  internal/distributed/indexservice/client/client.go
  internal/distributed/masterservice/masterservice_test.go
  internal/distributed/masterservice/server.go
  internal/distributed/proxynode/service.go
  internal/distributed/querynode/service.go
Labels: size/L

#5413 storage: s3_address support domain/hostname.
  core/src/config/Config.cpp
  core/src/utils/ValidationUtil.cpp
  core/src/utils/ValidationUtil.h
  core/unittest/server/test_util.cpp
Labels: size/M

#5452 Add comments to proto
  internal/proto/milvus.proto
Labels: size/L

#5455 Index case update
  tests20/python_client/testcases/test_index.py
Labels: size/M

#5453 Replace insertChannelsMap with channelsMgr
  internal/proxynode/channels_mgr.go
  internal/proxynode/channels_mgr_test.go
  internal/proxynode/impl.go
  internal/proxynode/proxy_node.go
  internal/proxynode/task.go
Labels: kind/feature, size/L

#5437 Add queryservice grpc retry
  internal/distributed/masterservice/masterservice_test.go
  internal/distributed/masterservice/server.go
  internal/distributed/proxynode/service.go
  internal/distributed/querynode/service.go
  internal/distributed/queryservice/client/client.go
Labels: size/L

#5454 Complete Flush procedure in DataNode
  internal/datanode/data_node.go
  internal/datanode/data_node_test.go
  internal/datanode/data_sync_service.go
  internal/datanode/flow_graph_dd_node.go
  internal/datanode/flow_graph_dd_node_test.go
  internal/datanode/flow_graph_insert_buffer_node.go
  internal/datanode/mock_test.go
  internal/dataservice/grpc_handler.go
  internal/dataservice/server.go
  internal/dataservice/server_test.go
  internal/distributed/dataservice/client/client.go
  internal/types/types.go
Labels: size/L

#5446 Support launch multiple services in one process
  cmd/datanode/main.go
  cmd/dataservice/main.go
  cmd/distributed/main.go
  cmd/indexnode/main.go
  cmd/indexservice/main.go
  cmd/masterservice/main.go
  cmd/proxy/node/proxy_node.go
  cmd/proxy/service/proxy_service.go
  cmd/querynode/querynode.go
  cmd/queryservice/queryservice.go
Labels: kind/feature, size/XL

#5395 Add power-off restart logic for IndexService and IndexNode
  internal/distributed/indexnode/client/client.go
  internal/distributed/indexnode/service.go
  internal/distributed/indexservice/client/client.go
  internal/distributed/indexservice/service.go
  internal/indexnode/indexnode.go
  internal/indexnode/task.go
  internal/indexservice/indexservice.go
  internal/indexservice/meta_table.go
  internal/indexservice/node_mgr.go
  internal/indexservice/priority_queue.go
  internal/indexservice/task.go
  internal/kv/etcd/etcd_kv.go
  internal/proto/index_service.proto
  internal/proto/indexpb/index_service.pb.go
  internal/types/types.go
Labels: kind/feature, size/XXL

#5458 [skip ci] update partition tests for #5373 and #5392
  tests20/python_client/testcases/test_partition.py
Labels: manual-merge, sdk/python, size/L

#5467 [skip ci]Update code owners
  .github/CODEOWNERS
  OWNERS
Labels: manual-merge, size/M

#5440 Add dablooms
  .gitignore
  Makefile
  internal/util/dablooms/cwrapper/.gitignore
  internal/util/dablooms/cwrapper/CMakeLists.txt
  internal/util/dablooms/cwrapper/LICENSE
  internal/util/dablooms/cwrapper/build.sh
  internal/util/dablooms/cwrapper/dablooms.cpp
  internal/util/dablooms/cwrapper/dablooms.h
  internal/util/dablooms/cwrapper/murmur.cpp
  internal/util/dablooms/cwrapper/murmur.h
  internal/util/dablooms/dablooms.go
  internal/util/dablooms/dablooms_test.go
  scripts/cwrapper_dablooms_build.sh
Labels: approved, kind/feature, lgtm, size/XL

#5469 Add historical and streaming module in querynode
  internal/msgstream/mq_msgstream.go
  internal/msgstream/mq_msgstream_test.go
  internal/proto/internal.proto
  internal/proto/internalpb/internal.pb.go
  internal/querynode/collection_replica.go
  internal/querynode/collection_replica_test.go
  internal/querynode/data_sync_service_test.go
  internal/querynode/historical.go
  internal/querynode/impl.go
  internal/querynode/load_service_test.go
  internal/querynode/meta_service.go
  internal/querynode/meta_service_test.go
  internal/querynode/query_node.go
  internal/querynode/query_node_test.go
  internal/querynode/search_collection.go
  internal/querynode/search_service.go
  internal/querynode/search_service_test.go
  internal/querynode/stats_service_test.go
  internal/querynode/streaming.go
  internal/querynode/task.go
Labels: approved, lgtm, size/XXL

#5471 Fix extract log files bug
  build/ci/jenkins/Jenkinsfile
Labels: approved, lgtm, size/XS

#5459 Fix #5191
  shards/mishards/service_handler.py
Labels: approved, size/S
