Repository milvus-io/milvus, pull requests merged in 2021-12, with the labels that each got.

#12469 Implement Drop mode for flush manager
  internal/datanode/compactor_test.go
  internal/datanode/data_sync_service.go
  internal/datanode/flow_graph_delete_node_test.go
  internal/datanode/flow_graph_insert_buffer_node_test.go
  internal/datanode/flush_manager.go
  internal/datanode/flush_manager_test.go
  internal/datanode/mock_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#12485 Add ut for CreateAlias when ctx is short
  internal/proxy/proxy_test.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#12500 [skip ci] Add comment for get_release_name.sh
  tests/scripts/get_release_name.sh
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#12501 [skip ci]Update grafana legendFormat
  deployments/monitor/grafana/milvus-dashboard.json
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#12502 [skip ci]Update grafana panel
  deployments/monitor/grafana/milvus-dashboard.json
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#12504 [skip ci] Add comment for ci_e2e.sh
  tests/scripts/ci_e2e.sh
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#12509 [skip ci] Add comment for milvus.yaml
  configs/milvus.yaml
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#12384 [skip ci] Add comments for milvus.yaml
  configs/milvus.yaml
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#12429 [skip ci] Add comments for milvus.yaml
  configs/milvus.yaml
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#12480 [skip ci] Set docker mirror for ci build docker image
  build/ci/jenkins/Jenkinsfile
  build/ci/jenkins/Nightly.groovy
  build/ci/jenkins/PR.groovy
  build/ci/jenkins/PublishImages.groovy
  build/set_docker_mirror.sh
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#12506 [skip ci] Add comment for ci_logs.sh
  tests/scripts/ci_logs.sh
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#12508 [skip ci] Add comment for milvus.yaml
  configs/milvus.yaml
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#12510 [skip ci] Add comment for milvus.yaml
  configs/milvus.yaml
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#12526 [skip ci] Modify L2 test case for design change
  tests/python_client/testcases/test_collection.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#12527 [skip ci] Adjust test case level
  tests/python_client/testcases/test_search_20.py
Labels: kind/improvement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#12522 Refine log of DropCollection
  internal/proxy/impl.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#12511 Fix similarity correlation
  internal/core/src/segcore/SimilarityCorelation.h
  internal/core/src/segcore/segment_c.cpp
  internal/core/unittest/test_similarity_corelation.cpp
  internal/proxy/task.go
  internal/util/distance/similarity_corelation.go
  internal/util/distance/similarity_corelation_test.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#12515 Format test_c_api.cpp
  internal/core/unittest/test_c_api.cpp
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#12460 [skip ci]Update typos in segment growing md
  docs/design_docs/segcore/segment_growing.md
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#12444 [skip ci]Update typos in proxy md
  docs/design_docs/proxy.md
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#12464 Refine test levels in test partition
  tests/python_client/testcases/test_partition_20.py
Labels: sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#12484 Add ut for CreateAlias when dd queue is full
  internal/proxy/proxy_test.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#12518 Refine test level for test partition
  tests/python_client/testcases/test_partition.py
Labels: sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#12520 [skip ci] Add comment for internal/storage/data_codec.go
  internal/storage/data_codec.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#12521 Add ut for DropAlias when proxy is unhealthy
  internal/proxy/proxy_test.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#12523 Refine log of HasCollection
  internal/proxy/impl.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#12524 [skip ci] Add comment for storage.ChunManger methods
  internal/storage/types.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#12525 [skip ci] Add comments for distributed/datanode/client/client.go
  internal/distributed/datanode/client/client.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#12533 [skip ci]Fix-failed to get environment variable CI_LOG_PATH
  tests/scripts/ci_e2e.sh
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#12517 Enlarge field number limitation
  configs/milvus.yaml
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#12538 [skip ci]Update release name in chaos test action
  .github/workflows/pod-kill-chaos-test.yaml
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#12499 Fix zero length slice declaration in proxy/channels_mgr.go
  internal/proxy/channels_mgr.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#12347 Add logs for add delta channels
  internal/querycoord/meta.go
  internal/querycoord/task.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#12337 support cpu/qemu only support SSE42
  internal/core/src/index/thirdparty/CMakeLists.txt
  internal/core/src/index/thirdparty/faiss/Makefile
  internal/core/src/index/thirdparty/faiss/utils/distances_simd_avx.cpp
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#12544 [skip ci]Update release name in export logs step
  .github/workflows/pod-kill-chaos-test.yaml
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#12542 [skip ci] add notes to client.go
  internal/distributed/proxy/client/client.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#12543 [skip ci] add client notes
  internal/distributed/proxy/client/client.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#12548 [skip ci]Update grafana panel
  deployments/monitor/grafana/milvus-dashboard.json
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#12549 [skip ci] Add new params on benchmark
  tests/benchmark/milvus_benchmark/config.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#12547 [skip ci] Update timeout to 70 minutes to run more test cases
  build/ci/jenkins/Jenkinsfile
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#12552 [skip ci] Add new func on update file
  tests/benchmark/milvus_benchmark/update.py
Labels: kind/improvement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#12553 [skip ci] Remove arguments equal to default
  tests/python_client/testcases/test_collection.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#12551 [skip ci] Delete package of parser on benchmark
  tests/benchmark/milvus_benchmark/parser.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, test/benchmark, dco-passed

#12539 Adjust the tags of collection cases
  tests/python_client/testcases/test_collection.py
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#12530 Adjust L2 to L1 test case level
  tests/python_client/testcases/test_search_20.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#12554 [skip ci] Add comment to test case
  tests/python_client/testcases/test_collection.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#12462 Add case to test compact with time travel
  tests/python_client/common/common_type.py
  tests/python_client/testcases/test_compaction.py
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#12519 disable traceback for checker of chaos test
  tests/python_client/chaos/checker.py
Labels: kind/improvement, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#12546 Fix thread safe issue when search
  internal/querynode/historical.go
  internal/querynode/streaming.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#12555 [skip ci]Update license for qn fg insert
  internal/querynode/flow_graph_insert_node.go
  internal/querynode/flow_graph_insert_node_test.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#12556 [skip ci]Update license for qn fg message
  internal/querynode/flow_graph_message.go
  internal/querynode/flow_graph_message_test.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#12562 [skip ci] Refine datacoord cluster comment
  internal/datacoord/cluster.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#12560 [skip ci] Refine data node param table comment
  internal/datanode/param_table.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#12561 [skip ci] Add license for data coord compaction
  internal/datacoord/compaction.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#12505 format code of test_utility.py
  tests/python_client/testcases/test_utility.py
Labels: kind/improvement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#12573 [skip ci]Add comment for removeNodeInfo
  internal/querycoord/cluster.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#12574 [skip ci]Add comment for stopNode
  internal/querycoord/cluster.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#12532 Remove querynode grpc error
  internal/querynode/impl.go
  internal/querynode/impl_test.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#12535 Remove querycoord grpc error
  internal/querycoord/impl.go
  internal/querycoord/impl_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#12537 Remove grpc returned error
  internal/datacoord/services.go
  internal/datanode/data_node.go
  internal/indexcoord/index_coord.go
  internal/indexnode/indexnode.go
  internal/proxy/impl.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#12568 [skip ci]Fix golint error for initPort in indexnode
  internal/distributed/indexnode/param_table.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#12564 [skip ci] Add comment for filterDeleteNode Name
  internal/querynode/flow_graph_filter_delete_node.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#12550 [skip ci]Remove useless words
  docs/developer_guides/how-guarantee-ts-works.md
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#12528 Use write lock when writing the var
  internal/querynode/segment.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#12557 [skip ci]Update license for qn fg querynode
  internal/querynode/flow_graph_node.go
  internal/querynode/flow_graph_query_node.go
  internal/querynode/flow_graph_query_node_test.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#12566 [skip ci] Add comment for filterDeleteNode filter func
  internal/querynode/flow_graph_filter_delete_node.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#12567 [skip ci]Fix golint error for indexcoord
  internal/distributed/indexnode/param_table.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#12569 [skip ci]Add comment for rocksmq reader
  internal/util/rocksmq/server/rocksmq/rocksmq_impl.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#12570 [skip ci]Add comment for rocksmq reader
  internal/util/rocksmq/server/rocksmq/rocksmq_impl.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#12572 Fix alloc segment with dropped segment
  internal/datacoord/segment_manager.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed

#12575 [skip ci]Add comment for getOnlineNodes
  internal/querycoord/cluster.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#12576 Fix zero length slice declaration in util/retry/retry.go
  internal/util/retry/retry.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#12577 Fix zero length slice declaration in rocksmq_impl.go
  internal/util/rocksmq/server/rocksmq/rocksmq_impl.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#12579 [skip ci] Update minio storage class in PR to be consistent with Nigh…
  build/ci/jenkins/PR.groovy
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#12255 Add rocksmq server close when standalone exit
  cmd/roles/roles.go
  internal/util/rocksmq/server/rocksmq/global_rmq.go
  internal/util/rocksmq/server/rocksmq/global_rmq_test.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#12536 Remove unmaintained CHANGELOG.md
  CHANGELOG.md
Labels: kind/improvement, size/XL, approved, lgtm, ci-passed, dco-passed

#12534 Remove unused dependency
  Makefile
  internal/util/dablooms/cwrapper/.gitignore
  internal/util/dablooms/cwrapper/CMakeLists.txt
  internal/util/dablooms/cwrapper/LICENSE
  internal/util/dablooms/cwrapper/build.sh
  internal/util/dablooms/cwrapper/dablooms.cpp
  internal/util/dablooms/cwrapper/dablooms.h
  internal/util/dablooms/cwrapper/murmur.cpp
  internal/util/dablooms/cwrapper/murmur.h
  internal/util/dablooms/dablooms.go
  internal/util/dablooms/dablooms_test.go
Labels: kind/improvement, size/XL, approved, lgtm, ci-passed, dco-passed

#12578 Update Search return type
  internal/core/src/segcore/SegmentInterface.cpp
  internal/core/src/segcore/SegmentInterface.h
  internal/core/src/segcore/segment_c.cpp
  internal/core/unittest/test_query.cpp
  internal/core/unittest/test_sealed.cpp
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#12591 Update proxy debug log
  internal/proxy/task.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#12595 [skip ci] Add new func of utils on benchmark
  tests/benchmark/milvus_benchmark/utils.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#12581 [skip ci] Add comment for ci_e2e.sh
  tests/scripts/ci_e2e.sh
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#12583 [skip ci] Add comment for get_release_name.sh
  tests/scripts/get_release_name.sh
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#12586 [skip ci] Remove arguments equal to default
  tests/python_client/testcases/test_insert_20.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#12587 Adjust the tags of insert cases
  tests/python_client/testcases/entity/test_insert.py
Labels: sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#12588 [skip ci]Comment out collection.release() for deploy and chaos test
  tests/python_client/chaos/scripts/hello_milvus.py
  tests/python_client/deploy/scripts/utils.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#12596 [skip ci] Update nq of locust_user on benchmark
  tests/benchmark/milvus_benchmark/runners/locust_user.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#12597 [skip ci] Add gt of query func on benchmark
  tests/benchmark/milvus_benchmark/client.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#12563 Apply DropVirtualChannel and FlushManager drop mode
  internal/datacoord/channel_manager.go
  internal/datacoord/handler.go
  internal/datacoord/meta.go
  internal/datacoord/mock_test.go
  internal/datacoord/server_test.go
  internal/datacoord/services.go
  internal/datanode/compaction_executor.go
  internal/datanode/compaction_executor_test.go
  internal/datanode/compactor.go
  internal/datanode/data_node.go
  internal/datanode/data_sync_service.go
  internal/datanode/data_sync_service_test.go
  internal/datanode/flow_graph_dd_node.go
  internal/datanode/flow_graph_dd_node_test.go
  internal/datanode/flow_graph_delete_node.go
  internal/datanode/flow_graph_delete_node_test.go
  internal/datanode/flow_graph_insert_buffer_node.go
  internal/datanode/flow_graph_insert_buffer_node_test.go
  internal/datanode/flush_manager.go
  internal/datanode/flush_manager_test.go
Labels: kind/enhancement, size/XL, approved, lgtm, ci-passed, dco-passed

#12628 [skip ci] remove docker mirror for https problem
  build/ci/jenkins/Jenkinsfile
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#12620 [skip ci] Fix golint for metricinfo/cache.go
  internal/util/metricsinfo/cache.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#12621 [skip ci] Fix comment for PayloadReader
  internal/storage/payload.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#12584 Adjust the tags of insert cases
  tests/python_client/testcases/test_compaction.py
  tests/python_client/testcases/test_insert_20.py
Labels: sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#12602 [skip ci]Add comment when stop rpc server in querynode service
  internal/distributed/querynode/service.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#12603 [skip ci]Add comment when stop rpc server in rootcoord service
  internal/distributed/rootcoord/service.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#12608 [skip ci] Add comment for milvus.yaml
  configs/milvus.yaml
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#12609 [skip ci] Add comment for milvus.yaml
  configs/milvus.yaml
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#12610 [skip ci] Add comment for milvus.yaml
  configs/milvus.yaml
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#12616 [skip ci] Add comment for DataDefinitionCodec
  internal/storage/data_codec.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#12637 [skip ci] Refine data node flow graph comment
  internal/datanode/flow_graph_dd_node.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#12601 Update compaction auto-merge case
  tests/python_client/testcases/test_compaction.py
Labels: sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#12594 Add check and delete pvc in case pvc is not cleaned up
  tests/scripts/uninstall_milvus.sh
Labels: kind/improvement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#12631 Add ctx for indexLoader
  internal/querynode/index_loader.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#12636 Fix typo in datacoord compaction trigger
  internal/datacoord/compaction_trigger.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#12638 [skip ci] Refine datanode binlog io comment
  internal/datanode/binlog_io.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#12590 Remove redundant conversion in event_writer.go
  internal/storage/event_writer.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#12582 Fix zero length slice declaration in datacoord/channel_manager.go
  internal/datacoord/channel_manager.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#12639 [skip ci]Update grafana panel
  deployments/monitor/grafana/milvus-dashboard.json
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#12641 [skip ci]Update grafana format
  deployments/monitor/grafana/milvus-dashboard.json
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#12650 [skip ci] Shorten long sentences
  tests/python_client/testcases/test_compaction.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#12651 [skip ci] Fix typos in comments
  tests/python_client/testcases/test_connection.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#12646 [skip ci]Update license for qn global sealed seg
  internal/querynode/global_sealed_segment_manager.go
  internal/querynode/global_sealed_segment_manager_test.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#12642 [skip ci]Organize wait pods ready function
  tests/python_client/chaos/test_chaos.py
  tests/python_client/common/cus_resource_opts.py
  tests/python_client/utils/util_k8s.py
Labels: kind/improvement, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#12645 [skip ci]Update license for qn fg service
  internal/querynode/flow_graph_service_time_node.go
  internal/querynode/flow_graph_service_time_node_test.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#12647 [skip ci]Update license for qn historical
  internal/querynode/historical.go
  internal/querynode/historical_test.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#12652 [skip ci] Fix typos in test comments
  tests/python_client/testcases/test_delete.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#12653 [skip ci]Change comment of CreateReader
  internal/util/mqclient/client.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#12654 [skip ci]Improve comment for CreateProducer
  internal/util/mqclient/client.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#12655 [skip ci]Improve comment for Subscribe
  internal/util/mqclient/client.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#12656 [skip ci] Add idle back
  build/ci/jenkins/Jenkinsfile
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#12657 [skip ci] Add comment for newFilterDeleteNode
  internal/querynode/flow_graph_filter_delete_node.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#12658 [skip ci] Add comment for filterDMNode
  internal/querynode/flow_graph_filter_dm_node.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#12659 [skip ci] Add comment for filterDMNode Name
  internal/querynode/flow_graph_filter_dm_node.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#12661 [skip ci]Add load balance testcase
  tests/python_client/chaos/checker.py
  tests/python_client/loadbalance/test_auto_load_balance.py
Labels: kind/improvement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#12663 [skip ci]Fix golint for getOfflineNodes
  internal/querycoord/cluster.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#12664 [skip ci]Fix golint for isOnline
  internal/querycoord/cluster.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#12665 [skip ci]Fix golint for getComponentInfos
  internal/querycoord/cluster.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#12451 Check the indexcoord state before building index
  internal/indexcoord/index_coord.go
  internal/indexcoord/index_coord_test.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#12666 [skip ci]Update grafana panel
  deployments/monitor/grafana/milvus-dashboard.json
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#12670 [skip ci]Fix import of util_k8s.py
  tests/python_client/utils/util_k8s.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#12630 Support load collection with multiple vector column
  internal/core/src/pb/milvus.pb.cc
  internal/core/src/pb/milvus.pb.h
  internal/proto/milvus.proto
  internal/proto/milvuspb/milvus.pb.go
  internal/querynode/impl_test.go
  internal/querynode/index_info.go
  internal/querynode/index_loader.go
  internal/querynode/index_loader_test.go
  internal/querynode/mock_components_test.go
  internal/querynode/mock_test.go
  internal/querynode/segment.go
  internal/querynode/segment_loader.go
  internal/querynode/segment_loader_test.go
  internal/querynode/segment_test.go
  internal/rootcoord/task.go
Labels: kind/bug, kind/improvement, area/api, size/XXL, approved, lgtm, ci-passed, dco-passed

#12679 [skip ci] Remove arguments equal to default
  tests/python_client/testcases/test_query.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#12669 [skip ci] Add comment for ci_e2e.sh
  tests/scripts/ci_e2e.sh
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#12671 [skip ci] Add devops email in failed build notification
  build/ci/jenkins/Jenkinsfile
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#12672 [skip ci] Remove space to fix jenkinsfile lint
  build/ci/jenkins/Nightly.groovy
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#12674 [skip ci] Add comments for milvus.yaml
  configs/milvus.yaml
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#12675 [skip ci] Add comments for milvus.yaml
  configs/milvus.yaml
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#12676 [skip ci] Add comments for milvus.yaml
  configs/milvus.yaml
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#12681 [skip ci] Add comment to util k8s method
  tests/python_client/utils/util_k8s.py
Labels: kind/improvement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#12683 [skip ci] Modify auto-merge case to L2 and increase timeout
  tests/python_client/testcases/test_compaction.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#12684 [skip ci] Fix typos in test case
  tests/python_client/utils/util_k8s.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#12685 [skip ci] Refine test comments
  tests/python_client/testcases/test_partition_20.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#12686 [skip ci] Modify test comments
  tests/python_client/testcases/test_partition_20.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#12689 [skip ci] Update nq of locust_user on benchmark
  tests/benchmark/milvus_benchmark/runners/locust_user.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#12687 [skip ci] Update server_resource of server config on benchmark
  tests/benchmark/milvus_benchmark/update.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#12688 [skip ci] Removed unused logs on benchmark
  tests/benchmark/milvus_benchmark/client.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#12699 [skip ci] Enable GC in nightly temporarily
  build/ci/jenkins/NightlyCI.groovy
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#12307 Fixbug: grpc connection is closed by mistake
  internal/distributed/datacoord/client/client.go
  internal/distributed/datacoord/client/client_test.go
  internal/distributed/datanode/client/client.go
  internal/distributed/datanode/client/client_test.go
  internal/distributed/indexcoord/client/client.go
  internal/distributed/indexcoord/client/client_test.go
  internal/distributed/indexnode/client/client.go
  internal/distributed/indexnode/client/client_test.go
  internal/distributed/proxy/client/client.go
  internal/distributed/proxy/client/client_test.go
  internal/distributed/querycoord/client/client.go
  internal/distributed/querycoord/client/client_test.go
  internal/distributed/querynode/client/client.go
  internal/distributed/querynode/client/client_test.go
  internal/distributed/rootcoord/client/client.go
  internal/distributed/rootcoord/client/client_test.go
  internal/querycoord/index_checker.go
  internal/querycoord/querynode.go
  internal/querycoord/task.go
  internal/querynode/data_sync_service_test.go
  internal/querynode/flow_graph_query_node_test.go
  internal/querynode/flow_graph_service_time_node_test.go
  internal/querynode/historical_test.go
  internal/querynode/mock_test.go
  internal/querynode/plan_test.go
  internal/querynode/query_collection_test.go
  internal/querynode/query_node.go
  internal/querynode/query_node_test.go
  internal/querynode/query_service_test.go
  internal/querynode/segment_test.go
  internal/querynode/streaming_test.go
  internal/querynode/tsafe_replica.go
  internal/querynode/tsafe_replica_test.go
  internal/util/grpcclient/client.go
  internal/util/grpcclient/client_test.go
  internal/util/mock/datacoord_client.go
  internal/util/mock/datanode_client.go
  internal/util/mock/grpcclient.go
  internal/util/mock/indexnode_client.go
  internal/util/mock/proxy_client.go
  internal/util/mock/querycoord_client.go
  internal/util/mock/querynode_client.go
  internal/util/mock/rootcoord_client.go
Labels: size/XXL, approved, lgtm, ci-passed, dco-passed

#12698 [skip ci]Update typos in opentracing user guide
  docs/jaeger_guides/opentracing_user_guide.md
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#12606 Refine words in proxy reduce md file
  docs/developer_guides/proxy-reduce.md
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#12607 [skip ci]Fix typos in drop collection release resource md file
  docs/design_docs/drop_collection_release_resources_en.md
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed
