Repository milvus-io/milvus, pull requests merged in 2021-10, with the labels that each got.

#8721 Change Log Name with NodeId
  cmd/roles/roles.go
  internal/datacoord/param_table.go
  internal/datacoord/server.go
  internal/datanode/data_node.go
  internal/datanode/param_table.go
  internal/indexcoord/index_coord.go
  internal/indexcoord/param_table.go
  internal/indexnode/indexnode.go
  internal/indexnode/param_table.go
  internal/proxy/param_table.go
  internal/proxy/proxy.go
  internal/querycoord/param_table.go
  internal/querycoord/query_coord.go
  internal/querynode/param_table.go
  internal/querynode/query_node.go
  internal/rootcoord/param_table.go
  internal/rootcoord/root_coord.go
  internal/util/paramtable/basetable.go
  internal/util/paramtable/basetable_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed

#8986 [skip ci] Add document about how to start test cluster
  DEVELOPMENT.md
Labels: kind/improvement, size/S, approved, lgtm, ci-passed

#8988 Optmize collection wrapper import
  tests/python_client/base/collection_wrapper.py
Labels: kind/improvement, size/XS, approved, lgtm, area/test, ci-passed

#8997 [skip ci]Fix links in README_CN.md
  README_CN.md
Labels: kind/improvement, size/S, approved, lgtm, ci-passed

#9003 [skip ci] Add mem limit of benchmark update server
  tests/benchmark/milvus_benchmark/update.py
Labels: kind/improvement, size/XS, approved, lgtm, area/test, ci-passed

#9005 [skip ci] Add log of update milvus on benchmark
  tests/benchmark/milvus_benchmark/update.py
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#9004 [skip ci] Add condition of milvus limit deploy on benchmark
  tests/benchmark/milvus_benchmark/update.py
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#9006 [skip ci] Add grafana panel description
  deployments/monitor/grafana/milvus-dashboard.json
Labels: kind/improvement, size/M, approved, lgtm, ci-passed

#8963 [skip ci] Add comment for newHistorical
  internal/querynode/historical.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#8961 [skip ci] Add comment for LoadSegments
  internal/types/types.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#8962 [skip ci] Add comment for newDataSyncService
  internal/querynode/data_sync_service.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#8913 [skip ci] Add comment for releaseCollection
  internal/querycoord/impl.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#8912 [skip ci] Add comment for loadPartition
  internal/querycoord/impl.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#8966 [skip ci]Add global id comment
  internal/allocator/global_id.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#8967 [skip ci]Add allocator id comment
  internal/allocator/id.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#8976 [skip ci]Update comments for configs in datanode
  configs/advanced/data_node.yaml
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#8964 [skip ci] Update order of header files
  internal/rootcoord/root_coord.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#8975 [skip ci]Fix golint in indexnode/param_table.go
  internal/indexnode/param_table.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#8977 [skip ci]Fix golint in indexnode/index.go
  internal/indexnode/index.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#8991 Refine indexnode logs
  internal/indexnode/indexnode.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed

#8994 [skip ci] Add comment for releasePartition
  internal/querycoord/impl.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#8995 [skip ci] Add comment for createQueryChannel
  internal/querycoord/impl.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#8996 [skip ci] Add comment for GetPartitionStates
  internal/querycoord/impl.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#8998 [skip ci] Print out cpp coverage report path
  scripts/run_cpp_codecov.sh
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#9008 [skip ci] Refine development doc toc
  DEVELOPMENT.md
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#9009 [skip ci] Add grafana panel description
  deployments/monitor/grafana/milvus-dashboard.json
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#9018 [skip ci] Add desc comments for channelsMgr
  internal/proxy/channels_mgr.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#9019 [skip ci] Add desc comments for Condition
  internal/proxy/condition.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#9020 [skip ci] Add desc comments for channelsTimeTicker
  internal/proxy/channels_time_ticker.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#9024 [skip ci] Increase pr ci timeout
  build/ci/jenkins/Jenkinsfile
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#8999 [skip ci] Macro for go coverage script
  scripts/run_go_codecov.sh
Labels: kind/improvement, size/S, approved, lgtm, ci-passed

#9000 [skip ci]Update test comments
  tests/python_client/testcases/test_partition_20.py
Labels: kind/improvement, size/XS, approved, lgtm, area/test, ci-passed

#9002 [skip ci]Update comments in connection test
  tests/python_client/testcases/test_connection.py
Labels: kind/improvement, size/XS, approved, lgtm, area/test, ci-passed

#9007 [skip ci]Refine comments in milvusSys class
  tests/python_client/common/milvus_sys.py
Labels: kind/improvement, size/XS, approved, lgtm, area/test, ci-passed

#9025 [skip ci] Add test comments
  tests/python_client/testcases/test_collection.py
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#9026 [skip ci] Add comments for test case
  tests/python_client/testcases/test_collection.py
Labels: kind/improvement, size/XS, ci-passed

#9023 [skip ci]Format rocksmq docs
  docs/developer_guides/chap04_message_stream.md
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#9027 [skip ci] Improve long sentence
  tests/python_client/testcases/test_alias.py
Labels: kind/improvement, size/XS, ci-passed

#9028 [skip ci]Add comment for github action
  .github/workflows/network-partition-chaos-test.yaml
Labels: kind/improvement, size/XS, ci-passed

#9021 [skip ci]Format message stream doc
  docs/developer_guides/chap04_message_stream.md
Labels: kind/improvement, size/S, approved, lgtm, ci-passed

#9011 Check error in server_test.go
  internal/datacoord/server_test.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#9012 Check error in server test
  internal/datacoord/server_test.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#9010 Add db_name for alias proto
  internal/core/src/pb/milvus.pb.cc
  internal/core/src/pb/milvus.pb.h
  internal/proto/internal.proto
  internal/proto/internalpb/internal.pb.go
  internal/proto/milvus.proto
  internal/proto/milvuspb/milvus.pb.go
  tests/python_client/requirements.txt
Labels: kind/improvement, size/XXL, approved, lgtm, ci-passed

#9033 [skip ci] Add comments for alias testcase
  tests/python_client/testcases/test_alias.py
Labels: kind/improvement, size/XS, ci-passed

#9034 [skip ci] Add comments for github action
  .github/workflows/pod-kill-chaos-test.yaml
Labels: kind/improvement, size/XS, ci-passed

#9030 [skip ci]Fix allocator comment
  internal/allocator/global_id.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#9036 [skip ci] Add comment for datanode meta_service.go
  internal/datanode/meta_service.go
Labels: kind/improvement, size/XS, ci-passed

#8907 Add unittest for distributed/proxy
  internal/distributed/proxy/client/client.go
  internal/distributed/proxy/client/client_test.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed

#9041 [skip ci] Fix golint error in indexcoord
  internal/indexcoord/task_scheduler.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#9040 [skip ci] fix golint error in datacoord
  internal/distributed/datacoord/service.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#9042 [skip ci] Fix golint error in print_binlog
  internal/storage/print_binlog.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#9043 [skip ci] Add comment for HandleCStatus
  internal/querynode/cgo_helper.go
Labels: kind/improvement

#9044 [skip ci] Add comment for HandleCProtoResult
  internal/querynode/cgo_helper.go
Labels: kind/improvement, size/XS, ci-passed

#9045 [skip ci] Add comment for Schema
  internal/querynode/collection.go
Labels: kind/improvement, size/XS, ci-passed

#9037 Add ClusterStore implementation assertion
  internal/datacoord/cluster_store.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#9046 [skip ci]Remove conflict rule of mergify
  .github/mergify.yml
Labels: kind/improvement, size/S, approved, lgtm, ci-passed

#9048 [skip ci]Remove some rules which cause unexpected behavior
  .github/mergify.yml
Labels: kind/improvement, size/S, approved, lgtm, ci-passed

#9050 [skip ci] Update deploy params of standalone milvus on benchmark
  tests/benchmark/milvus_benchmark/update.py
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#9049 [skip ci] Update deploy params of cluster milvus on benchmark
  tests/benchmark/milvus_benchmark/update.py
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#9051 [skip ci] Add comment of main file on benchmark
  tests/benchmark/milvus_benchmark/main.py
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#9053 [skip ci] Add visitor.md
  docs/design_docs/segcore/visitor.md
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#8941 [skip ci] Update comment for release DQL message stream
  internal/types/types.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed

#8943 [skip ci] Update comment for segment flush completed
  internal/types/types.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed

#8945 [skip ci] Update comment for get metrics
  internal/types/types.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#8946 [skip ci] Update comment for get metrics
  internal/types/types.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#8948 [skip ci] Update comment for update state code
  internal/types/types.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#8950 [skip ci] Update comment for set datacoord
  internal/types/types.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#8951 [skip ci] Update comment for set indexcoord
  internal/types/types.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#8956 [skip ci] Update comment for set querycoord
  internal/types/types.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#8957 [skip ci] Update comment for set proxy client
  internal/types/types.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#8993 Minor fixes
  tools/core_gen/assemble.py
  tools/core_gen/meta_gen.py
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#9055 [skip ci] Add comment for GetMetrics
  internal/querycoord/impl.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#9054 [skip ci] Add comment for GetSegmentInfo
  internal/querycoord/impl.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#9056 [skip ci] Add comment for MetaReplica
  internal/querycoord/meta.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#8959 [skip ci] Update comment for create index
  internal/types/types.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#8960 [skip ci] Update comment for drop index
  internal/types/types.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#9059 [skip ci]Fix GetSegmentInfo comment typo
  internal/querycoord/impl.go
Labels: kind/improvement, approved, lgtm, ci-passed

#9060 [skip ci] Comment for go coverage script
  scripts/run_go_unittest.sh
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#9062 [skip ci] Fix script comment
  scripts/stop.sh
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#9063 [skip ci] PR uses milvus-helm 2.1.22 to install milvus
  build/ci/jenkins/Jenkinsfile
  tests/scripts/install_milvus.sh
Labels: kind/improvement, sig/testing, size/M, approved, lgtm, area/test, ci-passed

#9064 [skip ci] Add desc comments for ValidateCollectionAlias
  internal/proxy/validate_util.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#9065 [skip ci] Add desc comments for MetricsCacheManager
  internal/util/metricsinfo/cache.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#9066 [skip ci] Add desc comments for GetCPUUsage
  internal/util/metricsinfo/hardware_info.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#9038 Add Manager implemenation assertion
  internal/datacoord/segment_manager.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#9069 [skip ci]Update grafana panel description
  deployments/monitor/grafana/milvus-dashboard.json
Labels: kind/improvement, size/M, approved, lgtm, ci-passed

#9070 [skip ci]Update build doc format
  build/README.md
Labels: kind/improvement, size/S, approved, lgtm, ci-passed

#9068 [skip ci]Update offline README.md format
  deployments/offline/README.md
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#9071 [skip ci] Fix golint error in id.go
  internal/allocator/id.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#9072 [skip ci] Refine milvus binary deployment doc
  deployments/binary/README.md
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#9073 [skip ci] Refine contributing doc
  CONTRIBUTING.md
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#9077 Optmize connection wrapper import
  tests/python_client/base/connections_wrapper.py
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed

#9078 [skip ci] Add comment to collection properities check
  tests/python_client/check/func_check.py
Labels: kind/improvement, sig/testing, size/S, approved, lgtm, area/test, ci-passed

#9079 [skip ci] Add comment to query result check
  tests/python_client/check/func_check.py
Labels: kind/improvement, sig/testing, size/S, approved, lgtm, area/test, ci-passed

#9075 Fix Assigner typo
  internal/proxy/proxy.go
  internal/proxy/segment.go
  internal/proxy/task.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed

#9083 [skip ci]Format message stream docs
  docs/developer_guides/chap04_message_stream.md
Labels: kind/improvement, size/S, approved, lgtm, ci-passed

#9080 [skip ci]Update comments for connection tests
  tests/python_client/testcases/test_connection.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed

#9081 [skip ci]Remove useless code
  tests/python_client/testcases/test_e2e.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed

#9082 [skip ci]Add comments in chaos checker
  tests/python_client/chaos/checker.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed

#9084 [skip ci]Format RmqTtMsgStream docs
  docs/developer_guides/chap04_message_stream.md
Labels: kind/improvement, size/S, approved, lgtm, ci-passed

#9085 [skip ci]Format schema docs
  docs/developer_guides/chap02_schema.md
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#9067 [skip ci] Fix golint error in GlobalTSOAllocator
  internal/tso/global_allocator.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#9086 [skip ci] Fix golint error in options.go
  internal/util/retry/options.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#9092 [skip ci] Remove useless test code
  tests/python_client/testcases/test_flush.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed

#9090 [skip ci] Add comments for test case
  tests/python_client/testcases/test_collection.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed

#9087 [skip ci]Add DescribeCollectionRequest in chap05_proxy.md
  docs/developer_guides/chap05_proxy.md
Labels: kind/improvement, size/L, approved, lgtm, ci-passed

#9089 [skip ci] Delete the config of report portal
  tests/python_client/pytest.ini
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed

#9088 Format doc markdown for proxy-reduce-cn.md
  docs/developer_guides/proxy-reduce-cn.md
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#9091 [skip ci] Shorten long sentence
  tests/python_client/testcases/test_alias.py
Labels: kind/improvement, sig/testing, size/S, approved, lgtm, area/test, ci-passed

#9093 Fix typo in testcase
  tests/python_client/testcases/test_alias.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed

#9094 Delete unused import
  tests/python_client/testcases/test_alias.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed

#9057 Make NewMeta private
  internal/datacoord/meta.go
  internal/datacoord/meta_test.go
  internal/datacoord/mock_test.go
  internal/datacoord/segment_manager_test.go
  internal/datacoord/server.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed

#9095 Add comment for AssignSegmentID for Datacoord in types
  internal/types/types.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed

#9101 [skip ci] Add comment for addPartitionID
  internal/querynode/collection.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#9102 [skip ci] Add comment for removePartitionID
  internal/querynode/collection.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#9096 [skip ci]Fix golint warnings in dabloom
  internal/util/dablooms/dablooms.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#9097 [skip ci]Fix golint warnings in distance
  internal/util/distance/calc_distance.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed

#9098 [skip ci]Fix golint warnings in uniquegenerator
  internal/util/uniquegenerator/unique_int_generator.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#9099 [skip ci]Fix golint warnings in tsoutil
  internal/util/tsoutil/tso.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#9100 [skip ci]Fix golint warnings in trace
  internal/util/trace/interceptor_suite.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#9103 [skip ci] Add comment for addVChannels
  internal/querynode/collection.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#9104 [skip ci]Fix golint warnings in timerecord
  internal/util/timerecord/time_recorder.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#9109 [skip ci] Add comment for Params
  internal/querycoord/param_table.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#9107 [skip ci] Add comment for UniqueID
  internal/querycoord/param_table.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#9108 [skip ci] Add comment for ParamTable
  internal/querycoord/param_table.go
Labels: kind/improvement, approved, lgtm, ci-passed

#9112 [skip ci] fix golint error in common.go
  internal/common/common.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed

#9110 [skip ci]Add comments in chaos checker
  tests/python_client/chaos/checker.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed

#9111 [skip ci]Add comments in chaos commons
  tests/python_client/chaos/chaos_commons.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed

#9113 [skip ci]Update log info
  tests/python_client/chaos/test_chaos_data_consist.py
Labels: kind/improvement, sig/testing, size/S, approved, lgtm, area/test, ci-passed

#9114 [skip ci] fix golint error in binlog_reader.go
  internal/storage/binlog_reader.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#9116 [skip ci] Fix golint in indexcoord/priority_queue.go
  internal/indexcoord/priority_queue.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#9117 [skip ci]Fix golint in indexnode/task_scheduler.go
  internal/indexnode/task_scheduler.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed

#9118 [skip ci]Fix golint in indexnode/indexnode.go
  internal/indexnode/indexnode.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed

#9121 [skip ci]Fix golint in indexnode/client/client.go
  internal/distributed/indexnode/client/client.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed

#9123 [skip ci]Fix golint for startGrpcLoop in indexcoord/server.go
  internal/distributed/indexcoord/service.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#9125 [skip ci]Fix golint for initParams in indexcoord/prama_table.go
  internal/distributed/indexcoord/param_table.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#9126 [skip ci]Add youtube link in README.md
  README.md
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#9124 [skip ci]Add GetCollectionStatisticsRequest in chap05_proxy.md
  docs/developer_guides/chap05_proxy.md
Labels: kind/improvement, size/S, approved, lgtm, ci-passed

#9128 [skip ci] Add desc comments for NewMetricsCacheManager
  internal/util/metricsinfo/cache.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#9129 [skip ci] Add desc comments for GetUsedMemoryCount
  internal/util/metricsinfo/hardware_info.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#9130 [skip ci] Add desc comments for ProcessFuncParallel
  internal/util/funcutil/parallel.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#9131 [skip ci] fix fmt error in common.go
  internal/common/common.go
Labels: kind/improvement, size/XS, approved

#9140 [skip ci]Modify comment in param table
  internal/datacoord/param_table.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#9135 [skip ci] Add section number to binlog developer guide
  docs/developer_guides/chap08_binlog.md
Labels: kind/improvement, size/S, approved, lgtm, ci-passed

#9133 [skip ci] Add grafana panel description
  deployments/monitor/grafana/milvus-dashboard.json
Labels: kind/improvement, size/M, approved, lgtm, ci-passed

#9134 [skip ci] Refine developer guide section number
  docs/developer_guides/chap09_data_coord.md
Labels: kind/improvement, size/S, approved, lgtm, ci-passed

#9137 [skip ci] Fix DEVELOPMENT.md
  DEVELOPMENT.md
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#9138 [skip ci] Add description to coverage script
  scripts/run_go_codecov.sh
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#9141 [skip ci]Modify comment for SetState
  internal/datacoord/segment_info.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#9142 [skip ci]Modify comment for Init in param table
  internal/datacoord/param_table.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#9136 [skip ci] Fix CONTRIBUTING.md
  CONTRIBUTING.md
Labels: kind/improvement, approved, lgtm, ci-passed
