Repository milvus-io/milvus, pull requests merged in 2021-03, with the labels that each got.

#4758 fix minor memory leak when querying by IVF_SQ8H
  CHANGELOG.md
  core/src/index/knowhere/knowhere/index/vector_index/gpu/IndexIVFSQHybrid.cpp
  core/src/index/unittest/test_gpuresource.cpp
Labels: PR | automerge

#4768 [1.x] CI nightly open
  ci/jenkins/Jenkinsfile
Labels: PR | automerge, PR | skip-ci

#4767 fix memory leak
  CHANGELOG.md
  core/src/codecs/default/DefaultIdBloomFilterFormat.cpp
  core/src/context/HybridSearchContext.h
  core/src/db/DBImpl.cpp
  core/src/index/knowhere/knowhere/index/vector_index/impl/nsg/NSG.cpp
  core/src/index/thirdparty/faiss/utils/BinaryDistance.cpp
  core/src/search/Task.cpp
  core/src/search/Task.h
  core/src/search/TaskInst.cpp
  core/src/search/TaskInst.h
  core/src/server/Server.cpp
  core/src/utils/Status.cpp
Labels: PR | automerge

#4774 Update oatpp third-party link
  core/cmake/ThirdPartyPackages.cmake
Labels: PR | automerge, PR | improvement

#4784 [skip ci] Shards v1.0.0
  shards/README.md
  shards/README_CN.md
  shards/all_in_one/all_in_one.yml
  shards/all_in_one_with_mysql/all_in_one.yml
  shards/mishards/settings.py
  shards/requirements.txt
Labels: PR | automerge, PR | improvement, PR | skip-ci, mishards

#4866 Fix the crash when query for a large topk on GPU Flat
  CHANGELOG.md
  core/src/index/thirdparty/faiss/gpu/impl/IVFFlatScanLargeK.cu
  core/src/index/thirdparty/faiss/gpu/utils/StackDeviceMemory.cpp
  core/src/scheduler/selector/FaissFlatPass.cpp
Labels: PR | automerge
