Repository milvus-io/milvus, pull requests merged in 2022-08, with the labels that each got.

#18421 config from etcd
  internal/config/config.go
  internal/config/config_test.go
  internal/config/env_source.go
  internal/config/etcd_source.go
  internal/config/event.go
  internal/config/file_source.go
  internal/config/manager.go
  internal/config/manager_test.go
  internal/config/source.go
  internal/config/source_test.go
  internal/core/build.sh
  internal/core/run_clang_format.sh
  internal/core/ubuntu_build_deps.sh
  internal/kv/etcd/embed_etcd_config_test.go
  internal/kv/etcd/embed_etcd_kv.go
  internal/kv/etcd/embed_etcd_kv_test.go
  internal/kv/mem/mem_kv.go
  internal/util/paramtable/base_table.go
  internal/util/paramtable/base_table_test.go
  internal/util/paramtable/component_param.go
  internal/util/paramtable/component_param_test.go
  internal/util/paramtable/param_item.go
  internal/util/paramtable/service_param.go
  scripts/run_cpp_unittest.sh
  scripts/run_go_unittest.sh
Labels: size/XXL, approved, lgtm, ci-passed, dco-passed

#18353 [skip e2e]Add publish image for new ci cluster
  ci/jenkins/PublishImages.groovy
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#18463 [skip e2e]Change CI jobs to new CI cluster
  .github/mergify.yml
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#18476 Close Node/Segment detector when close ShardCluster
  internal/querynode/shard_cluster.go
  internal/querynode/shard_cluster_test.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#18165 upgrade Go 1.18 in go.mod
  .env
  .golangci.yml
  DEVELOPMENT.md
  Makefile
  README.md
  README_CN.md
  go.mod
  go.sum
  scripts/README.md
  tools/check/go.mod
  tools/check/go.sum
Labels: area/dependency, size/XL, approved, lgtm, ci-passed, dco-passed, area/compilation, manual-pass

#18473 Decrease cpu request
  ci/jenkins/PR.groovy
  ci/jenkins/pod/e2e.yaml
  tests/scripts/values/ci/pr.yaml
Labels: kind/improvement, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#18477 [test]Update python version in pytest image
  tests/docker/Dockerfile
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#18468 [test]Add recall test
  tests/python_client/.gitignore
  tests/python_client/assets/ann_hdf5/download.sh
  tests/python_client/deploy/scripts/first_recall_test.py
  tests/python_client/deploy/scripts/second_recall_test.py
  tests/python_client/requirements.txt
Labels: kind/improvement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#18451 Add heap for dmlChannels to get next channel
  internal/rootcoord/dml_channels.go
  internal/rootcoord/dml_channels_test.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#18467 Add reqeust id log for minio chunk manager
  internal/storage/minio_chunk_manager.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#18464 Remove invalid build parameters for OpenBLAS
  build/docker/openblas/centos7/Dockerfile
  build/docker/openblas/ubuntu18.04/Dockerfile
  build/rpm/setup-env.sh
  scripts/README.md
  scripts/install_deps_embd.sh
Labels: size/S, approved, lgtm, ci-passed, dco-passed

#18488 Release collection resources when all partition released
  internal/querynode/task.go
  internal/querynode/task_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#18484 Add search and collection cases when dim=1
  tests/python_client/common/common_type.py
  tests/python_client/testcases/test_collection.py
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#18482 Fix indexcheck division by zero bug
  internal/util/indexparamcheck/conf_adapter.go
  internal/util/indexparamcheck/conf_adapter_test.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#18494 Revert settings of Pulsar address and refine config code
  cmd/roles/roles.go
  internal/distributed/connection_manager_test.go
  internal/mq/msgstream/mq_kafka_msgstream_test.go
  internal/mq/msgstream/mq_msgstream_test.go
  internal/mq/msgstream/mqwrapper/kafka/kafka_client_test.go
  internal/mq/msgstream/mqwrapper/kafka/kafka_consumer_test.go
  internal/mq/msgstream/mqwrapper/kafka/kafka_producer_test.go
  internal/mq/msgstream/mqwrapper/pulsar/pulsar_client_test.go
  internal/mq/msgstream/mqwrapper/pulsar/pulsar_consumer_test.go
  internal/mq/msgstream/mqwrapper/pulsar/pulsar_producer_test.go
  internal/storage/minio_chunk_manager_test.go
  internal/util/dependency/factory.go
  internal/util/paramtable/base_table.go
  internal/util/paramtable/base_table_test.go
  internal/util/paramtable/service_param.go
  internal/util/paramtable/service_param_test.go
  internal/util/sessionutil/session_util_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#18426 Add ShowConfigurations to QueryNode
  internal/config/manager.go
  internal/distributed/querynode/client/client.go
  internal/distributed/querynode/client/client_test.go
  internal/distributed/querynode/service.go
  internal/distributed/querynode/service_test.go
  internal/proto/query_coord.proto
  internal/proto/querypb/query_coord.pb.go
  internal/proxy/query_node_mock_test.go
  internal/querycoord/mock_querynode_client_test.go
  internal/querynode/impl.go
  internal/querynode/impl_test.go
  internal/querynode/metrics_info.go
  internal/querynode/metrics_info_test.go
  internal/types/types.go
  internal/util/mock/grpc_querynode_client.go
  internal/util/mock/querynode_client.go
  internal/util/paramtable/base_table.go
  internal/util/typeutil/string_util.go
Labels: sig/testing, size/XL, approved, lgtm, area/test, ci-passed, area/internal-api, dco-passed

#18498 Merge FloatSearch() and BinarySearch() into SearchOnGrowing()
  internal/core/src/query/SearchOnGrowing.cpp
  internal/core/src/segcore/SegmentSealedImpl.cpp
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#18513 Use chunkManager rather than minio.Client in datanode garbage collection
  internal/datacoord/garbage_collector.go
  internal/datacoord/garbage_collector_test.go
  internal/datacoord/server.go
  internal/datacoord/server_test.go
  internal/indexcoord/garbage_collector.go
  internal/indexcoord/garbage_collector_test.go
  internal/indexcoord/index_coord_mock.go
  internal/storage/local_chunk_manager.go
  internal/storage/local_chunk_manager_test.go
  internal/storage/minio_chunk_manager.go
  internal/storage/minio_chunk_manager_test.go
  internal/storage/types.go
  internal/storage/vector_chunk_manager.go
  internal/util/importutil/import_wrapper_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#18520 Update docs for run-cpu-e2e
  COMMAND_HELP.md
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#18519 Use vchannel name in datanode subName
  internal/datacoord/channel_manager.go
  internal/datanode/flow_graph_dmstream_input_node.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#18366 Use mockServer to enable kafka UT
  internal/mq/msgstream/mq_kafka_msgstream_test.go
  internal/mq/msgstream/mq_msgstream_test.go
  internal/mq/msgstream/mqwrapper/kafka/kafka_client.go
  internal/mq/msgstream/mqwrapper/kafka/kafka_client_test.go
  internal/mq/msgstream/mqwrapper/kafka/kafka_consumer_test.go
  internal/mq/msgstream/mqwrapper/kafka/kafka_producer_test.go
  scripts/run_go_codecov.sh
  scripts/run_go_unittest.sh
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#18522 [skip e2e]Try to fix mac build & upgrade go 1.18
  .github/workflows/code-checker.yaml
  .github/workflows/mac.yaml
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#18472 add heaptrack dockerfile
  build/docker/heaptrack/Dockerfile
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#18525 [skip e2e] Add commit url for pull request body
  .github/workflows/publish-test-images.yaml
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#18492 [skip e2e]Update pod failure
  tests/python_client/chaos/chaos_objects/pod_failure/chaos_allcluster_pod_failure.yaml
  tests/python_client/chaos/chaos_objects/pod_failure/chaos_allstandalone_pod_failure.yaml
  tests/python_client/chaos/chaos_objects/pod_failure/chaos_datacoord_pod_failure.yaml
  tests/python_client/chaos/chaos_objects/pod_failure/chaos_etcd_pod_failure.yaml
  tests/python_client/chaos/chaos_objects/pod_failure/chaos_indexcoord_pod_failure.yaml
  tests/python_client/chaos/chaos_objects/pod_failure/chaos_kafka_pod_failure.yaml
  tests/python_client/chaos/chaos_objects/pod_failure/chaos_minio_pod_failure.yaml
  tests/python_client/chaos/chaos_objects/pod_failure/chaos_pulsar_pod_failure.yaml
  tests/python_client/chaos/chaos_objects/pod_failure/chaos_querycoord_pod_failure.yaml
  tests/python_client/chaos/chaos_objects/pod_failure/chaos_rootcoord_pod_failure.yaml
  tests/python_client/chaos/chaos_objects/pod_failure/chaos_standalone_pod_failure.yaml
  tests/python_client/chaos/chaos_objects/pod_failure/testcases.yaml
Labels: kind/improvement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#18527 Fix kafka ut fail randomly
  internal/mq/msgstream/mqwrapper/kafka/kafka_client_test.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#18497 Remove Load Delta Channel Request
  cmd/milvus/mck.go
  internal/distributed/querynode/client/client.go
  internal/distributed/querynode/client/client_test.go
  internal/distributed/querynode/service.go
  internal/distributed/querynode/service_test.go
  internal/proto/query_coord.proto
  internal/proto/querypb/query_coord.pb.go
  internal/proxy/query_node_mock_test.go
  internal/querycoord/cluster.go
  internal/querycoord/cluster_test.go
  internal/querycoord/mock_querynode_client_test.go
  internal/querycoord/mock_querynode_server_test.go
  internal/querycoord/querynode.go
  internal/querycoord/task.go
  internal/querycoord/task_scheduler.go
  internal/querycoord/task_scheduler_test.go
  internal/querycoord/task_test.go
  internal/querycoord/task_util.go
  internal/querycoord/util.go
  internal/querynode/impl.go
  internal/querynode/query_shard_service.go
  internal/querynode/segment_loader.go
  internal/querynode/shard_cluster.go
  internal/querynode/task.go
  internal/querynode/task_test.go
  internal/types/types.go
  internal/util/funcutil/parallel.go
  internal/util/mock/grpc_querynode_client.go
  internal/util/mock/querynode_client.go
Labels: size/XXL, approved, lgtm, ci-passed, area/internal-api, dco-passed, manual-pass

#18394 Remove Load Delta Channel Request
  cmd/milvus/mck.go
  internal/distributed/querynode/client/client.go
  internal/distributed/querynode/client/client_test.go
  internal/distributed/querynode/service.go
  internal/distributed/querynode/service_test.go
  internal/mq/msgstream/mq_msgstream.go
  internal/proto/query_coord.proto
  internal/proto/querypb/query_coord.pb.go
  internal/proxy/query_node_mock_test.go
  internal/querycoord/cluster.go
  internal/querycoord/cluster_test.go
  internal/querycoord/mock_querynode_client_test.go
  internal/querycoord/mock_querynode_server_test.go
  internal/querycoord/querynode.go
  internal/querycoord/task.go
  internal/querycoord/task_scheduler.go
  internal/querycoord/task_scheduler_test.go
  internal/querycoord/task_test.go
  internal/querycoord/task_util.go
  internal/querycoord/util.go
  internal/querynode/impl.go
  internal/querynode/query_shard_service.go
  internal/querynode/segment_loader.go
  internal/querynode/shard_cluster.go
  internal/querynode/task.go
  internal/querynode/task_test.go
  internal/types/types.go
  internal/util/funcutil/parallel.go
  internal/util/mock/grpc_querynode_client.go
  internal/util/mock/querynode_client.go
Labels: size/XXL, approved, lgtm, ci-passed, area/internal-api, dco-passed, manual-pass

#18528 Support Role-Based Access Control II
  internal/core/src/pb/common.pb.cc
  internal/core/src/pb/common.pb.h
  internal/proto/common.proto
  internal/proto/commonpb/common.pb.go
  internal/proto/milvus.proto
  internal/proto/milvuspb/milvus.pb.go
  internal/proxy/impl.go
  internal/proxy/meta_cache.go
  internal/proxy/privilege_interceptor.go
  internal/proxy/proxy_test.go
  internal/proxy/util.go
  internal/proxy/util_test.go
  internal/rootcoord/root_coord.go
  internal/util/constant.go
  internal/util/funcutil/func.go
  internal/util/funcutil/func_test.go
  internal/util/funcutil/policy.go
  internal/util/funcutil/policy_test.go
Labels: area/api, size/XXL, approved, lgtm, ci-passed, dco-passed

#18562 [skip e2e]Add recall test
  .github/workflows/deploy-test.yaml
  tests/python_client/assets/ann_hdf5/download.sh
  tests/python_client/deploy/scripts/first_recall_test.py
  tests/python_client/deploy/scripts/second_recall_test.py
Labels: kind/improvement, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#18545 refine index node
  internal/core/src/pb/common.pb.cc
  internal/core/src/pb/common.pb.h
  internal/distributed/indexnode/service.go
  internal/indexnode/chunk_mgr_factory.go
  internal/indexnode/chunkmgr_mock.go
  internal/indexnode/etcd_mock.go
  internal/indexnode/indexnode.go
  internal/indexnode/indexnode_component_mock.go
  internal/indexnode/indexnode_mock_test.go
  internal/indexnode/indexnode_service.go
  internal/indexnode/indexnode_service_test.go
  internal/indexnode/indexnode_test.go
  internal/indexnode/task.go
  internal/indexnode/task_scheduler.go
  internal/indexnode/task_scheduler_test.go
  internal/indexnode/task_test.go
  internal/indexnode/taskinfo_ops.go
  internal/proto/common.proto
  internal/proto/commonpb/common.pb.go
  internal/proto/index_node.proto
  internal/proto/indexnodepb/index_node.pb.go
  internal/types/types.go
  internal/util/logutil/logutil.go
  scripts/proto_gen_go.sh
Labels: size/XXL

#18566 Remove deprecated cacheSize param
  internal/querynode/task_test.go
  internal/util/paramtable/component_param.go
  internal/util/paramtable/component_param_test.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#18461 Add cgo worker pool for querynode
  internal/querynode/meta_replica.go
  internal/querynode/meta_replica_test.go
  internal/querynode/mock_test.go
  internal/querynode/query_node.go
  internal/querynode/query_node_test.go
  internal/querynode/segment.go
  internal/querynode/segment_loader.go
  internal/querynode/segment_loader_test.go
  internal/querynode/segment_test.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#18568 Close Node/Segment detector when close ShardCluster (#18476)
  internal/querynode/shard_cluster.go
  internal/querynode/shard_cluster_test.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#18542 Add cgo worker pool for querynode
  internal/querynode/meta_replica.go
  internal/querynode/meta_replica_test.go
  internal/querynode/mock_test.go
  internal/querynode/query_node.go
  internal/querynode/query_node_test.go
  internal/querynode/segment.go
  internal/querynode/segment_loader.go
  internal/querynode/segment_loader_test.go
  internal/querynode/segment_test.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#18569 Release collection resources when all partition released (#18488)
  internal/querynode/task.go
  internal/querynode/task_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#18570 support dynamic change log level through http
  internal/log/log.go
  internal/log/log_test.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#18540 Fix a potential nullptr issue with metric
  internal/datacoord/services.go
  internal/proxy/metrics_info.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#18547 Improve slow Etcd logs by specifying keys
  internal/kv/etcd/etcd_kv.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#18546 Refine catalog of partition & alias.
  internal/kv/mock_snapshot_kv.go
  internal/kv/mock_snapshot_kv_test.go
  internal/metastore/catalog.go
  internal/metastore/kv/kv_catalog.go
  internal/metastore/kv/kv_catalog_test.go
  internal/metastore/kv/rootcorod_constant.go
  internal/metastore/model/alias.go
  internal/metastore/model/collection.go
  internal/metastore/model/collection_test.go
  internal/metastore/model/partition.go
  internal/proto/etcd_meta.proto
  internal/proto/etcdpb/etcd_meta.pb.go
  internal/rootcoord/meta_table.go
  internal/rootcoord/meta_table_test.go
Labels: size/XXL, approved, lgtm, ci-passed, dco-passed

#18575 Update pymilvus version
  tests/python_client/base/collection_wrapper.py
  tests/python_client/base/partition_wrapper.py
  tests/python_client/requirements.txt
  tests/python_client/testcases/test_alias.py
  tests/python_client/testcases/test_collection.py
  tests/python_client/testcases/test_e2e.py
  tests/python_client/testcases/test_index.py
Labels: sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#18583 Fix Parse binlog path failure
  internal/datacoord/garbage_collector.go
  internal/storage/binlog_util.go
  internal/storage/binlog_util_test.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#18586 [test]Update the way of flush
  tests/python_client/chaos/scripts/hello_milvus.py
  tests/python_client/chaos/scripts/verify_all_collections.py
  tests/python_client/deploy/scripts/first_recall_test.py
  tests/python_client/deploy/scripts/utils.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#18587 [skip e2e]Update etcd version
  .github/workflows/deploy-test.yaml
  tests/python_client/chaos/cluster-values.yaml
  tests/python_client/chaos/standalone-values.yaml
  tests/python_client/deploy/cluster-values-second.yaml
  tests/python_client/deploy/cluster-values.yaml
  tests/python_client/deploy/standalone-values.yaml
Labels: kind/improvement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#18582 Add a specific `KeyNotExistError` err for the metastore `load` interface
  internal/common/error.go
  internal/common/error_test.go
  internal/kv/etcd/embed_etcd_kv.go
  internal/kv/etcd/etcd_kv.go
  internal/kv/mem/mem_kv.go
  internal/metastore/kv/kv_catalog.go
  internal/proxy/proxy_test.go
  internal/rootcoord/meta_table_test.go
  internal/rootcoord/root_coord.go
  internal/util/funcutil/func.go
  internal/util/funcutil/func_test.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#18590 Fix querycoord handle offline node with wrong nodeID
  internal/querycoord/query_coord.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#17729 Abort execute timeout search/query
  internal/querynode/task_scheduler.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#18589 Refine output duplicate log frequently in indexcoord
  internal/datacoord/services.go
  internal/indexcoord/index_builder.go
  internal/indexcoord/meta_table.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#18325 Fix pk2offset occupy too much memory
  internal/core/src/common/Types.h
  internal/core/src/segcore/InsertRecord.h
Labels: size/S, approved, lgtm, ci-passed, dco-passed

#18559 Add script to auto clang format
  internal/core/run_clang_format.sh
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#18541 Support meta storing on database (#17236)
  cmd/components/root_coord.go
  codecov.yml
  configs/milvus.yaml
  go.mod
  go.sum
  internal/metastore/catalog.go
  internal/metastore/db/dao/collection.go
  internal/metastore/db/dao/collection_alias.go
  internal/metastore/db/dao/collection_alias_test.go
  internal/metastore/db/dao/collection_channel.go
  internal/metastore/db/dao/collection_channel_test.go
  internal/metastore/db/dao/collection_test.go
  internal/metastore/db/dao/common.go
  internal/metastore/db/dao/field.go
  internal/metastore/db/dao/field_test.go
  internal/metastore/db/dao/index.go
  internal/metastore/db/dao/index_test.go
  internal/metastore/db/dao/partition.go
  internal/metastore/db/dao/partition_test.go
  internal/metastore/db/dao/segment_index.go
  internal/metastore/db/dao/segment_index_test.go
  internal/metastore/db/dao/user.go
  internal/metastore/db/dao/user_test.go
  internal/metastore/db/dbcore/core.go
  internal/metastore/db/dbmodel/collection.go
  internal/metastore/db/dbmodel/collection_alias.go
  internal/metastore/db/dbmodel/collection_channel.go
  internal/metastore/db/dbmodel/common.go
  internal/metastore/db/dbmodel/field.go
  internal/metastore/db/dbmodel/index.go
  internal/metastore/db/dbmodel/mocks/ICollAliasDb.go
  internal/metastore/db/dbmodel/mocks/ICollChannelDb.go
  internal/metastore/db/dbmodel/mocks/ICollectionDb.go
  internal/metastore/db/dbmodel/mocks/IFieldDb.go
  internal/metastore/db/dbmodel/mocks/IIndexDb.go
  internal/metastore/db/dbmodel/mocks/IMetaDomain.go
  internal/metastore/db/dbmodel/mocks/IPartitionDb.go
  internal/metastore/db/dbmodel/mocks/ISegmentIndexDb.go
  internal/metastore/db/dbmodel/mocks/IUserDb.go
  internal/metastore/db/dbmodel/partition.go
  internal/metastore/db/dbmodel/segment_index.go
  internal/metastore/db/dbmodel/user.go
  internal/metastore/db/table_catalog.go
  internal/metastore/db/table_catalog_test.go
  internal/metastore/kv/kv_catalog.go
  internal/metastore/kv/rootcoord_constant.go
  internal/metastore/table/table_catalog.go
  internal/rootcoord/meta_table.go
  internal/rootcoord/meta_table_test.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
  internal/rootcoord/task.go
  internal/rootcoord/util.go
  internal/util/constant.go
  internal/util/contextutil/context_util.go
  internal/util/funcutil/func.go
  internal/util/paramtable/component_param.go
  internal/util/paramtable/service_param.go
  scripts/sql/meta.sql
Labels: area/dependency, size/XXL, approved, lgtm, ci-passed, dco-passed

#18347 Update binlog event format
  docs/developer_guides/chap08_binlog.md
  internal/storage/data_codec.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#18603 Exposes the REST-API port on the standalone docker-compose file
  deployments/docker/standalone/docker-compose.yml
Labels: size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#18612 Set LD_PRELOAD env for jemalloc
  build/docker/milvus/centos7/Dockerfile
  build/docker/milvus/ubuntu18.04/Dockerfile
  scripts/start_cluster.sh
  scripts/start_standalone.sh
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#18615 fix wrong operation model for user (#18614)
  internal/metastore/db/dao/user.go
  internal/metastore/db/dao/user_test.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#18611 Disable ut about kafka temporarily
  scripts/run_go_codecov.sh
  scripts/run_go_unittest.sh
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#18616 Expose REST-API port in docker-compose for cluster setup
  deployments/docker/cluster/docker-compose-apple-silicon.yml
  deployments/docker/cluster/docker-compose.yml
Labels: size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#18627 Update pymilvus version
  tests/docker/Dockerfile
  tests/python_client/requirements.txt
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed, manual-pass

#18633 Bump milvus version to v2.1.1
  deployments/binary/README.md
  deployments/docker/cluster/docker-compose-apple-silicon.yml
  deployments/docker/cluster/docker-compose.yml
  deployments/docker/standalone/docker-compose.yml
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#18629 Ignore pull deps when build
  build/builder.sh
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#18491 [skip e2e] Add ansible deployment support for centos/redhat/debain/ubuntu
  deployments/docker/cluster-distributed-deployment/ansible.cfg
  deployments/docker/cluster-distributed-deployment/deploy-docker.yml
  deployments/docker/cluster-distributed-deployment/inventory.ini
  deployments/docker/cluster-distributed-deployment/roles/configure-hosts-file/tasks/main.yml
  deployments/docker/cluster-distributed-deployment/roles/deploy-etcd/tasks/main.yml
  deployments/docker/cluster-distributed-deployment/roles/deploy-minio/tasks/main.yml
  deployments/docker/cluster-distributed-deployment/roles/deploy-pulsar/tasks/main.yml
  deployments/docker/cluster-distributed-deployment/roles/docker-installation/tasks/main.yml
  deployments/docker/cluster-distributed-deployment/roles/install-modules/tasks/main.yml
Labels: size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#18650 [skip e2e]Update milvus version in deploy test
  .github/workflows/deploy-test.yaml
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#18657 Fix DN flowgraph delete buffer logs
  internal/datacoord/segment_reference_manager.go
  internal/datanode/flow_graph_delete_node.go
  internal/datanode/flow_graph_delete_node_test.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#18647 Handle some apis about the default role
  internal/metastore/kv/kv_catalog.go
  internal/proxy/impl.go
  internal/proxy/privilege_interceptor.go
  internal/proxy/privilege_interceptor_test.go
  internal/proxy/proxy_test.go
  internal/proxy/util.go
  internal/proxy/util_test.go
  internal/rootcoord/meta_table_test.go
  internal/rootcoord/root_coord.go
  internal/util/constant.go
  internal/util/funcutil/policy.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#18584 Fix Parse binlog path failure
  internal/datacoord/garbage_collector.go
  internal/storage/binlog_util.go
  internal/storage/binlog_util_test.go
Labels: size/M, approved, lgtm, dco-passed, manual-pass

#18661 [test]Update testcase for deploy test
  tests/python_client/deploy/common.py
  tests/python_client/deploy/testcases/test_action_first_deployment.py
  tests/python_client/deploy/testcases/test_action_second_deployment.py
  tests/python_client/deploy/testcases/test_get_all_collections.py
Labels: kind/improvement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#18634 Rename real_topK_per_nq_ to topks_per_nq_prefix_sum_ in SearchResult
  internal/core/src/common/QueryResult.h
  internal/core/src/segcore/Reduce.cpp
  internal/core/unittest/test_c_api.cpp
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#18649 Add test cases about supporting bool as output fields for query and search
  tests/python_client/requirements.txt
  tests/python_client/testcases/test_query.py
  tests/python_client/testcases/test_search.py
Labels: kind/improvement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#18662 Add log for NoReplicaAvailable Error in QueryCoord.GetShardLeaders
  internal/querycoord/impl.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#18658 Fix DN flowgraph delete buffer logs
  internal/datacoord/segment_reference_manager.go
  internal/datanode/flow_graph_delete_node.go
  internal/datanode/flow_graph_delete_node_test.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#18593 Test connection with user and password
  tests/python_client/base/utility_wrapper.py
  tests/python_client/common/common_type.py
  tests/python_client/testcases/test_connection.py
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#18676 [skip e2e] Add mysql script
  tests/scripts/values/mysql.yaml
Labels: kind/improvement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#18673 Dedup output fields for task query
  internal/proxy/task_query.go
  internal/proxy/task_query_test.go
  tests/python_client/testcases/test_query.py
Labels: kind/bug, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#18687 Modify name length and delete unique constraint for index (#18685)
  scripts/sql/meta.sql
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#18682 [test]Update chaos test for milvus deployed by operator
  tests/python_client/chaos/conftest.py
  tests/python_client/chaos/test_chaos_apply.py
  tests/python_client/utils/util_common.py
  tests/python_client/utils/util_k8s.py
Labels: kind/improvement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#18690 Fix DataType::bool cast to double
  internal/core/src/segcore/Utils.cpp
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#18677 Fix flush panic after compaction
  internal/datanode/flow_graph_delete_node.go
  internal/datanode/flow_graph_delete_node_test.go
  internal/datanode/segment_replica.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#18694 [test]Fix chaos test
  tests/python_client/chaos/checker.py
  tests/python_client/chaos/test_chaos_apply.py
  tests/python_client/chaos/testcases/test_concurrent_operation.py
  tests/python_client/conftest.py
Labels: kind/improvement, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#18678 Fix flush panic after compaction
  internal/datanode/flow_graph_delete_node.go
  internal/datanode/flow_graph_delete_node_test.go
  internal/datanode/segment_replica.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#18675 Fix segcore benchmark
  internal/core/unittest/bench/bench_search.cpp
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#18683 [Cherry-pick]Dedup output fields for task query (#18673)
  internal/proxy/task_query.go
  internal/proxy/task_query_test.go
  tests/python_client/testcases/test_query.py
Labels: kind/bug, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, manual-pass

#18698 [skip e2e] Update mysql yaml
  tests/scripts/values/mysql.yaml
Labels: kind/improvement, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#18680 [test] Add case to test search and index about handoff
  tests/python_client/testcases/test_utility.py
Labels: kind/improvement, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#18693 [CherryPick] Fix DataType::bool cast to double (#18690)
  internal/core/src/segcore/Utils.cpp
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#18679 [test] Add case to test search and index about handoff
  tests/python_client/testcases/test_utility.py
Labels: kind/improvement, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed, manual-pass

#18702 Simplify Dml-DeltaChannel mapping logic
  internal/rootcoord/dml_channels.go
  internal/rootcoord/dml_channels_test.go
  internal/rootcoord/root_coord_test.go
  internal/rootcoord/task.go
  internal/rootcoord/timeticksync.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#18708 [Cherry-pick] Simplify Dml-DeltaChannel mapping logic
  internal/rootcoord/dml_channels.go
  internal/rootcoord/dml_channels_test.go
  internal/rootcoord/root_coord_test.go
  internal/rootcoord/task.go
  internal/rootcoord/timeticksync.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#18712 [skip e2e]Add mixcoord component for chaos test
  tests/python_client/chaos/chaos_objects/pod_failure/chaos_mixcoord_pod_failure.yaml
  tests/python_client/chaos/chaos_objects/pod_kill/chaos_mixcoord_pod_kill.yaml
Labels: kind/improvement, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#18710 Transfer some cases from test_connection to test_utility
  tests/python_client/testcases/test_connection.py
  tests/python_client/testcases/test_utility.py
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#18700 Fix RHNSWPQ pqm divide by zero
  internal/util/indexparamcheck/conf_adapter.go
  internal/util/indexparamcheck/conf_adapter_test.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#18688 Fix typo in error message
  internal/proxy/task_search.go
  internal/proxy/task_search_test.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#18701 Fix RHNSWPQ pqm divide by zero
  internal/util/indexparamcheck/conf_adapter.go
  internal/util/indexparamcheck/conf_adapter_test.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#18725 Fix query cluster metrics
  internal/querycoord/cluster.go
  internal/querycoord/metrics_info.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed

#18715 [test]Add test case for verification
  tests/python_client/chaos/testcases/test_all_collections_after_chaos.py
  tests/python_client/chaos/testcases/test_data_persistence.py
  tests/python_client/chaos/testcases/test_get_collections.py
  tests/python_client/utils/util_common.py
Labels: kind/improvement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#18718 [test]Reduce test cases for deploy test
  tests/python_client/deploy/testcases/test_action_first_deployment.py
  tests/python_client/deploy/testcases/test_get_all_collections.py
Labels: kind/improvement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#18727 Fix query cluster metrics (#18725)
  internal/querycoord/cluster.go
  internal/querycoord/metrics_info.go
Labels: size/S, approved, lgtm, dco-passed

#18714 Drop empty sealed segment (#17708)
  internal/datacoord/segment_manager.go
  internal/datacoord/segment_manager_test.go
  internal/datacoord/services.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#18735 Enable test cases after code fix
  tests/python_client/testcases/test_query.py
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#18730 Fix password verification miss cache
  internal/proxy/authentication_interceptor.go
  internal/proxy/impl.go
  internal/proxy/meta_cache.go
  internal/proxy/proxy_test.go
  internal/proxy/rootcoord_mock_test.go
  internal/proxy/util.go
  internal/proxy/util_test.go
  internal/util/crypto/crypto.go
  internal/util/crypto/crypto_test.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#18736 [Cherry Pick] Fix # of rows of recovering segment
  internal/datacoord/segment_info.go
  internal/datacoord/server.go
  internal/datacoord/session_manager.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#18733 Fix # of rows of recovering segment
  internal/datacoord/segment_info.go
  internal/datacoord/server.go
  internal/datacoord/session_manager.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#18290 Unified catalog interface for segment (#18289)
  internal/datacoord/compaction_test.go
  internal/datacoord/handler.go
  internal/datacoord/meta.go
  internal/datacoord/meta_test.go
  internal/datacoord/mock_test.go
  internal/datacoord/segment_manager_test.go
  internal/datacoord/server.go
  internal/datacoord/server_test.go
  internal/metastore/catalog.go
  internal/metastore/db/rootcoord/table_catalog.go
  internal/metastore/db/rootcoord/table_catalog_test.go
  internal/metastore/kv/datacoord/constant.go
  internal/metastore/kv/datacoord/kv_catalog.go
  internal/metastore/kv/datacoord/kv_catalog_test.go
  internal/metastore/kv/rootcoord/kv_catalog.go
  internal/metastore/kv/rootcoord/kv_catalog_test.go
  internal/metastore/kv/rootcoord/meta_snapshot.go
  internal/metastore/kv/rootcoord/meta_snapshot_test.go
  internal/metastore/kv/rootcoord/rootcoord_constant.go
  internal/metastore/kv/rootcoord/suffix_snapshot.go
  internal/metastore/kv/rootcoord/suffix_snapshot_test.go
  internal/proto/data_coord.proto
  internal/rootcoord/meta_table.go
  internal/rootcoord/meta_table_test.go
  internal/rootcoord/proxy_manager.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
  internal/storage/binlog_writer.go
  internal/util/typeutil/map.go
  internal/util/typeutil/map_test.go
Labels: area/dependency, size/XXL, approved, lgtm, ci-passed, area/internal-api, dco-passed

#18732 [cherry pick]Fix password verification cache missed
  internal/proxy/authentication_interceptor.go
  internal/proxy/impl.go
  internal/proxy/meta_cache.go
  internal/proxy/proxy_test.go
  internal/proxy/rootcoord_mock_test.go
  internal/proxy/util.go
  internal/proxy/util_test.go
  internal/util/crypto/crypto.go
  internal/util/crypto/crypto_test.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#18717 Add some cases of expression when search and query
  tests/python_client/common/common_func.py
Labels: sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#18737 Update pymilvus version
  tests/python_client/requirements.txt
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#18740 Update pymilvus version
  tests/python_client/requirements.txt
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed, manual-pass

#17899 support configurable sasl mechanisms for kafka
  configs/milvus.yaml
  internal/mq/msgstream/mqwrapper/kafka/kafka_client.go
  internal/util/paramtable/service_param.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#18744 Watch channels with start positions
  internal/datacoord/channel_manager.go
  internal/datacoord/channel_manager_test.go
  internal/datacoord/channel_store_test.go
  internal/datacoord/cluster_test.go
  internal/datacoord/handler.go
  internal/datacoord/mock_test.go
  internal/datacoord/policy_test.go
  internal/datacoord/server_test.go
  internal/datacoord/services.go
  internal/distributed/rootcoord/service_test.go
  internal/proto/data_coord.proto
  internal/proto/datapb/data_coord.pb.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
  internal/rootcoord/task.go
Labels: kind/improvement, size/XL, approved, lgtm, ci-passed, dco-passed

#18746 Upgrade to knowhere-v1.2.0
  internal/core/src/indexbuilder/VecIndexCreator.cpp
  internal/core/src/indexbuilder/VecIndexCreator.h
  internal/core/src/query/Plan.h
  internal/core/src/query/SearchBruteForce.cpp
  internal/core/thirdparty/knowhere/CMakeLists.txt
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed, area/compilation

#18704 Implement the mysql metastore of the rbac
  configs/milvus.yaml
  internal/metastore/catalog.go
  internal/metastore/db/dao/collection_test.go
  internal/metastore/db/dao/common.go
  internal/metastore/db/dao/grant.go
  internal/metastore/db/dao/grant_test.go
  internal/metastore/db/dao/role.go
  internal/metastore/db/dao/role_test.go
  internal/metastore/db/dao/user.go
  internal/metastore/db/dao/user_role.go
  internal/metastore/db/dao/user_role_test.go
  internal/metastore/db/dao/user_test.go
  internal/metastore/db/dbmodel/base_model.go
  internal/metastore/db/dbmodel/common.go
  internal/metastore/db/dbmodel/grant.go
  internal/metastore/db/dbmodel/mocks/IGrantDb.go
  internal/metastore/db/dbmodel/mocks/IMetaDomain.go
  internal/metastore/db/dbmodel/mocks/IRoleDb.go
  internal/metastore/db/dbmodel/mocks/IUserDb.go
  internal/metastore/db/dbmodel/mocks/IUserRoleDb.go
  internal/metastore/db/dbmodel/role.go
  internal/metastore/db/dbmodel/user.go
  internal/metastore/db/dbmodel/user_role.go
  internal/metastore/db/rootcoord/table_catalog.go
  internal/metastore/db/rootcoord/table_catalog_test.go
  internal/metastore/kv/rootcoord/kv_catalog.go
  internal/proxy/authentication_interceptor.go
  internal/rootcoord/meta_table.go
  internal/rootcoord/meta_table_test.go
  internal/rootcoord/root_coord.go
  scripts/run_go_unittest.sh
  scripts/sql/meta.sql
Labels: size/XXL, approved, lgtm, ci-passed, dco-passed, manual-pass

#18692 tracing enhancement
  cmd/roles/roles.go
  internal/distributed/datacoord/service.go
  internal/distributed/datanode/service.go
  internal/distributed/indexcoord/service.go
  internal/distributed/indexnode/service.go
  internal/distributed/proxy/service.go
  internal/distributed/querycoord/service.go
  internal/distributed/querynode/service.go
  internal/distributed/rootcoord/service.go
  internal/log/global.go
  internal/log/log.go
  internal/log/log_test.go
  internal/log/meta_logger.go
  internal/log/meta_logger_test.go
  internal/log/meta_ops.go
  internal/log/mlogger.go
  internal/log/mlogger_test.go
  internal/log/zap_log_test.go
  internal/metastore/model/collection_test.go
  internal/metastore/model/index_test.go
  internal/metastore/model/segment_test.go
  internal/proxy/impl.go
  internal/proxy/meta_cache_test.go
  internal/proxy/task_policies.go
  internal/proxy/task_query.go
  internal/proxy/task_search.go
  internal/proxy/task_search_test.go
  internal/querycoord/impl.go
  internal/querynode/benchmark_test.go
  internal/querynode/impl.go
  internal/querynode/query_shard_test.go
  internal/querynode/result.go
  internal/querynode/retrieve.go
  internal/querynode/retrieve_test.go
  internal/querynode/search.go
  internal/querynode/search_test.go
  internal/querynode/statistic_test.go
  internal/querynode/statistics.go
  internal/querynode/task_query.go
  internal/querynode/task_search.go
  internal/querynode/task_statistics.go
  internal/querynode/validate.go
  internal/querynode/validate_test.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/task.go
  internal/util/logutil/grpc_interceptor.go
  internal/util/logutil/grpc_interceptor_test.go
  internal/util/logutil/logutil.go
  internal/util/timerecord/time_recorder.go
Labels: size/XXL, approved, lgtm, ci-passed, dco-passed

#18773 release manager Rlock
  internal/config/manager.go
Labels: kind/enhancement, kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#18618 [skip e2e] add Go heap in use pannel for milvus dashboard
  deployments/monitor/grafana/milvus-dashboard.json
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#18750 remove redundant slashes
  internal/util/paramtable/base_table.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#18769 Fix func checkIfLoaded in proxy
  internal/proxy/task_search.go
  internal/proxy/task_search_test.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#18660 remove compaction timeout checker in datacoord
  go.mod
  go.sum
  internal/datacoord/compaction.go
  internal/datacoord/compaction_test.go
  internal/datacoord/compaction_trigger_test.go
  internal/datacoord/mock_test.go
  internal/datacoord/server_test.go
  internal/datacoord/services.go
  internal/datacoord/session_manager.go
  internal/datanode/compaction_executor.go
  internal/datanode/compaction_executor_test.go
  internal/datanode/compactor.go
  internal/datanode/compactor_test.go
  internal/datanode/data_node.go
  internal/datanode/data_node_test.go
  internal/distributed/datacoord/client/client.go
  internal/distributed/datacoord/client/client_test.go
  internal/distributed/datacoord/service.go
  internal/distributed/datacoord/service_test.go
  internal/distributed/datanode/client/client.go
  internal/distributed/datanode/client/client_test.go
  internal/distributed/datanode/service.go
  internal/distributed/datanode/service_test.go
  internal/proto/common.proto
  internal/proto/data_coord.proto
  internal/proto/datapb/data_coord.pb.go
  internal/proto/milvus.proto
  internal/proto/milvuspb/milvus.pb.go
  internal/types/types.go
  internal/util/mock/grpc_datanode_client.go
  internal/util/paramtable/component_param.go
  tests/python_client/testcases/test_compaction.py
Labels: area/dependency, sig/testing, area/api, size/XXL, approved, lgtm, area/test, ci-passed, dco-passed

#18783 fix load segment hangs
  internal/mq/msgstream/mqwrapper/id.go
  internal/mq/msgstream/mqwrapper/kafka/kafka_id.go
  internal/mq/msgstream/mqwrapper/kafka/kafka_id_test.go
  internal/mq/msgstream/mqwrapper/pulsar/pulsar_id.go
  internal/mq/msgstream/mqwrapper/pulsar/pulsar_id_test.go
  internal/mq/msgstream/mqwrapper/rmq/rmq_id.go
  internal/mq/msgstream/mqwrapper/rmq/rmq_id_test.go
  internal/querynode/segment_loader.go
  internal/querynode/segment_loader_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#18770 fix load segment hangs
  internal/mq/msgstream/mqwrapper/id.go
  internal/mq/msgstream/mqwrapper/kafka/kafka_id.go
  internal/mq/msgstream/mqwrapper/kafka/kafka_id_test.go
  internal/mq/msgstream/mqwrapper/pulsar/pulsar_id.go
  internal/mq/msgstream/mqwrapper/pulsar/pulsar_id_test.go
  internal/mq/msgstream/mqwrapper/rmq/rmq_id.go
  internal/mq/msgstream/mqwrapper/rmq/rmq_id_test.go
  internal/querynode/segment_loader.go
  internal/querynode/segment_loader_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#18789 Rocksmq message ID compare fail with LessOrEqualThan method
  internal/mq/msgstream/mqwrapper/rmq/rmq_client_test.go
  internal/mq/msgstream/mqwrapper/rmq/rmq_id.go
  internal/mq/msgstream/mqwrapper/rmq/rmq_id_test.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed

#18790 Fix watchDmChannel may be out-of-date after compaction issue and add …
  internal/datacoord/services.go
  internal/querycoord/global_meta_broker.go
  internal/querycoord/global_meta_broker_test.go
  internal/querycoord/mock_3rd_component_test.go
  internal/querycoord/task.go
  internal/querycoord/task_scheduler.go
  internal/querycoord/task_util.go
  internal/querycoord/task_util_test.go
  internal/querynode/task.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#18681 Fix watchDmChannel may be out-of-date after compaction issue
  internal/datacoord/services.go
  internal/querycoord/global_meta_broker.go
  internal/querycoord/global_meta_broker_test.go
  internal/querycoord/mock_3rd_component_test.go
  internal/querycoord/task.go
  internal/querycoord/task_scheduler.go
  internal/querycoord/task_util.go
  internal/querycoord/task_util_test.go
  internal/querynode/task.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#18695 fix insert meets vChannels reuse pChannel
  internal/datanode/flow_graph_dd_node.go
  internal/datanode/flow_graph_dd_node_test.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#18784 fix insert meets vChannels reuse pChannel
  internal/datanode/flow_graph_dd_node.go
  internal/datanode/flow_graph_dd_node_test.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#18795 refactor compaction concurency logic
  go.mod
  go.sum
  internal/datacoord/compaction.go
  internal/datacoord/compaction_test.go
  internal/datacoord/compaction_trigger_test.go
  internal/datacoord/mock_test.go
  internal/datacoord/server_test.go
  internal/datacoord/services.go
  internal/datacoord/session_manager.go
  internal/datanode/compaction_executor.go
  internal/datanode/compaction_executor_test.go
  internal/datanode/compactor.go
  internal/datanode/compactor_test.go
  internal/datanode/data_node.go
  internal/datanode/data_node_test.go
  internal/distributed/datacoord/client/client.go
  internal/distributed/datacoord/client/client_test.go
  internal/distributed/datacoord/service.go
  internal/distributed/datacoord/service_test.go
  internal/distributed/datanode/client/client.go
  internal/distributed/datanode/client/client_test.go
  internal/distributed/datanode/service.go
  internal/distributed/datanode/service_test.go
  internal/proto/common.proto
  internal/proto/data_coord.proto
  internal/proto/datapb/data_coord.pb.go
  internal/proto/milvus.proto
  internal/proto/milvuspb/milvus.pb.go
  internal/types/types.go
  internal/util/mock/grpc_datanode_client.go
  internal/util/paramtable/component_param.go
  tests/python_client/testcases/test_compaction.py
Labels: area/dependency, sig/testing, area/api, size/XXL, approved, lgtm, area/test, ci-passed, dco-passed, manual-pass

#18792 Support concurrent situations for the metastore
  internal/rootcoord/meta_table.go
  internal/rootcoord/meta_table_test.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#18796 [Cherry-pick] Add semver in session
  go.mod
  go.sum
  internal/common/version.go
  internal/util/sessionutil/session_util.go
  internal/util/sessionutil/session_util_test.go
Labels: area/dependency, kind/improvement, size/XL, approved, lgtm, ci-passed, dco-passed, manual-pass

#18786 Separate create & update user in mysql (#18785)
  internal/metastore/catalog.go
  internal/metastore/db/dao/user.go
  internal/metastore/db/dao/user_test.go
  internal/metastore/db/dbmodel/mocks/IUserDb.go
  internal/metastore/db/dbmodel/user.go
  internal/metastore/db/rootcoord/table_catalog.go
  internal/metastore/db/rootcoord/table_catalog_test.go
  internal/metastore/kv/rootcoord/kv_catalog.go
  internal/rootcoord/meta_table.go
  internal/rootcoord/meta_table_test.go
  internal/rootcoord/root_coord.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#18749 change retention time to 1 day
  configs/milvus.yaml
  internal/util/paramtable/component_param.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#18699 Adaptation for latest MinGW64
  .github/workflows/code-checker.yaml
  internal/core/CMakeLists.txt
  scripts/install_deps_msys.sh
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed, area/compilation

#18742 add user special kafka client config
  configs/milvus.yaml
  internal/config/manager.go
  internal/mq/msgstream/mq_kafka_msgstream_test.go
  internal/mq/msgstream/mqwrapper/kafka/kafka_client.go
  internal/mq/msgstream/mqwrapper/kafka/kafka_client_test.go
  internal/util/paramtable/base_table.go
  internal/util/paramtable/base_table_test.go
  internal/util/paramtable/component_param_test.go
  internal/util/paramtable/service_param.go
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#18823 Add zstd lib in docker images
  build/docker/builder/cpu/centos7/Dockerfile
  build/docker/builder/cpu/ubuntu18.04/Dockerfile
  build/docker/milvus/centos7/Dockerfile
  build/docker/milvus/ubuntu18.04/Dockerfile
  scripts/install_deps.sh
  scripts/install_deps_embd.sh
  scripts/install_deps_msys.sh
Labels: size/S, approved, lgtm, ci-passed, dco-passed

#18827 Optimize API vector_search parameter in segcore
  internal/core/src/query/SearchOnGrowing.cpp
  internal/core/src/query/SearchOnGrowing.h
  internal/core/src/query/SearchOnSealed.cpp
  internal/core/src/query/SearchOnSealed.h
  internal/core/src/query/visitors/ExecPlanNodeVisitor.cpp
  internal/core/src/segcore/SegmentGrowingImpl.cpp
  internal/core/src/segcore/SegmentGrowingImpl.h
  internal/core/src/segcore/SegmentInterface.h
  internal/core/src/segcore/SegmentSealedImpl.cpp
  internal/core/src/segcore/SegmentSealedImpl.h
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#18779 Refine save dropped segments into kv metastore
  internal/datacoord/meta.go
  internal/metastore/catalog.go
  internal/metastore/kv/datacoord/constant.go
  internal/metastore/kv/datacoord/kv_catalog.go
  internal/metastore/kv/datacoord/kv_catalog_test.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#18830 Add new API for searching on sealed segment without index
  internal/core/src/query/SearchOnSealed.cpp
  internal/core/src/query/SearchOnSealed.h
  internal/core/src/segcore/SegmentGrowingImpl.cpp
  internal/core/src/segcore/SegmentSealedImpl.cpp
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#18801 fix restart querycoord blocking issue
  internal/querycoord/task_scheduler.go
  internal/querycoord/task_scheduler_test.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#18808 Unify rootPath in configs and ChunkManager
  internal/common/common.go
  internal/datanode/binlog_io.go
  internal/datanode/binlog_io_test.go
  internal/datanode/data_node.go
  internal/datanode/flow_graph_delete_node_test.go
  internal/datanode/flush_manager.go
  internal/indexcoord/garbage_collector.go
  internal/indexcoord/index_builder.go
  internal/indexcoord/index_coord_mock.go
  internal/indexnode/chunkmgr_mock.go
  internal/storage/local_chunk_manager.go
  internal/storage/local_chunk_manager_test.go
  internal/storage/minio_chunk_manager.go
  internal/storage/minio_chunk_manager_test.go
  internal/storage/types.go
  internal/storage/vector_chunk_manager.go
  internal/storage/vector_chunk_manager_test.go
  internal/util/importutil/import_wrapper_test.go
  internal/util/paramtable/component_param.go
  internal/util/paramtable/component_param_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#18814 Fix load segment hangs forever
  internal/querynode/segment_loader.go
  internal/querynode/segment_loader_test.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#18832 Remove redundant code
  internal/core/src/query/SearchOnSealed.cpp
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#18834 Decrease cpu request to improve milvus ci concurrency
  ci/jenkins/PR.groovy
  tests/scripts/values/ci/pr.yaml
Labels: kind/improvement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#18839 Change CI to use ubuntu 20.04
  .env
  .github/mergify.yml
  .github/workflows/code-checker.yaml
  .github/workflows/main.yaml
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#18787 add rbac test case
  tests/python_client/base/utility_wrapper.py
  tests/python_client/check/func_check.py
  tests/python_client/common/common_func.py
  tests/python_client/common/common_type.py
  tests/python_client/testcases/test_utility.py
Labels: kind/improvement, approved, lgtm, ci-passed, dco-passed

#18809 Update pymilvus version
  tests/python_client/requirements.txt
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#18829 fix GetCompactionState hang
  internal/datacoord/compaction.go
  internal/datacoord/compaction_test.go
  internal/datacoord/compaction_trigger.go
  internal/datacoord/compaction_trigger_test.go
  internal/datacoord/services.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#18854 [skip e2e]Add deps to fix pkg-config error
  build/docker/builder/cpu/ubuntu20.04/Dockerfile
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#18850 fix GetCompactionState hang
  internal/datacoord/compaction.go
  internal/datacoord/compaction_test.go
  internal/datacoord/compaction_trigger.go
  internal/datacoord/compaction_trigger_test.go
  internal/datacoord/services.go
  internal/querycoord/task_util.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#18851 Change minio to standalone for ci to save resource
  tests/scripts/install_milvus.sh
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#18848 Add unit test for case of stream closed
  internal/querynode/segment_loader.go
  internal/querynode/segment_loader_test.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#18817 Improve the storage method of the grant info in the metastore
  internal/metastore/catalog.go
  internal/metastore/db/dao/collection_test.go
  internal/metastore/db/dao/common.go
  internal/metastore/db/dao/gran_id.go
  internal/metastore/db/dao/gran_id_test.go
  internal/metastore/db/dao/grant.go
  internal/metastore/db/dao/grant_test.go
  internal/metastore/db/dao/role.go
  internal/metastore/db/dao/user_role.go
  internal/metastore/db/dao/user_role_test.go
  internal/metastore/db/dbmodel/common.go
  internal/metastore/db/dbmodel/grant.go
  internal/metastore/db/dbmodel/grant_id.go
  internal/metastore/db/dbmodel/mocks/IGrantDb.go
  internal/metastore/db/dbmodel/mocks/IGrantIDDb.go
  internal/metastore/db/dbmodel/mocks/IMetaDomain.go
  internal/metastore/db/rootcoord/table_catalog.go
  internal/metastore/db/rootcoord/table_catalog_test.go
  internal/metastore/kv/rootcoord/kv_catalog.go
  internal/metastore/kv/rootcoord/rootcoord_constant.go
  internal/proxy/meta_cache.go
  internal/rootcoord/meta_table.go
  internal/rootcoord/meta_table_test.go
  internal/rootcoord/root_coord.go
  internal/util/crypto/crypto.go
  internal/util/crypto/crypto_test.go
  internal/util/typeutil/string_util_test.go
  scripts/sql/meta.sql
Labels: size/XXL, approved, lgtm, ci-passed, dco-passed

#18859 Fix cache path for 20.04
  .env
  .github/workflows/publish-builder.yaml
  build/build_image.sh
  build/builder.sh
  build/docker/builder/cpu/ubuntu20.04/Dockerfile
  build/docker/milvus/ubuntu20.04/Dockerfile
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#18857 Add search cases of expressions that linking and comparing two fields
  tests/python_client/common/common_func.py
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed
