Repository milvus-io/milvus, pull requests merged in 2022-12, with the labels that each got.

#20920 Setup lastSyncTs when add segment to avoid sync next timetick
  internal/datanode/channel_meta.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#20911 Fix Group Checker test fail
  internal/util/timerecord/group_checker_test.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#20910 [Cherry-pick] Etcd config source support TLS (#20874)
  cmd/milvus/mck.go
  cmd/roles/roles.go
  cmd/tools/migration/backend/etcd.go
  cmd/tools/migration/migration/runner.go
  internal/config/etcd_source.go
  internal/config/source.go
  internal/datacoord/garbage_collector_test.go
  internal/datacoord/segment_reference_manager_test.go
  internal/datacoord/server_test.go
  internal/datanode/data_node_test.go
  internal/datanode/flow_graph_manager_test.go
  internal/datanode/mock_test.go
  internal/distributed/datacoord/client/client_test.go
  internal/distributed/datacoord/service.go
  internal/distributed/datanode/service.go
  internal/distributed/indexcoord/client/client_test.go
  internal/distributed/indexcoord/service.go
  internal/distributed/indexnode/client/client_test.go
  internal/distributed/indexnode/service.go
  internal/distributed/indexnode/service_test.go
  internal/distributed/proxy/service.go
  internal/distributed/querycoord/client/client_test.go
  internal/distributed/querycoord/service.go
  internal/distributed/querynode/service.go
  internal/distributed/rootcoord/client/client_test.go
  internal/distributed/rootcoord/service.go
  internal/distributed/rootcoord/service_test.go
  internal/indexcoord/index_coord_test.go
  internal/kv/etcd/embed_etcd_config_test.go
  internal/kv/etcd/etcd_kv_test.go
  internal/kv/etcd/metakv_factory.go
  internal/metastore/kv/rootcoord/meta_snapshot_test.go
  internal/metastore/kv/rootcoord/suffix_snapshot_test.go
  internal/proxy/proxy_test.go
  internal/querycoordv2/balance/rowcount_based_balancer_test.go
  internal/querycoordv2/checkers/channel_checker_test.go
  internal/querycoordv2/checkers/segment_checker_test.go
  internal/querycoordv2/job/job_test.go
  internal/querycoordv2/meta/collection_manager_test.go
  internal/querycoordv2/meta/replica_manager_test.go
  internal/querycoordv2/observers/collection_observer_test.go
  internal/querycoordv2/observers/handoff_observer_test.go
  internal/querycoordv2/observers/leader_observer_test.go
  internal/querycoordv2/server_test.go
  internal/querycoordv2/services_test.go
  internal/querycoordv2/task/task_test.go
  internal/querynode/impl_test.go
  internal/querynode/metrics_info_test.go
  internal/querynode/mock_test.go
  internal/querynode/query_node_test.go
  internal/rootcoord/proxy_client_manager_test.go
  internal/rootcoord/proxy_manager_test.go
  internal/rootcoord/root_coord_test.go
  internal/rootcoord/timestamp_bench_test.go
  internal/util/etcd/etcd_server.go
  internal/util/etcd/etcd_util.go
  internal/util/etcd/etcd_util_test.go
  internal/util/paramtable/base_table.go
Labels: kind/enhancement, size/XL, approved, lgtm, ci-passed, dco-passed

#20923 [Cherry Pick] Setup lastSyncTs when add segment to avoid sync next timetick (#20920)
  internal/datanode/channel_meta.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#20922 Optimize scheduler, increase merge tasks probability
  internal/querycoordv2/task/scheduler.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#20837 Verify and adjust segment # of rows before saving and passing SegmentInfo
  internal/datacoord/server_test.go
  internal/datacoord/services.go
  internal/datacoord/util.go
  internal/metastore/kv/datacoord/kv_catalog.go
  internal/metastore/kv/datacoord/kv_catalog_test.go
  internal/util/segmentutil/utils.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#20834 GetFlushedSegments should include flushing segment
  internal/datacoord/services.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#20859 GetFlushedSegments should include flushing segment
  internal/datacoord/services.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#20890 [Cherry Pick] Delete logs that print sensitive information
  internal/core/src/storage/MinioChunkManager.cpp
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#20905 Remove bad & duplicate metric
  internal/datanode/channel_meta.go
  internal/metrics/datanode_metrics.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#20931 Optimize scheduler, increase merge tasks probability (#20922)
  internal/querycoordv2/task/scheduler.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#20814 Update pymilvus version
  tests/python_client/requirements.txt
  tests/python_client/testcases/test_insert.py
Labels: sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#20891 [test]add the testcase with scalar field
  tests/python_client/testcases/test_index.py
  tests/python_client/testcases/test_query.py
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#20930 [test]add the testcase with scalar field
  tests/python_client/testcases/test_index.py
  tests/python_client/testcases/test_query.py
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#20937 Fix compaction target segment rowNum is always 0
  internal/datanode/binlog_io.go
  internal/storage/data_codec.go
  internal/storage/index_data_codec_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#20928 Generate unique id with ts for sync task
  internal/datanode/flush_manager.go
  internal/datanode/flush_manager_test.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#20941 [Cherry Pick] Fix compaction target segment rowNum is always 0 (#20937)
  internal/datanode/binlog_io.go
  internal/storage/data_codec.go
  internal/storage/index_data_codec_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#20942 [Cherry-Pick] Generate unique id with ts for sync task (#20928)
  internal/datanode/flush_manager.go
  internal/datanode/flush_manager_test.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#20914 Upgrade Knowhere to 1.3.4
  internal/core/src/config/ConfigKnowhere.cpp
  internal/core/src/config/ConfigKnowhere.h
  internal/core/src/segcore/segcore_init_c.cpp
  internal/core/src/segcore/segcore_init_c.h
  internal/core/thirdparty/knowhere/CMakeLists.txt
  internal/indexnode/indexnode.go
  internal/indexnode/indexnode_service.go
  internal/indexnode/task.go
  internal/querynode/meta_replica.go
  internal/querynode/meta_replica_test.go
  internal/querynode/mock_test.go
  internal/querynode/query_node.go
  internal/querynode/query_node_test.go
  internal/querynode/segment.go
  internal/querynode/segment_loader.go
  internal/querynode/segment_loader_test.go
  internal/querynode/segment_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed, area/compilation

#20943 [Cherry Pick]Upgrade knowhere to 1.3.4
  internal/core/src/config/ConfigKnowhere.cpp
  internal/core/src/config/ConfigKnowhere.h
  internal/core/src/segcore/segcore_init_c.cpp
  internal/core/src/segcore/segcore_init_c.h
  internal/core/thirdparty/knowhere/CMakeLists.txt
  internal/indexnode/indexnode.go
  internal/indexnode/indexnode_service.go
  internal/indexnode/task.go
  internal/querynode/meta_replica.go
  internal/querynode/meta_replica_test.go
  internal/querynode/mock_test.go
  internal/querynode/query_node.go
  internal/querynode/query_node_test.go
  internal/querynode/segment.go
  internal/querynode/segment_loader.go
  internal/querynode/segment_loader_test.go
  internal/querynode/segment_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed, area/compilation

#20940 Update test cases
  tests/python_client/testcases/test_insert.py
Labels: sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#20902 Refine log level (#20896)
  internal/metastore/kv/rootcoord/kv_catalog.go
  internal/proxy/impl.go
  internal/proxy/task_scheduler.go
  internal/querycoordv2/meta/coordinator_broker.go
  internal/rootcoord/root_coord.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#20924 Add time records for search path
  internal/querynode/task_read.go
  internal/querynode/task_search.go
  internal/util/timerecord/time_recorder.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#20945 Revert "Fix fake segment is never handled"
  internal/metastore/kv/datacoord/kv_catalog.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#20950 Add time records for search path (#20924)
  internal/querynode/task_read.go
  internal/querynode/task_search.go
  internal/util/timerecord/time_recorder.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#20948 Make datanode Unittest use embed etcd server
  internal/datanode/data_node_test.go
  internal/querynode/query_node_test.go
  internal/util/etcd/etcd_util.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#20967 Check target node ID for query/search
  internal/proxy/task_query.go
  internal/proxy/task_search.go
  internal/querynode/impl.go
  internal/querynode/impl_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#20927 [test]Fix bulk insert perf
  tests/python_client/base/utility_wrapper.py
  tests/python_client/bulk_insert/conftest.py
  tests/python_client/bulk_insert/test_bulk_insert_perf.py
  tests/python_client/chaos/checker.py
  tests/python_client/common/common_func.py
Labels: kind/improvement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#20909 Add ut for rootcoord/kv/kv_catalog.go
  internal/metastore/catalog.go
  internal/metastore/kv/rootcoord/kv_catalog.go
  internal/metastore/kv/rootcoord/kv_catalog_test.go
Labels: kind/improvement, size/XXL, approved, lgtm, ci-passed, dco-passed

#20963 Fix BufferData limit calculation for BinaryVector
  internal/datanode/buffer.go
  internal/datanode/buffer_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#20973 Fix shard leader misses to fill target ID while delegates query/search
  internal/querynode/shard_cluster.go
  internal/querynode/shard_cluster_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#20968 Check last heartbeat response time while fetching shard leaders
  configs/milvus.yaml
  internal/querycoordv2/dist/dist_handler.go
  internal/querycoordv2/services.go
  internal/querycoordv2/services_test.go
  internal/querycoordv2/session/node_manager.go
  internal/util/paramtable/component_param.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#20976 [Cherry-Pick] Check target node ID for query/search (#20967, #20973)
  internal/proxy/task_query.go
  internal/proxy/task_search.go
  internal/querynode/impl.go
  internal/querynode/impl_test.go
  internal/querynode/shard_cluster.go
  internal/querynode/shard_cluster_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#20971 [Cherry-Pick] Fix BufferData limit calculation for BinaryVector (#20963)
  internal/datanode/buffer.go
  internal/datanode/buffer_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#20974 Add ut for rootcoord/kv/kv_catalog.go (#20909)
  internal/metastore/catalog.go
  internal/metastore/kv/rootcoord/kv_catalog.go
  internal/metastore/kv/rootcoord/kv_catalog_test.go
Labels: size/XXL, approved, lgtm, ci-passed, dco-passed

#20831 Support an analogous Java Guava cache implementation
  internal/storage/vector_chunk_manager.go
  internal/util/cache/cache_interface.go
  internal/util/cache/hash.go
  internal/util/cache/hash_test.go
  internal/util/cache/local_cache.go
  internal/util/cache/local_cache_test.go
  internal/util/cache/lru_cache.go
  internal/util/cache/lru_cache_test.go
  internal/util/cache/lru_impl.go
  internal/util/cache/lru_impl_test.go
  internal/util/cache/policy.go
  internal/util/cache/policy_test.go
  internal/util/cache/stats.go
  internal/util/cache/stats_test.go
  rules.go
Labels: size/XXL, approved, lgtm, ci-passed, dco-passed

#20832 Refine msgstream api
  internal/datacoord/server.go
  internal/datacoord/server_test.go
  internal/datanode/data_node_test.go
  internal/datanode/data_sync_service_test.go
  internal/datanode/flow_graph_dd_node.go
  internal/datanode/flow_graph_dmstream_input_node_test.go
  internal/datanode/flow_graph_insert_buffer_node.go
  internal/mq/msgstream/mock_msgstream.go
  internal/mq/msgstream/mq_kafka_msgstream_test.go
  internal/mq/msgstream/mq_msgstream.go
  internal/mq/msgstream/mq_msgstream_test.go
  internal/mq/msgstream/msgstream.go
  internal/proxy/mock_test.go
  internal/querynode/load_segment_task_test.go
  internal/querynode/segment_loader.go
  internal/querynode/segment_loader_test.go
  internal/rootcoord/dml_channels.go
  internal/rootcoord/dml_channels_test.go
  internal/util/flowgraph/input_node.go
  internal/util/flowgraph/input_node_test.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#20996 Split small segment proportion and small segment compact-able proportion
  configs/milvus.yaml
  internal/datacoord/compaction_trigger.go
  internal/util/paramtable/component_param.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#20999 Load should base on the accurate loaded number
  internal/querycoordv2/observers/collection_observer.go
  internal/querycoordv2/observers/collection_observer_test.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#20981 Remove not inuse stale segments in flushmsg
  internal/datanode/data_node.go
  internal/datanode/flow_graph_insert_buffer_node.go
  internal/datanode/flow_graph_insert_buffer_node_test.go
  internal/datanode/flow_graph_message.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#20991 Check whether segments are fully loaded while fetching shard leaders
  internal/querycoordv2/services.go
  internal/querycoordv2/services_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#20775 Make progress if any channel/segment was loaded on node
  internal/querycoordv2/meta/leader_view_manager.go
  internal/querycoordv2/observers/collection_observer.go
  internal/querycoordv2/observers/collection_observer_test.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#21015 Fix compaction handler may double release and block forever
  internal/datacoord/compaction.go
  internal/datacoord/compaction_test.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#20845 Fix Rpc Limit to 64M
  configs/milvus.yaml
  internal/core/src/storage/PayloadWriter.cpp
  internal/distributed/indexcoord/service_test.go
  internal/proxy/proxy_rpc_test.go
  internal/proxy/proxy_test.go
  internal/util/paramtable/grpc_param.go
  internal/util/paramtable/grpc_param_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#21012 [CherryPick] Split small segment proportion and small segment compactable proportion
  configs/milvus.yaml
  internal/datacoord/compaction_trigger.go
  internal/util/paramtable/component_param.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed, behavior-change

#21010 [CherryPick] Increase MaxWatchDuration and make it configurable
  configs/milvus.yaml
  internal/datacoord/channel_manager.go
  internal/datacoord/channel_manager_test.go
  internal/datacoord/policy.go
  internal/datacoord/policy_test.go
  internal/util/paramtable/component_param.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed, behavior-change

#21011 [CherryPick] Reduce seal proportion from 0.25 to 0.23
  configs/embedded-milvus.yaml
  configs/milvus.yaml
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#21028 [Cherry Pick] Fix segment_num, stored_rows_num and stored_rows_count metrics
  internal/datacoord/compaction.go
  internal/datacoord/meta.go
  internal/datacoord/meta_test.go
  internal/metrics/datacoord_metrics.go
  internal/metrics/metrics.go
  tests/python_client/testcases/test_utility.py
Labels: kind/bug, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#21029 [Cherry Pick] Refine segment stat metrics on QueryNode
  internal/metrics/metrics.go
  internal/metrics/querynode_metrics.go
  internal/querynode/meta_replica.go
  internal/querynode/segment.go
  internal/util/typeutil/map.go
  internal/util/typeutil/map_test.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#21030 [Cherry Pick] Remove bad & duplicate metric
  internal/datanode/channel_meta.go
  internal/metrics/datanode_metrics.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#20986 Refine bulkinsert
  internal/datanode/data_node.go
  internal/rootcoord/import_manager.go
  internal/rootcoord/import_manager_test.go
  internal/rootcoord/root_coord_test.go
  internal/util/importutil/import_util.go
  internal/util/importutil/import_wrapper.go
  internal/util/importutil/import_wrapper_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#20674 Using first unicastable address as local ip
  go.mod
  go.sum
  internal/util/funcutil/func.go
  internal/util/paramtable/grpc_param.go
Labels: area/dependency, kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed, behavior-change

#21038 Fix group checker ut
  internal/util/timerecord/group_checker.go
  internal/util/timerecord/group_checker_test.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#21036 [Cherry-Pick] Remove some logs from debug to info
  internal/config/manager.go
  internal/datanode/buffer.go
  internal/distributed/connection_manager.go
  internal/distributed/datacoord/client/client.go
  internal/distributed/datacoord/service.go
  internal/distributed/datanode/service.go
  internal/distributed/indexcoord/client/client.go
  internal/distributed/indexcoord/service.go
  internal/distributed/indexnode/service.go
  internal/distributed/proxy/service.go
  internal/distributed/querycoord/client/client.go
  internal/distributed/querycoord/service.go
  internal/distributed/querynode/service.go
  internal/distributed/rootcoord/client/client.go
  internal/distributed/rootcoord/service.go
  internal/indexcoord/handoff.go
  internal/indexcoord/index_coord.go
  internal/indexcoord/meta_table.go
  internal/indexcoord/node_manager.go
  internal/indexcoord/task.go
  internal/indexcoord/task_scheduler.go
  internal/indexnode/indexnode.go
  internal/indexnode/task_scheduler.go
  internal/indexnode/taskinfo_ops.go
  internal/metastore/kv/rootcoord/meta_snapshot.go
  internal/mq/mqimpl/rocksmq/client/client_impl.go
  internal/mq/mqimpl/rocksmq/server/global_rmq.go
  internal/mq/mqimpl/rocksmq/server/rocksmq_impl.go
  internal/mq/mqimpl/rocksmq/server/rocksmq_impl_test.go
  internal/mq/mqimpl/rocksmq/server/rocksmq_retention.go
  internal/mq/msgstream/mq_msgstream.go
  internal/mq/msgstream/mq_msgstream_test.go
  internal/mq/msgstream/mqwrapper/kafka/kafka_client.go
  internal/mq/msgstream/mqwrapper/kafka/kafka_producer.go
  internal/mq/msgstream/mqwrapper/pulsar/pulsar_consumer.go
  internal/proxy/impl.go
  internal/proxy/meta_cache.go
  internal/proxy/multi_rate_limiter.go
  internal/proxy/privilege_interceptor.go
  internal/proxy/proxy.go
  internal/proxy/task.go
  internal/proxy/task_index.go
  internal/querycoordv2/task/scheduler.go
  internal/querycoordv2/utils/meta.go
  internal/querynode/segment_loader.go
  internal/querynode/shard_cluster.go
  internal/querynode/shard_cluster_service.go
  internal/rootcoord/dml_channels.go
  internal/rootcoord/import_manager.go
  internal/rootcoord/proxy_manager.go
  internal/rootcoord/root_coord.go
  internal/tso/global_allocator.go
  internal/tso/tso.go
  internal/util/flowgraph/node.go
  internal/util/funcutil/func.go
  internal/util/paramtable/quota_param.go
  internal/util/paramtable/service_param.go
  internal/util/retry/retry.go
  internal/util/sessionutil/session_util.go
Labels: kind/improvement, size/XXL, approved, lgtm, ci-passed, manual-pass

#21040 Fix bug for ListWithPrefix from minio with recursive is false
  internal/storage/minio_chunk_manager.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#21035 Fix the concurrent write issue when init privilege policy
  internal/distributed/proxy/service.go
  internal/proxy/privilege_interceptor.go
  internal/proxy/privilege_interceptor_test.go
Labels: size/M, approved, lgtm, ci-passed

#21024 Forbid gc index meta when creating index
  internal/indexcoord/garbage_collector.go
  internal/indexcoord/index_coord.go
  internal/indexcoord/task.go
  internal/indexcoord/task_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#20989 Add case query with empty partition names
  tests/python_client/testcases/test_query.py
Labels: kind/improvement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#21016 Modify test case same with master
  tests/python_client/testcases/test_compaction.py
Labels: sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#20984 Enable test case after code fix for 2.2
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#20982 [skip e2e] Add log export for milvus installed by operator
  deployments/export-log/README.md
  deployments/export-log/export-milvus-log.sh
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#20983 Enable test case after code fix
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#20993 Modify test cases of search pagination
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#21032 Fix empty retrieve result
  internal/common/common.go
  internal/common/common_test.go
  internal/proxy/task_query.go
  internal/proxy/task_query_test.go
  internal/querynode/impl.go
  internal/querynode/result.go
  internal/querynode/task_query.go
  internal/util/typeutil/gen_empty_field_data.go
  internal/util/typeutil/get_dim.go
  internal/util/typeutil/kv_pair_helper.go
  internal/util/typeutil/kv_pair_helper_test.go
  internal/util/typeutil/result_helper.go
  internal/util/typeutil/result_helper_test.go
  internal/util/typeutil/retrieve_result.go
Labels: kind/bug, size/XL, approved, lgtm, ci-passed, dco-passed

#21058 Prevent flushWatcher watches new segment just after GetFlushedSegments
  internal/indexcoord/flush_segment_watcher.go
  internal/indexcoord/task.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed

#21059 [pick] Fix bug for ListWithPrefix from minio with recursive is false
  internal/storage/minio_chunk_manager.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#20990 Optimization of delete and insert
  internal/proxy/impl.go
  internal/proxy/msg_pack.go
  internal/proxy/task_delete.go
  internal/proxy/task_insert.go
  internal/proxy/task_insert_test.go
  internal/proxy/task_test.go
  internal/proxy/util.go
  internal/proxy/util_test.go
Labels: kind/improvement, size/XXL, approved, lgtm, ci-passed, dco-passed

#21046 Add more logs for GetShardLeaders
  configs/milvus.yaml
  internal/querycoordv2/errors.go
  internal/querycoordv2/handlers.go
  internal/querycoordv2/services.go
  internal/querycoordv2/services_test.go
  internal/util/paramtable/component_param.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#20681 Add retention for access log on minio
  internal/proxy/accesslog/access_log_test.go
  internal/proxy/accesslog/log_writer.go
  internal/proxy/accesslog/log_writer_test.go
  internal/proxy/accesslog/minio_handler.go
  internal/proxy/accesslog/minio_handler_test.go
  internal/proxy/accesslog/util.go
  internal/util/paramtable/component_param.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#21067 Fix group checker ut (#21038)
  internal/util/timerecord/group_checker.go
  internal/util/timerecord/group_checker_test.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#21071 Fix the concurrent write issue when init privilege policy
  internal/distributed/proxy/service.go
  internal/proxy/privilege_interceptor.go
  internal/proxy/privilege_interceptor_test.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#21073 Fix the concurrent write issue when init privilege policy
  internal/distributed/proxy/service.go
  internal/proxy/privilege_interceptor.go
  internal/proxy/privilege_interceptor_test.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#21080 [CherryPick]Increase MaxWatchDuration and make it configurable (#21010)
  configs/milvus.yaml
  internal/datacoord/channel_manager.go
  internal/datacoord/channel_manager_test.go
  internal/datacoord/policy.go
  internal/datacoord/policy_test.go
  internal/util/paramtable/component_param.go
Labels: kind/improvement, size/M, approved, lgtm

#21083 Add more test for file reader
  internal/storage/minio_chunk_manager.go
  internal/storage/minio_chunk_manager_test.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#21082 Add more test on file reader
  internal/storage/minio_chunk_manager.go
  internal/storage/minio_chunk_manager_test.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#21063 Refactor showConfigurations to allow print global config
  internal/config/manager.go
  internal/datacoord/metrics_info.go
  internal/datacoord/server_test.go
  internal/datacoord/services.go
  internal/datanode/data_node.go
  internal/datanode/data_node_test.go
  internal/datanode/metrics_info.go
  internal/indexcoord/index_coord.go
  internal/indexcoord/index_coord_test.go
  internal/indexcoord/metrics_info.go
  internal/indexnode/indexnode.go
  internal/indexnode/metrics_info.go
  internal/querycoordv2/services.go
  internal/querycoordv2/services_test.go
  internal/querynode/impl.go
  internal/querynode/metrics_info.go
  internal/querynode/metrics_info_test.go
  internal/rootcoord/metrics_info.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
  internal/util/paramtable/base_table.go
  internal/util/paramtable/param_item.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#21068 Make compaction target able to exceed segment max size by a bit
  configs/milvus.yaml
  internal/datacoord/compaction_trigger.go
  internal/datacoord/compaction_trigger_test.go
  internal/proto/data_coord.proto
  internal/proto/datapb/data_coord.pb.go
  internal/util/paramtable/component_param.go
Labels: size/XXL, approved, lgtm, ci-passed, dco-passed, behavior-change

#21090 Add the superuser config
  configs/milvus.yaml
  internal/proxy/proxy_test.go
  internal/proxy/util.go
  internal/util/paramtable/component_param.go
  internal/util/paramtable/component_param_test.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#21066 Fix empty retrieve result (#21032)
  internal/common/common.go
  internal/common/common_test.go
  internal/proxy/task_query.go
  internal/proxy/task_query_test.go
  internal/querynode/impl.go
  internal/querynode/result.go
  internal/querynode/task_query.go
  internal/util/typeutil/gen_empty_field_data.go
  internal/util/typeutil/get_dim.go
  internal/util/typeutil/kv_pair_helper.go
  internal/util/typeutil/kv_pair_helper_test.go
  internal/util/typeutil/result_helper.go
  internal/util/typeutil/result_helper_test.go
  internal/util/typeutil/retrieve_result.go
Labels: kind/bug, size/XL, approved, lgtm, ci-passed, dco-passed

#21086 Rename default accesslog dir name
  configs/milvus.yaml
  internal/proxy/accesslog/log_writer.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#21115 Fix the unsafe casbin `Model`
  internal/distributed/proxy/service.go
  internal/proxy/privilege_interceptor.go
  internal/proxy/privilege_interceptor_test.go
Labels: kind/improvement, size/M, approved, lgtm

#21109 Upgrade Knowhere to 1.3.5 to fix DiskANN aio issue
  internal/core/thirdparty/knowhere/CMakeLists.txt
Labels: size/XS, approved, lgtm, ci-passed, dco-passed, area/compilation

#21108 Fix metric with wrong label
  internal/querynode/meta_replica.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#21081 Add indexCountLabel for metric QueryNodeNumEntities
  internal/metrics/querynode_metrics.go
  internal/querynode/meta_replica.go
  internal/querynode/segment.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#21121 Add indexCountLabel for metric QueryNodeNumEntities (#21081)
  internal/metrics/querynode_metrics.go
  internal/querynode/meta_replica.go
  internal/querynode/segment.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#21105 Add ut for ListWithPrefix of minio chunk manager
  internal/storage/minio_chunk_manager_test.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#21061 Forbid gc index meta when creating index
  internal/indexcoord/flush_segment_watcher.go
  internal/indexcoord/garbage_collector.go
  internal/indexcoord/index_coord.go
  internal/indexcoord/task.go
  internal/indexcoord/task_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#21119 Fix flush didn't respect binaryvector and other schemas
  internal/datacoord/compaction_trigger.go
  internal/datacoord/compaction_trigger_test.go
  internal/datanode/buffer.go
  internal/datanode/compactor.go
  internal/datanode/compactor_test.go
  internal/datanode/flow_graph_insert_buffer_node_test.go
  internal/util/paramtable/component_param.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#21120 Fix flush didn't respect binaryvector and other schemas
  internal/datacoord/compaction_trigger.go
  internal/datacoord/compaction_trigger_test.go
  internal/datanode/buffer.go
  internal/datanode/compactor.go
  internal/datanode/compactor_test.go
  internal/datanode/flow_graph_insert_buffer_node_test.go
  internal/util/paramtable/component_param.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#21042 Move APIs of types.DataNode to services.go
  internal/datanode/channel_meta.go
  internal/datanode/data_node.go
  internal/datanode/data_node_test.go
  internal/datanode/flow_graph_insert_buffer_node_test.go
  internal/datanode/segment.go
  internal/datanode/services.go
  internal/datanode/services_test.go
Labels: kind/improvement, size/XXL, approved, lgtm, ci-passed, dco-passed, manual-pass

#21114 [Cherry-Pick] Fix search failed on disk index when search_list equal to limit
  internal/core/src/index/VectorDiskIndex.cpp
  internal/core/unittest/test_indexing.cpp
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#21130 Update healthz to support standby state and fix rootcoord active-standby
  internal/management/healthz/healthz_handler.go
  internal/rootcoord/root_coord.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#21135 [Cherry Pick]Cp knowhere upgrade
  internal/core/thirdparty/knowhere/CMakeLists.txt
Labels: size/XS, approved, lgtm, ci-passed, dco-passed, area/compilation

#21132 Fix the unsafe casbin `Model`
  internal/distributed/proxy/service.go
  internal/proxy/privilege_interceptor.go
  internal/proxy/privilege_interceptor_test.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#21134 Refine search logs in querynode
  internal/querynode/impl.go
  internal/querynode/reduce_test.go
  internal/querynode/result.go
  internal/querynode/search.go
  internal/querynode/segment.go
  internal/querynode/segment_test.go
  internal/querynode/validate.go
  internal/util/timerecord/time_recorder.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#21107 Fix observers may update current target to a unfinished next target
  internal/querycoordv2/meta/target_manager.go
  internal/querycoordv2/meta/target_manager_test.go
  internal/querycoordv2/observers/target_observer.go
  internal/querycoordv2/observers/target_observer_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#21136 Refine search logs in querynode
  internal/querynode/impl.go
  internal/querynode/reduce_test.go
  internal/querynode/result.go
  internal/querynode/search.go
  internal/querynode/segment.go
  internal/querynode/segment_test.go
  internal/querynode/validate.go
  internal/util/timerecord/time_recorder.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#21137 Move sync delete policy from deleteNode to insertBufferNode
  internal/datanode/buffer.go
  internal/datanode/data_sync_service.go
  internal/datanode/flow_graph_delete_node.go
  internal/datanode/flow_graph_delete_node_test.go
  internal/datanode/flow_graph_insert_buffer_node.go
  internal/datanode/flow_graph_insert_buffer_node_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#21144 Update pymilvus version
  tests/python_client/requirements.txt
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#21146 Update pymilvus version for 2.2
  tests/python_client/requirements.txt
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#21149 Fix access log panicking for nil response
  internal/proxy/accesslog/util.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#21150 Use channel-cp as seekPosition when FromDmlCPLoadDelete[pick#21110]
  internal/datacoord/server_test.go
  internal/datacoord/services.go
  internal/proto/data_coord.proto
  internal/proto/datapb/data_coord.pb.go
  internal/querycoordv2/meta/coordinator_broker.go
  internal/querycoordv2/meta/mock_broker.go
  internal/querycoordv2/task/executor.go
  internal/querycoordv2/task/task_test.go
  internal/querycoordv2/task/utils.go
  internal/querycoordv2/task/utils_test.go
Labels: size/XL, approved, lgtm, ci-passed, dco-passed

#21133 Load should base on the accurate loaded number
  internal/querycoordv2/observers/collection_observer.go
  internal/querycoordv2/observers/collection_observer_test.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#21156 Fix load timeout
  internal/querycoordv2/observers/collection_observer.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#21161 Fill collection schema after DataCoord restarts
  internal/datacoord/channel_store.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#21140 Fix channelmanager ut
  internal/datacoord/channel_manager_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#21163 [Cherry-Pick] Make progress if any channel/segment was loaded on node (#20775)
  internal/querycoordv2/meta/leader_view_manager.go
  internal/querycoordv2/observers/collection_observer.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#21164 [Cherry Pick] Fill collection schema after DataCoord restarts (#21161)
  internal/datacoord/channel_store.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#21139 Check whether segments are fully loaded while fetching shard leaders (#20991)
  internal/querycoordv2/errors.go
  internal/querycoordv2/services.go
  internal/querycoordv2/services_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#21168 Fix ci test for test_compaction
  tests/python_client/common/common_type.py
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#21155 [Cherry-Pick] Make TopK Limit configurable
  internal/core/src/index/VectorMemIndex.cpp
  internal/proxy/task_query_test.go
  internal/proxy/util.go
  internal/util/paramtable/component_param.go
  tests/python_client/testcases/test_search.py
Labels: kind/improvement, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#21127 Fix metric with wrong label
  internal/querynode/meta_replica.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#21106 Fix jemalloc.so not found
  .github/mergify.yml
  .github/workflows/code-checker.yaml
  .github/workflows/main.yaml
  internal/core/conanfile.py
  internal/core/conanfile.txt
  scripts/setenv.sh
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#21174 Fix metric with wrong label (#21127)
  internal/querynode/meta_replica.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#21175 [test]Add create checker
  tests/python_client/chaos/testcases/test_single_request_operation.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#21178 Fix ci test for test_compaction(2.2)
  tests/python_client/common/common_type.py
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#21180 [test]Fix github action for chaos test
  .github/workflows/pod-kill-chaos-test-kafka-version.yaml
  .github/workflows/pod-kill-chaos-test.yaml
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#21077 Recalculate segment max size during compaction
  internal/datacoord/compaction_trigger.go
  internal/datacoord/compaction_trigger_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#21152 Move sync delete policy from deleteNode to insertBufferNode[pick#21137]
  internal/datanode/buffer.go
  internal/datanode/data_sync_service.go
  internal/datanode/flow_graph_delete_node.go
  internal/datanode/flow_graph_delete_node_test.go
  internal/datanode/flow_graph_insert_buffer_node.go
  internal/datanode/flow_graph_insert_buffer_node_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#21110 Use channel-cp as seekPosition when FromDmlCPLoadDelete
  internal/datacoord/server_test.go
  internal/datacoord/services.go
  internal/proto/data_coord.proto
  internal/proto/datapb/data_coord.pb.go
  internal/querycoordv2/meta/coordinator_broker.go
  internal/querycoordv2/meta/mock_broker.go
  internal/querycoordv2/task/executor.go
  internal/querycoordv2/task/task_test.go
  internal/querycoordv2/task/utils.go
  internal/querycoordv2/task/utils_test.go
Labels: size/XL, approved, lgtm, ci-passed, dco-passed

#21034 Guard bad distance/score from knowhere
  internal/proxy/task_search.go
  internal/proxy/task_search_test.go
  internal/querynode/result.go
  internal/querynode/result_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#21190 Fix sealed segments ids unmatch after load balance
  tests/python_client/testcases/test_utility.py
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#21195 Add mysql to nightly
  ci/jenkins/Nightly.groovy
  tests/scripts/values/mysql.yaml
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#21205 Empty implement of the `GetLoadState` api
  go.mod
  go.sum
  internal/core/src/pb/common.pb.cc
  internal/core/src/pb/common.pb.h
  internal/core/src/pb/schema.pb.cc
  internal/distributed/proxy/service.go
  internal/distributed/proxy/service_test.go
  internal/proxy/impl.go
  internal/types/types.go
Labels: area/dependency, kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#21129 Fix the unsafe casbin `Model`
  internal/distributed/proxy/service.go
  internal/metastore/kv/rootcoord/kv_catalog.go
  internal/proxy/privilege_interceptor.go
  internal/proxy/privilege_interceptor_test.go
  internal/util/cache/local_cache_test.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#21104 Reduce maxFieldNum from 256 to 64
  configs/milvus.yaml
  internal/metastore/kv/datacoord/kv_catalog.go
  internal/metastore/kv/datacoord/kv_catalog_test.go
  internal/metastore/kv/rootcoord/kv_catalog.go
  internal/util/etcd/etcd_util.go
  tests/python_client/common/common_type.py
Labels: sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed, behavior-change

#21179 Fix test cases for search pagination
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#21182 [test]Modify the search list testcase of diskann
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#21214 [skip e2e]Add dependence google abseil for milvus builder and krte
  build/docker/builder/cpu/centos7/Dockerfile
  build/docker/builder/cpu/ubuntu18.04/Dockerfile
  build/docker/builder/cpu/ubuntu20.04/Dockerfile
  build/docker/krte/Dockerfile
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#21203 Make sure querynode stop only once
  internal/querynode/query_node.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#21226 Handler ErrCompacted for handler observer
  internal/querycoordv2/observers/handoff_observer.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#21233 Fix panic while concurrent releasing payload writer/reader (#21218)
  internal/core/src/storage/parquet_c.cpp
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#21220 Add test cases of index annoy
  tests/python_client/common/common_func.py
  tests/python_client/testcases/test_index.py
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#21224 [Cherry Pick]Create index before load for upgrading test
  tests/python_client/deploy/scripts/action_after_upgrade.py
  tests/python_client/deploy/scripts/action_before_upgrade.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#21222 Create index before load
  tests/python_client/deploy/scripts/action_after_upgrade.py
  tests/python_client/deploy/scripts/action_before_upgrade.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#21239 Update test cases about maximum field number 64
  tests/python_client/testcases/test_collection.py
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#21232 Fixbug: proxy meta_cache partially update
  internal/proxy/meta_cache.go
  internal/proxy/meta_cache_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#21242 Fixbug: proxy meta_cache partially update (#21232)
  internal/proxy/meta_cache.go
  internal/proxy/meta_cache_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#21243 [skip e2e] Update image revision of rte config (#21214)
  ci/jenkins/pod/rte.yaml
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#21241 [Cherry Pick] Upgrade knowhere to 1.3.6
  internal/core/thirdparty/knowhere/CMakeLists.txt
Labels: size/XS, approved, lgtm, ci-passed, dco-passed, area/compilation, manual-pass

#21231 Update test case of output empty search field
  tests/python_client/testcases/test_query.py
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#21244 [skip e2e] Update PR.groovy
  ci/jenkins/PR.groovy
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#21246 [skip e2e]Fix script of nightly 2.2 branch
  ci/jenkins/Nightly.groovy
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#21240 Upgrade Knowhere to 1.3.6 to fix bugs
  internal/core/thirdparty/knowhere/CMakeLists.txt
Labels: size/XS, approved, lgtm, ci-passed, dco-passed, area/compilation

#21237 Fix unit test of local cache cause data race
  internal/util/cache/local_cache_test.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#21151 Make TopK Limit configurable
  internal/proxy/util.go
  internal/util/paramtable/component_param.go
Labels: kind/improvement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#21255 Fix publish image jenkins task
  ci/jenkins/PublishImages.groovy
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#21252 Add test cases of search pagination in case offset >= num_entities
  tests/python_client/testcases/test_query.py
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#21250 [Cherry Pick] Small candidate compaction should only happen with >1 segments
  configs/milvus.yaml
  internal/datacoord/compaction_trigger.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#21021 Support the graceful stop for the indexnode
  internal/distributed/indexnode/service.go
  internal/indexcoord/index_coord.go
  internal/indexcoord/index_coord_test.go
  internal/indexcoord/node_manager.go
  internal/indexcoord/node_manager_test.go
  internal/indexnode/indexnode.go
  internal/indexnode/indexnode_service.go
  internal/indexnode/indexnode_service_test.go
  internal/indexnode/indexnode_test.go
  internal/indexnode/taskinfo_ops.go
  internal/querynode/query_node.go
  internal/util/commonpbutil/commonpbutil.go
  internal/util/commonpbutil/commonpbutil_test.go
  internal/util/paramtable/component_param.go
  internal/util/paramtable/component_param_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed
