Repository milvus-io/milvus, pull requests merged in 2022-05, with the labels that each got.

#16445 Merge utils/Types.h with common/Types.h
  internal/core/src/common/QueryResult.h
  internal/core/src/common/Types.cpp
  internal/core/src/common/Types.h
  internal/core/src/index/IndexFactory.h
  internal/core/src/segcore/SegmentInterface.cpp
  internal/core/src/segcore/SegmentSealedImpl.cpp
  internal/core/src/utils/Types.h
  internal/core/unittest/test_c_api.cpp
  internal/core/unittest/test_concurrent_vector.cpp
  internal/core/unittest/test_segcore.cpp
  internal/core/unittest/test_utils/DataGen.h
  internal/core/unittest/test_utils/indexbuilder_test_utils.h
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#16751 Support easylogging config for segcore and knowhere
  configs/easylogging.yaml
  internal/core/src/config/ConfigKnowhere.cpp
  internal/core/src/config/ConfigKnowhere.h
  internal/core/src/indexbuilder/init_c.cpp
  internal/core/src/indexbuilder/init_c.h
  internal/core/src/segcore/segcore_init_c.cpp
  internal/core/src/segcore/segcore_init_c.h
  internal/core/unittest/test_init.cpp
  internal/indexnode/indexnode.go
  internal/querynode/query_node.go
  internal/util/paramtable/base_table.go
  internal/util/paramtable/base_table_test.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#16762 Merge utils/Utils.h into common/Utils.h
  internal/core/src/common/Utils.h
  internal/core/src/segcore/ConcurrentVector.h
  internal/core/src/segcore/SegmentGrowingImpl.cpp
  internal/core/src/utils/Utils.h
  internal/core/unittest/test_expr.cpp
  internal/core/unittest/test_span.cpp
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#16758 test: use `T.TempDir` to create temporary test directory
  internal/kv/etcd/embed_etcd_kv_test.go
  internal/log/log_test.go
  internal/log/zap_log_test.go
  internal/mq/msgstream/mq_factory_test.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#16766 [skip e2e]Change insight to Attu in Readme
  README.md
  README_CN.md
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#16717 Remove AddTenant from meta table
  docs/developer_guides/chap06_root_coordinator.md
  internal/proto/etcd_meta.proto
  internal/proto/etcdpb/etcd_meta.pb.go
  internal/rootcoord/meta_table.go
  internal/rootcoord/meta_table_test.go
Labels: area/dependency, size/L, approved, lgtm, ci-passed, dco-passed

#16754 Reduce the number of retries and add error log
  internal/datacoord/server.go
  internal/datanode/data_node.go
  internal/distributed/rootcoord/service_test.go
  internal/indexcoord/index_coord.go
  internal/rootcoord/root_coord.go
  internal/storage/minio_chunk_manager.go
  internal/util/retry/retry.go
  internal/util/sessionutil/session_util.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed

#16731 Support Small index config
  configs/milvus.yaml
  internal/core/src/segcore/SegcoreConfig.h
  internal/core/src/segcore/segcore_init_c.cpp
  internal/core/src/segcore/segcore_init_c.h
  internal/querynode/query_node.go
  internal/util/paramtable/component_param.go
  internal/util/paramtable/component_param_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#16655 Clean up not used id_cache related code
  configs/embedded-milvus.yaml
  configs/milvus.yaml
  go.mod
  go.sum
  internal/proxy/id_cache.go
  internal/proxy/id_cache_test.go
  internal/util/paramtable/component_param.go
Labels: kind/enhancement, area/dependency, size/M, approved, lgtm, ci-passed, dco-passed

#16618 Remove unnessary Grpc log
  configs/milvus.yaml
  internal/distributed/datacoord/client/client.go
  internal/distributed/datanode/client/client.go
  internal/distributed/indexcoord/client/client.go
  internal/distributed/indexnode/client/client.go
  internal/distributed/proxy/client/client.go
  internal/distributed/querycoord/client/client.go
  internal/distributed/querynode/client/client.go
  internal/distributed/rootcoord/client/client.go
  internal/log/config.go
  internal/util/grpcclient/client.go
  internal/util/logutil/logutil.go
  internal/util/paramtable/base_table.go
  internal/util/paramtable/base_table_test.go
  internal/util/paramtable/component_param.go
  internal/util/paramtable/grpc_param.go
  internal/util/paramtable/grpc_param_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#16770 Fix LoadBalance failed to sync segments to shard leader when the leader is offline
  internal/querycoord/query_coord.go
  internal/querycoord/task.go
  internal/querycoord/task_scheduler.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed

#16788 Fix replicaID is allow zero from watch channel task
  internal/proto/query_coord.proto
  internal/proto/querypb/query_coord.pb.go
  internal/querycoord/task_scheduler.go
  internal/querynode/task.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, area/internal-api, dco-passed

#16757 Support replica as input parameters and update test cases to adapt to different replicas
  tests/python_client/base/client_base.py
  tests/python_client/base/collection_wrapper.py
  tests/python_client/base/partition_wrapper.py
  tests/python_client/common/common_func.py
  tests/python_client/common/common_type.py
  tests/python_client/conftest.py
  tests/python_client/testcases/test_collection.py
  tests/python_client/testcases/test_compaction.py
Labels: kind/improvement, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#16777 Fix security issue on coreos etcd dependency
  go.mod
  go.sum
Labels: area/dependency, kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#16785 Modify the replicas' shard info after load balance
  internal/querycoord/task.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#16725 Add DataQueryable and DataIndexed states to bulk load tasks
  configs/milvus.yaml
  internal/core/src/pb/common.pb.cc
  internal/core/src/pb/common.pb.h
  internal/distributed/rootcoord/service_test.go
  internal/proto/common.proto
  internal/proto/commonpb/common.pb.go
  internal/querycoord/impl.go
  internal/rootcoord/import_manager.go
  internal/rootcoord/meta_table.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
  internal/util/paramtable/component_param.go
Labels: kind/enhancement, size/XL, approved, lgtm, ci-passed, dco-passed

#16774 Prohibit creating diff indexes with same index_name on a collection
  internal/rootcoord/meta_table.go
  internal/rootcoord/meta_table_test.go
  internal/rootcoord/root_coord_test.go
  tests/python_client/testcases/test_collection.py
  tests/python_client/testcases/test_index.py
Labels: kind/feature, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#16780 Add tests for bulk load
  tests/python_client/base/utility_wrapper.py
  tests/python_client/check/func_check.py
  tests/python_client/testcases/test_import.py
Labels: sig/testing, size/XXL, approved, lgtm, area/test, ci-passed, dco-passed

#16760 Fix bulkload bugs
  internal/core/src/indexbuilder/VecIndexCreator.cpp
  internal/util/importutil/import_wrapper.go
  internal/util/importutil/import_wrapper_test.go
  internal/util/importutil/json_handler.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#16795 [skip e2e]Disable contributor action when repo is not milvus
  .github/workflows/all-contributors.yaml
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#16794 Delete set default type param max_len for varchar field
  internal/proxy/task.go
  internal/proxy/task_test.go
  internal/proxy/util.go
  tests/python_client/requirements.txt
  tests/python_client/testcases/test_collection.py
Labels: kind/bug, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#16797 [skip e2e] Force go 1.17 for Code Checker MinGW
  scripts/install_deps_msys.sh
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#16798 Add isShardLeader field in search/query request
  internal/proto/query_coord.proto
  internal/proto/querypb/query_coord.pb.go
  internal/proxy/task_query.go
  internal/proxy/task_search.go
  internal/querynode/impl_test.go
  internal/querynode/query_shard.go
  internal/querynode/query_shard_test.go
  internal/querynode/shard_cluster.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, area/internal-api, dco-passed

#16696 Support antlr as plan parser
  go.mod
  go.sum
  internal/core/src/pb/plan.pb.cc
  internal/core/src/pb/plan.pb.h
  internal/parser/planparserv2/Plan.g4
  internal/parser/planparserv2/README.md
  internal/parser/planparserv2/check_identical.go
  internal/parser/planparserv2/check_identical_test.go
  internal/parser/planparserv2/error_listener.go
  internal/parser/planparserv2/floating_comparision.go
  internal/parser/planparserv2/floating_comparision_test.go
  internal/parser/planparserv2/generated/Plan.interp
  internal/parser/planparserv2/generated/Plan.tokens
  internal/parser/planparserv2/generated/PlanLexer.interp
  internal/parser/planparserv2/generated/PlanLexer.tokens
  internal/parser/planparserv2/generated/plan_base_visitor.go
  internal/parser/planparserv2/generated/plan_lexer.go
  internal/parser/planparserv2/generated/plan_parser.go
  internal/parser/planparserv2/generated/plan_visitor.go
  internal/parser/planparserv2/logical_expr_visitor.go
  internal/parser/planparserv2/node_ret.go
  internal/parser/planparserv2/operators.go
  internal/parser/planparserv2/parser_visitor.go
  internal/parser/planparserv2/plan_parser_v2.go
  internal/parser/planparserv2/plan_parser_v2_test.go
  internal/parser/planparserv2/pool.go
  internal/parser/planparserv2/pool_test.go
  internal/parser/planparserv2/show_visitor.go
  internal/parser/planparserv2/utils.go
  internal/proto/plan.proto
  internal/proto/planpb/plan.pb.go
  internal/proxy/plan_parser.go
  internal/proxy/plan_parser_test.go
  internal/util/typeutil/schema.go
  ruleguard.rules.go
  scripts/run_go_codecov.sh
Labels: area/dependency, size/XXL, approved, lgtm, ci-passed, dco-passed

#16755 Make duplicate flush recalls success and other logic update
  internal/datacoord/session_manager.go
  internal/datanode/cache.go
  internal/datanode/cache_test.go
  internal/datanode/data_node.go
  internal/datanode/data_node_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#16803 [test]Update common func with string
  tests/python_client/common/common_func.py
  tests/python_client/common/common_type.py
  tests/python_client/requirements.txt
  tests/python_client/testcases/test_query.py
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#16800 [skip e2e] Add a new case label for cluster mode
  build/ci/jenkins/Nightly.groovy
  tests/python_client/common/common_type.py
  tests/python_client/testcases/test_collection.py
  tests/python_client/testcases/test_partition.py
Labels: kind/improvement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#16815 Fix wrong result topks when reduce search result
  internal/core/src/segcore/reduce_c.cpp
  internal/core/unittest/test_c_api.cpp
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#16814 Some minor fixes and improvements
  internal/datanode/data_node.go
  internal/rootcoord/root_coord.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, needs-dco

#16783 make SegmentMaxLifetime configurable
  configs/milvus.yaml
  internal/datacoord/segment_manager.go
  internal/util/paramtable/component_param.go
  internal/util/paramtable/component_param_test.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed

#16604 Change QueryNode Log level
  internal/querycoord/query_coord.go
  internal/querynode/collection.go
  internal/querynode/collection_replica.go
  internal/querynode/data_sync_service.go
  internal/querynode/flow_graph_delete_node.go
  internal/querynode/flow_graph_filter_delete_node.go
  internal/querynode/flow_graph_filter_dm_node.go
  internal/querynode/flow_graph_insert_node.go
  internal/querynode/flow_graph_query_node.go
  internal/querynode/flow_graph_service_time_node.go
  internal/querynode/impl.go
  internal/querynode/load_index_info.go
  internal/querynode/partition.go
  internal/querynode/proxy_session_manager.go
  internal/querynode/query_channel.go
  internal/querynode/query_collection.go
  internal/querynode/query_node.go
  internal/querynode/query_service.go
  internal/querynode/query_shard.go
  internal/querynode/query_shard_service.go
  internal/querynode/segment.go
  internal/querynode/segment_loader.go
  internal/querynode/shard_cluster.go
  internal/querynode/shard_cluster_service.go
  internal/querynode/shard_node_detector.go
  internal/querynode/shard_segment_detector.go
  internal/querynode/stats_service.go
  internal/querynode/streaming.go
  internal/querynode/task.go
  internal/querynode/task_queue.go
  internal/querynode/tsafe_replica.go
Labels: size/XL, approved, lgtm, ci-passed, dco-passed

#16820 Make each dataNode only accept one bulk load task simultaneously
  internal/datacoord/server_test.go
  internal/datacoord/services.go
  internal/rootcoord/import_manager.go
  internal/rootcoord/import_manager_test.go
  internal/rootcoord/root_coord.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#16827 [skip e2e]Update dependency for deploy test
  .github/workflows/deploy-test.yaml
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#16799 [test]Update testcase tag
  tests/python_client/testcases/test_e2e.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#16828 [test]Modify the common func
  tests/python_client/common/common_func.py
  tests/python_client/testcases/test_delete.py
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#16818 Limit and translate pattern match operations
  internal/parser/planparserv2/parser_visitor.go
  internal/parser/planparserv2/pattern_match.go
  internal/parser/planparserv2/pattern_match_test.go
  internal/parser/planparserv2/plan_parser_v2_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#16831 Add legacySegments for load balance segments rc track
  internal/querynode/shard_cluster.go
  internal/querynode/shard_cluster_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#16834 [test] Add string testcase to collection
  tests/python_client/testcases/test_collection.py
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#16836 Fix create index failed after drop index
  internal/proxy/task.go
  internal/rootcoord/meta_table.go
  tests/python_client/requirements.txt
Labels: kind/bug, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#16810 Sort out the log of IndexCoord
  internal/indexcoord/index_coord.go
  internal/indexcoord/index_coord_test.go
  internal/indexcoord/node_manager.go
  internal/indexcoord/node_manager_test.go
  internal/indexcoord/peek_client_policy.go
  internal/indexcoord/peek_client_policy_test.go
  internal/indexcoord/priority_queue_test.go
  internal/indexnode/indexnode_mock.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#16839 Fix pulsar unsubscribe failure with consumer not found
  internal/datacoord/channel_manager.go
  internal/mq/msgstream/mq_msgstream.go
  internal/mq/msgstream/mqwrapper/pulsar/pulsar_consumer.go
  internal/mq/msgstream/msgstream_util.go
  internal/querycoord/channel_unsubscribe.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#16845 [test] Add counter decorator and scale query multi replicas test
  build/ci/jenkins/Scale.groovy
  tests/python_client/customize/template/default.yaml
  tests/python_client/scale/scale_common.py
  tests/python_client/scale/test_data_node_scale.py
  tests/python_client/scale/test_index_node_scale.py
  tests/python_client/scale/test_proxy_scale.py
  tests/python_client/scale/test_query_node_scale.py
  tests/python_client/utils/wrapper.py
Labels: kind/improvement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#16847 [test]Add the string testcase of insert
  tests/python_client/testcases/test_insert.py
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#16852 [skip e2e]Update the right links for install milvus
  README.md
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#16849 Refine DataNode logs.
  internal/util/sessionutil/session_util.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#16848 Move locks back to meta table methods
  internal/rootcoord/meta_table.go
  internal/rootcoord/meta_table_test.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#16826 Make PayloadReader read column data in batch
  internal/storage/payload_benchmark_test.go
  internal/storage/payload_reader.go
  internal/storage/payload_test.go
Labels: kind/improvement, size/XL, approved, lgtm, ci-passed, dco-passed

#16870 [skip e2e]Update values yaml for chaos test
  tests/python_client/chaos/cluster-values.yaml
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#16869 Add bulk load data generate functions
  tests/python_client/base/utility_wrapper.py
  tests/python_client/bulk_load/bulk_load_data.py
  tests/python_client/bulk_load/test_bulk_load.py
  tests/python_client/common/common_type.py
  tests/python_client/requirements.txt
Labels: sig/testing, size/XL, approved, lgtm, area/test, ci-passed, dco-passed

#16861 [test]Add string testcase to search
  tests/python_client/base/client_base.py
  tests/python_client/common/common_func.py
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/XXL, approved, lgtm, area/test, ci-passed, dco-passed

#16854 Fix updating segments' NodeIds correctly after LoadBalance
  internal/querycoord/meta.go
  internal/querycoord/segments_info.go
  internal/querycoord/task.go
  internal/querycoord/task_scheduler.go
  internal/querycoord/task_test.go
  internal/querycoord/util.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#16825 Add tests where segments load delta logs
  internal/querynode/mock_test.go
  internal/querynode/segment_loader.go
  internal/querynode/segment_loader_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#16880 Add lock before query release collection from replica
  internal/querynode/task.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#16883 Fix msgstream unsubscription
  internal/mq/msgstream/mq_msgstream.go
  internal/mq/msgstream/mqwrapper/pulsar/pulsar_consumer.go
  internal/querycoord/meta.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#16886 Return error when no replica available
  internal/querycoord/impl.go
  internal/querycoord/impl_test.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#16706 support tls
  configs/cert/ca.key
  configs/cert/ca.pem
  configs/cert/ca.srl
  configs/cert/client.csr
  configs/cert/client.key
  configs/cert/client.pem
  configs/cert/server.csr
  configs/cert/server.key
  configs/cert/server.pem
  configs/milvus.yaml
  internal/distributed/proxy/service.go
  internal/distributed/proxy/service_test.go
  internal/util/paramtable/grpc_param.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#16878 Print collectionName when load failed
  internal/proxy/task.go
  internal/proxy/util.go
  internal/proxy/util_test.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#16877 Handle subscribe gracefully
  internal/datacoord/channel_manager.go
  internal/msgstream/mq_msgstream.go
  internal/querycoord/channel_unsubscribe.go
  internal/querycoord/meta.go
  internal/util/mqclient/pulsar_consumer.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#16895 [skip e2e] Add a script to export milvus log
  deployments/export-log/README.md
  deployments/export-log/export-milvus-log.sh
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#16896 [skip e2e]Update schema for string
  tests/python_client/chaos/scripts/hello_milvus.py
  tests/python_client/chaos/scripts/verify_all_collections.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#16908 [skip e2e] Add a description about docker-compose export log
  deployments/export-log/README.md
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#16912 Use NodeIds instead of NodeID in segment info
  internal/querynode/shard_cluster.go
  internal/querynode/shard_cluster_test.go
  internal/querynode/shard_segment_detector.go
  internal/querynode/shard_segment_detector_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#16884 [test]Add the string testcase of index and query
  tests/python_client/base/collection_wrapper.py
  tests/python_client/base/index_wrapper.py
  tests/python_client/requirements.txt
  tests/python_client/testcases/test_index.py
  tests/python_client/testcases/test_query.py
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#16925 Fix deadlock in release replica
  internal/querynode/impl.go
  internal/querynode/task.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#16903 Support deltaLog loading on growing segment
  internal/core/src/segcore/SegmentGrowingImpl.cpp
  internal/core/src/segcore/SegmentGrowingImpl.h
  internal/core/src/segcore/SegmentInterface.h
  internal/core/src/segcore/SegmentSealed.h
  internal/core/src/segcore/segment_c.cpp
  internal/querynode/mock_test.go
  internal/querynode/segment.go
  internal/querynode/segment_loader.go
  internal/querynode/segment_loader_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#16863 Delete all repeated primary keys
  internal/core/src/common/Types.h
  internal/core/src/segcore/Record.h
  internal/core/src/segcore/SegmentGrowing.h
  internal/core/src/segcore/SegmentGrowingImpl.cpp
  internal/core/src/segcore/SegmentGrowingImpl.h
  internal/core/src/segcore/SegmentSealedImpl.cpp
  internal/core/src/segcore/SegmentSealedImpl.h
  internal/core/src/segcore/Utils.cpp
  internal/core/src/segcore/Utils.h
  internal/core/unittest/test_c_api.cpp
  internal/core/unittest/test_utils/DataGen.h
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#16928 [skip e2e] Solve the problem of file residue when uninstalling rpm
  build/rpm/milvus.spec
  build/rpm/services/milvus-etcd.service
  build/rpm/services/milvus-minio.service
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#16917 [skip e2e]Add log export instructions for issue template
  .github/ISSUE_TEMPLATE/bug_report.yaml
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#16931 [test]Add the testcase of index
  tests/python_client/common/common_type.py
  tests/python_client/testcases/test_index.py
Labels: sig/testing, size/XL, approved, lgtm, area/test, ci-passed, dco-passed

#16946 Fix channelUnsubscribe data race and logic
  internal/querycoord/channel_unsubscribe.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#16952 [skip e2e]Add utils to get node id and corresponding pod name
  tests/python_client/utils/util_k8s.py
Labels: kind/improvement, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#16837 Make data queryable and data indexed states as independent flags
  internal/core/src/pb/common.pb.cc
  internal/core/src/pb/common.pb.h
  internal/core/src/pb/milvus.pb.cc
  internal/core/src/pb/milvus.pb.h
  internal/proto/common.proto
  internal/proto/commonpb/common.pb.go
  internal/proto/data_coord.proto
  internal/proto/datapb/data_coord.pb.go
  internal/proto/milvus.proto
  internal/proto/milvuspb/milvus.pb.go
  internal/rootcoord/import_manager.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
Labels: kind/improvement, area/api, size/XXL, approved, lgtm, ci-passed, dco-passed

#16955 Replace text codec of pb with binary codec
  internal/core/src/common/type_c.h
  internal/core/src/segcore/segment_c.cpp
  internal/core/src/segcore/segment_c.h
  internal/core/unittest/test_c_api.cpp
  internal/querynode/segment.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#16940 Make proxy update cache with NotShardLeader status code
  internal/core/src/pb/common.pb.cc
  internal/core/src/pb/common.pb.h
  internal/proto/common.proto
  internal/proto/commonpb/common.pb.go
  internal/proxy/task_query.go
  internal/proxy/task_search.go
  internal/querynode/impl.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#16966 [skip ci]Fix a minor mistake
  CONTRIBUTING.md
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#16950 Improve query shard log
  internal/querynode/query_shard.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#16975 [skip e2e]Delete duplicate file with search
  tests/python_client/testcases/test_search_20.py
Labels: kind/improvement, sig/testing, size/XXL, approved, lgtm, area/test, ci-passed, dco-passed

#16958 Fix bulkload bug for string primary key
  internal/datanode/data_node.go
  internal/util/importutil/import_wrapper.go
  internal/util/importutil/import_wrapper_test.go
  internal/util/importutil/json_handler.go
  internal/util/importutil/json_handler_test.go
  internal/util/importutil/json_parser.go
  internal/util/importutil/json_parser_test.go
Labels: size/XL, approved, lgtm, ci-passed, dco-passed

#16969 Modify index test cases to 2.0 interface
  tests/python_client/testcases/test_index.py
Labels: kind/improvement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#16939 Fix ut data race
  internal/distributed/proxy/service.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#16953 Fix valid error message
  internal/proxy/task.go
  internal/proxy/task_test.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#16907 Add new node into the replica which has the most of offline nodes
  internal/querycoord/cluster.go
  internal/querycoord/group_balance.go
  internal/querycoord/query_coord.go
  internal/querycoord/util.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#16976 Simplify chunk manager in QueryShard
  internal/querynode/query_shard.go
  internal/querynode/query_shard_service.go
  internal/querynode/query_shard_service_test.go
  internal/querynode/query_shard_test.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#16985 Support deltaLog loading on growing segment
  internal/core/src/segcore/SegmentGrowingImpl.cpp
  internal/core/src/segcore/SegmentGrowingImpl.h
  internal/core/src/segcore/SegmentInterface.h
  internal/core/src/segcore/segment_c.cpp
  internal/querynode/mock_test.go
  internal/querynode/segment.go
  internal/querynode/segment_loader_test.go
Labels: size/L, approved, lgtm, dco-passed

#16973 Remove not used QueryService
  internal/querynode/query_service.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#16983 Fix kafka client hang after killing broker pod of parition leader
  internal/mq/msgstream/mqwrapper/kafka/kafka_client.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#16982 Fix the comment info in task_test.go
  internal/proxy/task_test.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#17005 Load binlog for different field in parallel
  internal/querynode/segment_loader.go
Labels: kind/feature, size/M, approved, lgtm, ci-passed, dco-passed

#16970 [skip e2e]Update the way of reconnection
  tests/python_client/chaos/chaos_commons.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#16981 [skip e2e]Update multi replicas chaos test
  tests/python_client/chaos/chaos_objects/template/pod-kill-by-pod-list.yaml
  tests/python_client/chaos/checker.py
  tests/python_client/chaos/test_chaos_multi_replicas.py
Labels: kind/improvement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#17000 modify index test cases to 2.0
  tests/python_client/common/common_type.py
  tests/python_client/testcases/test_index.py
Labels: kind/improvement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#16998 Refine bulk load tests with data preparation
  tests/python_client/bulk_load/bulk_load_data.py
  tests/python_client/bulk_load/minio_comm.py
  tests/python_client/bulk_load/test_bulk_load.py
Labels: sig/testing, size/XXL, approved, lgtm, area/test, ci-passed, dco-passed

#16977 Update pymilvus version to 2.1.0.dev57
  tests/python_client/requirements.txt
  tests/python_client/testcases/test_connection.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#16891 proxy support tls document
  docs/user_guides/tls_proxy.md
  tests/python_client/testcases/test_import.py
Labels: kind/improvement, sig/testing, size/XXL, approved, lgtm, area/test, ci-passed, dco-passed

#17020 [skip e2e]Update issue template
  .github/ISSUE_TEMPLATE/bug_report.yaml
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#16921 Fix load the same segments multiple times for manual LoadBalance
  internal/querycoord/task.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed

#16978 Add some log.
  internal/querycoord/task.go
  internal/querycoord/task_scheduler.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#17034 Fix query lock logic in query shard
  internal/querynode/collection.go
  internal/querynode/collection_test.go
  internal/querynode/impl.go
  internal/querynode/impl_test.go
  internal/querynode/meta_replica.go
  internal/querynode/meta_replica_test.go
  internal/querynode/query_collection.go
  internal/querynode/query_shard.go
  internal/querynode/query_shard_test.go
  internal/querynode/task.go
  internal/querynode/tsafe.go
  internal/querynode/tsafe_replica.go
Labels: kind/improvement, size/XL, approved, lgtm, ci-passed, dco-passed

#17039 Fix Handoff log in shardCluster service
  internal/querynode/shard_cluster_service.go
  internal/querynode/shard_cluster_service_test.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#17018 [test] Add and update cases for insert a deleted id
  tests/python_client/testcases/test_delete.py
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#17019 [test] Add and update cases for insert a deleted id
  tests/python_client/testcases/test_delete.py
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#17033 Fix deletes not taking effect on sealed segment
  internal/core/src/segcore/SegmentSealedImpl.cpp
  internal/core/unittest/test_c_api.cpp
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#17027 Support Txn interface in rockskv
  internal/kv/rocksdb/rocksdb_kv.go
  internal/kv/rocksdb/rocksdb_kv_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#17003 Minio Error is not Handled gracefully
  internal/storage/local_chunk_manager.go
  internal/storage/local_chunk_manager_test.go
  internal/storage/minio_chunk_manager.go
  internal/storage/minio_chunk_manager_test.go
  internal/storage/types.go
  internal/storage/vector_chunk_manager.go
  internal/storage/vector_chunk_manager_test.go
  internal/util/importutil/import_wrapper_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#16942 Clear shard leaders cache when releasing
  internal/proxy/meta_cache.go
  internal/proxy/meta_cache_test.go
  internal/proxy/task.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#17032 Add MockCluster, make unit tests reliable
  internal/querycoord/impl_test.go
  internal/querycoord/mock_cluster.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#16305 Print err info when insert msg not aligned
  internal/querynode/flow_graph_insert_node.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#17045 Return buildID when creating index if the index alreay exists
  internal/rootcoord/root_coord.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#17058 Fix VectorChunkManager cache enable parameter
  internal/querynode/query_shard_service.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#17054 [test][skip-e2e] Update delete cases due to adding string field
  tests/python_client/testcases/test_delete.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#17047 [test] Add chaos memory stress test for multiple memory replicas
  tests/python_client/chaos/chaos_objects/memory_stress/chaos_querynode_memory_stress.yaml
  tests/python_client/chaos/chaos_objects/memory_stress/chaos_replicas_memory_stress_pods.yaml
  tests/python_client/chaos/test_chaos_memory_stress.py
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#17050 Fix prefix match on sealed segment
  internal/core/src/query/ScalarIndex.h
  internal/core/unittest/test_sealed.cpp
Labels: size/S, approved, lgtm, ci-passed, dco-passed

#17052 The GetIndexFilePaths interface judges whether the index is complete
  internal/indexcoord/index_coord.go
  internal/indexcoord/index_coord_test.go
  internal/indexcoord/meta_table.go
  internal/indexnode/task.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#17051 Fix LoadBalance doesn't remove the source nodes from segment
  internal/querycoord/task.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#16935 Disable segment small index
  configs/milvus.yaml
  internal/core/src/segcore/segment_c.cpp
  internal/querynode/segment_test.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed

#17082 Fix 'TestChannelManager_StateTransfer' ut when etcd is slow
  internal/datacoord/channel_manager_test.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#17078 [test]Add the string testcase of search and query
  tests/python_client/testcases/test_query.py
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#17084 [skip e2e]Update multi replicas chaos test
  tests/python_client/chaos/test_chaos_multi_replicas.py
Labels: kind/improvement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#17094 Add deferred clean up for ShardCluster
  internal/querynode/task.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#17085 [test]Add the string testcase of delete
  tests/python_client/check/func_check.py
  tests/python_client/check/param_check.py
  tests/python_client/testcases/test_delete.py
Labels: sig/testing, size/XL, approved, lgtm, area/test, ci-passed, dco-passed

#16882 Add collection load cache and support InvalidateCollMetaCache by collID
  internal/datacoord/mock_test.go
  internal/distributed/proxy/service_test.go
  internal/distributed/rootcoord/client/client.go
  internal/distributed/rootcoord/client/client_test.go
  internal/distributed/rootcoord/service.go
  internal/distributed/rootcoord/service_test.go
  internal/proto/proxy.proto
  internal/proto/proxypb/proxy.pb.go
  internal/proto/root_coord.proto
  internal/proto/rootcoordpb/root_coord.pb.go
  internal/proxy/authentication_interceptor_test.go
  internal/proxy/impl.go
  internal/proxy/meta_cache.go
  internal/proxy/meta_cache_test.go
  internal/proxy/proxy.go
  internal/proxy/proxy_test.go
  internal/proxy/rootcoord_mock_test.go
  internal/proxy/task.go
  internal/proxy/task_index_test.go
  internal/proxy/task_query.go
  internal/proxy/task_query_test.go
  internal/proxy/task_search.go
  internal/proxy/task_search_test.go
  internal/proxy/task_test.go
  internal/querycoord/global_meta_broker.go
  internal/querycoord/global_meta_broker_test.go
  internal/querycoord/mock_3rd_component_test.go
  internal/querycoord/task.go
  internal/querycoord/task_test.go
  internal/rootcoord/proxy_client_manager.go
  internal/rootcoord/proxy_client_manager_test.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
  internal/rootcoord/task.go
  internal/types/types.go
  internal/util/mock/rootcoord_client.go
  tests/python_client/testcases/test_partition.py
Labels: sig/testing, size/XXL, approved, lgtm, area/test, ci-passed, area/internal-api, dco-passed

#17065 Limit the query node timetick log rate
  internal/querynode/flow_graph_service_time_node.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#17106 Fix replica freeAll order
  internal/querynode/query_node.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#17064 Fix LoadBalance doesn't save the modification to replicas' shards
  internal/querycoord/group_balance.go
  internal/querycoord/querynode.go
  internal/querycoord/task.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#17090 Replace plan parser with antlr
  internal/parser/planparserv2/Plan.g4
  internal/parser/planparserv2/generated/Plan.interp
  internal/parser/planparserv2/generated/plan_parser.go
  internal/parser/planparserv2/parser_visitor.go
  internal/parser/planparserv2/plan_parser_v2_test.go
  internal/proxy/plan_parser_test.go
  internal/proxy/task_query.go
  internal/proxy/task_search.go
  tests/python_client/testcases/test_delete.py
  tests/python_client/testcases/test_query.py
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#17057 Fix data race for indexcoord test
  internal/indexnode/indexnode_mock.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#17111 Fix replicas info is not removed after release
  internal/querycoord/meta.go
  internal/querycoord/meta_test.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#17109 Make querynode LoadSegments interface idempotent
  internal/querynode/task.go
  internal/querynode/task_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#17101 [skip e2e]Add bulk load checker for chaos test
  tests/python_client/chaos/checker.py
  tests/python_client/chaos/test_chaos_bulk_load.py
  tests/python_client/common/common_func.py
  tests/python_client/utils/util_common.py
  tests/python_client/utils/util_k8s.py
Labels: kind/improvement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#17105 Bulkload not allow duplicate numpy file
  internal/util/importutil/import_wrapper.go
  internal/util/importutil/import_wrapper_test.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed

#17012 Support tls/ssl connection to etcd (#7703)
  configs/milvus.yaml
  internal/util/etcd/etcd_util.go
  internal/util/etcd/etcd_util_test.go
  internal/util/paramtable/service_param.go
  internal/util/paramtable/service_param_test.go
Labels: size/L, approved, lgtm, dco-passed

#17120 Fix shardLeader cache concurrent access
  internal/proxy/meta_cache.go
  internal/proxy/task_policies.go
  internal/proxy/task_policies_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#17121 Add NodeIds field for QuerySegmentInfo
  internal/core/src/pb/milvus.pb.cc
  internal/core/src/pb/milvus.pb.h
  internal/proto/milvus.proto
  internal/proto/milvuspb/milvus.pb.go
  internal/proto/query_coord.proto
  internal/proto/querypb/query_coord.pb.go
  internal/proxy/impl.go
  internal/querycoord/task.go
  internal/querycoord/task_scheduler.go
  tests/python_client/testcases/test_utility.py
Labels: kind/improvement, sig/testing, area/api, size/XXL, approved, lgtm, area/test, ci-passed, area/internal-api, dco-passed

#17129 Fix pool of lexer and parser
  internal/parser/planparserv2/plan_parser_v2.go
  internal/parser/planparserv2/plan_parser_v2_test.go
  internal/parser/planparserv2/pool.go
  internal/parser/planparserv2/pool_test.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#17132 Fix partition not found
  internal/querycoord/task.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#17137 [test]Modify the testcase with query
  tests/python_client/requirements.txt
  tests/python_client/testcases/test_query.py
Labels: sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#17138 [skip e2e]Add script to export containers log one by one
  .github/workflows/deploy-test.yaml
  tests/scripts/export_log_docker.sh
Labels: kind/improvement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#17061 move arrow from storage to core
  go.mod
  internal/core/CMakeLists.txt
  internal/core/src/common/CMakeLists.txt
  internal/core/thirdparty/CMakeLists.txt
  internal/core/thirdparty/arrow/CMakeLists.txt
  internal/storage/cwrapper/CMakeLists.txt
  internal/storage/payload_reader_cgo.go
Labels: area/dependency, size/L, approved, lgtm, ci-passed, dco-passed, area/compilation

#16929 [skip e2e] Add script for building deb package
  build/deb/build_deb.sh
  build/deb/debian/compat
  build/deb/debian/control
  build/deb/debian/copyright
  build/deb/debian/milvus-docs.docs
  build/deb/debian/rules
  build/deb/debian/source/format
  build/deb/scripts/milvus-etcd.service
  build/deb/scripts/milvus-minio.service
  build/deb/scripts/milvus.conf
  build/deb/scripts/milvus.service
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#17069 Refactor kafka msgstream implementation
  internal/mq/msgstream/mq_kafka_msgstream_test.go
  internal/mq/msgstream/mqwrapper/kafka/kafka_client.go
  internal/mq/msgstream/mqwrapper/kafka/kafka_client_test.go
  internal/mq/msgstream/mqwrapper/kafka/kafka_consumer.go
  internal/mq/msgstream/mqwrapper/kafka/kafka_consumer_test.go
  internal/mq/msgstream/mqwrapper/kafka/kafka_producer.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#17149 Remove rocksmq reader
  internal/mq/mqimpl/rocksmq/client/client.go
  internal/mq/mqimpl/rocksmq/client/client_impl.go
  internal/mq/mqimpl/rocksmq/client/consumer_impl.go
  internal/mq/mqimpl/rocksmq/client/reader.go
  internal/mq/mqimpl/rocksmq/client/reader_impl.go
  internal/mq/mqimpl/rocksmq/client/reader_impl_test.go
  internal/mq/mqimpl/rocksmq/server/rocksmq.go
  internal/mq/mqimpl/rocksmq/server/rocksmq_impl.go
  internal/mq/mqimpl/rocksmq/server/rocksmq_impl_test.go
  internal/mq/mqimpl/rocksmq/server/rocksmq_reader.go
Labels: size/XL, approved, lgtm, ci-passed, dco-passed

#17080 Configure indexSliceSize to 16MB
  configs/milvus.yaml
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#17153 Mark indexing task to retry when minio occurs error
  internal/indexnode/task.go
  internal/indexnode/task_test.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#17162 Fix unitest fail, change default index slice to 16
  internal/util/paramtable/component_param.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, do-not-merge/missing-related-issue, dco-passed

#17141 [skip e2e] Update monitor dashboard
  deployments/monitor/grafana/milvus-dashboard.json
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#17163 [test] Update case get growing segments info
  tests/python_client/testcases/test_utility.py
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#17154 Remove some xfail markers
  tests/python_client/bulk_load/minio_comm.py
  tests/python_client/bulk_load/test_bulk_load.py
Labels: sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#17170 [skip e2e]Add checker for chaos test
  tests/python_client/chaos/checker.py
Labels: kind/improvement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#17168 Acquire nq from placeholdergroup incase of nq is zero
  internal/proxy/task_search.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed

#17175 Add test for numpy files in diff folders
  tests/python_client/bulk_load/test_bulk_load.py
Labels: sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed
