Repository milvus-io/milvus, pull requests merged in 2022-01, with the labels that each got.

#14656 [skip e2e] Improve annotation
  internal/util/sessionutil/session_util.go
  tests/python_client/testcases/test_utility.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#14704 [skip e2e]Refactor chaos test to support multi experiments
  .github/workflows/pod-failure-chaos-test.yaml
  .github/workflows/pod-kill-chaos-test.yaml
  tests/python_client/chaos/chaos_test.sh
  tests/python_client/chaos/constants.py
  tests/python_client/chaos/test_chaos.py
Labels: kind/improvement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#14653 [skip e2e] Improve annotation
  internal/kv/rocksdb/rocksdb_kv_test.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14625 [skip e2e]Update license for cwrapper parquet
  internal/storage/cwrapper/ColumnType.h
  internal/storage/cwrapper/ParquetWrapper.cpp
  internal/storage/cwrapper/ParquetWrapper.h
  internal/util/distance/similarity_corelation_test.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#14626 [skip e2e]Update license for cwrapper payload
  internal/storage/cwrapper/PayloadStream.cpp
  internal/storage/cwrapper/PayloadStream.h
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#14628 Add test case query deleted ids after handoff
  tests/python_client/testcases/test_delete.py
Labels: sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#14642 [skip e2e] Update license
  internal/util/funcutil/func.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#14643 [skip e2e] Update license
  internal/util/funcutil/func_test.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#14644 [skip e2e] Update license
  internal/util/funcutil/parallel.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#14654 [skip e2e] Improve annotation
  internal/msgstream/mq_msgstream.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14611 Fix panic when close IndexCoord
  internal/indexcoord/index_coord.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed

#14712 [skip e2e] Modify log text according to the naming conventions
  internal/util/paramtable/global_param_test.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14715 [skip e2e] Modify log text according to the naming conventions
  internal/util/paramtable/global_param_test.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14713 [skip e2e] Modify log text according to the naming conventions
  internal/util/paramtable/global_param_test.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14716 [skip e2e] Modify log text according to the naming conventions
  internal/util/paramtable/global_param_test.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14698 Fix #12498 crashed when do specific actions
  core/src/db/insert/MemTable.cpp
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#14721 [skip e2e] Add comment for indexnode.Params
  internal/indexnode/indexnode.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14723 [skip e2e] Add comment for base table
  internal/util/paramtable/base_table.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14724 [skip e2e] Add coment for payloadwriter
  internal/storage/payload.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14726 [skip e2e]Reorder head files for indexnode/service_test.go
  internal/distributed/indexnode/service_test.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14727 [skip e2e]Reorder head files for indexnode/service.go
  internal/distributed/indexnode/service.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14729 [skip e2e]Reorder head files for indexcoord/client.go
  internal/distributed/indexcoord/client/client.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14739 [skip e2e]Use logutil in DataCoord
  internal/datacoord/server.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14740 [skip e2e] Fix typo for design doc
  docs/design_docs/segcore/segment_growing.md
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14741 [skip e2e] Fix typo for design doc
  docs/design_docs/segcore/segment_interface.md
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14742 [skip e2e] Fix typo for design doc
  docs/design_docs/segcore/timetravel.md
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14743 [skip e2e] Add comment for getIndexBinlog
  internal/querynode/index_loader.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14744 [skip e2e] Add comment for estimateIndexBinlogSize
  internal/querynode/index_loader.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14745 [skip e2e] Add comment for getIndexInfo
  internal/querynode/index_loader.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14746 [skip e2e] Add comment for meta_cache.go
  internal/proxy/meta_cache.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14750 [skip e2e] Add comment for newChannelsMgrImpl
  internal/proxy/channels_mgr.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14751 [skip e2e] Add comment for getMinTick
  internal/proxy/channels_time_ticker.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14752 [skip e2e] Add comment for minFloat32
  internal/proxy/task.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14753 [skip e2e] Improve SearchTask log format
  internal/proxy/task.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14754 [skip e2e] Fix grammar
  docs/design_docs/milvus_timesync_en.md
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14755 [skip e2e] Fix grammar
  docs/design_docs/milvus_timesync_en.md
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14756 [skip e2e] Fix grammar
  docs/design_docs/milvus_timesync_en.md
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14760 [skip e2e]Add comments to conf adapter file
  internal/util/indexparamcheck/conf_adapter.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14761 [skip e2e]Add comments to conf adapter file
  internal/util/indexparamcheck/conf_adapter.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14758 Fix not load delete log when handoff segment
  internal/querycoord/task.go
  tests/python_client/testcases/test_delete.py
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#14543 Fix pulsar reader not close
  internal/msgstream/mq_msgstream.go
  internal/querynode/segment_loader.go
  internal/querynode/task.go
  internal/querynode/task_test.go
  internal/util/mqclient/rmq_client.go
  internal/util/mqclient/rmq_consumer.go
  internal/util/mqclient/rmq_producer.go
  internal/util/rocksmq/client/rocksmq/client_impl.go
  internal/util/rocksmq/server/rocksmq/rocksmq_impl.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#14683 Fixbug: client connection reset by deadline
  internal/util/grpcclient/client.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14600 Add more logs on write path
  internal/datacoord/channel_manager.go
  internal/datanode/data_node.go
  internal/datanode/data_sync_service.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#14773 [skip e2e] Enable scale test release uninstall
  tests/python_client/scale/test_data_node_scale.py
  tests/python_client/scale/test_index_node_scale.py
  tests/python_client/scale/test_proxy_scale.py
  tests/python_client/scale/test_query_node_scale.py
Labels: kind/improvement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#14762 [skip e2e]Add comments to conf adapter file
  internal/util/indexparamcheck/conf_adapter.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14767 [skip e2e]Update milvus version for deploy test
  tests/python_client/deploy/test.sh
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#14770 [skip e2e]Update artifacts name of log
  .github/workflows/deploy-test.yaml
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14772 [skip e2e] Update server version on benchmark
  tests/benchmark/milvus_benchmark/config.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#14774 [skip e2e]Update grafana template
  deployments/monitor/grafana/milvus-dashboard.json
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14737 Use logutil in DataCoord
  internal/datacoord/server.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14748 Add comment for chanPartSegments
  internal/datacoord/meta.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14782 [skip e2e]Update grafana description
  deployments/monitor/grafana/milvus-dashboard.json
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14776 [skip e2e] Update mqclient pulsar client test license
  internal/util/mqclient/pulsar_client_test.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#14778 [skip e2e] Update mqclient pulsar id license
  internal/util/mqclient/pulsar_id.go
Labels: kind/improvement, size/S, approved, lgtm, dco-passed

#14728 [skip e2e] Remove redundant code
  internal/core/src/query/visitors/ExtractInfoPlanNodeVisitor.cpp
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14783 [skip e2e]Update grafana panel description
  deployments/monitor/grafana/milvus-dashboard.json
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14714 [skip e2e]Add comment for ci_e2e.sh
  tests/scripts/ci_e2e.sh
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#14708 [skip e2e] Check the syntax of query_boolean_expr md
  docs/design_docs/query_boolean_expr.md
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14710 [skip e2e] Update comment to uppercase
  scripts/core_build.sh
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14717 [skip e2e] Improve annotation
  internal/querycoord/task_scheduler.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14720 [skip e2e]Update comment for ci_logs.sh to upper case
  tests/scripts/ci_logs.sh
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#14722 [skip e2e] Optimize ExecPlanNodeVisitor.cpp
  internal/core/src/query/visitors/ExecPlanNodeVisitor.cpp
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14641 Delete useless var in watchDeletaChannelTask
  internal/querycoord/task.go
  internal/querycoord/task_scheduler.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14784 [skip e2e] Update scale test to run in parallel
  build/ci/jenkins/Scale.groovy
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14652 Add debug logs in tests
  tests/python_client/testcases/entity/test_insert.py
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#14430 Add log info
  internal/datacoord/services.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14685 [skip e2e]Update milvus component name
  docs/design_docs/root_coordinator_recovery_on_power_failure.md
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14686 [skip e2e]Fix a grammar issue
  CONTRIBUTING.md
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14631 Adjust usage of lock in datanode
  internal/datacoord/services.go
  internal/datanode/data_node.go
  internal/datanode/segment_replica.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#14763 Remove build_timeout in test code
  tests/python_client/testcases/test_index.py
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#14764 Add debug log in pytest fixture
  tests/python_client/conftest.py
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#14711 [skip e2e] Improve annotation
  docs/design_docs/milvus_create_index_en.md
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14719 [skip e2e] Reorder header files for ExecExprVisitor.cpp
  internal/core/src/query/visitors/ExecExprVisitor.cpp
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14725 [skip e2e] Remove redundant code
  internal/core/src/query/visitors/ExtractInfoExprVisitor.cpp
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14732 [skip e2e] Reorder header files for VerifyPlanNodeVisitor.cpp
  internal/core/src/query/visitors/VerifyPlanNodeVisitor.cpp
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14765 Remove useless code in test
  tests/python_client/testcases/test_flush.py
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#14777 [skip e2e] Update mqclient pulsar consumer test license
  internal/util/mqclient/pulsar_consumer_test.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#14702 Add log for watchDeltaChannelTask's nodeID
  internal/querynode/impl.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14788 [skip e2e]Update timeout of search for deploy test
  tests/python_client/deploy/scripts/utils.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#14792 [skip e2e] Add scale test post email notify
  build/ci/jenkins/Scale.groovy
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#14790 [skip e2e]Update license
  internal/util/typeutil/convension.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#14796 [skip e2e] Update license
  internal/util/funcutil/random.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#14794 [skip e2e] Update license
  internal/util/flowgraph/type_def.go
Labels: kind/improvement, size/S, lgtm, ci-passed, dco-passed

#14795 [skip e2e] Update license
  internal/util/funcutil/parallel_test.go
Labels: kind/improvement, size/S, approved, lgtm, dco-passed

#14797 Fix bug: should use Lock instead of RLock
  Makefile
  internal/datanode/segment_replica.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14731 [skip e2e] Reorder header files for ShowPlanNodeVisitor.cpp
  internal/core/src/query/visitors/ShowPlanNodeVisitor.cpp
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14779 Make pytest run in separate pods
  build/ci/jenkins/PR.groovy
  build/ci/jenkins/pod/rte.yaml
  tests/scripts/ci_e2e.sh
Labels: kind/improvement, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#14730 [skip e2e] Reorder header files for ShowExprVisitor.cpp
  internal/core/src/query/visitors/ShowExprVisitor.cpp
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14789 [skip e2e] Replace number 3000 with default nb variable
  tests/python_client/testcases/test_query.py
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14798 [skip e2e] Check the syntax of query_boolean_expr doc
  docs/design_docs/query_boolean_expr.md
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14321 [skip e2e]Fix function typo
  internal/datacoord/channel_manager.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14799 [skip e2e] Improve annotation
  internal/querycoord/task_scheduler.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14766 Improve timeout timestamp log when query in QueryNode
  internal/querynode/query_collection.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed

#14801 [skip e2e] Improve annotation
  tests/python_client/chaos/test_chaos_memory_stress.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#14808 [skip e2e] Reorder header files for common/Schema.cpp
  internal/core/src/common/Schema.cpp
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#14821 [skip e2e] Reorder header files for common/Span.h
  internal/core/src/common/Span.h
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14823 [skip e2e] Reorder header files for common/SystemProperty.cpp
  internal/core/src/common/SystemProperty.cpp
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14827 [skip e2e] Remove discard
  internal/core/src/common/SystemProperty.cpp
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14828 [skip e2e] Reorder header files for common/SystemProperty.h
  internal/core/src/common/SystemProperty.h
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14842 [skip e2e]Add comment for checkIndexMeta
  internal/indexnode/task.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14841 [skip e2e]Add comment for setID
  internal/indexnode/task.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14843 [skip e2e]Fix typo in comment
  internal/types/types.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14830 [skip e2e] Fix grammar
  docs/design_docs/milvus_timesync_en.md
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14831 [skip e2e] Fix grammar
  docs/design_docs/proxy.md
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14832 [skip e2e] Fix grammar
  docs/design_docs/milvus_proto.md
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14829 [skip e2e] Update scale index repeated release name
  tests/python_client/scale/test_index_node_scale.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#14835 [skip e2e] Removed unused codes on main file
  tests/benchmark/milvus_benchmark/main.py
Labels: kind/improvement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#14837 [skip e2e] Removed unused codes on client file
  tests/benchmark/milvus_benchmark/client.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#14838 [skip e2e] Delete unused logs on search file
  tests/benchmark/milvus_benchmark/runners/search.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#14803 [skip e2e] Add comment for payload
  internal/storage/payload.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14804 [skip e2e] Add comment for base table
  internal/util/paramtable/base_table.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14805 [skip e2e] Add comments for index type
  internal/util/indexparamcheck/index_type.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14806 [skip e2e]Sort imports
  internal/datanode/compactor.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14709 [skip e2e] Improve annotation
  internal/msgstream/mq_msgstream.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14807 [skip e2e]Sort imports
  internal/datacoord/server.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14809 [skip e2e]Sort imports
  internal/datacoord/segment_info.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14810 [skip e2e]Sort imports
  internal/datacoord/policy.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14812 [skip e2e]Sort imports
  internal/datacoord/meta.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14813 [skip e2e]Sort imports
  internal/datacoord/handler.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14814 [skip e2e]Sort imports
  internal/datacoord/garbage_collector.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14815 [skip e2e]Sort imports
  internal/datacoord/compaction_trigger.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14816 [skip e2e]Sort imports
  internal/datacoord/compaction.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14817 [skip e2e]Sort imports
  internal/datacoord/channel_manager.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14818 [skip e2e]Sort imports
  internal/allocator/id.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14819 [skip e2e]Sort imports
  internal/datanode/data_sync_service.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14820 [skip e2e]Sort imports
  internal/datanode/flow_graph_dd_node.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14824 [skip e2e] Add comment for GetCollectionInfo of proxy meta cache
  internal/proxy/meta_cache.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14825 [skip e2e] Improve comment for DataNode delete node
  internal/datanode/flow_graph_delete_node.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14826 [skip e2e] Improve log in allocator/id.go
  internal/allocator/id.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14845 [skip e2e]Update test description
  tests/python_client/deploy/README.md
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#14846 [skip e2e]Fix a grammar issue
  docs/design_docs/root_coordinator_recovery_on_power_failure.md
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14855 [skip e2e]Correct comments for proxy config
  configs/milvus.yaml
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14844 Fail fast when pulsar subscribe exlusive timeout
  internal/util/mqclient/pulsar_client.go
  internal/util/mqclient/pulsar_client_test.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#14863 [skip e2e] Refine docs
  docs/developer_guides/appendix_b_api_reference.md
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14853 [skip e2e] Remove unused parameter
  tests/python_client/testcases/test_collection.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#14857 [skip e2e]Add comments to conf adapter file
  internal/util/indexparamcheck/conf_adapter.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14811 [skip e2e]Sort imports
  internal/datacoord/metrics_info.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14860 [skip e2e] Update mqclient pulsar producer license
  internal/util/mqclient/pulsar_producer.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#14865 [skip e2e]Update grafana panel description
  deployments/monitor/grafana/milvus-dashboard.json
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14866 [skip e2e]Update grafana panel description
  deployments/monitor/grafana/milvus-dashboard.json
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14867 [skip e2e]Update grafana panel description
  deployments/monitor/grafana/milvus-dashboard.json
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14868 [skip e2e] Remove scale pipeline printenv
  build/ci/jenkins/Scale.groovy
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14869 [skip e2e] Enable expand indexnode test release uninstall
  tests/python_client/scale/test_index_node_scale.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#14874 [skip e2e] Format the comment
  tests/python_client/testcases/test_insert_20.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#14858 [skip e2e] Update mqclient pulsar id test license
  internal/util/mqclient/pulsar_id_test.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#14847 Add debug log in tests
  tests/python_client/testcases/test_flush.py
Labels: sig/testing, size/XS, approved, area/test, dco-passed

#14856 Modify the testcase
  tests/python_client/testcases/test_collection.py
Labels: kind/improvement, sig/testing, size/M, area/test, dco-passed

#14864 Modify the testcase
  tests/python_client/testcases/test_search_20.py
Labels: kind/improvement, sig/testing, size/L, area/test, dco-passed

#14802 Remove unused code in ci_e2e.sh
  tests/scripts/ci_e2e.sh
Labels: kind/improvement, sig/testing, size/XS, area/test, dco-passed

#14852 [skip e2e] Remove useless configuration rootcoord.timeout
  configs/milvus.yaml
  internal/util/paramtable/global_param.go
  internal/util/paramtable/global_param_test.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed
