Repository milvus-io/milvus, pull requests merged in 2022-02, with the labels that each got.

#15455 Respect SegmentIDs in querynode.GetSegmentInfo
  internal/querynode/impl.go
  internal/querynode/impl_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#15273 Add more specific log when exiting BackGroundGC goroutine
  internal/datanode/data_node.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#14418 Implement automatic item expiration on compaction
  configs/milvus.yaml
  internal/datanode/compactor.go
  internal/datanode/compactor_test.go
  internal/datanode/mock_test.go
  internal/util/paramtable/global_param.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#15448 Support windows compliation
  internal/core/src/indexbuilder/CMakeLists.txt
  internal/core/src/log/CMakeLists.txt
  internal/core/src/log/Log.cpp
  internal/core/src/segcore/CMakeLists.txt
  internal/core/src/utils/CMakeLists.txt
  internal/core/thirdparty/fiu/CMakeLists.txt
  internal/querynode/load_index_info.go
  internal/querynode/plan.go
  internal/querynode/reduce.go
  internal/querynode/segment.go
  internal/storage/cwrapper/CMakeLists.txt
  internal/storage/payload.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed, area/compilation

#15462 Update dependency install script.
  scripts/install_deps.sh
Labels: size/XS, lgtm

#15414 Add elapse logs in compaction
  internal/datanode/compactor.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#15485 Put logs of compaction elapse in defer
  internal/datanode/compactor.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#15463 Rename paramtable structure
  cmd/roles/roles.go
  internal/allocator/global_id_test.go
  internal/datacoord/server.go
  internal/datanode/data_node.go
  internal/distributed/indexnode/client/client_test.go
  internal/distributed/indexnode/service_test.go
  internal/indexcoord/index_coord.go
  internal/indexnode/indexnode.go
  internal/kv/etcd/embed_etcd_config_test.go
  internal/kv/etcd/embed_etcd_kv_test.go
  internal/kv/etcd/embed_etcd_restart_test.go
  internal/kv/etcd/etcd_kv_test.go
  internal/proxy/proxy.go
  internal/querycoord/query_coord.go
  internal/querynode/query_node.go
  internal/rootcoord/root_coord.go
  internal/util/etcd/etcd_util_test.go
  internal/util/paramtable/base_table.go
  internal/util/paramtable/component_param.go
  internal/util/paramtable/component_param_test.go
  internal/util/paramtable/grpc_param.go
  internal/util/paramtable/grpc_param_test.go
  internal/util/paramtable/service_param.go
  internal/util/paramtable/service_param_test.go
Labels: kind/improvement, size/XL, approved, lgtm, ci-passed, dco-passed

#14207 Get indexInfo and segment size by queryCoord
  internal/distributed/querynode/service.go
  internal/distributed/querynode/service_test.go
  internal/querycoord/cluster.go
  internal/querycoord/cluster_test.go
  internal/querycoord/global_meta_broker.go
  internal/querycoord/global_meta_broker_test.go
  internal/querycoord/impl.go
  internal/querycoord/impl_test.go
  internal/querycoord/index_checker.go
  internal/querycoord/index_checker_test.go
  internal/querycoord/mock_3rd_component_test.go
  internal/querycoord/query_coord.go
  internal/querycoord/query_coord_test.go
  internal/querycoord/segment_allocator.go
  internal/querycoord/segment_allocator_test.go
  internal/querycoord/task.go
  internal/querycoord/task_scheduler.go
  internal/querycoord/task_scheduler_test.go
  internal/querycoord/task_test.go
  internal/querycoord/util.go
  internal/querynode/collection_replica.go
  internal/querynode/collection_replica_test.go
  internal/querynode/flow_graph_delete_node.go
  internal/querynode/impl_test.go
  internal/querynode/index_info.go
  internal/querynode/index_info_test.go
  internal/querynode/index_loader.go
  internal/querynode/index_loader_test.go
  internal/querynode/load_index_info.go
  internal/querynode/load_index_info_test.go
  internal/querynode/load_service_test.go
  internal/querynode/mock_components_test.go
  internal/querynode/mock_test.go
  internal/querynode/query_node.go
  internal/querynode/query_node_test.go
  internal/querynode/reduce_test.go
  internal/querynode/segment.go
  internal/querynode/segment_loader.go
  internal/querynode/segment_loader_test.go
  internal/querynode/segment_test.go
  internal/querynode/stats_service.go
  internal/querynode/stats_service_test.go
  internal/types/types.go
  internal/util/funcutil/func.go
Labels: size/XXL, approved, lgtm, ci-passed, area/internal-api, dco-passed

#15487 Add test case for partition delete function
  tests/python_client/base/partition_wrapper.py
  tests/python_client/requirements.txt
  tests/python_client/testcases/test_partition_20.py
Labels: kind/improvement, approved, lgtm, ci-passed, dco-passed

#15171 [skip e2e] Modify code comments according to the naming conventions
  internal/proxy/metrics_info.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#15134 [skip e2e] Check the grammar of segment_growing.md
  docs/design_docs/segcore/segment_growing.md
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#15172 [skip e2e] Modify code comments according to the naming conventions
  internal/proxy/metrics_info.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#15173 [skip e2e] Modify code comments according to the naming conventions
  internal/rootcoord/root_coord.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#15174 [skip e2e] Check the grammar of segment_interface.md
  docs/design_docs/segcore/segment_interface.md
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#15182 [skip e2e] Check the grammar of segcore/timetravel.md
  docs/design_docs/segcore/timetravel.md
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#15501 Move ProxySubName/QueryNodeSubName/DataNodeSubName to msgChannelConfig
  internal/datacoord/channel_manager.go
  internal/datanode/data_node.go
  internal/datanode/flow_graph_dmstream_input_node.go
  internal/proxy/proxy.go
  internal/proxy/proxy_test.go
  internal/proxy/task_scheduler.go
  internal/querycoord/channel_unsubscribe.go
  internal/querynode/query_node.go
  internal/querynode/task.go
  internal/util/paramtable/component_param.go
  internal/util/paramtable/component_param_test.go
  internal/util/paramtable/service_param.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#15500 delete repeated partition testcase
  tests/python_client/testcases/test_partition.py
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#15506 Fix clean up data dir failed for TestEtcdRestartLoad
  internal/kv/etcd/embed_etcd_restart_test.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#15447 Move Logutil to Util dir
  cmd/roles/roles.go
  internal/datacoord/compaction_trigger.go
  internal/datacoord/server.go
  internal/datacoord/services.go
  internal/datanode/data_node.go
  internal/distributed/datacoord/service.go
  internal/proxy/impl.go
  internal/proxy/proxy.go
  internal/proxy/proxy_test.go
  internal/util/logutil/logutil.go
  internal/util/paramtable/base_table.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#15511 [skip e2e] Add jq into pytest docker image
  tests/docker/Dockerfile
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#15502 Update pytest image tag for QA cluster
  build/ci/jenkins/qa/pod/rte.yaml
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#15436 Fix watch dml channel fail because of no collection meta
  internal/querynode/collection_replica.go
  internal/querynode/task.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#15431 Fix confusing logs in rootcoord client
  internal/distributed/rootcoord/client/client.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#15498 Update timeout and retry for ci to install requirement
  tests/scripts/ci-util.sh
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#15530 Return flush state true when segment in Flushing state
  internal/datacoord/services.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#15507 Fix make clean can't remove build directories
  Makefile
Labels: size/XS, approved, lgtm, ci-passed, dco-passed, area/compilation

#15528 Revert go.mod change of forked gorocksdb
  go.mod
  go.sum
Labels: kind/bug, area/dependency, size/XS, approved, lgtm, ci-passed, dco-passed

#15495 delete repetitive insert case
  tests/python_client/testcases/entity/test_insert.py
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#15525 [skip e2e]Fix bad link in doc
  docs/design_docs/segcore/Search.md
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#15539 [skip e2e] Remove unused test cases
  tests/python_client/testcases/test_config.py
Labels: kind/improvement, sig/testing, size/XXL, approved, lgtm, area/test, ci-passed, dco-passed

#15545 Add pypi proxy for e2e test
  tests/scripts/ci-util.sh
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#15543 Update bookkeeper journal to use local-path
  tests/scripts/values/pr.yaml
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#15553 fix wrong link to Cpp SDK in README
  README.md
  README_CN.md
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#15550 Update query test cases
  tests/python_client/testcases/test_query.py
Labels: kind/improvement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#15547 Add more timeout for wait for compation completed
  tests/python_client/base/collection_wrapper.py
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#15571 Add docker pull & time before build
  tests/scripts/e2e-k8s.sh
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#15563 Update jvm config for pulsar in CI
  tests/scripts/values/pr.yaml
Labels: kind/improvement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#15569 delete testcase of flush
  tests/python_client/testcases/test_flush.py
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#15572 update testcase of partition
  tests/python_client/testcases/test_partition.py
  tests/python_client/testcases/test_partition_20.py
Labels: sig/testing, size/XXL, approved, lgtm, area/test, ci-passed, dco-passed

#15551 Avoid to copy during converting C bytes to Go bytes
  internal/querynode/segment.go
  internal/util/cgoconverter/bytes_converter.go
  internal/util/cgoconverter/bytes_converter_test.go
  internal/util/cgoconverter/test_utils.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#15497 Make SessionWatch keep watch even no Rewatch func when find ErrCompacted
  internal/datacoord/server.go
  internal/datacoord/server_test.go
  internal/indexcoord/index_coord.go
  internal/indexcoord/index_coord_test.go
  internal/querycoord/query_coord.go
  internal/querycoord/query_coord_test.go
  internal/querynode/query_node.go
  internal/querynode/query_node_test.go
  internal/util/sessionutil/session_util.go
  internal/util/sessionutil/session_util_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#15586 [skip e2e]Update nightly to run twice & keep the same load with pr ci
  build/ci/jenkins/Nightly.groovy
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#15588 Upgrade pulsar from 2.7.3 to 2.8.2
  build/ci/jenkins/Nightly.groovy
  build/ci/jenkins/PR.groovy
  build/ci/jenkins/qa/PR.groovy
  deployments/docker/cluster/docker-compose.yml
  deployments/docker/dev/docker-compose.yml
  tests/scripts/values/pr.yaml
Labels: kind/improvement, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#15590 Fix testcase assertion
  tests/python_client/testcases/test_search_20.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#15598 [skip e2e]Add commit number check for pr
  .github/mergify.yml
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#15591 Upgrade pulsar image for apple silicon
  build/docker/pulsar/Dockerfile
  build/docker/pulsar/apply-config-from-env.py
  deployments/docker/dev/docker-compose-apple-silicon.yml
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#15595 [test]Fix testcase assertion
  tests/python_client/testcases/test_search_20.py
  tests/python_client/utils/util_pymilvus.py
Labels: kind/improvement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#15601 [skip e2e]Update deploy test and chaos test github action
  .github/workflows/deploy-test.yaml
  tests/python_client/chaos/cluster-values.yaml
  tests/python_client/deploy/cluster-values.yaml
  tests/python_client/deploy/test.sh
Labels: kind/improvement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#15603 Switch to knowhere v1.0.1 and forked gorocksdb v0.0.1
  Makefile
  go.mod
  go.sum
  internal/core/thirdparty/knowhere/CMakeLists.txt
Labels: kind/bug, area/dependency, size/XS, approved, lgtm, ci-passed, dco-passed, area/compilation

#15618 Use stash instead of clone code multi times
  build/ci/jenkins/PR.groovy
  build/ci/jenkins/qa/PR.groovy
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#15453 Add log when remove keys in garbage collector.
  internal/datacoord/garbage_collector.go
  internal/datacoord/meta.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#15542 Implement mix compaction logic
  internal/datacoord/compaction.go
  internal/datacoord/compaction_trigger.go
  internal/datacoord/compaction_trigger_test.go
  internal/datanode/compactor.go
  internal/proto/data_coord.proto
  internal/proto/datapb/data_coord.pb.go
Labels: kind/enhancement, size/XL, approved, lgtm, ci-passed, dco-passed

#15537 Extract segments info into a new struct.
  internal/querycoord/meta.go
  internal/querycoord/meta_test.go
  internal/querycoord/segments_info.go
  internal/querycoord/segments_info_test.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#15636 [skip e2e] Update milvus20vs1x.md
  milvus20vs1x.md
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#15631 Fix eventmanager retry interval
  internal/datanode/event_manager.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#15639 Update codecov.yml
  codecov.yml
  internal/datacoord/allocator.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#15626 Abandon using protobuf to pass binaryset parameter
  internal/core/CMakeLists.txt
  internal/core/src/common/CMakeLists.txt
  internal/core/src/common/vector_index_c.cpp
  internal/core/src/common/vector_index_c.h
  internal/core/src/indexbuilder/CMakeLists.txt
  internal/core/src/indexbuilder/IndexWrapper.cpp
  internal/core/src/indexbuilder/IndexWrapper.h
  internal/core/src/indexbuilder/index_c.cpp
  internal/core/src/indexbuilder/index_c.h
  internal/core/src/segcore/CMakeLists.txt
  internal/core/src/segcore/load_index_c.cpp
  internal/core/src/segcore/load_index_c.h
  internal/core/unittest/test_index_wrapper.cpp
  internal/indexnode/index.go
  internal/querynode/load_index_info.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed, area/compilation

#15602 [test]Update insert testcase from 1.0 to 2.0
  tests/python_client/testcases/entity/test_insert.py
  tests/python_client/testcases/test_insert.py
Labels: sig/testing, size/XXL, approved, lgtm, area/test, ci-passed, dco-passed

#15643 [test] upgrade collection testcase 1.x to 2.0.
  tests/python_client/testcases/test_collection.py
Labels: sig/testing, size/XXL, approved, lgtm, area/test, ci-passed, dco-passed

#15638 Add prometheus metrics for IndexCoord
  internal/indexcoord/index_coord.go
  internal/indexcoord/meta_table.go
  internal/indexcoord/node_manager.go
  internal/metrics/indexcoord_metrics.go
  internal/metrics/metrics.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#15664 [skip e2e]Add ccache support for mac code checker
  .github/workflows/code-checker.yaml
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#15673 [skip e2e]Add push for code checker
  .github/workflows/code-checker.yaml
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#15675 [skip e2e]Add ccache into install mac deps
  scripts/install_deps.sh
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#15581 Modify parameter spelling of task queue
  internal/proxy/task_scheduler.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#15678 [skip e2e]Add go mod cache & 3rd party cache
  .github/workflows/code-checker.yaml
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#15686 Update some comments for data coord with some minor code refactoring.
  internal/datacoord/channel_manager.go
  internal/datacoord/channel_manager_factory.go
  internal/datacoord/channel_store.go
  internal/datacoord/cluster.go
  internal/datacoord/cluster_test.go
  internal/datacoord/policy.go
  internal/datacoord/policy_test.go
  internal/datacoord/segment_manager.go
  internal/datacoord/server.go
  internal/datacoord/services.go
  internal/kv/kv.go
  internal/proxy/segment.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#15663 Change all fields in Expr to const to avoid modification
  internal/core/src/query/Expr.h
  internal/core/src/query/ExprImpl.h
  internal/core/src/query/Parser.cpp
  internal/core/src/query/PlanProto.cpp
  internal/core/src/query/visitors/ExecExprVisitor.cpp
  internal/core/unittest/test_c_api.cpp
  internal/core/unittest/test_get_entity_by_ids.cpp
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#15687 [skip e2e]Add third party cache
  .github/workflows/code-checker.yaml
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#15690 Fix data race in test
  internal/querycoord/impl_test.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#15680 [test] Add and update compaction cases
  tests/python_client/base/collection_wrapper.py
  tests/python_client/check/func_check.py
  tests/python_client/common/common_type.py
  tests/python_client/testcases/test_compaction.py
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#15701 Disable concurrent build for CI
  .github/workflows/jenkins-checker.yaml
  build/ci/jenkins/qa/PR.groovy
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#15693 [test] Modify the insert testcase
  tests/python_client/testcases/test_insert.py
Labels: sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#15700 Rename variable names for better readibility
  internal/core/src/common/Types.h
  internal/core/src/query/PlanImpl.h
  internal/core/src/query/PlanProto.h
  internal/core/src/query/SearchOnSealed.h
  internal/core/src/query/generated/ExecExprVisitor.h
  internal/core/src/query/generated/ExecPlanNodeVisitor.h
  internal/core/src/query/generated/ShowExprVisitor.h
  internal/core/src/query/generated/VerifyExprVisitor.h
  internal/core/src/query/visitors/ExecExprVisitor.cpp
  internal/core/src/query/visitors/ExecPlanNodeVisitor.cpp
  internal/core/src/query/visitors/ShowExprVisitor.cpp
  internal/core/src/segcore/SegmentGrowingImpl.cpp
  internal/core/src/segcore/SegmentGrowingImpl.h
  internal/core/src/segcore/SegmentInterface.h
  internal/core/src/segcore/SegmentSealedImpl.cpp
  internal/core/src/segcore/SegmentSealedImpl.h
  internal/core/src/segcore/TimestampIndex.cpp
  internal/core/src/segcore/TimestampIndex.h
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#15702 Fix DataCoord panics if message queue service quits before it
  internal/datacoord/server.go
  internal/datacoord/server_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#15647 Add web server in proxy with sample handler
  configs/milvus.yaml
  go.mod
  go.sum
  internal/distributed/proxy/httpserver/handler.go
  internal/distributed/proxy/httpserver/handler_test.go
  internal/distributed/proxy/httpserver/wrapper.go
  internal/distributed/proxy/httpserver/wrapper_test.go
  internal/distributed/proxy/service.go
  internal/distributed/proxy/service_test.go
  internal/util/paramtable/http_param.go
  internal/util/paramtable/http_param_test.go
Labels: kind/feature, area/dependency, size/L, approved, lgtm, ci-passed, dco-passed

#15709 Bump milvus version to 2.0.1
  deployments/binary/README.md
  deployments/docker/cluster/docker-compose.yml
  deployments/docker/standalone/docker-compose.yml
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#15698 [test]upgrade search case 1.x to 2.0
  tests/python_client/testcases/test_search_20.py
Labels: sig/testing, size/XL, approved, lgtm, area/test, ci-passed, dco-passed

#15706 [test] Modify the insert testcase
  tests/python_client/testcases/test_insert.py
Labels: sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#15715 Add more compaction test cases
  internal/datanode/compactor_test.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#15577 Update demo link in README
  README.md
  README_CN.md
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#15712 Fix a bug for where it appears that DEPLOY_MODE is get/used before set.
  cmd/roles/roles.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#15727 [skip e2e]Add ci-passed automaticaly for docs changed only
  .github/mergify.yml
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#15740 Fix wrong flushSegmentInfos in watchdmChannel request
  internal/querycoord/task.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#15541 Add and implement chunkManager interface
  internal/querynode/mock_test.go
  internal/querynode/query_collection.go
  internal/querynode/query_service.go
  internal/querynode/segment.go
  internal/storage/local_chunk_manager.go
  internal/storage/local_chunk_manager_test.go
  internal/storage/minio_chunk_manager.go
  internal/storage/minio_chunk_manager_test.go
  internal/storage/options.go
  internal/storage/types.go
  internal/storage/vector_chunk_manager.go
  internal/storage/vector_chunk_manager_test.go
  internal/util/errorutil/util.go
  internal/util/errorutil/util_test.go
  internal/util/mqclient/pulsar_client_test.go
  internal/util/retry/retry.go
Labels: kind/enhancement, size/XXL, approved, lgtm, ci-passed, dco-passed

#15738 Add ByteSlice Method for Etcd-kv
  internal/kv/etcd/etcd_kv.go
  internal/kv/etcd/etcd_kv_test.go
Labels: kind/enhancement, size/XL, approved, lgtm, ci-passed, dco-passed

#15748 Remove unused ValueKV
  internal/kv/kv.go
  internal/kv/kv_test.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#15737 Make Etcd log level configurable.
  configs/milvus.yaml
  internal/util/etcd/etcd_util.go
  internal/util/paramtable/service_param.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#15732 [KV]: Add methods to load/save bytes for MinIOKV
  internal/kv/minio/minio_kv.go
  internal/kv/minio/minio_kv_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#15749 [KV]: Add bytes methods for RocksdbKV
  internal/kv/rocksdb/rocksdb_kv.go
  internal/kv/rocksdb/rocksdb_kv_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#15753 Show events when install failed
  tests/scripts/install_milvus.sh
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#15761 [skip e2e]Add all pods kill chaos test
  .github/workflows/pod-kill-chaos-test.yaml
  tests/python_client/chaos/chaos_objects/pod_kill/chaos_allcluster_pod_kill.yaml
  tests/python_client/chaos/chaos_objects/pod_kill/chaos_allstandalone_pod_kill.yaml
  tests/python_client/chaos/chaos_objects/pod_kill/testcases.yaml
  tests/python_client/chaos/chaos_test.sh
  tests/python_client/chaos/constants.py
  tests/python_client/chaos/test_chaos.py
  tests/python_client/common/cus_resource_opts.py
  tests/python_client/utils/util_common.py
Labels: kind/improvement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#15760 Fix centos build error
  internal/core/thirdparty/knowhere/CMakeLists.txt
  internal/storage/payload.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed, area/compilation

#15725 Set BaseMsg for LoadSegmentRequest, prevent crashing in log printing
  internal/querynode/segment_loader.go
  internal/querynode/segment_loader_test.go
  internal/querynode/task.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#15614 Add Extract() method to take out C pointer from BytesConverter without releasing it
  internal/util/cgoconverter/bytes_converter.go
  internal/util/cgoconverter/bytes_converter_test.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed

#15759 Refine code of DataNode binlogIO
  internal/datanode/binlog_io.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#15707 Make compaction not generate empty segment
  internal/datacoord/meta.go
  internal/datacoord/meta_test.go
  internal/datanode/compactor.go
  internal/datanode/compactor_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#15752 Fix querycoord ut bug
  internal/querycoord/impl_test.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#15776 [skip e2e][test]Add io latency chaos
  .github/workflows/io-latency-chaos-test.yaml
  tests/python_client/chaos/chaos_objects/io_latency/chaos_etcd_io_latency.yaml
  tests/python_client/chaos/chaos_objects/io_latency/chaos_minio_io_latency.yaml
  tests/python_client/chaos/chaos_objects/io_latency/chaos_pulsar_io_latency.yaml
  tests/python_client/chaos/chaos_objects/io_latency/testcases.yaml
Labels: kind/improvement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#15606 Add Prometheus metrics for QueryCoord
  internal/metrics/metrics.go
  internal/metrics/querycoord.go
  internal/querycoord/cluster.go
  internal/querycoord/impl.go
  internal/querycoord/meta.go
  internal/querycoord/segments_info.go
  internal/querycoord/task.go
  internal/querycoord/task_scheduler.go
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#15726 Remove globalZapWrapper in logutil.go
  internal/util/logutil/logutil.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#15650 Add prometheus metrics for DataNode
  internal/datanode/compaction_executor.go
  internal/datanode/compactor.go
  internal/datanode/data_node.go
  internal/datanode/data_sync_service.go
  internal/datanode/flow_graph_dd_node.go
  internal/datanode/flow_graph_delete_node.go
  internal/datanode/flow_graph_dmstream_input_node.go
  internal/datanode/flow_graph_insert_buffer_node.go
  internal/datanode/flow_graph_insert_buffer_node_test.go
  internal/datanode/flow_graph_manager.go
  internal/datanode/flush_manager.go
  internal/datanode/segment_replica.go
  internal/metrics/datanode.go
  internal/metrics/metrics.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#15733 Add lru cache
  internal/storage/lru_cache.go
  internal/storage/lru_cache_test.go
Labels: kind/enhancement, size/XL, approved, lgtm, ci-passed, dco-passed
