Repository milvus-io/milvus, pull requests merged in 2022-09, with the labels that each got.

#18943 Refine grpc server options of interceptor
  internal/distributed/proxy/service.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#18919 Set max read concurrency ratio to improve concurrent read performance [cherry-pick #18911]
  configs/milvus.yaml
  internal/util/paramtable/component_param.go
  internal/util/paramtable/component_param_test.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#18957 [skip e2e] Optimize test_reduce
  internal/core/unittest/test_reduce.cpp
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#18934 Fix random test case failure by empty string
  internal/proxy/mock_test.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#18966 [skip e2e] Keep 2.1.0 to use 18.04
  .github/mergify.yml
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#18960 Change ci namespace from jenkins to milvus-ci && Remove old jenkins
  .github/workflows/jenkins-checker.yaml
  build/ci/jenkins/Nightly.groovy
  build/ci/jenkins/PR.groovy
  build/ci/jenkins/PublishImages.groovy
  build/ci/jenkins/pod/rte.yaml
  ci/jenkins/pod/e2e.yaml
  ci/jenkins/pod/rte.yaml
Labels: kind/improvement, size/XL, approved, lgtm, ci-passed, dco-passed

#18969 [skip e2e] Update mergify rule with MacOS 12
  .github/mergify.yml
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#18953 Fix RocksMQ flaky test
  internal/mq/mqimpl/rocksmq/server/rocksmq_retention_test.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#18967 [skip e2e] Add more testcases with different parameter combinations in test_reduce
  internal/core/unittest/test_reduce.cpp
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#18912 Remove label of cases that have been solved
  tests/python_client/testcases/test_collection.py
  tests/python_client/testcases/test_search.py
  tests/python_client/testcases/test_utility.py
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#18918 Resolve the warnings of case test_search_binary_tanimoto_flat_index
  tests/python_client/common/common_func.py
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#18965 Add more cases to test shard_num valid range
  tests/python_client/testcases/test_collection.py
Labels: sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#18959 Fix bug for umarshal index model
  internal/indexcoord/meta_table.go
  internal/metastore/model/index.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed

#18950 Add limit to proto
  internal/proto/internal.proto
  internal/proto/internalpb/internal.pb.go
  internal/proto/milvus.proto
  internal/proto/milvuspb/milvus.pb.go
  internal/proxy/task.go
  internal/proxy/task_query.go
  internal/proxy/task_query_test.go
Labels: area/api, size/XXL, approved, lgtm, ci-passed, area/internal-api, dco-passed

#18954 Fix RocksMQ flaky test
  internal/mq/mqimpl/rocksmq/server/rocksmq_retention_test.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed

#18942 Update rate limit test file
  tests/python_client/common/common_func.py
  tests/python_client/common/common_type.py
  tests/python_client/rate_limit/test_rate_limit.py
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#18775 Use segment statslog instead of separate statslog
  internal/datacoord/meta.go
  internal/datacoord/server.go
  internal/datanode/binlog_io.go
  internal/datanode/binlog_io_test.go
  internal/datanode/compactor.go
  internal/datanode/compactor_test.go
  internal/datanode/flow_graph_insert_buffer_node.go
  internal/datanode/flush_manager.go
  internal/datanode/flush_manager_test.go
  internal/datanode/meta_util.go
  internal/datanode/segment_replica.go
  internal/datanode/segment_replica_test.go
  internal/querynode/segment_loader.go
Labels: kind/enhancement, size/XL, approved, lgtm, ci-passed, dco-passed

#18975 Add InvalidNodeID logic to remove segments from offline segments
  internal/common/common.go
  internal/querynode/impl_test.go
  internal/querynode/shard_cluster.go
  internal/querynode/shard_cluster_service_test.go
  internal/querynode/shard_cluster_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#18981 Improve log of datanode compactor
  internal/datanode/compactor.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#18990 [Cherry-Pick] Add InvalidNodeID logic to remove offline segments
  internal/common/common.go
  internal/querynode/impl_test.go
  internal/querynode/shard_cluster.go
  internal/querynode/shard_cluster_service_test.go
  internal/querynode/shard_cluster_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#18947 fix restart querycoord blocking issue (#18801)
  internal/querycoord/task_scheduler.go
  internal/querycoord/task_scheduler_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#18998 [skip e2e] Update mergify rule for 2.1.*
  .github/mergify.yml
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#18962 Add metrics for etcd
  cmd/roles/roles.go
  internal/kv/etcd/etcd_kv.go
  internal/kv/etcd/etcd_kv_test.go
  internal/metrics/etcd_metrics.go
  internal/metrics/metrics_test.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#18983 Add describe in ci logs
  tests/scripts/uninstall_milvus.sh
Labels: kind/improvement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#18997 Update the database initialization script for nightly test
  tests/scripts/values/mysql.yaml
Labels: sig/testing, size/XL, approved, lgtm, area/test, ci-passed, dco-passed

#18980 Fix the error of the search case reporting unmatched limit
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#18989 Update pymilvus version
  tests/python_client/requirements.txt
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#19000 Make DescribeCollection return collectionName
  internal/proxy/task.go
  internal/proxy/task_test.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#19002 Make DescribeCollection return collectionName [cherry-pick#19000]
  internal/proxy/task.go
  internal/proxy/task_test.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#18955 Return nil error when handling grpc request
  internal/proxy/impl.go
  internal/proxy/privilege_interceptor.go
  internal/proxy/proxy_test.go
  internal/rootcoord/root_coord.go
  internal/util/funcutil/policy.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#19005 Set insert&stats binlog timestamp range
  internal/datanode/flow_graph_insert_buffer_node.go
  internal/datanode/flow_graph_insert_buffer_node_test.go
  internal/datanode/flush_manager.go
  internal/storage/utils.go
  internal/storage/utils_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#18935 Upgrade to knowhere-v1.3.0, remove seldom used index types
  internal/core/src/indexbuilder/VecIndexCreator.cpp
  internal/core/src/indexbuilder/utils.cpp
  internal/core/src/indexbuilder/utils.h
  internal/core/src/query/deprecated/ValidationUtil.cpp
  internal/core/src/query/visitors/VerifyPlanNodeVisitor.cpp
  internal/core/thirdparty/knowhere/CMakeLists.txt
  internal/core/unittest/test_index_wrapper.cpp
  internal/core/unittest/test_utils/indexbuilder_test_utils.h
  internal/util/indexcgowrapper/index_test.go
  tests/benchmark/milvus_benchmark/client.py
  tests/python_client/common/common_func.py
  tests/python_client/common/common_type.py
  tests/python_client/deploy/common.py
  tests/python_client/deploy/scripts/utils.py
  tests/python_client/testcases/test_collection.py
  tests/python_client/testcases/test_search.py
  tests/python_client/utils/util_pymilvus.py
Labels: kind/improvement, sig/testing, size/XL, approved, lgtm, area/test, ci-passed, dco-passed, area/compilation

#18996 [Cherry-Pick] Unify rootPath in configs and ChunkManager
  internal/common/common.go
  internal/datanode/binlog_io.go
  internal/datanode/binlog_io_test.go
  internal/datanode/data_node.go
  internal/datanode/flow_graph_delete_node_test.go
  internal/datanode/flush_manager.go
  internal/indexcoord/garbage_collector.go
  internal/indexcoord/index_builder.go
  internal/indexcoord/index_coord_mock.go
  internal/indexnode/task.go
  internal/indexnode/task_test.go
  internal/storage/local_chunk_manager.go
  internal/storage/local_chunk_manager_test.go
  internal/storage/minio_chunk_manager.go
  internal/storage/minio_chunk_manager_test.go
  internal/storage/types.go
  internal/storage/vector_chunk_manager.go
  internal/storage/vector_chunk_manager_test.go
  internal/util/importutil/import_wrapper_test.go
  internal/util/paramtable/component_param.go
  internal/util/paramtable/component_param_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#19009 Add kafka metics dashboard
  deployments/monitor/grafana/kafka-dashboard.json
Labels: kind/improvement, size/XXL, approved, lgtm, ci-passed, dco-passed, manual-pass

#18971 Fix typo for index code
  internal/indexcoord/flush_segment_watcher.go
  internal/indexcoord/index_builder.go
  internal/indexcoord/meta_table.go
  internal/indexcoord/meta_table_test.go
  internal/proto/index_coord.proto
  internal/proto/indexpb/index_coord.pb.go
Labels: size/XL, approved, lgtm, ci-passed, area/internal-api, dco-passed

#19021 [skip e2e] Add push for 2.*.*
  .github/workflows/code-checker.yaml
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#18991 [Cherry-Pick] Use segment statslog instead of separate statslog
  internal/datacoord/meta.go
  internal/datacoord/server.go
  internal/datanode/binlog_io.go
  internal/datanode/binlog_io_test.go
  internal/datanode/compactor.go
  internal/datanode/compactor_test.go
  internal/datanode/flow_graph_insert_buffer_node.go
  internal/datanode/flush_manager.go
  internal/datanode/flush_manager_test.go
  internal/datanode/meta_util.go
  internal/datanode/segment_replica.go
  internal/datanode/segment_replica_test.go
  internal/querynode/segment_loader.go
  internal/storage/primary_key.go
Labels: kind/enhancement, size/XL, approved, lgtm, ci-passed, dco-passed

#19020 Fix the `Flush` privilege can't be granted
  internal/proxy/privilege_interceptor.go
  internal/proxy/privilege_interceptor_test.go
  internal/util/funcutil/policy.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#19028 [test] Add load balance verify in querynode scale test
  build/ci/jenkins/Scale.groovy
  build/ci/jenkins/pod/scale-test.yaml
  tests/python_client/scale/test_index_node_scale.py
  tests/python_client/scale/test_query_node_scale.py
Labels: kind/improvement, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#19031 [test] Update some index related cases
  tests/python_client/base/collection_wrapper.py
  tests/python_client/base/index_wrapper.py
  tests/python_client/testcases/test_index.py
  tests/python_client/testcases/test_utility.py
Labels: kind/improvement, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#19010 [Cherry-Pick] Set insert&stats binlog timestamp range (#19005)
  internal/datanode/flow_graph_insert_buffer_node.go
  internal/datanode/flow_graph_insert_buffer_node_test.go
  internal/datanode/flush_manager.go
  internal/storage/utils.go
  internal/storage/utils_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#18902 Optimize segcore Reduce
  internal/core/src/segcore/Reduce.cpp
  internal/core/src/segcore/Reduce.h
  internal/core/unittest/test_c_api.cpp
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#19025 Remove redundant parameter for segcore Search()
  internal/core/src/segcore/segment_c.cpp
  internal/core/src/segcore/segment_c.h
  internal/core/unittest/test_c_api.cpp
  internal/querynode/segment.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#19036 [skip e2e] Fail ci when upload codecov report failed
  .github/workflows/main.yaml
Labels: size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#19026 Fill index size and fail reason when query index job
  internal/distributed/indexnode/client/client_test.go
  internal/distributed/indexnode/service_test.go
  internal/indexcoord/flush_segment_watcher.go
  internal/indexcoord/index_builder.go
  internal/indexcoord/index_coord.go
  internal/indexnode/chunk_mgr_factory.go
  internal/indexnode/indexnode.go
  internal/indexnode/indexnode_service.go
  internal/indexnode/indexnode_service_test.go
  internal/indexnode/task.go
  internal/indexnode/task_scheduler.go
  internal/indexnode/task_scheduler_test.go
  internal/indexnode/taskinfo_ops.go
  internal/proto/index_coord.proto
  internal/proto/indexpb/index_coord.pb.go
  internal/types/types.go
Labels: size/L, approved, lgtm, ci-passed, area/internal-api, dco-passed

#19052 [skip e2e]Change the rate unit from minutes to seconds for dashboard
  deployments/monitor/grafana/milvus-dashboard.json
Labels: kind/improvement, size/XXL, approved, lgtm, ci-passed, dco-passed

#19060 Execute triggerTask in order of generation time
  internal/querycoord/task_scheduler.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed

#19045 Fix the error of the search case reporting unmatched limit
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#19069 [skip e2e] Ignore auto-generated mock files coverage
  codecov.yml
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#18738 [test]Add testcase for chaos test
  tests/python_client/chaos/testcases/test_single_request_operation.py
  tests/python_client/chaos/testcases/test_verify_all_collections.py
Labels: kind/improvement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#19064 Add triggerQueue check for handoff verifyReq
  internal/mocks/mock_datacoord.go
  internal/mocks/mock_rootcoord.go
  internal/querycoord/global_meta_broker.go
  internal/querycoord/global_meta_broker_test.go
  internal/querycoord/handoff_handler.go
  internal/querycoord/handoff_handler_test.go
  internal/querycoord/query_coord_test.go
Labels: kind/bug, size/XXL, approved, lgtm, ci-passed, dco-passed, manual-pass

#19080 [Cherry-pick] Add triggerQueue check for handoff verifyReq
  internal/mocks/mock_datacoord.go
  internal/mocks/mock_rootcoord.go
  internal/querycoord/global_meta_broker.go
  internal/querycoord/global_meta_broker_test.go
  internal/querycoord/handoff_handler.go
  internal/querycoord/handoff_handler_test.go
  internal/querycoord/query_coord_test.go
Labels: kind/bug, size/XXL, approved, lgtm, ci-passed, dco-passed, manual-pass

#19067 fix goroutine leak in querycoord
  internal/querycoord/task_scheduler.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#19024 Remove deprecated inner compaction type
  internal/datacoord/compaction.go
  internal/datacoord/compaction_test.go
  internal/datacoord/meta.go
  internal/datacoord/meta_test.go
  internal/datanode/compactor.go
  internal/datanode/compactor_test.go
  internal/proto/data_coord.proto
  internal/proto/datapb/data_coord.pb.go
Labels: kind/improvement, size/XL, approved, lgtm, ci-passed, dco-passed

#19054 [test] Add load balance verify in querynode scale test
  build/ci/jenkins/Scale.groovy
  build/ci/jenkins/pod/scale-test.yaml
  tests/python_client/scale/test_index_node_scale.py
  tests/python_client/scale/test_query_node_scale.py
Labels: kind/improvement, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#19063 add rbac test cases
  tests/python_client/base/utility_wrapper.py
  tests/python_client/check/func_check.py
  tests/python_client/common/common_type.py
  tests/python_client/testcases/test_utility.py
Labels: sig/testing, size/XXL, approved, lgtm, area/test, ci-passed, dco-passed

#19082 Not allow '$' in collection/partition/field name
  internal/proxy/util.go
  internal/proxy/util_test.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#19091 Not allow '$' in collection/partition/field name
  internal/proxy/util.go
  internal/proxy/util_test.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed

#19096 Make minioChunkManager ListObject level by level when recursive is true
  internal/storage/minio_chunk_manager.go
  internal/storage/minio_chunk_manager_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#19101 Fix git safe issue
  Makefile
Labels: size/XS, approved, lgtm, ci-passed, dco-passed, area/compilation

#19076 Schedule index building tasks orderly instead of randomly
  internal/indexcoord/index_builder.go
  internal/indexcoord/index_coord_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#19108 Add submodule unit test command entry
  Makefile
  scripts/run_go_unittest.sh
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed, area/compilation

#19112 [Cherry-pick] Make minioChunkManager ListObject level by level (#19096)
  internal/storage/minio_chunk_manager.go
  internal/storage/minio_chunk_manager_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#19103 Update the code of Load collection failure
  tests/python_client/testcases/test_collection.py
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#19120 Add missed unittest of querycoord
  scripts/run_go_unittest.sh
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#19100 Improve the `close` method in the graph
  internal/util/flowgraph/flow_graph.go
  internal/util/flowgraph/input_node.go
  internal/util/flowgraph/input_node_test.go
  internal/util/flowgraph/message.go
  internal/util/flowgraph/node.go
  internal/util/flowgraph/node_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#18888 Disable pulsar batching and make MaxPublishDelay higher to avoid high cpu consumption
  internal/mq/msgstream/mq_kafka_msgstream_test.go
  internal/mq/msgstream/mq_msgstream.go
  internal/mq/msgstream/mqwrapper/pulsar/pulsar_client.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#19132 [test] Update query with bool field case
  tests/python_client/requirements.txt
  tests/python_client/testcases/test_query.py
Labels: sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#19075 Only store segmentID for flushed segments event
  internal/datacoord/errors.go
  internal/datacoord/errors_test.go
  internal/datacoord/services.go
  internal/indexcoord/errors.go
  internal/indexcoord/errors_test.go
  internal/indexcoord/flush_segment_watcher.go
  internal/indexcoord/flushed_segment_watcher_test.go
  internal/indexcoord/index_builder.go
  internal/indexcoord/index_builder_test.go
  internal/indexcoord/index_coord.go
  internal/indexcoord/index_coord_mock.go
  internal/indexcoord/index_coord_test.go
  internal/indexcoord/meta_table.go
  internal/indexcoord/meta_table_test.go
  internal/indexnode/indexnode_service.go
  internal/indexnode/taskinfo_ops.go
  internal/metastore/kv/datacoord/kv_catalog.go
  internal/metastore/kv/indexcoord/constant.go
  internal/metastore/kv/indexcoord/kv_catalog.go
  internal/querynode/segment_loader.go
Labels: size/XXL, approved, lgtm, ci-passed, dco-passed

#19134 Remove debug log in minio chunk manager
  internal/storage/minio_chunk_manager.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#19111 Support input empty string
  internal/proxy/mock_test.go
  internal/proxy/task_insert.go
  internal/proxy/task_insert_test.go
  internal/storage/payload.go
  internal/storage/payload_cgo_test.go
  internal/storage/payload_test.go
  tests/python_client/testcases/test_insert.py
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#19148 Fix Cgo lock os thread failed
  internal/querynode/query_node.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#19135 [Cherry-Pick] Remove debug log in minio chunk manager
  internal/storage/minio_chunk_manager.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#19131 [cherry-pick]Add describe in ci logs (#18983)
  tests/scripts/uninstall_milvus.sh
Labels: kind/improvement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#19144 Support input empty string
  internal/storage/payload.go
  internal/storage/payload_cgo_test.go
  internal/storage/payload_test.go
  tests/python_client/testcases/test_insert.py
Labels: sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#19140 Fix bloom filter size not match
  internal/datanode/compactor.go
  internal/datanode/compactor_test.go
  internal/datanode/flow_graph_dd_node.go
  internal/datanode/flow_graph_dd_node_test.go
  internal/datanode/flow_graph_delete_node.go
  internal/datanode/flow_graph_delete_node_test.go
  internal/datanode/flow_graph_insert_buffer_node.go
  internal/datanode/flow_graph_insert_buffer_node_test.go
  internal/datanode/flow_graph_node.go
  internal/datanode/segment_replica.go
  internal/datanode/segment_replica_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#19122 Optimize openblas compile flags
  build/docker/openblas/ubuntu20.04/Dockerfile
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#19186 [skip e2e] Modify chart version and enable profiling
  ci/jenkins/Nightly.groovy
Labels: kind/improvement, approved, lgtm, ci-passed, dco-passed

#19116 Update pymilvus version
  tests/python_client/requirements.txt
  tests/python_client/testcases/test_collection.py
  tests/python_client/testcases/test_index.py
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#19178 Make sure that closing the graph is more secure
  internal/util/flowgraph/flow_graph.go
  internal/util/flowgraph/node.go
  internal/util/flowgraph/node_test.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#18894 Enable sort for segcore RetrieveResults
  internal/querynode/mock_test.go
  internal/querynode/query_shard_test.go
  internal/querynode/result.go
  internal/querynode/result_sorter.go
  internal/querynode/result_sorter_test.go
  internal/querynode/result_test.go
  internal/querynode/segment.go
  internal/querynode/segment_test.go
  internal/querynode/shard_cluster.go
  internal/querynode/task_query.go
  internal/util/typeutil/schema.go
  internal/util/typeutil/schema_test.go
Labels: size/XL, approved, lgtm, ci-passed, dco-passed

#19133 [test] Update query with bool field case
  tests/python_client/testcases/test_query.py
Labels: sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#18726 [skip e2e] Update export logs to support time range
  deployments/export-log/README.md
  deployments/export-log/export-milvus-log.sh
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#19198 [skip e2e]Add script to export log for Milvus deployed by operator
  tests/scripts/export_log_k8s_for_operator.sh
Labels: kind/improvement, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#19196 [skip e2e]Add diakann index dependency
  build/docker/builder/cpu/centos7/Dockerfile
  build/docker/milvus/centos7/Dockerfile
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#19194 [test]Make secure param as bool type
  tests/python_client/conftest.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#19044 Enable search with pagination
  internal/proxy/task_search.go
  internal/proxy/task_search_test.go
Labels: size/XL, approved, lgtm, ci-passed, dco-passed

#19193 Bump milvus helm version to 3.1.11
  ci/jenkins/PR.groovy
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#19202 [skip e2e]Optimize openblas compile in pod
  build/docker/openblas/ubuntu20.04/Dockerfile
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#19163 Don't mark index tasks as deleted when segment is compacted
  internal/indexcoord/flush_segment_watcher.go
  internal/indexcoord/flushed_segment_watcher_test.go
  internal/indexcoord/garbage_collector.go
  internal/indexcoord/garbage_collector_test.go
  internal/indexcoord/index_builder.go
  internal/indexcoord/index_coord.go
  internal/indexcoord/meta_table.go
  internal/indexcoord/meta_table_test.go
  internal/indexcoord/node_manager_test.go
  internal/indexcoord/task_state.go
Labels: size/XXL, approved, lgtm, ci-passed, dco-passed

#19210 Remove useless ut.
  internal/util/tsoutil/tso_test.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#18948 Add merger for retrieve results
  internal/querynode/result.go
  internal/querynode/result_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#19209 [skip e2e] Update builder image for new openblas
  build/docker/builder/cpu/ubuntu20.04/Dockerfile
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#19197 Optimize large memory usage of Variant used in InsertRecord
  internal/core/src/common/Types.h
  internal/core/src/segcore/InsertRecord.cpp
  internal/core/src/segcore/InsertRecord.h
  internal/core/unittest/test_segcore.cpp
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#19204 Fix log print
  internal/proxy/task.go
  internal/proxy/task_statistic.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#19062 Guarantee flushed segments are all indexed
  codecov.yml
  internal/datacoord/compaction_trigger.go
  internal/datacoord/compaction_trigger_test.go
  internal/datacoord/garbage_collector.go
  internal/datacoord/garbage_collector_test.go
  internal/datacoord/handler.go
  internal/datacoord/meta.go
  internal/datacoord/server.go
  internal/datacoord/server_test.go
  internal/datacoord/services.go
  internal/datacoord/util.go
  internal/datacoord/util_test.go
  internal/distributed/datacoord/service.go
  internal/distributed/datacoord/service_test.go
  internal/mocks/mock_indexcoord.go
  internal/querycoord/global_meta_broker.go
  internal/querycoord/task_test.go
  internal/types/types.go
  tests/python_client/testcases/test_collection.py
  tests/python_client/testcases/test_compaction.py
  tests/python_client/testcases/test_delete.py
  tests/python_client/testcases/test_utility.py
Labels: kind/improvement, sig/testing, size/XXL, approved, lgtm, area/test, ci-passed, dco-passed

#19207 Decrease build time by removing compiling openblas
  .env
  build/docker/milvus/ubuntu20.04/Dockerfile
  internal/core/thirdparty/knowhere/CMakeLists.txt
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed, area/compilation, manual-pass

#19251 Mix start with more role
  cmd/milvus/run.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#19215 Romove the xfail label of test_annoy_index
  tests/python_client/testcases/test_index.py
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#19184 Add cases to check the interface update_password
  tests/python_client/testcases/test_utility.py
Labels: sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#19228 [skip e2e]Move a script to tests dir
  tests/scripts/docker_image_find_tag.sh
Labels: kind/improvement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#19252 [skip e2e] Add unzip tool
  build/docker/builder/cpu/centos7/Dockerfile
  build/docker/builder/cpu/ubuntu18.04/Dockerfile
  build/docker/builder/cpu/ubuntu20.04/Dockerfile
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#19227 Add error log for load segment file failure
  internal/mocks/mock_chunk_manager.go
  internal/querynode/segment_loader.go
  internal/querynode/segment_loader_test.go
Labels: kind/improvement, size/XL, approved, lgtm, ci-passed, dco-passed

#19260 Disable kafka msgstream ut
  internal/mq/msgstream/mq_kafka_msgstream_test.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#19278 [skip e2e]Implement the `hook` interceptor
  api/milvuspb/milvus.pb.go
  configs/hook.yaml
  internal/datacoord/mock_test.go
  internal/distributed/proxy/client/client.go
  internal/distributed/proxy/service.go
  internal/distributed/proxy/service_test.go
  internal/distributed/rootcoord/client/client.go
  internal/distributed/rootcoord/service.go
  internal/mocks/mock_rootcoord.go
  internal/proto/milvus.proto
  internal/proto/proxy.proto
  internal/proto/proxypb/proxy.pb.go
  internal/proto/root_coord.proto
  internal/proto/rootcoordpb/root_coord.pb.go
  internal/proxy/hook_interceptor.go
  internal/proxy/impl.go
  internal/proxy/meta_cache.go
  internal/proxy/rootcoord_mock_test.go
  internal/rootcoord/proxy_client_manager.go
  internal/rootcoord/root_coord.go
  internal/types/types.go
  internal/util/mock/grpc_proxy_client.go
  internal/util/mock/grpc_rootcoord_client.go
  internal/util/paramtable/base_table.go
  internal/util/paramtable/component_param.go
  internal/util/paramtable/hook_config.go
Labels: kind/improvement, area/api, size/XXL, area/internal-api

#19242 Disable quota and limits
  configs/milvus.yaml
  internal/proxy/multi_rate_limiter_test.go
  internal/util/paramtable/quota_param_test.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#19249 Fix querynode data distribution return false positive dm channel
  internal/querycoordv2/checkers/segment_checker.go
  internal/querycoordv2/meta/channel_dist_manager.go
  internal/querycoordv2/meta/channel_dist_manager_test.go
  internal/querynode/impl.go
  internal/querynode/shard_cluster.go
  tests/python_client/testcases/test_utility.py
Labels: kind/bug, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed, manual-pass

#19240 Fix data race in querycoordv2
  internal/querycoordv2/mocks/querynode.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed

#19237 Refine logs in job
  internal/querycoordv2/checkers/segment_checker.go
  internal/querycoordv2/job/job.go
Labels: kind/bug, kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#19214 fix test unstable
  internal/log/log_test.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#19239 Remove incorrect formatting, unused conditions
  internal/datacoord/handler.go
  internal/datacoord/services.go
  tests/python_client/testcases/test_compaction.py
  tests/python_client/testcases/test_delete.py
  tests/python_client/testcases/test_utility.py
Labels: kind/improvement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#19292 Move growing segments to leaderview in GetDataDistributionResponse
  internal/proto/query_coord.proto
  internal/proto/querypb/query_coord.pb.go
  internal/querycoordv2/dist/dist_handler.go
  internal/querynode/impl.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, area/internal-api, dco-passed

#19295 Increase nightly master running time
  ci/jenkins/Nightly.groovy
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#19267 [test]Reduce collections that need verify
  tests/python_client/chaos/testcases/test_get_collections.py
Labels: kind/improvement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#19231 Enable query pagination
  internal/proxy/task_query.go
  internal/proxy/task_query_test.go
  internal/querynode/impl.go
  internal/querynode/result.go
  internal/querynode/result_test.go
  internal/querynode/task_query.go
  internal/util/typeutil/schema.go
  internal/util/typeutil/type.go
Labels: size/XL, approved, lgtm, ci-passed, dco-passed

#19222 Add policy to seal long time idle segment
  configs/milvus.yaml
  internal/datacoord/segment_allocation_policy.go
  internal/datacoord/segment_allocation_policy_test.go
  internal/datacoord/segment_info.go
  internal/datacoord/segment_manager.go
  internal/datacoord/util.go
  internal/datacoord/util_test.go
  internal/util/paramtable/component_param.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#19283 Handle multiple parquet RowGroup/Column
  internal/storage/payload_reader.go
  internal/storage/payload_reader_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#19293 Refine etcd config for docker-compose
  deployments/docker/cluster/docker-compose-apple-silicon.yml
  deployments/docker/cluster/docker-compose.yml
  deployments/docker/dev/docker-compose-apple-silicon.yml
  deployments/docker/dev/docker-compose.yml
  deployments/docker/standalone/docker-compose.yml
  docker-compose.yml
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#19281 [test]Update testcase
  tests/python_client/chaos/testcases/test_concurrent_operation.py
  tests/python_client/chaos/testcases/test_single_request_operation.py
  tests/python_client/chaos/testcases/test_verify_all_collections.py
Labels: kind/improvement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#19287 Add the string testcase
  tests/python_client/testcases/test_delete.py
  tests/python_client/testcases/test_index.py
  tests/python_client/testcases/test_insert.py
  tests/python_client/testcases/test_query.py
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#19234 Merge load segment tasks to improve performance
  internal/querycoordv2/job/scheduler.go
  internal/querycoordv2/server.go
  internal/querycoordv2/session/cluster.go
  internal/querycoordv2/session/cluster_test.go
  internal/querycoordv2/session/task.go
  internal/querycoordv2/task/executor.go
  internal/querycoordv2/task/merge_task.go
  internal/querycoordv2/task/merger.go
  internal/querycoordv2/task/merger_test.go
  internal/querycoordv2/task/mock_scheduler.go
  internal/querycoordv2/task/scheduler.go
  internal/querycoordv2/task/task_test.go
  internal/util/typeutil/group_scheduler.go
Labels: kind/improvement, size/XL, approved, lgtm, ci-passed, dco-passed, manual-pass

#19279 Make ddl follow tt mechanism
  internal/rootcoord/broker.go
  internal/rootcoord/broker_test.go
  internal/rootcoord/create_collection_task.go
  internal/rootcoord/create_partition_task.go
  internal/rootcoord/ddl_ts_lock_manager.go
  internal/rootcoord/ddl_ts_lock_manager_test.go
  internal/rootcoord/drop_collection_task.go
  internal/rootcoord/drop_collection_task_test.go
  internal/rootcoord/drop_partition_task.go
  internal/rootcoord/drop_partition_task_test.go
  internal/rootcoord/garbage_collector.go
  internal/rootcoord/garbage_collector_test.go
  internal/rootcoord/mock_test.go
  internal/rootcoord/redo.go
  internal/rootcoord/redo_test.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
  internal/rootcoord/scheduler.go
  internal/rootcoord/scheduler_test.go
  internal/rootcoord/step.go
  internal/rootcoord/step_executor.go
  internal/rootcoord/step_executor_test.go
  internal/rootcoord/timeticksync.go
  internal/rootcoord/timeticksync_test.go
  internal/rootcoord/undo.go
  internal/rootcoord/undo_test.go
Labels: size/XXL, approved, lgtm, ci-passed, dco-passed

#19230 All indexes segments both write handoff
  internal/indexcoord/flush_segment_watcher.go
  internal/indexcoord/flushed_segment_watcher_test.go
  internal/indexcoord/handoff.go
  internal/indexcoord/handoff_test.go
  internal/indexcoord/index_coord.go
  internal/indexcoord/index_coord_test.go
  internal/indexcoord/meta_table.go
  internal/indexcoord/task.go
  internal/indexcoord/util.go
  internal/metastore/model/segment_index.go
  internal/proto/data_coord.proto
  internal/proto/datapb/data_coord.pb.go
  internal/proto/index_coord.proto
  internal/proto/indexpb/index_coord.pb.go
  internal/querycoordv2/observers/handoff_observer.go
Labels: size/XXL, approved, lgtm, ci-passed, area/internal-api, dco-passed

#19320 [test]Fix chaos testcases
  tests/python_client/chaos/conftest.py
  tests/python_client/chaos/testcases/test_all_collections_after_chaos.py
  tests/python_client/chaos/testcases/test_concurrent_operation.py
  tests/python_client/chaos/testcases/test_single_request_operation.py
  tests/python_client/chaos/testcases/test_verify_all_collections.py
Labels: kind/improvement, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#19318 Fix Load returns incorrect error code
  internal/querycoordv2/handlers.go
  internal/querycoordv2/job/errors.go
  internal/querycoordv2/job/job.go
  internal/querycoordv2/job/job_test.go
  internal/querycoordv2/services.go
  internal/querycoordv2/services_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#19347 Add loading list filter logic for load segments
  internal/querynode/meta_replica.go
  internal/querynode/meta_replica_test.go
  internal/querynode/task.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#19326 Set default slice size for scalar index
  internal/core/src/indexbuilder/ScalarIndexCreator.cpp
  internal/core/src/indexbuilder/ScalarIndexCreator.h
  internal/core/src/indexbuilder/VecIndexCreator.cpp
  internal/core/src/indexbuilder/parse.h
  internal/core/unittest/CMakeLists.txt
  internal/core/unittest/test_config_parse.cpp
Labels: size/L, approved, lgtm, ci-passed, dco-passed, area/compilation, manual-pass

#19360 Fix SyncDistribution set Action
  internal/querynode/impl.go
  internal/querynode/impl_test.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#19353 Fix garbage collection on the wrong path
  cmd/milvus/mck.go
  internal/datacoord/server.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#19330 Increase timeout of load segment task
  configs/milvus.yaml
  internal/querycoordv2/handlers.go
  internal/util/paramtable/component_param.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#19322 Add collectionID when checking collection load
  internal/proxy/meta_cache.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#19340 Fix deadlock
  internal/datacoord/compaction_trigger.go
  internal/datacoord/util.go
  tests/python_client/testcases/test_compaction.py
Labels: kind/bug, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed, manual-pass

#19358 Remove manual balance timeout
  internal/querycoordv2/handlers.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#19362 Fix drop collection failed due to etcd txn limit.
  internal/metastore/kv/rootcoord/kv_catalog.go
  internal/rootcoord/drop_collection_task.go
  internal/rootcoord/drop_partition_task.go
  internal/rootcoord/garbage_collector.go
  internal/rootcoord/meta_table.go
  internal/rootcoord/step.go
  internal/rootcoord/step_executor.go
  internal/rootcoord/step_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#19368 Compaction requires the source segments indexed
  internal/datacoord/compaction_trigger.go
  internal/datacoord/compaction_trigger_test.go
  internal/datacoord/server_test.go
  internal/datacoord/util.go
  internal/datacoord/util_test.go
  internal/util/typeutil/data_format.go
  tests/python_client/testcases/test_compaction.py
Labels: kind/improvement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#19371 fix test_compact_manual_and_auto random failed
  tests/python_client/testcases/test_compaction.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#19380 [skip e2e] Disable test cases
  tests/python_client/testcases/test_search.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#19369 Fix L2 string case logic
  tests/python_client/testcases/test_search.py
Labels: kind/improvement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#19022 Drop segment indexes when drop partition
  internal/distributed/indexcoord/client/client_test.go
  internal/distributed/indexcoord/service_test.go
  internal/indexcoord/flushed_segment_watcher_test.go
  internal/indexcoord/garbage_collector.go
  internal/indexcoord/index_coord.go
  internal/indexcoord/index_coord_test.go
  internal/indexcoord/meta_table.go
  internal/indexcoord/meta_table_test.go
  internal/proto/index_coord.proto
  internal/proto/indexpb/index_coord.pb.go
  internal/proxy/task.go
  internal/rootcoord/broker.go
  internal/rootcoord/broker_test.go
  internal/rootcoord/drop_collection_task.go
  internal/rootcoord/drop_collection_task_test.go
  internal/rootcoord/drop_partition_task.go
  internal/rootcoord/drop_partition_task_test.go
  internal/rootcoord/garbage_collector.go
  internal/rootcoord/garbage_collector_test.go
  internal/rootcoord/mock_test.go
  internal/rootcoord/step.go
Labels: size/XL, approved, lgtm, ci-passed, area/internal-api, dco-passed

#19150 Add more log when creating index, Finished/Failed index will not be c…
  internal/indexnode/indexnode_service.go
  internal/indexnode/indexnode_service_test.go
  internal/indexnode/task.go
  internal/indexnode/task_scheduler.go
  internal/indexnode/taskinfo_ops.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#19294 Implement the `hook` interceptor
  api/hook/hook.go
  configs/hook.yaml
  internal/core/thirdparty/rocksdb/CMakeLists.txt
  internal/distributed/proxy/service.go
  internal/proxy/hook_interceptor.go
  internal/proxy/hook_interceptor_test.go
  internal/util/paramtable/base_table.go
  internal/util/paramtable/component_param.go
  internal/util/paramtable/hook_config.go
Labels: area/dependency, area/api, size/L, approved, lgtm, ci-passed, area/internal-api, dco-passed, area/compilation

#19349 Add ut for IndexCoord
  internal/indexcoord/garbage_collector.go
  internal/indexcoord/garbage_collector_test.go
  internal/indexcoord/index_builder.go
  internal/indexcoord/index_builder_test.go
  internal/indexcoord/meta_table.go
  internal/indexcoord/task_state_test.go
Labels: size/XXL, approved, lgtm, ci-passed, dco-passed

#19312 Add SyncSegments into proto
  internal/datacoord/mock_test.go
  internal/datanode/data_node.go
  internal/datanode/data_node_test.go
  internal/datanode/flow_graph_delete_node.go
  internal/datanode/flow_graph_delete_node_test.go
  internal/datanode/flow_graph_manager.go
  internal/datanode/flow_graph_manager_test.go
  internal/datanode/segment_replica.go
  internal/datanode/segment_replica_test.go
  internal/distributed/datanode/client/client.go
  internal/distributed/datanode/service.go
  internal/distributed/datanode/service_test.go
  internal/mocks/mock_datanode.go
  internal/proto/data_coord.proto
  internal/proto/datapb/data_coord.pb.go
  internal/types/types.go
  internal/util/mock/grpc_datanode_client.go
Labels: size/XXL, approved, lgtm, ci-passed, dco-passed, manual-pass

#19313 Add Revert in DataCoord meta catalog
  Makefile
  internal/kv/mocks/TxnKV.go
  internal/metastore/catalog.go
  internal/metastore/kv/datacoord/kv_catalog.go
  internal/metastore/kv/datacoord/kv_catalog_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed, area/compilation, manual-pass

#19391 Fix L2 string test case for 2.1 branch
  tests/python_client/testcases/test_search.py
Labels: kind/improvement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#19395 [skip e2e] Change milvus dashboard datasource uid
  deployments/monitor/grafana/milvus-dashboard.json
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#19141 Fix Chunk Manager Path mis use
  cmd/milvus/mck.go
  internal/datacoord/garbage_collector.go
  internal/datacoord/garbage_collector_test.go
  internal/datacoord/server.go
  internal/datanode/data_node.go
  internal/indexcoord/index_coord.go
  internal/indexnode/chunk_mgr_factory.go
  internal/indexnode/chunkmgr_mock.go
  internal/querycoord/query_coord.go
  internal/querycoordv2/meta/coordinator_broker.go
  internal/querycoordv2/server.go
  internal/querynode/mock_test.go
  internal/querynode/query_node.go
  internal/querynode/query_node_test.go
  internal/querynode/query_shard_service.go
  internal/querynode/query_shard_service_test.go
  internal/storage/factory.go
  internal/storage/minio_chunk_manager.go
  internal/util/dependency/factory.go
  internal/util/importutil/import_wrapper_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#19392 Fix leader observer confused with replicas
  internal/querycoordv2/meta/segment_dist_manager.go
  internal/querycoordv2/observers/leader_observer.go
  internal/querycoordv2/observers/leader_observer_test.go
  internal/querycoordv2/task/executor.go
  internal/querycoordv2/task/scheduler.go
  internal/querycoordv2/utils/test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#19400 Fix manual balance failed with TaskStale
  internal/querycoordv2/handlers.go
  internal/querycoordv2/services_test.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#19394 Fix start milvus failed on macos
  internal/core/src/CMakeLists.txt
  internal/core/src/common/CMakeLists.txt
  internal/core/src/config/CMakeLists.txt
  internal/core/src/exceptions/CMakeLists.txt
  internal/core/src/index/Utils.cpp
  internal/core/src/index/VectorMemIndex.cpp
  internal/core/src/indexbuilder/ScalarIndexCreator.cpp
  internal/core/src/indexbuilder/ScalarIndexCreator.h
  internal/core/src/indexbuilder/VecIndexCreator.cpp
  internal/core/src/indexbuilder/VecIndexCreator.h
  internal/core/src/segcore/load_index_c.cpp
  internal/core/src/segcore/load_index_c.h
  internal/core/src/utils/CMakeLists.txt
  internal/querynode/load_index_info.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed, area/compilation
