Repository milvus-io/milvus, pull requests merged in 2022-10, with the labels that each got.

#19491 Add the `GetLoadingProgress` RPC
  api/milvuspb/milvus.pb.go
  internal/distributed/proxy/service.go
  internal/distributed/proxy/service_test.go
  internal/proto/milvus.proto
  internal/proxy/impl.go
  internal/proxy/proxy_test.go
  internal/types/types.go
Labels: area/api, size/XXL, approved, lgtm, ci-passed, dco-passed, manual-pass

#19205 Implement GetPersistentSegmentInfo through datacoord
  internal/datacoord/server_test.go
  internal/datacoord/services.go
  internal/distributed/datacoord/client/client.go
  internal/distributed/datacoord/service.go
  internal/distributed/datacoord/service_test.go
  internal/distributed/proxy/service_test.go
  internal/mocks/mock_datacoord.go
  internal/proto/data_coord.proto
  internal/proto/datapb/data_coord.pb.go
  internal/proxy/data_coord_mock_test.go
  internal/proxy/impl.go
  internal/types/types.go
  internal/util/mock/grpc_datacoord_client.go
Labels: size/XL, approved, lgtm, ci-passed, dco-passed, manual-pass

#19620 [skip e2e]Export log for mac
  .github/workflows/mac.yaml
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#19624 docs: update compare table, show feat status with badge
  milvus20vs1x.md
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#19621 [skip e2e]fix mac compile error
  .github/workflows/mac.yaml
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#19570 Add logic of autoindex
  Makefile
  configs/milvus.yaml
  go.mod
  go.sum
  internal/common/common.go
  internal/distributed/rootcoord/service.go
  internal/distributed/rootcoord/service_test.go
  internal/indexcoord/index_coord.go
  internal/indexcoord/task.go
  internal/indexnode/indexnode_service_test.go
  internal/indexnode/task.go
  internal/metastore/db/dao/index_test.go
  internal/metastore/db/dbmodel/index.go
  internal/metastore/db/indexcoord/table_catalog.go
  internal/metastore/model/index.go
  internal/proto/index_coord.proto
  internal/proto/indexpb/index_coord.pb.go
  internal/proxy/impl.go
  internal/proxy/proxy_test.go
  internal/proxy/task.go
  internal/proxy/task_index.go
  internal/proxy/task_query.go
  internal/proxy/task_search.go
  internal/proxy/task_search_test.go
  internal/proxy/task_statistic.go
  internal/proxy/task_test.go
  internal/proxy/util.go
  internal/querynode/mock_test.go
  internal/rootcoord/proxy_client_manager_test.go
  internal/rootcoord/root_coord.go
  internal/types/types.go
  internal/util/autoindex/bigdata_index.go
  internal/util/autoindex/bigdata_index_test.go
  internal/util/autoindex/function.go
  internal/util/autoindex/function_test.go
  internal/util/autoindex/method.go
  internal/util/autoindex/method_test.go
  internal/util/autoindex/parser.go
  internal/util/autoindex/parser_test.go
  internal/util/autoindex/util.go
  internal/util/autoindex/util_test.go
  internal/util/funcutil/func.go
  internal/util/metricsinfo/metric_type.go
  internal/util/paramtable/autoindex_param.go
  internal/util/paramtable/autoindex_param_test.go
  internal/util/paramtable/component_param.go
  scripts/run_go_unittest.sh
  scripts/sql/meta.sql
  tests/python_client/requirements.txt
  tests/python_client/testcases/test_connection.py
Labels: area/dependency, sig/testing, size/XXL, approved, lgtm, area/test, ci-passed, area/internal-api, dco-passed, area/compilation, manual-pass

#19370 Add test cases of search paginationII
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#19484 Add test cases of query pagination
  tests/python_client/testcases/test_query.py
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#19638 [skip e2e]Update script for k8s log export
  tests/scripts/export_log_k8s_for_operator.sh
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#19627 Add TargetID in MsgBase and querynode v2 API check
  api/commonpb/common.pb.go
  internal/common/error.go
  internal/core/src/pb/common.pb.cc
  internal/core/src/pb/common.pb.h
  internal/proto/common.proto
  internal/querycoordv2/dist/dist_handler.go
  internal/querycoordv2/session/cluster.go
  internal/querycoordv2/session/cluster_test.go
  internal/querynode/impl.go
  internal/querynode/impl_test.go
  internal/querynode/metrics_info_test.go
  internal/querynode/mock_test.go
  internal/querynode/shard_cluster.go
  internal/querynode/shard_cluster_test.go
  internal/querynode/task_test.go
Labels: kind/bug, kind/enhancement, size/XXL, approved, lgtm, ci-passed, dco-passed

#19645 [skip e2e] Upload codecov even ut failed
  .github/workflows/main.yaml
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#19642 Fix panic when expr invalid
  internal/proxy/plan_parser.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#19628 Make creating collection/partition follow tt mechanism
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
  internal/rootcoord/scheduler.go
  internal/rootcoord/scheduler_test.go
  internal/util/funcutil/aggregation.go
  internal/util/funcutil/aggregation_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#19643 Fix a random failure of unittest
  internal/util/importutil/binlog_parser.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#19656 Support the `RELEASE` param to update the milvus/api version dynamically
  Makefile
  scripts/update_api_version.sh
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed, area/compilation

#19641 Update quota params and no limit for showCollection
  configs/milvus.yaml
  internal/proxy/multi_rate_limiter.go
  internal/proxy/rate_limit_interceptor.go
  internal/proxy/rate_limit_interceptor_test.go
  internal/util/paramtable/quota_param.go
  internal/util/paramtable/quota_param_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#19636 Fix lost disk index data
  internal/core/src/index/VectorDiskIndex.cpp
  internal/core/src/storage/DiskFileManagerImpl.cpp
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#19648 Improve some DataNode service logs
  internal/datanode/data_node.go
  internal/distributed/datanode/service.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#19497 Fix pagination check in QueryNode
  internal/proxy/task_query.go
  internal/proxy/task_query_test.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#19664 [skip e2e]Disable rebuild centos env for code checker
  .github/workflows/code-checker.yaml
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#19663 Add collection schema in watch channel info
  internal/datacoord/channel_manager.go
  internal/datacoord/services.go
  internal/datanode/compactor_test.go
  internal/datanode/data_node.go
  internal/datanode/data_node_test.go
  internal/datanode/data_sync_service_test.go
  internal/datanode/flow_graph_insert_buffer_node_test.go
  internal/datanode/flow_graph_manager.go
  internal/datanode/flow_graph_manager_test.go
  internal/datanode/flush_manager_test.go
  internal/datanode/segment_replica.go
  internal/datanode/segment_replica_test.go
  internal/proto/data_coord.proto
  internal/proto/datapb/data_coord.pb.go
  internal/rootcoord/broker.go
  internal/rootcoord/create_collection_task.go
Labels: kind/bug, size/XL, approved, lgtm, ci-passed, dco-passed

#19647 Do not try to report task state when DataNode itself is down
  internal/datanode/data_node.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#19632 Fix exclusive consumer conflict in import
  internal/datanode/data_node.go
  internal/datanode/data_sync_service.go
  internal/datanode/data_sync_service_test.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed

#19659 Prevent datacoord from syncing unflushed segments
  internal/datanode/segment_replica.go
  internal/datanode/segment_replica_test.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#19488 Fix reduce latency metric [pick#19479]
  internal/querynode/task_search.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#19681 Remove QueryCoordV1
  cmd/roles/roles.go
  internal/proxy/proxy_test.go
  internal/querycoord/OWNERS
  internal/querycoord/channel_allocator.go
  internal/querycoord/channel_allocator_test.go
  internal/querycoord/channel_unsubscribe.go
  internal/querycoord/channel_unsubscribe_test.go
  internal/querycoord/cluster.go
  internal/querycoord/cluster_test.go
  internal/querycoord/condition.go
  internal/querycoord/const.go
  internal/querycoord/global_meta_broker.go
  internal/querycoord/global_meta_broker_test.go
  internal/querycoord/group_balance.go
  internal/querycoord/group_balance_test.go
  internal/querycoord/handoff_handler.go
  internal/querycoord/handoff_handler_test.go
  internal/querycoord/impl.go
  internal/querycoord/impl_test.go
  internal/querycoord/meta.go
  internal/querycoord/meta_test.go
  internal/querycoord/metrics_info.go
  internal/querycoord/metrics_info_test.go
  internal/querycoord/mock_3rd_component_test.go
  internal/querycoord/mock_cluster.go
  internal/querycoord/mock_querynode_client_test.go
  internal/querycoord/mock_querynode_server_test.go
  internal/querycoord/query_coord.go
  internal/querycoord/query_coord_test.go
  internal/querycoord/querynode.go
  internal/querycoord/querynode_test.go
  internal/querycoord/replica.go
  internal/querycoord/replica_test.go
  internal/querycoord/segment_allocator.go
  internal/querycoord/segment_allocator_test.go
  internal/querycoord/segments_info.go
  internal/querycoord/segments_info_test.go
  internal/querycoord/task.go
  internal/querycoord/task_scheduler.go
  internal/querycoord/task_scheduler_test.go
  internal/querycoord/task_test.go
  internal/querycoord/task_util.go
  internal/querycoord/task_util_test.go
  internal/querycoord/util.go
Labels: kind/improvement, size/XXL, approved, lgtm, ci-passed, dco-passed

#19692 Use underscores to separate parameter names in the `GetLoadingProgressRequest`
  api/milvuspb/milvus.pb.go
  internal/proto/milvus.proto
Labels: kind/improvement, area/api, size/L, approved, lgtm, ci-passed, dco-passed

#19657 Add GetDataVChanPositions
  internal/datacoord/channel_manager.go
  internal/datacoord/handler.go
  internal/datacoord/mock_test.go
  internal/datacoord/server_test.go
  internal/datacoord/services.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#19707 Fix static-check
  internal/datacoord/server_test.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#19649 test: use `T.Setenv` to set env vars in tests
  internal/config/config_test.go
  internal/datacoord/channel_manager_test.go
  internal/kv/etcd/embed_etcd_config_test.go
  internal/kv/etcd/embed_etcd_kv_test.go
  internal/kv/etcd/embed_etcd_restart_test.go
  internal/metrics/metrics_test.go
  internal/proxy/proxy_test.go
  internal/util/flowgraph/input_node_test.go
  internal/util/flowgraph/node_test.go
  internal/util/metricsinfo/utils_test.go
  internal/util/paramtable/base_table_test.go
  internal/util/paramtable/service_param_test.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#19700 Refine method name from BroadCastXx to BroadcastXx
  internal/datacoord/services.go
  internal/datanode/mock_test.go
  internal/distributed/datacoord/client/client.go
  internal/distributed/datacoord/client/client_test.go
  internal/distributed/datacoord/service.go
  internal/distributed/datacoord/service_test.go
  internal/distributed/proxy/service_test.go
  internal/mocks/mock_datacoord.go
  internal/proto/data_coord.proto
  internal/proto/datapb/data_coord.pb.go
  internal/proxy/data_coord_mock_test.go
  internal/rootcoord/alter_collection_task_test.go
  internal/rootcoord/broker.go
  internal/rootcoord/broker_test.go
  internal/rootcoord/mock_test.go
  internal/rootcoord/step.go
  internal/types/types.go
  internal/util/mock/grpc_datacoord_client.go
Labels: kind/improvement, size/XL, approved, lgtm, ci-passed, dco-passed

#19592 Fix some page in rocksmq could not get acked timestamp
  internal/mq/mqimpl/rocksmq/server/rocksmq.go
  internal/mq/mqimpl/rocksmq/server/rocksmq_impl.go
  internal/mq/mqimpl/rocksmq/server/rocksmq_impl_test.go
  internal/mq/mqimpl/rocksmq/server/rocksmq_retention_test.go
  internal/mq/msgstream/mqwrapper/rmq/rmq_client_test.go
  internal/mq/msgstream/mqwrapper/rmq/rmq_consumer.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#19680 Force deny writing if disk quota exceeded
  configs/milvus.yaml
  internal/datacoord/meta.go
  internal/datacoord/meta_test.go
  internal/datacoord/metrics_info.go
  internal/rootcoord/quota_center.go
  internal/rootcoord/quota_center_test.go
  internal/util/metricsinfo/metrics_info.go
  internal/util/metricsinfo/quota_metric.go
  internal/util/paramtable/quota_param.go
  internal/util/paramtable/quota_param_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#19702 Fix bulkload failed bug
  internal/datanode/data_node.go
  internal/util/importutil/import_wrapper.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#19709 Add meta migration tool
  Makefile
  cmd/tools/migration/backend/backend.go
  cmd/tools/migration/backend/backup_header.go
  cmd/tools/migration/backend/backup_restore.go
  cmd/tools/migration/backend/backup_restore_test.go
  cmd/tools/migration/backend/etcd.go
  cmd/tools/migration/backend/etcd210.go
  cmd/tools/migration/backend/etcd220.go
  cmd/tools/migration/command/backup.go
  cmd/tools/migration/command/config.go
  cmd/tools/migration/command/help.go
  cmd/tools/migration/command/main.go
  cmd/tools/migration/command/rollback.go
  cmd/tools/migration/command/run.go
  cmd/tools/migration/configs/config.go
  cmd/tools/migration/console/console.go
  cmd/tools/migration/console/console_test.go
  cmd/tools/migration/example.yaml
  cmd/tools/migration/legacy/constant.go
  cmd/tools/migration/legacy/legacy.proto
  cmd/tools/migration/legacy/legacypb/legacy.pb.go
  cmd/tools/migration/legacy/util.go
  cmd/tools/migration/main.go
  cmd/tools/migration/meta/210_to_220.go
  cmd/tools/migration/meta/meta.go
  cmd/tools/migration/meta/meta210.go
  cmd/tools/migration/meta/meta220.go
  cmd/tools/migration/migration/210_to_220.go
  cmd/tools/migration/migration/constant.go
  cmd/tools/migration/migration/migration.go
  cmd/tools/migration/migration/migrator.go
  cmd/tools/migration/migration/runner.go
  cmd/tools/migration/utils/util.go
  cmd/tools/migration/utils/util_test.go
  cmd/tools/migration/versions/version.go
  cmd/tools/migration/versions/version_test.go
  go.mod
  go.sum
  internal/metastore/kv/indexcoord/kv_catalog.go
  internal/metastore/kv/rootcoord/kv_catalog.go
  internal/metastore/kv/rootcoord/kv_catalog_test.go
  internal/metastore/kv/rootcoord/rootcoord_constant.go
  internal/metastore/kv/rootcoord/suffix_snapshot.go
  internal/metastore/model/collection.go
  internal/rootcoord/constrant.go
  internal/rootcoord/meta_table.go
  internal/rootcoord/root_coord.go
  internal/util/paramtable/base_table.go
  internal/util/paramtable/base_table_test.go
  internal/util/paramtable/service_param.go
  internal/util/sessionutil/session_util.go
  internal/util/sessionutil/session_util_test.go
  scripts/proto_gen_go.sh
Labels: area/dependency, size/XXL, approved, lgtm, ci-passed, dco-passed, area/compilation

#19710 Prevent datacoord from syncing unflushed segments (#19659)
  internal/datanode/segment_replica.go
  internal/datanode/segment_replica_test.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#19711 Clean unnecessary deps to make milvus
  .github/workflows/code-checker.yaml
  DEVELOPMENT.md
  Makefile
  build/README.md
  scripts/README.md
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed, area/compilation

#19722 Fix timetravel error msg
  internal/proxy/util.go
  internal/proxy/util_test.go
  internal/util/paramtable/component_param.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#19661 Fix typo in core
  internal/core/thirdparty/CMakeLists.txt
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed, area/compilation

#19725 Fix insert buffer node time range uint64 conversion error
  internal/datanode/flow_graph_insert_buffer_node.go
  internal/datanode/flow_graph_insert_buffer_node_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#19726 Make NQ <= 16384 limit work
  internal/proxy/task.go
  internal/proxy/task_search.go
  internal/proxy/task_search_test.go
  internal/proxy/util.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#19676 Prepare http admin API
  cmd/roles/roles.go
  internal/log/log.go
  internal/log/log_test.go
  internal/management/server.go
  internal/management/server_test.go
  internal/metrics/metrics.go
  internal/metrics/metrics_test.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#19698 Remove unnecessary log for datacoord gc
  internal/datacoord/garbage_collector.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#19728 Add read result rate protection
  configs/milvus.yaml
  internal/proxy/impl.go
  internal/proxy/metrics_info.go
  internal/proxy/proxy.go
  internal/rootcoord/quota_center.go
  internal/rootcoord/quota_center_test.go
  internal/util/metricsinfo/quota_metric.go
  internal/util/paramtable/quota_param.go
  internal/util/paramtable/quota_param_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#19751 Use task's ID as the MsgID instead of source ID
  internal/querycoordv2/task/utils.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#19756 Fix ttProtection.enabled and memProtection
  internal/rootcoord/quota_center.go
  internal/util/paramtable/quota_param.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#19748 Add active-standby support in querycoord V2
  internal/querycoordv2/server.go
  internal/querycoordv2/server_test.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#19755 Modify test cases after code change
  ci/jenkins/Nightly.groovy
  ci/jenkins/PR.groovy
  tests/python_client/requirements.txt
  tests/python_client/testcases/test_compaction.py
  tests/python_client/testcases/test_delete.py
  tests/python_client/testcases/test_search.py
  tests/python_client/testcases/test_utility.py
Labels: sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#19759 Add the `TotalRows` value for the DescribeIndex
  internal/indexcoord/index_coord.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed

#19757 Fix potential long log
  internal/datacoord/server.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#19766 Fix make binlog
  Makefile
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed, area/compilation

#19694 Add GetVersion API for the client
  api/milvuspb/milvus.pb.go
  internal/distributed/proxy/service.go
  internal/distributed/proxy/service_test.go
  internal/proto/milvus.proto
  internal/proxy/proxy_test.go
  internal/util/funcutil/policy_test.go
Labels: kind/improvement, area/api, size/XL, approved, lgtm, ci-passed, dco-passed

#19771 Assemble RAW_DATA files
  internal/core/src/index/VectorMemIndex.cpp
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#19747 Refactor healthz API
  cmd/components/data_coord.go
  cmd/components/data_node.go
  cmd/components/index_coord.go
  cmd/components/index_node.go
  cmd/components/proxy.go
  cmd/components/query_coord.go
  cmd/components/query_node.go
  cmd/components/root_coord.go
  cmd/milvus/run.go
  cmd/roles/healthz_handler.go
  cmd/roles/roles.go
  go.mod
  go.sum
  internal/management/healthz/content_type.go
  internal/management/healthz/healthz_error_handler.go
  internal/management/healthz/healthz_handler.go
  internal/management/router.go
  internal/management/server.go
  internal/management/server_test.go
  internal/util/metricsinfo/hardware_info.go
  internal/util/paramtable/component_param.go
Labels: area/dependency, size/XL, approved, lgtm, ci-passed, dco-passed

#19770 Make DML failed if quota exceeds and remove autoindex config
  configs/milvus.yaml
  internal/datacoord/meta.go
  internal/datacoord/meta_test.go
  internal/util/paramtable/quota_param.go
  internal/util/paramtable/quota_param_test.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#19783 Fix segcore unit test name
  internal/core/unittest/test_query.cpp
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#19776 Limit max shard num to 64
  internal/rootcoord/constrant.go
  internal/rootcoord/create_collection_task.go
  internal/rootcoord/create_collection_task_test.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed

#19732 Do not use DataCoord context when DataNode is handling import task
  internal/datanode/data_node.go
  internal/datanode/data_node_test.go
  internal/datanode/mock_test.go
  internal/util/importutil/import_wrapper.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#19790 Revert DML quota check
  internal/datacoord/meta.go
  internal/datacoord/meta_test.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#19714 Move disk index params to config file
  cmd/milvus/run.go
  cmd/milvus/stop.go
  cmd/milvus/util.go
  configs/milvus.yaml
  internal/core/src/index/Meta.h
  internal/core/src/index/VectorDiskIndex.cpp
  internal/core/src/index/VectorDiskIndex.h
  internal/core/unittest/test_indexing.cpp
  internal/core/unittest/test_utils/indexbuilder_test_utils.h
  internal/datacoord/metrics_info.go
  internal/datanode/metrics_info.go
  internal/indexcoord/index_coord.go
  internal/indexcoord/metrics_info.go
  internal/indexnode/indexnode_mock.go
  internal/indexnode/metrics_info.go
  internal/indexnode/task.go
  internal/mq/mqimpl/rocksmq/server/rocksmq_impl.go
  internal/proto/index_coord.proto
  internal/proto/indexpb/index_coord.pb.go
  internal/proto/query_coord.proto
  internal/proto/querypb/query_coord.pb.go
  internal/proxy/metrics_info.go
  internal/proxy/task_index.go
  internal/querycoordv2/handlers.go
  internal/querycoordv2/meta/coordinator_broker.go
  internal/querynode/load_index_info.go
  internal/querynode/metrics_info.go
  internal/querynode/segment_loader.go
  internal/querynode/task_test.go
  internal/rootcoord/metrics_info.go
  internal/util/autoindex/bigdata_index.go
  internal/util/autoindex/bigdata_index_test.go
  internal/util/funcutil/func.go
  internal/util/hardware/container_darwin.go
  internal/util/hardware/container_linux.go
  internal/util/hardware/container_test_linux.go
  internal/util/hardware/container_windows.go
  internal/util/hardware/hardware_info.go
  internal/util/hardware/hardware_info_test.go
  internal/util/indexparams/disk_index_params.go
  internal/util/indexparams/disk_index_params_test.go
  internal/util/paramtable/autoindex_param.go
  internal/util/paramtable/autoindex_param_test.go
  internal/util/paramtable/component_param.go
Labels: kind/improvement, size/XXL, approved, lgtm, ci-passed, area/internal-api, dco-passed

#19787 Fix read queue metrics and memory protection
  internal/datacoord/services.go
  internal/querycoordv2/services.go
  internal/querynode/flow_graph_service_time_node.go
  internal/querynode/task_query.go
  internal/querynode/task_read.go
  internal/querynode/task_search.go
  internal/rootcoord/quota_center.go
  internal/rootcoord/quota_center_test.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#19786 Fix incorrect e2e test
  tests/python_client/testcases/test_utility.py
Labels: kind/bug, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#19793 Modify test cases due to pymilvus updates
  tests/python_client/testcases/test_collection.py
  tests/python_client/testcases/test_utility.py
Labels: sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#19789 Gracefully handle the hook plugin loading failure error
  internal/proxy/hook_interceptor.go
  internal/proxy/hook_interceptor_test.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed

#19798 [skip e2e]Close nightly ci at 22:50
  ci/jenkins/Nightly.groovy
Labels: size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#19799 [skip e2e]Update the script for nightly test
  tests/scripts/values/mysql.yaml
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed, manual-pass

#19800 [skip e2e]Only allow one nightly at the same time
  ci/jenkins/Nightly.groovy
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#19670 Fix scan may break GC limitation
  internal/datacoord/garbage_collector.go
  internal/datacoord/garbage_collector_test.go
  internal/datacoord/meta.go
  internal/datacoord/meta_test.go
  internal/datacoord/server.go
  internal/datacoord/services.go
  internal/storage/minio_chunk_manager.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#19802 Fix ttFactor in QuoterCenter
  internal/rootcoord/quota_center.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#19803 Add nameing rules for index name
  internal/proxy/task_index.go
  internal/proxy/task_test.go
  internal/proxy/util.go
  tests/python_client/testcases/test_index.py
Labels: sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#19814 Fix meta migration tool
  Makefile
  cmd/tools/migration/backend/backend.go
  cmd/tools/migration/backend/backup_header.go
  cmd/tools/migration/backend/etcd210.go
  cmd/tools/migration/command/config.go
  cmd/tools/migration/command/main.go
  cmd/tools/migration/command/run.go
  cmd/tools/migration/configs/config.go
  cmd/tools/migration/console/code.go
  cmd/tools/migration/console/console.go
  cmd/tools/migration/console/exit.go
  cmd/tools/migration/console/exit_config.go
  cmd/tools/migration/example.yaml
  cmd/tools/migration/migration/runner.go
  go.mod
  go.sum
  internal/util/sessionutil/session_util.go
  internal/util/sessionutil/session_util_test.go
Labels: area/dependency, size/L, approved, lgtm, ci-passed, dco-passed, area/compilation

#19812 Delete the unrelated content in the yaml file
  configs/hook.yaml
  configs/milvus.yaml
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#19816 Enable quota and limits and update quota unit
  configs/milvus.yaml
  internal/rootcoord/quota_center.go
  internal/util/paramtable/quota_param.go
  internal/util/paramtable/quota_param_test.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#19516 Must create index before load
  internal/proto/query_coord.proto
  internal/proto/querypb/query_coord.pb.go
  internal/proxy/impl.go
  internal/proxy/index_coord_mock_test.go
  internal/proxy/rootcoord_mock_test.go
  internal/proxy/task.go
  internal/proxy/task_index.go
  internal/proxy/task_test.go
  tests/python_client/base/client_base.py
  tests/python_client/common/common_type.py
  tests/python_client/requirements.txt
  tests/python_client/testcases/test_collection.py
  tests/python_client/testcases/test_compaction.py
  tests/python_client/testcases/test_delete.py
  tests/python_client/testcases/test_e2e.py
  tests/python_client/testcases/test_index.py
  tests/python_client/testcases/test_partition.py
  tests/python_client/testcases/test_query.py
  tests/python_client/testcases/test_search.py
  tests/python_client/testcases/test_utility.py
Labels: sig/testing, size/XL, approved, lgtm, area/test, ci-passed, area/internal-api, dco-passed

#19831 Remove dependency for dropped segment checkpoint in querynode
  internal/querynode/task.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#19811 Modify cases associated with updated shard num
  tests/python_client/testcases/test_collection.py
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#19833 Improve the making milvus process
  Makefile
  go.mod
  go.sum
  rules.go
  scripts/update-api-version.sh
Labels: area/dependency, size/S, approved, lgtm, ci-passed, dco-passed, area/compilation

#19843 Fix the wrong file name
  Makefile
Labels: kind/improvement, size/XS, dco-passed, area/compilation

#19836 Refine the error of QueryNode
  internal/querynode/errors.go
  internal/querynode/shard_cluster.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#19839 Remove dropped segments' info
  internal/querycoordv2/task/utils.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#19791 Refactor grpclient, make it generic
  internal/distributed/datacoord/client/client.go
  internal/distributed/datacoord/client/client_test.go
  internal/distributed/datanode/client/client.go
  internal/distributed/datanode/client/client_test.go
  internal/distributed/indexcoord/client/client.go
  internal/distributed/indexnode/client/client.go
  internal/distributed/indexnode/client/client_test.go
  internal/distributed/proxy/client/client.go
  internal/distributed/proxy/client/client_test.go
  internal/distributed/querycoord/client/client.go
  internal/distributed/querycoord/client/client_test.go
  internal/distributed/querynode/client/client.go
  internal/distributed/querynode/client/client_test.go
  internal/distributed/rootcoord/client/client.go
  internal/distributed/rootcoord/client/client_test.go
  internal/util/generic/generic.go
  internal/util/grpcclient/client.go
  internal/util/grpcclient/client_test.go
  internal/util/mock/grpcclient.go
  tests/python_client/testcases/test_utility.py
Labels: area/dependency, kind/improvement, sig/testing, size/XL, approved, lgtm, area/test, ci-passed, dco-passed

#19819 Refine NQ check logic
  internal/proxy/task_search.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#19824 [test]Make pymilvus version compatible
  tests/python_client/deploy/scripts/first_recall_test.py
  tests/python_client/deploy/scripts/utils.py
  tests/python_client/deploy/testcases/test_action_first_deployment.py
  tests/python_client/deploy/testcases/test_action_second_deployment.py
Labels: kind/improvement, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#19844 Fix proxy crash issue when meta cache miss
  internal/proxy/meta_cache.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#19779 Support check health for the cluster level
  go.mod
  go.sum
  internal/datacoord/mock_test.go
  internal/datacoord/server_test.go
  internal/datacoord/services.go
  internal/datanode/mock_test.go
  internal/distributed/datacoord/client/client.go
  internal/distributed/datacoord/client/client_test.go
  internal/distributed/datacoord/service.go
  internal/distributed/datacoord/service_test.go
  internal/distributed/indexcoord/client/client.go
  internal/distributed/indexcoord/client/client_test.go
  internal/distributed/indexcoord/service.go
  internal/distributed/indexcoord/service_test.go
  internal/distributed/proxy/service.go
  internal/distributed/proxy/service_test.go
  internal/distributed/querycoord/client/client.go
  internal/distributed/querycoord/client/client_test.go
  internal/distributed/querycoord/service.go
  internal/distributed/querycoord/service_test.go
  internal/distributed/rootcoord/client/client.go
  internal/distributed/rootcoord/client/client_test.go
  internal/distributed/rootcoord/service.go
  internal/distributed/rootcoord/service_test.go
  internal/indexcoord/index_coord.go
  internal/indexcoord/index_coord_mock.go
  internal/indexcoord/index_coord_test.go
  internal/mocks/mock_datacoord.go
  internal/mocks/mock_indexcoord.go
  internal/mocks/mock_rootcoord.go
  internal/proto/data_coord.proto
  internal/proto/datapb/data_coord.pb.go
  internal/proto/index_coord.proto
  internal/proto/indexpb/index_coord.pb.go
  internal/proto/query_coord.proto
  internal/proto/querypb/query_coord.pb.go
  internal/proto/root_coord.proto
  internal/proto/rootcoordpb/root_coord.pb.go
  internal/proxy/data_coord_mock_test.go
  internal/proxy/impl.go
  internal/proxy/impl_test.go
  internal/proxy/index_coord_mock_test.go
  internal/proxy/query_coord_mock_test.go
  internal/proxy/rootcoord_mock_test.go
  internal/querycoordv2/services.go
  internal/querycoordv2/services_test.go
  internal/querycoordv2/session/cluster.go
  internal/querycoordv2/session/cluster_test.go
  internal/querycoordv2/session/mock_cluster.go
  internal/rootcoord/mock_test.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
  internal/types/types.go
  internal/util/errorutil/util.go
  internal/util/mock/grpc_datacoord_client.go
  internal/util/mock/grpc_querycoord_client.go
  internal/util/mock/grpc_rootcoord_client.go
Labels: area/dependency, area/api, size/XXL, approved, lgtm, ci-passed, area/internal-api, dco-passed

#19858 Make newSegment transfer state after SaveBinlogPath succuess
  internal/datanode/flow_graph_insert_buffer_node_test.go
  internal/datanode/flush_manager.go
  internal/datanode/segment_replica.go
  internal/datanode/segment_replica_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#19859 Add a collection TTL doc
  docs/user_guides/collection_ttl.md
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#19815 Refactor segment replica in DN
  internal/datanode/channel_meta.go
  internal/datanode/channel_meta_test.go
  internal/datanode/compactor.go
  internal/datanode/compactor_test.go
  internal/datanode/data_node.go
  internal/datanode/data_node_test.go
  internal/datanode/data_sync_service.go
  internal/datanode/data_sync_service_test.go
  internal/datanode/flow_graph_delete_node.go
  internal/datanode/flow_graph_delete_node_test.go
  internal/datanode/flow_graph_insert_buffer_node.go
  internal/datanode/flow_graph_insert_buffer_node_test.go
  internal/datanode/flow_graph_manager.go
  internal/datanode/flow_graph_manager_test.go
  internal/datanode/flush_manager.go
  internal/datanode/flush_manager_test.go
  internal/datanode/meta_service.go
  internal/datanode/segment.go
  internal/datanode/segment_replica.go
  internal/datanode/segment_replica_test.go
  internal/datanode/segment_test.go
  internal/proto/data_coord.proto
  internal/proto/datapb/data_coord.pb.go
Labels: kind/improvement, size/XXL, approved, lgtm, ci-passed, dco-passed

#19856 Intercept import request in Proxy interceptor
  internal/proxy/rate_limit_interceptor.go
  internal/proxy/rate_limit_interceptor_test.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#19820 Alloc timestamp instead of using start position timestamp for index
  internal/indexcoord/flush_segment_watcher.go
  internal/indexcoord/flushed_segment_watcher_test.go
  internal/indexcoord/index_coord_mock.go
  internal/indexcoord/index_coord_test.go
  internal/indexcoord/task.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#19855 [test]Update bulk insert test case
  tests/python_client/.gitignore
  tests/python_client/base/utility_wrapper.py
  tests/python_client/bulk_insert/bulk_insert_data.py
  tests/python_client/bulk_insert/minio_comm.py
  tests/python_client/bulk_insert/test_bulk_insert.py
  tests/python_client/bulk_load/test_bulk_load.py
  tests/python_client/chaos/chaos_commons.py
  tests/python_client/chaos/checker.py
  tests/python_client/chaos/test_chaos_bulk_insert.py
  tests/python_client/chaos/test_load_with_checker.py
  tests/python_client/common/common_func.py
  tests/python_client/config/log_config.py
  tests/python_client/requirements.txt
  tests/python_client/testcases/test_import.py
  tests/python_client/testcases/test_utility.py
Labels: kind/improvement, sig/testing, size/XXL, approved, lgtm, area/test, ci-passed, dco-passed

#19860 Modify according cases because load needs index now
  tests/python_client/testcases/test_utility.py
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#19869 [skip e2e] Add publish migration image
  Makefile
  build/docker/meta-migration/Dockerfile
  build/docker/meta-migration/builder/Dockerfile
  ci/jenkins/MetaMigrationBuilder.groovy
  ci/jenkins/PublishMigrationImage.groovy
  ci/jenkins/pod/meta-builder.yaml
  ci/jenkins/pod/meta-migration.yaml
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed, area/compilation

#19825 Initiatively release session in etcd when service close
  internal/util/sessionutil/session_util.go
  internal/util/sessionutil/session_util_test.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed

#19686 Support collection level metrics
  internal/metrics/metrics.go
  internal/metrics/proxy_metrics.go
  internal/proxy/channels_mgr.go
  internal/proxy/channels_mgr_test.go
  internal/proxy/impl.go
  internal/proxy/meta_cache.go
  internal/proxy/mock_channels_mgr_test.go
  internal/proxy/proxy.go
  internal/proxy/task.go
  internal/proxy/test_delete.go
Labels: kind/feature, size/XXL, approved, lgtm, ci-passed, dco-passed

#19867 Fix querynode concurrent map rw panic
  internal/querynode/shard_cluster.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#19874 [test]Create index before load and fix error message
  tests/python_client/bulk_insert/test_bulk_insert.py
Labels: kind/improvement, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#19857 Fill MsgBase
  internal/distributed/datacoord/client/client.go
  internal/distributed/indexcoord/client/client.go
  internal/distributed/proxy/client/client.go
  internal/distributed/querycoord/client/client.go
  internal/distributed/rootcoord/client/client.go
  internal/proxy/channels_mgr.go
  internal/proxy/impl.go
  internal/proxy/meta_cache.go
  internal/proxy/proxy.go
  internal/proxy/task.go
  internal/proxy/task_index.go
  internal/proxy/task_insert.go
  internal/proxy/task_search.go
  internal/proxy/task_statistic.go
  internal/proxy/timestamp.go
  internal/util/commonpbutil/commonpbutil.go
  internal/util/grpcclient/client.go
  internal/util/mock/grpcclient.go
  internal/util/typeutil/convension.go
Labels: kind/improvement, size/XL, approved, lgtm, ci-passed, dco-passed

#19849 Fix panic due to double stop
  internal/querycoordv2/checkers/controller.go
  internal/querycoordv2/dist/dist_handler.go
  internal/querycoordv2/job/scheduler.go
  internal/querycoordv2/observers/collection_observer.go
  internal/querycoordv2/observers/handoff_observer.go
  internal/querycoordv2/observers/leader_observer.go
  internal/querycoordv2/server_test.go
  internal/querycoordv2/session/cluster.go
  internal/querycoordv2/task/merger.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#19887 [skip e2e] Update path for migration image
  ci/jenkins/PublishMigrationImage.groovy
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#19885 Add more logs for checkpoint of channel
  internal/querycoordv2/meta/target_manager.go
  internal/querycoordv2/task/executor.go
  internal/util/tsoutil/tso.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#19883 Add log for querynode checkpoint timestamp lag
  internal/querynode/flow_graph_query_node.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#19888 Fix an issue where working task might get cleaned up
  internal/rootcoord/import_manager.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#19200 [skip e2e]Update dashboard doc
  deployments/monitor/grafana/README.md
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#19510 change some metric names for milvus dashboards
  deployments/monitor/grafana/milvus-dashboard.json
Labels: kind/improvement, size/XXL, approved, lgtm, ci-passed, dco-passed, manual-pass

#19872 Add binlogSize and ttDelay metrics monitor
  configs/milvus.yaml
  internal/datacoord/meta.go
  internal/metrics/datacoord_metrics.go
  internal/metrics/rootcoord_metrics.go
  internal/rootcoord/quota_center.go
  internal/rootcoord/quota_center_test.go
  internal/util/paramtable/quota_param.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#19866 Replace segment index file path with index file key within segment index meta
  cmd/tools/migration/meta/210_to_220.go
  internal/indexcoord/garbage_collector.go
  internal/indexcoord/garbage_collector_test.go
  internal/indexcoord/handoff.go
  internal/indexcoord/handoff_test.go
  internal/indexcoord/index_builder.go
  internal/indexcoord/index_builder_test.go
  internal/indexcoord/index_coord.go
  internal/indexcoord/index_coord_test.go
  internal/indexcoord/meta_table.go
  internal/indexcoord/meta_table_test.go
  internal/indexnode/indexnode_mock.go
  internal/indexnode/indexnode_service.go
  internal/indexnode/indexnode_service_test.go
  internal/indexnode/indexnode_test.go
  internal/indexnode/task.go
  internal/indexnode/taskinfo_ops.go
  internal/metastore/db/dao/segment_index.go
  internal/metastore/db/dao/segment_index_test.go
  internal/metastore/db/dbmodel/segment_index.go
  internal/metastore/db/indexcoord/table_catalog.go
  internal/metastore/db/indexcoord/table_catalog_test.go
  internal/metastore/kv/indexcoord/kv_catalog_test.go
  internal/metastore/model/segment_index.go
  internal/metastore/model/segment_index_test.go
  internal/proto/index_coord.proto
  internal/proto/indexpb/index_coord.pb.go
  internal/util/metautil/segment_index.go
  scripts/sql/meta.sql
Labels: size/XXL, approved, lgtm, ci-passed, area/internal-api, dco-passed

#19892 Fix io pool goroutine leakage
  internal/datanode/data_sync_service.go
  internal/datanode/io_pool.go
  internal/datanode/io_pool_test.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#19897 Remove codes related to deprecated field
  internal/datacoord/util.go
  internal/querycoordv2/meta/coordinator_broker.go
  internal/querycoordv2/meta/errors.go
  internal/querynode/segment_loader.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#19903 fix clean handoff event
  internal/querycoordv2/observers/handoff_observer.go
  internal/querycoordv2/observers/handoff_observer_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#19894 Improve the `download_milvus_proto` bash
  Makefile
  go.sum
  scripts/download_milvus_proto.sh
  scripts/update-api-version.sh
Labels: area/dependency, kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed, area/compilation

#19907 Fix missing import limit and rename functions in quotaCenter
  internal/proxy/rate_limit_interceptor.go
  internal/proxy/rate_limit_interceptor_test.go
  internal/rootcoord/quota_center.go
  internal/rootcoord/quota_center_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#19906 Upgrade pymilvus version and update test cases
  tests/python_client/requirements.txt
  tests/python_client/testcases/test_collection.py
  tests/python_client/testcases/test_connection.py
  tests/python_client/testcases/test_insert.py
Labels: sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#19908 [skip e2e]Remove entrypoint for migration image
  build/docker/meta-migration/Dockerfile
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#19886 Dropping index must happen without collection being loaded
  internal/proxy/impl.go
  internal/proxy/task_index.go
  internal/proxy/task_index_test.go
  tests/python_client/testcases/test_index.py
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#19861 Add meta migration script for milvus installation in kubernetes
  deployments/migrate-meta/README.md
  deployments/migrate-meta/migrate.sh
Labels: kind/improvement, size/XL, approved, lgtm, ci-passed, dco-passed, manual-pass

#19902 Fix QueryNode panic when meta changed
  internal/querynode/flow_graph_delete_node.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#19914 Refine weekly release tag
  .github/workflows/weekly-release.yml
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#19854 Fix BucketExists bug in minio chunk manager (#19548)
  internal/core/src/storage/CMakeLists.txt
  internal/core/src/storage/DiskFileManagerImpl.cpp
  internal/core/src/storage/LocalChunkManager.cpp
  internal/core/src/storage/MinioChunkManager.cpp
  internal/core/src/storage/MinioChunkManager.h
  internal/core/thirdparty/aws_sdk/CMakeLists.txt
  internal/core/unittest/CMakeLists.txt
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed, area/compilation

#19810 Support pass start_ts and end_ts through Import API
  internal/datanode/data_node.go
  internal/proto/data_coord.proto
  internal/proto/datapb/data_coord.pb.go
  internal/proxy/impl.go
  internal/proxy/proxy_test.go
  internal/rootcoord/import_manager.go
  internal/rootcoord/import_manager_test.go
  internal/util/importutil/import_options.go
  internal/util/importutil/import_options_test.go
Labels: size/XL, approved, lgtm, ci-passed, dco-passed

#19923 Fix meta migration script
  deployments/migrate-meta/migrate.sh
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#19922 Add more panic info
  internal/core/src/segcore/SegmentSealedImpl.cpp
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#19910 Keep segment statslog if no insert applied
  internal/datanode/channel_meta.go
  internal/datanode/channel_meta_test.go
  internal/datanode/compactor.go
  internal/datanode/compactor_test.go
  internal/datanode/errors.go
  internal/datanode/flow_graph_delete_node.go
  internal/datanode/flow_graph_delete_node_test.go
  internal/datanode/flow_graph_insert_buffer_node.go
  internal/datanode/flush_manager.go
  internal/datanode/segment.go
  internal/datanode/segment_test.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#19928 Add an option to automatically cleanup after successful meta migration
  deployments/migrate-meta/README.md
  deployments/migrate-meta/migrate.sh
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#19926 Add assert for connection.connect
  tests/python_client/check/func_check.py
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#19863 print some group info in rocksmq monitor
  internal/mq/mqimpl/rocksmq/server/rocksmq_impl.go
  internal/mq/mqimpl/rocksmq/server/rocksmq_retention_test.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#19917 Improve proxy leader cache lock logic
  internal/proxy/meta_cache.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#19929 Fix SyncSegment generate source
  internal/querynode/impl.go
  internal/querynode/impl_test.go
  internal/querynode/query_node.go
  internal/querynode/query_node_test.go
  internal/querynode/shard_cluster.go
  internal/querynode/shard_cluster_service.go
  internal/querynode/shard_cluster_service_test.go
  internal/querynode/shard_cluster_test.go
Labels: kind/bug, kind/improvement, size/XXL, approved, lgtm, ci-passed, dco-passed

#19864 Refine flowgraph nodes for readability
  internal/datanode/buffer.go
  internal/datanode/buffer_test.go
  internal/datanode/compaction_executor.go
  internal/datanode/compactor.go
  internal/datanode/flow_graph_delete_node.go
  internal/datanode/flow_graph_insert_buffer_node.go
  internal/datanode/flow_graph_insert_buffer_node_test.go
  internal/datanode/flow_graph_message.go
  internal/proto/data_coord.proto
  internal/proto/datapb/data_coord.pb.go
Labels: kind/improvement, size/XXL, approved, lgtm, ci-passed, dco-passed

#19898 [test]Add test case for bulk insert
  tests/python_client/bulk_insert/test_bulk_insert.py
  tests/python_client/bulk_insert/test_bulk_insert_task_clean.py
Labels: kind/improvement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#19930 [test]Create index before load
  tests/python_client/deploy/scripts/action_before_reinstall.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#19932 Fix proxy trace operation name
  internal/datanode/flow_graph_insert_buffer_node.go
  internal/proxy/impl.go
Labels: kind/bug, kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#19895 Add status for GetVersionResponse and CheckHealthResponse
  go.mod
  go.sum
  internal/distributed/proxy/service.go
  internal/proxy/impl.go
Labels: area/dependency, kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#19918 Modify cases because error code of connectionNotExistException changed
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#19884 Fix wrong msg when load failed
  internal/proxy/impl.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#19937 Upgrade pymilvus version and update test cases for index and flush
  tests/python_client/requirements.txt
  tests/python_client/testcases/test_utility.py
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#19936 Fix compaction produces empty segment
  internal/datacoord/compaction.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#19945 [test]Update index issue for deploy test
  tests/python_client/deploy/testcases/test_action_second_deployment.py
Labels: kind/improvement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#19944 Fix collection metrics leakage
  internal/proxy/impl.go
  internal/proxy/meta_cache.go
  internal/rootcoord/alter_collection_task.go
  internal/rootcoord/create_partition_task.go
  internal/rootcoord/drop_partition_task.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed

#19956 Fix panic while applying deletions
  internal/querynode/flow_graph_delete_node.go
  internal/querynode/flow_graph_insert_node.go
  internal/querynode/segment.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#19938 Can't drop loaded partition
  internal/proxy/impl.go
  internal/proxy/query_coord_mock_test.go
  internal/proxy/task.go
  internal/proxy/task_index.go
  internal/proxy/task_test.go
  internal/proxy/util.go
  internal/proxy/util_test.go
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#19912 Fill MsgBase ALL
  internal/allocator/id_allocator.go
  internal/datacoord/allocator.go
  internal/datacoord/cluster.go
  internal/datacoord/server.go
  internal/datacoord/services.go
  internal/datacoord/session_manager.go
  internal/datanode/allocator.go
  internal/datanode/data_node.go
  internal/datanode/data_sync_service.go
  internal/datanode/flow_graph_dd_node.go
  internal/datanode/flow_graph_insert_buffer_node.go
  internal/datanode/flush_manager.go
  internal/datanode/meta_service.go
  internal/distributed/datacoord/client/client.go
  internal/distributed/indexcoord/client/client.go
  internal/distributed/proxy/client/client.go
  internal/distributed/querycoord/client/client.go
  internal/distributed/rootcoord/client/client.go
  internal/indexcoord/task.go
  internal/mq/msgstream/msg.go
  internal/proxy/impl.go
  internal/proxy/task.go
  internal/proxy/task_statistic.go
  internal/proxy/test_delete.go
  internal/querycoordv2/dist/dist_handler.go
  internal/querycoordv2/meta/coordinator_broker.go
  internal/querycoordv2/observers/leader_observer.go
  internal/querycoordv2/task/utils.go
  internal/querynode/task.go
  internal/rootcoord/broker.go
  internal/rootcoord/create_collection_task.go
  internal/rootcoord/expire_cache.go
  internal/rootcoord/garbage_collector.go
  internal/rootcoord/quota_center.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/timeticksync.go
  internal/util/commonpbutil/commonpbutil.go
  internal/util/metricsinfo/metric_type.go
Labels: kind/improvement, size/XL, approved, lgtm, ci-passed, dco-passed, manual-pass

#19970 Fix mis-copy of chunk in make_with_timestamps
  internal/core/src/segcore/SegmentSealedImpl.cpp
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#19950 Optimize ddl case when collection not exist
  internal/rootcoord/meta_table.go
  internal/rootcoord/meta_table_test.go
  internal/rootcoord/util.go
  internal/rootcoord/util_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#19980 [skip e2e] Fix test cases
  tests/python_client/testcases/test_search.py
Labels: kind/improvement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#19977 Modify test cases of connection error
  tests/python_client/common/common_type.py
  tests/python_client/testcases/test_connection.py
Labels: sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#19966 Skip build aws sdk when not need diskann (#19965)
  internal/core/thirdparty/CMakeLists.txt
Labels: size/XS, approved, lgtm, ci-passed, dco-passed, area/compilation

#19981 Improve the `stop` command
  scripts/stop.sh
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#19943 If autoID enabled, check to make sure user didn't specify autoID field
  internal/proxy/task_insert.go
  internal/util/typeutil/schema.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#19985 Add datanode&channel match check for Flush
  internal/datacoord/cluster.go
  internal/datacoord/cluster_test.go
  internal/datacoord/server.go
  internal/datanode/flow_graph_insert_buffer_node.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed
