Repository milvus-io/milvus, pull requests merged in 2022-11, with the labels that each got.

#20164 Add support for GCS(GoogleCloudStorage) with IAM
  configs/milvus.yaml
  go.mod
  internal/storage/factory.go
  internal/storage/gcp/gcp.go
  internal/storage/gcp/gcp_test.go
  internal/storage/minio_chunk_manager.go
  internal/storage/minio_chunk_manager_test.go
  internal/storage/options.go
  internal/util/indexcgowrapper/index.go
  internal/util/paramtable/base_table.go
  internal/util/paramtable/service_param.go
  internal/util/paramtable/service_param_test.go
Labels: area/dependency, size/L, approved, lgtm, ci-passed, dco-passed

#20224 [skip e2e] Expire migration session asap and fix exit code
  cmd/tools/migration/console/console.go
  cmd/tools/migration/migration/runner.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#20165 Check whether ubsubscribe/release task is stale
  internal/querycoordv2/task/scheduler.go
  internal/querycoordv2/task/task_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#20230 Fix session alive bug for meta migration script
  deployments/migrate-meta/migrate.sh
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#20189 Refine request merger
  internal/querycoordv2/meta/target_manager.go
  internal/querycoordv2/task/executor.go
  internal/querycoordv2/task/merger.go
  internal/querycoordv2/task/merger_test.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#20220 Revert Concurrent Load Segment Task
  internal/querynode/impl.go
  internal/querynode/load_segment_task.go
  internal/querynode/segment_loader.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#20219 Fix Segment Mutation lock
  internal/datanode/channel_meta.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#20244 revert concurrent segment load
  internal/querynode/impl.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#20240 Use compaction generated segment's checkpoint as compacted segment's seekPosition
  internal/datacoord/meta.go
  internal/datacoord/services.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#20238 Release delta flowgraph if loadSegment failed
  internal/querynode/load_segment_task.go
  internal/querynode/load_segment_task_test.go
  internal/querynode/task_test.go
Labels: size/XL, approved, lgtm, ci-passed, dco-passed

#20197 Make sure the query node isn't created repeatedly in concurrent situation
  internal/querycoordv2/session/cluster.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed

#20237 [skip e2e] Modify kafka configuration for nightly
  tests/scripts/values/kafka.yaml
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#20223 Modify test cases due to update of drop index
  tests/python_client/testcases/test_index.py
Labels: sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#20234 Only allow one file for row-based import
  internal/proxy/proxy_test.go
  internal/rootcoord/import_manager.go
  internal/rootcoord/import_manager_test.go
  internal/util/importutil/import_util.go
  internal/util/importutil/import_wrapper.go
  internal/util/importutil/import_wrapper_test.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#20239 Add role name to ttDelay metric
  internal/metrics/metrics.go
  internal/metrics/rootcoord_metrics.go
  internal/rootcoord/quota_center.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#20242 Fix querynode panic during stop
  internal/querynode/query_node.go
  internal/querynode/shard_cluster_service.go
  internal/querynode/shard_cluster_service_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#20261 Add install support to mac
  Makefile
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed, area/compilation

#20269 Fix rmq consumer cancel may block forever
  internal/mq/msgstream/mqwrapper/rmq/rmq_consumer.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#20277 Update bulk_insert to do_bulk_insert
  tests/python_client/base/utility_wrapper.py
  tests/python_client/bulk_insert/test_bulk_insert.py
  tests/python_client/bulk_insert/test_bulk_insert_task_clean.py
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#20279 Update pymilvus version in requirements.txt
  tests/python_client/requirements.txt
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#20278 Split large Etcd operations while altering segment info
  internal/metastore/kv/datacoord/kv_catalog.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#20282 [skip e2e] Exit migration after session expired
  cmd/tools/migration/command/backup.go
  cmd/tools/migration/command/rollback.go
  cmd/tools/migration/command/run.go
  cmd/tools/migration/console/code.go
  cmd/tools/migration/console/console.go
  cmd/tools/migration/console/exit.go
  cmd/tools/migration/console/exit_config.go
  cmd/tools/migration/migration/runner.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#20265 Improve DataCoord and DataNode logs
  internal/datacoord/compaction.go
  internal/datacoord/handler.go
  internal/datacoord/meta.go
  internal/datacoord/meta_test.go
  internal/datanode/channel_meta.go
  internal/util/tsoutil/tso.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#20284 Recuce memory consumption in MinioChunkManager
  internal/storage/local_chunk_manager.go
  internal/storage/minio_chunk_manager.go
  internal/storage/minio_chunk_manager_test.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#20286 Fix Proxy never updates the shard leaders cache
  internal/proxy/task_policies.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#20287 [skip e2e] Improve a commment for initial pr
  internal/datanode/flow_graph_manager.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#20288 Refactor Makefile to reduce duplicate steps for ci-ut
  .github/workflows/main.yaml
  Makefile
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed, area/compilation

#20267 Remove dup mock_kv.go and mock_txn_kv.go
  internal/datacoord/garbage_collector_test.go
  internal/datacoord/meta_test.go
  internal/datacoord/mock_test.go
  internal/datacoord/segment_manager_test.go
  internal/datacoord/server_test.go
  internal/kv/kv.go
  internal/kv/mock_kv.go
  internal/kv/mock_kv_test.go
  internal/kv/mock_txn_kv.go
  internal/kv/mocks/SnapShotKV.go
  internal/rootcoord/import_manager.go
  internal/rootcoord/import_manager_test.go
  internal/rootcoord/mock_test.go
  internal/rootcoord/root_coord_test.go
Labels: kind/improvement, size/XL, approved, lgtm, ci-passed, dco-passed

#20292 [skip e2e] Add sign for auto pytest pr && change the e2e image
  .github/workflows/publish-test-images.yaml
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#20263 Fix Release tasks may end with incorrect status
  internal/querycoordv2/task/action.go
  internal/querycoordv2/task/scheduler.go
  internal/querycoordv2/task/task_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#20271 Print seek postion time and seek elapse
  internal/datanode/flow_graph_dmstream_input_node.go
  internal/querynode/flow_graph_delete_node.go
  internal/querynode/flow_graph_filter_delete_node.go
  internal/querynode/flow_graph_filter_dm_node.go
  internal/querynode/flow_graph_insert_node.go
  internal/querynode/flow_graph_node.go
  internal/querynode/flow_graph_query_node.go
  internal/querynode/flow_graph_service_time_node.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#20078 [test]Update requirements for test
  ci/jenkins/pod/e2e.yaml
  tests/docker/Dockerfile
  tests/python_client/base/collection_wrapper.py
  tests/python_client/deploy/scripts/utils.py
  tests/python_client/requirements.txt
Labels: kind/improvement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#20180 [test]Update test cases for deploy and chaos test
  tests/python_client/deploy/scripts/action_after_reinstall.py
  tests/python_client/deploy/scripts/action_after_upgrade.py
  tests/python_client/deploy/scripts/action_before_reinstall.py
  tests/python_client/deploy/scripts/action_before_upgrade.py
  tests/python_client/deploy/scripts/utils.py
  tests/python_client/deploy/testcases/test_action_first_deployment.py
  tests/python_client/deploy/testcases/test_action_second_deployment.py
Labels: kind/improvement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#20300 [skip e2e] Update pytest image tag for the right ci yaml
  .github/workflows/publish-test-images.yaml
Labels: size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#20302 Fix log when building index
  internal/indexnode/indexnode_service.go
  internal/indexnode/task.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#20309 Don't build BIN_FLAT index really
  internal/indexcoord/const.go
  internal/indexcoord/flush_segment_watcher.go
  internal/indexcoord/flushed_segment_watcher_test.go
  internal/indexcoord/index_builder.go
  internal/indexcoord/util.go
  internal/indexcoord/util_test.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#20307 Fix get cpu num for segcore (#20120)
  internal/core/src/common/Common.cpp
  internal/core/src/common/Common.h
  internal/core/src/common/Consts.h
  internal/core/src/common/init_c.cpp
  internal/core/src/common/init_c.h
  internal/core/src/storage/ThreadPool.h
  internal/indexnode/indexnode.go
  internal/querynode/query_node.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#20304 Fix search failed with nil result
  internal/querynode/search.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#20295 Delete unused messages for the mq
  internal/mq/msgstream/mq_msgstream_test.go
  internal/mq/msgstream/msg.go
  internal/mq/msgstream/msg_test.go
  internal/mq/msgstream/unmarshal.go
  internal/querynode/mock_test.go
Labels: kind/improvement, size/XL, approved, lgtm, ci-passed, dco-passed

#20314 Remove teardown for bulk_insert tests
  tests/python_client/README.md
  tests/python_client/bulk_insert/test_bulk_insert.py
  tests/python_client/bulk_insert/test_bulk_insert_task_clean.py
Labels: sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#20328 Change default thread core coefficient (#20120)
  configs/milvus.yaml
  internal/util/paramtable/component_param.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#20336 [skip e2e] Add role_name for time_tick_delay panel of milvus dashboard
  deployments/monitor/grafana/milvus-dashboard.json
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#20333 Change default thread core coefficient (#20120) (#20328)
  configs/milvus.yaml
  internal/util/paramtable/component_param.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#20325 Open c++ log
  configs/easylogging.yaml
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#20345 [skip e2e] Disable ConcurrentBuilds for publish image to reducee resources
  ci/jenkins/PublishImages.groovy
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#20346 [skip e2e] Disable ConcurrentBuilds for publish image to reducee reso…
  ci/jenkins/PublishImages.groovy
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#20344 Remove KeyLock from querynode task
  internal/querynode/impl.go
  internal/querynode/mock_test.go
  internal/querynode/query_node.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#20347 Open c++ log
  configs/easylogging.yaml
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#20321 Support GC Tuner
  internal/querynode/query_node.go
  internal/util/gc/gc_tuner.go
  internal/util/paramtable/component_param.go
Labels: kind/feature, size/L, approved, lgtm, ci-passed, dco-passed

#20351 Add GCTuner
  internal/querynode/query_node.go
  internal/util/gc/gc_tuner.go
  internal/util/paramtable/component_param.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#20349 [cherry-pick] Remove KeyLock from querynode task
  internal/querynode/impl.go
  internal/querynode/mock_test.go
  internal/querynode/query_node.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#20296 Add some msgstream metrics
  deployments/monitor/grafana/README.md
  deployments/monitor/grafana/milvus-dashboard.json
  internal/datacoord/server.go
  internal/datanode/flow_graph_dd_node.go
  internal/datanode/flow_graph_dmstream_input_node.go
  internal/datanode/flow_graph_insert_buffer_node.go
  internal/metrics/datacoord_metrics.go
  internal/metrics/datanode_metrics.go
  internal/metrics/metrics.go
  internal/metrics/proxy_metrics.go
  internal/metrics/querynode_metrics.go
  internal/metrics/rootcoord_metrics.go
  internal/proxy/proxy.go
  internal/querynode/flow_graph_query_node.go
  internal/rootcoord/timeticksync.go
  internal/util/flowgraph/input_node.go
  internal/util/flowgraph/input_node_test.go
  internal/util/flowgraph/node_test.go
  internal/util/tsoutil/tso.go
Labels: kind/improvement, size/XXL, approved, lgtm, ci-passed, dco-passed

#20353 Fix GC Tuner when memory is too large
  internal/util/gc/gc_tuner.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#20354 Fix GCTuner calculation overflow
  internal/util/gc/gc_tuner.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#20327 Make index log better
  internal/indexcoord/index_coord.go
  internal/indexcoord/util_test.go
  internal/indexnode/indexnode.go
  internal/indexnode/indexnode_service.go
  internal/indexnode/task.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#20364 Refine task's priority
  internal/querycoordv2/checkers/balance_checker.go
  internal/querycoordv2/checkers/channel_checker.go
  internal/querycoordv2/task/scheduler.go
  internal/querycoordv2/task/utils.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#20368 Add healthy check for InvalidateCollectionMetaCache
  internal/proxy/impl.go
  internal/proxy/impl_test.go
  internal/proxy/proxy_test.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#20306 Skip handoff event on unloaded partition
  internal/querycoordv2/job/job_test.go
  internal/querycoordv2/observers/handoff_observer.go
  internal/querycoordv2/observers/handoff_observer_test.go
  internal/querycoordv2/server.go
  internal/querycoordv2/server_test.go
  internal/querycoordv2/services_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#20361 Fix version not deleted if expired by loadSegment
  internal/querynode/shard_cluster.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#20301 Fix listImportTasks bug
  internal/indexcoord/index_coord.go
  internal/rootcoord/import_manager.go
  internal/rootcoord/import_manager_test.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
  internal/util/importutil/binlog_adapter.go
  internal/util/importutil/binlog_adapter_test.go
  internal/util/importutil/binlog_file.go
  internal/util/importutil/binlog_parser.go
  internal/util/importutil/import_util.go
  internal/util/importutil/import_util_test.go
  internal/util/importutil/import_wrapper.go
  internal/util/importutil/import_wrapper_test.go
  internal/util/importutil/json_handler.go
  internal/util/importutil/json_handler_test.go
  internal/util/importutil/json_parser.go
  internal/util/importutil/numpy_adapter.go
  internal/util/importutil/numpy_parser.go
Labels: kind/bug, size/XL, approved, lgtm, ci-passed, dco-passed, manual-pass

#20370 Refine task's priority (#20364)
  internal/querycoordv2/checkers/balance_checker.go
  internal/querycoordv2/checkers/channel_checker.go
  internal/querycoordv2/task/scheduler.go
  internal/querycoordv2/task/utils.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#20213 Fix where Datanode crash due to oom when delta buff accumulating constantly because of non auto flush
  configs/milvus.yaml
  internal/datanode/buffer.go
  internal/datanode/compactor.go
  internal/datanode/compactor_test.go
  internal/datanode/flow_graph_delete_node.go
  internal/datanode/flow_graph_delete_node_test.go
  internal/util/paramtable/component_param.go
Labels: size/XL, approved, lgtm, ci-passed, dco-passed

#20372 Fix listImportTasks bug
  internal/indexcoord/index_coord.go
  internal/rootcoord/import_manager.go
  internal/rootcoord/import_manager_test.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
  internal/util/importutil/binlog_adapter.go
  internal/util/importutil/binlog_adapter_test.go
  internal/util/importutil/binlog_file.go
  internal/util/importutil/binlog_parser.go
  internal/util/importutil/import_util.go
  internal/util/importutil/import_util_test.go
  internal/util/importutil/import_wrapper.go
  internal/util/importutil/import_wrapper_test.go
  internal/util/importutil/json_handler.go
  internal/util/importutil/json_handler_test.go
  internal/util/importutil/json_parser.go
  internal/util/importutil/numpy_adapter.go
  internal/util/importutil/numpy_parser.go
Labels: kind/bug, size/XL, approved, lgtm, ci-passed, dco-passed, manual-pass

#19296 update target for querycoordv2
  internal/metastore/catalog.go
  internal/proto/query_coord.proto
  internal/proto/querypb/query_coord.pb.go
  internal/querycoordv2/checkers/channel_checker.go
  internal/querycoordv2/checkers/channel_checker_test.go
  internal/querycoordv2/checkers/segment_checker.go
  internal/querycoordv2/checkers/segment_checker_test.go
  internal/querycoordv2/dist/dist_controller_test.go
  internal/querycoordv2/dist/dist_handler.go
  internal/querycoordv2/handlers.go
  internal/querycoordv2/job/job.go
  internal/querycoordv2/job/job_test.go
  internal/querycoordv2/meta/channel_dist_manager.go
  internal/querycoordv2/meta/leader_view_manager.go
  internal/querycoordv2/meta/leader_view_manager_test.go
  internal/querycoordv2/meta/mock_store.go
  internal/querycoordv2/meta/store.go
  internal/querycoordv2/meta/target.go
  internal/querycoordv2/meta/target_manager.go
  internal/querycoordv2/meta/target_manager_test.go
  internal/querycoordv2/observers/collection_observer.go
  internal/querycoordv2/observers/collection_observer_test.go
  internal/querycoordv2/observers/handoff_observer.go
  internal/querycoordv2/observers/handoff_observer_test.go
  internal/querycoordv2/observers/leader_observer.go
  internal/querycoordv2/observers/leader_observer_test.go
  internal/querycoordv2/observers/target_observer.go
  internal/querycoordv2/observers/target_observer_test.go
  internal/querycoordv2/server.go
  internal/querycoordv2/server_test.go
  internal/querycoordv2/services.go
  internal/querycoordv2/services_test.go
  internal/querycoordv2/task/executor.go
  internal/querycoordv2/task/scheduler.go
  internal/querycoordv2/task/task_test.go
  internal/querycoordv2/utils/meta.go
  internal/querycoordv2/utils/test.go
  internal/querynode/data_sync_service_test.go
  internal/querynode/flow_graph_delete_node_test.go
  internal/querynode/flow_graph_insert_node.go
  internal/querynode/flow_graph_insert_node_test.go
  internal/querynode/impl.go
  internal/querynode/meta_replica.go
  internal/querynode/meta_replica_test.go
  internal/querynode/mock_test.go
  internal/querynode/query_node_test.go
  internal/querynode/segment.go
  internal/querynode/segment_loader.go
  internal/querynode/segment_loader_test.go
  internal/querynode/segment_test.go
  internal/util/paramtable/component_param.go
Labels: kind/enhancement, size/XXL, approved, lgtm, ci-passed, area/internal-api, dco-passed

#20378 [Cherry-pick] Add healthy check for InvalidateCollectionMetaCache (#20368)
  internal/proxy/impl.go
  internal/proxy/impl_test.go
  internal/proxy/proxy_test.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#20334 Pass backup flag through Import request options
  internal/datanode/data_node.go
  internal/util/importutil/import_options.go
  internal/util/importutil/import_options_test.go
  internal/util/importutil/import_wrapper.go
  internal/util/importutil/import_wrapper_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#20374 Pass backup flag through Import request options
  internal/datanode/data_node.go
  internal/util/importutil/import_options.go
  internal/util/importutil/import_options_test.go
  internal/util/importutil/import_wrapper.go
  internal/util/importutil/import_wrapper_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#20388 Filter segments when doing FromDmlCPLoadDelete
  internal/querynode/load_segment_task.go
  internal/querynode/load_segment_task_test.go
  internal/querynode/segment_loader.go
  internal/querynode/segment_loader_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#20380 Fix gcp oauth token not cached
  internal/storage/gcp/gcp.go
  internal/storage/gcp/gcp_test.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#20392 [Cherry-pick] Filter segments when doing FromDmlCPLoadDelete (#20388)
  internal/querynode/load_segment_task.go
  internal/querynode/load_segment_task_test.go
  internal/querynode/segment_loader.go
  internal/querynode/segment_loader_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#20376 Fix datarace at Setlogger
  cmd/milvus/run.go
  cmd/roles/roles.go
  internal/datacoord/server.go
  internal/datanode/data_node.go
  internal/indexcoord/index_coord.go
  internal/indexnode/indexnode.go
  internal/proxy/proxy.go
  internal/querycoordv2/server.go
  internal/querynode/query_node.go
  internal/rootcoord/root_coord.go
  internal/util/paramtable/base_table.go
  internal/util/paramtable/base_table_test.go
  internal/util/paramtable/component_param.go
  internal/util/paramtable/runtime.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#20379 [cherry-pick]skip handoff event on unloaded partition
  internal/querycoordv2/job/job_test.go
  internal/querycoordv2/observers/handoff_observer.go
  internal/querycoordv2/observers/handoff_observer_test.go
  internal/querycoordv2/server.go
  internal/querycoordv2/server_test.go
  internal/querycoordv2/services_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#20396 Fix gcp oauth token not cached
  internal/storage/gcp/gcp.go
  internal/storage/gcp/gcp_test.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#20339 Improve panic error readability
  internal/core/src/segcore/SegmentSealedImpl.cpp
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#20385 Close the no-use chan in the querycoord node
  internal/querycoordv2/job/scheduler.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#20297 [test]Fix index after load for chaos test
  tests/python_client/base/collection_wrapper.py
  tests/python_client/chaos/checker.py
  tests/python_client/chaos/testcases/test_all_collections_after_chaos.py
  tests/python_client/chaos/testcases/test_data_persistence.py
  tests/python_client/testcases/test_e2e.py
Labels: kind/improvement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#20341 [test]Fix bulk insert chaos test
  tests/python_client/chaos/checker.py
  tests/python_client/chaos/test_chaos_bulk_insert.py
Labels: kind/improvement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#20400 Modify test cases related to pagination
  tests/python_client/base/collection_wrapper.py
  tests/python_client/testcases/test_query.py
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#20382 [2.2.0] Refresh targets if haven't make progress for 5mins
  configs/milvus.yaml
  internal/querycoordv2/job/job.go
  internal/querycoordv2/observers/collection_observer.go
  internal/querycoordv2/observers/collection_observer_test.go
  internal/querycoordv2/observers/handoff_observer.go
  internal/querycoordv2/server.go
  internal/util/paramtable/component_param.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#20391 Add goroutines pool for creating index
  internal/indexcoord/index_coord.go
  internal/indexnode/indexnode.go
  internal/indexnode/indexnode_service.go
  internal/indexnode/task.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#20401 fix check segment stale task
  internal/querycoordv2/task/scheduler.go
  internal/querycoordv2/task/task_test.go
  internal/util/paramtable/component_param.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#20381 [skip e2e] Move codecov as separate job
  .github/workflows/main.yaml
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#20313 Add time log for methods of starting the node
  internal/datacoord/channel_store.go
  internal/datacoord/meta.go
  internal/indexcoord/flush_segment_watcher.go
  internal/indexcoord/meta_table.go
  internal/querycoordv2/server.go
  internal/rootcoord/meta_table.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed

#20331 Make the subName unique for the datanode tt channel
  internal/datacoord/server.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#20409 Fix rpc log of Proxy
  internal/proxy/channels_time_ticker.go
  internal/proxy/impl.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#20413 Fix log of alter collection
  internal/rootcoord/broker.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#20424 Remove kafka consumer ack
  internal/mq/msgstream/mqwrapper/kafka/kafka_consumer.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#20408 [pick] Add goroutine pool for creating index (#20391)
  internal/indexcoord/index_coord.go
  internal/indexnode/indexnode.go
  internal/indexnode/indexnode_service.go
  internal/indexnode/task.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#20403 Fix an error message
  internal/rootcoord/meta_table.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#20404 Fix an error message
  internal/rootcoord/meta_table.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#20411 Fix some unreasonable logs in Proxy
  internal/proxy/segment.go
  internal/proxy/task_insert.go
  internal/proxy/task_scheduler.go
  internal/proxy/task_search.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#20412 Fix log of RootCoord
  internal/rootcoord/proxy_client_manager.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/timeticksync.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#20429 Fix querycoord metrics
  internal/querycoordv2/server.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#20427 Fix rootcoord metrics
  internal/metastore/model/collection.go
  internal/metastore/model/collection_test.go
  internal/rootcoord/meta_table.go
  internal/rootcoord/meta_table_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#20407 Fix log of delete
  internal/proxy/task_delete.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#20434 Upgrade Knowhere to 1.3.3 to fix potential bugs
  internal/core/thirdparty/knowhere/CMakeLists.txt
Labels: size/XS, approved, lgtm, ci-passed, dco-passed, area/compilation

#20441 Fix rpc log of Proxy (#20409)
  internal/proxy/channels_time_ticker.go
  internal/proxy/impl.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#20447 Fix rootcoord metrics (#20427)
  internal/metastore/model/collection.go
  internal/metastore/model/collection_test.go
  internal/rootcoord/meta_table.go
  internal/rootcoord/meta_table_test.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#20431 Dont expire pending import tasks
  internal/proto/data_coord.proto
  internal/proto/datapb/data_coord.pb.go
  internal/rootcoord/import_manager.go
  internal/rootcoord/import_manager_test.go
  internal/util/importutil/import_options.go
  internal/util/importutil/import_wrapper.go
Labels: size/XL, approved, lgtm, ci-passed, dco-passed

#20432 Dont expire pending import tasks
  internal/proto/data_coord.proto
  internal/proto/datapb/data_coord.pb.go
  internal/rootcoord/import_manager.go
  internal/rootcoord/import_manager_test.go
  internal/util/importutil/import_options.go
  internal/util/importutil/import_wrapper.go
Labels: size/XL, approved, lgtm, ci-passed, dco-passed

#20414 Remove the unnecessary lock in the shard_cluster
  internal/querynode/shard_cluster.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#20428 Fix log of alter collection (#20413)
  internal/rootcoord/broker.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#20435 Fix log of RootCoord (#20412)
  internal/rootcoord/proxy_client_manager.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/timeticksync.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#20436 Fix some unreasonable logs in Proxy (#20411)
  internal/proxy/segment.go
  internal/proxy/task_insert.go
  internal/proxy/task_scheduler.go
  internal/proxy/task_search.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#20446 Fix delete log (#20407)
  internal/proxy/task_delete.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#20426 Improv/search metric
  internal/metrics/metrics.go
  internal/metrics/querynode_metrics.go
  internal/querynode/impl.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed

#20425 Drop fail jobs on indexnode
  internal/indexcoord/index_builder.go
  internal/indexcoord/index_builder_test.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed

#20458 [test]Update timeout for query
  tests/python_client/deploy/scripts/utils.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#20454 Remove too frequent logs
  internal/datanode/data_node.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#20461 Refine QueryCoordV2 metrics
  internal/metrics/querycoord_metrics.go
  internal/querycoordv2/job/job.go
  internal/querycoordv2/server.go
  internal/querycoordv2/session/node_manager.go
  internal/querycoordv2/task/scheduler.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#20462 Use all() api for bitset check
  internal/core/src/query/visitors/ExecPlanNodeVisitor.cpp
Labels: size/S, approved, lgtm, ci-passed, dco-passed

#20456 Clear stale replicas
  internal/querycoordv2/job/job.go
  internal/querycoordv2/meta/replica_manager.go
  internal/querycoordv2/meta/replica_manager_test.go
  internal/querycoordv2/server.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#20471 Refine QueryCoordV2 metrics
  internal/metrics/querycoord_metrics.go
  internal/querycoordv2/job/job.go
  internal/querycoordv2/server.go
  internal/querycoordv2/session/node_manager.go
  internal/querycoordv2/task/scheduler.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#19927 add access log for proxy
  configs/milvus.yaml
  internal/distributed/proxy/service.go
  internal/log/config.go
  internal/log/log_test.go
  internal/log/zap_log_test.go
  internal/log/zap_text_encoder.go
  internal/proxy/accesslog/access_log.go
  internal/proxy/accesslog/access_log_test.go
  internal/proxy/accesslog/chown.go
  internal/proxy/accesslog/chown_linux.go
  internal/proxy/accesslog/log_writer.go
  internal/proxy/accesslog/log_writer_test.go
  internal/proxy/accesslog/minio_handler.go
  internal/proxy/accesslog/minio_handler_test.go
  internal/proxy/accesslog/util.go
  internal/proxy/accesslog/util_test.go
  internal/proxy/proxy.go
  internal/util/logutil/logutil.go
  internal/util/paramtable/component_param.go
  internal/util/paramtable/component_param_test.go
Labels: kind/enhancement, size/XXL, approved, lgtm, ci-passed, dco-passed

#20483 skip balance on loading collection
  internal/querycoordv2/balance/rowcount_based_balancer.go
  internal/querycoordv2/balance/rowcount_based_balancer_test.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#20488 Add RootPath field back
  internal/log/config.go
  internal/util/logutil/logutil.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#20470 Reduce the memory used by load disk index
  configs/milvus.yaml
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#20496 [pick] Drop fail jobs on indexnode (#20425)
  internal/indexcoord/index_builder.go
  internal/indexcoord/index_builder_test.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed

#20487 [Cherry-Pick] Clear stale replicas
  internal/querycoordv2/job/job.go
  internal/querycoordv2/meta/replica_manager.go
  internal/querycoordv2/meta/replica_manager_test.go
  internal/querycoordv2/server.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#20494 [test]Fix bulk insert testcases
  tests/python_client/bulk_insert/test_bulk_insert.py
Labels: kind/improvement, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#19727 support auth
  configs/milvus.yaml
  internal/mq/msgstream/mq_factory.go
  internal/mq/msgstream/mq_factory_test.go
  internal/mq/msgstream/mq_msgstream_test.go
  internal/mq/msgstream/mqwrapper/pulsar/pulsar_client.go
  internal/mq/msgstream/mqwrapper/pulsar/pulsar_client_test.go
  internal/mq/msgstream/mqwrapper/pulsar/pulsar_consumer_test.go
  internal/mq/msgstream/mqwrapper/pulsar/pulsar_producer_test.go
  internal/util/paramtable/service_param.go
  internal/util/paramtable/service_param_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#20478 fix leader observer sync logic
  internal/querycoordv2/checkers/segment_checker.go
  internal/querycoordv2/checkers/segment_checker_test.go
  internal/querycoordv2/observers/leader_observer.go
  internal/querycoordv2/observers/leader_observer_test.go
  internal/querycoordv2/task/task.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#20449 Refine dashboard
  deployments/monitor/grafana/milvus-dashboard.json
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#20505 Only log if the refresh actually happens
  internal/querycoordv2/observers/collection_observer.go
  internal/util/indexparams/disk_index_params_test.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#20484 [test]Add assert for replica num
  tests/python_client/deploy/testcases/test_action_second_deployment.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#20507 [cherry-pick]skip balance on loading collection
  internal/querycoordv2/balance/rowcount_based_balancer.go
  internal/querycoordv2/balance/rowcount_based_balancer_test.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#20514 Fix checkFullLoaded always returns all partitions as unloaded
  internal/proxy/task_statistic.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#20516 Modify test case for async indexing
  tests/python_client/testcases/test_index.py
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#20521 [test]Add bulk insert testcases
  tests/python_client/bulk_insert/test_bulk_insert_perf.py
  tests/python_client/bulk_insert/test_bulk_insert_with_requests.py
  tests/python_client/chaos/checker.py
  tests/python_client/chaos/testcases/test_concurrent_operation.py
Labels: kind/improvement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#20465 Scheduler should returns err if the queue is full
  internal/querycoordv2/checkers/controller.go
  internal/querycoordv2/task/scheduler.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#20493 Filter fake segments for recovery info
  internal/datacoord/handler.go
  internal/datacoord/server_test.go
  internal/datacoord/services.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#20526 Modify branch for 2.2.0 nightly
  ci/jenkins/Nightly.groovy
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#20504 Ensure compatibility of channel seek position and move syncPeriod to config
  configs/milvus.yaml
  internal/datacoord/channel_manager.go
  internal/datacoord/handler.go
  internal/datacoord/meta.go
  internal/datacoord/server_test.go
  internal/datanode/flow_graph_insert_buffer_node.go
  internal/datanode/flow_graph_time_tick_node.go
  internal/datanode/segment.go
  internal/datanode/segment_sync_policy.go
  internal/datanode/segment_sync_policy_test.go
  internal/util/paramtable/component_param.go
  internal/util/paramtable/component_param_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#20527 Fix spell PQ error
  configs/milvus.yaml
  internal/util/autoindex/bigdata_index.go
  internal/util/autoindex/bigdata_index_test.go
  internal/util/indexparams/disk_index_params.go
  internal/util/indexparams/disk_index_params_test.go
  internal/util/paramtable/component_param.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#20518 [Cherry Pick]Remove kafka consumer ack
  internal/mq/msgstream/mqwrapper/kafka/kafka_consumer.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#20512 enable delbuf auto flush function to avoid OOM when del msg accumulat…
  configs/milvus.yaml
  internal/datanode/buffer.go
  internal/datanode/compactor.go
  internal/datanode/compactor_test.go
  internal/datanode/flow_graph_delete_node.go
  internal/datanode/flow_graph_delete_node_test.go
  internal/util/paramtable/component_param.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#20491 Fix bulkinsert bug for int64 value
  internal/util/importutil/import_util.go
  internal/util/importutil/import_util_test.go
  internal/util/importutil/json_handler.go
  internal/util/importutil/json_handler_test.go
  internal/util/importutil/json_parser.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#20506 Fix bulkinsert bug for int64 value
  internal/util/importutil/import_util.go
  internal/util/importutil/import_util_test.go
  internal/util/importutil/json_handler.go
  internal/util/importutil/json_handler_test.go
  internal/util/importutil/json_parser.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#20539 [Cherry-Pick] Scheduler should returns err if the queue is full
  internal/querycoordv2/checkers/controller.go
  internal/querycoordv2/task/scheduler.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#20547 Fix test_compact_cross_partition
  tests/python_client/testcases/test_compaction.py
Labels: kind/bug, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#20519 [Cherry-Pick] Fix checkFullLoaded always returns all partitions as unloaded
  internal/proxy/task_statistic.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#20541 Fix log to file not work
  cmd/roles/roles.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#20460 Return real-time indexed rows and total rows
  internal/datacoord/services.go
  internal/indexcoord/garbage_collector.go
  internal/indexcoord/index_coord.go
  internal/indexcoord/index_coord_test.go
  internal/indexcoord/meta_table.go
  internal/indexcoord/meta_table_test.go
  internal/proto/data_coord.proto
  internal/proto/datapb/data_coord.pb.go
  internal/proto/index_coord.proto
  internal/proto/indexpb/index_coord.pb.go
  tests/python_client/testcases/test_utility.py
Labels: kind/improvement, sig/testing, size/XL, approved, lgtm, area/test, ci-passed, area/internal-api, dco-passed

#20537 Fix Time Tick session2ChanTs map use the same nodeID
  cmd/components/root_coord.go
  internal/querynode/query_node.go
  internal/rootcoord/proxy_manager.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
  internal/rootcoord/timeticksync.go
  internal/rootcoord/timeticksync_test.go
  internal/util/sessionutil/session_util.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#20552 [skip e2e] Add time caculate for cpp ut && go ut
  scripts/run_cpp_codecov.sh
  scripts/run_go_codecov.sh
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#20553 fix collection not exist cause query coord panic
  internal/querycoordv2/server.go
  internal/querycoordv2/server_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#20556 Fix test_compact_cross_partition (#20547)
  tests/python_client/testcases/test_compaction.py
Labels: kind/bug, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#20450 Substitute traceid for msgid in rpc
  internal/proxy/impl.go
  internal/proxy/task.go
  internal/proxy/task_insert.go
  internal/proxy/task_query.go
  internal/proxy/task_scheduler.go
  internal/proxy/task_search.go
  internal/proxy/task_statistic.go
  internal/querycoordv2/job/job.go
  internal/querycoordv2/job/scheduler.go
  internal/querycoordv2/services.go
  internal/querynode/impl.go
  internal/querynode/load_segment_task.go
  internal/querynode/shard_cluster.go
  internal/querynode/task_query.go
  internal/querynode/task_search.go
  internal/querynode/task_statistics.go
  internal/rootcoord/root_coord.go
Labels: size/XXL, approved, lgtm, ci-passed, dco-passed, manual-pass

#20503 Make proxy process data definition requests concurrently
  internal/proxy/task_scheduler.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#20557 Remove invalid timestamp
  internal/allocator/id_allocator.go
  internal/datacoord/allocator.go
  internal/datacoord/server.go
  internal/datanode/allocator.go
  internal/datanode/data_node.go
  internal/datanode/data_sync_service.go
  internal/datanode/flush_manager.go
  internal/datanode/meta_service.go
  internal/proxy/impl.go
  internal/proxy/proxy.go
  internal/proxy/timestamp.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed
