Repository milvus-io/milvus, pull requests merged in 2022-06, with the labels that each got.

#17296 Fix err msg of invalid expression
  internal/parser/planparserv2/parser_visitor.go
  internal/parser/planparserv2/plan_parser_v2_test.go
  internal/parser/planparserv2/utils.go
  internal/parser/planparserv2/utils_test.go
  tests/python_client/testcases/test_query.py
Labels: area/dependency, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#17304 [skip e2e]Update account
  MAINTAINERS
  OWNERS_ALIASES
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#17310 Remove error return value when removeSegment
  internal/querynode/impl.go
  internal/querynode/impl_test.go
  internal/querynode/meta_replica.go
  internal/querynode/meta_replica_test.go
  internal/querynode/query_node_test.go
  internal/querynode/segment_loader_test.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#17299 [skip e2e]Add information of etcd to logs in chaos and deploy test
  build/ci/jenkins/ChaosTest.groovy
  build/ci/jenkins/ChaosTestKafkaMQ.groovy
  build/ci/jenkins/DeployTest.groovy
  tests/scripts/export_log_k8s.sh
Labels: kind/improvement, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#17320 [test]Add the testcase with query and search
  tests/python_client/testcases/test_delete.py
  tests/python_client/testcases/test_query.py
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#17306 Add retry mechanism for NodeDown LoadBalance
  internal/querycoord/query_coord.go
  internal/querycoord/task.go
Labels: kind/improvement, size/XL, approved, lgtm, ci-passed, dco-passed

#17317 Add ignorable error to prevent unnecessary panic
  internal/common/error.go
  internal/common/error_test.go
  internal/datanode/flow_graph_dd_node.go
  internal/mq/msgstream/mqwrapper/kafka/kafka_producer.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#17332 Fix mixture
  cmd/milvus/milvus.go
  cmd/roles/roles.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#17316 Enable marisa trie ut on MacOS
  internal/core/src/index/CMakeLists.txt
  internal/core/src/index/IndexFactory-inl.h
  internal/core/src/index/StringIndexMarisa.cpp
  internal/core/src/index/StringIndexMarisa.h
  internal/core/thirdparty/marisa/CMakeLists.txt
  internal/core/unittest/CMakeLists.txt
  internal/core/unittest/test_scalar_index_creator.cpp
  internal/core/unittest/test_string_index.cpp
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed, area/compilation

#17323 Add sasl configurations for kafka
  configs/milvus.yaml
  internal/mq/msgstream/mq_factory.go
  internal/mq/msgstream/mqwrapper/kafka/kafka_client.go
  internal/mq/msgstream/mqwrapper/kafka/kafka_client_test.go
  internal/util/paramtable/service_param.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#17301 Add cache of grpc client of ShardLeader in proxy
  internal/proxy/authentication_interceptor_test.go
  internal/proxy/impl.go
  internal/proxy/meta_cache.go
  internal/proxy/meta_cache_test.go
  internal/proxy/proxy.go
  internal/proxy/proxy_test.go
  internal/proxy/shard_client.go
  internal/proxy/shard_client_test.go
  internal/proxy/task_index_test.go
  internal/proxy/task_policies.go
  internal/proxy/task_policies_test.go
  internal/proxy/task_query.go
  internal/proxy/task_query_test.go
  internal/proxy/task_search.go
  internal/proxy/task_search_test.go
  internal/proxy/task_test.go
  internal/querynode/proxy_mock_test.go
  internal/querynode/proxy_session.go
  internal/querynode/proxy_session_manager.go
  internal/querynode/query_node.go
  internal/querynode/query_node_test.go
  internal/util/funcutil/func.go
  internal/util/funcutil/func_test.go
  internal/util/grpcclient/client.go
Labels: size/XXL, approved, lgtm, ci-passed, dco-passed

#17342 Fix data race in LoadSegmentsTask
  internal/querynode/impl.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#17315 Make Cluster interface's methods called outside public
  internal/querycoord/channel_allocator.go
  internal/querycoord/channel_allocator_test.go
  internal/querycoord/cluster.go
  internal/querycoord/cluster_test.go
  internal/querycoord/impl.go
  internal/querycoord/impl_test.go
  internal/querycoord/meta.go
  internal/querycoord/metrics_info.go
  internal/querycoord/mock_cluster.go
  internal/querycoord/query_coord.go
  internal/querycoord/query_coord_test.go
  internal/querycoord/querynode_test.go
  internal/querycoord/segment_allocator.go
  internal/querycoord/segment_allocator_test.go
  internal/querycoord/task.go
  internal/querycoord/task_scheduler.go
  internal/querycoord/util.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#17293 Make DataNode release rather than delete when reassign
  internal/datacoord/channel_manager.go
  internal/datacoord/channel_manager_test.go
  internal/datacoord/policy.go
  internal/datacoord/policy_test.go
Labels: kind/bug, size/XL, approved, lgtm, ci-passed, dco-passed

#17303 Remove segmentPtr lock and use collection lock instead
  internal/querynode/flow_graph_delete_node.go
  internal/querynode/flow_graph_delete_node_test.go
  internal/querynode/flow_graph_filter_delete_node.go
  internal/querynode/flow_graph_filter_delete_node_test.go
  internal/querynode/flow_graph_filter_dm_node.go
  internal/querynode/flow_graph_filter_dm_node_test.go
  internal/querynode/flow_graph_insert_node.go
  internal/querynode/flow_graph_insert_node_test.go
  internal/querynode/flow_graph_query_node.go
  internal/querynode/segment.go
  internal/querynode/segment_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#17333 [skip e2e]Update config for deploy and chaos test
  build/ci/jenkins/ChaosTest.groovy
  build/ci/jenkins/ChaosTestKafkaMQ.groovy
  build/ci/jenkins/DeployTest.groovy
  build/ci/jenkins/DeployTestKafkaMQ.groovy
  tests/python_client/chaos/cluster-values.yaml
  tests/python_client/chaos/standalone-values.yaml
  tests/python_client/deploy/cluster-values.yaml
  tests/python_client/deploy/standalone-values.yaml
Labels: kind/improvement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#17337 [skip e2e]Add export log step for first deployment
  build/ci/jenkins/DeployTest.groovy
  build/ci/jenkins/DeployTestKafkaMQ.groovy
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#17334 Refine channels management in Proxy.
  internal/proxy/channels_mgr.go
  internal/proxy/channels_mgr_test.go
  internal/proxy/impl.go
  internal/proxy/mock_cache_test.go
  internal/proxy/mock_channels_mgr_test.go
  internal/proxy/mock_msgstream_test.go
  internal/proxy/mock_test.go
  internal/proxy/proxy.go
  internal/proxy/proxy_test.go
  internal/proxy/rootcoord_mock_test.go
  internal/proxy/task.go
  internal/proxy/task_test.go
Labels: sig/testing, size/XXL, approved, lgtm, area/test, ci-passed, dco-passed

#17328 Add metrics in QueryNode and Proxy
  internal/metrics/proxy_metrics.go
  internal/metrics/querynode_metrics.go
  internal/proxy/impl.go
  internal/proxy/meta_cache.go
  internal/querynode/impl.go
  internal/querynode/meta_replica.go
  internal/querynode/segment.go
  internal/querynode/task_scheduler.go
  internal/querynode/task_search.go
  scripts/core_build.sh
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#17308 Fix lost delete msg caused by loadSegment after watchDeltaChannel
  internal/mq/msgstream/repack_func.go
  internal/proto/query_coord.proto
  internal/proto/querypb/query_coord.pb.go
  internal/querycoord/cluster.go
  internal/querycoord/cluster_test.go
  internal/querycoord/meta.go
  internal/querycoord/mock_3rd_component_test.go
  internal/querycoord/query_coord_test.go
  internal/querycoord/task_scheduler_test.go
  internal/querycoord/task_test.go
  internal/querynode/mock_test.go
  internal/querynode/segment_loader_test.go
  internal/querynode/task.go
  internal/querynode/task_test.go
Labels: kind/bug, size/XL, approved, lgtm, ci-passed, area/internal-api, dco-passed

#17260 Add RESTful API for new methods, fix err when receive empty boy
  internal/distributed/proxy/httpserver/handler.go
  internal/distributed/proxy/httpserver/handler_test.go
  internal/distributed/proxy/httpserver/wrapper.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#17273 Improve load performance
  internal/querynode/mock_test.go
  internal/querynode/segment_loader.go
  internal/querynode/segment_loader_test.go
  internal/querynode/task.go
  internal/util/concurrency/future.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#17348 proxy tls support one-way authentication
  configs/milvus.yaml
  docs/user_guides/tls_proxy.md
  internal/distributed/proxy/service.go
  internal/distributed/proxy/service_test.go
  internal/util/paramtable/grpc_param.go
  internal/util/paramtable/grpc_param_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#17292 Support access s3 through AWS IAM role
  configs/milvus.yaml
  internal/datacoord/server.go
  internal/datacoord/server_test.go
  internal/storage/minio_chunk_manager.go
  internal/storage/minio_chunk_manager_test.go
  internal/storage/options.go
  internal/util/dependency/factory.go
  internal/util/paramtable/base_table.go
  internal/util/paramtable/service_param.go
  internal/util/paramtable/service_param_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#17341 Wait for flow graph to exit
  internal/util/flowgraph/flow_graph.go
  internal/util/flowgraph/input_node.go
  internal/util/flowgraph/node.go
  internal/util/flowgraph/node_test.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#17359 [skip e2e]Update the method to check health for deploy
  tests/python_client/deploy/check_healthy.sh
  tests/python_client/deploy/utils.sh
Labels: kind/improvement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#17374 [skip e2e] Disable daily release when repo is not milvus-io/milvus
  .github/workflows/daily-release.yml
Labels: area/dependency, kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#17376 Fix datacoord set wrong state for node registering
  internal/datacoord/channel_manager.go
  internal/datacoord/channel_manager_test.go
  internal/datacoord/compaction_trigger.go
  internal/datacoord/compaction_trigger_test.go
  internal/util/paramtable/component_param.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#17336 Fix typo in publish builder
  .github/workflows/publish-builder.yaml
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#17373 Extract lease of cProto in QueryNode
  internal/querynode/cgo_helper.go
  internal/querynode/segment.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#17364 Make Indexcoord handle etcd error correctly
  internal/datacoord/channel_manager.go
  internal/datanode/data_node.go
  internal/indexcoord/index_coord.go
  internal/indexcoord/meta_table.go
  internal/querynode/query_node.go
  internal/querynode/shard_node_detector.go
  internal/querynode/shard_segment_detector.go
  internal/rootcoord/proxy_manager.go
  internal/util/sessionutil/session_util.go
  internal/util/sessionutil/session_util_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#17382 Fix container/list removal in iteration
  internal/querynode/scheduler_policy.go
  internal/querynode/task_scheduler.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#17377 Make assigning segments faster
  internal/querycoord/querynode.go
  internal/querycoord/segment_allocator.go
  internal/querycoord/task_scheduler.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#17387 Remove unnecessary bitset flip in Search and Query
  internal/core/src/query/visitors/ExecPlanNodeVisitor.cpp
  internal/core/src/segcore/SegmentSealedImpl.cpp
  internal/core/src/segcore/TimestampIndex.cpp
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#17385 Fix several code issues caused by carelessness
  internal/proxy/segment.go
  internal/querynode/global_sealed_segment_manager.go
  internal/querynode/global_sealed_segment_manager_test.go
  internal/querynode/task_scheduler.go
  internal/querynode/task_search.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#17389 Pass PlaceholderGroup pointer to prevent memory copy in SegCore
  internal/core/src/query/generated/ExecPlanNodeVisitor.h
  internal/core/src/query/visitors/ExecPlanNodeVisitor.cpp
  internal/core/src/segcore/SegmentInterface.cpp
  internal/core/src/segcore/SegmentInterface.h
  internal/core/src/segcore/segment_c.cpp
  internal/core/unittest/bench/bench_search.cpp
  internal/core/unittest/test_query.cpp
  internal/core/unittest/test_sealed.cpp
  internal/core/unittest/test_string_expr.cpp
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#17399 [skip e2e]Update the image of etcd for chaos and deploy test
  build/ci/jenkins/ChaosTest.groovy
  build/ci/jenkins/ChaosTestKafkaMQ.groovy
  build/ci/jenkins/DeployTest.groovy
  build/ci/jenkins/DeployTestKafkaMQ.groovy
  tests/python_client/chaos/cluster-values.yaml
  tests/python_client/chaos/standalone-values.yaml
  tests/python_client/deploy/cluster-values.yaml
  tests/python_client/deploy/standalone-values.yaml
Labels: kind/improvement, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#17143 Adaptation for cuda11 and legacy gpu/cpu
  core/CMakeLists.txt
  core/src/index/CMakeLists.txt
  core/src/index/cmake/ThirdPartyPackagesCore.cmake
  core/src/index/thirdparty/faiss/Makefile
  core/src/index/thirdparty/faiss/gpu/utils/DeviceDefs.cuh
  core/src/index/thirdparty/faiss/utils/distances_simd_avx.cpp
  core/src/index/unittest/faiss_ori/CMakeLists.txt
  docker/build_env/gpu/centos7/Dockerfile
  docker/deploy/gpu/centos7/Dockerfile
Labels: size/M, approved, lgtm, ci-passed

#17042 Unified metastore interface
  docs/developer_guides/chap06_root_coordinator.md
  go.mod
  go.sum
  internal/distributed/rootcoord/service_test.go
  internal/metastore/catalog.go
  internal/metastore/kv/constant.go
  internal/metastore/kv/kv_catalog.go
  internal/metastore/kv/meta_snapshot.go
  internal/metastore/kv/meta_snapshot_test.go
  internal/metastore/kv/suffix_snapshot.go
  internal/metastore/kv/suffix_snapshot_test.go
  internal/metastore/model/collection.go
  internal/metastore/model/credential.go
  internal/metastore/model/field.go
  internal/metastore/model/index.go
  internal/metastore/model/model_utils.go
  internal/metastore/model/partition.go
  internal/metastore/model/segment.go
  internal/metastore/table/table_catalog.go
  internal/rootcoord/meta_table.go
  internal/rootcoord/meta_table_test.go
  internal/rootcoord/proxy_manager.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
  internal/rootcoord/task.go
  internal/rootcoord/task_test.go
  internal/rootcoord/util.go
  internal/rootcoord/util_test.go
Labels: area/dependency, area/api, size/XXL, approved, lgtm, ci-passed, area/internal-api, dco-passed

#17407 Upgrade lint version for fixing fails on latest ubuntu-20 image
  .github/workflows/core.yml
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed

#17406 Fix compatibility of upgrade
  internal/util/paramtable/base_table.go
  internal/util/paramtable/base_table_test.go
  internal/util/paramtable/component_param.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#17414 [skip e2e] Lock msys package's versions
  .github/workflows/code-checker.yaml
  scripts/install_deps_msys.sh
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#17391 [skip e2e]Fix log path for deploy test
  build/ci/jenkins/DeployTest.groovy
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#17427 Add debug log in removing assignment
  internal/datacoord/channel_manager.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#17421 Avoid growing slice as deserializing binlogs
  internal/querynode/segment_loader.go
  internal/querynode/segment_loader_test.go
  internal/storage/data_codec.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#17386 Control etcd batch size
  internal/datacoord/channel_store.go
  internal/datacoord/meta.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#17390 [test] Update scale replica case as issue fixed
  build/ci/jenkins/Scale.groovy
  build/ci/jenkins/pod/scale-test.yaml
  tests/python_client/scale/test_index_node_scale.py
  tests/python_client/scale/test_query_node_scale.py
Labels: sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#17440 Fix DataNode processes event out of order
  internal/datanode/data_node.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#17446 [skip e2e]Decrease the timeout time of second test
  .github/workflows/deploy-test.yaml
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#17447 [skip e2e]Display the log of proxy after test
  tests/scripts/export_log_k8s.sh
Labels: kind/improvement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#17442 [test]Set flush timeout as 180s
  tests/python_client/testcases/test_e2e.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#17433 Align kafka consume from latest with puslar and rocksmq
  internal/mq/msgstream/mqwrapper/kafka/kafka_consumer.go
  internal/mq/msgstream/mqwrapper/kafka/kafka_consumer_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#17448 Print more information when loading fields with different lines
  internal/core/src/segcore/SegmentSealedImpl.cpp
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#17454 [skip e2e]Add timeout for some stage
  build/ci/jenkins/DeployTestKafkaMQ.groovy
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#17422 Add verify entities and fields after bulk load
  tests/python_client/bulk_load/bulk_load_data.py
  tests/python_client/bulk_load/test_bulk_load.py
Labels: sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#17459 [skip e2e] Add weekly release for milvus 2.1
  .github/workflows/weekly-release.yml
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#17461 Fix bulkload OOM issue
  internal/util/importutil/import_wrapper.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#17451 Predict the loading memory usage more accurate
  configs/milvus.yaml
  internal/querynode/segment_loader.go
  internal/util/paramtable/component_param.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#17466 [skip e2e]Get pod by label selector when export log
  tests/scripts/export_log_k8s.sh
Labels: kind/improvement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#17467 [skip e2e]Increase installation wait time
  tests/python_client/chaos/scripts/install_milvus_cluster.sh
  tests/python_client/chaos/scripts/install_milvus_standalone.sh
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#17438 Refine logs
  internal/rootcoord/import_manager.go
  internal/rootcoord/root_coord.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#17472 Add Err code when task rollback
  internal/querycoord/task_scheduler.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#17458 [skip e2e] Update milvus dashboard
  deployments/monitor/grafana/milvus-dashboard.json
Labels: kind/improvement, size/XL, approved, lgtm, ci-passed, dco-passed

#17450 Skip remove if reassigns to the original node
  internal/datacoord/channel_manager.go
  internal/datacoord/channel_manager_test.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#17470 Use jemalloc in QueryNode, DataNode and IndexNode
  internal/core/src/segcore/reduce_c.cpp
  internal/core/thirdparty/CMakeLists.txt
  internal/core/thirdparty/jemalloc/CMakeLists.txt
  internal/core/thirdparty/versions.txt
  scripts/start_cluster.sh
  scripts/start_standalone.sh
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, area/compilation

#17480 Revert "Use unified catalog interface to reconstruct metastore (#17042)"
  docs/developer_guides/chap06_root_coordinator.md
  go.mod
  go.sum
  internal/distributed/rootcoord/service_test.go
  internal/metastore/catalog.go
  internal/metastore/kv/constant.go
  internal/metastore/kv/kv_catalog.go
  internal/metastore/model/collection.go
  internal/metastore/model/credential.go
  internal/metastore/model/field.go
  internal/metastore/model/index.go
  internal/metastore/model/model_utils.go
  internal/metastore/model/partition.go
  internal/metastore/model/segment.go
  internal/metastore/table/table_catalog.go
  internal/rootcoord/meta_snapshot.go
  internal/rootcoord/meta_snapshot_test.go
  internal/rootcoord/meta_table.go
  internal/rootcoord/meta_table_test.go
  internal/rootcoord/proxy_manager.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
  internal/rootcoord/suffix_snapshot.go
  internal/rootcoord/suffix_snapshot_test.go
  internal/rootcoord/task.go
  internal/rootcoord/task_test.go
  internal/rootcoord/util.go
  internal/rootcoord/util_test.go
Labels: area/dependency, size/XXL, approved, lgtm, ci-passed, dco-passed

#17469 ignore getReplica's error when handle rebalanceTask
  internal/querycoord/task.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#17476 upgrade ruleguard and integrate into golang-ci
  .golangci.yml
  Makefile
  go.mod
  go.sum
  rules.go
Labels: area/dependency, kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed, area/compilation

#17492 [skip e2e]Set images repo as input parameter for chaos test
  .github/workflows/pod-kill-chaos-test.yaml
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#17496 [skip e2e]Set image repo and tag as input parameters
  .github/workflows/pod-failure-chaos-test.yaml
  .github/workflows/pod-kill-chaos-test-kafka-version.yaml
  .github/workflows/pod-kill-chaos-test.yaml
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#17444 Fix segOffset grater than insert barrier when mark delete
  internal/core/src/query/SearchOnGrowing.cpp
  internal/core/src/segcore/InsertRecord.h
  internal/core/src/segcore/SegmentGrowingImpl.cpp
  internal/core/src/segcore/SegmentGrowingImpl.h
  internal/core/src/segcore/SegmentSealedImpl.cpp
  internal/core/src/segcore/SegmentSealedImpl.h
  internal/core/src/segcore/Utils.cpp
  internal/core/src/segcore/Utils.h
  internal/core/unittest/test_utils.cpp
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#17494 Set jemalloc LD_PRELOAD env to docker image
  build/docker/milvus/centos7/Dockerfile
  build/docker/milvus/ubuntu18.04/Dockerfile
  cmd/roles/roles.go
  scripts/start_cluster.sh
  scripts/start_standalone.sh
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#17501 [skip e2e]Add default value for schedule job
  .github/workflows/pod-failure-chaos-test.yaml
  .github/workflows/pod-kill-chaos-test-kafka-version.yaml
  .github/workflows/pod-kill-chaos-test.yaml
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#17509 [skip e2e] Update url to ci jenkins and clean old qa jenkins data
  .github/workflows/jenkins-checker.yaml
  build/ci/jenkins/qa/PR.groovy
  build/ci/jenkins/qa/pod/rte.yaml
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#17507 [skip e2e]Update pod template and etcd version
  build/ci/jenkins/ChaosTest.groovy
  build/ci/jenkins/ChaosTestKafkaMQ.groovy
  build/ci/jenkins/DeployTest.groovy
  build/ci/jenkins/DeployTestKafkaMQ.groovy
  build/ci/jenkins/pod/chaos-test.yaml
  tests/python_client/chaos/cluster-values.yaml
  tests/python_client/chaos/standalone-values.yaml
  tests/python_client/deploy/cluster-values.yaml
  tests/python_client/deploy/standalone-values.yaml
Labels: kind/improvement, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#17497 Add time record log on search/query execution path
  internal/querynode/impl.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#17510 Adjust keepalive timeout to 20s as default
  configs/milvus.yaml
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#17514 [skip e2e]Remove node selector
  build/ci/jenkins/ChaosTest.groovy
  build/ci/jenkins/ChaosTestKafkaMQ.groovy
  build/ci/jenkins/DeployTest.groovy
  build/ci/jenkins/DeployTestKafkaMQ.groovy
  build/ci/jenkins/pod/chaos-test.yaml
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#17484 Fix %w verb for error wrapping in grpcclient
  internal/util/grpcclient/client.go
  internal/util/grpcclient/client_test.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#17511 Cancel timers while adding new timer
  internal/datacoord/channel_checker.go
  internal/datacoord/channel_checker_test.go
  internal/datacoord/channel_manager.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed

#17522 [skip e2e]Make work node number can be configured
  build/ci/jenkins/ChaosTest.groovy
  build/ci/jenkins/ChaosTestKafkaMQ.groovy
  build/ci/jenkins/DeployTest.groovy
  build/ci/jenkins/DeployTestKafkaMQ.groovy
  tests/python_client/chaos/scripts/install_milvus_cluster.sh
Labels: kind/improvement, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#17519 Sync grpc DefaultKeepAliveTimeout to milvus.yaml
  internal/util/paramtable/grpc_param.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#17516 Add aliases return value in describeCollection task
  internal/proxy/task.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#17533 [skip e2e]Set the log to be exported when the job is not successful
  .github/workflows/deploy-test.yaml
  .github/workflows/pod-failure-chaos-test.yaml
  .github/workflows/pod-kill-chaos-test-kafka-version.yaml
  .github/workflows/pod-kill-chaos-test.yaml
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#17538 Disable jemalloc and use malloc_trim instead
  build/docker/milvus/centos7/Dockerfile
  build/docker/milvus/ubuntu18.04/Dockerfile
  internal/core/src/segcore/reduce_c.cpp
  internal/core/thirdparty/CMakeLists.txt
  scripts/start_cluster.sh
  scripts/start_standalone.sh
Labels: size/M, approved, lgtm, ci-passed, dco-passed, area/compilation

#17539 [skip e2e]Enable serviceMonitor for installation
  tests/python_client/chaos/scripts/install_milvus_cluster.sh
  tests/python_client/chaos/scripts/install_milvus_standalone.sh
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#17473 Change bulkload bufsize for row-based parser
  internal/datanode/data_node.go
  internal/datanode/data_node_test.go
  internal/rootcoord/import_manager.go
  internal/rootcoord/import_manager_test.go
  internal/rootcoord/meta_table.go
  internal/rootcoord/meta_table_test.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
  internal/util/importutil/import_wrapper.go
  internal/util/importutil/import_wrapper_test.go
  internal/util/importutil/json_parser.go
  internal/util/importutil/json_parser_test.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#17547 Handle wrapped grpc error in funcutil.IsGrpcError
  internal/util/funcutil/func.go
  internal/util/funcutil/func_test.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#17531 Add BindContext function for querycoord task scheduler
  internal/querycoord/task.go
  internal/querycoord/task_scheduler.go
  internal/querycoord/task_scheduler_test.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#17553 Fix err msg when the dimension of query vectors mismatch field
  internal/core/src/query/Plan.cpp
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#17457 Add segment reference lock for bulk load
  Makefile
  configs/milvus.yaml
  internal/core/src/pb/common.pb.cc
  internal/core/src/pb/common.pb.h
  internal/datacoord/segment_reference_manager.go
  internal/datacoord/server.go
  internal/datacoord/server_test.go
  internal/datanode/data_node.go
  internal/datanode/mock_test.go
  internal/distributed/rootcoord/service_test.go
  internal/proto/common.proto
  internal/proto/commonpb/common.pb.go
  internal/proto/data_coord.proto
  internal/proto/datapb/data_coord.pb.go
  internal/proto/milvus.proto
  internal/proto/milvuspb/milvus.pb.go
  internal/rootcoord/import_manager.go
  internal/rootcoord/import_manager_test.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
  internal/util/paramtable/component_param.go
Labels: area/api, size/XXL, approved, lgtm, ci-passed, dco-passed, area/compilation

#17558 Remove the redundant 'for' in the TaskCondition
  internal/proxy/condition.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#17548 Fix bug #17403 by double check collmeta prefix and alias prefix
  internal/rootcoord/meta_table.go
  internal/rootcoord/meta_table_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#17554 Fix VDC-510
  internal/datacoord/meta.go
  internal/datacoord/meta_test.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#17543 Delete the log that prints a lot of deleteMsg.timestamps
  internal/querynode/flow_graph_insert_node.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#17545 Improve time record log in search/query
  internal/querynode/impl.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#17550 Fix a bug that causes infinite loop
  internal/datacoord/channel_manager.go
  internal/datacoord/policy.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#17349 Add channel information to flow graph node
  internal/querynode/flow_graph_delete_node.go
  internal/querynode/flow_graph_delete_node_test.go
  internal/querynode/flow_graph_filter_delete_node.go
  internal/querynode/flow_graph_filter_delete_node_test.go
  internal/querynode/flow_graph_filter_dm_node.go
  internal/querynode/flow_graph_filter_dm_node_test.go
  internal/querynode/flow_graph_insert_node.go
  internal/querynode/flow_graph_insert_node_test.go
  internal/querynode/flow_graph_query_node.go
  internal/querynode/mock_test.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#17544 Acquiring the segment reference lock on task level
  internal/datacoord/garbage_collector_test.go
  internal/datacoord/segment_reference_manager.go
  internal/datacoord/segment_reference_manager_test.go
  internal/datacoord/server_test.go
  internal/datacoord/services.go
  internal/distributed/rootcoord/service_test.go
  internal/indexcoord/index_coord.go
  internal/indexcoord/index_coord_test.go
  internal/proto/data_coord.proto
  internal/proto/datapb/data_coord.pb.go
  internal/querycoord/global_meta_broker.go
  internal/querycoord/task.go
  internal/rootcoord/import_manager.go
  internal/rootcoord/import_manager_test.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
Labels: size/XXL, approved, lgtm, ci-passed, dco-passed

#17486 Refine compaction trigger policy
  internal/datacoord/compaction.go
  internal/datacoord/compaction_policy.go
  internal/datacoord/compaction_policy_test.go
  internal/datacoord/compaction_test.go
  internal/datacoord/compaction_trigger.go
  internal/datacoord/compaction_trigger_test.go
  internal/datacoord/mock_test.go
  internal/datacoord/segment_info.go
  internal/datacoord/server_test.go
  internal/datacoord/services.go
  internal/datacoord/util.go
  internal/datacoord/util_test.go
  internal/util/paramtable/component_param.go
  tests/python_client/common/common_type.py
  tests/python_client/testcases/test_compaction.py
Labels: sig/testing, size/XXL, approved, lgtm, area/test, ci-passed, dco-passed

#17575 [skip e2e] Upgrade codecov-action && add retry upload
  .github/workflows/main.yaml
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#17441 Move SegmentInfo out of VchannelInfo, leave Id only to decrease kv si…
  internal/datacoord/handler.go
  internal/datacoord/server_test.go
  internal/datanode/data_node_test.go
  internal/datanode/data_sync_service.go
  internal/datanode/data_sync_service_test.go
  internal/datanode/flow_graph_dd_node.go
  internal/datanode/flow_graph_dd_node_test.go
  internal/datanode/flow_graph_manager.go
  internal/datanode/mock_test.go
  internal/proto/data_coord.proto
  internal/proto/datapb/data_coord.pb.go
  internal/proto/query_coord.proto
  internal/proto/querypb/query_coord.pb.go
  internal/querycoord/channel_allocator_test.go
  internal/querycoord/cluster_test.go
  internal/querycoord/index_checker_test.go
  internal/querycoord/meta.go
  internal/querycoord/meta_test.go
  internal/querycoord/mock_3rd_component_test.go
  internal/querycoord/query_coord.go
  internal/querycoord/segment_allocator_test.go
  internal/querycoord/task.go
  internal/querycoord/task_test.go
  internal/querynode/task.go
  internal/querynode/task_test.go
Labels: size/XXL, approved, lgtm, ci-passed, area/internal-api, dco-passed

#17570 Return error when bulkload pending list hit limit
  internal/rootcoord/import_manager.go
  internal/rootcoord/import_manager_test.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#17586 [skip e2e] Move feature label to exemptLabels
  .github/stale.yml
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#17591 Add Image size after build docker image
  build/build_image.sh
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#17590 Fix wrong IP distances
  internal/proxy/task_search.go
  tests/python_client/testcases/test_search.py
Labels: kind/bug, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#17593 Filter out duplicated sealed segments which are online and offline
  internal/querynode/query_node.go
  internal/querynode/query_node_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#17595 Print error when failed to broadcast message
  internal/rootcoord/dml_channels.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#17598 Set the task state to TaskFailed if error occurs
  internal/querycoord/task.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed

#17549 GetIndexState only get the index state generated when CreateIndex is called
  internal/datacoord/mock_test.go
  internal/distributed/proxy/service_test.go
  internal/distributed/rootcoord/client/client.go
  internal/distributed/rootcoord/service.go
  internal/proto/etcd_meta.proto
  internal/proto/etcdpb/etcd_meta.pb.go
  internal/proto/root_coord.proto
  internal/proto/rootcoordpb/root_coord.pb.go
  internal/proxy/rootcoord_mock_test.go
  internal/proxy/task.go
  internal/proxy/task_index_test.go
  internal/rootcoord/meta_table.go
  internal/rootcoord/meta_table_test.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
  internal/rootcoord/task.go
  internal/types/types.go
  internal/util/mock/grpc_rootcoord_client.go
Labels: size/XL, approved, lgtm, ci-passed, dco-passed

#17601 verify data_queryable state after bulk load
  tests/python_client/base/utility_wrapper.py
  tests/python_client/bulk_load/test_bulk_load.py
Labels: sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#17596 [skip e2e] Update compaction related test cases for code change
  tests/python_client/testcases/test_compaction.py
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#17608 Fix LoadBalance may not update the shard leader
  internal/querycoord/task.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#17605 Simplify the implementations of ToPhysicalChannel and ConvertChannelName
  internal/util/funcutil/func.go
  internal/util/funcutil/func_test.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed

#17616 Return err if failed to assign segments/channels to nodes
  internal/querycoord/task.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#17613 Forbid system fields in user schema
  internal/rootcoord/task.go
  internal/rootcoord/task_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#17552 Make querycoord channel allocator respect context
  internal/querycoord/channel_allocator.go
  internal/querycoord/channel_allocator_test.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#17609 Use segment version instead of ref cnt
  internal/proto/query_coord.proto
  internal/proto/querypb/query_coord.pb.go
  internal/querycoord/util.go
  internal/querynode/impl.go
  internal/querynode/impl_test.go
  internal/querynode/shard_cluster.go
  internal/querynode/shard_cluster_test.go
  internal/querynode/shard_cluster_version.go
  internal/querynode/shard_cluster_version_test.go
  internal/querynode/shard_node_detector.go
  internal/querynode/shard_node_detector_test.go
Labels: kind/bug, size/XXL, approved, lgtm, ci-passed, area/internal-api, dco-passed

#17565 Add PurgeMemory interface to malloc_trim according to memory stats
  configs/milvus.yaml
  internal/core/src/common/CMakeLists.txt
  internal/core/src/common/memory_c.cpp
  internal/core/src/common/memory_c.h
  internal/core/src/indexbuilder/index_c.cpp
  internal/core/src/segcore/collection_c.cpp
  internal/core/src/segcore/reduce_c.cpp
  internal/core/thirdparty/CMakeLists.txt
  internal/core/thirdparty/rapidxml/CMakeLists.txt
  internal/core/unittest/test_c_api.cpp
  internal/querynode/reduce.go
  internal/util/memutil/purge_memory.go
  internal/util/memutil/purge_memory_test.go
  internal/util/paramtable/component_param.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed, area/compilation

#17490 Mark deleted before drop index
  internal/distributed/indexcoord/client/client.go
  internal/distributed/indexcoord/client/client_test.go
  internal/distributed/indexcoord/service.go
  internal/distributed/indexcoord/service_test.go
  internal/distributed/proxy/service_test.go
  internal/distributed/rootcoord/service_test.go
  internal/indexcoord/index_coord.go
  internal/indexcoord/index_coord_mock.go
  internal/indexcoord/index_coord_mock_test.go
  internal/indexcoord/index_coord_test.go
  internal/indexcoord/meta_table.go
  internal/indexcoord/meta_table_test.go
  internal/proto/etcd_meta.proto
  internal/proto/etcdpb/etcd_meta.pb.go
  internal/proto/index_coord.proto
  internal/proto/indexpb/index_coord.pb.go
  internal/proxy/index_coord_mock_test.go
  internal/rootcoord/meta_table.go
  internal/rootcoord/meta_table_test.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
  internal/rootcoord/task.go
  internal/rootcoord/task_test.go
  internal/types/types.go
Labels: size/XXL, approved, lgtm, ci-passed, area/internal-api, dco-passed

#17617 Support return dropped segments info in GetSegmentInfo rpc
  internal/datacoord/meta.go
  internal/datacoord/meta_test.go
  internal/datacoord/server_test.go
  internal/datacoord/services.go
  internal/datanode/data_sync_service.go
  internal/proto/data_coord.proto
  internal/proto/datapb/data_coord.pb.go
  internal/querycoord/meta.go
Labels: size/XL, approved, lgtm, ci-passed, dco-passed

#17623 Remove wait before release collection/partition
  internal/querynode/task.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#17622 [skip e2e] Upgrade chart to add kafka metrics for nightly
  build/ci/jenkins/Nightly.groovy
  tests/scripts/values/nightly.yaml
Labels: kind/improvement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#17620 Fix a bug of bulkload
  internal/util/importutil/import_wrapper.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#17624 Fix bulkload failed bug caused by dropping collection
  internal/rootcoord/root_coord.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#17619 Acquire reference lock of compacted from segments during index building
  internal/datacoord/meta.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#17631 Refine meta, remove redundant proxy data
  internal/rootcoord/meta_table.go
  internal/rootcoord/meta_table_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#17229 Fix mock querynode server session not revoked
  internal/querycoord/mock_querynode_server_test.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#17634 Fix Delta log loss after compaction
  internal/datacoord/meta.go
Labels: kind/bug, approved, lgtm, ci-passed, dco-passed

#17628 [test] Add some compaction test cases
  tests/python_client/testcases/test_compaction.py
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#17626 RocksMQ Memory tunable
  configs/milvus.yaml
  internal/mq/mqimpl/rocksmq/client/test_helper.go
  internal/mq/mqimpl/rocksmq/server/global_rmq.go
  internal/mq/mqimpl/rocksmq/server/rocksmq_impl.go
  internal/mq/mqimpl/rocksmq/server/rocksmq_impl_test.go
  internal/mq/mqimpl/rocksmq/server/rocksmq_retention_test.go
Labels: area/dependency, size/L, approved, lgtm, ci-passed, dco-passed

#17630 [skip e2e]Update jenkins file for chaos and deploy test
  build/ci/jenkins/ChaosTest.groovy
  build/ci/jenkins/ChaosTestKafkaMQ.groovy
  build/ci/jenkins/DeployTest.groovy
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#17641 Fix segments info in drop virtual channel request is not set
  internal/datanode/flush_manager.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#17643 [skip e2e]Fix log mistake: WatchDmChannels -> WatchDeltaChannels
  internal/querycoord/querynode.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#17640 Add log for mqtt msgstream seek
  internal/mq/msgstream/mq_msgstream.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#17635 Fix bug for dropping index
  internal/proxy/proxy_test.go
  internal/rootcoord/meta_table.go
  internal/rootcoord/meta_table_test.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#17642 Use pulsar client go v0.6.8
  go.mod
  go.sum
Labels: area/dependency, size/XS, approved, lgtm, ci-passed, dco-passed

#17650 [skip e2e]Fix etcd version in first deployment for upgrading test
  .github/workflows/deploy-test.yaml
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#17652 Fix bug for align segments
  internal/rootcoord/meta_table.go
  internal/rootcoord/root_coord.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed

#17649 Segments can't be compacted when they have reference lock
  internal/datacoord/compaction.go
  internal/datacoord/compaction_test.go
  internal/datacoord/compaction_trigger.go
  internal/datacoord/compaction_trigger_test.go
  internal/datacoord/meta.go
  internal/datacoord/meta_test.go
  internal/datacoord/server.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#17136 Add the consistency check tool
  cmd/milvus/help.go
  cmd/milvus/mck.go
  cmd/milvus/milvus.go
  cmd/milvus/run.go
  cmd/milvus/stop.go
  cmd/milvus/util.go
  internal/util/typeutil/type.go
Labels: kind/improvement, size/XXL, approved, lgtm, ci-passed, dco-passed

#17661 Fix datasorter swap vector logic
  internal/storage/data_sorter.go
  internal/storage/data_sorter_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#17654 Add msg id to log in search path.
  internal/proxy/task_search.go
  internal/querynode/plan.go
  internal/querynode/segment.go
  internal/querynode/task_search.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#17658 [test] Update some compaction test cases
  tests/python_client/testcases/test_compaction.py
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#17667 Update pymilvus version
  tests/python_client/requirements.txt
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#17663 Add the offlines nodes previously crashed to offline nodes channel
  internal/querycoord/query_coord.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#17669 Make LoadCollection compatible
  internal/proxy/task.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#17668 fix typo
  internal/datacoord/channel_checker.go
  internal/datacoord/channel_checker_test.go
  internal/datacoord/channel_manager.go
  internal/datacoord/channel_manager_test.go
  internal/datacoord/server.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#17683 [skip e2e]Update deploy test
  build/ci/jenkins/DeployTest.groovy
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#17671 Clear segment cache when closing flowgraph
  internal/datanode/data_sync_service.go
  internal/datanode/data_sync_service_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed
