Repository milvus-io/milvus, pull requests merged in 2022-03, with the labels that each got.

#15787 Support to build docker image for centos7
  build/build_image.sh
  build/docker/milvus/centos7/Dockerfile
  build/docker/milvus/ubuntu18.04/Dockerfile
Labels: kind/enhancement, kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#15743 Make C++ log level configurable and add log configuration for embedded Milvus.
  internal/core/src/segcore/CMakeLists.txt
  internal/core/src/segcore/segcore_init_c.cpp
  scripts/core_build.sh
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed, area/compilation

#15770 Optimize CMakeLists.txt under internal/core
  internal/core/CMakeLists.txt
  internal/core/build.sh
  internal/core/src/common/CMakeLists.txt
  internal/core/src/indexbuilder/CMakeLists.txt
  internal/core/src/segcore/CMakeLists.txt
  internal/storage/cwrapper/CMakeLists.txt
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed, area/compilation

#15790 Fix shallow copy of typeutil.AppendFieldData
  internal/util/typeutil/schema.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#15795 [skip e2e]Add build centos milvus docker image into jenkins job
  build/ci/jenkins/PublishImages.groovy
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#15798 Update 8 to 9
  README.md
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#15804 [skip ci] Update knowhere/CMakeLists.txt
  internal/core/thirdparty/knowhere/CMakeLists.txt
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed, area/compilation

#15801 Refactor rocksmq comments and logs for readability
  internal/util/rocksmq/server/rocksmq/rocksmq_impl.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#15803 [skip e2e] Refine the script to get milvus manifests for kubernetes
  deployments/offline/README.md
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#15809 Fixbug: building index return nil by mistake when error not occur
  internal/indexnode/task.go
  tests/python_client/testcases/test_compaction.py
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#15813 Refine tso log print
  internal/log/global.go
  internal/tso/tso.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#15649 Add Prometheus metrics for QueryNode
  internal/metrics/metrics.go
  internal/metrics/querycoord.go
  internal/metrics/querynode.go
  internal/msgstream/msg.go
  internal/querynode/collection.go
  internal/querynode/collection_replica.go
  internal/querynode/data_sync_service.go
  internal/querynode/flow_graph_query_node.go
  internal/querynode/historical.go
  internal/querynode/mock_test.go
  internal/querynode/query_collection.go
  internal/querynode/segment.go
  internal/querynode/segment_loader.go
  internal/querynode/streaming.go
  internal/querynode/task.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#15582 Add some prometheus metrics for proxy
  internal/metrics/indexcoord_metrics.go
  internal/metrics/metrics.go
  internal/metrics/proxy_metrics.go
  internal/metrics/proxy_metrics_test.go
  internal/proxy/channels_mgr.go
  internal/proxy/channels_time_ticker.go
  internal/proxy/impl.go
  internal/proxy/meta_cache.go
  internal/proxy/proxy.go
  internal/proxy/task.go
  internal/proxy/task_test.go
Labels: size/XXL, approved, lgtm, ci-passed, dco-passed

#15774 Add ByteSlice Methods for memkv
  internal/kv/mem/mem_kv.go
  internal/kv/mem/mem_kv_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#15814 Let MemoryKV.Load return error when key not exist
  internal/kv/mem/mem_kv.go
  internal/kv/mem/mem_kv_test.go
  internal/querynode/mock_test.go
  internal/storage/utils_test.go
  internal/util/paramtable/base_table.go
  internal/util/paramtable/base_table_test.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#15640 Add prometheus metrics for indexnode
  internal/indexnode/indexnode.go
  internal/indexnode/task.go
  internal/metrics/indexcoord_metrics.go
  internal/metrics/indexnode_metrics.go
  internal/metrics/metrics.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#15684 Add prometheus metrics for RootCoord
  internal/metrics/metrics.go
  internal/metrics/rootcoord_metrics.go
  internal/rootcoord/dml_channels.go
  internal/rootcoord/proxy_manager.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/task.go
  internal/rootcoord/timeticksync.go
  internal/tso/global_allocator.go
Labels: size/XL, approved, lgtm, ci-passed, dco-passed

#15796 add array hashKeys empty check
  internal/proxy/task.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#15839 Fix metrics label conflict
  internal/datanode/flow_graph_delete_node.go
  internal/datanode/flow_graph_insert_buffer_node.go
  internal/datanode/flush_manager.go
  internal/metrics/datanode.go
  internal/metrics/indexcoord_metrics.go
  internal/metrics/indexnode_metrics.go
  internal/metrics/metrics.go
  internal/metrics/proxy_metrics.go
  internal/metrics/proxy_metrics_test.go
  internal/metrics/querycoord.go
  internal/metrics/querynode.go
  internal/metrics/rootcoord_metrics.go
  internal/querycoord/impl.go
  internal/querycoord/task.go
  internal/querynode/historical.go
  internal/querynode/query_collection.go
  internal/querynode/segment.go
  internal/querynode/streaming.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#15845 [skip e2e]Update mergify to add mac code check
  .github/mergify.yml
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#15838 Ban DataType_String in CreateCollection
  internal/proxy/proxy_test.go
  internal/proxy/task.go
  internal/proxy/validate_util.go
  internal/proxy/validate_util_test.go
  tests/python_client/testcases/test_collection.py
Labels: kind/enhancement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#15826 Specify appropriate timestamp in initPKBloomFilter
  internal/datanode/data_sync_service.go
  internal/datanode/segment_replica.go
  internal/datanode/segment_replica_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#15847 Extend ChannelWatchState in protobuf
  internal/proto/data_coord.proto
  internal/proto/datapb/data_coord.pb.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#15851 [test]Add e2e case for Collection with string field
  tests/python_client/testcases/test_collection.py
Labels: kind/improvement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#15855 Let search fail as if one query_node return error result
  internal/proxy/task.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#15842 Update pymilvus version
  tests/python_client/requirements.txt
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#15843 Merge msgChannelConfig and knowhereConfig into commonConfig
  configs/milvus.yaml
  internal/datacoord/channel_manager.go
  internal/datacoord/server.go
  internal/datacoord/server_test.go
  internal/datacoord/services.go
  internal/datanode/data_node.go
  internal/datanode/data_node_test.go
  internal/datanode/flow_graph_dd_node.go
  internal/datanode/flow_graph_dmstream_input_node.go
  internal/datanode/flow_graph_insert_buffer_node.go
  internal/distributed/rootcoord/service_test.go
  internal/indexnode/indexnode.go
  internal/indexnode/indexnode_mock.go
  internal/indexnode/metrics_info.go
  internal/proxy/task_scheduler.go
  internal/querycoord/channel_unsubscribe.go
  internal/querycoord/impl.go
  internal/querycoord/meta.go
  internal/querycoord/metrics_info.go
  internal/querycoord/query_coord.go
  internal/querycoord/query_coord_test.go
  internal/querycoord/task.go
  internal/querynode/impl.go
  internal/querynode/metrics_info.go
  internal/querynode/query_node.go
  internal/querynode/query_node_test.go
  internal/querynode/stats_service.go
  internal/querynode/stats_service_test.go
  internal/querynode/task.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
  internal/rootcoord/task.go
  internal/rootcoord/timestamp_test.go
  internal/rootcoord/timeticksync.go
  internal/rootcoord/timeticksync_test.go
  internal/util/paramtable/base_table.go
  internal/util/paramtable/base_table_test.go
  internal/util/paramtable/component_param.go
  internal/util/paramtable/component_param_test.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#15865 Decrease scrape interval
  tests/scripts/values/nightly.yaml
  tests/scripts/values/pr.yaml
  tests/scripts/values/qa/pr.yaml
Labels: kind/improvement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#15863 [skip e2e]Update mergify rule for 2.*.* branch
  .github/mergify.yml
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#15802 Support column-based insert data in message stream
  internal/datanode/flow_graph_insert_buffer_node.go
  internal/mq/msgstream/msg.go
  internal/mq/msgstream/msg_test.go
  internal/mq/msgstream/repack_func.go
  internal/proto/internal.proto
  internal/proto/internalpb/internal.pb.go
  internal/proxy/task.go
  internal/proxy/task_test.go
  internal/querynode/flow_graph_filter_dm_node.go
  internal/querynode/flow_graph_insert_node.go
  internal/storage/utils.go
  internal/storage/utils_test.go
  internal/util/typeutil/data_format.go
  internal/util/typeutil/data_format_test.go
  internal/util/typeutil/schema.go
  internal/util/typeutil/schema_test.go
Labels: size/XXL, approved, lgtm, ci-passed, area/internal-api, dco-passed

#15844 Add ByteSlice Method for embed etcd
  internal/kv/etcd/embed_etcd_kv.go
  internal/kv/etcd/embed_etcd_kv_test.go
Labels: kind/enhancement, size/XL, approved, lgtm, ci-passed, dco-passed

#15856 [test] Update case of search after index and compact
  tests/python_client/base/collection_wrapper.py
  tests/python_client/testcases/test_compaction.py
Labels: sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#15868 Fix misuse of timerecord
  internal/indexnode/task.go
  internal/proxy/channels_time_ticker.go
  internal/proxy/impl.go
  internal/proxy/task.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed

#15853 Specify appropriate timestamp in initPKBloomFilter (#15823)
  internal/datanode/data_sync_service.go
  internal/datanode/segment_replica.go
  internal/datanode/segment_replica_test.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#15875 [skip e2e] Update committer/maintainer list
  COMMITTERS
  MAINTAINERS
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#15881 Modify test case for interface change
  tests/python_client/testcases/test_insert.py
  tests/python_client/testcases/test_utility.py
Labels: sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#15862 [skip e2e] Enable L2 test case after code fix
  tests/python_client/testcases/test_search_20.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#15832 [test] Add testcase for search
  tests/python_client/testcases/test_search_20.py
Labels: sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#15870 [test] Update case of search after index and compact
  tests/python_client/base/collection_wrapper.py
  tests/python_client/testcases/test_compaction.py
Labels: sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#15894 [skip e2e]Use absolute path for hashFiles
  .github/workflows/main.yaml
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#15901 [skip e2e]Add network latency chaos test
  .github/workflows/network-latency-chaos-test.yaml
  tests/python_client/chaos/chaos_objects/network_latency/chaos_datacoord_network_latency.yaml
  tests/python_client/chaos/chaos_objects/network_latency/chaos_datanode_network_latency.yaml
  tests/python_client/chaos/chaos_objects/network_latency/chaos_etcd_network_latency.yaml
  tests/python_client/chaos/chaos_objects/network_latency/chaos_indexcoord_network_latency.yaml
  tests/python_client/chaos/chaos_objects/network_latency/chaos_indexnode_network_latency.yaml
  tests/python_client/chaos/chaos_objects/network_latency/chaos_minio_network_latency.yaml
  tests/python_client/chaos/chaos_objects/network_latency/chaos_proxy_network_latency.yaml
  tests/python_client/chaos/chaos_objects/network_latency/chaos_pulsar_network_latency.yaml
  tests/python_client/chaos/chaos_objects/network_latency/chaos_querycoord_network_latency.yaml
  tests/python_client/chaos/chaos_objects/network_latency/chaos_querynode_network_latency.yaml
  tests/python_client/chaos/chaos_objects/network_latency/chaos_rootcoord_network_latency.yaml
  tests/python_client/chaos/chaos_objects/network_latency/testcases.yaml
Labels: kind/improvement, sig/testing, size/XL, approved, lgtm, area/test, ci-passed, dco-passed

#15900 [skip e2e]Add response time metric for chaos test
  tests/python_client/chaos/checker.py
  tests/python_client/chaos/test_chaos.py
Labels: kind/improvement, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#15905 [skip e2e]Update io latency chaos test
  .github/workflows/io-latency-chaos-test.yaml
  tests/python_client/chaos/chaos_objects/io_latency/chaos_etcd_io_latency.yaml
  tests/python_client/chaos/chaos_objects/io_latency/chaos_minio_io_latency.yaml
  tests/python_client/chaos/chaos_objects/io_latency/chaos_pulsar_io_latency.yaml
Labels: kind/improvement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#15898 [skip e2e]Add wait pod ready function for chaos data consist test
  tests/python_client/chaos/test_chaos_data_consist.py
Labels: kind/improvement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#15893 Add CompareFailErr for CAS operation error check
  internal/kv/etcd/embed_etcd_kv.go
  internal/kv/etcd/embed_etcd_kv_test.go
  internal/kv/etcd/etcd_kv.go
  internal/kv/etcd/etcd_kv_test.go
  internal/kv/kv.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#15895 Refactor assigning loading segments task in QueryCoord
  internal/querycoord/task.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#15911 [skip e2e]Add pod previous log export
  tests/scripts/export_log_k8s.sh
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#15907 [skip e2e]Add memory stress chaos test
  .github/workflows/mem-stress-chaos-test.yaml
  tests/python_client/chaos/chaos_objects/mem_stress/chaos_datanode_mem_stress.yaml
  tests/python_client/chaos/chaos_objects/mem_stress/chaos_etcd_mem_stress.yaml
  tests/python_client/chaos/chaos_objects/mem_stress/chaos_indexnode_mem_stress.yaml
  tests/python_client/chaos/chaos_objects/mem_stress/chaos_minio_mem_stress.yaml
  tests/python_client/chaos/chaos_objects/mem_stress/chaos_proxy_mem_stress.yaml
  tests/python_client/chaos/chaos_objects/mem_stress/chaos_pulsar_mem_stress.yaml
  tests/python_client/chaos/chaos_objects/mem_stress/chaos_querynode_mem_stress.yaml
  tests/python_client/chaos/chaos_objects/mem_stress/chaos_standalone_mem_stress.yaml
  tests/python_client/chaos/chaos_objects/mem_stress/testcases.yaml
Labels: kind/improvement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#15914 Add health check to docker-compose etcd and service dependencies
  docker-compose.yml
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#15854 Add search benchmark in QueryNode
  internal/querynode/benchmark_test.go
  internal/querynode/mock_test.go
Labels: kind/improvement, size/XL, approved, lgtm, ci-passed, dco-passed

#15920 [skip e2e]Delete some verbose info
  tests/python_client/chaos/test_chaos.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#15923 Use Microseconds in performance tests
  internal/proxy/impl.go
  internal/proxy/task.go
  internal/querynode/query_collection.go
Labels: size/M, approved, lgtm, ci-passed

#15927 Fix passing empty binlog content in compaction (#15909)
  internal/datanode/compactor.go
  internal/datanode/compactor_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#15935 [skip e2e]Use absolute path for hashFiles (#15894)
  .github/workflows/main.yaml
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#15779 Add zstd compressor in util
  internal/util/compressor/compressor.go
  internal/util/compressor/compressor_test.go
  internal/util/mock/io_fake.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#15945 [skip e2e]Update mergify rule to add ci-passed label for 2.*.* branch
  .github/mergify.yml
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#15934 Change log level to debug in perf branch
  configs/milvus.yaml
Labels: size/XS, approved, lgtm, ci-passed

#15858 fix checkSegmentSize overflows int64
  internal/querynode/segment_loader.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#15951 [skip e2e]Update jenkins file
  build/ci/jenkins/ChaosTest.groovy
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#15317 Return error when create message stream in QueryNode
  internal/querynode/data_sync_service.go
  internal/querynode/data_sync_service_test.go
  internal/querynode/flow_graph_delete_node.go
  internal/querynode/flow_graph_filter_delete_node.go
  internal/querynode/flow_graph_filter_dm_node.go
  internal/querynode/flow_graph_insert_node.go
  internal/querynode/flow_graph_query_node.go
  internal/querynode/flow_graph_query_node_test.go
  internal/querynode/flow_graph_service_time_node.go
  internal/querynode/flow_graph_service_time_node_test.go
  internal/querynode/mock_test.go
  internal/querynode/task.go
  internal/querynode/task_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#15925 Extend watch/release channel logic in DataNode
  internal/datacoord/channel_manager.go
  internal/datacoord/policy.go
  internal/datanode/data_node.go
  internal/datanode/data_node_test.go
  internal/datanode/event_manager.go
  internal/datanode/event_manager_test.go
Labels: kind/enhancement, size/XL, approved, lgtm, ci-passed, dco-passed

#15922 Handle error in topic creation of rocksmq
  internal/mq/mqimpl/rocksmq/server/rocksmq_impl.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#15950 Enhance error message when coordinator not healthy
  internal/distributed/datacoord/client/client.go
  internal/distributed/indexcoord/client/client.go
  internal/distributed/querycoord/client/client.go
  internal/distributed/rootcoord/client/client.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#15930 Add rpc interfaces for import
  internal/core/src/pb/common.pb.cc
  internal/core/src/pb/common.pb.h
  internal/core/src/pb/milvus.pb.cc
  internal/core/src/pb/milvus.pb.h
  internal/datacoord/mock_test.go
  internal/datacoord/services.go
  internal/datanode/data_node.go
  internal/distributed/datacoord/client/client.go
  internal/distributed/datacoord/service.go
  internal/distributed/datacoord/service_test.go
  internal/distributed/datanode/client/client.go
  internal/distributed/datanode/service.go
  internal/distributed/datanode/service_test.go
  internal/distributed/proxy/service.go
  internal/distributed/proxy/service_test.go
  internal/proto/common.proto
  internal/proto/commonpb/common.pb.go
  internal/proto/data_coord.proto
  internal/proto/datapb/data_coord.pb.go
  internal/proto/milvus.proto
  internal/proto/milvuspb/milvus.pb.go
  internal/proxy/data_coord_mock_test.go
  internal/proxy/impl.go
  internal/types/types.go
  internal/util/mock/datacoord_client.go
  internal/util/mock/datanode_client.go
  scripts/run_go_codecov.sh
Labels: area/api, size/XXL, approved, lgtm, ci-passed, dco-passed

#15956 Enhance error message when coordinator not healthy (#15950)
  internal/distributed/datacoord/client/client.go
  internal/distributed/indexcoord/client/client.go
  internal/distributed/querycoord/client/client.go
  internal/distributed/rootcoord/client/client.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#15963 [skip e2e]Check chaos status
  tests/python_client/chaos/test_chaos.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#15967 Remove milvus mertrics collect for ci
  build/ci/jenkins/Nightly.groovy
  build/ci/jenkins/PR.groovy
  build/ci/jenkins/qa/PR.groovy
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#15984 [skip e2e]Fix install and test script for chaos
  tests/python_client/chaos/scripts/install_milvus_cluster.sh
  tests/python_client/chaos/scripts/install_milvus_standalone.sh
  tests/python_client/chaos/test_chaos.py
Labels: kind/improvement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#15981 [skip e2e] Fix scale test pod is not ready when reading logs
  tests/python_client/scale/test_data_node_scale.py
  tests/python_client/scale/test_index_node_scale.py
  tests/python_client/scale/test_proxy_scale.py
  tests/python_client/scale/test_query_node_scale.py
Labels: kind/improvement, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#15960 Add unit tests in segcore
  internal/core/unittest/test_segcore.cpp
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#15994 [skip e2e] Get restart count for containers for debug info
  .github/workflows/main.yaml
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#15928 Make load operation parallel improve performance
  internal/querynode/segment_loader.go
  internal/querynode/segment_loader_test.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#16002 Support aliyun oss storage
  core/cmake/DefineOptions.cmake
  core/cmake/ThirdPartyPackages.cmake
  core/conf/demo/server_config.yaml
  core/src/CMakeLists.txt
  core/src/config/Config.cpp
  core/src/config/Config.h
  core/src/db/Utils.cpp
  core/src/storage/FSHandler.h
  core/src/storage/oss/OSSClientWrapper.cpp
  core/src/storage/oss/OSSClientWrapper.h
  core/src/storage/oss/OSSIOReader.cpp
  core/src/storage/oss/OSSIOReader.h
  core/src/storage/oss/OSSIOWriter.cpp
  core/src/storage/oss/OSSIOWriter.h
  core/src/storage/oss/OSSOperation.cpp
  core/src/storage/oss/OSSOperation.h
  core/src/storage/s3/S3ClientWrapper.cpp
  core/thirdparty/versions.txt
  shards/all_in_one/ro_server.yml
  shards/all_in_one/wr_server.yml
  shards/all_in_one_with_mysql/ro_server.yml
  shards/all_in_one_with_mysql/wr_server.yml
Labels: size/XXL, approved, lgtm, ci-passed

#16010 Chunk manager support scalar data
  internal/storage/utils.go
  internal/storage/utils_test.go
  internal/storage/vector_chunk_manager.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#15980 Add methods to compress/decompress small blocks
  internal/util/compressor/compressor.go
  internal/util/compressor/compressor_test.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#16006 Modify import rpc interfaces
  internal/core/src/pb/common.pb.cc
  internal/core/src/pb/common.pb.h
  internal/core/src/pb/milvus.pb.cc
  internal/core/src/pb/milvus.pb.h
  internal/datacoord/mock_test.go
  internal/datacoord/services.go
  internal/datanode/data_node.go
  internal/distributed/datacoord/client/client.go
  internal/distributed/datacoord/service.go
  internal/distributed/datacoord/service_test.go
  internal/distributed/datanode/client/client.go
  internal/distributed/datanode/service.go
  internal/distributed/datanode/service_test.go
  internal/distributed/proxy/service_test.go
  internal/distributed/rootcoord/client/client.go
  internal/distributed/rootcoord/client/client_test.go
  internal/distributed/rootcoord/service.go
  internal/proto/common.proto
  internal/proto/commonpb/common.pb.go
  internal/proto/data_coord.proto
  internal/proto/datapb/data_coord.pb.go
  internal/proto/milvus.proto
  internal/proto/milvuspb/milvus.pb.go
  internal/proto/root_coord.proto
  internal/proto/rootcoordpb/root_coord.pb.go
  internal/proxy/data_coord_mock_test.go
  internal/rootcoord/root_coord.go
  internal/types/types.go
  internal/util/mock/datacoord_client.go
  internal/util/mock/datanode_client.go
  internal/util/mock/rootcoord_client.go
Labels: area/api, size/XXL, approved, lgtm, ci-passed, dco-passed

#16000 Fix README offline installation
  deployments/offline/README.md
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#15886 Remove Consume() API from mqstream interface
  internal/datacoord/server.go
  internal/datacoord/server_test.go
  internal/datanode/flow_graph_dmstream_input_node_test.go
  internal/mq/msgstream/mq_msgstream.go
  internal/mq/msgstream/mq_msgstream_test.go
  internal/mq/msgstream/msgstream.go
  internal/proxy/mock_test.go
  internal/proxy/task_test.go
  internal/querynode/mock_test.go
  internal/querynode/query_collection.go
  internal/rootcoord/dml_channels_test.go
  internal/util/flowgraph/input_node.go
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#16009 [skip e2e]Add input for github action
  .github/workflows/pod-kill-chaos-test.yaml
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#16027 Explictly specify Load operation meta
  internal/proto/query_coord.proto
  internal/proto/querypb/query_coord.pb.go
  internal/querycoord/impl.go
  internal/querycoord/index_checker_test.go
  internal/querycoord/meta.go
  internal/querycoord/meta_test.go
  internal/querycoord/query_coord_test.go
  internal/querycoord/task.go
  internal/querycoord/task_test.go
  internal/querynode/task.go
Labels: kind/bug, size/XL, approved, lgtm, ci-passed, area/internal-api, dco-passed

#16039 Use RmqFactory in DataNode unit test
  internal/datanode/data_node_test.go
  internal/datanode/mock_test.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#16038 Fix load failure and remove parition release related code
  internal/querynode/collection.go
  internal/querynode/collection_test.go
  internal/querynode/flow_graph_filter_dm_node.go
  internal/querynode/flow_graph_filter_dm_node_test.go
  internal/querynode/historical.go
  internal/querynode/historical_test.go
  internal/querynode/segment.go
  internal/querynode/streaming.go
  internal/querynode/task.go
  internal/querynode/task_test.go
  internal/querynode/type_def.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#15904 Support create collection with VarChar field
  internal/core/src/pb/schema.pb.cc
  internal/core/src/pb/schema.pb.h
  internal/datacoord/mock_test.go
  internal/proto/schema.proto
  internal/proto/schemapb/schema.pb.go
  internal/proxy/validate_util.go
  internal/proxy/validate_util_test.go
  internal/util/typeutil/schema.go
  internal/util/typeutil/schema_test.go
Labels: kind/feature, size/L, approved, lgtm, ci-passed, dco-passed

#16035 Explictly specify Load operation meta (#16027)
  internal/proto/query_coord.proto
  internal/proto/querypb/query_coord.pb.go
  internal/querycoord/impl.go
  internal/querycoord/index_checker_test.go
  internal/querycoord/meta.go
  internal/querycoord/meta_test.go
  internal/querycoord/query_coord_test.go
  internal/querycoord/task.go
  internal/querycoord/task_test.go
  internal/querynode/task.go
Labels: kind/bug, size/XL, approved, lgtm, ci-passed, area/internal-api, dco-passed

#16036 Add project knowhere in CONTRIBUTING.md
  CONTRIBUTING.md
  a
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#16032 Alter comments in parallel.go for readability
  internal/util/funcutil/parallel.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#16031 [test] Increase handoff timeout limit in compact case
  tests/python_client/testcases/test_compaction.py
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#16044 [skip e2e] Add search test case
  tests/python_client/testcases/test_search_20.py
Labels: kind/improvement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#15971 Remove reader API from Mqstream and replace it with consumer API
  go.mod
  go.sum
  internal/datanode/flow_graph_dmstream_input_node_test.go
  internal/mq/mqimpl/rocksmq/client/consumer.go
  internal/mq/mqimpl/rocksmq/client/consumer_impl.go
  internal/mq/mqimpl/rocksmq/server/rocksmq.go
  internal/mq/mqimpl/rocksmq/server/rocksmq_impl.go
  internal/mq/mqimpl/rocksmq/server/rocksmq_impl_test.go
  internal/mq/msgstream/mq_msgstream.go
  internal/mq/msgstream/mq_msgstream_test.go
  internal/mq/msgstream/mqwrapper/client.go
  internal/mq/msgstream/mqwrapper/consumer.go
  internal/mq/msgstream/mqwrapper/id.go
  internal/mq/msgstream/mqwrapper/pulsar/pulsar_client.go
  internal/mq/msgstream/mqwrapper/pulsar/pulsar_client_test.go
  internal/mq/msgstream/mqwrapper/pulsar/pulsar_consumer.go
  internal/mq/msgstream/mqwrapper/pulsar/pulsar_consumer_test.go
  internal/mq/msgstream/mqwrapper/pulsar/pulsar_id.go
  internal/mq/msgstream/mqwrapper/pulsar/pulsar_id_test.go
  internal/mq/msgstream/mqwrapper/pulsar/pulsar_reader.go
  internal/mq/msgstream/mqwrapper/pulsar/pulsar_reader_test.go
  internal/mq/msgstream/mqwrapper/reader.go
  internal/mq/msgstream/mqwrapper/rmq/rmq_client.go
  internal/mq/msgstream/mqwrapper/rmq/rmq_client_test.go
  internal/mq/msgstream/mqwrapper/rmq/rmq_consumer.go
  internal/mq/msgstream/mqwrapper/rmq/rmq_id.go
  internal/mq/msgstream/mqwrapper/rmq/rmq_id_test.go
  internal/mq/msgstream/mqwrapper/rmq/rmq_reader.go
  internal/mq/msgstream/msgstream.go
  internal/proxy/mock_test.go
  internal/querynode/mock_test.go
  internal/querynode/segment_loader.go
  internal/querynode/segment_loader_test.go
  internal/querynode/task_test.go
  internal/rootcoord/dml_channels_test.go
Labels: area/dependency, size/XXL, approved, lgtm, ci-passed, dco-passed

#16050 Add grpc healthy check
  internal/distributed/proxy/service.go
  internal/distributed/proxy/service_test.go
  internal/util/mock/health_watch_server.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#16052 [skip e2e] Remove not useful file a
  a
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#16053 [skip e2e]Create tests for import api
  tests/python_client/testcases/test_import.py
Labels: kind/improvement, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#15155 Enhance the error handling of describeSegment
  internal/rootcoord/root_coord.go
  internal/rootcoord/task.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#15992 Refactor querynode historical replica
  internal/querynode/historical.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#16060 Set load meta info in load balance task
  internal/querycoord/task.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#16030 Reduce the number of metrics
  Makefile
  internal/datacoord/cluster.go
  internal/datacoord/handler.go
  internal/datacoord/meta.go
  internal/datacoord/server.go
  internal/datanode/compactor.go
  internal/datanode/data_node.go
  internal/datanode/data_sync_service.go
  internal/datanode/flow_graph_dd_node.go
  internal/datanode/flow_graph_dmstream_input_node.go
  internal/datanode/flow_graph_insert_buffer_node.go
  internal/datanode/flow_graph_manager.go
  internal/datanode/flush_manager.go
  internal/datanode/segment_replica.go
  internal/indexcoord/node_manager.go
  internal/indexnode/task.go
  internal/metrics/datacoord.go
  internal/metrics/datanode.go
  internal/metrics/indexcoord_metrics.go
  internal/metrics/indexnode_metrics.go
  internal/metrics/metrics.go
  internal/metrics/proxy_metrics.go
  internal/metrics/querycoord.go
  internal/metrics/querynode.go
  internal/metrics/rootcoord_metrics.go
  internal/proxy/channels_mgr.go
  internal/proxy/channels_time_ticker.go
  internal/proxy/impl.go
  internal/proxy/meta_cache.go
  internal/proxy/proxy.go
  internal/proxy/task.go
  internal/proxy/timestamp.go
  internal/querycoord/meta.go
  internal/querycoord/segments_info.go
  internal/querycoord/task.go
  internal/querynode/collection.go
  internal/querynode/collection_replica.go
  internal/querynode/flow_graph_query_node.go
  internal/querynode/query_collection.go
  internal/querynode/segment.go
  internal/querynode/segment_loader.go
  internal/querynode/streaming.go
  internal/querynode/task.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
  internal/rootcoord/task.go
  internal/rootcoord/timeticksync.go
  internal/rootcoord/util.go
  internal/rootcoord/util_test.go
  internal/util/funcutil/func.go
  internal/util/funcutil/func_test.go
Labels: size/XXL, approved, lgtm, ci-passed, dco-passed, area/compilation

#16063 Set load meta info in load balance task (#16060)
  internal/querycoord/task.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed

#15988 Remove collect query result by MQ
  internal/proxy/task_scheduler.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#16065 Set load info in rescheduled tasks
  internal/querycoord/task.go
  internal/querynode/task.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#16066 Set load info in reschedule tasks (#16065)
  internal/querycoord/task.go
  internal/querynode/task.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#16058 [test]Update all the testcase to 2.0.2
  tests/python_client/requirements.txt
  tests/python_client/testcases/test_collection.py
  tests/python_client/testcases/test_compaction.py
  tests/python_client/testcases/test_insert.py
  tests/python_client/testcases/test_search_20.py
  tests/python_client/testcases/test_utility.py
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#16064 [skip e2e]Fix scheduled github action cant't get input
  .github/workflows/pod-kill-chaos-test.yaml
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#16071 Fix rootcoord goroutine leak
  internal/mq/msgstream/mq_msgstream.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#16072 Cherry pick from master
  Makefile
  internal/datacoord/cluster.go
  internal/datacoord/handler.go
  internal/datacoord/meta.go
  internal/datacoord/server.go
  internal/datanode/compactor.go
  internal/datanode/data_node.go
  internal/datanode/data_sync_service.go
  internal/datanode/flow_graph_dd_node.go
  internal/datanode/flow_graph_dmstream_input_node.go
  internal/datanode/flow_graph_insert_buffer_node.go
  internal/datanode/flow_graph_manager.go
  internal/datanode/flush_manager.go
  internal/datanode/segment_replica.go
  internal/indexcoord/node_manager.go
  internal/indexnode/task.go
  internal/metrics/datacoord.go
  internal/metrics/datanode.go
  internal/metrics/indexcoord_metrics.go
  internal/metrics/indexnode_metrics.go
  internal/metrics/metrics.go
  internal/metrics/proxy_metrics.go
  internal/metrics/querycoord.go
  internal/metrics/querynode.go
  internal/metrics/rootcoord_metrics.go
  internal/proxy/channels_mgr.go
  internal/proxy/channels_time_ticker.go
  internal/proxy/impl.go
  internal/proxy/meta_cache.go
  internal/proxy/proxy.go
  internal/proxy/task.go
  internal/proxy/timestamp.go
  internal/querycoord/meta.go
  internal/querycoord/segments_info.go
  internal/querycoord/task.go
  internal/querynode/collection.go
  internal/querynode/collection_replica.go
  internal/querynode/collection_test.go
  internal/querynode/flow_graph_filter_dm_node.go
  internal/querynode/flow_graph_filter_dm_node_test.go
  internal/querynode/flow_graph_query_node.go
  internal/querynode/historical.go
  internal/querynode/historical_test.go
  internal/querynode/mock_test.go
  internal/querynode/query_collection.go
  internal/querynode/segment.go
  internal/querynode/segment_loader.go
  internal/querynode/segment_loader_test.go
  internal/querynode/streaming.go
  internal/querynode/task.go
  internal/querynode/task_test.go
  internal/querynode/type_def.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
  internal/rootcoord/task.go
  internal/rootcoord/timeticksync.go
  internal/rootcoord/util.go
  internal/rootcoord/util_test.go
  internal/util/funcutil/func.go
  internal/util/funcutil/func_test.go
Labels: kind/improvement, size/XXL, approved, lgtm, ci-passed, dco-passed, area/compilation

#15979 Bump go version in documentation
  DEVELOPMENT.md
  README.md
  README_CN.md
  go.mod
  internal/util/metricsinfo/metrics_info_test.go
  scripts/README.md
  tools/check/go.mod
Labels: area/dependency, kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#16080 Remove useless LogMgr
  internal/core/src/log/CMakeLists.txt
  internal/core/src/log/LogMgr.cpp
  internal/core/src/log/LogMgr.h
  internal/core/thirdparty/knowhere/CMakeLists.txt
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed, area/compilation

#15786 Support compile under windows
  .github/workflows/code-checker.yaml
  .github/workflows/main.yaml
  Makefile
  cmd/milvus/milvus.go
  deployments/windows/cleanup_data.bat
  deployments/windows/run_etcd.bat
  deployments/windows/run_milvus.bat
  deployments/windows/run_minio.bat
  go.mod
  go.sum
  internal/core/CMakeLists.txt
  internal/core/src/indexbuilder/CMakeLists.txt
  internal/core/src/indexbuilder/index_c.cpp
  internal/core/src/log/Log.cpp
  internal/core/src/query/SearchBruteForce.cpp
  internal/core/src/segcore/FieldIndexing.cpp
  internal/core/src/segcore/collection_c.cpp
  internal/core/thirdparty/knowhere/CMakeLists.txt
  internal/datacoord/server.go
  internal/datanode/data_node.go
  internal/indexcoord/index_coord.go
  internal/indexnode/index.go
  internal/indexnode/indexnode.go
  internal/proxy/proxy.go
  internal/querycoord/query_coord.go
  internal/querynode/collection.go
  internal/querynode/load_index_info.go
  internal/querynode/plan.go
  internal/querynode/query_node.go
  internal/querynode/segment.go
  internal/rootcoord/root_coord.go
  internal/storage/cwrapper/CMakeLists.txt
  internal/storage/payload.go
  internal/storage/print_binlog.go
  internal/util/cgoconverter/test_utils.go
  scripts/core_build.sh
  scripts/cwrapper_build.sh
  scripts/cwrapper_rocksdb_build.sh
  scripts/install_deps_msys.sh
  scripts/package_windows.sh
Labels: area/dependency, size/L, approved, lgtm, ci-passed, dco-passed, area/compilation

#15936 Replace minio kv with minio chunk manager
  internal/datanode/binlog_io.go
  internal/datanode/binlog_io_test.go
  internal/datanode/compactor_test.go
  internal/datanode/data_node.go
  internal/datanode/data_sync_service.go
  internal/datanode/data_sync_service_test.go
  internal/datanode/flow_graph_delete_node_test.go
  internal/datanode/flow_graph_insert_buffer_node_test.go
  internal/datanode/flow_graph_manager.go
  internal/datanode/flush_manager.go
  internal/datanode/flush_manager_test.go
  internal/datanode/segment_replica.go
  internal/datanode/segment_replica_test.go
  internal/indexcoord/index_coord.go
  internal/indexcoord/task_scheduler.go
  internal/indexnode/indexnode.go
  internal/indexnode/indexnode_test.go
  internal/indexnode/task.go
  internal/indexnode/task_scheduler.go
  internal/kv/minio/minio_kv.go
  internal/kv/minio/minio_kv_test.go
  internal/querycoord/cluster_test.go
  internal/querycoord/global_meta_broker.go
  internal/querycoord/global_meta_broker_test.go
  internal/querycoord/index_checker_test.go
  internal/querycoord/mock_3rd_component_test.go
  internal/querycoord/query_coord.go
  internal/querycoord/query_coord_test.go
  internal/querynode/mock_test.go
  internal/querynode/query_node.go
  internal/querynode/query_node_test.go
  internal/querynode/segment_loader.go
Labels: size/XXL, approved, lgtm, ci-passed, dco-passed

#16068 Fix wrong unittest, check whether loading collection will cause OOM
  internal/querynode/task_test.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#16084 Refine embed etcd metrics and logs
  cmd/roles/roles.go
  internal/distributed/datacoord/service.go
  internal/metrics/datacoord_metrics.go
  internal/metrics/datanode_metrics.go
  internal/metrics/indexcoord_metrics.go
  internal/metrics/indexnode_metrics.go
  internal/metrics/metrics.go
  internal/metrics/metrics_test.go
  internal/metrics/proxy_metrics.go
  internal/metrics/querycoord_metrics.go
  internal/metrics/querynode_metrics.go
  internal/metrics/rootcoord_metrics.go
  internal/proxy/proxy_test.go
  internal/util/etcd/etcd_server.go
  internal/util/etcd/etcd_util.go
  internal/util/etcd/etcd_util_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#15891 Add new config file(not applied)
  configs/config.go
  configs/config_test.go
  configs/milvus.example.toml
  go.mod
  go.sum
Labels: area/dependency, kind/improvement, size/XL, approved, lgtm, ci-passed, dco-passed

#16099 [test]Update the testcase with consistency
  tests/python_client/testcases/test_search_20.py
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#16094 [skip e2e]Fix comments of exposed functions in QC
  internal/querycoord/query_coord.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#15916 Implements restful entities api
  internal/distributed/proxy/httpserver/handler.go
  internal/distributed/proxy/httpserver/handler_test.go
  internal/distributed/proxy/httpserver/wrapper.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#16096 Tidy getQueryChannel for readability
  internal/querycoord/meta.go
  internal/querycoord/meta_test.go
  internal/querycoord/query_coord.go
  internal/querycoord/task.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#16093 Remove redundent requirement in python test
  tests/python_client/requirements.txt
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#15959 Unify interface of vector index & scalar index.
  internal/core/bench/bench_indexbuilder.cpp
  internal/core/src/indexbuilder/CMakeLists.txt
  internal/core/src/indexbuilder/IndexCreatorBase.h
  internal/core/src/indexbuilder/IndexFactory.h
  internal/core/src/indexbuilder/ScalarIndexCreator-inl.h
  internal/core/src/indexbuilder/ScalarIndexCreator.h
  internal/core/src/indexbuilder/StringIndexImpl.cpp
  internal/core/src/indexbuilder/StringIndexImpl.h
  internal/core/src/indexbuilder/VecIndexCreator.cpp
  internal/core/src/indexbuilder/VecIndexCreator.h
  internal/core/src/indexbuilder/helper.h
  internal/core/src/indexbuilder/index_c.cpp
  internal/core/src/indexbuilder/index_c.h
  internal/core/src/indexbuilder/type_c.h
  internal/core/src/indexbuilder/utils.cpp
  internal/core/src/indexbuilder/utils.h
  internal/core/src/pb/index_cgo_msg.pb.cc
  internal/core/src/pb/index_cgo_msg.pb.h
  internal/core/src/pb/milvus.pb.cc
  internal/core/src/pb/milvus.pb.h
  internal/core/unittest/CMakeLists.txt
  internal/core/unittest/test_index_c_api.cpp
  internal/core/unittest/test_index_wrapper.cpp
  internal/core/unittest/test_scalar_index_creator.cpp
  internal/core/unittest/test_segcore.cpp
  internal/core/unittest/test_utils/indexbuilder_test_utils.h
  internal/indexcoord/util.go
  internal/indexcoord/util_test.go
  internal/indexnode/index.go
  internal/indexnode/index_test.go
  internal/indexnode/task.go
  internal/proto/index_cgo_msg.proto
  internal/proto/indexcgopb/index_cgo_msg.pb.go
  internal/proto/milvus.proto
  internal/proto/milvuspb/milvus.pb.go
  internal/proxy/task.go
  internal/querycoord/cluster_test.go
  internal/querynode/mock_test.go
  internal/rootcoord/task.go
  internal/util/indexcgowrapper/codec_index_test.go
  internal/util/indexcgowrapper/dataset.go
  internal/util/indexcgowrapper/helper.go
  internal/util/indexcgowrapper/index.go
  internal/util/indexcgowrapper/index_bench.go
  internal/util/indexcgowrapper/index_test.go
  internal/util/indexparamcheck/scalar_index_checker.go
  internal/util/indexparamcheck/scalar_index_checker_test.go
Labels: kind/improvement, area/api, size/XXL, approved, lgtm, ci-passed, dco-passed, area/compilation

#16083 Prepare for import
  go.sum
  internal/core/src/pb/common.pb.cc
  internal/core/src/pb/common.pb.h
  internal/datacoord/mock_test.go
  internal/datacoord/server_test.go
  internal/datacoord/services.go
  internal/datanode/data_node.go
  internal/datanode/data_node_test.go
  internal/distributed/proxy/service_test.go
  internal/distributed/rootcoord/service_test.go
  internal/proto/common.proto
  internal/proto/commonpb/common.pb.go
  internal/proto/root_coord.proto
  internal/proto/rootcoordpb/root_coord.pb.go
  internal/proxy/impl.go
  internal/proxy/proxy_test.go
  internal/proxy/rootcoord_mock_test.go
  internal/rootcoord/import_manager.go
  internal/rootcoord/import_manager_test.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
  internal/types/types.go
Labels: area/dependency, size/XXL, approved, lgtm, ci-passed, dco-passed

#16125 [skip e2e]Add docker restart step for deploy test
  tests/python_client/deploy/test.sh
Labels: kind/improvement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#16129 modify import rpc interface
  internal/core/src/pb/common.pb.cc
  internal/core/src/pb/common.pb.h
  internal/core/src/pb/milvus.pb.cc
  internal/core/src/pb/schema.pb.cc
  internal/datacoord/server_test.go
  internal/datacoord/services.go
  internal/distributed/datacoord/client/client.go
  internal/distributed/datacoord/service.go
  internal/distributed/datacoord/service_test.go
  internal/distributed/proxy/service_test.go
  internal/distributed/rootcoord/service_test.go
  internal/proto/common.proto
  internal/proto/commonpb/common.pb.go
  internal/proto/data_coord.proto
  internal/proto/datapb/data_coord.pb.go
  internal/proto/milvus.proto
  internal/proto/milvuspb/milvus.pb.go
  internal/proto/schema.proto
  internal/proto/schemapb/schema.pb.go
  internal/proxy/data_coord_mock_test.go
  internal/rootcoord/import_manager.go
  internal/rootcoord/import_manager_test.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
  internal/types/types.go
  internal/util/mock/datacoord_client.go
Labels: area/api, size/XXL, approved, lgtm, ci-passed, dco-passed

#16109 Refactor search reduce in QueryNode, remove translateHits and redundant memory copy
  internal/core/src/common/FieldMeta.h
  internal/core/src/common/QueryResult.h
  internal/core/src/common/Types.h
  internal/core/src/segcore/Reduce.h
  internal/core/src/segcore/ReduceStructure.h
  internal/core/src/segcore/SegmentInterface.cpp
  internal/core/src/segcore/SegmentInterface.h
  internal/core/src/segcore/reduce_c.cpp
  internal/core/src/segcore/reduce_c.h
  internal/core/unittest/test_c_api.cpp
  internal/core/unittest/test_query.cpp
  internal/querynode/cgo_helper.go
  internal/querynode/mock_test.go
  internal/querynode/query_collection.go
  internal/querynode/reduce.go
  internal/querynode/reduce_test.go
  internal/querynode/segment_test.go
Labels: size/XXL, approved, lgtm, ci-passed

#16143 Add searchMerged function
  internal/querynode/query_collection.go
  internal/querynode/query_collection_test.go
  internal/querynode/reduce.go
  internal/querynode/reduce_test.go
Labels: size/L, approved, lgtm, ci-passed

#16100 Add column-based insert interface in segcore
  internal/core/src/segcore/segment_c.cpp
  internal/core/src/segcore/segment_c.h
  internal/core/unittest/test_c_api.cpp
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#16124 merge search reqs v1
  internal/querynode/query_collection.go
  internal/querynode/query_collection_test.go
Labels: size/L, approved, lgtm, ci-passed

#16155 modify import proto
  internal/core/src/pb/common.pb.cc
  internal/core/src/pb/common.pb.h
  internal/proto/common.proto
  internal/proto/commonpb/common.pb.go
  internal/proto/root_coord.proto
  internal/proto/rootcoordpb/root_coord.pb.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#16166 Support dynamic topk in search reduce
  internal/core/src/segcore/reduce_c.cpp
  internal/core/src/segcore/reduce_c.h
  internal/core/unittest/test_c_api.cpp
  internal/querynode/mock_test.go
  internal/querynode/query_collection.go
  internal/querynode/reduce.go
Labels: size/L

#16131 Support configurable msgstream
  cmd/roles/roles.go
  docs/developer_guides/chap04_message_stream.md
  internal/datacoord/server.go
  internal/datacoord/server_test.go
  internal/datanode/data_node.go
  internal/datanode/data_node_test.go
  internal/datanode/data_sync_service_test.go
  internal/datanode/flow_graph_dmstream_input_node_test.go
  internal/datanode/flow_graph_insert_buffer_node_test.go
  internal/mq/msgstream/mq_factory.go
  internal/mq/msgstream/mq_factory_test.go
  internal/mq/msgstream/mq_msgstream_test.go
  internal/mq/msgstream/msgstream.go
  internal/proxy/mock_test.go
  internal/proxy/proxy.go
  internal/querycoord/channel_unsubscribe_test.go
  internal/querycoord/cluster_test.go
  internal/querycoord/query_coord.go
  internal/querynode/mock_test.go
  internal/querynode/query_collection_test.go
  internal/querynode/query_node.go
  internal/querynode/query_node_test.go
  internal/querynode/stats_service_test.go
  internal/rootcoord/dml_channels_test.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
  internal/rootcoord/timestamp_test.go
  internal/rootcoord/timeticksync_test.go
  internal/util/flowgraph/input_node_test.go
  internal/util/flowgraph/node_test.go
  internal/util/paramtable/component_param.go
Labels: area/dependency, size/L, approved, lgtm, ci-passed, dco-passed

#16172 Loading segments concurrency level fallbacks to the value that won't cause OOM
  internal/querynode/segment_loader.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed

#16162 Copy index file content to c memory
  internal/core/src/common/vector_index_c.cpp
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#16178 Copy index file content to c memory
  internal/core/src/common/vector_index_c.cpp
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#16181 Fix reduce error and add range check
  internal/core/src/segcore/reduce_c.cpp
  internal/querynode/reduce.go
Labels: size/S, approved, lgtm, ci-passed

#16170 Improve log print in OOM error info
  internal/querynode/segment_loader.go
  internal/querynode/segment_loader_test.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#16165 Fix data race in unittest
  internal/querycoord/mock_querynode_server_test.go
  internal/querycoord/task_scheduler_test.go
  internal/querycoord/task_test.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#15931 Fix GetMemoryCount, get min as total memory
  internal/util/metricsinfo/hardware_info.go
  internal/util/metricsinfo/hardware_info_test.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#16185 [skip e2e]Fix deploy config
  .github/workflows/pod-kill-chaos-test.yaml
  tests/python_client/chaos/cluster-values.yaml
Labels: kind/improvement, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#16184 [test]Modify the testcase with collection
  tests/python_client/requirements.txt
  tests/python_client/testcases/test_collection.py
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#16164 Add Etcd support for Import Tasks.
  internal/kv/etcd/embed_etcd_kv.go
  internal/kv/etcd/embed_etcd_kv_test.go
  internal/kv/etcd/etcd_kv.go
  internal/kv/etcd/etcd_kv_test.go
  internal/kv/kv.go
  internal/kv/mock_kv.go
  internal/kv/mock_kv_test.go
  internal/proto/data_coord.proto
  internal/proto/datapb/data_coord.pb.go
  internal/rootcoord/import_manager.go
  internal/rootcoord/import_manager_test.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
  internal/util/paramtable/component_param.go
Labels: kind/feature, size/XXL, approved, lgtm, ci-passed, dco-passed

#16153 Add protobuf messages to support multi memory replica
  internal/core/src/pb/milvus.pb.cc
  internal/core/src/pb/milvus.pb.h
  internal/proto/milvus.proto
  internal/proto/milvuspb/milvus.pb.go
  internal/proto/query_coord.proto
  internal/proto/querypb/query_coord.pb.go
Labels: kind/feature, area/api, size/XXL, approved, lgtm, ci-passed, area/internal-api, dco-passed

#16182 Fix unregister in datacoord cluster
  internal/datacoord/cluster.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#16186 Upgrade to knowhere v1.1.0
  internal/core/bench/bench_indexbuilder.cpp
  internal/core/src/common/LoadInfo.h
  internal/core/src/common/vector_index_c.cpp
  internal/core/src/config/ConfigKnowhere.cpp
  internal/core/src/index/Index.h
  internal/core/src/indexbuilder/ScalarIndexCreator-inl.h
  internal/core/src/indexbuilder/ScalarIndexCreator.h
  internal/core/src/indexbuilder/VecIndexCreator.cpp
  internal/core/src/indexbuilder/VecIndexCreator.h
  internal/core/src/indexbuilder/index_c.cpp
  internal/core/src/indexbuilder/utils.cpp
  internal/core/src/indexbuilder/utils.h
  internal/core/src/query/SearchBruteForce.cpp
  internal/core/src/query/SearchOnIndex.cpp
  internal/core/src/query/SearchOnSealed.cpp
  internal/core/src/segcore/load_index_c.cpp
  internal/core/thirdparty/knowhere/CMakeLists.txt
  internal/core/unittest/test_c_api.cpp
  internal/core/unittest/test_conf_adapter_mgr.cpp
  internal/core/unittest/test_index_c_api.cpp
  internal/core/unittest/test_index_wrapper.cpp
  internal/core/unittest/test_indexing.cpp
  internal/core/unittest/test_scalar_index_creator.cpp
  internal/core/unittest/test_sealed.cpp
  internal/core/unittest/test_utils/DataGen.h
  internal/core/unittest/test_utils/indexbuilder_test_utils.h
  internal/util/indexcgowrapper/index_test.go
Labels: kind/enhancement, size/XXL, approved, lgtm, ci-passed, dco-passed, area/compilation

#16190 Add replica interfaces for Meta and Cluster
  internal/querycoord/cluster.go
  internal/querycoord/meta.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#15993 Support insert string data
  go.sum
  internal/datanode/binlog_io_test.go
  internal/datanode/compactor.go
  internal/datanode/compactor_test.go
  internal/datanode/data_node_test.go
  internal/datanode/data_sync_service_test.go
  internal/datanode/flow_graph_insert_buffer_node.go
  internal/datanode/flow_graph_insert_buffer_node_test.go
  internal/datanode/flow_graph_manager_test.go
  internal/datanode/flush_manager_test.go
  internal/datanode/meta_service_test.go
  internal/datanode/mock_test.go
  internal/datanode/segment_replica.go
  internal/datanode/segment_replica_test.go
  internal/mq/msgstream/msg.go
  internal/mq/msgstream/msg_test.go
  internal/mq/msgstream/repack_func.go
  internal/proxy/impl.go
  internal/proxy/mock_test.go
  internal/proxy/task.go
  internal/proxy/task_test.go
  internal/proxy/util.go
  internal/proxy/util_test.go
  internal/querynode/flow_graph_filter_dm_node.go
  internal/querynode/flow_graph_insert_node.go
  internal/storage/cwrapper/ColumnType.h
  internal/storage/cwrapper/ParquetWrapper.cpp
  internal/storage/data_codec.go
  internal/storage/data_sorter.go
  internal/storage/payload.go
  internal/storage/primary_key.go
  internal/storage/primary_key_test.go
  internal/storage/print_binlog.go
  internal/storage/stats.go
  internal/storage/stats_test.go
  internal/storage/utils.go
  internal/storage/utils_test.go
  internal/util/funcutil/func.go
  internal/util/funcutil/func_test.go
  internal/util/typeutil/data_format.go
  internal/util/typeutil/data_format_test.go
  internal/util/typeutil/hash.go
  internal/util/typeutil/hash_test.go
  internal/util/typeutil/schema.go
  internal/util/typeutil/schema_test.go
Labels: kind/feature, area/dependency, size/XXL, approved, lgtm, ci-passed, dco-passed

#16188 [skip e2e]Add more check step in jenkins pipline
  build/ci/jenkins/ChaosTest.groovy
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#15912 Add cache for vector chunk
  configs/milvus.yaml
  internal/querynode/mock_test.go
  internal/querynode/query_collection.go
  internal/storage/local_chunk_manager.go
  internal/storage/lru_cache.go
  internal/storage/minio_chunk_manager.go
  internal/storage/minio_chunk_manager_test.go
  internal/storage/types.go
  internal/storage/vector_chunk_manager.go
  internal/storage/vector_chunk_manager_test.go
  internal/util/cache/lru_cache.go
  internal/util/cache/lru_cache_test.go
  internal/util/paramtable/component_param.go
Labels: size/XXL, approved, lgtm, ci-passed, dco-passed

#16194 Add libtool to builder image
  build/docker/builder/cpu/centos7/Dockerfile
  build/docker/builder/cpu/ubuntu18.04/Dockerfile
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#16206 [skip e2e]Fix deploy config
  tests/python_client/deploy/cluster-values.yaml
Labels: kind/improvement, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#16210 Upgrade to knowhere v1.1.1 to support Mac M1 build
  internal/core/thirdparty/knowhere/CMakeLists.txt
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed, area/compilation

#16213 Add interface to get replications by collection ID
  internal/querycoord/meta.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#16221 [test]Add performance monitor for ApiCollectionWrapper
  tests/python_client/base/collection_wrapper.py
  tests/python_client/requirements.txt
  tests/python_client/testcases/test_e2e.py
  tests/python_client/utils/wrapper.py
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#16198 Support check index state in root coord, for bulk load feature.
  internal/proxy/task.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
Labels: kind/feature, size/L, approved, lgtm, ci-passed, dco-passed
