Repository milvus-io/milvus, pull requests merged in 2022-04, with the labels that each got.

#16296 Add performance test for import
  internal/util/importutil/import_wrapper.go
  internal/util/importutil/import_wrapper_test.go
  internal/util/importutil/json_handler.go
  internal/util/importutil/json_parser.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#16337 Fix Datacoord unsubAttempt using pchannel
  internal/datacoord/channel_manager.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#16321 Implement RC, DC, DN calling path for import.
  internal/datacoord/cluster.go
  internal/datacoord/cluster_test.go
  internal/datacoord/mock_test.go
  internal/datacoord/server_test.go
  internal/datacoord/services.go
  internal/datacoord/session_manager.go
  internal/datanode/data_node.go
  internal/datanode/data_node_test.go
  internal/distributed/datacoord/client/client.go
  internal/distributed/datacoord/service.go
  internal/distributed/datacoord/service_test.go
  internal/distributed/datanode/client/client.go
  internal/distributed/datanode/service.go
  internal/distributed/datanode/service_test.go
  internal/distributed/proxy/service_test.go
  internal/distributed/rootcoord/service_test.go
  internal/proto/data_coord.proto
  internal/proto/datapb/data_coord.pb.go
  internal/proxy/data_coord_mock_test.go
  internal/rootcoord/import_manager.go
  internal/rootcoord/import_manager_test.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
  internal/types/types.go
  internal/util/mock/datacoord_client.go
  internal/util/mock/datanode_client.go
Labels: kind/feature, size/XL, approved, lgtm, ci-passed, dco-passed

#16340 [skip e2e]Update deploy test github action
  .github/workflows/deploy-test.yaml
  tests/python_client/deploy/check_healthy.sh
Labels: kind/improvement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#16317 Add QueryShardService implementation in QueryNode
  internal/querynode/query_shard.go
  internal/querynode/query_shard_service.go
  internal/querynode/query_shard_service_test.go
  internal/querynode/query_shard_test.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#16338 Fix Datacoord unsubAttempt using pchannel (#16337)
  internal/datacoord/channel_manager.go
Labels: kind/bug, size/XS, approved, lgtm, dco-passed

#16316 [skip e2e] Add commit-id after date
  .github/workflows/publish-builder.yaml
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#16328 Modify proto & add GetReplicas() interface
  internal/distributed/proxy/service_test.go
  internal/distributed/querycoord/client/client.go
  internal/distributed/querycoord/client/client_test.go
  internal/distributed/querycoord/service.go
  internal/distributed/querycoord/service_test.go
  internal/proto/query_coord.proto
  internal/proto/querypb/query_coord.pb.go
  internal/proxy/query_coord_mock_test.go
  internal/querycoord/impl.go
  internal/querycoord/meta.go
  internal/querycoord/replica.go
  internal/types/types.go
  internal/util/mock/querycoord_client.go
Labels: kind/improvement, size/XXL, approved, lgtm, ci-passed, area/internal-api, dco-passed

#16344 Use fmt.Errorf instead of string concat in tsafe_replica
  internal/querynode/tsafe_replica.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#16325 Rearrange search/queryTask for readability
  internal/proxy/task.go
  internal/proxy/task_query.go
  internal/proxy/task_query_test.go
  internal/proxy/task_search.go
  internal/proxy/task_search_test.go
  internal/proxy/task_test.go
Labels: size/XXL, approved, lgtm, ci-passed, dco-passed

#16346 Fix ticker leakage in datanode flowgraph
  internal/datanode/flow_graph_time_ticker.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#16350 [skip e2e]Update issue example into #<xyx>
  .github/mergify.yml
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#16352 Fix DML channel AsProducer after Close
  internal/rootcoord/dml_channels.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#16326 Modify grpc interface for replica Search/Query in QueryNode
  internal/distributed/querynode/client/client.go
  internal/distributed/querynode/service.go
  internal/distributed/querynode/service_test.go
  internal/proto/query_coord.proto
  internal/proto/querypb/query_coord.pb.go
  internal/querycoord/mock_querynode_client_test.go
  internal/querynode/impl.go
  internal/types/types.go
  internal/util/mock/querynode_client.go
Labels: size/L, approved, lgtm, ci-passed, area/internal-api, dco-passed

#16358 Bump milvus version to v2.0.2
  deployments/binary/README.md
  deployments/docker/cluster/docker-compose.yml
  deployments/docker/standalone/docker-compose.yml
Labels: kind/improvement, size/S, approved, lgtm, dco-passed

#16360 Add ShardCluster implementation
  internal/querynode/shard_cluster.go
  internal/querynode/shard_cluster_test.go
Labels: kind/enhancement, size/XXL, approved, lgtm, ci-passed, dco-passed

#16229 Support delete varChar value
  internal/core/src/pb/plan.pb.cc
  internal/core/src/pb/plan.pb.h
  internal/datanode/binlog_io_test.go
  internal/datanode/compactor.go
  internal/datanode/compactor_test.go
  internal/datanode/flow_graph_dd_node.go
  internal/datanode/flow_graph_delete_node.go
  internal/datanode/flow_graph_delete_node_test.go
  internal/datanode/flow_graph_insert_buffer_node_test.go
  internal/datanode/mock_test.go
  internal/datanode/segment_replica.go
  internal/datanode/segment_replica_test.go
  internal/mq/msgstream/mq_msgstream_test.go
  internal/mq/msgstream/msg.go
  internal/mq/msgstream/msg_test.go
  internal/mq/msgstream/repack_func.go
  internal/proto/internal.proto
  internal/proto/internalpb/internal.pb.go
  internal/proto/plan.proto
  internal/proto/planpb/plan.pb.go
  internal/proto/schema.proto
  internal/proxy/impl.go
  internal/proxy/mock_test.go
  internal/proxy/plan_parser.go
  internal/proxy/task.go
  internal/proxy/task_test.go
  internal/proxy/util.go
  internal/querynode/flow_graph_delete_node.go
  internal/querynode/flow_graph_delete_node_test.go
  internal/querynode/flow_graph_filter_delete_node.go
  internal/querynode/flow_graph_filter_delete_node_test.go
  internal/querynode/flow_graph_filter_dm_node.go
  internal/querynode/flow_graph_filter_dm_node_test.go
  internal/querynode/flow_graph_insert_node.go
  internal/querynode/flow_graph_insert_node_test.go
  internal/querynode/mock_test.go
  internal/querynode/segment.go
  internal/querynode/segment_loader.go
  internal/querynode/segment_loader_test.go
  internal/querynode/segment_test.go
  internal/storage/binlog_iterator.go
  internal/storage/binlog_iterator_test.go
  internal/storage/data_codec.go
  internal/storage/data_codec_test.go
  internal/storage/payload_reader.go
  internal/storage/primary_key.go
  internal/storage/primary_key_test.go
  internal/storage/stats.go
  internal/storage/stats_test.go
  internal/util/typeutil/schema.go
Labels: kind/feature, area/dependency, size/XXL, approved, lgtm, ci-passed, area/internal-api, dco-passed

#16348 Support import numpy file
  go.mod
  go.sum
  internal/util/importutil/import_wrapper.go
  internal/util/importutil/import_wrapper_test.go
  internal/util/importutil/json_parser.go
  internal/util/importutil/numpy_adapter.go
  internal/util/importutil/numpy_adapter_test.go
  internal/util/importutil/numpy_parser.go
  internal/util/importutil/numpy_parser_test.go
  scripts/run_go_unittest.sh
Labels: area/dependency, size/XXL, approved, lgtm, ci-passed, dco-passed

#16355 Implement task expiring logic and make all deadlines configurable.
  configs/milvus.yaml
  internal/rootcoord/import_manager.go
  internal/rootcoord/import_manager_test.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
  internal/util/paramtable/component_param.go
  internal/util/paramtable/component_param_test.go
Labels: kind/feature, size/L, approved, lgtm, ci-passed, dco-passed

#16380 Fix build error on mac
  internal/core/unittest/test_utils/Timer.h
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#16386 Move bench to directory unittest
  internal/core/CMakeLists.txt
  internal/core/unittest/CMakeLists.txt
  internal/core/unittest/bench/CMakeLists.txt
  internal/core/unittest/bench/bench_indexbuilder.cpp
  internal/core/unittest/bench/bench_naive.cpp
  internal/core/unittest/bench/bench_search.cpp
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed, area/compilation

#16354 Compressed log
  internal/indexcoord/index_coord.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#16363 Fix log error
  internal/indexnode/task.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#16365 Compress IndexNode log
  internal/indexnode/indexnode.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#16368 Unify QueryNode in log print
  internal/querynode/query_node.go
  internal/querynode/task.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#16370 Fix segIDAssigner spelling mistake
  internal/proxy/segment.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#16367 Handle error and oragnize log
  internal/indexcoord/index_coord.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#16369 Print numTimestamps instead of Timestamps
  internal/querynode/flow_graph_delete_node.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#16390 Impl GetReplicas in Proxy
  internal/core/src/pb/milvus.pb.cc
  internal/core/src/pb/milvus.pb.h
  internal/distributed/proxy/service.go
  internal/distributed/proxy/service_test.go
  internal/distributed/querycoord/client/client.go
  internal/distributed/querycoord/service.go
  internal/distributed/querycoord/service_test.go
  internal/proto/milvus.proto
  internal/proto/milvuspb/milvus.pb.go
  internal/proto/query_coord.proto
  internal/proto/querypb/query_coord.pb.go
  internal/proxy/impl.go
  internal/proxy/query_coord_mock_test.go
  internal/querycoord/cluster.go
  internal/querycoord/impl.go
  internal/querycoord/meta.go
  internal/querycoord/replica.go
  internal/types/types.go
  internal/util/mock/querycoord_client.go
Labels: area/api, size/XXL, approved, lgtm, ci-passed, area/internal-api, dco-passed

#16374 Implement set segment state call from RootCoord to DataCoord.
  internal/datacoord/server.go
  internal/datacoord/server_test.go
  internal/datacoord/services.go
  internal/distributed/datacoord/client/client.go
  internal/distributed/datacoord/service.go
  internal/distributed/datacoord/service_test.go
  internal/distributed/proxy/service_test.go
  internal/distributed/rootcoord/service_test.go
  internal/kv/mock_kv.go
  internal/proto/data_coord.proto
  internal/proto/datapb/data_coord.pb.go
  internal/proxy/data_coord_mock_test.go
  internal/rootcoord/import_manager.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
  internal/types/types.go
  internal/util/mock/datacoord_client.go
Labels: kind/feature, size/XXL, approved, lgtm, ci-passed, dco-passed

#16373 Add ShardNodeDetector implementation
  internal/querynode/shard_cluster.go
  internal/querynode/shard_cluster_test.go
  internal/querynode/shard_node_detector.go
  internal/querynode/shard_node_detector_test.go
Labels: kind/improvement, size/XL, approved, lgtm, ci-passed, dco-passed

#16393 Upgrade minio version to RELEASE.2022-03-17T06-34-49Z
  deployments/docker/cluster/docker-compose.yml
  deployments/docker/dev/docker-compose-apple-silicon.yml
  deployments/docker/dev/docker-compose.yml
  deployments/docker/standalone/docker-compose.yml
  docker-compose.yml
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#16400 Fix ReplicaInfo package name
  .github/workflows/code-checker.yaml
  Makefile
  internal/querynode/shard_node_detector.go
  internal/querynode/shard_node_detector_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed, area/compilation

#16398 Avoid using specific port in ut
  internal/distributed/connection_manager_test.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#16408 [skip e2e]Update MilvusSys to adapt to new version pymilvus
  tests/python_client/common/milvus_sys.py
Labels: kind/improvement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#16409 Reduce ID cache duration.
  configs/embedded-milvus.yaml
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#16415 Fix mac build error
  internal/core/src/segcore/load_index_c.cpp
  internal/core/unittest/test_c_api.cpp
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#16410 Drop log level in delete node showDelBuf
  internal/datanode/flow_graph_delete_node.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#16419 Remove unused directory
  internal/core/src/value/CMakeLists.txt
  internal/core/src/value/Value.h
  internal/core/src/value/ValueMgr.cpp
  internal/core/src/value/ValueMgr.h
  internal/core/src/value/ValueType.cpp
  internal/core/src/value/ValueType.h
  internal/core/src/value/ValueTypeTest1.cpp
  internal/core/src/value/ValueTypeTest2.cpp
  internal/core/src/value/config/ConfigInit.cpp
  internal/core/src/value/config/ConfigMgr.cpp
  internal/core/src/value/config/ConfigMgr.h
  internal/core/src/value/config/ServerConfig.cpp
  internal/core/src/value/config/ServerConfig.h
  internal/core/src/value/config/ServerConfigTest.cpp
  internal/core/src/value/status/ServerStatus.cpp
  internal/core/src/value/status/ServerStatus.h
  internal/core/src/value/status/StatusInit.cpp
  internal/core/src/value/status/StatusMgr.cpp
  internal/core/src/value/status/StatusMgr.h
Labels: kind/improvement, size/XXL, approved, lgtm, ci-passed, dco-passed, area/compilation

#16418 [test] Add and update cases for insert a deleted id
  tests/python_client/testcases/test_delete.py
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#16395 Fix bug for merging search messages
  internal/metrics/querynode.go
  internal/proxy/task.go
  internal/querynode/mock_test.go
  internal/querynode/msg.go
  internal/querynode/query_collection.go
Labels: size/L, approved, lgtm, ci-passed

#16416 Support milvus build on mac
  .github/workflows/code-checker.yaml
  internal/core/CMakeLists.txt
  internal/core/src/index/IndexFactory-inl.h
  internal/core/src/index/StringIndexMarisa.cpp
  internal/core/src/indexbuilder/VecIndexCreator.cpp
  internal/core/src/indexbuilder/utils.cpp
  internal/core/src/query/SearchBruteForce.cpp
  internal/core/src/query/visitors/VerifyPlanNodeVisitor.cpp
  internal/core/src/segcore/FieldIndexing.cpp
  internal/core/thirdparty/knowhere/CMakeLists.txt
  internal/core/unittest/CMakeLists.txt
  internal/core/unittest/test_index_c_api.cpp
  internal/core/unittest/test_indexing.cpp
  internal/core/unittest/test_query.cpp
  internal/core/unittest/test_sealed.cpp
  internal/core/unittest/test_utils/indexbuilder_test_utils.h
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed, area/compilation

#16436 Cherry pick remove translateHits commit to mater
  internal/core/src/common/FieldMeta.h
  internal/core/src/common/QueryResult.h
  internal/core/src/common/Types.h
  internal/core/src/segcore/Reduce.h
  internal/core/src/segcore/ReduceStructure.h
  internal/core/src/segcore/SegmentInterface.cpp
  internal/core/src/segcore/SegmentInterface.h
  internal/core/src/segcore/reduce_c.cpp
  internal/core/src/segcore/reduce_c.h
  internal/core/unittest/test_c_api.cpp
  internal/core/unittest/test_query.cpp
  internal/querynode/cgo_helper.go
  internal/querynode/mock_test.go
  internal/querynode/query_collection.go
  internal/querynode/reduce.go
  internal/querynode/reduce_test.go
  internal/querynode/segment_test.go
Labels: kind/improvement, size/XXL, approved, lgtm, ci-passed, dco-passed

#16438 Add configuration common.indexSliceSize
  configs/milvus.yaml
  internal/core/src/config/ConfigKnowhere.cpp
  internal/core/src/config/ConfigKnowhere.h
  internal/core/src/indexbuilder/init_c.cpp
  internal/core/src/indexbuilder/init_c.h
  internal/core/src/segcore/segcore_init_c.cpp
  internal/core/src/segcore/segcore_init_c.h
  internal/core/thirdparty/knowhere/CMakeLists.txt
  internal/indexnode/indexnode.go
  internal/querynode/query_node.go
  internal/util/paramtable/component_param.go
  internal/util/paramtable/component_param_test.go
Labels: kind/feature, size/M, approved, lgtm, ci-passed, dco-passed, area/compilation

#16441 [skip e2e] Remove useless OpenMP settings in CMakeLists.txt
  internal/core/CMakeLists.txt
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed, area/compilation

#16404 Use fmt.Errorf instead of string concat in schema.go
  internal/util/typeutil/schema.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#16439 Add test coverage target in Makefile
  Makefile
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed, area/compilation

#16432 [test] Update test case for indexing process assert
  tests/python_client/testcases/test_utility.py
Labels: sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#16341 Support login with username and password #15656
  go.mod
  internal/core/src/pb/common.pb.cc
  internal/core/src/pb/common.pb.h
  internal/core/src/pb/milvus.pb.cc
  internal/core/src/pb/milvus.pb.h
  internal/datacoord/mock_test.go
  internal/distributed/proxy/client/client.go
  internal/distributed/proxy/client/client_test.go
  internal/distributed/proxy/service.go
  internal/distributed/proxy/service_test.go
  internal/distributed/rootcoord/client/client.go
  internal/distributed/rootcoord/client/client_test.go
  internal/distributed/rootcoord/service.go
  internal/metrics/metrics.go
  internal/metrics/proxy_metrics.go
  internal/metrics/rootcoord_metrics.go
  internal/proto/common.proto
  internal/proto/commonpb/common.pb.go
  internal/proto/internal.proto
  internal/proto/internalpb/internal.pb.go
  internal/proto/milvus.proto
  internal/proto/milvuspb/milvus.pb.go
  internal/proto/proxy.proto
  internal/proto/proxypb/proxy.pb.go
  internal/proto/root_coord.proto
  internal/proto/rootcoordpb/root_coord.pb.go
  internal/proxy/authentication_interceptor.go
  internal/proxy/authentication_interceptor_test.go
  internal/proxy/error.go
  internal/proxy/impl.go
  internal/proxy/meta_cache.go
  internal/proxy/meta_cache_test.go
  internal/proxy/proxy_test.go
  internal/proxy/rootcoord_mock_test.go
  internal/proxy/util.go
  internal/proxy/util_test.go
  internal/querynode/proxy_mock_test.go
  internal/rootcoord/meta_table.go
  internal/rootcoord/meta_table_test.go
  internal/rootcoord/proxy_client_manager.go
  internal/rootcoord/proxy_client_manager_test.go
  internal/rootcoord/root_coord.go
  internal/types/types.go
  internal/util/constant.go
  internal/util/crypto/crypto.go
  internal/util/crypto/crypto_test.go
  internal/util/grpcclient/auth.go
  internal/util/grpcclient/client.go
  internal/util/mock/proxy_client.go
  internal/util/mock/rootcoord_client.go
  internal/util/paramtable/component_param.go
  internal/util/typeutil/string_util.go
  internal/util/typeutil/string_util_test.go
Labels: kind/feature, area/dependency, area/api, size/XXL, approved, lgtm, ci-passed, area/internal-api, dco-passed

#16457 Bump milvus helm version to 3.0.19
  build/ci/jenkins/Nightly.groovy
  build/ci/jenkins/PR.groovy
  tests/scripts/values/pr.yaml
Labels: kind/improvement, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#16458 Remove dependency on knowhere::scalar
  internal/core/src/query/ScalarIndex.h
  internal/core/src/query/visitors/ExecExprVisitor.cpp
  internal/core/src/segcore/FieldIndexing.h
  internal/core/unittest/test_bitmap.cpp
  internal/core/unittest/test_scalar_index_creator.cpp
  internal/core/unittest/test_utils/indexbuilder_test_utils.h
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#16435 [skip e2e]Update image repo in jenkins file
  build/ci/jenkins/ChaosTest.groovy
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#16460 Add negtive tescases for load balance
  tests/python_client/testcases/test_utility.py
Labels: kind/improvement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#16464 [skip e2e]Update latest release version and fix check healthy script
  .github/workflows/deploy-test.yaml
  tests/python_client/deploy/check_healthy.sh
Labels: kind/improvement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#16149 Support Kafka
  cmd/roles/roles.go
  configs/milvus.yaml
  deployments/docker/dev/docker-compose.yml
  go.mod
  go.sum
  internal/datacoord/server.go
  internal/kv/mem/mem_kv.go
  internal/mq/msgstream/mq_factory.go
  internal/mq/msgstream/mq_kafka_msgstream_test.go
  internal/mq/msgstream/mq_msgstream.go
  internal/mq/msgstream/mq_msgstream_test.go
  internal/mq/msgstream/mqwrapper/consumer.go
  internal/mq/msgstream/mqwrapper/kafka/kafka_client.go
  internal/mq/msgstream/mqwrapper/kafka/kafka_client_test.go
  internal/mq/msgstream/mqwrapper/kafka/kafka_consumer.go
  internal/mq/msgstream/mqwrapper/kafka/kafka_consumer_test.go
  internal/mq/msgstream/mqwrapper/kafka/kafka_id.go
  internal/mq/msgstream/mqwrapper/kafka/kafka_id_test.go
  internal/mq/msgstream/mqwrapper/kafka/kafka_message.go
  internal/mq/msgstream/mqwrapper/kafka/kafka_message_test.go
  internal/mq/msgstream/mqwrapper/kafka/kafka_producer.go
  internal/mq/msgstream/mqwrapper/kafka/kafka_producer_test.go
  internal/querycoord/query_coord.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
  internal/util/dependency/factory.go
  internal/util/paramtable/base_table.go
  internal/util/paramtable/base_table_test.go
  internal/util/paramtable/component_param.go
  internal/util/paramtable/service_param.go
  scripts/run_go_codecov.sh
  scripts/run_go_unittest.sh
Labels: area/dependency, size/XXL, approved, lgtm, ci-passed, dco-passed

#16466 Disable pulsar pod monitor
  tests/scripts/install_milvus.sh
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#16465 Add env variable for metric ports
  internal/metrics/metrics.go
  internal/metrics/metrics_test.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#16414 Add datanode import
  internal/datacoord/services.go
  internal/datanode/data_node.go
  internal/datanode/data_node_test.go
  internal/datanode/mock_test.go
  internal/storage/local_chunk_manager.go
  internal/storage/local_chunk_manager_test.go
  internal/storage/minio_chunk_manager.go
  internal/storage/minio_chunk_manager_test.go
  internal/storage/types.go
  internal/storage/vector_chunk_manager.go
  internal/storage/vector_chunk_manager_test.go
  internal/util/importutil/import_wrapper.go
  internal/util/importutil/import_wrapper_test.go
  internal/util/importutil/json_handler.go
  internal/util/importutil/json_handler_test.go
  internal/util/importutil/json_parser.go
  internal/util/importutil/numpy_adapter.go
  internal/util/importutil/numpy_parser_test.go
Labels: kind/enhancement, size/XL, approved, lgtm, ci-passed, dco-passed

#16471 [skip e2e]Add to util to map pod ip to pod name
  tests/python_client/utils/util_k8s.py
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#16467 [skip e2e]Split verification into more steps
  .github/workflows/pod-kill-chaos-test.yaml
  tests/python_client/chaos/scripts/verify_all_collections.py
Labels: kind/improvement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#16444 Adaptation windows for Knowhere 1.1.3
  internal/core/thirdparty/knowhere/CMakeLists.txt
  internal/indexnode/indexnode.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed, area/compilation

#16478 Fix bug: data race caused by read and write Params.DataNodeCfg.NodeID
  internal/datanode/data_node_test.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#16483 Fix mq factory ut
  internal/mq/msgstream/mq_factory_test.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#16472 Update compile options and config for embedded Milvus
  Makefile
  configs/embedded-milvus.yaml
  internal/distributed/proxy/service.go
  internal/kv/rocksdb/cwrapper/CMakeLists.txt
  internal/storage/cwrapper/CMakeLists.txt
  scripts/cwrapper_build.sh
  scripts/cwrapper_rocksdb_build.sh
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed, area/compilation

#16474 Fix a bug where RPC calls before proxy finishes init crashes Milvus
  cmd/components/proxy.go
  cmd/roles/roles.go
  internal/proxy/authentication_interceptor.go
  internal/proxy/error.go
  internal/proxy/proxy.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#16494 Add kafka support in nightly CI
  build/ci/jenkins/Nightly.groovy
  tests/scripts/get_release_name.sh
  tests/scripts/values/kafka.yaml
  tests/scripts/values/pulsar.yaml
Labels: sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#16476 Use boost dynamic_bitset in segcore
  internal/core/run_clang_format.sh
  internal/core/src/common/BitsetView.cpp
  internal/core/src/common/BitsetView.h
  internal/core/src/common/CMakeLists.txt
  internal/core/src/common/Types.h
  internal/core/src/query/CMakeLists.txt
  internal/core/src/query/SearchBruteForce.cpp
  internal/core/src/query/SearchBruteForce.h
  internal/core/src/query/SearchOnGrowing.cpp
  internal/core/src/query/SearchOnGrowing.h
  internal/core/src/query/SearchOnIndex.cpp
  internal/core/src/query/SearchOnIndex.h
  internal/core/src/query/SearchOnSealed.cpp
  internal/core/src/query/SearchOnSealed.h
  internal/core/src/query/visitors/ExecPlanNodeVisitor.cpp
  internal/core/src/segcore/DeletedRecord.h
  internal/core/src/segcore/SegmentGrowingImpl.cpp
  internal/core/src/segcore/SegmentGrowingImpl.h
  internal/core/src/segcore/SegmentInterface.h
  internal/core/src/segcore/SegmentSealedImpl.cpp
  internal/core/src/segcore/SegmentSealedImpl.h
  internal/core/thirdparty/knowhere/CMakeLists.txt
  internal/core/unittest/test_indexing.cpp
  internal/core/unittest/test_query.cpp
  internal/core/unittest/test_scalar_index_creator.cpp
  internal/core/unittest/test_sealed.cpp
  internal/core/unittest/test_utils/indexbuilder_test_utils.h
Labels: size/L, approved, lgtm, ci-passed, dco-passed, area/compilation

#16498 Upgrade to knowhere v1.1.5 to fully support MinGW build
  internal/core/src/common/BitsetView.cpp
  internal/core/src/common/BitsetView.h
  internal/core/src/common/CMakeLists.txt
  internal/core/thirdparty/knowhere/CMakeLists.txt
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed, area/compilation

#16449 Remove usage to rootcoord timetick
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
  internal/rootcoord/timeticksync.go
  internal/util/paramtable/component_param.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed, area/compilation

#16492 [skip e2e] Add distributed deployment on docker host
  deployments/docker/cluster-distributed-deployment/ansible.cfg
  deployments/docker/cluster-distributed-deployment/deploy-docker.yml
  deployments/docker/cluster-distributed-deployment/deploy-milvus.yml
  deployments/docker/cluster-distributed-deployment/inventory.ini
  deployments/docker/cluster-distributed-deployment/roles/configure-hosts-file/tasks/main.yml
  deployments/docker/cluster-distributed-deployment/roles/deploy-datacoord/tasks/main.yml
  deployments/docker/cluster-distributed-deployment/roles/deploy-datanode/tasks/main.yml
  deployments/docker/cluster-distributed-deployment/roles/deploy-etcd/tasks/main.yml
  deployments/docker/cluster-distributed-deployment/roles/deploy-indexcoord/tasks/main.yml
  deployments/docker/cluster-distributed-deployment/roles/deploy-indexnode/tasks/main.yml
  deployments/docker/cluster-distributed-deployment/roles/deploy-minio/tasks/main.yml
  deployments/docker/cluster-distributed-deployment/roles/deploy-proxy/tasks/main.yml
  deployments/docker/cluster-distributed-deployment/roles/deploy-pulsar/tasks/main.yml
  deployments/docker/cluster-distributed-deployment/roles/deploy-querycoord/tasks/main.yml
  deployments/docker/cluster-distributed-deployment/roles/deploy-querynode/tasks/main.yml
  deployments/docker/cluster-distributed-deployment/roles/deploy-rootcoord/tasks/main.yml
  deployments/docker/cluster-distributed-deployment/roles/docker-installation/tasks/main.yml
  deployments/docker/cluster-distributed-deployment/roles/install-modules/tasks/main.yml
Labels: kind/improvement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, area/compilation

#16527 Update version of pymilvus and fix ci cases
  tests/python_client/requirements.txt
  tests/python_client/scale/test_data_node_scale.py
  tests/python_client/scale/test_index_node_scale.py
  tests/python_client/scale/test_proxy_scale.py
  tests/python_client/scale/test_query_node_scale.py
  tests/python_client/testcases/test_compaction.py
  tests/python_client/testcases/test_index.py
  tests/python_client/testcases/test_insert.py
  tests/python_client/testcases/test_utility.py
Labels: approved, lgtm, area/test, ci-passed, dco-passed

#16523 fix bug: updating the password for a non-existing user does not report error
  configs/milvus.yaml
  internal/core/src/pb/milvus.pb.cc
  internal/core/src/pb/milvus.pb.h
  internal/distributed/proxy/service.go
  internal/distributed/proxy/service_test.go
  internal/proto/milvus.proto
  internal/proto/milvuspb/milvus.pb.go
  internal/proxy/authentication_interceptor.go
  internal/proxy/authentication_interceptor_test.go
  internal/proxy/impl.go
  internal/proxy/proxy_test.go
  internal/rootcoord/meta_table.go
  internal/rootcoord/meta_table_test.go
  internal/types/types.go
  internal/util/paramtable/component_param.go
Labels: area/api, size/XXL, approved, lgtm, ci-passed, dco-passed

#16542 Fix storage type config key
  internal/util/paramtable/component_param.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#16442 Use fmt.Errorf instead of string concat in local_chunk_manager.go
  internal/storage/local_chunk_manager.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#16547 Skip global reduce when there's only one SearchResult
  internal/proxy/task.go
Labels: size/L

#16548 Pass PlaceholderGroup pointer to prevent memory copy
  internal/core/bench/bench_search.cpp
  internal/core/src/query/generated/ExecPlanNodeVisitor.h
  internal/core/src/query/visitors/ExecPlanNodeVisitor.cpp
  internal/core/src/segcore/SegmentInterface.cpp
  internal/core/src/segcore/SegmentInterface.h
  internal/core/src/segcore/segment_c.cpp
  internal/core/unittest/test_query.cpp
  internal/core/unittest/test_sealed.cpp
Labels: size/M

#16402 Remove unnecessary bitset flip in search
  internal/core/src/query/visitors/ExecPlanNodeVisitor.cpp
  internal/core/src/segcore/SegmentSealedImpl.cpp
  internal/core/src/segcore/TimestampIndex.cpp
Labels: size/S

#16403 Add search metrics to perf
  internal/metrics/proxy_metrics.go
  internal/metrics/querynode.go
  internal/proxy/impl.go
  internal/proxy/task.go
  internal/querynode/query_collection.go
Labels: size/L

#16522 [skip e2e]Add chaos test for kafka version milvus
  .github/workflows/pod-kill-chaos-test-kafka-version.yaml
  tests/python_client/chaos/chaos_objects/pod_kill/chaos_kafka_pod_kill.yaml
  tests/python_client/chaos/chaos_objects/pod_kill/testcases.yaml
  tests/python_client/chaos/cluster-values.yaml
Labels: kind/improvement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#16531 [skip e2e]Add chaos test jenkins file for kafka version
  build/ci/jenkins/ChaosTestKafkaMQ.groovy
Labels: kind/improvement, approved, lgtm, ci-passed, dco-passed

#16549 create default root user for authentication (#16545)
  internal/proxy/impl.go
  internal/proxy/proxy_test.go
  internal/proxy/util.go
  internal/proxy/util_test.go
  internal/rootcoord/root_coord.go
  internal/util/constant.go
  internal/util/paramtable/component_param.go
  internal/util/paramtable/component_param_test.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#16512 Make bulk load fully work
  internal/datacoord/meta.go
  internal/datacoord/meta_test.go
  internal/datacoord/server_test.go
  internal/datacoord/services.go
  internal/datanode/data_node.go
  internal/datanode/data_node_test.go
  internal/datanode/flow_graph_dd_node.go
  internal/datanode/mock_test.go
  internal/distributed/datacoord/client/client.go
  internal/distributed/datacoord/client/client_test.go
  internal/distributed/datacoord/service.go
  internal/distributed/datacoord/service_test.go
  internal/distributed/proxy/service_test.go
  internal/proto/data_coord.proto
  internal/proto/datapb/data_coord.pb.go
  internal/proxy/channels_mgr.go
  internal/proxy/data_coord_mock_test.go
  internal/proxy/impl.go
  internal/proxy/proxy_test.go
  internal/rootcoord/import_manager.go
  internal/rootcoord/import_manager_test.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
  internal/types/types.go
  internal/util/importutil/import_wrapper.go
  internal/util/importutil/import_wrapper_test.go
  internal/util/importutil/json_handler.go
  internal/util/importutil/json_handler_test.go
  internal/util/mock/datacoord_client.go
Labels: kind/enhancement, size/XXL, approved, lgtm, ci-passed, dco-passed

#16521 [skip e2e]Add deploy test for kafka version milvus
  .github/workflows/deploy-test.yaml
  tests/python_client/deploy/cluster-values.yaml
Labels: kind/improvement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#16169 Handle flowgraph releasing properly
  internal/datanode/data_node.go
  internal/datanode/data_node_test.go
  internal/datanode/event_manager.go
  internal/datanode/event_manager_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#16496 Disable knowhere logging for embedded Milvus
  Makefile
  cmd/milvus/milvus.go
  internal/core/src/config/CMakeLists.txt
  internal/core/src/config/ConfigKnowhere.cpp
  internal/core/src/indexbuilder/VecIndexCreator.cpp
  internal/proxy/authentication_interceptor.go
  internal/proxy/error.go
  internal/util/etcd/etcd_server.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed, area/compilation

#16529 [skip e2e] Add dependency install script for embedded Milvus
  scripts/install_deps_embd.sh
Labels: kind/improvement, approved, lgtm, ci-passed, dco-passed

#16552 Fix build and tests for Mac M1, also enabled more tests for OSX systems
  Makefile
  scripts/run_go_codecov.sh
  scripts/run_go_unittest.sh
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed, area/compilation

#16553 [skip e2e]Add deploy test jenkins file for kafka version
  build/ci/jenkins/DeployTestKafkaMQ.groovy
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#16554 optimize log & imports
  internal/rootcoord/meta_table.go
  internal/rootcoord/meta_table_test.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
  internal/util/crypto/crypto_test.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#16555 Report bulk load state
  deployments/docker/dev/docker-compose-apple-silicon.yml
  deployments/docker/dev/docker-compose.yml
  internal/datanode/data_node.go
  internal/datanode/data_node_test.go
  internal/datanode/mock_test.go
  internal/rootcoord/import_manager.go
  internal/util/importutil/import_wrapper.go
  internal/util/importutil/import_wrapper_test.go
  internal/util/importutil/json_handler.go
  internal/util/importutil/numpy_parser.go
  internal/util/importutil/numpy_parser_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#16572 Remove debug log in querynode segment/node detector
  internal/querynode/shard_node_detector.go
  internal/querynode/shard_segment_detector.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#16583 Remove debug log with no meaning
  internal/querynode/shard_node_detector.go
  internal/querynode/shard_segment_detector.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#16578 Fix panic: Set Base of GetReplicas request
  internal/core/src/pb/common.pb.cc
  internal/core/src/pb/common.pb.h
  internal/proto/common.proto
  internal/proto/commonpb/common.pb.go
  internal/proxy/impl.go
  internal/proxy/proxy_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#16594 [skip e2e]Update e2e timeout to 2 hours
  build/ci/jenkins/Nightly.groovy
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#16201 Return the local variable directly, make RVO enabled
  internal/core/src/query/visitors/ExecPlanNodeVisitor.cpp
  internal/core/src/segcore/SegmentSealedImpl.cpp
  internal/core/unittest/test_utils/DataGen.h
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#16591 Fix bulkload bug
  internal/datanode/data_node.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#16014 Enable ZSTD compression for pulsar
  internal/mq/msgstream/mq_msgstream.go
  internal/mq/msgstream/mqwrapper/producer.go
  internal/mq/msgstream/mqwrapper/pulsar/pulsar_client.go
  internal/mq/msgstream/mqwrapper/pulsar/pulsar_consumer_test.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#16601 Refine import task related logic
  internal/rootcoord/import_manager.go
  internal/rootcoord/import_manager_test.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#16597 Fix GetReplicas() returns all nodes in ShardReplicas
  internal/querycoord/impl.go
  internal/querycoord/impl_test.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#16520 Support arithmetic operations on numerical fields for scalar filtering
  internal/core/src/pb/plan.pb.cc
  internal/core/src/pb/plan.pb.h
  internal/core/src/query/Expr.h
  internal/core/src/query/ExprImpl.h
  internal/core/src/query/Parser.cpp
  internal/core/src/query/PlanProto.cpp
  internal/core/src/query/PlanProto.h
  internal/core/src/query/generated/ExecExprVisitor.h
  internal/core/src/query/generated/Expr.cpp
  internal/core/src/query/generated/ExprVisitor.h
  internal/core/src/query/generated/ExtractInfoExprVisitor.h
  internal/core/src/query/generated/ShowExprVisitor.h
  internal/core/src/query/generated/VerifyExprVisitor.h
  internal/core/src/query/visitors/ExecExprVisitor.cpp
  internal/core/src/query/visitors/ExtractInfoExprVisitor.cpp
  internal/core/src/query/visitors/ShowExprVisitor.cpp
  internal/core/src/query/visitors/VerifyExprVisitor.cpp
  internal/core/unittest/test_expr.cpp
  internal/core/unittest/test_plan_proto.cpp
  internal/core/unittest/test_utils/DataGen.h
  internal/proto/plan.proto
  internal/proto/planpb/plan.pb.go
  internal/proxy/plan_parser.go
  internal/proxy/plan_parser_test.go
Labels: kind/feature, size/XXL, approved, lgtm, ci-passed, dco-passed

#16616 Always add the shard leader into the nodes list of shard
  internal/querycoord/impl.go
  internal/querycoord/impl_test.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed

#16533 Use AssertInfo instead of assert to ensure compiling
  internal/core/src/common/BitsetView.h
Labels: kind/improvement, approved, lgtm, ci-passed, dco-passed

#16609 Resolve an issue with bulk load with "DataNode abnormal"
  internal/datacoord/cluster.go
  internal/datacoord/segment_manager.go
  internal/datacoord/segment_manager_test.go
  internal/datacoord/server.go
  internal/datacoord/server_test.go
  internal/datacoord/services.go
  internal/datanode/data_node.go
  internal/datanode/data_node_test.go
  internal/datanode/flow_graph_insert_buffer_node.go
  internal/proto/data_coord.proto
  internal/proto/datapb/data_coord.pb.go
  internal/rootcoord/import_manager_test.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
Labels: kind/enhancement, size/XL, approved, lgtm, ci-passed, dco-passed

#16629 Fix an issue where query coord calls MinioChunkManager during init
  internal/querycoord/query_coord.go
  internal/querynode/query_shard_service.go
  internal/storage/minio_chunk_manager.go
  internal/storage/minio_chunk_manager_test.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#16620 Add segment reference count and handles change info in ShardCluster
  internal/querynode/query_channel.go
  internal/querynode/query_channel_test.go
  internal/querynode/query_shard_service.go
  internal/querynode/shard_cluster.go
  internal/querynode/shard_cluster_service.go
  internal/querynode/shard_cluster_service_test.go
  internal/querynode/shard_cluster_test.go
Labels: kind/enhancement, size/XL, approved, lgtm, ci-passed, dco-passed

#16614 [skip e2e]Update config for embedded Milvus
  configs/embedded-milvus.yaml
  configs/milvus.yaml
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#16537 Fix unit test timeout
  internal/querycoord/task_test.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#16514 Improve load performance
  go.mod
  go.sum
  internal/querynode/segment_loader.go
  internal/querynode/segment_loader_test.go
  internal/storage/data_codec.go
  internal/util/concurrency/future.go
  internal/util/concurrency/pool.go
  internal/util/concurrency/pool_test.go
  internal/util/funcutil/parallel.go
Labels: area/dependency, kind/improvement, size/XL, approved, lgtm, ci-passed, dco-passed

#16422 Use fmt.Errorf instead of string concat in querynode/segment.go
  internal/querynode/segment.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#16605 Add list import tasks api
  internal/core/src/pb/milvus.pb.cc
  internal/core/src/pb/milvus.pb.h
  internal/datacoord/mock_test.go
  internal/datanode/data_node.go
  internal/distributed/proxy/service.go
  internal/distributed/proxy/service_test.go
  internal/distributed/rootcoord/client/client.go
  internal/distributed/rootcoord/client/client_test.go
  internal/distributed/rootcoord/service.go
  internal/proto/milvus.proto
  internal/proto/milvuspb/milvus.pb.go
  internal/proto/root_coord.proto
  internal/proto/rootcoordpb/root_coord.pb.go
  internal/proxy/impl.go
  internal/proxy/proxy_test.go
  internal/proxy/rootcoord_mock_test.go
  internal/rootcoord/import_manager.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
  internal/types/types.go
  internal/util/importutil/import_wrapper.go
  internal/util/mock/rootcoord_client.go
  scripts/run_go_unittest.sh
Labels: area/api, size/XXL, approved, lgtm, ci-passed, dco-passed

#16646 Fix proxy unable to update cache
  internal/distributed/querynode/client/client.go
  internal/proxy/task_policies.go
  internal/proxy/task_query.go
  internal/proxy/task_search.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#16590 Change log level in querycoord
  internal/querycoord/channel_unsubscribe.go
  internal/querycoord/cluster.go
  internal/querycoord/global_meta_broker.go
  internal/querycoord/impl.go
  internal/querycoord/index_checker.go
  internal/querycoord/meta.go
  internal/querycoord/query_coord.go
  internal/querycoord/querynode.go
  internal/querycoord/segment_allocator.go
  internal/querycoord/task.go
  internal/querycoord/task_scheduler.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#16649 [test] Add multi memory replicas test cases
  tests/python_client/base/collection_wrapper.py
  tests/python_client/base/partition_wrapper.py
  tests/python_client/requirements.txt
  tests/python_client/testcases/test_collection.py
  tests/python_client/testcases/test_partition.py
  tests/python_client/testcases/test_utility.py
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#16654 Add comments for concurrency package
  internal/querynode/segment_loader.go
  internal/util/concurrency/future.go
  internal/util/concurrency/pool.go
  internal/util/concurrency/pool_test.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#16639 Validate partitionIDs & segmentIDs in search request
  internal/querynode/historical.go
  internal/querynode/historical_test.go
  internal/querynode/query_shard.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#16650 Optimize Mac M1 support and adjust knowhere log setting
  Makefile
  configs/embedded-milvus.yaml
  configs/milvus.yaml
  internal/core/src/config/ConfigKnowhere.cpp
  scripts/install_deps.sh
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed, area/compilation

#16571 Remove the collectionID label from metrics
  internal/metrics/rootcoord_metrics.go
  internal/proxy/task.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/task.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#16653 Remove offline nodes from replica info after LoadBalanceTask done
  internal/querycoord/segment_allocator.go
  internal/querycoord/task.go
  internal/querycoord/task_test.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#16668 [test]Add test case for multi replicase
  tests/python_client/base/utility_wrapper.py
  tests/python_client/chaos/chaos_objects/template/pod-failure-by-pod-list.yaml
  tests/python_client/chaos/test_chaos_multi_replicas.py
  tests/python_client/testcases/test_utility.py
Labels: kind/improvement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#16624 Remove useless log message
  internal/datanode/flow_graph_dmstream_input_node.go
  internal/indexnode/task.go
  internal/querynode/flow_graph_query_node.go
  internal/rootcoord/meta_table.go
  internal/rootcoord/root_coord.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#16672 Add SyncReplicaSegments interface for QueryNode
  internal/distributed/querynode/client/client.go
  internal/distributed/querynode/client/client_test.go
  internal/distributed/querynode/service.go
  internal/distributed/querynode/service_test.go
  internal/proto/query_coord.proto
  internal/proto/querypb/query_coord.pb.go
  internal/proxy/query_node_mock_test.go
  internal/querycoord/mock_querynode_client_test.go
  internal/querynode/impl.go
  internal/querynode/impl_test.go
  internal/querynode/shard_cluster.go
  internal/querynode/shard_cluster_service.go
  internal/querynode/shard_cluster_service_test.go
  internal/querynode/shard_cluster_test.go
  internal/types/types.go
  internal/util/mock/querynode_client.go
Labels: kind/enhancement, size/XL, approved, lgtm, ci-passed, area/internal-api, dco-passed

#16679 Fix timestamp bitset init, fix perf ut
  internal/core/src/segcore/TimestampIndex.cpp
Labels: size/XS, approved, lgtm

#16669 Search partitions concurrently in historical and skip search when no segment
  internal/querynode/historical.go
  internal/querynode/query_collection.go
  internal/querynode/query_node_test.go
Labels: size/M, approved, lgtm, ci-passed

#16677 Filter out the unavailable shard leaders
  internal/querycoord/impl.go
  internal/querycoord/impl_test.go
  internal/querycoord/meta.go
  internal/querycoord/querynode_test.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#16663 Add ut for task_policies
  internal/proxy/task_policies.go
  internal/proxy/task_policies_test.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#16490 Correct wrong words
  internal/distributed/rootcoord/client/client.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#16681 [test] Update load multi replicas cases
  tests/python_client/testcases/test_collection.py
  tests/python_client/testcases/test_partition.py
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#16689 Fix Datacoord ut when etcd is slow
  internal/datacoord/channel_manager_test.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#16688 Disable the unit test for the case of filter out unavailable leaders of GetShardLeaders
  internal/querycoord/impl_test.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#16687 Simplify monitoring metrics
  internal/datacoord/server.go
  internal/datanode/data_node.go
  internal/datanode/flow_graph_insert_buffer_node.go
  internal/datanode/flush_manager.go
  internal/indexnode/task.go
  internal/metrics/datacoord_metrics.go
  internal/metrics/datanode_metrics.go
  internal/metrics/indexcoord_metrics.go
  internal/metrics/indexnode_metrics.go
  internal/metrics/metrics.go
  internal/metrics/proxy_metrics.go
  internal/metrics/querycoord_metrics.go
  internal/metrics/querynode_metrics.go
  internal/metrics/rootcoord_metrics.go
  internal/proxy/channels_mgr.go
  internal/proxy/impl.go
  internal/proxy/proxy.go
  internal/proxy/task.go
  internal/querynode/query_collection.go
  internal/querynode/query_collection_test.go
  internal/rootcoord/proxy_manager.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/timeticksync.go
Labels: kind/improvement, size/XXL, approved, lgtm, ci-passed, dco-passed

#16697 Validate the number of replicas for load collection/partitions request
  internal/querycoord/impl.go
  internal/querycoord/impl_test.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#16694 Using a temporary dir instead of a specified dir within embed etcd test
  internal/kv/etcd/embed_etcd_kv_test.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#16665 Fix Compaction Entity Expire not follow time travel retention time
  configs/milvus.yaml
  internal/datanode/compactor.go
  internal/datanode/compactor_test.go
  internal/util/paramtable/component_param.go
  internal/util/paramtable/component_param_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#16685 Sync the distribution of segments to shard leaders
  internal/querycoord/cluster.go
  internal/querycoord/mock_querynode_server_test.go
  internal/querycoord/querynode.go
  internal/querycoord/task.go
  internal/querycoord/util.go
  internal/util/typeutil/set.go
  internal/util/typeutil/set_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#16709 [test]Modify the search testcase
  tests/python_client/testcases/test_search_20.py
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#16693 Refine log in query_shard.go
  internal/querynode/query_shard.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#16690 Refine list import task api
  internal/core/src/pb/milvus.pb.cc
  internal/core/src/pb/milvus.pb.h
  internal/proto/milvus.proto
  internal/proto/milvuspb/milvus.pb.go
  internal/proxy/rootcoord_mock_test.go
  internal/rootcoord/import_manager.go
  internal/rootcoord/import_manager_test.go
  internal/util/importutil/import_wrapper.go
  internal/util/importutil/json_handler.go
Labels: area/api, size/XXL, approved, lgtm, ci-passed, dco-passed

#16692 Remove DataKV interface
  internal/kv/kv.go
  internal/kv/mem/mem_kv.go
  internal/kv/mem/mem_kv_test.go
  internal/querycoord/cluster_test.go
  internal/querynode/segment_loader.go
  internal/storage/utils.go
  internal/storage/utils_test.go
  scripts/run_go_unittest.sh
Labels: size/XL, approved, lgtm, ci-passed, dco-passed

#16720 Enable and modify test cases after code fix
  tests/python_client/requirements.txt
  tests/python_client/testcases/test_connection.py
  tests/python_client/testcases/test_utility.py
Labels: kind/improvement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#16710 [skip e2e]Add tasks to check compatibility
  tests/python_client/deploy/scripts/action_after_upgrade.py
  tests/python_client/deploy/scripts/action_before_upgrade.py
  tests/python_client/deploy/scripts/utils.py
Labels: kind/improvement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#16676 Add Milvus Log to issue template
  .github/ISSUE_TEMPLATE/bug_report.yaml
Labels: size/XS, dco-passed

#16703 Lock meta-replica during search/query
  internal/querynode/query_shard.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#16719 Fix miss segments/DmChannel when query by nodeID
  internal/proto/query_coord.proto
  internal/proto/querypb/query_coord.pb.go
  internal/querycoord/cluster.go
  internal/querycoord/cluster_test.go
  internal/querycoord/meta.go
  internal/querycoord/meta_test.go
  internal/querycoord/mock_querynode_server_test.go
  internal/querynode/collection_replica.go
  internal/querynode/shard_cluster_test.go
  internal/querynode/shard_segment_detector_test.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, area/internal-api, dco-passed

#16387 Implements remaining rest APIs
  configs/milvus.yaml
  internal/distributed/proxy/httpserver/handler.go
  internal/distributed/proxy/httpserver/handler_test.go
  internal/distributed/proxy/service.go
  internal/util/paramtable/http_param.go
  internal/util/paramtable/http_param_test.go
Labels: size/XL, approved, lgtm, ci-passed, dco-passed

#16734 Fix LoadBalance loads the same segment multiple times
  internal/querycoord/task.go
  internal/querycoord/task_scheduler.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#16714 Fix bug: wrong metrics name and forget to register metrics
  internal/datacoord/meta.go
  internal/metrics/datacoord_metrics.go
  internal/metrics/rootcoord_metrics.go
  internal/proxy/impl.go
  internal/querynode/historical.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#16712 Add unit test for case of failed to sync segments to shard leader
  internal/querycoord/impl_test.go
  internal/querycoord/mock_querynode_server_test.go
  internal/querycoord/task_test.go
  internal/querycoord/util.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#16736 Benchmark go/cgo parquet payload readers
  internal/storage/payload_benchmark_test.go
  internal/storage/payload_cgo_test.go
  internal/storage/payload_reader_cgo.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#16739 Use a singleton kafka producer
  internal/mq/msgstream/mqwrapper/kafka/kafka_client.go
  internal/mq/msgstream/mqwrapper/kafka/kafka_producer.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#16718 Enable dimension check in Proxy when create index request received
  internal/proxy/mock_cache_test.go
  internal/proxy/task.go
  internal/proxy/task_test.go
  internal/util/indexparamcheck/conf_adapter.go
  internal/util/indexparamcheck/conf_adapter_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed
