Repository milvus-io/milvus, pull requests merged in 2023-11, with the labels that each got.

#28017 refine stop order
  cmd/roles/roles.go
  internal/distributed/rootcoord/service.go
  scripts/stop_graceful.sh
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#27952 Delete by complex expression use partitionKey optimization
  internal/proxy/task_delete.go
  internal/proxy/task_delete_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#27931 fix azure ListObjects
  .github/workflows/mac.yaml
  internal/proxy/task_search_test.go
  internal/storage/azure_object_storage.go
  internal/storage/azure_object_storage_test.go
  internal/storage/minio_object_storage.go
  internal/storage/minio_object_storage_test.go
  internal/storage/remote_chunk_manager.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#28016 refine stop order
  cmd/roles/roles.go
  internal/distributed/rootcoord/service.go
  scripts/stop_graceful.sh
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#27901 add a custom http header: Accept-Type-Allow-Int64
  internal/core/src/storage/MinioChunkManager.cpp
  internal/distributed/proxy/httpserver/constant.go
  internal/distributed/proxy/httpserver/handler_v1.go
  internal/distributed/proxy/httpserver/handler_v1_test.go
  internal/distributed/proxy/httpserver/utils.go
  internal/distributed/proxy/httpserver/utils_test.go
  internal/distributed/proxy/service.go
  pkg/util/paramtable/http_param.go
  pkg/util/paramtable/http_param_test.go
Labels: size/XXL, approved, lgtm, ci-passed, dco-passed

#27992 avoid sleep to ctx done during retry
  pkg/util/retry/retry.go
  pkg/util/retry/retry_test.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#28042 Update milvs helm repo for ci
  .github/workflows/deploy-test.yaml
  .github/workflows/io-latency-chaos-test.yaml
  .github/workflows/mem-stress-chaos-test.yaml
  .github/workflows/network-latency-chaos-test.yaml
  .github/workflows/network-partition-chaos-test.yaml
  .github/workflows/pod-failure-chaos-test.yaml
  .github/workflows/pod-kill-chaos-test-kafka-version.yaml
  .github/workflows/pod-kill-chaos-test.yaml
  build/ci/jenkins/ChaosTest.groovy
  build/ci/jenkins/ChaosTestKafkaMQ.groovy
  build/ci/jenkins/DeployTest.groovy
  build/ci/jenkins/DeployTestKafkaMQ.groovy
  ci/jenkins/PR.groovy
  ci/jenkins/PRGPU.groovy
  deployments/offline/README.md
  tests/python_client/chaos/scripts/install_milvus.sh
  tests/python_client/standby/scripts/install_milvus.sh
  tests/scripts/install_milvus.sh
Labels: kind/improvement, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#27990 Bulkinsert support pure list json
  internal/util/importutil/json_parser.go
  internal/util/importutil/json_parser_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#28073 Refine offline segments logic in shard delegator
  internal/querynodev2/delegator/delegator.go
  internal/querynodev2/delegator/delegator_data.go
  internal/querynodev2/delegator/delegator_test.go
  internal/querynodev2/delegator/distribution.go
  internal/querynodev2/delegator/distribution_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#28071 Revert "Remove Properties in rocksmq"
  internal/mq/mqimpl/rocksmq/server/rocksmq_impl.go
Labels: size/XS, approved, dco-passed

#28062 fix precision for segcore reduce(#27325)
  internal/core/src/segcore/ReduceStructure.h
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#28074 [2.3] Change task sourceID to stringer interface (#27965)
  internal/querycoordv2/balance/utils.go
  internal/querycoordv2/checkers/balance_checker.go
  internal/querycoordv2/checkers/channel_checker.go
  internal/querycoordv2/checkers/checker.go
  internal/querycoordv2/checkers/controller.go
  internal/querycoordv2/checkers/index_checker.go
  internal/querycoordv2/checkers/segment_checker.go
  internal/querycoordv2/handlers.go
  internal/querycoordv2/task/executor.go
  internal/querycoordv2/task/merger_test.go
  internal/querycoordv2/task/scheduler.go
  internal/querycoordv2/task/task.go
  internal/querycoordv2/task/task_test.go
  internal/querycoordv2/task/utils.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#28075 [2.3] Add ctx parameter for tsafe pkg & NewDelegator method (#27877)
  internal/querynodev2/delegator/delegator.go
  internal/querynodev2/delegator/delegator_data_test.go
  internal/querynodev2/delegator/delegator_test.go
  internal/querynodev2/pipeline/delete_node_test.go
  internal/querynodev2/pipeline/manager_test.go
  internal/querynodev2/pipeline/pipeline_test.go
  internal/querynodev2/services.go
  internal/querynodev2/tsafe/manager.go
  internal/querynodev2/tsafe/tsafe_test.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#28084 [2.3] Refine offline segments logic in shard delegator (#28073)
  internal/querynodev2/delegator/delegator.go
  internal/querynodev2/delegator/delegator_data.go
  internal/querynodev2/delegator/delegator_test.go
  internal/querynodev2/delegator/distribution.go
  internal/querynodev2/delegator/distribution_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#28083 Fix unstable cpp ut
  internal/core/src/storage/ChunkCache.cpp
  internal/core/src/storage/ChunkCache.h
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#28089 [cherry-pick]refine stop order (#28016)
  cmd/roles/roles.go
  internal/distributed/rootcoord/service.go
  scripts/stop_graceful.sh
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#28092 [cherry-pick]avoid sleep to ctx done during retry (#27992)
  pkg/util/retry/retry.go
  pkg/util/retry/retry_test.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed

#28090 [cherry-pick]remove binlog/delta log from getRecoveryInfoV2 (#27895)
  internal/datacoord/services.go
  internal/datacoord/services_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#28066 update pymilvus version and some cases
  tests/python_client/requirements.txt
  tests/python_client/testcases/test_delete.py
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#28101 Fix unstable search task ut
  internal/proxy/task_search_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#28055 Refactor collection's cgo call
  internal/core/src/segcore/Collection.cpp
  internal/core/src/segcore/Collection.h
  internal/core/src/segcore/collection_c.cpp
  internal/core/src/segcore/collection_c.h
  internal/core/unittest/test_c_api.cpp
  internal/core/unittest/test_float16.cpp
  internal/core/unittest/test_utils/DataGen.h
  internal/querynodev2/segments/collection.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#27960 [cherry-pick] Fix duplicated segment id in bulkinsert task state
  internal/rootcoord/import_manager.go
  internal/rootcoord/import_manager_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#28061 fix fromShardLeader typo
  internal/querynodev2/handlers.go
  internal/querynodev2/services.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#28098 [For Milvus 2.2.15] update knowhere verison to 1.3.19
  internal/core/thirdparty/knowhere/CMakeLists.txt
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed, area/compilation, kind/branch-feature

#28117 Set qcv2 index task priority to Low
  internal/querycoordv2/checkers/index_checker.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#26901 Support collection-level mmap control
  internal/core/src/common/LoadInfo.h
  internal/core/src/segcore/SegmentSealedImpl.cpp
  internal/core/src/segcore/Types.h
  internal/core/src/segcore/load_field_data_c.cpp
  internal/core/src/segcore/load_field_data_c.h
  internal/core/src/segcore/load_index_c.cpp
  internal/core/src/segcore/load_index_c.h
  internal/core/unittest/test_c_api.cpp
  internal/core/unittest/test_sealed.cpp
  internal/core/unittest/test_utils/storage_test_utils.h
  internal/querycoordv2/job/job_test.go
  internal/querycoordv2/job/utils.go
  internal/querycoordv2/meta/collection_manager.go
  internal/querycoordv2/meta/collection_manager_test.go
  internal/querycoordv2/meta/coordinator_broker.go
  internal/querycoordv2/meta/coordinator_broker_test.go
  internal/querycoordv2/meta/mock_broker.go
  internal/querycoordv2/observers/leader_observer.go
  internal/querycoordv2/observers/leader_observer_test.go
  internal/querycoordv2/server_test.go
  internal/querycoordv2/services_test.go
  internal/querycoordv2/task/executor.go
  internal/querycoordv2/task/task_test.go
  internal/querycoordv2/task/utils.go
  internal/querycoordv2/task/utils_test.go
  internal/querynodev2/segments/collection.go
  internal/querynodev2/segments/load_field_data_info.go
  internal/querynodev2/segments/load_index_info.go
  internal/querynodev2/segments/reduce_test.go
  internal/querynodev2/segments/retrieve_test.go
  internal/querynodev2/segments/search_test.go
  internal/querynodev2/segments/segment.go
  internal/querynodev2/segments/segment_loader.go
  internal/querynodev2/segments/segment_loader_test.go
  internal/querynodev2/segments/segment_test.go
  internal/querynodev2/services.go
  pkg/common/common.go
Labels: kind/feature, size/XL, approved, lgtm, ci-passed, dco-passed

#28120 Fix unstable search task ut (#28101)
  internal/proxy/task_search_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#28134 [2.3] Set qcv2 index task priority to Low (#28117)
  internal/querycoordv2/checkers/index_checker.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#28093 Implement `Injection` for SyncManager with block and meta transition
  internal/datanode/metacache/actions.go
  internal/datanode/metacache/actions_test.go
  internal/datanode/metacache/segment.go
  internal/datanode/syncmgr/sync_manager.go
  internal/datanode/syncmgr/sync_manager_test.go
  internal/datanode/syncmgr/task.go
  internal/datanode/syncmgr/task_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#28047 fix load index for stopping node
  internal/querycoordv2/checkers/controller.go
  internal/querycoordv2/checkers/index_checker.go
  internal/querycoordv2/checkers/index_checker_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#28091 [cherry-pick]remove retry in getShards (#28011)
  internal/proxy/meta_cache.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed

#28079 fix retry on offline node
  Makefile
  internal/querynodev2/delegator/delegator_data.go
  internal/querynodev2/delegator/delegator_data_test.go
  internal/util/grpcclient/client.go
  internal/util/grpcclient/client_test.go
  internal/util/sessionutil/mock_session.go
  internal/util/sessionutil/session.go
Labels: kind/bug, size/XL, approved, lgtm, ci-passed, dco-passed, area/compilation

#27792 Add write cache for access log
  internal/proxy/accesslog/access_log.go
  internal/proxy/accesslog/log_writer.go
  pkg/util/paramtable/component_param.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#28080 Use go 1.20 csv_reader to keep milvus go=1.18 limitation
  internal/util/importutil/csv_parser.go
  internal/util/importutil/csv_reader.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#28140 [skip e2e] Change storageType to the default minio
  configs/milvus.yaml
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#28033 Fix the unstable resource manager testcase
  internal/proxy/authentication_interceptor.go
  pkg/util/resource/resource_manager_test.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#28137 [cherry-pick]fix load index for stopping node (#28047)
  internal/querycoordv2/checkers/controller.go
  internal/querycoordv2/checkers/index_checker.go
  internal/querycoordv2/checkers/index_checker_test.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#28102 Add dockerignore for building milvus image
  .dockerignore
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#28141 Fix flushManager.isFull is too slow
  internal/datanode/channel_meta.go
  internal/datanode/data_sync_service_test.go
  internal/datanode/flush_manager.go
  internal/datanode/flush_manager_test.go
  internal/datanode/flush_task_counter.go
  internal/datanode/flush_task_counter_test.go
  internal/datanode/services.go
Labels: kind/bug, kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#28151 [cherry-pick]Add dockerignore for building milvus image
  .dockerignore
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#28113 Fix delete records timestamp may be reordered (#27941)
  internal/core/src/segcore/SegmentGrowingImpl.cpp
  internal/core/src/segcore/SegmentSealedImpl.cpp
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#28139 [cherry-pick]fix retry on offline node (#28079)
  Makefile
  internal/querynodev2/delegator/delegator_data.go
  internal/querynodev2/delegator/delegator_data_test.go
  internal/util/grpcclient/client.go
  internal/util/grpcclient/client_test.go
  internal/util/sessionutil/mock_session.go
  internal/util/sessionutil/session.go
Labels: size/XL, approved, lgtm, ci-passed, dco-passed, area/compilation

#28126 [cherry-pick] Bulkinsert support pure list json
  internal/util/importutil/json_parser.go
  internal/util/importutil/json_parser_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#28127 [cherry-pick] Bulkinsert support pure list json
  internal/util/importutil/json_parser.go
  internal/util/importutil/json_parser_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#28148 Fix flushManager.isFull is too slow (#28141)
  internal/datanode/channel_meta.go
  internal/datanode/flow_graph_insert_buffer_node_test.go
  internal/datanode/flush_manager.go
  internal/datanode/flush_manager_test.go
  internal/datanode/flush_task_counter.go
  internal/datanode/flush_task_counter_test.go
Labels: kind/bug, kind/improvement, size/L, approved, lgtm, ci-passed

#28155 [skip e2e]modify nightly script for 2.3 branch
  ci/jenkins/Nightly.groovy
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed, do-not-merge/missing-related-pr

#28114 Fix QueryNode panic while upgrading (#28034)
  internal/core/src/segcore/FieldIndexing.h
  internal/querynodev2/services.go
  internal/querynodev2/services_test.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#28130 fix sync distribution with wrong version
  internal/querycoordv2/observers/collection_observer_test.go
  internal/querycoordv2/observers/leader_observer.go
  internal/querycoordv2/observers/leader_observer_test.go
  internal/querycoordv2/server.go
  internal/querynodev2/services.go
  internal/querynodev2/services_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#28149 Fix flushManager.isFull is too slow (#28141)
  internal/datanode/channel_meta.go
  internal/datanode/flow_graph_insert_buffer_node_test.go
  internal/datanode/flush_manager.go
  internal/datanode/flush_manager_test.go
  internal/datanode/flush_task_counter.go
  internal/datanode/flush_task_counter_test.go
Labels: kind/bug, kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#28088 [2.2]skip load segment if already loaded
  internal/querynode/impl.go
  internal/querynode/impl_test.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed, kind/branch-feature

#28169 fix grpc client retry on node server not match error
  internal/util/grpcclient/client.go
  internal/util/grpcclient/client_test.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#28164 Use `IVFFLAT_CC` instead of `IVFFLAT` for sealed segment tmp index
  internal/core/src/segcore/IndexConfigGenerator.h
Labels: kind/bug, priority/critical-urgent, size/XS, approved, lgtm, ci-passed, dco-passed

#28121 Use merr to prevent datanode panic
  internal/datanode/channel_meta.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#28122 Use merr to prevent datanode panic (#28121)
  internal/datanode/channel_meta.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#28110 Check length before comparing strings
  internal/core/src/common/Utils.h
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#28111 [Pick]Check length before comparing strings
  internal/core/src/common/Utils.h
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#28112 [Pick] Check length before comparing strings
  internal/core/src/common/Utils.h
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#28154 Increase the ChunkManager request timeout (#28015)
  configs/milvus.yaml
  internal/core/src/common/Consts.h
  internal/core/src/storage/ThreadPool.cpp
  internal/core/src/storage/ThreadPool.h
  internal/core/src/storage/ThreadPools.cpp
  pkg/util/paramtable/base_table.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#27874 Add `WriteBuffer` to provided absbraction for delta policy
  Makefile
  internal/datanode/metacache/actions.go
  internal/datanode/metacache/actions_test.go
  internal/datanode/metacache/meta_cache.go
  internal/datanode/metacache/meta_cache_test.go
  internal/datanode/metacache/mock_meta_cache.go
  internal/datanode/metacache/segment.go
  internal/datanode/syncmgr/meta_writer.go
  internal/datanode/syncmgr/mock_sync_manager.go
  internal/datanode/syncmgr/options.go
  internal/datanode/syncmgr/task.go
  internal/datanode/syncmgr/task_test.go
  internal/datanode/writebuffer/bf_write_buffer.go
  internal/datanode/writebuffer/bf_write_buffer_test.go
  internal/datanode/writebuffer/delta_buffer.go
  internal/datanode/writebuffer/delta_buffer_test.go
  internal/datanode/writebuffer/insert_buffer.go
  internal/datanode/writebuffer/insert_buffer_test.go
  internal/datanode/writebuffer/l0_write_buffer.go
  internal/datanode/writebuffer/l0_write_buffer_test.go
  internal/datanode/writebuffer/manager.go
  internal/datanode/writebuffer/manager_test.go
  internal/datanode/writebuffer/mock_write_buffer.go
  internal/datanode/writebuffer/options.go
  internal/datanode/writebuffer/segment_buffer.go
  internal/datanode/writebuffer/sync_policy.go
  internal/datanode/writebuffer/sync_policy_test.go
  internal/datanode/writebuffer/write_buffer.go
  internal/datanode/writebuffer/write_buffer_test.go
  pkg/util/merr/utils.go
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/XXL, approved, lgtm, ci-passed, dco-passed, area/compilation

#28109 [Pick] Refine code for fixed-length types array
  internal/core/src/common/Array.h
Labels: size/S, approved, lgtm, ci-passed, dco-passed

#28146 Fix getting incorrect CPU num
  .golangci.yml
  internal/datacoord/compaction.go
  internal/datanode/io_pool.go
  internal/indexnode/task.go
  internal/mq/mqimpl/rocksmq/server/rocksmq_impl.go
  internal/querycoordv2/task/scheduler.go
  internal/querynodev2/segments/pool.go
  internal/querynodev2/segments/segment_loader.go
  pkg/util/cgoconverter/bytes_converter_test.go
  pkg/util/compressor/compressor_test.go
  pkg/util/conc/pool.go
  pkg/util/funcutil/parallel_test.go
  pkg/util/hardware/hardware_info.go
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/component_param_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#28167 update test cases for new growing segment index
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#28124 Upsert compatible with 2.3.3 status log
  internal/datanode/channel_meta.go
  internal/querynode/segment_loader.go
  internal/storage/types.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed, kind/branch-feature

#28115 Limit max thread num for pool (#28018)
  internal/core/src/storage/ThreadPool.h
  internal/querynodev2/segments/segment_loader.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#28170 fix sync distribution with wrong version (#28130)
  internal/querycoordv2/observers/collection_observer_test.go
  internal/querycoordv2/observers/leader_observer.go
  internal/querycoordv2/observers/leader_observer_test.go
  internal/querycoordv2/server.go
  internal/querynodev2/services.go
  internal/querynodev2/services_test.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#28163 [Fixup] error root path for catalog when using tikv
  internal/datacoord/server.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#28187 Update README.md
  README.md
Labels: size/XS, ci-passed, do-not-merge/missing-related-issue, dco-passed

#28021 Adjust datacoord for L0 Delta
  internal/datacoord/meta.go
  internal/datacoord/meta_test.go
  internal/datacoord/segment_allocation_policy.go
  internal/datacoord/segment_allocation_policy_test.go
  internal/datacoord/segment_manager.go
  internal/datacoord/segment_manager_test.go
  internal/datacoord/server_test.go
  internal/datacoord/services.go
  internal/datacoord/util.go
  internal/metastore/kv/datacoord/kv_catalog.go
  internal/metastore/kv/datacoord/util.go
  internal/proto/data_coord.proto
  internal/proto/datapb/data_coord.pb.go
Labels: size/XXL, approved, lgtm, ci-passed, area/internal-api, dco-passed

#28125 [cherry-pick]add a custom http header: Accept-Type-Allow-Int64
  internal/core/src/storage/MinioChunkManager.cpp
  internal/distributed/proxy/httpserver/constant.go
  internal/distributed/proxy/httpserver/handler_v1.go
  internal/distributed/proxy/httpserver/handler_v1_test.go
  internal/distributed/proxy/httpserver/utils.go
  internal/distributed/proxy/httpserver/utils_test.go
  internal/distributed/proxy/service.go
  pkg/util/paramtable/http_param.go
  pkg/util/paramtable/http_param_test.go
Labels: kind/bug, size/XXL, approved, lgtm, ci-passed, dco-passed, do-not-merge/missing-related-pr

#28194 Fix mac code check
  .github/workflows/mac.yaml
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#28195 Fix mac code check (#28194)
  .github/workflows/mac.yaml
Labels: kind/improvement, size/XS, approved, lgtm, dco-passed

#28198 update pymilvus version for 2.2 branch
  tests/python_client/requirements.txt
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed, do-not-merge/missing-related-pr

#28184 Fix coordinator fast restart
  configs/milvus.yaml
  internal/util/sessionutil/session_util.go
  pkg/util/paramtable/component_param.go
Labels: size/M, approved, dco-passed

#28202 [2.2]fix panic during close delte flow graph
  internal/querynode/data_sync_service.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass, kind/branch-feature

#27761 Update session manager
  internal/datacoord/session_manager.go
  internal/datacoord/session_manager_test.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#28157 reduce useless ObjectExists
  internal/core/src/storage/AzureChunkManager.cpp
  internal/core/src/storage/AzureChunkManager.h
  internal/core/src/storage/MinioChunkManager.cpp
  internal/core/src/storage/MinioChunkManager.h
  internal/core/src/storage/azure-blob-storage/AzureBlobChunkManager.cpp
  internal/core/src/storage/azure-blob-storage/AzureBlobChunkManager.h
  internal/core/src/storage/azure-blob-storage/CMakeLists.txt
  internal/core/src/storage/azure-blob-storage/test/CMakeLists.txt
  internal/core/src/storage/azure-blob-storage/test/test_azure_blob_chunk_manager.cpp
  internal/core/unittest/test_azure_chunk_manager.cpp
  scripts/azure_build.sh
  scripts/core_build.sh
Labels: kind/improvement, size/XL, approved, lgtm, ci-passed, dco-passed, area/compilation, manual-pass, do-not-merge/missing-related-pr

#28177 fix grpc client retry on node server not match error (#28169)
  internal/util/grpcclient/client.go
  internal/util/grpcclient/client_test.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#27722 Deliver L0 segments delete records
  internal/proto/query_coord.proto
  internal/proto/querypb/query_coord.pb.go
  internal/querycoordv2/task/executor.go
  internal/querynodev2/delegator/delegator_data.go
  internal/querynodev2/delegator/delegator_data_test.go
  internal/querynodev2/delegator/delegator_test.go
  internal/querynodev2/handlers.go
  internal/querynodev2/segments/manager.go
  internal/querynodev2/segments/manager_test.go
  internal/querynodev2/segments/mock_data.go
  internal/querynodev2/segments/mock_loader.go
  internal/querynodev2/segments/mock_segment.go
  internal/querynodev2/segments/mock_segment_manager.go
  internal/querynodev2/segments/reduce_test.go
  internal/querynodev2/segments/retrieve_test.go
  internal/querynodev2/segments/search_test.go
  internal/querynodev2/segments/segment.go
  internal/querynodev2/segments/segment_interface.go
  internal/querynodev2/segments/segment_l0.go
  internal/querynodev2/segments/segment_loader.go
  internal/querynodev2/segments/segment_test.go
  internal/querynodev2/segments/utils.go
  internal/querynodev2/server_test.go
  internal/querynodev2/services.go
  internal/querynodev2/services_test.go
  internal/storage/data_codec.go
  internal/storage/data_codec_test.go
Labels: kind/feature, size/XXL, approved, lgtm, ci-passed, area/internal-api, dco-passed

#27938 Add scheduler
  internal/datacoord/compaction.go
  internal/datacoord/compaction_test.go
  internal/datacoord/compaction_trigger_test.go
Labels: size/XL, approved, lgtm, ci-passed, dco-passed

#28205 Fix coordinator fast restart
  configs/milvus.yaml
  internal/util/sessionutil/session_util.go
  pkg/util/paramtable/component_param.go
Labels: size/M, approved, dco-passed, do-not-merge/missing-related-pr

#28199 Add compaction meta in `SyncSegmentsRequest`
  internal/datacoord/compaction.go
  internal/datanode/services.go
  internal/datanode/services_test.go
  internal/proto/data_coord.proto
  internal/proto/datapb/data_coord.pb.go
Labels: kind/improvement, size/XL, approved, lgtm, ci-passed, dco-passed

#28197 update pymilvus version and add cases of array exists
  tests/python_client/common/common_func.py
  tests/python_client/requirements.txt
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#28178 Fix getting incorrect CPU num (#28146)
  .golangci.yml
  internal/datacoord/compaction.go
  internal/datanode/io_pool.go
  internal/indexnode/task.go
  internal/mq/mqimpl/rocksmq/server/rocksmq_impl.go
  internal/querycoordv2/task/scheduler.go
  internal/querynodev2/segments/pool.go
  internal/querynodev2/segments/segment_loader.go
  pkg/util/cgoconverter/bytes_converter_test.go
  pkg/util/compressor/compressor_test.go
  pkg/util/conc/pool.go
  pkg/util/funcutil/parallel_test.go
  pkg/util/hardware/hardware_info.go
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/component_param_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#28182 fix check grpc error logic
  internal/util/grpcclient/client.go
  internal/util/grpcclient/client_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#28191 disable auto balance when old node exists
  Makefile
  configs/milvus.yaml
  internal/datacoord/channel_manager.go
  internal/datacoord/channel_manager_test.go
  internal/datacoord/index_service.go
  internal/datacoord/metrics_info.go
  internal/datacoord/mock_channel_store.go
  internal/datacoord/server.go
  internal/datacoord/server_test.go
  internal/datacoord/services.go
  internal/querycoordv2/handlers.go
  internal/querycoordv2/server.go
  internal/querycoordv2/server_test.go
  internal/util/sessionutil/mock_session.go
  internal/util/sessionutil/session.go
  internal/util/sessionutil/session_util.go
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/component_param_test.go
Labels: kind/improvement, size/XL, approved, lgtm, ci-passed, dco-passed, area/compilation

#28218 [cherry-pick]fix check grpc error logic (#28182)
  internal/util/grpcclient/client.go
  internal/util/grpcclient/client_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#28192 Fix bulkinsert bug that segments are compacted after import
  internal/datanode/services.go
  internal/util/importutil/csv_parser.go
  internal/util/importutil/import_wrapper.go
  internal/util/importutil/import_wrapper_test.go
  internal/util/importutil/json_parser.go
  internal/util/importutil/numpy_adapter.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#28200 [cherry-pick] Fix bulkinsert bug that segments are compacted after import
  internal/datanode/data_node.go
  internal/util/importutil/import_wrapper.go
  internal/util/importutil/import_wrapper_test.go
  internal/util/importutil/json_parser.go
  internal/util/importutil/numpy_adapter.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#28216 Fix atomic.Int64 not found in go 1.18
  internal/datanode/syncmgr/sync_manager_test.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#28245 [skip e2e]Mark a case as xfail
  tests/python_client/testcases/test_bulk_insert.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#28248 [skip e2e][cherry-pick]Mark a case as xfail
  tests/python_client/testcases/test_bulk_insert.py
Labels: kind/improvement, sig/testing, size/XS, area/test, ci-passed, dco-passed, do-not-merge/missing-related-pr

#28119 Get vector concurrently (#27838)
  internal/core/src/segcore/SegmentSealedImpl.cpp
  internal/core/src/storage/ChunkCache.cpp
  internal/core/unittest/test_chunk_cache.cpp
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#28236 Change default storage type to minio
  pkg/util/paramtable/component_param.go
Labels: kind/improvement, size/XS, approved, lgtm, dco-passed

#28244 [2.2.0]: Delay the cancellation of ctx when stopping the node
  internal/datanode/data_node.go
  internal/querynode/query_node.go
  internal/querynode/task_scheduler.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#28226 [2.2]Add timeout for graceful stop (#27326)
  internal/distributed/datacoord/service.go
  internal/distributed/datanode/service.go
  internal/distributed/indexnode/service.go
  internal/distributed/proxy/service.go
  internal/distributed/querycoord/service.go
  internal/distributed/querynode/service.go
  internal/distributed/rootcoord/service.go
  internal/distributed/utils/util.go
  internal/distributed/utils/util_test.go
  internal/util/paramtable/grpc_param.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#28243 [2.2]Fix datanode panic during save binlog path
  internal/datanode/flush_manager.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed, kind/branch-feature

#28220 Fix bug for setting index state when indexnode connecting failed
  internal/datacoord/index_builder.go
  internal/datacoord/index_builder_test.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#28221 Fix bug for setting index state when indexnode connecting failed
  internal/datacoord/index_builder.go
  internal/datacoord/index_builder_test.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#28186 Fix bug for constructing ArrayView with fixed-length type
  internal/core/src/common/Array.h
  internal/core/unittest/test_array.cpp
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#28185 Fix bug for constructing ArrayView with fixed-length type
  internal/core/src/common/Array.h
  internal/core/unittest/test_array.cpp
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#28249 [2.3]: Delay the cancellation of ctx when stopping the node
  internal/datanode/data_node.go
  internal/querynodev2/server.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#28223 Fix proxy not healthy before graceful stop
  internal/distributed/proxy/service.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#28255 [cherry-pick]Fix proxy not healthy before graceful stop
  internal/distributed/proxy/service.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#28247 Delay the cancellation of ctx when stopping the node
  internal/datanode/data_node.go
  internal/querynodev2/server.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#28224 [cherry-pick]Disable auto balance when old node exists (#28191)
  Makefile
  configs/milvus.yaml
  internal/datacoord/channel_manager.go
  internal/datacoord/channel_manager_test.go
  internal/datacoord/index_service.go
  internal/datacoord/metrics_info.go
  internal/datacoord/mock_channel_store.go
  internal/datacoord/server.go
  internal/datacoord/server_test.go
  internal/datacoord/services.go
  internal/querycoordv2/handlers.go
  internal/querycoordv2/server.go
  internal/querycoordv2/server_test.go
  internal/util/sessionutil/mock_session.go
  internal/util/sessionutil/session.go
  internal/util/sessionutil/session_util.go
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/component_param_test.go
Labels: size/XL, approved, lgtm, ci-passed, dco-passed, area/compilation

#28252 [2.3] Set Knowhere version to v2.2.2
  internal/core/thirdparty/knowhere/CMakeLists.txt
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed, area/compilation, kind/branch-feature

#28227 [cherry-pick] Fix bulkinsert bug that segments are compacted after import
  internal/datanode/services.go
  internal/util/importutil/import_wrapper.go
  internal/util/importutil/import_wrapper_test.go
  internal/util/importutil/json_parser.go
  internal/util/importutil/numpy_adapter.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#28254 [2.3] Publish cardinal for milvus 2.3.3
  internal/core/thirdparty/knowhere/CMakeLists.txt
Labels: size/XS, approved, lgtm, ci-passed, dco-passed, area/compilation, kind/branch-feature

#28237 Force set aliyun use_virtual_host to true for all
  internal/core/src/storage/ChunkManagers.cpp
  internal/core/src/storage/MinioChunkManager.cpp
Labels: size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#28204 add fast fail while querynode not ready
  internal/querynode/impl.go
  internal/querynode/impl_test.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed, kind/branch-feature

#28250 Fix the target updated before version updated to cause data missing
  internal/querycoordv2/job/job_test.go
  internal/querycoordv2/observers/collection_observer.go
  internal/querycoordv2/observers/collection_observer_test.go
  internal/querycoordv2/observers/leader_observer.go
  internal/querycoordv2/observers/leader_observer_test.go
  internal/querycoordv2/observers/target_observer.go
  internal/querycoordv2/observers/target_observer_test.go
  internal/querycoordv2/server.go
  internal/querycoordv2/server_test.go
  internal/querycoordv2/services_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#28261 Fix delete session key with prefix
  cmd/milvus/util.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#28232 Not convert legacy error code to new merr
  internal/datanode/broker/broker.go
  internal/datanode/broker/datacoord.go
  internal/datanode/broker/datacoord_test.go
  internal/datanode/broker/mock_broker.go
  internal/datanode/data_sync_service_test.go
  internal/datanode/event_manager_test.go
  internal/datanode/flow_graph_manager_test.go
  internal/datanode/flush_manager.go
  internal/datanode/flush_manager_test.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#28260 Fix delete session key with prefix
  cmd/milvus/util.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#28213 Fix panic while forwarding empty deletions to growing segment
  internal/querynodev2/delegator/delegator_data.go
  internal/querynodev2/delegator/delegator_data_test.go
  internal/querynodev2/segments/segment.go
  internal/querynodev2/services.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#28265 Fix passing the wrong dropped list from current target
  internal/querycoordv2/observers/target_observer.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#28267 Fix delete session key with prefix
  cmd/milvus/util.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass, do-not-merge/missing-related-pr

#28240 Print azure sdk log
  internal/core/src/storage/AzureChunkManager.cpp
  internal/core/src/storage/AzureChunkManager.h
  internal/core/src/storage/azure-blob-storage/AzureBlobChunkManager.cpp
  internal/core/src/storage/azure-blob-storage/AzureBlobChunkManager.h
  internal/core/src/storage/azure-blob-storage/test/CMakeLists.txt
  internal/core/src/storage/azure-blob-storage/test/test_azure_blob_chunk_manager.cpp
  internal/core/unittest/test_azure_chunk_manager.cpp
  scripts/azure_build.sh
  scripts/core_build.sh
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed, area/compilation

#28281 fix datacoord unstable ut
  internal/datacoord/server_test.go
  internal/querycoordv2/server_test.go
Labels: size/S, dco-passed

#28282 fix datacoord unstable ut
  internal/datacoord/server_test.go
  internal/querycoordv2/server_test.go
Labels: size/S, dco-passed

#28257 Fix the target updated before version updated to cause data missing (#28250)
  internal/querycoordv2/job/job_test.go
  internal/querycoordv2/observers/collection_observer.go
  internal/querycoordv2/observers/collection_observer_test.go
  internal/querycoordv2/observers/leader_observer.go
  internal/querycoordv2/observers/leader_observer_test.go
  internal/querycoordv2/observers/target_observer.go
  internal/querycoordv2/observers/target_observer_test.go
  internal/querycoordv2/server.go
  internal/querycoordv2/server_test.go
  internal/querycoordv2/services_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#28268 Bump Milvus & milvus-proto version to v2.3.3
  go.mod
  go.sum
  pkg/common/version.go
  pkg/go.mod
  pkg/go.sum
Labels: area/dependency, kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed, manual-pass, kind/branch-feature

#28274 Not convert legacy error code to new merr (#28232)
  internal/datanode/broker/broker.go
  internal/datanode/broker/datacoord.go
  internal/datanode/broker/datacoord_test.go
  internal/datanode/broker/mock_broker.go
  internal/datanode/data_sync_service_test.go
  internal/datanode/event_manager_test.go
  internal/datanode/flow_graph_manager_test.go
  internal/datanode/flush_manager.go
  internal/datanode/flush_manager_test.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#28181 Change some log level in the pkg package
  pkg/config/manager.go
  pkg/config/refresher.go
  pkg/util/paramtable/component_param.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#28290 for compatible with sync target version
  internal/querynode/impl.go
  internal/querynode/impl_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#28288 fix unstable auto balance config ut
  internal/datacoord/server.go
  internal/querycoordv2/server.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#28289 [cherry-pick]fix unstable auto balance config ut
  internal/datacoord/server.go
  internal/querycoordv2/server.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#28241 Print azure sdk log
  internal/core/src/storage/AzureChunkManager.cpp
  internal/core/src/storage/AzureChunkManager.h
  internal/core/src/storage/azure-blob-storage/AzureBlobChunkManager.cpp
  internal/core/src/storage/azure-blob-storage/AzureBlobChunkManager.h
  internal/core/src/storage/azure-blob-storage/test/CMakeLists.txt
  internal/core/src/storage/azure-blob-storage/test/test_azure_blob_chunk_manager.cpp
  internal/core/unittest/test_azure_chunk_manager.cpp
  scripts/azure_build.sh
  scripts/core_build.sh
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed, area/compilation, manual-pass

#28263 [cherry-pick]Fix retry when proxy stopped
  internal/rootcoord/proxy_client_manager.go
  internal/rootcoord/proxy_client_manager_test.go
  internal/util/grpcclient/client.go
  internal/util/grpcclient/client_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#28258 Use OpenDAL 0.42
  scripts/3rdparty_build.sh
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#28276 [cherry-pick]Fix auto balance block channel reassign after datanode restart
  internal/datacoord/channel_manager.go
  internal/datacoord/policy.go
  internal/datacoord/policy_test.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#28295 Fix buffer FieldData has no `ElementType` and array logsize always zero
  internal/storage/utils.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#28296 [Cherry-Pick] Fix buffer FieldData has no `ElementType` and array logsize always zero
  internal/storage/utils.go
Labels: kind/bug, size/XS, approved, lgtm, dco-passed

#28298 Bump Milvus version to v2.2.15
  internal/common/version.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass, kind/branch-feature

#28304 Handle exception while loading
  internal/core/src/common/Channel.h
  internal/core/src/segcore/SegmentSealedImpl.cpp
  internal/core/src/segcore/Utils.cpp
Labels: kind/bug, size/M, lgtm, dco-passed

#28314 Fix wrong rootPath when querynode clean local dir
  cmd/roles/roles.go
Labels: kind/bug, size/XS, do-not-merge/missing-related-issue, dco-passed, do-not-merge/missing-related-pr

#28264 Fix retry when proxy stopped
  internal/rootcoord/proxy_client_manager.go
  internal/rootcoord/proxy_client_manager_test.go
  internal/util/grpcclient/client.go
  internal/util/grpcclient/client_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#28275 Fix auto balance block channel reassign after datanode restart
  internal/datacoord/channel_manager.go
  internal/datacoord/policy.go
  internal/datacoord/policy_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#28299 update pymilvus version
  tests/python_client/requirements.txt
  tests/python_client/testcases/test_collection.py
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#28306 Handle exception while loading (#28304)
  internal/core/src/common/Channel.h
  internal/core/src/segcore/SegmentSealedImpl.cpp
  internal/core/src/segcore/Utils.cpp
Labels: kind/bug, size/M, approved, dco-passed

#28311 [2.2]fix external grpc server doesn't graceful stop
  internal/distributed/proxy/service.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#28316 Sync proto generated files to avoid --dirty tag
  internal/core/src/pb/common.pb.cc
  internal/core/src/pb/common.pb.h
Labels: kind/improvement, size/XXL, approved, lgtm, ci-passed, dco-passed, manual-pass, kind/branch-feature

#28302 [cherry-pick] Don't throw error when the index exceeds the array length
  internal/core/src/query/visitors/ExecExprVisitor.cpp
  internal/core/unittest/test_array_expr.cpp
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/XL, approved, lgtm, area/test, ci-passed, dco-passed

#28309 Fix external grpc server doesn't graceful stop
  internal/distributed/proxy/service.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#24390 Upgrade go to 1.20
  .golangci.yml
  DEVELOPMENT.md
  README.md
  README_CN.md
  build/docker/meta-migration/builder/Dockerfile
  go.mod
  pkg/go.mod
  scripts/README.md
Labels: area/dependency, kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed, area/compilation

#28301 Don't throw error when the index exceeds the array length
  internal/core/src/query/visitors/ExecExprVisitor.cpp
  internal/core/unittest/test_array_expr.cpp
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/XL, approved, lgtm, area/test, ci-passed, dco-passed

#28158 Force set aliyun use_virtual_host to true for all
  internal/core/src/storage/ChunkManager.cpp
  internal/core/src/storage/MinioChunkManager.cpp
Labels: size/S, approved, lgtm, ci-passed, dco-passed

#28331 enhance: modify log to avoid ambiguity and improve readability
  internal/querycoordv2/task/scheduler.go
  internal/querycoordv2/task/task.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#28323 enhance: reduce 1x copy while retrieving data from growing segment
  internal/core/src/segcore/SegmentGrowingImpl.cpp
  internal/core/unittest/test_growing.cpp
  internal/core/unittest/test_index_wrapper.cpp
  internal/core/unittest/test_indexing.cpp
  internal/core/unittest/test_utils/DataGen.h
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#28351 Fix check segment loaded logic on querynode
  internal/querynode/impl.go
  internal/querynode/meta_replica.go
  internal/querynode/meta_replica_test.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed, manual-pass, kind/branch-feature
