Repository milvus-io/milvus, pull requests merged in 2023-12, with the labels that each got.

#28829 fix: Balance channel may cause channel not availble error
  internal/querycoordv2/task/scheduler.go
  internal/querycoordv2/task/task_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#28862 feat: avoid dereferencing nullptr
  internal/core/src/index/VectorDiskIndex.cpp
Labels: kind/feature, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#28876 enhance: Move datacoord broker into separate package
  internal/datacoord/broker/coordinator_broker.go
  internal/datacoord/broker/coordinator_broker_test.go
  internal/datacoord/server.go
  internal/datacoord/server_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#28841 fix: [cherry-pick] schema->size() check logic with system field (#28802)
  internal/core/src/segcore/SegmentGrowingImpl.cpp
  internal/core/unittest/test_c_api.cpp
  internal/querynodev2/segments/mock_data.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#28878 fix: update folly to resolve simd issue
  internal/core/conanfile.py
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#28866 fix: Fix get binary vector from chunk cache
  internal/core/src/segcore/SegmentSealedImpl.cpp
Labels: kind/bug, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed, test/integration

#28887 enhance: [skip e2e]delete unsed arch for gpu builder
  .github/workflows/publish-gpu-builder.yaml
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#28824 fix: accesslog method status not return failed when error in response
  internal/proxy/accesslog/info.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#28827 fix: [Cherry-Pick] accesslog method status not return failed when error in response
  internal/proxy/accesslog/info.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#28884 fix: Fix get binary vector from chunk cache (#28866)
  internal/core/src/segcore/SegmentSealedImpl.cpp
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#28812 enhance: enable assert method to format arguments
  internal/core/src/common/Array.h
  internal/core/src/common/BitsetView.h
  internal/core/src/common/EasyAssert.h
  internal/core/src/common/FieldMeta.h
  internal/core/src/common/File.h
  internal/core/src/common/Json.h
  internal/core/src/common/QueryResult.h
  internal/core/src/common/protobuf_utils.h
  internal/core/src/mmap/Column.h
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#28894 fix: azure ListObjects (#27931)
  internal/proxy/task_search_test.go
  internal/storage/azure_object_storage.go
  internal/storage/azure_object_storage_test.go
  internal/storage/minio_object_storage.go
  internal/storage/minio_object_storage_test.go
  internal/storage/remote_chunk_manager.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#28911 fix: Fix missing target db name for RenameCollection
  internal/proxy/database_interceptor.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#28913 fix: [cherry-pick] azure ListObjects (#27931)
  internal/proxy/task_search_test.go
  internal/storage/azure_object_storage.go
  internal/storage/azure_object_storage_test.go
  internal/storage/minio_object_storage.go
  internal/storage/minio_object_storage_test.go
  internal/storage/remote_chunk_manager.go
Labels: size/L, approved, lgtm, ci-passed

#28891 enhance: Remove too frequency read ddl log from rootcoord
  internal/rootcoord/root_coord.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#28892 fix: [cherry-pick] Check whether compaction plan exist before update(#28826)
  internal/datacoord/compaction.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#28846 test: modify test cases for error msg update
  tests/python_client/testcases/test_collection.py
  tests/python_client/testcases/test_partition.py
Labels: sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#28922 enhance: Update pymilvus
  tests/python_client/requirements.txt
Labels: kind/enhancement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#28942 enhance: Use a non-blocking method to trigger compaction when saveBinlogPath is executed
  internal/datacoord/compaction_trigger.go
  internal/datacoord/compaction_trigger_test.go
  internal/datacoord/mock_test.go
  internal/datacoord/services.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#28936 enhance: [hotfix] Resolve libunwind requirement conflict using 1.7.2
  internal/core/conanfile.py
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, manual-pass

#28946 enhance: [skip e2e] Update install_deps.sh cmake version
  scripts/install_deps.sh
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#28934 enhance: Change some frequency log to rated level (#28897)
  internal/querycoordv2/observers/target_observer.go
  internal/querycoordv2/services.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#28925 fix: Reject compaction task with growing segments
  internal/datanode/services.go
  internal/datanode/services_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#28947 enhance: [cherry-pick] Change const magic number in querycoord to param (#28819)
  internal/querycoordv2/observers/leader_observer.go
  internal/querycoordv2/session/cluster.go
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#28927 fix: [2.3] Reject compaction task with growing segments
  internal/datanode/channel_meta.go
  internal/datanode/channel_meta_test.go
  internal/datanode/flush_manager.go
  internal/datanode/services.go
  internal/datanode/services_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed, kind/branch-feature

#28731 feat: Define import API and metadata
  internal/datacoord/mock_test.go
  internal/datanode/services.go
  internal/distributed/datanode/client/client.go
  internal/distributed/datanode/service.go
  internal/distributed/datanode/service_test.go
  internal/mocks/mock_datanode.go
  internal/mocks/mock_datanode_client.go
  internal/proto/data_coord.proto
  internal/proto/datapb/data_coord.pb.go
  internal/util/mock/grpc_datanode_client.go
Labels: kind/feature, size/XXL, approved, lgtm, ci-passed, dco-passed

#28953 enhance: [hotfix] Reject compaction task with growing segments
  internal/datanode/channel_meta.go
  internal/datanode/channel_meta_test.go
  internal/datanode/flush_manager.go
  internal/datanode/services.go
  internal/datanode/services_test.go
Labels: size/L, approved, lgtm, ci-passed

#28939 fix: [cherry-pick]Fix failed to release collection with more than 128 partitions
  internal/metastore/kv/querycoord/kv_catalog.go
  internal/metastore/kv/querycoord/kv_catalog_test.go
Labels: size/M, approved, lgtm, ci-passed

#28907 enhance: enable assert method to format arguments (#28812)
  internal/core/src/common/Array.h
  internal/core/src/common/BitsetView.h
  internal/core/src/common/EasyAssert.h
  internal/core/src/common/FieldMeta.h
  internal/core/src/common/File.h
  internal/core/src/common/Json.h
  internal/core/src/common/QueryResult.h
  internal/core/src/common/protobuf_utils.h
  internal/core/src/mmap/Column.h
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#28954 test: add checker unittests
  internal/distributed/querycoord/client/client_test.go
  internal/distributed/querycoord/service_test.go
  internal/querycoordv2/checkers/controller_base_test.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed, kind/test

#28963 [automated] Update Builder gpu image changes
  .env
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#28969 enhance: Remove partition load infos with prefix
  internal/metastore/kv/querycoord/kv_catalog.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#28932 enhance: Remove too frequency read ddl log from rootcoord (#28891)
  internal/rootcoord/root_coord.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#28964 fix:[cherry-pick] Fix failed to release collection with more than 128 partitions
  internal/querycoordv2/meta/store.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#28971 enhance: [skip e2e]upgrade minio version
  deployments/docker/cluster-distributed-deployment/roles/deploy-minio/tasks/main.yml
  deployments/docker/dev/docker-compose-apple-silicon.yml
  deployments/docker/dev/docker-compose.yml
  deployments/docker/gpu/standalone/docker-compose.yml
  docker-compose.yml
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#28906 enhance: [skip e2e] upgrade minio version
  deployments/docker/cluster-distributed-deployment/roles/deploy-minio/tasks/main.yml
  deployments/docker/dev/docker-compose-apple-silicon.yml
  deployments/docker/dev/docker-compose.yml
  deployments/docker/gpu/standalone/docker-compose.yml
  docker-compose.yml
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed, do-not-merge/missing-related-pr

#28966 Fix DiskANN's async cache making
  internal/core/thirdparty/knowhere/CMakeLists.txt
Labels: size/XS, approved, lgtm, ci-passed, dco-passed, area/compilation, do-not-merge/missing-related-pr

#28502 fix: clean snapshots meta
  internal/rootcoord/meta_table.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#28877 fix: Change ranges of HNSW parameters according to Knowhere
  pkg/util/indexparamcheck/constraints.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#28875 fix: Change ranges of HNSW parameters according to Knowhere
  pkg/util/indexparamcheck/constraints.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#28835 enhance: pack proxy connection code and support accesslog print SDK_Version
  configs/milvus.yaml
  internal/distributed/proxy/service.go
  internal/proxy/accesslog/formatter.go
  internal/proxy/accesslog/info.go
  internal/proxy/accesslog/info_test.go
  internal/proxy/client_info.go
  internal/proxy/connection/client_info.go
  internal/proxy/connection/global.go
  internal/proxy/connection/manager.go
  internal/proxy/connection/manager_test.go
  internal/proxy/connection/util.go
  internal/proxy/connection/util_test.go
  internal/proxy/impl.go
  internal/proxy/proxy.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#28982 [automated] Update Builder image changes
  .env
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#28871 fix: may miss stream delta while loading
  internal/querycoordv2/observers/leader_observer.go
  internal/querycoordv2/observers/leader_observer_test.go
  internal/querycoordv2/task/executor.go
  internal/querycoordv2/task/task_test.go
  internal/querycoordv2/utils/types.go
  internal/querycoordv2/utils/types_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#28970 enhance: Write buffer time range when syncing logs
  internal/datanode/syncmgr/task.go
  internal/datanode/writebuffer/insert_buffer.go
  internal/datanode/writebuffer/segment_buffer.go
  internal/datanode/writebuffer/write_buffer.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#28814 fix: Fix L0 compaction in datacoord
  Makefile
  internal/datacoord/compaction.go
  internal/datacoord/compaction_l0_view.go
  internal/datacoord/compaction_scheduler.go
  internal/datacoord/compaction_scheduler_test.go
  internal/datacoord/compaction_test.go
  internal/datacoord/compaction_trigger.go
  internal/datacoord/compaction_trigger_v2.go
  internal/datacoord/compaction_trigger_v2_test.go
  internal/datacoord/compaction_view.go
  internal/datacoord/compaction_view_manager.go
  internal/datacoord/compaction_view_manager_test.go
  internal/datacoord/meta.go
  internal/datacoord/meta_test.go
  internal/datacoord/mock_compaction_meta.go
  internal/datacoord/mock_scheduler.go
  internal/datacoord/server.go
  internal/datacoord/services.go
Labels: kind/bug, size/XXL, approved, lgtm, ci-passed, dco-passed, area/compilation

#28972 enhance: Remove partition load infos with prefix (#28969)
  internal/metastore/kv/querycoord/kv_catalog.go
Labels: size/S, approved, lgtm, ci-passed

#28973 enhance: Remove partition load infos with prefix (#28969)
  internal/metastore/kv/querycoord/kv_catalog.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#28999 fix: clean snapshots meta (#28502)
  internal/rootcoord/meta_table.go
Labels: kind/bug, size/XS, approved, dco-passed

#28998 fix: clean snapshots meta (#28502)
  internal/rootcoord/meta_table.go
Labels: size/XS, approved

#28945 enhance: Add proxy.ginLogSkipPaths
  configs/milvus.yaml
  internal/distributed/proxy/service.go
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#28991 enhance: Update pymilvus (#28922)
  tests/python_client/requirements.txt
Labels: kind/enhancement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#28888 enhance: Load raw data while scalar index doesn't have raw data
  internal/core/src/index/Index.h
  internal/core/src/index/ScalarIndex.h
  internal/core/src/index/ScalarIndexSort.h
  internal/core/src/index/StringIndexMarisa.h
  internal/core/src/query/visitors/ExecExprVisitor.cpp
  internal/core/src/segcore/SegmentSealedImpl.cpp
  internal/core/src/segcore/SegmentSealedImpl.h
  internal/core/unittest/test_scalar_index.cpp
  internal/core/unittest/test_string_index.cpp
  internal/querynodev2/segments/segment.go
  internal/querynodev2/segments/segment_loader.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#28756 feat: skip some empty ttMsg in Datanode flowgraph
  configs/milvus.yaml
  internal/util/flowgraph/input_node.go
  internal/util/flowgraph/input_node_test.go
  internal/util/flowgraph/node_test.go
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/component_param_test.go
Labels: kind/feature, size/L, approved, lgtm, ci-passed, dco-passed

#29012 enhance:[cherry-pick] Use binlog index for better search performance
  configs/milvus.yaml
  internal/core/src/segcore/FieldIndexing.cpp
  internal/core/src/segcore/FieldIndexing.h
  internal/core/src/segcore/IndexConfigGenerator.cpp
  internal/core/src/segcore/IndexConfigGenerator.h
  internal/core/src/segcore/SegcoreConfig.h
  internal/core/src/segcore/SegmentGrowingImpl.cpp
  internal/core/src/segcore/SegmentSealedImpl.cpp
  internal/core/src/segcore/SegmentSealedImpl.h
  internal/core/src/segcore/segcore_init_c.cpp
  internal/core/src/segcore/segcore_init_c.h
  internal/core/src/segcore/segment_c.cpp
  internal/core/unittest/CMakeLists.txt
  internal/core/unittest/bench/bench_search.cpp
  internal/core/unittest/test_binlog_index.cpp
  internal/core/unittest/test_float16.cpp
  internal/core/unittest/test_growing.cpp
  internal/core/unittest/test_growing_index.cpp
  internal/proto/planpb/plan.pb.go
  internal/querynodev2/segments/segment_loader.go
  internal/querynodev2/server.go
  internal/querynodev2/services_test.go
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/component_param_test.go
  tests/python_client/testcases/test_search.py
Labels: kind/enhancement, sig/testing, size/XL, approved, lgtm, area/test, ci-passed, dco-passed, area/compilation

#28993 enhance: Log channel checkpoint source info in writebuffer
  internal/datanode/syncmgr/mock_sync_manager.go
  internal/datanode/syncmgr/sync_manager.go
  internal/datanode/writebuffer/write_buffer.go
  internal/datanode/writebuffer/write_buffer_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#28844 enhance: [Cherry-pick] pack proxy connection code and support accesslog print SDK_Version
  configs/milvus.yaml
  internal/distributed/proxy/service.go
  internal/proxy/accesslog/formatter.go
  internal/proxy/accesslog/info.go
  internal/proxy/accesslog/info_test.go
  internal/proxy/client_info.go
  internal/proxy/connection/client_info.go
  internal/proxy/connection/global.go
  internal/proxy/connection/manager.go
  internal/proxy/connection/manager_test.go
  internal/proxy/connection/util.go
  internal/proxy/connection/util_test.go
  internal/proxy/impl.go
  internal/proxy/proxy.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#28977 enhance: [2.3] Use a non-blocking method to trigger compaction when saveBinlogPath is executed
  internal/datacoord/compaction_trigger.go
  internal/datacoord/compaction_trigger_test.go
  internal/datacoord/mock_test.go
  internal/datacoord/services.go
Labels: kind/enhancement, kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#28952 enhance: Refine C.NewSegment response and handle exception
  internal/core/src/common/type_c.h
  internal/core/src/segcore/segment_c.cpp
  internal/core/src/segcore/segment_c.h
  internal/core/unittest/test_c_api.cpp
  internal/querynodev2/segments/segment.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#28956 fix: [Cherry-pick] sync action load segment with lack collection index info list
  internal/proto/query_coord.proto
  internal/proto/querypb/query_coord.pb.go
  internal/querycoordv2/observers/leader_observer.go
  internal/querycoordv2/observers/leader_observer_test.go
  internal/querycoordv2/observers/target_observer.go
  internal/querycoordv2/observers/target_observer_test.go
  internal/querynodev2/services.go
Labels: kind/bug, size/XL, approved, lgtm, ci-passed, area/internal-api, dco-passed

#29029 enhance: add more metrics for level zero segments
  internal/querynodev2/delegator/delegator_data.go
  internal/querynodev2/delegator/delegator_data_test.go
  internal/querynodev2/segments/manager.go
  pkg/metrics/querynode_metrics.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#29003 enhance: Delete datanode metric after flowgraph released
  pkg/metrics/datanode_metrics.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#29018 fix: panic caused by type assert LocalSegment on Segment
  internal/querynodev2/handlers.go
  internal/querynodev2/local_worker.go
  internal/querynodev2/local_worker_test.go
  internal/querynodev2/segments/retrieve.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#29031 fix: fix reduce precision for search(#27325)
  internal/core/src/segcore/ReduceStructure.h
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#29032 fix: fix precision for search reduce(#27325)
  internal/core/src/segcore/ReduceStructure.h
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#28978 enhance: Make import-related error message clearer
  internal/util/importutil/binlog_adapter.go
  internal/util/importutil/binlog_adapter_test.go
  internal/util/importutil/binlog_parser.go
  internal/util/importutil/import_wrapper.go
  internal/util/importutil/import_wrapper_test.go
  internal/util/importutil/json_handler.go
  internal/util/importutil/json_parser.go
  internal/util/importutil/numpy_adapter.go
  internal/util/importutil/numpy_parser.go
  internal/util/importutil/parquet_parser.go
  internal/util/importutil/parquet_parser_test.go
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#29002 enhance: [cherry-pick] support mmap for indexes loaded from disk file
  internal/core/src/index/VectorDiskIndex.cpp
  internal/core/thirdparty/knowhere/CMakeLists.txt
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed, area/compilation

#28989 fix: createCollection failed occasionally (#28592)
  internal/distributed/datanode/client/client.go
  internal/distributed/indexnode/client/client.go
  internal/distributed/proxy/client/client.go
  internal/distributed/proxy/service.go
  internal/distributed/querynode/client/client.go
  internal/util/grpcclient/client.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#29070 enhance: improve load speed (#28518)
  internal/querynodev2/segments/pool.go
  internal/querynodev2/segments/segment.go
  internal/querynodev2/segments/segment_loader.go
Labels: size/M, approved, lgtm, ci-passed, manual-pass

#29077 enhance: [skip-e2e] enlarge disk space of action runner
  .github/workflows/code-checker.yaml
  .github/workflows/main.yaml
Labels: kind/enhancement, kind/improvement, size/XS, lgtm, dco-passed

#29008 enhance: Add proxy.ginLogSkipPaths
  configs/milvus.yaml
  internal/distributed/proxy/service.go
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/S, approved, lgtm, dco-passed

#29079 enhance: [hotfix] Add client connect wrapper to keep connection alive
  internal/util/grpcclient/client.go
  internal/util/grpcclient/client_test.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, manual-pass

#29093 fix: Fix rustup update
  scripts/3rdparty_build.sh
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#29058 enhance: Add client connect wrapper to keep connection alive
  internal/util/grpcclient/client.go
  internal/util/grpcclient/client_test.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#28869 enhance: pack datacoord Cluster and SessionManager with interface and mock them
  Makefile
  internal/datacoord/cluster.go
  internal/datacoord/cluster_test.go
  internal/datacoord/compaction.go
  internal/datacoord/compaction_test.go
  internal/datacoord/mock_cluster.go
  internal/datacoord/mock_session_manager.go
  internal/datacoord/server.go
  internal/datacoord/server_test.go
  internal/datacoord/services.go
  internal/datacoord/session_manager.go
  internal/datacoord/session_manager_test.go
Labels: kind/enhancement, size/XXL, approved, lgtm, ci-passed, dco-passed, area/compilation

#29127 fix: balance_unstable_view unit test
  internal/querycoordv2/balance/rowcount_based_balancer_test.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#28796 fix: fix datarace in root_coord proxy_client_manager
  internal/rootcoord/proxy_client_manager.go
  internal/rootcoord/proxy_client_manager_test.go
  internal/rootcoord/root_coord.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#29117 enhance: Avoid initializing casbin enforcer for each request
  internal/proxy/meta_cache.go
  internal/proxy/meta_cache_adapter.go
  internal/proxy/meta_cache_adapter_test.go
  internal/proxy/privilege_interceptor.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#29118 enhance: [cherry-pick] Avoid initializing casbin enforcer for each request
  internal/proxy/meta_cache.go
  internal/proxy/meta_cache_adapter.go
  internal/proxy/meta_cache_adapter_test.go
  internal/proxy/privilege_interceptor.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#29062 enhance: remove merger for load segments
  internal/querycoordv2/task/action.go
  internal/querycoordv2/task/executor.go
  internal/querycoordv2/task/merge_task.go
  internal/querycoordv2/task/merger.go
  internal/querycoordv2/task/merger_test.go
  internal/querycoordv2/task/task_test.go
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/XL, approved, lgtm, ci-passed, dco-passed, manual-pass

#29115 enhance: Support otlp with insecure
  configs/milvus.yaml
  internal/core/src/common/Tracer.cpp
  internal/core/src/common/Tracer.h
  internal/core/src/common/init_c.cpp
  internal/core/src/common/type_c.h
  pkg/tracer/tracer.go
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#29069 test: modify cases for the update of IVF_FLAT
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#29112 enhance: Add config for auto upgrade segment index
  internal/datacoord/compaction_trigger.go
  internal/datacoord/compaction_trigger_test.go
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/component_param_test.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#29100 enhance: upgrade proto to use partition related privileges
  go.mod
  go.sum
  internal/core/src/pb/common.pb.cc
  internal/core/src/pb/common.pb.h
  internal/core/src/pb/schema.pb.cc
  internal/core/src/pb/schema.pb.h
  internal/distributed/proxy/service.go
  internal/distributed/proxy/service_test.go
  internal/mocks/mock_proxy.go
  internal/proxy/impl.go
  pkg/go.mod
  pkg/go.sum
  pkg/util/constant.go
  pkg/util/funcutil/policy_test.go
Labels: kind/enhancement, area/dependency, kind/improvement, size/XXL, approved, lgtm, ci-passed, dco-passed, kind/branch-feature

#28570 feat: Introduce channelCheckpointUpdater to reduce goroutine use in ttNode
  configs/milvus.yaml
  internal/datanode/channel_checkpoint_updater.go
  internal/datanode/data_node.go
  internal/datanode/data_sync_service.go
  internal/datanode/data_sync_service_test.go
  internal/datanode/flow_graph_time_tick_node.go
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/component_param_test.go
Labels: kind/feature, size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#29107 feat: Introduce channelCheckpointUpdater to reduce goroutine in ttNode
  configs/milvus.yaml
  internal/datanode/channel_checkpoint_updater.go
  internal/datanode/data_node.go
  internal/datanode/data_sync_service.go
  internal/datanode/data_sync_service_test.go
  internal/datanode/flow_graph_time_tick_node.go
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/component_param_test.go
Labels: kind/feature, size/L, approved, lgtm, ci-passed, dco-passed

#29090 enhance: add more logs for target updating
  internal/querycoordv2/observers/target_observer.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#29105 fix: [cherry-pick] fix rootcoord_collection_num metric is twice the real value
  internal/rootcoord/root_coord.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#29124 fix: txn control not applied to snapshot.Remove
  internal/metastore/kv/rootcoord/kv_catalog.go
  internal/metastore/kv/rootcoord/kv_catalog_test.go
  pkg/util/etcd/etcd_util.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#29046 enhance: Support implicit type conversion for parquet
  internal/core/src/index/ScalarIndex.h
  internal/rootcoord/import_manager.go
  internal/rootcoord/import_manager_test.go
  internal/util/importutil/parquet_column_reader.go
  internal/util/importutil/parquet_parser.go
  internal/util/importutil/parquet_parser_test.go
Labels: kind/enhancement, size/XXL, approved, lgtm, ci-passed, dco-passed

#29119 enhance: [Pick]Support implicit type conversion for parquet
  internal/rootcoord/import_manager.go
  internal/rootcoord/import_manager_test.go
  internal/util/importutil/parquet_column_reader.go
  internal/util/importutil/parquet_parser.go
  internal/util/importutil/parquet_parser_test.go
Labels: kind/enhancement, size/XXL, approved, lgtm, ci-passed, dco-passed

#29064 enhance: remove merger for load segments (#29062)
  internal/querycoordv2/task/action.go
  internal/querycoordv2/task/executor.go
  internal/querycoordv2/task/merge_task.go
  internal/querycoordv2/task/merger.go
  internal/querycoordv2/task/merger_test.go
  internal/querycoordv2/task/task_test.go
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/XL, approved, lgtm, ci-passed, dco-passed, manual-pass

#29075 fix: wait server to listen the http port
  internal/http/server_test.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#29076 fix: wait server to listen the http port
  internal/http/server_test.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#29137 fix: txn control not applied to snapshot.Remove (#29124)
  internal/metastore/kv/rootcoord/kv_catalog.go
  internal/metastore/kv/rootcoord/kv_catalog_test.go
  pkg/util/etcd/etcd_util.go
Labels: kind/bug, size/M, approved, lgtm, dco-passed

#29131 enhance: Support otlp with insecure
  configs/milvus.yaml
  internal/core/src/common/Tracer.cpp
  internal/core/src/common/Tracer.h
  internal/core/src/common/init_c.cpp
  internal/core/src/common/type_c.h
  pkg/tracer/tracer.go
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#29133 enhance: Add config for auto upgrade segment index (#29112)
  internal/datacoord/compaction_trigger.go
  internal/datacoord/compaction_trigger_test.go
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/component_param_test.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#29130 fix: forbid balancing level zero segments
  internal/querycoordv2/balance/rowcount_based_balancer.go
  internal/querycoordv2/balance/score_based_balancer.go
  internal/querycoordv2/balance/score_based_balancer_test.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#29142 fix: txn control not applied to snapshot.Remove (#29124)
  internal/metastore/kv/rootcoord/kv_catalog.go
  internal/metastore/kv/rootcoord/kv_catalog_test.go
  internal/util/etcd/etcd_util.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#29071 fix: autoindex panic with flat index type
  pkg/util/indexparamcheck/flat_checker.go
  pkg/util/indexparamcheck/flat_checker_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#29072 fix: autoindex panic with flat index type (#29071)
  pkg/util/indexparamcheck/flat_checker.go
  pkg/util/indexparamcheck/flat_checker_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#29108 enhance: specify version while rust-init
  build/docker/builder/cpu/amazonlinux2023/Dockerfile
  build/docker/builder/cpu/ubuntu20.04/Dockerfile
  build/docker/builder/gpu/ubuntu20.04/Dockerfile
Labels: kind/enhancement, kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#29141 enhance: Add more logs for target updating (#29090)
  internal/querycoordv2/observers/target_observer.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#29143 enhance: Use zap.Stringer for large log field
  internal/proxy/segment.go
  internal/proxy/task_search.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#29022 test: modify some cases for error msg update
  tests/python_client/testcases/test_high_level_api.py
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#29153 enhance: [cherry-pick] Use zap.Stringer for large log field (#29143)
  internal/proxy/segment.go
  internal/proxy/task_search.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#29074 enhance: Use mockery to replace manual mock code
  Makefile
  internal/distributed/datacoord/client/client_test.go
  internal/distributed/datacoord/service_test.go
  internal/distributed/datanode/service_test.go
  internal/distributed/proxy/client/client_test.go
  internal/distributed/proxy/service_test.go
  internal/distributed/querycoord/service_test.go
  internal/distributed/rootcoord/service_test.go
  internal/mocks/mock_grpc_client.go
  internal/rootcoord/broker_test.go
  internal/rootcoord/mock_test.go
  internal/rootcoord/quota_center_test.go
  internal/rootcoord/root_coord_test.go
  internal/util/mock/grpc_datacoord_client.go
  internal/util/mock/grpc_proxy_client.go
Labels: kind/enhancement, size/XXL, approved, lgtm, ci-passed, dco-passed, area/compilation

#29147 fix: [2.3] the unstable unit test TestReplicateManager
  internal/proxy/replicate_stream_manager_test.go
Labels: kind/bug, kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#29157 [automated] Update Builder gpu image changes
  .env
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#29106 enhance: use specific rust version to compile opendal
  scripts/3rdparty_build.sh
Labels: kind/enhancement, kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#28995 feat: integrate storagev2 into index build process
  go.mod
  internal/datacoord/index_builder.go
  internal/datacoord/index_builder_test.go
  internal/datacoord/server.go
  internal/datacoord/services.go
  internal/datanode/metacache/storagev2_cache.go
  internal/datanode/syncmgr/taskv2.go
  internal/datanode/syncmgr/taskv2_test.go
  internal/datanode/writebuffer/bf_write_buffer_test.go
  internal/indexnode/indexnode_service.go
  internal/indexnode/task.go
  internal/indexnode/task_scheduler.go
  internal/indexnode/task_test.go
  internal/indexnode/taskinfo_ops.go
  internal/metastore/model/segment_index.go
  internal/mocks/mock_datanode.go
  internal/mocks/mock_datanode_client.go
  internal/proto/index_coord.proto
  internal/util/indexcgowrapper/build_index_info.go
  internal/util/indexcgowrapper/index.go
  internal/util/typeutil/schema.go
  internal/util/typeutil/schema_test.go
Labels: kind/feature, area/dependency, size/XXL, approved, lgtm, ci-passed, area/internal-api, dco-passed, manual-pass

#29027 fix: Fix some left comments
  internal/datacoord/compaction.go
  internal/datacoord/compaction_l0_view.go
  internal/datacoord/compaction_l0_view_test.go
  internal/datacoord/compaction_trigger_v2.go
  internal/datacoord/compaction_view.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#28899 fix: accesslog can not print search expression
  configs/milvus.yaml
  internal/proxy/accesslog/info.go
  internal/proxy/accesslog/info_test.go
  pkg/util/paramtable/component_param.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#29030 test: add array data type and parquet file type for bulk insert case
  tests/python_client/common/bulk_insert_data.py
  tests/python_client/common/common_func.py
  tests/python_client/testcases/test_bulk_insert.py
Labels: sig/testing, size/XL, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#29154 enhance: Add a config item for partition name as regexp feature and disable it by default
  internal/proxy/task_search.go
  internal/proxy/task_search_test.go
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed, behavior-change

#29145 enhance: [skip-e2e] auto cancel stale workflows
  .github/workflows/code-checker.yaml
  .github/workflows/mac.yaml
  .github/workflows/main.yaml
  .github/workflows/publish-builder.yaml
  .github/workflows/publish-gpu-builder.yaml
  .github/workflows/publish-krte-images.yaml
  .github/workflows/publish-test-images.yaml
Labels: kind/enhancement, kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#29161 enhance: Change channel to Interface (#27839)
  internal/datacoord/channel.go
  internal/datacoord/channel_manager.go
  internal/datacoord/channel_manager_test.go
  internal/datacoord/channel_store.go
  internal/datacoord/channel_store_test.go
  internal/datacoord/cluster.go
  internal/datacoord/cluster_test.go
  internal/datacoord/compaction_test.go
  internal/datacoord/handler.go
  internal/datacoord/mock_channel_store.go
  internal/datacoord/mock_handler.go
  internal/datacoord/mock_test.go
  internal/datacoord/policy.go
  internal/datacoord/policy_test.go
  internal/datacoord/server_test.go
  internal/datacoord/services.go
  internal/datacoord/services_test.go
Labels: kind/enhancement, size/XXL, approved, lgtm, ci-passed, dco-passed

#29168 fix: forbid balancing level zero segments
  internal/datacoord/services.go
  internal/querycoordv2/balance/score_based_balancer.go
  internal/querycoordv2/utils/types.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#29180 enhance: improve datanode channel checkpoint source log
  internal/datanode/channel_meta.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed, kind/branch-feature

#29163 fix: bulkinsert binlog didn't consider ts order when processing delta data
  internal/util/importutil/binlog_adapter.go
  internal/util/importutil/binlog_adapter_test.go
  internal/util/importutil/binlog_file_test.go
  internal/util/importutil/binlog_parser_test.go
  internal/util/importutil/import_util_test.go
  internal/util/importutil/import_wrapper_test.go
  internal/util/importutil/json_handler_test.go
  internal/util/importutil/numpy_parser_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#29176 fix: [cherry-pick] bulkinsert binlog didn't consider ts order when processing delta data
  internal/util/importutil/binlog_adapter.go
  internal/util/importutil/binlog_adapter_test.go
  internal/util/importutil/binlog_file_test.go
  internal/util/importutil/binlog_parser_test.go
  internal/util/importutil/import_util_test.go
  internal/util/importutil/import_wrapper_test.go
  internal/util/importutil/json_handler_test.go
  internal/util/importutil/numpy_parser_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#29183 enhance: [cherry-pick] Add a config item for partition name as regexp feature (#29154)
  internal/proxy/task_search.go
  internal/proxy/task_search_test.go
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#29184 feat: enable balance based on growing segment row count (#28623)
  internal/proto/query_coord.proto
  internal/querycoordv2/balance/rowcount_based_balancer.go
  internal/querycoordv2/balance/rowcount_based_balancer_test.go
  internal/querycoordv2/balance/score_based_balancer.go
  internal/querycoordv2/balance/score_based_balancer_test.go
  internal/querycoordv2/dist/dist_handler.go
  internal/querycoordv2/meta/leader_view_manager.go
  internal/querycoordv2/meta/leader_view_manager_test.go
  internal/querynodev2/services.go
Labels: kind/feature, size/L, approved, lgtm, ci-passed, area/internal-api, dco-passed

#29195 enhance: remove reset seed for every shuffle
  internal/proxy/meta_cache.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#29173 fix: missing the grant info when using the SelectGrant api with the default db
  internal/metastore/kv/rootcoord/kv_catalog.go
  internal/metastore/kv/rootcoord/kv_catalog_test.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#29174 fix: [2.3] missing the grant info when using the SelectGrant api with the default db
  internal/metastore/kv/rootcoord/kv_catalog.go
  internal/metastore/kv/rootcoord/kv_catalog_test.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#29116 enhance: Skip balance segment when channel need be balanced
  internal/querycoordv2/balance/rowcount_based_balancer.go
  internal/querycoordv2/balance/rowcount_based_balancer_test.go
  internal/querycoordv2/balance/score_based_balancer.go
  internal/querycoordv2/meta/resource_manager.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#29182 enhance: Use mockery to replace manual mock code (#29074)
  Makefile
  internal/distributed/datacoord/client/client_test.go
  internal/distributed/datacoord/service_test.go
  internal/distributed/datanode/service_test.go
  internal/distributed/proxy/client/client_test.go
  internal/distributed/proxy/service_test.go
  internal/distributed/querycoord/service_test.go
  internal/distributed/rootcoord/service_test.go
  internal/mocks/mock_grpc_client.go
  internal/rootcoord/broker_test.go
  internal/rootcoord/mock_test.go
  internal/rootcoord/quota_center_test.go
  internal/rootcoord/root_coord_test.go
  internal/util/mock/grpc_datacoord_client.go
  internal/util/mock/grpc_proxy_client.go
Labels: kind/enhancement, size/XXL, approved, lgtm, ci-passed, dco-passed, area/compilation

#29192 fix: load gets stuck probably (#29191)
  internal/querycoordv2/observers/task_dispatcher.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#29196 enhance: [cherry-pick] remove reset seed for every shuffle
  internal/proxy/meta_cache.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#29206 fix: data race in ProxyClientManager
  internal/rootcoord/mock_test.go
  internal/rootcoord/proxy_client_manager.go
  internal/rootcoord/proxy_client_manager_test.go
  internal/rootcoord/quota_center_test.go
  internal/rootcoord/root_coord.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#29191 fix: load gets stuck probably
  internal/querycoordv2/observers/task_dispatcher.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#29190 fix: Set compacted segments' level to level one
  internal/datacoord/meta.go
  internal/datacoord/meta_test.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#29052 enhance: Add http method to control datacoord garbage collection
  internal/datacoord/garbage_collector.go
  internal/datacoord/garbage_collector_test.go
  internal/datacoord/server.go
  internal/datacoord/services.go
  internal/datacoord/services_test.go
  internal/distributed/datacoord/client/client.go
  internal/distributed/datacoord/client/client_test.go
  internal/distributed/datacoord/service.go
  internal/distributed/datacoord/service_test.go
  internal/http/server.go
  internal/mocks/mock_datacoord.go
  internal/mocks/mock_datacoord_client.go
  internal/proto/data_coord.proto
  internal/proxy/management.go
  internal/proxy/management_test.go
Labels: kind/enhancement, size/XL, approved, lgtm, ci-passed, dco-passed

#28990 test:add array data type and parquet file type for bulk insert case
  tests/python_client/common/bulk_insert_data.py
  tests/python_client/common/common_func.py
  tests/python_client/testcases/test_bulk_insert.py
Labels: sig/testing, size/XL, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#29216 enhance: Change sync manager parallel config item
  internal/datanode/data_node.go
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#29212 enhance: [cherry-pick] Add http method to control datacoord garbage collection
  internal/datacoord/garbage_collector.go
  internal/datacoord/garbage_collector_test.go
  internal/datacoord/server.go
  internal/datacoord/services.go
  internal/datacoord/services_test.go
  internal/distributed/datacoord/client/client.go
  internal/distributed/datacoord/client/client_test.go
  internal/distributed/datacoord/service.go
  internal/distributed/datacoord/service_test.go
  internal/http/server.go
  internal/mocks/mock_datacoord.go
  internal/mocks/mock_datacoord_client.go
  internal/proto/data_coord.proto
  internal/proto/datapb/data_coord.pb.go
  internal/proto/planpb/plan.pb.go
  internal/proto/querypb/query_coord.pb.go
  internal/proxy/management.go
  internal/proxy/management_test.go
Labels: kind/enhancement, size/XXL, approved, lgtm, ci-passed, area/internal-api, dco-passed

#29224 enhance: make SyncManager pool size refreshable
  internal/datanode/data_node.go
  internal/datanode/mock_test.go
  internal/datanode/syncmgr/key_lock_dispatcher.go
  internal/datanode/syncmgr/sync_manager.go
  internal/datanode/syncmgr/sync_manager_test.go
  pkg/util/conc/pool.go
  pkg/util/conc/pool_test.go
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#29148 enhance: find collection schema from cache
  internal/distributed/proxy/httpserver/handler_v1.go
  internal/distributed/proxy/httpserver/handler_v1_test.go
  internal/distributed/proxy/httpserver/utils.go
  internal/distributed/proxy/httpserver/utils_test.go
  internal/proxy/meta_cache.go
  internal/proxy/meta_cache_test.go
  internal/proxy/mock_cache_test.go
  internal/proxy/util.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#29209 enhance: Enable balance channel in querycoord (#28469)
  internal/querycoordv2/balance/rowcount_based_balancer.go
  internal/querycoordv2/balance/rowcount_based_balancer_test.go
  internal/querycoordv2/balance/score_based_balancer.go
  internal/querycoordv2/balance/score_based_balancer_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#29188 fix: [cherry-pick] bulkinsert binlog didn't consider ts order when processing delta data
  internal/util/importutil/binlog_adapter.go
  internal/util/importutil/binlog_adapter_test.go
  internal/util/importutil/binlog_file_test.go
  internal/util/importutil/binlog_parser_test.go
  internal/util/importutil/import_util_test.go
  internal/util/importutil/import_wrapper_test.go
  internal/util/importutil/json_handler_test.go
  internal/util/importutil/numpy_parser_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#29219 enhance: [Pick] Set default index name as field name
  internal/proxy/task_index.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#29218 enhance: Set default index name as field name
  internal/proxy/task_index.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#29207 enhance: Remove omp from segcore
  internal/core/src/common/RangeSearchHelper.cpp
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#29225 enhance: [cherry-pick] make `conc.Pool` resizable
  pkg/util/conc/pool.go
  pkg/util/conc/pool_test.go
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#29232 enhance: Skip balance segment when channel need be balanced (#29116)
  internal/querycoordv2/balance/rowcount_based_balancer.go
  internal/querycoordv2/balance/rowcount_based_balancer_test.go
  internal/querycoordv2/balance/score_based_balancer.go
  internal/querycoordv2/meta/resource_manager.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#29220 fix: Skip updating checkpoint after dropcollection
  internal/datanode/flow_graph_dd_node.go
  internal/datanode/flow_graph_time_tick_node.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#29221 fix: [cherry-pick]Skip updating checkpoint after dropcollection
  internal/datanode/flow_graph_dd_node.go
  internal/datanode/flow_graph_time_tick_node.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#29236 enhance: Remove omp from segcore
  internal/core/src/common/RangeSearchHelper.cpp
Labels: kind/enhancement, kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed, do-not-merge/missing-related-pr

#29041 enhance: [skip e2e]update chart version
  ci/jenkins/Nightly.groovy
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#29136 enhance: modify test cases for error msg update
  tests/python_client/common/common_func.py
  tests/python_client/testcases/test_search.py
Labels: kind/enhancement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed
