Repository milvus-io/milvus, pull requests merged in 2023-04, with the labels that each got.

#23159 Update pymilvus version
  tests/python_client/requirements.txt
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#23072 Modify test cases of diskann
  tests/python_client/testcases/test_index.py
  tests/python_client/testcases/test_insert.py
Labels: kind/improvement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#23158 Update pymilvus version
  tests/python_client/requirements.txt
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#23117 [test] Remove unused python lib
  tests/python_client/requirements.txt
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#23118 [test] Remove unused python lib
  tests/python_client/requirements.txt
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#22867 Update tests for resource group
  tests/python_client/testcases/test_resourcegroup.py
Labels: sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#22936 Bump ants to v2.7.2 for performance improvement
  go.mod
  go.sum
  internal/querynode/segment_loader.go
Labels: area/dependency, kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#23144 Improve search/query logs in Proxy
  internal/proxy/task_query.go
  internal/proxy/task_search.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#23056 enhance segment balance by considering global rowCount(##22914)
  internal/querycoordv2/balance/balance.go
  internal/querycoordv2/balance/balance_test.go
  internal/querycoordv2/balance/mock_balancer.go
  internal/querycoordv2/balance/priority_queue_test.go
  internal/querycoordv2/balance/rowcount_based_balancer.go
  internal/querycoordv2/balance/rowcount_based_balancer_test.go
  internal/querycoordv2/balance/score_based_balancer.go
  internal/querycoordv2/balance/score_based_balancer_test.go
  internal/querycoordv2/balance/utils.go
  internal/querycoordv2/checkers/controller.go
  internal/querycoordv2/checkers/segment_checker.go
  internal/querycoordv2/checkers/segment_checker_test.go
  internal/querycoordv2/handlers.go
  internal/querycoordv2/server.go
  internal/querycoordv2/server_test.go
  internal/querycoordv2/task/mock_scheduler.go
  internal/querycoordv2/task/scheduler.go
  internal/querynode/impl.go
  internal/util/paramtable/component_param.go
  internal/util/typeutil/set.go
  internal/util/typeutil/set_test.go
Labels: size/XXL, approved, lgtm, ci-passed, dco-passed

#23181 Fix querynode panic
  internal/querynodev2/segments/retrieve.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#23162 Check if loaded before delegator search/query
  internal/querynodev2/delegator/delegator.go
  internal/querynodev2/delegator/delegator_test.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#23163 Add metrics for QueryNodeV2
  internal/querynodev2/services.go
  internal/querynodev2/tasks/scheduler.go
  internal/querynodev2/tasks/task.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#23036 [2.2] Use singleflight to limit readWithCache concurrent operation
  internal/storage/vector_chunk_manager.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#23183 Use peek segment info in querynodev2
  internal/querynodev2/delegator/delegator.go
  internal/querynodev2/delegator/delegator_data_test.go
  internal/querynodev2/delegator/delegator_test.go
  internal/querynodev2/delegator/distribution.go
  internal/querynodev2/delegator/distribution_test.go
  internal/querynodev2/delegator/mock_delegator.go
  internal/querynodev2/delegator/snapshot.go
  internal/querynodev2/services.go
  internal/querynodev2/services_test.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#23196 Add OWNERS file for qnv2
  internal/querynodev2/OWNERS
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#23153 Fix buffer calculate memorysize negative
  internal/datanode/buffer.go
  internal/datanode/buffer_test.go
  internal/datanode/flow_graph_delete_node.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#23199 Add prometheus-cpp
  internal/core/conanfile.py
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#23195 Fix DescribeCollection failed with undefined msg type (#23192)
  internal/datacoord/server.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#23192 Fix DescribeCollection failed with undefined msg type
  internal/datacoord/server.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#23166 Remove useCustomConfig and simpilify the session type
  cmd/tools/migration/migration/runner.go
  internal/util/sessionutil/session_util.go
  internal/util/sessionutil/session_util_test.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#23084 Modify test cases of max dim of diskann(2.2)
  tests/python_client/testcases/test_index.py
Labels: sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed, manual-pass

#23201 Remove tests for ANNOY index
  tests/python_client/common/common_type.py
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#23194 Rename RAFT_IVF_FLAT/RAFT_IVF_PQ to GPU_IVF_FLAT/GPU_IVF_PQ
  internal/util/indexparamcheck/index_type.go
  tests/python_client/common/common_func.py
  tests/python_client/common/common_type.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#23188 Remove partition target check in querynodev2
  internal/querynodev2/pipeline/filter_node_test.go
  internal/querynodev2/pipeline/filter_policy.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#23207 Update Development.md
  DEVELOPMENT.md
  README.md
  deployments/docker/dev/docker-compose-apple-silicon.yml
  deployments/docker/dev/docker-compose.yml
  docs/design_docs/20211217-milvus_create_collection.md
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#23189 Remove ANNOY index type
  internal/core/src/query/deprecated/ValidationUtil.cpp
  internal/core/src/query/visitors/VerifyPlanNodeVisitor.cpp
  internal/core/unittest/test_index_wrapper.cpp
  internal/core/unittest/test_indexing.cpp
  internal/core/unittest/test_utils/indexbuilder_test_utils.h
  internal/querynode/mock_test.go
  internal/util/indexparamcheck/conf_adapter.go
  internal/util/indexparamcheck/conf_adapter_mgr.go
  internal/util/indexparamcheck/conf_adapter_mgr_test.go
  internal/util/indexparamcheck/conf_adapter_test.go
  internal/util/indexparamcheck/index_type.go
  tests/python_client/deploy/common.py
  tests/python_client/deploy/scripts/utils.py
  tests/python_client/utils/util_pymilvus.py
Labels: kind/improvement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#23220 Remove legacy annoy_inner_error
  internal/core/src/common/Utils.h
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#23223 [cherry-pick][test]Remove annoy index type for deploy test
  tests/python_client/deploy/scripts/utils.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed, manual-pass

#23229 Remove annoy related unit tests
  internal/querynodev2/mock_data.go
  internal/querynodev2/segments/mock_data.go
  internal/util/indexcgowrapper/index_test.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#23140 Support queryHook in querynodev2
  internal/common/common.go
  internal/querynodev2/handlers.go
  internal/querynodev2/handlers_test.go
  internal/querynodev2/mock_query_hook.go
  internal/querynodev2/server.go
  internal/querynodev2/services.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#23242 Fix bug for type params when indexing
  internal/proxy/task_index.go
Labels: kind/bug, size/XS, lgtm

#23235 Fix metric ProxySyncTimeTickLag
  internal/proxy/proxy.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#23236 Fix metric RootCoordInsertChannelTimeTick
  internal/rootcoord/timeticksync.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#23239 split go and cpp ut
  .github/workflows/main.yaml
  scripts/run_cpp_codecov.sh
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#23249 Fix bug for type params when indexing (#23242)
  internal/proxy/task_index.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#23119 set query node thread pool size in milvus.yaml
  configs/milvus.yaml
  internal/core/src/segcore/segcore_init_c.cpp
  internal/core/src/segcore/segcore_init_c.h
  internal/querynode/query_node.go
  internal/util/paramtable/component_param.go
  internal/util/paramtable/component_param_test.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#23276 Fix MetaCache ut internal not changed
  internal/proxy/meta_cache_test.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#23248 Optimize unittest to save runtime
  internal/core/unittest/test_c_api.cpp
  internal/core/unittest/test_sealed.cpp
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#23266 Fix time tick lag too much (#23265)
  internal/rootcoord/timeticksync.go
Labels: kind/bug, kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#23267 Fix time tick lag too much (#23265)
  internal/rootcoord/timeticksync.go
Labels: kind/bug, kind/improvement, size/S, approved, lgtm, ci-passed, manual-pass

#23225 Add collectionID in logs
  internal/querycoordv2/server.go
  internal/rootcoord/root_coord.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#23102 Support show knowhere prometheus metrics
  cmd/roles/roles.go
  internal/core/src/segcore/CMakeLists.txt
  internal/core/src/segcore/metrics_c.cpp
  internal/core/src/segcore/metrics_c.h
  pkg/metrics/c_registry.go
  pkg/metrics/metrics_test.go
  pkg/metrics/milvus_registry.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed, area/compilation

#23271 Add slow log for read
  internal/proxy/impl.go
  internal/proxy/rpc_msg.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#23274 Add slow log for read
  internal/proxy/impl.go
  internal/proxy/rpc_msg.go
Labels: size/M, approved, lgtm, ci-passed, manual-pass

#23280 Add .git into upload list
  .github/workflows/main.yaml
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#23217 fix balance generate unexpect task
  internal/querycoordv2/balance/balance.go
  internal/querycoordv2/balance/balance_test.go
  internal/querycoordv2/balance/rowcount_based_balancer.go
  internal/querycoordv2/balance/rowcount_based_balancer_test.go
  internal/querycoordv2/balance/utils.go
  internal/querycoordv2/checkers/balance_checker.go
  internal/querycoordv2/meta/target_manager.go
  internal/querycoordv2/task/scheduler.go
  internal/querycoordv2/task/utils.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#23254 Fix proxy panicking when QueryCoord offline
  internal/proxy/impl.go
  internal/proxy/impl_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#23270 Fix compile error on MacOS
  .github/workflows/mac.yaml
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed, area/compilation, manual-pass

#23193 [MEP] Search by primary keys
  docs/design_docs/20230403-search_by_pk.md
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#23227 enable balance channel
  internal/querycoordv2/balance/rowcount_based_balancer.go
  internal/querycoordv2/balance/rowcount_based_balancer_test.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#23292 fix set task proirity
  internal/querycoordv2/balance/utils.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#23234 Modify test case of load balance
  tests/python_client/testcases/test_utility.py
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#23237 Add test cases of search partition
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#23216 fix bug when syncing distribution without schema and remove unused logic
  Makefile
  internal/proto/query_coord.proto
  internal/proto/querypb/query_coord.pb.go
  internal/querycoordv2/observers/leader_observer.go
  internal/querycoordv2/observers/leader_observer_test.go
  internal/querycoordv2/utils/test.go
  internal/querynodev2/delegator/delegator_data.go
  internal/querynodev2/delegator/distribution.go
  internal/querynodev2/services.go
  internal/querynodev2/services_test.go
Labels: size/XL, approved, lgtm, ci-passed, area/internal-api, dco-passed, area/compilation

#23298 Fix DescribeCollection failed with undefined msg type (#23192)
  internal/datacoord/server.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, manual-pass

#23257 [Cherry-Pick] Fix proxy panicking when QueryCoord offline
  internal/proxy/impl.go
  internal/proxy/impl_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#23307 enhance segment balance by considering global rowCount(##22914)
  internal/querycoordv2/balance/balance.go
  internal/querycoordv2/balance/balance_test.go
  internal/querycoordv2/balance/mock_balancer.go
  internal/querycoordv2/balance/priority_queue_test.go
  internal/querycoordv2/balance/rowcount_based_balancer.go
  internal/querycoordv2/balance/rowcount_based_balancer_test.go
  internal/querycoordv2/balance/score_based_balancer.go
  internal/querycoordv2/balance/score_based_balancer_test.go
  internal/querycoordv2/balance/utils.go
  internal/querycoordv2/checkers/controller.go
  internal/querycoordv2/checkers/segment_checker.go
  internal/querycoordv2/checkers/segment_checker_test.go
  internal/querycoordv2/handlers.go
  internal/querycoordv2/server.go
  internal/querycoordv2/server_test.go
  internal/querycoordv2/task/mock_scheduler.go
  internal/querycoordv2/task/scheduler.go
  internal/util/paramtable/component_param.go
  internal/util/typeutil/set.go
  internal/util/typeutil/set_test.go
Labels: size/XXL, approved, lgtm, ci-passed, dco-passed

#23304 Check balance checker chore to 10s
  configs/milvus.yaml
  internal/querycoordv2/server.go
  pkg/util/paramtable/component_param.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#23305 Change balance check interval to 10s
  configs/milvus.yaml
  internal/querycoordv2/server.go
  internal/util/paramtable/component_param.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#23250 Fix bug for type params when indexing (#23242)
  internal/proxy/task_index.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#23090 Fix bug for batch delete files on gcp of minio (#23052)
  internal/datacoord/garbage_collector.go
  internal/storage/minio_chunk_manager.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#23265 Fix time tick lag too much
  internal/rootcoord/timeticksync.go
Labels: kind/bug, kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#23306 speedup upload
  .github/workflows/main.yaml
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#23310 Fix concurrent LRU
  internal/storage/vector_chunk_manager.go
  internal/util/cache/lru_cache.go
  internal/util/cache/lru_cache_test.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#23244 Fix metric ProxySyncTimeTickLag (#23235)
  internal/proxy/proxy.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#23245 Fix metric RootCoordInsertChannelTimeTick (#23236)
  internal/rootcoord/timeticksync.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#23282 Fix metric ProxySyncTimeTickLag (#23235)
  internal/proxy/proxy.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, manual-pass

#23284 Fix metric RootCoordInsertChannelTimeTick (#23236)
  internal/rootcoord/timeticksync.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, manual-pass

#23318 [cherry-pick]enable balance channel
  internal/querycoordv2/balance/rowcount_based_balancer.go
  internal/querycoordv2/balance/rowcount_based_balancer_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#23263 fix false memory toleration calculation when loading segments on qnode
  internal/datacoord/policy.go
  internal/querycoordv2/balance/utils.go
  internal/querynode/load_segment_task.go
  internal/querynode/segment_loader.go
  internal/util/hardware/hardware_info.go
  internal/util/hardware/hardware_info_test.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#23168 Refine codes of datanode buffer
  internal/datanode/buffer.go
  internal/datanode/buffer_test.go
  internal/datanode/data_sync_service.go
  internal/datanode/flow_graph_delete_node.go
  internal/datanode/flow_graph_delete_node_test.go
  internal/datanode/flow_graph_insert_buffer_node.go
  internal/datanode/flow_graph_insert_buffer_node_test.go
  internal/datanode/services.go
  scripts/start_cluster.sh
Labels: kind/improvement, size/XL, approved, lgtm, ci-passed, dco-passed, manual-pass

#23330 Fix knowhere cpp header files name
  internal/core/src/index/VectorMemIndex.cpp
  internal/core/src/index/VectorMemNMIndex.cpp
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#23334 fix balance segment cause panic
  internal/querycoordv2/balance/rowcount_based_balancer.go
  internal/querycoordv2/balance/rowcount_based_balancer_test.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#23312 Make pkg code change trigger ci workflow
  .github/workflows/code-checker.yaml
  .github/workflows/mac.yaml
  .github/workflows/main.yaml
  Makefile
  pkg/metrics/metrics.go
  pkg/mq/msgdispatcher/manager_test.go
  pkg/mq/msgdispatcher/mock_test.go
  pkg/util/paramtable/base_table.go
  scripts/run_go_codecov.sh
  scripts/run_go_unittest.sh
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed, area/compilation, manual-pass

#23290 Fix timetick block caused by dml task pop failed (#23277)
  internal/proxy/mock_channels_mgr_test.go
  internal/proxy/task_delete.go
  internal/proxy/task_delete_test.go
  internal/proxy/task_insert.go
  internal/proxy/task_insert_test.go
  internal/proxy/task_scheduler.go
  internal/proxy/task_scheduler_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#23277 Fix timetick block caused by dml task pop failed
  internal/proxy/mock_channels_mgr_test.go
  internal/proxy/task_delete.go
  internal/proxy/task_delete_test.go
  internal/proxy/task_insert.go
  internal/proxy/task_insert_test.go
  internal/proxy/task_scheduler.go
  internal/proxy/task_scheduler_test.go
  internal/proxy/task_upsert.go
  internal/proxy/task_upsert_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#23299 fix balance generate unexpected task
  internal/querycoordv2/balance/balance.go
  internal/querycoordv2/balance/balance_test.go
  internal/querycoordv2/balance/rowcount_based_balancer.go
  internal/querycoordv2/balance/rowcount_based_balancer_test.go
  internal/querycoordv2/balance/score_based_balancer.go
  internal/querycoordv2/balance/score_based_balancer_test.go
  internal/querycoordv2/balance/utils.go
  internal/querycoordv2/checkers/balance_checker.go
  internal/querycoordv2/task/utils.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#23316 Update pymilvus version to support python3.11
  tests/python_client/requirements.txt
Labels: kind/improvement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#23317 Update pymilvus version to support python3.11
  tests/python_client/requirements.txt
  tests/python_client/utils/util_k8s.py
Labels: kind/improvement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed, manual-pass

#23335 Fix bug: wrong logic on session delete
  internal/util/sessionutil/session_util.go
Labels: size/XS, approved, lgtm, ci-passed, manual-pass

#23321 Support Count(*) on querynodev2
  internal/querynodev2/handlers.go
  internal/querynodev2/segments/count_reducer.go
  internal/querynodev2/segments/count_reducer_test.go
  internal/querynodev2/segments/default_limit_reducer.go
  internal/querynodev2/segments/reducer.go
  internal/querynodev2/segments/reducer_test.go
  internal/querynodev2/segments/result.go
  internal/querynodev2/services.go
Labels: kind/feature, size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#23344 Fix bug: wrong logic on session delete
  internal/util/sessionutil/session_util.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#23032 Fix DataCoord's meta may be broken with DataNode of prior version (#23030)
  internal/datacoord/server.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#23353 Clean ANNOY params
  pkg/util/indexparamcheck/conf_adapter.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#23358 Wait safe signal before release growing
  internal/querynodev2/delegator/delegator_data.go
  internal/querynodev2/delegator/distribution.go
  internal/querynodev2/delegator/distribution_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#23259 Add test cases of load collection
  tests/python_client/testcases/test_collection.py
Labels: sig/testing, size/XL, approved, lgtm, area/test, ci-passed, dco-passed

#23371 Remove lib reportportal
  tests/python_client/requirements.txt
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#23375 Forbid counting entities with pagination
  internal/proxy/task_query.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#23385 [skip e2e][test]Fix crd for deploy
  tests/python_client/deploy/milvus_crd.yaml
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#23107 Support async refresh
  go.mod
  go.sum
  internal/proto/query_coord.proto
  internal/proto/querypb/query_coord.pb.go
  internal/proxy/impl.go
  internal/proxy/util.go
  internal/querycoordv2/meta/collection_manager.go
  internal/querycoordv2/observers/target_observer.go
  internal/querycoordv2/services.go
  internal/querycoordv2/services_test.go
Labels: kind/feature, area/dependency, size/XXL, approved, lgtm, ci-passed, area/internal-api, dco-passed, manual-pass

#23382 Revert "Restrain gc files by collection (#22504) (#22518)"
  internal/datacoord/garbage_collector.go
  internal/datacoord/garbage_collector_test.go
  internal/datacoord/server.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#23190 Check leader ready before transfer load/release
  internal/querynode/impl_utils.go
  internal/querynode/impl_utils_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#23387 Add query count(*) test cases
  tests/python_client/common/common_type.py
  tests/python_client/testcases/test_collection.py
  tests/python_client/testcases/test_query.py
Labels: kind/improvement, sig/testing, size/XL, approved, lgtm, area/test, ci-passed, dco-passed

#23354 Add retry in recovery
  internal/querycoordv2/server.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#23388 Fix watch event timeout when IO Pool busy(#23293)
  configs/milvus.yaml
  internal/datanode/data_sync_service.go
  internal/util/paramtable/component_param.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed

#23332 [Cherry-pick] Refine codes of datanode buffer (#23168)
  internal/datanode/buffer.go
  internal/datanode/buffer_test.go
  internal/datanode/data_node.go
  internal/datanode/data_sync_service.go
  internal/datanode/flow_graph_delete_node.go
  internal/datanode/flow_graph_delete_node_test.go
  internal/datanode/flow_graph_insert_buffer_node.go
  internal/datanode/flow_graph_insert_buffer_node_test.go
Labels: size/XL, approved, lgtm, ci-passed, dco-passed

#23380 Revert "Restrain gc files by collection (#22504)"
  internal/datacoord/garbage_collector.go
  internal/datacoord/garbage_collector_test.go
  internal/datacoord/server.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#22164 Exit component process when session key is deleted (#21658)
  cmd/tools/migration/migration/runner.go
  internal/datacoord/server.go
  internal/datacoord/server_test.go
  internal/datanode/data_node.go
  internal/indexnode/indexnode.go
  internal/proxy/proxy.go
  internal/querycoordv2/server.go
  internal/querynodev2/server.go
  internal/rootcoord/root_coord.go
  internal/util/sessionutil/session_util.go
  internal/util/sessionutil/session_util_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#23383 Revert "Restrain gc files by collection (#22504) (#22518)"
  internal/datacoord/garbage_collector.go
  internal/datacoord/garbage_collector_test.go
  internal/datacoord/server.go
Labels: size/L, approved, lgtm, ci-passed, manual-pass

#23366 Ignore gather c metrics fail
  pkg/metrics/milvus_registry.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#23395 Define array type and ANNS syntax
  internal/mysqld/parser/antlrparser/parser/MySqlLexer.g4
  internal/mysqld/parser/antlrparser/parser/MySqlLexer.interp
  internal/mysqld/parser/antlrparser/parser/MySqlLexer.tokens
  internal/mysqld/parser/antlrparser/parser/MySqlParser.g4
  internal/mysqld/parser/antlrparser/parser/MySqlParser.interp
  internal/mysqld/parser/antlrparser/parser/MySqlParser.tokens
  internal/mysqld/parser/antlrparser/parser/mysql_lexer.go
  internal/mysqld/parser/antlrparser/parser/mysql_parser.go
  internal/mysqld/parser/antlrparser/parser/mysqlparser_base_visitor.go
  internal/mysqld/parser/antlrparser/parser/mysqlparser_visitor.go
Labels: kind/improvement, size/XXL, approved, lgtm, ci-passed, dco-passed, manual-pass

#23391 Revert "Restrain gc files by collection (#22504) (#22518)"
  internal/datacoord/garbage_collector.go
  internal/datacoord/garbage_collector_test.go
  internal/datacoord/server.go
  internal/datanode/flow_graph_manager_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#23360 Add IoPoolSize config
  internal/querynodev2/segments/segment_loader.go
  internal/querynodev2/segments/segment_loader_test.go
  internal/querynodev2/server.go
  pkg/util/conc/pool.go
  pkg/util/paramtable/component_param.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#23418 Fix AddDistribution unit test
  internal/querynodev2/delegator/distribution_test.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#23394 Fix watcher loop quit and channel shouldDrop logic
  internal/common/common.go
  internal/datacoord/channel_checker.go
  internal/datacoord/channel_manager.go
  internal/datacoord/channel_manager_test.go
  internal/datacoord/channel_store.go
  internal/datacoord/handler.go
  internal/datacoord/server_test.go
  internal/datanode/data_node.go
  internal/datanode/flow_graph_dd_node.go
  internal/indexcoord/index_coord.go
  internal/querynode/shard_cluster_service_test.go
  internal/querynode/shard_node_detector.go
  internal/querynode/shard_segment_detector.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#23402 [Cherry-Pick] Fix watcher loop quit and channel shouldDrop logic
  internal/datacoord/channel_checker.go
  internal/datacoord/channel_manager.go
  internal/datacoord/channel_manager_test.go
  internal/datacoord/channel_store.go
  internal/datacoord/handler.go
  internal/datacoord/server_test.go
  internal/datanode/data_node.go
  internal/datanode/flow_graph_dd_node.go
  pkg/common/common.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#23426 Bump to v2.2.6
  deployments/binary/README.md
  deployments/docker/cluster/docker-compose-apple-silicon.yml
  deployments/docker/cluster/docker-compose.yml
  deployments/docker/standalone/docker-compose.yml
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#23412 Protect the QueryCoord meta from stale data migrated from old version
  internal/querycoordv2/job/job_load.go
  internal/querycoordv2/meta/collection_manager.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#23428 [skip e2e]Update slack invite link
  README.md
  README_CN.md
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#23390 Remove velox
  .github/workflows/mac.yaml
  internal/core/conanfile.py
  internal/core/src/segcore/CMakeLists.txt
  internal/core/src/segcore/VeloxDemo.cpp
  scripts/core_build.sh
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed, area/compilation

#23405 Fix task merge doesn't work
  internal/querynodev2/services_test.go
  internal/querynodev2/tasks/scheduler.go
  internal/querynodev2/tasks/task.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#23417 Update pymilvus version
  tests/python_client/requirements.txt
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#23439 Improve the check logic of channel remove
  internal/datacoord/channel_manager.go
  internal/datacoord/handler.go
  internal/datacoord/mock_test.go
  internal/datacoord/server.go
  internal/datacoord/server_test.go
  internal/datanode/flow_graph_manager_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#23286 Set query node thread pool size in milvus.yaml
  configs/milvus.yaml
  internal/core/src/segcore/segcore_init_c.cpp
  internal/core/src/segcore/segcore_init_c.h
  internal/querynodev2/server.go
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/component_param_test.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#23432 Optimize log trace (#23431)
  internal/rootcoord/broker.go
  internal/rootcoord/meta_table.go
  internal/rootcoord/root_coord.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#23398 remove segment from datanode meta when segment dropped
  internal/datanode/flush_manager.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#23431 Optimize log trace
  internal/rootcoord/broker.go
  internal/rootcoord/meta_table.go
  internal/rootcoord/root_coord.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#23293 use a large watchTimeoutInterval
  configs/milvus.yaml
  internal/datanode/data_sync_service.go
  pkg/util/paramtable/component_param.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#23369 Add range search integration test
  tests/integration/bulkinsert_test.go
  tests/integration/hello_milvus_test.go
  tests/integration/range_search_test.go
Labels: sig/testing, size/XL, approved, lgtm, area/test, ci-passed, dco-passed, manual-pass

#23437 Update knowhere version from main to commit_id
  internal/core/thirdparty/knowhere/CMakeLists.txt
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed, area/compilation

#23446 Fix Shard cluster hang
  internal/querynode/distribution.go
  internal/querynode/distribution_test.go
  internal/querynode/impl_utils_test.go
  internal/querynode/shard_cluster.go
  internal/querynode/shard_cluster_test.go
  internal/querynode/snapshot.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#23445 Fix Shard Cluster Hang
  internal/querynode/distribution.go
  internal/querynode/distribution_test.go
  internal/querynode/impl_utils_test.go
  internal/querynode/shard_cluster.go
  internal/querynode/shard_cluster_test.go
  internal/querynode/snapshot.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#23438 Protect the QueryCoord meta from stale data migrated from old version (#23412)
  internal/querycoordv2/meta/collection_manager.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#23466 Fix compile error: dup code
  tests/integration/hello_milvus_test.go
Labels: kind/bug, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed, manual-pass

#23473 Improve the check logic of channel remove
  internal/datacoord/channel_manager.go
  internal/datacoord/handler.go
  internal/datacoord/mock_test.go
  internal/datacoord/server.go
  internal/datacoord/server_test.go
  internal/datanode/flow_graph_manager_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#23472 Improve the check logic of channel remove (#23439)
  internal/datacoord/channel_manager.go
  internal/datacoord/handler.go
  internal/datacoord/mock_test.go
  internal/datacoord/server.go
  internal/datacoord/server_test.go
  internal/datanode/flow_graph_manager_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#23463 Support to parse ANNS plan node
  internal/mysqld/parser/antlrparser/ast_builder.go
  internal/mysqld/parser/antlrparser/node_ret.go
  internal/mysqld/parser/antlrparser/parser_test.go
  internal/mysqld/planner/anns_clause.go
  internal/mysqld/planner/binary_vector.go
  internal/mysqld/planner/float_vector.go
  internal/mysqld/planner/kv_pair.go
  internal/mysqld/planner/query_specification.go
  internal/mysqld/planner/vector.go
  internal/mysqld/planner/visitor.go
  internal/mysqld/planner/visitor_expression_text_restorer.go
  internal/mysqld/planner/visitor_json.go
  internal/mysqld/sqlutil/conv.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#23325 fix pull target
  internal/datacoord/handler.go
  internal/datacoord/mock_test.go
  internal/datacoord/services.go
  internal/datacoord/services_test.go
  internal/distributed/datacoord/client/client.go
  internal/distributed/datacoord/client/client_test.go
  internal/distributed/datacoord/service.go
  internal/distributed/proxy/service_test.go
  internal/mocks/mock_datacoord.go
  internal/proto/data_coord.proto
  internal/proto/datapb/data_coord.pb.go
  internal/querycoordv2/balance/rowcount_based_balancer_test.go
  internal/querycoordv2/balance/score_based_balancer_test.go
  internal/querycoordv2/checkers/channel_checker_test.go
  internal/querycoordv2/checkers/segment_checker_test.go
  internal/querycoordv2/job/job_test.go
  internal/querycoordv2/meta/coordinator_broker.go
  internal/querycoordv2/meta/coordinator_broker_test.go
  internal/querycoordv2/meta/mock_broker.go
  internal/querycoordv2/meta/target_manager.go
  internal/querycoordv2/meta/target_manager_test.go
  internal/querycoordv2/observers/collection_observer_test.go
  internal/querycoordv2/observers/leader_observer_test.go
  internal/querycoordv2/observers/target_observer_test.go
  internal/querycoordv2/server_test.go
  internal/querycoordv2/services_test.go
  internal/querycoordv2/task/task_test.go
  internal/types/types.go
  internal/util/mock/grpc_datacoord_client.go
Labels: kind/enhancement, size/XXL, approved, lgtm, ci-passed, dco-passed

#23478 [skip e2e] [DOC] Add QueryNodev2 design doc
  docs/design_docs/20230418-querynode_v2.md
  docs/design_docs/graphs/pk_oracle.png
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, kind/developer-doc, dco-passed

#23488 [skip e2e] Update minio&etcd version
  deployments/docker/cluster-distributed-deployment/roles/deploy-etcd/tasks/main.yml
  deployments/docker/cluster-distributed-deployment/roles/deploy-minio/tasks/main.yml
  deployments/docker/cluster/docker-compose-apple-silicon.yml
  deployments/docker/cluster/docker-compose.yml
  deployments/docker/dev/docker-compose-apple-silicon.yml
  deployments/docker/dev/docker-compose.yml
  deployments/docker/standalone/docker-compose.yml
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#23489 [skip e2e] Add OWNERS files for querycoordv2 sub pkgs
  internal/querycoordv2/balance/OWNERS
  internal/querycoordv2/checkers/OWNERS
  internal/querycoordv2/dist/OWNERS
  internal/querycoordv2/job/OWNERS
  internal/querycoordv2/meta/OWNERS
  internal/querycoordv2/observers/OWNERS
  internal/querycoordv2/params/OWNERS
  internal/querycoordv2/session/OWNERS
  internal/querycoordv2/task/OWNERS
  internal/querycoordv2/utils/OWNERS
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#23484 [test]Fix get collection for chaos test
  tests/python_client/chaos/testcases/test_all_collections_after_chaos.py
  tests/python_client/utils/util_common.py
Labels: kind/improvement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#23485 [test]Fix get collection for chaos test
  tests/python_client/chaos/testcases/test_all_collections_after_chaos.py
  tests/python_client/utils/util_common.py
Labels: kind/improvement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#23471 Update pymilvus version
  tests/python_client/requirements.txt
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#23480 Add log in AddImportSegment.getChannelLatestMsgID
  internal/datanode/data_sync_service.go
  internal/datanode/services.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#23494 Add log in AddImportSegment.getChannelLatestMsgID
  internal/datanode/data_sync_service.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#23493 Add Close method for ChannelManager in datacoord
  internal/datacoord/channel_manager.go
  internal/datacoord/cluster.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#23487 Fix querynodev2 stop logic
  internal/querynodev2/server.go
  pkg/mq/msgdispatcher/client.go
  pkg/mq/msgdispatcher/mock_client.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#23491 fix pull target
  Makefile
  internal/datacoord/handler.go
  internal/datacoord/mock_test.go
  internal/datacoord/services.go
  internal/datacoord/services_test.go
  internal/datanode/allocator/mock_allocator.go
  internal/distributed/datacoord/client/client.go
  internal/distributed/datacoord/client/client_test.go
  internal/distributed/datacoord/service.go
  internal/distributed/proxy/service_test.go
  internal/mocks/mock_datacoord.go
  internal/proto/data_coord.proto
  internal/proto/datapb/data_coord.pb.go
  internal/querycoordv2/balance/mock_balancer.go
  internal/querycoordv2/balance/rowcount_based_balancer_test.go
  internal/querycoordv2/balance/score_based_balancer_test.go
  internal/querycoordv2/checkers/channel_checker_test.go
  internal/querycoordv2/checkers/segment_checker_test.go
  internal/querycoordv2/job/job_test.go
  internal/querycoordv2/meta/coordinator_broker.go
  internal/querycoordv2/meta/coordinator_broker_test.go
  internal/querycoordv2/meta/mock_broker.go
  internal/querycoordv2/meta/mock_store.go
  internal/querycoordv2/meta/target_manager.go
  internal/querycoordv2/meta/target_manager_test.go
  internal/querycoordv2/mocks/mock_querynode.go
  internal/querycoordv2/observers/collection_observer_test.go
  internal/querycoordv2/observers/leader_observer_test.go
  internal/querycoordv2/observers/target_observer_test.go
  internal/querycoordv2/server_test.go
  internal/querycoordv2/services_test.go
  internal/querycoordv2/session/mock_cluster.go
  internal/querycoordv2/task/mock_scheduler.go
  internal/querycoordv2/task/task_test.go
  internal/types/types.go
  internal/util/mock/grpc_datacoord_client.go
Labels: size/XXL, approved, lgtm, ci-passed, dco-passed, area/compilation

#23490 skip to balance redundant segment
  internal/querycoordv2/balance/rowcount_based_balancer.go
  internal/querycoordv2/balance/rowcount_based_balancer_test.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#23459 protect balance parameters by setting legal range(#23454)
  internal/util/paramtable/component_param.go
  internal/util/paramtable/component_param_test.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#23468 support detailed querycoord task metrics(#23414)
  internal/metrics/querycoord_metrics.go
  internal/querycoordv2/task/scheduler.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#23507 Fix test_watch_channel unit test unstable
  internal/datanode/data_node_test.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#23503 Upgrade to knowhere-v1.3.12
  internal/core/thirdparty/knowhere/CMakeLists.txt
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed, area/compilation

#23453 Opt compile time for Mac
  .github/workflows/mac.yaml
  internal/core/CMakeLists.txt
  internal/core/cmake/BuildUtils.cmake
  scripts/core_build.sh
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed, area/compilation, manual-pass

#23524 Fix data race of timerecord
  internal/querynodev2/tasks/scheduler.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#23533 Revert "Opt compile time for Mac (#23453)"
  .github/workflows/mac.yaml
  internal/core/CMakeLists.txt
  internal/core/cmake/BuildUtils.cmake
  scripts/core_build.sh
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed, area/compilation, manual-pass

#23455 refine balance mechanism by pruning code and support urgent stopping
  internal/querycoordv2/balance/balance.go
  internal/querycoordv2/balance/mock_balancer.go
  internal/querycoordv2/balance/rowcount_based_balancer.go
  internal/querycoordv2/balance/rowcount_based_balancer_test.go
  internal/querycoordv2/balance/score_based_balancer.go
  internal/querycoordv2/balance/score_based_balancer_test.go
  internal/querycoordv2/balance/utils.go
  internal/querycoordv2/checkers/balance_checker.go
  internal/querycoordv2/checkers/balance_checker_test.go
  internal/querycoordv2/checkers/controller.go
  internal/querynode/distribution.go
Labels: size/XL, approved, lgtm, ci-passed, dco-passed

#23535 Add mac workflow for test
  .github/workflows/new_mac.yaml
Labels: size/M, do-not-merge/hold, do-not-merge/missing-related-issue, dco-passed, needs-rebase

#23515 Modify test cases and add case of ignore growing
  tests/python_client/testcases/test_collection.py
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed
