Repository milvus-io/milvus, pull requests merged in 2023-06, with the labels that each got.

#24562 Return to be indexed rows when describe index
  go.mod
  go.sum
  internal/indexcoord/index_coord.go
  internal/indexcoord/index_coord_mock.go
  internal/indexcoord/index_coord_test.go
  internal/proto/index_coord.proto
  internal/proto/indexpb/index_coord.pb.go
  internal/proxy/task_index.go
  tests/python_client/requirements.txt
  tests/python_client/testcases/test_utility.py
Labels: area/dependency, sig/testing, size/XL, approved, lgtm, area/test, ci-passed, area/internal-api, dco-passed

#24583 Assign metric type in search request when user has not explicitly assigned
  internal/core/src/segcore/plan_c.cpp
  internal/core/src/segcore/plan_c.h
  internal/proto/query_coord.proto
  internal/proto/querypb/query_coord.pb.go
  internal/proxy/task_search_test.go
  internal/querycoordv2/meta/coordinator_broker.go
  internal/querycoordv2/meta/mock_broker.go
  internal/querycoordv2/server_test.go
  internal/querycoordv2/task/executor.go
  internal/querycoordv2/task/task_test.go
  internal/querycoordv2/task/utils.go
  internal/querycoordv2/task/utils_test.go
  internal/querynode/collection.go
  internal/querynode/collection_test.go
  internal/querynode/impl.go
  internal/querynode/plan.go
  internal/querynode/watch_dm_channels_task.go
  tests/python_client/common/common_type.py
  tests/python_client/testcases/test_search.py
Labels: kind/enhancement, sig/testing, size/XL, approved, lgtm, area/test, ci-passed, area/internal-api, dco-passed, manual-pass

#24571 add metrics for assinging segments on proxy(#24570)
  internal/metrics/proxy_metrics.go
  internal/proxy/segment.go
  internal/proxy/task_insert.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#24569 [cherry-pick] Fix bug of bulkinsert for dynamic field
  internal/util/importutil/import_util.go
  internal/util/importutil/numpy_parser.go
  internal/util/importutil/numpy_parser_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#24587 Update pymilvus version
  tests/python_client/requirements.txt
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#24574 Retry keepalive when keepalive channel close
  internal/util/sessionutil/session_util.go
  internal/util/sessionutil/session_util_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#24581 Retry keepalive when keepalive channel close
  internal/util/sessionutil/session_util.go
  internal/util/sessionutil/session_util_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#24591 Assign metric type in search request when user has not explicitly assigned (#24583)
  internal/core/src/segcore/plan_c.cpp
  internal/core/src/segcore/plan_c.h
  internal/proto/query_coord.proto
  internal/proto/querypb/query_coord.pb.go
  internal/querycoordv2/task/executor.go
  internal/querycoordv2/task/task_test.go
  internal/querycoordv2/task/utils.go
  internal/querycoordv2/task/utils_test.go
  internal/querynodev2/segments/collection.go
  internal/querynodev2/segments/plan.go
  internal/querynodev2/services.go
  tests/python_client/common/common_type.py
  tests/python_client/testcases/test_search.py
Labels: kind/enhancement, sig/testing, size/XL, approved, lgtm, area/test, ci-passed, area/internal-api, dco-passed

#24588 Support return pending index rows when describe index
  go.mod
  go.sum
  internal/datacoord/index_service.go
  internal/datacoord/index_service_test.go
  internal/proto/index_coord.proto
  internal/proto/indexpb/index_coord.pb.go
  internal/proxy/task_index.go
  tests/python_client/requirements.txt
  tests/python_client/testcases/test_utility.py
Labels: area/dependency, sig/testing, size/L, approved, lgtm, area/test, ci-passed, area/internal-api, dco-passed

#24596 Fix potential crash bug of bulkinsert
  internal/datanode/data_node.go
  internal/datanode/data_node_test.go
  internal/datanode/mock_test.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed

#24610 Fix aws-c-cal lib missing
  internal/core/conanfile.py
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#24612 add independent nq limit option
  internal/proxy/task_query.go
  internal/proxy/task_search.go
  internal/proxy/util.go
  internal/proxy/util_test.go
  internal/util/paramtable/component_param.go
  internal/util/paramtable/quota_param.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#24375 [db] Update flush cases for db issue fixed
  tests/python_client/requirements.txt
  tests/python_client/testcases/test_database.py
  tests/python_client/testcases/test_utility.py
Labels: kind/improvement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#24603 Fix db name is empty for describe collection response
  internal/proxy/impl.go
  internal/rootcoord/describe_collection_task.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#24561 Add test cases of AutoIndex
  tests/python_client/base/collection_wrapper.py
  tests/python_client/common/common_func.py
  tests/python_client/testcases/test_index.py
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#24624 Optimize the penalty mechanism for exceeding rate limits
  internal/proxy/multi_rate_limiter.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#24628 Fix show loaded collections
  internal/proxy/task.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#24631 [skip e2e]Bump milvus version to v2.2.9
  deployments/binary/README.md
  deployments/docker/standalone/docker-compose.yml
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#24513 Add test cases of load partition
  tests/python_client/testcases/test_collection.py
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#24629 Fix show loaded collections (#24628)
  internal/proxy/task.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#24653 Add RBAC for Database API
  internal/util/constant.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#24627 Add pkg-config to brew install when using x86 Mac
  scripts/install_deps.sh
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#24047 Support partition Key
  internal/core/src/pb/plan.pb.cc
  internal/core/src/pb/plan.pb.h
  internal/core/src/pb/schema.pb.cc
  internal/core/src/pb/schema.pb.h
  internal/metastore/model/field.go
  internal/parser/planparserv2/parser_visitor.go
  internal/proto/plan.proto
  internal/proto/planpb/plan.pb.go
  internal/proxy/expr_checker.go
  internal/proxy/expr_checker_test.go
  internal/proxy/impl.go
  internal/proxy/mock_test.go
  internal/proxy/msg_pack.go
  internal/proxy/msg_pack_test.go
  internal/proxy/plan_parser.go
  internal/proxy/rootcoord_mock_test.go
  internal/proxy/task.go
  internal/proxy/task_delete.go
  internal/proxy/task_insert.go
  internal/proxy/task_query.go
  internal/proxy/task_search.go
  internal/proxy/task_statistic_test.go
  internal/proxy/task_test.go
  internal/proxy/task_upsert.go
  internal/proxy/util.go
  internal/rootcoord/create_collection_task.go
  internal/rootcoord/create_collection_task_test.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
  internal/util/flowgraph/message_test.go
  internal/util/typeutil/hash.go
  pkg/common/common.go
  pkg/mq/msgstream/mq_msgstream_test.go
  pkg/mq/msgstream/msg.go
  pkg/util/typeutil/hash.go
  pkg/util/typeutil/schema.go
  tests/python_client/testcases/test_collection.py
Labels: area/dependency, sig/testing, size/XXL, approved, lgtm, area/test, ci-passed, dco-passed

#24525 Add json and dynamic support cases
  tests/python_client/base/client_base.py
  tests/python_client/check/func_check.py
  tests/python_client/common/common_func.py
  tests/python_client/common/common_type.py
  tests/python_client/testcases/test_collection.py
  tests/python_client/testcases/test_delete.py
  tests/python_client/testcases/test_index.py
  tests/python_client/testcases/test_insert.py
  tests/python_client/testcases/test_query.py
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/XL, approved, lgtm, area/test, ci-passed, dco-passed

#24593 Modify test cases for some updates
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#24636 Add test cases of default value
  tests/python_client/common/common_func.py
  tests/python_client/requirements.txt
  tests/python_client/testcases/test_collection.py
  tests/python_client/testcases/test_insert.py
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#24594 Try to fix new added nightly pipeline
  ci/jenkins/Nightly.groovy
  tests/python_client/deploy/testcases/test_action_after_reinstall.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#24665 Set metric type while init the collection
  internal/querynodev2/segments/collection.go
  internal/querynodev2/services.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#24666 Remove Ubuntu18.04 support
  .github/workflows/publish-builder.yaml
  DEVELOPMENT.md
  build/README.md
  build/docker/builder/cpu/ubuntu18.04/Dockerfile
  build/docker/heaptrack/Dockerfile
  build/docker/milvus/ubuntu18.04/Dockerfile
  build/docker/openblas/ubuntu18.04/Dockerfile
  scripts/README.md
  scripts/install_deps.sh
  scripts/install_deps_embd.sh
  tests/benchmark/ci/publish_jenkinsfile
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#24671 Add array_at method to get array from JSON
  internal/core/src/common/Json.h
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#24625 [cherry-pick] Disable search params rewrite while searching with filter
  internal/querynodev2/handlers.go
  pkg/common/common.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#24661 Use SA_ONSTACK flag for SIGPIPE handler
  internal/core/src/storage/MinioChunkManager.cpp
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#24670 Fix NoSuchKey error caused by special stats log
  internal/storage/types.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#24651 Fix build index performance downgrade
  internal/core/src/storage/MinioChunkManager.cpp
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#24691 Fix search failed due to metric type mismatch
  internal/querycoordv2/task/executor.go
  internal/querycoordv2/task/task_test.go
  internal/querynodev2/services.go
  internal/querynodev2/services_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#24667 Fix retryKeepAlive assertion panic
  internal/util/sessionutil/session_util.go
  internal/util/sessionutil/session_util_test.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#24620 Update pymilvus version
  tests/python_client/requirements.txt
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#24632 add independent nq limit option
  internal/proxy/reducer.go
  internal/proxy/task_query.go
  internal/proxy/task_search.go
  internal/proxy/util.go
  internal/proxy/util_test.go
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/quota_param.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#24669 Use only one go.mod
  Makefile
  go.mod
  go.sum
  pkg/go.mod
  pkg/go.sum
  scripts/run_go_codecov.sh
Labels: area/dependency, kind/improvement, sig/testing, size/XXL, approved, lgtm, area/test, ci-passed, area/internal-api, dco-passed, area/compilation

#24701 Add partition_key tests
  tests/python_client/common/common_func.py
  tests/python_client/testcases/test_partition_key.py
  tests/python_client/testcases/test_resourcegroup.py
Labels: sig/testing, size/XL, approved, lgtm, area/test, ci-passed, dco-passed

#24652 Check metric type before search
  internal/querynodev2/services.go
  internal/querynodev2/services_test.go
  tests/python_client/testcases/test_search.py
Labels: kind/enhancement, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#24678 Add proto field to support reverse in
  internal/core/src/pb/plan.pb.cc
  internal/core/src/pb/plan.pb.h
  internal/proto/plan.proto
  internal/proto/planpb/plan.pb.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#24710 Add partition_key tests
  tests/python_client/common/common_func.py
  tests/python_client/testcases/test_partition_key.py
  tests/python_client/testcases/test_resourcegroup.py
Labels: sig/testing, size/XL, approved, lgtm, area/test, ci-passed, dco-passed

#24707 Upgrade golangci-lint
  .golangci.yml
  Makefile
  go.mod
  go.sum
  internal/http/server.go
  internal/proxy/interface_def.go
  internal/proxy/mock_tso_test.go
  internal/proxy/task_policies.go
  internal/querynodev2/cluster/mock_manager.go
  internal/querynodev2/delegator/mock_delegator.go
  internal/querynodev2/pipeline/delete_node.go
  internal/querynodev2/pipeline/filter_node_test.go
  internal/querynodev2/pipeline/pipeline.go
  internal/querynodev2/segments/mock_loader.go
  internal/querynodev2/segments/mock_segment.go
  internal/querynodev2/segments/segment.go
  internal/querynodev2/tsafe/tsafe_test.go
  internal/storage/aliyun/aliyun.go
  internal/storage/data_codec.go
  internal/util/pipeline/node.go
  pkg/util/funcutil/math.go
Labels: area/dependency, kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed, area/compilation, manual-pass

#24682 Update count* cases for issue fixed
  tests/python_client/testcases/test_query.py
Labels: kind/improvement, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#24698 Modify test cases
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#24711 Update test cases nightly
  tests/python_client/testcases/test_collection.py
  tests/python_client/testcases/test_insert.py
  tests/python_client/testcases/test_query.py
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#24563 Add test cases of AutoIndex master
  tests/python_client/base/collection_wrapper.py
  tests/python_client/common/common_func.py
  tests/python_client/testcases/test_index.py
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#24719 Fix getting partitions in Proxy meta cache
  internal/proxy/meta_cache.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#24714 Bump semver to 2.2.10-pre+dev
  internal/common/version.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#24722 Fix creating collection not idempotent (#24721)
  internal/metastore/model/field.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#24739 Fix data race in MetaCache
  internal/proxy/meta_cache.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#24737 [test]Reduce batches to avoid exceeding request body size limit
  tests/python_client/chaos/checker.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#24729 [MetaKV refactory part 1]clean up meta interface
  docs/developer_guides/appendix_a_basic_components.md
  internal/datacoord/mock_test.go
  internal/datacoord/server.go
  internal/indexnode/task_test.go
  internal/kv/etcd/embed_etcd_kv.go
  internal/kv/etcd/embed_etcd_kv_test.go
  internal/kv/etcd/etcd_kv.go
  internal/kv/etcd/etcd_kv_test.go
  internal/kv/kv.go
  internal/querynodev2/server.go
Labels: size/XL, approved, lgtm, ci-passed, dco-passed

#24741 [Cherry-Pick] Fix confusing log while plugin is not enabled
  internal/querynodev2/server.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#24656 Add go payload writer
  go.mod
  internal/storage/event_writer.go
  internal/storage/payload.go
  internal/storage/payload_cgo_test.go
  internal/storage/payload_reader_test.go
  internal/storage/payload_test.go
  internal/storage/payload_writer.go
Labels: area/dependency, kind/improvement, size/XL, approved, lgtm, ci-passed, dco-passed

#24734 Add ut to check if two collections are identical
  internal/metastore/model/collection.go
  internal/metastore/model/collection_test.go
  internal/metastore/model/field_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#24735 Fix confusing log while plugin is not enabled
  internal/querynode/query_node.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#24412 Fix querynode read quota
  internal/querynodev2/collector/average.go
  internal/querynodev2/collector/counter.go
  internal/querynodev2/collector/counter_test.go
  internal/querynodev2/handlers.go
  internal/querynodev2/metrics_info.go
  internal/querynodev2/tasks/scheduler.go
  internal/querynodev2/tasks/task.go
  internal/rootcoord/quota_center.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#24748 [test]Skip new feature in upgrade deploy test cases
  tests/python_client/base/client_base.py
  tests/python_client/chaos/testcases/test_all_collections_after_chaos.py
  tests/python_client/common/common_func.py
  tests/python_client/deploy/testcases/test_action_first_deployment.py
  tests/python_client/deploy/testcases/test_action_second_deployment.py
  tests/python_client/testcases/test_query.py
Labels: kind/improvement, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#24743 Remove unused iterator initialization
  internal/kv/rocksdb/rocks_iterator.go
  internal/kv/rocksdb/rocksdb_kv.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#24755 Add RBAC for FlushAll (#24751)
  go.mod
  go.sum
  internal/core/src/pb/common.pb.cc
  internal/core/src/pb/common.pb.h
  internal/util/constant.go
Labels: kind/enhancement, area/dependency, size/M, approved, lgtm, ci-passed, dco-passed

#24716 Check metric type before search (#24652)
  internal/querynode/impl.go
  internal/querynode/impl_test.go
  tests/python_client/testcases/test_search.py
Labels: kind/enhancement, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#24765 Add metric of waiting for tSafe latency
  internal/querynodev2/delegator/delegator.go
  pkg/metrics/querynode_metrics.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#24773 Fix update-api-version.sh for master branch
  scripts/download_milvus_proto.sh
  scripts/update-api-version.sh
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#24762 Add go payload writer (#24656)
  go.mod
  internal/storage/event_writer.go
  internal/storage/payload.go
  internal/storage/payload_reader_test.go
  internal/storage/payload_test.go
  internal/storage/payload_writer.go
Labels: area/dependency, kind/improvement, size/XL, approved, lgtm, ci-passed, dco-passed

#24774 Fix download&update-api-version.sh for 2.2.0 branch
  Makefile
  scripts/download_milvus_proto.sh
  scripts/update-api-version.sh
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed, area/compilation

#24758 [Cherry-Pick] Remove unused iterator initialization
  internal/kv/rocksdb/rocks_iterator.go
  internal/kv/rocksdb/rocksdb_kv.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#24720 Support json_contains for json field
  internal/parser/planparserv2/Plan.g4
  internal/parser/planparserv2/generated/Plan.interp
  internal/parser/planparserv2/generated/Plan.tokens
  internal/parser/planparserv2/generated/PlanLexer.interp
  internal/parser/planparserv2/generated/PlanLexer.tokens
  internal/parser/planparserv2/generated/plan_base_visitor.go
  internal/parser/planparserv2/generated/plan_lexer.go
  internal/parser/planparserv2/generated/plan_parser.go
  internal/parser/planparserv2/generated/plan_visitor.go
  internal/parser/planparserv2/parser_visitor.go
  internal/parser/planparserv2/plan_parser_v2.go
  internal/parser/planparserv2/plan_parser_v2_test.go
Labels: size/XXL, approved, lgtm, ci-passed, dco-passed

#24775 Fix autoindex filter bug
  internal/querynodev2/handlers.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#24795 [skip e2e]Fix etcd leader or followers chaos test
  tests/python_client/chaos/test_chaos_apply_to_determined_pod.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#24784 Use collInfo instead of reading again
  internal/proxy/meta_cache.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#24777 Fix aws-c-io not found
  internal/core/conanfile.py
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#24788 Fix list milvus-proto go.mod when try to parse API_VERSION
  scripts/download_milvus_proto.sh
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#24786 Remove metric_type check and fix some minor bugs
  configs/milvus.yaml
  internal/proxy/meta_cache.go
  internal/proxy/task_search.go
  internal/proxy/task_search_test.go
  internal/util/paramtable/autoindex_param.go
  tests/python_client/common/common_type.py
  tests/python_client/requirements.txt
  tests/python_client/testcases/test_collection.py
Labels: kind/bug, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#24589 Implement GetIndexStatistics interface
  Makefile
  internal/datacoord/garbage_collector_test.go
  internal/datacoord/server_test.go
  internal/datacoord/services_test.go
  internal/distributed/datacoord/service_test.go
  internal/distributed/indexcoord/client/client.go
  internal/distributed/indexcoord/client/client_test.go
  internal/distributed/indexcoord/service.go
  internal/distributed/proxy/service_test.go
  internal/indexcoord/index_coord.go
  internal/indexcoord/index_coord_mock.go
  internal/indexcoord/index_coord_test.go
  internal/mocks/mock_datacoord.go
  internal/mocks/mock_indexcoord.go
  internal/proto/index_coord.proto
  internal/proto/indexpb/index_coord.pb.go
  internal/proxy/impl.go
  internal/proxy/index_coord_mock_test.go
  internal/proxy/proxy_test.go
  internal/proxy/task_index.go
  internal/proxy/task_index_test.go
  internal/types/types.go
Labels: size/XXL, approved, lgtm, ci-passed, area/internal-api, dco-passed, area/compilation

#24783 Improve the panic code about the milvus component
  cmd/components/data_coord.go
  cmd/components/data_node.go
  cmd/components/index_coord.go
  cmd/components/index_node.go
  cmd/components/proxy.go
  cmd/components/query_coord.go
  cmd/components/query_node.go
  cmd/components/root_coord.go
  cmd/roles/roles.go
  internal/util/dependency/factory.go
  internal/util/paramtable/component_param.go
Labels: priority/critical-urgent, kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#24766 Fix load collection failed after drop partition (#24680)
  internal/querycoordv2/meta/collection_manager.go
  internal/querycoordv2/meta/collection_manager_test.go
  internal/querycoordv2/meta/coordinator_broker.go
  internal/querycoordv2/meta/coordinator_broker_test.go
  internal/querycoordv2/server.go
  internal/querycoordv2/server_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#24807 Update Knowhere to 1.3.16 & Check HNSW config before search
  internal/core/src/index/VectorDiskIndex.cpp
  internal/core/src/index/VectorMemIndex.cpp
  internal/core/thirdparty/knowhere/CMakeLists.txt
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed, area/compilation, manual-pass

#24789 [2.2] Fix list milvus-proto go.mod when try to parse API_VERSION
  scripts/download_milvus_proto.sh
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#24824 Add sa_mask for SIGPIPE handler
  internal/core/src/storage/MinioChunkManager.cpp
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#24752 Update test cases nightly
  tests/python_client/testcases/test_collection.py
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#24796 Fix deleted data is still visible
  internal/querynode/flow_graph_delete_node.go
  internal/querynode/flow_graph_insert_node.go
  internal/querynode/flow_graph_insert_node_test.go
  internal/querynode/load_segment_task_test.go
  internal/querynode/segment.go
  internal/querynode/segment_loader.go
  internal/querynode/segment_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#24367 refactor replica selection and retry policy on channel
  Makefile
  internal/proxy/impl.go
  internal/proxy/lb_balancer.go
  internal/proxy/lb_policy.go
  internal/proxy/lb_policy_test.go
  internal/proxy/meta_cache.go
  internal/proxy/mock_lb_balancer.go
  internal/proxy/mock_lb_policy.go
  internal/proxy/mock_shardclient_manager.go
  internal/proxy/proxy.go
  internal/proxy/roundrobin_balancer.go
  internal/proxy/roundrobin_balancer_test.go
  internal/proxy/shard_client.go
  internal/proxy/task_policies.go
  internal/proxy/task_query.go
  internal/proxy/task_query_test.go
  internal/proxy/task_search.go
  internal/proxy/task_search_test.go
  internal/proxy/task_statistic.go
  internal/proxy/task_statistic_test.go
  pkg/util/merr/errors.go
  pkg/util/merr/utils.go
  pkg/util/typeutil/set.go
  pkg/util/typeutil/set_test.go
  scripts/run_go_unittest.sh
Labels: size/XXL, approved, lgtm, ci-passed, dco-passed, area/compilation

#24763 [cherry-pick] Fix potential crash bug of bulkinsert
  internal/datanode/mock_test.go
  internal/datanode/services.go
  internal/datanode/services_test.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed

#24814 Support JSON_CONTAINS or json_contains
  internal/parser/planparserv2/Plan.g4
  internal/parser/planparserv2/generated/Plan.interp
  internal/parser/planparserv2/generated/Plan.tokens
  internal/parser/planparserv2/generated/PlanLexer.interp
  internal/parser/planparserv2/generated/PlanLexer.tokens
  internal/parser/planparserv2/generated/plan_lexer.go
  internal/parser/planparserv2/generated/plan_parser.go
  internal/parser/planparserv2/plan_parser_v2_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#24778 [MetaKV refactory part 2]make etcdKV private
  cmd/milvus/mck.go
  docs/developer_guides/appendix_a_basic_components.md
  docs/developer_guides/chap06_root_coordinator.md
  internal/kv/etcd/embed_etcd_kv_test.go
  internal/kv/etcd/embed_etcd_restart_test.go
  internal/kv/etcd/etcd_kv.go
  internal/kv/etcd/etcd_kv_test.go
  internal/metastore/kv/rootcoord/suffix_snapshot_test.go
  internal/mq/msgstream/mqwrapper/rmq/rocksmq_msgstream_test.go
  internal/querycoordv2/balance/rowcount_based_balancer_test.go
  internal/querycoordv2/balance/score_based_balancer_test.go
  internal/querycoordv2/checkers/balance_checker_test.go
  internal/querycoordv2/checkers/channel_checker_test.go
  internal/querycoordv2/checkers/segment_checker_test.go
  internal/querycoordv2/dist/dist_controller_test.go
  internal/querycoordv2/meta/mock_broker.go
  internal/querycoordv2/meta/resource_manager_test.go
  internal/querycoordv2/meta/target_manager_test.go
  internal/querycoordv2/observers/leader_observer_test.go
  internal/querycoordv2/observers/replica_observer_test.go
  internal/querycoordv2/observers/resource_observer_test.go
  internal/querycoordv2/observers/target_observer_test.go
  internal/util/tsoutil/tso.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#24797 Modify test case of search partition
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#24732 Update test cases nightly
  tests/python_client/testcases/test_collection.py
  tests/python_client/testcases/test_insert.py
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#24837 Optimize range search result sort in segcore
  internal/core/src/common/RangeSearchHelper.cpp
  internal/core/src/common/RangeSearchHelper.h
  internal/core/src/index/VectorDiskIndex.cpp
  internal/core/src/index/VectorMemIndex.cpp
  internal/core/src/query/SearchBruteForce.cpp
  internal/core/unittest/test_range_search_sort.cpp
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#24861 Check metric type at watchChannelTask (#24860)
  internal/querynode/impl_test.go
  internal/querynode/task_test.go
  internal/querynode/watch_dm_channels_task.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#24862 Refine sigpipe handling
  cmd/milvus/run.go
  internal/core/src/storage/MinioChunkManager.cpp
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#24857 Optimize CI
  tests/python_client/common/common_func.py
  tests/python_client/common/common_type.py
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#24872 [Cherry-Pick] Refine sigpipe handling
  cmd/milvus/run.go
  internal/core/src/storage/MinioChunkManager.cpp
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#24870 [2.2] Enlarge e2e timeout to 120min
  ci/jenkins/PR.groovy
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#24876 Fix test structure for rmq
  internal/mq/mqimpl/rocksmq/server/global_rmq.go
  internal/mq/mqimpl/rocksmq/server/global_rmq_test.go
  internal/mq/msgstream/mqwrapper/rmq/rocksmq_msgstream_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#24867 Fix term expression on interger overflow case
  internal/core/src/query/PlanProto.cpp
  internal/core/src/query/Utils.h
  internal/core/unittest/test_range_search_sort.cpp
  internal/core/unittest/test_utils.cpp
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#24882 [skip e2e]add nats mq chaos test
  tests/python_client/chaos/nats-standalone-values.yaml
Labels: kind/improvement, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#24831 Modify nightly script
  ci/jenkins/Nightly.groovy
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#24884 [skip e2e] Bump milvus version to 2.2.10
  deployments/binary/README.md
  deployments/docker/standalone/docker-compose.yml
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#23156 Remove datanode timetick mq, use rpc to report instead
  configs/milvus.yaml
  internal/datacoord/server.go
  internal/datacoord/server_test.go
  internal/datacoord/services.go
  internal/datanode/data_node.go
  internal/datanode/data_node_test.go
  internal/datanode/data_sync_service.go
  internal/datanode/data_sync_service_test.go
  internal/datanode/flow_graph_insert_buffer_node.go
  internal/datanode/flow_graph_insert_buffer_node_test.go
  internal/datanode/flow_graph_manager.go
  internal/datanode/flow_graph_time_ticker_test.go
  internal/datanode/mock_test.go
  internal/datanode/timetick_sender.go
  internal/datanode/timetick_sender_test.go
  internal/distributed/datacoord/client/client.go
  internal/distributed/datacoord/service.go
  internal/distributed/proxy/service_test.go
  internal/mocks/mock_datacoord.go
  internal/mocks/mock_datanode.go
  internal/proto/data_coord.proto
  internal/proto/datapb/data_coord.pb.go
  internal/types/types.go
  internal/util/mock/grpc_datacoord_client.go
  pkg/util/paramtable/component_param.go
Labels: area/dependency, size/XXL, approved, lgtm, ci-passed, area/internal-api, dco-passed

#24829 Support element in json array in segcore part(#24677)
  internal/core/src/query/Expr.h
  internal/core/src/query/ExprImpl.h
  internal/core/src/query/Parser.cpp
  internal/core/src/query/PlanProto.cpp
  internal/core/src/query/generated/ExecExprVisitor.h
  internal/core/src/query/visitors/ExecExprVisitor.cpp
  internal/core/unittest/test_c_api.cpp
  internal/core/unittest/test_expr.cpp
  internal/core/unittest/test_plan_proto.cpp
  internal/core/unittest/test_query.cpp
  internal/core/unittest/test_utils/DataGen.h
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#24696 Add missing indexInfo in watchDmChannelsRequest
  internal/querycoordv2/task/executor.go
  internal/querycoordv2/task/utils.go
  internal/querycoordv2/task/utils_test.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#24879 fix function name in comment
  internal/datacoord/segment_allocation_policy.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#24892 Remove cgo PayloadWriter
  internal/storage/payload.go
  internal/storage/payload_writer.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#24895 Fix e2e read timeout error
  ci/jenkins/pod/rte-gpu.yaml
  ci/jenkins/pod/rte.yaml
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#24897 Update minio version
  deployments/docker/dev/docker-compose.yml
  deployments/docker/standalone/docker-compose.yml
  docker-compose.yml
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#24759 Add length check when insert, upsert and check default value max length
  internal/proxy/task_insert.go
  internal/proxy/task_upsert.go
  internal/proxy/validate_util.go
  internal/rootcoord/create_collection_task.go
  internal/rootcoord/create_collection_task_test.go
  pkg/util/parameterutil.go/get_max_len.go
  pkg/util/parameterutil.go/get_max_len_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#24899 fix get partition progress return wrong error msg
  internal/proxy/util.go
  internal/proxy/util_test.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#24893 Fix UnaryRange expression on integer overflow case
  internal/core/src/query/Parser.cpp
  internal/core/src/query/PlanProto.cpp
  internal/core/src/query/Utils.h
  internal/core/src/query/generated/ExecExprVisitor.h
  internal/core/src/query/visitors/ExecExprVisitor.cpp
  internal/core/src/query/visitors/ShowExprVisitor.cpp
Labels: size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#24413 add request cost metrics on qn
  internal/proto/internal.proto
  internal/proto/internalpb/internal.pb.go
  internal/querynodev2/delegator/delegator.go
  internal/querynodev2/segments/result.go
  internal/querynodev2/segments/result_test.go
  internal/querynodev2/segments/utils.go
  internal/querynodev2/services.go
  internal/querynodev2/tasks/scheduler.go
  internal/querynodev2/tasks/task.go
Labels: size/XL, approved, lgtm, ci-passed, area/internal-api, dco-passed

#24660 Segcore retrieve by pk optimazation (#24659)
  internal/core/src/query/Expr.h
  internal/core/src/query/generated/ExecExprVisitor.h
  internal/core/src/query/generated/ExecPlanNodeVisitor.h
  internal/core/src/query/visitors/ExecExprVisitor.cpp
  internal/core/src/query/visitors/ExecPlanNodeVisitor.cpp
  internal/core/src/segcore/SegmentGrowingImpl.cpp
  internal/core/src/segcore/SegmentGrowingImpl.h
  internal/core/src/segcore/SegmentInterface.h
  internal/core/src/segcore/SegmentSealedImpl.cpp
  internal/core/src/segcore/SegmentSealedImpl.h
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#24503 Refine Rocksdb option (#24394)
  internal/core/conanfile.py
  internal/core/thirdparty/rocksdb/rocksdb-win.pc.in
  internal/core/thirdparty/rocksdb/rocksdb.pc.in
  internal/mq/mqimpl/rocksmq/server/rocksmq_impl.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed

#24918 fix group nq metrics
  internal/querynodev2/tasks/task.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#24902 Memset sigaction before using it
  internal/core/src/storage/MinioChunkManager.cpp
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#24924 Enlarge compact testcase timeout
  internal/rootcoord/proxy_manager_test.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#24927 Fix TestChannelMetaMockSkipBFLoad/transient_error not stable
  internal/datanode/channel_meta_test.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#24928 [Cherry-Pick] Fix TestChannelMetaMockSkipBFLoad/transient_error not stable
  internal/datanode/channel_meta_test.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#24920 Fix BinaryRange expression on integer overflow case
  internal/core/src/query/PlanProto.cpp
  internal/core/src/query/visitors/ExecExprVisitor.cpp
  internal/core/unittest/test_query.cpp
Labels: size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#24937 [skip e2e] modify default used balancer for 2.3
  configs/milvus.yaml
  pkg/util/paramtable/component_param.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#24933 [Cherry-Pick] Memset sigaction before using it
  internal/core/src/storage/MinioChunkManager.cpp
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#24881 Limit the num of concurrent sync tasks and allow only one sync task for same segment
  configs/milvus.yaml
  internal/datanode/compactor_test.go
  internal/datanode/flow_graph_insert_buffer_node.go
  internal/datanode/flow_graph_insert_buffer_node_test.go
  internal/datanode/flush_manager.go
  internal/datanode/segment.go
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/component_param_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#24898 Update knowhere version, update diskann api and generate cache nodes in build process
  internal/core/src/index/VectorDiskIndex.cpp
  internal/core/unittest/test_indexing.cpp
  pkg/util/indexparams/disk_index_params.go
  pkg/util/indexparams/disk_index_params_test.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed, area/compilation, manual-pass

#24935 Hide autoindex params details (#24851)
  internal/proxy/task_index.go
  pkg/util/funcutil/func_test.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#24954 [skip e2e]add script to get chart version by app version
  tests/scripts/get_helm_chart_version_by_app_version.py
Labels: kind/improvement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#24828 Set pchannels before dml enqueue to prevent panic
  internal/proxy/mock_test.go
  internal/proxy/task.go
  internal/proxy/task_delete.go
  internal/proxy/task_delete_test.go
  internal/proxy/task_insert.go
  internal/proxy/task_insert_test.go
  internal/proxy/task_scheduler.go
  internal/proxy/task_upsert.go
  internal/proxy/task_upsert_test.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#24800 Change segcore search_id from travelling all bits to select true bits…
  internal/core/src/query/visitors/ExecPlanNodeVisitor.cpp
  internal/core/src/segcore/SegmentGrowingImpl.cpp
  internal/core/src/segcore/SegmentSealedImpl.cpp
  internal/core/unittest/test_c_api.cpp
Labels: size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#24859 Improve the panic code about the rootcoord/session/rocksmq
  internal/datacoord/server.go
  internal/mq/mqimpl/rocksmq/server/rocksmq_impl.go
  internal/rootcoord/dml_channels.go
  internal/rootcoord/dml_channels_test.go
  internal/util/sessionutil/session_util.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#24917 Assign metric type in load segment request
  internal/querycoordv2/task/executor.go
  internal/querycoordv2/task/task_test.go
  internal/querynodev2/services.go
  internal/querynodev2/services_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#24943 Fix BinaryArithOpEvalRange integer overflow case
  internal/core/src/query/Parser.cpp
  internal/core/src/query/PlanProto.cpp
  internal/core/src/query/visitors/ExecExprVisitor.cpp
  internal/core/src/query/visitors/ShowExprVisitor.cpp
Labels: size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#24484 fixup E2E L2 test case
  tests/python_client/testcases/test_collection.py
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#24849 Fix deleted data is still visible
  internal/core/src/segcore/DeletedRecord.h
  internal/core/src/segcore/InsertRecord.h
  internal/core/src/segcore/Record.h
  internal/core/src/segcore/SegmentGrowingImpl.cpp
  internal/core/src/segcore/SegmentGrowingImpl.h
  internal/core/src/segcore/SegmentInterface.h
  internal/core/src/segcore/SegmentSealedImpl.cpp
  internal/core/src/segcore/SegmentSealedImpl.h
  internal/core/src/segcore/Utils.h
  internal/core/src/segcore/segment_c.cpp
  internal/core/src/segcore/segment_c.h
  internal/core/unittest/test_c_api.cpp
  internal/core/unittest/test_growing.cpp
  internal/core/unittest/test_retrieve.cpp
  internal/core/unittest/test_sealed.cpp
  internal/core/unittest/test_segcore.cpp
  internal/core/unittest/test_utils.cpp
  internal/querynodev2/segments/segment.go
  internal/querynodev2/services.go
Labels: kind/bug, area/dependency, size/L, approved, lgtm, ci-passed, dco-passed

#24949 Upgrade pymilvus
  tests/python_client/requirements.txt
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#24791 enable look aside balancer on replica selection
  Makefile
  internal/proxy/lb_balancer.go
  internal/proxy/lb_policy.go
  internal/proxy/lb_policy_test.go
  internal/proxy/look_aside_balancer.go
  internal/proxy/look_aside_balancer_test.go
  internal/proxy/mock_lb_balancer.go
  internal/proxy/mock_lb_policy.go
  internal/proxy/proxy.go
  internal/proxy/roundrobin_balancer.go
  internal/proxy/roundrobin_balancer_test.go
  internal/proxy/task_query.go
  internal/proxy/task_query_test.go
  internal/proxy/task_search.go
  internal/proxy/task_search_test.go
  internal/proxy/task_statistic_test.go
  internal/querynodev2/services.go
Labels: size/XL, approved, lgtm, ci-passed, area/internal-api, dco-passed, area/compilation

#24962 [skip e2e]increase compatibility with different inputs
  tests/scripts/get_helm_chart_version_by_app_version.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#24919 [CherryPick]: Improve the panic code about the milvus component #24783
  cmd/components/data_coord.go
  cmd/components/data_node.go
  cmd/components/index_node.go
  cmd/components/proxy.go
  cmd/components/query_coord.go
  cmd/components/query_node.go
  cmd/components/root_coord.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#24921 Remove metric_type check and fix some minor bugs
  configs/milvus.yaml
  internal/proxy/task_search.go
  internal/proxy/task_search_test.go
  pkg/util/paramtable/autoindex_param.go
  tests/python_client/common/common_type.py
  tests/python_client/requirements.txt
  tests/python_client/testcases/test_collection.py
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#24708 Fix build index performance downgrade (#24651)
  internal/core/src/storage/MinioChunkManager.cpp
Labels: size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#24945 Add log for confirming gc finished
  internal/rootcoord/broker.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed

#24910 Fix e2e read timeout error
  ci/jenkins/pod/rte.yaml
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#24938 Bump semver to 2.2.11-pre+dev
  internal/common/version.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#24936 Refactor logs in proxy package.
  internal/proxy/meta_cache.go
  internal/proxy/multi_rate_limiter.go
  internal/proxy/privilege_interceptor.go
  internal/proxy/proxy.go
  internal/proxy/task_calc_distance.go
  internal/proxy/task_delete.go
  internal/proxy/task_insert.go
  internal/proxy/task_query.go
  internal/proxy/task_scheduler.go
  internal/proxy/task_search.go
  internal/proxy/task_statistic.go
  internal/proxy/task_upsert.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#24976 Add compaction log
  internal/datacoord/compaction.go
  internal/datanode/binlog_io.go
  internal/datanode/compaction_executor.go
  internal/datanode/compactor.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed

#24975 Add compaction log
  internal/datacoord/compaction.go
  internal/datanode/binlog_io.go
  internal/datanode/compaction_executor.go
  internal/datanode/compactor.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed

#24880 modify test cases
  tests/python_client/common/common_func.py
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#24891 Add test cases of default value
  tests/python_client/testcases/test_collection.py
  tests/python_client/testcases/test_insert.py
  tests/python_client/testcases/test_query.py
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#24922 Move loadDelta operation after needTransfer check
  internal/querynodev2/services.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#24912 [test]Not output vector field for sq pq index
  tests/python_client/deploy/scripts/utils.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#24989 Support sync when cp is lagged
  internal/core/conanfile.py
  internal/datanode/channel_meta.go
  internal/datanode/data_sync_service_test.go
  internal/datanode/segment_sync_policy.go
  internal/datanode/segment_sync_policy_test.go
  pkg/util/paramtable/component_param.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#24953 [Cherry-pick]Fix Flush hang after SyncSegments timeout
  internal/datanode/compaction_executor.go
  internal/datanode/compaction_executor_test.go
  internal/datanode/compactor.go
  internal/datanode/compactor_test.go
  internal/datanode/services.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed
