Repository milvus-io/milvus, pull requests merged in 2023-07, with the labels that each got.

#25244 Disable release partition when drop partition
  internal/rootcoord/drop_partition_task.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#25237 Treat small segment without index as sealed
  internal/datacoord/handler.go
  internal/datacoord/server_test.go
  internal/datacoord/services_test.go
  internal/datacoord/util.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#25266 Fixbug: metric_type not set in shard member
  internal/querynode/plan.go
  internal/querynode/plan_test.go
  internal/querynode/reduce_test.go
  internal/querynode/segment_test.go
  internal/querynode/validate_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#24858 Fix delete record may be re-applied
  internal/querynode/load_segment_task.go
  internal/querynode/segment.go
  internal/querynode/segment_loader.go
  internal/querynode/segment_test.go
  internal/storage/stats.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#25152 Support dynamic tuning config
  internal/querynodev2/handlers.go
  internal/querynodev2/mock_query_hook.go
  internal/querynodev2/server.go
  internal/querynodev2/server_test.go
  pkg/common/common.go
  pkg/config/event_dispatcher.go
  pkg/config/manager_test.go
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/hook_config.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#25248 Check field type when create index
  internal/proxy/task_index.go
  internal/proxy/task_index_test.go
  tests/python_client/testcases/test_search.py
Labels: kind/bug, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#25278 Change default log level to info
  configs/milvus.yaml
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#25243 Fix not fully loaded error after restart
  internal/querycoordv2/services.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#25283 Enlarge integration test timeout
  internal/core/src/common/Json.h
  scripts/run_intergration_test.sh
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#24839 [Feature] Support configurable policy for query node, Add user level schedule policy
  configs/milvus.yaml
  internal/proto/internal.proto
  internal/proto/internalpb/internal.pb.go
  internal/proxy/task_query.go
  internal/proxy/task_search.go
  internal/querynodev2/collector/counter.go
  internal/querynodev2/handlers.go
  internal/querynodev2/server.go
  internal/querynodev2/services.go
  internal/querynodev2/tasks/concurrent_safe_scheduler.go
  internal/querynodev2/tasks/concurrent_safe_scheduler_test.go
  internal/querynodev2/tasks/fifo_policy.go
  internal/querynodev2/tasks/mock_task_test.go
  internal/querynodev2/tasks/policy_test.go
  internal/querynodev2/tasks/query_task.go
  internal/querynodev2/tasks/queues.go
  internal/querynodev2/tasks/queues_test.go
  internal/querynodev2/tasks/scheduler.go
  internal/querynodev2/tasks/task.go
  internal/querynodev2/tasks/tasks.go
  internal/querynodev2/tasks/user_task_polling_policy.go
  pkg/metrics/querynode_metrics.go
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/param_item.go
Labels: kind/feature, kind/improvement, size/XXL, approved, lgtm, ci-passed, area/internal-api, dco-passed

#25187 add coordinator broker, to unify rootcoord api access
  internal/datacoord/coordinator_broker.go
  internal/datacoord/handler.go
  internal/datacoord/server.go
  internal/datacoord/server_test.go
  internal/datacoord/services.go
  internal/querycoordv2/meta/coordinator_broker.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#25290 Fix querycoord segment checker nil reference
  internal/querycoordv2/checkers/segment_checker.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#24990 Fix expression on integer overflow case (#24867, #24893, #24920, #24943)
  internal/core/src/query/Parser.cpp
  internal/core/src/query/PlanProto.cpp
  internal/core/src/query/Utils.h
  internal/core/src/query/generated/ExecExprVisitor.h
  internal/core/src/query/visitors/ExecExprVisitor.cpp
  internal/core/src/query/visitors/ShowExprVisitor.cpp
  internal/core/unittest/test_c_api.cpp
  internal/core/unittest/test_retrieve.cpp
  internal/core/unittest/test_utils.cpp
Labels: size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#25192 Skip unnecessary reduce phase during search (#25166)
  internal/querynode/result.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#25285 Add SetMetricType and set metric only for shard leader
  internal/querycoordv2/task/executor.go
  internal/querycoordv2/task/task_test.go
  internal/querynodev2/segments/collection.go
  internal/querynodev2/segments/plan.go
  internal/querynodev2/segments/plan_test.go
  internal/querynodev2/segments/reduce_test.go
  internal/querynodev2/services.go
  internal/querynodev2/services_test.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#25222 Disable retryKeepAlive when LivenessCheck's Context close
  internal/util/sessionutil/session_util.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#25280 Fix rootcoord restoration misses gcConfirmStep
  internal/rootcoord/garbage_collector.go
  internal/rootcoord/garbage_collector_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#25306 Fix queryHook ut data race
  internal/querynodev2/server_test.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#25241 chunk manager supports using gcs & oss with accessKey
  internal/core/src/storage/MinioChunkManager.cpp
  internal/core/src/storage/MinioChunkManager.h
Labels: size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#25272 growing index memory opt & getvector bugfix
  configs/milvus.yaml
  internal/core/src/query/SearchOnGrowing.cpp
  internal/core/src/segcore/FieldIndexing.cpp
  internal/core/src/segcore/FieldIndexing.h
  internal/core/src/segcore/SegmentGrowingImpl.cpp
  internal/core/src/segcore/SegmentGrowingImpl.h
  internal/core/thirdparty/knowhere/CMakeLists.txt
  internal/core/unittest/test_growing_index.cpp
  pkg/util/paramtable/component_param_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed, area/compilation

#25320 Fix expression on integer overflow case
  internal/core/src/query/visitors/ExecExprVisitor.cpp
  internal/core/unittest/CMakeLists.txt
  internal/core/unittest/test_integer_overflow.cpp
Labels: kind/improvement, size/XL, approved, lgtm, ci-passed, dco-passed, area/compilation

#25318 Make cgo pool size larger than worker pool size
  configs/milvus.yaml
  internal/querynodev2/segments/pool.go
  pkg/util/paramtable/component_param.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#25319 refine grafana metrics for replica selection
  internal/proxy/look_aside_balancer.go
  pkg/metrics/proxy_metrics.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#25287 fix search/query count metrics
  internal/querynodev2/handlers.go
  internal/querynodev2/services.go
  pkg/metrics/querynode_metrics.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#25240 fix unexpected metrics value cause by wrong time unit
  Makefile
  internal/datanode/timetick_sender.go
  internal/datanode/timetick_sender_test.go
  internal/types/mock_datacoord.go
Labels: kind/improvement, size/XXL, approved, lgtm, ci-passed, dco-passed, area/compilation

#25328 Stop blocking until all channels & segments released
  internal/querynodev2/server.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#25337 fix sync target version with wrong segment list
  internal/querycoordv2/meta/target_manager.go
  internal/querycoordv2/meta/target_manager_test.go
  internal/querycoordv2/observers/leader_observer.go
  internal/querycoordv2/observers/leader_observer_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#25212 Load batch by batch
  internal/core/src/common/Channel.h
  internal/core/src/common/Consts.h
  internal/core/src/mmap/Column.h
  internal/core/src/mmap/Types.h
  internal/core/src/mmap/Utils.h
  internal/core/src/segcore/InsertRecord.h
  internal/core/src/segcore/SegmentGrowingImpl.cpp
  internal/core/src/segcore/SegmentSealed.h
  internal/core/src/segcore/SegmentSealedImpl.cpp
  internal/core/src/segcore/SegmentSealedImpl.h
  internal/core/src/segcore/Utils.cpp
  internal/core/src/segcore/Utils.h
  internal/core/src/segcore/segment_c.cpp
  internal/core/src/storage/FieldData.h
  internal/core/src/storage/LocalChunkManagerSingleton.h
  internal/core/src/storage/Util.cpp
  internal/core/src/storage/Util.h
  internal/core/unittest/test_expr.cpp
  internal/core/unittest/test_sealed.cpp
  internal/core/unittest/test_utils/DataGen.h
  internal/querynodev2/segments/segment_loader.go
Labels: size/XL, approved, lgtm, ci-passed, dco-passed, manual-pass

#25347 Fix delegator leaked
  internal/querynodev2/services.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#25354 Fix data race in session
  internal/util/sessionutil/session_util.go
  internal/util/sessionutil/session_util_test.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#25224 Fix the data race in waitgroup for graceful stop
  internal/querynode/impl.go
  internal/querynode/impl_test.go
  internal/querynode/query_node.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#25200 Fix InsertExcluded policy for flushed/dropped segments
  internal/querynodev2/services.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#25377 fix metric label in search/query count
  internal/querynodev2/handlers.go
  internal/querynodev2/services.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#25339 Avoid rewriting all binlogs every time a segment is updated
  internal/datacoord/meta.go
  internal/metastore/catalog.go
  internal/metastore/kv/datacoord/kv_catalog.go
  internal/metastore/kv/datacoord/kv_catalog_test.go
  internal/metastore/mocks/DataCoordCatalog.go
  internal/mocks/mock_datacoord_catalog.go
Labels: size/XL, approved, lgtm, ci-passed, dco-passed

#25360 enable metrics expire for replica selection
  internal/proxy/look_aside_balancer.go
  internal/proxy/look_aside_balancer_test.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#25379 Fix false load success for partition load timeout but collection remains
  internal/querycoordv2/meta/collection_manager.go
  internal/querycoordv2/meta/collection_manager_test.go
  internal/querycoordv2/observers/collection_observer.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#25381 Fix data race in session (#25354)
  internal/util/sessionutil/session_util.go
  internal/util/sessionutil/session_util_test.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#25349 [Fixup] unexpected read_task_ready_len metric
  internal/querynodev2/tasks/concurrent_safe_scheduler.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#25382 Remove alter segment interface
  internal/datacoord/meta.go
  internal/metastore/catalog.go
  internal/metastore/kv/datacoord/kv_catalog.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#25372 Fix BinaryRange expression on indexed chunk
  internal/core/src/query/visitors/ExecExprVisitor.cpp
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#25333 Fix expression on integer overflow case (#25320, #25372)
  internal/core/src/query/visitors/ExecExprVisitor.cpp
  internal/core/unittest/CMakeLists.txt
  internal/core/unittest/test_integer_overflow.cpp
  internal/core/unittest/test_utils/DataGen.h
Labels: kind/improvement, size/XL, approved, lgtm, ci-passed, dco-passed, area/compilation, manual-pass

#25010 Use write lock for lru_cache.Get
  internal/util/cache/lru_cache.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#24810 Fix typo in suffix_snapshot.go
  internal/metastore/kv/rootcoord/suffix_snapshot.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#25074 [ci] Add standalone kafka e2e pipeline
  ci/jenkins/PR.groovy
  tests/scripts/get_release_name.sh
Labels: kind/improvement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#25122 [cherry-pick][ci] Add standalone kafka e2e pipeline
  ci/jenkins/PR.groovy
  tests/scripts/get_release_name.sh
Labels: kind/improvement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#25399 fix metric label for sq count metrics
  internal/querynodev2/handlers.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#25369 Fix dup deletions make deleted records visible
  internal/core/src/segcore/DeletedRecord.h
  internal/core/src/segcore/InsertRecord.h
  internal/core/src/segcore/Record.h
  internal/core/src/segcore/SegmentGrowing.h
  internal/core/src/segcore/SegmentGrowingImpl.cpp
  internal/core/src/segcore/SegmentGrowingImpl.h
  internal/core/src/segcore/SegmentInterface.h
  internal/core/src/segcore/SegmentSealedImpl.cpp
  internal/core/src/segcore/SegmentSealedImpl.h
  internal/core/src/segcore/segment_c.cpp
  internal/core/src/segcore/segment_c.h
  internal/core/unittest/test_c_api.cpp
  internal/core/unittest/test_growing.cpp
  internal/core/unittest/test_retrieve.cpp
  internal/core/unittest/test_sealed.cpp
  internal/core/unittest/test_segcore.cpp
  internal/core/unittest/test_utils.cpp
  internal/querynode/flow_graph_insert_node.go
  internal/querynode/segment.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#25390 Use PK index for string data type
  internal/core/src/query/visitors/ExecExprVisitor.cpp
  internal/core/src/segcore/SegmentGrowingImpl.cpp
  internal/core/src/segcore/SegmentSealedImpl.cpp
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#25380 decrease default value of group max nq
  configs/milvus.yaml
  pkg/util/paramtable/component_param.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#24255 Add output fields value check
  tests/python_client/check/func_check.py
  tests/python_client/check/param_check.py
  tests/python_client/common/common_func.py
  tests/python_client/testcases/test_query.py
  tests/python_client/testcases/test_search.py
Labels: kind/improvement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#25409 Fix querynodev2 grace stop condition reversed
  internal/querynodev2/server.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#25405 fix querynode panic in get distribution
  internal/querynodev2/services.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#25211 fix possible deadlock in when syncing segments to datanode(#25196)
  internal/datanode/data_node.go
  internal/datanode/data_node_test.go
  internal/util/flowgraph/flow_graph.go
  internal/util/lock/lock_util.go
  internal/util/lock/lock_util_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#25418 fix set shard unservicable when sync target version
  internal/querynodev2/delegator/distribution.go
  internal/querynodev2/delegator/distribution_test.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed

#25420 Remove redundant kv mocks
  internal/datacoord/cluster_test.go
  internal/datacoord/compaction_test.go
  internal/datacoord/index_meta_test.go
  internal/datacoord/index_service_test.go
  internal/datacoord/meta_test.go
  internal/datacoord/mock_test.go
  internal/datacoord/segment_manager_test.go
  internal/metastore/kv/datacoord/kv_catalog_test.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#25424 Set compaction default value to be true
  pkg/util/paramtable/component_param.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#25426 Remove kv mocks
  internal/metastore/kv/datacoord/kv_catalog_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#25293 [Cherry-Pick] Fix rootcoord restoration missing gcConfirmStep
  internal/rootcoord/garbage_collector.go
  internal/rootcoord/garbage_collector_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#25029 Stop loading stats after segment released
  internal/querynode/segment_loader.go
  internal/querynode/segment_loader_test.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#25437 Fix aws-c-event-stream not found
  internal/core/conanfile.py
Labels: size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#25412 Fix bug of missing JSON type when sorting retrieve results
  internal/querynode/mock_test.go
  internal/querynode/result_sorter.go
  internal/querynode/result_sorter_test.go
Labels: size/M, do-not-merge/hold, approved, lgtm, dco-passed

#25421 fix consume growing from dml after release
  internal/querynodev2/services.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#25447 Update e2e
  ci/jenkins/PR.groovy
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#25417 HNSW support binary vector
  pkg/util/indexparamcheck/constraints.go
  pkg/util/indexparamcheck/hnsw_checker.go
  pkg/util/indexparamcheck/hnsw_checker_test.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#25453 Fix segment released early in case of balancing
  internal/querynodev2/delegator/distribution.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#24761 support high-level RESTFUL API, listen on the same port as grpc
  .golangci.yml
  go.mod
  go.sum
  internal/distributed/proxy/httpserver/constant.go
  internal/distributed/proxy/httpserver/handler_v1.go
  internal/distributed/proxy/httpserver/handler_v1_test.go
  internal/distributed/proxy/httpserver/request.go
  internal/distributed/proxy/httpserver/utils.go
  internal/distributed/proxy/httpserver/utils_test.go
  internal/distributed/proxy/service.go
  internal/distributed/proxy/service_test.go
  internal/proxy/privilege_interceptor.go
  internal/proxy/util.go
Labels: area/dependency, size/XXL, approved, lgtm, ci-passed, dco-passed

#25454 Fix bug of missing JSON type when sorting retrieve results (#25412)
  internal/querynode/mock_test.go
  internal/querynode/result_sorter.go
  internal/querynode/result_sorter_test.go
Labels: size/M, approved, lgtm, ci-passed, manual-pass

#25455 Fix bug of missing JSON type when sorting retrieve results (#25412)
  internal/querynodev2/segments/mock_data.go
  internal/querynodev2/segments/result_sorter.go
  internal/querynodev2/segments/result_test.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#24011 [Backport] Remove datanode timetick mq, use rpc to report instead
  configs/milvus.yaml
  internal/datacoord/server.go
  internal/datacoord/server_test.go
  internal/datacoord/services.go
  internal/datacoord/services_test.go
  internal/datanode/data_node.go
  internal/datanode/data_sync_service.go
  internal/datanode/data_sync_service_test.go
  internal/datanode/flow_graph_insert_buffer_node.go
  internal/datanode/flow_graph_insert_buffer_node_test.go
  internal/datanode/flow_graph_manager.go
  internal/datanode/mock_test.go
  internal/datanode/timetick_sender.go
  internal/datanode/timetick_sender_test.go
  internal/distributed/datacoord/client/client.go
  internal/distributed/datacoord/service.go
  internal/distributed/proxy/service_test.go
  internal/mocks/mock_datacoord.go
  internal/mocks/mock_datanode.go
  internal/proto/data_coord.proto
  internal/proto/datapb/data_coord.pb.go
  internal/types/types.go
  internal/util/mock/grpc_datacoord_client.go
  internal/util/paramtable/component_param.go
Labels: size/XXL, approved, lgtm, ci-passed, dco-passed, manual-pass

#25450 Set aio pool
  internal/core/src/config/ConfigKnowhere.cpp
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#25458 fix set wrong consistency level in proxy
  internal/proxy/meta_cache.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#25462 Add HasPrefix in kv
  internal/kv/etcd/embed_etcd_kv.go
  internal/kv/etcd/embed_etcd_kv_test.go
  internal/kv/etcd/etcd_kv.go
  internal/kv/etcd/etcd_kv_test.go
  internal/kv/kv.go
  internal/kv/mem/mem_kv.go
  internal/kv/mem/mem_kv_test.go
  internal/kv/mocks/MetaKv.go
  internal/kv/mocks/TxnKV.go
  internal/kv/mocks/WatchKV.go
  internal/kv/rocksdb/rocksdb_kv.go
  internal/kv/rocksdb/rocksdb_kv_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#25460 Fix indexnode memory leakage when update index fails
  internal/indexnode/task.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#25351 Add rate limit and deny write in upsert
  configs/milvus.yaml
  internal/proto/internal.proto
  internal/proto/internalpb/internal.pb.go
  internal/proxy/impl.go
  internal/proxy/metrics_info.go
  internal/proxy/multi_rate_limiter.go
  internal/proxy/proxy.go
  internal/proxy/rate_limit_interceptor.go
  internal/proxy/rate_limit_interceptor_test.go
  internal/rootcoord/quota_center.go
  internal/rootcoord/quota_center_test.go
  internal/rootcoord/util.go
  pkg/common/common.go
  pkg/util/paramtable/quota_param.go
  pkg/util/paramtable/quota_param_test.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, area/internal-api, dco-passed

#25444 Add index info in GetDataDistribution response
  internal/proto/query_coord.proto
  internal/proto/querypb/query_coord.pb.go
  internal/querycoordv2/dist/dist_handler.go
  internal/querycoordv2/meta/segment_dist_manager.go
  internal/querynodev2/services.go
Labels: kind/improvement, size/XL, approved, lgtm, ci-passed, area/internal-api, dco-passed

#25469 Reduce the load memory usage predict factor to 2
  configs/milvus.yaml
  pkg/util/paramtable/component_param.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#25442 refinement towards sync_cp_lag_too_behind_policy to avoid submit sync…
  internal/datanode/segment_sync_policy.go
  internal/datanode/segment_sync_policy_test.go
  internal/util/paramtable/base_table.go
  internal/util/paramtable/base_table_test.go
  internal/util/paramtable/component_param.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#25284 Bulkinsert supports partition keys
  internal/datanode/data_node.go
  internal/datanode/mock_test.go
  internal/datanode/services.go
  internal/datanode/services_test.go
  internal/proto/data_coord.proto
  internal/proto/datapb/data_coord.pb.go
  internal/proxy/util.go
  internal/rootcoord/import_manager.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
  internal/util/importutil/binlog_adapter.go
  internal/util/importutil/binlog_adapter_test.go
  internal/util/importutil/binlog_file.go
  internal/util/importutil/binlog_file_test.go
  internal/util/importutil/binlog_parser.go
  internal/util/importutil/binlog_parser_test.go
  internal/util/importutil/collection_info.go
  internal/util/importutil/collection_info_test.go
  internal/util/importutil/import_options.go
  internal/util/importutil/import_options_test.go
  internal/util/importutil/import_util.go
  internal/util/importutil/import_util_test.go
  internal/util/importutil/import_wrapper.go
  internal/util/importutil/import_wrapper_test.go
  internal/util/importutil/json_handler.go
  internal/util/importutil/json_handler_test.go
  internal/util/importutil/json_parser.go
  internal/util/importutil/json_parser_test.go
  internal/util/importutil/numpy_adapter.go
  internal/util/importutil/numpy_parser.go
  internal/util/importutil/numpy_parser_test.go
  pkg/util/typeutil/hash.go
  pkg/util/typeutil/hash_test.go
Labels: size/XXL, approved, lgtm, ci-passed, dco-passed

#25473 Improve error message throwed from knowhere
  internal/core/src/common/Utils.h
  internal/core/src/index/VectorDiskIndex.cpp
  internal/core/src/index/VectorMemIndex.cpp
  internal/core/src/index/VectorMemNMIndex.cpp
  internal/core/src/query/SearchBruteForce.cpp
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#25475 Separate segments/shards reduce latency metrics
  internal/querynodev2/services.go
  internal/querynodev2/tasks/task.go
  pkg/metrics/metrics.go
  pkg/metrics/querynode_metrics.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#25471 Replace LoadWithPrefix with HasPrefix
  internal/datacoord/compaction_test.go
  internal/metastore/kv/datacoord/kv_catalog.go
  internal/metastore/kv/datacoord/kv_catalog_test.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed

#25489 Reduce DataScope to historical for segment release task
  internal/querycoordv2/balance/utils.go
  internal/querycoordv2/checkers/segment_checker.go
  internal/querycoordv2/handlers.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#25478 [Cherry-Pick] Fix indexnode memory leakage when update index fails (#25460)
  internal/indexnode/task.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#25088 Faster garbage collect on compacted data
  configs/milvus.yaml
  internal/datacoord/garbage_collector.go
  pkg/util/paramtable/component_param.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#25402 Use PK index for string data type (#25390)
  internal/core/src/query/visitors/ExecExprVisitor.cpp
  internal/core/src/segcore/SegmentGrowingImpl.cpp
  internal/core/src/segcore/SegmentSealedImpl.cpp
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#25406 Add entities size metric in querynode
  internal/querynodev2/metrics_info.go
  pkg/metrics/querynode_metrics.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#25415 Rename newTimeTickManager to newTimeTickSender
  internal/datanode/data_node.go
  internal/datanode/data_sync_service_test.go
  internal/datanode/flow_graph_insert_buffer_node_test.go
  internal/datanode/timetick_sender.go
  internal/datanode/timetick_sender_test.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#25376 Prevent `exclusive consumer` exception in pulsar
  internal/datanode/data_node.go
  internal/datanode/event_manager.go
  internal/querynodev2/delegator/delegator_data.go
  internal/querynodev2/delegator/delegator_data_test.go
  internal/querynodev2/services_test.go
  pkg/mq/msgdispatcher/dispatcher.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#25529 Fix unstable ut in timetick_sender_test
  internal/datanode/timetick_sender_test.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#25510 Add func check of output fields and modify cases
  tests/python_client/base/client_base.py
  tests/python_client/check/func_check.py
  tests/python_client/check/param_check.py
  tests/python_client/common/common_func.py
  tests/python_client/testcases/test_collection.py
  tests/python_client/testcases/test_delete.py
  tests/python_client/testcases/test_index.py
  tests/python_client/testcases/test_query.py
  tests/python_client/testcases/test_search.py
  tests/python_client/testcases/test_utility.py
Labels: sig/testing, size/XL, approved, lgtm, area/test, ci-passed, dco-passed

#25527 Fix incorrect IP distance
  internal/proxy/task_search.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#25495 Fix QueryNode panic while inserting to released segment
  internal/querynodev2/delegator/delegator_data.go
  internal/querynodev2/handlers.go
  internal/querynodev2/pipeline/filter_node.go
  internal/querynodev2/pipeline/manager.go
  internal/querynodev2/segments/errors.go
  internal/querynodev2/segments/retrieve_test.go
  internal/querynodev2/segments/segment.go
  internal/querynodev2/segments/segment_loader.go
  internal/querynodev2/segments/validate.go
  internal/querynodev2/services.go
  pkg/util/merr/errors.go
  pkg/util/merr/errors_test.go
  pkg/util/merr/utils.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#25500 refinement towards sync_cp_lag_too_behind_policy to avoid submit sync…
  internal/datanode/segment_sync_policy.go
  internal/datanode/segment_sync_policy_test.go
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/param_item.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#25499 Fix compile error caused by aws sdk with openssl3.0
  internal/core/thirdparty/aws_sdk/CMakeLists.txt
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed, area/compilation

#25316 remove sync segmentLastExpire every time when assigning(#25271)
  configs/milvus.yaml
  internal/datacoord/meta.go
  internal/datacoord/segment_manager.go
  internal/datacoord/segment_manager_test.go
  internal/datacoord/server.go
  internal/util/paramtable/component_param.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#25539 Fix unstable ut in timetick_sender_test
  internal/datanode/timetick_sender_test.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#25378 [Cherry-Pick]: Prevent `exclusive consumer` exception in pulsar (#25376)
  internal/datanode/data_node.go
  internal/datanode/data_node_test.go
  internal/datanode/event_manager.go
  internal/datanode/flow_graph_dmstream_input_node.go
  internal/querynode/flow_graph_query_node.go
  internal/querynode/task_test.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#25526 Avoid update all binlogs every a segment is updated
  internal/datacoord/meta.go
  internal/metastore/kv/datacoord/kv_catalog.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#24995 Bulkinsert supports partition keys
  internal/datanode/data_node.go
  internal/datanode/data_node_test.go
  internal/datanode/mock_test.go
  internal/proto/data_coord.proto
  internal/proto/datapb/data_coord.pb.go
  internal/proxy/util.go
  internal/rootcoord/import_manager.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
  internal/util/importutil/binlog_adapter.go
  internal/util/importutil/binlog_adapter_test.go
  internal/util/importutil/binlog_file.go
  internal/util/importutil/binlog_file_test.go
  internal/util/importutil/binlog_parser.go
  internal/util/importutil/binlog_parser_test.go
  internal/util/importutil/collection_info.go
  internal/util/importutil/collection_info_test.go
  internal/util/importutil/import_options_test.go
  internal/util/importutil/import_util.go
  internal/util/importutil/import_util_test.go
  internal/util/importutil/import_wrapper.go
  internal/util/importutil/import_wrapper_test.go
  internal/util/importutil/json_handler.go
  internal/util/importutil/json_handler_test.go
  internal/util/importutil/json_parser.go
  internal/util/importutil/json_parser_test.go
  internal/util/importutil/numpy_adapter.go
  internal/util/importutil/numpy_parser.go
  internal/util/importutil/numpy_parser_test.go
  internal/util/typeutil/hash.go
  internal/util/typeutil/hash_test.go
Labels: size/XXL, approved, lgtm, ci-passed, dco-passed

#25540 [Cherry-Pick] Retry on SyncSegment failure
  internal/datacoord/session_manager.go
  internal/datanode/flush_manager.go
  internal/datanode/flush_manager_test.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#25524 fix datacoord consume datanode tt metrics
  internal/datacoord/services.go
  internal/datanode/timetick_sender.go
  internal/datanode/timetick_sender_test.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#25555 fix release sealed segment on unwatch channel
  internal/querynodev2/services.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#25532 Reduce log frequency in timetick_sender
  internal/datanode/timetick_sender.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#25537 Retry on SyncSegment failure
  internal/datacoord/session_manager.go
  internal/datanode/flush_manager.go
  internal/datanode/flush_manager_test.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#25534 Allow empty minio.rootPath
  pkg/util/paramtable/service_param.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#25513 Fix deleted data may be returned by search/query
  internal/querynode/watch_dm_channels_task.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#25494 Fix about high level restful api
  internal/distributed/proxy/httpserver/constant.go
  internal/distributed/proxy/httpserver/handler_v1.go
  internal/distributed/proxy/httpserver/handler_v1_test.go
  internal/distributed/proxy/httpserver/utils.go
  internal/distributed/proxy/httpserver/utils_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#25538 Use librdkafka for all platform
  .github/workflows/code-checker.yaml
  Makefile
  internal/core/conanfile.py
  internal/core/thirdparty/CMakeLists.txt
  internal/core/thirdparty/rdkafka/CMakeLists.txt
  internal/core/thirdparty/rdkafka/rdkafka.pc.in
  internal/core/thirdparty/rocksdb/CMakeLists.txt
  internal/core/thirdparty/rocksdb/rocksdb-win.pc.in
  scripts/run_go_codecov.sh
  scripts/run_go_unittest.sh
  scripts/run_intergration_test.sh
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed, area/compilation

#25528 Fix incorrect IP distance (#25527)
  internal/proxy/task_search.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#25260 Support dynamic simd framework and using term expr as example
  Makefile
  internal/core/CMakeLists.txt
  internal/core/src/CMakeLists.txt
  internal/core/src/common/Types.h
  internal/core/src/query/CMakeLists.txt
  internal/core/src/query/visitors/ExecExprVisitor.cpp
  internal/core/src/simd/CMakeLists.txt
  internal/core/src/simd/avx2.cpp
  internal/core/src/simd/avx2.h
  internal/core/src/simd/avx512.cpp
  internal/core/src/simd/avx512.h
  internal/core/src/simd/common.h
  internal/core/src/simd/hook.cpp
  internal/core/src/simd/hook.h
  internal/core/src/simd/instruction_set.h
  internal/core/src/simd/ref.cpp
  internal/core/src/simd/ref.h
  internal/core/src/simd/sse2.cpp
  internal/core/src/simd/sse2.h
  internal/core/src/simd/sse4.cpp
  internal/core/src/simd/sse4.h
  internal/core/unittest/CMakeLists.txt
  internal/core/unittest/test_c_api.cpp
  internal/core/unittest/test_expr.cpp
  internal/core/unittest/test_simd.cpp
  scripts/core_build.sh
  scripts/run_cpp_unittest.sh
Labels: size/XXL, approved, lgtm, ci-passed, dco-passed, area/compilation

#25542 Reduce log frequency in timetick_sender
  internal/datanode/timetick_sender.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#25451 Fix dead loop in session
  internal/util/sessionutil/session_util.go
  internal/util/sessionutil/session_util_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#25463 Fix dead loop in session
  internal/util/sessionutil/session_util.go
  internal/util/sessionutil/session_util_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#25305 Revert aws-sdk-cpp version
  internal/core/thirdparty/aws_sdk/CMakeLists.txt
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed, area/compilation

#25485 Use sync.Map to reduce lock granularity to make create collection faster
  pkg/mq/msgdispatcher/client.go
  pkg/mq/msgdispatcher/client_test.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#25582 fix compute score on replica selection
  internal/proxy/look_aside_balancer.go
  internal/proxy/look_aside_balancer_test.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed

#25466 Organize mocks from types.go
  internal/datacoord/compaction_test.go
  internal/datanode/timetick_sender_test.go
  internal/distributed/proxy/service_test.go
  internal/distributed/querycoord/service_test.go
  internal/distributed/querynode/service_test.go
  internal/mocks/mock_datacoord.go
  internal/mocks/mock_datanode.go
  internal/mocks/mock_proxy.go
  internal/mocks/mock_querycoord.go
  internal/mocks/mock_querynode.go
  internal/mocks/mock_rootcoord.go
  internal/proxy/authentication_interceptor_test.go
  internal/proxy/impl_test.go
  internal/proxy/lb_policy_test.go
  internal/proxy/look_aside_balancer_test.go
  internal/proxy/meta_cache_test.go
  internal/proxy/privilege_interceptor_test.go
  internal/proxy/task_index_test.go
  internal/proxy/task_query_test.go
  internal/proxy/task_search_test.go
  internal/proxy/task_statistic_test.go
  internal/proxy/util_test.go
  internal/querycoordv2/meta/coordinator_broker_test.go
  internal/querycoordv2/server_test.go
  internal/querynodev2/cluster/worker_test.go
  internal/rootcoord/broker_test.go
  internal/rootcoord/garbage_collector_test.go
  internal/rootcoord/mock_test.go
  internal/rootcoord/quota_center_test.go
  internal/types/mock_datacoord.go
  internal/types/mock_proxy.go
  internal/types/types.go
Labels: size/XXL, approved, lgtm, ci-passed, dco-passed

#25486 Clear collection meta after all channels/segments released
  internal/querynodev2/delegator/delegator_data_test.go
  internal/querynodev2/delegator/delegator_test.go
  internal/querynodev2/local_worker.go
  internal/querynodev2/local_worker_test.go
  internal/querynodev2/segments/collection.go
  internal/querynodev2/segments/manager.go
  internal/querynodev2/segments/mock_collection_manager.go
  internal/querynodev2/segments/mock_segment_manager.go
  internal/querynodev2/segments/retrieve_test.go
  internal/querynodev2/segments/search_test.go
  internal/querynodev2/segments/segment_loader_test.go
  internal/querynodev2/segments/segment_test.go
  internal/querynodev2/services.go
  internal/querynodev2/services_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#25574 Refactor logs in DataCoord & DataNode
  internal/datacoord/channel_checker.go
  internal/datacoord/channel_manager.go
  internal/datacoord/compaction.go
  internal/datacoord/compaction_trigger.go
  internal/datacoord/coordinator_broker.go
  internal/datacoord/garbage_collector.go
  internal/datacoord/handler.go
  internal/datacoord/index_builder.go
  internal/datacoord/index_meta.go
  internal/datacoord/index_service.go
  internal/datacoord/indexnode_manager.go
  internal/datacoord/meta.go
  internal/datacoord/segment_manager.go
  internal/datacoord/server.go
  internal/datacoord/server_test.go
  internal/datacoord/services.go
  internal/datanode/channel_meta.go
  internal/datanode/data_sync_service.go
  internal/datanode/event_manager.go
  internal/datanode/flow_graph_dd_node.go
  internal/datanode/flow_graph_dd_node_test.go
  internal/datanode/flow_graph_dmstream_input_node.go
  internal/datanode/flow_graph_insert_buffer_node.go
  internal/datanode/flush_manager.go
  internal/datanode/flush_task.go
  internal/datanode/services.go
  internal/indexnode/task.go
  internal/metastore/db/dao/collection.go
  internal/metastore/db/dao/collection_channel.go
  internal/metastore/db/dao/field.go
  internal/metastore/db/dao/index.go
  internal/metastore/db/dao/partition.go
  internal/metastore/db/dao/segment_index.go
  internal/metastore/db/dbmodel/collection.go
  internal/metastore/db/dbmodel/field.go
  internal/metastore/db/dbmodel/index.go
  internal/metastore/db/dbmodel/segment_index.go
  internal/metastore/db/indexcoord/table_catalog.go
  internal/metastore/db/indexcoord/table_catalog_test.go
  internal/metastore/db/rootcoord/table_catalog.go
  internal/metastore/kv/datacoord/kv_catalog.go
  internal/proxy/impl.go
  internal/proxy/meta_cache.go
  internal/proxy/msg_pack.go
  internal/proxy/task_index.go
  internal/proxy/task_insert.go
  internal/proxy/task_upsert.go
  internal/querynodev2/handlers.go
  internal/rootcoord/broker.go
  internal/rootcoord/dml_channels.go
  internal/rootcoord/import_manager.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/timeticksync.go
  internal/util/segmentutil/utils.go
Labels: kind/improvement, size/XXL, approved, lgtm, ci-passed, dco-passed

#25598 Refund the tokens to limiter
  internal/proxy/multi_rate_limiter.go
  pkg/util/ratelimitutil/limiter.go
  pkg/util/ratelimitutil/limiter_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#25589 Improve the operation log
  internal/proxy/impl.go
  internal/proxy/lb_policy.go
  internal/proxy/task_delete.go
  internal/proxy/task_insert.go
  internal/proxy/task_query.go
  internal/proxy/task_search.go
  internal/util/grpcclient/client.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#25498 Update retrieve vectors test cases
  tests/python_client/testcases/test_high_level_api.py
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#25599 Fix DeleteCollection not protected
  internal/querynodev2/segments/collection.go
  internal/querynodev2/segments/plan.go
  internal/querynodev2/segments/plan_test.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#25594 Add log field for local worker call
  internal/querynodev2/local_worker.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#25583 [test]Add restful api test
  tests/restful_client/README.md
  tests/restful_client/api/milvus.py
  tests/restful_client/base/error_code_message.py
  tests/restful_client/base/testbase.py
  tests/restful_client/config/log_config.py
  tests/restful_client/conftest.py
  tests/restful_client/pytest.ini
  tests/restful_client/requirements.txt
  tests/restful_client/testcases/test_collection_operations.py
  tests/restful_client/testcases/test_vector_operations.py
  tests/restful_client/utils/constant.py
  tests/restful_client/utils/util_log.py
  tests/restful_client/utils/utils.py
Labels: kind/improvement, sig/testing, size/XXL, approved, lgtm, area/test, ci-passed, dco-passed

#25612 [test]Add RPO and RTO metric for rolling update test
  tests/python_client/chaos/checker.py
  tests/python_client/chaos/testcases/test_single_request_operation_for_rolling_update.py
  tests/python_client/utils/api_request.py
Labels: kind/improvement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#25616 Support create alias with dropping collection name
  internal/rootcoord/meta_table.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#25577 Modify nightly log level to debug
  ci/jenkins/Nightly.groovy
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#25317 Add some test cases
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#25588 Fix search request miss import parameter
  internal/distributed/proxy/httpserver/handler_v1.go
  internal/distributed/proxy/httpserver/handler_v1_test.go
  internal/distributed/proxy/httpserver/utils.go
  internal/distributed/proxy/httpserver/utils_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#25549 Fix monitoring metrics
  internal/rootcoord/meta_table.go
  internal/rootcoord/proxy_client_manager.go
  internal/rootcoord/proxy_manager.go
  internal/rootcoord/quota_center.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#25611 fix use pChannel in seek position
  pkg/mq/msgdispatcher/dispatcher.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#25436 Narrow the scope of deleteMut lock in loadStreamDelete
  internal/querynodev2/delegator/delegator_data.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#25578 Make query set guarantee ts based on default consistency level
  internal/proxy/task_query.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed

#25579 Make query set guarantee ts based on default consistency level
  internal/proxy/task_query.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#25601 Fix knowhere prometheus metrics not show
  internal/core/CMakeLists.txt
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed, area/compilation

#25131 Add test case of drop collection during insert
  tests/python_client/testcases/test_collection.py
Labels: sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#25590 Add current used disk log when load
  internal/querynode/segment_loader.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#25253 [cherry-pick]Check field type when create index
  internal/proxy/task_index.go
  internal/proxy/task_index_test.go
  tests/python_client/testcases/test_search.py
Labels: kind/bug, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#25637 refine rated log of look aside balancer
  internal/proxy/look_aside_balancer.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#24926 Handle errors by merr for QueryCoord
  internal/proxy/lb_policy.go
  internal/proxy/lb_policy_test.go
  internal/proxy/look_aside_balancer.go
  internal/proxy/look_aside_balancer_test.go
  internal/proxy/roundrobin_balancer.go
  internal/querycoordv2/errors.go
  internal/querycoordv2/handlers.go
  internal/querycoordv2/job/errors.go
  internal/querycoordv2/job/job_load.go
  internal/querycoordv2/job/job_release.go
  internal/querycoordv2/job/job_sync.go
  internal/querycoordv2/job/job_test.go
  internal/querycoordv2/meta/resource_manager.go
  internal/querycoordv2/meta/resource_manager_test.go
  internal/querycoordv2/server_test.go
  internal/querycoordv2/services.go
  internal/querycoordv2/services_test.go
  internal/querycoordv2/task/task_test.go
  internal/querycoordv2/utils/meta.go
  internal/querycoordv2/utils/types.go
  internal/querynodev2/collector/average.go
  internal/querynodev2/services_test.go
  pkg/util/merr/errors.go
  pkg/util/merr/errors_test.go
  pkg/util/merr/utils.go
  tests/python_client/common/common_type.py
  tests/python_client/testcases/test_utility.py
Labels: kind/improvement, sig/testing, size/XL, approved, lgtm, area/test, ci-passed, dco-passed, manual-pass

#25408 Speed up of compiling thirdparty for aws and google sdk
  internal/core/thirdparty/CMakeLists.txt
  internal/core/thirdparty/aws_sdk/CMakeLists.txt
  internal/core/thirdparty/google_cloud_sdk/CMakeLists.txt
Labels: size/S, approved, lgtm, ci-passed, dco-passed, area/compilation, manual-pass

#25631 Fix datacoord crash
  internal/datacoord/services.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#25638 Fix querycoord crash
  internal/querycoordv2/checkers/balance_checker.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#25654 Make compaction rpc timeout and parallel maxium configurable
  configs/milvus.yaml
  internal/datacoord/compaction.go
  internal/datacoord/session_manager.go
  internal/util/paramtable/component_param.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#25613 fix panic due to lack of indexInfo on querynode(#25362)
  internal/proto/query_coord.proto
  internal/proto/querypb/query_coord.pb.go
  internal/querycoordv2/task/executor.go
  internal/querycoordv2/task/task_test.go
  internal/querycoordv2/task/utils.go
  internal/querynodev2/services.go
Labels: size/XL, approved, lgtm, ci-passed, area/internal-api, dco-passed, manual-pass

#25643 Fix segment loader skip wait if all segments are loading
  internal/querynodev2/segments/segment_loader.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#25479 Update pymilvus version and update some test cases
  ci/jenkins/Nightly.groovy
  tests/python_client/common/common_func.py
  tests/python_client/requirements.txt
  tests/python_client/testcases/test_collection.py
  tests/python_client/testcases/test_database.py
  tests/python_client/testcases/test_index.py
  tests/python_client/testcases/test_insert.py
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#25659 Fix monitoring metrics (#25549)
  internal/rootcoord/meta_table.go
  internal/rootcoord/proxy_client_manager.go
  internal/rootcoord/proxy_manager.go
  internal/rootcoord/quota_center.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#25660 Support refund the tokens to limiter (#25598)
  internal/proxy/multi_rate_limiter.go
  internal/util/ratelimitutil/limiter.go
  internal/util/ratelimitutil/limiter_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed, manual-pass
