Repository milvus-io/milvus, pull requests merged in 2023-08, with the labels that each got.

#26032 Fix lock usage in DataCoord compaction
  internal/datacoord/compaction.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#26021 Use different cgo pool for SQ and other operations
  internal/querynodev2/segments/pool.go
  internal/querynodev2/segments/segment.go
  pkg/util/conc/options.go
  pkg/util/conc/pool.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#26035 Add back segment CGO pool and separate sq/dm ops
  go.mod
  go.sum
  internal/datanode/io_pool.go
  internal/querynode/cgo_pool.go
  internal/querynode/flow_graph_delete_node.go
  internal/querynode/impl_test.go
  internal/querynode/mock_test.go
  internal/querynode/query_node.go
  internal/querynode/segment.go
  internal/querynode/segment_loader.go
  internal/util/concurrency/pool.go
  internal/util/concurrency/pool_option.go
  internal/util/concurrency/pool_option_test.go
  internal/util/paramtable/component_param.go
Labels: area/dependency, kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#26039 [test]Enable standby during rolling update and refine bulk insert
  tests/python_client/chaos/checker.py
  tests/python_client/chaos/testcases/test_get_collections.py
  tests/python_client/chaos/testcases/test_single_request_operation_for_rolling_update.py
  tests/python_client/deploy/milvus_crd.yaml
Labels: kind/improvement, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#26033 Record only failed task error
  internal/querycoordv2/services.go
  internal/querycoordv2/task/executor.go
  internal/querycoordv2/task/scheduler.go
  internal/querycoordv2/task/task.go
  internal/querycoordv2/task/task_test.go
  pkg/util/merr/utils.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#25888 Refine test chunkmanager of querynode v2
  internal/querynodev2/segments/mock_data.go
  internal/querynodev2/segments/reduce_test.go
  internal/querynodev2/segments/retrieve_test.go
  internal/querynodev2/segments/segment_loader_test.go
  internal/querynodev2/segments/segment_test.go
  internal/querynodev2/services_test.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#26025 Improve memory/disk usage prediction logs
  internal/querynode/segment_loader.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#26042 Fix lock usage in DataCoord compaction (#26032)
  internal/datacoord/compaction.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#25859 Fix collection and channel not match
  internal/proxy/lb_policy.go
  internal/proxy/lb_policy_test.go
  internal/proxy/meta_cache.go
  internal/proxy/meta_cache_test.go
  internal/proxy/mock_cache_test.go
  internal/proxy/mock_lb_policy.go
  internal/proxy/task.go
  internal/proxy/task_query.go
  internal/proxy/task_search.go
  internal/proxy/task_statistic.go
  internal/proxy/task_statistic_test.go
Labels: kind/bug, size/XL, approved, lgtm, ci-passed, dco-passed

#26045 Add worker num as one of load resource
  internal/querynodev2/segments/segment_loader.go
  pkg/util/merr/errors.go
  pkg/util/merr/errors_test.go
  pkg/util/merr/utils.go
  pkg/util/paramtable/param_item.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#26046 Add Promethues suite test utility
  internal/datacoord/cluster_test.go
  internal/datacoord/meta_test.go
  pkg/util/testutils/prometheus_metric.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#26022 Fix wrong log
  internal/querynodev2/handlers.go
  internal/querynodev2/services_test.go
Labels: kind/bug, kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#26061 Fix init log failed on macOS standalone mode
  internal/core/src/config/ConfigKnowhere.cpp
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#26050 Cancel previous ctx for session retry keepalive
  internal/util/sessionutil/session_util.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#26082 Fix panic while saw the failed task status
  internal/querycoordv2/task/scheduler.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#26056 Sync GlobleCompactionInterval unit to Second
  internal/util/paramtable/component_param.go
  internal/util/paramtable/component_param_test.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#25811 Upgrade minio-go and add region and virtual host config for segcore c…
  configs/milvus.yaml
  go.mod
  go.sum
  internal/core/src/common/type_c.h
  internal/core/src/indexbuilder/index_c.cpp
  internal/core/src/storage/MinioChunkManager.cpp
  internal/core/src/storage/Types.h
  internal/core/src/storage/storage_c.cpp
  internal/core/unittest/test_minio_chunk_manager.cpp
  internal/core/unittest/test_utils/indexbuilder_test_utils.h
  internal/datacoord/server_test.go
  internal/indexcoord/index_builder.go
  internal/proto/index_coord.proto
  internal/proto/indexpb/index_coord.pb.go
  internal/querynode/mock_test.go
  internal/storage/factory.go
  internal/storage/minio_chunk_manager.go
  internal/storage/minio_chunk_manager_test.go
  internal/storage/options.go
  internal/util/compressor/compressor_test.go
  internal/util/indexcgowrapper/build_index_info.go
  internal/util/initcore/init_storage_config.go
  internal/util/paramtable/base_table.go
  internal/util/paramtable/service_param.go
Labels: area/dependency, size/L, approved, lgtm, ci-passed, area/internal-api, dco-passed, manual-pass

#26086 [test]Refine timeout for search and query
  tests/python_client/chaos/checker.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed, manual-pass

#26060 Reduce log volumes of DC&DN
  internal/datacoord/services.go
  internal/datanode/services.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed

#26053 ci: fix kafka e2e pipeline
  ci/jenkins/PR.groovy
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#26028 add new threadpool with various priority to avoid deadlock(#25781)
  configs/milvus.yaml
  internal/core/src/common/Common.cpp
  internal/core/src/common/Common.h
  internal/core/src/common/Consts.h
  internal/core/src/common/init_c.cpp
  internal/core/src/common/init_c.h
  internal/core/src/index/VectorMemIndex.cpp
  internal/core/src/segcore/SegmentGrowingImpl.cpp
  internal/core/src/segcore/SegmentSealedImpl.cpp
  internal/core/src/storage/CMakeLists.txt
  internal/core/src/storage/DiskFileManagerImpl.cpp
  internal/core/src/storage/ThreadPool.cpp
  internal/core/src/storage/ThreadPool.h
  internal/core/src/storage/ThreadPools.cpp
  internal/core/src/storage/ThreadPools.h
  internal/core/src/storage/Util.cpp
  internal/core/unittest/test_disk_file_manager_test.cpp
  internal/indexnode/indexnode.go
  internal/querynodev2/server.go
  pkg/util/paramtable/component_param.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed, area/compilation, manual-pass

#26100 Remove unused code
  internal/querynodev2/segments/validate.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#26101 Cherry pick session util fixes
  internal/util/sessionutil/session_util.go
  internal/util/sessionutil/session_util_test.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#26029 Fix restore redrop enormous dup collections
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#26109 fix lost parameter for threadCoefficient
  internal/querynodev2/segments/segment_loader.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#26103 support metrics mutex to monitor cost of locks(#26102)
  configs/milvus.yaml
  pkg/metrics/metrics.go
  pkg/util/lock/metric_mutex.go
  pkg/util/lock/metrics_mutex_test.go
  pkg/util/paramtable/component_param.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#26095 disable retry in grpc connect and grpc sendMsg
  internal/util/grpcclient/client.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#26096 Optimize bitset usage
  internal/core/src/query/visitors/ExecPlanNodeVisitor.cpp
  internal/core/src/segcore/InsertRecord.h
  internal/core/src/segcore/SegmentGrowingImpl.h
  internal/core/src/segcore/SegmentInterface.cpp
  internal/core/src/segcore/SegmentInterface.h
  internal/core/src/segcore/SegmentSealedImpl.h
  internal/core/src/segcore/Utils.cpp
  internal/core/src/segcore/Utils.h
  internal/core/unittest/test_offset_ordered_array.cpp
  internal/core/unittest/test_offset_ordered_map.cpp
  internal/core/unittest/test_utils.cpp
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#26111 [skip e2e]Modify nightly log level to debug
  ci/jenkins/Nightly.groovy
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#26058 Fix useless log
  internal/proxy/task_search.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#26059 Fix useless log
  internal/proxy/task_search.go
  internal/querynode/flow_graph_insert_node.go
  internal/querynode/impl.go
Labels: kind/bug, kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#26115 [Cherry Pick]Check if database exists when Connect was called
  internal/proxy/impl.go
  internal/proxy/impl_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#26043 refine retry times on replica
  internal/proxy/lb_policy.go
  internal/proxy/lb_policy_test.go
  internal/proxy/look_aside_balancer.go
  internal/proxy/look_aside_balancer_test.go
  internal/querycoordv2/observers/leader_observer.go
  internal/querycoordv2/observers/leader_observer_test.go
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/component_param_test.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#26112 Fix compile failed with llvm16
  internal/core/conanfile.py
  internal/core/src/common/Types.h
  scripts/setenv.sh
Labels: size/S, approved, lgtm, ci-passed, dco-passed

#26107 [cherry-pick]ci: fix kafka e2e pipeline
  ci/jenkins/PR.groovy
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#26110 [cherry-pick][test]Update teardown method for restful test
  tests/restful_client/base/testbase.py
  tests/restful_client/conftest.py
  tests/restful_client/testcases/test_collection_operations.py
  tests/restful_client/testcases/test_vector_operations.py
  tests/scripts/ci_e2e.sh
Labels: kind/improvement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#26066 [2.2.0]Make check order more reasonable
  internal/util/indexparamcheck/bin_ivf_flat_checker.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#26054 remove pull target rpc from lock
  internal/querycoordv2/balance/rowcount_based_balancer_test.go
  internal/querycoordv2/balance/score_based_balancer_test.go
  internal/querycoordv2/checkers/channel_checker_test.go
  internal/querycoordv2/checkers/controller_test.go
  internal/querycoordv2/checkers/segment_checker_test.go
  internal/querycoordv2/job/job_load.go
  internal/querycoordv2/job/job_test.go
  internal/querycoordv2/meta/collection_manager.go
  internal/querycoordv2/meta/collection_manager_test.go
  internal/querycoordv2/meta/target.go
  internal/querycoordv2/meta/target_manager.go
  internal/querycoordv2/meta/target_manager_test.go
  internal/querycoordv2/observers/collection_observer.go
  internal/querycoordv2/observers/collection_observer_test.go
  internal/querycoordv2/observers/leader_observer_test.go
  internal/querycoordv2/observers/target_observer.go
  internal/querycoordv2/task/task_test.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#26118 Enable print_binlog support json data type
  internal/storage/print_binlog.go
  internal/storage/print_binlog_test.go
Labels: kind/enhancement, kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#26094 Reduce log volumes of DC&DN (#26060)
  internal/datacoord/services.go
  internal/datanode/data_node.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#26098 Add pursuit mode for mqtt msgstream
  internal/mq/msgstream/mqwrapper/rmq/rmq_client_test.go
  pkg/mq/msgdispatcher/mock_test.go
  pkg/mq/msgstream/mq_msgstream.go
  pkg/mq/msgstream/mq_msgstream_test.go
  pkg/util/paramtable/service_param.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#26123 Update e2e resource for branch 2.2.0
  ci/jenkins/PR.groovy
  ci/jenkins/pod/e2e.yaml
  ci/jenkins/pod/rte-build.yaml
  tests/scripts/values/ci/pr.yaml
Labels: kind/improvement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#25802 [Fixup] Short-term fix metacache data race
  internal/proxy/meta_cache.go
  internal/proxy/meta_cache_test.go
  internal/proxy/mock_cache_test.go
  internal/proxy/task.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#26064 Add default value for mq.type
  pkg/util/paramtable/service_param.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#25988 Delete the user-role mapping info when deleting the user
  internal/core/conanfile.py
  internal/metastore/kv/rootcoord/kv_catalog.go
  internal/metastore/kv/rootcoord/kv_catalog_test.go
  internal/proxy/impl.go
  internal/proxy/meta_cache.go
  internal/proxy/proxy_test.go
  internal/rootcoord/meta_table.go
  internal/rootcoord/meta_table_test.go
  internal/rootcoord/mock_test.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
  internal/rootcoord/step.go
  internal/rootcoord/util.go
  pkg/util/merr/errors_test.go
  pkg/util/merr/utils.go
  pkg/util/paramtable/component_param_test.go
  pkg/util/typeutil/cache.go
Labels: size/XXL, approved, lgtm, ci-passed, dco-passed

#26048 [Cherry-Pick]: Delete the user-role mapping info when deleting the user (#25988)
  internal/metastore/kv/rootcoord/kv_catalog.go
  internal/metastore/kv/rootcoord/kv_catalog_test.go
  internal/proxy/impl.go
  internal/proxy/meta_cache.go
  internal/proxy/proxy_test.go
  internal/rootcoord/mock_test.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
  internal/rootcoord/step.go
  internal/util/typeutil/cache.go
Labels: size/XL, approved, lgtm, ci-passed, dco-passed

#26144 Use last end position in pursuit mode
  pkg/mq/msgstream/mq_msgstream.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#26154 fix sync memory policy lose effect when inserting too many partitions
  internal/datanode/channel_meta.go
  internal/datanode/channel_meta_test.go
  internal/datanode/flow_graph_insert_buffer_node.go
  internal/datanode/flow_graph_manager_test.go
  internal/datanode/flush_manager.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#26150 Refine the rbac cache update process
  internal/proxy/meta_cache.go
  internal/proxy/meta_cache_test.go
  internal/rootcoord/root_coord.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#26151 Refine the rbac cache update process (#26150)
  internal/proxy/meta_cache.go
  internal/proxy/meta_cache_test.go
  internal/rootcoord/root_coord.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#26135 Fix failed to load index due to lost binary
  internal/core/src/index/VectorMemIndex.cpp
  internal/core/src/storage/MemFileManagerImpl.cpp
  internal/core/src/storage/MemFileManagerImpl.h
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#26167 Fix incorrect result while retrieving int8 type data
  internal/core/src/segcore/SegmentGrowingImpl.cpp
Labels: kind/bug, kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#25108 support high-level RESTFUL API, listen on the same port as grpc
  .golangci.yml
  go.mod
  go.sum
  internal/distributed/proxy/httpserver/constant.go
  internal/distributed/proxy/httpserver/handler_v1.go
  internal/distributed/proxy/httpserver/handler_v1_test.go
  internal/distributed/proxy/httpserver/request.go
  internal/distributed/proxy/httpserver/utils.go
  internal/distributed/proxy/httpserver/utils_test.go
  internal/distributed/proxy/service.go
  internal/distributed/proxy/service_test.go
  internal/proxy/privilege_interceptor.go
  internal/proxy/util.go
  pkg/util/merr/errors.go
  pkg/util/paramtable/http_param.go
  pkg/util/paramtable/http_param_test.go
Labels: area/dependency, size/XXL, approved, lgtm, ci-passed, dco-passed, area/compilation

#25923 Add a new configuration item: proxy.http.port
  internal/distributed/proxy/httpserver/constant.go
  internal/distributed/proxy/httpserver/handler_v1.go
  internal/distributed/proxy/httpserver/handler_v1_test.go
  internal/distributed/proxy/httpserver/request.go
  internal/distributed/proxy/httpserver/utils.go
  internal/distributed/proxy/httpserver/utils_test.go
  internal/distributed/proxy/service.go
  internal/distributed/proxy/service_test.go
  internal/util/paramtable/http_param.go
  internal/util/paramtable/http_param_test.go
  tests/restful_client/testcases/test_collection_operations.py
  tests/restful_client/testcases/test_vector_operations.py
Labels: area/dependency, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#26173 Delete useless config
  internal/querycoordv2/handlers.go
  internal/rootcoord/root_coord_test.go
  internal/rootcoord/timeticksync_test.go
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/component_param_test.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#26146 [test]Add test cases for restful and sdk mix use
  tests/restful_client/api/milvus.py
  tests/restful_client/base/testbase.py
  tests/restful_client/conftest.py
  tests/restful_client/testcases/test_collection_operations.py
  tests/restful_client/testcases/test_restful_sdk_mix_use_scenario.py
Labels: kind/improvement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#25896 Refine describe index that doesn't wait compacted segment indexed
  internal/indexcoord/index_coord.go
  internal/indexcoord/index_coord_test.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#25942 optimise install_deps.sh
  scripts/install_deps.sh
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#26136 Fix search on empty segments set bug
  internal/querycoordv2/observers/leader_observer.go
  internal/querycoordv2/observers/leader_observer_test.go
  internal/querycoordv2/task/executor.go
  internal/querycoordv2/utils/types.go
  internal/querycoordv2/utils/types_test.go
  internal/querynodev2/delegator/delegator_data.go
  internal/querynodev2/delegator/distribution.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#26176 force use DNS for aliyunoss because of sdk bug
  internal/storage/minio_chunk_manager.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#26163 Disable deny writing when the growing segment size exceeds the watermark
  configs/milvus.yaml
  internal/rootcoord/quota_center.go
  internal/rootcoord/quota_center_test.go
  pkg/util/paramtable/quota_param.go
  pkg/util/paramtable/quota_param_test.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#26196 [skip e2e]add mergify rule
  .github/mergify.yml
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#26133 Add unit test for channel store reload & metrics
  internal/datacoord/channel_store_test.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#26209 [skip e2e]Update mergify rule for related pr
  .github/mergify.yml
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#26195 refine log out for datanode(#25763)
  internal/datanode/channel_meta.go
  internal/datanode/flow_graph_insert_buffer_node.go
  internal/datanode/flow_graph_manager.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed

#26217 Fix copylocks linter errors
  internal/datanode/compactor_test.go
  internal/datanode/flow_graph_insert_buffer_node_test.go
  internal/datanode/io_pool_test.go
  internal/distributed/proxy/service.go
  internal/distributed/querynode/client/client.go
  internal/indexnode/taskinfo_ops.go
  internal/proxy/multi_rate_limiter_test.go
  internal/proxy/util_test.go
  internal/rootcoord/quota_center_test.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#26204 Update pymilvus version
  tests/python_client/requirements.txt
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed, manual-pass, kind/branch-feature

#26203 Save binlog timestampFrom, timestampTo meta when compact
  internal/datacoord/compaction_trigger.go
  internal/datanode/compactor.go
  internal/datanode/compactor_test.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#26210 Save binlog timestampFrom, timestampTo meta when compact
  internal/datacoord/compaction_trigger.go
  internal/datanode/compactor.go
  internal/datanode/compactor_test.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#26220 Fix bug for GetIndexState
  internal/indexcoord/meta_table.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass, kind/branch-feature

#26171 [cherry-pick]Fix incorrect result while retrieving int8 type data
  internal/core/src/segcore/SegmentGrowingImpl.cpp
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass, do-not-merge/missing-related-pr

#26179 Reduce MQ buffer length and flowgraph wait queue length to 16
  configs/milvus.yaml
  internal/mq/msgstream/mq_factory.go
  internal/mq/msgstream/mq_factory_test.go
  internal/util/dependency/factory.go
  pkg/mq/msgdispatcher/mock_test.go
  pkg/mq/msgstream/mq_factory.go
  pkg/mq/msgstream/mq_factory_test.go
  pkg/mq/msgstream/mqwrapper/kafka/kafka_client.go
  pkg/mq/msgstream/mqwrapper/kafka/kafka_consumer.go
  pkg/mq/msgstream/mqwrapper/kafka/kafka_consumer_test.go
  pkg/mq/msgstream/msgstream_util_test.go
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/component_param_test.go
  pkg/util/paramtable/service_param.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#26190 Fix miss index file while slice meta contains raw data only
  internal/core/src/index/VectorMemIndex.cpp
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#26206 Bump semver to 2.2.13
  internal/common/version.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass, kind/branch-feature

#26218 Fix nilness linter errors
  internal/distributed/proxy/httpserver/utils.go
  internal/indexnode/indexnode.go
  internal/rootcoord/meta_table.go
  internal/storage/data_codec.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#26132 enable config shard level cost metrics whether contains worker's cost
  internal/querynodev2/segments/result.go
  internal/querynodev2/tasks/query_task.go
  internal/querynodev2/tasks/task.go
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/component_param_test.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#26229 Perform alter distribution under mutex protection
  internal/querynodev2/delegator/delegator_data.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#26208 Disable deny writing when the growing segment size exceeds the watermark (#26163)
  configs/milvus.yaml
  internal/rootcoord/quota_center.go
  internal/rootcoord/quota_center_test.go
  internal/util/paramtable/quota_param.go
  internal/util/paramtable/quota_param_test.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#26226 Replace deprecated grpc WithInsecure option
  internal/distributed/connection_manager.go
  internal/distributed/proxy/service_test.go
  internal/querycoordv2/session/cluster_test.go
  internal/util/grpcclient/client.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#26127 Fix rate limit not woring for upsert
  internal/proxy/rate_limit_interceptor.go
  internal/proxy/rate_limit_interceptor_test.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#26182 Fix components' setup
  cmd/roles/roles.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#26233 [skip e2e]Bump milvus version to 2.2.13
  deployments/binary/README.md
  deployments/docker/standalone/docker-compose.yml
Labels: kind/improvement, size/XS, ci-passed, dco-passed, kind/branch-feature

#26216 [skip e2e]Update workflows/main.yaml
  .github/workflows/main.yaml
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed, kind/branch-feature

#26174 Fix database cases
  tests/python_client/testcases/test_database.py
Labels: sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#26236 Fix load index with empty file list
  internal/querycoordv2/checkers/index_checker.go
  internal/querycoordv2/checkers/index_checker_test.go
  internal/querynodev2/segments/segment_loader.go
  internal/querynodev2/segments/segment_loader_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#26207 Fast GC compacted dropped segment
  internal/datacoord/garbage_collector.go
  internal/datacoord/garbage_collector_test.go
  internal/datacoord/meta.go
  internal/proto/data_coord.proto
  internal/proto/datapb/data_coord.pb.go
Labels: size/XL, approved, lgtm, ci-passed, dco-passed

#26187 Fix incorrect error message while validating insert data
  internal/proxy/validate_util.go
  internal/proxy/validate_util_test.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#26153 Support empty expression
  internal/core/src/pb/plan.pb.cc
  internal/core/src/pb/plan.pb.h
  internal/core/src/query/Expr.h
  internal/core/src/query/PlanProto.cpp
  internal/core/src/query/generated/ExecExprVisitor.h
  internal/core/src/query/generated/Expr.cpp
  internal/core/src/query/generated/ExprVisitor.h
  internal/core/src/query/generated/ExtractInfoExprVisitor.h
  internal/core/src/query/generated/ShowExprVisitor.h
  internal/core/src/query/generated/VerifyExprVisitor.h
  internal/core/src/query/visitors/ExecExprVisitor.cpp
  internal/core/src/query/visitors/ExtractInfoExprVisitor.cpp
  internal/core/src/query/visitors/ShowExprVisitor.cpp
  internal/core/src/query/visitors/VerifyExprVisitor.cpp
  internal/core/unittest/CMakeLists.txt
  internal/core/unittest/test_always_true_expr.cpp
  internal/parser/planparserv2/plan_parser_v2.go
  internal/parser/planparserv2/plan_parser_v2_test.go
  internal/parser/planparserv2/utils.go
  internal/parser/planparserv2/utils_test.go
  internal/proto/plan.proto
  internal/proto/planpb/plan.pb.go
  internal/proxy/task_query.go
Labels: kind/feature, size/XXL, approved, lgtm, ci-passed, dco-passed, area/compilation

#26231 modify default value for sync max parallel to mitigate oom on dn(#26763)
  configs/milvus.yaml
  pkg/util/paramtable/component_param.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#25877 Enable mmap for vector index
  Makefile
  internal/core/src/index/Index.h
  internal/core/src/index/Utils.cpp
  internal/core/src/index/VectorIndex.h
  internal/core/src/index/VectorMemIndex.cpp
  internal/core/src/index/VectorMemIndex.h
  internal/core/src/mmap/Column.h
  internal/core/src/mmap/Utils.h
  internal/core/src/query/SearchOnSealed.cpp
  internal/core/src/segcore/SegmentSealedImpl.cpp
  internal/core/src/segcore/Types.h
  internal/core/src/segcore/load_index_c.cpp
  internal/core/src/segcore/load_index_c.h
  internal/core/src/utils/File.h
  internal/core/unittest/test_c_api.cpp
  internal/core/unittest/test_index_c_api.cpp
  internal/core/unittest/test_indexing.cpp
  internal/querynodev2/segments/load_index_info.go
  internal/querynodev2/segments/segment_loader.go
  internal/querynodev2/server.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed, area/compilation

#26224 [skip e2e]Disable heaptrack in standalone deployment
  tests/python_client/chaos/nats-standalone-values.yaml
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#26248 Fix sessionutil Liveness check block in watch forever
  internal/util/sessionutil/session_util.go
  internal/util/sessionutil/session_util_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed, PR | need cherry-pick

#24782 Add default retrieve limit
  internal/core/src/common/Consts.h
  internal/core/src/segcore/SegmentGrowingImpl.cpp
  internal/core/src/segcore/SegmentInterface.cpp
  internal/core/src/segcore/SegmentInterface.h
  internal/core/src/segcore/SegmentSealedImpl.cpp
  internal/core/src/segcore/Utils.cpp
  internal/core/src/segcore/Utils.h
  internal/core/src/segcore/segment_c.cpp
  internal/core/src/segcore/segment_c.h
  internal/core/src/storage/Util.cpp
  internal/core/src/storage/Util.h
  internal/core/unittest/test_c_api.cpp
  internal/core/unittest/test_retrieve.cpp
  internal/core/unittest/test_string_expr.cpp
  internal/proxy/task_query.go
  internal/proxy/task_query_test.go
  internal/proxy/task_search.go
  internal/querynodev2/segments/result.go
  internal/querynodev2/segments/result_test.go
  internal/querynodev2/segments/segment.go
  internal/querynodev2/segments/segment_loader.go
  pkg/util/paramtable/quota_param.go
  pkg/util/typeutil/schema.go
Labels: kind/bug, size/XL, approved, lgtm, ci-passed, dco-passed, manual-pass

#26250 [Cherry-Pick] Fix sessionutil Liveness check blcok in watch forever
  internal/util/sessionutil/session_util.go
  internal/util/sessionutil/session_util_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#26235 Remove redundant macro setting for knowhere
  internal/core/CMakeLists.txt
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed, area/compilation

#26263 Fix leader view return loading shard cluster
  internal/querynode/shard_cluster_service.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed, kind/branch-feature

#26227 fix describe rg with non exist collection
  internal/proxy/meta_cache.go
  internal/proxy/meta_cache_test.go
  internal/proxy/mock_cache.go
  internal/proxy/task.go
  internal/proxy/task_test.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#26119 Remove time travel 1
  internal/core/src/segcore/SegmentInterface.cpp
  internal/core/src/segcore/SegmentInterface.h
  internal/core/src/segcore/segment_c.cpp
  internal/core/src/segcore/segment_c.h
  internal/core/unittest/bench/bench_search.cpp
  internal/core/unittest/test_c_api.cpp
  internal/core/unittest/test_growing_index.cpp
  internal/core/unittest/test_query.cpp
  internal/core/unittest/test_sealed.cpp
  internal/core/unittest/test_string_expr.cpp
  internal/proto/internal.proto
  internal/proto/internalpb/internal.pb.go
  internal/proxy/impl.go
  internal/proxy/task_query.go
  internal/proxy/task_search.go
  internal/proxy/task_statistic.go
  internal/proxy/util.go
  internal/proxy/util_test.go
  internal/querynodev2/segments/mock_data.go
  internal/querynodev2/segments/plan.go
  internal/querynodev2/segments/reduce_test.go
  internal/querynodev2/segments/segment.go
  internal/querynodev2/services.go
  internal/querynodev2/services_test.go
  internal/querynodev2/tasks/query_task.go
  internal/querynodev2/tasks/task.go
  tests/python_client/testcases/test_compaction.py
  tests/python_client/testcases/test_delete.py
  tests/python_client/testcases/test_query.py
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/XXL, approved, lgtm, area/test, ci-passed, area/internal-api, dco-passed

#26128 Not allow to set partition name for collection with partition key
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#26129 [cherry-pick] Not allow to set partition name for collection with partition key
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#26259 [Cherry-Pick] Replace deprecated grpc WithInsecure option
  internal/distributed/connection_manager.go
  internal/distributed/proxy/service_test.go
  internal/querycoordv2/session/cluster_test.go
  internal/util/grpcclient/client.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#26071 Add test cases about json contains and others
  tests/python_client/requirements.txt
  tests/python_client/testcases/test_insert.py
  tests/python_client/testcases/test_query.py
  tests/python_client/testcases/test_search.py
  tests/python_client/testcases/test_utility.py
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#26213 fix unexpected score in look aside balancer
  internal/proxy/look_aside_balancer.go
  internal/proxy/look_aside_balancer_test.go
  pkg/metrics/proxy_metrics.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#26239 Fix miss to handle error from GetCollectionSchema
  internal/proxy/meta_cache.go
  internal/proxy/task_search.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#25675 Add disk metric info
  internal/querynodev2/segments/segment_loader.go
  internal/querynodev2/server.go
  pkg/metrics/querynode_metrics.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#26194 add region and virtual host config for segcore chunk manager
  configs/milvus.yaml
  go.mod
  go.sum
  internal/core/src/common/type_c.h
  internal/core/src/indexbuilder/index_c.cpp
  internal/core/src/storage/MinioChunkManager.cpp
  internal/core/src/storage/Types.h
  internal/core/src/storage/storage_c.cpp
  internal/core/unittest/test_disk_file_manager_test.cpp
  internal/core/unittest/test_index_wrapper.cpp
  internal/core/unittest/test_indexing.cpp
  internal/core/unittest/test_minio_chunk_manager.cpp
  internal/core/unittest/test_utils/indexbuilder_test_utils.h
  internal/datacoord/index_builder.go
  internal/datacoord/server_test.go
  internal/proto/index_coord.proto
  internal/proto/indexpb/index_coord.pb.go
  internal/storage/factory.go
  internal/storage/minio_chunk_manager.go
  internal/storage/minio_chunk_manager_test.go
  internal/storage/options.go
  internal/util/indexcgowrapper/build_index_info.go
  internal/util/initcore/init_core.go
  pkg/util/compressor/compressor_test.go
  pkg/util/paramtable/base_table.go
  pkg/util/paramtable/service_param.go
Labels: area/dependency, size/XL, approved, lgtm, ci-passed, area/internal-api, dco-passed, manual-pass

#26191 Refine index log
  internal/datacoord/index_service.go
Labels: kind/improvement, size/XS, dco-passed

#26180 fix set dirty segment distribution to leader view
  Makefile
  internal/querycoordv2/observers/leader_observer.go
  internal/querycoordv2/services.go
  internal/querynodev2/cluster/mock_manager.go
  internal/querynodev2/delegator/distribution.go
  internal/querynodev2/delegator/distribution_test.go
  internal/querynodev2/handlers.go
  internal/querynodev2/segments/manager.go
  internal/querynodev2/segments/mock_loader.go
  internal/querynodev2/segments/mock_segment.go
  internal/querynodev2/segments/mock_segment_manager.go
  internal/querynodev2/segments/segment.go
  internal/querynodev2/segments/segment_interface.go
  internal/querynodev2/segments/segment_loader.go
  internal/querynodev2/segments/segment_loader_test.go
  internal/querynodev2/services_test.go
Labels: size/XL, approved, lgtm, ci-passed, dco-passed, area/compilation, manual-pass

#26269 Add rpath ldflag for unittest
  scripts/run_go_unittest.sh
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#26258 [cherry-pick] disable retry in grpc connect and grpc sendMsg
  internal/util/grpcclient/client.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#26099 Support ScaNN index
  internal/core/thirdparty/knowhere/CMakeLists.txt
  internal/querynodev2/mock_data.go
  internal/querynodev2/segments/mock_data.go
  internal/util/indexcgowrapper/index_test.go
  pkg/util/indexparamcheck/conf_adapter_mgr.go
  pkg/util/indexparamcheck/conf_adapter_mgr_test.go
  pkg/util/indexparamcheck/index_type.go
  tests/integration/getvector/get_vector_test.go
  tests/integration/util_index.go
Labels: sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed, area/compilation, test/integration

#26265 Optimize multi logical exprs performance when meet some situations
  internal/core/src/query/visitors/ExecExprVisitor.cpp
  internal/core/unittest/test_expr.cpp
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#25384 Support json contains feature
  internal/core/src/common/Types.h
  internal/core/src/pb/plan.pb.cc
  internal/core/src/pb/plan.pb.h
  internal/core/src/query/Expr.h
  internal/core/src/query/ExprImpl.h
  internal/core/src/query/PlanProto.cpp
  internal/core/src/query/PlanProto.h
  internal/core/src/query/generated/ExecExprVisitor.h
  internal/core/src/query/generated/Expr.cpp
  internal/core/src/query/generated/ExprVisitor.h
  internal/core/src/query/generated/ExtractInfoExprVisitor.h
  internal/core/src/query/generated/ShowExprVisitor.h
  internal/core/src/query/generated/VerifyExprVisitor.h
  internal/core/src/query/visitors/ExecExprVisitor.cpp
  internal/core/src/query/visitors/ExtractInfoExprVisitor.cpp
  internal/core/src/query/visitors/ShowExprVisitor.cpp
  internal/core/src/query/visitors/VerifyExprVisitor.cpp
  internal/core/unittest/test_expr.cpp
  internal/core/unittest/test_utils/DataGen.h
  internal/parser/planparserv2/Plan.g4
  internal/parser/planparserv2/generated/Plan.interp
  internal/parser/planparserv2/generated/Plan.tokens
  internal/parser/planparserv2/generated/PlanLexer.interp
  internal/parser/planparserv2/generated/PlanLexer.tokens
  internal/parser/planparserv2/generated/plan_base_visitor.go
  internal/parser/planparserv2/generated/plan_lexer.go
  internal/parser/planparserv2/generated/plan_parser.go
  internal/parser/planparserv2/generated/plan_visitor.go
  internal/parser/planparserv2/parser_visitor.go
  internal/parser/planparserv2/plan_parser_v2_test.go
  internal/proto/plan.proto
  internal/proto/planpb/plan.pb.go
  tests/integration/jsonexpr/json_expr_test.go
Labels: sig/testing, size/XXL, approved, lgtm, area/test, ci-passed, dco-passed, test/integration

#26293 Fix spawn too many threads
  .clang-tidy
  configs/milvus.yaml
  internal/querynodev2/segments/segment_loader.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#26295 Fix missing totalChannelNum bug
  internal/querynodev2/services.go
  internal/querynodev2/services_test.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#26030 Fix restore redrop enormous dup collections
  Makefile
  internal/mocks/mock_rootcoord.go
  internal/rootcoord/mocks/GarbageCollector.go
  internal/rootcoord/mocks/IMetaTable.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
Labels: kind/improvement, size/XXL, approved, lgtm, ci-passed, dco-passed, area/compilation

#26264 Fix calculation of memory usage prediction for mmap mode
  internal/core/src/mmap/Column.h
  internal/querynodev2/segments/segment_loader.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#26302 Fix IndexNode panic if storage config empty
  internal/indexnode/chunk_mgr_factory.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#26314 Fix kafka producer init many times
  pkg/mq/msgstream/mqwrapper/kafka/kafka_client.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#26268 Add ut for growing segment load binlog
  internal/core/unittest/init_gtest.cpp
  internal/core/unittest/test_c_api.cpp
  internal/core/unittest/test_disk_file_manager_test.cpp
  internal/core/unittest/test_index_c_api.cpp
  internal/core/unittest/test_index_wrapper.cpp
  internal/core/unittest/test_indexing.cpp
  internal/core/unittest/test_utils/indexbuilder_test_utils.h
  internal/core/unittest/test_utils/storage_test_utils.h
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#26286 Use Knowhere AIO Context Init Defalut Value and Panic when Fail
  internal/core/src/config/ConfigKnowhere.cpp
  internal/core/thirdparty/knowhere/CMakeLists.txt
  internal/core/unittest/test_init.cpp
Labels: size/S, approved, lgtm, ci-passed, dco-passed, area/compilation

#26312 Check data consistency after loading
  internal/core/src/mmap/Column.h
  internal/core/src/segcore/SegmentSealedImpl.cpp
  internal/core/src/segcore/SegmentSealedImpl.h
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#26319 Fix compile error on Arm
  internal/core/src/query/visitors/ExecExprVisitor.cpp
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#26168 [Fixup] nats log configuration
  configs/milvus.yaml
  pkg/mq/msgstream/mqwrapper/nmq/nmq_server.go
  pkg/mq/msgstream/mqwrapper/nmq/nmq_server_test.go
  pkg/util/paramtable/service_param.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#26253 Chanege cluster for e2e to 4am
  ci/jenkins/PR.groovy
  ci/jenkins/pod/e2e.yaml
  ci/jenkins/pod/rte-build.yaml
  tests/scripts/ci-util-4am.sh
  tests/scripts/ci_e2e_4am.sh
  tests/scripts/ci_logs.sh
  tests/scripts/values/ci/pr-4am.yaml
Labels: kind/improvement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, manual-pass

#26274 Chanege cluster for e2e to 4am
  ci/jenkins/PR.groovy
  ci/jenkins/pod/e2e.yaml
  ci/jenkins/pod/rte-build.yaml
  tests/scripts/ci-util-4am.sh
  tests/scripts/ci_e2e_4am.sh
  tests/scripts/ci_logs.sh
  tests/scripts/values/ci/pr-4am.yaml
Labels: kind/improvement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#26328 Set default thread pool size to be smaller
  internal/core/src/common/Consts.h
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#26117 Refine index log
  internal/indexcoord/index_coord.go
  internal/indexnode/indexnode_service.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#26067 Add cases about offset and alias
  tests/python_client/requirements.txt
  tests/python_client/testcases/test_collection.py
  tests/python_client/testcases/test_search.py
  tests/python_client/testcases/test_utility.py
Labels: sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#26310 Refactor log for Query
  internal/querycoordv2/dist/dist_controller.go
  internal/querycoordv2/job/job_load.go
  internal/querycoordv2/job/job_sync.go
  internal/querycoordv2/meta/collection_manager.go
  internal/querycoordv2/meta/coordinator_broker.go
  internal/querycoordv2/meta/target_manager.go
  internal/querycoordv2/observers/leader_observer.go
  internal/querycoordv2/observers/target_observer.go
  internal/querycoordv2/server.go
  internal/querycoordv2/services.go
  internal/querycoordv2/task/scheduler.go
  internal/querycoordv2/utils/meta.go
  internal/querynodev2/delegator/distribution.go
  internal/querynodev2/pipeline/manager.go
  internal/querynodev2/segments/result.go
  internal/querynodev2/segments/segment_loader.go
  internal/querynodev2/server.go
  internal/querynodev2/services.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#26354 Add -g flag to compile with debug info
  internal/core/CMakeLists.txt
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed, area/compilation

#26335 Use float64 for resource estimation log
  internal/querynodev2/segments/segment_loader.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#26344 Update DiskAnnMinDim value
  pkg/util/indexparamcheck/constraints.go
  pkg/util/indexparamcheck/diskann_checker_test.go
  tests/python_client/testcases/test_index.py
Labels: kind/improvement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#26338 set sealed segment to unreadable before sync target version
  internal/querynodev2/delegator/delegator_data_test.go
  internal/querynodev2/delegator/delegator_test.go
  internal/querynodev2/delegator/distribution.go
  internal/querynodev2/delegator/distribution_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#26356 Adjust some confusing Warning log to INFO
  internal/datacoord/garbage_collector.go
  internal/datanode/flow_graph_dd_node.go
  internal/proxy/privilege_interceptor.go
  pkg/util/funcutil/policy.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#26370 Fill Collection start position timestamp in WatchInfo
  internal/datacoord/channel_manager.go
  internal/datacoord/handler.go
  internal/datacoord/services.go
  internal/proto/data_coord.proto
  internal/proto/datapb/data_coord.pb.go
  internal/rootcoord/broker.go
Labels: kind/bug, size/XL, approved, lgtm, ci-passed, dco-passed

#26380 Use map&mutex for dispatcher client
  pkg/mq/msgdispatcher/client.go
  pkg/mq/msgdispatcher/client_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#26363 [skip e2e] Fix unstable TestSingleflight unit test
  pkg/util/conc/singleflight_test.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#26374 Remove QueryMsgStream in MqFactory interface
  docs/developer_guides/chap04_message_stream.md
  internal/datanode/flow_graph_dmstream_input_node_test.go
  internal/indexnode/chunkmgr_mock.go
  internal/mq/msgstream/mq_factory_test.go
  internal/proxy/channels_mgr.go
  internal/proxy/channels_mgr_test.go
  internal/proxy/mock_msgstream_test.go
  internal/proxy/mock_test.go
  internal/util/dependency/factory.go
  pkg/mq/msgstream/common_mq_factory.go
  pkg/mq/msgstream/factory_test.go
  pkg/mq/msgstream/mq_factory.go
  pkg/mq/msgstream/mq_factory_test.go
  pkg/mq/msgstream/msgstream.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#26332 Add data sync service close log for watch stuck debugging
  internal/datanode/data_sync_service.go
  internal/datanode/flush_manager.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#26339 add log trace for segcore(#26277)
  internal/core/src/common/Tracer.cpp
  internal/core/src/common/Tracer.h
  internal/core/src/segcore/segment_c.cpp
  internal/proxy/task_insert.go
  internal/querynodev2/tsafe/manager.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#26383 Check the offsets of search result
  internal/core/src/segcore/Reduce.cpp
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#26347 Fix the number of rows of column not correct
  internal/core/src/mmap/Column.h
  internal/core/src/segcore/SegmentInterface.cpp
  internal/core/src/segcore/SegmentSealedImpl.cpp
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#26372 Update range search cases
  tests/python_client/common/common_func.py
  tests/python_client/common/common_type.py
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#26350 Support to update the hook config in the runtime
  internal/proxy/hook_interceptor.go
  pkg/util/paramtable/hook_config.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#26387 Fix data race while updating segment version
  internal/querynodev2/segments/segment.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#26389 Calculate memory usage without page cache
  internal/querycoordv2/task/scheduler.go
  pkg/util/hardware/container_linux.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#26271 Add test cases of query empty expression
  tests/python_client/testcases/test_query.py
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#26360 refine retry on grpc
  configs/milvus.yaml
  internal/util/grpcclient/client.go
  pkg/util/paramtable/grpc_param.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#26365 Fix error message of proto parser not clear
  internal/core/src/query/PlanProto.cpp
  internal/core/unittest/CMakeLists.txt
  internal/core/unittest/test_plan_proto.cpp
Labels: size/M, approved, lgtm, ci-passed, dco-passed, area/compilation
