Repository milvus-io/milvus, pull requests merged in 2023-01, with the labels that each got.

#21469 Make the `UnsubDmChannel` rpc unsuccessful when the releaseCollectionTask fails
  internal/querynode/impl.go
  internal/querynode/impl_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#21473 fix empty auth config unmarshal
  internal/util/paramtable/service_param.go
  internal/util/paramtable/service_param_test.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#21474 fix auth config unmarshal
  internal/util/paramtable/service_param.go
  internal/util/paramtable/service_param_test.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed

#21486 [test]Fix deploy test
  tests/python_client/chaos/scripts/install_milvus.sh
  tests/python_client/deploy/testcases/test_action_first_deployment.py
Labels: kind/improvement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#21487 [Cherry-Pick][test]Fix deploy test
  tests/python_client/chaos/scripts/install_milvus.sh
  tests/python_client/deploy/testcases/test_action_first_deployment.py
Labels: kind/improvement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#21456 Upgrade pulsar client
  go.mod
  go.sum
  internal/mq/msgstream/mq_factory_test.go
  internal/mq/msgstream/mqwrapper/pulsar/pulsar_client_test.go
Labels: area/dependency, size/M, approved, lgtm, ci-passed, dco-passed

#21490 Setup first tsafe to avoid false maxLag error
  internal/querynode/flow_graph_query_node.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#21478 Use tt msg stream for consume delete msg
  internal/querynode/mock_test.go
  internal/querynode/segment_loader.go
  internal/querynode/segment_loader_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#21235 Fix bad import task expiration default
  internal/util/paramtable/component_param.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#21492 Increase timeout minutes of UT temporarily
  .github/workflows/main.yaml
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#21471 Fix collection not exist when tried to do recovery
  Makefile
  internal/common/error.go
  internal/common/error_test.go
  internal/datacoord/compaction_trigger.go
  internal/datacoord/mock_test.go
  internal/datacoord/server.go
  internal/datacoord/server_test.go
  internal/datacoord/services.go
  internal/datanode/meta_service.go
  internal/datanode/meta_service_test.go
  internal/datanode/mock_test.go
  internal/distributed/proxy/service_test.go
  internal/distributed/rootcoord/client/client.go
  internal/distributed/rootcoord/service.go
  internal/mocks/mock_rootcoord.go
  internal/proto/root_coord.proto
  internal/proto/rootcoordpb/root_coord.pb.go
  internal/proxy/rootcoord_mock_test.go
  internal/querycoordv2/meta/coordinator_broker.go
  internal/querycoordv2/meta/coordinator_broker_test.go
  internal/rootcoord/broker.go
  internal/rootcoord/broker_test.go
  internal/rootcoord/describe_collection_task.go
  internal/rootcoord/describe_collection_task_test.go
  internal/rootcoord/import_helper.go
  internal/rootcoord/meta_table.go
  internal/rootcoord/meta_table_test.go
  internal/rootcoord/mock_test.go
  internal/rootcoord/mocks/IMetaTable.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
  internal/rootcoord/show_partition_task.go
  internal/rootcoord/show_partition_task_test.go
  internal/types/types.go
  internal/util/mock/grpc_rootcoord_client.go
Labels: kind/bug, size/XL, approved, lgtm, ci-passed, dco-passed, area/compilation

#21503 Fix the bug statistics indexnode num
  internal/indexcoord/index_coord.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#20875 Support upsert
  internal/core/src/segcore/Utils.h
  internal/core/unittest/test_c_api.cpp
  internal/core/unittest/test_utils.cpp
  internal/distributed/proxy/service.go
  internal/distributed/proxy/service_test.go
  internal/metrics/metrics.go
  internal/mq/msgstream/msg.go
  internal/proxy/impl.go
  internal/proxy/proxy_test.go
  internal/proxy/task.go
  internal/proxy/task_delete.go
  internal/proxy/task_insert.go
  internal/proxy/task_test.go
  internal/proxy/task_upsert.go
  internal/proxy/task_upsert_test.go
  internal/proxy/util.go
  internal/proxy/util_test.go
  internal/querynode/flow_graph_filter_dm_node.go
  internal/types/types.go
Labels: area/dependency, size/XXL, approved, lgtm, ci-passed, dco-passed, behavior-change

#21514 limit the frequency of GetMetrics() log
  internal/datacoord/services.go
  internal/datanode/services.go
  internal/indexcoord/index_coord.go
  internal/indexnode/indexnode_service.go
  internal/proxy/impl.go
  internal/querycoordv2/services.go
  internal/querynode/impl.go
  internal/rootcoord/root_coord.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#21519 [Cherry-Pick] limit the frequency of GetMetrics() log (#21514)
  internal/datacoord/services.go
  internal/datanode/data_node.go
  internal/indexcoord/index_coord.go
  internal/indexnode/indexnode_service.go
  internal/proxy/impl.go
  internal/querycoordv2/services.go
  internal/querynode/impl.go
  internal/rootcoord/root_coord.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#21493 Optimize GetLoadingProgress to save RPC
  internal/proxy/impl.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#21515 Empty implement of the `GetLoadState` api
  go.mod
  go.sum
  internal/core/src/pb/common.pb.cc
  internal/core/src/pb/common.pb.h
  internal/distributed/proxy/service.go
  internal/distributed/proxy/service_test.go
  internal/proxy/impl.go
  internal/types/types.go
Labels: area/dependency, kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#21521 Modify test cases consistent with master
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#21522 Skip some cases not supported yet
  tests/python_client/testcases/test_alias.py
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#21501 quick fix queryCoordV2 active-standby
  internal/querycoordv2/server.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#21500 Use tt msg stream for consume delete msg (#21478)
  internal/querynode/mock_test.go
  internal/querynode/segment_loader.go
  internal/querynode/segment_loader_test.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#21499 Fix checkpoint will not update after delete and compact (#21495)
  internal/datanode/flow_graph_delete_node.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#21532 [cherry-pick]Refine bulkinsert
  internal/datanode/data_node.go
  internal/rootcoord/import_manager.go
  internal/rootcoord/import_manager_test.go
  internal/rootcoord/root_coord_test.go
  internal/util/importutil/import_util.go
  internal/util/importutil/import_wrapper.go
  internal/util/importutil/import_wrapper_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#21535 [Cherry-Pick] Add With method for MLogger (#21530)
  internal/log/mlogger.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#21518 [test]Add assert for chaos test
  tests/python_client/chaos/testcases/test_all_collections_after_chaos.py
  tests/python_client/testcases/test_e2e.py
Labels: kind/improvement, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#21531 [test]Update creating index behavior
  tests/python_client/base/client_base.py
  tests/python_client/chaos/testcases/test_all_collections_after_chaos.py
  tests/python_client/testcases/test_collection.py
  tests/python_client/testcases/test_delete.py
  tests/python_client/testcases/test_e2e.py
  tests/python_client/testcases/test_index.py
  tests/python_client/testcases/test_query.py
  tests/python_client/testcases/test_search.py
Labels: kind/improvement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#21533 [cherry-pick]: Implement the `GetLoadState` api
  internal/proxy/impl.go
  internal/proxy/proxy_test.go
  internal/proxy/util.go
Labels: size/XL, approved, lgtm, ci-passed, dco-passed

#21467 Add guarantee and serviceable lag too large check (#21441)
  configs/milvus.yaml
  internal/querynode/errors.go
  internal/querynode/task_read.go
  internal/querynode/task_read_test.go
  internal/util/paramtable/component_param.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed, behavior-change

#21544 Fix show configuration bug
  internal/config/manager.go
  internal/util/paramtable/base_table_test.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed

#21551 Remove redundant LoadPrefix requests for Catalog ListCollections
  internal/metastore/kv/rootcoord/kv_catalog.go
  internal/metastore/kv/rootcoord/kv_catalog_test.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#21536 Update cgroups version from v1.0.2 to v1.0.4
  go.mod
  go.sum
Labels: kind/bug, area/dependency, size/XS, approved, lgtm, ci-passed, dco-passed

#21556 [cherry-pick]: Support the graceful stop for the indexnode
  internal/distributed/indexnode/service.go
  internal/indexcoord/index_coord.go
  internal/indexcoord/index_coord_test.go
  internal/indexcoord/node_manager.go
  internal/indexcoord/node_manager_test.go
  internal/indexnode/indexnode.go
  internal/indexnode/indexnode_service.go
  internal/indexnode/indexnode_service_test.go
  internal/indexnode/indexnode_test.go
  internal/indexnode/taskinfo_ops.go
  internal/util/commonpbutil/commonpbutil.go
  internal/util/commonpbutil/commonpbutil_test.go
  internal/util/paramtable/component_param.go
  internal/util/paramtable/component_param_test.go
Labels: size/XL, approved, lgtm, ci-passed, dco-passed

#21526 Increase bulk insert file size limit
  internal/util/importutil/import_wrapper.go
  internal/util/importutil/json_parser_test.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#21497 [Cherry-Pick] Setup first tsafe to avoid false maxLag error (#21490)
  internal/querynode/flow_graph_query_node.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#21561 Return error code when deny to read/write
  go.mod
  go.sum
  internal/core/src/pb/common.pb.cc
  internal/core/src/pb/common.pb.h
  internal/proto/proxy.proto
  internal/proto/proxypb/proxy.pb.go
  internal/proxy/error.go
  internal/proxy/error_test.go
  internal/proxy/impl.go
  internal/proxy/impl_test.go
  internal/proxy/multi_rate_limiter.go
  internal/proxy/multi_rate_limiter_test.go
  internal/proxy/rate_limit_interceptor.go
  internal/proxy/rate_limit_interceptor_test.go
  internal/rootcoord/quota_center.go
  internal/rootcoord/quota_center_test.go
  internal/types/types.go
Labels: area/dependency, size/XL, approved, lgtm, ci-passed, area/internal-api, dco-passed

#21477 Improve ListSegments performance for datacoord catalog
  internal/datacoord/channel_store_test.go
  internal/datacoord/compaction_test.go
  internal/datacoord/garbage_collector_test.go
  internal/datacoord/index_builder_test.go
  internal/datacoord/index_meta_test.go
  internal/datacoord/index_service_test.go
  internal/datacoord/meta.go
  internal/datacoord/meta_test.go
  internal/datacoord/mock_test.go
  internal/datacoord/segment_manager_test.go
  internal/datacoord/server.go
  internal/datacoord/server_test.go
  internal/metastore/catalog.go
  internal/metastore/kv/datacoord/kv_catalog.go
  internal/metastore/kv/datacoord/kv_catalog_test.go
  internal/metastore/mocks/DataCoordCatalog.go
Labels: size/XXL, approved, lgtm, ci-passed, dco-passed

#21507 enable auto balance paramter(#21504)
  internal/querycoordv2/checkers/balance_checker.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass, behavior-change

#21421 Support force sync in data sync service
  internal/datanode/buffer.go
  internal/datanode/channel_meta.go
  internal/datanode/data_sync_service.go
  internal/datanode/data_sync_service_test.go
  internal/datanode/flow_graph_dd_node.go
  internal/datanode/flow_graph_dd_node_test.go
  internal/datanode/flow_graph_delete_node.go
  internal/datanode/flow_graph_delete_node_test.go
  internal/datanode/flow_graph_insert_buffer_node.go
  internal/datanode/flow_graph_insert_buffer_node_test.go
  internal/datanode/flow_graph_message.go
  internal/datanode/flow_graph_time_tick_node.go
  internal/datanode/flush_manager.go
  internal/datanode/flush_task.go
  internal/datanode/mock_test.go
  internal/datanode/segment_sync_policy.go
  internal/querynode/flow_graph_delete_node.go
  internal/querynode/flow_graph_filter_delete_node.go
  internal/querynode/flow_graph_filter_dm_node.go
  internal/querynode/flow_graph_insert_node.go
  internal/querynode/flow_graph_message.go
  internal/querynode/flow_graph_service_time_node.go
  internal/util/flowgraph/flow_graph_test.go
  internal/util/flowgraph/input_node.go
  internal/util/flowgraph/message.go
  internal/util/flowgraph/node.go
Labels: size/XXL, approved, lgtm, ci-passed, dco-passed

#21555 Add Cgo Symbolizer and crash dump
  cmd/roles/roles.go
  go.mod
  go.sum
  internal/util/indexcgowrapper/codec_index_test.go
  internal/util/indexcgowrapper/index_test.go
  internal/util/symbolizer/symbolizer.go
Labels: area/dependency, size/M, approved, lgtm, ci-passed, dco-passed

#21565 [cherry-pick]: Fix some errors of querynode and query coord
  internal/mq/msgstream/mq_factory.go
  internal/querycoordv2/balance/rowcount_based_balancer.go
  internal/querycoordv2/balance/rowcount_based_balancer_test.go
  internal/querycoordv2/session/node_manager.go
  internal/querynode/impl.go
  internal/querynode/impl_test.go
  internal/querynode/query_node.go
  internal/util/concurrency/pool.go
  scripts/stop_graceful.sh
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#21546 Remove unnecessary dependency
  tests/python_client/requirements.txt
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#21553 [cherry-pick] Show trigger reason when deny to read/write
  go.mod
  go.sum
  internal/core/src/pb/common.pb.cc
  internal/core/src/pb/common.pb.h
  internal/core/src/pb/schema.pb.cc
  internal/distributed/proxy/service.go
  internal/metrics/rootcoord_metrics.go
  internal/proto/proxy.proto
  internal/proto/proxypb/proxy.pb.go
  internal/proxy/error.go
  internal/proxy/error_test.go
  internal/proxy/impl.go
  internal/proxy/impl_test.go
  internal/proxy/multi_rate_limiter.go
  internal/proxy/multi_rate_limiter_test.go
  internal/proxy/rate_limit_interceptor.go
  internal/proxy/rate_limit_interceptor_test.go
  internal/rootcoord/quota_center.go
  internal/rootcoord/quota_center_test.go
  internal/types/types.go
Labels: area/dependency, size/XL, approved, lgtm, ci-passed, area/internal-api, dco-passed

#21564 Add segment gc restraint of dml position before channel cp
  internal/datacoord/garbage_collector.go
  internal/datacoord/garbage_collector_test.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed, behavior-change

#21540 Streaming read numpy
  internal/util/importutil/import_util.go
  internal/util/importutil/import_util_test.go
  internal/util/importutil/import_wrapper.go
  internal/util/importutil/import_wrapper_test.go
  internal/util/importutil/json_parser.go
  internal/util/importutil/json_parser_test.go
  internal/util/importutil/numpy_adapter.go
  internal/util/importutil/numpy_adapter_test.go
  internal/util/importutil/numpy_parser.go
  internal/util/importutil/numpy_parser_test.go
Labels: size/XXL, approved, lgtm, ci-passed, dco-passed

#21575 [cherry-pick ]Return error code when deny to read/write
  go.mod
  go.sum
  internal/core/src/pb/common.pb.cc
  internal/core/src/pb/common.pb.h
  internal/proto/proxy.proto
  internal/proto/proxypb/proxy.pb.go
  internal/proxy/error.go
  internal/proxy/error_test.go
  internal/proxy/impl.go
  internal/proxy/impl_test.go
  internal/proxy/multi_rate_limiter.go
  internal/proxy/multi_rate_limiter_test.go
  internal/proxy/rate_limit_interceptor.go
  internal/proxy/rate_limit_interceptor_test.go
  internal/rootcoord/quota_center.go
  internal/rootcoord/quota_center_test.go
  internal/types/types.go
Labels: area/dependency, size/XL, approved, lgtm, ci-passed, area/internal-api, dco-passed

#21576 [cherry-pick]: Support sync all segments while close
  internal/datanode/buffer.go
  internal/datanode/channel_meta.go
  internal/datanode/data_sync_service.go
  internal/datanode/data_sync_service_test.go
  internal/datanode/flow_graph_dd_node.go
  internal/datanode/flow_graph_dd_node_test.go
  internal/datanode/flow_graph_delete_node.go
  internal/datanode/flow_graph_delete_node_test.go
  internal/datanode/flow_graph_insert_buffer_node.go
  internal/datanode/flow_graph_insert_buffer_node_test.go
  internal/datanode/flow_graph_message.go
  internal/datanode/flow_graph_time_tick_node.go
  internal/datanode/flush_manager.go
  internal/datanode/flush_task.go
  internal/datanode/mock_test.go
  internal/datanode/segment_sync_policy.go
  internal/querynode/flow_graph_delete_node.go
  internal/querynode/flow_graph_filter_delete_node.go
  internal/querynode/flow_graph_filter_dm_node.go
  internal/querynode/flow_graph_insert_node.go
  internal/querynode/flow_graph_message.go
  internal/querynode/flow_graph_service_time_node.go
  internal/util/flowgraph/flow_graph_test.go
  internal/util/flowgraph/input_node.go
  internal/util/flowgraph/message.go
  internal/util/flowgraph/node.go
Labels: size/XXL, approved, lgtm, ci-passed, dco-passed

#21580 [cherry-pick]: Improvement apis and error messages about the graceful stop
  configs/milvus.yaml
  internal/querycoordv2/dist/dist_handler.go
  internal/querycoordv2/services.go
  internal/querycoordv2/services_test.go
  internal/util/paramtable/component_param_test.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#21586 Upgrade numpy bool str type
  tests/python_client/common/common_func.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#21585 [Cherry-Pick]Add A WalkWithPrefix API for MetaKv interface
  docs/design_docs/milvus_meta_snapshot_en.md
  internal/core/src/query/deprecated/ValidationUtil.cpp
  internal/indexcoord/index_coord_mock.go
  internal/kv/etcd/embed_etcd_kv.go
  internal/kv/etcd/embed_etcd_kv_test.go
  internal/kv/etcd/etcd_kv.go
  internal/kv/etcd/etcd_kv_test.go
  internal/kv/kv.go
  internal/kv/mem/mem_kv.go
  internal/kv/mocks/MetaKv.go
  internal/kv/mocks/SnapShotKV.go
  internal/kv/mocks/TxnKV.go
  internal/rootcoord/proxy_manager.go
Labels: size/XXL, approved, lgtm, ci-passed, dco-passed

#21578 Remove index checking phase for bulk insert
  internal/datacoord/segment_manager.go
  internal/rootcoord/import_manager.go
  internal/rootcoord/import_manager_test.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#21583 Update segment id for import task
  internal/datanode/data_node.go
  internal/rootcoord/import_manager.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#21505 fix flaws found in the process of ideal benchmark(#21504)
  internal/querycoordv2/checkers/balance_checker.go
  internal/querynode/shard_cluster.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#21568 Fix mac ci conan cache not hit
  .github/workflows/mac.yaml
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#21597 Forbid IndexCoord start with version<2.3
  internal/datacoord/server.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#21579 [cherry-pick] Streaming read numpy
  internal/util/importutil/import_util.go
  internal/util/importutil/import_util_test.go
  internal/util/importutil/import_wrapper.go
  internal/util/importutil/import_wrapper_test.go
  internal/util/importutil/json_parser.go
  internal/util/importutil/json_parser_test.go
  internal/util/importutil/numpy_adapter.go
  internal/util/importutil/numpy_adapter_test.go
  internal/util/importutil/numpy_parser.go
  internal/util/importutil/numpy_parser_test.go
Labels: size/XXL, approved, lgtm, ci-passed, dco-passed

#21600 [Cherry-Pick]Improve ListSegments performance for datacoord catalog
  internal/datacoord/channel_store_test.go
  internal/datacoord/compaction_test.go
  internal/datacoord/meta.go
  internal/datacoord/meta_test.go
  internal/datacoord/mock_test.go
  internal/datacoord/segment_manager_test.go
  internal/datacoord/server.go
  internal/metastore/catalog.go
  internal/metastore/kv/datacoord/kv_catalog.go
  internal/metastore/kv/datacoord/kv_catalog_test.go
  internal/metastore/mocks/DataCoordCatalog.go
Labels: size/XXL, approved, lgtm, ci-passed, dco-passed

#21594 [Cherry-Pick]Remove redundant LoadPrefix requests for Catalog ListCollections
  internal/metastore/kv/rootcoord/kv_catalog.go
  internal/metastore/kv/rootcoord/kv_catalog_test.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#21601 [Cherry-Pick]Improve LoadWithPrefix performance for SuffixSnapshot
  internal/metastore/kv/rootcoord/suffix_snapshot.go
  internal/metastore/kv/rootcoord/suffix_snapshot_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#21552 Add QueryCoord OWNERS file
  internal/querycoordv2/OWNERS
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#21606 Use singleflight in localCache.load
  .golangci.yml
  internal/util/cache/local_cache.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#21608 Set GetIndexState is compatible with SDK version 2.1
  internal/indexcoord/index_coord.go
  internal/indexcoord/index_coord_test.go
  internal/proxy/task_index.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#21612 Report bulkinsert progress
  internal/datanode/data_node.go
  internal/rootcoord/import_manager.go
  internal/util/importutil/binlog_parser.go
  internal/util/importutil/binlog_parser_test.go
  internal/util/importutil/import_util.go
  internal/util/importutil/import_util_test.go
  internal/util/importutil/import_wrapper.go
  internal/util/importutil/import_wrapper_test.go
  internal/util/importutil/json_parser.go
  internal/util/importutil/json_parser_test.go
  internal/util/importutil/numpy_parser.go
  internal/util/importutil/numpy_parser_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#21616 [Cherry-Pick]Make the subName unique for the datanode tt channel
  internal/datacoord/server.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#21611 [cherry-pick] Add the superuser config
  configs/milvus.yaml
  internal/proxy/proxy_test.go
  internal/proxy/util.go
  internal/util/paramtable/component_param.go
  internal/util/paramtable/component_param_test.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#21574 Return insufficient memory error when load failed
  internal/proxy/error.go
  internal/proxy/error_test.go
  internal/proxy/impl.go
  internal/proxy/proxy_test.go
  internal/proxy/util.go
  internal/querycoordv2/job/job.go
  internal/querycoordv2/job/job_test.go
  internal/querycoordv2/meta/failed_load_cache.go
  internal/querycoordv2/meta/failed_load_cache_test.go
  internal/querycoordv2/server.go
  internal/querycoordv2/services.go
  internal/querycoordv2/services_test.go
  internal/querycoordv2/task/executor.go
  internal/querycoordv2/task/scheduler.go
  internal/querycoordv2/task/task_test.go
  internal/querynode/errors.go
  internal/querynode/impl.go
  internal/querynode/impl_utils.go
  internal/querynode/impl_utils_test.go
  internal/querynode/segment_loader.go
  internal/querynode/shard_cluster.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#21383 Skip search GRPC call for standalon
  internal/proxy/task_search.go
  internal/querynode/impl.go
  internal/querynode/query_node.go
  internal/querynode/shard_cluster.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#21592 [cherry-pick] Return insufficient memory error when load failed
  internal/proxy/error.go
  internal/proxy/error_test.go
  internal/proxy/impl.go
  internal/proxy/proxy_test.go
  internal/proxy/util.go
  internal/querycoordv2/job/job.go
  internal/querycoordv2/job/job_test.go
  internal/querycoordv2/meta/failed_load_cache.go
  internal/querycoordv2/meta/failed_load_cache_test.go
  internal/querycoordv2/server.go
  internal/querycoordv2/services.go
  internal/querycoordv2/services_test.go
  internal/querycoordv2/task/executor.go
  internal/querycoordv2/task/scheduler.go
  internal/querycoordv2/task/task_test.go
  internal/querynode/errors.go
  internal/querynode/impl.go
  internal/querynode/impl_utils.go
  internal/querynode/impl_utils_test.go
  internal/querynode/segment_loader.go
  internal/querynode/shard_cluster.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#21472 Forbid deleting entities by non-pk field (#21459)
  internal/proxy/task_delete.go
  internal/proxy/task_delete_test.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#21590 Add test wrapper describe and its cases
  tests/python_client/base/collection_wrapper.py
  tests/python_client/testcases/test_collection.py
Labels: kind/improvement, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#21627 Use milvus-proto 2.2
  go.mod
  go.sum
  internal/core/src/pb/common.pb.cc
  internal/core/src/pb/common.pb.h
  internal/core/src/pb/schema.pb.cc
  internal/distributed/proxy/service.go
  internal/proxy/impl.go
Labels: area/dependency, kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#21629 Optimize GetLoadingProgress to save RPC (#21493)
  internal/proxy/impl.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#21621 [cherry-pick] Update segment id for import task
  internal/datanode/services.go
  internal/rootcoord/import_manager.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#21620 Reset indexpb for upgrade
  internal/datacoord/index_meta.go
  internal/datacoord/index_meta_test.go
  internal/datacoord/index_service.go
  internal/datacoord/index_service_test.go
  internal/distributed/datacoord/client/client.go
  internal/distributed/datacoord/service.go
  internal/distributed/datacoord/service_test.go
  internal/distributed/proxy/service_test.go
  internal/metastore/kv/datacoord/kv_catalog.go
  internal/metastore/kv/datacoord/kv_catalog_test.go
  internal/metastore/model/index.go
  internal/metastore/model/index_test.go
  internal/metastore/model/segment_index.go
  internal/metastore/model/segment_index_test.go
  internal/mocks/mock_datacoord.go
  internal/mocks/mock_indexcoord.go
  internal/proto/data_coord.proto
  internal/proto/datapb/data_coord.pb.go
  internal/proto/index_coord.proto
  internal/proto/index_node.proto
  internal/proto/indexpb/index_coord.pb.go
  internal/proto/indexpb/index_node.pb.go
  internal/proxy/data_coord_mock_test.go
  internal/proxy/task.go
  internal/proxy/task_index.go
  internal/proxy/task_index_test.go
  internal/proxy/task_test.go
  internal/querycoordv2/meta/coordinator_broker.go
  internal/rootcoord/broker.go
  internal/rootcoord/broker_test.go
  internal/rootcoord/import_helper.go
  internal/rootcoord/mock_test.go
  internal/types/types.go
  internal/util/mock/datacoord_client.go
  internal/util/mock/grpc_datacoord_client.go
  scripts/proto_gen_go.sh
Labels: size/XXL, approved, lgtm, ci-passed, area/internal-api, dco-passed

#21638 [cherry-pick] Report bulkinsert progress
  internal/datanode/services.go
  internal/rootcoord/import_manager.go
  internal/util/importutil/binlog_parser.go
  internal/util/importutil/binlog_parser_test.go
  internal/util/importutil/import_util.go
  internal/util/importutil/import_util_test.go
  internal/util/importutil/import_wrapper.go
  internal/util/importutil/import_wrapper_test.go
  internal/util/importutil/json_parser.go
  internal/util/importutil/json_parser_test.go
  internal/util/importutil/numpy_parser.go
  internal/util/importutil/numpy_parser_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#21604 [Cherry-Pick] BulkInsert now completes when segments are flushed, without checking indexes
  internal/datacoord/segment_manager.go
  internal/rootcoord/broker.go
  internal/rootcoord/import_helper.go
  internal/rootcoord/import_manager.go
  internal/rootcoord/import_manager_test.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
Labels: kind/improvement, size/XL, approved, lgtm, ci-passed, dco-passed, manual-pass

#21642 Update numpy bool type
  tests/python_client/common/common_func.py
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#21584 [skip e2e] Fix load meta migration
  Makefile
  cmd/tools/migration/meta/210_to_220.go
  internal/util/sessionutil/session_util.go
Labels: kind/bug, kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed, area/compilation

#21628 Fix collection not exist when tried to do recovery (#21471)
  Makefile
  internal/common/error.go
  internal/common/error_test.go
  internal/datacoord/compaction_trigger.go
  internal/datacoord/mock_test.go
  internal/datacoord/server.go
  internal/datacoord/server_test.go
  internal/datacoord/services.go
  internal/datanode/meta_service.go
  internal/datanode/meta_service_test.go
  internal/datanode/mock_test.go
  internal/distributed/proxy/service_test.go
  internal/distributed/rootcoord/client/client.go
  internal/distributed/rootcoord/service.go
  internal/mocks/mock_rootcoord.go
  internal/proto/root_coord.proto
  internal/proto/rootcoordpb/root_coord.pb.go
  internal/proxy/rootcoord_mock_test.go
  internal/querycoordv2/meta/coordinator_broker.go
  internal/querycoordv2/meta/coordinator_broker_test.go
  internal/rootcoord/broker.go
  internal/rootcoord/broker_test.go
  internal/rootcoord/describe_collection_task.go
  internal/rootcoord/describe_collection_task_test.go
  internal/rootcoord/import_helper.go
  internal/rootcoord/meta_table.go
  internal/rootcoord/meta_table_test.go
  internal/rootcoord/mock_test.go
  internal/rootcoord/mocks/IMetaTable.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
  internal/rootcoord/show_partition_task.go
  internal/rootcoord/show_partition_task_test.go
  internal/types/types.go
  internal/util/mock/grpc_rootcoord_client.go
Labels: kind/bug, size/XL, approved, lgtm, ci-passed, dco-passed, area/compilation

#21651 Make rootcoord client compatible with older version
  internal/distributed/rootcoord/client/client.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed

#21637 Fix lag behind error with 0 servicetime
  internal/querynode/task_read.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#21656 Update PublishMigrationImage.groovy
  ci/jenkins/PublishMigrationImage.groovy
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#21641 Register after start to prevent there are tow coordinator at the same time
  Makefile
  internal/datacoord/server.go
  internal/distributed/datacoord/service.go
  internal/distributed/indexcoord/service.go
  internal/distributed/querycoord/service.go
  internal/distributed/rootcoord/service.go
  internal/indexcoord/index_coord.go
  internal/indexcoord/index_coord_test.go
  internal/indexcoord/task_scheduler.go
  internal/mocks/mock_datacoord.go
  internal/querycoordv2/server.go
  internal/querycoordv2/server_test.go
  internal/rootcoord/root_coord.go
Labels: kind/improvement, size/XL, approved, lgtm, ci-passed, dco-passed, area/compilation

#21645 Make the rbac error message clearer
  internal/rootcoord/meta_table.go
  internal/rootcoord/root_coord.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed

#21646 Make the rbac error message clearer
  configs/milvus.yaml
  internal/rootcoord/meta_table.go
  internal/rootcoord/root_coord.go
  internal/util/paramtable/component_param.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed

#21674 [skip e2e] Update PublishMigrationImage.groovy
  ci/jenkins/PublishMigrationImage.groovy
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#21675 [skip e2e] Update docker-compoer.yaml to open minio 9000 port
  deployments/docker/standalone/docker-compose.yml
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#21659 Remove factory in querycoord
  internal/distributed/querycoord/service.go
  internal/querycoordv2/server.go
  internal/querycoordv2/server_test.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed

#21509 Use opentelemetry
  cmd/components/root_coord.go
  cmd/roles/roles.go
  configs/milvus.yaml
  go.mod
  go.sum
  internal/datacoord/segment_manager.go
  internal/datacoord/services.go
  internal/datanode/flow_graph_dd_node.go
  internal/datanode/flow_graph_delete_node.go
  internal/datanode/flow_graph_insert_buffer_node.go
  internal/datanode/util.go
  internal/distributed/connection_manager.go
  internal/distributed/datacoord/service.go
  internal/distributed/datanode/service.go
  internal/distributed/indexnode/service.go
  internal/distributed/proxy/service.go
  internal/distributed/querycoord/service.go
  internal/distributed/querynode/service.go
  internal/distributed/rootcoord/service.go
  internal/indexnode/indexnode.go
  internal/indexnode/indexnode_service.go
  internal/log/meta_logger.go
  internal/log/meta_logger_test.go
  internal/log/meta_ops.go
  internal/mq/msgstream/mq_msgstream.go
  internal/mq/msgstream/trace.go
  internal/proxy/accesslog/access_log_test.go
  internal/proxy/accesslog/util.go
  internal/proxy/accesslog/util_test.go
  internal/proxy/impl.go
  internal/proxy/proxy_test.go
  internal/proxy/task_delete.go
  internal/proxy/task_insert.go
  internal/proxy/task_scheduler.go
  internal/proxy/task_search.go
  internal/proxy/task_statistic.go
  internal/proxy/task_upsert.go
  internal/querycoordv2/balance/rowcount_based_balancer.go
  internal/querynode/flow_graph_delete_node.go
  internal/querynode/flow_graph_filter_delete_node.go
  internal/querynode/flow_graph_filter_dm_node.go
  internal/querynode/flow_graph_insert_node.go
  internal/querynode/impl.go
  internal/querynode/mock_test.go
  internal/querynode/search.go
  internal/querynode/segment.go
  internal/tracer/interceptor_suite.go
  internal/tracer/stack_trace.go
  internal/tracer/stack_trace_test.go
  internal/tracer/tracer.go
  internal/util/flowgraph/input_node.go
  internal/util/grpcclient/client.go
  internal/util/logutil/grpc_interceptor.go
  internal/util/mock/grpcclient.go
  internal/util/paramtable/component_param.go
  internal/util/timerecord/time_recorder.go
  internal/util/trace/util.go
  internal/util/trace/util_test.go
  scripts/run_go_unittest.sh
Labels: area/dependency, size/XXL, approved, lgtm, ci-passed, dco-passed, manual-pass

#21676 add resource group interface
  go.mod
  go.sum
  internal/core/src/pb/common.pb.cc
  internal/core/src/pb/common.pb.h
  internal/distributed/proxy/service.go
  internal/distributed/proxy/service_test.go
  internal/proxy/impl.go
Labels: area/dependency, size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#21654 [skip e2e]Update export log script
  .github/ISSUE_TEMPLATE/bug_report.yaml
  deployments/export-log/README.md
  deployments/export-log/export-milvus-log.sh
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#21686 [skip e2e]Update meta-migratition build
  build/docker/meta-migration/Dockerfile
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#21664 Prevent panicking when index segment info not exists
  internal/datacoord/index_meta_test.go
  internal/datacoord/segment_info.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#21694 Fix mock bug
  internal/querycoordv2/server_test.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#21689 Support zstd compression in grpc
  configs/milvus.yaml
  internal/distributed/datacoord/client/client.go
  internal/distributed/datanode/client/client.go
  internal/distributed/indexnode/client/client.go
  internal/distributed/proxy/client/client.go
  internal/distributed/querycoord/client/client.go
  internal/distributed/querynode/client/client.go
  internal/distributed/rootcoord/client/client.go
  internal/util/grpcclient/client.go
  internal/util/grpcclient/client_test.go
  internal/util/grpcclient/grpc_encoder.go
  internal/util/grpcclient/grpc_encoder_test.go
  internal/util/paramtable/grpc_param.go
  internal/util/paramtable/grpc_param_test.go
Labels: kind/feature, size/L, approved, lgtm, ci-passed, dco-passed, behavior-change

#21688 Fix reading config from etcd may block forever
  internal/config/etcd_source.go
Labels: kind/bug, area/dependency, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, area/internal-api, dco-passed, area/compilation

#21683 [Cherry Pick]Optimize some low efficient code
  internal/core/src/segcore/Reduce.cpp
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#21679 Upgrade protobuf to 3.21.9
  internal/core/CMakeLists.txt
  internal/core/conanfile.py
  internal/core/src/pb/CMakeLists.txt
  internal/core/src/pb/common.pb.cc
  internal/core/src/pb/common.pb.h
  internal/core/src/pb/index_cgo_msg.pb.cc
  internal/core/src/pb/index_cgo_msg.pb.h
  internal/core/src/pb/plan.pb.cc
  internal/core/src/pb/plan.pb.h
  internal/core/src/pb/schema.pb.cc
  internal/core/src/pb/schema.pb.h
  internal/core/src/pb/segcore.pb.cc
  internal/core/src/pb/segcore.pb.h
Labels: kind/improvement, size/XXL, approved, lgtm, ci-passed, dco-passed, area/compilation

#21703 Add MLogger.WithRateGroup for logger
  internal/log/log.go
  internal/log/mlogger.go
  internal/querycoordv2/dist/dist_handler.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#21669 Replace session.ServerID with config.NodeID
  internal/datacoord/services.go
  internal/datanode/data_node.go
  internal/indexcoord/index_coord.go
  internal/indexnode/indexnode_service.go
  internal/proxy/impl.go
  internal/querycoordv2/services.go
  internal/querynode/impl.go
  internal/rootcoord/root_coord.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#21682 [Cherry Pick]Use all() api for bitset check
  internal/core/src/query/visitors/ExecPlanNodeVisitor.cpp
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#21706 Fix data race
  internal/proxy/task_upsert.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#21653 Fix not show some configs in birdwatcher
  internal/config/manager.go
  internal/core/conanfile.py
  internal/datacoord/services.go
  internal/datanode/services.go
  internal/indexnode/indexnode.go
  internal/proxy/proxy.go
  internal/querycoordv2/services.go
  internal/querynode/impl.go
  internal/rootcoord/root_coord.go
  internal/util/paramtable/base_table.go
  internal/util/paramtable/base_table_test.go
  internal/util/paramtable/component_param.go
  internal/util/paramtable/service_param.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#21672 [skip e2e] Fix load meta migration (#21584)
  Makefile
  cmd/tools/migration/meta/210_to_220.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed, area/compilation

#21670 Make rootcoord client compatible with older version (#21651)
  internal/distributed/rootcoord/client/client.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#21700 Fix RootCoord standby bug
  internal/rootcoord/root_coord.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#21680 [cherry-pick] Fix bulkinsert progress bug
  internal/util/importutil/numpy_parser.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#21697 Add warning comments
  internal/querycoordv2/job/job.go
  internal/querycoordv2/meta/target_manager.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#21709 Update default image tag for meta migration
  deployments/migrate-meta/README.md
  deployments/migrate-meta/migrate.sh
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#21698 Fix may update the current target to an unavailable target when node down
  internal/querycoordv2/observers/target_observer.go
  internal/querycoordv2/observers/target_observer_test.go
  internal/querycoordv2/server.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#21668 Fix bulkinsert progress bug
  internal/util/importutil/numpy_parser.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#21677 Skip unresolved cases and reslove warnings
  tests/python_client/testcases/test_collection.py
  tests/python_client/testcases/test_insert.py
  tests/python_client/testcases/test_partition.py
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#21712 Fix ready notifiers leak when collection released
  internal/querycoordv2/job/job.go
  internal/querycoordv2/job/job_test.go
  internal/querycoordv2/observers/target_observer.go
  internal/querycoordv2/services.go
  internal/querycoordv2/services_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#21714 generate-mockery for querycoordv2, querynode and rootcoort
  Makefile
  internal/querycoordv2/balance/mock_balancer.go
  internal/querycoordv2/meta/mock_broker.go
  internal/querycoordv2/meta/mock_store.go
  internal/querycoordv2/mocks/mock_querynode.go
  internal/querycoordv2/session/mock_cluster.go
  internal/querycoordv2/task/mock_scheduler.go
  internal/querynode/mock_tsafe_replica_test.go
  internal/rootcoord/mocks/GarbageCollector.go
  internal/rootcoord/mocks/IMetaTable.go
  internal/rootcoord/mocks/garbage_collector.go
  internal/rootcoord/mocks/meta_table.go
  internal/tso/mocks/allocator.go
Labels: kind/improvement, size/XXL, approved, lgtm, ci-passed, dco-passed, area/compilation

#21735 Upgrade knowhere to 1.3.7
  internal/core/thirdparty/knowhere/CMakeLists.txt
Labels: size/XS, approved, lgtm, ci-passed, dco-passed, area/compilation

#21722 Optimize performance of reducing segments
  internal/core/src/segcore/Reduce.cpp
  internal/core/src/segcore/Reduce.h
  internal/core/src/segcore/ReduceStructure.h
  internal/core/src/segcore/reduce_c.cpp
  internal/core/unittest/test_c_api.cpp
  internal/core/unittest/test_reduce_c.cpp
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#21724 Check ScalarIndex deserialization
  internal/core/src/index/ScalarIndex-inl.h
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#21741 Fix search result check of binary superstructure
  tests/python_client/testcases/test_collection.py
  tests/python_client/testcases/test_partition.py
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#21743 [Cherry-Pick] Fix may update the current target to an unavailable target when node down
  internal/querycoordv2/job/job.go
  internal/querycoordv2/job/job_test.go
  internal/querycoordv2/observers/target_observer.go
  internal/querycoordv2/observers/target_observer_test.go
  internal/querycoordv2/server.go
  internal/querycoordv2/services.go
  internal/querycoordv2/services_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#21737 Fix check time tick lag with no channel
  internal/rootcoord/quota_center.go
  internal/rootcoord/quota_center_test.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#21750 [skip e2e]Fix cpp lint errors
  internal/core/src/segcore/Reduce.h
  internal/core/src/segcore/ReduceStructure.h
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#21742 Fix current target may be updated to an invalid target
  internal/querycoordv2/observers/collection_observer.go
  internal/querycoordv2/observers/collection_observer_test.go
  internal/querycoordv2/observers/target_observer.go
  internal/querycoordv2/server.go
  internal/querycoordv2/server_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#21747 Fix active-standby switch fail bug
  internal/util/sessionutil/session_util.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#21755 Fix active-standby switch fail bug
  internal/util/sessionutil/session_util.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#21739 downgrade curl for compiled on aarch64 platform
  internal/core/conanfile.py
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#21759 Fix load timeout after next target updates
  internal/querycoordv2/meta/collection_manager.go
  internal/querycoordv2/meta/target.go
  internal/querycoordv2/meta/target_manager.go
  internal/querycoordv2/observers/collection_observer.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#21762 [Cherry-Pick] Fix current target may be updated to an invalid target (#21742)
  internal/querycoordv2/observers/collection_observer.go
  internal/querycoordv2/observers/collection_observer_test.go
  internal/querycoordv2/observers/target_observer.go
  internal/querycoordv2/server.go
  internal/querycoordv2/server_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#21768 Fix check time tick lag with no channel (#21737)
  internal/rootcoord/quota_center.go
  internal/rootcoord/quota_center_test.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#21758 Fix bulkinsert report bug
  internal/rootcoord/import_manager.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#21752 Combine similar function
  internal/proxy/task_insert.go
  internal/proxy/task_upsert.go
  internal/proxy/task_upsert_test.go
  internal/proxy/util.go
  internal/proxy/util_test.go
Labels: kind/improvement, size/XL, approved, lgtm, ci-passed, dco-passed

#21764 timestamp decided if the pks were the same (#20166)
  internal/core/src/query/PlanImpl.h
  internal/core/src/segcore/SegmentGrowingImpl.cpp
  internal/core/src/segcore/SegmentInterface.cpp
  internal/core/src/segcore/SegmentInterface.h
  internal/core/src/segcore/SegmentSealedImpl.cpp
  internal/core/unittest/test_retrieve.cpp
  internal/core/unittest/test_timestamp_index.cpp
  internal/proxy/task_query.go
  internal/proxy/task_query_test.go
  internal/proxy/task_search.go
  internal/querynode/result.go
  internal/querynode/result_test.go
  internal/util/typeutil/schema.go
  internal/util/typeutil/schema_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#21772 Fix data race caused by no clone while updating index
  internal/datacoord/segment_info.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#21773 [Cherry-Pick] Add segment gc restraint of dml position before channel cp
  internal/datacoord/garbage_collector.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed, manual-pass, behavior-change

#21770 Fix load timeout after next target updates (#21759)
  internal/querycoordv2/meta/collection_manager.go
  internal/querycoordv2/meta/target.go
  internal/querycoordv2/meta/target_manager.go
  internal/querycoordv2/observers/collection_observer.go
  internal/querycoordv2/observers/collection_observer_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#21751 Fix offset panic (#21292)
  internal/proxy/task_query.go
  internal/proxy/task_query_test.go
  internal/util/typeutil/gen_empty_field_data.go
  internal/util/typeutil/result_helper.go
  internal/util/typeutil/result_helper_test.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed

#21778 [cherry-pick] Fix bulkinsert report bug
  internal/rootcoord/import_manager.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#21734 Add slow gc warning log
  internal/util/gc/gc_tuner.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed

#21733 Add GC slow log
  internal/util/gc/gc_tuner.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#21775 Disable time-travel by default
  configs/milvus.yaml
  internal/util/paramtable/component_param.go
  internal/util/paramtable/component_param_test.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#21788 Disable time-travel by default
  configs/milvus.yaml
  internal/util/paramtable/component_param.go
  internal/util/paramtable/component_param_test.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#21776 Add refresh option for LoadCollection/LoadPartitions interfaces
  internal/proto/query_coord.proto
  internal/proto/querypb/query_coord.pb.go
  internal/querycoordv2/meta/leader_view_manager.go
  internal/querycoordv2/observers/collection_observer.go
  internal/querycoordv2/observers/target_observer.go
  internal/querycoordv2/services.go
  internal/querycoordv2/services_test.go
  internal/querycoordv2/utils/meta.go
  internal/querycoordv2/utils/test.go
Labels: kind/improvement, size/XL, approved, lgtm, ci-passed, area/internal-api, dco-passed, manual-pass

#21769 Change CreateAt to UpdatedAt when checking timeout
  internal/querycoordv2/observers/collection_observer.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#21766 Update chart version and add concerned cases
  ci/jenkins/Nightly.groovy
  ci/jenkins/PR.groovy
  tests/python_client/testcases/test_index.py
  tests/python_client/testcases/test_insert.py
Labels: kind/improvement, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#21513 Add unsubscribe dmchannel task
  internal/querynode/impl.go
  internal/querynode/impl_test.go
  internal/querynode/query_shard_service.go
  internal/querynode/task.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#21789 [test]Refine recall test
  tests/python_client/deploy/scripts/first_recall_test.py
  tests/python_client/deploy/scripts/second_recall_test.py
  tests/python_client/requirements.txt
Labels: kind/improvement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#21793 Update pymilvus version
  tests/python_client/requirements.txt
  tests/python_client/testcases/test_index.py
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#21809 Use AdressSantizer build when cpp files is changed
  .github/workflows/main.yaml
  Makefile
  scripts/core_build.sh
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed, area/compilation

#21693 Support rename collection
  go.mod
  go.sum
  internal/core/src/pb/common.pb.cc
  internal/core/src/pb/common.pb.h
  internal/datacoord/mock_test.go
  internal/distributed/proxy/service.go
  internal/distributed/proxy/service_test.go
  internal/distributed/rootcoord/client/client.go
  internal/distributed/rootcoord/service.go
  internal/distributed/rootcoord/service_test.go
  internal/mocks/mock_rootcoord.go
  internal/proto/root_coord.proto
  internal/proto/rootcoordpb/root_coord.pb.go
  internal/proxy/impl.go
  internal/proxy/impl_test.go
  internal/proxy/proxy_test.go
  internal/proxy/rootcoord_mock_test.go
  internal/rootcoord/drop_collection_task_test.go
  internal/rootcoord/meta_table.go
  internal/rootcoord/meta_table_test.go
  internal/rootcoord/mock_test.go
  internal/rootcoord/mocks/meta_table.go
  internal/rootcoord/rename_collection_task.go
  internal/rootcoord/rename_collection_task_test.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
  internal/types/types.go
  internal/util/mock/grpc_rootcoord_client.go
Labels: kind/feature, area/dependency, size/XXL, approved, lgtm, ci-passed, dco-passed, behavior-change

#21812 Update pymilvus version and charts version
  ci/jenkins/Nightly.groovy
  ci/jenkins/PR.groovy
  tests/python_client/requirements.txt
  tests/python_client/testcases/test_index.py
  tests/python_client/testcases/test_insert.py
Labels: sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#21782 Make base table init only once
  internal/datacoord/index_builder_test.go
  internal/datacoord/server_test.go
  internal/datanode/io_pool_test.go
  internal/distributed/datacoord/client/client_test.go
  internal/distributed/datanode/client/client_test.go
  internal/distributed/indexnode/service_test.go
  internal/distributed/proxy/client/client_test.go
  internal/distributed/querycoord/client/client_test.go
  internal/distributed/rootcoord/client/client_test.go
  internal/indexnode/indexnode_service_test.go
  internal/kv/etcd/embed_etcd_config_test.go
  internal/kv/etcd/embed_etcd_kv_test.go
  internal/kv/etcd/embed_etcd_restart_test.go
  internal/mq/mqimpl/rocksmq/server/rocksmq_impl_test.go
  internal/mq/mqimpl/rocksmq/server/rocksmq_retention_test.go
  internal/mq/msgstream/mqwrapper/kafka/kafka_client_test.go
  internal/mq/msgstream/mqwrapper/pulsar/pulsar_client_test.go
  internal/proxy/proxy_rpc_test.go
  internal/proxy/proxy_test.go
  internal/rootcoord/drop_partition_task_test.go
  internal/rootcoord/meta_table_test.go
  internal/rootcoord/mock_test.go
  internal/rootcoord/root_coord_test.go
  internal/rootcoord/scheduler_test.go
  internal/rootcoord/timestamp_bench_test.go
  internal/storage/minio_chunk_manager_test.go
  internal/storage/vector_chunk_manager_test.go
  internal/util/indexcgowrapper/codec_index_test.go
  internal/util/indexcgowrapper/index_test.go
  internal/util/paramtable/base_table.go
  internal/util/paramtable/base_table_test.go
  internal/util/paramtable/component_param.go
  internal/util/paramtable/grpc_param_test.go
  internal/util/paramtable/hook_config.go
  internal/util/paramtable/http_param_test.go
  internal/util/paramtable/runtime.go
  internal/util/paramtable/service_param.go
  internal/util/paramtable/service_param_test.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#21815 Allow empty AK/SK for minio cfg
  internal/util/paramtable/service_param.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed
