Repository milvus-io/milvus, pull requests merged in 2023-10, with the labels that each got.

#27360 Optimize the codec code of session
  internal/datacoord/index_engine_version_manager_test.go
  internal/datacoord/index_service_test.go
  internal/datacoord/server_test.go
  internal/datanode/data_node_test.go
  internal/datanode/mock_test.go
  internal/datanode/services_test.go
  internal/distributed/connection_manager_test.go
  internal/proxy/impl_test.go
  internal/proxy/metrics_info_test.go
  internal/rootcoord/mock_test.go
  internal/rootcoord/proxy_client_manager_test.go
  internal/rootcoord/proxy_manager_test.go
  internal/rootcoord/root_coord_test.go
  internal/rootcoord/timeticksync_test.go
  internal/util/sessionutil/session_util.go
  internal/util/sessionutil/session_util_test.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#27119 Print the server id when active-standby switch
  internal/util/sessionutil/session_util.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#27424 Add var-name sub linter in revive
  .golangci.yml
  internal/datacoord/server_test.go
  internal/kv/tikv/main_test.go
  internal/kv/tikv/txn_tikv.go
  internal/kv/tikv/txn_tikv_test.go
  internal/querycoordv2/checkers/controller.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#27426 Block creating new error from status reason
  .golangci.yml
  internal/datacoord/index_builder.go
  internal/datacoord/index_service_test.go
  internal/datanode/data_sync_service.go
  internal/datanode/flow_graph_time_tick_node.go
  internal/datanode/flush_manager.go
  internal/datanode/flush_manager_test.go
  internal/datanode/mock_test.go
  internal/datanode/services.go
  internal/datanode/timetick_sender.go
  internal/distributed/proxy/httpserver/handler_v1.go
  internal/distributed/proxy/httpserver/handler_v1_test.go
  internal/distributed/proxy/httpserver/utils.go
  internal/distributed/proxy/service.go
  internal/proto/planpb/plan.pb.go
  internal/proto/proxypb/proxy.pb.go
  internal/proto/rootcoordpb/root_coord.pb.go
  internal/proxy/channels_mgr.go
  internal/proxy/task.go
  internal/proxy/task_index.go
  internal/proxy/util.go
  internal/querycoordv2/meta/coordinator_broker.go
  internal/rootcoord/broker.go
  internal/rootcoord/proxy_client_manager.go
  internal/util/componentutil/componentutil.go
  pkg/util/funcutil/verify_response.go
  pkg/util/merr/utils.go
  tests/python_client/README.md
  tests/python_client/testcases/test_collection.py
  tests/python_client/testcases/test_partition.py
  tests/python_client/testcases/test_utility.py
Labels: kind/improvement, sig/testing, size/XL, approved, lgtm, area/test, ci-passed, area/internal-api, dco-passed, manual-pass

#27501 [skip e2e] Fix var-naming caused by old PRs
  internal/datanode/data_sync_service.go
  internal/datanode/flow_graph_time_tick_node.go
  pkg/util/merr/utils.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#27500 Improve bulk insert test in timeout
  tests/python_client/testcases/test_bulk_insert.py
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed, manual-pass

#27497 Fix some unstable complex delete test
  tests/python_client/testcases/test_delete.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed, manual-pass

#27495 Add revive sub-lints and fix existing problems
  .golangci.yml
  internal/datacoord/index_meta_test.go
  internal/datacoord/index_service_test.go
  internal/datanode/binlog_io.go
  internal/kv/tikv/txn_tikv.go
  internal/kv/tikv/txn_tikv_test.go
  internal/parser/planparserv2/plan_parser_v2.go
  internal/proxy/impl_test.go
  internal/proxy/plan_parser.go
  internal/querycoordv2/meta/collection_manager.go
  internal/querycoordv2/meta/replica_manager.go
  internal/querycoordv2/meta/resource_manager.go
  pkg/mq/msgstream/mqwrapper/kafka/kafka_consumer.go
  pkg/util/indexparamcheck/float_vector_base_checker.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#27502 Add `SegmentLevel` field for L0 delta
  internal/proto/data_coord.proto
  internal/proto/datapb/data_coord.pb.go
Labels: kind/improvement, size/XL, approved, lgtm, ci-passed, dco-passed

#27508 fix knowhere version-changing
  .github/workflows/update-knowhere-commit.yaml
  internal/core/thirdparty/knowhere/CMakeLists.txt
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed, area/compilation

#27503 Remove the log for GetFlushableSegments in the datacoord
  internal/datacoord/segment_manager.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#27475 Change grpc limit to larger value by default
  configs/milvus.yaml
  internal/util/paramtable/grpc_param.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed, manual-pass, do-not-merge/missing-related-pr

#26712 Fix miss to handle error from GetCollectionID
  internal/proxy/impl.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#27484 Reduce rpc size for GetRecoveryInfoV2
  internal/datacoord/services.go
  internal/datacoord/services_test.go
  internal/indexcoord/index_coord.go
  internal/metastore/kv/datacoord/kv_catalog.go
  internal/metastore/kv/datacoord/kv_catalog_test.go
  internal/querycoordv2/meta/coordinator_broker.go
Labels: size/L, approved, lgtm, dco-passed

#27514 Remove not used plan parser
  go.mod
  internal/proxy/plan_parser.go
  internal/proxy/plan_parser_test.go
  internal/proxy/task_index_test.go
  internal/querycoordv2/balance/mock_balancer.go
  internal/querycoordv2/dist/mock_controller.go
  internal/querycoordv2/meta/mock_broker.go
  internal/querycoordv2/mocks/mock_querynode.go
  internal/querycoordv2/session/mock_cluster.go
  internal/querycoordv2/task/mock_scheduler.go
Labels: area/dependency, kind/improvement, size/XXL, approved, lgtm, ci-passed, dco-passed, manual-pass

#27437 [test]Fix timeout in create index
  ci/jenkins/PR.groovy
  tests/python_client/base/collection_wrapper.py
  tests/python_client/testcases/test_bulk_insert.py
Labels: kind/improvement, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed, manual-pass

#27504 Set timeout for leader observer syncing
  internal/querycoordv2/observers/leader_observer.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#27399 update openssl to 3.1.2
  Makefile
  internal/core/conanfile.py
  internal/core/src/storage/AzureChunkManager.cpp
  internal/core/src/storage/ChunkManagers.cpp
  internal/core/src/storage/MinioChunkManager.cpp
  internal/core/src/storage/azure-blob-storage/AzureBlobChunkManager.cpp
  pkg/util/paramtable/service_param.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed, area/compilation

#27507 Add host & enable_disk to session
  internal/indexnode/indexnode.go
  internal/util/sessionutil/session_util.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#27389 Improve the error message for getting all indexes of collection
  internal/datacoord/index_service.go
  internal/proxy/default_limit_reducer.go
  internal/proxy/task.go
  internal/proxy/task_index.go
  pkg/util/merr/errors_test.go
  pkg/util/merr/utils.go
  pkg/util/typeutil/gen_empty_field_data.go
  pkg/util/typeutil/schema.go
Labels: kind/improvement, sig/testing, size/XXL, approved, lgtm, area/test, ci-passed, dco-passed

#27308 Add Channel Manager in DataNode
  internal/datanode/channel_manager.go
  internal/datanode/channel_manager_test.go
  internal/datanode/data_node.go
  internal/datanode/data_sync_service.go
  internal/datanode/data_sync_service_test.go
  internal/datanode/flow_graph_insert_buffer_node.go
  internal/datanode/flow_graph_manager.go
  pkg/util/paramtable/component_param.go
Labels: size/XL, approved, lgtm, ci-passed, dco-passed

#27539 Fix bug for concurrent parsing expr with strings(#26721)
  internal/parser/planparserv2/parser_visitor.go
  internal/parser/planparserv2/plan_parser_v2_test.go
  internal/parser/planparserv2/utils.go
  internal/parser/planparserv2/utils_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#27499 Refine Proxy errors
  internal/proxy/impl.go
  internal/proxy/impl_test.go
  internal/proxy/proxy.go
  internal/proxy/proxy_rpc_test.go
  internal/proxy/proxy_test.go
  internal/proxy/task_database.go
  internal/proxy/task_search.go
  internal/proxy/util.go
  pkg/util/merr/errors.go
  pkg/util/merr/utils.go
Labels: kind/improvement, size/XL, approved, lgtm, ci-passed, dco-passed

#27531 Add ctx control for observer manual check methods
  internal/querycoordv2/observers/collection_observer.go
  internal/querycoordv2/observers/leader_observer.go
  internal/querycoordv2/observers/leader_observer_test.go
  internal/querycoordv2/observers/target_observer.go
  internal/querycoordv2/observers/target_observer_test.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#27551 Skip a test for issue 27462 to unblock ci
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed, manual-pass

#27534 Update e2e log archive
  tests/scripts/ci_logs.sh
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#27553 [cherry-pick]Update e2e log archive
  tests/scripts/ci_logs.sh
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#27405 rm dependency to rc when getting recovery info(#25363)
  internal/datacoord/channel_manager.go
  internal/datacoord/services.go
  internal/datacoord/services_test.go
  internal/querycoordv2/meta/coordinator_broker.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#27546 Refine log and err handling in querycoord broker
  internal/querycoordv2/meta/coordinator_broker.go
  internal/querycoordv2/meta/coordinator_broker_test.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#27554 modify test case search index partitions
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#27517 Modify nightly test cases
  tests/python_client/testcases/test_insert.py
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#27585 update e2e for log archive
  tests/scripts/ci_logs.sh
Labels: kind/improvement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#27586 [cherry-pick]update e2e for log archive
  tests/scripts/ci_logs.sh
Labels: kind/improvement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#27599 [skip e2e]Fix get image when short tag is out of date
  tests/scripts/get_image_tag_by_short_name.py
Labels: kind/improvement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#27351 Remove topic empty restriction when preCreated topic
  internal/mq/mqimpl/rocksmq/server/rocksmq_impl.go
  internal/mq/mqimpl/rocksmq/server/rocksmq_impl_test.go
  internal/rootcoord/dml_channels.go
  pkg/mq/msgstream/mq_msgstream.go
  pkg/mq/msgstream/mqwrapper/kafka/kafka_consumer.go
  pkg/mq/msgstream/mqwrapper/nmq/nmq_consumer.go
  pkg/mq/msgstream/mqwrapper/nmq/nmq_consumer_test.go
  pkg/mq/msgstream/mqwrapper/pulsar/pulsar_consumer.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#27602 Modify unstable test
  tests/python_client/testcases/test_compaction.py
Labels: kind/bug, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#27582 Support llvm17 on MacOS
  scripts/setenv.sh
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#27608 Add new compaction types
  internal/datanode/compactor.go
  internal/proto/data_coord.proto
  internal/proto/datapb/data_coord.pb.go
Labels: size/XL, approved, lgtm, ci-passed, dco-passed

#27572 refine log of update target version
  internal/querynodev2/delegator/distribution.go
  internal/querynodev2/services.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#27618 [skip e2e] Fix unstable UT
  internal/datanode/channel_manager_test.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#27362 remove useless log in querycoord
  internal/querycoordv2/observers/collection_observer.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#27567 Limit faiss ivf index build thread num and fix ut
  internal/core/thirdparty/knowhere/CMakeLists.txt
  internal/core/unittest/test_indexing.cpp
  internal/core/unittest/test_utils/DataGen.h
  internal/core/unittest/test_utils/indexbuilder_test_utils.h
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed, area/compilation

#27579 install ninja in advance for arm64
  build/docker/builder/cpu/ubuntu20.04/Dockerfile
  scripts/azure_build.sh
  scripts/core_build.sh
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#27616 Map old error code to new error
  internal/datanode/flush_manager.go
  pkg/util/merr/utils.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#27625 [test]Fix apply chaos condition
  tests/python_client/chaos/checker.py
  tests/python_client/chaos/test_chaos_apply.py
  tests/python_client/utils/util_common.py
  tests/python_client/utils/util_k8s.py
Labels: kind/improvement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#27558 Fix typo in priority name
  internal/querycoordv2/task/task.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#27547 Reduce goroutine resulting from GetIndexInfos
  internal/datacoord/mock_test.go
  internal/datacoord/util.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed, manual-pass, do-not-merge/missing-related-pr

#27557 Fix diskann searchCache param compatibility
  Makefile
  pkg/util/indexparams/disk_index_params.go
  pkg/util/indexparams/disk_index_params_test.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed, area/compilation

#27575 Add case query filter json field
  tests/python_client/testcases/test_query.py
Labels: kind/improvement, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#27631 Add broker for datanode grpc operations
  Makefile
  internal/datanode/broker/broker.go
  internal/datanode/broker/datacoord.go
  internal/datanode/broker/datacoord_test.go
  internal/datanode/broker/mock_broker.go
  internal/datanode/broker/rootcoord.go
  internal/datanode/broker/rootcoord_test.go
Labels: kind/improvement, size/XXL, approved, lgtm, ci-passed, dco-passed, area/compilation

#27635 fix vcpkg install path
  scripts/core_build.sh
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#27492 fix use same logidx in different field
  internal/datanode/flush_manager.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#27622 Remove useless parameters for Makefile
  .github/workflows/main.yaml
  Makefile
  internal/core/thirdparty/CMakeLists.txt
  scripts/core_build.sh
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed, area/compilation

#27647 Add test cases of COSINE logic optimize
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#27666 [skip e2e]Remove compact in concurrent test
  tests/python_client/chaos/testcases/test_concurrent_operation.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#27674 [skip e2e]Fix get image tag for 2.2.0 branch
  tests/scripts/get_image_tag_by_short_name.py
Labels: kind/improvement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#27672 Fix build with diskann failed
  Makefile
  scripts/core_build.sh
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed, area/compilation

#27676 Replace manual composed grpc call with Broker methods in DataNode
  internal/datanode/allocator/mock_allocator.go
  internal/datanode/broker/broker.go
  internal/datanode/broker/datacoord.go
  internal/datanode/broker/datacoord_test.go
  internal/datanode/broker/mock_broker.go
  internal/datanode/channel_meta.go
  internal/datanode/channel_meta_test.go
  internal/datanode/compactor_test.go
  internal/datanode/data_node.go
  internal/datanode/data_node_test.go
  internal/datanode/data_sync_service.go
  internal/datanode/data_sync_service_test.go
  internal/datanode/event_manager_test.go
  internal/datanode/flow_graph_insert_buffer_node_test.go
  internal/datanode/flow_graph_manager_test.go
  internal/datanode/flow_graph_time_tick_node.go
  internal/datanode/flush_manager.go
  internal/datanode/flush_manager_test.go
  internal/datanode/meta_service.go
  internal/datanode/meta_service_test.go
  internal/datanode/mock_test.go
  internal/datanode/services.go
  internal/datanode/services_test.go
  internal/datanode/timetick_sender.go
  internal/datanode/timetick_sender_test.go
Labels: kind/enhancement, size/XXL, approved, lgtm, ci-passed, dco-passed

#27510 Refine minio chunks manager
  internal/core/src/storage/MinioChunkManager.cpp
  internal/core/src/storage/MinioChunkManager.h
  internal/core/src/storage/Types.h
  internal/core/unittest/CMakeLists.txt
  internal/core/unittest/test_minio_chunk_manager.cpp
Labels: size/L, approved, lgtm, ci-passed, dco-passed, area/compilation

#27562 Remove recollect segment stats during starting datacoord
  internal/datacoord/cluster.go
  internal/datacoord/cluster_test.go
  internal/datacoord/server.go
  internal/datacoord/session_manager.go
  internal/datanode/data_node.go
  internal/datanode/data_node_test.go
  internal/proto/data_coord.proto
  internal/proto/datapb/data_coord.pb.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#27671 Fix panic at loadSegment during rolling upgrade
  internal/querynodev2/delegator/delegator_data.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#27669 Fix printing too many warnings (#27015)
  internal/util/flowgraph/node.go
Labels: kind/bug, kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#27588 Refine KV errors
  internal/kv/etcd/embed_etcd_kv.go
  internal/kv/etcd/etcd_kv.go
  internal/kv/mem/mem_kv.go
  internal/kv/tikv/txn_tikv.go
  internal/metastore/kv/rootcoord/kv_catalog.go
  internal/metastore/kv/rootcoord/kv_catalog_test.go
  internal/rootcoord/root_coord.go
  pkg/common/error.go
  pkg/common/error_test.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#27543 Fix compatibility of Flush
  internal/core/src/pb/common.pb.cc
  internal/core/src/pb/common.pb.h
  internal/datacoord/server_test.go
  internal/datacoord/services.go
Labels: kind/bug, size/XL, approved, lgtm, ci-passed, dco-passed

#27565 Add a stop hook to clean session(start milvus as a child process)
  cmd/main.go
  cmd/milvus/help.go
  cmd/milvus/run.go
  cmd/milvus/util.go
  cmd/roles/roles.go
  internal/datacoord/server.go
  internal/datanode/data_node.go
  internal/indexcoord/index_coord.go
  internal/indexnode/indexnode.go
  internal/proxy/proxy.go
  internal/querycoordv2/server.go
  internal/querynode/query_node.go
  internal/rootcoord/root_coord.go
  internal/util/sessionutil/session_util.go
  internal/util/sessionutil/session_util_test.go
  scripts/start_cluster.sh
  scripts/start_standalone.sh
  scripts/stop.sh
Labels: size/XL, approved, lgtm, ci-passed, dco-passed

#27688 remove flush from ddl queue in proxy
  internal/proxy/impl.go
  internal/proxy/proxy_test.go
  internal/proxy/task_scheduler.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#27695 Remove deprecated cmake parameter
  internal/core/CMakeLists.txt
  scripts/core_build.sh
Labels: size/S, approved, lgtm, ci-passed, dco-passed, area/compilation

#27703 Fix glog thread-safe bug for standalone mode
  internal/core/src/segcore/segcore_init_c.cpp
Labels: size/S, approved, lgtm, ci-passed, dco-passed

#27638 Compatible with scalar index types marisa-trie and Ascending
  internal/proxy/task_index.go
  internal/proxy/task_index_test.go
  internal/proxy/util.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#27711 Skip empty segment while query/search
  internal/querynodev2/segments/manager.go
Labels: kind/feature, kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#27598 Fix cannot find -latomic
  scripts/install_deps.sh
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#27609 update pymilvus version and modify Error code & msg improvement
  tests/python_client/requirements.txt
  tests/python_client/testcases/test_alias.py
  tests/python_client/testcases/test_collection.py
  tests/python_client/testcases/test_delete.py
  tests/python_client/testcases/test_high_level_api.py
  tests/python_client/testcases/test_index.py
  tests/python_client/testcases/test_partition.py
  tests/python_client/testcases/test_query.py
  tests/python_client/testcases/test_search.py
  tests/python_client/testcases/test_utility.py
Labels: sig/testing, size/XL, approved, lgtm, area/test, ci-passed, dco-passed

#27646 Fix RocksMQ seek speed
  go.mod
  go.sum
  internal/mq/mqimpl/rocksmq/client/client.go
  internal/mq/mqimpl/rocksmq/client/client_impl.go
  internal/mq/mqimpl/rocksmq/client/client_impl_test.go
  internal/mq/mqimpl/rocksmq/client/consumer.go
  internal/mq/mqimpl/rocksmq/client/consumer_impl.go
  internal/mq/mqimpl/rocksmq/client/producer.go
  internal/mq/mqimpl/rocksmq/client/producer_impl.go
  internal/mq/mqimpl/rocksmq/client/rmq_message.go
  internal/mq/mqimpl/rocksmq/client/test_helper.go
  internal/mq/mqimpl/rocksmq/client/util.go
  internal/mq/mqimpl/rocksmq/server/rmq_id.go
  internal/mq/mqimpl/rocksmq/server/rmq_id_test.go
  internal/mq/mqimpl/rocksmq/server/rocksmq.go
  internal/mq/mqimpl/rocksmq/server/rocksmq_impl.go
  internal/mq/mqimpl/rocksmq/server/rocksmq_impl_test.go
  internal/mq/msgstream/mqwrapper/rmq/rmq_client.go
  internal/mq/msgstream/mqwrapper/rmq/rmq_client_test.go
  internal/mq/msgstream/mqwrapper/rmq/rmq_consumer.go
  internal/mq/msgstream/mqwrapper/rmq/rmq_producer.go
Labels: area/dependency, size/XL, approved, lgtm, ci-passed, dco-passed

#27564 Add a stop hook to clean session(start milvus as a child process)
  cmd/main.go
  cmd/milvus/help.go
  cmd/milvus/run.go
  cmd/milvus/util.go
  cmd/roles/roles.go
  internal/datacoord/server.go
  internal/datanode/data_node.go
  internal/indexnode/indexnode.go
  internal/proxy/proxy.go
  internal/querycoordv2/server.go
  internal/querynodev2/server.go
  internal/rootcoord/root_coord.go
  internal/util/sessionutil/session_util.go
  internal/util/sessionutil/session_util_test.go
  scripts/start_cluster.sh
  scripts/start_standalone.sh
  scripts/stop.sh
Labels: size/L, approved, lgtm, ci-passed, dco-passed, area/compilation

#27410 Remove recollect segment stats during starting datacoord
  internal/datacoord/cluster.go
  internal/datacoord/cluster_test.go
  internal/datacoord/server.go
  internal/datacoord/session_manager.go
  internal/datanode/flow_graph_manager.go
  internal/datanode/services.go
  internal/datanode/services_test.go
  internal/proto/data_coord.proto
  internal/proto/datapb/data_coord.pb.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#27601 Add some log to print size of search result
  internal/core/src/segcore/Reduce.cpp
  internal/proxy/task_search.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#27639 fix retry on unimplemented rpc error
  internal/util/grpcclient/client.go
  internal/util/grpcclient/client_test.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#27640 speed up shard leader cache update frequency
  pkg/util/paramtable/component_param.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#27698 Expose metrics of standby coordinators
  internal/datacoord/services.go
  internal/querycoordv2/services.go
  internal/rootcoord/root_coord.go
  pkg/util/merr/utils.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed

#25882 Implement "SearchByPks" path in Search (work in progress)
  internal/proxy/impl.go
  internal/proxy/proxy_test.go
  pkg/util/funcutil/placeholdergroup.go
  pkg/util/funcutil/placeholdergroup_test.go
Labels: area/dependency, size/XL, approved, lgtm, ci-passed, dco-passed

#27641 [cherry-pick]speed up shard leader cache update frequency
  internal/util/paramtable/component_param.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#27134 remove unused code
  scripts/install_deps.sh
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#27724 update pymilvus verison
  tests/python_client/requirements.txt
  tests/python_client/testcases/test_index.py
  tests/python_client/testcases/test_utility.py
Labels: sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#27427 add gpu support
  tests/scripts/values/ci/pr-gpu.yaml
Labels: kind/improvement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#27725 Add channel name paramter in `FlushSegmentsRequest`
  internal/datacoord/cluster.go
  internal/proto/data_coord.proto
  internal/proto/datapb/data_coord.pb.go
Labels: kind/improvement, size/XL, approved, lgtm, ci-passed, dco-passed

#27376 add test cases
  tests/python_client/common/common_type.py
  tests/python_client/testcases/test_insert.py
  tests/python_client/testcases/test_utility.py
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#27729 Fix Flush error message typo
  internal/datacoord/services.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#27436 Enhance InsertData and FieldData
  internal/storage/data_codec.go
  internal/storage/data_codec_test.go
  internal/storage/insert_data.go
  internal/storage/insert_data_test.go
Labels: kind/improvement, size/XXL, approved, lgtm, ci-passed, dco-passed

#27749 Handle legacy querynode `Delete` Unimplemented
  internal/querynodev2/cluster/worker.go
  internal/querynodev2/cluster/worker_test.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#27747 Remove deprecated io/ioutil usage
  .golangci.yml
  cmd/milvus/util.go
  cmd/tools/migration/backend/etcd210.go
  internal/allocator/global_id_allocator_test.go
  internal/distributed/proxy/service.go
  internal/http/server_test.go
  internal/indexnode/etcd_mock.go
  internal/proxy/accesslog/log_writer.go
  internal/storage/local_chunk_manager.go
  internal/storage/print_binlog_test.go
  internal/util/importutil/numpy_adapter.go
  internal/util/sessionutil/session_util_test.go
  pkg/eventlog/handler_test.go
  pkg/log/zap_log_test.go
  pkg/util/etcd/etcd_util.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#27723 Support the apikey authentication
  go.mod
  go.sum
  internal/distributed/proxy/service.go
  internal/proxy/authentication_interceptor.go
  internal/proxy/authentication_interceptor_test.go
  internal/proxy/hook_interceptor.go
  internal/proxy/hook_interceptor_test.go
Labels: area/dependency, kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#27736 Fix SIGSEGV if run within gdb
  internal/core/src/common/Array.h
  internal/core/src/segcore/ConcurrentVector.h
  internal/proxy/impl.go
  internal/querynodev2/pipeline/filter_node.go
  internal/querynodev2/pipeline/message.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#27651 Fix non-removed 2 GB temporary file in test_utils.cpp
  internal/core/unittest/test_utils.cpp
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#27751 Return newly defined merr instead of grpc unimplemented err
  internal/datacoord/server_test.go
  internal/datacoord/services.go
  internal/querycoordv2/meta/target_manager.go
  internal/querycoordv2/meta/target_manager_test.go
  internal/util/grpcclient/client.go
  internal/util/grpcclient/client_test.go
  pkg/util/merr/errors.go
  pkg/util/merr/errors_test.go
  pkg/util/merr/utils.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#27758 Support the apikey authentication for the restful api
  internal/distributed/proxy/httpserver/utils.go
  internal/distributed/proxy/service.go
  internal/distributed/proxy/service_test.go
  internal/proxy/authentication_interceptor.go
  internal/proxy/authentication_interceptor_test.go
  internal/proxy/hook_interceptor.go
  internal/proxy/util.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#27765 fix query shard inUse leak
  internal/querynode/impl.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed, kind/branch-feature

#27643 Add iterators
  internal/datanode/iterators/binlog_iterator.go
  internal/datanode/iterators/binlog_iterator_test.go
  internal/datanode/iterators/deltalog_iterator.go
  internal/datanode/iterators/deltalog_iterator_test.go
  internal/datanode/iterators/iterator.go
  internal/storage/data_codec_test.go
Labels: kind/improvement, size/XL, approved, lgtm, ci-passed, dco-passed

#27755 Support receive signal from parent process
  cmd/main.go
  cmd/milvus/util.go
  internal/util/sessionutil/session_util.go
  internal/util/sessionutil/session_util_test.go
  scripts/stop.sh
Labels: size/L, approved, lgtm, ci-passed, dco-passed, do-not-merge/missing-related-pr

#27615 Limiting the idempotence check for index to user index params
  internal/datacoord/index_meta.go
  internal/datacoord/index_meta_test.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#27756 Support receive signals from parent process
  cmd/main.go
  cmd/milvus/util.go
  internal/util/sessionutil/session_util.go
  internal/util/sessionutil/session_util_test.go
  scripts/stop.sh
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#27491 Refine insert when send message
  pkg/mq/msgstream/mq_msgstream.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#27767 Use pool to block exceeded tasks
  internal/proxy/task_scheduler.go
  pkg/util/paramtable/component_param.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#27738 fix unstable unit test of delete
  tests/python_client/testcases/test_delete.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#27728 Set channel work pool size in datanode
  configs/milvus.yaml
  internal/datanode/io_pool.go
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/component_param_test.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#27781 Add querynode client wrapper and avoid grpc in standalone mode
  internal/proxy/shard_client.go
  internal/querynodev2/server.go
  internal/registry/in_mem_resolver.go
  internal/util/streamrpc/in_memory_streamer.go
  internal/util/streamrpc/in_memory_streamer_test.go
  internal/util/wrappers/qn_wrapper.go
  internal/util/wrappers/qn_wrapper_test.go
Labels: kind/enhancement, size/XL, approved, lgtm, ci-passed, dco-passed

#27593 Schedule loading L0 segments first
  internal/querycoordv2/checkers/segment_checker.go
  internal/querycoordv2/meta/leader_view_manager.go
Labels: kind/feature, size/M, approved, lgtm, ci-passed, dco-passed

#27785 Use pool to block exceeded tasks (#27767)
  internal/proxy/task_scheduler.go
  internal/util/paramtable/component_param.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#27744 Register metrics before component start
  cmd/roles/roles.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#27769 Rectify wrong exception messages associated with Array datatype
  internal/proxy/meta_cache.go
  internal/proxy/util.go
  internal/proxy/validate_util.go
  internal/querycoordv2/handlers.go
  internal/querynodev2/server_test.go
  internal/rootcoord/meta_table.go
  pkg/util/merr/errors.go
  pkg/util/merr/utils.go
  tests/python_client/requirements.txt
  tests/python_client/testcases/test_alias.py
  tests/python_client/testcases/test_collection.py
  tests/python_client/testcases/test_insert.py
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#27804 enable traceID for retrieve
  internal/querynodev2/segments/segment.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#27810 Update knowhere version to v2.2.2
  internal/core/thirdparty/knowhere/CMakeLists.txt
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed, area/compilation

#27789 check data sync service num in graceful stop
  internal/querynode/impl.go
  internal/querynode/query_node.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed, manual-pass, kind/branch-feature

#27774 update collection target after observer start
  internal/querycoordv2/observers/target_observer.go
  internal/querycoordv2/observers/target_observer_test.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#27809 Add ctx parameter and log tracer for watch and selectNodes
  internal/datacoord/channel_manager.go
  internal/datacoord/channel_manager_test.go
  internal/datacoord/cluster.go
  internal/datacoord/cluster_test.go
  internal/datacoord/server_test.go
  internal/datacoord/services.go
  internal/datacoord/services_test.go
  internal/proxy/lb_policy.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#27800 fix grpc error judge logic
  internal/querynodev2/cluster/worker.go
  internal/querynodev2/cluster/worker_test.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#27787 [restful] new interface: upsert
  internal/distributed/proxy/httpserver/constant.go
  internal/distributed/proxy/httpserver/handler_v1.go
  internal/distributed/proxy/httpserver/handler_v1_test.go
  internal/distributed/proxy/httpserver/request.go
  internal/distributed/proxy/httpserver/utils.go
  internal/distributed/proxy/httpserver/utils_test.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#27784 Add test cases of scann index
  tests/python_client/testcases/test_index.py
  tests/python_client/testcases/test_search.py
Labels: kind/improvement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#27400 add senario: rename collection in a new db
  tests/python_client/base/utility_wrapper.py
  tests/python_client/testcases/test_database.py
Labels: sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#27820 [skip e2e]Update the method whether vector field is indexed
  tests/python_client/deploy/testcases/test_action_second_deployment.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#27816 Fix partition's gc
  internal/metastore/kv/rootcoord/kv_catalog.go
  internal/metastore/kv/rootcoord/kv_catalog_test.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed

#27834 Add the mock factory of msg stream
  pkg/Makefile
  pkg/mq/msgstream/mock_msgstream_factory.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed, area/compilation

#27823 Reduce write lock scope in channel manager
  internal/datacoord/channel_manager.go
  internal/datacoord/channel_manager_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#27824 Reduce write lock scope in channel manager
  internal/datacoord/channel_manager.go
  internal/datacoord/channel_manager_test.go
  internal/datacoord/mock_handler.go
  internal/datacoord/mock_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#27788 modify error code nightly cases
  tests/python_client/testcases/test_collection.py
  tests/python_client/testcases/test_delete.py
  tests/python_client/testcases/test_partition.py
  tests/python_client/testcases/test_query.py
  tests/python_client/testcases/test_search.py
  tests/python_client/testcases/test_utility.py
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#27826 [test]Reduce some op frequency
  tests/python_client/chaos/checker.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#27633 [test]Add concurrent test in ci
  tests/python_client/chaos/checker.py
  tests/python_client/chaos/conftest.py
  tests/python_client/conftest.py
  tests/python_client/testcases/test_concurrent.py
  tests/scripts/ci_e2e_4am.sh
Labels: kind/improvement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#27849 [skip e2e]Skip creating index when it was already created
  tests/python_client/deploy/scripts/utils.py
Labels: kind/improvement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#27854 Make KeyLock generic
  pkg/util/lock/key_lock.go
  pkg/util/lock/key_lock_test.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#27768 Add meta cache to datanode for L0 Delta
  internal/datanode/metacache/meta_cache.go
  internal/datanode/metacache/meta_cache_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#27692 Add chunk manager request timeout
  configs/milvus.yaml
  internal/core/src/common/Consts.h
  internal/core/src/common/type_c.h
  internal/core/src/indexbuilder/index_c.cpp
  internal/core/src/storage/ChunkManagers.cpp
  internal/core/src/storage/MinioChunkManager.cpp
  internal/core/src/storage/Types.h
  internal/core/src/storage/storage_c.cpp
  internal/datacoord/index_builder.go
  internal/indexnode/chunk_mgr_factory.go
  internal/proto/index_coord.proto
  internal/proto/indexpb/index_coord.pb.go
  internal/storage/factory.go
  internal/storage/options.go
  internal/util/indexcgowrapper/build_index_info.go
  internal/util/initcore/init_core.go
  pkg/util/paramtable/base_table.go
  pkg/util/paramtable/service_param.go
Labels: size/L, approved, lgtm, ci-passed, area/internal-api, dco-passed

#27483 Reduce rpc size for GetRecoveryInfoV2
  configs/milvus.yaml
  internal/datacoord/channel_manager.go
  internal/datacoord/cluster_test.go
  internal/datacoord/server_test.go
  internal/datacoord/services.go
  internal/datacoord/services_test.go
  internal/metastore/kv/datacoord/kv_catalog.go
  internal/metastore/kv/datacoord/kv_catalog_test.go
  internal/querycoordv2/meta/coordinator_broker.go
  pkg/util/paramtable/grpc_param.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#27835 [skip e2e] update gpu builder image
  build/docker/builder/gpu/ubuntu20.04/Dockerfile
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#27603 Add test cases of array
  tests/python_client/common/common_func.py
  tests/python_client/common/common_type.py
  tests/python_client/testcases/test_collection.py
  tests/python_client/testcases/test_delete.py
  tests/python_client/testcases/test_high_level_api.py
  tests/python_client/testcases/test_index.py
  tests/python_client/testcases/test_insert.py
  tests/python_client/testcases/test_query.py
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/XL, approved, lgtm, area/test, ci-passed, dco-passed

#27791 Update pymilvus version
  tests/python_client/requirements.txt
  tests/python_client/testcases/test_collection.py
  tests/python_client/testcases/test_insert.py
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#27851 fix some typos
  DEVELOPMENT.md
  ci/jenkins/PublishImages.groovy
  configs/advanced/etcd.yaml
  configs/milvus.yaml
  docs/design_docs/20210604-datanode_flowgraph_recovery_design.md
  docs/design_docs/20211217-milvus_create_collection.md
  docs/design_docs/20220105-proxy.md
  docs/design_docs/20220105-query_boolean_expr.md
  docs/design_docs/20230918-datanode_remove_datacoord_dependency.md
  docs/design_docs/segcore/segment_growing.md
  docs/developer_guides/appendix_a_basic_components.md
  docs/developer_guides/chap04_message_stream.md
  docs/developer_guides/chap05_proxy.md
  docs/developer_guides/chap07_query_coordinator.md
  docs/user_guides/tls_proxy.md
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#27844 Make qcv2 target&leader observer execute in parallel
  internal/querycoordv2/observers/collection_observer.go
  internal/querycoordv2/observers/leader_observer.go
  internal/querycoordv2/observers/leader_observer_test.go
  internal/querycoordv2/observers/target_observer.go
  internal/querycoordv2/observers/target_observer_test.go
  internal/querycoordv2/observers/task_dispatcher.go
  pkg/util/paramtable/component_param.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#27879 [skip e2e]Update chaos duration time
  tests/python_client/chaos/checker.py
Labels: kind/improvement, sig/testing, size/XS, approved, area/test, ci-passed, dco-passed

#27848 fix query shard service leak
  internal/querynode/impl.go
  internal/querynode/load_segment_task.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed, manual-pass, kind/branch-feature

#27859 check stopping node during start qc
  internal/querycoordv2/server.go
  internal/querycoordv2/server_test.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#27317 Add some log for delete task when it need query
  internal/proxy/task_delete.go
  internal/querynodev2/delegator/delegator.go
  internal/querynodev2/handlers.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed

#27885 Fix taskDispatcher add multiple tasks will ignore following ones
  internal/querycoordv2/observers/task_dispatcher.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#27884 Refine RPC call in unwatch drop channel
  internal/datacoord/channel_manager.go
  internal/datacoord/channel_manager_test.go
  internal/datacoord/handler.go
  internal/datacoord/mock_handler.go
  internal/datacoord/mock_test.go
  internal/datacoord/server.go
  internal/datacoord/server_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#27864 Refine RPC call in unwatch drop channel
  internal/datacoord/channel_manager.go
  internal/datacoord/channel_manager_test.go
  internal/datacoord/handler.go
  internal/datacoord/mock_handler.go
  internal/datacoord/mock_test.go
  internal/datacoord/server.go
  internal/datacoord/server_test.go
  pkg/mq/msgstream/mock_msgstream_factory.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#27870 Upgrade conan to 1.61.0
  .github/workflows/mac.yaml
  DEVELOPMENT.md
  build/docker/builder/cpu/amazonlinux2023/Dockerfile
  build/docker/builder/cpu/ubuntu20.04/Dockerfile
  build/docker/builder/gpu/ubuntu20.04/Dockerfile
  internal/core/conanfile.py
  scripts/install_deps.sh
  scripts/install_deps_msys.sh
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#27878 Fix datanode ttNode goroutine leak
  internal/datanode/flow_graph_time_tick_node.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, area/internal-api, dco-passed

#27852 Remove annoying warning logs
  internal/datanode/flow_graph_dd_node.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed, kind/branch-feature

#27836 [skip e2e] update gpu builder image
  build/docker/builder/gpu/ubuntu20.04/Dockerfile
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed, do-not-merge/missing-related-pr

#27889 Add test cases of array contains
  tests/python_client/common/common_func.py
  tests/python_client/testcases/test_query.py
  tests/python_client/testcases/test_search.py
Labels: kind/improvement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#27893 Bump Milvus Version & milvus-proto/go-api to v2.3.2
  go.mod
  go.sum
  pkg/common/version.go
Labels: area/dependency, kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#27894 Fix initialization and backward compatibility issue for GRPC compression
  configs/milvus.yaml
  internal/distributed/datacoord/service.go
  internal/distributed/datanode/service.go
  internal/distributed/indexnode/service.go
  internal/distributed/proxy/service.go
  internal/distributed/querycoord/service.go
  internal/distributed/querynode/service.go
  internal/distributed/rootcoord/service.go
  pkg/util/paramtable/grpc_param.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed
