Repository milvus-io/milvus, pull requests merged in 2023-05, with the labels that each got.

#23825 Add collection in querynode when sync new partitions
  internal/proto/query_coord.proto
  internal/proto/querypb/query_coord.pb.go
  internal/querycoordv2/job/job_load.go
  internal/querycoordv2/job/job_release.go
  internal/querycoordv2/job/job_sync.go
  internal/querycoordv2/job/utils.go
  internal/querynodev2/services.go
  internal/querynodev2/services_test.go
  internal/rootcoord/broker.go
Labels: kind/bug, size/XL, approved, lgtm, ci-passed, area/internal-api, dco-passed

#23835 Fix upgrade cause panic
  internal/querycoordv2/server.go
  internal/rootcoord/dml_channels.go
  internal/rootcoord/timeticksync.go
  internal/rootcoord/timeticksync_test.go
  internal/rootcoord/util.go
  internal/rootcoord/util_test.go
  tests/python_client/testcases/test_compaction.py
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#23832 Fix upgrade cause panic
  internal/querycoordv2/server.go
  internal/rootcoord/dml_channels.go
  internal/rootcoord/timeticksync.go
  internal/rootcoord/timeticksync_test.go
  internal/rootcoord/util.go
  internal/rootcoord/util_test.go
  tests/python_client/testcases/test_compaction.py
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#23833 Fix upgrade cause panic
  internal/querycoordv2/server.go
  internal/rootcoord/dml_channels.go
  internal/rootcoord/timeticksync.go
  internal/rootcoord/timeticksync_test.go
  internal/rootcoord/util.go
  internal/rootcoord/util_test.go
  tests/python_client/testcases/test_compaction.py
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, manual-pass

#23838 Bump semver to 2.2.8
  internal/common/version.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#23841 Bump milvus version to v2.2.8
  deployments/binary/README.md
  deployments/docker/standalone/docker-compose.yml
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#23791 refine balance mechanism including:(#23454) (#23763)
  configs/milvus.yaml
  internal/datacoord/compaction.go
  internal/datacoord/meta.go
  internal/datacoord/server.go
  internal/datacoord/server_test.go
  internal/datanode/flow_graph_manager_test.go
  internal/querycoordv2/balance/balance.go
  internal/querycoordv2/balance/mock_balancer.go
  internal/querycoordv2/balance/rowcount_based_balancer.go
  internal/querycoordv2/balance/rowcount_based_balancer_test.go
  internal/querycoordv2/balance/score_based_balancer.go
  internal/querycoordv2/balance/score_based_balancer_test.go
  internal/querycoordv2/balance/utils.go
  internal/querycoordv2/checkers/balance_checker.go
  internal/querycoordv2/checkers/balance_checker_test.go
  internal/querycoordv2/checkers/controller.go
  internal/querycoordv2/task/executor.go
  internal/querycoordv2/task/scheduler.go
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/component_param_test.go
Labels: size/XL, approved, lgtm, ci-passed, dco-passed

#23843 Update test case due to max shards num 16
  tests/python_client/common/common_type.py
  tests/python_client/testcases/test_collection.py
  tests/python_client/testcases/test_search.py
Labels: kind/improvement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#23844 [cherry-pick] Update test case due to max shards num 16
  tests/python_client/common/common_type.py
  tests/python_client/testcases/test_collection.py
  tests/python_client/testcases/test_search.py
Labels: kind/improvement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#23830 Fix ignoring error when loading segment
  internal/querynodev2/segments/segment_loader.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#23688 Remove index check to trigger compaction (#23657)
  internal/datacoord/compaction_trigger.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#23851 [2.2.x] Fix Int8~Int32 empty result set type
  internal/util/typeutil/gen_empty_field_data.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#23847 Fix dependency conflict
  internal/core/conanfile.py
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#23862 ci: update log level to debug
  tests/scripts/values/pr.yaml
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#23779 Make datanode load statslog lazy if SkipBFStatsLog is true
  internal/datanode/channel_meta.go
  internal/datanode/channel_meta_test.go
  internal/datanode/data_sync_service.go
  internal/datanode/errors.go
  internal/datanode/segment.go
  internal/util/errorutil/util.go
  internal/util/errorutil/util_test.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#23873 [Cherry-Pick] Bump github.com/gin-gonic/gin from 1.7.7 to 1.9.0
  go.mod
  go.sum
Labels: area/dependency, kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#23871 Bump semantic version to 2.2.9-pre+dev
  internal/common/version.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#23885 Change mac code checker timeout to 5h
  .github/workflows/mac.yaml
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#23878 Improve the rbac log when milvus is starting
  internal/metastore/kv/rootcoord/kv_catalog.go
  internal/metastore/kv/rootcoord/kv_catalog_test.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#23600 Reduce memory usage for diskann index
  internal/core/src/storage/DiskFileManagerImpl.cpp
  internal/core/src/storage/DiskFileManagerImpl.h
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#23603 Implement GetIndexStatistics interface
  internal/datacoord/index_service.go
  internal/datacoord/index_service_test.go
  internal/distributed/datacoord/client/client.go
  internal/distributed/datacoord/client/client_test.go
  internal/distributed/datacoord/service.go
  internal/distributed/datacoord/service_test.go
  internal/distributed/proxy/service_test.go
  internal/mocks/mock_datacoord.go
  internal/proto/data_coord.proto
  internal/proto/datapb/data_coord.pb.go
  internal/proto/index_coord.proto
  internal/proto/indexpb/index_coord.pb.go
  internal/proxy/data_coord_mock_test.go
  internal/proxy/impl.go
  internal/proxy/proxy_test.go
  internal/proxy/task_index.go
  internal/types/types.go
  internal/util/mock/grpc_datacoord_client.go
  tests/integration/get_index_statistics_test.go
Labels: area/dependency, sig/testing, size/XXL, approved, lgtm, area/test, ci-passed, area/internal-api, dco-passed

#23856 Refactor check logic of index parameters
  internal/proxy/impl.go
  internal/proxy/task_index.go
  pkg/util/indexparamcheck/base_checker.go
  pkg/util/indexparamcheck/base_checker_test.go
  pkg/util/indexparamcheck/bin_flat_checker.go
  pkg/util/indexparamcheck/bin_flat_checker_test.go
  pkg/util/indexparamcheck/bin_ivf_flat_checker.go
  pkg/util/indexparamcheck/bin_ivf_flat_checker_test.go
  pkg/util/indexparamcheck/binary_vector_base_checker.go
  pkg/util/indexparamcheck/binary_vector_base_checker_test.go
  pkg/util/indexparamcheck/conf_adapter.go
  pkg/util/indexparamcheck/conf_adapter_mgr.go
  pkg/util/indexparamcheck/conf_adapter_mgr_test.go
  pkg/util/indexparamcheck/conf_adapter_test.go
  pkg/util/indexparamcheck/constraints.go
  pkg/util/indexparamcheck/diskann_checker.go
  pkg/util/indexparamcheck/diskann_checker_test.go
  pkg/util/indexparamcheck/float_vector_base_checker.go
  pkg/util/indexparamcheck/float_vector_base_checker_test.go
  pkg/util/indexparamcheck/hnsw_checker.go
  pkg/util/indexparamcheck/hnsw_checker_test.go
  pkg/util/indexparamcheck/index_checker.go
  pkg/util/indexparamcheck/index_checker_test.go
  pkg/util/indexparamcheck/ivf_base_checker.go
  pkg/util/indexparamcheck/ivf_base_checker_test.go
  pkg/util/indexparamcheck/ivf_pq_checker.go
  pkg/util/indexparamcheck/ivf_pq_checker_test.go
  pkg/util/indexparamcheck/ivf_sq_checker.go
  pkg/util/indexparamcheck/ivf_sq_checker_test.go
  pkg/util/indexparamcheck/raft_ivf_pq_checker.go
  pkg/util/indexparamcheck/raft_ivf_pq_checker_test.go
  pkg/util/indexparamcheck/utils.go
Labels: size/XXL, approved, lgtm, ci-passed, dco-passed

#23858 Add test cases of Get Vector By Id
  tests/python_client/common/common_type.py
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#23852 Fix Int8~Int32 empty result set type
  pkg/util/typeutil/gen_empty_field_data.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#23883 Re-calculate segment entry num when binlog field is zero
  internal/querynodev2/segments/segment_loader.go
  internal/querynodev2/segments/segment_loader_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#23877 [Cherry-Pick] Make datanode load statslog lazy if SkipBFStatsLog is true
  internal/datanode/channel_meta.go
  internal/datanode/channel_meta_test.go
  internal/datanode/data_sync_service.go
  internal/datanode/segment.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#23876 ci: update log level to debug
  tests/scripts/values/pr.yaml
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#23787 Update pymilvus version and modify some cases
  tests/python_client/requirements.txt
  tests/python_client/testcases/test_connection.py
  tests/python_client/testcases/test_insert.py
  tests/python_client/testcases/test_partition.py
Labels: sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#23773 Add it for refresh config
  pkg/config/env_source.go
  pkg/config/etcd_source.go
  pkg/config/file_source.go
  pkg/config/manager.go
  pkg/config/manager_test.go
  pkg/config/source.go
  pkg/util/paramtable/base_table.go
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/service_param.go
  tests/integration/minicluster.go
  tests/integration/refresh_config_test.go
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, manual-pass

#23872 Fix partition released but can be searched
  internal/querynodev2/services.go
  internal/querynodev2/services_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#23889 support cp lag behind policy(#23621)
  internal/datanode/channel_meta.go
  internal/datanode/data_sync_service_test.go
  internal/datanode/segment_sync_policy.go
  internal/datanode/segment_sync_policy_test.go
  internal/util/paramtable/component_param.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#23762 Update pymilvus version
  tests/python_client/base/collection_wrapper.py
  tests/python_client/check/func_check.py
  tests/python_client/requirements.txt
  tests/python_client/testcases/test_collection.py
  tests/python_client/testcases/test_insert.py
  tests/python_client/testcases/test_partition.py
Labels: sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#23625 Add test cases of partition dynamic
  tests/python_client/testcases/test_collection.py
Labels: sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#23694 Add test cases of search expression
  tests/python_client/common/common_type.py
  tests/python_client/testcases/test_compaction.py
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#23859 Improve the metric of binlog size to the level of collection and segment
  internal/datacoord/meta.go
  pkg/metrics/datacoord_metrics.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#23894 Remove superfluous idempotent in proxy
  internal/proxy/task.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#23897 Add some log in getIndexStatisticsTask
  internal/proxy/task_index.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#23919 Fix nil pointer access
  internal/querycoordv2/checkers/balance_checker.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#23823 Fix creating partition is not atomic
  internal/rootcoord/create_partition_task.go
  internal/rootcoord/garbage_collector.go
  internal/rootcoord/garbage_collector_test.go
  internal/rootcoord/mocks/garbage_collector.go
  internal/rootcoord/root_coord.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#23909 Fix parse token error
  internal/proxy/authentication_interceptor.go
  internal/proxy/authentication_interceptor_test.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#23928 Make CollectionObserver trigger checker during load procedure
  internal/querycoordv2/checkers/controller.go
  internal/querycoordv2/observers/collection_observer.go
  internal/querycoordv2/observers/collection_observer_test.go
  internal/querycoordv2/server.go
  internal/querycoordv2/server_test.go
  internal/querycoordv2/services_test.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#23904 Make querynode lazy load statslog if SkipBFLoad is true
  internal/querynode/errors.go
  internal/querynode/segment.go
  internal/querynode/segment_loader.go
  internal/querynode/segment_loader_test.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#23884 Improve the rbac log when milvus is starting
  internal/metastore/kv/rootcoord/kv_catalog.go
  internal/metastore/kv/rootcoord/kv_catalog_test.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#23922 Fix to list grant with db return empty
  internal/metastore/kv/rootcoord/kv_catalog.go
  internal/metastore/kv/rootcoord/kv_catalog_test.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#23946 Upgrade Knowhere to 1.3.13
  internal/core/thirdparty/knowhere/CMakeLists.txt
Labels: size/XS, approved, lgtm, ci-passed, dco-passed, area/compilation

#23957 [2.2.x] Fix concurrent map read/write in rate limiter
  internal/proxy/multi_rate_limiter.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#23951 Add trace log for grpc client
  internal/util/grpcclient/client.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#23930 Log optimized search params
  internal/querynodev2/handlers.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#23955 [2.2.x] Refresh etcd source config with Searializable option
  internal/config/etcd_source.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#23287 Remove load cache
  internal/proxy/meta_cache.go
  internal/proxy/meta_cache_test.go
  internal/proxy/task_query.go
  internal/proxy/task_query_test.go
  internal/proxy/task_search.go
  internal/proxy/task_search_test.go
  internal/querycoordv2/services.go
  internal/querycoordv2/services_test.go
  tests/python_client/testcases/test_partition.py
Labels: kind/enhancement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#23958 Fix concurrent map read/write in rate limiter
  internal/proxy/multi_rate_limiter.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#23954 Refresh etcd source config with Searializable option
  pkg/config/etcd_source.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#23939 Modify test cases
  tests/python_client/base/client_base.py
  tests/python_client/common/common_type.py
  tests/python_client/testcases/test_collection.py
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#23926 Modify test cases due to pymilvus update
  tests/python_client/testcases/test_connection.py
Labels: sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#23963 correct the behavior of create duplicate rg
  internal/querycoordv2/meta/resource_manager.go
  internal/querycoordv2/meta/resource_manager_test.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#23903 Refactor check logic of index parameters (#23856)
  internal/proxy/task_index.go
  internal/util/indexparamcheck/annoy_checker.go
  internal/util/indexparamcheck/annoy_checker_test.go
  internal/util/indexparamcheck/base_checker.go
  internal/util/indexparamcheck/base_checker_test.go
  internal/util/indexparamcheck/bin_flat_checker.go
  internal/util/indexparamcheck/bin_flat_checker_test.go
  internal/util/indexparamcheck/bin_ivf_flat_checker.go
  internal/util/indexparamcheck/bin_ivf_flat_checker_test.go
  internal/util/indexparamcheck/binary_vector_base_checker.go
  internal/util/indexparamcheck/binary_vector_base_checker_test.go
  internal/util/indexparamcheck/conf_adapter.go
  internal/util/indexparamcheck/conf_adapter_mgr.go
  internal/util/indexparamcheck/conf_adapter_mgr_test.go
  internal/util/indexparamcheck/conf_adapter_test.go
  internal/util/indexparamcheck/constraints.go
  internal/util/indexparamcheck/diskann_checker.go
  internal/util/indexparamcheck/diskann_checker_test.go
  internal/util/indexparamcheck/float_vector_base_checker.go
  internal/util/indexparamcheck/float_vector_base_checker_test.go
  internal/util/indexparamcheck/hnsw_checker.go
  internal/util/indexparamcheck/hnsw_checker_test.go
  internal/util/indexparamcheck/index_checker.go
  internal/util/indexparamcheck/index_checker_test.go
  internal/util/indexparamcheck/ivf_base_checker.go
  internal/util/indexparamcheck/ivf_base_checker_test.go
  internal/util/indexparamcheck/ivf_pq_checker.go
  internal/util/indexparamcheck/ivf_pq_checker_test.go
  internal/util/indexparamcheck/ivf_sq_checker.go
  internal/util/indexparamcheck/ivf_sq_checker_test.go
  internal/util/indexparamcheck/ngt_onng_checker.go
  internal/util/indexparamcheck/ngt_onng_checker_test.go
  internal/util/indexparamcheck/ngt_panng_checker.go
  internal/util/indexparamcheck/ngt_panng_checker_test.go
  internal/util/indexparamcheck/nsg_checker.go
  internal/util/indexparamcheck/nsg_checker_test.go
  internal/util/indexparamcheck/rhnsw_checker.go
  internal/util/indexparamcheck/rhnsw_checker_test.go
  internal/util/indexparamcheck/rhnsw_pq_checker.go
  internal/util/indexparamcheck/rhnsw_pq_checker_test.go
  internal/util/indexparamcheck/rhnsw_sq_checker.go
  internal/util/indexparamcheck/rhnsw_sq_checker_test.go
  internal/util/indexparamcheck/utils.go
Labels: size/XXL, approved, lgtm, ci-passed, dco-passed

#23982 Filter id field out if not specified
  internal/proxy/task_search.go
  internal/proxy/task_search_test.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#23984 Update pymilvus version
  tests/python_client/requirements.txt
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#23983 Update pymilvus version
  tests/python_client/requirements.txt
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#23967 make ddl rate limit be global level
  internal/proxy/multi_rate_limiter.go
  internal/proxy/multi_rate_limiter_test.go
  internal/proxy/rate_limit_interceptor.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#23961 Load delete from channel checkpoint
  internal/proto/query_coord.proto
  internal/proto/querypb/query_coord.pb.go
  internal/querycoordv2/observers/leader_observer.go
  internal/querycoordv2/observers/leader_observer_test.go
  internal/querycoordv2/task/executor.go
  internal/querycoordv2/task/utils.go
  internal/querycoordv2/utils/types.go
  internal/querycoordv2/utils/types_test.go
  internal/querynodev2/delegator/delegator_data.go
  internal/querynodev2/delegator/delegator_data_test.go
  internal/querynodev2/segments/segment.go
  internal/querynodev2/segments/segment_loader.go
  internal/querynodev2/services_test.go
Labels: kind/bug, size/XL, approved, lgtm, ci-passed, area/internal-api, dco-passed

#23976 Add integration test workflow
  .github/workflows/main.yaml
  scripts/run_intergration_test.sh
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#23892 Modify diskann memory estimation method
  internal/querynode/load_index_info.go
  internal/querynode/segment_loader.go
  internal/querynode/segment_loader_test.go
  internal/util/indexparams/disk_index_params.go
  internal/util/indexparams/disk_index_params_test.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#23879 Update hello_milvus.py
  tests/python_client/chaos/scripts/hello_milvus.py
Labels: kind/improvement, sig/testing, size/S, approved, lgtm, area/test, dco-passed

#23990 Fix some wrong ut
  internal/datacoord/server.go
  internal/datacoord/server_test.go
  internal/proxy/impl.go
  internal/proxy/proxy_test.go
  internal/proxy/task_statistic_test.go
  internal/proxy/task_test.go
  internal/querycoordv2/services_test.go
  internal/querynodev2/services.go
  internal/querynodev2/services_test.go
  internal/rootcoord/dml_channels.go
  internal/rootcoord/timeticksync_test.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#23977 Use boost 1.79 to avoid queue memory leak
  internal/core/conanfile.py
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#23804 Support expr with json field
  internal/core/src/pb/plan.pb.cc
  internal/core/src/pb/plan.pb.h
  internal/core/src/query/Expr.h
  internal/core/src/query/ExprImpl.h
  internal/core/src/query/Parser.cpp
  internal/core/src/query/PlanProto.cpp
  internal/core/src/query/PlanProto.h
  internal/core/src/query/generated/ExecExprVisitor.h
  internal/core/src/query/generated/Expr.cpp
  internal/core/src/query/generated/ExprVisitor.h
  internal/core/src/query/generated/ExtractInfoExprVisitor.h
  internal/core/src/query/generated/ShowExprVisitor.h
  internal/core/src/query/generated/VerifyExprVisitor.h
  internal/core/src/query/visitors/ExecExprVisitor.cpp
  internal/core/src/query/visitors/ExtractInfoExprVisitor.cpp
  internal/core/src/query/visitors/ShowExprVisitor.cpp
  internal/core/src/query/visitors/VerifyExprVisitor.cpp
  internal/core/unittest/test_c_api.cpp
  internal/core/unittest/test_expr.cpp
  internal/core/unittest/test_retrieve.cpp
  internal/core/unittest/test_utils/DataGen.h
  internal/parser/planparserv2/Plan.g4
  internal/parser/planparserv2/generated/Plan.interp
  internal/parser/planparserv2/generated/Plan.tokens
  internal/parser/planparserv2/generated/PlanLexer.interp
  internal/parser/planparserv2/generated/PlanLexer.tokens
  internal/parser/planparserv2/generated/plan_base_visitor.go
  internal/parser/planparserv2/generated/plan_lexer.go
  internal/parser/planparserv2/generated/plan_parser.go
  internal/parser/planparserv2/generated/plan_visitor.go
  internal/parser/planparserv2/parser_visitor.go
  internal/parser/planparserv2/plan_parser_v2.go
  internal/parser/planparserv2/plan_parser_v2_test.go
  internal/parser/planparserv2/utils.go
  internal/proto/plan.proto
  internal/proto/planpb/plan.pb.go
  pkg/util/typeutil/schema.go
  tests/integration/json_expr_test.go
Labels: kind/improvement, sig/testing, size/XXL, approved, lgtm, area/test, ci-passed, dco-passed

#23972 Optimize PrivilegeAll permission check
  internal/proxy/privilege_interceptor.go
  internal/proxy/privilege_interceptor_test.go
  internal/proxy/util_test.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#23956 Support aliyun OSS for chunk manager (#22663) (#22842)
  internal/core/src/storage/AliyunCredentialsProvider.cpp
  internal/core/src/storage/AliyunCredentialsProvider.h
  internal/core/src/storage/AliyunSTSClient.cpp
  internal/core/src/storage/AliyunSTSClient.h
  internal/core/src/storage/CMakeLists.txt
  internal/core/src/storage/MinioChunkManager.cpp
  internal/core/src/storage/MinioChunkManager.h
Labels: size/XL, approved, lgtm, dco-passed, area/compilation

#23913 Can only use the topic in the list when preCreatedTopicEnabled
  internal/rootcoord/dml_channels.go
  internal/rootcoord/dml_channels_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#23996 [2.2.x] Execute set -e after source setenv.sh
  scripts/run_go_codecov.sh
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#23995 Update test case
  tests/python_client/testcases/test_index.py
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#23949 Support aliyun oss as object storage with ak or IAM
  configs/milvus.yaml
  go.mod
  go.sum
  internal/storage/aliyun/aliyun.go
  internal/storage/aliyun/aliyun_test.go
  internal/storage/aliyun/mocks/Credential.go
  internal/storage/minio_chunk_manager.go
  internal/util/paramtable/service_param.go
Labels: area/dependency, size/XL, approved, lgtm, ci-passed, dco-passed

#23974 Execute set -e after source setenv.sh
  scripts/run_go_codecov.sh
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#24013 Add collection level auto compaction enabled config
  Makefile
  internal/datacoord/compaction_trigger.go
  internal/datacoord/compaction_trigger_test.go
  internal/datacoord/handler.go
  internal/datacoord/mock_compaction_plan_context.go
  internal/datacoord/mock_handler.go
  internal/datacoord/util.go
  internal/datacoord/util_test.go
  pkg/common/common.go
Labels: kind/enhancement, size/XL, approved, lgtm, ci-passed, dco-passed, area/compilation

#24018 Fix Integration test for bulk insert
  tests/integration/bulkinsert_test.go
  tests/integration/util_index.go
Labels: kind/improvement, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed, manual-pass

#24001 Modify test cases
  tests/python_client/testcases/test_collection.py
  tests/python_client/testcases/test_compaction.py
  tests/python_client/testcases/test_index.py
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#24025 Fix redundant comment that cause dev container build failed
  docker-compose.yml
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#24020 Trigger main workflow when integration test changed
  .github/workflows/main.yaml
  tests/integration/OWNERS
Labels: kind/improvement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#24003 Fix panic while balancing releasing collection
  internal/querycoordv2/checkers/balance_checker.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#24031 Make data node start only once
  internal/datanode/data_node.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#24030 Remove extra log
  internal/rootcoord/dml_channels.go
Labels: kind/bug, kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#24016 Support expr with json field (#23804)
  internal/core/src/pb/plan.pb.cc
  internal/core/src/pb/plan.pb.h
  internal/core/src/query/Expr.h
  internal/core/src/query/ExprImpl.h
  internal/core/src/query/Parser.cpp
  internal/core/src/query/PlanProto.cpp
  internal/core/src/query/PlanProto.h
  internal/core/src/query/generated/ExecExprVisitor.h
  internal/core/src/query/generated/Expr.cpp
  internal/core/src/query/generated/ExprVisitor.h
  internal/core/src/query/generated/ExtractInfoExprVisitor.h
  internal/core/src/query/generated/ShowExprVisitor.h
  internal/core/src/query/generated/VerifyExprVisitor.h
  internal/core/src/query/visitors/ExecExprVisitor.cpp
  internal/core/src/query/visitors/ExtractInfoExprVisitor.cpp
  internal/core/src/query/visitors/ShowExprVisitor.cpp
  internal/core/src/query/visitors/VerifyExprVisitor.cpp
  internal/core/unittest/test_c_api.cpp
  internal/core/unittest/test_expr.cpp
  internal/core/unittest/test_retrieve.cpp
  internal/core/unittest/test_utils/DataGen.h
  internal/parser/planparserv2/Plan.g4
  internal/parser/planparserv2/generated/Plan.interp
  internal/parser/planparserv2/generated/Plan.tokens
  internal/parser/planparserv2/generated/PlanLexer.interp
  internal/parser/planparserv2/generated/PlanLexer.tokens
  internal/parser/planparserv2/generated/plan_base_visitor.go
  internal/parser/planparserv2/generated/plan_lexer.go
  internal/parser/planparserv2/generated/plan_parser.go
  internal/parser/planparserv2/generated/plan_visitor.go
  internal/parser/planparserv2/parser_visitor.go
  internal/parser/planparserv2/plan_parser_v2.go
  internal/parser/planparserv2/plan_parser_v2_test.go
  internal/parser/planparserv2/utils.go
  internal/proto/plan.proto
  internal/proto/planpb/plan.pb.go
  internal/util/typeutil/schema.go
Labels: kind/improvement, sig/testing, size/XXL, approved, lgtm, area/test, ci-passed, dco-passed

#23968 Improve predict the resource usage
  internal/querynodev2/delegator/delegator_data.go
  internal/querynodev2/local_worker.go
  internal/querynodev2/segments/manager.go
  internal/querynodev2/segments/segment_loader.go
  internal/querynodev2/segments/segment_loader_test.go
  internal/querynodev2/server.go
  internal/querynodev2/services.go
  pkg/util/typeutil/map.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#24023 Update proto API
  go.mod
  go.sum
  internal/core/src/pb/common.pb.cc
  internal/core/src/pb/schema.pb.cc
  internal/core/src/pb/schema.pb.h
Labels: area/dependency, kind/improvement, size/XXL, approved, lgtm, ci-passed, dco-passed

#24034 Update knowhere version for new GetVectorByIds interface
  internal/core/src/index/VectorDiskIndex.cpp
  internal/core/src/index/VectorDiskIndex.h
  internal/core/src/index/VectorIndex.h
  internal/core/src/index/VectorMemIndex.cpp
  internal/core/src/index/VectorMemIndex.h
  internal/core/thirdparty/knowhere/CMakeLists.txt
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed, area/compilation

#24037 Fix integration test not wait for index built
  internal/querynodev2/server.go
  scripts/run_intergration_test.sh
  tests/integration/get_vector_test.go
  tests/integration/hello_milvus_test.go
  tests/integration/json_expr_test.go
  tests/integration/meta_watcher_test.go
  tests/integration/querynodev2_test.go
  tests/integration/range_search_test.go
  tests/integration/upsert_test.go
Labels: kind/improvement, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed, test/integration

#24046 Add trace log for datacoord
  internal/datacoord/compaction_trigger.go
  internal/datacoord/services.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#24035 Check the length of JSON
  internal/proxy/validate_util.go
  internal/proxy/validate_util_test.go
  pkg/util/paramtable/component_param.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#23717 Support SIMD of UnaryRangeExpr (#23715)
  Makefile
  internal/core/CMakeLists.txt
  internal/core/src/common/Types.h
  internal/core/src/index/ScalarIndex-inl.h
  internal/core/src/index/ScalarIndex.h
  internal/core/src/index/ScalarIndexSort-inl.h
  internal/core/src/index/ScalarIndexSort.h
  internal/core/src/index/StringIndex.h
  internal/core/src/index/StringIndexMarisa.cpp
  internal/core/src/index/StringIndexMarisa.h
  internal/core/src/index/StringIndexSort.h
  internal/core/src/query/PlanProto.cpp
  internal/core/src/query/generated/ExecExprVisitor.h
  internal/core/src/query/visitors/ExecExprVisitor.cpp
  internal/core/unittest/test_bitmap.cpp
  internal/core/unittest/test_bool_index.cpp
  internal/core/unittest/test_c_api.cpp
  internal/core/unittest/test_expr.cpp
  internal/core/unittest/test_string_index.cpp
  internal/core/unittest/test_utils/AssertUtils.h
  internal/core/unittest/test_utils/DataGen.h
  scripts/core_build.sh
Labels: size/XXL, approved, lgtm, ci-passed, dco-passed, area/compilation

#24009 enable global static rate limit
  internal/proxy/multi_rate_limiter.go
  internal/proxy/multi_rate_limiter_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#24015 Enable global static limit
  internal/proxy/multi_rate_limiter.go
  internal/proxy/multi_rate_limiter_test.go
Labels: kind/bug, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#24057 fix qc coordinator retry policy
  internal/querycoordv2/meta/coordinator_broker.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#24058 fix qc coordinator retry policy
  internal/querycoordv2/meta/coordinator_broker.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#24070 Fix panic while balancing releasing collection (#24003)
  internal/querycoordv2/checkers/balance_checker.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#24073 Add Statistic entity id log for datacoord
  internal/datacoord/services.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#24012 enable config collection level rate limit
  configs/milvus.yaml
  internal/proxy/multi_rate_limiter.go
  internal/proxy/multi_rate_limiter_test.go
  internal/rootcoord/quota_center.go
  internal/rootcoord/quota_center_test.go
  pkg/util/paramtable/quota_param.go
  pkg/util/paramtable/quota_param_test.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#24033 Replace num_entities with count(*) in some test cases
  tests/python_client/testcases/test_delete.py
  tests/python_client/testcases/test_insert.py
Labels: sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#24059 Fix panic caused by wrong logic of getting unindexed segments (#24044)
  internal/datacoord/handler.go
  internal/datacoord/server_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed

#24085 Fix aws-c-sdkutils
  internal/core/conanfile.py
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#23781 Support SIMD of several Expr (#23715)
  Makefile
  internal/core/CMakeLists.txt
  internal/core/src/common/Types.h
  internal/core/src/index/ScalarIndex-inl.h
  internal/core/src/index/ScalarIndex.h
  internal/core/src/index/ScalarIndexSort-inl.h
  internal/core/src/index/ScalarIndexSort.h
  internal/core/src/index/StringIndex.h
  internal/core/src/index/StringIndexMarisa.cpp
  internal/core/src/index/StringIndexMarisa.h
  internal/core/src/index/StringIndexSort.h
  internal/core/src/query/PlanProto.cpp
  internal/core/src/query/generated/ExecExprVisitor.h
  internal/core/src/query/visitors/ExecExprVisitor.cpp
  internal/core/unittest/test_bitmap.cpp
  internal/core/unittest/test_bool_index.cpp
  internal/core/unittest/test_c_api.cpp
  internal/core/unittest/test_expr.cpp
  internal/core/unittest/test_string_index.cpp
  internal/core/unittest/test_utils/AssertUtils.h
  internal/core/unittest/test_utils/DataGen.h
  scripts/core_build.sh
Labels: size/XXL, approved, lgtm, ci-passed, dco-passed, area/compilation

#24062 Support access json key without quotation marks
  internal/parser/planparserv2/Plan.g4
  internal/parser/planparserv2/generated/PlanLexer.interp
  internal/parser/planparserv2/generated/plan_lexer.go
  internal/parser/planparserv2/plan_parser_v2_test.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#24054 [test]Add bin flat index for deploy test
  tests/python_client/deploy/scripts/utils.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#24055 [test]Add bin flat index for deploy test
  tests/python_client/deploy/scripts/utils.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#23992 Add test cases of load and other functions
  tests/python_client/check/func_check.py
  tests/python_client/testcases/test_collection.py
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/XXL, approved, lgtm, area/test, ci-passed, dco-passed

#24096 fix rate limit ut
  internal/proxy/multi_rate_limiter_test.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#24086 Update pymilvus version
  tests/python_client/requirements.txt
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#24087 Update pymilvus version
  tests/python_client/requirements.txt
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#24049 Fix the error when a role removes an already deleted user
  internal/proxy/proxy_test.go
  internal/rootcoord/root_coord.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed

#24063 Fix integration tests logic
  .github/workflows/main.yaml
  pkg/util/gc/gc_tuner.go
  pkg/util/paramtable/base_table.go
  tests/integration/bulkinsert_test.go
  tests/integration/get_index_statistics_test.go
  tests/integration/meta_watcher.go
  tests/integration/minicluster.go
Labels: kind/improvement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, manual-pass, test/integration

#24089 revert query_coord proto
  internal/proto/query_coord.proto
  internal/proto/querypb/query_coord.pb.go
Labels: size/L, approved, lgtm, ci-passed, area/internal-api, dco-passed

#24038 Fix the `not shard leader` error when gracefully stopping
  internal/proxy/task_search.go
  internal/proxy/task_search_test.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#24095 fix rate limit ut
  internal/proxy/multi_rate_limiter_test.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#23448 Support Default Value
  internal/proxy/task_insert_test.go
  internal/proxy/task_upsert.go
  internal/proxy/task_upsert_test.go
  internal/proxy/util.go
  internal/proxy/util_test.go
  internal/proxy/validate_util.go
  internal/proxy/validate_util_test.go
  internal/rootcoord/create_collection_task.go
  internal/rootcoord/create_collection_task_test.go
Labels: area/dependency, size/XXL, approved, lgtm, ci-passed, area/internal-api, dco-passed

#24107 Fix metric QueryCoordNumCollections (#24053)
  internal/querycoordv2/job/job_load.go
  internal/querycoordv2/meta/collection_manager.go
  internal/querycoordv2/server.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed

#24108 Fix standalone upgrade chaos
  internal/querycoordv2/server.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#24122 [test]Add index params for bin_flat
  tests/python_client/deploy/scripts/utils.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#23771 Fix session stop/goingStop stuck after connection lost
  internal/util/sessionutil/session_util.go
  internal/util/sessionutil/session_util_test.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#24119 Fix querynode consume ts lag metrics
  internal/querynodev2/pipeline/filter_node.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#24109 Fix the error when a role removes an already deleted user (#24049)
  internal/proxy/proxy_test.go
  internal/rootcoord/root_coord.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed

#23718 Support configurable policy for query node, Add user level schedule policy
  configs/milvus.yaml
  internal/metrics/querynode_metrics.go
  internal/proxy/privilege_interceptor_test.go
  internal/proxy/proxy_rpc_test.go
  internal/proxy/proxy_test.go
  internal/proxy/task_query.go
  internal/proxy/task_search.go
  internal/proxy/util_test.go
  internal/querynode/impl.go
  internal/querynode/scheduler_policy.go
  internal/querynode/scheduler_policy_test.go
  internal/querynode/shard_cluster.go
  internal/querynode/task_scheduler.go
  internal/querynode/task_scheduler_test.go
  internal/util/constant.go
  internal/util/contextutil/context_util.go
  internal/util/contextutil/context_util_test.go
  internal/util/paramtable/component_param.go
Labels: size/XL, approved, lgtm, ci-passed, dco-passed

#24131 [Cherry-Pick] Fix session stop/goingStop stuck after connection lost
  internal/util/sessionutil/session_util.go
  internal/util/sessionutil/session_util_test.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#24127 Fix data race in pipeline/manager
  internal/querynodev2/pipeline/manager.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#24148 [skip e2e]handle error when exporting log
  tests/scripts/export_log_k8s.sh
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#24126 Fix insert node doesn't handle JSON data while merging
  internal/querynodev2/pipeline/insert_node.go
  internal/querynodev2/pipeline/insert_node_test.go
  pkg/util/typeutil/schema.go
  pkg/util/typeutil/schema_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#24113 Json key must be enclosed in double quotes
  internal/parser/planparserv2/Plan.g4
  internal/parser/planparserv2/generated/PlanLexer.interp
  internal/parser/planparserv2/generated/plan_lexer.go
  internal/parser/planparserv2/parser_visitor.go
  internal/parser/planparserv2/plan_parser_v2_test.go
  internal/parser/planparserv2/pool_test.go
  pkg/util/typeutil/schema.go
  tests/integration/json_expr_test.go
Labels: area/dependency, kind/improvement, sig/testing, size/XL, approved, lgtm, area/test, ci-passed, dco-passed, test/integration

#24141 Fix get vector it timeout and improve some string const usage
  internal/datacoord/compaction_trigger_test.go
  internal/datacoord/index_builder_test.go
  internal/datacoord/index_meta_test.go
  internal/datacoord/index_service_test.go
  internal/datacoord/mock_test.go
  internal/datacoord/segment_allocation_policy_test.go
  internal/datacoord/util.go
  internal/datanode/buffer_test.go
  internal/datanode/compactor_test.go
  internal/datanode/mock_test.go
  internal/indexnode/indexnode_service_test.go
  internal/indexnode/indexnode_test.go
  internal/indexnode/task.go
  internal/metastore/kv/rootcoord/kv_catalog_test.go
  internal/proxy/get_max_len.go
  internal/proxy/get_max_len_test.go
  internal/proxy/proxy_test.go
  internal/proxy/task.go
  internal/proxy/task_index.go
  internal/proxy/task_index_test.go
  internal/proxy/task_test.go
  internal/proxy/util.go
  internal/proxy/util_test.go
  internal/proxy/validate_util_test.go
  internal/querynodev2/delegator/delegator_data_test.go
  internal/querynodev2/delegator/delegator_test.go
  internal/querynodev2/segments/mock_data.go
  internal/querynodev2/segments/segment_loader.go
  internal/querynodev2/segments/utils.go
  internal/storage/index_data_codec_test.go
  internal/storage/print_binlog_test.go
  internal/storage/utils.go
  internal/storage/utils_test.go
  internal/util/importutil/import_util.go
  internal/util/importutil/import_util_test.go
  internal/util/importutil/import_wrapper_test.go
  internal/util/importutil/json_handler_test.go
  internal/util/importutil/json_parser_test.go
  internal/util/importutil/numpy_parser_test.go
  internal/util/indexcgowrapper/codec_index_test.go
  internal/util/indexcgowrapper/index_test.go
  internal/util/typeutil/result_helper_test.go
  pkg/common/common.go
  pkg/util/constant.go
  pkg/util/indexparamcheck/constraints.go
  pkg/util/indexparams/disk_index_params.go
  pkg/util/indexparams/disk_index_params_test.go
  pkg/util/typeutil/get_dim.go
  pkg/util/typeutil/kv_pair_helper_test.go
  pkg/util/typeutil/schema.go
  pkg/util/typeutil/schema_test.go
  tests/integration/bulkinsert_test.go
  tests/integration/get_vector_test.go
  tests/integration/json_expr_test.go
  tests/integration/meta_watcher_test.go
  tests/integration/util_index.go
  tests/integration/util_query.go
Labels: kind/improvement, sig/testing, size/XL, approved, lgtm, area/test, ci-passed, dco-passed, test/integration

#24137 [test]Skip compact check
  tests/python_client/chaos/testcases/test_concurrent_operation.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#24160 [skip e2e]remove binary flat index type
  tests/python_client/deploy/scripts/utils.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#24159 [skip e2e]remove binary flat index type
  tests/python_client/deploy/scripts/utils.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#24134 Fix rocksmq retention no trigger at datacoord timetick channel
  internal/mq/mqimpl/rocksmq/client/client_impl.go
  internal/mq/mqimpl/rocksmq/server/rocksmq_impl.go
  internal/mq/mqimpl/rocksmq/server/rocksmq_retention.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed

#24142 Check overflow for inserted integer
  internal/proxy/task_insert.go
  internal/proxy/task_upsert.go
  internal/proxy/validate_util.go
  internal/proxy/validate_util_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#24117 Add test case and function check about search/query output
  tests/python_client/check/func_check.py
  tests/python_client/common/common_func.py
  tests/python_client/testcases/test_query.py
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#24121 Support rate limit based on growing segments size
  configs/milvus.yaml
  internal/querynodev2/metrics_info.go
  internal/rootcoord/quota_center.go
  internal/rootcoord/quota_center_test.go
  pkg/util/metricsinfo/quota_metric.go
  pkg/util/paramtable/quota_param.go
  pkg/util/paramtable/quota_param_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#24129 Improve the metric of binlog size to the level of collection and segment (#23859)
  internal/datacoord/meta.go
  internal/metrics/datacoord_metrics.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#24079 Move release collection metrics to job
  internal/querycoordv2/job/job_release.go
  internal/querycoordv2/services.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#24162 Change output fields with star behavior
  internal/proxy/task_test.go
  internal/proxy/util.go
  tests/python_client/testcases/test_delete.py
  tests/python_client/testcases/test_query.py
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#24172 Check overflow for inserted integer (#24142)
  internal/proxy/task_insert.go
  internal/proxy/validate_util.go
  internal/proxy/validate_util_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#24152 fix deny writing use wrong errcode
  internal/rootcoord/quota_center.go
  internal/rootcoord/quota_center_test.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed

#24125 Fix typo in handler.go
  internal/datacoord/handler.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#24174 Change output fields with star behavior
  internal/proxy/task_test.go
  internal/proxy/util.go
  tests/python_client/testcases/test_delete.py
  tests/python_client/testcases/test_query.py
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#24167 Add ut for partition key
  internal/mq/msgstream/mq_msgstream_test.go
  internal/mq/msgstream/msg.go
  internal/proxy/task.go
  internal/proxy/task_insert.go
  internal/proxy/task_test.go
  internal/proxy/util.go
  internal/rootcoord/create_collection_task_test.go
  internal/util/flowgraph/message_test.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#24147 fix alter collection merge multi props policy
  internal/rootcoord/alter_collection_task.go
  internal/rootcoord/alter_collection_task_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#24103 support try-best reducer methods(#24075)
  internal/proto/internal.proto
  internal/proto/internalpb/internal.pb.go
  internal/proxy/reducer.go
  internal/proxy/reducer_test.go
  internal/proxy/task.go
  internal/proxy/task_query.go
  internal/proxy/task_query_test.go
  internal/querynodev2/segments/default_limit_reducer.go
  internal/querynodev2/segments/reducer.go
  internal/querynodev2/segments/reducer_test.go
Labels: size/L, approved, lgtm, ci-passed, area/internal-api, dco-passed

#24151 Fix compaction doesn't support JSON data
  internal/datanode/compactor.go
  internal/datanode/compactor_test.go
  pkg/util/typeutil/schema.go
  pkg/util/typeutil/schema_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#24112 Fix dynamic partitions loading
  internal/proto/query_coord.proto
  internal/proto/querypb/query_coord.pb.go
  internal/querycoordv2/job/job_load.go
  internal/querycoordv2/job/job_release.go
  internal/querycoordv2/job/job_sync.go
  internal/querycoordv2/job/job_test.go
  internal/querycoordv2/job/undo.go
  internal/querycoordv2/job/utils.go
  internal/querycoordv2/services.go
  internal/querycoordv2/services_test.go
  internal/querycoordv2/task/task_test.go
  internal/querycoordv2/task/utils.go
  internal/querynodev2/segments/collection.go
  internal/querynodev2/services.go
  internal/querynodev2/services_test.go
  internal/rootcoord/broker.go
Labels: kind/bug, size/XXL, approved, lgtm, ci-passed, area/internal-api, dco-passed

#24176 Support dynamic schema for create collection
  go.mod
  go.sum
  internal/core/src/pb/schema.pb.cc
  internal/core/src/pb/schema.pb.h
  internal/metastore/model/collection.go
  internal/metastore/model/field.go
  internal/parser/planparserv2/Plan.g4
  internal/parser/planparserv2/generated/PlanLexer.interp
  internal/parser/planparserv2/generated/plan_lexer.go
  internal/parser/planparserv2/plan_parser_v2_test.go
  internal/proxy/meta_cache.go
  internal/proxy/plan_parser_test.go
  internal/proxy/task.go
  internal/proxy/task_index.go
  internal/proxy/task_index_test.go
  internal/proxy/task_insert.go
  internal/proxy/task_insert_test.go
  internal/proxy/task_test.go
  internal/proxy/util.go
  internal/rootcoord/create_collection_task.go
  internal/rootcoord/field_id.go
  internal/rootcoord/root_coord.go
  pkg/common/common.go
  pkg/go.mod
  pkg/go.sum
  pkg/util/typeutil/schema.go
  tests/integration/json_expr_test.go
  tests/integration/util_schema.go
Labels: area/dependency, kind/improvement, sig/testing, size/XXL, approved, lgtm, area/test, ci-passed, dco-passed, test/integration

#24180 Fix flat index can be created with invalid metric type
  pkg/util/indexparamcheck/conf_adapter_mgr.go
  pkg/util/indexparamcheck/conf_adapter_mgr_test.go
  pkg/util/indexparamcheck/flat_checker.go
  pkg/util/indexparamcheck/flat_checker_test.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#24181 Fix flat index can be created with invalid metric type (#24180)
  internal/util/indexparamcheck/conf_adapter_mgr.go
  internal/util/indexparamcheck/conf_adapter_mgr_test.go
  internal/util/indexparamcheck/flat_checker.go
  internal/util/indexparamcheck/flat_checker_test.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#24188 fix deny writing use wrong errcode
  internal/rootcoord/quota_center.go
  internal/rootcoord/quota_center_test.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed, manual-pass
