Repository milvus-io/milvus, pull requests merged in 2023-09, with the labels that each got.

#26746 Optimize loading by reduce 1x copy while reading data
  internal/core/src/storage/FieldData.cpp
  internal/core/src/storage/FieldDataInterface.h
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#26724 [test]Add method to analyze chaos test result
  tests/benchmark/requirements.txt
  tests/python_client/chaos/checker.py
  tests/python_client/chaos/conftest.py
  tests/python_client/chaos/constants.py
  tests/python_client/chaos/requirements.txt
  tests/python_client/chaos/test_chaos_apply.py
  tests/python_client/chaos/testcases/test_concurrent_operation.py
  tests/python_client/chaos/testcases/test_single_request_operation.py
  tests/python_client/deploy/requirements.txt
  tests/python_client/requirements.txt
  tests/python_client/utils/util_common.py
  tests/restful_client/requirements.txt
Labels: kind/improvement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#26761 Fix LoadSegmentLatency metric p99
  internal/querynodev2/segments/segment_loader.go
  pkg/metrics/querynode_metrics.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#26773 Remove merr mask logic
  internal/distributed/proxy/httpserver/handler_v1.go
  internal/distributed/proxy/httpserver/utils.go
  pkg/util/merr/errors.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#26775 remove pull target from qc recover
  internal/querycoordv2/checkers/channel_checker.go
  internal/querycoordv2/checkers/channel_checker_test.go
  internal/querycoordv2/checkers/controller_test.go
  internal/querycoordv2/checkers/segment_checker.go
  internal/querycoordv2/checkers/segment_checker_test.go
  internal/querycoordv2/observers/collection_observer.go
  internal/querycoordv2/observers/leader_observer.go
  internal/querycoordv2/observers/leader_observer_test.go
  internal/querycoordv2/observers/target_observer.go
  internal/querycoordv2/server.go
  internal/querycoordv2/server_test.go
  internal/querycoordv2/services_test.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#26759 refine checker code style
  internal/querycoordv2/checkers/channel_checker.go
  internal/querycoordv2/checkers/segment_checker.go
  internal/querycoordv2/meta/target_manager.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#26783 Remove log.Error(err.error())-style log
  internal/datacoord/server_test.go
  internal/datanode/data_node_test.go
  internal/datanode/flow_graph_delete_node.go
  internal/datanode/flow_graph_insert_buffer_node.go
  internal/distributed/datacoord/client/client_test.go
  internal/distributed/querycoord/client/client_test.go
  internal/distributed/rootcoord/client/client_test.go
  internal/http/server_test.go
  internal/indexnode/indexnode.go
  internal/proxy/channels_mgr.go
  internal/proxy/meta_cache_test.go
  internal/querycoordv2/server_test.go
  internal/querynodev2/collector/collector.go
  internal/querynodev2/pipeline/filter_node.go
  internal/querynodev2/services.go
  internal/rootcoord/import_manager.go
  pkg/log/log.go
  pkg/util/hardware/hardware_info.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#26769 Accelerate flush in flushAll
  internal/proxy/impl.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#26763 Fix failed to load collection with more than 128 partitions
  internal/metastore/kv/querycoord/kv_catalog.go
  internal/querycoordv2/job/job_load.go
  internal/querycoordv2/job/job_release.go
  internal/querycoordv2/job/undo.go
  internal/querycoordv2/meta/collection_manager.go
  internal/querycoordv2/meta/collection_manager_test.go
  internal/querycoordv2/observers/collection_observer.go
  internal/querycoordv2/services_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#26808 fix panic due to empty trace ID(#issue-26754)
  internal/core/src/common/Tracer.cpp
  internal/core/src/common/Tracer.h
  internal/core/src/segcore/segment_c.cpp
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#26709 Add rate limit ratio monitoring
  internal/rootcoord/quota_center.go
  pkg/metrics/rootcoord_metrics.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#26788 Improve rated log in insertBufferNode
  internal/datanode/flow_graph_insert_buffer_node.go
  internal/rootcoord/quota_center.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#26791 [Fixup] remove nats from default
  configs/milvus.yaml
  internal/util/dependency/factory.go
  internal/util/dependency/factory_test.go
Labels: area/dependency, size/XS, approved, lgtm, ci-passed, dco-passed

#26778 [Cherry-Pick] Refine standalone components stop order (#26742)
  cmd/roles/roles.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#26713 Merge syncCPLagTooBehind policy into syncPeriodically policy
  internal/datanode/channel_meta.go
  internal/datanode/data_sync_service_test.go
  internal/datanode/flow_graph_insert_buffer_node.go
  internal/datanode/flow_graph_insert_buffer_node_test.go
  internal/datanode/segment.go
  internal/datanode/segment_sync_policy.go
  internal/datanode/segment_sync_policy_test.go
  internal/datanode/services.go
  pkg/util/paramtable/component_param.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#26776 Increase minio log level to avoid unnecessary log
  configs/milvus.yaml
  pkg/util/paramtable/base_table.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#26822 Fix bug for get index state with compaction segment
  internal/datacoord/compaction.go
  internal/datacoord/index_service.go
  internal/datacoord/meta.go
  internal/datacoord/meta_test.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#26676 Refine error message for json length exceed max length
  internal/proxy/validate_util.go
  internal/proxy/validate_util_test.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#26728 stop heartbeat if reach heartbeat limit
  configs/milvus.yaml
  internal/proxy/look_aside_balancer.go
  internal/proxy/look_aside_balancer_test.go
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/component_param_test.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#26835 Add ctx parameter for organizeTask and GetWorker method
  internal/querynodev2/cluster/manager.go
  internal/querynodev2/cluster/manager_test.go
  internal/querynodev2/cluster/mock_manager.go
  internal/querynodev2/delegator/delegator.go
  internal/querynodev2/delegator/delegator_data.go
  internal/querynodev2/delegator/delegator_data_test.go
  internal/querynodev2/delegator/delegator_test.go
  internal/querynodev2/server.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#26823 [test]Refine chaos apply
  .pre-commit-config.yaml
  tests/python_client/chaos/checker.py
  tests/python_client/utils/util_common.py
Labels: kind/improvement, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#26804 add case about diskann and binary index
  tests/python_client/testcases/test_index.py
  tests/python_client/testcases/test_query.py
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#26842 Update CONTRIBUTING.md for mockery generation
  CONTRIBUTING.md
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#26843 Add build-cpp and setenv for querynode mockery regen command
  Makefile
  internal/datanode/allocator/mock_allocator.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed, area/compilation

#26847 [skip e2e]Add wait time when verifying the chaos is deleted
  tests/python_client/chaos/test_chaos_apply.py
Labels: kind/improvement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#26845 Use specified mockery & golangci-lint version
  Makefile
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed, area/compilation

#26839 Refactor storage.MergeInsertData() to optimize data merge
  internal/datanode/flow_graph_insert_buffer_node.go
  internal/storage/utils.go
  internal/storage/utils_test.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#26802 Enhance FlushAll/GetFlushAllState API
  go.mod
  go.sum
  internal/datacoord/server_test.go
  internal/datacoord/services.go
  internal/proxy/impl.go
  internal/proxy/impl_test.go
Labels: area/dependency, size/L, approved, lgtm, ci-passed, dco-passed

#26810 fix dc standby to active
  internal/datacoord/server.go
  internal/util/sessionutil/session_util.go
  internal/util/sessionutil/session_util_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#26867 [test]Fix occasional FileExistsError triggered when concurrently executing pytest
  tests/python_client/config/log_config.py
Labels: kind/improvement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#26865 Fix misuse of waitgroup in metrics mutex ut
  pkg/util/lock/metrics_mutex_test.go
Labels: kind/improvement, size/XS, approved, lgtm, dco-passed

#26818 fix false load failure for long unserviable period(#26813)
  internal/querynodev2/delegator/delegator.go
  internal/querynodev2/segments/segment_loader.go
  internal/querynodev2/services.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#26873 [test]Update chaos apply and chaos scope
  tests/python_client/chaos/checker.py
  tests/python_client/chaos/conftest.py
  tests/python_client/chaos/test_chaos_apply.py
  tests/python_client/chaos/test_chaos_apply_to_determined_pod.py
Labels: kind/improvement, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#26864 Fix embedded milvus log bug
  internal/core/src/config/ConfigKnowhere.cpp
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#26870 Workaround fix ChannelManager holding mutex too long
  internal/datacoord/handler.go
Labels: size/S, dco-passed

#26670 Fix retrieving may return more result than limit
  internal/core/src/segcore/InsertRecord.h
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#26882 [skip e2e] Fix mergify rules for unit test file changed under pkg folder
  .github/mergify.yml
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#26878 Should set index task retry not failed when task canceled
  internal/indexnode/task_scheduler.go
  internal/indexnode/task_scheduler_test.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed

#26872 update test cases
  tests/python_client/testcases/test_collection.py
  tests/python_client/testcases/test_delete.py
  tests/python_client/testcases/test_insert.py
  tests/python_client/testcases/test_utility.py
Labels: sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#26874 Workaround fix ChannelManager holding mutex too long (#26870)
  internal/datacoord/handler.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#26881 Refine delegator lifetime control
  internal/querynodev2/delegator/delegator.go
  internal/querynodev2/delegator/delegator_test.go
  pkg/util/lifetime/lifetime.go
  pkg/util/lifetime/safe_chan.go
  pkg/util/lifetime/safe_chan_test.go
  pkg/util/typeutil/chan.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#26889 Upgrade Knowhere to 2.2.1
  internal/core/thirdparty/knowhere/CMakeLists.txt
Labels: kind/improvement, size/XS, approved, lgtm, dco-passed, area/compilation

#26896 [skip e2e] Use same mergify rule for branch 2.3.0
  .github/mergify.yml
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#26883 [skip e2e] Fix amazonlinux cache not work
  .env
  .github/workflows/code-checker.yaml
  build/builder.sh
  build/docker/builder/cpu/amazonlinux2023/Dockerfile
  build/docker/builder/cpu/ubuntu20.04/Dockerfile
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#26902 Bump semver to 2.3.1
  pkg/common/version.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed, kind/branch-feature

#26911 [skip e2e]Add python script to get image tag name
  tests/scripts/get_image_tag_by_short_name.py
Labels: kind/improvement, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#26919 [skip e2e]Refine the script of getting image tag
  tests/scripts/get_image_tag_by_short_name.py
Labels: kind/improvement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#26910 Avoid the panic when the status of rpc response is nil
  internal/datacoord/index_service.go
  internal/datacoord/services.go
  internal/querycoordv2/services.go
  internal/rootcoord/root_coord.go
  internal/util/grpcclient/client.go
  internal/util/grpcclient/client_test.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#26912 Avoid the panic when the status of rpc response is nil
  internal/datacoord/index_service.go
  internal/datacoord/services.go
  internal/querycoordv2/services.go
  internal/rootcoord/root_coord.go
  internal/util/grpcclient/client.go
  internal/util/grpcclient/client_test.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#26686 Add timeout in dispatcher, AsConsumer and Seek
  Makefile
  internal/datacoord/compaction_trigger_test.go
  internal/datacoord/server.go
  internal/datacoord/server_test.go
  internal/datanode/data_sync_service.go
  internal/datanode/flow_graph_delete_node.go
  internal/datanode/flow_graph_dmstream_input_node.go
  internal/datanode/flow_graph_dmstream_input_node_test.go
  internal/datanode/flow_graph_insert_buffer_node.go
  internal/distributed/proxy/service.go
  internal/mq/msgstream/mqwrapper/rmq/rmq_client.go
  internal/mq/msgstream/mqwrapper/rmq/rocksmq_msgstream_test.go
  internal/proxy/mock_test.go
  internal/querynodev2/delegator/delegator_data.go
  internal/querynodev2/delegator/delegator_data_test.go
  internal/querynodev2/pipeline/manager_test.go
  internal/querynodev2/pipeline/pipeline_test.go
  internal/querynodev2/services_test.go
  internal/rootcoord/dml_channels.go
  internal/rootcoord/dml_channels_test.go
  internal/util/flowgraph/input_node_test.go
  internal/util/flowgraph/node_test.go
  internal/util/pipeline/stream_pipeline.go
  internal/util/pipeline/stream_pipeline_test.go
  pkg/eventlog/mock_logger.go
  pkg/go.mod
  pkg/mq/msgdispatcher/client.go
  pkg/mq/msgdispatcher/client_test.go
  pkg/mq/msgdispatcher/dispatcher.go
  pkg/mq/msgdispatcher/dispatcher_test.go
  pkg/mq/msgdispatcher/manager.go
  pkg/mq/msgdispatcher/manager_test.go
  pkg/mq/msgdispatcher/mock_client.go
  pkg/mq/msgdispatcher/mock_test.go
  pkg/mq/msgstream/common_mq_factory.go
  pkg/mq/msgstream/factory_stream_test.go
  pkg/mq/msgstream/factory_test.go
  pkg/mq/msgstream/mock_mq_factory.go
  pkg/mq/msgstream/mock_msgstream.go
  pkg/mq/msgstream/mq_factory.go
  pkg/mq/msgstream/mq_factory_test.go
  pkg/mq/msgstream/mq_kafka_msgstream_test.go
  pkg/mq/msgstream/mq_msgstream.go
  pkg/mq/msgstream/mq_msgstream_test.go
  pkg/mq/msgstream/mqwrapper/kafka/kafka_client.go
  pkg/mq/msgstream/mqwrapper/kafka/kafka_client_test.go
  pkg/mq/msgstream/mqwrapper/nmq/nmq_client.go
  pkg/mq/msgstream/mqwrapper/nmq/nmq_client_test.go
  pkg/mq/msgstream/msgstream.go
  pkg/mq/msgstream/stream_bench_test.go
  pkg/util/retry/retry.go
  pkg/util/retry/retry_test.go
Labels: area/dependency, size/XXL, approved, lgtm, ci-passed, dco-passed, area/compilation

#26918 [skip e2e] Forbid returning merr directly
  .golangci.yml
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#26926 Fix segment loader return false success
  internal/querynodev2/segments/segment_loader.go
  internal/querynodev2/segments/segment_loader_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed, PR | need cherry-pick

#26927 Fix indexnode log
  internal/indexnode/indexnode_service.go
Labels: kind/bug, kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#26940 Handle nil status in `merr.OK`
  pkg/util/merr/utils.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#26953 Fix checker using default interval after manual check
  internal/querycoordv2/checkers/controller.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed, PR | need cherry-pick

#26933 Fix amazonlinux cache not work (#26883)
  .env
  .github/workflows/code-checker.yaml
  build/builder.sh
  build/docker/builder/cpu/amazonlinux2023/Dockerfile
  build/docker/builder/cpu/ubuntu20.04/Dockerfile
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#26931 Remove segment to LocalSegment type assertion
  internal/querynodev2/segments/manager.go
  internal/querynodev2/segments/mock_segment.go
  internal/querynodev2/segments/reduce_test.go
  internal/querynodev2/segments/retrieve.go
  internal/querynodev2/segments/retrieve_test.go
  internal/querynodev2/segments/search.go
  internal/querynodev2/segments/search_test.go
  internal/querynodev2/segments/segment.go
  internal/querynodev2/segments/segment_interface.go
  internal/querynodev2/segments/segment_loader.go
  internal/querynodev2/segments/segment_test.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#26951 Fix typo in comment
  internal/proxy/impl.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#26959 Fix querynodev2 concurrent load logic
  internal/querynodev2/delegator/delegator.go
  internal/querynodev2/delegator/delegator_data.go
  internal/querynodev2/segments/segment_loader.go
  internal/querynodev2/segments/segment_loader_test.go
  internal/querynodev2/services_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#26944 fix unstable checker id due to go map iteration(#26943)
  internal/querycoordv2/checkers/controller.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#26963 Cherry-pick query related logic and code refine
  internal/querycoordv2/checkers/controller.go
  internal/querycoordv2/checkers/segment_checker.go
  internal/querynodev2/delegator/delegator.go
  internal/querynodev2/delegator/delegator_data.go
  internal/querynodev2/segments/manager.go
  internal/querynodev2/segments/mock_segment.go
  internal/querynodev2/segments/reduce_test.go
  internal/querynodev2/segments/retrieve.go
  internal/querynodev2/segments/retrieve_test.go
  internal/querynodev2/segments/search.go
  internal/querynodev2/segments/search_test.go
  internal/querynodev2/segments/segment.go
  internal/querynodev2/segments/segment_interface.go
  internal/querynodev2/segments/segment_loader.go
  internal/querynodev2/segments/segment_loader_test.go
  internal/querynodev2/segments/segment_test.go
  internal/querynodev2/services_test.go
Labels: kind/bug, kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#26962 Set task reason for collection released
  internal/querycoordv2/checkers/segment_checker.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#26946 [Cherry-Pick] Handle nil status in `merr.OK` (#26940)
  pkg/util/merr/utils.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#26986 [test]Update health_checkers assertion for standby test
  tests/python_client/chaos/testcases/test_single_request_operation_for_standby.py
  tests/python_client/utils/util_k8s.py
Labels: kind/improvement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#26990 [skip e2e]Increase the chaos duration for chaos test
  tests/python_client/chaos/conftest.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#26993 Remove config content output before credential mask implemented
  pkg/util/paramtable/base_table.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#26987 Refine `NewNmqClient` logic with nats.CustomDialer option
  pkg/mq/msgstream/mqwrapper/nmq/nmq_client.go
  pkg/mq/msgstream/mqwrapper/nmq/nmq_client_test.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#26616 Reduce copy while retrieving primary keys
  internal/core/src/segcore/SegmentGrowingImpl.cpp
  internal/core/src/segcore/SegmentSealedImpl.cpp
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#26992 Make segment loaded successful put in manager even ctx done
  internal/querynodev2/segments/segment_loader.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#26995 [Cherry-Pick] Remove config content output before credential mask implemented (#26993)
  pkg/util/paramtable/base_table.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#26977 Fix historm metrics buckets range for index
  internal/indexnode/task.go
  internal/indexnode/task_scheduler.go
  pkg/metrics/indexnode_metrics.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#26797 Improve the retry of the rpc client
  configs/milvus.yaml
  go.sum
  internal/distributed/datacoord/client/client.go
  internal/distributed/datanode/client/client.go
  internal/distributed/indexcoord/client/client.go
  internal/distributed/indexnode/client/client.go
  internal/distributed/proxy/client/client.go
  internal/distributed/querycoord/client/client.go
  internal/distributed/querynode/client/client.go
  internal/distributed/rootcoord/client/client.go
  internal/querycoordv2/meta/collection_manager.go
  internal/querycoordv2/meta/coordinator_broker.go
  internal/querycoordv2/server.go
  internal/querycoordv2/server_test.go
  internal/rootcoord/root_coord.go
  internal/util/grpcclient/client.go
  internal/util/grpcclient/client_test.go
  internal/util/paramtable/grpc_param.go
  internal/util/paramtable/grpc_param_test.go
  internal/util/retry/retry.go
  internal/util/retry/retry_test.go
Labels: area/dependency, size/XL, approved, lgtm, ci-passed, dco-passed

#25752 support complex delete expression
  Makefile
  internal/core/src/pb/common.pb.cc
  internal/core/src/pb/common.pb.h
  internal/core/src/pb/schema.pb.cc
  internal/core/src/pb/schema.pb.h
  internal/distributed/querynode/client/client.go
  internal/distributed/querynode/client/client_test.go
  internal/distributed/querynode/service.go
  internal/distributed/querynode/service_test.go
  internal/mocks/mock_querynode.go
  internal/proto/query_coord.proto
  internal/proto/querypb/query_coord.pb.go
  internal/proxy/impl.go
  internal/proxy/mock_channels_manager.go
  internal/proxy/task_delete.go
  internal/proxy/task_delete_test.go
  internal/proxy/task_test.go
  internal/proxy/util.go
  internal/querycoordv2/mocks/mock_querynode.go
  internal/querynodev2/cluster/mock_worker.go
  internal/querynodev2/cluster/worker.go
  internal/querynodev2/cluster/worker_test.go
  internal/querynodev2/delegator/delegator.go
  internal/querynodev2/delegator/delegator_test.go
  internal/querynodev2/delegator/mock_delegator.go
  internal/querynodev2/handlers.go
  internal/querynodev2/local_worker.go
  internal/querynodev2/segments/retrieve.go
  internal/querynodev2/segments/retrieve_test.go
  internal/querynodev2/services.go
  internal/querynodev2/services_test.go
  internal/querynodev2/tasks/query_stream_task.go
  internal/querynodev2/tasks/query_task.go
  internal/types/types.go
  internal/util/mock/grpc_querynode_client.go
  internal/util/mock/grpc_stream_client.go
  internal/util/mock/querynode_client.go
  internal/util/streamrpc/mocks/mock_query_stream_segments_server.go
  internal/util/streamrpc/mocks/mock_query_stream_server.go
  internal/util/streamrpc/streamer.go
  tests/python_client/testcases/test_delete.py
Labels: sig/testing, size/XXL, approved, lgtm, area/test, ci-passed, area/internal-api, dco-passed, area/compilation

#27011 [skip e2e]Set resource for indexnode in chaos test
  .pre-commit-config.yaml
  tests/python_client/chaos/cluster-values.yaml
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#27015 Fix printing too many warnings
  internal/util/flowgraph/node.go
Labels: kind/bug, kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#27016 Enable ASAN for ut
  Makefile
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed, area/compilation

#26904 Fix wrong error codes & names
  internal/distributed/proxy/httpserver/handler_v1.go
  internal/distributed/proxy/httpserver/handler_v1_test.go
  internal/mq/mqimpl/rocksmq/server/rocksmq_impl.go
  internal/mq/mqimpl/rocksmq/server/rocksmq_impl_test.go
  pkg/mq/msgstream/mq_msgstream.go
  pkg/mq/msgstream/mqwrapper/errors.go
  pkg/mq/msgstream/mqwrapper/kafka/kafka_consumer.go
  pkg/mq/msgstream/mqwrapper/nmq/nmq_consumer.go
  pkg/mq/msgstream/mqwrapper/nmq/nmq_consumer_test.go
  pkg/mq/msgstream/mqwrapper/pulsar/pulsar_consumer.go
  pkg/util/merr/errors.go
  pkg/util/merr/errors_test.go
  pkg/util/merr/utils.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#26924 Remove MultiRemoveWithPrefix
  internal/kv/etcd/embed_etcd_kv.go
  internal/kv/etcd/embed_etcd_kv_test.go
  internal/kv/etcd/etcd_kv.go
  internal/kv/etcd/etcd_kv_test.go
  internal/kv/kv.go
  internal/kv/mem/mem_kv.go
  internal/kv/rocksdb/rocksdb_kv.go
  internal/kv/rocksdb/rocksdb_kv_test.go
  internal/kv/tikv/txn_tikv.go
  internal/kv/tikv/txn_tikv_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#27013 Refine QueryNode errors
  internal/datacoord/index_builder.go
  internal/datacoord/indexnode_manager.go
  internal/datanode/data_node.go
  internal/datanode/services.go
  internal/distributed/proxy/httpserver/handler_v1.go
  internal/distributed/proxy/service.go
  internal/proxy/impl.go
  internal/proxy/meta_cache.go
  internal/proxy/segment.go
  internal/proxy/task.go
  internal/proxy/task_index.go
  internal/proxy/task_statistic.go
  internal/proxy/timestamp.go
  internal/proxy/util.go
  internal/querynodev2/handlers.go
  internal/querynodev2/metrics_info.go
  internal/querynodev2/services.go
  internal/querynodev2/services_test.go
  internal/querynodev2/utils.go
  internal/rootcoord/broker.go
  internal/util/componentutil/componentutil.go
  pkg/util/merr/utils.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#27025 [skip e2e]Set resource for worker node in chaos test
  tests/python_client/chaos/cluster-values.yaml
Labels: kind/improvement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#26859 Flush by flush channels
  go.mod
  go.sum
  internal/datacoord/cluster.go
  internal/datacoord/mock_test.go
  internal/datacoord/server_test.go
  internal/datacoord/services.go
  internal/datacoord/session_manager.go
  internal/datanode/channel_meta.go
  internal/datanode/data_sync_service_test.go
  internal/datanode/flow_graph_insert_buffer_node.go
  internal/datanode/flow_graph_insert_buffer_node_test.go
  internal/datanode/flow_graph_manager.go
  internal/datanode/flow_graph_manager_test.go
  internal/datanode/flow_graph_time_tick_node.go
  internal/datanode/segment_sync_policy.go
  internal/datanode/segment_sync_policy_test.go
  internal/datanode/services.go
  internal/datanode/services_test.go
  internal/distributed/datacoord/client/client.go
  internal/distributed/datacoord/service.go
  internal/distributed/datacoord/service_test.go
  internal/distributed/datanode/client/client.go
  internal/distributed/datanode/service.go
  internal/distributed/datanode/service_test.go
  internal/distributed/proxy/service.go
  internal/distributed/proxy/service_test.go
  internal/mocks/mock_datacoord.go
  internal/mocks/mock_datanode.go
  internal/proto/data_coord.proto
  internal/proto/datapb/data_coord.pb.go
  internal/proxy/data_coord_mock_test.go
  internal/proxy/impl.go
  internal/proxy/proxy_test.go
  internal/proxy/task.go
  internal/types/types.go
  internal/util/mock/datacoord_client.go
  internal/util/mock/grpc_datacoord_client.go
  internal/util/mock/grpc_datanode_client.go
  tests/integration/getvector/get_vector_test.go
  tests/integration/hellomilvus/hello_milvus_test.go
  tests/integration/indexstat/get_index_statistics_test.go
  tests/integration/jsonexpr/json_expr_test.go
  tests/integration/meta_watcher_test.go
  tests/integration/rangesearch/range_search_test.go
  tests/integration/refreshconfig/refresh_config_test.go
  tests/integration/upsert/upsert_test.go
  tests/integration/util_insert.go
  tests/python_client/requirements.txt
Labels: kind/bug, area/dependency, sig/testing, size/XXL, approved, lgtm, area/test, ci-passed, area/internal-api, dco-passed, test/integration

#26981 show index info while GetSegmentInfo
  internal/querycoordv2/utils/types.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#26982 show index info while GetSegmentInfo
  internal/querycoordv2/utils/types.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed, do-not-merge/missing-related-pr

#27024 Refine QueryNode errors (#27013)
  internal/datacoord/index_builder.go
  internal/datacoord/indexnode_manager.go
  internal/datanode/data_node.go
  internal/datanode/services.go
  internal/distributed/proxy/httpserver/handler_v1.go
  internal/distributed/proxy/service.go
  internal/proxy/impl.go
  internal/proxy/meta_cache.go
  internal/proxy/segment.go
  internal/proxy/task.go
  internal/proxy/task_index.go
  internal/proxy/task_statistic.go
  internal/proxy/timestamp.go
  internal/proxy/util.go
  internal/querynodev2/handlers.go
  internal/querynodev2/metrics_info.go
  internal/querynodev2/services.go
  internal/querynodev2/services_test.go
  internal/querynodev2/utils.go
  internal/rootcoord/broker.go
  internal/util/componentutil/componentutil.go
  pkg/util/merr/utils.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#26907 [Improvement] add pulsar metrics
  configs/milvus.yaml
  pkg/metrics/metrics.go
  pkg/metrics/metrics_test.go
  pkg/mq/msgstream/mq_factory.go
  pkg/util/paramtable/service_param.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed

#27042 Fix wrong error codes & names (#26904)
  internal/distributed/proxy/httpserver/handler_v1.go
  internal/distributed/proxy/httpserver/handler_v1_test.go
  internal/mq/mqimpl/rocksmq/server/rocksmq_impl.go
  internal/mq/mqimpl/rocksmq/server/rocksmq_impl_test.go
  pkg/mq/msgstream/mq_msgstream.go
  pkg/mq/msgstream/mqwrapper/errors.go
  pkg/mq/msgstream/mqwrapper/kafka/kafka_consumer.go
  pkg/mq/msgstream/mqwrapper/nmq/nmq_consumer.go
  pkg/mq/msgstream/mqwrapper/nmq/nmq_consumer_test.go
  pkg/mq/msgstream/mqwrapper/pulsar/pulsar_consumer.go
  pkg/util/merr/errors.go
  pkg/util/merr/errors_test.go
  pkg/util/merr/utils.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#27039 Discard SyncDistribution set action from legacy querycoord (#27027)
  internal/querynodev2/segments/segment_loader.go
  internal/querynodev2/services.go
  internal/querynodev2/services_test.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#27014 Do not reset connection immediately if grpc code is `Canceled` or `DeadlineExceeded`
  internal/distributed/datanode/client/client.go
  internal/distributed/indexnode/client/client.go
  internal/distributed/proxy/client/client.go
  internal/distributed/querynode/client/client.go
  internal/util/grpcclient/client.go
  internal/util/grpcclient/client_test.go
  internal/util/sessionutil/session_util.go
  pkg/util/paramtable/grpc_param.go
  pkg/util/paramtable/grpc_param_test.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#27043 Reduce cpp test time
  internal/core/unittest/test_indexing.cpp
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#27046 Fix printing too many warnings (#27015)
  internal/util/flowgraph/node.go
Labels: kind/bug, kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#27032 Remove unused log
  cmd/components/index_coord.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#27033 Remove unused log
  cmd/components/index_coord.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#26976 Fix historm metrics buckets range for index
  internal/indexnode/task.go
  internal/indexnode/task_scheduler.go
  pkg/metrics/indexnode_metrics.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#27050 [amazonlinux:2023]install perl-IPC-Cmd
  build/docker/builder/cpu/amazonlinux2023/Dockerfile
Labels: size/XS, approved, lgtm, ci-passed, dco-passed, do-not-merge/missing-related-pr

#27048 Cherry pick segment loader & grpcclient fix
  internal/distributed/datanode/client/client.go
  internal/distributed/indexnode/client/client.go
  internal/distributed/proxy/client/client.go
  internal/distributed/querynode/client/client.go
  internal/querynodev2/segments/segment_loader.go
  internal/util/grpcclient/client.go
  internal/util/grpcclient/client_test.go
  internal/util/sessionutil/session_util.go
  pkg/util/paramtable/grpc_param.go
  pkg/util/paramtable/grpc_param_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#27051 Fix misusing chunk manager
  internal/indexnode/chunk_mgr_factory.go
  internal/proto/index_coord.proto
  internal/proto/indexpb/index_coord.pb.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, area/internal-api, dco-passed

#27059 [skip e2e]Update index config in test
  tests/python_client/chaos/cluster-values.yaml
  tests/python_client/chaos/nats-standalone-values.yaml
  tests/python_client/chaos/standalone-values.yaml
  tests/python_client/deploy/cluster-values.yaml
  tests/python_client/deploy/standalone-values.yaml
Labels: kind/improvement, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#27049 [amazonlinux:2023]install perl-IPC-Cmd
  build/docker/builder/cpu/amazonlinux2023/Dockerfile
Labels: size/XS, approved, lgtm, ci-passed, dco-passed

#27058 Add tracer for querycoord tasks
  internal/querycoordv2/task/executor.go
  internal/querycoordv2/task/scheduler.go
  internal/querycoordv2/task/task.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#27063 Flush by flush channels (#26859)
  go.mod
  go.sum
  internal/datacoord/cluster.go
  internal/datacoord/mock_test.go
  internal/datacoord/server_test.go
  internal/datacoord/services.go
  internal/datacoord/session_manager.go
  internal/datanode/channel_meta.go
  internal/datanode/data_sync_service_test.go
  internal/datanode/flow_graph_insert_buffer_node.go
  internal/datanode/flow_graph_insert_buffer_node_test.go
  internal/datanode/flow_graph_manager.go
  internal/datanode/flow_graph_manager_test.go
  internal/datanode/flow_graph_time_tick_node.go
  internal/datanode/segment_sync_policy.go
  internal/datanode/segment_sync_policy_test.go
  internal/datanode/services.go
  internal/datanode/services_test.go
  internal/distributed/datacoord/client/client.go
  internal/distributed/datacoord/service.go
  internal/distributed/datacoord/service_test.go
  internal/distributed/datanode/client/client.go
  internal/distributed/datanode/service.go
  internal/distributed/datanode/service_test.go
  internal/distributed/proxy/service.go
  internal/distributed/proxy/service_test.go
  internal/mocks/mock_datacoord.go
  internal/mocks/mock_datanode.go
  internal/proto/data_coord.proto
  internal/proto/datapb/data_coord.pb.go
  internal/proxy/data_coord_mock_test.go
  internal/proxy/impl.go
  internal/proxy/proxy_test.go
  internal/proxy/task.go
  internal/types/types.go
  internal/util/mock/datacoord_client.go
  internal/util/mock/grpc_datacoord_client.go
  internal/util/mock/grpc_datanode_client.go
  tests/integration/getvector/get_vector_test.go
  tests/integration/hellomilvus/hello_milvus_test.go
  tests/integration/indexstat/get_index_statistics_test.go
  tests/integration/jsonexpr/json_expr_test.go
  tests/integration/meta_watcher_test.go
  tests/integration/rangesearch/range_search_test.go
  tests/integration/refreshconfig/refresh_config_test.go
  tests/integration/upsert/upsert_test.go
  tests/integration/util_insert.go
  tests/python_client/requirements.txt
Labels: kind/bug, area/dependency, sig/testing, size/XXL, approved, lgtm, area/test, ci-passed, dco-passed, test/integration

#27083 [skip e2e]Update etcd follower num to apply chaos
  tests/python_client/chaos/test_chaos_apply_to_determined_pod.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#27072 Fix component pointer to `component` interface never be nil caused panic
  cmd/roles/roles.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#27078 Maintain compatibility of GetFlushState with old client (#27077)
  internal/datacoord/server_test.go
  internal/datacoord/services.go
  internal/proxy/impl.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#27081 Fix proxy panic (#27066)
  internal/proxy/timestamp.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#27082 Use GetXXX instead of directly using dots to get value
  internal/datacoord/index_builder.go
  internal/datacoord/index_meta.go
  internal/datacoord/index_service.go
  internal/datacoord/indexnode_manager.go
  internal/indexnode/indexnode_service.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#27066 Fix proxy panic
  internal/proxy/timestamp.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#27074 [Cherry-Pick] Fix component pointer to `component` interface never be nil caused panic
  cmd/roles/roles.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#27071 Add tracer for querycoord tasks (#27058)
  internal/querycoordv2/task/executor.go
  internal/querycoordv2/task/scheduler.go
  internal/querycoordv2/task/task.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#27079 [Cherry-Pick] Fix component pointer to `component` interface never be nil caused panic
  cmd/roles/roles.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#27092 [Cherry-Pick] Fix grpcclient use needReset as needRetry for cancel&timeout code
  internal/util/grpcclient/client.go
  internal/util/grpcclient/client_test.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#26997 [Cherry-Pick] Refine `TestSessionProcessActiveStandBy` unit test logic (#26980)
  internal/util/sessionutil/session_util_test.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#27091 Fix grpcclient use needReset as needRetry for cancel&timeout code
  internal/util/grpcclient/client.go
  internal/util/grpcclient/client_test.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#27101 Fix the double nil return values from RPC call
  internal/util/grpcclient/client.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#27102 Optimize the generic zero value
  pkg/util/generic/generic.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#27093 Delete failed index tasks ASAP
  internal/indexnode/indexnode_service.go
  internal/indexnode/taskinfo_ops.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#27065 Fix cloudProvider not passed
  internal/datacoord/index_builder.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#27077 Maintain compatibility of GetFlushState with old client
  internal/datacoord/server_test.go
  internal/datacoord/services.go
  internal/proxy/impl.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#27105 Fix growing index hasRawData
  internal/core/src/segcore/FieldIndexing.h
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#27103 Fix the double nil return values from RPC call (#27101)
  internal/util/grpcclient/client.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#27045 Use GetXXX instead of directly using dots to get value
  internal/datacoord/index_builder.go
  internal/datacoord/index_meta.go
  internal/datacoord/index_service.go
  internal/datacoord/indexnode_manager.go
  internal/indexnode/indexnode_service.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#27110 [Cherry-Pick] Refine `TestSessionProcessActiveStandBy` unit test logic (#26980)
  internal/util/sessionutil/session_util_test.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#27029 Handle the error from new RootCoord for DescribeCollection
  internal/proxy/task.go
Labels: kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#27121 Fix compile error at core/storage
  internal/core/src/storage/ChunkCache.cpp
  internal/core/src/storage/storage_c.cpp
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#27124 Fix flush slowly due to wrong DBName (#27123)
  internal/proxy/database_interceptor.go
  internal/proxy/database_interceptor_test.go
Labels: kind/bug, size/XS, dco-passed

#27107 [skip e2e]Add retry when getting image tag from dockerhub
  tests/python_client/requirements.txt
  tests/scripts/get_image_tag_by_short_name.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#27126 [skip e2e]Update config of milvus crd for rolling update
  tests/python_client/deploy/milvus_crd.yaml
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#27115 Update etcd-sdk-python to 0.0.4
  tests/python_client/requirements.txt
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#27114 Update etcd-sdk-python to 0.0.4
  tests/python_client/requirements.txt
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#27123 Fix flush slowly due to wrong DBName
  internal/proxy/database_interceptor.go
  internal/proxy/database_interceptor_test.go
Labels: kind/bug, size/XS, approved, lgtm, dco-passed

#27135 [skip e2e] Add action to check issue title
  .github/workflows/check-issue.yaml
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#27130 update nightly script and pymilvus version
  ci/jenkins/Nightly.groovy
  tests/python_client/requirements.txt
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed, do-not-merge/missing-related-pr

#27141 Increase FlushChannel retry times (#27140)
  internal/datacoord/services.go
  internal/datanode/services.go
Labels: kind/bug, size/XS, dco-passed

#27133 Fix lock not applied in quota center
  internal/rootcoord/quota_center.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#27138 [Cherry-Pick] Fix lock not applied in quota center
  internal/rootcoord/quota_center.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#27144 [skip e2e]Fix get latest image with wrong arch and etcd follower chaos apply
  tests/python_client/chaos/test_chaos_apply_to_determined_pod.py
  tests/scripts/get_image_tag_by_short_name.py
Labels: kind/improvement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#27140 Increase FlushChannel retry times
  internal/datacoord/services.go
  internal/datanode/services.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#27054 Fix high cpu usage caused by proto.size
  internal/proxy/task_query.go
  internal/proxy/task_search.go
  internal/querynodev2/segments/result.go
  pkg/util/typeutil/schema.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#27108 enable ctx traceId for assignsegment on dc(#26972)
  internal/datacoord/compaction_test.go
  internal/datacoord/garbage_collector_test.go
  internal/datacoord/meta.go
  internal/datacoord/meta_test.go
  internal/datacoord/segment_manager.go
  internal/datacoord/segment_manager_test.go
  internal/datacoord/server_test.go
  internal/datacoord/services_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed

#27156 Remove some logs in querynode delegator
  internal/querynodev2/delegator/delegator_data.go
  internal/querynodev2/local_worker.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#27155 Remove some logs in querynode delegator
  internal/querynodev2/delegator/delegator_data.go
  internal/querynodev2/local_worker.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass, do-not-merge/missing-related-pr

#27163 Enable test cases
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#27125 Replace all status with only error string
  internal/datacoord/services.go
  internal/datanode/metrics_info.go
  internal/datanode/services.go
  internal/indexnode/indexnode_service.go
  internal/indexnode/indexnode_service_test.go
  internal/indexnode/metrics_info.go
  internal/proxy/impl.go
  internal/proxy/metrics_info.go
  internal/rootcoord/metrics_info.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#27137 Use merr to handle segcore errors
  internal/util/indexcgowrapper/helper.go
  pkg/util/merr/errors.go
  pkg/util/merr/utils.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed

#27170 use MADV_WILLNEED for scalar column data
  internal/core/src/mmap/Column.h
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#27181 Increase FlushChannel timeout to 3min (#27180)
  internal/datacoord/services.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#27162 Fix datanode panic due to concurrent compaction and delete processing (#27158)
  internal/datanode/channel_meta.go
  internal/datanode/channel_meta_test.go
  internal/datanode/data_node.go
  internal/datanode/flow_graph_delete_node.go
  internal/datanode/flow_graph_insert_buffer_node.go
  internal/datanode/flow_graph_time_tick_node.go
  internal/datanode/flush_manager.go
  internal/datanode/services.go
  internal/datanode/services_test.go
  internal/util/flowgraph/node.go
  pkg/util/retry/retry_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#27167 Fix datanode panic due to concurrent compaction and delete processing
  internal/datanode/channel_meta.go
  internal/datanode/channel_meta_test.go
  internal/datanode/data_node.go
  internal/datanode/flow_graph_delete_node.go
  internal/datanode/flow_graph_insert_buffer_node.go
  internal/datanode/flow_graph_time_tick_node.go
  internal/datanode/flush_manager.go
  internal/datanode/services.go
  internal/datanode/services_test.go
  internal/util/flowgraph/node.go
  pkg/util/retry/retry_test.go
Labels: size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#27180 Increase FlushChannel timeout to 3min
  internal/datacoord/services.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#26398 support azure
  .env
  .github/workflows/code-checker.yaml
  .github/workflows/main.yaml
  docker-compose.yml
  go.mod
  go.sum
  internal/core/src/common/type_c.h
  internal/core/src/indexbuilder/index_c.cpp
  internal/core/src/storage/AzureChunkManager.cpp
  internal/core/src/storage/AzureChunkManager.h
  internal/core/src/storage/CMakeLists.txt
  internal/core/src/storage/ChunkManager.h
  internal/core/src/storage/ChunkManagers.cpp
  internal/core/src/storage/MinioChunkManager.cpp
  internal/core/src/storage/MinioChunkManager.h
  internal/core/src/storage/Types.h
  internal/core/src/storage/Util.cpp
  internal/core/src/storage/azure-blob-storage/AzureBlobChunkManager.cpp
  internal/core/src/storage/azure-blob-storage/AzureBlobChunkManager.h
  internal/core/src/storage/azure-blob-storage/CMakeLists.txt
  internal/core/src/storage/azure-blob-storage/cmake-modules/AzureVcpkg.cmake
  internal/core/src/storage/azure-blob-storage/vcpkg.json
  internal/core/src/storage/storage_c.cpp
  internal/core/unittest/CMakeLists.txt
  internal/core/unittest/test_azure_chunk_manager.cpp
  internal/core/unittest/test_remote_chunk_manager.cpp
  internal/datacoord/garbage_collector.go
  internal/datacoord/garbage_collector_test.go
  internal/storage/azure_object_storage.go
  internal/storage/azure_object_storage_test.go
  internal/storage/factory.go
  internal/storage/minio_chunk_manager.go
  internal/storage/minio_object_storage.go
  internal/storage/minio_object_storage_test.go
  internal/storage/remote_chunk_manager.go
  internal/storage/remote_chunk_manager_test.go
  internal/util/indexcgowrapper/build_index_info.go
  internal/util/initcore/init_core.go
  pkg/util/paramtable/http_param.go
  scripts/azure_build.sh
  scripts/core_build.sh
  scripts/install_deps.sh
Labels: area/dependency, size/XXL, approved, lgtm, ci-passed, area/internal-api, dco-passed, area/compilation

#27174 Add staticcheck linter and fix existing problems
  .golangci.yml
  internal/datacoord/compaction_test.go
  internal/datacoord/compaction_trigger_test.go
  internal/datacoord/meta_test.go
  internal/distributed/proxy/httpserver/utils.go
  internal/distributed/proxy/httpserver/utils_test.go
  internal/metastore/kv/datacoord/kv_catalog_test.go
  internal/parser/planparserv2/plan_parser_v2_test.go
  internal/proxy/mock_test.go
  internal/proxy/reducer_test.go
  internal/proxy/util.go
  internal/querycoordv2/balance/score_based_balancer_test.go
  internal/querycoordv2/meta/replica_manager.go
  internal/querynodev2/delegator/delegator_data.go
  internal/querynodev2/segments/manager.go
  internal/querynodev2/services_test.go
  internal/rootcoord/import_manager_test.go
  internal/rootcoord/mock_test.go
  internal/storage/binlog_test.go
  internal/storage/vector_chunk_manager_test.go
  internal/util/importutil/json_parser.go
  pkg/log/mlogger_test.go
  pkg/mq/msgstream/mq_msgstream.go
  pkg/util/cache/local_cache_test.go
  pkg/util/etcd/etcd_util_test.go
Labels: kind/improvement, size/M, approved, lgtm, ci-passed, area/internal-api, dco-passed
