Repository milvus-io/milvus, pull requests merged in 2024-11, with the labels that each got.

#37288 fix: [skip e2e] TestNodeDownOnSingleReplica has unstable result
  tests/integration/replicas/balance/replica_test.go
Labels: kind/bug, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed, manual-pass, test/integration

#36306 enhance: [skip ci] remove tools/core_gen after #35251
  internal/core/src/query/ExecPlanNodeVisitor.cpp
  internal/core/src/query/ExecPlanNodeVisitor.h
  tools/core_gen/__init__.py
  tools/core_gen/all_generate.py
  tools/core_gen/assemble.py
  tools/core_gen/meta_gen.py
  tools/core_gen/templates/node_def.cpp
  tools/core_gen/templates/visitor_base.h
  tools/core_gen/templates/visitor_derived.cpp
  tools/core_gen/templates/visitor_derived.h
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#37350 fix: [skip e2e] TestNodeDownOnSingleReplica has unstable result (#37288)
  tests/integration/replicas/balance/replica_test.go
Labels: kind/bug, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed, test/integration

#37339 enhance: Fix case error msg after knowhere upgrade
  internal/querynodev2/delegator/delta_forward.go
  tests/go_client/testcases/index_test.go
Labels: kind/enhancement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#37340 enhance: [2.4] Move forward l0 logic out of delta lock
  internal/querynodev2/delegator/delegator_data.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#37351 fix: [skip e2e] TestNodeDownOnSingleReplica has unstable result (#37288)
  tests/integration/replicas/balance/replica_test.go
Labels: kind/bug, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed, manual-pass, test/integration

#37331 enhance: [CP25]add unify vector index config management
  configs/milvus.yaml
  internal/datacoord/task_index.go
  internal/indexnode/task_index.go
  internal/proxy/task_index.go
  internal/proxy/task_index_test.go
  pkg/config/config.go
  pkg/config/file_source.go
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/knowhere_param.go
  pkg/util/paramtable/knowhere_param_test.go
Labels: kind/enhancement, size/XL, approved, lgtm, ci-passed, dco-passed

#37254 fix: fix hasCollection response has no status
  internal/proxy/task.go
  internal/proxy/task_test.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#37295 fix: parse fail in empty json(#37294)
  internal/core/src/common/Json.h
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#37310 enhance: load deltalogs on demand when doing compactions
  internal/datanode/compaction/clustering_compactor.go
  internal/datanode/compaction/compactor_common.go
  internal/datanode/compaction/merge_sort.go
  internal/datanode/compaction/mix_compactor.go
  internal/datanode/compaction/mix_compactor_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#37313 fix: crash when startup if the milvus volume is on-operation concurrently
  internal/core/src/storage/LocalChunkManager.cpp
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#37343 fix: [2.5]Fix the bug where some expressions do not correctly parse the value
  internal/parser/planparserv2/parser_visitor.go
  internal/parser/planparserv2/plan_parser_v2_test.go
  internal/parser/planparserv2/utils.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#37341 fix: Fix the bug where some expressions do not correctly parse the value
  internal/parser/planparserv2/parser_visitor.go
  internal/parser/planparserv2/plan_parser_v2_test.go
  internal/parser/planparserv2/utils.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#37290 enhance: Rename textmatch to text_match
  internal/parser/planparserv2/Plan.g4
  internal/parser/planparserv2/generated/PlanLexer.interp
  internal/parser/planparserv2/generated/plan_lexer.go
  internal/parser/planparserv2/plan_parser_v2_test.go
  tests/python_client/chaos/checker.py
  tests/python_client/common/common_func.py
  tests/python_client/testcases/test_bulk_insert.py
  tests/python_client/testcases/test_full_text_search.py
  tests/python_client/testcases/test_query.py
  tests/python_client/testcases/test_search.py
  tests/restful_client_v2/testcases/test_vector_operations.py
Labels: kind/enhancement, sig/testing, size/XL, approved, lgtm, area/test, ci-passed, dco-passed

#37291 enhance: [2.5]Rename textmatch to text_match
  internal/parser/planparserv2/Plan.g4
  internal/parser/planparserv2/generated/PlanLexer.interp
  internal/parser/planparserv2/generated/plan_lexer.go
  internal/parser/planparserv2/plan_parser_v2_test.go
  tests/python_client/chaos/checker.py
  tests/python_client/common/common_func.py
  tests/python_client/testcases/test_bulk_insert.py
  tests/python_client/testcases/test_full_text_search.py
  tests/python_client/testcases/test_query.py
  tests/python_client/testcases/test_search.py
  tests/restful_client_v2/testcases/test_vector_operations.py
Labels: kind/enhancement, sig/testing, size/XL, approved, lgtm, area/test, ci-passed, dco-passed

#37342 fix: [2.4] Fix the bug where some expressions do not correctly parse the value
  internal/parser/planparserv2/parser_visitor.go
  internal/parser/planparserv2/plan_parser_v2_test.go
  internal/parser/planparserv2/utils.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#37294 fix: parse fail in empty json
  internal/core/src/common/Json.h
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#37337 enhance: Move forward l0 logic out of delta lock
  internal/querynodev2/delegator/delegator_data.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#37314 enhance: [2.5]Increase the concurrency of index tasks in CI
  tests/_helm/values/e2e/distributed
  tests/_helm/values/e2e/distributed-streaming-service
  tests/_helm/values/e2e/standalone
  tests/_helm/values/e2e/standalone-kafka-mmap
  tests/_helm/values/e2e/standalone-one-pod
Labels: kind/enhancement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#37332 enhance: [cp25] Update Knowhere version
  internal/core/thirdparty/knowhere/CMakeLists.txt
  tests/go_client/testcases/index_test.go
Labels: kind/enhancement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed, area/compilation, kind/branch-feature

#37376 fix: optimize invalid datatype error msg
  internal/proxy/task_index.go
  tests/go_client/testcases/index_test.go
Labels: kind/bug, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#37377 fix: [cp25]optimize invalid error msg
  internal/proxy/task_index.go
  tests/go_client/testcases/index_test.go
Labels: kind/bug, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#37330 enhance: [CP25] remove useless vector index param checker
  internal/util/indexparamcheck/base_checker.go
  internal/util/indexparamcheck/bin_flat_checker.go
  internal/util/indexparamcheck/bin_ivf_flat_checker.go
  internal/util/indexparamcheck/binary_vector_base_checker.go
  internal/util/indexparamcheck/cagra_checker.go
  internal/util/indexparamcheck/diskann_checker.go
  internal/util/indexparamcheck/flat_checker.go
  internal/util/indexparamcheck/float_vector_base_checker.go
  internal/util/indexparamcheck/hnsw_checker.go
  internal/util/indexparamcheck/ivf_base_checker.go
  internal/util/indexparamcheck/ivf_pq_checker.go
  internal/util/indexparamcheck/ivf_pq_checker_test.go
  internal/util/indexparamcheck/ivf_sq_checker.go
  internal/util/indexparamcheck/raft_brute_force_checker.go
  internal/util/indexparamcheck/raft_ivf_flat_checker.go
  internal/util/indexparamcheck/raft_ivf_pq_checker.go
  internal/util/indexparamcheck/scann_checker.go
  internal/util/indexparamcheck/scann_checker_test.go
  internal/util/indexparamcheck/sparse_float_vector_base_checker.go
  internal/util/indexparamcheck/sparse_inverted_index_checker.go
  internal/util/indexparamcheck/vector_index_checker.go
  pkg/util/typeutil/schema.go
Labels: kind/enhancement, size/XL, approved, lgtm, ci-passed, dco-passed, manual-pass

#37333 enhance: Update Knowhere version
  .github/workflows/update-knowhere-commit.yaml
  internal/core/thirdparty/knowhere/CMakeLists.txt
Labels: kind/enhancement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed, area/compilation

#37335 enhance: Increase the concurrency of index tasks in CI
  tests/_helm/values/e2e/distributed
  tests/_helm/values/e2e/distributed-streaming-service
  tests/_helm/values/e2e/standalone
  tests/_helm/values/e2e/standalone-kafka-mmap
  tests/_helm/values/e2e/standalone-one-pod
Labels: kind/enhancement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#37312 fix: crash when startup if the milvus volume is on-operation concurrently
  internal/core/src/storage/LocalChunkManager.cpp
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#37307 fix: [cp24]l0RowCount metrics value always empty
  internal/datacoord/meta.go
  internal/datacoord/meta_test.go
  internal/datacoord/segment_info.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#37406 enhance: [skip e2e] update helm chart version for nightly
  ci/jenkins/Nightly2.groovy
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#37415 Revert "enhance: Support db for bulkinsert (#37012) (#37017)"
  internal/datacoord/import_job.go
  internal/datacoord/services.go
  internal/datacoord/services_test.go
  internal/distributed/proxy/httpserver/handler_v2.go
  internal/distributed/proxy/httpserver/request_v2.go
  internal/proto/internal.proto
  internal/proxy/impl.go
  internal/proxy/impl_test.go
  internal/proxy/proxy_test.go
Labels: size/L, area/internal-api

#37418 fix: process null value in yaml
  pkg/config/config.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#37119 test: fix tokenizer and monkey patch faker function
  tests/python_client/chaos/checker.py
  tests/python_client/common/common_func.py
  tests/python_client/testcases/test_full_text_search.py
  tests/python_client/testcases/test_query.py
  tests/python_client/testcases/test_search.py
  tests/restful_client_v2/base/testbase.py
  tests/restful_client_v2/testcases/test_jobs_operation.py
Labels: kind/improvement, sig/testing, size/XL, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#37354 fix: dead lock if query node crash during shard client init
  internal/proxy/shard_client.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed, kind/branch-feature

#37421 fix: [2.4] Revert "enhance: Support db for bulkinsert (#37012) (#37017)"
  internal/datacoord/import_job.go
  internal/datacoord/services.go
  internal/datacoord/services_test.go
  internal/distributed/proxy/httpserver/handler_v2.go
  internal/distributed/proxy/httpserver/request_v2.go
  internal/proto/internal.proto
  internal/proxy/impl.go
  internal/proxy/impl_test.go
  internal/proxy/proxy_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, area/internal-api, dco-passed

#37326 fix: proxy retry to get shard leader on unloaded collection
  internal/proxy/lb_policy.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed, kind/branch-feature

#37440 enhance: [2.4] Pass rpc stats via gin.Context
  internal/distributed/proxy/httpserver/handler_v2.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#37435 enhance: Bump milvus & proto version to v2.4.15
  go.mod
  go.sum
  pkg/common/version.go
  pkg/go.mod
  pkg/go.sum
Labels: kind/enhancement, area/dependency, size/S, approved, lgtm, ci-passed, dco-passed, manual-pass, kind/branch-feature

#37359 fix: repeated error code in milvus and segcore
  internal/core/src/common/EasyAssert.h
  pkg/util/merr/errors.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#37292 fix: fix group by on chunked segment
  internal/core/src/common/QueryResult.h
  internal/core/src/exec/operator/groupby/SearchGroupByOperator.h
  internal/core/src/mmap/ChunkedColumn.h
  internal/core/src/query/SearchOnGrowing.cpp
  internal/core/src/query/SearchOnSealed.cpp
  internal/core/unittest/test_chunked_segment.cpp
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#37439 enhance: Pass rpc stats via gin.Context
  internal/distributed/proxy/httpserver/handler_v2.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#37445 fix: Skip EOF error when default empty yaml file
  pkg/config/file_source.go
  pkg/config/file_source_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#37412 enhance: refine the pipeline
  ci/jenkins/Nightly2.groovy
  ci/jenkins/PR-for-go-sdk.groovy
  ci/jenkins/PR.groovy
  ci/jenkins/UT-CPP.groovy
  scripts/3rdparty_build.sh
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#37456 enhance: refine the pipeline
  ci/jenkins/Nightly2.groovy
  ci/jenkins/PR.groovy
  scripts/3rdparty_build.sh
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#37319 fix: [cp24]Saperate L0 and Mix trigger interval
  configs/milvus.yaml
  internal/datacoord/compaction_trigger.go
  internal/datacoord/compaction_trigger_v2.go
  pkg/util/paramtable/component_param.go
  tests/integration/compaction/compaction_test.go
  tests/integration/compaction/l2_single_compaction_test.go
Labels: kind/bug, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, test/integration

#37365 enhance: [GoSDK] Add alter collection API & expose options
  client/collection.go
  client/collection_options.go
  client/collection_test.go
  client/read_options.go
  client/read_test.go
  tests/go_client/testcases/collection_test.go
Labels: kind/enhancement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#37352 enhance: improve rootcoord task scheduling policy
  go.sum
  internal/rootcoord/alter_alias_task.go
  internal/rootcoord/alter_collection_task.go
  internal/rootcoord/alter_database_task.go
  internal/rootcoord/create_alias_task.go
  internal/rootcoord/create_collection_task.go
  internal/rootcoord/create_db_task.go
  internal/rootcoord/create_partition_task.go
  internal/rootcoord/describe_collection_task.go
  internal/rootcoord/describe_db_task.go
  internal/rootcoord/drop_alias_task.go
  internal/rootcoord/drop_collection_task.go
  internal/rootcoord/drop_db_task.go
  internal/rootcoord/drop_partition_task.go
  internal/rootcoord/has_collection_task.go
  internal/rootcoord/has_partition_task.go
  internal/rootcoord/list_db_task.go
  internal/rootcoord/rename_collection_task.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/scheduler.go
  internal/rootcoord/scheduler_test.go
  internal/rootcoord/show_collection_task.go
  internal/rootcoord/show_partition_task.go
  internal/rootcoord/task.go
  internal/rootcoord/task_test.go
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, area/dependency, size/XL, approved, lgtm, ci-passed, dco-passed

#37403 fix: search/query failed due to segment not loaded
  internal/querycoordv2/meta/leader_view_manager.go
  internal/querycoordv2/task/executor.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#37048 feat: Tokenizer support build with params and clone for concurrency
  internal/core/src/common/FieldMeta.cpp
  internal/core/src/common/FieldMeta.h
  internal/core/src/index/TextMatchIndex.cpp
  internal/core/src/index/TextMatchIndex.h
  internal/core/src/indexbuilder/index_c.cpp
  internal/core/src/segcore/ChunkedSegmentSealedImpl.cpp
  internal/core/src/segcore/SegmentGrowingImpl.cpp
  internal/core/src/segcore/SegmentSealedImpl.cpp
  internal/core/src/segcore/tokenizer_c.cpp
  internal/core/src/segcore/tokenizer_c.h
  internal/core/thirdparty/tantivy/tantivy-binding/Cargo.lock
  internal/core/thirdparty/tantivy/tantivy-binding/Cargo.toml
  internal/core/thirdparty/tantivy/tantivy-binding/include/tantivy-binding.h
  internal/core/thirdparty/tantivy/tantivy-binding/src/error.rs
  internal/core/thirdparty/tantivy/tantivy-binding/src/index_reader_text.rs
  internal/core/thirdparty/tantivy/tantivy-binding/src/index_reader_text_c.rs
  internal/core/thirdparty/tantivy/tantivy-binding/src/index_writer_text_c.rs
  internal/core/thirdparty/tantivy/tantivy-binding/src/lib.rs
  internal/core/thirdparty/tantivy/tantivy-binding/src/tokenizer.rs
  internal/core/thirdparty/tantivy/tantivy-binding/src/tokenizer_c.rs
  internal/core/thirdparty/tantivy/tantivy-binding/src/tokenizer_filter.rs
  internal/core/thirdparty/tantivy/tantivy-binding/src/util.rs
  internal/core/thirdparty/tantivy/tantivy-wrapper.h
  internal/core/thirdparty/tantivy/tokenizer.h
  internal/core/unittest/test_c_tokenizer.cpp
  internal/core/unittest/test_text_match.cpp
  internal/proxy/task_query.go
  internal/proxy/task_search.go
  internal/util/ctokenizer/c_tokenizer.go
  internal/util/ctokenizer/c_tokenizer_factory.go
  internal/util/ctokenizer/c_tokenizer_test.go
  internal/util/ctokenizer/text_schema_validator_test.go
  internal/util/function/bm25_function.go
  internal/util/tokenizerapi/tokenizer.go
  tests/python_client/common/common_func.py
  tests/python_client/testcases/test_full_text_search.py
  tests/python_client/testcases/test_query.py
  tests/python_client/testcases/test_search.py
  tests/restful_client_v2/testcases/test_vector_operations.py
Labels: kind/feature, sig/testing, size/XL, approved, lgtm, area/test, ci-passed, dco-passed

#37215 test: update test cases
  tests/python_client/testcases/test_index.py
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#37480 fix: [skip e2e]unstable integration test TestNodeDownOnSingleReplica
  tests/integration/replicas/balance/replica_test.go
Labels: kind/bug, sig/testing, size/M, approved, lgtm, area/test, dco-passed, test/integration

#37405 enhance: Add cgo call metrics for load/write API
  internal/querynodev2/segments/load_index_info.go
  internal/querynodev2/segments/segment.go
  pkg/metrics/metrics.go
  pkg/metrics/querynode_metrics.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#37416 fix: Add IP address validation from paramtable
  pkg/util/funcutil/func.go
  pkg/util/funcutil/func_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#37444 fix: drop collection failed if enable streaming service
  internal/datacoord/channel_manager.go
  internal/datacoord/channel_manager_factory.go
  internal/datacoord/channel_store.go
  internal/datacoord/channel_store_test.go
  internal/datacoord/compaction.go
  internal/datacoord/compaction_test.go
  internal/datacoord/policy.go
  internal/datacoord/server.go
  internal/datacoord/server_test.go
  internal/datacoord/services.go
  internal/datacoord/services_test.go
  internal/flushcommon/pipeline/data_sync_service.go
  internal/flushcommon/pipeline/flow_graph_time_tick_node.go
  internal/rootcoord/create_collection_task.go
  internal/rootcoord/create_collection_task_test.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/timeticksync.go
  internal/streamingnode/server/flusher/flusherimpl/channel_lifetime.go
  internal/streamingnode/server/flusher/flusherimpl/flusher_impl.go
  internal/streamingnode/server/flusher/flusherimpl/flusher_impl_test.go
  internal/streamingnode/server/wal/adaptor/wal_test.go
  internal/streamingnode/server/wal/interceptors/ddl/ddl_interceptor.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#37443 enhance: [2.4] Refine error message for contains array
  internal/parser/planparserv2/plan_parser_v2_test.go
  internal/parser/planparserv2/utils.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#37383 enhance: Refine error message for contains array
  internal/parser/planparserv2/plan_parser_v2_test.go
  internal/parser/planparserv2/utils.go
  tests/python_client/testcases/test_mix_scenes.py
Labels: kind/enhancement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed, manual-pass

#37449 fix: repeated error code in milvus and segcore
  internal/core/src/common/EasyAssert.h
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#37472 enhance: [GoSDK] Remove example in main pkg to make ut script work
  client/column/columns_test.go
  client/example/database/main.go
  client/example/playground/main.go
  client/example/rowbase/main.go
  scripts/run_go_codecov.sh
Labels: kind/enhancement, size/XL, approved, lgtm, ci-passed, dco-passed

#37410 fix: Correct dropped segment num metrics
  internal/datacoord/meta.go
  internal/datacoord/meta_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#37400 fix: merge sort segment loss data
  internal/datanode/compaction/merge_sort.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#37453 fix: wrong path spelling when use rootpath in segcore
  internal/core/src/clustering/KmeansClustering.h
  internal/core/src/index/InvertedIndexTantivy.cpp
  internal/core/src/storage/ChunkManager.h
  internal/core/src/storage/FileManager.h
  internal/core/src/storage/Util.cpp
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#37344 feat: add segment,pipeline, replica and resourcegroup api for WebUI
  internal/datacoord/channel_manager.go
  internal/datacoord/channel_manager_test.go
  internal/datacoord/index_meta.go
  internal/datacoord/meta.go
  internal/datacoord/meta_test.go
  internal/datacoord/metrics_info.go
  internal/datacoord/metrics_info_test.go
  internal/datacoord/mock_channelmanager.go
  internal/datacoord/server.go
  internal/datacoord/stats_task_meta.go
  internal/datanode/data_node.go
  internal/flushcommon/metacache/segment.go
  internal/flushcommon/pipeline/flow_graph_manager.go
  internal/flushcommon/pipeline/flow_graph_manager_test.go
  internal/flushcommon/pipeline/mock_fgmanager.go
  internal/flushcommon/syncmgr/task.go
  internal/flushcommon/syncmgr/task_test.go
  internal/flushcommon/util/timetick_sender.go
  internal/http/router.go
  internal/http/webui/header.html
  internal/http/webui/index.html
  internal/http/webui/nodes.html
  internal/http/webui/static/js/mockdata.js
  internal/proxy/impl.go
  internal/proxy/impl_test.go
  internal/querycoordv2/handlers.go
  internal/querycoordv2/handlers_test.go
  internal/querycoordv2/meta/channel_dist_manager.go
  internal/querycoordv2/meta/channel_dist_manager_test.go
  internal/querycoordv2/meta/dist_manager.go
  internal/querycoordv2/meta/dist_manager_test.go
  internal/querycoordv2/meta/leader_view_manager.go
  internal/querycoordv2/meta/leader_view_manager_test.go
  internal/querycoordv2/meta/mock_target_manager.go
  internal/querycoordv2/meta/replica_manager.go
  internal/querycoordv2/meta/replica_manager_test.go
  internal/querycoordv2/meta/resource_manager.go
  internal/querycoordv2/meta/resource_manager_test.go
  internal/querycoordv2/meta/segment_dist_manager.go
  internal/querycoordv2/meta/segment_dist_manager_test.go
  internal/querycoordv2/meta/target.go
  internal/querycoordv2/meta/target_manager.go
  internal/querycoordv2/meta/target_manager_test.go
  internal/querycoordv2/server.go
  internal/querynodev2/metrics_info.go
  internal/querynodev2/metrics_info_test.go
  internal/querynodev2/pipeline/manager.go
  internal/querynodev2/pipeline/pipeline.go
  internal/querynodev2/server.go
  internal/util/flowgraph/flow_graph.go
  internal/util/flowgraph/node.go
  internal/util/flowgraph/node_test.go
  internal/util/metrics/utils.go
  internal/util/pipeline/stream_pipeline.go
  pkg/util/metricsinfo/metric_request.go
  pkg/util/metricsinfo/metrics_info.go
  pkg/util/metricsinfo/utils.go
  pkg/util/typeutil/time.go
Labels: kind/feature, size/XXL, approved, lgtm, ci-passed, dco-passed

#37481 fix: add rescorer activation function for BM25
  internal/proxy/reScorer.go
  tests/python_client/common/common_func.py
Labels: kind/bug, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#37485 enhance: [2.4]Update the template expression proto to improve transmission efficiency
  go.mod
  go.sum
  internal/parser/planparserv2/convert_field_data_to_generic_value.go
  internal/parser/planparserv2/convert_field_data_to_generic_value_test.go
  internal/parser/planparserv2/fill_expression_value_test.go
  internal/parser/planparserv2/plan_parser_v2_test.go
Labels: kind/enhancement, area/dependency, size/XL, approved, lgtm, ci-passed, dco-passed

#37491 enhance: [2.4] Use cancel label for ctx canceled storage op (#37468)
  internal/storage/remote_chunk_manager.go
  pkg/metrics/metrics.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#37235 enhance: refactor createIndex in RESTful API
  internal/distributed/proxy/httpserver/handler_v2.go
  internal/distributed/proxy/httpserver/handler_v2_test.go
  internal/distributed/proxy/httpserver/utils.go
  tests/restful_client_v2/testcases/test_index_operation.py
Labels: kind/enhancement, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#37237 enhance: refactor createIndex in RESTful API(#37235)
  internal/distributed/proxy/httpserver/handler_v2.go
  internal/distributed/proxy/httpserver/handler_v2_test.go
  internal/distributed/proxy/httpserver/utils.go
  tests/restful_client_v2/testcases/test_index_operation.py
Labels: kind/enhancement, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#37433 fix: watch channel stuck due to misuse of timer.Reset
  client/index.go
  client/maintenance.go
  internal/datanode/channel/channel_manager.go
  pkg/mq/msgdispatcher/target.go
  pkg/mq/msgdispatcher/target_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#37334 fix: parse error given duplicated plan cache key
  internal/parser/planparserv2/plan_parser_v2.go
  internal/parser/planparserv2/plan_parser_v2_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#37385 enhance: Handoff growing segment after sorted
  internal/datacoord/compaction_task_clustering.go
  internal/datacoord/handler.go
  internal/datacoord/handler_test.go
  internal/datacoord/meta.go
  internal/datacoord/server.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#37484 enhance: Update the template expression proto to improve transmission efficiency
  go.mod
  go.sum
  internal/parser/planparserv2/convert_field_data_to_generic_value.go
  internal/parser/planparserv2/convert_field_data_to_generic_value_test.go
  internal/parser/planparserv2/fill_expression_value_test.go
  internal/parser/planparserv2/plan_parser_v2_test.go
Labels: kind/enhancement, area/dependency, size/XL, approved, lgtm, ci-passed, dco-passed

#37471 fix: [cp24]Correct dropped segment num metrics
  internal/datacoord/meta.go
  internal/datacoord/meta_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#37499 fix: [skip e2e]unstable integration test TestNodeDownOnSingleReplica(#37480)
  tests/integration/replicas/balance/replica_test.go
Labels: kind/bug, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed, test/integration

#37476 test: update test cases
  tests/python_client/testcases/test_query.py
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#37420 fix: Revert "enhance: Support db for bulkinsert (#37012)"
  internal/datacoord/import_job.go
  internal/datacoord/services.go
  internal/datacoord/services_test.go
  internal/distributed/proxy/httpserver/handler_v2.go
  internal/distributed/proxy/httpserver/request_v2.go
  internal/proto/internal.proto
  internal/proxy/impl.go
  internal/proxy/impl_test.go
  internal/proxy/proxy_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, area/internal-api, dco-passed

#37388 fix: Fix large growing segment
  internal/datacoord/segment_allocation_policy.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed, PR | need cherry-pick

#37501 enhance: regenerate datacoord mockery
  internal/datacoord/mock_channel_store.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#37479 enhance: avoid memory copy and serde in mix compaction
  internal/datanode/compaction/mix_compactor.go
  internal/datanode/compaction/segment_writer.go
  internal/storage/serde.go
  internal/storage/serde_events.go
  internal/storage/serde_events_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#37490 enhance: optimize describe collection and index
  internal/querycoordv2/observers/target_observer.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#37513 enhance: enable the lock scheduler for the rootcoord
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#37524 enhance: Add context trace for querycoord queryable check
  internal/querycoordv2/services.go
  internal/querycoordv2/utils/meta_test.go
  internal/querycoordv2/utils/util.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#37530 enhance: Accelerate Build stage by skipping cpp ut compilation
  .github/workflows/main.yaml
  internal/json/sonic.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#37523 enhance: [2.4] improve rootcoord task scheduling policy
  internal/rootcoord/alter_alias_task.go
  internal/rootcoord/alter_collection_task.go
  internal/rootcoord/alter_database_task.go
  internal/rootcoord/create_alias_task.go
  internal/rootcoord/create_collection_task.go
  internal/rootcoord/create_db_task.go
  internal/rootcoord/create_partition_task.go
  internal/rootcoord/describe_collection_task.go
  internal/rootcoord/describe_db_task.go
  internal/rootcoord/drop_alias_task.go
  internal/rootcoord/drop_collection_task.go
  internal/rootcoord/drop_db_task.go
  internal/rootcoord/drop_partition_task.go
  internal/rootcoord/has_collection_task.go
  internal/rootcoord/has_partition_task.go
  internal/rootcoord/list_db_task.go
  internal/rootcoord/rename_collection_task.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/scheduler.go
  internal/rootcoord/scheduler_test.go
  internal/rootcoord/show_collection_task.go
  internal/rootcoord/show_partition_task.go
  internal/rootcoord/task.go
  internal/rootcoord/task_test.go
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/XL, approved, lgtm, ci-passed, dco-passed

#37506 enhance: Add integration test for stats task
  tests/integration/stats_task/stats_task_test.go
  tests/integration/util_query.go
Labels: kind/enhancement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, manual-pass, test/integration

#37382 fix: Fix subscription leak
  internal/rootcoord/dml_channels.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#37540 fix: Fix large growing segment (#37388)
  internal/datacoord/segment_allocation_policy.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#37541 fix: Fix subscription leak (#37382)
  internal/rootcoord/dml_channels.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#37542 fix: watch channel stuck due to misuse of timer.Reset (#37433)
  internal/datanode/channel_manager.go
  pkg/mq/msgdispatcher/target.go
  pkg/mq/msgdispatcher/target_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#37544 fix: search/query failed due to segment not loaded (#37403)
  internal/querycoordv2/meta/leader_view_manager.go
  internal/querycoordv2/task/executor.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#37534 enhance: [2.4] Add context trace for querycoord queryable check (#37524)
  internal/querycoordv2/services.go
  internal/querycoordv2/utils/meta_test.go
  internal/querycoordv2/utils/util.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#37551 fix: Set correct memory size
  internal/storage/serde.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#37454 fix: Fix load slowly
  internal/querycoordv2/meta/target_manager.go
  internal/querycoordv2/observers/target_observer.go
  internal/querycoordv2/observers/target_observer_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#37087 enhance: Support custom privilege group for RBAC
  client/go.mod
  go.mod
  go.sum
  internal/datacoord/mock_test.go
  internal/datanode/importv2/pool_test.go
  internal/distributed/proxy/httpserver/constant.go
  internal/distributed/proxy/httpserver/handler_v2.go
  internal/distributed/proxy/httpserver/request_v2.go
  internal/distributed/proxy/service.go
  internal/distributed/rootcoord/client/client.go
  internal/distributed/rootcoord/client/client_test.go
  internal/distributed/rootcoord/service.go
  internal/metastore/catalog.go
  internal/metastore/kv/rootcoord/kv_catalog.go
  internal/metastore/kv/rootcoord/kv_catalog_test.go
  internal/metastore/kv/rootcoord/rootcoord_constant.go
  internal/metastore/mocks/mock_rootcoord_catalog.go
  internal/mocks/mock_proxy.go
  internal/mocks/mock_rootcoord.go
  internal/mocks/mock_rootcoord_client.go
  internal/proto/internal.proto
  internal/proto/root_coord.proto
  internal/proxy/impl.go
  internal/proxy/meta_cache.go
  internal/proxy/rootcoord_mock_test.go
  internal/proxy/util.go
  internal/proxy/util_test.go
  internal/querycoordv2/task/mock_scheduler.go
  internal/rootcoord/meta_table.go
  internal/rootcoord/meta_table_test.go
  internal/rootcoord/mock_test.go
  internal/rootcoord/mocks/meta_table.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
  internal/util/mock/grpc_rootcoord_client.go
  pkg/go.mod
  pkg/go.sum
  pkg/metrics/rootcoord_metrics.go
  pkg/util/constant.go
  pkg/util/funcutil/policy.go
  tests/integration/rbac/privilege_group_test.go
  tests/integration/rbac/rbac_backup_test.go
Labels: kind/enhancement, area/dependency, sig/testing, size/XXL, approved, lgtm, area/test, ci-passed, area/internal-api, dco-passed, test/integration

#37545 test: fix unstable testcase caused by server refactor
  tests/python_client/testcases/test_utility.py
Labels: sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#37558 enhance: RBAC custom privilege group ut coverage
  internal/distributed/proxy/httpserver/handler_v2.go
  internal/distributed/proxy/httpserver/handler_v2_test.go
  internal/distributed/proxy/httpserver/request_v2.go
  internal/rootcoord/meta_table_test.go
  internal/rootcoord/mock_test.go
  internal/rootcoord/root_coord_test.go
  tests/integration/rbac/privilege_group_test.go
Labels: kind/enhancement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, test/integration

#37478 enhance: rename tokenizer to analyzer and check analyzer params
  internal/core/src/common/FieldMeta.cpp
  internal/core/src/common/FieldMeta.h
  internal/core/src/common/Schema.h
  internal/core/src/index/TextMatchIndex.cpp
  internal/core/src/index/TextMatchIndex.h
  internal/core/src/indexbuilder/index_c.cpp
  internal/core/src/segcore/ChunkedSegmentSealedImpl.cpp
  internal/core/src/segcore/SegmentGrowingImpl.cpp
  internal/core/src/segcore/SegmentSealedImpl.cpp
  internal/core/thirdparty/tantivy/jieba_demo.cpp
  internal/core/thirdparty/tantivy/tantivy-binding/include/tantivy-binding.h
  internal/core/thirdparty/tantivy/tantivy-binding/src/index_reader_text_c.rs
  internal/core/thirdparty/tantivy/tantivy-binding/src/index_writer_text_c.rs
  internal/core/thirdparty/tantivy/tantivy-binding/src/tokenizer_c.rs
  internal/core/thirdparty/tantivy/tantivy-wrapper.h
  internal/core/unittest/test_c_tokenizer.cpp
  internal/core/unittest/test_text_match.cpp
  internal/datacoord/job_manager_test.go
  internal/distributed/proxy/httpserver/handler_v2.go
  internal/distributed/proxy/httpserver/utils.go
  internal/flushcommon/pipeline/flow_graph_embedding_node_test.go
  internal/metastore/kv/rootcoord/kv_catalog_test.go
  internal/proxy/task.go
  internal/proxy/task_test.go
  internal/proxy/util.go
  internal/proxy/util_test.go
  internal/util/ctokenizer/text_schema_validator.go
  internal/util/ctokenizer/text_schema_validator_test.go
  internal/util/function/bm25_function.go
  pkg/util/typeutil/field_schema.go
  tests/python_client/common/common_func.py
  tests/python_client/requirements.txt
  tests/python_client/testcases/test_bulk_insert.py
  tests/python_client/testcases/test_full_text_search.py
  tests/python_client/testcases/test_query.py
  tests/python_client/testcases/test_search.py
  tests/restful_client_v2/requirements.txt
  tests/restful_client_v2/testcases/test_collection_operations.py
  tests/restful_client_v2/testcases/test_index_operation.py
  tests/restful_client_v2/testcases/test_vector_operations.py
Labels: kind/enhancement, sig/testing, size/XXL, approved, lgtm, area/test, ci-passed, dco-passed

#37539 test: remove case skip label
  tests/go_client/testcases/search_test.go
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed, manual-pass, kind/test

#37500 fix: [2.4] Add IP address validation from paramtable (#37416)
  pkg/util/funcutil/func.go
  pkg/util/funcutil/func_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#37565 enhance: Handle legacy proxy load fields request
  internal/datanode/importv2/pool_test.go
  internal/metastore/mocks/mock_rootcoord_catalog.go
  internal/querycoordv2/job/job_load.go
  internal/querycoordv2/job/job_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#37531 enhance: move the search utilities from querynode into new module
  internal/querynodev2/delegator/delegator.go
  internal/querynodev2/server.go
  internal/querynodev2/server_test.go
  internal/querynodev2/services.go
  internal/querynodev2/tasks/query_stream_task.go
  internal/querynodev2/tasks/query_task.go
  internal/querynodev2/tasks/search_task.go
  internal/util/searchutil/optimizers/mock_query_hook.go
  internal/util/searchutil/optimizers/query_hook.go
  internal/util/searchutil/optimizers/query_hook_test.go
  internal/util/searchutil/scheduler/concurrent_safe_scheduler.go
  internal/util/searchutil/scheduler/concurrent_safe_scheduler_test.go
  internal/util/searchutil/scheduler/fifo_policy.go
  internal/util/searchutil/scheduler/mock_task_test.go
  internal/util/searchutil/scheduler/policy_test.go
  internal/util/searchutil/scheduler/queues.go
  internal/util/searchutil/scheduler/queues_test.go
  internal/util/searchutil/scheduler/tasks.go
  internal/util/searchutil/scheduler/user_task_polling_policy.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#37575 fix: panic calclulating data size on writing binlogs
  internal/storage/serde.go
  internal/storage/serde_events.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#37560 enhance: [2.4] RBAC custom privilege group
  go.mod
  go.sum
  internal/datacoord/mock_test.go
  internal/datanode/importv2/pool_test.go
  internal/distributed/proxy/httpserver/constant.go
  internal/distributed/proxy/httpserver/handler_v2.go
  internal/distributed/proxy/httpserver/handler_v2_test.go
  internal/distributed/proxy/httpserver/request_v2.go
  internal/distributed/proxy/service.go
  internal/distributed/rootcoord/client/client.go
  internal/distributed/rootcoord/client/client_test.go
  internal/distributed/rootcoord/service.go
  internal/metastore/catalog.go
  internal/metastore/kv/rootcoord/kv_catalog.go
  internal/metastore/kv/rootcoord/kv_catalog_test.go
  internal/metastore/kv/rootcoord/rootcoord_constant.go
  internal/metastore/mocks/mock_rootcoord_catalog.go
  internal/mocks/mock_proxy.go
  internal/mocks/mock_querynode.go
  internal/mocks/mock_querynode_client.go
  internal/mocks/mock_rootcoord.go
  internal/mocks/mock_rootcoord_client.go
  internal/proto/internal.proto
  internal/proto/root_coord.proto
  internal/proxy/impl.go
  internal/proxy/meta_cache.go
  internal/proxy/rootcoord_mock_test.go
  internal/proxy/util.go
  internal/proxy/util_test.go
  internal/rootcoord/meta_table.go
  internal/rootcoord/meta_table_test.go
  internal/rootcoord/mock_test.go
  internal/rootcoord/mocks/meta_table.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
  internal/util/mock/grpc_rootcoord_client.go
  pkg/go.mod
  pkg/go.sum
  pkg/metrics/rootcoord_metrics.go
  pkg/util/constant.go
  pkg/util/funcutil/policy.go
  tests/integration/rbac/privilege_group_test.go
  tests/integration/rbac/rbac_backup_test.go
Labels: kind/enhancement, area/dependency, sig/testing, size/XXL, approved, lgtm, area/test, ci-passed, area/internal-api, dco-passed, test/integration

#37567 enhance: Generate milvusclient mockery with latest proto
  client/Makefile
  client/go.mod
  client/go.sum
  client/milvusclient/mock_milvus_server_test.go
  tests/go_client/go.mod
  tests/go_client/go.sum
Labels: kind/enhancement, area/dependency, sig/testing, size/XXL, approved, lgtm, area/test, ci-passed, dco-passed, area/compilation

#37538 fix: Lost loading collection's updateTs after qc restart
  internal/querycoordv2/meta/collection_manager.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#37306 fix: l0RowCount metrics value always empty
  internal/datacoord/meta.go
  internal/datacoord/meta_test.go
  internal/datacoord/segment_info.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#37564 enhance: refactor the consumer grpc proto for reusing grpc stream for multi-consumer
  internal/datacoord/services.go
  internal/datacoord/services_test.go
  internal/distributed/streaming/append.go
  internal/distributed/streaming/internal/consumer/consumer.go
  internal/distributed/streaming/internal/consumer/consumer_impl.go
  internal/distributed/streaming/streaming.go
  internal/distributed/streaming/txn.go
  internal/distributed/streaming/util.go
  internal/distributed/streaming/wal.go
  internal/streamingnode/client/handler/consumer/consumer_impl.go
  internal/streamingnode/client/handler/consumer/consumer_test.go
  internal/streamingnode/client/handler/handler_client.go
  internal/streamingnode/client/handler/handler_client_impl.go
  internal/streamingnode/client/handler/handler_client_test.go
  internal/streamingnode/server/flusher/flusherimpl/channel_lifetime.go
  internal/streamingnode/server/service/handler/consumer/consume_grpc_server_helper.go
  internal/streamingnode/server/service/handler/consumer/consume_server.go
  internal/streamingnode/server/service/handler/consumer/consume_server_test.go
  internal/streamingnode/server/wal/adaptor/scanner_adaptor.go
  internal/streamingnode/server/wal/adaptor/scanner_adaptor_test.go
  internal/streamingnode/server/wal/adaptor/wal_adaptor_test.go
  internal/streamingnode/server/wal/adaptor/wal_test.go
  internal/streamingnode/server/wal/scanner.go
  internal/util/streamingutil/service/contextutil/create_consumer_test.go
  pkg/streaming/proto/streaming.proto
  pkg/streaming/util/options/deliver.go
  pkg/streaming/util/options/deliver_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#37580 fix: Lost loading collection's updateTs after qc restart (#37538)
  internal/querycoordv2/meta/collection_manager.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#37423 fix: use yaml.v2 as yaml parser
  pkg/config/config.go
  pkg/config/file_source.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#37570 enhance: enable multiple chunked segment by default
  configs/milvus.yaml
  internal/core/src/segcore/SegmentChunkReader.cpp
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#37572 test: Add nullable test cases for bulk writer
  tests/python_client/testcases/test_bulk_insert.py
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#37483 enhance:refine group_strict_size parameter(#37482)
  internal/core/src/common/QueryInfo.h
  internal/core/src/exec/operator/groupby/SearchGroupByOperator.cpp
  internal/core/src/exec/operator/groupby/SearchGroupByOperator.h
  internal/core/src/query/PlanProto.cpp
  internal/core/unittest/test_group_by.cpp
  internal/distributed/proxy/httpserver/constant.go
  internal/distributed/proxy/httpserver/handler_v2.go
  internal/distributed/proxy/httpserver/request_v2.go
  internal/proto/plan.proto
  internal/proxy/search_util.go
  internal/proxy/task.go
  internal/proxy/task_search_test.go
  tests/python_client/requirements.txt
  tests/python_client/testcases/test_mix_scenes.py
Labels: kind/enhancement, sig/testing, size/L, approved, lgtm, area/test, dco-passed

#37577 enhance: Invalidate collection cache when release collection
  internal/proxy/impl.go
  internal/querycoordv2/job/job_release.go
  internal/querycoordv2/job/job_test.go
  internal/querycoordv2/services.go
  internal/querycoordv2/services_test.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#37371 enhance: Decouple shard client manager from shard cache
  internal/proxy/lb_balancer.go
  internal/proxy/lb_policy.go
  internal/proxy/lb_policy_test.go
  internal/proxy/look_aside_balancer.go
  internal/proxy/look_aside_balancer_test.go
  internal/proxy/meta_cache.go
  internal/proxy/meta_cache_test.go
  internal/proxy/mock_cache.go
  internal/proxy/mock_lb_balancer.go
  internal/proxy/mock_shardclient_manager.go
  internal/proxy/roundrobin_balancer.go
  internal/proxy/shard_client.go
  internal/proxy/shard_client_test.go
  internal/proxy/task_policies.go
  internal/proxy/task_policies_test.go
  internal/proxy/task_query_test.go
  internal/proxy/task_search_test.go
  internal/proxy/task_statistic_test.go
Labels: kind/enhancement, size/XL, approved, lgtm, ci-passed, dco-passed

#37190 fix: Separate L0 and Mix trigger interval
  configs/milvus.yaml
  internal/datacoord/compaction_trigger.go
  internal/datacoord/compaction_trigger_v2.go
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/service_param.go
  tests/integration/compaction/compaction_test.go
  tests/integration/compaction/l2_single_compaction_test.go
Labels: kind/bug, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, test/integration

#37590 enhance: [GoSDK] support Doc-in-doc-out APIs
  client/entity/common.go
  client/entity/field.go
  client/entity/field_test.go
  client/entity/field_type.go
  client/entity/function.go
  client/entity/function_test.go
  client/entity/schema.go
  client/entity/schema_test.go
  client/entity/vectors.go
  client/milvusclient/read.go
  client/milvusclient/read_option_test.go
  client/milvusclient/read_options.go
  client/milvusclient/read_test.go
  client/milvusclient/write_options.go
  client/milvusclient/write_test.go
  pkg/common/common.go
Labels: kind/enhancement, size/XXL, approved, lgtm, ci-passed, dco-passed

#37408 enhance: Support gc with bm25 stats logs
  internal/datacoord/garbage_collector.go
  internal/metastore/kv/datacoord/kv_catalog.go
  internal/metastore/kv/datacoord/kv_catalog_test.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#36549 fix: Search may return less result after qn recover
  internal/querycoordv2/dist/dist_controller.go
  internal/querycoordv2/dist/dist_controller_test.go
  internal/querycoordv2/dist/dist_handler.go
  internal/querycoordv2/dist/dist_handler_test.go
  internal/querycoordv2/job/job_test.go
  internal/querycoordv2/meta/leader_view_manager.go
  internal/querycoordv2/meta/target_manager.go
  internal/querycoordv2/observers/collection_observer_test.go
  internal/querycoordv2/observers/target_observer.go
  internal/querycoordv2/observers/target_observer_test.go
  internal/querycoordv2/ops_service_test.go
  internal/querycoordv2/server.go
  internal/querycoordv2/server_test.go
  internal/querycoordv2/services.go
  internal/querycoordv2/services_test.go
  internal/querycoordv2/utils/util.go
  internal/querycoordv2/utils/util_test.go
  tests/integration/replicas/load/load_test.go
Labels: kind/bug, kind/enhancement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, test/integration

#37605 enhance: optimize describe collection and index (#37490)
  internal/querycoordv2/observers/target_observer.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#37606 enhance: Print results if a test fails
  tests/python_client/testcases/test_search.py
Labels: kind/enhancement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#37561 feat: add segment/channel/task/slow query render
  internal/datacoord/compaction_task_meta.go
  internal/datacoord/compaction_task_meta_test.go
  internal/datacoord/import_meta.go
  internal/datacoord/import_meta_test.go
  internal/datacoord/import_task.go
  internal/datacoord/index_meta.go
  internal/datacoord/index_meta_test.go
  internal/datacoord/job_manager_test.go
  internal/datacoord/metrics_info_test.go
  internal/datacoord/task_scheduler.go
  internal/distributed/proxy/httpserver/handler.go
  internal/flushcommon/syncmgr/sync_manager.go
  internal/http/router.go
  internal/http/webui/channels.html
  internal/http/webui/collections.html
  internal/http/webui/configs.html
  internal/http/webui/data_component.html
  internal/http/webui/header.html
  internal/http/webui/index.html
  internal/http/webui/query_component.html
  internal/http/webui/query_target.html
  internal/http/webui/segments.html
  internal/http/webui/slow_requests.html
  internal/http/webui/static/css/style.css
  internal/http/webui/static/js/common.js
  internal/http/webui/static/js/mockdata.js
  internal/http/webui/static/js/render.js
  internal/http/webui/tasks.html
  internal/http/webui/tools.html
  internal/proxy/http_req_impl.go
  internal/proxy/impl.go
  internal/proxy/proxy.go
  internal/proxy/task_search.go
  internal/proxy/task_search_test.go
  internal/querycoordv2/meta/dist_manager.go
  internal/querycoordv2/server.go
  internal/querycoordv2/task/scheduler.go
  pkg/go.mod
  pkg/go.sum
  pkg/util/metricsinfo/metric_request.go
  pkg/util/metricsinfo/metrics_info.go
  pkg/util/metricsinfo/utils.go
  pkg/util/metricsinfo/utils_test.go
  tests/integration/minicluster_v2.go
Labels: kind/feature, area/dependency, sig/testing, size/XXL, approved, lgtm, area/test, ci-passed, dco-passed, test/integration

#37507 test: update sdk version and cases
  tests/python_client/requirements.txt
  tests/python_client/testcases/test_index.py
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#37599 fix: [2.4]Fix the bug that retrieved from wrong field for L0 segments
  internal/querynodev2/handlers.go
  internal/querynodev2/services_test.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#37571 enhance: [cpp-unit-test] abort previous build if it's a PR, otherwise…
  ci/jenkins/UT-CPP.groovy
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#37610 fix: Search may return less result after qn recover (#36549)
  internal/querycoordv2/dist/dist_controller.go
  internal/querycoordv2/dist/dist_controller_test.go
  internal/querycoordv2/dist/dist_handler.go
  internal/querycoordv2/dist/dist_handler_test.go
  internal/querycoordv2/job/job_test.go
  internal/querycoordv2/meta/leader_view_manager.go
  internal/querycoordv2/meta/target_manager.go
  internal/querycoordv2/observers/collection_observer_test.go
  internal/querycoordv2/observers/target_observer.go
  internal/querycoordv2/observers/target_observer_test.go
  internal/querycoordv2/ops_service_test.go
  internal/querycoordv2/server.go
  internal/querycoordv2/server_test.go
  internal/querycoordv2/services.go
  internal/querycoordv2/services_test.go
  internal/querycoordv2/utils/util.go
  internal/querycoordv2/utils/util_test.go
  tests/integration/replicas/load/load_test.go
Labels: kind/bug, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, test/integration

#37598 fix: Fix the bug that retrieved from wrong field for L0 segments
  internal/querynodev2/handlers.go
  internal/querynodev2/services_test.go
Labels: kind/bug, area/dependency, size/S, approved, lgtm, ci-passed, dco-passed

#37595 enhance: tidy compaction logs
  internal/datacoord/compaction_policy_l0.go
  internal/datacoord/compaction_policy_single.go
  internal/datacoord/compaction_task_mix.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#37612 fix: data race when using fields_
  internal/core/src/segcore/ChunkedSegmentSealedImpl.cpp
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#37517 enhance: support null in text match index
  internal/core/src/exec/expression/Expr.h
  internal/core/src/index/TextMatchIndex.cpp
  internal/core/src/index/TextMatchIndex.h
  internal/core/src/segcore/ChunkedSegmentSealedImpl.cpp
  internal/core/src/segcore/SegmentGrowingImpl.cpp
  internal/core/src/segcore/SegmentGrowingImpl.h
  internal/core/src/segcore/SegmentSealedImpl.cpp
  internal/core/unittest/test_expr.cpp
  internal/core/unittest/test_text_match.cpp
Labels: kind/enhancement, size/XL, approved, lgtm, ci-passed, dco-passed

#37588 enhance: Enable node assign policy on resource group (#36968)
  client/go.mod
  client/go.sum
  client/mock_milvus_server_test.go
  go.mod
  go.sum
  internal/querycoordv2/meta/resource_group.go
  internal/querycoordv2/meta/resource_group_test.go
  internal/querycoordv2/meta/resource_manager.go
  internal/querycoordv2/meta/resource_manager_test.go
  internal/querycoordv2/observers/resource_observer_test.go
  internal/querycoordv2/server.go
  internal/querycoordv2/session/node_manager.go
  internal/util/sessionutil/session_util.go
  internal/util/sessionutil/session_util_test.go
  pkg/go.mod
  pkg/go.sum
Labels: kind/enhancement, area/dependency, size/XXL, approved, lgtm, ci-passed, dco-passed

#37627 enhance: [2.4] Add cgo call metrics for load/write API (#37405)
  internal/querynodev2/segments/load_index_info.go
  internal/querynodev2/segments/segment.go
  pkg/metrics/metrics.go
  pkg/metrics/querynode_metrics.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#37642 fix: Balance channel may stuck at increasing replica number case
  internal/querycoordv2/observers/target_observer.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#37589 fix: refuse schedule compaction tasks if there is no slot
  internal/datacoord/compaction.go
  internal/datacoord/compaction_task_mix.go
  internal/datacoord/compaction_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#37608 fix: config file validator missed the file tail validation
  cmd/tools/config/generate.go
  cmd/tools/config/generate_test.go
  configs/milvus.yaml
  pkg/util/paramtable/knowhere_param.go
  pkg/util/paramtable/param_item.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#37487 fix: some error in restful
  internal/distributed/proxy/httpserver/constant.go
  internal/distributed/proxy/httpserver/handler_v1.go
  internal/distributed/proxy/httpserver/handler_v1_test.go
  internal/distributed/proxy/httpserver/handler_v2.go
  internal/distributed/proxy/httpserver/handler_v2_test.go
  internal/distributed/proxy/httpserver/utils.go
  internal/distributed/proxy/httpserver/utils_test.go
  tests/go_client/testcases/collection_test.go
  tests/restful_client/testcases/test_vector_operations.py
Labels: kind/bug, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#37618 test: Add expression template tests and use error msg only as assertion
  tests/python_client/check/func_check.py
  tests/python_client/common/code_mapping.py
  tests/python_client/common/common_func.py
  tests/python_client/common/common_type.py
  tests/python_client/milvus_client/test_milvus_client_alias.py
  tests/python_client/milvus_client/test_milvus_client_collection.py
  tests/python_client/milvus_client/test_milvus_client_index.py
  tests/python_client/milvus_client/test_milvus_client_insert.py
  tests/python_client/milvus_client/test_milvus_client_partition.py
  tests/python_client/testcases/test_alias.py
  tests/python_client/testcases/test_collection.py
  tests/python_client/testcases/test_compaction.py
  tests/python_client/testcases/test_connection.py
  tests/python_client/testcases/test_delete.py
  tests/python_client/testcases/test_field_partial_load.py
  tests/python_client/testcases/test_index.py
  tests/python_client/testcases/test_insert.py
  tests/python_client/testcases/test_mix_scenes.py
  tests/python_client/testcases/test_partition.py
  tests/python_client/testcases/test_query.py
  tests/python_client/testcases/test_search.py
  tests/python_client/testcases/test_utility.py
Labels: sig/testing, size/XXL, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#37641 fix: Balance channel may stuck at increasing replica number case
  internal/querycoordv2/observers/target_observer.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#37591 fix: Sparse to use CC index as growing/temp index
  internal/core/src/segcore/IndexConfigGenerator.cpp
  internal/core/src/segcore/IndexConfigGenerator.h
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed, area/compilation

#37576 fix: make NewDataSyncService idempotent of dispatcher
  internal/flushcommon/pipeline/data_sync_service.go
  internal/flushcommon/pipeline/flow_graph_dd_node.go
  internal/flushcommon/pipeline/flow_graph_dd_node_test.go
  internal/flushcommon/pipeline/flow_graph_dmstream_input_node.go
  internal/flushcommon/pipeline/flow_graph_dmstream_input_node_test.go
  internal/flushcommon/pipeline/flow_graph_time_tick_node.go
  internal/streamingnode/server/flusher/flusherimpl/channel_lifetime.go
  pkg/mq/msgdispatcher/manager.go
  pkg/mq/msgdispatcher/manager_test.go
Labels: kind/bug, area/dependency, size/L, approved, lgtm, ci-passed, dco-passed

#37617 fix: Correct varchar primarykey size calculation
  internal/flushcommon/writebuffer/delta_buffer_test.go
  internal/querynodev2/delegator/deletebuffer/delete_buffer_test.go
  internal/storage/primary_key.go
  internal/storage/primary_key_test.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#37619 fix: [cp24]Correct varchar primarykey size calculation
  internal/datanode/writebuffer/delta_buffer_test.go
  internal/querynodev2/delegator/deletebuffer/delete_buffer_test.go
  internal/storage/primary_key.go
  internal/storage/primary_key_test.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#37650 fix: brute force bm25 search lack avgdl param
  internal/core/src/query/SearchBruteForce.cpp
  internal/querynodev2/delegator/util.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#37600 enhance: Add more expr ut for chunked segment
  internal/core/unittest/test_chunked_segment.cpp
Labels: kind/enhancement, area/dependency, size/L, approved, lgtm, ci-passed, dco-passed

#37647 enhance: [cp24]tidy compaction logs (#37595)
  internal/datacoord/compaction_policy_l0.go
  internal/datacoord/compaction_policy_single.go
  internal/datacoord/compaction_task_mix.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#37657 fix: Int64 overflow in JSON encoding
  cmd/tools/migration/meta/210_to_220.go
  go.mod
  go.sum
  internal/datacoord/compaction_task_meta.go
  internal/datacoord/compaction_trigger_test.go
  internal/datacoord/garbage_collector_test.go
  internal/datacoord/index_meta.go
  internal/datacoord/index_meta_test.go
  internal/datacoord/index_service.go
  internal/datacoord/index_service_test.go
  internal/datacoord/metrics_info.go
  internal/datacoord/metrics_info_test.go
  internal/datacoord/server_test.go
  internal/datacoord/services_test.go
  internal/datacoord/task_scheduler_test.go
  internal/distributed/proxy/httpserver/handler.go
  internal/distributed/proxy/service.go
  internal/flushcommon/pipeline/flow_graph_manager.go
  internal/flushcommon/pipeline/flow_graph_manager_test.go
  internal/flushcommon/syncmgr/task.go
  internal/flushcommon/syncmgr/task_test.go
  internal/http/router.go
  internal/http/webui/collections.html
  internal/http/webui/static/js/common.js
  internal/http/webui/static/js/mockdata.js
  internal/http/webui/static/js/render.js
  internal/http/webui/tools.html
  internal/metastore/kv/datacoord/kv_catalog_test.go
  internal/metastore/model/index.go
  internal/metastore/model/segment_index.go
  internal/metastore/model/segment_index_test.go
  internal/proxy/http_req_impl.go
  internal/proxy/http_req_impl_test.go
  internal/proxy/impl.go
  internal/proxy/task_database_test.go
  internal/querycoordv2/meta/segment_dist_manager.go
  internal/querycoordv2/meta/segment_dist_manager_test.go
  internal/querycoordv2/task/task.go
  internal/querycoordv2/task/task_test.go
  internal/querynodev2/metrics_info_test.go
  internal/querynodev2/pipeline/manager.go
  internal/util/metrics/utils.go
  pkg/go.mod
  pkg/go.sum
  pkg/util/metricsinfo/metrics_info.go
  pkg/util/metricsinfo/utils.go
  pkg/util/tsoutil/tso.go
  pkg/util/typeutil/time.go
Labels: kind/bug, area/dependency, size/XXL, approved, lgtm, ci-passed, dco-passed

#37688 enhance: update knowhere version
  internal/core/thirdparty/knowhere/CMakeLists.txt
  internal/proxy/task_test.go
  tests/python_client/conftest.py
Labels: kind/enhancement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed, area/compilation

#37692 fix: Modify the batchsize of writer to timely flushing binlogs
  internal/indexnode/task_stats.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#37694 fix: Delegator stuck at unserviceable status
  internal/querycoordv2/dist/dist_handler.go
  internal/querycoordv2/observers/target_observer.go
  tests/integration/target/target_test.go
Labels: kind/bug, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed, test/integration

#37678 enhance: Enable `RemoteLoad` l0 forward policy by default
  configs/milvus.yaml
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#37691 fix: Store default value if `ErrKeyNotFound` is returned
  pkg/config/manager.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#37686 fix: Fix query failure with inverted index
  internal/core/src/exec/expression/CompareExpr.h
  internal/core/unittest/test_chunked_segment.cpp
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#37525 fix: Change memoryCheck write lock to read lock
  internal/datacoord/services.go
  internal/flushcommon/syncmgr/task.go
  internal/flushcommon/writebuffer/manager.go
Labels: kind/bug, kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#37704 enhance: Optimize GetChunkIDByOffset and add ut
  internal/core/src/mmap/ChunkedColumn.h
  internal/core/unittest/CMakeLists.txt
  internal/core/unittest/test_chunked_column.cpp
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed, area/compilation
