Repository milvus-io/milvus, pull requests merged in 2024-05, with the labels that each got.

#32739 enhance: resource group unittest refactory
  internal/querycoordv2/observers/resource_observer_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#32740 enhance: resource group unittest refactory
  internal/querycoordv2/observers/resource_observer_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#32712 fix: Refine index param check for Create/Alter Index
  internal/datacoord/index_service.go
  internal/datacoord/index_service_test.go
  internal/datacoord/indexnode_manager.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#32781 test: Fix a deep copy issue when getting search params
  tests/python_client/common/common_func.py
  tests/python_client/common/common_type.py
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#32780 test: update test cases
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#32785 fix mmap
  internal/core/thirdparty/knowhere/CMakeLists.txt
Labels: size/XS, area/compilation

#32767 fix: remove flaky sparse integration test
  tests/integration/sparse/sparse_test.go
Labels: kind/bug, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed, manual-pass, test/integration

#32779 improve: change some frequent log to debug
  internal/datanode/flow_graph_dd_node.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass, do-not-merge/invalid-pr-format

#32777 enhance: check field data type of input
  internal/proxy/validate_util.go
  internal/proxy/validate_util_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#32794 fix: remove flaky sparse integration test
  tests/integration/sparse/sparse_test.go
Labels: kind/bug, sig/testing, size/S, area/test, dco-passed, test/integration

#32725 enhance: Remove legacy L0 segment if watch failed
  internal/querynodev2/services.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#32746 fix: Add Wrapper and Keepalive for CTraceContext ids
  internal/querynodev2/segments/load_index_info.go
  internal/querynodev2/segments/segment.go
  internal/querynodev2/segments/trace.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#32770 fix: Validate num of rows for insert field data with schema
  internal/proxy/validate_util.go
  pkg/util/funcutil/func.go
  pkg/util/funcutil/func_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#32795 fix: Fix scalar auto index config incorrect version
  pkg/util/paramtable/autoindex_param.go
Labels: kind/bug, size/XS, approved, lgtm, dco-passed

#32796 fix: [Pick]Fix scalar auto index config incorrect version
  pkg/util/paramtable/autoindex_param.go
Labels: kind/bug, size/XS, approved, lgtm, dco-passed

#32775 fix: skip to check auto id when inserting data
  internal/proxy/util.go
  internal/proxy/util_test.go
Labels: kind/bug, kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#32797 enhance: Fix compilation error
  internal/querynodev2/services.go
Labels: kind/bug, kind/enhancement, kind/improvement, size/XS, do-not-merge/missing-related-issue, dco-passed

#32680 enhance: add the config to control the way when fail to init plugin
  internal/util/hookutil/hook.go
  internal/util/hookutil/hook_test.go
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#32738 fix: Make the dynamic column optional in parquet import
  internal/util/importutilv2/common/util.go
  internal/util/importutilv2/numpy/reader.go
  internal/util/importutilv2/numpy/util.go
  internal/util/importutilv2/parquet/reader.go
  internal/util/importutilv2/parquet/util.go
  tests/integration/import/dynamic_field_test.go
Labels: kind/bug, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, test/integration

#32734 enhance: add more trace for search & query
  internal/core/src/segcore/Reduce.cpp
  internal/core/src/segcore/Reduce.h
  internal/core/src/segcore/SegmentInterface.cpp
  internal/core/src/segcore/SegmentInterface.h
  internal/core/src/segcore/reduce_c.cpp
  internal/core/src/segcore/reduce_c.h
  internal/core/src/segcore/segment_c.cpp
  internal/core/unittest/test_c_api.cpp
  internal/core/unittest/test_group_by.cpp
  internal/proxy/task_search.go
  internal/querynodev2/segments/reduce.go
  internal/querynodev2/segments/result.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#32706 test: add testcase for import without meta when enabled dynamic
  tests/python_client/common/bulk_insert_data.py
  tests/python_client/testcases/test_bulk_insert.py
Labels: sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#32804 test:fix retry for network error
  tests/restful_client/api/milvus.py
  tests/restful_client/requirements.txt
  tests/restful_client_v2/api/milvus.py
  tests/restful_client_v2/requirements.txt
  tests/scripts/ci_e2e_4am.sh
Labels: sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#32789 enhance: check field data type of input (#32777)
  internal/proxy/validate_util.go
  internal/proxy/validate_util_test.go
Labels: kind/enhancement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, area/compilation, test/integration

#32790 enhance: check field data type of input (#32777)
  internal/proxy/validate_util.go
  internal/proxy/validate_util_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#32798 fix: [2.4] cherry-pick three litter pr
  internal/proxy/task.go
  internal/proxy/task_test.go
  internal/proxy/util.go
  internal/proxy/util_test.go
  internal/util/hookutil/hook.go
  internal/util/hookutil/hook_test.go
  pkg/util/paramtable/component_param.go
  tests/python_client/testcases/test_partition_key.py
Labels: kind/bug, kind/improvement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#32522 enhance: add type info for payload writer error message and add log when querynode find new collection
  internal/querynodev2/segments/collection.go
  internal/storage/payload_writer.go
  internal/storage/payload_writer_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#32805 fix: Unify querynode metrics cleanup in collection release
  internal/querynodev2/pipeline/pipeline.go
  internal/querynodev2/segments/collection.go
  pkg/metrics/querynode_metrics.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#32471 Refine datanode major compaction
  internal/datacoord/analyze_meta.go
  internal/datacoord/analyze_meta_test.go
  internal/datacoord/clustering_compaction_manager.go
  internal/datacoord/garbage_collector.go
  internal/datacoord/index_meta.go
  internal/datacoord/index_service.go
  internal/datacoord/task_analyze.go
  internal/datacoord/task_index.go
  internal/datacoord/task_scheduler_test.go
  internal/datanode/clustering_compactor.go
  internal/indexnode/indexnode_service.go
  internal/indexnode/task_analyze.go
  internal/indexnode/taskinfo_ops.go
  internal/proto/data_coord.proto
  internal/proto/index_coord.proto
  pkg/common/common.go
Labels: size/XXL, area/internal-api

#32709 fix: add request resource timeout for lazy load, refactor context usage in cache
  configs/milvus.yaml
  internal/querynodev2/segments/manager.go
  internal/querynodev2/segments/retrieve.go
  internal/querynodev2/segments/search.go
  internal/querynodev2/segments/segment_loader.go
  internal/querynodev2/segments/utils.go
  pkg/util/cache/cache.go
  pkg/util/cache/cache_test.go
  pkg/util/contextutil/context_util.go
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/component_param_test.go
  pkg/util/paramtable/param_item.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed, area/compilation

#32802 fix: Make the dynamic column optional in parquet import (#32738)
  internal/util/importutilv2/common/util.go
  internal/util/importutilv2/numpy/reader.go
  internal/util/importutilv2/numpy/util.go
  internal/util/importutilv2/parquet/reader.go
  internal/util/importutilv2/parquet/util.go
  tests/integration/import/dynamic_field_test.go
Labels: kind/bug, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, manual-pass, test/integration

#32704 enhance: Remove deprecated EnableIndex
  internal/querycoordv2/meta/coordinator_broker.go
  internal/querynodev2/segments/mock_data.go
  internal/querynodev2/segments/segment.go
  internal/querynodev2/segments/segment_loader.go
Labels: kind/enhancement, kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#32730 fix: Fix cannot specify partition name in binlog import
  internal/proxy/impl.go
  tests/integration/import/binlog_test.go
  tests/restful_client_v2/testcases/test_jobs_operation.py
Labels: kind/bug, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed, test/integration

#32800 fix: Compaction trigger choose 2 same segments
  internal/datacoord/compaction_trigger.go
  internal/datacoord/compaction_trigger_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#32749 enhance: Add `metautil.Channel` to convert string compare to int
  internal/querynodev2/delegator/delegator_data_test.go
  internal/querynodev2/local_worker_test.go
  internal/querynodev2/segments/manager.go
  internal/querynodev2/segments/manager_test.go
  internal/querynodev2/segments/mock_data.go
  internal/querynodev2/segments/mock_segment.go
  internal/querynodev2/segments/reduce_test.go
  internal/querynodev2/segments/retrieve_test.go
  internal/querynodev2/segments/search_test.go
  internal/querynodev2/segments/segment.go
  internal/querynodev2/segments/segment_interface.go
  internal/querynodev2/segments/segment_l0.go
  internal/querynodev2/segments/segment_loader.go
  internal/querynodev2/segments/segment_loader_test.go
  internal/querynodev2/segments/segment_test.go
  internal/querynodev2/server_test.go
  internal/querynodev2/services.go
  internal/querynodev2/services_test.go
  pkg/util/metautil/channel.go
  pkg/util/metautil/channel_test.go
Labels: kind/enhancement, size/XL, approved, lgtm, ci-passed, dco-passed, manual-pass

#32799 fix: [2.4]Validate num of rows for insert field data with schema (#32770)
  internal/proxy/validate_util.go
  pkg/util/funcutil/func.go
  pkg/util/funcutil/func_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#32808 enhance: remove deprecated api
  internal/core/src/segcore/SegmentInterface.cpp
  internal/core/src/segcore/SegmentInterface.h
  internal/core/unittest/test_float16.cpp
  internal/core/unittest/test_retrieve.cpp
  internal/core/unittest/test_string_expr.cpp
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#32642 enhance: Reuse hash locations during access bloom fitler
  internal/querynodev2/delegator/delegator_data.go
  internal/querynodev2/delegator/delegator_data_test.go
  internal/querynodev2/delegator/delegator_test.go
  internal/querynodev2/pkoracle/bloom_filter_set.go
  internal/querynodev2/pkoracle/bloom_filter_set_test.go
  internal/querynodev2/pkoracle/candidate.go
  internal/querynodev2/pkoracle/key.go
  internal/querynodev2/pkoracle/pk_oracle.go
  internal/querynodev2/pkoracle/pk_oracle_test.go
  internal/querynodev2/segments/mock_segment.go
  internal/querynodev2/segments/segment.go
  internal/querynodev2/segments/segment_interface.go
  internal/querynodev2/segments/segment_loader.go
  internal/querynodev2/segments/segment_test.go
  internal/storage/pk_statistics.go
Labels: kind/enhancement, size/L, lgtm, dco-passed

#32812 enhance: enable stopping balance after balance has been suspended
  internal/querycoordv2/checkers/balance_checker.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#32620 enhance: add the cost response for the rest api
  internal/distributed/proxy/httpserver/constant.go
  internal/distributed/proxy/httpserver/handler_v2.go
  internal/distributed/proxy/httpserver/request_v2.go
  internal/proxy/util.go
  internal/proxy/util_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#32828 enhance: Remove deprecated EnableIndex (#32704)
  internal/querycoordv2/meta/coordinator_broker.go
  internal/querynodev2/segments/mock_data.go
  internal/querynodev2/segments/segment.go
  internal/querynodev2/segments/segment_loader.go
Labels: kind/enhancement, kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#32829 fix: Fix cannot specify partition name in binlog import (#32730)
  internal/proxy/impl.go
  tests/integration/import/binlog_test.go
  tests/restful_client_v2/testcases/test_jobs_operation.py
Labels: kind/bug, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed, test/integration

#32836 enhance: [skip e2e] disable unstable ut temporarily
  internal/core/unittest/test_indexing.cpp
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#32839 enhance: Change ddl log to info (#32838)
  internal/datacoord/meta.go
Labels: kind/enhancement, kind/improvement, size/XS, dco-passed

#32838 enhance: Change ddl log to info
  internal/datacoord/meta.go
Labels: kind/enhancement, kind/improvement, size/XS, approved, lgtm, dco-passed

#32841 enhance: [2.4] add the cost response for the rest api
  internal/distributed/proxy/httpserver/constant.go
  internal/distributed/proxy/httpserver/handler_v2.go
  internal/distributed/proxy/httpserver/request_v2.go
  internal/proxy/util.go
  internal/proxy/util_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#32840 fix: [2.3] skip to check auto id when inserting data
  internal/proxy/util.go
  internal/proxy/util_test.go
Labels: kind/bug, kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#32819 enhance: The LRU cache evicts items and retries loading if the disk limit is reached.
  internal/querynodev2/segments/segment_loader.go
  pkg/util/cache/cache.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#32845 fix: [2.3] Validate num of rows for insert field data with schema (#32770)
  internal/proxy/validate_util.go
  pkg/util/funcutil/func.go
  pkg/util/funcutil/func_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#32690 fix: [2.3] Make compactor able to clear empty segments
  internal/datanode/compactor.go
  internal/datanode/compactor_test.go
  internal/datanode/flow_graph_dd_node.go
  internal/datanode/flow_graph_insert_buffer_node.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed, kind/branch-feature

#32852 enhance: [2.4] Remove legacy L0 segment if watch failed (#32725)
  internal/querynodev2/services.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#32858 fix: make sure inverted index has only one segment
  internal/core/thirdparty/tantivy/tantivy-binding/Cargo.lock
  internal/core/thirdparty/tantivy/tantivy-binding/Cargo.toml
  internal/core/thirdparty/tantivy/tantivy-binding/src/index_reader.rs
  internal/core/thirdparty/tantivy/tantivy-binding/src/index_reader_c.rs
  internal/core/thirdparty/tantivy/tantivy-binding/src/index_writer.rs
  internal/core/thirdparty/tantivy/tantivy-binding/src/lib.rs
  internal/core/thirdparty/tantivy/tantivy-binding/src/log.rs
  internal/core/thirdparty/tantivy/tantivy-binding/src/vec_collector.rs
  internal/core/thirdparty/tantivy/test.cpp
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#32831 enhance: Improve datacoord segment filtering with collection
  internal/datacoord/broker/mock_coordinator_broker.go
  internal/datacoord/compaction.go
  internal/datacoord/compaction_test.go
  internal/datacoord/compaction_trigger_v2_test.go
  internal/datacoord/compaction_view_manager_test.go
  internal/datacoord/garbage_collector.go
  internal/datacoord/garbage_collector_test.go
  internal/datacoord/handler.go
  internal/datacoord/index_service.go
  internal/datacoord/index_service_test.go
  internal/datacoord/meta.go
  internal/datacoord/mock_compaction_meta.go
  internal/datacoord/segment_info.go
  internal/datacoord/segment_operator.go
Labels: kind/enhancement, size/XXL, approved, lgtm, ci-passed, dco-passed

#32558 feat: [2.4]datacoord/node watch based on rpc
  Makefile
  internal/datacoord/channel.go
  internal/datacoord/channel_manager.go
  internal/datacoord/channel_manager_factory.go
  internal/datacoord/channel_manager_test.go
  internal/datacoord/channel_manager_v2.go
  internal/datacoord/channel_manager_v2_test.go
  internal/datacoord/channel_store.go
  internal/datacoord/channel_store_test.go
  internal/datacoord/channel_store_v2.go
  internal/datacoord/channel_store_v2_test.go
  internal/datacoord/cluster.go
  internal/datacoord/cluster_test.go
  internal/datacoord/mock_channel_store.go
  internal/datacoord/mock_channelmanager.go
  internal/datacoord/mock_cluster.go
  internal/datacoord/mock_subcluster.go
  internal/datacoord/policy.go
  internal/datacoord/policy_test.go
  internal/datacoord/server.go
  internal/datacoord/server_test.go
  internal/datacoord/services.go
  internal/datacoord/services_test.go
  internal/datacoord/session.go
  internal/datacoord/session_manager_test.go
  internal/datanode/channel_manager.go
  internal/datanode/channel_manager_test.go
  internal/datanode/data_node.go
  internal/datanode/event_manager.go
  internal/datanode/event_manager_test.go
  internal/datanode/mock_test.go
  internal/datanode/services.go
  internal/datanode/services_test.go
  internal/distributed/datacoord/service.go
  internal/distributed/datanode/service.go
  pkg/util/conc/pool.go
  pkg/util/paramtable/component_param.go
  tests/integration/minicluster_v2.go
  tests/integration/watchcompatibility/watch_test.go
Labels: kind/feature, area/dependency, sig/testing, size/XXL, approved, lgtm, area/test, ci-passed, area/internal-api, dco-passed, area/compilation, test/integration, do-not-merge/missing-related-pr

#32865 fix: Make syncmgr lock key before returning future
  internal/datanode/syncmgr/key_lock_dispatcher.go
  internal/datanode/syncmgr/mock_task.go
  internal/datanode/syncmgr/sync_manager.go
  internal/datanode/syncmgr/sync_manager_test.go
  internal/datanode/syncmgr/task.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#32846 enhance: [2.4]trigger compaction by size and fix (#32326)
  internal/datacoord/compaction_trigger.go
  internal/datacoord/compaction_trigger_test.go
Labels: kind/enhancement, size/XL, approved, lgtm, ci-passed, dco-passed

#32882 fix: [2.4] Make syncmgr lock key before returning future (#32865)
  internal/datanode/syncmgr/key_lock_dispatcher.go
  internal/datanode/syncmgr/mock_task.go
  internal/datanode/syncmgr/sync_manager.go
  internal/datanode/syncmgr/sync_manager_test.go
  internal/datanode/syncmgr/task.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#32822 enhance: optimize vector offsets handling for parquet
  internal/util/importutilv2/parquet/field_reader.go
  internal/util/importutilv2/parquet/reader_test.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#32874 enhance: [2.4] Improve datacoord segment filtering with collection (#32831)
  internal/datacoord/broker/mock_coordinator_broker.go
  internal/datacoord/compaction.go
  internal/datacoord/compaction_test.go
  internal/datacoord/compaction_trigger_v2_test.go
  internal/datacoord/compaction_view_manager_test.go
  internal/datacoord/garbage_collector.go
  internal/datacoord/garbage_collector_test.go
  internal/datacoord/handler.go
  internal/datacoord/index_service.go
  internal/datacoord/index_service_test.go
  internal/datacoord/meta.go
  internal/datacoord/mock_compaction_meta.go
  internal/datacoord/segment_info.go
  internal/datacoord/segment_operator.go
Labels: kind/enhancement, size/XXL, approved, lgtm, ci-passed, dco-passed

#32883 fix: [skip-e2e] Fix unstable policy_test
  internal/datacoord/policy_test.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#32884 fix: [skip-e2e][2.4] Fix unstable policy_test
  internal/datacoord/policy_test.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#32887 enhance: Avoid iteration over channel results when update leaderview
  internal/querycoordv2/dist/dist_handler.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#32885 doc: fix typos in design docs
  docs/design_docs/20210521-datanode_recovery_design.md
  docs/developer_guides/appendix_a_basic_components.md
  docs/developer_guides/chap02_schema.md
Labels: size/S, approved, lgtm, ci-passed, dco-passed, kind/doc

#32891 fix: Make SyncManager callback func ignore nil error
  internal/datanode/syncmgr/sync_manager.go
  internal/datanode/syncmgr/sync_manager_test.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#32867 enhance: change prune ratio meaning(#32866)
  internal/querynodev2/delegator/delegator_data_test.go
  internal/querynodev2/delegator/segment_pruner.go
  internal/querynodev2/delegator/segment_pruner_test.go
  internal/querynodev2/segments/manager.go
  pkg/util/cache/cache_test.go
  pkg/util/paramtable/component_param.go
Labels: size/M, lgtm

#32892 enhance: Utilize coll2replica mapping when getting rg by collection
  internal/querycoordv2/meta/replica_manager.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#32912 enhance: add metrics for segment prune latency(#30376)
  internal/querynodev2/delegator/segment_pruner.go
  pkg/metrics/querynode_metrics.go
Labels: size/S

#32906 enhance: update knowhere and remove unused function
  internal/core/src/storage/DiskFileManagerImpl.h
  internal/core/thirdparty/knowhere/CMakeLists.txt
Labels: size/S, area/compilation

#32634 Refine state machine
  internal/datacoord/clustering_compaction_job.go
  internal/datacoord/clustering_compaction_manager.go
  internal/datacoord/compaction_trigger.go
  internal/datacoord/meta.go
  internal/datacoord/mock_compaction_meta.go
  internal/datacoord/segment_info.go
  internal/datacoord/server.go
  internal/datacoord/services.go
  internal/datanode/clustering_compactor.go
  internal/metastore/catalog.go
  internal/metastore/kv/datacoord/constant.go
  internal/metastore/kv/datacoord/kv_catalog.go
  internal/metastore/kv/datacoord/util.go
  internal/metastore/mocks/mock_datacoord_catalog.go
  internal/proto/data_coord.proto
  pkg/util/merr/errors.go
  pkg/util/merr/utils.go
Labels: size/XXL

#32732 enhance: expose DescribeDatabase api in proxy
  go.mod
  go.sum
  internal/distributed/proxy/service.go
  internal/distributed/proxy/service_test.go
  internal/mocks/mock_proxy.go
  internal/proto/root_coord.proto
  internal/proxy/impl.go
  internal/proxy/impl_test.go
  internal/proxy/task.go
  internal/proxy/task_database.go
  internal/proxy/task_database_test.go
  internal/proxy/task_test.go
  internal/rootcoord/describe_db_task.go
  pkg/go.mod
  pkg/go.sum
Labels: kind/enhancement, area/dependency, size/XL, approved, lgtm, ci-passed, dco-passed

#32683 enhance: Add channelCPs in FlushResponse
  go.mod
  go.sum
  internal/datacoord/meta.go
  internal/datacoord/server.go
  internal/datacoord/server_test.go
  internal/datacoord/services.go
  internal/proto/data_coord.proto
  internal/proxy/task.go
  internal/rootcoord/broker.go
  pkg/go.mod
  pkg/go.sum
Labels: kind/enhancement, area/dependency, size/L, approved, lgtm, ci-passed, dco-passed, do-not-merge/missing-related-pr

#32904 fix: [2.4]Make SyncManager callback func ignore nil error (#32891)
  internal/datanode/syncmgr/sync_manager.go
  internal/datanode/syncmgr/sync_manager_test.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#32848 enhance: add lazy load retry configurations
  pkg/util/cache/cache.go
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#32844 fix: fix Indexing.Iterator ut: build index with all data at once
  internal/core/unittest/test_indexing.cpp
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed, area/compilation

#32908 test: add import checker to chaos test
  tests/python_client/chaos/checker.py
  tests/python_client/chaos/conftest.py
  tests/python_client/chaos/testcases/test_single_request_operation.py
Labels: sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#32878 fix: set channel checkpoint to delta position
  internal/querycoordv2/utils/types.go
  internal/querycoordv2/utils/types_test.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#32842 fix: fix index resource estimation
  internal/querynodev2/segments/segment_loader.go
  internal/querynodev2/segments/segment_loader_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#32930 test: add more json datatype in restful test cases
  tests/restful_client_v2/testcases/test_vector_operations.py
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#32927 fix: temporarily disable two-phase retrieval when lru is enabled
  internal/querynodev2/segments/retrieve.go
Labels: kind/bug, size/XS, dco-passed

#32857 enhance: Add update milvus yaml command to makefile
  Makefile
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed, area/compilation

#32929 fix: Segment on stopping query node can't be release successfully
  internal/querycoordv2/meta/replica.go
  internal/querycoordv2/meta/replica_test.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#32922 enhance: [2.4] Utilize coll2replica mapping when getting rg by collection (#32892)
  internal/querycoordv2/meta/replica_manager.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#32924 test: Update insert data tests and refactor some data gen functions
  tests/python_client/common/common_func.py
  tests/python_client/testcases/test_insert.py
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/XL, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#32889 enhance: remove duplicated data generation APIs for bulk insert test
  internal/util/importutilv2/binlog/reader_test.go
  internal/util/importutilv2/json/reader_test.go
  internal/util/importutilv2/numpy/reader_test.go
  internal/util/importutilv2/parquet/reader_test.go
  internal/util/testutil/test_util.go
  tests/integration/import/util_test.go
Labels: kind/enhancement, sig/testing, size/XXL, approved, lgtm, area/test, ci-passed, dco-passed, test/integration

#32931 enhance: update knowhere version
  internal/core/thirdparty/knowhere/CMakeLists.txt
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed, area/compilation

#32923 fix: Set segment to delegator failed due to wrong time unit in segment version
  internal/querycoordv2/observers/leader_observer.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#32911 enhance: Enable channel exclusive balance policy
  internal/proto/query_coord.proto
  internal/querycoordv2/balance/balance.go
  internal/querycoordv2/balance/channel_level_score_balancer.go
  internal/querycoordv2/balance/channel_level_score_balancer_test.go
  internal/querycoordv2/checkers/channel_checker.go
  internal/querycoordv2/checkers/segment_checker.go
  internal/querycoordv2/job/job_load.go
  internal/querycoordv2/meta/constant.go
  internal/querycoordv2/meta/replica.go
  internal/querycoordv2/meta/replica_manager.go
  internal/querycoordv2/meta/replica_manager_test.go
  internal/querycoordv2/meta/replica_test.go
  internal/querycoordv2/observers/collection_observer_test.go
  internal/querycoordv2/observers/replica_observer_test.go
  internal/querycoordv2/observers/target_observer_test.go
  internal/querycoordv2/server.go
  internal/querycoordv2/utils/meta.go
  internal/querycoordv2/utils/meta_test.go
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/component_param_test.go
  tests/integration/balance/channel_exclusive_balance_test.go
Labels: kind/enhancement, sig/testing, size/XXL, approved, lgtm, area/test, ci-passed, area/internal-api, dco-passed, test/integration

#32920 fix: sync milvus.yaml
  configs/milvus.yaml
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#32916 fix: lru related issue fixup patch
  internal/querycoordv2/services_test.go
  internal/querynodev2/segments/manager.go
  internal/querynodev2/segments/retrieve.go
  internal/querynodev2/segments/retrieve_test.go
  internal/querynodev2/segments/segment_loader.go
  internal/querynodev2/segments/segment_loader_test.go
  internal/querynodev2/tasks/query_task.go
  pkg/util/cache/cache.go
  pkg/util/cache/cache_test.go
  pkg/util/syncutil/context_condition_variable.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#32947 enhance: Bump milvus & proto version to v2.3.15
  go.mod
  go.sum
  pkg/common/version.go
  pkg/go.mod
  pkg/go.sum
Labels: kind/enhancement, area/dependency, size/M, approved, lgtm, ci-passed, dco-passed, kind/branch-feature

#32934 enhance: add ut and refine partitions stats(#32446)
  internal/querycoordv2/checkers/leader_checker.go
  internal/querycoordv2/task/executor.go
  internal/querynodev2/services_test.go
Labels: size/M

#32956 enhance: Use collection default consistency level for restv2
  internal/distributed/proxy/httpserver/handler_v2.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#32898 enhance:Improve load speed
  internal/querycoordv2/observers/collection_observer.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#32869 enhance: optimize plan parser pool to avoid unnessary recycle
  go.mod
  go.sum
  internal/parser/planparserv2/pool.go
  internal/parser/planparserv2/pool_test.go
Labels: kind/enhancement, area/dependency, size/L, approved, lgtm, ci-passed, dco-passed

#32928 fix:[2.4] Indexing.Iterator ut: build index with all data at once
  internal/core/unittest/test_indexing.cpp
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#32958 Fix cpp ut and add constraint for major compaction
  configs/milvus.yaml
  internal/core/unittest/CMakeLists.txt
  internal/datacoord/task_analyze.go
  pkg/util/paramtable/component_param.go
Labels: size/S, area/compilation

#32957 Fix index ut
  internal/distributed/indexnode/service_test.go
Labels: size/M

#32971 fix: Proxy crash due to shard leader cache data race
  internal/proxy/meta_cache.go
Labels: kind/bug, size/XS, approved, lgtm, dco-passed

#32948 enhance: Utilize `TestLocations` ability to accelerate write & compaction
  internal/datanode/l0_compactor.go
  internal/datanode/metacache/bloom_filter_set.go
  internal/datanode/metacache/bloom_filter_set_test.go
  internal/datanode/metacache/meta_cache.go
  internal/datanode/writebuffer/bf_write_buffer.go
  internal/datanode/writebuffer/l0_write_buffer.go
  internal/storage/pk_statistics.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#32973 enhance: Sync go.mod version & dep to main pkg
  .github/workflows/code-checker.yaml
  .github/workflows/mac.yaml
  client/example/database/main.go
  client/example/playground/main.go
  client/go.mod
  client/go.sum
  client/mock_milvus_server_test.go
Labels: kind/enhancement, area/dependency, size/L, approved, lgtm, ci-passed, dco-passed

#32871 enhance: improve reduce performance on very large topk
  internal/proxy/search_reduce_util.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#32946 enhance: remove fallback keys for config generator
  cmd/tools/config/generate.go
  configs/milvus.yaml
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/component_param_test.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#33004 fix: Fill deltalog entry num & time range in L0 compactions
  internal/datanode/l0_compactor.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#32950 enhance: change default partition num to 16 when using partition key
  client/collection_options.go
  pkg/common/common.go
  tests/integration/partitionkey/partition_key_test.go
  tests/python_client/common/common_type.py
Labels: kind/enhancement, kind/improvement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed, test/integration

#32997 enhance: add score compute consistency config for knowhere
  configs/milvus.yaml
  internal/core/src/config/ConfigKnowhere.cpp
  internal/core/src/config/ConfigKnowhere.h
  internal/core/src/segcore/segcore_init_c.cpp
  internal/core/src/segcore/segcore_init_c.h
  internal/core/thirdparty/knowhere/CMakeLists.txt
  internal/querynodev2/server.go
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/component_param_test.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed, area/compilation, manual-pass

#32985 fix: remove redundant replica recover
  internal/querycoordv2/meta/replica_manager.go
  internal/querycoordv2/observers/resource_observer.go
  internal/querycoordv2/services.go
  internal/querycoordv2/services_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#33002 fix: metric milvus_rootcoord_indexed_entity_num
  internal/datacoord/metrics_info.go
  internal/rootcoord/quota_center.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#32979 enhance: Add metrics for segment index files size
  internal/datacoord/index_builder_test.go
  internal/datacoord/meta.go
  internal/datacoord/meta_test.go
  internal/datacoord/metrics_info.go
  pkg/metrics/datacoord_metrics.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#32821 fix: Make compactor able to clear empty segments
  internal/datanode/compactor.go
  internal/datanode/compactor_test.go
  internal/datanode/flow_graph_dd_node.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#32788 enhance: Enable to upload by batch
  internal/datanode/io/binlog_io.go
  internal/datanode/l0_compactor.go
  internal/datanode/l0_compactor_test.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#33006 test: add timeout for import testcases
  tests/python_client/common/milvus_sys.py
  tests/python_client/testcases/test_bulk_insert.py
  tests/scripts/ci_e2e_4am.sh
Labels: sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#32818 enhance: Remove rootcoord from datanode broker
  internal/datanode/broker/broker.go
  internal/datanode/broker/datacoord_test.go
  internal/datanode/broker/mock_broker.go
  internal/datanode/broker/rootcoord.go
  internal/datanode/broker/rootcoord_test.go
  internal/datanode/compactor_test.go
  internal/datanode/data_node.go
  internal/datanode/flow_graph_manager_test.go
  internal/datanode/meta_service.go
  internal/datanode/meta_service_test.go
  internal/datanode/services_test.go
Labels: kind/enhancement, size/XL, approved, lgtm, ci-passed, dco-passed

#32988 enhance: clean channel node info in meta store
  configs/milvus.yaml
  internal/querycoordv2/meta/replica.go
  internal/querycoordv2/meta/replica_test.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#33014 fix: Remove channel when create flowgraph timeout
  internal/datanode/data_sync_service.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#33024 test: add timeout for GetMetrics grpc interface
  tests/python_client/common/milvus_sys.py
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#32976 fix: should init access logger before init server
  internal/distributed/proxy/service.go
  internal/proxy/proxy.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#32986 fix: Enable to balance released standby channel
  internal/datacoord/channel_manager_v2.go
  internal/datacoord/policy.go
  internal/datacoord/policy_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#33035 fix: Start `LeaderCacheObserver` before `SyncAll`
  internal/querycoordv2/server.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#33042 fix: remove busy log
  internal/querynodev2/segments/segment.go
Labels: kind/bug, size/XS, dco-passed

#32955 enhance: unify data generation test APIs
  internal/proxy/mock_test.go
  internal/proxy/msg_pack_test.go
  internal/proxy/proxy_test.go
  internal/proxy/task_insert_test.go
  internal/proxy/task_query_test.go
  internal/proxy/task_test.go
  internal/proxy/task_upsert_test.go
  internal/proxy/validate_util_test.go
  internal/querynodev2/pipeline/mock_data.go
  internal/querynodev2/segments/mock_data.go
  internal/querynodev2/segments/reduce_test.go
  internal/storage/utils_test.go
  internal/util/testutil/test_util.go
  pkg/go.mod
  pkg/go.sum
  pkg/util/testutils/gen_data.go
  pkg/util/testutils/sparse_test_utils.go
  tests/integration/util_insert.go
Labels: kind/enhancement, area/dependency, sig/testing, size/XXL, approved, lgtm, area/test, ci-passed, dco-passed, manual-pass, test/integration

#33017 enhance: use different value to get related data size according to segment type
  internal/proto/query_coord.proto
  internal/querycoordv2/utils/types.go
  internal/querynodev2/segments/retrieve.go
  internal/querynodev2/segments/utils.go
  internal/querynodev2/segments/utils_test.go
  internal/querynodev2/tasks/query_task.go
  internal/querynodev2/tasks/search_task.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, area/internal-api, dco-passed

#33023 test: Remove useless common types and refine error assert in negative cases
  tests/python_client/common/common_type.py
  tests/python_client/conftest.py
  tests/python_client/testcases/test_collection.py
  tests/python_client/testcases/test_database.py
  tests/python_client/testcases/test_index.py
  tests/python_client/testcases/test_insert.py
  tests/python_client/testcases/test_partition.py
  tests/python_client/testcases/test_query.py
  tests/python_client/testcases/test_resourcegroup.py
  tests/python_client/testcases/test_search.py
  tests/python_client/testcases/test_utility.py
Labels: sig/testing, size/XXL, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#33040 fix: etcd txn exceeds limit due to too many fields
  internal/metastore/kv/rootcoord/kv_catalog.go
  internal/metastore/kv/rootcoord/suffix_snapshot.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#33045 fix: Remove `RLock` re-entry in `GetNumRowsOfPartition`
  internal/datacoord/meta.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#33041 fix: exceed etcd limit
  internal/metastore/kv/rootcoord/kv_catalog.go
  internal/rootcoord/step_executor.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#33029 enhance: use Delete instead of DeletePartialMatch to remove metrics
  internal/datacoord/meta.go
  internal/datacoord/services.go
  internal/metastore/kv/datacoord/kv_catalog.go
  pkg/metrics/datacoord_metrics.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#33043 enhance: update knowhere new version
  internal/core/thirdparty/knowhere/CMakeLists.txt
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed, area/compilation

#33027 fix: Fix binlog import
  internal/proxy/impl.go
  tests/restful_client_v2/testcases/test_jobs_operation.py
Labels: kind/bug, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#33053 fix: Make submit idempotent
  internal/datanode/channel_manager.go
  internal/datanode/channel_manager_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#33049 fix: etcd txn exceeds limit due to too many fields (#33040)
  internal/metastore/kv/rootcoord/kv_catalog.go
  internal/metastore/kv/rootcoord/suffix_snapshot.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#33025 enhance: Add memory size for binlog
  internal/datacoord/compaction_trigger.go
  internal/datacoord/compaction_trigger_test.go
  internal/datacoord/compaction_view.go
  internal/datacoord/compaction_view_manager_test.go
  internal/datacoord/segment_info.go
  internal/datacoord/util.go
  internal/datacoord/util_test.go
  internal/datanode/binlog_io.go
  internal/datanode/l0_compactor.go
  internal/datanode/syncmgr/task.go
  internal/metastore/kv/datacoord/kv_catalog.go
  internal/proto/data_coord.proto
  internal/querycoordv2/meta/coordinator_broker.go
  internal/querynodev2/segments/index_attr_cache.go
  internal/querynodev2/segments/segment.go
  internal/querynodev2/segments/segment_loader.go
  internal/querynodev2/segments/segment_loader_test.go
  internal/querynodev2/segments/segment_test.go
  internal/querynodev2/services.go
  internal/storage/data_codec.go
  internal/storage/index_data_codec_test.go
  internal/util/indexcgowrapper/index.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#33061 fix: Fix segments lost in flush response
  internal/datacoord/services.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#33048 enhance: Bump milvus version to v2.4.2
  client/go.mod
  client/go.sum
  go.mod
  go.sum
  pkg/common/version.go
  pkg/go.mod
  pkg/go.sum
Labels: kind/enhancement, area/dependency, size/S, approved, lgtm, ci-passed, dco-passed

#33050 enhance: Reduce the frequency of index ralted logs
  internal/datacoord/index_service.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#32856 fix: validate sparse vector in search request
  internal/core/src/common/Utils.h
  internal/core/src/query/Plan.cpp
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#33063 enhance: Add `go-deadlock` as unittest only dependency
  go.mod
  go.sum
  internal/datacoord/channel_manager.go
  internal/datacoord/channel_manager_v2.go
  internal/datacoord/compaction.go
  internal/datacoord/compaction_scheduler.go
  internal/datacoord/compaction_trigger.go
  internal/datacoord/compaction_view_manager.go
  internal/datacoord/garbage_collector_test.go
  internal/datacoord/import_meta.go
  internal/datacoord/import_scheduler.go
  internal/datacoord/index_builder.go
  internal/datacoord/index_engine_version_manager.go
  internal/datacoord/indexnode_manager.go
  internal/datacoord/indexnode_manager_test.go
  internal/datacoord/meta.go
  internal/datacoord/segment_manager.go
  internal/datacoord/server.go
  internal/datacoord/server_test.go
  internal/datacoord/session.go
  internal/datacoord/session_manager.go
  pkg/go.mod
  pkg/go.sum
  pkg/util/lock/mutex.go
  pkg/util/lock/mutex_deadlock.go
  scripts/run_go_codecov.sh
  scripts/run_go_unittest.sh
Labels: kind/enhancement, area/dependency, size/L, approved, lgtm, ci-passed, dco-passed

#32945 fix: two-phase retrieval on lru-segment
  internal/querynodev2/segments/default_limit_reducer.go
  internal/querynodev2/segments/reducer.go
  internal/querynodev2/segments/reducer_test.go
  internal/querynodev2/segments/result.go
  internal/querynodev2/segments/result_test.go
  internal/querynodev2/segments/retrieve.go
  internal/querynodev2/segments/segment_do.go
  internal/querynodev2/tasks/query_task.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#32213 enhance: Support access log use stdout with write cache and auto flush as time
  internal/proxy/accesslog/global.go
  internal/proxy/accesslog/global_test.go
  internal/proxy/accesslog/writer.go
  internal/proxy/accesslog/writer_test.go
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#32086 enhance: add nullable in Field, check valid_data and fill data
  internal/metastore/model/field.go
  internal/proxy/task.go
  internal/proxy/task_insert_test.go
  internal/proxy/task_upsert_test.go
  internal/proxy/util.go
  internal/proxy/util_test.go
  internal/proxy/validate_util.go
  internal/proxy/validate_util_test.go
Labels: kind/enhancement, area/dependency, size/XXL, approved, lgtm, ci-passed, dco-passed

#33083 enhance: Refine channelCpUpdater field & test
  internal/datanode/channel_checkpoint_updater.go
  internal/datanode/channel_checkpoint_updater_test.go
  internal/datanode/data_node.go
  internal/datanode/data_sync_service_test.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#33064 enhance: Support readable JSON file import for Float16/BFloat16/SparseFloat
  internal/util/importutilv2/json/reader_test.go
  internal/util/importutilv2/json/row_parser.go
  pkg/util/testutils/gen_data.go
  pkg/util/typeutil/convension.go
  pkg/util/typeutil/conversion_test.go
  pkg/util/typeutil/schema.go
  pkg/util/typeutil/schema_test.go
  tests/integration/import/import_test.go
  tests/integration/import/util_test.go
  tests/python_client/common/bulk_insert_data.py
Labels: kind/enhancement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, test/integration

#33077 test: update pymilvus version
  tests/python_client/chaos/checker.py
  tests/python_client/requirements.txt
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#33079 test: update pymilvus version
  tests/python_client/chaos/checker.py
  tests/python_client/requirements.txt
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#33094 enhance: sync milvus proto version
  client/go.mod
  client/go.sum
  go.mod
  go.sum
  internal/proxy/validate_util_test.go
  pkg/go.mod
  pkg/go.sum
Labels: kind/enhancement, area/dependency, size/S, approved, lgtm, ci-passed, dco-passed

#32814 enhance: Skip return data distribution if no change happen
  Makefile
  internal/proto/query_coord.proto
  internal/querycoordv2/dist/dist_controller_test.go
  internal/querycoordv2/dist/dist_handler.go
  internal/querycoordv2/dist/dist_handler_test.go
  internal/querycoordv2/meta/mock_target_manager.go
  internal/querycoordv2/meta/target_manager.go
  internal/querynodev2/server.go
  internal/querynodev2/services.go
Labels: kind/enhancement, size/XXL, approved, lgtm, ci-passed, area/internal-api, dco-passed, area/compilation

#33105 enhance: Update latest sdk update to client pkg
  client/OWNERS
  client/client.go
  client/client_config.go
  client/collection.go
  client/collection_options.go
  client/column/columns.go
  client/column/columns_test.go
  client/database.go
  client/database_options.go
  client/entity/collection.go
  client/entity/schema.go
  client/index_options.go
  client/interceptors.go
  client/interceptors_test.go
  client/read.go
  client/read_options.go
  client/write.go
  client/write_test.go
Labels: kind/enhancement, size/XL, approved, lgtm, ci-passed, dco-passed

#32941 enhance: enable stopping balance after balance has been suspended (#32812)
  internal/querycoordv2/checkers/balance_checker.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#33070 enhance: use the only MaxEtcdTxnNum
  internal/metastore/kv/datacoord/kv_catalog.go
  internal/metastore/kv/rootcoord/kv_catalog.go
  internal/metastore/kv/rootcoord/kv_catalog_test.go
  internal/metastore/kv/rootcoord/suffix_snapshot.go
  pkg/util/constant.go
  pkg/util/etcd/etcd_util.go
  pkg/util/etcd/etcd_util_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#33087 fix: avoid concurrent sync and segment tasks
  internal/querycoordv2/observers/collection_observer_test.go
  internal/querycoordv2/observers/leader_observer.go
  internal/querycoordv2/observers/leader_observer_test.go
  internal/querycoordv2/server.go
  internal/querycoordv2/task/mock_scheduler.go
  internal/querycoordv2/task/scheduler.go
Labels: kind/bug, kind/feature, size/L, approved, lgtm, ci-passed, dco-passed, manual-pass, kind/branch-feature

#33065 fix: add openblas in install_deps.sh
  DEVELOPMENT.md
  README.md
  build/docker/builder/gpu/ubuntu20.04/Dockerfile
  scripts/README.md
  scripts/install_deps.sh
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#33101 enhance: Store SparseFloatVector into parquet as JSON string
  internal/util/importutilv2/json/reader_test.go
  internal/util/importutilv2/json/row_parser.go
  internal/util/importutilv2/parquet/field_reader.go
  internal/util/importutilv2/parquet/util.go
  internal/util/testutil/test_util.go
  pkg/util/typeutil/convension.go
  pkg/util/typeutil/schema.go
  pkg/util/typeutil/schema_test.go
  tests/integration/import/util_test.go
Labels: kind/enhancement, sig/testing, size/XL, approved, lgtm, area/test, ci-passed, dco-passed, manual-pass, test/integration
