Repository milvus-io/milvus, pull requests merged in 2024-08, with the labels that each got.

#35137 enhance: [2.4] Pre-allocate space for reduce data structure (#35118)
  internal/querynodev2/segments/result.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#35140 enhance: Add depguard rules to ban deprecated proto lib
  .golangci.yml
  pkg/streaming/util/message/message_builder_test.go
  tests/integration/sealpolicies/seal_by_total_growing_test.go
Labels: kind/enhancement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed, test/integration

#35092 enhance: Reduce delegator memory overloaded factor to 0.1
  configs/milvus.yaml
  internal/querycoordv2/balance/channel_level_score_balancer_test.go
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/component_param_test.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#34634 enhance: add chunk basic impl
  internal/core/src/common/CMakeLists.txt
  internal/core/src/common/Chunk.cpp
  internal/core/src/common/Chunk.h
  internal/core/src/common/ChunkFileWriter.cpp
  internal/core/src/common/ChunkFileWriter.h
  internal/core/src/common/ChunkTarget.cpp
  internal/core/src/common/ChunkTarget.h
  internal/core/src/common/ChunkWriter.cpp
  internal/core/src/common/ChunkWriter.h
  internal/core/unittest/CMakeLists.txt
  internal/core/unittest/test_chunk.cpp
Labels: kind/enhancement, size/XXL, approved, lgtm, ci-passed, dco-passed, area/compilation

#35143 test: update pymilvus version
  tests/python_client/requirements.txt
  tests/python_client/testcases/test_collection.py
  tests/python_client/testcases/test_utility.py
Labels: sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#35094 enhance: Skip updating the level that are already at the specified level
  internal/datacoord/compaction_task_clustering.go
  internal/datacoord/meta.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#35145 fix: Fix data race for clustering buffer writer
  internal/datanode/compaction/clustering_compactor.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#35152 enhance: update param documents
  cmd/tools/config-docs-generator/main.go
  configs/milvus.yaml
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/grpc_param.go
  pkg/util/paramtable/quota_param.go
  pkg/util/paramtable/service_param.go
Labels: kind/enhancement, size/XL, approved, lgtm, ci-passed, dco-passed

#35164 enhance: Reduce delegator memory overloaded factor to 0.1 (#35092)
  configs/milvus.yaml
  internal/querycoordv2/balance/channel_level_score_balancer_test.go
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/component_param_test.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#35154 fix:fix get array error for int type
  internal/core/src/index/BitmapIndex.cpp
  internal/core/src/index/BitmapIndex.h
  internal/core/unittest/test_array_bitmap_index.cpp
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#35057 enhance: the datacoord gc should fast quitable
  internal/datacoord/garbage_collector.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#35163 fix: Fix unstable TestDispatchToVchannels ut
  pkg/mq/msgdispatcher/manager_test.go
  pkg/mq/msgdispatcher/mock_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#35146 fix: [cherry-pick] Fix data race for clustering buffer writer
  internal/datanode/compaction/clustering_compactor.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#35166 enhance: Resolve ChunkFileWriter lint issue
  internal/core/src/common/ChunkFileWriter.cpp
  tests/integration/compaction/l2_single_compaction_test.go
Labels: kind/enhancement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed, manual-pass, test/integration

#35076 enhance: Change the fixed value to a ratio for clustering segment size
  configs/milvus.yaml
  internal/datacoord/compaction_policy_clustering.go
  internal/datacoord/compaction_policy_clustering_test.go
  internal/datacoord/compaction_trigger_v2.go
  internal/datacoord/compaction_trigger_v2_test.go
  internal/datacoord/segment_allocation_policy.go
  internal/datacoord/segment_allocation_policy_test.go
  internal/datacoord/task_analyze.go
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/component_param_test.go
  tests/integration/compaction/clustering_compaction_test.go
Labels: kind/enhancement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, manual-pass, test/integration

#35155 enhance:[cherry-pick] Support calculate segment maxRows with diskann
  internal/datacoord/compaction_policy_clustering.go
  internal/datacoord/compaction_trigger_v2.go
  internal/datacoord/compaction_trigger_v2_test.go
  internal/datacoord/segment_allocation_policy.go
  internal/datacoord/segment_allocation_policy_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#35185 enhance: add metric to record maxInsertRate and queryNodeMemoryHighWaterLevel
  internal/rootcoord/quota_center.go
  internal/util/quota/quota_constant.go
  pkg/metrics/proxy_metrics.go
  pkg/metrics/rootcoord_metrics.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#35188 enhance: add metric to record maxInsertRate and queryNodeMemoryHighWaterLevel (#35185)
  internal/rootcoord/quota_center.go
  internal/util/quota/quota_constant.go
  pkg/metrics/proxy_metrics.go
  pkg/metrics/rootcoord_metrics.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#35197 fix: Set legacy level to l0 segment after qc restart
  internal/proto/query_coord.proto
  internal/querycoordv2/balance/channel_level_score_balancer.go
  internal/querycoordv2/balance/multi_target_balance.go
  internal/querycoordv2/balance/rowcount_based_balancer.go
  internal/querycoordv2/balance/score_based_balancer.go
  internal/querycoordv2/dist/dist_handler.go
  internal/querycoordv2/meta/target_manager.go
  internal/querynodev2/services.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, area/internal-api, dco-passed

#35167 enhance: unify time in clustering compaction task to unix
  internal/datacoord/compaction.go
  internal/datacoord/compaction_task_clustering.go
  internal/datacoord/compaction_task_l0.go
  internal/datacoord/compaction_test.go
  internal/datacoord/compaction_trigger_v2.go
  internal/datanode/compaction/clustering_compactor_test.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#35168 enhance: [cherry-pick] unify time in clustering compaction task to unix
  internal/datacoord/compaction.go
  internal/datacoord/compaction_task_clustering.go
  internal/datacoord/compaction_test.go
  internal/datacoord/compaction_trigger_v2.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#35181 enhance: Refine param init for MmapDirPath
  internal/util/initcore/init_core.go
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/component_param_test.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#35194 enhance: Support proxy/delegator qn client pooling
  configs/milvus.yaml
  internal/proxy/shard_client.go
  internal/querynodev2/cluster/worker.go
  internal/querynodev2/server.go
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#35195 enhance: [2.4] Support proxy/delegator qn client pooling
  configs/milvus.yaml
  internal/proxy/shard_client.go
  internal/querynodev2/cluster/worker.go
  internal/querynodev2/server.go
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#34771 fix: evict paramtable cache miss
  pkg/config/manager.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#35183 enhance: Set WatchProgress for channel operation progress response
  internal/datanode/channel/channel_manager.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#34954 enhance: Avoid unnecesary syncTargetVersion func call after querycoord recover
  internal/querycoordv2/meta/target.go
  internal/querycoordv2/meta/target_manager_test.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#35153 enhance: add segment state on data coord bin log size metrics
  internal/datacoord/meta.go
  pkg/metrics/datacoord_metrics.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#35030 enhance: add valid_data in span
  internal/core/src/common/Span.h
  internal/core/src/exec/expression/CompareExpr.cpp
  internal/core/src/exec/expression/Expr.h
  internal/core/src/mmap/ChunkVector.h
  internal/core/src/mmap/Column.h
  internal/core/src/query/groupby/SearchGroupByOperator.h
  internal/core/src/segcore/ConcurrentVector.h
  internal/core/src/segcore/InsertRecord.h
  internal/core/src/segcore/SegmentGrowingImpl.cpp
  internal/core/src/segcore/SegmentGrowingImpl.h
  internal/core/src/segcore/SegmentInterface.h
  internal/core/src/segcore/SegmentSealedImpl.cpp
  internal/core/src/segcore/SegmentSealedImpl.h
  internal/core/unittest/test_common.cpp
  internal/core/unittest/test_sealed.cpp
  internal/core/unittest/test_span.cpp
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#35125 enhance: add commit time in partitionStats proto
  internal/datacoord/compaction_policy_clustering.go
  internal/datacoord/compaction_policy_clustering_test.go
  internal/datacoord/compaction_task_clustering.go
  internal/datacoord/compaction_task_clustering_test.go
  internal/datacoord/partition_stats_meta.go
  internal/datacoord/partition_stats_meta_test.go
  internal/proto/data_coord.proto
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#34328 enhance: change autoindex default metric type
  configs/milvus.yaml
  internal/datacoord/index_meta.go
  internal/datacoord/index_meta_test.go
  internal/proto/index_coord.proto
  internal/proxy/task_index.go
  internal/proxy/task_index_test.go
  pkg/common/common.go
  pkg/util/indexparamcheck/constraints.go
  pkg/util/paramtable/autoindex_param.go
  tests/python_client/testcases/test_index.py
Labels: kind/enhancement, sig/testing, size/L, approved, lgtm, area/test, area/internal-api, dco-passed

#35192 enhance: Sync otlp dependency version to fix security issue
  client/go.mod
  client/go.sum
  go.mod
  go.sum
  pkg/go.mod
  pkg/go.sum
  tests/go_client/go.mod
  tests/go_client/go.sum
Labels: kind/enhancement, area/dependency, sig/testing, size/XL, approved, lgtm, area/test, ci-passed, dco-passed

#35225 fix: Fix index memory estimation
  internal/querynodev2/segments/segment_loader.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#35214 enhance: Refine param init for MmapDirPath (#35181)
  internal/util/initcore/init_core.go
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/component_param_test.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#35206 enhance: [cherry-pick] improve ut for compaction_policy_clustering
  internal/datacoord/compaction_policy_clustering.go
  internal/datacoord/compaction_policy_clustering_test.go
  internal/datacoord/compaction_policy_l0_test.go
  internal/datacoord/compaction_trigger_v2.go
  internal/datacoord/compaction_trigger_v2_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#35231 enhance: [2.4] Set WatchProgress for channel operation progress response (#35183)
  internal/datanode/channel_manager.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#34947 fix: check collection health(queryable) fail for releasing collection
  configs/milvus.yaml
  internal/querycoordv2/balance/channel_level_score_balancer.go
  internal/querycoordv2/balance/multi_target_balance.go
  internal/querycoordv2/balance/rowcount_based_balancer.go
  internal/querycoordv2/balance/score_based_balancer.go
  internal/querycoordv2/dist/dist_controller.go
  internal/querycoordv2/job/job_load.go
  internal/querycoordv2/job/job_release.go
  internal/querycoordv2/job/undo.go
  internal/querycoordv2/meta/mock_target_manager.go
  internal/querycoordv2/meta/target_manager.go
  internal/querycoordv2/observers/collection_observer.go
  internal/querycoordv2/observers/target_observer.go
  internal/querycoordv2/server.go
  internal/querycoordv2/services_test.go
  internal/querycoordv2/task/executor.go
  internal/querycoordv2/task/scheduler.go
  internal/querycoordv2/utils/util.go
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/component_param_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#35179 fix: [cherry-pick] Maintain load idempotency even when building new indexes
  internal/querycoordv2/job/job_load.go
  internal/querycoordv2/job/job_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#35211 fix: Set legacy level to l0 segment after qc restart (#35197)
  internal/proto/query_coord.proto
  internal/querycoordv2/balance/channel_level_score_balancer.go
  internal/querycoordv2/balance/multi_target_balance.go
  internal/querycoordv2/balance/rowcount_based_balancer.go
  internal/querycoordv2/balance/score_based_balancer.go
  internal/querycoordv2/dist/dist_handler.go
  internal/querycoordv2/meta/mock_target_manager.go
  internal/querycoordv2/meta/target_manager.go
  internal/querynodev2/services.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, area/internal-api, dco-passed

#35235 enhance: add segment state on data coord bin log size metrics (#35153)
  internal/datacoord/meta.go
  pkg/metrics/datacoord_metrics.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#35189 fix: querynode hang when failing to allocate disk space for mmap(#35184)
  internal/core/src/storage/ChunkCache.cpp
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#35215 enhance: upgrade conan version
  .github/workflows/mac.yaml
  DEVELOPMENT.md
  build/docker/builder/cpu/amazonlinux2023/Dockerfile
  build/docker/builder/cpu/rockylinux8/Dockerfile
  build/docker/builder/cpu/ubuntu20.04/Dockerfile
  build/docker/builder/cpu/ubuntu22.04/Dockerfile
  build/docker/builder/gpu/ubuntu20.04/Dockerfile
  build/docker/builder/gpu/ubuntu22.04/Dockerfile
  scripts/install_deps.sh
  scripts/install_deps_msys.sh
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#35216 enhance: upgrade conan version
  .github/workflows/mac.yaml
  DEVELOPMENT.md
  build/docker/builder/cpu/amazonlinux2023/Dockerfile
  build/docker/builder/cpu/rockylinux8/Dockerfile
  build/docker/builder/cpu/ubuntu20.04/Dockerfile
  build/docker/builder/cpu/ubuntu22.04/Dockerfile
  build/docker/builder/gpu/ubuntu20.04/Dockerfile
  build/docker/builder/gpu/ubuntu22.04/Dockerfile
  scripts/install_deps.sh
  scripts/install_deps_msys.sh
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#35186 enhance:[cherry-pick]update mmapchunkmanager config in milvus.yaml
  configs/milvus.yaml
  internal/util/initcore/init_core.go
Labels: kind/enhancement, size/XS, ci-passed, dco-passed

#35180 enhance:update mmap_chunk_manager config in milvus.yaml
  configs/milvus.yaml
  internal/util/initcore/init_core.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#35208 enhance: use docker compose instead of docker-compose
  .github/workflows/deploy-test.yaml
  .github/workflows/main.yaml
  .github/workflows/publish-test-images.yaml
  DEVELOPMENT.md
  build/README.md
  build/builder.sh
  build/builder_gpu.sh
  build/util.sh
  deployments/export-log/README.md
  deployments/offline/README.md
  scripts/README.md
  scripts/devcontainer.sh
  scripts/run_docker.sh
  tests/README.md
  tests/README_CN.md
  tests/integration/README.md
  tests/python_client/deploy/README.md
  tests/python_client/deploy/check_healthy.sh
  tests/python_client/deploy/test.sh
  tests/python_client/deploy/utils.sh
  tests/scripts/e2e.sh
  tests/scripts/export_log_docker.sh
  tests/scripts/prepare_e2e.sh
Labels: kind/enhancement, sig/testing, size/L, lgtm, area/test, ci-passed, dco-passed, test/integration

#35207 enhance: remove timestamp_filter after retrieve
  internal/core/src/exec/expression/TermExpr.cpp
  internal/core/src/query/generated/ExecPlanNodeVisitor.h
  internal/core/src/query/visitors/ExecExprVisitor.cpp
  internal/core/src/query/visitors/ExecPlanNodeVisitor.cpp
  internal/core/src/segcore/InsertRecord.h
  internal/core/src/segcore/SegmentGrowingImpl.h
  internal/core/src/segcore/SegmentInterface.h
  internal/core/src/segcore/SegmentSealedImpl.h
  internal/core/unittest/test_offset_ordered_array.cpp
  internal/core/unittest/test_offset_ordered_map.cpp
Labels: kind/enhancement, size/L, dco-passed

#35220 enhance: add log for partition stats(#30376)
  internal/querycoordv2/checkers/leader_checker.go
  internal/querycoordv2/meta/target_manager.go
  internal/querynodev2/delegator/delegator.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#35219 enhance: add log for partition stats( #30376)
  internal/querycoordv2/checkers/leader_checker.go
  internal/querycoordv2/meta/target_manager.go
  internal/querynodev2/delegator/delegator.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#35227 enhance: docker-compose first then try to use docker compose
  .github/workflows/deploy-test.yaml
  .github/workflows/main.yaml
  .github/workflows/publish-test-images.yaml
  DEVELOPMENT.md
  build/README.md
  build/builder.sh
  build/builder_gpu.sh
  build/util.sh
  deployments/export-log/README.md
  deployments/offline/README.md
  scripts/README.md
  scripts/devcontainer.sh
  scripts/run_docker.sh
  tests/README.md
  tests/README_CN.md
  tests/integration/README.md
  tests/python_client/deploy/README.md
  tests/python_client/deploy/check_healthy.sh
  tests/python_client/deploy/test.sh
  tests/python_client/deploy/utils.sh
  tests/scripts/e2e.sh
  tests/scripts/export_log_docker.sh
  tests/scripts/prepare_e2e.sh
Labels: kind/enhancement, sig/testing, size/L, lgtm, area/test, ci-passed, dco-passed, test/integration

#35228 enhance: docker-compose first then try to use docker compose
  .github/workflows/deploy-test.yaml
  .github/workflows/main.yaml
  .github/workflows/publish-test-images.yaml
  DEVELOPMENT.md
  build/README.md
  build/builder.sh
  build/builder_gpu.sh
  build/util.sh
  deployments/export-log/README.md
  deployments/offline/README.md
  scripts/README.md
  scripts/devcontainer.sh
  scripts/run_docker.sh
  tests/README.md
  tests/README_CN.md
  tests/integration/README.md
  tests/python_client/deploy/README.md
  tests/python_client/deploy/check_healthy.sh
  tests/python_client/deploy/test.sh
  tests/python_client/deploy/utils.sh
  tests/scripts/e2e.sh
  tests/scripts/export_log_docker.sh
  tests/scripts/prepare_e2e.sh
Labels: kind/enhancement, sig/testing, size/L, lgtm, area/test, ci-passed, dco-passed, test/integration

#35217 enhance: upgrade conan version
  .github/workflows/mac.yaml
  DEVELOPMENT.md
  build/docker/builder/cpu/amazonlinux2023/Dockerfile
  build/docker/builder/cpu/ubuntu20.04/Dockerfile
  build/docker/builder/gpu/ubuntu20.04/Dockerfile
  scripts/install_deps.sh
  scripts/install_deps_msys.sh
Labels: kind/enhancement, size/S, lgtm, ci-passed, dco-passed

#35141 enhance: [cherry-pick] Add monitoring metrics for task execution time in datacoord
  internal/datacoord/task_analyze.go
  internal/datacoord/task_index.go
  internal/datacoord/task_scheduler.go
  internal/datacoord/task_scheduler_test.go
  internal/datacoord/types.go
  pkg/metrics/datacoord_metrics.go
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/component_param_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#34996 enhance: segment alloc interceptor
  internal/.mockery.yaml
  internal/datacoord/services_test.go
  internal/distributed/streamingnode/service.go
  internal/metastore/catalog.go
  internal/metastore/kv/streamingnode/constant.go
  internal/metastore/kv/streamingnode/kv_catalog.go
  internal/metastore/kv/streamingnode/kv_catalog_test.go
  internal/mocks/mock_metastore/mock_StreamingNodeCataLog.go
  internal/mocks/streamingnode/server/mock_walmanager/mock_Manager.go
  internal/mocks/streamingnode/server/wal/interceptors/segment/mock_inspector/mock_SealOperator.go
  internal/proto/streaming.proto
  internal/streamingcoord/server/balancer/balance_timer.go
  internal/streamingcoord/server/balancer/balancer_impl.go
  internal/streamingnode/server/builder.go
  internal/streamingnode/server/flusher/flusherimpl/flusher_impl_test.go
  internal/streamingnode/server/resource/resource.go
  internal/streamingnode/server/resource/resource_test.go
  internal/streamingnode/server/resource/test_utility.go
  internal/streamingnode/server/wal/adaptor/builder.go
  internal/streamingnode/server/wal/adaptor/wal_test.go
  internal/streamingnode/server/wal/interceptors/segment/builder.go
  internal/streamingnode/server/wal/interceptors/segment/inspector/impls.go
  internal/streamingnode/server/wal/interceptors/segment/inspector/inspector.go
  internal/streamingnode/server/wal/interceptors/segment/inspector/inspector_test.go
  internal/streamingnode/server/wal/interceptors/segment/manager/params.go
  internal/streamingnode/server/wal/interceptors/segment/manager/partition_manager.go
  internal/streamingnode/server/wal/interceptors/segment/manager/partition_managers.go
  internal/streamingnode/server/wal/interceptors/segment/manager/pchannel_manager.go
  internal/streamingnode/server/wal/interceptors/segment/manager/pchannel_manager_test.go
  internal/streamingnode/server/wal/interceptors/segment/manager/seal_queue.go
  internal/streamingnode/server/wal/interceptors/segment/manager/segment_manager.go
  internal/streamingnode/server/wal/interceptors/segment/policy/global_seal_policy.go
  internal/streamingnode/server/wal/interceptors/segment/policy/segment_limitation_policy.go
  internal/streamingnode/server/wal/interceptors/segment/policy/segment_seal_policy.go
  internal/streamingnode/server/wal/interceptors/segment/segment_assign_interceptor.go
  internal/streamingnode/server/wal/interceptors/segment/stats/signal_notifier.go
  internal/streamingnode/server/wal/interceptors/segment/stats/stats.go
  internal/streamingnode/server/wal/interceptors/segment/stats/stats_manager.go
  internal/streamingnode/server/wal/interceptors/segment/stats/stats_manager_test.go
  internal/streamingnode/server/wal/interceptors/segment/stats/stats_test.go
  internal/streamingnode/server/wal/interceptors/timetick/ack/ack_test.go
  internal/streamingnode/server/walmanager/manager_impl_test.go
  internal/streamingnode/server/walmanager/wal_lifetime_test.go
  pkg/streaming/util/message/builder.go
  pkg/streaming/util/message/messagepb/message.proto
  pkg/streaming/util/message/specialized_message.go
  pkg/streaming/util/message/test_case.go
  pkg/util/syncutil/context_condition_variable.go
  pkg/util/syncutil/context_condition_variable_test.go
  pkg/util/syncutil/versioned_notifier.go
  pkg/util/syncutil/versioned_notifier_test.go
  pkg/util/typeutil/backoff_timer.go
  pkg/util/typeutil/backoff_timer_test.go
Labels: kind/enhancement, size/XXL, approved, lgtm, ci-passed, dco-passed, area/compilation

#35234 enhance: Avoid unnecesary syncTargetVersion func call after querycoord recover (#34954)
  internal/querycoordv2/meta/target.go
  internal/querycoordv2/meta/target_manager_test.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#35193 enhance: add metric to record maxInsertRate and queryNodeMemoryHighWaterLevel (#35185)
  internal/proxy/proxy.go
  internal/rootcoord/quota_center.go
  pkg/metrics/proxy_metrics.go
  pkg/metrics/rootcoord_metrics.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#35103 enhance: revert remove duplicated pk function
  internal/core/src/segcore/DeletedRecord.h
  internal/core/src/segcore/InsertRecord.h
  internal/core/src/segcore/SegmentGrowing.h
  internal/core/src/segcore/SegmentGrowingImpl.cpp
  internal/core/src/segcore/SegmentGrowingImpl.h
  internal/core/src/segcore/SegmentInterface.cpp
  internal/core/src/segcore/SegmentInterface.h
  internal/core/src/segcore/SegmentSealed.h
  internal/core/src/segcore/SegmentSealedImpl.cpp
  internal/core/src/segcore/SegmentSealedImpl.h
  internal/core/src/segcore/Utils.h
  internal/core/src/segcore/segment_c.cpp
  internal/core/src/segcore/segment_c.h
  internal/core/unittest/test_array_expr.cpp
  internal/core/unittest/test_c_api.cpp
  internal/core/unittest/test_c_stream_reduce.cpp
  internal/core/unittest/test_exec.cpp
  internal/core/unittest/test_expr.cpp
  internal/core/unittest/test_group_by.cpp
  internal/core/unittest/test_growing.cpp
  internal/core/unittest/test_retrieve.cpp
  internal/core/unittest/test_sealed.cpp
  internal/core/unittest/test_utils.cpp
  internal/core/unittest/test_utils/DataGen.h
  internal/querynodev2/segments/segment.go
  internal/querynodev2/segments/segment_loader.go
  tests/python_client/testcases/test_query.py
Labels: kind/enhancement, sig/testing, size/XL, approved, lgtm, area/test, ci-passed, dco-passed, manual-pass

#35199 fix: Fix deadlock on compaction when stopping datanode
  internal/datanode/compaction_executor.go
  internal/datanode/compaction_executor_test.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed, manual-pass, kind/branch-feature

#35241 fix: delete by expr failed at retry progress
  internal/proxy/task_delete.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#35256 enhance: Remove stackerror imported unexpected
  go.sum
  pkg/go.mod
  pkg/go.sum
  pkg/util/retry/retry_test.go
Labels: kind/enhancement, area/dependency, size/XS, approved, lgtm, ci-passed, dco-passed

#35122 enhance: Skip manual stopped component during health check (#34953)
  cmd/roles/roles.go
  internal/http/healthz/healthz_handler.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#35165 enhance: Reduce delegator memory overloaded factor to 0.1 (#35092)
  configs/milvus.yaml
  internal/proxy/task.go
  internal/proxy/task_alias.go
  internal/proxy/task_index.go
  internal/querycoordv2/balance/score_based_balancer_test.go
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/component_param_test.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#35061 enhance: [cherry-pick] Retry on incomplete query result
  internal/proxy/impl.go
  internal/proxy/task_search.go
  pkg/util/merr/errors.go
  pkg/util/merr/errors_test.go
  pkg/util/merr/utils.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#35136 fix: Fix datanode cannot watch channel
  internal/datanode/event_manager.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass, kind/branch-feature

#35068 enhance: Refine import error log (#35067)
  internal/util/importutilv2/parquet/field_reader.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#35067 enhance: Refine import error log
  internal/util/importutilv2/parquet/field_reader.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#35257 enhance: upgrade go version to 1.21.11
  .github/workflows/mac.yaml
  DEVELOPMENT.md
  build/docker/builder/cpu/amazonlinux2023/Dockerfile
  build/docker/builder/cpu/rockylinux8/Dockerfile
  build/docker/builder/cpu/ubuntu20.04/Dockerfile
  build/docker/builder/cpu/ubuntu22.04/Dockerfile
  build/docker/builder/gpu/ubuntu20.04/Dockerfile
  build/docker/builder/gpu/ubuntu22.04/Dockerfile
  build/docker/meta-migration/builder/Dockerfile
  tests/go_client/go.mod
Labels: kind/enhancement, area/dependency, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#35178 fix: Maintain load idempotency even when building new indexes
  internal/querycoordv2/job/job_load.go
  internal/querycoordv2/job/job_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#35139 enhance: Add monitoring metrics for task execution time in datacoord
  internal/datacoord/task_analyze.go
  internal/datacoord/task_index.go
  internal/datacoord/task_scheduler.go
  internal/datacoord/task_scheduler_test.go
  internal/datacoord/types.go
  pkg/metrics/datacoord_metrics.go
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/component_param_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#35274 enhance: Add import option to skip disk quota check
  internal/datacoord/import_util.go
  internal/datacoord/import_util_test.go
  internal/util/importutilv2/option.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#35020 enhance: Gin & restfulv1 handler use sonic json
  Makefile
  internal/distributed/proxy/httpserver/handler_v1.go
  internal/distributed/proxy/httpserver/utils.go
  internal/json/sonic.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed, area/compilation, manual-pass

#35258 enhance: upgrade go version to 1.21.11
  .github/workflows/mac.yaml
  DEVELOPMENT.md
  build/docker/builder/cpu/amazonlinux2023/Dockerfile
  build/docker/builder/cpu/rockylinux8/Dockerfile
  build/docker/builder/cpu/ubuntu20.04/Dockerfile
  build/docker/builder/cpu/ubuntu22.04/Dockerfile
  build/docker/builder/gpu/ubuntu20.04/Dockerfile
  build/docker/builder/gpu/ubuntu22.04/Dockerfile
  build/docker/meta-migration/builder/Dockerfile
Labels: kind/enhancement, size/M, lgtm, dco-passed

#35191 test: update cases for index describe and upsert with autoID
  .github/workflows/code-checker.yaml
  .github/workflows/mac.yaml
  tests/go_client/base/milvus_client.go
  tests/go_client/common/consts.go
  tests/go_client/common/response_checker.go
  tests/go_client/go.mod
  tests/go_client/go.sum
  tests/go_client/testcases/collection_test.go
  tests/go_client/testcases/delete_test.go
  tests/go_client/testcases/helper/data_helper.go
  tests/go_client/testcases/index_test.go
  tests/go_client/testcases/insert_test.go
  tests/go_client/testcases/partition_test.go
  tests/go_client/testcases/query_test.go
  tests/go_client/testcases/search_test.go
  tests/go_client/testcases/upsert_test.go
Labels: area/dependency, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, manual-pass, kind/test

#35271 enhance: Add in-memory cache for casbin enforcer result
  internal/datacoord/compaction_policy_clustering_test.go
  internal/datacoord/compaction_trigger_v2_test.go
  internal/proxy/meta_cache.go
  internal/proxy/privilege_cache.go
  internal/proxy/privilege_cache_test.go
  internal/proxy/privilege_interceptor.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#34656 enhance: streaming service client
  internal/distributed/streaming/OWNERS
  internal/distributed/streaming/append.go
  internal/distributed/streaming/internal/consumer/consumer.go
  internal/distributed/streaming/internal/consumer/consumer_impl.go
  internal/distributed/streaming/internal/consumer/consumer_test.go
  internal/distributed/streaming/internal/consumer/message_handler.go
  internal/distributed/streaming/internal/errs/error.go
  internal/distributed/streaming/internal/producer/producer.go
  internal/distributed/streaming/internal/producer/producer_resuming.go
  internal/distributed/streaming/internal/producer/producer_test.go
  internal/distributed/streaming/streaming.go
  internal/distributed/streaming/streaming_test.go
  internal/distributed/streaming/wal.go
  internal/distributed/streamingnode/OWNERS
  internal/mocks/streamingnode/server/mock_wal/mock_WAL.go
  internal/proto/streaming.proto
  internal/streamingcoord/OWNERS
  internal/streamingcoord/server/balancer/balancer_impl.go
  internal/streamingnode/OWNERS
  internal/streamingnode/client/handler/handler_client.go
  internal/streamingnode/client/handler/handler_client_impl.go
  internal/streamingnode/client/handler/handler_client_test.go
  internal/streamingnode/client/handler/producer/producer_impl.go
  internal/streamingnode/client/handler/shared_producer.go
  internal/streamingnode/server/service/handler/producer/produce_server.go
  internal/streamingnode/server/service/handler/producer/produce_server_test.go
  internal/streamingnode/server/wal/adaptor/wal_adaptor.go
  internal/streamingnode/server/wal/adaptor/wal_test.go
  internal/streamingnode/server/wal/interceptors/segment/manager/seal_queue.go
  internal/streamingnode/server/wal/interceptors/timetick/timetick_message.go
  internal/streamingnode/server/wal/wal.go
  internal/streamingnode/server/walmanager/manager_impl.go
  internal/util/streamingutil/OWNERS
  pkg/metrics/streaming_service_metrics.go
  pkg/mocks/streaming/util/mock_message/mock_MutableMessage.go
  pkg/streaming/util/message/builder.go
  pkg/streaming/util/message/message.go
  pkg/streaming/util/message/message_builder_test.go
  pkg/streaming/util/message/specialized_message_test.go
  pkg/streaming/util/message/test_case.go
  pkg/streaming/walimpls/test_framework.go
  scripts/run_go_unittest.sh
Labels: kind/enhancement, size/XXL, approved, lgtm, ci-passed, dco-passed, area/compilation

#35223 feat: put inverted index into ram (#35222)
  cmd/roles/roles.go
  internal/core/src/index/InvertedIndexTantivy.cpp
  internal/core/src/storage/DiskFileManagerImpl.cpp
  internal/core/src/storage/DiskFileManagerImpl.h
  internal/core/src/storage/Util.cpp
  internal/core/src/storage/Util.h
Labels: kind/feature, size/M, approved, lgtm, ci-passed, dco-passed, kind/branch-feature

#35232 feat: [skip e2e] effective way to use cache
  .github/workflows/code-checker.yaml
  .github/workflows/main.yaml
Labels: kind/enhancement, kind/feature, size/S, approved, lgtm, ci-passed, dco-passed

#35233 feat: [skip e2e] effective way to use cache
  .github/actions/cache-restore/action.yaml
  .github/actions/cache-save/action.yaml
  .github/workflows/code-checker.yaml
  .github/workflows/main.yaml
Labels: kind/enhancement, kind/feature, size/L, approved, lgtm, ci-passed, dco-passed

#34159 enhance: change gpu default mem pool size
  configs/milvus.yaml
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#35149 enhance: Avoid unnecessary compaction (#35148)
  internal/datacoord/compaction_trigger.go
  internal/datacoord/import_checker.go
  internal/datacoord/import_util.go
  internal/datacoord/import_util_test.go
  internal/datacoord/index_meta.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#35148 enhance: Avoid unnecessary compaction
  internal/datacoord/compaction_trigger.go
  internal/datacoord/import_checker.go
  internal/datacoord/import_util.go
  internal/datacoord/import_util_test.go
  internal/datacoord/index_meta.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#35222 feat: put inverted index into ram
  cmd/roles/roles.go
  internal/core/src/index/InvertedIndexTantivy.cpp
  internal/core/src/storage/DiskFileManagerImpl.cpp
  internal/core/src/storage/DiskFileManagerImpl.h
  internal/core/src/storage/Util.cpp
  internal/core/src/storage/Util.h
Labels: kind/feature, size/M, approved, lgtm, ci-passed, dco-passed, kind/branch-feature

#35272 enhance: [2.4] Add in-memory cache for casbin enforcer result
  internal/datacoord/compaction_policy_clustering_test.go
  internal/proxy/meta_cache.go
  internal/proxy/privilege_cache.go
  internal/proxy/privilege_cache_test.go
  internal/proxy/privilege_interceptor.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#35034 enhance: Bump milvus & proto version to v2.4.7
  client/go.mod
  client/go.sum
  go.mod
  go.sum
  pkg/common/version.go
  pkg/go.mod
  pkg/go.sum
Labels: kind/enhancement, area/dependency, size/S, approved, lgtm, ci-passed, dco-passed, kind/branch-feature

#34561 enhance: Enable setting the replica number and resource group during collection creation (#34403)
  internal/querycoordv2/meta/coordinator_broker.go
  internal/querycoordv2/meta/coordinator_broker_test.go
  internal/querycoordv2/services.go
  pkg/common/common.go
  tests/integration/replicas/load/load_test.go
  tests/integration/util_collection.go
Labels: kind/enhancement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, manual-pass, test/integration

#34807 feat: Encode traceID and spanID as hex string
  internal/core/src/common/Tracer.cpp
  internal/core/src/common/Tracer.h
  internal/core/src/index/VectorIndex.h
  internal/core/src/query/SearchBruteForce.cpp
  internal/core/thirdparty/knowhere/CMakeLists.txt
  internal/core/unittest/test_tracer.cpp
Labels: kind/feature, size/L, approved, lgtm, ci-passed, do-not-merge/missing-related-issue, dco-passed, area/compilation

#35282 enhance: [2.4] Add disk filemananger parallel load control to reduce the memory consumption
  internal/core/src/storage/DiskFileManagerImpl.cpp
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#35275 enhance: Add import option to skip disk quota check (#35274)
  internal/datacoord/import_util.go
  internal/datacoord/import_util_test.go
  internal/util/importutilv2/option.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#35312 fix: Set corresponding DataScope for `loadStreamDelete`
  internal/querynodev2/delegator/delegator_data.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#35313 fix: [2.4] Set corresponding DataScope for `loadStreamDelete`
  internal/querynodev2/delegator/delegator_data.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#35210 test: update test cases
  tests/python_client/testcases/test_index.py
  tests/python_client/testcases/test_insert.py
Labels: sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#35294 fix: support string match for hybrid and bitmap index
  internal/core/src/exec/expression/UnaryExpr.h
  internal/core/src/index/BitmapIndex.cpp
  internal/core/src/index/BitmapIndex.h
  internal/core/src/index/HybridScalarIndex.h
  internal/core/src/index/InvertedIndexTantivy.cpp
  internal/core/src/index/InvertedIndexTantivy.h
  internal/core/src/index/ScalarIndex.h
  tests/python_client/testcases/test_query.py
Labels: kind/bug, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#35322 fix: error message when input is not aligned
  internal/proxy/validate_util.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#35323 fix: error message when input is not aligned (#35322)
  internal/proxy/validate_util.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#35327 Change minio use virtual config to not panic
  pkg/util/paramtable/service_param.go
Labels: kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed, PR | need cherry-pick, do-not-merge/invalid-pr-format

#35264 fix: comparision operations between incompatible operands
  internal/parser/planparserv2/parser_visitor.go
  internal/parser/planparserv2/plan_parser_v2_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#35306 enhance: add metric to record disk quota (#35305)
  internal/rootcoord/quota_center.go
  pkg/metrics/rootcoord_metrics.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#35305 enhance: add metric to record disk quota
  internal/rootcoord/quota_center.go
  pkg/metrics/rootcoord_metrics.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#35307 fix: comparision operations between incompatible operands (#35264)
  internal/parser/planparserv2/parser_visitor.go
  internal/parser/planparserv2/plan_parser_v2_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#35267 fix: [cherry-pick] Fix the issue of missing stats log after clustering compaction
  internal/datacoord/sync_segments_scheduler.go
  internal/datanode/compaction/clustering_compactor.go
  internal/datanode/compaction/clustering_compactor_test.go
  internal/datanode/compaction/compactor_common.go
  internal/datanode/compaction/mix_compactor.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#35169 enhance: enable to set load config in cluster level
  internal/querycoordv2/meta/coordinator_broker.go
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/component_param_test.go
  pkg/util/paramtable/param_item.go
  tests/integration/replicas/load/load_test.go
Labels: kind/enhancement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, test/integration

#35293 enhance: enable to set load config in cluster level
  internal/querycoordv2/meta/coordinator_broker.go
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/component_param_test.go
  pkg/util/paramtable/param_item.go
  tests/integration/replicas/load/load_test.go
Labels: kind/enhancement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, test/integration

#35299 fix: [2.4] init telemetry fails when set otlp as trace exporter
  internal/core/conanfile.py
  internal/util/initcore/init_core_test.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#35301 fix: init telemetry fails when set otlp as trace exporter
  internal/core/conanfile.py
  internal/util/initcore/init_core_test.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#35291 fix: [2.3] Reduce duplicate PKs in segcore (#34267)
  internal/core/src/segcore/InsertRecord.h
  internal/core/unittest/test_c_api.cpp
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#35324 fix: error message when input is not aligned (#35322)
  internal/proxy/validate_util.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#35331 enhance: Remove duplicated `generate-mockery-flushcommon` target
  Makefile
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed, area/compilation

#35205 enhance: improve ut for compaction_policy_clustering
  internal/datacoord/compaction_policy_clustering.go
  internal/datacoord/compaction_policy_clustering_test.go
  internal/datacoord/compaction_policy_l0_test.go
  internal/datacoord/compaction_trigger_v2.go
  internal/datacoord/compaction_trigger_v2_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#35308 fix: comparision operations between incompatible operands (#35264)
  internal/parser/planparserv2/parser_visitor.go
  internal/parser/planparserv2/plan_parser_v2_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#35242 enhance: improve ut cov of clustering compaction task
  internal/datacoord/compaction_task_clustering.go
  internal/datacoord/compaction_task_clustering_test.go
Labels: kind/enhancement, size/XL, approved, lgtm, ci-passed, dco-passed

#35339 fix: datacoord binlog size metrics include dropped segment
  internal/datacoord/meta.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#35338 fix: datacoord binlog size metrics include dropped segment
  internal/datacoord/meta.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#35326 enhance: Append drop partition msg to wal
  internal/.mockery.yaml
  internal/distributed/streaming/streaming.go
  internal/mocks/distributed/mock_streaming/mock_WALAccesser.go
  internal/rootcoord/drop_collection_task_test.go
  internal/rootcoord/drop_partition_task.go
  internal/rootcoord/drop_partition_task_test.go
  internal/rootcoord/garbage_collector.go
  internal/rootcoord/garbage_collector_test.go
  internal/rootcoord/mock_test.go
  internal/rootcoord/mocks/garbage_collector.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
  internal/rootcoord/step.go
  internal/util/streamingutil/checker.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#35309 fix: fix panic when generating plans
  internal/querycoordv2/balance/multi_target_balance.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#35336 enhance: support bitmap index
  internal/core/conanfile.py
  internal/core/src/common/Consts.h
  internal/core/src/exec/expression/BinaryArithOpEvalRangeExpr.cpp
  internal/core/src/exec/expression/BinaryRangeExpr.cpp
  internal/core/src/exec/expression/Expr.h
  internal/core/src/exec/expression/TermExpr.cpp
  internal/core/src/exec/expression/UnaryExpr.cpp
  internal/core/src/exec/expression/UnaryExpr.h
  internal/core/src/index/BitmapIndex.cpp
  internal/core/src/index/BitmapIndex.h
  internal/core/src/index/CMakeLists.txt
  internal/core/src/index/IndexFactory.cpp
  internal/core/src/index/InvertedIndexTantivy.cpp
  internal/core/src/index/InvertedIndexTantivy.h
  internal/core/src/index/Meta.h
  internal/core/src/index/ScalarIndex.h
  internal/core/src/index/ScalarIndexSort.cpp
  internal/core/src/index/ScalarIndexSort.h
  internal/core/src/index/StringIndexMarisa.cpp
  internal/core/src/index/StringIndexMarisa.h
  internal/core/unittest/CMakeLists.txt
  internal/core/unittest/test_bitmap_index.cpp
  internal/core/unittest/test_utils/indexbuilder_test_utils.h
  internal/proxy/task_index.go
  pkg/util/indexparamcheck/auto_index_checker.go
  pkg/util/indexparamcheck/base_checker.go
  pkg/util/indexparamcheck/base_checker_test.go
  pkg/util/indexparamcheck/bin_flat_checker_test.go
  pkg/util/indexparamcheck/bin_ivf_flat_checker_test.go
  pkg/util/indexparamcheck/binary_vector_base_checker.go
  pkg/util/indexparamcheck/binary_vector_base_checker_test.go
  pkg/util/indexparamcheck/bitmap_checker_test.go
  pkg/util/indexparamcheck/bitmap_index_checker.go
  pkg/util/indexparamcheck/conf_adapter_mgr.go
  pkg/util/indexparamcheck/diskann_checker_test.go
  pkg/util/indexparamcheck/float_vector_base_checker.go
  pkg/util/indexparamcheck/float_vector_base_checker_test.go
  pkg/util/indexparamcheck/hnsw_checker.go
  pkg/util/indexparamcheck/hnsw_checker_test.go
  pkg/util/indexparamcheck/index_checker.go
  pkg/util/indexparamcheck/index_type.go
  pkg/util/indexparamcheck/inverted_checker.go
  pkg/util/indexparamcheck/inverted_checker_test.go
  pkg/util/indexparamcheck/ivf_base_checker_test.go
  pkg/util/indexparamcheck/ivf_pq_checker_test.go
  pkg/util/indexparamcheck/ivf_sq_checker_test.go
  pkg/util/indexparamcheck/raft_ivf_flat_checker_test.go
  pkg/util/indexparamcheck/raft_ivf_pq_checker_test.go
  pkg/util/indexparamcheck/scann_checker_test.go
  pkg/util/indexparamcheck/sparse_float_vector_base_checker.go
  pkg/util/indexparamcheck/stl_sort_checker.go
  pkg/util/indexparamcheck/stl_sort_checker_test.go
  pkg/util/indexparamcheck/trie_checker.go
  pkg/util/indexparamcheck/trie_checker_test.go
  tests/python_client/testcases/test_query.py
Labels: kind/enhancement, sig/testing, size/XXL, approved, lgtm, area/test, ci-passed, dco-passed, area/compilation

#35316 enhance: pinpoint revision of 3thirdparty package
  internal/core/conanfile.py
  scripts/3rdparty_build.sh
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#35325 enhance: pinpoint revision of 3thirdparty package
  internal/core/conanfile.py
  scripts/3rdparty_build.sh
Labels: size/M, approved, lgtm, ci-passed, dco-passed, do-not-merge/invalid-pr-format

#35320 enhance: add metric to record disk quota (#35305)
  internal/rootcoord/quota_center.go
  pkg/metrics/rootcoord_metrics.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#35314 fix:redefine hybrid internal index type
  internal/core/src/index/BitmapIndex.h
  internal/core/src/index/HybridScalarIndex.cpp
  internal/core/src/index/InvertedIndexTantivy.h
  internal/core/src/index/ScalarIndex.h
  internal/core/unittest/CMakeLists.txt
  internal/core/unittest/test_bitmap_index.cpp
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed, area/compilation, PR | need cherry-pick

#35352 enhance: Init channel cp metric when DataCoord recover
  internal/datacoord/meta.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#35266 fix: Fix the issue of missing stats log after clustering compaction
  internal/datacoord/sync_segments_scheduler.go
  internal/datanode/compaction/clustering_compactor.go
  internal/datanode/compaction/clustering_compactor_test.go
  internal/datanode/compaction/compactor_common.go
  internal/datanode/compaction/mix_compactor.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#35374 enhance: Fix progress always zero due to integer divide
  internal/flushcommon/util/tickler.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#35380 fix: Use k locations only for basic BF test location
  internal/storage/pk_statistics.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#35381 fix: [2.4] Use k locations only for basic BF test location
  internal/storage/pk_statistics.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#35353 enhance: Init channel cp metric when DataCoord recover
  internal/datacoord/meta.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#35386 fix: [2.4] rollback grpc to 1.50.1
  internal/core/conanfile.py
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#35385 fix: rollback grpc to 1.50.1
  internal/core/conanfile.py
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#35292 enhance: memory value are displayed in MB
  pkg/util/merr/utils.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#35373 fix:use echo instead of print in Makefile
  Makefile
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed, area/compilation

#35100 enhance: Add more ut for l0CompactionTask
  internal/datacoord/compaction_task_l0.go
  internal/datacoord/compaction_task_l0_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#35243 enhance:[cherry-pick] improve ut cov of clustering compaction task
  internal/datacoord/compaction_task_clustering.go
  internal/datacoord/compaction_task_clustering_test.go
Labels: kind/enhancement, size/XL, approved, lgtm, ci-passed, dco-passed

#35268 fix: delete by expr failed at retry progress (#35241)
  internal/proxy/task_delete.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#35393 enhance: [2.4] Fix progress always zero due to integer divide
  internal/datanode/channel_manager.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#35074 enhance: make delegator delete buffer holding all delete from cp (#29626)
  internal/proto/query_coord.proto
  internal/querycoordv2/observers/target_observer.go
  internal/querynodev2/delegator/delegator.go
  internal/querynodev2/delegator/delegator_data.go
  internal/querynodev2/delegator/delegator_data_test.go
  internal/querynodev2/delegator/delegator_test.go
  internal/querynodev2/delegator/deletebuffer/delete_buffer.go
  internal/querynodev2/delegator/deletebuffer/list_delete_buffer.go
  internal/querynodev2/delegator/deletebuffer/list_delete_buffer_test.go
  internal/querynodev2/delegator/mock_delegator.go
  internal/querynodev2/services.go
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, area/internal-api, dco-passed, manual-pass

#35370 fix: incorrect memory size and delta count in SegmentInfo
  internal/datacoord/segment_info.go
  internal/datacoord/segment_info_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#35400 fix: fix empty indices of sparse float
  internal/core/src/mmap/Utils.h
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed, kind/branch-feature

#35390 fix: [2.3] Use k locations only for basic BF test location
  internal/storage/pk_statistics.go
Labels: kind/bug, size/XS, approved, lgtm, dco-passed

#35363 enhance: optimize index interface
  internal/core/src/exec/expression/Expr.h
  internal/core/src/exec/expression/UnaryExpr.h
  internal/core/src/index/BitmapIndex.cpp
  internal/core/src/index/BitmapIndex.h
  internal/core/src/index/InvertedIndexTantivy.h
  internal/core/src/index/ScalarIndex.h
  internal/core/src/mmap/Column.h
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#35330 enhance: [2.4] Remove stackerror imported unexpected (#35256)
  go.sum
  pkg/go.mod
  pkg/go.sum
  pkg/util/retry/retry_test.go
Labels: kind/enhancement, area/dependency, size/XS, approved, lgtm, ci-passed, dco-passed

#35420 fix: datacoord binlog size metrics include dropped segment (#35338)
  internal/datacoord/meta.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#35421 fix: delete by expr failed at retry progress (#35241)
  internal/proxy/task_delete.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#35130 fix: upsert use the previous pk in insert when autoid(#34672)
  internal/proxy/task_insert.go
  internal/proxy/task_upsert.go
  internal/proxy/util.go
  internal/proxy/util_test.go
  tests/integration/upsert/upsert_test.go
Labels: kind/bug, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, test/integration

#35287 enhance: timetick interceptor optimization
  internal/.mockery.yaml
  internal/distributed/streaming/append.go
  internal/distributed/streaming/internal/producer/producer.go
  internal/distributed/streaming/internal/producer/producer_test.go
  internal/distributed/streaming/streaming.go
  internal/distributed/streaming/streaming_test.go
  internal/mocks/streamingnode/client/handler/mock_producer/mock_Producer.go
  internal/mocks/streamingnode/server/mock_wal/mock_WAL.go
  internal/mocks/streamingnode/server/wal/interceptors/timetick/mock_inspector/mock_TimeTickSyncOperator.go
  internal/mocks/streamingnode/server/wal/mock_interceptors/mock_InterceptorBuilder.go
  internal/rootcoord/garbage_collector.go
  internal/streamingnode/client/handler/producer/producer.go
  internal/streamingnode/client/handler/producer/producer_impl.go
  internal/streamingnode/server/resource/resource.go
  internal/streamingnode/server/resource/resource_test.go
  internal/streamingnode/server/resource/test_utility.go
  internal/streamingnode/server/service/handler/producer/produce_server.go
  internal/streamingnode/server/service/handler/producer/produce_server_test.go
  internal/streamingnode/server/wal/adaptor/message_handler.go
  internal/streamingnode/server/wal/adaptor/message_handler_test.go
  internal/streamingnode/server/wal/adaptor/scanner_adaptor.go
  internal/streamingnode/server/wal/adaptor/scanner_adaptor_test.go
  internal/streamingnode/server/wal/adaptor/wal_adaptor.go
  internal/streamingnode/server/wal/adaptor/wal_adaptor_test.go
  internal/streamingnode/server/wal/adaptor/wal_test.go
  internal/streamingnode/server/wal/interceptors/chain_interceptor.go
  internal/streamingnode/server/wal/interceptors/chain_interceptor_test.go
  internal/streamingnode/server/wal/interceptors/ddl/builder.go
  internal/streamingnode/server/wal/interceptors/ddl/ddl_interceptor.go
  internal/streamingnode/server/wal/interceptors/interceptor.go
  internal/streamingnode/server/wal/interceptors/segment/builder.go
  internal/streamingnode/server/wal/interceptors/segment/segment_assign_interceptor.go
  internal/streamingnode/server/wal/interceptors/timetick/ack/ack_details.go
  internal/streamingnode/server/wal/interceptors/timetick/ack/ack_details_test.go
  internal/streamingnode/server/wal/interceptors/timetick/ack/manager.go
  internal/streamingnode/server/wal/interceptors/timetick/ack_details.go
  internal/streamingnode/server/wal/interceptors/timetick/builder.go
  internal/streamingnode/server/wal/interceptors/timetick/inspector/impls.go
  internal/streamingnode/server/wal/interceptors/timetick/inspector/inspector.go
  internal/streamingnode/server/wal/interceptors/timetick/inspector/inspector_test.go
  internal/streamingnode/server/wal/interceptors/timetick/inspector/notifier.go
  internal/streamingnode/server/wal/interceptors/timetick/inspector/notifier_test.go
  internal/streamingnode/server/wal/interceptors/timetick/timetick_interceptor.go
  internal/streamingnode/server/wal/interceptors/timetick/timetick_message.go
  internal/streamingnode/server/wal/interceptors/timetick/timetick_sync_operator.go
  internal/streamingnode/server/wal/interceptors/timetick/timetick_sync_operator_test.go
  internal/streamingnode/server/wal/scanner.go
  internal/streamingnode/server/wal/wal.go
  pkg/mocks/streaming/util/mock_message/mock_MutableMessage.go
  pkg/streaming/proto/streaming.proto
  pkg/streaming/util/message/adaptor/handler.go
  pkg/streaming/util/message/adaptor/message_id.go
  pkg/streaming/util/message/message.go
  pkg/streaming/util/message/message_impl.go
  pkg/streaming/util/message/message_test.go
  pkg/streaming/util/message/properties.go
  pkg/streaming/util/options/deliver.go
  pkg/streaming/util/types/streaming_node.go
Labels: kind/enhancement, size/XXL, approved, lgtm, ci-passed, dco-passed, area/compilation

#35384 enhance: Remove the check for channel cp lag when generating compaction plan (#35383)
  internal/datacoord/compaction_trigger.go
  internal/datacoord/compaction_trigger_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#35366 fix: force update next target if target can't be loaded
  internal/querycoordv2/task/scheduler.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#35432 enhance: limit getSegmentInfo batch size to avoid excced grpc message limit
  internal/datanode/broker/datacoord.go
  internal/datanode/channel_manager.go
  internal/querycoordv2/meta/coordinator_broker.go
  internal/querycoordv2/meta/coordinator_broker_test.go
  internal/querycoordv2/meta/mock_broker.go
  internal/querycoordv2/task/executor.go
  internal/querycoordv2/task/task_test.go
  internal/querycoordv2/task/utils.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#35419 enhance: Bump milvus version to v2.3.21
  pkg/common/version.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass, kind/branch-feature

#35398 enhance: Append create partition msg to wal
  internal/distributed/streaming/streaming.go
  internal/distributed/streaming/test_streaming.go
  internal/mocks/distributed/mock_streaming/mock_WALAccesser.go
  internal/rootcoord/create_partition_task.go
  internal/rootcoord/garbage_collector_test.go
  internal/rootcoord/step.go
  internal/rootcoord/step_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#35262 enhance:[Cherry-pick] Check by proxy rate limiter when delete get data by query. (#30891)
  configs/milvus.yaml
  internal/datanode/compaction/clustering_compactor.go
  internal/datanode/compaction/compactor_common.go
  internal/proxy/impl.go
  internal/proxy/impl_test.go
  internal/proxy/proxy.go
  internal/proxy/proxy_test.go
  internal/proxy/rate_limit_interceptor_test.go
  internal/proxy/simple_rate_limiter.go
  internal/proxy/simple_rate_limiter_test.go
  internal/proxy/task_delete.go
  internal/proxy/task_delete_test.go
  internal/types/types.go
  pkg/util/paramtable/quota_param.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#35437 fix: fix sparse float vector column warmup
  internal/core/src/mmap/Column.h
  internal/core/src/storage/ChunkCache.cpp
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed, kind/branch-feature
