Repository milvus-io/milvus, pull requests merged in 2024-07, with the labels that each got.

#33800 enhance: improve check health
  internal/datacoord/meta.go
  internal/datacoord/server_test.go
  internal/datacoord/services.go
  internal/datacoord/util.go
  internal/querycoordv2/services.go
  internal/querycoordv2/utils/util.go
  internal/rootcoord/mock_test.go
  internal/rootcoord/quota_center.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
  internal/rootcoord/util.go
  internal/util/componentutil/componentutil.go
  pkg/mq/mqimpl/rocksmq/server/rocksmq_retention.go
  pkg/util/merr/errors.go
  pkg/util/merr/utils.go
  pkg/util/paramtable/quota_param.go
  pkg/util/paramtable/quota_param_test.go
Labels: kind/enhancement, size/XL, approved, lgtm, ci-passed, dco-passed

#34265 enhance: improve check health
  internal/datacoord/meta.go
  internal/datacoord/server_test.go
  internal/datacoord/services.go
  internal/datacoord/util.go
  internal/querycoordv2/services.go
  internal/querycoordv2/utils/util.go
  internal/rootcoord/mock_test.go
  internal/rootcoord/quota_center.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
  internal/rootcoord/util.go
  internal/util/componentutil/componentutil.go
  pkg/mq/mqimpl/rocksmq/server/rocksmq_retention.go
  pkg/util/merr/errors.go
  pkg/util/merr/utils.go
  pkg/util/paramtable/quota_param.go
  pkg/util/paramtable/quota_param_test.go
Labels: kind/enhancement, size/XL, approved, lgtm, ci-passed, dco-passed

#34231 enhance: decrease cpu overhead during filter segments on datacoord
  internal/datacoord/compaction_trigger_test.go
  internal/datacoord/garbage_collector_test.go
  internal/datacoord/index_service_test.go
  internal/datacoord/meta_test.go
  internal/datacoord/segment_info.go
  internal/datacoord/segment_operator.go
  internal/datacoord/sync_segments_scheduler_test.go
  internal/querynodev2/segments/pool.go
  internal/querynodev2/segments/segment.go
Labels: kind/enhancement, size/XL, approved, lgtm, ci-passed, dco-passed

#34099 enhance: Skip update index for L0 segment
  internal/querycoordv2/checkers/balance_checker.go
  internal/querycoordv2/checkers/channel_checker.go
  internal/querycoordv2/checkers/controller.go
  internal/querycoordv2/checkers/index_checker.go
  internal/querycoordv2/checkers/index_checker_test.go
  internal/querycoordv2/checkers/leader_checker.go
  internal/querycoordv2/checkers/segment_checker.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#34245 enhance: Avoid assign too much segment/channels to new querynode (#34096)
  internal/querycoordv2/balance/balance.go
  internal/querycoordv2/balance/balance_test.go
  internal/querycoordv2/balance/channel_level_score_balancer_test.go
  internal/querycoordv2/balance/rowcount_based_balancer.go
  internal/querycoordv2/balance/rowcount_based_balancer_test.go
  internal/querycoordv2/balance/score_based_balancer.go
  internal/querycoordv2/balance/score_based_balancer_test.go
  internal/querycoordv2/ops_service_test.go
  internal/querycoordv2/services_test.go
  internal/querycoordv2/task/mock_scheduler.go
  internal/querycoordv2/task/scheduler.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#34250 fix: Implement singleflight for segcore ChunkCache
  internal/core/src/storage/ChunkCache.cpp
  internal/core/src/storage/ChunkCache.h
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#34240 fix: [cherry-pick]Fix datacoord's properties overwriten
  internal/rootcoord/broker.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#33498 enhance: support mark error as user error
  internal/proxy/accesslog/info/grpc_info.go
  internal/proxy/accesslog/info/grpc_info_test.go
  internal/proxy/accesslog/info/info.go
  internal/proxy/accesslog/info/restful_info.go
  internal/proxy/impl.go
  internal/proxy/task.go
  internal/proxy/task_delete.go
  internal/proxy/task_insert.go
  internal/proxy/task_query.go
  internal/proxy/task_search.go
  internal/proxy/task_upsert.go
  internal/proxy/util.go
  pkg/util/merr/errors.go
  pkg/util/merr/utils.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#34253 enhance: Optimize grow slice cost during query
  internal/proxy/task_query.go
  internal/querynodev2/segments/result.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#34254 enhance: Optimize grow slice cost during query
  internal/proxy/task_query.go
  internal/querynodev2/segments/result.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#34229 fix: Fix panic due to failed to seek
  pkg/mq/msgdispatcher/dispatcher.go
  pkg/mq/msgdispatcher/manager_test.go
  pkg/util/funcutil/func.go
  pkg/util/funcutil/func_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#34230 fix: Fix panic due to failed to seek (#34229)
  pkg/mq/msgdispatcher/dispatcher.go
  pkg/mq/msgdispatcher/manager_test.go
  pkg/util/funcutil/func.go
  pkg/util/funcutil/func_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#34280 enhance: Skip update index for L0 segment (#34099)
  internal/querycoordv2/checkers/balance_checker.go
  internal/querycoordv2/checkers/channel_checker.go
  internal/querycoordv2/checkers/controller.go
  internal/querycoordv2/checkers/index_checker.go
  internal/querycoordv2/checkers/index_checker_test.go
  internal/querycoordv2/checkers/leader_checker.go
  internal/querycoordv2/checkers/segment_checker.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#34235 fix: descriptor event in previous version not has nullable to parse error
  internal/core/src/common/Consts.h
  internal/core/src/storage/DataCodec.cpp
  internal/core/src/storage/Event.cpp
  internal/core/src/storage/Event.h
  internal/core/src/storage/InsertData.cpp
  internal/storage/binlog_reader.go
  internal/storage/binlog_test.go
  internal/storage/binlog_writer.go
  internal/storage/event_data.go
  internal/storage/event_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#34256 enhance: Optimize grow slice cost during query
  go.mod
  go.sum
  internal/proxy/task_query.go
  internal/querynodev2/segments/result.go
  internal/querynodev2/segments/result_test.go
Labels: kind/enhancement, area/dependency, size/M, approved, lgtm, ci-passed, dco-passed

#34282 fix: Check partition in current target when observing partition load status
  internal/querycoordv2/checkers/balance_checker.go
  internal/querycoordv2/checkers/channel_checker.go
  internal/querycoordv2/checkers/leader_checker.go
  internal/querycoordv2/checkers/segment_checker.go
  internal/querycoordv2/meta/mock_target_manager.go
  internal/querycoordv2/meta/target.go
  internal/querycoordv2/meta/target_manager.go
  internal/querycoordv2/meta/target_manager_test.go
  internal/querycoordv2/observers/collection_observer.go
  internal/querycoordv2/observers/target_observer.go
  internal/querycoordv2/observers/target_observer_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#34267 fix: Reduce duplicate PKs in segcore
  internal/core/src/segcore/InsertRecord.h
  internal/core/unittest/test_c_api.cpp
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#34215 enhance: use the only MaxEtcdTxnNum(#33070)
  internal/metastore/kv/datacoord/kv_catalog.go
  internal/metastore/kv/rootcoord/kv_catalog.go
  internal/metastore/kv/rootcoord/kv_catalog_test.go
  internal/metastore/kv/rootcoord/suffix_snapshot.go
  pkg/util/constant.go
  pkg/util/etcd/etcd_util.go
  pkg/util/etcd/etcd_util_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#34213 enhance:change wrong log(#33447)
  internal/datanode/broker/datacoord.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#34212 enhance: do check when add not empty logpath(#33640)
  internal/datacoord/meta_test.go
  internal/datacoord/segment_info.go
  internal/datacoord/segment_manager_test.go
  internal/datacoord/server_test.go
  internal/datacoord/services_test.go
  internal/metastore/kv/datacoord/kv_catalog_test.go
  internal/metastore/kv/datacoord/util.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#34185 fix: LegacyVersionWithoutRPCWatch default value to 2.4.1
  configs/milvus.yaml
  pkg/util/paramtable/component_param.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#34294 enhance: Use channel name map finding channel watcher
  internal/datacoord/channel_manager_v2.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#34302 fix: Reduce duplicate PKs in segcore (#34267)
  internal/core/src/segcore/InsertRecord.h
  internal/core/unittest/test_c_api.cpp
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#34300 enhance: Refine max length exceeded error message
  internal/proxy/validate_util.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#34301 fix: Sync the sealed and flushed segments to datanode
  internal/datacoord/compaction_trigger.go
  internal/datacoord/sync_segments_scheduler.go
  internal/datanode/metacache/meta_cache.go
  internal/datanode/services_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#34315 enhance: [cherry-pick] Batch pick PRs related to compaction
  internal/datanode/channel_checkpoint_updater.go
  internal/datanode/compaction/executor.go
  internal/datanode/compaction/executor_test.go
  internal/datanode/data_node.go
  internal/datanode/data_sync_service.go
  internal/datanode/flow_graph_dd_node.go
  internal/datanode/flow_graph_dd_node_test.go
  internal/datanode/flow_graph_time_tick_node.go
  internal/datanode/services.go
  internal/datanode/services_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#34283 fix: [2.4] Implement singleflight for segcore ChunkCache (#34250)
  internal/core/src/storage/ChunkCache.cpp
  internal/core/src/storage/ChunkCache.h
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#34284 fix: [2.3] Implement singleflight for segcore ChunkCache (#34250)
  internal/core/src/storage/ChunkCache.cpp
  internal/core/src/storage/ChunkCache.h
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#34309 enhance: [2.4] Use channel name map finding channel watcher (#34294)
  internal/datacoord/channel_manager_v2.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#34297 enhance: [2.4] Refine frequent log in datacoord (#33449)
  internal/datacoord/index_service.go
  internal/datacoord/meta.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#34238 enhance: timetick interceptor implementation
  internal/mocks/streamingnode/server/mock_wal/mock_WAL.go
  internal/mocks/streamingnode/server/wal/mock_interceptors/mock_Interceptor.go
  internal/mocks/streamingnode/server/wal/mock_interceptors/mock_InterceptorBuilder.go
  internal/mocks/streamingnode/server/wal/mock_interceptors/mock_InterceptorWithReady.go
  internal/proto/streamingpb/extends.go
  internal/streamingnode/server/resource/resource.go
  internal/streamingnode/server/resource/resource_test.go
  internal/streamingnode/server/resource/test_utility.go
  internal/streamingnode/server/resource/timestamp/basic_allocator.go
  internal/streamingnode/server/resource/timestamp/basic_allocator_test.go
  internal/streamingnode/server/resource/timestamp/test_mock_root_coord_client.go
  internal/streamingnode/server/resource/timestamp/timestamp_allocator.go
  internal/streamingnode/server/resource/timestamp/timestamp_allocator_test.go
  internal/streamingnode/server/wal/builder.go
  internal/streamingnode/server/wal/interceptors/chain_interceptor.go
  internal/streamingnode/server/wal/interceptors/chain_interceptor_test.go
  internal/streamingnode/server/wal/interceptors/interceptor.go
  internal/streamingnode/server/wal/interceptors/timetick/ack/ack.go
  internal/streamingnode/server/wal/interceptors/timetick/ack/ack_test.go
  internal/streamingnode/server/wal/interceptors/timetick/ack/detail.go
  internal/streamingnode/server/wal/interceptors/timetick/ack/detail_test.go
  internal/streamingnode/server/wal/interceptors/timetick/ack/manager.go
  internal/streamingnode/server/wal/interceptors/timetick/ack_details.go
  internal/streamingnode/server/wal/interceptors/timetick/builder.go
  internal/streamingnode/server/wal/interceptors/timetick/timetick_interceptor.go
  internal/streamingnode/server/wal/interceptors/timetick/timetick_message.go
  pkg/mocks/streaming/mock_walimpls/mock_WALImpls.go
  pkg/mocks/streaming/util/mock_message/mock_ImmutableMessage.go
  pkg/mocks/streaming/util/mock_message/mock_MutableMessage.go
  pkg/streaming/util/message/builder.go
  pkg/streaming/util/message/message.go
  pkg/streaming/util/message/message_builder_test.go
  pkg/streaming/util/message/message_impl.go
  pkg/streaming/util/message/message_type.go
  pkg/streaming/util/message/properties.go
  pkg/streaming/util/message/version.go
  pkg/streaming/util/options/deliver_test.go
  pkg/streaming/walimpls/impls/pulsar/scanner.go
  pkg/streaming/walimpls/impls/rmq/scanner.go
  pkg/streaming/walimpls/impls/walimplstest/builder.go
  pkg/streaming/walimpls/impls/walimplstest/message_id.go
  pkg/streaming/walimpls/test_framework.go
  pkg/util/syncutil/future.go
  pkg/util/syncutil/future_test.go
  pkg/util/typeutil/heap.go
  pkg/util/typeutil/heap_test.go
Labels: kind/enhancement, size/XXL, lgtm, ci-passed, dco-passed

#34291 enhance: Don't set timeout for SyncSegments
  internal/datacoord/session_manager.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#34295 enhance: [Cherry-Pick] Update access log
  internal/distributed/proxy/httpserver/constant.go
  internal/distributed/proxy/httpserver/handler_v1.go
  internal/distributed/proxy/httpserver/handler_v2.go
  internal/distributed/proxy/httpserver/utils.go
  internal/distributed/proxy/service.go
  internal/proxy/accesslog/formater_test.go
  internal/proxy/accesslog/global.go
  internal/proxy/accesslog/global_test.go
  internal/proxy/accesslog/info/grpc_info.go
  internal/proxy/accesslog/info/grpc_info_test.go
  internal/proxy/accesslog/info/info.go
  internal/proxy/accesslog/info/restful_info.go
  internal/proxy/accesslog/info/restful_info_test.go
  internal/proxy/accesslog/util.go
  internal/proxy/accesslog/writer.go
  internal/proxy/accesslog/writer_test.go
  pkg/util/paramtable/component_param.go
  pkg/util/requestutil/getter.go
Labels: kind/enhancement, size/XXL, approved, lgtm, ci-passed, dco-passed

#34324 enhance: [2.3] Refine max length exceeded error message (#34300)
  internal/proxy/validate_util.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#34305 fix: [2.4] Check partition in current target when observing partition load status (#34282)
  internal/querycoordv2/checkers/balance_checker.go
  internal/querycoordv2/checkers/channel_checker.go
  internal/querycoordv2/checkers/leader_checker.go
  internal/querycoordv2/checkers/segment_checker.go
  internal/querycoordv2/meta/mock_target_manager.go
  internal/querycoordv2/meta/target.go
  internal/querycoordv2/meta/target_manager.go
  internal/querycoordv2/meta/target_manager_test.go
  internal/querycoordv2/observers/collection_observer.go
  internal/querycoordv2/observers/target_observer.go
  internal/querycoordv2/observers/target_observer_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#34323 enhance: [2.4] Refine max length exceeded error message (#34300)
  internal/proxy/validate_util.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#34321 fix: [2.3] Check partition in current target when observing partition load status (#34282)
  internal/querycoordv2/checkers/balance_checker.go
  internal/querycoordv2/checkers/channel_checker.go
  internal/querycoordv2/checkers/segment_checker.go
  internal/querycoordv2/meta/target.go
  internal/querycoordv2/meta/target_manager.go
  internal/querycoordv2/meta/target_manager_test.go
  internal/querycoordv2/observers/collection_observer.go
  internal/querycoordv2/observers/leader_observer.go
  internal/querycoordv2/observers/target_observer.go
  internal/querycoordv2/observers/target_observer_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#34312 enhance: [cherry-pick] Remove compaction plans on the datanode (#33548)
  internal/datacoord/compaction_task_l0.go
  internal/datacoord/compaction_task_mix.go
  internal/datacoord/compaction_test.go
  internal/datacoord/mock_session_manager.go
  internal/datacoord/mock_test.go
  internal/datacoord/session_manager.go
  internal/datanode/services.go
  internal/datanode/services_test.go
  internal/distributed/datanode/client/client.go
  internal/distributed/datanode/client/client_test.go
  internal/distributed/datanode/service.go
  internal/distributed/datanode/service_test.go
  internal/mocks/mock_datanode.go
  internal/mocks/mock_datanode_client.go
  internal/proto/data_coord.proto
  internal/util/mock/grpc_datanode_client.go
Labels: kind/enhancement, size/L, approved, ci-passed, dco-passed

#34322 enhance: [2.4] Add go-deadlock as unittest only dependency (#33063)
  go.mod
  internal/datacoord/analyze_meta.go
  internal/datacoord/channel_manager.go
  internal/datacoord/channel_manager_v2.go
  internal/datacoord/cluster.go
  internal/datacoord/compaction_task_meta.go
  internal/datacoord/compaction_trigger.go
  internal/datacoord/garbage_collector_test.go
  internal/datacoord/import_meta.go
  internal/datacoord/import_scheduler.go
  internal/datacoord/index_engine_version_manager.go
  internal/datacoord/index_meta.go
  internal/datacoord/index_meta_test.go
  internal/datacoord/indexnode_manager.go
  internal/datacoord/indexnode_manager_test.go
  internal/datacoord/segment_manager.go
  internal/datacoord/server_test.go
  internal/datacoord/session.go
  internal/datacoord/session_manager.go
  internal/datacoord/sync_segments_scheduler_test.go
  internal/datacoord/task_scheduler.go
  internal/datacoord/task_scheduler_test.go
  pkg/go.mod
  pkg/go.sum
  scripts/run_go_codecov.sh
  scripts/run_go_unittest.sh
Labels: kind/enhancement, area/dependency, size/L, approved, lgtm, ci-passed, dco-passed

#34361 enhance: update knowhere version
  internal/core/thirdparty/knowhere/CMakeLists.txt
Labels: kind/enhancement, size/XS, dco-passed, area/compilation

#34335 enhance: refine misleading param name for bloom filter parallel factor
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#34318 fix: [cherry-pick] Sync the sealed and flushed segments to datanode (#34301)
  internal/datacoord/sync_segments_scheduler.go
  internal/datanode/metacache/meta_cache.go
  internal/datanode/services_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#33713 fix: update check for sparse hnsw index
  internal/proxy/task_index.go
  pkg/common/common.go
  pkg/util/indexparamcheck/base_checker.go
  pkg/util/indexparamcheck/base_checker_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#34109 test: [cherry-pick] update test case
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#34363 enhance: Refine compaction (#33982)
  .golangci.yml
  go.mod
  internal/datacoord/compaction.go
  internal/datacoord/compaction_task_clustering.go
  internal/datacoord/compaction_task_l0.go
  internal/datacoord/compaction_task_mix.go
  internal/datacoord/compaction_test.go
  internal/datacoord/meta.go
  internal/datacoord/meta_test.go
  internal/datacoord/mock_compaction_meta.go
Labels: kind/enhancement, area/dependency, size/XL, approved, dco-passed

#34360 fix: [Cherry-pick]Pick major compaction fixs and optimizations
  configs/milvus.yaml
  internal/datacoord/compaction_task_clustering.go
  internal/datacoord/handler.go
  internal/datanode/compaction/clustering_compactor.go
  internal/datanode/compaction/mix_compactor.go
  internal/datanode/compaction/segment_writer.go
  internal/metastore/kv/datacoord/constant.go
  internal/proxy/impl.go
  internal/proxy/task.go
  internal/proxy/task_test.go
  internal/querycoordv2/checkers/balance_checker.go
  internal/querycoordv2/checkers/leader_checker_test.go
  internal/querycoordv2/task/action.go
  internal/querycoordv2/task/task.go
  internal/querynodev2/delegator/delegator.go
  internal/querynodev2/delegator/segment_pruner.go
  internal/querynodev2/delegator/segment_pruner_test.go
  internal/storage/partition_stats.go
  internal/storage/serde.go
  internal/util/clustering/clustering.go
  pkg/common/map.go
  pkg/common/map_test.go
  pkg/util/merr/errors.go
  pkg/util/merr/errors_test.go
  pkg/util/merr/utils.go
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/component_param_test.go
  tests/integration/balance/balance_test.go
Labels: kind/bug, sig/testing, size/L, area/test, dco-passed, test/integration

#34356 enhance: [2.4] the proxy metric in the query request
  internal/proxy/impl.go
  internal/proxy/util.go
  internal/proxy/util_test.go
Labels: kind/enhancement, kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#34094 enhance: add metrics for segment prune latnecy(#30376)
  internal/querynodev2/delegator/segment_pruner.go
  pkg/metrics/querynode_metrics.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#34299 fix: Revert a optimize in clustering compaction
  internal/datacoord/compaction_task_clustering.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#34378 enhance: [skip e2e] update the version of MV
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#34380 enhance: [skip e2e][2.4] update the version of MV
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#34308 enhance: Tag gotestsum version when install deps
  Makefile
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed, area/compilation

#34348 enhance: Skip pick worker when task doesn't need to execute actually
  internal/datacoord/index_service.go
  internal/datacoord/task_analyze.go
  internal/datacoord/task_index.go
  internal/datacoord/task_scheduler.go
  internal/datacoord/task_scheduler_test.go
  internal/datacoord/types.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed, PR | need cherry-pick

#34382 enhance: [cherry-pick] Skip pick worker when task doesn't need to execute actually
  internal/datacoord/index_service.go
  internal/datacoord/task_analyze.go
  internal/datacoord/task_index.go
  internal/datacoord/task_scheduler.go
  internal/datacoord/task_scheduler_test.go
  internal/datacoord/types.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#34343 fix: Use raw parameter value to perform CAS
  pkg/util/paramtable/param_item.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed, PR | need cherry-pick

#34373 fix: [2.4] Use raw parameter value to perform CAS
  pkg/util/paramtable/param_item.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#34393 fix: [cherry-pick] Only load or release Flushed segment in datanode meta
  internal/datanode/services.go
  internal/datanode/services_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#34281 enhance: [Cherry-pick] Merge query stream result for reduce delete task (#32855)
  configs/milvus.yaml
  internal/querynodev2/handlers.go
  internal/querynodev2/server.go
  internal/querynodev2/tasks/query_stream_task.go
  internal/util/streamrpc/streamer.go
  internal/util/streamrpc/streamer_test.go
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#34338 fix: remove isFull check in compaction.enqueue
  internal/datacoord/compaction.go
  internal/datacoord/compaction_test.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#34384 enhance: [cherry-pick] Refine clustering_compaction_task retry mechanism
  internal/datacoord/compaction_task_clustering.go
  pkg/util/merr/errors.go
  pkg/util/merr/utils.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#34395 doc: [skip e2e] add extraConfig to embed milvus
  scripts/standalone_embed.sh
Labels: size/S, approved, lgtm, ci-passed, dco-passed, manual-pass, kind/doc

#34285 enhance:[Cherry-pick] avoid maintain checkpoint info in sync manager (#33413)
  internal/datanode/importv2/scheduler_test.go
  internal/datanode/importv2/task_l0_import_test.go
  internal/datanode/syncmgr/mock_sync_manager.go
  internal/datanode/syncmgr/sync_manager.go
  internal/datanode/writebuffer/bf_write_buffer_test.go
  internal/datanode/writebuffer/write_buffer.go
  internal/datanode/writebuffer/write_buffer_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#34288 fix: Avoid datarace in clustering compaction
  internal/datacoord/compaction_task.go
  internal/datacoord/compaction_task_clustering.go
  internal/proto/data_coord.proto
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed, manual-pass, PR | need cherry-pick

#34399 enhance: Fix lint issues & sdk testcase
  internal/storage/event_data.go
  pkg/streaming/util/options/deliver_test.go
  tests/go_client/testcases/insert_test.go
  tests/go_client/testcases/search_test.go
Labels: kind/enhancement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#34340 enhance: remove deprecated code within channel manager
  internal/datacoord/channel_manager.go
  internal/datacoord/channel_manager_test.go
  internal/datacoord/channel_store.go
  internal/datacoord/channel_store_test.go
  internal/datacoord/channel_store_v2.go
  internal/datacoord/channel_store_v2_test.go
Labels: kind/enhancement, size/XXL, approved, lgtm, ci-passed, dco-passed

#34406 fix: Remove unused code to fix compiling
  internal/datacoord/compaction.go
  internal/datacoord/compaction_trigger_v2.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#34398 enhance: [cherry-pick] Optimize clustering compaction (#34313)
  internal/datacoord/compaction.go
  internal/datanode/compaction/clustering_compactor.go
  internal/datanode/io/binlog_io.go
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#34293 enhance: use configed max topk for iterator when input topk exceeds(#34292)
  internal/proxy/search_util.go
  internal/proxy/task_search_test.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#34334 enhance: refine misleading param name for bloom filter parallel factor
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#34396 enhance: [Cherry-Pick] support mark error as user error (#33498)
  internal/proxy/accesslog/info/grpc_info.go
  internal/proxy/accesslog/info/grpc_info_test.go
  internal/proxy/accesslog/info/info.go
  internal/proxy/accesslog/info/restful_info.go
  internal/proxy/impl.go
  internal/proxy/task.go
  internal/proxy/task_delete.go
  internal/proxy/task_insert.go
  internal/proxy/task_query.go
  internal/proxy/task_search.go
  internal/proxy/task_upsert.go
  internal/proxy/util.go
  pkg/util/merr/errors.go
  pkg/util/merr/utils.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#34364 enhance: add metrics for segment prune latnecy(#30376)
  internal/querynodev2/delegator/segment_pruner.go
  pkg/metrics/querynode_metrics.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#34201 fix: DataNode might OOM by estimating based on MemorySize
  configs/milvus.yaml
  internal/datanode/compaction/l0_compactor.go
  internal/datanode/compaction/l0_compactor_test.go
  pkg/util/paramtable/component_param.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#34401 enhance: [2.4] Tag gotestsum version when install deps (#34308)
  Makefile
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed, area/compilation

#34200 enhance: async search and retrieve in cgo
  .golangci.yml
  Makefile
  configs/milvus.yaml
  internal/core/CMakeLists.txt
  internal/core/src/CMakeLists.txt
  internal/core/src/common/EasyAssert.h
  internal/core/src/futures/CMakeLists.txt
  internal/core/src/futures/Executor.cpp
  internal/core/src/futures/Executor.h
  internal/core/src/futures/Future.h
  internal/core/src/futures/LeakyResult.h
  internal/core/src/futures/Ready.h
  internal/core/src/futures/future_c.cpp
  internal/core/src/futures/future_c.h
  internal/core/src/futures/future_c_types.h
  internal/core/src/futures/future_test_case_c.cpp
  internal/core/src/futures/milvus_futures.pc.in
  internal/core/src/segcore/CMakeLists.txt
  internal/core/src/segcore/segment_c.cpp
  internal/core/src/segcore/segment_c.h
  internal/core/unittest/CMakeLists.txt
  internal/core/unittest/init_gtest.cpp
  internal/core/unittest/test_c_api.cpp
  internal/core/unittest/test_futures.cpp
  internal/core/unittest/test_group_by.cpp
  internal/core/unittest/test_utils/c_api_test_utils.h
  internal/querynodev2/segments/cgo_util.go
  internal/querynodev2/segments/retrieve_test.go
  internal/querynodev2/segments/segment.go
  internal/util/cgo/errors.go
  internal/util/cgo/executor.go
  internal/util/cgo/futures.go
  internal/util/cgo/futures_test.go
  internal/util/cgo/futures_test_case.go
  internal/util/cgo/manager_active.go
  internal/util/cgo/options.go
  internal/util/cgo/pool.go
  internal/util/cgo/state.go
  pkg/metrics/cgo_metrics.go
  pkg/metrics/metrics_test.go
  pkg/metrics/querynode_metrics.go
  pkg/util/merr/errors.go
  pkg/util/paramtable/component_param.go
  scripts/run_go_unittest.sh
Labels: kind/enhancement, area/dependency, size/XXL, approved, lgtm, ci-passed, dco-passed, area/compilation

#34331 enhance: Continue loop when reassign channel fails
  internal/datacoord/channel_manager.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#34290 enhance: use configed max topk for iterator when input topk exceeds
  internal/proxy/search_util.go
  internal/proxy/task_search_test.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#34400 test: add cases for gosdk v2 upsert
  tests/go_client/go.mod
  tests/go_client/go.sum
  tests/go_client/testcases/collection_test.go
  tests/go_client/testcases/database_test.go
  tests/go_client/testcases/delete_test.go
  tests/go_client/testcases/helper/data_helper.go
  tests/go_client/testcases/helper/helper.go
  tests/go_client/testcases/insert_test.go
  tests/go_client/testcases/query_test.go
  tests/go_client/testcases/search_test.go
  tests/go_client/testcases/upsert_test.go
Labels: area/dependency, sig/testing, size/XXL, approved, lgtm, area/test, ci-passed, dco-passed, manual-pass, kind/test

#34402 fix:[cherry-pick] minor fixs for major compaction
  internal/datacoord/compaction.go
  internal/datacoord/compaction_task.go
  internal/datacoord/compaction_task_clustering.go
  internal/datacoord/compaction_test.go
  internal/datacoord/compaction_trigger_v2.go
  internal/proto/data_coord.proto
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#34405 enhance: Update Knowhere version
  internal/core/src/common/QueryResult.h
  internal/core/src/index/VectorDiskIndex.cpp
  internal/core/src/index/VectorDiskIndex.h
  internal/core/src/index/VectorIndex.h
  internal/core/src/index/VectorMemIndex.cpp
  internal/core/src/index/VectorMemIndex.h
  internal/core/src/query/GroupByOperator.h
  internal/core/src/query/SearchBruteForce.cpp
  internal/core/src/query/SubSearchResult.h
  internal/core/thirdparty/knowhere/CMakeLists.txt
  internal/core/unittest/test_c_api.cpp
  internal/core/unittest/test_indexing.cpp
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed, area/compilation, manual-pass, kind/branch-feature

#34345 enhance: [cherry-pick] Batch pick PRs related to data codec
  internal/storage/binlog_iterator.go
  internal/storage/data_codec.go
  internal/storage/data_codec_test.go
  internal/storage/payload_writer.go
  internal/storage/utils.go
  internal/storage/utils_test.go
Labels: kind/enhancement, size/XL, approved, lgtm, ci-passed, dco-passed

#34122 enhance: wal adaptor implementation
  go.mod
  internal/mocks/google.golang.org/mock_grpc/mock_ClientStream.go
  internal/proto/streaming.proto
  internal/streamingnode/server/wal/adaptor/builder.go
  internal/streamingnode/server/wal/adaptor/opener.go
  internal/streamingnode/server/wal/adaptor/opener_test.go
  internal/streamingnode/server/wal/adaptor/scanner_adaptor.go
  internal/streamingnode/server/wal/adaptor/scanner_adaptor_test.go
  internal/streamingnode/server/wal/adaptor/scanner_registry.go
  internal/streamingnode/server/wal/adaptor/wal_adaptor.go
  internal/streamingnode/server/wal/adaptor/wal_adaptor_test.go
  internal/streamingnode/server/wal/adaptor/wal_test.go
  internal/streamingnode/server/wal/interceptors/timetick/timetick_interceptor.go
  internal/streamingnode/server/wal/scanner.go
  internal/streamingnode/server/wal/utility/immutable_message_queue.go
  internal/streamingnode/server/wal/utility/immutable_message_queue_test.go
  internal/streamingnode/server/wal/utility/message_heap.go
  internal/streamingnode/server/wal/utility/message_heap_test.go
  internal/streamingnode/server/wal/utility/reorder_buffer.go
  internal/streamingnode/server/wal/utility/reorder_buffer_test.go
  internal/streamingservice/.mockery.yaml
  internal/util/streamingutil/status/checker.go
  internal/util/streamingutil/status/checker_test.go
  internal/util/streamingutil/status/client_stream_wrapper.go
  internal/util/streamingutil/status/client_stream_wrapper_test.go
  internal/util/streamingutil/status/rpc_error.go
  internal/util/streamingutil/status/rpc_error_test.go
  internal/util/streamingutil/status/streaming_error.go
  internal/util/streamingutil/status/streaming_error_test.go
  internal/util/streamingutil/util/id_allocator.go
  pkg/metrics/metrics.go
  pkg/metrics/streaming_service_metrics.go
  pkg/util/typeutil/type.go
Labels: kind/enhancement, area/dependency, size/XXL, lgtm, ci-passed, dco-passed, area/compilation

#34203 fix: DataNode might OOM by estimating based on MemorySize
  configs/milvus.yaml
  internal/datanode/compaction/l0_compactor.go
  internal/datanode/compaction/l0_compactor_test.go
  pkg/util/paramtable/component_param.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#34365 enhance: reconstruct scalar part's code for segment-pruner(#30376)
  internal/querynodev2/delegator/ScalarPruner.go
  internal/querynodev2/delegator/segment_pruner.go
  internal/querynodev2/delegator/segment_pruner_test.go
  internal/storage/field_value.go
Labels: kind/enhancement, size/XL, approved, lgtm, ci-passed, dco-passed

#34339 fix: Correct the update logic of timerecorder
  internal/datanode/pipeline/flow_graph_dd_node.go
  internal/datanode/pipeline/flow_graph_dd_node_test.go
  internal/datanode/pipeline/flow_graph_dmstream_input_node.go
  internal/datanode/pipeline/flow_graph_write_node.go
  internal/util/flowgraph/node.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed, PR | need cherry-pick

#34383 enhance: [cherry-pick] optimize datanode cpu usage and correct the update logic of ttchecker
  internal/datanode/flow_graph_dd_node.go
  internal/datanode/flow_graph_dd_node_test.go
  internal/datanode/flow_graph_dmstream_input_node.go
  internal/datanode/flow_graph_write_node.go
  internal/datanode/timetick_sender.go
  internal/util/flowgraph/input_node.go
  internal/util/flowgraph/node.go
  internal/util/pipeline/node.go
  internal/util/pipeline/pipeline.go
  pkg/util/timerecord/group_checker.go
  pkg/util/timerecord/group_checker_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#34346 enhance: reconstruct scalar part's code for segment-pruner(#30376)
  internal/querynodev2/delegator/ScalarPruner.go
  internal/querynodev2/delegator/segment_pruner.go
  internal/querynodev2/delegator/segment_pruner_test.go
  internal/storage/field_value.go
Labels: kind/enhancement, size/XL, approved, lgtm, ci-passed, dco-passed

#34388 fix: Skip l0 segments when syncing segments to datanodes
  internal/datacoord/sync_segments_scheduler.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#34389 fix: [2.4] Skip l0 segments when syncing segments to datanodes
  internal/datacoord/sync_segments_scheduler.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#34369 fix: [restful v2] count(*) & hook
  internal/distributed/proxy/httpserver/handler_v2.go
  internal/distributed/proxy/httpserver/handler_v2_test.go
  internal/distributed/proxy/httpserver/request_v2.go
  internal/proxy/hook_interceptor.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed, PR | need cherry-pick

#34414 enhance: reduce cpp ut test cost time
  internal/core/unittest/test_exec.cpp
  internal/core/unittest/test_expr.cpp
  internal/core/unittest/test_growing_index.cpp
  internal/core/unittest/test_indexing.cpp
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#34423 [hotfix-2.4.5] update knowhere version to v2.3.5-hotfix
  internal/core/thirdparty/knowhere/CMakeLists.txt
Labels: size/XS, approved, lgtm, ci-passed, dco-passed, area/compilation, manual-pass

#34431 test: add test cases for gosdk v2 index
  client/index/common.go
  client/index/ivf.go
  client/index/scann.go
  client/index/sparse.go
  tests/go_client/base/milvus_client.go
  tests/go_client/common/response_checker.go
  tests/go_client/go.mod
  tests/go_client/go.sum
  tests/go_client/testcases/delete_test.go
  tests/go_client/testcases/helper/data_helper.go
  tests/go_client/testcases/helper/helper.go
  tests/go_client/testcases/helper/index_helper.go
  tests/go_client/testcases/index_test.go
  tests/go_client/testcases/query_test.go
  tests/go_client/testcases/search_test.go
  tests/go_client/testcases/upsert_test.go
Labels: area/dependency, sig/testing, size/XXL, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#34433 fix: [cherry-pick] [restful v2] count(*) & hook
  internal/distributed/proxy/httpserver/handler_v2.go
  internal/distributed/proxy/httpserver/handler_v2_test.go
  internal/distributed/proxy/httpserver/request_v2.go
  internal/proxy/hook_interceptor.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#34366 enhance: Enhance and correct exception module
  internal/core/src/common/Channel.h
  internal/core/src/common/EasyAssert.cpp
  internal/core/src/common/EasyAssert.h
  internal/core/src/common/Exception.h
  internal/core/src/common/FieldData.cpp
  internal/core/src/common/Types.h
  internal/core/src/exec/QueryContext.h
  internal/core/src/exec/operator/Operator.h
  internal/core/src/expr/ITypeExpr.h
  internal/core/src/index/IndexFactory.cpp
  internal/core/src/index/InvertedIndexTantivy.cpp
  internal/core/src/index/ScalarIndex.cpp
  internal/core/src/index/ScalarIndexSort.cpp
  internal/core/src/index/StringIndexMarisa.cpp
  internal/core/src/index/Utils.cpp
  internal/core/src/index/VectorDiskIndex.cpp
  internal/core/src/index/VectorIndex.h
  internal/core/src/index/VectorMemIndex.cpp
  internal/core/src/indexbuilder/IndexFactory.h
  internal/core/src/mmap/Column.h
  internal/core/src/mmap/Utils.h
  internal/core/src/query/GroupByOperator.h
  internal/core/src/query/Plan.cpp
  internal/core/src/query/SearchBruteForce.cpp
  internal/core/src/segcore/SegmentInterface.cpp
  internal/core/src/segcore/Utils.cpp
  internal/core/src/segcore/load_field_data_c.cpp
  internal/core/src/storage/AzureChunkManager.h
  internal/core/src/storage/LocalChunkManager.cpp
  internal/core/src/storage/MinioChunkManager.h
  internal/core/src/storage/OpenDALChunkManager.cpp
  internal/core/src/storage/OpenDALChunkManager.h
  internal/core/src/storage/Util.cpp
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#34359 fix: centroids file not removed when data skew in major compaction
  internal/core/src/clustering/KmeansClustering.cpp
  internal/core/unittest/test_kmeans_clustering.cpp
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#34425 enhance: [2.4] Continue loop when reassign channel fails (#34331)
  internal/datacoord/channel_manager_v2.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#34153 enhance: implement wal managerment on streaming node
  internal/proto/streamingpb/extends.go
  internal/streamingnode/server/wal/adaptor/scanner_adaptor.go
  internal/streamingnode/server/wal/adaptor/scanner_adaptor_test.go
  internal/streamingnode/server/wal/utility/reorder_buffer.go
  internal/streamingnode/server/walmanager/manager.go
  internal/streamingnode/server/walmanager/manager_impl.go
  internal/streamingnode/server/walmanager/manager_impl_test.go
  internal/streamingnode/server/walmanager/wal_lifetime.go
  internal/streamingnode/server/walmanager/wal_lifetime_test.go
  internal/streamingnode/server/walmanager/wal_state.go
  internal/streamingnode/server/walmanager/wal_state_pair.go
  internal/streamingnode/server/walmanager/wal_state_pair_test.go
  internal/streamingnode/server/walmanager/wal_state_test.go
  internal/util/streamingutil/util/wal_selector.go
  internal/util/streamingutil/util/wal_selector_test.go
  pkg/streaming/util/types/pchannel_info.go
  pkg/streaming/walimpls/impls/rmq/builder.go
Labels: kind/enhancement, area/dependency, size/XXL, lgtm, ci-passed, dco-passed, area/compilation

#33577 doc: Update # of GitHub stars in README.md
  README.md
Labels: size/XS, approved, lgtm, ci-passed, needs-dco, kind/doc

#34278 enhance: use the key lock and concurrent map in the msg dispatcher client
  pkg/mq/msgdispatcher/client.go
  pkg/mq/msgdispatcher/client_test.go
Labels: kind/enhancement, kind/improvement, size/M, lgtm, ci-passed, dco-passed

#34421 enhance: Remove datanode reporting TT based on MQ implementation
  configs/milvus.yaml
  internal/datacoord/channel_manager.go
  internal/datacoord/channel_manager_test.go
  internal/datacoord/channel_store.go
  internal/datacoord/server.go
  internal/datacoord/services.go
  internal/datacoord/services_test.go
  internal/datanode/compaction/clustering_compactor.go
  internal/datanode/data_node.go
  internal/datanode/pipeline/data_sync_service.go
  internal/datanode/pipeline/flow_graph_time_ticker.go
  internal/datanode/pipeline/flow_graph_write_node.go
  internal/datanode/pipeline/stats_updater.go
  internal/datanode/pipeline/stats_updater_test.go
  internal/datanode/util/timetick_sender.go
  internal/proxy/search_util.go
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/XL, approved, lgtm, ci-passed, dco-passed

#34350 fix: fix bitmap supported type
  internal/proxy/task_index.go
  pkg/util/indexparamcheck/auto_index_checker.go
  pkg/util/indexparamcheck/base_checker.go
  pkg/util/indexparamcheck/base_checker_test.go
  pkg/util/indexparamcheck/bin_flat_checker_test.go
  pkg/util/indexparamcheck/bin_ivf_flat_checker_test.go
  pkg/util/indexparamcheck/binary_vector_base_checker.go
  pkg/util/indexparamcheck/binary_vector_base_checker_test.go
  pkg/util/indexparamcheck/bitmap_checker_test.go
  pkg/util/indexparamcheck/bitmap_index_checker.go
  pkg/util/indexparamcheck/diskann_checker_test.go
  pkg/util/indexparamcheck/float_vector_base_checker.go
  pkg/util/indexparamcheck/float_vector_base_checker_test.go
  pkg/util/indexparamcheck/hnsw_checker.go
  pkg/util/indexparamcheck/hnsw_checker_test.go
  pkg/util/indexparamcheck/index_checker.go
  pkg/util/indexparamcheck/inverted_checker.go
  pkg/util/indexparamcheck/inverted_checker_test.go
  pkg/util/indexparamcheck/ivf_base_checker_test.go
  pkg/util/indexparamcheck/ivf_pq_checker_test.go
  pkg/util/indexparamcheck/ivf_sq_checker_test.go
  pkg/util/indexparamcheck/raft_ivf_flat_checker_test.go
  pkg/util/indexparamcheck/raft_ivf_pq_checker_test.go
  pkg/util/indexparamcheck/scann_checker_test.go
  pkg/util/indexparamcheck/sparse_float_vector_base_checker.go
  pkg/util/indexparamcheck/stl_sort_checker.go
  pkg/util/indexparamcheck/stl_sort_checker_test.go
  pkg/util/indexparamcheck/trie_checker.go
  pkg/util/indexparamcheck/trie_checker_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#34367 enhance: refactor variable column to reduce memory cost (#33875)
  internal/core/src/common/Common.h
  internal/core/src/common/EasyAssert.h
  internal/core/src/common/File.h
  internal/core/src/exec/expression/CompareExpr.cpp
  internal/core/src/exec/expression/ExistsExpr.cpp
  internal/core/src/exec/expression/Expr.h
  internal/core/src/exec/expression/JsonContainsExpr.cpp
  internal/core/src/mmap/Column.h
  internal/core/src/mmap/Utils.h
  internal/core/src/query/GroupByOperator.h
  internal/core/src/segcore/SegmentGrowingImpl.cpp
  internal/core/src/segcore/SegmentGrowingImpl.h
  internal/core/src/segcore/SegmentInterface.h
  internal/core/src/segcore/SegmentSealedImpl.cpp
  internal/core/src/segcore/SegmentSealedImpl.h
  internal/core/unittest/test_c_api.cpp
  internal/core/unittest/test_sealed.cpp
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#34142 fix: generate gin logs failed cause access logs panic
  internal/proxy/accesslog/info/restful_info.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#34377 enhance: Use Blocked Bloom Filter instead of basic bloom fitler impl
  go.mod
  go.sum
  internal/datanode/metacache/bloom_filter_set.go
  internal/datanode/syncmgr/storage_serializer.go
  internal/querynodev2/delegator/delegator_data_test.go
  internal/querynodev2/pkoracle/bloom_filter_set.go
  internal/querynodev2/segments/bloom_filter_set.go
  internal/querynodev2/segments/bloom_filter_set_test.go
  internal/storage/field_stats.go
  internal/storage/field_stats_test.go
  internal/storage/pk_statistics.go
  internal/storage/stats.go
  internal/storage/stats_test.go
  internal/util/bloomfilter/bloom_filter.go
  internal/util/bloomfilter/bloom_filter_test.go
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/component_param_test.go
  tests/integration/bloomfilter/bloom_filter_test.go
Labels: kind/enhancement, area/dependency, sig/testing, size/XXL, approved, lgtm, area/test, ci-passed, dco-passed, test/integration

#34443 fix: Write padding into mmap file in case of SIGBUS
  internal/core/src/mmap/Column.h
  internal/core/src/mmap/Utils.h
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#34448 fix: [GoSDK] Avoid creating schema for non-fast CreateCollection
  client/collection_options.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#34368 enhance: add disk quota and max collections into db properties
  internal/distributed/proxy/httpserver/handler_v1_test.go
  internal/metastore/model/database.go
  internal/proxy/meta_cache.go
  internal/rootcoord/create_collection_task.go
  internal/rootcoord/create_collection_task_test.go
  internal/rootcoord/quota_center.go
  internal/rootcoord/quota_center_test.go
  pkg/common/common.go
  pkg/util/merr/utils.go
  pkg/util/typeutil/map.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#34386 enhance: add disk quota and max collections into db properties
  internal/distributed/proxy/httpserver/handler_v1_test.go
  internal/metastore/model/database.go
  internal/proxy/meta_cache.go
  internal/rootcoord/create_collection_task.go
  internal/rootcoord/create_collection_task_test.go
  internal/rootcoord/quota_center.go
  internal/rootcoord/quota_center_test.go
  pkg/common/common.go
  pkg/util/merr/utils.go
  pkg/util/typeutil/map.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#34208 enhance: retry etcd server start with 3 default retries
  internal/kv/etcd/embed_etcd_kv.go
  internal/kv/etcd/etcd_kv_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#34438 enhance: Check segment existence when FlushSegments and add some key logs
  internal/datanode/pipeline/flow_graph_dd_node.go
  internal/datanode/pipeline/flow_graph_dd_node_test.go
  internal/datanode/syncmgr/task.go
  internal/datanode/writebuffer/write_buffer.go
  internal/datanode/writebuffer/write_buffer_test.go
  pkg/mq/msgdispatcher/dispatcher.go
  pkg/mq/msgdispatcher/manager.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#34116 enhance: add delta log stream new format reader and writer
  internal/storage/event_data.go
  internal/storage/event_writer.go
  internal/storage/serde.go
  internal/storage/serde_events.go
  internal/storage/serde_events_test.go
  internal/storage/serde_test.go
Labels: kind/enhancement, size/XL, approved, lgtm, ci-passed, dco-passed

#33958 enhance: Pre-allocate ids for import
  internal/allocator/local_allocator.go
  internal/allocator/local_allocator_test.go
  internal/datacoord/import_util.go
  internal/datanode/data_node.go
  internal/datanode/data_node_test.go
  internal/datanode/importv2/scheduler_test.go
  internal/datanode/importv2/task_import.go
  internal/datanode/importv2/task_l0_import.go
  internal/datanode/importv2/task_l0_import_test.go
  internal/datanode/importv2/task_l0_preimport.go
  internal/datanode/importv2/task_preimport.go
  internal/datanode/importv2/util.go
  internal/datanode/importv2/util_test.go
  internal/datanode/syncmgr/storage_serializer.go
  internal/datanode/syncmgr/storage_serializer_test.go
  internal/datanode/syncmgr/storage_v2_serializer.go
  internal/datanode/syncmgr/storage_v2_serializer_test.go
  internal/datanode/syncmgr/sync_manager.go
  internal/datanode/syncmgr/sync_manager_test.go
  internal/datanode/syncmgr/taskv2_test.go
  internal/datanode/writebuffer/write_buffer.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#34445 fix: fix clustering compaction can't enqueue when compaction queue is full
  internal/datacoord/compaction_task_clustering.go
  internal/datacoord/compaction_trigger_v2.go
  internal/datacoord/compaction_trigger_v2_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#34444 fix: [cherry-pick] [restful v2] count(*) & hook
  internal/distributed/proxy/httpserver/handler_v2.go
  internal/distributed/proxy/httpserver/handler_v2_test.go
  internal/distributed/proxy/httpserver/request_v2.go
  internal/proxy/hook_interceptor.go
Labels: size/L, approved, lgtm, ci-passed, manual-pass

#34455 fix: [2.4] Write padding into mmap file in case of SIGBUS (#34443)
  internal/core/src/mmap/Column.h
  internal/core/src/mmap/Utils.h
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#34447 fix: [cherry-pick] [restful v2] count(*) & hook
  internal/distributed/proxy/httpserver/handler_v2.go
  internal/distributed/proxy/httpserver/handler_v2_test.go
  internal/distributed/proxy/httpserver/request_v2.go
  internal/proxy/hook_interceptor.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed, do-not-merge/missing-related-pr

#34277 enhance: change autoindex default metric type
  pkg/util/indexparamcheck/constraints.go
  pkg/util/indexparamcheck/hnsw_checker_test.go
  pkg/util/paramtable/autoindex_param.go
  tests/python_client/testcases/test_index.py
Labels: kind/enhancement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#34451 fix: Add `nbits` parameter check for IVF_PQ
  pkg/util/indexparamcheck/ivf_pq_checker.go
  pkg/util/indexparamcheck/ivf_pq_checker_test.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#34108 test: update test case
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#34471 test: [cherry-pick]add testcase for count query
  tests/restful_client_v2/testcases/test_vector_operations.py
Labels: sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#34481 fix: Accidently exit the check loop
  internal/datacoord/compaction_policy_l0.go
  internal/datacoord/compaction_policy_l0_test.go
  internal/datacoord/compaction_trigger_v2.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#34473 fix: [2.4] Add `nbits` parameter check for IVF_PQ (#34451)
  pkg/util/indexparamcheck/ivf_pq_checker.go
  pkg/util/indexparamcheck/ivf_pq_checker_test.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#34480 fix: Accidently exit the check loop
  internal/datacoord/compaction_policy_l0.go
  internal/datacoord/compaction_policy_l0_test.go
  internal/datacoord/compaction_trigger_v2.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#34474 fix: Fix incorrect segment num rows (#34441)
  internal/datanode/writebuffer/insert_buffer.go
  internal/datanode/writebuffer/write_buffer.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#34464 fix: Upgraded Azidentity Package to v1.6.0
  go.mod
  go.sum
Labels: kind/bug, area/dependency, size/L, approved, ci-passed, dco-passed

#34472 enhance: Check segment existence when FlushSegments and add some key logs (#34438)
  internal/datanode/flow_graph_dd_node.go
  internal/datanode/flow_graph_dd_node_test.go
  internal/datanode/syncmgr/task.go
  internal/datanode/writebuffer/write_buffer.go
  internal/datanode/writebuffer/write_buffer_test.go
  pkg/mq/msgdispatcher/dispatcher.go
  pkg/mq/msgdispatcher/manager.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#34469 fix: [cherry-pick]fix can't enqueue when compaction queue is full(#34445)
  internal/datacoord/compaction_task_clustering.go
  internal/datacoord/compaction_trigger_v2.go
  internal/datacoord/compaction_trigger_v2_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#34475 fix: lose partitionIDs when scalar pruning and refine segment prune ratio metrics(#30376)
  internal/querynodev2/delegator/segment_pruner.go
  pkg/metrics/metrics.go
  pkg/metrics/querynode_metrics.go
Labels: kind/bug, kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#34479 enhance: ensure autoindex default metric type compatibility
  internal/datacoord/index_meta.go
  internal/datacoord/index_meta_test.go
  internal/proto/index_coord.proto
  internal/proxy/task_index.go
  internal/proxy/task_index_test.go
  pkg/common/common.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, area/internal-api, dco-passed

#34261 enhance: change autoindex default metric type
  internal/datacoord/index_meta.go
  internal/datacoord/index_meta_test.go
  internal/proto/index_coord.proto
  internal/proxy/task_index.go
  internal/proxy/task_index_test.go
  pkg/common/common.go
  pkg/util/indexparamcheck/constraints.go
  pkg/util/indexparamcheck/hnsw_checker_test.go
  pkg/util/paramtable/autoindex_param.go
  tests/python_client/testcases/test_index.py
Labels: kind/enhancement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, area/internal-api, dco-passed

#34477 fix: lose partitionIDs when scalar pruning and refine segment prune ratio metrics(#30376)
  internal/querynodev2/delegator/segment_pruner.go
  pkg/metrics/metrics.go
  pkg/metrics/querynode_metrics.go
Labels: kind/bug, kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#34441 fix: Fix incorrect segment num rows
  internal/datanode/writebuffer/insert_buffer.go
  internal/datanode/writebuffer/write_buffer.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#34488 fix: Check err is ErrKeyNotFound when CASCachedValue
  pkg/config/config_test.go
  pkg/config/env_source.go
  pkg/config/etcd_source.go
  pkg/config/file_source.go
  pkg/config/manager.go
  pkg/config/manager_test.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#34502 fix: Query may return deleted records
  internal/querynodev2/delegator/delegator_data.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#34490 enhance: update milvus proto
  go.mod
  go.sum
  pkg/go.mod
  pkg/go.sum
Labels: kind/enhancement, area/dependency, size/XS, approved, lgtm, ci-passed, dco-passed

#34486 fix: Fix unstable ut of msgdispatcher (#34485)
  pkg/mq/msgdispatcher/manager_test.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#34485 fix: Fix unstable ut of msgdispatcher
  pkg/mq/msgdispatcher/manager_test.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#34496 fix: fix compaction task startTime is 0
  internal/datacoord/compaction.go
  internal/datacoord/compaction_trigger_v2.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#34501 fix: Query may return deleted records
  internal/querynodev2/delegator/delegator_data.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#34505 fix: [cherry-pick] Fix compaction start time
  internal/datacoord/compaction.go
  internal/datacoord/compaction_trigger_v2.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#34507 fix: reuse deserialize result to help improve memory management
  internal/storage/serde.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#34454 enhance: release the record in delete codec and add some log for compaction
  internal/datanode/compaction/mix_compactor.go
  internal/storage/data_codec.go
Labels: kind/enhancement, kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#34506 enhance: [2.4] release the record in delete codec and add some log for compaction
  internal/datanode/compaction/mix_compactor.go
  internal/storage/data_codec.go
Labels: kind/enhancement, kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#34489 fix: [2.4] Check err is ErrKeyNotFound when CASCachedValue
  pkg/config/config_test.go
  pkg/config/env_source.go
  pkg/config/etcd_source.go
  pkg/config/file_source.go
  pkg/config/manager.go
  pkg/config/manager_test.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#34510 enhance: support setting properties in create database request
  internal/metastore/kv/rootcoord/kv_catalog_test.go
  internal/metastore/model/database.go
  internal/rootcoord/broker_test.go
  internal/rootcoord/create_db_task.go
  internal/rootcoord/meta_table_test.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#34511 enhance: support setting properties in create database request
  go.mod
  go.sum
  internal/metastore/kv/rootcoord/kv_catalog_test.go
  internal/metastore/model/database.go
  internal/rootcoord/broker_test.go
  internal/rootcoord/create_db_task.go
  internal/rootcoord/meta_table_test.go
Labels: kind/enhancement, area/dependency, size/M, approved, lgtm, ci-passed, dco-passed

#34515 enhance: Tidy dc channel manager
  internal/datacoord/channel_manager.go
  internal/datacoord/channel_manager_factory.go
  internal/datacoord/channel_manager_test.go
  internal/datacoord/channel_store.go
  internal/datacoord/mock_channel_store.go
  internal/datacoord/policy.go
  internal/datacoord/policy_test.go
  internal/datacoord/server.go
  internal/datacoord/server_test.go
Labels: kind/enhancement, size/XL, approved, lgtm, ci-passed, dco-passed

#34530 fix: [2.4] Write padding at end of mmap file not chunk
  internal/core/src/mmap/Utils.h
  internal/core/src/segcore/SegmentSealedImpl.cpp
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#34542 fix: RootCoord panic during check health
  internal/rootcoord/util.go
Labels: kind/bug, size/S, lgtm, ci-passed, dco-passed

#34541 fix: RootCoord panic during check health
  internal/rootcoord/util.go
Labels: kind/bug, size/S, lgtm, dco-passed
