Repository milvus-io/milvus, pull requests merged in 2024-12, with the labels that each got.

#38099 test: update check search result
  tests/python_client/common/common_params.py
  tests/python_client/testcases/test_mix_scenes.py
Labels: sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#38025 fix: Check if the dynamic fields contain any static fields
  internal/proxy/util.go
  internal/proxy/util_test.go
  internal/proxy/validate_util.go
  internal/proxy/validate_util_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#37976 fix: Fix checkGeneralCapacity slowly
  internal/rootcoord/constrant.go
  internal/rootcoord/create_collection_task.go
  internal/rootcoord/create_collection_task_test.go
  internal/rootcoord/create_partition_task.go
  internal/rootcoord/create_partition_task_test.go
  internal/rootcoord/meta_table.go
  internal/rootcoord/mocks/meta_table.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#38104 fix: [2.4] Return thread watcher goroutine after closed (#38091)
  internal/util/metrics/thread.go
  internal/util/metrics/thread_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#38105 enhance: [skip e2e][mergify] Update unit test file list for client pkg
  .github/mergify.yml
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#38110 fix: fix grant/revoke v2 meta and unclear error messages
  configs/milvus.yaml
  internal/proxy/impl.go
  internal/proxy/util.go
  internal/rootcoord/meta_table.go
  internal/rootcoord/meta_table_test.go
  internal/rootcoord/root_coord.go
  pkg/util/constant.go
  pkg/util/merr/errors.go
  pkg/util/merr/utils.go
  tests/integration/rbac/privilege_group_test.go
Labels: kind/bug, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, test/integration

#38095 enhance: [24]Increase task capacity and clean illegal task (#37896)
  configs/milvus.yaml
  internal/datacoord/compaction.go
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#38106 enhance: [skip e2e] Update test plugin version
  tests/python_client/requirements.txt
Labels: kind/enhancement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#38027 fix: [2.4]Check if the dynamic fields contain any static fields
  internal/proxy/util.go
  internal/proxy/util_test.go
  internal/proxy/validate_util.go
  internal/proxy/validate_util_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#38133 enhance: [10kcp] Reduce memory usage of BF in DataNode and QueryNode
  configs/milvus.yaml
  internal/datanode/writebuffer/l0_write_buffer.go
  internal/datanode/writebuffer/l0_write_buffer_test.go
  internal/querynodev2/segments/segment.go
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/component_param_test.go
Labels: size/M

#38045 fix: Fix variable redeclaration in term filter
  internal/core/src/exec/expression/TermExpr.cpp
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#37709 enhance: try compact small segments first if they may compose a full segment
  internal/datacoord/compaction_trigger.go
  internal/datacoord/compaction_trigger_test.go
  internal/datacoord/knapsack.go
  internal/datacoord/knapsack_test.go
Labels: kind/enhancement, size/XL, approved, lgtm, ci-passed, dco-passed, manual-pass

#38078 enhance: no need database check in restful sdk
  internal/distributed/proxy/httpserver/handler_v2.go
  internal/distributed/proxy/httpserver/handler_v2_test.go
  internal/rootcoord/drop_collection_task.go
  internal/rootcoord/meta_table.go
  internal/rootcoord/meta_table_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#38130 fix: move grant/revoke v2 params check from rootcoord to proxy
  internal/proxy/impl.go
  internal/proxy/util.go
  internal/rootcoord/root_coord.go
  tests/integration/rbac/privilege_group_test.go
Labels: kind/bug, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed, test/integration

#38102 enhance: [2.4] Refine clustering compaction log
  internal/datacoord/compaction_task_clustering.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#38096 fix: grant ManualCompact api doesn't work
  go.mod
  go.sum
  internal/proxy/database_interceptor.go
  internal/proxy/database_interceptor_test.go
  internal/proxy/impl.go
Labels: kind/bug, area/dependency, size/S, approved, lgtm, ci-passed, dco-passed

#38163 fix: Fix datacoord metrics
  internal/datacoord/index_meta.go
  internal/datacoord/meta.go
  internal/metastore/kv/datacoord/kv_catalog.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#38165 fix: [hotfix] Fix datacoord metrics
  internal/datacoord/index_meta.go
  internal/datacoord/meta.go
  internal/metastore/kv/datacoord/kv_catalog.go
Labels: size/M, approved, lgtm, ci-passed, manual-pass

#38164 fix: [2.4] Fix datacoord metrics
  internal/datacoord/index_meta.go
  internal/datacoord/meta.go
  internal/metastore/kv/datacoord/kv_catalog.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#38153 enhance: [10kcp] Update segment manger
  internal/datacoord/mock_segment_manager.go
  internal/datacoord/segment_manager.go
  internal/datacoord/segment_manager_test.go
  internal/datacoord/services.go
  internal/datacoord/services_test.go
Labels: size/XL

#38152 fix: [10kcp] Fix timeout when listing meta
  internal/metastore/kv/datacoord/kv_catalog.go
  internal/metastore/kv/datacoord/kv_catalog_test.go
  internal/metastore/kv/querycoord/kv_catalog.go
  internal/metastore/kv/querycoord/kv_catalog_test.go
Labels: size/L

#38100 enhance: Refine clustering compaction log
  internal/datacoord/compaction_task_clustering.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#38157 enhance: Use fdopen, fwrite to reduce direct syscall
  internal/core/src/common/File.h
  internal/core/src/mmap/Utils.h
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#38151 fix: Fix timeout when listing meta
  internal/metastore/kv/datacoord/kv_catalog.go
  internal/metastore/kv/datacoord/kv_catalog_test.go
  internal/metastore/kv/querycoord/kv_catalog.go
  internal/metastore/kv/querycoord/kv_catalog_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#38144 enhance: Add collection id to search request count metrics (#38069)
  internal/querynodev2/handlers.go
  internal/querynodev2/services.go
  pkg/metrics/querynode_metrics.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#38141 enhance: [GoSDK] add operate privilege & privilege group API
  client/entity/privilege_group.go
  client/milvusclient/rbac.go
  client/milvusclient/rbac_options.go
  client/milvusclient/rbac_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#38181 enhance: [hotfix] Use fdopen, fwrite to reduce direct syscall (#38157)
  internal/core/src/common/File.h
  internal/core/src/mmap/Utils.h
Labels: size/M, approved, lgtm, ci-passed, manual-pass

#38072 enhance: [2.4] Accelerate observe collection
  internal/querycoordv2/meta/collection_manager.go
  internal/querycoordv2/meta/collection_manager_test.go
  internal/querycoordv2/observers/collection_observer.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#38140 enhance: support db request in Restful api
  internal/datacoord/knapsack.go
  internal/distributed/proxy/httpserver/constant.go
  internal/distributed/proxy/httpserver/handler_v2.go
  internal/distributed/proxy/httpserver/handler_v2_test.go
  internal/distributed/proxy/httpserver/request_v2.go
  internal/proxy/util.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#38180 enhance: [2.4] Use fdopen, fwrite to reduce direct syscall (#38157)
  internal/core/src/common/File.h
  internal/core/src/mmap/Utils.h
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#38146 fix: [2.4] fix grant/revoke v2 meta and unclear error messages
  configs/milvus.yaml
  internal/proxy/impl.go
  internal/proxy/util.go
  internal/rootcoord/meta_table.go
  internal/rootcoord/meta_table_test.go
  internal/rootcoord/root_coord.go
  pkg/util/constant.go
  pkg/util/merr/errors.go
  pkg/util/merr/utils.go
  tests/integration/rbac/privilege_group_test.go
Labels: kind/bug, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, test/integration

#38176 enhance: add list aliases privilege into public role
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#38073 fix: [2.4] Fix inaccurate partition num metric
  internal/rootcoord/meta_table.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#38190 enhance: enable limiter for restful v1(#38160)
  internal/distributed/proxy/httpserver/handler_v1.go
  internal/distributed/proxy/httpserver/handler_v1_test.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#38188 enhance: support db request in Restful api(#38140)(#38078)
  internal/distributed/proxy/httpserver/constant.go
  internal/distributed/proxy/httpserver/handler_v2.go
  internal/distributed/proxy/httpserver/handler_v2_test.go
  internal/distributed/proxy/httpserver/request_v2.go
  internal/proxy/util.go
  internal/rootcoord/drop_collection_task.go
  internal/rootcoord/meta_table.go
  internal/rootcoord/meta_table_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#38160 enhance: enable limiter for restful v1
  internal/distributed/proxy/httpserver/handler_v1.go
  internal/distributed/proxy/httpserver/handler_v1_test.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#37653 enhance: Remove pre-marking segments as L2 during clustering compaction
  internal/datacoord/compaction_task_clustering.go
  internal/datacoord/compaction_task_clustering_test.go
  internal/datacoord/handler.go
  internal/datacoord/handler_test.go
  internal/datacoord/meta.go
  internal/datacoord/partition_stats_meta_test.go
  internal/metastore/kv/datacoord/kv_catalog.go
Labels: kind/enhancement, size/XL, approved, lgtm, ci-passed, dco-passed

#38167 enhance: Clean querynode metrics after collection released
  pkg/metrics/querynode_metrics.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#35595 enhance: optimize CPU usage for CheckHealth requests
  configs/milvus.yaml
  internal/datacoord/mock_segment_manager.go
  internal/datacoord/mock_session_manager.go
  internal/datacoord/mock_test.go
  internal/datacoord/server.go
  internal/datacoord/server_test.go
  internal/datacoord/services.go
  internal/datacoord/session_manager.go
  internal/datacoord/util.go
  internal/datanode/services.go
  internal/datanode/services_test.go
  internal/distributed/datanode/client/client.go
  internal/distributed/datanode/service.go
  internal/distributed/datanode/service_test.go
  internal/distributed/querynode/client/client.go
  internal/distributed/querynode/service.go
  internal/metastore/mocks/mock_rootcoord_catalog.go
  internal/mocks/mock_datanode.go
  internal/mocks/mock_datanode_client.go
  internal/mocks/mock_querynode.go
  internal/mocks/mock_querynode_client.go
  internal/proto/data_coord.proto
  internal/proto/query_coord.proto
  internal/querycoordv2/balance/channel_level_score_balancer.go
  internal/querycoordv2/balance/multi_target_balance.go
  internal/querycoordv2/balance/rowcount_based_balancer.go
  internal/querycoordv2/balance/score_based_balancer.go
  internal/querycoordv2/dist/dist_controller.go
  internal/querycoordv2/job/job_load.go
  internal/querycoordv2/job/job_release.go
  internal/querycoordv2/job/undo.go
  internal/querycoordv2/meta/collection_manager.go
  internal/querycoordv2/mocks/mock_querynode.go
  internal/querycoordv2/observers/collection_observer.go
  internal/querycoordv2/observers/target_observer.go
  internal/querycoordv2/server.go
  internal/querycoordv2/services.go
  internal/querycoordv2/services_test.go
  internal/querycoordv2/session/cluster.go
  internal/querycoordv2/session/mock_cluster.go
  internal/querycoordv2/task/executor.go
  internal/querycoordv2/task/scheduler.go
  internal/querycoordv2/utils/util.go
  internal/querynodev2/services.go
  internal/querynodev2/services_test.go
  internal/rootcoord/mock_test.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
  internal/rootcoord/util.go
  internal/util/componentutil/componentutil.go
  internal/util/healthcheck/checker.go
  internal/util/healthcheck/checker_test.go
  internal/util/mock/grpc_datanode_client.go
  internal/util/mock/grpc_querynode_client.go
  internal/util/wrappers/qn_wrapper.go
  pkg/util/funcutil/func.go
  pkg/util/merr/utils.go
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/component_param_test.go
  pkg/util/ratelimitutil/utils.go
Labels: kind/enhancement, size/XXL, approved, lgtm, ci-passed, area/internal-api, dco-passed

#38124 feat: add config field to set internal tls sni
  cmd/tools/config/generate.go
  configs/milvus.yaml
  internal/distributed/datacoord/client/client.go
  internal/distributed/datanode/client/client.go
  internal/distributed/indexnode/client/client.go
  internal/distributed/proxy/client/client.go
  internal/distributed/querycoord/client/client.go
  internal/distributed/querynode/client/client.go
  internal/distributed/rootcoord/client/client.go
  internal/mocks/mock_grpc_client.go
  internal/util/grpcclient/client.go
  internal/util/mock/grpcclient.go
  pkg/util/paramtable/grpc_param.go
  pkg/util/paramtable/grpc_param_test.go
  tests/integration/internaltls/internaltls_test.go
Labels: kind/feature, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, test/integration

#38148 fix: empty analyzer params not use standard tokenizer
  internal/core/thirdparty/tantivy/tantivy-binding/src/tokenizer.rs
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#38193 enhance: Add mmap file usage metric
  internal/core/src/mmap/Column.h
  internal/core/src/monitor/prometheus_client.cpp
  internal/core/src/monitor/prometheus_client.h
  internal/core/src/storage/MmapChunkManager.cpp
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#38208 enhance: [2.4] add list aliases privilege into public role and fix typo
  internal/proxy/impl.go
  internal/proxy/util.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#38067 fix: Add version to the proxy cache to resolve concurrency issues
  go.mod
  go.sum
  internal/proxy/impl.go
  internal/proxy/meta_cache.go
  internal/proxy/meta_cache_test.go
  internal/proxy/mock_cache.go
  internal/rootcoord/alter_alias_task.go
  internal/rootcoord/alter_alias_task_test.go
  internal/rootcoord/alter_collection_task.go
  internal/rootcoord/create_collection_task.go
  internal/rootcoord/describe_collection_task.go
  internal/rootcoord/drop_alias_task.go
  internal/rootcoord/drop_alias_task_test.go
  internal/rootcoord/meta_table.go
  internal/rootcoord/mocks/meta_table.go
  internal/rootcoord/rename_collection_task.go
  internal/rootcoord/rename_collection_task_test.go
  internal/util/hookutil/default.go
  tests/integration/minicluster_v2.go
Labels: kind/bug, area/dependency, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, test/integration

#38211 enhance: Add mmap file usage metric
  internal/core/src/mmap/Column.h
  internal/core/src/monitor/prometheus_client.cpp
  internal/core/src/monitor/prometheus_client.h
  internal/core/src/storage/MmapChunkManager.cpp
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#38007 enhance: refine pular related mq interfaces
  internal/datacoord/compaction_trigger.go
  internal/flushcommon/pipeline/flow_graph_dmstream_input_node_test.go
  internal/proxy/channels_mgr.go
  internal/proxy/channels_mgr_test.go
  internal/proxy/impl.go
  internal/proxy/impl_test.go
  internal/proxy/mock_channels_manager.go
  internal/proxy/mock_msgstream_test.go
  internal/proxy/mock_test.go
  internal/proxy/proxy.go
  internal/proxy/replicate_stream_manager.go
  internal/proxy/task_delete.go
  internal/proxy/task_delete_test.go
  internal/proxy/task_insert.go
  internal/proxy/task_test.go
  internal/proxy/task_upsert.go
  internal/proxy/util.go
  internal/proxy/util_test.go
  internal/rootcoord/dml_channels.go
  internal/rootcoord/dml_channels_test.go
  internal/util/flowgraph/input_node_test.go
  internal/util/flowgraph/node_test.go
  pkg/mq/msgdispatcher/manager_test.go
  pkg/mq/msgdispatcher/mock_test.go
  pkg/mq/msgstream/factory_stream_test.go
  pkg/mq/msgstream/mock_msgstream.go
  pkg/mq/msgstream/mq_kafka_msgstream_test.go
  pkg/mq/msgstream/mq_msgstream.go
  pkg/mq/msgstream/mq_msgstream_test.go
  pkg/mq/msgstream/mq_rocksmq_msgstream_test.go
  pkg/mq/msgstream/mqwrapper/client.go
  pkg/mq/msgstream/mqwrapper/kafka/kafka_client.go
  pkg/mq/msgstream/mqwrapper/kafka/kafka_client_test.go
  pkg/mq/msgstream/mqwrapper/kafka/kafka_producer_test.go
  pkg/mq/msgstream/mqwrapper/nmq/nmq_client.go
  pkg/mq/msgstream/mqwrapper/nmq/nmq_client_test.go
  pkg/mq/msgstream/mqwrapper/nmq/nmq_consumer_test.go
  pkg/mq/msgstream/mqwrapper/nmq/nmq_producer.go
  pkg/mq/msgstream/mqwrapper/nmq/nmq_producer_test.go
  pkg/mq/msgstream/mqwrapper/pulsar/pulsar_client.go
  pkg/mq/msgstream/mqwrapper/pulsar/pulsar_client_test.go
  pkg/mq/msgstream/mqwrapper/pulsar/pulsar_consumer_test.go
  pkg/mq/msgstream/mqwrapper/pulsar/pulsar_producer_test.go
  pkg/mq/msgstream/mqwrapper/rmq/rmq_client.go
  pkg/mq/msgstream/mqwrapper/rmq/rmq_client_test.go
  pkg/mq/msgstream/msgstream.go
  pkg/mq/msgstream/msgstream_util_test.go
  pkg/mq/msgstream/stream_bench_test.go
  pkg/mq/msgstream/stream_test.go
  pkg/mq/msgstream/wasted_mock_msgstream.go
Labels: kind/enhancement, size/XL, approved, lgtm, ci-passed, dco-passed

#38158 enhance: [ci]get log from loki instead of api-server
  ci/jenkins/PR-for-go-sdk.groovy
  ci/jenkins/PR.groovy
  ci/jenkins/UT-CPP.groovy
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#38204 enhance: [nightly ci] get log from loki instead of api-server
  ci/jenkins/Nightly2.groovy
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#38085 fix: Fix bug for Search fails with filter expression contains underscore
  internal/core/src/exec/expression/UnaryExpr.cpp
  internal/core/src/exec/expression/UnaryExpr.h
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#38212 enhance: Fill version for load delta request
  internal/querynodev2/delegator/delta_forward.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#38222 fix: compilation failed due to CI conflicts
  internal/proxy/task_test.go
Labels: kind/bug, size/XS, approved, lgtm, dco-passed

#38186 enhance: Put release segment and other misc cgo call into pool
  internal/querynodev2/segments/segment.go
  internal/querynodev2/segments/segment_loader.go
  internal/querynodev2/segments/utils.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#38229 enhance: [10kcp] Reduce mutex contention in datacoord meta
  internal/datacoord/compaction_policy_clustering.go
  internal/datacoord/compaction_policy_single.go
  internal/datacoord/compaction_trigger.go
  internal/datacoord/compaction_trigger_test.go
  internal/datacoord/meta.go
  internal/datacoord/meta_test.go
  internal/datacoord/segment_manager.go
Labels: size/L

#37907 enhance: [10kcp] Refine Replica manager colle2Replicas secondary index
  internal/querycoordv2/meta/replica_manager.go
Labels: size/L, approved, 10kcp

#38228 enhance: [2.4] Fill version for load delta request (#38212)
  internal/querynodev2/delegator/delta_forward.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#38218 fix: invalid rate limit for time tick delay
  internal/datanode/flow_graph_write_node.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass, kind/branch-feature

#38161 enhance: support templates for expression in Restful api(#38040)
  internal/distributed/proxy/httpserver/handler_v2.go
  internal/distributed/proxy/httpserver/handler_v2_test.go
  internal/distributed/proxy/httpserver/request_v2.go
  internal/distributed/proxy/httpserver/utils.go
  internal/distributed/proxy/httpserver/utils_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#38234 test: relax the checks on range search (#36542)
  tests/restful_client_v2/testcases/test_vector_operations.py
  tests/restful_client_v2/utils/utils.py
Labels: kind/improvement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed, kind/branch-feature, kind/test

#38154 enhance: Add ctx param to KV operation interfaces
  cmd/milvus/mck.go
  cmd/tools/datameta/main.go
  cmd/tools/migration/backend/etcd.go
  cmd/tools/migration/backend/etcd210.go
  cmd/tools/migration/backend/etcd220.go
  internal/datacoord/channel_manager_test.go
  internal/datacoord/channel_store.go
  internal/datacoord/channel_store_test.go
  internal/datacoord/index_meta_test.go
  internal/datacoord/index_service_test.go
  internal/datacoord/meta_test.go
  internal/datacoord/mock_test.go
  internal/datacoord/segment_manager_test.go
  internal/datacoord/server.go
  internal/datacoord/server_test.go
  internal/distributed/datanode/service_test.go
  internal/kv/etcd/embed_etcd_config_test.go
  internal/kv/etcd/embed_etcd_kv.go
  internal/kv/etcd/embed_etcd_kv_test.go
  internal/kv/etcd/embed_etcd_restart_test.go
  internal/kv/etcd/etcd_kv.go
  internal/kv/etcd/etcd_kv_test.go
  internal/kv/mem/mem_kv.go
  internal/kv/mem/mem_kv_test.go
  internal/kv/mock_snapshot_kv.go
  internal/kv/mock_snapshot_kv_test.go
  internal/kv/mocks/meta_kv.go
  internal/kv/mocks/snapshot_kv.go
  internal/kv/mocks/txn_kv.go
  internal/kv/mocks/watch_kv.go
  internal/kv/tikv/txn_tikv.go
  internal/kv/tikv/txn_tikv_test.go
  internal/metastore/kv/datacoord/kv_catalog.go
  internal/metastore/kv/datacoord/kv_catalog_test.go
  internal/metastore/kv/querycoord/kv_catalog.go
  internal/metastore/kv/querycoord/kv_catalog_test.go
  internal/metastore/kv/rootcoord/kv_catalog.go
  internal/metastore/kv/rootcoord/kv_catalog_test.go
  internal/metastore/kv/rootcoord/suffix_snapshot.go
  internal/metastore/kv/rootcoord/suffix_snapshot_test.go
  internal/metastore/kv/streamingcoord/kv_catalog.go
  internal/metastore/kv/streamingcoord/kv_catalog_test.go
  internal/metastore/kv/streamingnode/kv_catalog.go
  internal/metastore/kv/streamingnode/kv_catalog_test.go
  internal/querycoordv2/meta/replica_manager_test.go
  internal/querycoordv2/meta/resource_manager.go
  internal/querycoordv2/meta/resource_manager_test.go
  internal/querycoordv2/observers/collection_observer_test.go
  internal/querycoordv2/server.go
  internal/querycoordv2/task/task_test.go
  internal/tso/tso.go
  internal/util/sessionutil/session_util_test.go
  pkg/kv/kv.go
  pkg/kv/rocksdb/rocksdb_kv.go
  pkg/kv/rocksdb/rocksdb_kv_test.go
  pkg/mocks/mock_kv/mock_MetaKv.go
  pkg/mq/mqimpl/rocksmq/server/rocksmq_impl.go
  pkg/mq/mqimpl/rocksmq/server/rocksmq_retention.go
  pkg/mq/mqimpl/rocksmq/server/rocksmq_retention_test.go
Labels: kind/enhancement, size/XXL, approved, lgtm, ci-passed, dco-passed

#38233 enhance: Unify querycoord meta metrics
  internal/querycoordv2/job/job_release.go
  internal/querycoordv2/meta/collection_manager.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#38168 fix: grant ManualCompact api doesn't work (#38096)
  client/go.mod
  client/go.sum
  client/mock_milvus_server_test.go
  go.mod
  go.sum
  internal/proxy/database_interceptor.go
  internal/proxy/database_interceptor_test.go
  internal/proxy/impl.go
  pkg/go.mod
  pkg/go.sum
Labels: kind/bug, area/dependency, size/M, approved, lgtm, ci-passed, dco-passed

#38059 enhance: Make dynamic load/release partition follow targets
  internal/querycoordv2/job/job_load.go
  internal/querycoordv2/job/job_release.go
  internal/querycoordv2/job/job_sync.go
  internal/querycoordv2/job/job_test.go
  internal/querycoordv2/job/undo.go
  internal/querycoordv2/job/utils.go
  internal/querycoordv2/meta/mock_target_manager.go
  internal/querycoordv2/meta/target_manager.go
  internal/querycoordv2/observers/collection_observer_test.go
  internal/querycoordv2/observers/target_observer.go
  internal/querycoordv2/services.go
  internal/querycoordv2/services_test.go
  internal/querycoordv2/task/executor.go
  internal/querycoordv2/utils/meta.go
  internal/querynodev2/delegator/delegator.go
  internal/querynodev2/delegator/delegator_data.go
  internal/querynodev2/delegator/delegator_data_test.go
  internal/querynodev2/delegator/delegator_test.go
  internal/querynodev2/delegator/delta_forward_test.go
  internal/querynodev2/delegator/distribution.go
  internal/querynodev2/delegator/distribution_test.go
  internal/querynodev2/delegator/mock_delegator.go
  internal/querynodev2/delegator/snapshot.go
  internal/querynodev2/segments/validate.go
  internal/querynodev2/services.go
  internal/querynodev2/services_test.go
Labels: kind/enhancement, size/XL, approved, lgtm, ci-passed, dco-passed

#38246 enhance: remove the rpc layer of coordinator when enabling standalone or mixcoord
  cmd/milvus/util.go
  cmd/roles/roles.go
  configs/milvus.yaml
  go.mod
  go.sum
  internal/coordinator/coordclient/registry.go
  internal/coordinator/coordclient/registry_test.go
  internal/distributed/querycoord/service.go
  internal/querycoordv2/server.go
  internal/util/grpcclient/local_grpc_client.go
  internal/util/grpcclient/local_grpc_client_test.go
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/component_param_test.go
Labels: area/dependency, size/L

#38249 fix: [10kcp] Fix init rootcoord meta timeout
  internal/metastore/kv/rootcoord/kv_catalog.go
  internal/metastore/kv/rootcoord/suffix_snapshot.go
Labels: size/S

#38252 enhance: Resolve compilation error due to PR conflict
  internal/querycoordv2/job/job_release.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#38074 fix: [2.4] Fix checkGeneralCapacity slowly
  internal/rootcoord/constrant.go
  internal/rootcoord/create_collection_task.go
  internal/rootcoord/create_collection_task_test.go
  internal/rootcoord/create_partition_task.go
  internal/rootcoord/create_partition_task_test.go
  internal/rootcoord/meta_table.go
  internal/rootcoord/mocks/meta_table.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#38197 enhance: [2.4][ci] get log from loki instead of api-server
  ci/jenkins/Nightly2.groovy
  ci/jenkins/PR.groovy
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#38239 fix: fix crash when enable standby and streaming
  internal/datacoord/server.go
  internal/streamingcoord/server/builder.go
  internal/streamingcoord/server/server.go
  internal/streamingcoord/server/service/assignment.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#38266 fix: nil pointer in health check request
  internal/datacoord/session_manager.go
  internal/querycoordv2/services.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#38264 enhance: Remove pool from produer and consumer in kafka client
  pkg/mq/msgstream/mqwrapper/kafka/kafka_consumer.go
  pkg/mq/msgstream/mqwrapper/kafka/kafka_producer.go
  pkg/mq/msgstream/mqwrapper/kafka/pool.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#38111 enhance: [2.4]alterindex & altercollection supports altering properties
  go.mod
  go.sum
  internal/datacoord/index_service.go
  internal/datacoord/index_service_test.go
  internal/datacoord/mock_test.go
  internal/distributed/proxy/service.go
  internal/distributed/rootcoord/client/client.go
  internal/distributed/rootcoord/service.go
  internal/mocks/mock_proxy.go
  internal/mocks/mock_rootcoord.go
  internal/mocks/mock_rootcoord_client.go
  internal/proto/index_coord.proto
  internal/proto/root_coord.proto
  internal/proxy/impl.go
  internal/proxy/rootcoord_mock_test.go
  internal/proxy/task.go
  internal/proxy/task_index.go
  internal/rootcoord/alter_collection_task.go
  internal/rootcoord/alter_collection_task_test.go
  internal/rootcoord/broker.go
  internal/rootcoord/root_coord.go
  internal/util/mock/grpc_rootcoord_client.go
  pkg/go.mod
  pkg/go.sum
  pkg/util/typeutil/schema.go
Labels: kind/enhancement, area/dependency, size/XL, approved, lgtm, ci-passed, area/internal-api, dco-passed

#38247 enhance: Support collection name for ProxyDeleteVectors as well
  internal/proxy/task_delete.go
  pkg/metrics/proxy_metrics.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#38250 fix: sparse inc mast less than uint32 max
  internal/util/function/bm25_function.go
  pkg/util/typeutil/hash.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#38271 enhance: Set loaded collection/partition number to metrics
  internal/querycoordv2/meta/collection_manager.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#38268 enhance: use require dbname for some db req(#38267)
  internal/distributed/proxy/httpserver/handler_v2.go
  internal/distributed/proxy/httpserver/request_v2.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#38267 enhance: use require dbname for some db req
  internal/distributed/proxy/httpserver/handler_v2.go
  internal/distributed/proxy/httpserver/request_v2.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#38048 enhance: add end time stats for compaction and index build tasks
  internal/datacoord/compaction_task_clustering.go
  internal/datacoord/compaction_task_l0.go
  internal/datacoord/compaction_task_mix.go
  internal/datacoord/index_meta.go
  internal/metastore/model/segment_index.go
  pkg/util/metricsinfo/metrics_info.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#38033 enhance: add disk stats within system metrics
  internal/datacoord/metrics_info.go
  internal/datanode/metrics_info.go
  internal/indexnode/metrics_info.go
  internal/proxy/metrics_info.go
  internal/querycoordv2/handlers.go
  internal/querynodev2/metrics_info.go
  internal/rootcoord/metrics_info.go
  pkg/util/hardware/hardware_info.go
  pkg/util/hardware/hardware_info_test.go
  pkg/util/metricsinfo/metrics_info.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#37869 enhance: [2.4] Reduce segmentManager lock granularity
  internal/datacoord/mock_segment_manager.go
  internal/datacoord/segment_manager.go
  internal/datacoord/segment_manager_test.go
  internal/datacoord/server_test.go
  internal/datacoord/services.go
  internal/datacoord/services_test.go
Labels: kind/enhancement, size/XL, approved, lgtm, ci-passed, dco-passed, 10kcp

#38240 fix: [2.4] querycoord collection num metric (#36471)(#38233)
  internal/querycoordv2/job/job_release.go
  internal/querycoordv2/meta/collection_manager.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#38258 enhance: [GoSDK] Handle dynamic column & partial load output
  client/milvusclient/read.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#38262 enhance: refine lock granularity for produers in msgstream
  pkg/mq/msgstream/mq_msgstream.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#38274 fix: Datanode stop progress stuck at writer buffer memory check
  internal/flushcommon/writebuffer/manager.go
  internal/flushcommon/writebuffer/manager_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#38278 enhance: Refine the error msg for filter node
  internal/querynodev2/pipeline/filter_node.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#38277 enhance: [2.4] update knowhere version
  internal/core/thirdparty/knowhere/CMakeLists.txt
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed, area/compilation, kind/branch-feature

#38281 test: add restful testcases for database api
  tests/restful_client_v2/api/milvus.py
  tests/restful_client_v2/base/testbase.py
  tests/restful_client_v2/testcases/test_database_operation.py
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#38282 test: add restful testcases for database api
  tests/restful_client_v2/api/milvus.py
  tests/restful_client_v2/base/testbase.py
  tests/restful_client_v2/testcases/test_database_operation.py
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#38245 fix:remove unnecessary error logs
  internal/datacoord/task_index.go
  internal/datacoord/util.go
  internal/util/vecindexmgr/vector_index_mgr.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#38179 enhance: change bitmap index mmap mode to view mode
  internal/core/src/index/BitmapIndex.cpp
  internal/core/src/index/BitmapIndex.h
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#38210 enhance: [2.4]Determine the number of buffers based on the resource limits of the DataNode
  configs/milvus.yaml
  internal/datanode/compaction/clustering_compactor.go
  internal/datanode/compaction/clustering_compactor_test.go
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#38209 enhance: Determine the number of buffers based on the resource limits of the DataNode
  configs/milvus.yaml
  internal/datanode/compaction/clustering_compactor.go
  internal/datanode/compaction/clustering_compactor_test.go
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#38248 fix: Fix init rootcoord meta timeout
  internal/metastore/kv/rootcoord/kv_catalog.go
  internal/metastore/kv/rootcoord/suffix_snapshot.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#38253 fix: [2.4] Fix init rootcoord meta timeout (#38249)
  internal/metastore/kv/rootcoord/kv_catalog.go
  internal/metastore/kv/rootcoord/suffix_snapshot.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#38287 fix: Datanode stop progress stuck at writer buffer memory check (#38274)
  internal/datanode/writebuffer/manager.go
  internal/datanode/writebuffer/manager_test.go
  internal/querynodev2/pipeline/filter_node.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#38286 fix: [10kcp] Replace outer lock with concurrent map
  internal/datanode/writebuffer/manager.go
  internal/datanode/writebuffer/manager_test.go
  internal/datanode/writebuffer/write_buffer.go
Labels: size/L

#38298 enhance: [10kcp] Speed up meta recovery
  internal/metastore/kv/datacoord/kv_catalog.go
  internal/metastore/kv/querycoord/kv_catalog.go
  internal/metastore/kv/rootcoord/suffix_snapshot.go
  pkg/util/paramtable/service_param.go
  pkg/util/paramtable/service_param_test.go
Labels: size/M

#38300 fix: [10kcp] Query coord stop progress is too slow
  internal/querycoordv2/balance/channel_level_score_balancer_test.go
  internal/querycoordv2/balance/rowcount_based_balancer_test.go
  internal/querycoordv2/balance/score_based_balancer_test.go
  internal/querycoordv2/checkers/balance_checker_test.go
  internal/querycoordv2/checkers/channel_checker_test.go
  internal/querycoordv2/checkers/controller_base_test.go
  internal/querycoordv2/checkers/controller_test.go
  internal/querycoordv2/checkers/leader_checker_test.go
  internal/querycoordv2/checkers/segment_checker_test.go
  internal/querycoordv2/dist/dist_controller_test.go
  internal/querycoordv2/job/job_test.go
  internal/querycoordv2/meta/collection_manager_test.go
  internal/querycoordv2/meta/mock_broker.go
  internal/querycoordv2/meta/mock_target_manager.go
  internal/querycoordv2/meta/target_manager.go
  internal/querycoordv2/meta/target_manager_test.go
  internal/querycoordv2/mocks/mock_querynode.go
  internal/querycoordv2/observers/collection_observer_test.go
  internal/querycoordv2/observers/target_observer_test.go
  internal/querycoordv2/ops_service_test.go
  internal/querycoordv2/server.go
  internal/querycoordv2/server_test.go
  internal/querycoordv2/services_test.go
  internal/querycoordv2/task/task_test.go
Labels: size/L

#38225 enhance: update pymilvus version
  tests/python_client/requirements.txt
  tests/python_client/testcases/test_insert.py
Labels: kind/enhancement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#38227 enhance: update pymilvus version(2.4)
  tests/python_client/requirements.txt
Labels: kind/enhancement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#38312 enhance: [10kcp] Add secondary index for querynode segment manager
  internal/querynodev2/segments/manager.go
  internal/querynodev2/segments/segment_filter.go
  pkg/util/metautil/channel.go
Labels: approved, 10kcp

#38324 fix: [10kcp] Fix standby mixcoord start failed
  internal/datacoord/server.go
  internal/querycoordv2/server.go
  internal/rootcoord/root_coord.go
Labels: size/S

#38297 enhance: Remove constraint on release segment task
  internal/querycoordv2/task/executor.go
Labels: kind/bug, kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#38306 enhance: Remove constraint on release segment task
  internal/querycoordv2/task/executor.go
Labels: kind/bug, kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#38327 fix: [10kcp] Fix standby mixcoord start failed
  internal/datacoord/services.go
  internal/querycoordv2/services.go
  internal/rootcoord/root_coord.go
Labels: size/XS

#38296 enhance: Move `SyncCreatedPartition` step to proxy
  internal/proxy/impl.go
  internal/proxy/task.go
  internal/proxy/task_test.go
  internal/rootcoord/create_partition_task.go
  internal/rootcoord/step.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#38311 enhance: Add secondary index for querynode segment manager
  internal/querynodev2/segments/manager.go
  internal/querynodev2/segments/segment_filter.go
  pkg/util/metautil/channel.go
Labels: kind/enhancement, size/XL, approved, lgtm, ci-passed, dco-passed, 10kcp

#38202 fix: Leader task stuck and retry again and again
  internal/querycoordv2/task/action.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#38340 enhance: Add mockery package config for QC&QN
  Makefile
  internal/querycoordv2/.mockery.yaml
  internal/querynodev2/.mockery.yaml
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed, area/compilation

#38207 enhance: remove the rpc layer of coordinator when enabling standalone or mixcoord
  cmd/roles/roles.go
  configs/milvus.yaml
  internal/coordinator/coordclient/registry.go
  internal/coordinator/coordclient/registry_test.go
  internal/datacoord/server.go
  internal/distributed/datacoord/service.go
  internal/distributed/querycoord/service.go
  internal/distributed/querycoord/service_test.go
  internal/distributed/rootcoord/service.go
  internal/distributed/rootcoord/service_test.go
  internal/querycoordv2/server.go
  internal/querycoordv2/server_test.go
  internal/util/grpcclient/local_grpc_client.go
  internal/util/grpcclient/local_grpc_client_test.go
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/component_param_test.go
  pkg/util/syncutil/future.go
  pkg/util/syncutil/future_test.go
Labels: kind/enhancement, area/dependency, size/XL, approved, lgtm, ci-passed, dco-passed

#38352 enhance: [10kcp] Refine querynode collection number metrics
  internal/querynodev2/segments/collection.go
  internal/querynodev2/segments/manager.go
Labels: size/M, approved, 10kcp

#38328 enhance: [2.4] add metrics for counting number of nun-zeros/tokens of sparse search
  internal/proxy/task_search.go
  pkg/metrics/proxy_metrics.go
  pkg/util/funcutil/placeholdergroup.go
  pkg/util/typeutil/schema.go
  pkg/util/typeutil/schema_test.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#38349 fix: Leader task stuck and retry again and again (#38202)
  internal/querycoordv2/task/action.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#38345 enhance: Optimize save colelction target latency
  internal/metastore/kv/querycoord/kv_catalog.go
  internal/querycoordv2/meta/target_manager_test.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#37437 enhance: alterindex & altercollection supports altering properties
  go.mod
  go.sum
  internal/datacoord/index_service.go
  internal/datacoord/index_service_test.go
  internal/datacoord/mock_test.go
  internal/distributed/proxy/service.go
  internal/distributed/rootcoord/client/client.go
  internal/distributed/rootcoord/service.go
  internal/mocks/mock_rootcoord.go
  internal/mocks/mock_rootcoord_client.go
  internal/proto/index_coord.proto
  internal/proto/root_coord.proto
  internal/proxy/impl.go
  internal/proxy/rootcoord_mock_test.go
  internal/proxy/task.go
  internal/proxy/task_index.go
  internal/rootcoord/alter_collection_task.go
  internal/rootcoord/alter_collection_task_test.go
  internal/rootcoord/broker.go
  internal/rootcoord/root_coord.go
  internal/util/mock/grpc_rootcoord_client.go
  pkg/go.mod
  pkg/go.sum
  pkg/util/typeutil/schema.go
Labels: kind/enhancement, area/dependency, size/XL, approved, lgtm, ci-passed, area/internal-api, dco-passed, manual-pass

#38351 enhance: [2.4] keep the latest snapshot key if the origin key is existed
  internal/kv/etcd/etcd_kv.go
  internal/metastore/kv/rootcoord/suffix_snapshot.go
  internal/metastore/kv/rootcoord/suffix_snapshot_test.go
Labels: kind/enhancement, kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#38357 fix:add more info to local chunk manager log
  internal/core/src/storage/LocalChunkManager.cpp
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#38333 enhance: keep the latest snapshot key if the origin key is existed
  internal/kv/etcd/etcd_kv.go
  internal/metastore/kv/rootcoord/suffix_snapshot.go
  internal/metastore/kv/rootcoord/suffix_snapshot_test.go
Labels: kind/enhancement, kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#38356 fix: [skip e2e] unstable ut in services_test.go
  internal/querycoordv2/services_test.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed, kind/branch-feature

#38342 fix: Fix role be dropped when grant still exist.
  internal/rootcoord/root_coord.go
  tests/integration/rbac/rbac_basic_test.go
Labels: kind/bug, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, test/integration

#38350 enhance: Refine querynode collection number metrics
  internal/querynodev2/segments/collection.go
  internal/querynodev2/segments/manager.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#38361 enhance: [2.4]alterindex & altercollection supports altering properties
  tests/python_client/requirements.txt
Labels: kind/enhancement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#38362 enhance: alterindex & altercollection supports altering properties updata pymilvus (#37437)
  tests/python_client/requirements.txt
Labels: kind/enhancement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#38334 enhance: Refine task scheduler logs
  internal/datacoord/task_scheduler.go
  internal/indexnode/task_stats.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#38335 enhance: [2.4]Skip create index for l0 segment
  internal/datacoord/index_service.go
  internal/datacoord/task_scheduler.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#38353 fix: [2.4] Set the start time for index tasks that no need actual building
  internal/datacoord/task_index.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed, kind/branch-feature, 2.4-features

#38320 fix: stream connection leak in case of error
  pkg/mq/msgdispatcher/dispatcher.go
  pkg/mq/msgdispatcher/dispatcher_test.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#38321 fix: stream connection leak in case of error
  pkg/mq/msgdispatcher/dispatcher.go
  pkg/mq/msgdispatcher/dispatcher_test.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#38316 fix: Fix empty import task result
  internal/datacoord/import_util.go
  internal/datanode/importv2/task_manager.go
  internal/datanode/importv2/task_manager_test.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#38317 fix: [2.4] Fix empty import task result
  internal/datacoord/import_util.go
  internal/datanode/importv2/task_manager.go
  internal/datanode/importv2/task_manager_test.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#38259 fix: delay the wait other coord logic in query coord after query coord change into standby state
  internal/distributed/querycoord/service.go
  internal/distributed/querycoord/service_test.go
  internal/querycoordv2/server.go
  internal/querycoordv2/server_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#38341 fix: Use the correct RootPath when decompressing binlog in stats task
  internal/datacoord/import_checker.go
  internal/datacoord/import_checker_test.go
  internal/datacoord/import_util.go
  internal/datacoord/import_util_test.go
  internal/datacoord/job_manager.go
  internal/datacoord/mock_job_manager.go
  internal/datacoord/mock_segment_manager.go
  internal/indexnode/task_stats.go
  internal/metastore/kv/binlog/binlog.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#38143 enhance: Enable score based balance channel policy
  configs/milvus.yaml
  internal/querycoordv2/balance/balance.go
  internal/querycoordv2/balance/balance_test.go
  internal/querycoordv2/balance/channel_level_score_balancer.go
  internal/querycoordv2/balance/mock_balancer.go
  internal/querycoordv2/balance/rowcount_based_balancer.go
  internal/querycoordv2/balance/score_based_balancer.go
  internal/querycoordv2/balance/score_based_balancer_test.go
  internal/querycoordv2/checkers/channel_checker.go
  internal/querycoordv2/checkers/channel_checker_test.go
  internal/querycoordv2/checkers/controller_test.go
  internal/querycoordv2/handlers.go
  internal/querycoordv2/utils/meta.go
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/component_param_test.go
Labels: kind/enhancement, size/XL, approved, lgtm, ci-passed, dco-passed

#38369 fix: Fix role be dropped when grant still exist. (#38342)
  internal/rootcoord/root_coord.go
  tests/integration/rbac/rbac_basic_test.go
Labels: kind/bug, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, test/integration

#38376 fix:[2.4]Set the correct compactionFroms for clustering segments
  internal/datacoord/meta.go
  internal/datacoord/meta_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#38370 enhance: Optimize save collection target latency (#38345)
  internal/metastore/kv/querycoord/kv_catalog.go
  internal/querycoordv2/meta/target_manager_test.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#38344 enhance: improve mix compaction performance by removing max segment limitations
  configs/milvus.yaml
  internal/datacoord/compaction_trigger.go
  internal/datacoord/compaction_trigger_test.go
  internal/datacoord/knapsack.go
  internal/datanode/compaction/mix_compactor.go
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#38017 enhance: support recall estimation
  internal/proto/internal.proto
  internal/proxy/impl.go
  internal/proxy/task_search.go
  internal/proxy/util.go
  internal/proxy/util_test.go
  internal/querynodev2/segments/result.go
  internal/querynodev2/services.go
  internal/querynodev2/services_test.go
  internal/util/searchutil/optimizers/query_hook.go
  internal/util/searchutil/optimizers/query_hook_test.go
  pkg/common/common.go
  pkg/metrics/proxy_metrics.go
Labels: kind/enhancement, area/dependency, size/L, approved, lgtm, ci-passed, area/internal-api, dco-passed

#38064 enhance: [2.4] support recall estimation
  internal/proto/internal.proto
  internal/proxy/impl.go
  internal/proxy/task_search.go
  internal/proxy/util.go
  internal/proxy/util_test.go
  internal/querynodev2/optimizers/query_hook.go
  internal/querynodev2/optimizers/query_hook_test.go
  internal/querynodev2/segments/result.go
  internal/querynodev2/services.go
  internal/querynodev2/services_test.go
  pkg/common/common.go
  pkg/metrics/proxy_metrics.go
Labels: kind/enhancement, area/dependency, size/L, approved, lgtm, ci-passed, area/internal-api, dco-passed

#38375 fix: Check target partition load state only when dropping partition
  internal/proxy/util.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#38285 enhance: Speed up meta recovery
  internal/metastore/kv/datacoord/kv_catalog.go
  internal/metastore/kv/querycoord/kv_catalog.go
  internal/metastore/kv/rootcoord/suffix_snapshot.go
  pkg/util/paramtable/service_param.go
  pkg/util/paramtable/service_param_test.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#38392 enhance: remove unnecessary clone in meta cache (#36628)
  internal/datacoord/meta.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#38015 fix:GrowingDataGetter get the wrong string data
  internal/core/src/exec/operator/groupby/SearchGroupByOperator.h
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#38329 enhance: add metrics for counting number of nun-zeros/tokens of sparse/FTS search
  internal/proxy/task_search.go
  internal/querynodev2/delegator/delegator_data.go
  pkg/metrics/proxy_metrics.go
  pkg/metrics/querynode_metrics.go
  pkg/util/funcutil/placeholdergroup.go
  pkg/util/typeutil/schema.go
  pkg/util/typeutil/schema_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#38398 enhance: [10kcp] remove unnecessary clone in meta cache
  internal/datacoord/meta.go
Labels: size/S

#38404 enhance: [10kcp] Read metadata concurrently to accelerate recovery
  cmd/tools/migration/mmap/tool/main.go
  internal/datacoord/broker/coordinator_broker.go
  internal/datacoord/broker/mock_coordinator_broker.go
  internal/datacoord/compaction_task_clustering_test.go
  internal/datacoord/garbage_collector_test.go
  internal/datacoord/import_checker_test.go
  internal/datacoord/import_scheduler_test.go
  internal/datacoord/import_util_test.go
  internal/datacoord/meta.go
  internal/datacoord/meta_test.go
  internal/datacoord/mock_test.go
  internal/datacoord/segment_manager_test.go
  internal/datacoord/server.go
  internal/datacoord/server_test.go
  internal/distributed/rootcoord/client/client.go
  internal/distributed/rootcoord/client/client_test.go
  internal/distributed/rootcoord/service.go
  internal/metastore/catalog.go
  internal/metastore/kv/datacoord/kv_catalog.go
  internal/metastore/kv/datacoord/kv_catalog_test.go
  internal/metastore/kv/querycoord/kv_catalog.go
  internal/metastore/kv/querycoord/kv_catalog_test.go
  internal/metastore/kv/rootcoord/kv_catalog.go
  internal/metastore/kv/rootcoord/kv_catalog_test.go
  internal/metastore/mocks/mock_datacoord_catalog.go
  internal/metastore/mocks/mock_querycoord_catalog.go
  internal/metastore/mocks/mock_rootcoord_catalog.go
  internal/mocks/mock_rootcoord.go
  internal/mocks/mock_rootcoord_client.go
  internal/proto/root_coord.proto
  internal/proxy/rootcoord_mock_test.go
  internal/querycoordv2/meta/collection_manager.go
  internal/rootcoord/meta_table.go
  internal/rootcoord/meta_table_test.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
  internal/util/mock/grpc_rootcoord_client.go
  pkg/util/paramtable/service_param.go
  pkg/util/paramtable/service_param_test.go
Labels: size/XXL

#38385 test: add log level for go sdk test and update part cases
  tests/go_client/base/milvus_client.go
  tests/go_client/testcases/insert_test.go
  tests/go_client/testcases/load_release_test.go
  tests/go_client/testcases/main_test.go
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, manual-pass, kind/test

#38380 enhance: alterdatabase support delete property
  go.mod
  go.sum
  internal/proto/root_coord.proto
  internal/proxy/task_database.go
  internal/proxy/task_database_test.go
  internal/rootcoord/alter_collection_task.go
  internal/rootcoord/alter_database_task.go
  internal/rootcoord/alter_database_task_test.go
  internal/rootcoord/quota_center.go
  pkg/go.mod
  pkg/go.sum
Labels: kind/enhancement, area/dependency, size/L, approved, lgtm, ci-passed, dco-passed

#38394 fix: [2.4] Check target partition load state only when dropping partition (#38375)
  internal/proxy/util.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#38393 enhance: add privilege group privilege into built-in privilege group
  configs/milvus.yaml
  pkg/util/constant.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#38408 enhance: [2.4] add privilege group privilege into built-in privilege group
  configs/milvus.yaml
  pkg/util/constant.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed
