Repository milvus-io/milvus, pull requests merged in 2024-02, with the labels that each got.

#30405 enhance: Add PrimaryKeys interface to reduce memory usage
  internal/storage/primary_keys.go
  internal/storage/primary_keys_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#30406 test: refine debug log and error handle
  tests/python_client/chaos/checker.py
  tests/python_client/testcases/test_concurrent.py
  tests/scripts/ci_e2e_4am.sh
Labels: sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#30248 enhance: [skip e2e]revert back to original way to archive, upload and download
  .github/workflows/main.yaml
  scripts/run_cpp_codecov.sh
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#30420 enhance: move network mode of container into builder.sh file
  build/builder.sh
  ci/jenkins/PublishImages.groovy
  tests/scripts/e2e-k8s.sh
Labels: kind/enhancement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed, do-not-merge/missing-related-pr

#30408 enhance: Reduce get segments scan during l0 compaction
  internal/datanode/l0_compactor.go
  internal/datanode/l0_compactor_test.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#30364 fix: [skip e2e]use unique topic name for test pulsarCtl
  pkg/mq/msgstream/mqwrapper/pulsar/pulsar_client_test.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#30419 enhance: move the option of network mode into builder.sh file
  build/builder.sh
  ci/jenkins/PublishImages.groovy
  tests/scripts/e2e-k8s.sh
Labels: kind/enhancement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#30288 enhance: full-support for wildcard pattern matching
  internal/core/src/common/CMakeLists.txt
  internal/core/src/common/RegexQuery.cpp
  internal/core/src/common/RegexQuery.h
  internal/core/src/exec/expression/Expr.h
  internal/core/src/exec/expression/UnaryExpr.cpp
  internal/core/src/exec/expression/UnaryExpr.h
  internal/core/src/index/InvertedIndexTantivy.cpp
  internal/core/src/index/InvertedIndexTantivy.h
  internal/core/src/index/ScalarIndex.h
  internal/core/thirdparty/tantivy/tantivy-binding/include/tantivy-binding.h
  internal/core/thirdparty/tantivy/tantivy-binding/src/index_reader.rs
  internal/core/thirdparty/tantivy/tantivy-binding/src/index_reader_c.rs
  internal/core/thirdparty/tantivy/tantivy-wrapper.h
  internal/core/thirdparty/tantivy/test.cpp
  internal/core/unittest/CMakeLists.txt
  internal/core/unittest/test_bf.cpp
  internal/core/unittest/test_disk_file_manager_test.cpp
  internal/core/unittest/test_index_c_api.cpp
  internal/core/unittest/test_inverted_index.cpp
  internal/core/unittest/test_regex_query.cpp
  internal/core/unittest/test_regex_query_util.cpp
  internal/core/unittest/test_string_expr.cpp
  internal/core/unittest/test_utils.cpp
  internal/core/unittest/test_utils/GenExprProto.h
  internal/core/unittest/test_utils/indexbuilder_test_utils.h
  internal/parser/planparserv2/pattern_match.go
  internal/parser/planparserv2/pattern_match_test.go
  internal/parser/planparserv2/plan_parser_v2_test.go
Labels: kind/enhancement, size/XXL, approved, lgtm, ci-passed, dco-passed, area/compilation

#30277 fix: call injectDone after compaction failed
  internal/datacoord/compaction.go
  internal/datacoord/services.go
  internal/datanode/compaction_executor.go
  internal/datanode/compactor.go
  internal/datanode/compactor_test.go
  internal/datanode/l0_compactor.go
  internal/datanode/l0_compactor_test.go
  internal/datanode/services.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#30426 enhance: [skip e2e]extract cache stuff into a independent composite action
  .github/actions/cache/action.yaml
  .github/workflows/code-checker.yaml
  .github/workflows/main.yaml
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#30247 enhance: [skip e2e]correct a shell syntax error
  scripts/run_cpp_codecov.sh
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#30425 enhance: [skip e2e]cleanup unnecessary part in the github action
  .github/workflows/main.yaml
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#30114 fix: Support mvcc with hybrid serach
  internal/distributed/querynode/client/client.go
  internal/distributed/querynode/service.go
  internal/mocks/mock_querynode.go
  internal/mocks/mock_querynode_client.go
  internal/proto/internal.proto
  internal/proto/query_coord.proto
  internal/proxy/impl.go
  internal/proxy/reScorer.go
  internal/proxy/search_util.go
  internal/proxy/task_hybrid_search.go
  internal/proxy/task_hybrid_search_test.go
  internal/proxy/task_search.go
  internal/querycoordv2/mocks/mock_querynode.go
  internal/querynodev2/delegator/delegator.go
  internal/querynodev2/delegator/delegator_test.go
  internal/querynodev2/delegator/mock_delegator.go
  internal/querynodev2/handlers.go
  internal/querynodev2/services.go
  internal/querynodev2/services_test.go
  internal/util/mock/grpc_querynode_client.go
  internal/util/wrappers/qn_wrapper.go
Labels: kind/bug, size/XXL, approved, lgtm, ci-passed, area/internal-api, dco-passed

#30399 enhance: check load state before altering collection
  internal/proxy/impl.go
  internal/proxy/task.go
Labels: kind/enhancement, kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#30377 enhance: support varchar autoid when bulkinsert
  internal/util/importutil/import_util.go
  internal/util/importutil/numpy_parser_test.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#30435 enhance: [skip e2e]allow github actions runner run on ubuntu-latest os
  .github/workflows/main.yaml
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#30398 enhance: roll back apimachinery to v0.28.6
  go.mod
  go.sum
  pkg/go.mod
  pkg/go.sum
Labels: kind/enhancement, area/dependency, size/L, approved, lgtm, ci-passed, dco-passed

#30374 fix: Limit L0 Compaction segment size and count
  configs/milvus.yaml
  internal/datacoord/compaction_l0_view.go
  internal/datacoord/compaction_l0_view_test.go
  internal/datacoord/compaction_view_manager_test.go
  pkg/util/paramtable/component_param.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#30446 fix: Deprecated shard leader cache while deprecating collection
  internal/proxy/impl.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#30397 fix: Correct Size calculation of DeleteData
  internal/datanode/writebuffer/bf_write_buffer_test.go
  internal/datanode/writebuffer/delta_buffer.go
  internal/datanode/writebuffer/delta_buffer_test.go
  internal/datanode/writebuffer/l0_write_buffer_test.go
  internal/storage/data_codec.go
  internal/storage/data_codec_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#30465 adition index params for raft index
  pkg/util/indexparamcheck/cagra_checker.go
  pkg/util/indexparamcheck/cagra_checker_test.go
  pkg/util/indexparamcheck/constraints.go
  pkg/util/indexparamcheck/raft_ivf_flat_checker.go
  pkg/util/indexparamcheck/raft_ivf_flat_checker_test.go
  pkg/util/indexparamcheck/raft_ivf_pq_checker.go
Labels: size/M

#30400 enhance: update milvus-proto dep to add sparse vector related protos
  go.mod
  go.sum
Labels: kind/enhancement, area/dependency, size/XS, approved, lgtm, ci-passed, dco-passed

#30380 fix: failed to download OpenDAL
  scripts/3rdparty_build.sh
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#30440 enhance: Opt maxVectorFieldNum param check
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#30456 enhance: add milvus client rbac test cases
  tests/python_client/base/client_base.py
  tests/python_client/base/high_level_api_wrapper.py
  tests/python_client/milvus_client/test_milvus_client_rbac.py
Labels: kind/enhancement, sig/testing, size/XL, approved, lgtm, area/test, ci-passed, dco-passed

#30447 enhance: [skip e2e] add alter collection task ut
  internal/proxy/task_test.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#30453 fix: [2.3] add more requests to the database interceptor
  internal/proxy/database_interceptor.go
  internal/proxy/database_interceptor_test.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#30448 enhance: support varchar autoid when bulkinsert（#30377）
  internal/util/importutil/import_util.go
  internal/util/importutil/numpy_parser_test.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#30416 fix: proxy may never setup if the port binded (#30035)
  internal/distributed/proxy/service.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#30444 fix: fix requery without partitionIDs in hybrid search
  internal/proxy/search_util.go
  internal/proxy/task_hybrid_search.go
  internal/proxy/task_search.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#30452 fix: add more requests to the database interceptor
  internal/proxy/database_interceptor.go
  internal/proxy/database_interceptor_test.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#30472 update knowhere version
  internal/core/thirdparty/knowhere/CMakeLists.txt
Labels: size/XS, area/compilation

#30464 fix: fix hybrid search panic when has multi shard
  internal/proxy/task_hybrid_search.go
Labels: kind/bug, size/XS, approved, lgtm, dco-passed

#30459 doc: Add Milvus standalone all in one script
  scripts/standalone_embed.sh
Labels: kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed, manual-pass, kind/doc

#30471 enhance: Remove useless frequent log in Mintimestamp
  internal/datanode/writebuffer/segment_buffer.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#30461 fix: Only use bound indexnodes in bound mode
  internal/datacoord/server.go
Labels: kind/bug, kind/enhancement, size/XS, lgtm, dco-passed

#30439 fix: Decoupling importing segment from flush process (#30402)
  internal/datacoord/segment_allocation_policy.go
  internal/datacoord/segment_manager.go
  internal/datacoord/segment_manager_test.go
  internal/datacoord/server_test.go
  internal/datacoord/services.go
  tests/integration/bulkinsert/bulkinsert_test.go
Labels: kind/bug, sig/testing, size/L, approved, lgtm, area/test, dco-passed, test/integration

#30402 fix: Decoupling importing segment from flush process
  internal/datacoord/segment_allocation_policy.go
  internal/datacoord/segment_manager.go
  internal/datacoord/segment_manager_test.go
  internal/datacoord/server_test.go
  internal/datacoord/services.go
  internal/datacoord/services_test.go
  internal/datanode/importv2/util.go
  internal/datanode/metacache/actions.go
  internal/datanode/metacache/segment.go
  internal/datanode/services.go
  internal/datanode/writebuffer/write_buffer.go
  tests/integration/bulkinsert/bulkinsert_test.go
Labels: kind/bug, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, test/integration

#30475 enhance: calculate the accuracy memory usage while loading segment (#30473)
  internal/core/src/segcore/load_index_c.cpp
  internal/core/src/segcore/load_index_c.h
  internal/querynodev2/segments/segment_loader.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#30462 fix: [pick]Only use bound indexnodes in bound mode
  internal/datacoord/server.go
Labels: kind/bug, kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#29194 fix: donot set l0 segment as growing when savebinlogs
  internal/datacoord/compaction_trigger.go
  internal/datacoord/compaction_trigger_test.go
  internal/datacoord/meta.go
  internal/datacoord/meta_test.go
  internal/datacoord/services.go
  internal/datacoord/services_test.go
  internal/proxy/multi_rate_limiter_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#30410 enhance: Speed up L0 compaction
  internal/datanode/io/binlog_io.go
  internal/datanode/iterators/deltalog_iterator.go
  internal/datanode/iterators/deltalog_iterator_test.go
  internal/datanode/l0_compactor.go
  internal/datanode/l0_compactor_test.go
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#30492 enhance: Bump milvus & milvus-proto version to v2.3.8
  go.mod
  go.sum
  pkg/common/version.go
  pkg/go.mod
  pkg/go.sum
Labels: kind/enhancement, area/dependency, size/M, approved, lgtm, ci-passed, dco-passed, manual-pass, kind/branch-feature

#30489 enhance: Use dynamic pool for `NewLoadIndexInfo`
  internal/querynodev2/segments/load_index_info.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#30450 fix: not store timestampTo and timestampFrom
  internal/metastore/kv/binlog/binlog.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#30409 enhance: access log method support get status when method only return error instead of status
  internal/proxy/accesslog/info.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#30496 enhance: [Cherry-Pick] Fix some access log bugs
  internal/proxy/accesslog/info.go
  internal/proxy/accesslog/info_test.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#30497 enhance: [Cherry-pick] Use dynamic pool for `NewLoadIndexInfo` (#30489)
  internal/querynodev2/segments/load_index_info.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#30477 enhance: Extend support for varchar autoID to BulkInsertV2
  internal/datanode/importv2/executor_test.go
  internal/datanode/importv2/util.go
  internal/datanode/importv2/util_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#30478 enhance: [skip e2e] set logrus log level to reduce output error logs
  pkg/util/hardware/mem_info.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed, do-not-merge/missing-related-pr

#30505 enhance: [skip e2e]to use yaml anchor and alias to abstract common part in yaml
  .github/mergify.yml
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#30503 enhance: [Cherry-Pick] access log should get get client info by get method
  internal/proxy/accesslog/info.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#30498 enhance: [skip-e2e] disable asan
  internal/core/unittest/CMakeLists.txt
  internal/core/unittest/test_indexing.cpp
Labels: kind/enhancement, kind/improvement, size/XL, approved, lgtm, ci-passed, dco-passed, area/compilation

#30500 fix: Verify sync task target segment and retry if not match
  Makefile
  internal/datanode/syncmgr/key_lock_dispatcher.go
  internal/datanode/syncmgr/key_lock_dispatcher_test.go
  internal/datanode/syncmgr/mock_task.go
  internal/datanode/syncmgr/sync_manager.go
  internal/datanode/syncmgr/sync_manager_test.go
  internal/datanode/syncmgr/task.go
  internal/datanode/syncmgr/task_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed, area/compilation

#30518 fix: [skip e2e] Correct check UT for go rules
  .github/mergify.yml
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#29822 enhance: decrease coordinator init time
  internal/querycoordv2/observers/target_observer.go
  internal/util/sessionutil/session_util.go
  internal/util/sessionutil/session_util_test.go
  scripts/run_intergration_test.sh
  tests/integration/coordrecovery/coord_recovery_test.go
  tests/integration/minicluster_v2.go
Labels: kind/enhancement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, test/integration

#30508 fix: [skip-e2e] Fix unstable SaveBinlogPath ut
  internal/datacoord/services_test.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#30536 enhance: Add log when garbage collection resumed
  internal/datacoord/garbage_collector.go
Labels: kind/enhancement, size/XS, dco-passed

#30504 fix: safety access unordered_map and remove some useless code excute
  internal/core/src/segcore/SegmentSealedImpl.cpp
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#30540 enhance: Maximize build space at the begin
  .github/workflows/main.yaml
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#30027 enhance: disallow tikv/rawkv usages
  .golangci.yml
  internal/kv/tikv/main_test.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#30407 enhance: delete codc deserialize data by stream batch
  internal/storage/data_codec.go
  internal/storage/data_codec_test.go
  internal/storage/payload.go
  internal/storage/payload_reader.go
  internal/storage/payload_test.go
  internal/storage/utils.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#30562 enhance: [skip e2e]Maximize build space at the begin
  .github/workflows/code-checker.yaml
  .github/workflows/main.yaml
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#30428 fix: groupby results lack good results(#29883)
  internal/core/src/index/VectorMemIndex.cpp
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#30557 enhance: Use RWMutex and change WLock to RLock
  internal/datanode/metacache/bloom_filter_set.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#30188 feat: add a balancer based on both of row count and segment count
  internal/querycoordv2/balance/multi_target_balance.go
  internal/querycoordv2/balance/multi_target_balancer_test.go
  pkg/util/paramtable/component_param.go
Labels: kind/feature, size/XL, approved, lgtm, ci-passed, dco-passed

#30563 enhance: add configurable memory index load predict memory usage factor
  internal/querynodev2/segments/segment_loader.go
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/component_param_test.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#30549 enhance: update test cases and increase timeout of rbac pipeline
  ci/jenkins/Nightly.groovy
  tests/python_client/base/high_level_api_wrapper.py
  tests/python_client/milvus_client/test_milvus_client_alias.py
  tests/python_client/milvus_client/test_milvus_client_index.py
  tests/python_client/milvus_client/test_milvus_client_search.py
  tests/python_client/requirements.txt
  tests/python_client/testcases/test_collection.py
  tests/python_client/testcases/test_high_level_api.py
  tests/python_client/testcases/test_index.py
  tests/python_client/testcases/test_insert.py
  tests/python_client/testcases/test_search.py
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#30485 feat: restful support new features
  internal/distributed/proxy/httpserver/constant.go
  internal/distributed/proxy/httpserver/handler_v2.go
  internal/distributed/proxy/httpserver/handler_v2_test.go
  internal/distributed/proxy/httpserver/request_v2.go
  internal/distributed/proxy/httpserver/timeout_middleware.go
Labels: kind/feature, size/L, approved, lgtm, ci-passed, dco-passed

#30578 fix: erase pk empty check when pk index replace raw data (#30432)
  internal/core/src/segcore/SegmentSealedImpl.cpp
  internal/core/unittest/test_sealed.cpp
  internal/querynodev2/services.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#30532 fix: should return collectionName in response of ListAliases
  internal/proxy/task_alias.go
  internal/querycoordv2/services.go
  internal/rootcoord/root_coord.go
  tests/python_client/milvus_client/test_milvus_client_partition.py
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#30533 fix: should return collectionName in response of ListAliases
  internal/proxy/task_alias.go
  internal/querycoordv2/services.go
  internal/rootcoord/root_coord.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#30479 enhance: [skip e2e] set logrus log level to reduce output error logs
  pkg/util/hardware/mem_info.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#30601 enhance: remove unused code
  internal/core/src/exec/expression/TermExpr.h
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#30622 test: remove xfail for testcase
  tests/restful_client/testcases/test_vector_operations.py
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed, manual-pass, kind/test

#30523 enhance: Add param item for datanode l0 batch/linear mode memory ratio
  internal/datanode/l0_compactor.go
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#30603 fix: make compactor inject done called no more than once
  internal/datanode/compactor.go
  internal/datanode/compactor_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#29595 enhance: Add L2 segment level
  internal/proto/data_coord.proto
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#30628 enhance: Remove ci-passed label when ci failed on any changes to source code
  .github/mergify.yml
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#29567 feat: add collection level flush rate control
  configs/milvus.yaml
  internal/proxy/multi_rate_limiter.go
  internal/proxy/multi_rate_limiter_test.go
  internal/proxy/rate_limit_interceptor.go
  internal/proxy/rate_limit_interceptor_test.go
  internal/types/types.go
  pkg/util/paramtable/quota_param.go
  pkg/util/paramtable/quota_param_test.go
Labels: kind/feature, size/L, approved, lgtm, ci-passed, dco-passed

#30623 enhance: Print out range_filter and radius when range search param check fail
  internal/core/src/common/RangeSearchHelper.cpp
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#30625 enhance: Reduce unnessary log in binlog_io
  internal/datanode/io/binlog_io.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#30634 fix: Remove balance plan of which From, To nodes are same when merging
  internal/querycoordv2/balance/multi_target_balance.go
  internal/querycoordv2/balance/multi_target_balancer_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#30554 fix: Add retry on unimplemented error for datacoord
  internal/querycoordv2/meta/coordinator_broker.go
  internal/querycoordv2/meta/coordinator_broker_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#30635 enhance: Bump milvus version to v2.3.9
  pkg/common/version.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass, kind/branch-feature

#30639 fix: Add retry on unimplemented error for datacoord (#30554)
  internal/querycoordv2/meta/coordinator_broker.go
  internal/querycoordv2/meta/coordinator_broker_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#30640 enhance: Update Knowhere version
  internal/core/thirdparty/knowhere/CMakeLists.txt
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed, area/compilation, kind/branch-feature

#30573 enhance: [skip 2e2]add the option of host network mode into builder_gpu.sh file
  build/builder_gpu.sh
  ci/jenkins/PublishGPUImages.groovy
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#30649 enhance: move the option of network mode into builder.sh file
  build/builder_gpu.sh
  ci/jenkins/PublishGPUImages.groovy
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#30659 enhance:[skip e2e] disable dirty tag
  ci/jenkins/PublishGPUImages.groovy
  ci/jenkins/PublishImages.groovy
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#30660 enhance:[skip e2e] disable dirty tag
  ci/jenkins/PublishGPUImages.groovy
  ci/jenkins/PublishImages.groovy
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#30636 enhance: make balance cost threshold configurable
  internal/querycoordv2/balance/balance.go
  internal/querycoordv2/balance/multi_target_balance.go
  internal/querycoordv2/server.go
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#30641 enhance: Add force trigger
  internal/datacoord/compaction_l0_view.go
  internal/datacoord/compaction_l0_view_test.go
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#30666 fix: Prevent ChunkCache use absolute path in All-in-one mode
  internal/core/src/storage/ChunkCache.cpp
  internal/core/src/storage/ChunkCache.h
  internal/core/unittest/test_storage.cpp
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#30675 enhance: Update Knowhere version
  internal/core/thirdparty/knowhere/CMakeLists.txt
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed, area/compilation

#30197 enhance: convert the `GetObject` util to async (#30166)
  internal/core/src/storage/DiskFileManagerImpl.cpp
  internal/core/src/storage/MemFileManagerImpl.cpp
  internal/core/src/storage/Util.cpp
  internal/core/src/storage/Util.h
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#29830 test: add hybrid search cases
  tests/python_client/base/client_base.py
  tests/python_client/base/collection_wrapper.py
  tests/python_client/check/func_check.py
  tests/python_client/common/common_func.py
  tests/python_client/common/common_type.py
  tests/python_client/requirements.txt
  tests/python_client/testcases/test_index.py
  tests/python_client/testcases/test_query.py
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/XXL, approved, lgtm, area/test, ci-passed, dco-passed, manual-pass, kind/test

#30650 enhance: Use virtual host for tencent cloud
  internal/storage/minio_object_storage.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#30534 enhance: support clean paramtable config event in test
  internal/proxy/multi_rate_limiter_test.go
  pkg/config/event_dispatcher.go
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#30670 enhance: Check Level-zero segment memory usage as well
  internal/querynodev2/segments/segment_loader.go
  internal/querynodev2/segments/segment_loader_test.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#29725 enhance: replace binlogIO with io.BinlogIO in datanode
  internal/datanode/binlog_io.go
  internal/datanode/binlog_io_test.go
  internal/datanode/compactor.go
  internal/datanode/compactor_test.go
  internal/datanode/services.go
  internal/storage/data_codec.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#30473 enhance: calculate the accuracy memory usage while loading segment
  internal/core/src/segcore/load_index_c.cpp
  internal/core/src/segcore/load_index_c.h
  internal/querynodev2/segments/segment_loader.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#30415 enhance: limit the max pool size to 16 (#30371)
  internal/core/src/storage/ThreadPool.h
  internal/querynodev2/segments/pool.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#30548 enhance: Return parse expression failed error with reason
  internal/parser/planparserv2/utils.go
  internal/proxy/task_delete.go
  internal/proxy/task_query.go
  tests/python_client/testcases/test_delete.py
  tests/python_client/testcases/test_query.py
Labels: kind/enhancement, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#30679 fix: [Cherry-pick] Prevent ChunkCache use absolute path in All-in-one mode (#30666)
  internal/core/src/storage/ChunkCache.cpp
  internal/core/src/storage/ChunkCache.h
  internal/core/unittest/test_storage.cpp
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#30690 enhance: reduce many I/O operations while loading disk index (#30189)
  internal/core/src/storage/DiskFileManagerImpl.cpp
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#30695 doc: change image version to 2.3.9
  scripts/standalone_embed.sh
Labels: size/XS, approved, lgtm, ci-passed, dco-passed, kind/doc

#30702 fix: Update disk usage metrics after segment released
  internal/querynodev2/segments/segment.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#30697 enhance: [skip e2e] bump milvus version for scripts/standalone_embed.sh
  .github/workflows/bump-version.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#30696 enhance: [skip e2e]bump milvus version for scripts/standalone_embed.sh
  .github/workflows/bump-version.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#29773 enhance: Skip timestamp allocation when search/query consistency level is eventually
  internal/proxy/meta_cache.go
  internal/proxy/meta_cache_test.go
  internal/proxy/mock_cache.go
  internal/proxy/mock_test.go
  internal/proxy/task.go
  internal/proxy/task_alias.go
  internal/proxy/task_database.go
  internal/proxy/task_delete.go
  internal/proxy/task_hybrid_search.go
  internal/proxy/task_index.go
  internal/proxy/task_insert.go
  internal/proxy/task_query.go
  internal/proxy/task_query_test.go
  internal/proxy/task_scheduler.go
  internal/proxy/task_scheduler_test.go
  internal/proxy/task_search.go
  internal/proxy/task_search_test.go
  internal/proxy/task_statistic.go
  internal/proxy/task_upsert.go
Labels: kind/enhancement, size/XL, approved, lgtm, ci-passed, dco-passed

#30685 [Pick]enhance: Use virtual host for tencent cloud
  internal/storage/minio_object_storage.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass, do-not-merge/invalid-pr-format

#30668 fix: replace sse2 simd interface with older version
  internal/core/src/simd/avx512.cpp
  internal/core/src/simd/sse2.cpp
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#30658 enhance: The error information is not clear
  internal/proxy/validate_util.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#30707 fix: [cherry-pick] Update disk usage metrics after segment released (#30702)
  internal/querynodev2/segments/segment.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#30258 fix: Make leader checker generate leader task instead of segment task
  internal/querycoordv2/checkers/leader_checker.go
  internal/querycoordv2/checkers/leader_checker_test.go
  internal/querycoordv2/task/action.go
  internal/querycoordv2/task/executor.go
  internal/querycoordv2/task/scheduler.go
  internal/querycoordv2/task/task.go
  internal/querycoordv2/task/task_test.go
Labels: kind/bug, size/XL, approved, lgtm, ci-passed, dco-passed, manual-pass

#30704 enhance: Add deltalog expansion rate in segment loader
  internal/querynodev2/segments/segment_loader.go
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#30618 test: support multiple data/querynodes in integration test
  internal/datanode/broker/broker.go
  internal/datanode/broker/datacoord.go
  internal/datanode/broker/datacoord_test.go
  internal/datanode/broker/rootcoord.go
  internal/datanode/broker/rootcoord_test.go
  internal/datanode/data_node.go
  internal/datanode/data_sync_service.go
  internal/datanode/event_manager.go
  internal/datanode/flow_graph_manager.go
  internal/datanode/mock_test.go
  internal/datanode/services.go
  internal/datanode/stats_updater.go
  internal/datanode/syncmgr/meta_writer.go
  internal/datanode/syncmgr/meta_writer_test.go
  internal/datanode/syncmgr/sync_manager_test.go
  internal/datanode/syncmgr/task_test.go
  internal/datanode/syncmgr/taskv2_test.go
  internal/distributed/datanode/client/client.go
  internal/distributed/datanode/service.go
  internal/distributed/datanode/service_test.go
  internal/distributed/querynode/client/client.go
  internal/distributed/querynode/service.go
  internal/distributed/querynode/service_test.go
  internal/mocks/mock_datanode.go
  internal/mocks/mock_querynode.go
  internal/querynodev2/handlers.go
  internal/querynodev2/metrics_info.go
  internal/querynodev2/server.go
  internal/querynodev2/services.go
  internal/querynodev2/tasks/task.go
  internal/types/types.go
  pkg/util/merr/utils.go
  tests/integration/datanode/datanode_test.go
  tests/integration/minicluster_v2.go
  tests/integration/querynode/querynode_test.go
Labels: sig/testing, size/XXL, approved, lgtm, area/test, ci-passed, dco-passed, test/integration, kind/test

#30324 fix: move test from NEON to X86
  internal/core/unittest/test_simd.cpp
Labels: kind/bug, size/XXL, approved, lgtm, ci-passed, dco-passed

#30644 feat: support groupby on growing and non-indexed sealed egment(#30307)
  internal/core/src/common/QueryResult.h
  internal/core/src/index/VectorDiskIndex.cpp
  internal/core/src/index/VectorDiskIndex.h
  internal/core/src/index/VectorIndex.h
  internal/core/src/index/VectorMemIndex.cpp
  internal/core/src/index/VectorMemIndex.h
  internal/core/src/indexbuilder/VecIndexCreator.cpp
  internal/core/src/query/GroupByOperator.cpp
  internal/core/src/query/GroupByOperator.h
  internal/core/src/query/SearchBruteForce.cpp
  internal/core/src/query/SearchBruteForce.h
  internal/core/src/query/SearchOnGrowing.cpp
  internal/core/src/query/SearchOnGrowing.h
  internal/core/src/query/SearchOnIndex.cpp
  internal/core/src/query/SearchOnIndex.h
  internal/core/src/query/SearchOnSealed.cpp
  internal/core/src/query/SearchOnSealed.h
  internal/core/src/query/SubSearchResult.cpp
  internal/core/src/query/SubSearchResult.h
  internal/core/src/query/visitors/ExecPlanNodeVisitor.cpp
  internal/core/src/segcore/FieldIndexing.cpp
  internal/core/src/segcore/FieldIndexing.h
  internal/core/src/segcore/SegmentGrowingImpl.cpp
  internal/core/unittest/test_c_api.cpp
  internal/core/unittest/test_group_by.cpp
  internal/core/unittest/test_indexing.cpp
  internal/core/unittest/test_sealed.cpp
  internal/proxy/search_util.go
Labels: kind/feature, size/XXL, approved, lgtm, ci-passed, dco-passed, area/compilation

#30682 enhance: Adding a generic stream payload reader
  internal/storage/data_codec.go
  internal/storage/payload.go
  internal/storage/payload_reader.go
  internal/storage/payload_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#30502 enhance: access log should get get client info by get method
  internal/proxy/accesslog/info.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#30745 fix: [Cherry-pick] Release loaded growing if WatchDmlChannel fail (#30735)
  internal/querynodev2/services.go
  internal/querynodev2/services_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#30767 fix: cpp format check not work
  Makefile
  scripts/check_cpp_fmt.sh
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed, area/compilation

#30764 fix: pattern match use incorrect raw data
  internal/core/src/exec/expression/UnaryExpr.h
  internal/core/unittest/test_group_by.cpp
  internal/core/unittest/test_indexing.cpp
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed, area/compilation, manual-pass

#30749 fix: [Pick] Skip filling segmentID in indexBuildCh to prevent flush blocked
  internal/datacoord/meta.go
  internal/datacoord/server.go
  internal/datacoord/services.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#30773 fix: fix upsert using wrong field to compute partition key
  internal/proxy/task_upsert.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#30772 fix: fix upsert using wrong field to compute partition key
  internal/proxy/task_upsert.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#30718 enhance: Add unit test for level-zero segment deltalog request resource
  internal/querynodev2/segments/segment_loader_test.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#30770 enhance: Use defer to clean legacy growing segment
  internal/querynodev2/services.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#30755 fix: nil ptr is used as nil interface in grpc client
  internal/distributed/datacoord/client/client.go
  internal/distributed/datacoord/client/client_test.go
  internal/distributed/datanode/client/client.go
  internal/distributed/datanode/client/client_test.go
  internal/distributed/indexnode/client/client.go
  internal/distributed/indexnode/client/client_test.go
  internal/distributed/proxy/client/client.go
  internal/distributed/proxy/client/client_test.go
  internal/distributed/querycoord/client/client.go
  internal/distributed/querycoord/client/client_test.go
  internal/distributed/querynode/client/client.go
  internal/distributed/querynode/client/client_test.go
  internal/distributed/rootcoord/client/client.go
  internal/distributed/rootcoord/client/client_test.go
  tests/integration/crossclusterrouting/cross_cluster_routing_test.go
Labels: kind/bug, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, test/integration

#30724 fix: Skip generate balance task when target not ready
  internal/querycoordv2/checkers/balance_checker.go
  internal/querycoordv2/checkers/balance_checker_test.go
  internal/querycoordv2/checkers/controller.go
  internal/querycoordv2/task/scheduler.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#30341 test: add hybrid search in checker for test
  tests/python_client/base/collection_wrapper.py
  tests/python_client/chaos/checker.py
  tests/python_client/chaos/constants.py
  tests/python_client/chaos/testcases/test_all_collections_after_chaos.py
  tests/python_client/chaos/testcases/test_concurrent_operation.py
  tests/python_client/chaos/testcases/test_single_request_operation.py
  tests/python_client/common/common_func.py
  tests/python_client/requirements.txt
  tests/python_client/testcases/test_concurrent.py
  tests/restful_client/requirements.txt
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#30776 enhance: Bump milvus version to 2.3.10
  pkg/common/version.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed, kind/branch-feature

#30781 enhance: [2.3] change frequent log to debug
  internal/querynodev2/pipeline/insert_node.go
Labels: kind/enhancement, kind/improvement, size/XS, approved, dco-passed

#30805 [automated] Bump milvus version to v2.3.10
  deployments/binary/README.md
  deployments/docker/cluster-distributed-deployment/inventory.ini
  deployments/docker/gpu/standalone/docker-compose.yml
  deployments/docker/standalone/docker-compose.yml
Labels: size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#30671 enhance: refine error log of json parse error
  internal/proxy/validate_util.go
Labels: kind/enhancement, kind/improvement, size/XS, approved, dco-passed

#30706 fix: close rocksmq and natsmq when shutdown
  cmd/roles/roles.go
  internal/mq/mqimpl/rocksmq/server/rocksmq_impl.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#30664 enhance: some patches for #30636
  internal/querycoordv2/balance/multi_target_balance.go
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#30739 fix: reorder hybridsearch result for L2 metric
  internal/proxy/task_hybrid_search.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#30179 enhance: add addition index params for raft index
  pkg/util/indexparamcheck/cagra_checker.go
  pkg/util/indexparamcheck/cagra_checker_test.go
  pkg/util/indexparamcheck/constraints.go
  pkg/util/indexparamcheck/raft_ivf_flat_checker.go
  pkg/util/indexparamcheck/raft_ivf_flat_checker_test.go
  pkg/util/indexparamcheck/raft_ivf_pq_checker.go
  pkg/util/indexparamcheck/raft_ivf_pq_checker_test.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#30119 fix: compatibility for diskann cache param
  internal/datacoord/index_builder.go
  internal/datacoord/util.go
  pkg/util/indexparams/index_params.go
  pkg/util/indexparams/index_params_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#30757 fix: Disk resource is not requested for index loaded with disk
  internal/querynodev2/segments/index_attr_cache.go
  internal/querynodev2/segments/index_attr_cache_test.go
  internal/querynodev2/segments/segment_loader.go
  pkg/util/typeutil/pair.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#30753 enhance: reduce 1x memory copy when loading json
  internal/core/src/common/FieldDataInterface.h
Labels: kind/enhancement, kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#30782 enhance: change frequent log to debug
  internal/querynodev2/pipeline/insert_node.go
Labels: kind/enhancement, kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#30813 enhance: [skip e2e] How to build Milvus v2.3.4 arm image to support ky10 sp3
  DEVELOPMENT.md
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#30825 test: use jax.numpy to generate brain float16 datatype
  tests/python_client/common/common_func.py
  tests/python_client/requirements.txt
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#30821 test: fix query result empty
  tests/python_client/chaos/testcases/test_all_collections_after_chaos.py
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#30740 fix: [restful v2] bug list
  internal/distributed/proxy/httpserver/constant.go
  internal/distributed/proxy/httpserver/handler_v1.go
  internal/distributed/proxy/httpserver/handler_v1_test.go
  internal/distributed/proxy/httpserver/handler_v2.go
  internal/distributed/proxy/httpserver/handler_v2_test.go
  internal/distributed/proxy/httpserver/request_v2.go
  internal/distributed/proxy/httpserver/utils.go
  internal/distributed/proxy/httpserver/utils_test.go
Labels: kind/bug, size/XL, approved, lgtm, ci-passed, dco-passed, manual-pass

#30862 test: remove concurrent test in ci
  tests/scripts/ci_e2e_4am.sh
Labels: sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed, manual-pass, kind/test
