Repository milvus-io/milvus, pull requests merged in 2024-01, with the labels that each got.

#29599 test: add query expr test for larger int
  tests/python_client/testcases/test_query.py
Labels: sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed, manual-pass, kind/test

#29530 enhance: compaction use ChannelManager interface
  internal/datacoord/compaction.go
  internal/datacoord/compaction_test.go
Labels: kind/enhancement, size/XXL, approved, lgtm, ci-passed, dco-passed

#29614 enhance: add param for bloomfilter(#29388)
  configs/milvus.yaml
  internal/datanode/channel_meta_test.go
  internal/datanode/flow_graph_insert_buffer_node_test.go
  internal/datanode/segment.go
  internal/querynodev2/delegator/delegator_data_test.go
  internal/querynodev2/pkoracle/bloom_filter.go
  internal/querynodev2/segments/bloom_filter_set.go
  internal/querynodev2/segments/bloom_filter_set_test.go
  internal/storage/stats.go
  pkg/config/config.go
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#29226 enhance:Add upsert vector metrics
  internal/proxy/impl.go
  pkg/metrics/proxy_metrics.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#29628 fix: [Cherry-pick] throw exception when upload file failed for DiskIndex
  internal/core/src/index/VectorDiskIndex.cpp
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#29557 enhance: [2.3] Add concurrency for datacoord segment GC
  internal/datacoord/garbage_collector.go
  internal/datacoord/garbage_collector_test.go
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#29561 enhance: Add concurrency for datacoord segment GC
  internal/datacoord/garbage_collector.go
  internal/datacoord/garbage_collector_test.go
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#29562 enhance: [hotfix-2.3.3] Add concurrency for datacoord segment GC
  internal/datacoord/garbage_collector.go
  internal/datacoord/garbage_collector_test.go
  pkg/util/paramtable/component_param.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed

#29635 test: add multi-tenancy checker
  tests/python_client/chaos/checker.py
  tests/python_client/chaos/conftest.py
  tests/python_client/chaos/testcases/test_concurrent_operation_for_multi_tenancy.py
  tests/python_client/conftest.py
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, manual-pass

#29600 enhance: update pymilvus version
  tests/python_client/requirements.txt
Labels: kind/enhancement, kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed, manual-pass, kind/branch-feature

#29607 enhance: [skip e2e] use docker/steup-xxx-action plugin to do same thing instead
  .github/workflows/publish-builder.yaml
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#29534 test: update bulk insert bench test
  tests/python_client/bulk_insert/test_bulk_insert_bench.py
  tests/python_client/common/bulk_insert_data.py
Labels: sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#29535 test: update bulk insert bench test
  tests/python_client/bulk_insert/test_bulk_insert_bench.py
  tests/python_client/common/bulk_insert_data.py
Labels: sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#29634 test:add xfail for test case
  tests/python_client/testcases/test_query.py
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#29573 enhance: [skip e2e]abstract bump builder version into a composite action
  .github/actions/bump-builder-version/action.yaml
  .github/workflows/publish-builder.yaml
  .github/workflows/publish-gpu-builder.yaml
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#29653 fix: Print number of pks instead of delete pk val
  internal/datanode/flow_graph_delete_node.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed, kind/branch-feature

#29574 enhance: Rewrite gen segment plan based on assign segment
  internal/querycoordv2/balance/rowcount_based_balancer.go
  internal/querycoordv2/balance/score_based_balancer.go
  internal/querycoordv2/balance/score_based_balancer_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#29616 enhance: unable to compile C++ tests
  internal/core/src/index/IndexFactory.cpp
  internal/core/src/index/IndexFactory.h
  internal/core/unittest/test_string_index.cpp
  internal/proxy/proxy_test.go
  internal/rootcoord/show_collection_task.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#29612 enhance: Explicitly pass LevelZero segment ids in vchan info
  internal/datacoord/handler.go
  internal/datacoord/server_test.go
  internal/proto/data_coord.proto
  internal/querycoordv2/task/utils.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#29636 fix: serializer shall bypass L0 segment merge stats step
  internal/datanode/syncmgr/mock_serializer.go
  internal/datanode/syncmgr/storage_serializer.go
  internal/datanode/syncmgr/storage_v2_serializer.go
  internal/datanode/writebuffer/bf_write_buffer_test.go
  internal/datanode/writebuffer/write_buffer.go
  internal/datanode/writebuffer/write_buffer_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#29626 enhance: make delegator delete buffer holding all delete from cp
  internal/proto/query_coord.proto
  internal/querycoordv2/observers/target_observer.go
  internal/querynodev2/delegator/delegator.go
  internal/querynodev2/delegator/delegator_data.go
  internal/querynodev2/delegator/delegator_data_test.go
  internal/querynodev2/delegator/delegator_test.go
  internal/querynodev2/delegator/deletebuffer/delete_buffer.go
  internal/querynodev2/delegator/deletebuffer/list_delete_buffer.go
  internal/querynodev2/delegator/deletebuffer/list_delete_buffer_test.go
  internal/querynodev2/delegator/mock_delegator.go
  internal/querynodev2/services.go
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, area/internal-api, dco-passed

#29659 fix: the config value of DataCoordTimeTick become longer and longer
  internal/datacoord/server_test.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#29669 enhance: update pymilvus version
  tests/python_client/requirements.txt
Labels: kind/enhancement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#29640 fix: Reigster CompactionTaskNum metrics
  pkg/metrics/datacoord_metrics.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#29571 fix: Correct flush buffer size metrics
  internal/datanode/writebuffer/bf_write_buffer_test.go
  internal/datanode/writebuffer/insert_buffer.go
  internal/datanode/writebuffer/insert_buffer_test.go
  internal/datanode/writebuffer/l0_write_buffer.go
  internal/datanode/writebuffer/l0_write_buffer_test.go
  internal/datanode/writebuffer/write_buffer.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#29624 fix: unstable ut and fix goroutine leak
  internal/mq/mqimpl/rocksmq/client/client_impl_test.go
  internal/mq/mqimpl/rocksmq/client/consumer_impl_test.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#29668 enhance: cache collection schema attributes to reduce proxy cpu
  internal/distributed/proxy/httpserver/handler_v1.go
  internal/proxy/meta_cache.go
  internal/proxy/meta_cache_test.go
  internal/proxy/mock_cache.go
  internal/proxy/task.go
  internal/proxy/task_delete.go
  internal/proxy/task_delete_test.go
  internal/proxy/task_index.go
  internal/proxy/task_index_test.go
  internal/proxy/task_insert.go
  internal/proxy/task_query.go
  internal/proxy/task_query_test.go
  internal/proxy/task_search.go
  internal/proxy/task_search_test.go
  internal/proxy/task_test.go
  internal/proxy/task_upsert.go
  internal/proxy/task_upsert_test.go
  internal/proxy/util.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#29678 enhance: use GPU pool for gpu tasks
  internal/querynodev2/segments/collection.go
  internal/querynodev2/tasks/concurrent_safe_scheduler.go
  internal/querynodev2/tasks/mock_task_test.go
  internal/querynodev2/tasks/query_stream_task.go
  internal/querynodev2/tasks/query_task.go
  internal/querynodev2/tasks/task.go
  internal/querynodev2/tasks/tasks.go
  pkg/util/indexparamcheck/index_type.go
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#29610 enhance: fill missed info for segcore error
  internal/core/src/storage/Util.cpp
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#29592 enhance: Rename SearchV2 to HybridSearch
  go.mod
  go.sum
  internal/distributed/proxy/service.go
  internal/mocks/mock_proxy.go
  internal/proxy/impl.go
Labels: kind/enhancement, area/dependency, size/L, approved, lgtm, ci-passed, dco-passed

#29644 fix: make the entity num metric accurate (#29643)
  internal/querynodev2/delegator/delegator_data_test.go
  internal/querynodev2/segments/manager.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#29602 enhance: Read azure file without ReadAll
  internal/storage/azure_object_storage.go
  internal/storage/azure_object_storage_test.go
  internal/storage/file.go
  internal/storage/file_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#29679 enhance: [Cherry-pick] Cache segment row num, size, and insert count to reduce CGO calls (#28007)
  internal/querynodev2/segments/segment.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#29701 enhance: reduce SyncTask AllocID call and refine code
  internal/datanode/syncmgr/task.go
  internal/datanode/syncmgr/task_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#29702 fix: make sure balance candidate is alway pushed back
  internal/querycoordv2/balance/score_based_balancer.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#28910 feat: Add import reader for binlog
  internal/storage/insert_data.go
  internal/util/importutilv2/binlog/field_reader.go
  internal/util/importutilv2/binlog/filter.go
  internal/util/importutilv2/binlog/reader.go
  internal/util/importutilv2/binlog/reader_test.go
  internal/util/importutilv2/binlog/util.go
  internal/util/importutilv2/option.go
  internal/util/importutilv2/reader.go
  pkg/util/typeutil/schema.go
  scripts/run_go_unittest.sh
Labels: kind/feature, size/XXL, approved, lgtm, ci-passed, dco-passed

#29686 enhance: Add ctx for load index logs
  internal/querynodev2/segments/segment.go
  internal/querynodev2/segments/segment_loader.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#29703 enhance: get a blob to check object storage config
  internal/core/src/storage/azure-blob-storage/AzureBlobChunkManager.cpp
  internal/core/unittest/CMakeLists.txt
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed, area/compilation

#29674 enhance:Add upsert vector metrics(#29226)
  internal/proxy/impl.go
  pkg/metrics/proxy_metrics.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#28983 feat: support search_group_by for milvus(#25324)
  internal/core/src/common/QueryInfo.h
  internal/core/src/common/QueryResult.h
  internal/core/src/common/Types.h
  internal/core/src/index/VectorMemIndex.cpp
  internal/core/src/query/CMakeLists.txt
  internal/core/src/query/GroupByOperator.cpp
  internal/core/src/query/GroupByOperator.h
  internal/core/src/query/PlanProto.cpp
  internal/core/src/query/SearchOnSealed.cpp
  internal/core/src/query/visitors/ExecPlanNodeVisitor.cpp
  internal/core/src/segcore/Reduce.cpp
  internal/core/src/segcore/Reduce.h
  internal/core/src/segcore/ReduceStructure.h
  internal/core/src/segcore/SegmentGrowingImpl.cpp
  internal/core/src/segcore/SegmentGrowingImpl.h
  internal/core/src/segcore/SegmentInterface.h
  internal/core/src/segcore/SegmentSealedImpl.cpp
  internal/core/src/segcore/SegmentSealedImpl.h
  internal/core/unittest/CMakeLists.txt
  internal/core/unittest/bench/bench_search.cpp
  internal/core/unittest/test_group_by.cpp
  internal/core/unittest/test_sealed.cpp
  internal/core/unittest/test_utils/DataGen.h
  internal/core/unittest/test_utils/c_api_test_utils.h
  internal/proto/plan.proto
  internal/proxy/task.go
  internal/proxy/task_search.go
  internal/proxy/task_search_test.go
  internal/querynodev2/segments/result.go
  internal/querynodev2/segments/result_test.go
  pkg/util/typeutil/schema.go
Labels: kind/feature, area/dependency, size/XXL, approved, lgtm, ci-passed, dco-passed, area/compilation

#29454 enhance: refactor leader_observer to leader_checker
  internal/querycoordv2/checkers/balance_checker.go
  internal/querycoordv2/checkers/channel_checker.go
  internal/querycoordv2/checkers/checker.go
  internal/querycoordv2/checkers/controller.go
  internal/querycoordv2/checkers/controller_base_test.go
  internal/querycoordv2/checkers/index_checker.go
  internal/querycoordv2/checkers/leader_checker.go
  internal/querycoordv2/checkers/leader_checker_test.go
  internal/querycoordv2/checkers/segment_checker.go
  internal/querycoordv2/observers/collection_observer.go
  internal/querycoordv2/observers/collection_observer_test.go
  internal/querycoordv2/observers/leader_observer.go
  internal/querycoordv2/observers/leader_observer_test.go
  internal/querycoordv2/ops_services.go
  internal/querycoordv2/server.go
  internal/querycoordv2/server_test.go
  internal/querycoordv2/services_test.go
  internal/querycoordv2/task/utils.go
  internal/querycoordv2/utils/checker.go
Labels: kind/enhancement, size/XXL, approved, lgtm, ci-passed, dco-passed

#29682 fix: Unexpected rpc msg size limit
  configs/milvus.yaml
  pkg/util/paramtable/grpc_param.go
  pkg/util/paramtable/grpc_param_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#29579 enhance:change some logs
  internal/allocator/cached_allocator.go
  internal/datacoord/channel_manager.go
  internal/datacoord/compaction_l0_view_test.go
  internal/datacoord/compaction_trigger.go
  internal/datacoord/segment_manager.go
  internal/datacoord/server.go
  internal/datacoord/session_manager.go
  internal/datanode/binlog_io_test.go
  internal/datanode/event_manager.go
  internal/distributed/connection_manager.go
  internal/distributed/indexnode/service.go
  internal/indexnode/indexnode.go
  internal/indexnode/task_scheduler.go
  internal/mq/mqimpl/rocksmq/client/client_impl.go
  internal/mq/mqimpl/rocksmq/client/consumer_impl.go
  internal/mq/mqimpl/rocksmq/client/producer_impl.go
  internal/mq/mqimpl/rocksmq/client/test_helper.go
  internal/mq/mqimpl/rocksmq/server/rocksmq_impl.go
  internal/mq/mqimpl/rocksmq/server/rocksmq_retention.go
  internal/proxy/accesslog/minio_handler.go
  internal/proxy/accesslog/writer.go
  internal/proxy/meta_cache.go
  internal/proxy/segment.go
  internal/proxy/task.go
  internal/proxy/task_scheduler.go
  internal/proxy/task_search.go
  internal/querynodev2/pipeline/manager.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/timeticksync.go
  internal/storage/minio_object_storage.go
  internal/util/flowgraph/input_node.go
  internal/util/importutil/binlog_adapter.go
  internal/util/sessionutil/session_util.go
  pkg/mq/msgstream/mq_factory.go
  pkg/mq/msgstream/mqwrapper/kafka/kafka_client.go
  pkg/mq/msgstream/mqwrapper/kafka/kafka_consumer.go
  pkg/mq/msgstream/mqwrapper/kafka/kafka_producer.go
  pkg/util/funcutil/parallel.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#29646 enhance: support access log print cluster prefix
  internal/proxy/accesslog/formatter.go
  internal/proxy/accesslog/info.go
  internal/proxy/accesslog/info_test.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#29083 enhance: [skip e2e]increase timeout for image build
  ci/jenkins/PublishImages.groovy
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#29705 enhance: get a blob to check object storage config
  internal/core/src/storage/azure-blob-storage/AzureBlobChunkManager.cpp
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed, area/compilation

#29252 feat: Add import reader for json
  internal/storage/insert_data.go
  internal/util/importutilv2/json/reader.go
  internal/util/importutilv2/json/reader_test.go
  internal/util/importutilv2/json/row_parser.go
  pkg/util/typeutil/schema.go
Labels: kind/feature, size/XL, approved, lgtm, ci-passed, dco-passed

#29643 fix: make the entity num metric accurate
  internal/querynodev2/delegator/delegator_data_test.go
  internal/querynodev2/segments/manager.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#29713 enhance: add MockSerializer generation command into Makefile
  Makefile
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed, area/compilation

#29684 enhance: Rewrite gen segment plan based on assign segment (#29574)
  internal/querycoordv2/balance/rowcount_based_balancer.go
  internal/querycoordv2/balance/score_based_balancer.go
  internal/querycoordv2/balance/score_based_balancer_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#29737 fix: Assertion all async invocations in test case
  internal/querycoordv2/checkers/controller_test.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#29716 enhance: skip loading duplicated index (#29715)
  internal/querynodev2/segments/segment.go
  internal/querynodev2/segments/segment_test.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#29711 fix: Fix bug for pk index doesn't have raw data
  internal/core/src/segcore/SegmentSealedImpl.cpp
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#29618 feat: Add import reader for Parquet
  internal/util/importutilv2/parquet/field_reader.go
  internal/util/importutilv2/parquet/reader.go
  internal/util/importutilv2/parquet/reader_test.go
  internal/util/importutilv2/parquet/util.go
Labels: kind/feature, size/XXL, approved, lgtm, ci-passed, dco-passed

#29731 fix:[CHERRY_PICK] link with install path's libblob-chunk-manager
  internal/core/src/storage/CMakeLists.txt
  internal/core/src/storage/azure-blob-storage/test/CMakeLists.txt
  internal/distributed/proxy/httpserver/handler_v1.go
  internal/distributed/proxy/httpserver/handler_v1_test.go
  internal/distributed/proxy/service.go
  scripts/azure_build.sh
  scripts/core_build.sh
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed, area/compilation

#29506 feat: add clustering key in create/describe collection
  go.mod
  go.sum
  internal/metastore/model/field.go
  internal/proxy/task.go
  internal/proxy/task_test.go
  pkg/util/merr/errors.go
  pkg/util/merr/utils.go
Labels: kind/feature, area/dependency, size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#29627 fix: throw exception when upload file failed for DiskIndex
  internal/core/src/index/VectorDiskIndex.cpp
Labels: kind/bug, size/XS, dco-passed

#29586 enhance: add rust to install_dep.sh
  scripts/install_deps.sh
Labels: kind/enhancement, size/S, approved, lgtm, dco-passed

#29193 enhance: [skip-e2e] auto cancel stale workflows (#29145)
  .github/workflows/code-checker.yaml
  .github/workflows/mac.yaml
  .github/workflows/main.yaml
  .github/workflows/publish-builder.yaml
  .github/workflows/publish-gpu-builder.yaml
  .github/workflows/publish-krte-images.yaml
  .github/workflows/publish-test-images.yaml
  build/docker/builder/cpu/amazonlinux2023/Dockerfile
Labels: kind/enhancement, kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#29351 enhance: print total memory when milvus starts
  cmd/milvus/run.go
Labels: kind/enhancement, size/S, approved, lgtm, dco-passed

#29432 enhance: add compare simd function
  internal/core/src/exec/expression/CompareExpr.h
  internal/core/src/query/visitors/ExecExprVisitor.cpp
  internal/core/src/simd/CMakeLists.txt
  internal/core/src/simd/avx2.cpp
  internal/core/src/simd/avx512.cpp
  internal/core/src/simd/avx512.h
  internal/core/src/simd/common.h
  internal/core/src/simd/hook.cpp
  internal/core/src/simd/hook.h
  internal/core/src/simd/interface.h
  internal/core/src/simd/ref.h
  internal/core/src/simd/sse2.cpp
  internal/core/src/simd/sse4.cpp
  internal/core/unittest/test_simd.cpp
Labels: kind/enhancement, size/XXL, approved, lgtm, ci-passed, dco-passed, area/compilation

#29623 enhance: load delta logs concurrently
  internal/querynodev2/segments/segment_loader.go
Labels: kind/enhancement, kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#29695 fix: inverted index file not found
  internal/core/run_clang_format.sh
  internal/core/src/index/InvertedIndexTantivy.cpp
  internal/core/thirdparty/tantivy/tantivy-binding/include/tantivy-binding.h
  internal/core/thirdparty/tantivy/tantivy-binding/src/index_writer.rs
  internal/core/thirdparty/tantivy/tantivy-binding/src/index_writer_c.rs
  internal/core/thirdparty/tantivy/tantivy-wrapper.h
  internal/core/unittest/test_c_api.cpp
  internal/core/unittest/test_utils/indexbuilder_test_utils.h
  internal/core/unittest/test_utils/storage_test_utils.h
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#29692 enhance: [Cherry-pick] cache collection schema attributes to reduce proxy cpu (#29668)
  internal/distributed/proxy/httpserver/handler_v1.go
  internal/proxy/meta_cache.go
  internal/proxy/meta_cache_test.go
  internal/proxy/mock_cache.go
  internal/proxy/task.go
  internal/proxy/task_delete.go
  internal/proxy/task_delete_test.go
  internal/proxy/task_index.go
  internal/proxy/task_index_test.go
  internal/proxy/task_insert.go
  internal/proxy/task_query.go
  internal/proxy/task_query_test.go
  internal/proxy/task_search.go
  internal/proxy/task_search_test.go
  internal/proxy/task_test.go
  internal/proxy/task_upsert.go
  internal/proxy/task_upsert_test.go
  internal/proxy/util.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#29667 enhance:[skip e2e] use docker pugin to do same thing instead
  .github/workflows/publish-builder.yaml
  .github/workflows/publish-gpu-builder.yaml
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#29740 fix: Set & Return correct SegmentLevel in querynode segment manager
  internal/querynodev2/delegator/delegator_data.go
  internal/querynodev2/segments/segment.go
  internal/querynodev2/segments/segment_l0.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#29747 feat: Authorize users to query grant info of their roles
  internal/proxy/privilege_interceptor.go
  tests/python_client/testcases/test_utility.py
Labels: kind/feature, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#29433 feat: Support multiple vector search
  internal/core/src/segcore/SegmentGrowingImpl.h
  internal/core/src/segcore/SegmentSealedImpl.cpp
  internal/proto/query_coord.proto
  internal/proxy/impl.go
  internal/proxy/proxy_test.go
  internal/proxy/reScorer.go
  internal/proxy/reScorer_test.go
  internal/proxy/task.go
  internal/proxy/task_hybrid_search.go
  internal/proxy/task_hybrid_search_test.go
  internal/proxy/task_search.go
  internal/proxy/task_test.go
  internal/proxy/util.go
  internal/querycoordv2/task/executor.go
  internal/querycoordv2/task/utils.go
  internal/querycoordv2/task/utils_test.go
  internal/querynodev2/mock_data.go
  internal/querynodev2/segments/collection.go
  internal/querynodev2/segments/mock_data.go
  internal/querynodev2/segments/plan.go
  internal/querynodev2/services.go
  internal/querynodev2/services_test.go
  pkg/metrics/metrics.go
  pkg/util/typeutil/schema_test.go
  tests/integration/hybridsearch/hybridsearch_test.go
  tests/integration/util_index.go
Labels: kind/feature, area/dependency, sig/testing, size/XXL, approved, lgtm, area/test, ci-passed, area/internal-api, dco-passed, manual-pass, test/integration

#29753 enhance: use random root path for minio unit tests
  internal/storage/minio_chunk_manager_test.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#29629 enhance: Use ChannelManger interface in Server
  internal/datacoord/compaction_test.go
  internal/datacoord/server.go
  internal/datacoord/server_test.go
  internal/datacoord/services.go
  internal/datacoord/services_test.go
Labels: kind/enhancement, size/XXL, approved, lgtm, ci-passed, dco-passed

#29762 feat: Authorize users to query grant info of their roles (#29747)
  internal/proxy/privilege_interceptor.go
  tests/python_client/testcases/test_utility.py
Labels: kind/feature, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed, manual-pass

#29253 feat: Add import reader for numpy
  internal/storage/insert_data.go
  internal/util/importutilv2/numpy/field_reader.go
  internal/util/importutilv2/numpy/reader.go
  internal/util/importutilv2/numpy/reader_test.go
  internal/util/importutilv2/numpy/util.go
Labels: kind/feature, size/XL, approved, lgtm, ci-passed, dco-passed, manual-pass

#29771 fix: create new HybridSearch request in case of data race
  tests/integration/hybridsearch/hybridsearch_test.go
Labels: kind/bug, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed, manual-pass, test/integration

#29587 fix: compacted segment status was flushing instead flushed and L0 segment trigger gc slowly
  internal/datacoord/compaction.go
  internal/datacoord/compaction_test.go
  internal/datacoord/meta.go
  internal/datacoord/meta_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#29749 fix: Restore the MVCC functionality.
  internal/core/src/segcore/SegmentInterface.cpp
  internal/core/src/segcore/SegmentInterface.h
  internal/core/src/segcore/segment_c.cpp
  internal/core/src/segcore/segment_c.h
  internal/core/unittest/bench/bench_search.cpp
  internal/core/unittest/test_binlog_index.cpp
  internal/core/unittest/test_c_api.cpp
  internal/core/unittest/test_float16.cpp
  internal/core/unittest/test_group_by.cpp
  internal/core/unittest/test_growing_index.cpp
  internal/core/unittest/test_query.cpp
  internal/core/unittest/test_sealed.cpp
  internal/core/unittest/test_string_expr.cpp
  internal/core/unittest/test_utils/DataGen.h
  internal/core/unittest/test_utils/c_api_test_utils.h
  internal/proto/internal.proto
  internal/proto/internalpb/internal.pb.go~parent of ca1349708... Remove time travel ralted testcase (#26119)
  internal/proxy/lb_policy.go
  internal/proxy/lb_policy_test.go
  internal/proxy/task_delete.go
  internal/proxy/task_delete_test.go
  internal/proxy/task_hybrid_search.go
  internal/proxy/task_query.go
  internal/proxy/task_search.go
  internal/proxy/task_search_test.go
  internal/proxy/task_statistic.go
  internal/querynodev2/delegator/delegator.go
  internal/querynodev2/handlers.go
  internal/querynodev2/segments/plan.go
  internal/querynodev2/segments/reduce_test.go
  internal/querynodev2/segments/result.go
  internal/querynodev2/segments/segment.go
  internal/querynodev2/services.go
  internal/querynodev2/services_test.go
  internal/querynodev2/tasks/task.go
Labels: kind/bug, size/XXL, approved, lgtm, ci-passed, area/internal-api, dco-passed

#29758 enhance: make `ColumnBasedInsertMsgToInsertData` check field missing
  internal/datanode/writebuffer/write_buffer_test.go
  internal/storage/utils.go
  internal/storage/utils_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#29706 enhance: use GPU pool for gpu tasks (#29678)
  internal/querynodev2/segments/collection.go
  internal/querynodev2/tasks/concurrent_safe_scheduler.go
  internal/querynodev2/tasks/mock_task_test.go
  internal/querynodev2/tasks/query_stream_task.go
  internal/querynodev2/tasks/query_task.go
  internal/querynodev2/tasks/task.go
  internal/querynodev2/tasks/tasks.go
  pkg/util/indexparamcheck/index_type.go
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#29681 enhance: make the error of parsing expression to `ParameterInvalid`
  internal/proxy/task_search.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#29785 fix: limit minimal pq code size for diskann index
  internal/core/thirdparty/knowhere/CMakeLists.txt
Labels: size/XS, approved, lgtm, ci-passed, area/compilation, manual-pass

#29726 enhance: pre-allocate result FieldData space to reduce copy & growslice
  internal/proxy/task_search.go
  pkg/util/typeutil/schema.go
  pkg/util/typeutil/schema_test.go
  tests/integration/jsonexpr/json_expr_test.go
Labels: kind/enhancement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, manual-pass, test/integration

#29603 fix: add move cursor function to physical expr
  internal/core/src/exec/expression/AlwaysTrueExpr.h
  internal/core/src/exec/expression/CompareExpr.h
  internal/core/src/exec/expression/ConjunctExpr.cpp
  internal/core/src/exec/expression/ConjunctExpr.h
  internal/core/src/exec/expression/Expr.h
  internal/core/src/exec/expression/LogicalBinaryExpr.h
  internal/core/src/exec/expression/LogicalUnaryExpr.h
  internal/core/unittest/test_expr.cpp
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#29782 fix: [cherry-pick] Assertion all async invocations in test case (#29737)
  internal/querycoordv2/checkers/controller_test.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#29800 test: Add hybrid search test cases-collection part
  tests/python_client/common/common_func.py
  tests/python_client/common/common_type.py
  tests/python_client/testcases/test_collection.py
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#29801 enhance: update milvus-proto to support rbac for alias
  go.mod
  go.sum
Labels: kind/enhancement, area/dependency, size/XS, approved, lgtm, ci-passed, dco-passed

#29806 enhance: make Load process traceable in querycoord
  internal/querycoordv2/checkers/channel_checker.go
  internal/querycoordv2/checkers/segment_checker.go
  internal/querycoordv2/job/job_load.go
  internal/querycoordv2/meta/collection_manager.go
  internal/querycoordv2/task/task.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#29767 fix: the entities num metric may be contributed more than once
  internal/querynodev2/delegator/delegator_data.go
  internal/querynodev2/segments/manager.go
  internal/querynodev2/segments/segment.go
  internal/querynodev2/segments/segment_loader.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#29798 enhance: update milvus-proto to support rbac for alias
  go.mod
  go.sum
Labels: kind/enhancement, area/dependency, size/XS, approved, lgtm, ci-passed, dco-passed, kind/branch-feature

#29805 enhance: Upgrade gtest to 1.13.0
  internal/core/conanfile.py
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#29810 enhance: Correct sampleFraction's type to float
  internal/core/src/common/Tracer.h
  internal/core/src/common/type_c.h
  internal/util/initcore/init_core.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#29817 fix: meta cache in datanode incorrectly tracking row nums
  internal/datanode/metacache/meta_cache.go
  internal/datanode/metacache/meta_cache_test.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#29690 enhance: filter out the not needed collections while listing
  internal/rootcoord/show_collection_task.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#29833 enhance: remove .git folder for unit test workflow
  .github/workflows/main.yaml
  internal/querynodev2/services.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#29842 enhance: Use estimated batch size to initalize BF
  internal/datanode/metacache/bloom_filter_set.go
  internal/datanode/writebuffer/write_buffer.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#29751 fix: [cherry-pick]Save lite WatchInfo into etcd in DataNode
  internal/datanode/event_manager.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#29854 fix: Release collection delete proxy collection meta
  internal/proxy/task.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#29858 enhance: make Load process traceable in querynode & segcore
  internal/core/src/common/Tracer.cpp
  internal/core/src/common/Tracer.h
  internal/core/src/index/Index.h
  internal/core/src/index/InvertedIndexTantivy.cpp
  internal/core/src/index/InvertedIndexTantivy.h
  internal/core/src/index/ScalarIndexSort.cpp
  internal/core/src/index/ScalarIndexSort.h
  internal/core/src/index/StringIndexMarisa.cpp
  internal/core/src/index/StringIndexMarisa.h
  internal/core/src/index/VectorDiskIndex.cpp
  internal/core/src/index/VectorDiskIndex.h
  internal/core/src/index/VectorMemIndex.cpp
  internal/core/src/index/VectorMemIndex.h
  internal/core/src/segcore/load_index_c.cpp
  internal/core/src/segcore/load_index_c.h
  internal/core/unittest/test_indexing.cpp
  internal/core/unittest/test_inverted_index.cpp
  internal/core/unittest/test_utils/DataGen.h
  internal/querynodev2/segments/load_index_info.go
  internal/querynodev2/segments/segment.go
  internal/querynodev2/segments/segment_loader.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#29859 enhance: [skip e2e]We aim to cancel the previously initiated job exclusively during PR
  .github/workflows/code-checker.yaml
  .github/workflows/mac.yaml
  .github/workflows/main.yaml
  .github/workflows/publish-builder.yaml
  .github/workflows/publish-gpu-builder.yaml
  .github/workflows/publish-krte-images.yaml
  .github/workflows/publish-test-images.yaml
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#29613 feat: support mmap for marisa trie
  internal/core/src/common/File.h
  internal/core/src/index/StringIndexMarisa.cpp
  scripts/run_intergration_test.sh
Labels: kind/feature, size/M, approved, lgtm, ci-passed, dco-passed

#29825 fix: the entities num metric may be contributed more than once (#29767)
  internal/querynodev2/delegator/delegator_data.go
  internal/querynodev2/segments/manager.go
  internal/querynodev2/segments/segment.go
  internal/querynodev2/segments/segment_loader.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#29860 fix: increase expr recursion depth to avoid parse failed
  internal/core/src/query/Plan.cpp
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#29794 enhance: optimize search performance of inverted index
  internal/core/thirdparty/tantivy/CMakeLists.txt
  internal/core/thirdparty/tantivy/bench.cpp
  internal/core/thirdparty/tantivy/tantivy-binding/build.rs
  internal/core/thirdparty/tantivy/tantivy-binding/include/tantivy-binding.h
  internal/core/thirdparty/tantivy/tantivy-binding/src/array.rs
  internal/core/thirdparty/tantivy/tantivy-binding/src/data_type.rs
  internal/core/thirdparty/tantivy/tantivy-binding/src/hashset_collector.rs
  internal/core/thirdparty/tantivy/tantivy-binding/src/index_reader.rs
  internal/core/thirdparty/tantivy/tantivy-binding/src/index_reader_c.rs
  internal/core/thirdparty/tantivy/tantivy-binding/src/index_writer.rs
  internal/core/thirdparty/tantivy/tantivy-binding/src/index_writer_c.rs
  internal/core/thirdparty/tantivy/tantivy-binding/src/lib.rs
  internal/core/thirdparty/tantivy/tantivy-binding/src/linkedlist_collector.rs
  internal/core/thirdparty/tantivy/tantivy-binding/src/util.rs
  internal/core/thirdparty/tantivy/tantivy-binding/src/util_c.rs
  internal/core/thirdparty/tantivy/tantivy-binding/src/vec_collector.rs
  internal/core/thirdparty/tantivy/time_recorder.h
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed, area/compilation

#29715 enhance: skip loading duplicated index
  internal/querynodev2/segments/segment.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#29856 fix: Drop segment meta info with prefix
  internal/datacoord/meta_test.go
  internal/kv/etcd/embed_etcd_kv_test.go
  internal/metastore/kv/datacoord/kv_catalog.go
  internal/metastore/kv/datacoord/kv_catalog_test.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#29836 fix: remove Unnecessary lock in config manager
  pkg/config/manager.go
  pkg/config/manager_test.go
  pkg/mq/msgstream/mqwrapper/kafka/kafka_client_test.go
  pkg/util/paramtable/service_param_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#29873 enhance: Simplify cross cluster routing integration test
  tests/integration/crossclusterrouting/cross_cluster_routing_test.go
  tests/integration/minicluster_v2.go
Labels: kind/enhancement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, test/integration

#29802 fix: Restore the MVCC functionality. (#29749)
  internal/core/src/common/Channel.h
  internal/core/src/segcore/SegmentInterface.cpp
  internal/core/src/segcore/SegmentInterface.h
  internal/core/src/segcore/segment_c.cpp
  internal/core/src/segcore/segment_c.h
  internal/core/src/storage/azure-blob-storage/CMakeLists.txt
  internal/core/src/storage/azure-blob-storage/test/CMakeLists.txt
  internal/core/src/storage/azure-blob-storage/test/test_azure_blob_chunk_manager.cpp
  internal/core/unittest/bench/bench_search.cpp
  internal/core/unittest/test_array.cpp
  internal/core/unittest/test_array_expr.cpp
  internal/core/unittest/test_binlog_index.cpp
  internal/core/unittest/test_c_api.cpp
  internal/core/unittest/test_float16.cpp
  internal/core/unittest/test_growing_index.cpp
  internal/core/unittest/test_query.cpp
  internal/core/unittest/test_sealed.cpp
  internal/core/unittest/test_string_expr.cpp
  internal/core/unittest/test_utils.cpp
  internal/proto/internal.proto
  internal/proto/internalpb/internal.pb.go~parent of ca1349708... Remove time travel ralted testcase (#26119)
  internal/proxy/lb_policy.go
  internal/proxy/lb_policy_test.go
  internal/proxy/task_delete.go
  internal/proxy/task_delete_test.go
  internal/proxy/task_query.go
  internal/proxy/task_search.go
  internal/proxy/task_search_test.go
  internal/proxy/task_statistic.go
  internal/querynodev2/delegator/delegator.go
  internal/querynodev2/handlers.go
  internal/querynodev2/segments/plan.go
  internal/querynodev2/segments/reduce_test.go
  internal/querynodev2/segments/result.go
  internal/querynodev2/segments/segment.go
  internal/querynodev2/services.go
  internal/querynodev2/services_test.go
  internal/querynodev2/tasks/task.go
Labels: kind/bug, size/XXL, approved, lgtm, ci-passed, area/internal-api, dco-passed, area/compilation

#29870 fix: the insert count is zero after set the pointer to nil
  internal/querynodev2/segments/segment.go
  internal/querynodev2/segments/segment_test.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#29855 fix: Remove Unnecessary lock in config manager
  pkg/config/manager.go
  pkg/config/manager_test.go
  pkg/mq/msgstream/mqwrapper/kafka/kafka_client_test.go
  pkg/util/paramtable/service_param_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#29857 fix: Drop segment meta info with prefix
  internal/datacoord/meta_test.go
  internal/kv/etcd/embed_etcd_kv_test.go
  internal/metastore/kv/datacoord/kv_catalog.go
  internal/metastore/kv/datacoord/kv_catalog_test.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#29871 fix: Add multi logical exprs case
  tests/python_client/testcases/test_query.py
Labels: kind/bug, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#29720 enhance: Change some frequency log to rated level
  internal/proxy/meta_cache.go
  internal/querycoordv2/observers/collection_observer.go
  pkg/config/etcd_source.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#29866 enhance: [Cherry-pick] pre-allocate result FieldData space to reduce growslice (#29726)
  internal/proxy/task_search.go
  pkg/util/typeutil/schema.go
  pkg/util/typeutil/schema_test.go
  tests/integration/jsonexpr/json_expr_test.go
Labels: kind/enhancement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, test/integration

#29869 enhance: [Cherry-pick] make Load process traceable in querycoord (#29806)
  internal/querycoordv2/checkers/channel_checker.go
  internal/querycoordv2/checkers/segment_checker.go
  internal/querycoordv2/job/job_load.go
  internal/querycoordv2/meta/collection_manager.go
  internal/querycoordv2/task/task.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#29884 enhance: add standalone mode for nightly ci
  ci/jenkins/Nightly.groovy
  tests/scripts/values/ci/nightly-standalone-mode.yaml
Labels: kind/enhancement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#29524 enhance: clean .github/workflow/main.yaml
  .github/workflows/main.yaml
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#29641 feat: Implement DescribeAlias and ListAliases interfaces
  internal/datacoord/mock_test.go
  internal/distributed/proxy/httpserver/handler_test.go
  internal/distributed/proxy/service.go
  internal/distributed/proxy/service_test.go
  internal/distributed/rootcoord/client/client.go
  internal/distributed/rootcoord/client/client_test.go
  internal/distributed/rootcoord/service.go
  internal/mocks/mock_rootcoord.go
  internal/mocks/mock_rootcoord_client.go
  internal/proto/root_coord.proto
  internal/proxy/impl.go
  internal/proxy/proxy_test.go
  internal/proxy/rootcoord_mock_test.go
  internal/proxy/task.go
  internal/proxy/task_alias.go
  internal/proxy/task_alias_test.go
  internal/proxy/task_test.go
  internal/rootcoord/meta_table.go
  internal/rootcoord/meta_table_test.go
  internal/rootcoord/mock_test.go
  internal/rootcoord/mocks/meta_table.go
  internal/rootcoord/name_db.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
  internal/util/mock/grpc_rootcoord_client.go
  pkg/util/merr/errors.go
  pkg/util/merr/errors_test.go
  pkg/util/merr/utils.go
  tests/integration/alias/alias_test.go
Labels: kind/feature, sig/testing, size/XXL, approved, lgtm, area/test, ci-passed, dco-passed, test/integration

#29847 enhance: Support read hardware metrics for cgroupv2
  go.mod
  go.sum
  internal/querynodev2/segments/segment_loader.go
  pkg/go.mod
  pkg/go.sum
  pkg/util/hardware/container_linux.go
  pkg/util/hardware/container_test_linux.go
  pkg/util/hardware/hardware_info.go
Labels: kind/enhancement, area/dependency, size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#29882 enhance: update pymilvus version and test cases
  tests/python_client/requirements.txt
  tests/python_client/testcases/test_search.py
Labels: kind/enhancement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#29853 test: remove xfail from case
  tests/python_client/testcases/test_query.py
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#29900 fix: panic caused by type assert LocalSegment on Segment (#29018)
  internal/querynodev2/local_worker.go
  internal/querynodev2/local_worker_test.go
  internal/querynodev2/segments/retrieve.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#29881 fix: the insert count is zero after set the pointer to nil (#29870)
  internal/querynodev2/segments/segment.go
  internal/querynodev2/segments/segment_test.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#29850 enhance: Support read hardware metrics for cgroupv2
  go.mod
  go.sum
  internal/querynodev2/segments/segment_loader.go
  pkg/go.mod
  pkg/go.sum
  pkg/util/hardware/container_linux.go
  pkg/util/hardware/container_test_linux.go
  pkg/util/hardware/hardware_info.go
Labels: kind/enhancement, area/dependency, size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#29890 enhance: [skip e2e]debug why no configuration file when docker-compose up
  .github/workflows/main.yaml
Labels: kind/bug, kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#29903 enhance: Change some frequency log to rated level (#29720)
  internal/proxy/meta_cache.go
  internal/querycoordv2/observers/collection_observer.go
  pkg/config/etcd_source.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#29911 enhance: add trace span for wait tsafe
  internal/querynodev2/delegator/delegator.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#29912 fix: missing field data after appending scalar index to loaded segment
  internal/core/src/segcore/SegmentSealedImpl.cpp
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#29849 fix: unhealthy datacoord started with unhealthy channel manager
  internal/datacoord/server.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#29910 enhance: optimize the loading strategy
  internal/core/src/common/Consts.h
  internal/core/src/segcore/SegmentGrowingImpl.cpp
  internal/core/src/segcore/SegmentSealedImpl.cpp
  internal/core/src/segcore/Utils.cpp
  internal/core/src/segcore/Utils.h
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#29916 enhance: reduce delete detail log to delete range
  internal/querynodev2/services.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#29919 enhance: correct nightly e2e
  tests/scripts/get_release_name.sh
  tests/scripts/values/ci/nightly-one-pod.yaml
Labels: kind/enhancement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#29776 fix: compact operation on datacoord meta should preform as a transcation
  internal/datacoord/compaction.go
  internal/datacoord/meta.go
  internal/datacoord/meta_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#29902 fix: Dynamic update rate limit config with wrong value
  internal/proxy/multi_rate_limiter.go
  internal/proxy/multi_rate_limiter_test.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#29885 feat: Add RBAC functionality to alias
  pkg/go.mod
  pkg/go.sum
  pkg/util/constant.go
  pkg/util/funcutil/policy_test.go
  tests/python_client/testcases/test_utility.py
Labels: kind/feature, area/dependency, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#29891 enhance: move confusing warning log to error branch
  internal/datanode/flush_manager.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed, manual-pass, kind/branch-feature

#29896 feat: [Cherry-pick] Implement DescribeAlias and ListAliases interfaces
  internal/datacoord/mock_test.go
  internal/distributed/proxy/httpserver/handler_test.go
  internal/distributed/proxy/service.go
  internal/distributed/proxy/service_test.go
  internal/distributed/rootcoord/client/client.go
  internal/distributed/rootcoord/client/client_test.go
  internal/distributed/rootcoord/service.go
  internal/mocks/mock_rootcoord.go
  internal/mocks/mock_rootcoord_client.go
  internal/proto/root_coord.proto
  internal/proxy/impl.go
  internal/proxy/proxy_test.go
  internal/proxy/rootcoord_mock_test.go
  internal/proxy/task.go
  internal/proxy/task_alias.go
  internal/proxy/task_alias_test.go
  internal/proxy/task_test.go
  internal/rootcoord/meta_table.go
  internal/rootcoord/meta_table_test.go
  internal/rootcoord/mock_test.go
  internal/rootcoord/mocks/meta_table.go
  internal/rootcoord/name_db.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
  internal/util/mock/grpc_rootcoord_client.go
  pkg/util/merr/errors.go
  pkg/util/merr/errors_test.go
  pkg/util/merr/utils.go
  tests/integration/alias/alias_test.go
Labels: kind/feature, sig/testing, size/XXL, approved, lgtm, area/test, ci-passed, dco-passed, test/integration

#29894 enhance: optimize the loading index performance
  internal/core/src/index/VectorMemIndex.cpp
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#29917 fix: [2.3] the delete msg disorder issue
  internal/datanode/compactor.go
  internal/datanode/compactor_test.go
Labels: kind/bug, kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#29336 feat: integrate storagev2 into loading segment
  go.mod
  go.sum
  internal/core/src/indexbuilder/IndexFactory.h
  internal/core/src/indexbuilder/VecIndexCreator.cpp
  internal/core/src/indexbuilder/VecIndexCreator.h
  internal/core/src/indexbuilder/index_c.cpp
  internal/core/src/segcore/Utils.cpp
  internal/core/src/segcore/Utils.h
  internal/core/src/storage/DiskFileManagerImpl.cpp
  internal/core/src/storage/Util.cpp
  internal/core/thirdparty/milvus-storage/CMakeLists.txt
  internal/datacoord/index_builder.go
  internal/datacoord/meta.go
  internal/datanode/syncmgr/storage_v2_serializer.go
  internal/datanode/syncmgr/storage_v2_serializer_test.go
  internal/datanode/syncmgr/taskv2.go
  internal/datanode/syncmgr/taskv2_test.go
  internal/indexnode/indexnode_service.go
  internal/proto/query_coord.proto
  internal/querycoordv2/utils/types.go
  internal/querynodev2/segments/load_field_data_info.go
  internal/querynodev2/segments/load_index_info.go
  internal/querynodev2/segments/mock_data.go
  internal/querynodev2/segments/mock_loader.go
  internal/querynodev2/segments/segment.go
  internal/querynodev2/segments/segment_loader.go
  internal/querynodev2/segments/segment_loader_test.go
  internal/querynodev2/server.go
  internal/util/typeutil/schema.go
  internal/util/typeutil/storage.go
  pkg/util/paramtable/component_param.go
Labels: kind/feature, area/dependency, size/XXL, approved, lgtm, ci-passed, area/internal-api, dco-passed, area/compilation, manual-pass

#29724 enhance: Skip generate load segment task
  internal/querycoordv2/checkers/controller_test.go
  internal/querycoordv2/checkers/segment_checker.go
  internal/querycoordv2/checkers/segment_checker_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#29905 enhance: Add ctx for load index logs (#29686)
  internal/querynodev2/segments/segment.go
  internal/querynodev2/segments/segment_loader.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#29831 enhance: [Cherry-Pick] support access log print cluster prefix (#29646)
  internal/proxy/accesslog/formatter.go
  internal/proxy/accesslog/info.go
  internal/proxy/accesslog/info_test.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#29898 fix: Fix error message for indexing
  internal/proxy/task_index.go
  tests/python_client/testcases/test_index.py
Labels: kind/bug, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#29929 enhance: [cherry-pick] add trace span for wait tsafe (#29911)
  internal/querynodev2/delegator/delegator.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#29930 enhance: [cherry-pick] reduce delete detail log to delete range (#29916)
  internal/querynodev2/services.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#29946 enhance: bump milvus & proto version to 2.3.5
  go.sum
  pkg/common/version.go
  pkg/go.mod
  pkg/go.sum
Labels: kind/enhancement, area/dependency, size/S, approved, lgtm, ci-passed, dco-passed, manual-pass, kind/branch-feature

#29941 fix: remove checking if running inside container
  go.mod
  go.sum
  pkg/go.mod
  pkg/go.sum
  pkg/util/hardware/container_darwin.go
  pkg/util/hardware/container_linux.go
  pkg/util/hardware/container_test_linux.go
  pkg/util/hardware/container_windows.go
  pkg/util/hardware/hardware_info.go
  pkg/util/hardware/mem_info_darwin.go
Labels: kind/bug, area/dependency, size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#29939 enhance: Add a group by case
  tests/python_client/common/common_func.py
  tests/python_client/testcases/test_search.py
Labels: kind/enhancement, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#29945 enhance: make compactor use actual buffer size to decide when to sync
  internal/datanode/binlog_io_test.go
  internal/datanode/compactor.go
  internal/datanode/compactor_test.go
  internal/datanode/mock_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#29922 enhance: Use newer checkpoint when packing LoadSegmentRequest
  internal/querycoordv2/utils/types.go
  internal/querycoordv2/utils/types_test.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#29959 enhance: [skip e2e]fix conan lock issue in macos
  .github/workflows/mac.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed
