Repository milvus-io/milvus, pull requests merged in 2024-03, with the labels that each got.

#30955 enhance: Remove debug log
  internal/datanode/flow_graph_manager.go
  internal/datanode/services.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#30944 fix: Use localStorage path to check disk cap
  pkg/util/paramtable/component_param.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#29568 feat: add collection level flush rate control
  configs/milvus.yaml
  internal/proxy/multi_rate_limiter.go
  internal/proxy/multi_rate_limiter_test.go
  internal/proxy/rate_limit_interceptor.go
  internal/proxy/rate_limit_interceptor_test.go
  internal/types/types.go
  pkg/util/paramtable/quota_param.go
  pkg/util/paramtable/quota_param_test.go
Labels: kind/feature, size/L, approved, lgtm, ci-passed, dco-passed

#30829 enhance: optimize access log formatter and add bench test
  internal/proxy/accesslog/benchmark_test.go
  internal/proxy/accesslog/formatter.go
  internal/proxy/accesslog/info.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#30429 enhance: clean invalid pipline excluded segment info
  internal/querynodev2/pipeline/filter_node.go
  internal/querynodev2/pipeline/filter_node_test.go
  internal/querynodev2/pipeline/filter_policy.go
  internal/querynodev2/pipeline/pipeline.go
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#30914 fix: Mmap could be enabled on ScaNN index
  pkg/util/indexparamcheck/index_type.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#30834 fix: Add hybridsearch result cases
  tests/python_client/testcases/test_search.py
Labels: kind/bug, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#30946 fix: [restful v2] align search api with milvus client
  internal/distributed/proxy/httpserver/handler_v1.go
  internal/distributed/proxy/httpserver/handler_v2.go
  internal/distributed/proxy/httpserver/handler_v2_test.go
  internal/distributed/proxy/httpserver/request_v2.go
  internal/distributed/proxy/httpserver/utils.go
  internal/distributed/proxy/httpserver/utils_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#30847 fix:Update tencent cloud version
  go.mod
  go.sum
Labels: kind/bug, area/dependency, size/XS, approved, lgtm, ci-passed, dco-passed

#30850 fix: Clear DN unkown compaction tasks
  internal/datacoord/compaction.go
  internal/datacoord/compaction_test.go
  internal/datacoord/compaction_trigger.go
  internal/datacoord/mock_session_manager.go
  internal/datacoord/session_manager.go
  internal/datanode/compaction_executor.go
  internal/datanode/services.go
  internal/datanode/services_test.go
  tests/integration/datanode/compaction_test.go
Labels: kind/bug, area/dependency, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, test/integration

#30766 enhance: Refine describe collection error message when collection not found
  internal/proxy/task.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#30948 fix: [Cherry-pick] Disk resource is not requested for index loaded with disk (#30757)
  internal/querynodev2/segments/index_attr_cache.go
  internal/querynodev2/segments/index_attr_cache_test.go
  internal/querynodev2/segments/segment_loader.go
  pkg/util/typeutil/pair.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#30959 fix: wrong segment binlog path cause load segment failed #30726
  internal/datacoord/services.go
  internal/datacoord/services_test.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#30960 fix: index attr caches wrong result variable
  internal/querynodev2/segments/index_attr_cache.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#30964 fix: Update tencent cloud version
  go.mod
  go.sum
Labels: kind/bug, area/dependency, size/XS, approved, lgtm, ci-passed, dco-passed

#30928 fix: Prevent clone when selecting segments from meta
  internal/datacoord/compaction_trigger.go
  internal/datacoord/compaction_trigger_test.go
  internal/datacoord/meta.go
  internal/datacoord/meta_test.go
  internal/datacoord/segment_operator.go
  internal/datacoord/segment_operator_test.go
  internal/datacoord/services.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#30951 fix: segment version doesn't update as expected
  internal/querynodev2/segments/segment_loader.go
  internal/querynodev2/segments/segment_loader_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#30953 fix: Segment version doesn't update as expected
  internal/querynodev2/segments/segment_loader.go
  internal/querynodev2/segments/segment_loader_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#30966 fix: [Cherry-pick] Use localStorage path to check disk cap (#30944)
  pkg/util/paramtable/component_param.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#30561 enhance: add configurable memory index load predict memory usage factor
  internal/querynodev2/segments/index_attr_cache.go
  internal/querynodev2/segments/index_attr_cache_test.go
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/component_param_test.go
  tests/integration/minicluster_v2.go
  tests/integration/querynode/querynode_test.go
Labels: kind/enhancement, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed, test/integration

#30952 enhance: make the watch dm channel request better compatibility
  internal/querycoordv2/server.go
  internal/querycoordv2/session/node_manager.go
  internal/querycoordv2/task/executor.go
  internal/querycoordv2/task/utils.go
  internal/querynodev2/cluster/worker.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#30954 enhance: [2.3] make the watch dm channel request better compatibility
  internal/querycoordv2/server.go
  internal/querycoordv2/session/node_manager.go
  internal/querycoordv2/task/executor.go
  internal/querycoordv2/task/utils.go
  internal/querynodev2/cluster/worker.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#30902 enhance: Support more relational operators for binary expressions
  internal/core/src/exec/expression/BinaryArithOpEvalRangeExpr.cpp
  internal/core/src/exec/expression/BinaryArithOpEvalRangeExpr.h
  internal/core/unittest/test_array_expr.cpp
  internal/core/unittest/test_expr.cpp
  internal/parser/planparserv2/plan_parser_v2_test.go
  internal/parser/planparserv2/utils.go
  tests/integration/expression/expression_test.go
  tests/python_client/testcases/test_search.py
Labels: kind/enhancement, sig/testing, size/XXL, approved, lgtm, area/test, ci-passed, dco-passed, test/integration

#30717 enhance:Add integration test for searching when coord down
  tests/integration/coorddownsearch/search_after_coord_down_test.go
  tests/integration/util_query.go
Labels: kind/enhancement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, manual-pass, test/integration

#30901 fix: add pk sort for same distance of hybridsearch
  internal/proxy/task_hybrid_search.go
  tests/python_client/testcases/test_search.py
Labels: kind/bug, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed, manual-pass

#30689 fix: Fix binlog_io metric name conflict
  internal/datanode/binlog_io.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#30372 feat: support lazy load on querycoord
  internal/proxy/task.go
  internal/querycoordv2/task/utils.go
  pkg/common/common.go
Labels: kind/feature, area/dependency, size/M, approved, lgtm, ci-passed, area/internal-api, dco-passed, manual-pass

#30925 fix: Clean kafka default configuration
  configs/milvus.yaml
  pkg/util/paramtable/service_param.go
  pkg/util/paramtable/service_param_test.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#30924 fix: Clean kafka default configuration
  configs/milvus.yaml
  pkg/util/paramtable/service_param.go
  pkg/util/paramtable/service_param_test.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#30968 enhance: Reduce the memory usage of the timeTickSender
  internal/datanode/timetick_sender.go
  internal/datanode/timetick_sender_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#30777 test: update test cases
  tests/python_client/common/common_func.py
  tests/python_client/testcases/test_collection.py
  tests/python_client/testcases/test_delete.py
  tests/python_client/testcases/test_insert.py
  tests/python_client/testcases/test_query.py
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#30984 test: add restful v2 test
  tests/restful_client_v2/README.md
  tests/restful_client_v2/api/milvus.py
  tests/restful_client_v2/base/testbase.py
  tests/restful_client_v2/config/log_config.py
  tests/restful_client_v2/conftest.py
  tests/restful_client_v2/pytest.ini
  tests/restful_client_v2/requirements.txt
  tests/restful_client_v2/testcases/test_alias_operation.py
  tests/restful_client_v2/testcases/test_collection_operations.py
  tests/restful_client_v2/testcases/test_index_operation.py
  tests/restful_client_v2/testcases/test_jobs_operation.py
  tests/restful_client_v2/testcases/test_partition_operation.py
  tests/restful_client_v2/testcases/test_restful_sdk_mix_use_scenario.py
  tests/restful_client_v2/testcases/test_role_operation.py
  tests/restful_client_v2/testcases/test_user_operation.py
  tests/restful_client_v2/testcases/test_vector_operations.py
  tests/restful_client_v2/utils/constant.py
  tests/restful_client_v2/utils/util_log.py
  tests/restful_client_v2/utils/utils.py
Labels: sig/testing, size/XXL, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#30873 fix: [cherry-pick] [restful v1] bug list
  internal/distributed/proxy/httpserver/constant.go
  internal/distributed/proxy/httpserver/handler_v1.go
  internal/distributed/proxy/httpserver/handler_v1_test.go
  internal/distributed/proxy/httpserver/utils.go
  internal/distributed/proxy/httpserver/utils_test.go
Labels: kind/bug, size/XL, approved, lgtm, ci-passed, dco-passed, manual-pass

#30969 fix: use GetBinaryField incorrectly
  internal/distributed/proxy/httpserver/handler_v1.go
  internal/distributed/proxy/httpserver/utils.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#30939 enhance: Optimize DescribeIndex to reduce lock contention
  internal/datacoord/index_service.go
  internal/datacoord/index_service_test.go
  internal/datacoord/meta.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#30976 enhance: [2.3] retry to read when the s3 get the unexpect eof error
  internal/storage/minio_chunk_manager.go
  internal/storage/remote_chunk_manager.go
  pkg/util/merr/errors.go
  pkg/util/merr/errors_test.go
  pkg/util/merr/utils.go
  pkg/util/retry/options.go
  pkg/util/retry/retry.go
  pkg/util/retry/retry_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#30975 enhance: Optimize DescribeIndex to reduce lock contention
  internal/datacoord/index_service.go
  internal/datacoord/index_service_test.go
  internal/datacoord/meta.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#30656 fix: Make datacoord client retry on index api
  internal/distributed/datacoord/client/client.go
  internal/distributed/datacoord/client/client_test.go
  internal/util/grpcclient/client.go
  internal/util/grpcclient/client_test.go
Labels: kind/bug, size/XL, approved, lgtm, ci-passed, dco-passed

#30725 fix: Skip generate balance task when target not ready
  internal/querycoordv2/checkers/balance_checker.go
  internal/querycoordv2/checkers/balance_checker_test.go
  internal/querycoordv2/checkers/controller.go
  internal/querycoordv2/task/scheduler.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#30654 fix: Make datacoord client retry on index api
  internal/distributed/datacoord/client/client.go
  internal/distributed/datacoord/client/client_test.go
  internal/util/grpcclient/client.go
  internal/util/grpcclient/client_test.go
Labels: kind/bug, size/XL, approved, lgtm, ci-passed, dco-passed

#30869 enhance: index meta use independent rather than global meta lock
  internal/datacoord/broker/mock_coordinator_broker.go
  internal/datacoord/compaction_trigger.go
  internal/datacoord/compaction_trigger_test.go
  internal/datacoord/garbage_collector.go
  internal/datacoord/garbage_collector_test.go
  internal/datacoord/index_builder.go
  internal/datacoord/index_builder_test.go
  internal/datacoord/index_meta.go
  internal/datacoord/index_meta_test.go
  internal/datacoord/index_service.go
  internal/datacoord/index_service_test.go
  internal/datacoord/meta.go
  internal/datacoord/meta_test.go
  internal/datacoord/mock_allocator_test.go
  internal/datacoord/mock_cluster.go
  internal/datacoord/mock_segment_manager.go
  internal/datacoord/mock_session_manager.go
  internal/datacoord/segment_info.go
  internal/datacoord/server.go
  internal/datacoord/server_test.go
  internal/datacoord/services_test.go
  internal/datacoord/util.go
  tests/integration/datanode/compaction_test.go
Labels: kind/enhancement, sig/testing, size/XXL, approved, lgtm, area/test, ci-passed, dco-passed, manual-pass, test/integration

#30942 test: add test cases for mmap
  tests/python_client/base/collection_wrapper.py
  tests/python_client/requirements.txt
  tests/python_client/testcases/test_alias.py
  tests/python_client/testcases/test_collection.py
  tests/python_client/testcases/test_index.py
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#30981 enhance: Avoid create schema helper for each read task
  internal/parser/planparserv2/plan_parser_v2.go
  internal/parser/planparserv2/plan_parser_v2_test.go
  internal/proxy/expr_checker_test.go
  internal/proxy/meta_cache.go
  internal/proxy/search_util.go
  internal/proxy/task_delete.go
  internal/proxy/task_delete_test.go
  internal/proxy/task_query.go
  internal/proxy/task_query_test.go
  internal/proxy/task_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#30994 enhance: Add back load memory factor when esitmating memory resource
  internal/querynodev2/segments/segment_loader.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#30965 fix: starve lock caused by slow GetCompactionTo method when too much segments
  internal/datacoord/compaction_test.go
  internal/datacoord/compaction_trigger_test.go
  internal/datacoord/garbage_collector_test.go
  internal/datacoord/index_service_test.go
  internal/datacoord/meta.go
  internal/datacoord/meta_test.go
  internal/datacoord/segment_info.go
  internal/datacoord/segment_info_test.go
  internal/datacoord/services.go
Labels: kind/bug, size/XL, approved, lgtm, ci-passed, dco-passed

#30986 enhance: index meta use independent rather than global meta lock
  internal/datacoord/compaction_trigger.go
  internal/datacoord/compaction_trigger_test.go
  internal/datacoord/garbage_collector.go
  internal/datacoord/garbage_collector_test.go
  internal/datacoord/index_builder.go
  internal/datacoord/index_builder_test.go
  internal/datacoord/index_meta.go
  internal/datacoord/index_meta_test.go
  internal/datacoord/index_service.go
  internal/datacoord/index_service_test.go
  internal/datacoord/meta.go
  internal/datacoord/meta_test.go
  internal/datacoord/segment_info.go
  internal/datacoord/server.go
  internal/datacoord/server_test.go
  internal/datacoord/services_test.go
  internal/datacoord/util.go
Labels: kind/enhancement, size/XXL, approved, lgtm, ci-passed, dco-passed

#30999 enhance: [Cherry-Pick] Add back load memory factor when esitmating memory resource
  internal/querynodev2/segments/segment_loader.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#30963 fix: starve lock caused by slow GetCompactionTo method when too much segments
  internal/datacoord/compaction_trigger_test.go
  internal/datacoord/garbage_collector_test.go
  internal/datacoord/index_service_test.go
  internal/datacoord/meta.go
  internal/datacoord/meta_test.go
  internal/datacoord/segment_info.go
  internal/datacoord/segment_info_test.go
  internal/datacoord/services.go
Labels: kind/bug, size/XL, approved, lgtm, ci-passed, dco-passed

#31008 enhance: Change proxy connection manager to concurrent safe
  configs/milvus.yaml
  internal/proxy/accesslog/global_test.go
  internal/proxy/accesslog/info_test.go
  internal/proxy/connection/global.go
  internal/proxy/connection/manager.go
  internal/proxy/connection/manager_test.go
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#30991 enhance: Reduce the memory usage of the timeTickSender (#30968)
  internal/datanode/timetick_sender.go
  internal/datanode/timetick_sender_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#30768 enhance: access log support print output fields of Query or Search
  internal/proxy/accesslog/formatter.go
  internal/proxy/accesslog/info.go
  internal/proxy/accesslog/info_test.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#30997 enhance: Check channel cp lag before generate compaction task
  internal/datacoord/compaction_trigger.go
  internal/datacoord/compaction_trigger_test.go
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#31009 enhance: [Cherry-pick] Change proxy connection manager to concurrent safe
  configs/milvus.yaml
  internal/proxy/accesslog/global_test.go
  internal/proxy/accesslog/info_test.go
  internal/proxy/connection/global.go
  internal/proxy/connection/manager.go
  internal/proxy/connection/manager_test.go
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#30676 fix: binary vector should not limit dimension to 32768
  internal/core/CMakeLists.txt
  internal/proxy/util.go
  internal/proxy/util_test.go
  pkg/util/indexparamcheck/base_checker.go
  pkg/util/indexparamcheck/constraints.go
  pkg/util/indexparamcheck/ivf_pq_checker_test.go
  pkg/util/indexparamcheck/raft_ivf_pq_checker_test.go
  tests/python_client/common/common_type.py
  tests/python_client/milvus_client/test_milvus_client_collection.py
  tests/python_client/testcases/test_collection.py
  tests/python_client/testcases/test_search.py
Labels: kind/bug, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, area/compilation

#31024 enhance: Prevent the backlog of channelCP update tasks, perform batch updates of channelCPs (#30941)
  configs/milvus.yaml
  internal/datacoord/garbage_collector_test.go
  internal/datacoord/meta.go
  internal/datacoord/meta_test.go
  internal/datacoord/server_test.go
  internal/datacoord/services.go
  internal/datacoord/services_test.go
  internal/datanode/broker/broker.go
  internal/datanode/broker/datacoord.go
  internal/datanode/broker/datacoord_test.go
  internal/datanode/broker/mock_broker.go
  internal/datanode/channel_checkpoint_updater.go
  internal/datanode/channel_checkpoint_updater_test.go
  internal/datanode/data_node.go
  internal/datanode/data_sync_service_test.go
  internal/datanode/event_manager_test.go
  internal/datanode/flow_graph_manager_test.go
  internal/datanode/flow_graph_time_tick_node.go
  internal/datanode/services_test.go
  internal/metastore/catalog.go
  internal/metastore/kv/datacoord/kv_catalog.go
  internal/metastore/kv/datacoord/kv_catalog_test.go
  internal/metastore/mocks/mock_datacoord_catalog.go
  internal/mocks/mock_datacoord_catalog.go
  internal/proto/data_coord.proto
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/component_param_test.go
Labels: kind/enhancement, size/XXL, approved, lgtm, ci-passed, dco-passed

#31025 fix: add GetSegments optimization to avoid meta mutex competition
  internal/datacoord/meta.go
  internal/datacoord/segment_manager.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#31026 fix: add GetSegments optimization to avoid meta mutex competition
  internal/datacoord/meta.go
  internal/datacoord/segment_manager.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#29698 feat: Revise the RESTful bulk insert API
  internal/distributed/proxy/httpserver/handler_v2.go
  internal/distributed/proxy/httpserver/handler_v2_test.go
  internal/distributed/proxy/httpserver/request_v2.go
  internal/types/types.go
Labels: kind/feature, size/L, approved, lgtm, ci-passed, area/internal-api, dco-passed

#31019 fix: data race in querynode task test
  internal/querycoordv2/task/task_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#31021 enhance: Fix misleading log content & possible nil panic
  internal/querynodev2/segments/segment.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#30729 fix: Trigger l0 compaction when l0 views don't change
  internal/datacoord/compaction.go
  internal/datacoord/compaction_l0_view.go
  internal/datacoord/compaction_scheduler.go
  internal/datacoord/compaction_test.go
  internal/datacoord/compaction_trigger_v2.go
  internal/datacoord/compaction_trigger_v2_test.go
  internal/datacoord/compaction_view.go
  internal/datacoord/compaction_view_manager.go
  internal/datacoord/compaction_view_manager_test.go
  internal/datacoord/server.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#31035 enhance: Bump milvus & proto version to v2.3.11
  go.mod
  go.sum
  pkg/common/version.go
  pkg/go.mod
  pkg/go.sum
Labels: kind/enhancement, area/dependency, size/M, approved, lgtm, ci-passed, dco-passed, kind/branch-feature

#31037 enhance: purge client infos periodically
  configs/milvus.yaml
  internal/proxy/connection/manager.go
  internal/proxy/connection/manager_test.go
  internal/proxy/connection/priority_queue.go
  internal/proxy/connection/priority_queue_test.go
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#30992 fix: check collection lazy load prop using schema
  internal/proto/query_coord.proto
  internal/querynodev2/segments/segment.go
  internal/querynodev2/segments/segment_loader.go
  pkg/common/common.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, area/internal-api, dco-passed, manual-pass

#30882 fix: reduce incorrectly for group-by with offset(#30828)
  internal/proxy/search_reduce_util.go
  internal/proxy/search_util.go
  internal/proxy/task_search.go
  internal/proxy/task_search_test.go
Labels: kind/bug, size/XL, approved, lgtm, ci-passed, dco-passed

#31067 enhance: Skip partition key name check if feature not enabled
  internal/proxy/meta_cache.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#31045 fix: Skip invalid compaction plan
  internal/datacoord/compaction.go
  internal/datacoord/compaction_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#31077 fix: Fix errors in the Index service APIs are ignored
  internal/distributed/datacoord/client/client.go
  internal/distributed/datacoord/client/client_test.go
Labels: kind/bug, size/XL, approved, lgtm, ci-passed, dco-passed

#31086 fix: Fix errors in the Index service APIs are ignored (#31077)
  internal/distributed/datacoord/client/client.go
  internal/distributed/datacoord/client/client_test.go
  internal/querycoordv2/meta/coordinator_broker.go
  internal/querycoordv2/meta/coordinator_broker_test.go
Labels: kind/bug, size/XL, approved, lgtm, ci-passed, dco-passed

#31064 fix: [skip e2e]Increase graceful time to ensure that bounded search executing normally
  tests/integration/coorddownsearch/search_after_coord_down_test.go
Labels: kind/bug, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed, test/integration

#30286 feat: Define FieldValue, FieldStats and PartitionStats
  internal/storage/field_stats.go
  internal/storage/field_stats_test.go
  internal/storage/field_value.go
  internal/storage/field_value_test.go
  internal/storage/partition_stats.go
  internal/storage/partition_stats_test.go
Labels: kind/feature, size/XXL, lgtm, dco-passed

#31079 test: skip test cases
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#30814 fix: set CollectionID field for AlterCollection request
  internal/proxy/task.go
  internal/proxy/task_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#31082 enhance: [2.3] Add flush trigger for channel cp updater
  internal/datanode/channel_checkpoint_updater.go
  internal/datanode/channel_checkpoint_updater_test.go
  internal/datanode/flow_graph_time_tick_node.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed, kind/branch-feature

#31004 enhance: update pymilvus version
  tests/python_client/requirements.txt
Labels: kind/enhancement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed, do-not-merge/missing-related-pr

#31095 fix: Dirty sealed segment won't release after channel balance
  internal/querycoordv2/checkers/segment_checker.go
  internal/querycoordv2/checkers/segment_checker_test.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#31104 enhance: Add `ListIndexes` API from datacoord
  internal/datacoord/index_service.go
  internal/datacoord/index_service_test.go
  internal/distributed/datacoord/client/client.go
  internal/distributed/datacoord/client/client_test.go
  internal/distributed/datacoord/service.go
  internal/distributed/datacoord/service_test.go
  internal/mocks/mock_datacoord.go
  internal/mocks/mock_datacoord_client.go
  internal/proto/data_coord.proto
  internal/proto/index_coord.proto
Labels: kind/enhancement, size/XL, approved, lgtm, ci-passed, area/internal-api, dco-passed

#30013 enhance: support stream call for grpc client
  internal/util/grpcclient/client.go
  internal/util/grpcclient/client_test.go
  internal/util/streamrpc/mock_grpc_client_stream.go
  internal/util/streamrpc/mocks/mock_query_stream_segments_server.go
  internal/util/streamrpc/mocks/mock_query_stream_server.go
Labels: kind/enhancement, size/XL, approved, lgtm, ci-passed, dco-passed

#31001 enhance: update pymilvus version
  tests/python_client/requirements.txt
Labels: kind/enhancement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#31096 test: add json and array datatype check in restful v1
  tests/restful_client/testcases/test_restful_sdk_mix_use_scenario.py
  tests/restful_client/utils/utils.py
Labels: sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#30941 enhance: Prevent the backlog of channelCP update tasks, perform batch updates of channelCPs
  configs/milvus.yaml
  internal/datacoord/compaction_trigger_test.go
  internal/datacoord/garbage_collector_test.go
  internal/datacoord/meta.go
  internal/datacoord/meta_test.go
  internal/datacoord/server_test.go
  internal/datacoord/services.go
  internal/datanode/broker/broker.go
  internal/datanode/broker/datacoord.go
  internal/datanode/broker/datacoord_test.go
  internal/datanode/broker/mock_broker.go
  internal/datanode/channel_checkpoint_updater.go
  internal/datanode/channel_checkpoint_updater_test.go
  internal/datanode/data_node.go
  internal/datanode/data_sync_service_test.go
  internal/datanode/event_manager_test.go
  internal/datanode/flow_graph_manager_test.go
  internal/datanode/flow_graph_time_tick_node.go
  internal/datanode/services_test.go
  internal/metastore/catalog.go
  internal/metastore/kv/datacoord/kv_catalog.go
  internal/metastore/kv/datacoord/kv_catalog_test.go
  internal/metastore/mocks/mock_datacoord_catalog.go
  internal/proto/data_coord.proto
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/component_param_test.go
Labels: kind/enhancement, size/XL, approved, lgtm, ci-passed, dco-passed

#29522 enhance: jemalloc aarch64 platform use 64k pagesize.
  internal/core/thirdparty/jemalloc/CMakeLists.txt
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed, area/compilation

#31122 enhance: Use `ListIndexes` instead of `DescribeIndex` for qc broker
  internal/querycoordv2/job/job_test.go
  internal/querycoordv2/job/utils.go
  internal/querycoordv2/meta/coordinator_broker.go
  internal/querycoordv2/meta/coordinator_broker_test.go
  internal/querycoordv2/meta/mock_broker.go
  internal/querycoordv2/observers/target_observer.go
  internal/querycoordv2/server_test.go
  internal/querycoordv2/services_test.go
  internal/querycoordv2/task/executor.go
  internal/querycoordv2/task/task_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#31130 fix: fix oom because of wrong load mode for index's raw data
  internal/querynodev2/segments/segment_loader.go
Labels: kind/bug, size/XS, lgtm, dco-passed

#31092 enhance: purge client infos periodically (#31037)
  configs/milvus.yaml
  internal/proxy/connection/manager.go
  internal/proxy/connection/manager_test.go
  internal/proxy/connection/priority_queue.go
  internal/proxy/connection/priority_queue_test.go
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#31116 fix: Skip unstable compaction test it
  tests/integration/datanode/compaction_test.go
Labels: kind/bug, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed, manual-pass, test/integration

#31076 test: fix chaos apply time
  tests/python_client/chaos/test_chaos_apply_to_determined_pod.py
  tests/python_client/utils/util_common.py
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#31097 test: add json and array datatype check in restful v1
  tests/restful_client/testcases/test_restful_sdk_mix_use_scenario.py
  tests/restful_client/utils/utils.py
Labels: sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#31040 fix: Leader checker can't update segment's load version
  internal/querycoordv2/checkers/leader_checker.go
  internal/querycoordv2/checkers/leader_checker_test.go
  internal/querycoordv2/task/action.go
  internal/querycoordv2/task/executor.go
  internal/querycoordv2/task/task_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#31112 fix: Balance param use duplicated key
  pkg/util/paramtable/component_param.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#30824 enhance: ban range-search iteration for search-group-by
  internal/core/src/query/PlanProto.cpp
  internal/proxy/task.go
  internal/proxy/task_search.go
  internal/proxy/task_search_test.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#31136 enhance: Set log level to INFO for integration test
  tests/integration/hellomilvus/hello_milvus_test.go
  tests/integration/suite.go
Labels: kind/enhancement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed, test/integration

#31055 fix: Disable knowhere trace as a quick fix
  internal/core/src/index/VectorIndex.h
  internal/core/src/query/SearchBruteForce.cpp
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#31005 enhance: add metrics for load segment progress
  internal/querynodev2/segments/segment_loader.go
  pkg/metrics/metrics.go
  pkg/metrics/querynode_metrics.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#30998 enhance: Enable L0 by default
  configs/milvus.yaml
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed, behavior-change

#31073 enhance: refactor segment dist manager interface
  internal/querycoordv2/balance/multi_target_balance.go
  internal/querycoordv2/balance/rowcount_based_balancer.go
  internal/querycoordv2/balance/score_based_balancer.go
  internal/querycoordv2/balance/utils.go
  internal/querycoordv2/checkers/index_checker.go
  internal/querycoordv2/checkers/leader_checker.go
  internal/querycoordv2/checkers/segment_checker.go
  internal/querycoordv2/handlers.go
  internal/querycoordv2/job/utils.go
  internal/querycoordv2/meta/segment_dist_manager.go
  internal/querycoordv2/meta/segment_dist_manager_test.go
  internal/querycoordv2/observers/replica_observer.go
  internal/querycoordv2/services.go
  internal/querycoordv2/task/action.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#31084 enhance: change frequency log to rated level
  internal/querycoordv2/checkers/channel_checker.go
  internal/querycoordv2/checkers/util.go
  internal/querycoordv2/checkers/util_test.go
  internal/querycoordv2/services.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#31147 enhance: Auto release in integration test tear down
  tests/integration/suite.go
Labels: kind/enhancement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed, test/integration

#31046 feat: Replacing the current import API with the v2 implementation
  internal/datacoord/services.go
  internal/proxy/impl.go
  internal/proxy/impl_test.go
  internal/proxy/proxy_test.go
  tests/python_client/testcases/test_bulk_insert.py
Labels: kind/feature, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#31150 enhance: [Cherry-pick] Add `ListIndexes` API from datacoord (#31104)
  internal/datacoord/index_service.go
  internal/datacoord/index_service_test.go
  internal/distributed/datacoord/client/client.go
  internal/distributed/datacoord/client/client_test.go
  internal/distributed/datacoord/service.go
  internal/distributed/datacoord/service_test.go
  internal/mocks/mock_datacoord.go
  internal/mocks/mock_datacoord_client.go
  internal/proto/data_coord.proto
  internal/proto/index_coord.proto
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, area/internal-api, dco-passed, manual-pass

#31144 enhance: Add segment id short cut for WithSegmentID filter
  internal/datanode/compactor_test.go
  internal/datanode/metacache/actions.go
  internal/datanode/metacache/actions_test.go
  internal/datanode/metacache/meta_cache.go
  internal/datanode/metacache/meta_cache_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#31114 enhance: jemalloc aarch64 platform use 64k pagesize.
  internal/core/thirdparty/jemalloc/CMakeLists.txt
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed, area/compilation

#31128 fix: alter index request's index name can not be empty
  internal/datacoord/index_service.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#31071 fix: Save traceID and spanID as hex string into search config
  internal/core/src/common/Tracer.cpp
  internal/core/src/common/Tracer.h
  internal/core/src/index/VectorIndex.h
  internal/core/src/query/SearchBruteForce.cpp
  internal/core/unittest/test_tracer.cpp
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#31163 enhance: [Cherry-Pick] Use `ListIndexes` instead of `DescribeIndex` for qc broker
  internal/datanode/broker/mock_broker.go
  internal/metastore/mocks/mock_datacoord_catalog.go
  internal/querycoordv2/job/job_test.go
  internal/querycoordv2/job/utils.go
  internal/querycoordv2/meta/coordinator_broker.go
  internal/querycoordv2/meta/coordinator_broker_test.go
  internal/querycoordv2/meta/mock_broker.go
  internal/querycoordv2/observers/leader_observer.go
  internal/querycoordv2/observers/leader_observer_test.go
  internal/querycoordv2/observers/target_observer.go
  internal/querycoordv2/server_test.go
  internal/querycoordv2/services_test.go
  internal/querycoordv2/task/executor.go
  internal/querycoordv2/task/task_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#30357 feat: [Sparse Float Vector] segcore basics and index building
  internal/core/src/common/FieldData.cpp
  internal/core/src/common/FieldData.h
  internal/core/src/common/FieldDataInterface.h
  internal/core/src/common/FieldMeta.h
  internal/core/src/common/Schema.cpp
  internal/core/src/common/Schema.h
  internal/core/src/common/Span.h
  internal/core/src/common/Types.h
  internal/core/src/common/Utils.h
  internal/core/src/common/VectorTrait.h
  internal/core/src/common/type_c.h
  internal/core/src/index/IndexFactory.cpp
  internal/core/src/index/Utils.cpp
  internal/core/src/index/VectorMemIndex.cpp
  internal/core/src/indexbuilder/IndexFactory.h
  internal/core/src/indexbuilder/index_c.cpp
  internal/core/src/indexbuilder/index_c.h
  internal/core/src/mmap/Column.h
  internal/core/src/mmap/Utils.h
  internal/core/src/segcore/CMakeLists.txt
  internal/core/src/segcore/ConcurrentVector.cpp
  internal/core/src/segcore/ConcurrentVector.h
  internal/core/src/segcore/FieldIndexing.cpp
  internal/core/src/segcore/FieldIndexing.h
  internal/core/src/segcore/IndexConfigGenerator.cpp
  internal/core/src/segcore/IndexConfigGenerator.h
  internal/core/src/segcore/InsertRecord.cpp
  internal/core/src/segcore/InsertRecord.h
  internal/core/src/segcore/ScalarIndex.cpp
  internal/core/src/segcore/ScalarIndex.h
  internal/core/src/segcore/SegmentGrowing.h
  internal/core/src/segcore/SegmentGrowingImpl.cpp
  internal/core/src/segcore/SegmentGrowingImpl.h
  internal/core/src/segcore/SegmentSealedImpl.cpp
  internal/core/src/segcore/SegmentSealedImpl.h
  internal/core/src/segcore/Utils.cpp
  internal/core/src/segcore/segment_c.cpp
  internal/core/src/storage/ChunkCache.cpp
  internal/core/src/storage/ChunkManager.h
  internal/core/src/storage/Event.cpp
  internal/core/src/storage/PayloadReader.cpp
  internal/core/src/storage/PayloadWriter.cpp
  internal/core/src/storage/Util.cpp
  internal/core/src/storage/parquet_c.h
  internal/core/unittest/test_binlog_index.cpp
  internal/core/unittest/test_concurrent_vector.cpp
  internal/core/unittest/test_data_codec.cpp
  internal/core/unittest/test_growing_index.cpp
  internal/core/unittest/test_index_c_api.cpp
  internal/core/unittest/test_index_wrapper.cpp
  internal/core/unittest/test_indexing.cpp
  internal/core/unittest/test_range_search_sort.cpp
  internal/core/unittest/test_retrieve.cpp
  internal/core/unittest/test_utils.cpp
  internal/core/unittest/test_utils/Constants.h
  internal/core/unittest/test_utils/DataGen.h
  internal/core/unittest/test_utils/c_api_test_utils.h
  internal/core/unittest/test_utils/indexbuilder_test_utils.h
Labels: kind/feature, area/dependency, size/XXL, approved, lgtm, ci-passed, dco-passed, area/compilation, manual-pass

#31087 enhance: remove duplicated target node id check
  internal/querynodev2/services.go
  internal/querynodev2/services_test.go
  pkg/util/merr/utils.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#31113 fix: [restful v2] search & advanced_search API
  internal/distributed/proxy/httpserver/constant.go
  internal/distributed/proxy/httpserver/handler_v1.go
  internal/distributed/proxy/httpserver/handler_v1_test.go
  internal/distributed/proxy/httpserver/handler_v2.go
  internal/distributed/proxy/httpserver/handler_v2_test.go
  internal/distributed/proxy/httpserver/request_v2.go
  internal/distributed/proxy/httpserver/utils.go
  internal/distributed/proxy/httpserver/utils_test.go
Labels: kind/bug, size/XL, approved, lgtm, ci-passed, dco-passed

#31167 fix: lost dbname when only passing collection id to describeCollection
  internal/metastore/kv/rootcoord/kv_catalog.go
  internal/metastore/kv/rootcoord/kv_catalog_test.go
  internal/rootcoord/describe_collection_task.go
  internal/rootcoord/describe_collection_task_test.go
  internal/rootcoord/meta_table.go
  internal/rootcoord/root_coord.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#31173 fix: TestBlock case use different segment id in testcase
  internal/datanode/syncmgr/sync_manager_test.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#31177 fix: lost dbname when only passing collection id to describeCollection
  internal/metastore/kv/rootcoord/kv_catalog.go
  internal/metastore/kv/rootcoord/kv_catalog_test.go
  internal/rootcoord/describe_collection_task.go
  internal/rootcoord/describe_collection_task_test.go
  internal/rootcoord/meta_table.go
  internal/rootcoord/root_coord.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#31052 feat: Support for multiple forms of JSON
  internal/core/src/common/Json.h
  internal/parser/planparserv2/parser_visitor.go
  internal/parser/planparserv2/plan_parser_v2_test.go
  internal/proxy/validate_util.go
  internal/proxy/validate_util_test.go
  tests/integration/jsonexpr/json_expr_test.go
  tests/python_client/testcases/test_search.py
Labels: kind/feature, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, manual-pass, test/integration

#31182 Use logID instead of logPath for import segment
  internal/datacoord/import_scheduler.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass, do-not-merge/invalid-pr-format

#30947 enhance: cache config values for saving cpu cycles to parse config item
  internal/querynodev2/server.go
  pkg/config/manager.go
  pkg/config/manager_test.go
  pkg/util/paramtable/base_table.go
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/component_param_test.go
  pkg/util/paramtable/grpc_param_test.go
  pkg/util/paramtable/param_item.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#31183 enhance: Constraint dynamic field as key-value format
  internal/parser/planparserv2/parser_visitor.go
  internal/parser/planparserv2/plan_parser_v2_test.go
  internal/proxy/validate_util.go
  internal/proxy/validate_util_test.go
  internal/util/importutil/import_util.go
  internal/util/importutil/import_util_test.go
  internal/util/importutilv2/json/reader_test.go
  internal/util/importutilv2/numpy/field_reader.go
  internal/util/importutilv2/numpy/reader_test.go
  internal/util/importutilv2/parquet/field_reader.go
  internal/util/importutilv2/parquet/reader_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#31184 fix:restrict pk in [...] optimization situations
  internal/core/src/exec/expression/Expr.cpp
  internal/core/src/exec/expression/Expr.h
  internal/core/src/exec/expression/TermExpr.cpp
  internal/core/src/exec/expression/TermExpr.h
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#30629 feat: [Sparse Float Vector] segcore to support sparse vector search and get raw vector by id
  internal/core/src/common/FieldDataInterface.h
  internal/core/src/common/Types.h
  internal/core/src/common/Utils.h
  internal/core/src/common/VectorTrait.h
  internal/core/src/index/VectorDiskIndex.cpp
  internal/core/src/index/VectorDiskIndex.h
  internal/core/src/index/VectorIndex.h
  internal/core/src/index/VectorMemIndex.cpp
  internal/core/src/index/VectorMemIndex.h
  internal/core/src/mmap/Column.h
  internal/core/src/query/Plan.cpp
  internal/core/src/query/PlanImpl.h
  internal/core/src/query/PlanNode.h
  internal/core/src/query/PlanProto.cpp
  internal/core/src/query/SearchBruteForce.cpp
  internal/core/src/query/SearchOnGrowing.cpp
  internal/core/src/query/SearchOnIndex.cpp
  internal/core/src/query/SearchOnIndex.h
  internal/core/src/query/SearchOnSealed.cpp
  internal/core/src/query/generated/ExecPlanNodeVisitor.h
  internal/core/src/query/generated/ExtractInfoPlanNodeVisitor.h
  internal/core/src/query/generated/PlanNode.cpp
  internal/core/src/query/generated/PlanNodeVisitor.h
  internal/core/src/query/generated/ShowPlanNodeVisitor.h
  internal/core/src/query/generated/VerifyPlanNodeVisitor.h
  internal/core/src/query/visitors/ExecPlanNodeVisitor.cpp
  internal/core/src/query/visitors/ExtractInfoPlanNodeVisitor.cpp
  internal/core/src/query/visitors/ShowPlanNodeVisitor.cpp
  internal/core/src/query/visitors/VerifyPlanNodeVisitor.cpp
  internal/core/src/segcore/ConcurrentVector.h
  internal/core/src/segcore/FieldIndexing.cpp
  internal/core/src/segcore/FieldIndexing.h
  internal/core/src/segcore/IndexConfigGenerator.h
  internal/core/src/segcore/InsertRecord.h
  internal/core/src/segcore/SegmentGrowingImpl.cpp
  internal/core/src/segcore/SegmentGrowingImpl.h
  internal/core/src/segcore/SegmentSealedImpl.cpp
  internal/core/src/segcore/SegmentSealedImpl.h
  internal/core/src/segcore/Utils.cpp
  internal/core/src/segcore/segment_c.cpp
  internal/core/unittest/CMakeLists.txt
  internal/core/unittest/test_always_true_expr.cpp
  internal/core/unittest/test_bf_sparse.cpp
  internal/core/unittest/test_binlog_index.cpp
  internal/core/unittest/test_exec.cpp
  internal/core/unittest/test_expr.cpp
  internal/core/unittest/test_growing.cpp
  internal/core/unittest/test_growing_index.cpp
  internal/core/unittest/test_index_wrapper.cpp
  internal/core/unittest/test_indexing.cpp
  internal/core/unittest/test_offset_ordered_array.cpp
  internal/core/unittest/test_offset_ordered_map.cpp
  internal/core/unittest/test_retrieve.cpp
  internal/core/unittest/test_scalar_index.cpp
  internal/core/unittest/test_scalar_index_creator.cpp
  internal/core/unittest/test_sealed.cpp
  internal/core/unittest/test_utils/Constants.h
  internal/core/unittest/test_utils/DataGen.h
  internal/core/unittest/test_utils/indexbuilder_test_utils.h
  internal/proto/plan.proto
Labels: kind/feature, size/XXL, lgtm, dco-passed, area/compilation

#31203 enhance: Add ctx trace for segment load `prepare`
  internal/querynodev2/segments/segment_loader.go
  internal/querynodev2/segments/segment_loader_test.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#31205 fix: Fix binlog import
  internal/proxy/impl.go
  internal/util/importutilv2/binlog/reader.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#31171 fix: fix mmap load
  internal/querynodev2/segments/manager.go
  internal/querynodev2/segments/segment_loader.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#31132 test: add more index type in deploy test
  tests/python_client/deploy/testcases/test_action_first_deployment.py
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#31208 test: update the max binary vector dim in test code
  tests/python_client/common/common_type.py
  tests/python_client/testcases/test_collection.py
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#31202 fix: Balance channel stuck forever due to logic dead lock
  internal/querycoordv2/balance/multi_target_balance.go
  internal/querycoordv2/balance/rowcount_based_balancer.go
  internal/querycoordv2/balance/score_based_balancer.go
  internal/querycoordv2/checkers/balance_checker.go
  internal/querycoordv2/checkers/segment_checker.go
  internal/querycoordv2/checkers/segment_checker_test.go
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/component_param_test.go
  tests/integration/balance/balance_test.go
Labels: kind/bug, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, manual-pass, test/integration

#31223 test: update the dim of the largest or smallest vector in case
  tests/python_client/testcases/test_collection.py
  tests/python_client/testcases/test_index.py
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#31161 test: update test cases
  tests/python_client/requirements.txt
  tests/python_client/testcases/test_collection.py
  tests/python_client/testcases/test_high_level_api.py
  tests/python_client/testcases/test_insert.py
Labels: sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed, do-not-merge/missing-related-pr, kind/test

#31225 test: update test cases
  tests/python_client/common/common_func.py
  tests/python_client/requirements.txt
  tests/python_client/testcases/test_high_level_api.py
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#31192 enhance: Enhance and modify the return content of ImportV2
  internal/datacoord/import_checker.go
  internal/datacoord/import_job.go
  internal/datacoord/import_scheduler.go
  internal/datacoord/import_task.go
  internal/datacoord/import_util.go
  internal/datacoord/import_util_test.go
  internal/datacoord/services.go
  internal/datanode/importv2/executor.go
  internal/datanode/importv2/executor_test.go
  internal/datanode/importv2/task.go
  internal/datanode/importv2/util.go
  internal/distributed/proxy/httpserver/handler_v2.go
  internal/distributed/proxy/httpserver/handler_v2_test.go
  internal/distributed/proxy/httpserver/request_v2.go
  internal/proto/data_coord.proto
  internal/proto/internal.proto
  internal/proxy/impl.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, area/internal-api, dco-passed

#31179 enhance: Add id,type filter shortcut for QueryNode segment manager
  internal/querynodev2/segments/manager.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#31170 fix: fix growing index data race and properly handle build error
  internal/core/src/segcore/FieldIndexing.cpp
  internal/core/src/segcore/FieldIndexing.h
  internal/core/src/segcore/SegmentGrowingImpl.cpp
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed, area/compilation

#30630 feat: [Sparse Float Vector] add sparse vector support to milvus components
  internal/datacoord/compaction_trigger.go
  internal/datanode/compactor.go
  internal/datanode/compactor_test.go
  internal/indexnode/util.go
  internal/parser/planparserv2/plan_parser_v2.go
  internal/parser/planparserv2/plan_parser_v2_test.go
  internal/proxy/task.go
  internal/proxy/task_index.go
  internal/proxy/task_index_test.go
  internal/proxy/util.go
  internal/proxy/validate_util.go
  internal/querynodev2/local_worker_test.go
  internal/querynodev2/pipeline/insert_node_test.go
  internal/querynodev2/pipeline/pipeline_test.go
  internal/querynodev2/segments/manager_test.go
  internal/querynodev2/segments/mock_data.go
  internal/querynodev2/segments/plan_test.go
  internal/querynodev2/segments/reduce_test.go
  internal/querynodev2/segments/retrieve_test.go
  internal/querynodev2/segments/search_test.go
  internal/querynodev2/segments/segment_loader_test.go
  internal/querynodev2/segments/segment_test.go
  internal/querynodev2/segments/utils.go
  internal/querynodev2/server_test.go
  internal/querynodev2/services_test.go
  internal/storage/binlog_writer.go
  internal/storage/data_codec.go
  internal/storage/data_codec_test.go
  internal/storage/data_sorter.go
  internal/storage/data_sorter_test.go
  internal/storage/event_writer.go
  internal/storage/insert_data.go
  internal/storage/insert_data_test.go
  internal/storage/payload.go
  internal/storage/payload_reader.go
  internal/storage/payload_test.go
  internal/storage/payload_writer.go
  internal/storage/print_binlog.go
  internal/storage/stats.go
  internal/storage/utils.go
  internal/storage/utils_test.go
  internal/util/indexcgowrapper/dataset.go
  internal/util/indexcgowrapper/index.go
  pkg/util/funcutil/func.go
  pkg/util/funcutil/placeholdergroup.go
  pkg/util/gc/gc_tuner.go
  pkg/util/indexparamcheck/conf_adapter_mgr.go
  pkg/util/indexparamcheck/constraints.go
  pkg/util/indexparamcheck/hnsw_checker.go
  pkg/util/indexparamcheck/index_type.go
  pkg/util/indexparamcheck/sparse_float_vector_base_checker.go
  pkg/util/indexparamcheck/sparse_inverted_index_checker.go
  pkg/util/testutils/sparse_test_utils.go
  pkg/util/typeutil/gen_empty_field_data.go
  pkg/util/typeutil/get_dim.go
  pkg/util/typeutil/schema.go
  pkg/util/typeutil/schema_test.go
Labels: kind/feature, size/XXL, approved, lgtm, dco-passed, area/compilation

#31198 fix: Correct the last empty l0 views
  internal/datacoord/compaction_trigger_v2_test.go
  internal/datacoord/compaction_view_manager.go
  internal/datacoord/compaction_view_manager_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#31230 fix: Fix data race on loadSealedSegmentFields opts
  internal/querynodev2/segments/segment_loader.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#31259 fix: Set nodeID when remove distribution
  internal/querycoordv2/task/executor.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#31212 fix: Use lock and map instead of concurrentMap
  internal/datanode/data_node.go
  internal/datanode/event_manager.go
  internal/datanode/event_manager_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#31213 fix: revoke session may be ignored due to server context cancellation in advance
  internal/datacoord/server.go
  internal/datanode/data_node.go
  internal/distributed/datacoord/service.go
  internal/distributed/datanode/service.go
  internal/distributed/datanode/service_test.go
  internal/distributed/indexnode/service.go
  internal/distributed/proxy/service.go
  internal/distributed/querycoord/service.go
  internal/distributed/querynode/service.go
  internal/distributed/rootcoord/service.go
  internal/indexnode/indexnode.go
  internal/querycoordv2/server.go
  internal/querynodev2/server.go
  internal/rootcoord/root_coord.go
  internal/util/sessionutil/session_util.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#31193 enhance: Bump milvus & proto version to v2.3.12
  go.mod
  go.sum
  pkg/common/version.go
  pkg/go.mod
  pkg/go.sum
Labels: kind/enhancement, area/dependency, size/S, approved, lgtm, ci-passed, dco-passed, kind/branch-feature

#31269 fix: [restful v2] create collection & describe collection
  internal/distributed/proxy/httpserver/constant.go
  internal/distributed/proxy/httpserver/handler_v1.go
  internal/distributed/proxy/httpserver/handler_v2.go
  internal/distributed/proxy/httpserver/handler_v2_test.go
  internal/distributed/proxy/httpserver/request_v2.go
  internal/distributed/proxy/httpserver/utils.go
  internal/distributed/proxy/httpserver/utils_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#31244 enhance: Remove adding import segments to the datanode
  internal/datacoord/import_checker.go
  internal/datacoord/import_checker_test.go
  internal/datacoord/import_util.go
  internal/datacoord/import_util_test.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#31139 fix: unmarshal nil when check search params
  internal/proxy/task_search.go
  internal/proxy/task_search_test.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#31256 fix: Grpcclient return unrecoverable error
  internal/util/grpcclient/client.go
  pkg/util/retry/retry.go
  pkg/util/retry/retry_test.go
  tests/integration/replicas/balance/replica_test.go
Labels: kind/bug, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, test/integration

#31270 fix: Skip to submit l0 tasks when scheduler full
  internal/datacoord/compaction_trigger_v2.go
  internal/datacoord/compaction_trigger_v2_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#31277 fix: Set node unreachable when get shard client failed
  internal/proxy/look_aside_balancer.go
  internal/proxy/look_aside_balancer_test.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#31220 fix: ctx cancel should be the last step while stopping server
  internal/datacoord/server.go
  internal/datanode/data_node.go
  internal/distributed/datacoord/service.go
  internal/distributed/datanode/service.go
  internal/distributed/datanode/service_test.go
  internal/distributed/indexnode/service.go
  internal/distributed/proxy/service.go
  internal/distributed/querycoord/service.go
  internal/distributed/querynode/service.go
  internal/distributed/rootcoord/service.go
  internal/indexnode/indexnode.go
  internal/querycoordv2/server.go
  internal/querynodev2/server.go
  internal/rootcoord/root_coord.go
  internal/util/sessionutil/session_util.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#30673 enhance: add hostname into node info
  internal/querycoordv2/balance/balance_test.go
  internal/querycoordv2/balance/rowcount_based_balancer_test.go
  internal/querycoordv2/balance/score_based_balancer_test.go
  internal/querycoordv2/checkers/balance_checker_test.go
  internal/querycoordv2/checkers/channel_checker_test.go
  internal/querycoordv2/checkers/controller_test.go
  internal/querycoordv2/checkers/index_checker_test.go
  internal/querycoordv2/checkers/leader_checker_test.go
  internal/querycoordv2/checkers/segment_checker_test.go
  internal/querycoordv2/checkers/util_test.go
  internal/querycoordv2/job/job_test.go
  internal/querycoordv2/meta/resource_manager_test.go
  internal/querycoordv2/observers/replica_observer_test.go
  internal/querycoordv2/observers/resource_observer_test.go
  internal/querycoordv2/server.go
  internal/querycoordv2/server_test.go
  internal/querycoordv2/services_test.go
  internal/querycoordv2/session/cluster_test.go
  internal/querycoordv2/session/node_manager.go
  internal/querycoordv2/task/task_test.go
  internal/querycoordv2/utils/meta_test.go
Labels: kind/enhancement, size/XL, approved, lgtm, ci-passed, dco-passed

#31241 fix: Fix binlog import and refine error reporting
  internal/datacoord/import_util.go
  internal/datacoord/import_util_test.go
  internal/datacoord/services.go
  internal/datacoord/services_test.go
  internal/datanode/importv2/executor.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#31268 enhance: Allow import tasks to retry for more errors
  internal/datacoord/import_scheduler.go
  internal/datacoord/import_scheduler_test.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#31006 enhance: Add runtime config to paramtable
  pkg/config/manager.go
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/param_item.go
  pkg/util/paramtable/runtime.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#31240 enhance: Speed up target recovery after query coord restart
  internal/distributed/querycoord/service.go
  internal/metastore/catalog.go
  internal/metastore/kv/querycoord/kv_catalog.go
  internal/metastore/kv/querycoord/kv_catalog_test.go
  internal/metastore/mocks/mock_querycoord_catalog.go
  internal/proto/query_coord.proto
  internal/querycoordv2/meta/target.go
  internal/querycoordv2/meta/target_manager.go
  internal/querycoordv2/meta/target_manager_test.go
  internal/querycoordv2/server.go
  tests/integration/minicluster_v2.go
  tests/integration/target/target_test.go
Labels: kind/enhancement, sig/testing, size/XL, approved, lgtm, area/test, ci-passed, area/internal-api, dco-passed, test/integration

#31131 feat: Add disk quota checks for import V2
  internal/datacoord/import_checker.go
  internal/datacoord/import_job.go
  internal/datacoord/import_util.go
  internal/datacoord/import_util_test.go
  internal/datacoord/meta.go
  internal/datacoord/segment_manager.go
  internal/proto/data_coord.proto
  tests/integration/import/import_test.go
Labels: kind/feature, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, test/integration

#31297 enhance: Update groupby tests
  tests/python_client/testcases/test_search.py
Labels: kind/enhancement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, manual-pass
