Repository milvus-io/milvus, pull requests merged in 2024-10, with the labels that each got.

#36602 fix: Fix import segments leak in segment manager
  internal/datacoord/import_checker.go
  internal/datacoord/import_checker_test.go
  internal/datacoord/import_util.go
  internal/datacoord/import_util_test.go
  internal/datacoord/mock_segment_manager.go
  internal/datacoord/segment_manager.go
  internal/datacoord/segment_manager_test.go
  internal/datacoord/server.go
  internal/datacoord/server_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#36631 fix: Fix import segments leak in segment manager (#36602)
  internal/datacoord/import_checker.go
  internal/datacoord/import_checker_test.go
  internal/datacoord/import_util.go
  internal/datacoord/import_util_test.go
  internal/datacoord/mock_segment_manager.go
  internal/datacoord/segment_manager.go
  internal/datacoord/segment_manager_test.go
  internal/datacoord/server.go
  internal/datacoord/server_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#33623 enhance: Reopen chunk cache cpp ut (#33622)
  internal/core/unittest/test_sealed.cpp
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#36624 enhance:use proto.clone in compaction tasks to prevent omissions
  internal/datacoord/compaction_task_clustering.go
  internal/datacoord/compaction_task_l0.go
  internal/datacoord/compaction_task_mix.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed, PR | need cherry-pick

#36671 enhance: Bump milvus version to v2.3.22
  pkg/common/version.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass, kind/branch-feature

#36503 fix: Remove neighbors if compactTo is unindexed
  internal/datacoord/handler.go
  internal/datacoord/handler_test.go
  internal/datacoord/segment_info.go
  internal/datacoord/server_test.go
  internal/proto/data_coord.proto
Labels: kind/bug, size/XXL, approved, lgtm, ci-passed, dco-passed

#36579 enhance: decrease CPU overhead when calculating index file size
  internal/datacoord/index_meta.go
  internal/datacoord/meta.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#36580 enhance: decrease CPU overhead when calculating index file size
  internal/datacoord/index_meta.go
  internal/datacoord/meta.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#36581 enhance: enable manual compaction for collections without indexes
  internal/datacoord/compaction_policy_single.go
  internal/datacoord/compaction_trigger.go
  internal/datacoord/compaction_trigger_test.go
  internal/datacoord/garbage_collector.go
  internal/datacoord/handler.go
  internal/datacoord/index_meta.go
  internal/datacoord/util.go
  tests/integration/compaction/mix_compaction_test.go
Labels: kind/enhancement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, test/integration

#36590 test: update pymilvus version and test case
  tests/python_client/requirements.txt
  tests/python_client/testcases/test_collection.py
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#36612 test: add null and default test cases
  tests/python_client/check/func_check.py
  tests/python_client/milvus_client/test_milvus_client_collection.py
  tests/python_client/milvus_client/test_milvus_client_search.py
  tests/python_client/testcases/test_collection.py
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#36589 test: update test case for support dynamic load replica
  tests/python_client/testcases/test_collection.py
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#36521 fix: [2.4] improve mmap related code in Column.h
  internal/core/src/common/Types.h
  internal/core/src/mmap/Column.h
  internal/core/src/mmap/Utils.h
  internal/core/src/segcore/SegmentSealedImpl.cpp
  internal/core/src/storage/ChunkCache.cpp
  internal/core/unittest/test_chunk_cache.cpp
  internal/core/unittest/test_sealed.cpp
Labels: kind/bug, size/XL, approved, lgtm, ci-passed, dco-passed

#36665 fix: [2.4] Add defer Unpin when error happens (#36620)
  internal/querynodev2/segments/validate.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#36462 enhance: [2.4] Produce messages of multiple topics in parallel (#36344)
  pkg/mq/msgstream/mq_msgstream.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#36577 enhance: enable manual compaction for collections without indexes
  internal/datacoord/compaction_policy_single.go
  internal/datacoord/compaction_trigger.go
  internal/datacoord/compaction_trigger_test.go
  internal/datacoord/garbage_collector.go
  internal/datacoord/handler.go
  internal/datacoord/index_meta.go
  internal/datacoord/util.go
  tests/integration/compaction/mix_compaction_test.go
Labels: kind/enhancement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, test/integration

#36675 enhance: Convert unincode to ascii to improving expression parsing efficiency
  internal/parser/planparserv2/parser_visitor.go
  internal/parser/planparserv2/plan_parser_v2.go
  internal/parser/planparserv2/plan_parser_v2_test.go
  internal/parser/planparserv2/utils.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#36676 enhance: [cherry-pick]Convert unincode to ascii to improving expression parsing efficiency
  internal/parser/planparserv2/plan_parser_v2.go
  internal/parser/planparserv2/plan_parser_v2_test.go
  internal/parser/planparserv2/utils.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#36679 enhance: [2.4] remove warnings when there is no partition key set
  internal/datacoord/task_index.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed, do-not-merge/missing-related-pr

#36674 enhance: remove warnings when there is no partition key set
  internal/datacoord/task_index.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#36699 enhance: Swap the position of import job states
  internal/proto/internal.proto
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, area/internal-api, dco-passed

#36617 fix: rocksmq consume too slow when the channel is full
  pkg/mq/mqimpl/rocksmq/client/client_impl.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#36618 fix: rocksmq consume too slow if the channel is full
  pkg/mq/mqimpl/rocksmq/client/client_impl.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#36626 enhance: fix skip msg log with empty position info
  pkg/mq/msgstream/mq_msgstream.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#36601 enhance: Optimize import scheduling and add time cost metric
  configs/milvus.yaml
  internal/datacoord/import_checker.go
  internal/datacoord/import_checker_test.go
  internal/datacoord/import_job.go
  internal/datacoord/import_meta.go
  internal/datacoord/import_scheduler.go
  internal/datacoord/import_scheduler_test.go
  internal/datacoord/import_task.go
  internal/datacoord/import_util.go
  internal/datacoord/services.go
  internal/datanode/importv2/scheduler.go
  internal/datanode/importv2/task.go
  internal/datanode/importv2/task_import.go
  internal/datanode/importv2/task_l0_import.go
  internal/datanode/importv2/task_l0_preimport.go
  internal/datanode/importv2/task_preimport.go
  pkg/metrics/datacoord_metrics.go
  pkg/metrics/metrics.go
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/component_param_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#36694 fix: [24]Remove neighbors if compactTo is unindexed (#36503)
  internal/datacoord/handler.go
  internal/datacoord/handler_test.go
  internal/datacoord/segment_info.go
  internal/datacoord/server_test.go
  internal/proto/data_coord.proto
Labels: kind/bug, size/XXL, approved, lgtm, ci-passed, dco-passed

#36706 enhance: Update knowhere commit to fix mac compilation
  internal/core/thirdparty/knowhere/CMakeLists.txt
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed, area/compilation

#36690 fix: raise l0 compaction memory ratio to 0.5
  configs/milvus.yaml
  pkg/util/paramtable/component_param.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#36691 fix: [24]raise l0 compaction memory ratio to 0.5
  configs/milvus.yaml
  pkg/util/paramtable/component_param.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#36712 enhance: [2.4] Add streaming forward policy switch for delegator (#36330)
  configs/milvus.yaml
  internal/querynodev2/delegator/delegator_data.go
  internal/querynodev2/delegator/delegator_delta_forward.go
  internal/querynodev2/delegator/delta_forward.go
  internal/querynodev2/delegator/delta_forward_test.go
  internal/querynodev2/delegator/scalar_pruner.go
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/XL, approved, lgtm, ci-passed, dco-passed

#36701 fix: streaming metrics do not clear
  internal/streamingnode/server/wal/metricsutil/segment.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#36688 enhance: open mmap on standalone-kafka in ci-e2e
  ci/jenkins/PR.groovy
  tests/_helm/values/e2e/standalone-kafka-mmap
  tests/scripts/get_release_name.sh
Labels: kind/enhancement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#36547 enhance: Datacoord to support prioritization of compaction tasks
  configs/milvus.yaml
  internal/datacoord/compaction.go
  internal/datacoord/compaction_queue.go
  internal/datacoord/compaction_queue_test.go
  internal/datacoord/compaction_test.go
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/XL, approved, lgtm, ci-passed, dco-passed

#36668 enhance: Use common gc config
  cmd/roles/roles.go
  internal/querynodev2/handlers_test.go
  internal/querynodev2/local_worker_test.go
  internal/querynodev2/server_test.go
  internal/querynodev2/services_test.go
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#36670 enhance: Use common gc config (#36668)
  cmd/roles/roles.go
  internal/querynodev2/handlers_test.go
  internal/querynodev2/local_worker_test.go
  internal/querynodev2/server_test.go
  internal/querynodev2/services_test.go
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#36628 enhance: remove unnecessary clone in meta cache
  internal/datacoord/meta.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#36729 enhance: [Cherry-Pick] UpdateSegmentsInfo should update remaining segment info even if some one not exist
  internal/datacoord/meta.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#36726 enhance: UpdateSegmentsInfo should update remaining segment info even if some one not exist
  internal/datacoord/meta.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed, PR | need cherry-pick

#36687 enhance: use new implementation of e2e pipeline
  ci/jenkins/PR.groovy
  ci/jenkins/PR2.groovy
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#36732 enhance: [24]Add more info in logs
  internal/datanode/channel_manager.go
  internal/datanode/compaction/mix_compactor.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#36480 feat: add enable_tokenizer params to VarChar field
  internal/core/src/common/FieldMeta.cpp
  internal/core/src/common/FieldMeta.h
  internal/core/src/common/Schema.h
  internal/core/thirdparty/tantivy/tantivy-binding/src/tokenizer.rs
  internal/core/unittest/test_c_tokenizer.cpp
  internal/core/unittest/test_text_match.cpp
  internal/datacoord/job_manager_test.go
  internal/flushcommon/pipeline/flow_graph_embedding_node_test.go
  internal/metastore/kv/rootcoord/kv_catalog_test.go
  internal/proxy/task_test.go
  internal/proxy/util.go
  internal/util/ctokenizer/text_schema_validator.go
  internal/util/ctokenizer/text_schema_validator_test.go
  pkg/util/typeutil/field_schema.go
  tests/python_client/requirements.txt
  tests/python_client/testcases/test_bulk_insert.py
  tests/python_client/testcases/test_query.py
  tests/python_client/testcases/test_search.py
  tests/restful_client_v2/testcases/test_vector_operations.py
Labels: kind/feature, sig/testing, size/XL, approved, lgtm, area/test, ci-passed, dco-passed

#36721 fix: fix json in [] expr bug
  internal/core/src/exec/expression/TermExpr.cpp
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#36728 enhance: [2.4] the estimate method when loading the collection
  internal/core/src/common/resource_c.h
  internal/core/src/index/IndexFactory.cpp
  internal/core/src/index/IndexFactory.h
  internal/core/src/index/Meta.h
  internal/core/src/index/StringIndexMarisa.cpp
  internal/core/src/segcore/SegmentSealedImpl.cpp
  internal/core/src/segcore/Types.h
  internal/core/src/segcore/load_index_c.cpp
  internal/core/src/segcore/load_index_c.h
  internal/core/thirdparty/knowhere/CMakeLists.txt
  internal/core/unittest/CMakeLists.txt
  internal/core/unittest/test_loading.cpp
  internal/proto/cgo_msg.proto
  internal/querynodev2/segments/load_index_info.go
  internal/querynodev2/segments/segment.go
  internal/querynodev2/segments/segment_loader.go
  internal/querynodev2/segments/utils.go
  pkg/util/constant.go
Labels: kind/enhancement, size/XL, lgtm, ci-passed, dco-passed, area/compilation

#36747 enhance: Add balance report log for qc balancer
  internal/querycoordv2/balance/balance.go
  internal/querycoordv2/balance/channel_level_score_balancer.go
  internal/querycoordv2/balance/multi_target_balance.go
  internal/querycoordv2/balance/report.go
  internal/querycoordv2/balance/rowcount_based_balancer.go
  internal/querycoordv2/balance/rowcount_based_balancer_test.go
  internal/querycoordv2/balance/score_based_balancer.go
  internal/querycoordv2/balance/utils.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#36749 enhance: [2.4] Add balance report log for qc balancer
  internal/querycoordv2/balance/balance.go
  internal/querycoordv2/balance/channel_level_score_balancer.go
  internal/querycoordv2/balance/multi_target_balance.go
  internal/querycoordv2/balance/report.go
  internal/querycoordv2/balance/rowcount_based_balancer.go
  internal/querycoordv2/balance/rowcount_based_balancer_test.go
  internal/querycoordv2/balance/score_based_balancer.go
  internal/querycoordv2/balance/utils.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#36684 enhance: Optimize import scheduling and add time cost metric (#36601)
  configs/milvus.yaml
  internal/datacoord/import_checker.go
  internal/datacoord/import_checker_test.go
  internal/datacoord/import_job.go
  internal/datacoord/import_meta.go
  internal/datacoord/import_scheduler.go
  internal/datacoord/import_scheduler_test.go
  internal/datacoord/import_task.go
  internal/datacoord/import_util.go
  internal/datacoord/services.go
  internal/datanode/importv2/scheduler.go
  internal/datanode/importv2/task.go
  internal/datanode/importv2/task_import.go
  internal/datanode/importv2/task_l0_import.go
  internal/datanode/importv2/task_l0_preimport.go
  internal/datanode/importv2/task_preimport.go
  pkg/metrics/datacoord_metrics.go
  pkg/metrics/metrics.go
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/component_param_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#36745 enhance: Update antlr version and refine parsing not in
  go.mod
  go.sum
  internal/parser/planparserv2/Plan.g4
  internal/parser/planparserv2/README.md
  internal/parser/planparserv2/error_listener.go
  internal/parser/planparserv2/generate.sh
  internal/parser/planparserv2/generated/Plan.interp
  internal/parser/planparserv2/generated/Plan.tokens
  internal/parser/planparserv2/generated/PlanLexer.interp
  internal/parser/planparserv2/generated/PlanLexer.tokens
  internal/parser/planparserv2/generated/plan_base_visitor.go
  internal/parser/planparserv2/generated/plan_lexer.go
  internal/parser/planparserv2/generated/plan_parser.go
  internal/parser/planparserv2/generated/plan_visitor.go
  internal/parser/planparserv2/parser_visitor.go
  internal/parser/planparserv2/plan_parser_v2.go
  internal/parser/planparserv2/plan_parser_v2_test.go
  internal/parser/planparserv2/pool.go
  internal/parser/planparserv2/pool_test.go
  scripts/antlr-4.13.2-complete.jar
  scripts/antlr-4.9-complete.jar
Labels: kind/enhancement, area/dependency, size/XXL, approved, lgtm, ci-passed, dco-passed

#36738 test: Add json key in [] test to verify issue 36718
  tests/python_client/common/common_func.py
  tests/python_client/testcases/test_query.py
Labels: sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#36270 fix: BinlogDeserializeReader leak in mix_compactor.go
  internal/datanode/compaction/mix_compactor.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#36758 enhance: Bump milvus & proto version to v2.4.13
  go.mod
  go.sum
  pkg/common/version.go
  pkg/go.mod
  pkg/go.sum
Labels: kind/enhancement, area/dependency, size/S, approved, lgtm, ci-passed, dco-passed, kind/branch-feature

#36753 enhance: Support new RESTful URL to describe import job
  internal/distributed/proxy/httpserver/constant.go
  internal/distributed/proxy/httpserver/handler_v2.go
  internal/distributed/proxy/httpserver/handler_v2_test.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#36741 fix: [24]fail to init fg clears flushTs so that slows flush
  internal/datanode/data_sync_service.go
  internal/datanode/writebuffer/manager.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#36565 enhance: [2.4]support sparse vector mmap in growing segment type
  internal/core/src/common/VectorTrait.h
  internal/core/src/mmap/ChunkData.h
  internal/core/src/mmap/ChunkVector.h
  internal/core/unittest/test_chunk_vector.cpp
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#36783 fix: [2.4] Use metrics values instead of hardcode mock values
  internal/rootcoord/quota_center.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#36773 fix: may exceed max tnx in etcd operations
  internal/metastore/kv/rootcoord/suffix_snapshot.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#36782 fix: Use metrics values instead of hardcode mock values
  internal/rootcoord/quota_center.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#35825 enhance: support null and default value in restful api
  internal/distributed/proxy/httpserver/constant.go
  internal/distributed/proxy/httpserver/handler_v1.go
  internal/distributed/proxy/httpserver/handler_v2.go
  internal/distributed/proxy/httpserver/handler_v2_test.go
  internal/distributed/proxy/httpserver/request_v2.go
  internal/distributed/proxy/httpserver/utils.go
  internal/distributed/proxy/httpserver/utils_test.go
Labels: kind/enhancement, size/XL, approved, lgtm, ci-passed, dco-passed

#36796 doc: Update go version in DEVELOPMENT.md
  DEVELOPMENT.md
Labels: size/S, approved, lgtm, ci-passed, dco-passed, kind/doc

#36786 enhance: skip alter operation when no change are detected
  internal/proxy/meta_cache.go
  internal/rootcoord/alter_collection_task.go
  internal/rootcoord/alter_collection_task_test.go
  internal/rootcoord/alter_database_task.go
  internal/rootcoord/alter_database_task_test.go
  internal/rootcoord/util.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#36793 enhance: [2.4] gc in the snapshot kv
  internal/metastore/kv/rootcoord/suffix_snapshot.go
  internal/metastore/kv/rootcoord/suffix_snapshot_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#36798 enhance: [2.4] support to execute the method which contains the ctx param
  pkg/util/expr/expr.go
Labels: kind/enhancement, kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#36797 enhance: support to execute the method which contains the ctx param
  pkg/util/expr/expr.go
Labels: kind/enhancement, kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#36792 enhance: gc in the snapshot kv
  internal/metastore/kv/rootcoord/suffix_snapshot.go
  internal/metastore/kv/rootcoord/suffix_snapshot_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#36785 enhance: skip alter operation when no change are detected
  internal/proxy/meta_cache.go
  internal/rootcoord/alter_collection_task.go
  internal/rootcoord/alter_collection_task_test.go
  internal/rootcoord/alter_database_task.go
  internal/rootcoord/alter_database_task_test.go
  internal/rootcoord/util.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#36715 feat: add bulk insert support for Functions
  internal/datanode/importv2/hash.go
  internal/datanode/importv2/task_import.go
  internal/datanode/importv2/task_l0_import.go
  internal/datanode/importv2/util.go
  internal/storage/insert_data.go
  internal/util/importutilv2/binlog/util.go
  internal/util/importutilv2/csv/reader_test.go
  internal/util/importutilv2/csv/row_parser.go
  internal/util/importutilv2/json/reader_test.go
  internal/util/importutilv2/json/row_parser.go
  internal/util/importutilv2/numpy/reader.go
  internal/util/importutilv2/numpy/reader_test.go
  internal/util/importutilv2/parquet/reader_test.go
  internal/util/importutilv2/parquet/util.go
  internal/util/testutil/test_util.go
  pkg/util/testutils/gen_data.go
Labels: kind/feature, size/L, approved, lgtm, ci-passed, dco-passed

#36810 test: [cherry pick]Add json key in [] test to verify issue
  tests/python_client/common/common_func.py
  tests/python_client/testcases/test_query.py
Labels: sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#36813 enhance: update knowhere version to support diskann iterator
  internal/core/thirdparty/knowhere/CMakeLists.txt
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed, area/compilation

#36808 fix: make sure alias is cached
  internal/proxy/meta_cache.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed, kind/branch-feature, do-not-merge/missing-related-pr

#36713 feat: Restful support for BM25 function
  internal/distributed/proxy/httpserver/constant.go
  internal/distributed/proxy/httpserver/handler_v2.go
  internal/distributed/proxy/httpserver/handler_v2_test.go
  internal/distributed/proxy/httpserver/request_v2.go
  internal/distributed/proxy/httpserver/utils.go
  internal/distributed/proxy/httpserver/utils_test.go
  internal/proxy/task_search.go
  internal/querynodev2/delegator/delegator.go
Labels: kind/feature, size/XL, approved, lgtm, ci-passed, dco-passed

#36766 feat: added more checks for function creation check
  internal/proxy/task_index.go
  internal/proxy/util.go
  internal/proxy/util_test.go
  internal/querynodev2/delegator/delegator.go
  internal/querynodev2/delegator/delegator_data.go
  internal/storage/insert_data.go
  pkg/util/metric/metric_type.go
Labels: kind/feature, size/XL, approved, lgtm, ci-passed, dco-passed

#36734 enhance: Add PreallocatedSegmentIDs for the compaction task
  internal/datacoord/compaction_task_clustering.go
  internal/datacoord/compaction_task_meta.go
  internal/datacoord/compaction_task_mix.go
  internal/datacoord/compaction_trigger.go
  internal/datacoord/compaction_trigger_test.go
  internal/datacoord/compaction_trigger_v2.go
  internal/datacoord/mock_test.go
  internal/proto/data_coord.proto
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#36817 fix: fix macos code checker
  internal/core/src/common/ChunkTarget.cpp
  internal/core/src/mmap/ChunkedColumn.h
Labels: kind/bug, size/S, approved, lgtm, dco-passed

#36833 enhance: enable macos checker
  .github/mergify.yml
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#36761 fix: add proportion for capacity seal policy in streaming flusher
  internal/flushcommon/pipeline/data_sync_service.go
  internal/flushcommon/writebuffer/options.go
  internal/flushcommon/writebuffer/write_buffer.go
  internal/streamingnode/server/flusher/flusherimpl/channel_lifetime.go
  internal/streamingnode/server/wal/interceptors/segment/manager/pchannel_manager_test.go
  internal/streamingnode/server/wal/interceptors/segment/policy/segment_limitation_policy.go
  internal/streamingnode/server/wal/interceptors/segment/stats/stats.go
  internal/streamingnode/server/wal/interceptors/segment/stats/stats_manager.go
  internal/streamingnode/server/wal/interceptors/segment/stats/stats_manager_test.go
  internal/streamingnode/server/wal/interceptors/segment/stats/stats_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#36818 fix: streaming consumer may get stucked when handler is un-consumed
  internal/distributed/streaming/internal/consumer/consumer_impl.go
  internal/distributed/streaming/internal/consumer/consumer_test.go
  internal/distributed/streaming/internal/consumer/handler.go
  internal/distributed/streaming/internal/consumer/message_handler.go
  internal/streamingnode/client/handler/consumer/consumer_impl.go
  internal/streamingnode/client/handler/consumer/consumer_test.go
  pkg/streaming/util/message/adaptor/handler.go
  pkg/streaming/util/message/adaptor/handler_test.go
  pkg/streaming/util/message/message_handler.go
  pkg/streaming/util/message/message_handler_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#36820 test: Add upsert in rows tests
  tests/python_client/requirements.txt
  tests/python_client/testcases/test_insert.py
Labels: sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#36072 feat: support bm25 logs mixcompaction
  internal/datacoord/import_task.go
  internal/datacoord/meta.go
  internal/datacoord/task_stats.go
  internal/datanode/compaction/clustering_compactor.go
  internal/datanode/compaction/clustering_compactor_test.go
  internal/datanode/compaction/compactor_common.go
  internal/datanode/compaction/merge_sort.go
  internal/datanode/compaction/mix_compactor.go
  internal/datanode/compaction/mix_compactor_test.go
  internal/datanode/compaction/segment_reader_from_binlogs.go
  internal/datanode/compaction/segment_writer.go
  internal/datanode/compaction/segment_writer_test.go
  internal/indexnode/indexnode_service.go
  internal/indexnode/task_stats.go
  internal/indexnode/task_stats_test.go
  internal/indexnode/taskinfo_ops.go
  internal/indexnode/taskinfo_ops_test.go
  internal/metastore/kv/binlog/binlog.go
  internal/metastore/kv/datacoord/util.go
  internal/proto/worker.proto
  internal/querynodev2/delegator/idf_oracle.go
  internal/querynodev2/delegator/idf_oracle_test.go
Labels: kind/feature, area/dependency, sig/testing, size/XL, approved, lgtm, area/test, ci-passed, area/internal-api, dco-passed, area/compilation

#36838 fix: heap buffer overflow when unittest at index wrapper
  internal/core/unittest/test_index_wrapper.cpp
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#36841 test: update test cases
  tests/python_client/testcases/test_index.py
  tests/python_client/testcases/test_query.py
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#36853 test: Update Diskann supporting group by
  tests/python_client/testcases/test_mix_scenes.py
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#36789 enhance: [GoSDK] support unmarshal result set into orm receiver
  client/read.go
  client/results.go
  client/results_test.go
  client/row/type.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#36842 enhance: able to upload pytest logs when test is done
  ci/jenkins/Nightly2.groovy
  ci/jenkins/PR.groovy
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#36832 enhance: update the expr version to support automatic conversion of variable types
  go.mod
  go.sum
  internal/proxy/meta_cache.go
  pkg/go.mod
  pkg/go.sum
  pkg/util/expr/expr.go
  pkg/util/expr/expr_test.go
Labels: kind/enhancement, area/dependency, kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#36847 enhance: [2.4] update the expr version to support automatic conversion of variable types
  go.mod
  go.sum
  internal/proxy/meta_cache.go
  pkg/go.mod
  pkg/go.sum
  pkg/util/expr/expr.go
  pkg/util/expr/expr_test.go
Labels: kind/enhancement, area/dependency, kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#36566 enhance: support sparse vector mmap in growing segment type
  internal/core/src/common/VectorTrait.h
  internal/core/src/mmap/ChunkData.h
  internal/core/src/mmap/ChunkVector.h
  internal/core/unittest/test_chunk_vector.cpp
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#36861 enhance: able to upload pytest logs when test is done
  ci/jenkins/Nightly2.groovy
  ci/jenkins/PR.groovy
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#36857 enhance: add checkers for Faiss-based HNSW
  pkg/util/indexparamcheck/conf_adapter_mgr.go
  pkg/util/indexparamcheck/index_type.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#36862 enhance: able to upload pytest logs when test is done
  ci/jenkins/Nightly2.groovy
  ci/jenkins/PR.groovy
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, do-not-merge/missing-related-issue, dco-passed

#36873 enhance: [ci] separate ccache by branch for e2e pipeline
  ci/jenkins/Nightly2.groovy
  ci/jenkins/PR.groovy
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#36874 enhance: [ci] separate ccache by branch for e2e pipeline
  ci/jenkins/Nightly2.groovy
  ci/jenkins/PR.groovy
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#36821 enhance: Ignore db not found error in quota center
  internal/rootcoord/quota_center.go
  internal/rootcoord/quota_center_test.go
Labels: kind/enhancement, kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#36870 enhance: [ci] separate ccache by branch for e2e pipeline
  ci/jenkins/Nightly2.groovy
  ci/jenkins/PR-for-go-sdk.groovy
  ci/jenkins/PR.groovy
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#36878 test: update test cases
  tests/python_client/testcases/test_collection.py
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#36879 fix: Unify loaded partition check to delegator
  internal/querynodev2/delegator/delegator.go
  internal/querynodev2/segments/retrieve.go
  internal/querynodev2/segments/validate.go
  internal/querynodev2/tasks/search_task.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#36850 enhance: Ignore db not found error in quota center (#36821)
  internal/rootcoord/quota_center.go
  internal/rootcoord/quota_center_test.go
Labels: kind/enhancement, kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#36848 enhance: Enhance segment log
  internal/datacoord/meta.go
  internal/querynodev2/segments/segment_l0.go
  internal/querynodev2/services.go
Labels: kind/enhancement, kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#36849 enhance: Enhance segment log (#36848)
  internal/datacoord/meta.go
  internal/querynodev2/segments/segment_l0.go
  internal/querynodev2/services.go
Labels: kind/enhancement, kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#36839 test: update test cases
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed, manual-pass, kind/test

#36855 test: [cherry pick]Add upsert in row test
  tests/python_client/milvus_client/test_milvus_client_insert.py
  tests/python_client/requirements.txt
  tests/python_client/testcases/test_insert.py
Labels: sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#36859 fix: remove excessive logging
  internal/core/thirdparty/tantivy/tantivy-binding/src/tokenizer.rs
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#36882 fix: use chunk_row_nums to iterate
  internal/core/src/mmap/ChunkedColumn.h
  internal/core/src/segcore/InsertRecord.h
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#36886 fix: bm25 search failed when nq > 1 and remove idf oracle when no bm25 field exist.
  internal/querynodev2/delegator/delegator.go
  internal/querynodev2/delegator/delegator_data.go
  internal/querynodev2/delegator/distribution.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, needs-dco

#36714 fix: not return err if consistencyLevel is not set to a valid value
  internal/distributed/proxy/httpserver/handler_v2.go
  internal/distributed/proxy/httpserver/handler_v2_test.go
  internal/distributed/proxy/httpserver/request_v2.go
  internal/distributed/proxy/httpserver/utils.go
  internal/distributed/proxy/httpserver/utils_test.go
  tests/restful_client_v2/testcases/test_vector_operations.py
Labels: kind/bug, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#36888 enhance: Fill start pos & level for growing segment
  internal/querynodev2/handlers.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#36899 fix: Direct forward delta exclude l0 segments
  internal/querynodev2/delegator/delta_forward.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#36909 test: Add Diskann for grouping search
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#36924 enhance: improve scripts standalone_embed,add upgrade
  scripts/standalone_embed.sh
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#36572 enhance: add ts support for iterator(#22718)
  go.mod
  go.sum
  internal/proxy/search_util.go
  internal/proxy/task_query.go
  internal/proxy/task_query_test.go
  internal/proxy/task_search.go
  internal/proxy/task_search_test.go
  internal/querynodev2/delegator/delegator.go
Labels: kind/enhancement, area/dependency, sig/testing, size/XL, approved, lgtm, area/test, ci-passed, dco-passed

#36912 enhance: [GoSDK] Use variadic params for options
  client/example/playground/main.go
  client/maintenance_options.go
  client/maintenance_test.go
  client/read.go
  client/read_options.go
  client/read_test.go
  client/results.go
  tests/go_client/testcases/delete_test.go
  tests/go_client/testcases/index_test.go
  tests/go_client/testcases/insert_test.go
  tests/go_client/testcases/partition_test.go
  tests/go_client/testcases/query_test.go
  tests/go_client/testcases/search_test.go
  tests/go_client/testcases/upsert_test.go
Labels: kind/enhancement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#36907 fix: add checks for bm25 k1 and b in sparse index checker
  pkg/util/indexparamcheck/constraints.go
  pkg/util/indexparamcheck/sparse_float_vector_base_checker.go
  pkg/util/indexparamcheck/sparse_float_vector_base_checker_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#36910 fix: return error if searching against BM25 output field with incorrect metric type
  internal/proxy/task_index.go
  internal/querynodev2/delegator/delegator.go
  internal/querynodev2/delegator/delegator_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#36935 fix: [hotfix] Load original key if ts is MaxTimestamp
  configs/milvus.yaml
  internal/metastore/kv/rootcoord/suffix_snapshot.go
  pkg/util/paramtable/service_param.go
Labels: size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#36535 fix: Remove enableLevelZeroSegment config
  internal/datacoord/compaction_policy_l0.go
  internal/datanode/data_node.go
  internal/flushcommon/writebuffer/bf_write_buffer.go
  internal/flushcommon/writebuffer/bf_write_buffer_test.go
  internal/flushcommon/writebuffer/options.go
  internal/flushcommon/writebuffer/write_buffer.go
  internal/flushcommon/writebuffer/write_buffer_test.go
  internal/streamingnode/server/server.go
  pkg/util/paramtable/component_param.go
Labels: kind/bug, size/XL, approved, lgtm, ci-passed, dco-passed

#36840 enhance: adjust some err msg
  internal/rootcoord/create_collection_task.go
  internal/rootcoord/create_collection_task_test.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#36700 enhance: support default value in import
  internal/proxy/validate_util.go
  internal/util/importutilv2/json/reader_test.go
  internal/util/importutilv2/json/row_parser.go
  internal/util/importutilv2/parquet/field_reader.go
  internal/util/importutilv2/parquet/reader_test.go
  internal/util/importutilv2/parquet/util.go
  internal/util/nullutil/nullutil.go
  internal/util/testutil/test_util.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#36852 fix: datacoord stuck at stopping progress
  internal/datacoord/session/datanode_manager.go
  internal/datacoord/session/mock_datanode_manager.go
  internal/datacoord/sync_segments_scheduler.go
  internal/datacoord/sync_segments_scheduler_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#36881 fix: Rootcoord stuck at graceful stop progress
  Makefile
  internal/allocator/global_id_allocator.go
  internal/allocator/mock_global_id_allocator.go
  internal/datacoord/channel_manager_v2.go
  internal/datacoord/channel_manager_v2_test.go
  internal/datacoord/server.go
  internal/datacoord/server_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed, area/compilation

#36880 fix: Rootcoord stuck at graceful stop progress
  Makefile
  internal/allocator/global_id_allocator.go
  internal/allocator/mock_global_id_allocator.go
  internal/datacoord/channel_manager.go
  internal/datacoord/channel_manager_test.go
  internal/datacoord/server.go
  internal/datacoord/server_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed, area/compilation

#36917 enhance: [2.4] force to stop buffer message when receiving the drop collection message
  pkg/mq/msgstream/mq_msgstream.go
  pkg/mq/msgstream/mq_msgstream_test.go
Labels: kind/enhancement, kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#36943 enhance: mmap for faiss hnsw
  pkg/util/indexparamcheck/index_type.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#36914 fix: [2.4] Direct forward delta exclude l0 segments (#36899)
  internal/querynodev2/delegator/delta_forward.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#36934 fix: Load original key if ts is MaxTimestamp
  configs/milvus.yaml
  internal/metastore/kv/rootcoord/suffix_snapshot.go
  pkg/util/paramtable/service_param.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#36948 Bump milvus version to v2.4.13-hotfix
  deployments/binary/README.md
  deployments/docker/cluster-distributed-deployment/inventory.ini
  deployments/docker/gpu/standalone/docker-compose.yml
  deployments/docker/standalone/docker-compose.yml
Labels: size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass, do-not-merge/missing-related-pr, do-not-merge/invalid-pr-format

#36945 enhance: [GoSDK] Set default max send recv size
  client/client_config.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#36310 fix: unicode replacement character (0xFFFD) are not supported as csv delimiter
  internal/util/importutilv2/option.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#36816 enhance: enable parallel execution of L0 compactions
  internal/datacoord/compaction.go
  internal/datacoord/compaction_test.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#36942 fix: loss small bm25 binlogs
  internal/flushcommon/syncmgr/task.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#36908 enhance: report err when group_size is wrong(#36146)
  internal/distributed/proxy/httpserver/handler_v2.go
  internal/proxy/search_util.go
  internal/proxy/task_search_test.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#36950 fix: [2.4] Load original key if ts is MaxTimestamp (#36934)
  configs/milvus.yaml
  internal/metastore/kv/rootcoord/suffix_snapshot.go
  pkg/util/paramtable/service_param.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#36938 fix:[2.4]Chunk Id out of range in vector BF search, after the growing index removes the vec chunks.
  internal/core/src/query/SearchOnGrowing.cpp
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#35970 fix:add log in mixCompactionTask and set fail/timeout task to clean
  internal/datacoord/compaction_task_l0.go
  internal/datacoord/compaction_task_l0_test.go
  internal/datacoord/compaction_task_mix.go
  internal/datacoord/compaction_task_mix_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#36952 test: check query response data
  tests/python_client/testcases/test_mix_scenes.py
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#36803 fix: [cherry-pick] Fix clustering compaction task leak
  internal/datacoord/compaction_task_clustering.go
  internal/datacoord/compaction_task_clustering_test.go
  internal/datanode/compaction/clustering_compactor.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#35527 enhance: all op(Null) is false in expr
  internal/core/src/common/FieldData.cpp
  internal/core/src/common/Vector.h
  internal/core/src/exec/expression/AlwaysTrueExpr.cpp
  internal/core/src/exec/expression/BinaryArithOpEvalRangeExpr.cpp
  internal/core/src/exec/expression/BinaryArithOpEvalRangeExpr.h
  internal/core/src/exec/expression/BinaryRangeExpr.cpp
  internal/core/src/exec/expression/BinaryRangeExpr.h
  internal/core/src/exec/expression/CompareExpr.cpp
  internal/core/src/exec/expression/CompareExpr.h
  internal/core/src/exec/expression/ExistsExpr.cpp
  internal/core/src/exec/expression/Expr.h
  internal/core/src/exec/expression/JsonContainsExpr.cpp
  internal/core/src/exec/expression/LogicalBinaryExpr.cpp
  internal/core/src/exec/expression/LogicalUnaryExpr.cpp
  internal/core/src/exec/expression/TermExpr.cpp
  internal/core/src/exec/expression/UnaryExpr.cpp
  internal/core/src/exec/expression/UnaryExpr.h
  internal/core/src/exec/operator/FilterBitsNode.cpp
  internal/core/src/exec/operator/MvccNode.cpp
  internal/core/src/exec/operator/groupby/SearchGroupByOperator.h
  internal/core/src/index/BitmapIndex.cpp
  internal/core/src/index/BitmapIndex.h
  internal/core/src/index/HybridScalarIndex.h
  internal/core/src/index/InvertedIndexTantivy.h
  internal/core/src/index/ScalarIndex.h
  internal/core/src/index/ScalarIndexSort.cpp
  internal/core/src/index/ScalarIndexSort.h
  internal/core/src/index/StringIndexMarisa.cpp
  internal/core/src/index/StringIndexMarisa.h
  internal/core/src/query/ScalarIndex.h
  internal/core/src/segcore/ChunkedSegmentSealedImpl.cpp
  internal/core/src/segcore/FieldIndexing.cpp
  internal/core/src/segcore/SegmentSealedImpl.cpp
  internal/core/src/segcore/Utils.cpp
  internal/core/unittest/test_expr.cpp
  internal/core/unittest/test_string_expr.cpp
  internal/core/unittest/test_utils/AssertUtils.h
  internal/core/unittest/test_utils/DataGen.h
  tests/python_client/testcases/test_search.py
Labels: kind/enhancement, sig/testing, size/XXL, lgtm, area/test, ci-passed, dco-passed, area/compilation, test/integration

#36843 enhance: add vector index mgr to remove vector index type dependency
  cmd/tools/migration/mmap/mmap_230_240.go
  internal/core/src/index/Index.h
  internal/core/src/index/ScalarIndex.h
  internal/core/src/index/VectorIndex.h
  internal/core/src/segcore/vector_index_c.cpp
  internal/core/src/segcore/vector_index_c.h
  internal/core/thirdparty/knowhere/CMakeLists.txt
  internal/core/unittest/test_c_api.cpp
  internal/datacoord/index_meta.go
  internal/datacoord/index_service.go
  internal/datacoord/task_index.go
  internal/datacoord/task_scheduler_test.go
  internal/datacoord/util.go
  internal/indexnode/task_index.go
  internal/proxy/cgo_util_test.go
  internal/proxy/task_index.go
  internal/querynodev2/segments/collection.go
  internal/querynodev2/segments/index_attr_cache.go
  internal/querynodev2/segments/index_attr_cache_test.go
  internal/querynodev2/segments/segment.go
  internal/querynodev2/segments/utils.go
  internal/querynodev2/segments/utils_test.go
  internal/util/vecindexmgr/vector_index_mgr.go
  internal/util/vecindexmgr/vector_index_mgr_test.go
  pkg/util/indexparamcheck/index_type_test.go
Labels: kind/enhancement, size/XL, approved, lgtm, ci-passed, dco-passed, area/compilation

#36814 enhance: consider the mmap chunck cache config when resource usage estimate
  internal/core/src/index/IndexFactory.cpp
  internal/querynodev2/segments/segment_loader.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#36964 enhance: [GoSDK] write back auto id value to row based input
  client/example/rowbase/main.go
  client/row/data.go
  client/write.go
  client/write_options.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#36956 enhance: adding mix compaction first prioritizer
  configs/milvus.yaml
  internal/datacoord/compaction_queue.go
  internal/datacoord/compaction_queue_test.go
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#36959 fix: avoid panic when load segment with pkoracle and idforacle already exist
  internal/querynodev2/delegator/delegator.go
  internal/querynodev2/delegator/delegator_data.go
  internal/querynodev2/delegator/distribution.go
  internal/querynodev2/delegator/distribution_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#36939 fix:Chunk Id out of range in vector BF search, after the growing index removes the vec chunks.
  internal/core/src/query/SearchOnGrowing.cpp
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#36975 fix: Query node panic during sending rpc to worker
  internal/querynodev2/cluster/worker.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#36930 fix: not add isClusteringKey when describe collection
  internal/distributed/proxy/httpserver/constant.go
  internal/distributed/proxy/httpserver/handler_v1_test.go
  internal/distributed/proxy/httpserver/handler_v2.go
  internal/distributed/proxy/httpserver/utils.go
  internal/distributed/proxy/httpserver/utils_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#36979 enhance: Datacoord to support prioritization of compaction tasks
  configs/milvus.yaml
  internal/datacoord/compaction.go
  internal/datacoord/compaction_queue.go
  internal/datacoord/compaction_queue_test.go
  internal/datacoord/compaction_test.go
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/XL, approved, lgtm, ci-passed, dco-passed

#36961 fix: datacoord stuck at stopping progress (#36852)
  internal/datacoord/mock_session_manager.go
  internal/datacoord/session_manager.go
  internal/datacoord/sync_segments_scheduler.go
  internal/datacoord/sync_segments_scheduler_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#36985 enhance: enable parallel execution of L0 compactions (#36816)
  internal/datacoord/compaction.go
  internal/datacoord/compaction_test.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#36978 test: Add alias test with rename collection
  tests/python_client/milvus_client/test_milvus_client_collection.py
  tests/python_client/milvus_client/test_milvus_client_delete.py
  tests/python_client/milvus_client/test_milvus_client_insert.py
  tests/python_client/milvus_client/test_milvus_client_partition.py
  tests/python_client/testcases/test_alias.py
  tests/python_client/testcases/test_collection.py
  tests/python_client/testcases/test_compaction.py
  tests/python_client/testcases/test_field_partial_load.py
  tests/python_client/testcases/test_mix_scenes.py
  tests/python_client/testcases/test_partition_key.py
  tests/python_client/testcases/test_search.py
  tests/python_client/testcases/test_utility.py
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#35836 enhance: Support memory mode chunk cache (#35347)
  configs/milvus.yaml
  internal/core/src/segcore/SegmentSealed.h
  internal/core/src/segcore/SegmentSealedImpl.cpp
  internal/core/src/segcore/SegmentSealedImpl.h
  internal/core/src/segcore/segment_c.cpp
  internal/core/src/segcore/segment_c.h
  internal/core/src/storage/ChunkCache.cpp
  internal/core/src/storage/ChunkCache.h
  internal/core/unittest/test_chunk_cache.cpp
  internal/core/unittest/test_sealed.cpp
  internal/querynodev2/segments/segment.go
  internal/querynodev2/server.go
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/component_param_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#36954 enhance: Log when limit writing by deletion
  internal/rootcoord/quota_center.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#36955 enhance: [cp24]Log when limit writing by deletion
  internal/rootcoord/quota_center.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#36957 enhance: Track complex delete rates
  internal/proxy/impl.go
  internal/proxy/task_delete.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed
