Repository milvus-io/milvus, pull requests merged in 2024-09, with the labels that each got.

#35879 fix: bump bytedance/sonic to v1.12.2 to fix compilation error with go 1.23.0
  go.mod
  go.sum
  internal/distributed/proxy/httpserver/handler_v2_test.go
Labels: kind/bug, area/dependency, size/S, approved, lgtm, ci-passed, dco-passed

#35844 enhance: Add build-go target
  Makefile
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed, area/compilation

#35870 enhance: Refine flusher channel management
  internal/streamingnode/server/flusher/flusherimpl/channel_lifetime.go
  internal/streamingnode/server/flusher/flusherimpl/flusher_impl.go
  internal/streamingnode/server/flusher/flusherimpl/flusher_impl_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#35801 feat: tantivy tokenizer binding
  internal/core/src/segcore/CMakeLists.txt
  internal/core/src/segcore/map_c.cpp
  internal/core/src/segcore/map_c.h
  internal/core/src/segcore/token_stream_c.cpp
  internal/core/src/segcore/token_stream_c.h
  internal/core/src/segcore/tokenizer_c.cpp
  internal/core/src/segcore/tokenizer_c.h
  internal/core/thirdparty/tantivy/CMakeLists.txt
  internal/core/thirdparty/tantivy/rust-hashmap.h
  internal/core/thirdparty/tantivy/tantivy-binding/Cargo.lock
  internal/core/thirdparty/tantivy/tantivy-binding/Cargo.toml
  internal/core/thirdparty/tantivy/tantivy-binding/include/tantivy-binding.h
  internal/core/thirdparty/tantivy/tantivy-binding/src/hashmap_c.rs
  internal/core/thirdparty/tantivy/tantivy-binding/src/index_writer.rs
  internal/core/thirdparty/tantivy/tantivy-binding/src/lib.rs
  internal/core/thirdparty/tantivy/tantivy-binding/src/string_c.rs
  internal/core/thirdparty/tantivy/tantivy-binding/src/token_stream_c.rs
  internal/core/thirdparty/tantivy/tantivy-binding/src/tokenizer.rs
  internal/core/thirdparty/tantivy/tantivy-binding/src/tokenizer_c.rs
  internal/core/thirdparty/tantivy/token-stream.h
  internal/core/thirdparty/tantivy/tokenizer.h
  internal/core/thirdparty/tantivy/tokenizer_demo.cpp
  internal/util/ctokenizer/c_map.go
  internal/util/ctokenizer/c_token_stream.go
  internal/util/ctokenizer/c_tokenizer.go
  internal/util/ctokenizer/c_tokenizer_factory.go
  internal/util/ctokenizer/c_tokenizer_test.go
  internal/util/ctokenizer/helper.go
  internal/util/tokenizerapi/mocks/TokenStream.go
  internal/util/tokenizerapi/mocks/Tokenizer.go
  internal/util/tokenizerapi/token_stream.go
  internal/util/tokenizerapi/tokenizer.go
Labels: kind/feature, size/XXL, approved, lgtm, ci-passed, dco-passed, area/compilation

#35875 fix: Fix the reference to a variable after it has been moved
  internal/core/src/common/FieldDataInterface.h
  internal/core/src/common/Vector.h
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#35845 enhance: Add build-go target (#35844)
  Makefile
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed, area/compilation

#35865 fix: Check clustering key skip load behavior
  internal/proxy/meta_cache.go
  internal/proxy/meta_cache_test.go
  internal/proxy/util.go
  internal/proxy/util_test.go
  pkg/util/typeutil/schema.go
  pkg/util/typeutil/schema_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#35901 fix: Fix compile error
  internal/datanode/compaction/merge_sort.go
Labels: kind/bug, kind/improvement, size/XS, do-not-merge/missing-related-issue, dco-passed

#35855 fix: memory leak in unittest and open the USE_ASAN option when build unittest
  internal/core/unittest/CMakeLists.txt
  internal/core/unittest/test_c_api.cpp
  internal/core/unittest/test_data_codec.cpp
  internal/core/unittest/test_sealed.cpp
  internal/core/unittest/test_utils/c_api_test_utils.h
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed, area/compilation

#35857 fix: memory leak in unittest and open the USE_ASAN option when build unittest
  internal/core/unittest/CMakeLists.txt
  internal/core/unittest/test_c_api.cpp
  internal/core/unittest/test_utils/c_api_test_utils.h
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed, area/compilation

#35874 test: add array inverted index function test
  tests/python_client/common/common_func.py
  tests/python_client/testcases/test_query.py
  tests/python_client/testcases/test_search.py
Labels: kind/improvement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#35814 enhance: make search groupby stop when reaching topk groups
  internal/core/src/common/QueryInfo.h
  internal/core/src/query/PlanProto.cpp
  internal/core/src/query/groupby/SearchGroupByOperator.cpp
  internal/core/src/query/groupby/SearchGroupByOperator.h
  internal/core/unittest/test_group_by.cpp
  internal/proto/plan.proto
  internal/proxy/search_util.go
  internal/proxy/task.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#35905 enhance: Check load fields for previous loaded collection
  internal/querycoordv2/job/job_load.go
  internal/querycoordv2/job/job_test.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#35788 enhance: rewrite index params for compatibility
  internal/datacoord/index_meta.go
  internal/datacoord/index_meta_test.go
  internal/proxy/task_index.go
  pkg/util/indexparamcheck/index_type.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#35910 enhance: [2.4] Check load fields for previous loaded collection (#35905)
  internal/querycoordv2/job/job_load.go
  internal/querycoordv2/job/job_test.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#35904 fix: Fix the reference to a variable after it has been moved (#35875)
  internal/core/src/common/FieldDataInterface.h
  internal/core/src/common/Vector.h
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#35902 enhance: Remove bf from streaming node
  internal/flushcommon/pipeline/data_sync_service.go
  internal/flushcommon/syncmgr/key_lock_dispatcher.go
  internal/flushcommon/syncmgr/mock_task.go
  internal/flushcommon/syncmgr/task.go
  internal/flushcommon/writebuffer/l0_write_buffer.go
  internal/flushcommon/writebuffer/write_buffer.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#35850 fix: Fix some replicas don't participate in the query after the failure recovery
  internal/querycoordv2/checkers/channel_checker.go
  internal/querycoordv2/dist/dist_handler.go
  internal/querycoordv2/dist/dist_handler_test.go
  internal/querycoordv2/meta/leader_view_manager.go
  internal/querycoordv2/meta/leader_view_manager_test.go
  internal/querycoordv2/services_test.go
  internal/querycoordv2/task/scheduler.go
  internal/querycoordv2/task/task_test.go
  internal/querycoordv2/utils/util.go
  internal/querycoordv2/utils/util_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#35810 fix:rename mmap file path to avoid directory conflict
  internal/core/src/segcore/SegmentSealedImpl.cpp
  internal/core/src/segcore/load_index_c.cpp
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#35909 test: add bitmap index cases
  tests/python_client/base/client_base.py
  tests/python_client/check/func_check.py
  tests/python_client/common/code_mapping.py
  tests/python_client/common/common_func.py
  tests/python_client/common/common_params.py
  tests/python_client/common/common_type.py
  tests/python_client/testcases/test_index.py
Labels: sig/testing, size/XXL, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#35805 test: fix repeated random partition name
  tests/go_client/testcases/partition_test.go
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed, manual-pass, kind/test

#35907 fix: SkipIndex cause segment fault
  internal/core/src/index/SkipIndex.cpp
  internal/core/src/index/SkipIndex.h
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#35281 enhance: Add disk filemananger parallel load control to reduce the memory consumption
  internal/core/src/storage/DiskFileManagerImpl.cpp
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#35908 fix: SkipIndex cause segment fault
  internal/core/src/index/SkipIndex.cpp
  internal/core/src/index/SkipIndex.h
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#35920 enhance: [GoSDK] Add load option for field partial load
  client/maintenance_options.go
  client/maintenance_test.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#35898 fix: Handle Input/Output Errors in vsnprintf and snprintf
  internal/core/src/log/Log.cpp
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#35867 test: update test cases
  tests/python_client/milvus_client/test_milvus_client_insert.py
  tests/python_client/requirements.txt
  tests/python_client/testcases/test_collection.py
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#35887 feat: add static view for the expr
  internal/http/router.go
  internal/http/server.go
  internal/http/static/index.html
  internal/http/static_view.go
Labels: kind/feature, kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#35954 feat: [2.4] add static view for the expr interface
  internal/http/router.go
  internal/http/server.go
  internal/http/static/index.html
  internal/http/static_view.go
Labels: kind/feature, kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#35931 enhance: add IT for rate limit using db properties
  tests/integration/minicluster_v2.go
  tests/integration/ratelimit/db_properties_test.go
Labels: kind/enhancement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, test/integration

#35930 enhance: add IT for rate limit using db properties
  tests/integration/minicluster_v2.go
  tests/integration/ratelimit/db_properties_test.go
Labels: kind/enhancement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, test/integration

#35935 enhance: remove cooling off in rate limiter for read requests
  configs/milvus.yaml
  internal/proxy/impl.go
  internal/proxy/metrics_info.go
  internal/proxy/proxy.go
  internal/querynodev2/collector/collector.go
  internal/querynodev2/metrics_info.go
  internal/querynodev2/services.go
  internal/querynodev2/tasks/query_task.go
  internal/querynodev2/tasks/search_task.go
  internal/rootcoord/quota_center.go
  internal/rootcoord/quota_center_test.go
  pkg/util/metricsinfo/quota_metric.go
  pkg/util/paramtable/quota_param.go
  pkg/util/paramtable/quota_param_test.go
Labels: kind/enhancement, size/XL, approved, lgtm, ci-passed, dco-passed

#35936 enhance: remove cooling off in rate limiter for read requests
  configs/milvus.yaml
  internal/proxy/impl.go
  internal/proxy/metrics_info.go
  internal/proxy/proxy.go
  internal/querynodev2/collector/collector.go
  internal/querynodev2/metrics_info.go
  internal/querynodev2/services.go
  internal/querynodev2/tasks/query_task.go
  internal/querynodev2/tasks/search_task.go
  internal/rootcoord/quota_center.go
  internal/rootcoord/quota_center_test.go
  pkg/util/metricsinfo/quota_metric.go
  pkg/util/paramtable/quota_param.go
  pkg/util/paramtable/quota_param_test.go
Labels: kind/enhancement, size/XL, approved, lgtm, ci-passed, dco-passed

#35891 fix: err degenerated to a new variable
  internal/datanode/importv2/task_l0_import.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#35963 fix: [2.4] fill the metric type field in the LoadMetaInfo object
  internal/core/src/query/SearchOnSealed.cpp
  internal/core/src/segcore/ConcurrentVector.h
  internal/querycoordv2/task/executor.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#35957 fix: Fix data race for clustering compaction writer
  internal/datanode/compaction/clustering_compactor.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#35958 fix: [cherry-pick]Fix data race for clustering compaction writer
  internal/datanode/compaction/clustering_compactor.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#35964 fix: [hotfix-2.4] fill the metric type field in the LoadMetaInfo object
  internal/core/src/query/SearchOnSealed.cpp
  internal/core/src/segcore/ConcurrentVector.h
  internal/querycoordv2/task/executor.go
Labels: size/S, approved

#35968 fix:[cherry-pick] add log in mixCompactionTask and set fail/timeout task to clean
  internal/datacoord/compaction_task_l0.go
  internal/datacoord/compaction_task_l0_test.go
  internal/datacoord/compaction_task_mix.go
  internal/datacoord/compaction_task_mix_test.go
Labels: size/L, approved, lgtm, ci-passed, manual-pass

#35948 enhance: Fix typo of clustering key not loaded msg
  internal/proxy/meta_cache.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#35989 enhance: [2.4] fix cpp-lint issue for recent change
  internal/core/src/query/SearchOnSealed.cpp
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass, kind/branch-feature

#35984 feat: [hotfix-2.4] add static view for the expr interface
  internal/http/router.go
  internal/http/server.go
  internal/http/static/index.html
  internal/http/static_view.go
Labels: kind/improvement, size/L, approved, lgtm, ci-passed

#35987 fix: not check nullable and default value in pk field
  internal/rootcoord/create_collection_task.go
  internal/rootcoord/create_collection_task_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#35918 enhance: Add delete buffer related quota logic
  configs/milvus.yaml
  internal/querynodev2/delegator/delegator.go
  internal/querynodev2/delegator/deletebuffer/delete_buffer.go
  internal/querynodev2/delegator/deletebuffer/delete_buffer_test.go
  internal/querynodev2/delegator/deletebuffer/delete_item.go
  internal/querynodev2/delegator/deletebuffer/delete_item_test.go
  internal/querynodev2/delegator/deletebuffer/list_delete_buffer.go
  internal/querynodev2/delegator/deletebuffer/list_delete_buffer_test.go
  internal/querynodev2/delegator/mock_delegator.go
  internal/querynodev2/metrics_info.go
  internal/querynodev2/services_test.go
  internal/rootcoord/quota_center.go
  pkg/util/metricsinfo/quota_metric.go
  pkg/util/paramtable/quota_param.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#35980 enhance: Remove too frequent logs in Delete
  internal/querynodev2/pipeline/delete_node.go
  internal/querynodev2/services.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#35928 fix: Fix tracing config update logic
  cmd/roles/roles.go
  internal/core/src/common/Tracer.cpp
  internal/distributed/datacoord/service.go
  internal/distributed/datanode/service.go
  internal/distributed/indexnode/service.go
  internal/distributed/proxy/service.go
  internal/distributed/querycoord/service.go
  internal/distributed/querynode/service.go
  internal/distributed/rootcoord/service.go
  internal/distributed/streamingnode/service.go
  internal/util/grpcclient/client.go
  pkg/tracer/stats_handler.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#35943 fix: Check all values for `trie.predictive_search`
  internal/core/src/index/StringIndexMarisa.cpp
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#35937 fix: Fix privilege group hasn't been register for validate
  internal/proxy/privilege_interceptor.go
  internal/proxy/privilege_interceptor_test.go
  internal/rootcoord/root_coord.go
  pkg/util/constant.go
  tests/integration/rbac/privilege_group_test.go
Labels: kind/bug, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, test/integration

#36004 enhance: Fix trace.cpp lint format issue
  internal/core/src/common/Tracer.cpp
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#35997 enhance: [2.4] Add delete buffer related quota logic (#35918)
  configs/milvus.yaml
  internal/querynodev2/delegator/delegator.go
  internal/querynodev2/delegator/deletebuffer/delete_buffer.go
  internal/querynodev2/delegator/deletebuffer/delete_buffer_test.go
  internal/querynodev2/delegator/deletebuffer/delete_item.go
  internal/querynodev2/delegator/deletebuffer/delete_item_test.go
  internal/querynodev2/delegator/deletebuffer/list_delete_buffer.go
  internal/querynodev2/delegator/deletebuffer/list_delete_buffer_test.go
  internal/querynodev2/delegator/mock_delegator.go
  internal/querynodev2/metrics_info.go
  internal/querynodev2/services_test.go
  internal/rootcoord/quota_center.go
  pkg/util/metricsinfo/quota_metric.go
  pkg/util/paramtable/quota_param.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#35999 fix: [2.4] Check all values for `trie.predictive_search` (#35943)
  internal/core/src/index/StringIndexMarisa.cpp
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#35993 fix: Fill load field list from old version load info
  internal/querycoordv2/meta/collection_manager.go
  internal/querycoordv2/meta/collection_manager_test.go
  internal/querycoordv2/server_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#36000 enhance: [2.4] Fix typo of clustering key not loaded msg (#35948)
  internal/proxy/meta_cache.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#35992 fix: Fix DB limiter nodes are mistakenly cleaned up (#35991)
  internal/proxy/simple_rate_limiter.go
  internal/util/ratelimitutil/rate_limiter_tree.go
  internal/util/ratelimitutil/rate_limiter_tree_test.go
  tests/integration/ratelimit/flush_test.go
Labels: kind/bug, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, test/integration

#35991 fix: Fix DB limiter nodes are mistakenly cleaned up
  internal/proxy/simple_rate_limiter.go
  internal/util/ratelimitutil/rate_limiter_tree.go
  internal/util/ratelimitutil/rate_limiter_tree_test.go
  tests/integration/ratelimit/flush_test.go
Labels: kind/bug, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, test/integration

#35974 enhance: reduce mmap_rss after chunkcache warmup
  internal/core/src/segcore/SegmentSealedImpl.cpp
  internal/core/src/storage/ChunkCache.cpp
  internal/core/src/storage/ChunkCache.h
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#35938 fix: Fix privilege group hasn't been register for validate
  internal/proxy/privilege_interceptor.go
  internal/proxy/privilege_interceptor_test.go
  internal/rootcoord/root_coord.go
  pkg/util/constant.go
  tests/integration/rbac/privilege_group_test.go
Labels: kind/bug, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, manual-pass, test/integration

#36009 enhance: [skip e2e] Add git safe dir for code check env
  .github/workflows/code-checker.yaml
Labels: kind/bug, kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#36017 enhance: [skip e2e][2.4] Add git safe dir for code check env (#36009)
  .github/workflows/code-checker.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#35919 fix: Fix dynamic release partition may fail search/query request
  internal/querycoordv2/job/job_release.go
  internal/querycoordv2/job/undo.go
  internal/querycoordv2/observers/collection_observer.go
  internal/querycoordv2/observers/target_observer.go
  internal/querycoordv2/observers/target_observer_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#36006 fix: fallback params may be overridden (#35972)
  configs/milvus.yaml
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/component_param_test.go
  pkg/util/paramtable/param_item.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#36012 enhance: [nightly pipeline] add more timeout for log and list all pods status
  ci/jenkins/Nightly2.groovy
Labels: kind/enhancement, size/XS, dco-passed

#36011 enhance: [nightly pipeline] add more timeout for log and list all pods status
  ci/jenkins/Nightly2.groovy
Labels: kind/enhancement, size/XS, dco-passed

#36013 enhance: [nightly pipeline] add more timeout for log and list all pods status
  ci/jenkins/Nightly2.groovy
Labels: kind/enhancement, size/XS, dco-passed

#35945 fix: binary arith expression on inverted index
  internal/core/src/exec/expression/BinaryArithOpEvalRangeExpr.cpp
  internal/core/src/exec/expression/Expr.h
  tests/python_client/testcases/test_index.py
Labels: kind/bug, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#36026 fix: datacoord broker use querycoord broker config and get segment info timeout
  internal/flushcommon/broker/datacoord.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#35978 enhance: bump etcd version
  deployments/docker/cluster-distributed-deployment/roles/deploy-etcd/tasks/main.yml
  deployments/docker/dev/docker-compose-apple-silicon.yml
  deployments/docker/dev/docker-compose.yml
  deployments/docker/gpu/standalone/docker-compose.yml
  deployments/docker/standalone/docker-compose.yml
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#35977 enhance: bump etcd version
  deployments/docker/cluster-distributed-deployment/roles/deploy-etcd/tasks/main.yml
  deployments/docker/dev/docker-compose-apple-silicon.yml
  deployments/docker/dev/docker-compose.yml
  deployments/docker/gpu/standalone/docker-compose.yml
  deployments/docker/standalone/docker-compose.yml
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#35981 enhance: [cp]Remove too frequent logs in Delete
  internal/querynodev2/pipeline/delete_node.go
  internal/querynodev2/services.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#36019 fix: Fix dynamic release partition may fail search/query request (#35919)
  internal/querycoordv2/job/job_release.go
  internal/querycoordv2/job/undo.go
  internal/querycoordv2/observers/collection_observer.go
  internal/querycoordv2/observers/target_observer.go
  internal/querycoordv2/observers/target_observer_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#35998 fix: [2.4] Fix tracing config update logic (#35928)
  cmd/roles/roles.go
  internal/core/src/common/Tracer.cpp
  internal/distributed/datacoord/service.go
  internal/distributed/datanode/service.go
  internal/distributed/indexnode/service.go
  internal/distributed/proxy/service.go
  internal/distributed/querycoord/service.go
  internal/distributed/querynode/service.go
  internal/distributed/rootcoord/service.go
  internal/util/grpcclient/client.go
  pkg/tracer/stats_handler.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#35962 fix: fill the metric type field in the LoadMetaInfo object
  internal/core/src/query/SearchOnSealed.cpp
  internal/core/src/segcore/ConcurrentVector.h
  internal/datanode/compaction/priority_queue_test.go
  internal/datanode/compaction/segment_writer.go
Labels: kind/bug, size/S, lgtm, ci-passed, dco-passed

#36027 fix: not append valid data when transfer to insert record
  internal/core/src/segcore/InsertRecord.h
  internal/proxy/search_util.go
  internal/proxy/task_search_test.go
  internal/storage/utils.go
  pkg/util/typeutil/schema.go
  tests/integration/null_data/null_data_test.go
Labels: kind/bug, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, test/integration

#36056 enhance: Fix SearchOnSealed clang-format lint
  internal/core/src/query/SearchOnSealed.cpp
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#36035 fix: [cp]Change deltalog memory estimation factor to one
  internal/querynodev2/segments/segment_loader.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#36033 fix: Change deltalog memory estimation factor to one
  internal/querynodev2/segments/segment_loader.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#36060 enhance: [2.4] Use `MARISA_LABEL_ORDER` when building trie index
  internal/core/src/index/StringIndexMarisa.cpp
  internal/core/src/index/StringIndexMarisa.h
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#36062 fix: [2.4] Use SliceSetEqual to compare load field list
  internal/querycoordv2/job/job_load.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#36045 fix: Set an empty segment if compaction deleted all inserts
  internal/datanode/compaction/mix_compactor_test.go
  internal/datanode/compaction/segment_writer.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#36067 enhance: Update Knowhere version
  internal/core/thirdparty/knowhere/CMakeLists.txt
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed, area/compilation, kind/branch-feature

#36066 fix: Fix logic dead lock when delegator has high memory usage
  internal/querycoordv2/balance/balance.go
  internal/querycoordv2/balance/score_based_balancer.go
  internal/querycoordv2/checkers/balance_checker.go
  internal/querycoordv2/checkers/balance_checker_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#35967 fix: [cherry-pick] add log in mixCompactionTask and set fail/timeout task to clean
  internal/datacoord/compaction_task_l0.go
  internal/datacoord/compaction_task_l0_test.go
  internal/datacoord/compaction_task_mix.go
  internal/datacoord/compaction_task_mix_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed, manual-pass, do-not-merge/missing-related-pr

#36069 enhance: Bump milvus & proto version to v2.4.11
  client/go.mod
  client/go.sum
  go.mod
  go.sum
  pkg/common/version.go
  pkg/go.mod
  pkg/go.sum
Labels: kind/enhancement, area/dependency, size/S, approved, lgtm, ci-passed, dco-passed, kind/branch-feature

#36078 fix: binlog reader not released in time
  internal/storage/data_codec.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#36015 fix: Change l0SegmentsRowCount limits to a reasonable value
  configs/milvus.yaml
  pkg/util/paramtable/quota_param.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#35975 fix:rename mmap file path to avoid directory conflict (#35810)
  internal/core/src/segcore/SegmentSealedImpl.cpp
  internal/core/src/segcore/load_index_c.cpp
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#36049 enhance: Log warn on delayed compaction tasks
  internal/datacoord/compaction.go
  internal/datacoord/compaction_test.go
  internal/datacoord/services.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#36075 fix: memory leak in proxy meta cache
  internal/proxy/meta_cache.go
  internal/proxy/meta_cache_test.go
  internal/proxy/mock_cache.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#36076 fix: memory leak in proxy meta cache
  internal/proxy/meta_cache.go
  internal/proxy/meta_cache_test.go
  internal/proxy/mock_cache.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#35985 fix:support config index offsetcache and fix create same index again
  configs/milvus.yaml
  internal/datacoord/index_meta.go
  internal/datacoord/index_service.go
  internal/querynodev2/segments/segment.go
  pkg/util/indexparams/index_params.go
  pkg/util/paramtable/component_param.go
  tests/python_client/testcases/test_query.py
Labels: kind/bug, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#36085 fix: [2.4] delay to start the metric server port
  cmd/roles/roles.go
  internal/http/healthz/healthz_handler.go
  internal/http/server_test.go
Labels: kind/bug, kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#36065 fix: Fix logic dead lock when delegator has high memory usage
  internal/querycoordv2/balance/balance.go
  internal/querycoordv2/balance/score_based_balancer.go
  internal/querycoordv2/checkers/balance_checker.go
  internal/querycoordv2/checkers/balance_checker_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#36097 fix: binary arith expression on inverted index (#35945)
  internal/core/src/exec/expression/BinaryArithOpEvalRangeExpr.cpp
  internal/core/src/exec/expression/Expr.h
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#36080 fix: delay to start the metric server port
  cmd/roles/roles.go
  internal/http/healthz/healthz_handler.go
  internal/http/server_test.go
Labels: kind/bug, kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#36044 fix: Set an empty segment if compaction deleted all inserts
  internal/datanode/compaction/mix_compactor_test.go
  internal/datanode/compaction/segment_writer.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#36034 enhance: Use `MARISA_LABEL_ORDER` when building trie index
  internal/core/src/index/StringIndexMarisa.cpp
  internal/core/src/index/StringIndexMarisa.h
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#36105 enhance: [skip e2e] add a rule to label ci-pass when go-sdk check status
  .github/mergify.yml
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#36107 enhance: Use stats Handler to record request/response size metrics
  internal/distributed/proxy/service.go
  internal/proxy/impl.go
  pkg/metrics/grpc_stats_handler.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#36110 enhance: Remove duplicated log in proxy service
  internal/distributed/proxy/service.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#36114 fix: Revert "enhance: avoid the coexistence of the old coordinator and the new node/proxy (#35760)"
  cmd/roles/roles.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#35912 enhance: Bulkinsert supports null in csv formats
  internal/util/importutilv2/csv/reader.go
  internal/util/importutilv2/csv/reader_test.go
  internal/util/importutilv2/csv/row_parser.go
  internal/util/importutilv2/csv/row_parser_test.go
  internal/util/importutilv2/option.go
  internal/util/importutilv2/reader.go
  internal/util/testutil/test_util.go
  tests/integration/import/util_test.go
Labels: kind/enhancement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, test/integration

#36073 test: add query expr test cases
  tests/python_client/base/client_base.py
  tests/python_client/common/code_mapping.py
  tests/python_client/common/common_func.py
  tests/python_client/common/common_params.py
  tests/python_client/testcases/test_mix_scenes.py
  tests/scripts/ci_e2e_4am.sh
Labels: sig/testing, size/XL, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#36126 fix: [2.4] Make legacy non-lexicographic branch break swtich
  internal/core/src/index/StringIndexMarisa.cpp
  internal/core/unittest/test_string_index.cpp
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#36051 fix: Use SliceSetEqual to compare load field list
  internal/querycoordv2/job/job_load.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#36125 fix: Make legacy non-lexicographic branch break swtich
  internal/core/src/index/StringIndexMarisa.cpp
  internal/core/unittest/test_string_index.cpp
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#36113 fix: Revert "enhance: avoid the coexistence of the old coordinator and the new node/proxy (#35720)"
  cmd/roles/roles.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#36032 test: update pymilvus version and test cases
  tests/python_client/requirements.txt
  tests/python_client/testcases/test_partition.py
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#36131 test: add more bitmap test cases
  tests/python_client/common/code_mapping.py
  tests/python_client/common/common_params.py
  tests/python_client/testcases/test_index.py
  tests/python_client/testcases/test_mix_scenes.py
Labels: sig/testing, size/XL, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#36135 enhance: [skip e2e] fix mergify
  .github/mergify.yml
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#36039 test: set bulk insert test fail fast
  tests/scripts/ci_e2e_4am.sh
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#36087 fix: BinlogDeserializeReader leak
  internal/indexnode/task_stats.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#35403 fix: fix empty indices of sparse float
  internal/core/src/mmap/Utils.h
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#36128 fix: empty result when having only one subReq(#36098)
  internal/querynodev2/segments/result.go
  tests/integration/hybridsearch/hybridsearch_test.go
Labels: kind/bug, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, test/integration

#36121 enhance: Reset task check interval configuration
  pkg/util/paramtable/component_param.go
  tests/_helm/values/e2e/distributed
  tests/_helm/values/e2e/distributed-streaming-service
  tests/_helm/values/e2e/standalone
  tests/_helm/values/e2e/standalone-kafka
  tests/_helm/values/e2e/standalone-one-pod
  tests/scripts/values/ci/pr-4am.yaml
Labels: kind/enhancement, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#36142 enhance: add a env
  deployments/docker/standalone/docker-compose.yml
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#36143 enhance: add a env
  deployments/docker/standalone/docker-compose.yml
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass, do-not-merge/missing-related-pr

#36139 enhance: [skip e2e] [mergify]replace branch by reference
  .github/mergify.yml
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#36133 enhance: timer instead of ticker
  internal/proxy/connection/manager.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#36118 enhance: [2.4] Use stats Handler to record request/response size metrics (#36107)
  internal/distributed/proxy/service.go
  internal/proxy/impl.go
  pkg/metrics/grpc_stats_handler.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#36040 enhance: [pipeline] list all status before uninstall helm release
  ci/jenkins/Nightly2.groovy
  ci/jenkins/PR-for-go-sdk.groovy
  ci/jenkins/PR2.groovy
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#36043 enhance: [pipeline] list all status before uninstall helm release
  ci/jenkins/Nightly2.groovy
  ci/jenkins/PR2.groovy
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#36154 enhance: fix a security vulnerability
  .github/workflows/check-issue.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#36156 enhance: fix a security vulnerability
  .github/workflows/check-issue.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#36155 enhance: fix a security vulnerability
  .github/workflows/check-issue.yaml
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#36042 enhance: [pipeline] list all status before uninstall helm release
  ci/jenkins/Nightly2.groovy
  ci/jenkins/PR2.groovy
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#36137 enhance: delete streaming-service pipeline in nightly
  ci/jenkins/Nightly2.groovy
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed, do-not-merge/missing-related-pr

#36148 test: update test cases and sdk version
  tests/python_client/requirements.txt
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#36158 test: add check after altering cardinality limit
  tests/python_client/common/common_func.py
  tests/python_client/common/common_params.py
  tests/python_client/testcases/test_index.py
  tests/python_client/testcases/test_mix_scenes.py
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#36014 fix: Change l0SegmentsRowCount limits to a reasonable value
  configs/milvus.yaml
  pkg/util/paramtable/quota_param.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#36152 fix: clustering compact not support null
  internal/datanode/compaction/clustering_compactor.go
  internal/datanode/compaction/clustering_compactor_test.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#36172 enhance: Check ANN field loaded in proxy
  internal/parser/planparserv2/plan_parser_v2.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#36061 enhance: [2.4]Allow empty sparse row
  internal/core/src/common/Utils.h
  internal/core/src/segcore/FieldIndexing.h
  internal/core/unittest/test_indexing.cpp
  pkg/util/typeutil/schema.go
  pkg/util/typeutil/schema_test.go
  tests/integration/sparse/sparse_test.go
Labels: kind/enhancement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, test/integration

#36177 fix: [GoSDK] Sync empty result set handling
  client/column/columns.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#35973 feat: Support create collection with functions
  go.mod
  go.sum
  internal/metastore/kv/rootcoord/kv_catalog.go
  internal/metastore/kv/rootcoord/kv_catalog_test.go
  internal/metastore/kv/rootcoord/rootcoord_constant.go
  internal/metastore/model/collection.go
  internal/metastore/model/collection_test.go
  internal/metastore/model/field.go
  internal/metastore/model/function.go
  internal/metastore/model/function_test.go
  internal/proxy/meta_cache.go
  internal/proxy/meta_cache_test.go
  internal/proxy/task.go
  internal/proxy/task_index.go
  internal/proxy/task_test.go
  internal/proxy/util.go
  internal/rootcoord/broker.go
  internal/rootcoord/create_collection_task.go
  internal/rootcoord/field_id.go
  internal/rootcoord/root_coord.go
  pkg/common/common.go
  pkg/go.mod
  pkg/go.sum
  pkg/util/merr/utils.go
  pkg/util/typeutil/schema.go
Labels: kind/feature, area/dependency, size/XL, approved, lgtm, ci-passed, dco-passed

#36189 enhance: Add L0 forward policy to support remote load
  configs/milvus.yaml
  internal/querynodev2/delegator/delegator_data.go
  internal/querynodev2/delegator/delegator_delta_forward.go
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#36138 enhance: rename some params and reduce default bitmapCardinalityLimit…
  configs/milvus.yaml
  internal/core/src/common/Consts.h
  internal/core/src/index/BitmapIndex.cpp
  internal/core/src/index/HybridScalarIndex.cpp
  internal/proxy/task_index.go
  internal/proxy/task_index_test.go
  pkg/util/paramtable/autoindex_param.go
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#36194 enhance: [2.4] Check ANN field loaded in proxy (#36172)
  internal/parser/planparserv2/plan_parser_v2.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#36186 test: Add part of test cases for default and null support
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#36175 enhance: Add metrics for Delete entries num of L0seg
  internal/datacoord/meta.go
  internal/datacoord/services.go
  pkg/metrics/datacoord_metrics.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#36208 enhance: [2.4] Add L0 forward policy to support remote load (#36189)
  configs/milvus.yaml
  internal/querynodev2/delegator/delegator_data.go
  internal/querynodev2/delegator/delegator_delta_forward.go
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#35947 enhance: Update stats task to optional
  internal/datacoord/compaction_trigger.go
  internal/datacoord/go_channel_singleton.go
  internal/datacoord/import_scheduler.go
  internal/datacoord/import_scheduler_test.go
  internal/datacoord/index_service.go
  internal/datacoord/job_manager.go
  internal/datacoord/job_manager_test.go
  internal/datacoord/meta.go
  internal/datacoord/segment_operator.go
  internal/datacoord/server.go
  internal/datacoord/stats_task_meta.go
  internal/datacoord/stats_task_meta_test.go
  internal/datacoord/task_analyze.go
  internal/datacoord/task_index.go
  internal/datacoord/task_scheduler.go
  internal/datacoord/task_scheduler_test.go
  internal/datacoord/task_stats.go
  internal/datacoord/task_stats_test.go
  internal/datanode/compaction/merge_sort.go
  internal/datanode/compaction/mix_compactor_test.go
  internal/indexnode/indexnode_service.go
  internal/indexnode/indexnode_test.go
  internal/indexnode/task_stats.go
  internal/indexnode/taskinfo_ops.go
  internal/indexnode/taskinfo_ops_test.go
  internal/metastore/kv/datacoord/kv_catalog.go
  internal/proto/index_coord.proto
  internal/proto/worker.proto
Labels: kind/enhancement, size/XXL, approved, lgtm, ci-passed, area/internal-api, dco-passed

#36185 feat: adding cache to expression parse
  go.mod
  go.sum
  internal/parser/planparserv2/plan_parser_v2.go
  internal/parser/planparserv2/plan_parser_v2_test.go
  pkg/util/typeutil/schema.go
Labels: kind/feature, area/dependency, size/M, approved, lgtm, ci-passed, dco-passed

#36216 enhance: Add error handler for write buffer
  internal/flushcommon/syncmgr/serializer.go
  internal/flushcommon/syncmgr/storage_serializer.go
  internal/flushcommon/writebuffer/options.go
  internal/flushcommon/writebuffer/write_buffer.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#36145 fix: fix ReadWrite privilege group deny all global API
  internal/proxy/privilege_interceptor.go
  internal/proxy/privilege_interceptor_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#36144 fix: fix ReadWrite privilege group deny all global API
  internal/proxy/privilege_interceptor.go
  internal/proxy/privilege_interceptor_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#36205 enhance: span tracing of c++ part
  internal/core/src/common/Tracer.cpp
  internal/core/src/common/Tracer.h
  internal/core/src/query/visitors/ExecPlanNodeVisitor.cpp
  internal/core/src/segcore/SegmentInterface.cpp
  internal/core/src/segcore/reduce/Reduce.cpp
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#36090 fix: split stream query result to avoid grpc response too large error
  configs/milvus.yaml
  internal/querynodev2/handlers.go
  internal/querynodev2/server.go
  internal/querynodev2/tasks/query_stream_task.go
  internal/util/streamrpc/streamer.go
  internal/util/streamrpc/streamer_test.go
  pkg/util/paramtable/component_param.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#36240 test: Add group size tests
  tests/python_client/check/param_check.py
  tests/python_client/common/milvus_sys.py
  tests/python_client/requirements.txt
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#36151 fix: streaming node consume blocks if recv message is too large
  internal/streamingnode/client/handler/consumer/consumer_impl.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#35824 enhance: Enable dynamic update replica selection policy
  internal/proxy/lb_policy.go
  internal/proxy/lb_policy_test.go
  internal/proxy/meta_cache.go
  internal/proxy/roundrobin_balancer.go
  internal/proxy/roundrobin_balancer_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed
