Repository milvus-io/milvus, pull requests merged in 2025-03, with the labels that each got.

#40269 enhance: [GoSDK][2.5] Use pkg v2 module path (#40134)
  client/entity/vectors.go
  client/go.mod
  client/go.sum
  client/milvusclient/admin.go
  client/milvusclient/admin_test.go
  client/milvusclient/alias.go
  client/milvusclient/alias_test.go
  client/milvusclient/client.go
  client/milvusclient/client_config.go
  client/milvusclient/collection.go
  client/milvusclient/collection_example_test.go
  client/milvusclient/collection_test.go
  client/milvusclient/common.go
  client/milvusclient/database.go
  client/milvusclient/database_test.go
  client/milvusclient/index.go
  client/milvusclient/index_test.go
  client/milvusclient/maintenance.go
  client/milvusclient/maintenance_test.go
  client/milvusclient/partition.go
  client/milvusclient/partition_test.go
  client/milvusclient/rbac.go
  client/milvusclient/rbac_test.go
  client/milvusclient/read.go
  client/milvusclient/read_test.go
  client/milvusclient/resource_group.go
  client/milvusclient/resource_group_test.go
  client/milvusclient/write.go
  client/milvusclient/write_options.go
  client/milvusclient/write_test.go
  tests/go_client/base/milvus_client.go
  tests/go_client/common/response_checker.go
  tests/go_client/common/utils.go
  tests/go_client/go.mod
  tests/go_client/go.sum
  tests/go_client/testcases/collection_test.go
  tests/go_client/testcases/database_test.go
  tests/go_client/testcases/delete_test.go
  tests/go_client/testcases/helper/data_helper.go
  tests/go_client/testcases/helper/field_helper.go
  tests/go_client/testcases/helper/helper.go
  tests/go_client/testcases/helper/schema_helper.go
  tests/go_client/testcases/index_test.go
  tests/go_client/testcases/insert_test.go
  tests/go_client/testcases/load_release_test.go
  tests/go_client/testcases/main_test.go
  tests/go_client/testcases/partition_test.go
  tests/go_client/testcases/query_test.go
  tests/go_client/testcases/search_test.go
  tests/go_client/testcases/upsert_test.go
Labels: kind/enhancement, area/dependency, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, PR | need cherry-pick, component/gosdk

#40259 fix: Fix task delta cache data race
  internal/querycoordv2/task/scheduler.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#40262 fix: [2.5] Fix task delta cache data race
  internal/querycoordv2/task/scheduler.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#40101 enhance: decrease delete record dump snapshot limit
  internal/core/src/segcore/DeletedRecord.h
  internal/core/unittest/test_delete_record.cpp
Labels: kind/enhancement, kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#40273 enhance: [skip e2e] only use mixcoord for scripts
  scripts/start_cluster.sh
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#40141 enhance: add monitor metric for retrieve raw data
  internal/core/src/monitor/prometheus_client.cpp
  internal/core/src/monitor/prometheus_client.h
  internal/core/src/segcore/SegmentInterface.cpp
  internal/core/src/segcore/reduce/Reduce.cpp
Labels: kind/enhancement, area/monitoring, size/M, approved, lgtm, ci-passed, dco-passed

#40251 enhance: Optimize Task Scheduling to Enable Concurrent Execution
  internal/datacoord/index_meta.go
  internal/datacoord/job_manager.go
  internal/datacoord/job_manager_test.go
  internal/datacoord/server.go
  internal/datacoord/session/indexnode_manager.go
  internal/datacoord/session/mock_worker_manager.go
  internal/datacoord/stats_task_meta.go
  internal/datacoord/task_index.go
  internal/datacoord/task_queue.go
  internal/datacoord/task_scheduler.go
  internal/datacoord/task_scheduler_test.go
  internal/indexnode/indexnode_service.go
  internal/indexnode/task_stats.go
Labels: kind/enhancement, size/XXL, approved, lgtm, ci-passed, dco-passed, component/indexnode

#40193 fix: [2.5] use the different msg type for the OperatePrivilegeV2 api
  client/go.mod
  client/go.sum
  go.mod
  go.sum
  internal/proxy/impl.go
  pkg/go.mod
  pkg/go.sum
  tests/go_client/go.mod
  tests/go_client/go.sum
  tests/integration/import/import_test.go
Labels: kind/bug, area/dependency, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed, go, test/integration

#40260 fix: restful drop db properties failed(#39953)
  internal/distributed/proxy/httpserver/request_v2.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#40271 test: update drop collection in teardown method
  tests/python_client/base/client_base.py
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed, python, kind/test

#40286 test: update drop collection in teardown method[2.5]
  tests/python_client/base/client_base.py
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed, python, kind/test

#40289 fix: [2.5] Change CMake variable for switch to knowhere-cuvs
  .gitignore
  README.md
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#40257 fix: restful drop db properties failure(#39953)
  internal/distributed/proxy/httpserver/request_v2.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, area/internal-api, dco-passed

#40293 enhance: Bump milvus & proto version to v2.5.6
  client/go.mod
  client/go.sum
  go.mod
  go.sum
  pkg/common/version.go
  pkg/go.mod
  pkg/go.sum
  tests/go_client/go.mod
  tests/go_client/go.sum
Labels: kind/enhancement, area/dependency, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed, go, kind/branch-feature

#40284 fix: [GoSDK] Return role without grants
  client/milvusclient/database_options.go
  client/milvusclient/rbac.go
  client/milvusclient/rbac_options.go
  client/milvusclient/rbac_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed, component/gosdk

#40296 test: [cherry-pick]fix text match
  tests/python_client/chaos/testcases/test_all_collections_after_chaos.py
  tests/python_client/common/common_func.py
Labels: kind/improvement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#40295 test: fix text match
  tests/python_client/chaos/testcases/test_all_collections_after_chaos.py
  tests/python_client/common/common_func.py
Labels: kind/improvement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#40254 fix: Add duplication param check for create index
  internal/proxy/task_index.go
  internal/proxy/task_index_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#40140 enhance: make json path index support term filter
  internal/core/src/exec/expression/TermExpr.cpp
  internal/core/src/exec/expression/TermExpr.h
  internal/core/src/segcore/arrow_fs_c.cpp
  internal/core/src/segcore/arrow_fs_c.h
  internal/core/src/segcore/column_groups_c.cpp
  internal/core/src/segcore/column_groups_c.h
  internal/core/src/segcore/packed_reader_c.cpp
  internal/core/src/segcore/packed_writer_c.cpp
  internal/core/unittest/test_column_groups_c.cpp
  internal/core/unittest/test_expr.cpp
  internal/core/unittest/test_packed_c.cpp
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#40301 enhance: Remove iterators in datanode
  internal/compaction/common.go
  internal/compaction/entity_filter.go
  internal/compaction/entity_filter_test.go
  internal/compaction/load_stats.go
  internal/datanode/compactor/clustering_compactor.go
  internal/datanode/compactor/clustering_compactor_test.go
  internal/datanode/compactor/compactor.go
  internal/datanode/compactor/compactor_common.go
  internal/datanode/compactor/executor.go
  internal/datanode/compactor/executor_test.go
  internal/datanode/compactor/l0_compactor.go
  internal/datanode/compactor/l0_compactor_test.go
  internal/datanode/compactor/merge_sort.go
  internal/datanode/compactor/mix_compactor.go
  internal/datanode/compactor/mix_compactor_test.go
  internal/datanode/compactor/mock_compactor.go
  internal/datanode/compactor/priority_queue.go
  internal/datanode/compactor/priority_queue_test.go
  internal/datanode/compactor/segment_record_reader.go
  internal/datanode/compactor/segment_writer.go
  internal/datanode/compactor/segment_writer_bench_test.go
  internal/datanode/compactor/segment_writer_test.go
  internal/datanode/data_node.go
  internal/datanode/iterators/deltalog_iterator.go
  internal/datanode/iterators/deltalog_iterator_test.go
  internal/datanode/iterators/iterator.go
  internal/datanode/services.go
  internal/datanode/services_test.go
  internal/flushcommon/pipeline/data_sync_service.go
  internal/flushcommon/pipeline/flow_graph_dd_node.go
  internal/flushcommon/pipeline/flow_graph_dd_node_test.go
  internal/flushcommon/util/util.go
  internal/indexnode/task_stats.go
  internal/indexnode/task_stats_test.go
Labels: kind/enhancement, kind/improvement, size/XL, approved, lgtm, ci-passed, dco-passed

#40305 fix: fix storage v2 cgo mem leak
  internal/storagev2/packed/packed_reader.go
  internal/storagev2/packed/packed_writer.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#40316 fix: duplicate consuming from stream for invisble segment
  internal/datacoord/handler.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#40318 fix: duplicate consuming from stream for invisible segment
  internal/datacoord/handler.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#40319 test: Remove the old get index params method
  tests/python_client/common/common_func.py
  tests/python_client/common/common_type.py
  tests/python_client/conftest.py
  tests/python_client/load/test_workload.py
  tests/python_client/milvus_client/test_milvus_client_index.py
  tests/python_client/testcases/test_collection.py
  tests/python_client/testcases/test_index.py
  tests/python_client/testcases/test_partition.py
  tests/python_client/testcases/test_partition_key.py
  tests/python_client/testcases/test_search.py
  tests/python_client/utils/util_pymilvus.py
Labels: test/ut, kind/improvement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, python, kind/test

#40317 enhance: upgrade rust version to 1.83 (#39295)
  build/docker/builder/cpu/amazonlinux2023/Dockerfile
  build/docker/builder/cpu/rockylinux8/Dockerfile
  build/docker/builder/cpu/ubuntu20.04/Dockerfile
  build/docker/builder/cpu/ubuntu22.04/Dockerfile
  build/docker/builder/gpu/ubuntu20.04/Dockerfile
  build/docker/builder/gpu/ubuntu22.04/Dockerfile
  internal/core/thirdparty/opendal/CMakeLists.txt
  scripts/3rdparty_build.sh
  scripts/install_deps.sh
Labels: kind/enhancement, area/dependency, size/M, approved, lgtm, ci-passed, dco-passed, area/compilation

#40350 fix: compaction task cannot be genereted if size greater than max size
  internal/datacoord/compaction_trigger.go
  internal/datacoord/compaction_trigger_test.go
  internal/datacoord/knapsack.go
  internal/datacoord/task_scheduler_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#40232 enhance: add more metrics for async cgo component
  internal/core/src/futures/Executor.cpp
  internal/core/src/futures/Future.h
  internal/core/src/futures/future_c.cpp
  internal/core/src/monitor/prometheus_client.cpp
  internal/core/src/monitor/prometheus_client.h
Labels: kind/enhancement, area/monitoring, size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#40330 fix: [2.5] Add duplication param check for create index (#40254)
  internal/proxy/task_index.go
  internal/proxy/task_index_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#40303 test: Add search iterator with external filter func neg tests
  tests/python_client/base/client_v2_base.py
  tests/python_client/check/func_check.py
  tests/python_client/milvus_client/test_milvus_client_alias.py
  tests/python_client/milvus_client/test_milvus_client_search_interator.py
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/XL, approved, lgtm, area/test, ci-passed, dco-passed, python, kind/test

#39663 feat: storage v2 sync
  internal/datacoord/mock_segment_manager.go
  internal/datacoord/segment_manager.go
  internal/datacoord/segment_manager_test.go
  internal/datacoord/services.go
  internal/datacoord/services_test.go
  internal/flushcommon/metacache/segment.go
  internal/flushcommon/syncmgr/options.go
  internal/flushcommon/syncmgr/pack_writer_v2.go
  internal/flushcommon/syncmgr/pack_writer_v2_test.go
  internal/flushcommon/syncmgr/task.go
  internal/flushcommon/syncmgr/task_test.go
  internal/flushcommon/writebuffer/l0_write_buffer.go
  internal/flushcommon/writebuffer/manager.go
  internal/flushcommon/writebuffer/manager_test.go
  internal/flushcommon/writebuffer/mock_manager.go
  internal/flushcommon/writebuffer/mock_write_buffer.go
  internal/flushcommon/writebuffer/options.go
  internal/flushcommon/writebuffer/write_buffer.go
  internal/storage/rw.go
  internal/storage/serde_events_v2.go
  internal/storagev2/packed/constant.go
  internal/streamingnode/server/flusher/flusherimpl/msg_handler_impl.go
  internal/streamingnode/server/server.go
  internal/streamingnode/server/wal/interceptors/segment/manager/partition_manager.go
  internal/streamingnode/server/wal/interceptors/segment/manager/pchannel_manager_test.go
  internal/streamingnode/server/wal/interceptors/segment/manager/segment_manager.go
  pkg/proto/data_coord.proto
  pkg/proto/datapb/data_coord.pb.go
  pkg/proto/messages.proto
  pkg/proto/messagespb/messages.pb.go
  pkg/proto/streaming.proto
  pkg/proto/streamingpb/streaming.pb.go
Labels: kind/feature, area/dependency, size/XXL, approved, lgtm, ci-passed, area/internal-api, dco-passed, area/compilation

#40333 fix: [2.5] Fix parsing import endTs
  internal/util/importutilv2/option.go
  internal/util/importutilv2/option_test.go
  pkg/util/tsoutil/tso.go
  pkg/util/tsoutil/tso_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#40334 fix: [2.4] Fix parsing import endTs
  internal/util/importutilv2/option.go
  internal/util/importutilv2/option_test.go
  pkg/util/tsoutil/tso.go
  pkg/util/tsoutil/tso_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#40336 fix: Fix missing null or non-exist key in json index
  internal/core/src/index/JsonInvertedIndex.cpp
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#40359 test: update sdk version and test cases[2.5]
  tests/python_client/requirements.txt
  tests/python_client/testcases/test_collection.py
Labels: sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed, python, kind/test

#39863 enhance: Introduce batch subscription in msgdispatcher
  configs/milvus.yaml
  internal/datacoord/channel_manager.go
  internal/flushcommon/pipeline/data_sync_service_test.go
  internal/flushcommon/pipeline/flow_graph_dmstream_input_node.go
  internal/querynodev2/services_test.go
  internal/util/pipeline/stream_pipeline.go
  pkg/mq/msgdispatcher/client.go
  pkg/mq/msgdispatcher/client_test.go
  pkg/mq/msgdispatcher/dispatcher.go
  pkg/mq/msgdispatcher/dispatcher_test.go
  pkg/mq/msgdispatcher/manager.go
  pkg/mq/msgdispatcher/manager_test.go
  pkg/mq/msgdispatcher/mock_test.go
  pkg/mq/msgdispatcher/target.go
  pkg/mq/msgdispatcher/target_test.go
  pkg/mq/msgstream/mq_msgstream.go
  pkg/util/merr/errors.go
  pkg/util/merr/errors_test.go
  pkg/util/merr/utils.go
  pkg/util/paramtable/service_param.go
  pkg/util/paramtable/service_param_test.go
Labels: kind/enhancement, size/XXL, approved, lgtm, ci-passed, dco-passed

#40337 enhance: better logging for grpc resolver
  internal/streamingcoord/server/resource/resource.go
  internal/util/streamingutil/service/resolver/builder.go
  internal/util/streamingutil/service/resolver/builder_test.go
  internal/util/streamingutil/service/resolver/resolver_with_discoverer.go
  internal/util/streamingutil/service/resolver/resolver_with_discoverer_test.go
  internal/util/streamingutil/service/resolver/watch_based_grpc_resolver.go
  internal/util/streamingutil/service/resolver/watch_based_grpc_resolver_test.go
Labels: kind/enhancement, area/logging, size/M, approved, lgtm, ci-passed, dco-passed

#40338 enhance: better logging for grpc resolver
  internal/streamingcoord/server/resource/resource.go
  internal/util/streamingutil/service/resolver/builder.go
  internal/util/streamingutil/service/resolver/builder_test.go
  internal/util/streamingutil/service/resolver/resolver_with_discoverer.go
  internal/util/streamingutil/service/resolver/resolver_with_discoverer_test.go
  internal/util/streamingutil/service/resolver/watch_based_grpc_resolver.go
  internal/util/streamingutil/service/resolver/watch_based_grpc_resolver_test.go
Labels: kind/enhancement, area/logging, size/M, approved, lgtm, ci-passed, dco-passed

#40363 fix: fix concurrent issues in null offset
  internal/core/src/index/InvertedIndexTantivy.cpp
  internal/core/src/index/InvertedIndexTantivy.h
  internal/core/src/index/JsonInvertedIndex.cpp
  internal/core/src/index/TextMatchIndex.cpp
  internal/core/unittest/test_text_match.cpp
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#40376 enhance: Remove debug log in rg handler v2
  internal/distributed/proxy/httpserver/resource_group_handler_v2.go
Labels: kind/enhancement, area/logging, size/XS, approved, lgtm, ci-passed, dco-passed

#40378 fix: skip storage v2 unstable ut for now
  internal/storage/serde_events_v2_test.go
Labels: kind/bug, size/XS, approved, lgtm, dco-passed

#40373 enhance: [GoSDK] Add DescribeReplica API & sync rbac v2
  client/entity/resource_group.go
  client/milvusclient/rbac.go
  client/milvusclient/rbac_options.go
  client/milvusclient/rbac_test.go
  client/milvusclient/rbac_v2.go
  client/milvusclient/resource_group.go
  client/milvusclient/resource_group_option.go
  client/milvusclient/resource_group_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed, component/gosdk

#40304 fix: Fix a crash issue of bulkinsert
  internal/util/importutilv2/parquet/field_reader.go
  internal/util/importutilv2/parquet/util.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#40381 enhance: [GoSDK] support update ts caching policy
  client/entity/collection.go
  client/milvusclient/collection.go
  client/milvusclient/common.go
  client/milvusclient/common_test.go
  client/milvusclient/database_example_test.go
  client/milvusclient/write.go
  client/milvusclient/write_options.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed, component/gosdk

#40371 test: update test cases
  tests/_helm/values/nightly/distributed-kafka
  tests/_helm/values/nightly/distributed-pulsar
  tests/python_client/milvus_client/test_milvus_client_collection.py
  tests/python_client/milvus_client/test_milvus_client_query.py
  tests/python_client/milvus_client/test_milvus_client_search.py
  tests/python_client/testcases/test_collection.py
  tests/python_client/testcases/test_partition.py
  tests/python_client/testcases/test_utility.py
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, python, kind/test

#40362 test: update sdk version and test cases[2.4]
  tests/python_client/requirements.txt
  tests/python_client/testcases/test_collection.py
Labels: sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed, python, kind/test

#40379 test: update teardown collection after rename
  tests/python_client/base/client_v2_base.py
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed, python, kind/test

#40393 enhance: [2.5] Remove debug log in rg handler v2 (#40376)
  internal/distributed/proxy/httpserver/resource_group_handler_v2.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#40401 fix: [2.5] Pass Knapsnak ptr to avoid compact multiple times
  internal/datacoord/knapsack.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#40400 fix: Pass Knapsnak ptr to avoid compact multiple times
  internal/datacoord/knapsack.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#40377 fix: correct memory size estimation on arrays
  internal/storage/serde.go
  internal/storage/serde_events.go
  internal/storage/serde_events_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed, go

#39921 fix: Skip loading primary key if index has raw data
  internal/core/src/segcore/ChunkedSegmentSealedImpl.cpp
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed, component/querynode

#40399 enhance: [2.5]upgrade go toolchain to 1.22.7, remove unnecessary binary
  build/docker/milvus/amazonlinux2023/Dockerfile
  build/docker/milvus/gpu/ubuntu20.04/Dockerfile
  build/docker/milvus/gpu/ubuntu22.04/Dockerfile
  build/docker/milvus/rockylinux8/Dockerfile
  build/docker/milvus/ubuntu20.04/Dockerfile
  build/docker/milvus/ubuntu22.04/Dockerfile
  go.mod
Labels: kind/enhancement, area/dependency, area/deployment, size/S, approved, lgtm, ci-passed, dco-passed, go

#40398 enhance: [skip e2e] upgrade go toolchain to 1.22.7, remove unnecessary binary
  build/docker/milvus/amazonlinux2023/Dockerfile
  build/docker/milvus/gpu/ubuntu20.04/Dockerfile
  build/docker/milvus/gpu/ubuntu22.04/Dockerfile
  build/docker/milvus/rockylinux8/Dockerfile
  build/docker/milvus/ubuntu20.04/Dockerfile
  build/docker/milvus/ubuntu22.04/Dockerfile
  go.mod
Labels: kind/enhancement, area/dependency, area/deployment, size/S, approved, lgtm, ci-passed, dco-passed, go

#40417 enhance: [GoSDK] Support alter/drop index properties
  client/milvusclient/index.go
  client/milvusclient/index_options.go
  client/milvusclient/index_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed, component/gosdk

#40434 enhance: [2.5][GoSDK] Support index properties API & bump version
  client/common/version.go
  client/milvusclient/index.go
  client/milvusclient/index_options.go
  client/milvusclient/index_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed, go, PR | need cherry-pick, component/gosdk

#40447 enhance: [2.5]Only check element type with not null array
  internal/core/src/index/InvertedIndexTantivy.cpp
Labels: kind/enhancement, size/XS, dco-passed

#40449 fix: [2.5] Skip executing stats for zero segment
  internal/datacoord/task_scheduler_test.go
  internal/datacoord/task_stats.go
  internal/indexnode/task_stats.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#40443 fix: [GoSDK] move metaheader to client in case of race
  client/entity/field.go
  client/milvusclient/client.go
  client/milvusclient/client_config.go
  client/milvusclient/interceptors.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, needs-dco, component/gosdk

#40453 fix: [2.5]store wrong offset when build tantivy in nullable field
  internal/core/src/index/InvertedIndexTantivy.cpp
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#40457 fix: Null expr does not work for json field
  internal/core/src/mmap/ChunkedColumn.h
  internal/core/src/segcore/ChunkedSegmentSealedImpl.cpp
  internal/core/src/storage/ChunkCache.cpp
Labels: kind/bug, size/M, approved, lgtm, dco-passed

#40433 fix:array corrupt for ignoring validity(#40384)
  internal/core/src/common/Array.h
  tests/_helm/values/e2e/standalone-kafka-mmap
Labels: kind/bug, sig/testing, size/S, approved, lgtm, area/test, dco-passed, do-not-merge/missing-related-pr

#40479 doc: json storage format
  docs/design_docs/json_storage.md
Labels: size/L, approved, lgtm, ci-passed, kind/developer-doc, dco-passed, kind/doc

#40452 fix: store wrong offset when build tantivy in nullable field
  internal/core/src/index/InvertedIndexTantivy.cpp
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#40448 fix: Skip executing stats for zero segment
  internal/datacoord/task_scheduler_test.go
  internal/datacoord/task_stats.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#40482 fix: rockmq race condition
  pkg/mq/mqimpl/rocksmq/server/rocksmq_impl.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#40074 enhance: Replace currRows with NumOfRows
  internal/datacoord/compaction_test.go
  internal/datacoord/import_util.go
  internal/datacoord/import_util_test.go
  internal/datacoord/index_service_test.go
  internal/datacoord/meta.go
  internal/datacoord/meta_test.go
  internal/datacoord/segment_allocation_policy.go
  internal/datacoord/segment_allocation_policy_test.go
  internal/datacoord/segment_info.go
  internal/datacoord/segment_manager.go
  internal/datacoord/segment_manager_test.go
  internal/datacoord/server.go
  internal/datacoord/server_test.go
  internal/datacoord/services.go
  internal/datacoord/services_test.go
  internal/flushcommon/broker/broker.go
  internal/flushcommon/broker/datacoord.go
  internal/flushcommon/broker/datacoord_test.go
  internal/flushcommon/broker/mock_broker.go
  internal/flushcommon/pipeline/data_sync_service_test.go
  internal/flushcommon/pipeline/testutils_test.go
  pkg/proto/data_coord.proto
  pkg/proto/datapb/data_coord_grpc.pb.go
Labels: kind/enhancement, kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed, kind/test

#40445 test: Add test cases for part of json path index
  tests/python_client/base/client_v2_base.py
  tests/python_client/check/func_check.py
  tests/python_client/common/common_type.py
  tests/python_client/milvus_client/test_milvus_client_collection.py
  tests/python_client/milvus_client/test_milvus_client_compact.py
  tests/python_client/milvus_client/test_milvus_client_database.py
  tests/python_client/milvus_client/test_milvus_client_hybrid_search.py
  tests/python_client/milvus_client/test_milvus_client_index.py
  tests/python_client/milvus_client/test_milvus_client_insert.py
  tests/python_client/milvus_client/test_milvus_client_search.py
  tests/python_client/requirements.txt
  tests/python_client/testcases/test_index.py
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/XXL, approved, lgtm, area/test, ci-passed, dco-passed, python, kind/test

#40414 enhance: [2.5] Avoid convert body byte slice to string in httpserver (#40405)
  internal/distributed/proxy/httpserver/handler_v1.go
  internal/distributed/proxy/httpserver/handler_v2.go
  internal/distributed/proxy/httpserver/utils.go
  internal/distributed/proxy/httpserver/utils_test.go
Labels: kind/enhancement, area/performance, size/M, approved, lgtm, ci-passed, dco-passed

#40315 enhance: Log start position of delete msgs
  internal/flushcommon/pipeline/flow_graph_dd_node.go
  internal/flushcommon/pipeline/flow_graph_dd_node_test.go
Labels: kind/enhancement, area/logging, size/S, approved, lgtm, ci-passed, dco-passed

#40498 enhance: Automatically Close Knowhere Automated PRs
  .github/workflows/update-knowhere-commit.yaml
Labels: kind/enhancement, area/knowhere, size/S, approved, lgtm, dco-passed, github_actions

#40505 enhance: Add channel seal policy based on blocking l0
  configs/milvus.yaml
  internal/datacoord/segment_allocation_policy.go
  internal/datacoord/segment_allocation_policy_test.go
  internal/datacoord/segment_manager.go
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#40394 enhance: Use correct counter metrics for overall wa calculation
  internal/datanode/compactor/executor.go
  internal/flushcommon/syncmgr/task.go
  pkg/metrics/datanode_metrics.go
  pkg/metrics/metrics.go
Labels: kind/enhancement, kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#40332 fix: Fix parsing import endTs
  internal/util/importutilv2/option.go
  internal/util/importutilv2/option_test.go
  pkg/util/tsoutil/tso.go
  pkg/util/tsoutil/tso_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed, go

#40499 enhance: Truly support multi vector data types in SearchBruteForce
  internal/core/src/query/SearchBruteForce.cpp
Labels: kind/enhancement, kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#40510 fix: add collection flush before sparse searching in pytest
  tests/python_client/testcases/test_search.py
Labels: kind/bug, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed, python, kind/branch-feature, kind/test

#40522 fix: add collection flush before sparse searching in pytest
  tests/python_client/testcases/test_search.py
Labels: kind/bug, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed, python, kind/test

#40358 feat: Add function running monitoring
  internal/proxy/task_insert.go
  internal/proxy/task_search.go
  internal/proxy/task_test.go
  internal/proxy/task_upsert.go
  internal/proxy/util.go
  internal/proxy/util_test.go
  internal/util/function/ali_embedding_provider.go
  internal/util/function/alitext_embedding_provider_test.go
  internal/util/function/bedrock_embedding_provider.go
  internal/util/function/bedrock_text_embedding_provider_test.go
  internal/util/function/cohere_embedding_provider.go
  internal/util/function/cohere_embedding_provider_test.go
  internal/util/function/common.go
  internal/util/function/function_base.go
  internal/util/function/function_executor.go
  internal/util/function/function_executor_test.go
  internal/util/function/mock_embedding_service.go
  internal/util/function/models/ali/ali_dashscope_text_embedding.go
  internal/util/function/models/cohere/cohere_text_embedding.go
  internal/util/function/models/openai/openai_embedding.go
  internal/util/function/models/openai/openai_embedding_test.go
  internal/util/function/models/siliconflow/siliconflow_text_embedding.go
  internal/util/function/models/tei/tei.go
  internal/util/function/models/utils/embedding_util.go
  internal/util/function/models/vertexai/vertexai_text_embedding.go
  internal/util/function/models/voyageai/voyageai_text_embedding.go
  internal/util/function/models/voyageai/voyageai_text_embedding_test.go
  internal/util/function/openai_embedding_provider.go
  internal/util/function/siliconflow_embedding_provider.go
  internal/util/function/siliconflow_embedding_provider_test.go
  internal/util/function/text_embedding_function.go
  internal/util/function/text_embedding_function_test.go
  internal/util/function/vertexai_embedding_provider.go
  internal/util/function/vertexai_embedding_provider_test.go
  internal/util/function/voyageai_embedding_provider.go
  internal/util/function/voyageai_embedding_provider_test.go
  pkg/metrics/metrics.go
  pkg/metrics/proxy_metrics.go
Labels: kind/feature, area/monitoring, size/XL, approved, lgtm, ci-passed, dco-passed

#39387 fix: rocksmq consumer register not concurrent safe
  pkg/mq/mqimpl/rocksmq/client/client_impl.go
  pkg/mq/mqimpl/rocksmq/server/rocksmq_impl.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#40462 fix: Add duplicated type/index params check creating collection
  internal/rootcoord/create_collection_task.go
  internal/rootcoord/create_collection_task_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed, component/rootcoord

#40465 fix: [2.5] Add duplicated type/index params check creating collection
  internal/rootcoord/create_collection_task.go
  internal/rootcoord/create_collection_task_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed, component/rootcoord, PR | need cherry-pick

#40470 fix: [skip e2e] wab unittest may failure
  internal/streamingnode/server/wal/interceptors/wab/write_ahead_buffer_test.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#40407 enhance: add json path escape and replace $meta with dynamic field name
  internal/datacoord/index_service.go
  internal/proxy/task_index.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#40422 fix: Fix channel not balance on datanodes
  internal/datacoord/channel_manager.go
  internal/datacoord/channel_manager_test.go
  internal/datacoord/policy.go
  internal/datacoord/policy_test.go
  pkg/mq/msgdispatcher/client.go
  pkg/mq/msgdispatcher/client_test.go
  pkg/mq/msgdispatcher/manager.go
  pkg/mq/msgdispatcher/manager_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed, PR | need cherry-pick

#40446 enhance: Only check element type with not null array
  internal/core/src/index/InvertedIndexTantivy.cpp
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#40538 enhance: Upgrade simdjson version
  internal/core/thirdparty/simdjson/CMakeLists.txt
Labels: kind/enhancement, area/dependency, size/XS, approved, lgtm, ci-passed, dco-passed, area/compilation

#40536 enhance: [2.5] Fix Array.h clang format issue
  internal/core/src/common/Array.h
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed, kind/branch-feature

#40549 fix: ref collection for search/query
  internal/querynodev2/handlers.go
  internal/querynodev2/services.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed, component/querynode

#40556 fix: [2.4] rbac star privilege return empty when listing policy
  internal/metastore/kv/rootcoord/kv_catalog.go
  internal/metastore/kv/rootcoord/kv_catalog_test.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed, component/rootcoord, PR | need cherry-pick

#40555 fix: msgstream adaptor may not gc quickly after comsumed
  pkg/util/typeutil/multipart_queue.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#40553 fix: rbac star privilege return empty when listing policy
  internal/metastore/kv/rootcoord/kv_catalog.go
  internal/metastore/kv/rootcoord/kv_catalog_test.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed, component/rootcoord

#40597 enhance: [2.5] Improve import error msgs
  internal/util/importutilv2/common/util.go
  internal/util/importutilv2/csv/row_parser.go
  internal/util/importutilv2/json/reader.go
  internal/util/importutilv2/json/row_parser.go
  internal/util/importutilv2/json/row_parser_test.go
  internal/util/importutilv2/numpy/field_reader.go
  internal/util/importutilv2/parquet/field_reader.go
Labels: kind/enhancement, kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#40366 fix: use correct delete checkpoint to prevent premature data cleanup
  internal/datacoord/handler.go
  internal/datacoord/handler_test.go
  internal/datacoord/services.go
  internal/querycoordv2/meta/target.go
  internal/querycoordv2/observers/target_observer_test.go
  internal/querynodev2/delegator/delegator_data.go
  internal/querynodev2/services.go
  pkg/proto/query_coord.proto
  pkg/proto/querypb/query_coord.pb.go
Labels: kind/bug, size/XXL, approved, lgtm, ci-passed, area/internal-api, dco-passed, component/querynode

#40586 fix: [2.5] empty row for sparse vector
  internal/util/importutilv2/csv/row_parser_test.go
  internal/util/importutilv2/parquet/field_reader.go
  internal/util/importutilv2/parquet/file_reader_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#40612 fix: [2.5] empty row for sparse vector (#40586)
  internal/util/importutilv2/csv/row_parser_test.go
  internal/util/importutilv2/parquet/field_reader.go
  internal/util/importutilv2/parquet/file_reader_test.go
Labels: kind/bug, size/L, approved, lgtm

#40602 fix: Fix QueryNodeNumEntities metric
  internal/querynodev2/metrics_info.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed, component/querynode

#40598 enhance: [2.4] Improve import error msgs
  internal/util/importutilv2/common/util.go
  internal/util/importutilv2/json/reader.go
  internal/util/importutilv2/json/row_parser.go
  internal/util/importutilv2/json/row_parser_test.go
  internal/util/importutilv2/numpy/field_reader.go
  internal/util/importutilv2/parquet/field_reader.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#40440 enhance: move object storage client creation to pkg package
  go.mod
  internal/datacoord/compaction_task_clustering_test.go
  internal/datanode/data_node_test.go
  internal/datanode/services_test.go
  internal/flushcommon/io/binlog_io_test.go
  internal/flushcommon/pipeline/data_sync_service_test.go
  internal/flushcommon/syncmgr/pack_writer_v2_test.go
  internal/indexnode/chunk_mgr_factory.go
  internal/mocks/util/mock_segcore/mock_data.go
  internal/querynodev2/handlers_test.go
  internal/querynodev2/server_test.go
  internal/storage/azure_object_storage.go
  internal/storage/azure_object_storage_test.go
  internal/storage/factory.go
  internal/storage/gcp_native_object_storage.go
  internal/storage/gcp_native_object_storage_test.go
  internal/storage/local_chunk_manager.go
  internal/storage/local_chunk_manager_test.go
  internal/storage/minio_object_storage.go
  internal/storage/minio_object_storage_test.go
  internal/storage/options.go
  internal/storage/remote_chunk_manager.go
  internal/storage/remote_chunk_manager_test.go
  internal/storage/utils.go
  internal/util/dependency/factory.go
  internal/util/importutilv2/csv/reader_test.go
  internal/util/importutilv2/parquet/reader_test.go
  pkg/go.mod
  pkg/go.sum
  pkg/objectstorage/aliyun/aliyun.go
  pkg/objectstorage/aliyun/aliyun_test.go
  pkg/objectstorage/aliyun/mocks/Credential.go
  pkg/objectstorage/gcp/gcp.go
  pkg/objectstorage/gcp/gcp_test.go
  pkg/objectstorage/options.go
  pkg/objectstorage/tencent/tencent.go
  pkg/objectstorage/tencent/tencent_test.go
  pkg/objectstorage/util.go
Labels: kind/enhancement, area/dependency, size/XXL, approved, lgtm, ci-passed, dco-passed, go

#40600 fix: [2.5.6] rbac star privilege return empty when listing policy
  internal/core/src/common/Array.h
  internal/metastore/kv/rootcoord/kv_catalog.go
  internal/metastore/kv/rootcoord/kv_catalog_test.go
Labels: size/S, approved, lgtm, component/rootcoord, PR | need cherry-pick

#40594 enhance: [2.4] Remove unnecessary collection and partition label from the metrics
  internal/datacoord/compaction_task_clustering.go
  internal/datacoord/import_checker.go
  internal/datacoord/import_checker_test.go
  internal/datanode/stats_updater.go
  internal/querynodev2/metrics_info.go
  internal/querynodev2/segments/manager.go
  internal/querynodev2/services_test.go
  pkg/metrics/datacoord_metrics.go
  pkg/metrics/datanode_metrics.go
  pkg/metrics/metrics.go
  pkg/metrics/querynode_metrics.go
Labels: kind/enhancement, kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#40542 fix: [2.5] avoid panic when field not exists in schema in query node
  internal/core/src/query/PlanImpl.h
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed, component/querynode, PR | need cherry-pick

#40605 fix: Fix null offset loading in inverted index (#40523)
  internal/core/src/index/InvertedIndexTantivy.cpp
Labels: kind/bug, size/L, approved, lgtm, ci-passed, manual-pass

#40541 fix: avoid panic when field not exists in schema in query node
  internal/core/src/query/PlanImpl.h
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed, component/querynode

#40557 fix: [2.5] rbac star privilege return empty when listing policy
  internal/metastore/kv/rootcoord/kv_catalog.go
  internal/metastore/kv/rootcoord/kv_catalog_test.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed, component/rootcoord, PR | need cherry-pick

#40585 fix: empty sparse row in importer
  internal/util/importutilv2/csv/row_parser_test.go
  internal/util/importutilv2/parquet/field_reader.go
  internal/util/importutilv2/parquet/file_reader_test.go
Labels: kind/bug, size/L, approved, lgtm, dco-passed

#40606 fix: too many memory usage of streaming node
  internal/distributed/streamingnode/service.go
  internal/streamingnode/server/builder.go
  internal/streamingnode/server/flusher/flusherimpl/flusher_components.go
  internal/streamingnode/server/flusher/flusherimpl/wal_flusher.go
  internal/streamingnode/server/flusher/flusherimpl/wal_flusher_test.go
  internal/streamingnode/server/resource/resource.go
  internal/streamingnode/server/resource/resource_test.go
  internal/streamingnode/server/resource/test_utility.go
  internal/streamingnode/server/server.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#40593 enhance: [2.5] Remove unnecessary collection and partition label from the metrics
  internal/datacoord/compaction_task_clustering.go
  internal/datacoord/import_checker.go
  internal/datacoord/import_checker_test.go
  internal/querynodev2/metrics_info.go
  internal/querynodev2/segments/manager.go
  internal/querynodev2/services_test.go
  pkg/metrics/datacoord_metrics.go
  pkg/metrics/datanode_metrics.go
  pkg/metrics/metrics.go
  pkg/metrics/querynode_metrics.go
Labels: kind/enhancement, kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#40133 enhance: API integration with storage v2 in clustering-compactions
  internal/compaction/common.go
  internal/datacoord/compaction_task_clustering.go
  internal/datacoord/compaction_trigger_v2.go
  internal/datacoord/task_scheduler_test.go
  internal/datanode/compactor/clustering_compactor.go
  internal/datanode/compactor/clustering_compactor_test.go
  internal/datanode/compactor/compactor_common.go
  internal/datanode/compactor/l0_compactor.go
  internal/datanode/compactor/merge_sort.go
  internal/datanode/compactor/mix_compactor.go
  internal/datanode/compactor/segment_writer.go
  internal/flushcommon/syncmgr/storage_serializer.go
  internal/querynodev2/segments/segment_loader.go
  internal/storage/rw_test.go
  internal/storage/serde.go
  internal/storage/serde_events.go
  internal/storage/serde_events_test.go
  internal/storage/serde_events_v2.go
  internal/storage/serde_events_v2_test.go
  internal/storage/serde_test.go
  internal/storage/sort.go
  internal/storage/stats.go
  internal/storagev2/packed/packed_reader.go
  internal/util/importutilv2/binlog/l0_reader.go
  tests/integration/compaction/clustering_compaction_null_data_test.go
Labels: kind/enhancement, sig/testing, area/api, size/XXL, approved, lgtm, area/test, ci-passed, dco-passed, test/integration

#40352 test: add cases for go client rbac APIs
  client/entity/rbac.go
  client/milvusclient/rbac.go
  client/milvusclient/rbac_options.go
  client/milvusclient/rbac_test.go
  tests/go_client/base/milvus_client.go
  tests/go_client/common/consts.go
  tests/go_client/common/utils.go
  tests/go_client/testcases/advcases/rbac_test.go
  tests/go_client/testcases/helper/test_setup.go
Labels: sig/testing, size/XL, approved, lgtm, area/test, ci-passed, dco-passed, manual-pass, go, kind/test, component/gosdk

#40459 enhance: Remove CPU profile to prevent blocking stop progress
  cmd/components/util.go
Labels: kind/enhancement, area/performance, size/M, approved, lgtm, ci-passed, dco-passed

#40630 doc: Add README for go milvusclient
  client/README.md
Labels: kind/user-doc, size/M, approved, lgtm, ci-passed, dco-passed, kind/doc

#40626 fix: Catch invalid json pointer error
  internal/core/src/index/JsonInvertedIndex.cpp
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#40589 fix: backoff will retry infinitely after reaching max elapse
  internal/distributed/streaming/internal/consumer/consumer_impl.go
  internal/distributed/streaming/internal/producer/producer.go
  internal/rootcoord/dml_channels.go
  internal/streamingnode/client/handler/handler_client_impl.go
  internal/streamingnode/server/flusher/flusherimpl/pchannel_checkpoint.go
  internal/util/streamingutil/service/lazygrpc/conn.go
  pkg/util/typeutil/backoff_timer.go
  pkg/util/typeutil/backoff_timer_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed, go

#40623 feature: add a prefix on environment config
  pkg/config/env_source.go
Labels: kind/feature, size/S, approved, lgtm, ci-passed, dco-passed, go, do-not-merge/invalid-pr-format

#40353 enhance: [2.5] Refine task meta with key lock
  internal/datacoord/compaction_trigger_test.go
  internal/datacoord/garbage_collector_test.go
  internal/datacoord/index_meta.go
  internal/datacoord/index_meta_test.go
  internal/datacoord/index_service_test.go
  internal/datacoord/job_manager_test.go
  internal/datacoord/metrics_info_test.go
  internal/datacoord/stats_task_meta.go
  internal/datacoord/stats_task_meta_test.go
  internal/datacoord/task_scheduler.go
  internal/datacoord/task_scheduler_test.go
  internal/datacoord/task_stats.go
  internal/datacoord/task_stats_test.go
  internal/indexnode/task_scheduler.go
Labels: kind/enhancement, kind/improvement, size/XXL, approved, lgtm, ci-passed, dco-passed

#40567 enhance: Improve import error msgs
  internal/util/importutilv2/common/util.go
  internal/util/importutilv2/csv/row_parser.go
  internal/util/importutilv2/json/reader.go
  internal/util/importutilv2/json/row_parser.go
  internal/util/importutilv2/json/row_parser_test.go
  internal/util/importutilv2/numpy/field_reader.go
  internal/util/importutilv2/parquet/field_reader.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#40634 enhance: add metrics for random sample
  internal/core/src/exec/operator/RandomSampleNode.cpp
  internal/core/src/monitor/prometheus_client.cpp
  internal/core/src/monitor/prometheus_client.h
Labels: kind/enhancement, area/monitoring, size/S, approved, lgtm, ci-passed, dco-passed

#40466 feat: [2.5] Support get segment binlogs info with new interface GetSegmentsInfo
  internal/distributed/proxy/client/client.go
  internal/distributed/proxy/client/client_test.go
  internal/distributed/proxy/httpserver/constant.go
  internal/distributed/proxy/httpserver/handler_v2.go
  internal/distributed/proxy/httpserver/handler_v2_test.go
  internal/distributed/proxy/httpserver/request_v2.go
  internal/distributed/proxy/service.go
  internal/mocks/mock_proxy.go
  internal/mocks/mock_proxy_client.go
  internal/mocks/mock_rootcoord.go
  internal/proxy/impl.go
  internal/proxy/impl_test.go
  internal/proxy/proxy_test.go
  pkg/proto/internal.proto
  pkg/proto/internalpb/internal.pb.go
  pkg/proto/proxy.proto
  pkg/proto/proxypb/proxy.pb.go
  pkg/proto/proxypb/proxy_grpc.pb.go
Labels: kind/feature, size/XXL, approved, lgtm, ci-passed, area/internal-api, dco-passed, go

#40535 enhance: [2.5] Add channel seal policy based on blocking l0 (#40505)
  configs/milvus.yaml
  internal/datacoord/segment_allocation_policy.go
  internal/datacoord/segment_allocation_policy_test.go
  internal/datacoord/segment_manager.go
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#40591 enhance: add walimpls access mode options
  pkg/proto/streaming.proto
  pkg/proto/streamingpb/streaming.pb.go
  pkg/streaming/util/types/pchannel_info.go
  pkg/streaming/walimpls/helper/wal_helper.go
  pkg/streaming/walimpls/helper/wal_helper_test.go
  pkg/streaming/walimpls/impls/kafka/opener.go
  pkg/streaming/walimpls/impls/kafka/wal.go
  pkg/streaming/walimpls/impls/pulsar/opener.go
  pkg/streaming/walimpls/impls/pulsar/wal.go
  pkg/streaming/walimpls/impls/rmq/opener.go
  pkg/streaming/walimpls/impls/rmq/wal.go
  pkg/streaming/walimpls/impls/walimplstest/opener.go
  pkg/streaming/walimpls/impls/walimplstest/wal.go
  pkg/streaming/walimpls/opener.go
  pkg/streaming/walimpls/test_framework.go
  pkg/streaming/walimpls/wal.go
Labels: kind/enhancement, size/XXL, approved, lgtm, ci-passed, area/internal-api, dco-passed, feature/streaming node

#40653 feat: [2.5] add DDLDB rate type and related quota configurations
  configs/milvus.yaml
  internal/proxy/rate_limit_interceptor.go
  internal/proxy/rate_limit_interceptor_test.go
  internal/proxy/simple_rate_limiter.go
  internal/proxy/simple_rate_limiter_test.go
  internal/proxy/util.go
  internal/rootcoord/quota_center.go
  internal/rootcoord/quota_center_test.go
  internal/util/quota/quota_constant.go
  internal/util/quota/quota_constant_test.go
  pkg/proto/internal.proto
  pkg/proto/internalpb/internal.pb.go
  pkg/util/paramtable/quota_param.go
  pkg/util/paramtable/quota_param_test.go
Labels: kind/feature, size/L, approved, lgtm, ci-passed, area/internal-api, dco-passed

#40654 feat: [2.4] add DDLDB rate type and related quota configurations
  configs/milvus.yaml
  internal/proxy/rate_limit_interceptor.go
  internal/proxy/rate_limit_interceptor_test.go
  internal/proxy/simple_rate_limiter.go
  internal/proxy/simple_rate_limiter_test.go
  internal/proxy/util.go
  internal/rootcoord/quota_center.go
  internal/rootcoord/quota_center_test.go
  internal/util/quota/quota_constant.go
  internal/util/quota/quota_constant_test.go
  pkg/proto/internal.proto
  pkg/proto/internalpb/internal.pb.go
  pkg/util/paramtable/quota_param.go
  pkg/util/paramtable/quota_param_test.go
Labels: kind/feature, size/L, approved, lgtm, ci-passed, area/internal-api, dco-passed

#40651 feat: add DDLDB rate type and related quota configurations
  configs/milvus.yaml
  internal/proxy/rate_limit_interceptor.go
  internal/proxy/rate_limit_interceptor_test.go
  internal/proxy/simple_rate_limiter.go
  internal/proxy/simple_rate_limiter_test.go
  internal/proxy/util.go
  internal/rootcoord/quota_center.go
  internal/rootcoord/quota_center_test.go
  internal/util/quota/quota_constant.go
  internal/util/quota/quota_constant_test.go
  pkg/proto/internal.proto
  pkg/proto/internalpb/internal.pb.go
  pkg/util/paramtable/quota_param.go
  pkg/util/paramtable/quota_param_test.go
Labels: kind/feature, size/L, approved, lgtm, ci-passed, area/internal-api, dco-passed, go

#40613 enhance: Refine task meta with key lock
  internal/datacoord/compaction_trigger_test.go
  internal/datacoord/garbage_collector_test.go
  internal/datacoord/index_meta.go
  internal/datacoord/index_meta_test.go
  internal/datacoord/index_service_test.go
  internal/datacoord/job_manager_test.go
  internal/datacoord/metrics_info_test.go
  internal/datacoord/stats_task_meta.go
  internal/datacoord/stats_task_meta_test.go
  internal/datacoord/task_analyze.go
  internal/datacoord/task_index.go
  internal/datacoord/task_scheduler.go
  internal/datacoord/task_scheduler_test.go
  internal/datacoord/task_stats.go
  internal/datacoord/task_stats_test.go
  internal/datacoord/types.go
  internal/datanode/index/scheduler.go
  pkg/metrics/datacoord_metrics.go
  pkg/metrics/metrics.go
  pkg/metrics/proxy_metrics.go
  pkg/metrics/querycoord_metrics.go
Labels: kind/enhancement, size/XXL, approved, lgtm, ci-passed, dco-passed

#40456 fix: Null expr does not work for json field
  internal/core/src/mmap/ChunkedColumn.h
  internal/core/src/segcore/ChunkedSegmentSealedImpl.cpp
  internal/core/src/storage/ChunkCache.cpp
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#40632 enhance: [2.5] make segment prune config refreshable
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed, go

#40633 enhance: [2.4] make segment prune config refreshable
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#39819 Revert "fix:reset default auto index type for scalar (#37086)"
  internal/proxy/task_index_test.go
  pkg/util/paramtable/autoindex_param.go
Labels: size/S, approved, lgtm, ci-passed, dco-passed, do-not-merge/invalid-pr-format

#40611 fix: json path should be empty string if it's root
  internal/datacoord/index_service.go
  internal/datacoord/index_service_test.go
  tests/python_client/milvus_client/test_milvus_client_index.py
Labels: kind/bug, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed, go

#40619 fix: Build double index for all json numeric field
  internal/core/src/exec/expression/TermExpr.cpp
  internal/core/src/exec/expression/UnaryExpr.cpp
  internal/core/src/index/IndexFactory.cpp
  internal/core/src/segcore/SegmentSealed.h
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#40625 fix: Catch invalid json pointer error
  internal/core/src/index/JsonInvertedIndex.cpp
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#40331 fix: Fix a crash issue of bulkinsert
  internal/util/importutilv2/parquet/field_reader.go
  internal/util/importutilv2/parquet/util.go
Labels: kind/bug, severity/critical, size/M, approved, lgtm, ci-passed, dco-passed

#40524 fix: Fix null offset loading in inverted index
  internal/core/src/index/InvertedIndexTantivy.cpp
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#40658 enhance: add GetService method to retrieve MilvusServiceClient
  client/milvusclient/client.go
Labels: kind/enhancement, kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#40648 fix: fix json index not-equal filter
  internal/core/src/common/JsonCastType.h
  internal/core/src/index/IndexFactory.cpp
  internal/core/src/index/IndexFactory.h
  internal/core/src/index/IndexInfo.h
  internal/core/src/index/JsonInvertedIndex.cpp
  internal/core/src/indexbuilder/ScalarIndexCreator.cpp
  internal/core/src/segcore/load_index_c.cpp
  internal/core/unittest/test_expr.cpp
  internal/datacoord/index_service_test.go
  internal/proxy/task_index.go
  internal/proxy/task_index_test.go
  internal/util/indexparamcheck/inverted_checker.go
  internal/util/indexparamcheck/inverted_checker_test.go
  tests/python_client/testcases/test_index.py
Labels: kind/bug, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#40671 enhance: Record simdjson error
  internal/core/src/index/JsonInvertedIndex.cpp
  internal/core/src/index/JsonInvertedIndex.h
  internal/core/unittest/CMakeLists.txt
  internal/core/unittest/test_json_index.cpp
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed, area/compilation

#40464 feat: Support get segment binlogs info with new interface GetSegmentsInfo
  internal/distributed/proxy/client/client.go
  internal/distributed/proxy/client/client_test.go
  internal/distributed/proxy/httpserver/constant.go
  internal/distributed/proxy/httpserver/handler_v2.go
  internal/distributed/proxy/httpserver/handler_v2_test.go
  internal/distributed/proxy/httpserver/request_v2.go
  internal/distributed/proxy/service.go
  internal/mocks/mock_proxy.go
  internal/mocks/mock_proxy_client.go
  internal/proxy/impl.go
  internal/proxy/impl_test.go
  internal/proxy/proxy_test.go
  pkg/proto/internal.proto
  pkg/proto/internalpb/internal.pb.go
  pkg/proto/proxy.proto
  pkg/proto/proxypb/proxy.pb.go
  pkg/proto/proxypb/proxy_grpc.pb.go
Labels: kind/feature, size/XXL, approved, lgtm, ci-passed, area/internal-api, dco-passed, go

#40618 enhance: refine chunk access logic and add some comment on data
  internal/core/src/common/Chunk.h
  internal/core/src/common/ChunkWriter.h
  internal/core/src/mmap/ChunkedColumn.h
  internal/core/unittest/test_cached_search_iterator.cpp
  internal/core/unittest/test_chunk.cpp
  internal/core/unittest/test_chunked_segment.cpp
Labels: kind/enhancement, kind/improvement, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#40643 enhance: [skip e2e][GoSDK] Add client example for common usage
  client/milvusclient/index_example_test.go
  client/milvusclient/maintenance_example_test.go
  client/milvusclient/read_example_test.go
  client/milvusclient/resource_group_example_test.go
  client/milvusclient/write_example_test.go
Labels: kind/enhancement, size/XL, approved, lgtm, ci-passed, dco-passed, manual-pass, component/gosdk

#40678 enhance: [25]Log start position of delete msgs (#40315)
  internal/flushcommon/pipeline/flow_graph_dd_node.go
  internal/flushcommon/pipeline/flow_graph_dd_node_test.go
Labels: kind/enhancement, kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#40679 enhance: Use correct counter metrics for overall wa calculation (#40394)
  internal/datanode/compaction/executor.go
  internal/flushcommon/syncmgr/task.go
  pkg/metrics/datanode_metrics.go
  pkg/metrics/metrics.go
Labels: kind/enhancement, area/monitoring, size/M, approved, lgtm, ci-passed, dco-passed

#40559 enhance: Add buffer forwarder for stream delta loading
  configs/milvus.yaml
  internal/querynodev2/delegator/buffered_forwarder.go
  internal/querynodev2/delegator/buffered_forwarder_test.go
  internal/querynodev2/delegator/delegator_data.go
  internal/querynodev2/delegator/deletebuffer/list_delete_buffer.go
  internal/querynodev2/delegator/delta_forward.go
  internal/querynodev2/delegator/delta_forward_test.go
  internal/querynodev2/services.go
  internal/querynodev2/services_test.go
  internal/storage/delta_data.go
  internal/storage/primary_keys.go
  pkg/proto/query_coord.proto
  pkg/proto/querypb/query_coord.pb.go
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/XXL, approved, lgtm, ci-passed, area/internal-api, dco-passed, component/querynode

#40695 enhance: improve documentation on large page size support
  DEVELOPMENT.md
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed, kind/doc

#40697 enhance: [skip e2e][mergify rule] Resolve go tests rule conflict
  .github/mergify.yml
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed, github_actions

#40415 feat: compaction to support add field
  .golangci.yml
  Makefile
  client/.golangci.yml
  internal/datanode/compactor/merge_sort.go
  internal/datanode/compactor/mix_compactor_test.go
  internal/datanode/compactor/segment_record_reader.go
  internal/datanode/compactor/segment_writer.go
  internal/storage/rw.go
  internal/storage/rw_test.go
  internal/storage/serde_events.go
  internal/storage/serde_events_test.go
  tests/go_client/.golangci.yml
Labels: kind/feature, sig/testing, size/XL, approved, lgtm, area/test, ci-passed, dco-passed, area/compilation

#40710 fix: Fix json test
  internal/core/unittest/test_json_index.cpp
Labels: kind/bug, test/ut, size/XS, approved, lgtm, dco-passed

#40703 fix: [2.4]Do not delete the centroids file when sampling fails instead wait GC
  internal/core/src/clustering/KmeansClustering.cpp
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#40546 fix: [2.5] avoid segmentation faults caused by retrieving empty vector datasets
  internal/core/src/index/VectorDiskIndex.cpp
  internal/core/src/index/VectorMemIndex.cpp
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#40683 test: [cherry-pick]add empty sparse in import test
  tests/python_client/common/bulk_insert_data.py
  tests/python_client/common/common_func.py
  tests/python_client/conftest.py
  tests/python_client/testcases/test_bulk_insert.py
Labels: sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed, python, PR | need cherry-pick, kind/test

#40503 enhance: remove redundant resource key watch operation, just keep consistency of wal
  internal/distributed/streaming/broadcast.go
  internal/distributed/streaming/streaming.go
  internal/distributed/streaming/streaming_test.go
  internal/distributed/streaming/wal_test.go
  internal/mocks/streamingcoord/client/mock_broadcast/mock_Watcher.go
  internal/mocks/streamingcoord/mock_client/mock_BroadcastService.go
  internal/mocks/streamingcoord/server/mock_broadcaster/mock_Watcher.go
  internal/rootcoord/broadcast_task.go
  internal/streamingcoord/client/broadcast/broadcast_impl.go
  internal/streamingcoord/client/broadcast/broadcast_test.go
  internal/streamingcoord/client/broadcast/grpc_watcher.go
  internal/streamingcoord/client/broadcast/grpc_watcher_test.go
  internal/streamingcoord/client/broadcast/watcher.go
  internal/streamingcoord/client/broadcast/watcher_resuming.go
  internal/streamingcoord/client/broadcast/watcher_resuming_test.go
  internal/streamingcoord/client/client.go
  internal/streamingcoord/server/broadcaster/broadcast_manager.go
  internal/streamingcoord/server/broadcaster/broadcast_task.go
  internal/streamingcoord/server/broadcaster/broadcaster.go
  internal/streamingcoord/server/broadcaster/broadcaster_impl.go
  internal/streamingcoord/server/broadcaster/broadcaster_test.go
  internal/streamingcoord/server/broadcaster/metrics.go
  internal/streamingcoord/server/broadcaster/task.go
  internal/streamingcoord/server/broadcaster/watcher.go
  internal/streamingcoord/server/service/broadcast.go
  internal/streamingcoord/server/service/broadcast/broadcast_watch_grpc_server_helper.go
  internal/streamingcoord/server/service/broadcast/broadcast_watch_server.go
  internal/streamingcoord/server/service/broadcast/broadcast_watch_test.go
  pkg/metrics/streaming_service_metrics.go
  pkg/mocks/proto/mock_streamingpb/mock_StreamingCoordBroadcastServiceClient.go
  pkg/mocks/proto/mock_streamingpb/mock_StreamingCoordBroadcastService_WatchClient.go
  pkg/mocks/proto/mock_streamingpb/mock_StreamingCoordBroadcastService_WatchServer.go
  pkg/proto/messages.proto
  pkg/proto/messagespb/messages.pb.go
  pkg/proto/streaming.proto
  pkg/proto/streamingpb/streaming.pb.go
  pkg/proto/streamingpb/streaming_grpc.pb.go
  pkg/streaming/util/message/broadcast.go
Labels: kind/enhancement, size/XXL, approved, lgtm, ci-passed, area/internal-api, dco-passed, feature/streaming node

#40723 enhance: mergify to check correct ut code
  .github/mergify.yml
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass, github_actions
