Repository milvus-io/milvus, pull requests merged in 2025-01, with the labels that each got.

#38871 fix: drop partition can not be successful if load failed[2.4]
  internal/proxy/task.go
  internal/proxy/util.go
  internal/proxy/util_test.go
  internal/querycoordv2/services.go
  internal/querycoordv2/services_test.go
  pkg/util/merr/utils.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#38874 fix: drop partition can not be successful if load failed[2.5]
  internal/proxy/task.go
  internal/proxy/util.go
  internal/proxy/util_test.go
  internal/querycoordv2/services.go
  internal/querycoordv2/services_test.go
  pkg/util/merr/utils.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#38850 enhance: Bump golang/x/net to v0.33 fixing security alarm
  client/go.mod
  client/go.sum
  go.mod
  go.sum
  pkg/go.mod
  pkg/go.sum
  tests/go_client/go.mod
  tests/go_client/go.sum
Labels: kind/enhancement, area/dependency, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#38883 enhance: [2.5] add param for tuning max VARCHAR length and restore limit to 65535
  internal/proxy/task.go
  internal/proxy/util.go
  pkg/util/paramtable/component_param.go
  tests/go_client/common/consts.go
  tests/go_client/testcases/collection_test.go
  tests/python_client/testcases/test_collection.py
Labels: kind/enhancement, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#38772 enhance: support null expr
  internal/core/src/common/Types.h
  internal/core/src/exec/expression/BinaryRangeExpr.cpp
  internal/core/src/exec/expression/Expr.cpp
  internal/core/src/exec/expression/NullExpr.cpp
  internal/core/src/exec/expression/NullExpr.h
  internal/core/src/exec/expression/UnaryExpr.cpp
  internal/core/src/expr/ITypeExpr.h
  internal/core/src/query/PlanProto.cpp
  internal/core/src/query/PlanProto.h
  internal/core/unittest/test_array_expr.cpp
  internal/core/unittest/test_expr.cpp
  internal/core/unittest/test_string_expr.cpp
  internal/core/unittest/test_utils/GenExprProto.h
  internal/parser/planparserv2/Plan.g4
  internal/parser/planparserv2/check_identical_test.go
  internal/parser/planparserv2/generated/Plan.interp
  internal/parser/planparserv2/generated/Plan.tokens
  internal/parser/planparserv2/generated/PlanLexer.interp
  internal/parser/planparserv2/generated/PlanLexer.tokens
  internal/parser/planparserv2/generated/plan_base_visitor.go
  internal/parser/planparserv2/generated/plan_lexer.go
  internal/parser/planparserv2/generated/plan_parser.go
  internal/parser/planparserv2/generated/plan_visitor.go
  internal/parser/planparserv2/parser_visitor.go
  internal/parser/planparserv2/plan_parser_v2_test.go
  internal/parser/planparserv2/show_visitor.go
  internal/proto/plan.proto
Labels: kind/enhancement, size/XXL, approved, lgtm, ci-passed, dco-passed

#38822 enhance: excessive disk usage logs generated if the path does not exist
  pkg/util/hardware/hardware_info.go
  pkg/util/hardware/hardware_info_test.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#38884 enhance: add param for tuning max VARCHAR length and restore limit to 65535
  internal/proxy/task.go
  internal/proxy/util.go
  pkg/util/paramtable/component_param.go
  tests/go_client/common/consts.go
  tests/go_client/testcases/collection_test.go
  tests/python_client/testcases/test_collection.py
Labels: kind/enhancement, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#38690 fix: Block warmup submit if pool full in sync mode
  internal/core/src/common/ChunkTarget.cpp
  internal/querynodev2/delegator/delegator_data.go
  internal/querynodev2/segments/manager_test.go
  internal/querynodev2/segments/pool.go
  internal/querynodev2/segments/retrieve_test.go
  internal/querynodev2/segments/search_test.go
  internal/querynodev2/segments/segment.go
  internal/querynodev2/segments/segment_loader.go
  internal/querynodev2/segments/segment_loader_test.go
  internal/querynodev2/segments/segment_test.go
  internal/querynodev2/server.go
  internal/querynodev2/server_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#38928 fix: [2.5] expression with capital AND and OR are not recognized
  Makefile
  internal/parser/planparserv2/Plan.g4
  internal/parser/planparserv2/generate.sh
  internal/parser/planparserv2/generated/PlanLexer.interp
  internal/parser/planparserv2/generated/plan_lexer.go
  internal/parser/planparserv2/plan_parser_v2_test.go
Labels: kind/bug, size/XL, approved, lgtm, ci-passed, dco-passed, area/compilation, manual-pass

#38953 enhance: [10kcp] Add logs for querycoord checker
  internal/querycoordv2/checkers/controller.go
  internal/querycoordv2/dist/dist_handler.go
  internal/querycoordv2/meta/target.go
Labels: size/XS

#38952 enhance: [10ckp] Add log for case which target not update as expected
  internal/querycoordv2/utils/util.go
Labels: size/XS

#38951 fix: [10kcp] Querycoord will trigger unexpected balance task after restart
  internal/proto/query_coord.proto
  internal/querycoordv2/balance/mock_balancer.go
  internal/querycoordv2/checkers/balance_checker.go
  internal/querycoordv2/checkers/balance_checker_test.go
  internal/querycoordv2/meta/mock_target_manager.go
  internal/querycoordv2/meta/target.go
  internal/querycoordv2/meta/target_manager.go
  internal/querycoordv2/meta/target_manager_test.go
Labels: size/L, area/internal-api

#38956 enhance: [10kcp] Reducing the granularity of locks in the target manager
  internal/querycoordv2/meta/target_manager.go
Labels: size/S

#38954 fix: search req transfer correctly
  internal/querynodev2/delegator/delegator.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#38955 fix: search req transfer correctly
  internal/querynodev2/delegator/delegator.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#38968 enhance: [10kcp] Remove scheduler and target manager mutex
  internal/querycoordv2/meta/target.go
  internal/querycoordv2/meta/target_manager.go
  internal/querycoordv2/meta/target_manager_test.go
  internal/querycoordv2/task/scheduler.go
  internal/querycoordv2/task/task_test.go
  pkg/metrics/querycoord_metrics.go
Labels: size/L

#38969 enhance: update opensource etcd version
  deployments/docker/dev/docker-compose.yml
  deployments/docker/gpu/standalone/docker-compose.yml
  deployments/docker/standalone/docker-compose.yml
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass, kind/branch-feature

#38972 fix: [10kcp] channel unbalance during stopping balance progress
  internal/querycoordv2/balance/balance.go
  internal/querycoordv2/balance/rowcount_based_balancer.go
  internal/querycoordv2/balance/score_based_balancer.go
  internal/querycoordv2/balance/score_based_balancer_test.go
Labels: size/M

#38935 enhance: TestDeleteComplexExpr may failure because of timeout
  tests/go_client/testcases/delete_test.go
Labels: kind/enhancement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed, manual-pass

#38323 enhance: extract the task step execution process
  internal/rootcoord/alter_collection_task.go
  internal/rootcoord/alter_database_task.go
  internal/rootcoord/create_collection_task.go
  internal/rootcoord/create_partition_task.go
  internal/rootcoord/drop_collection_task.go
  internal/rootcoord/drop_db_task.go
  internal/rootcoord/drop_partition_task.go
  internal/rootcoord/rbac_task.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/task_test.go
Labels: kind/enhancement, size/XXL, approved, lgtm, ci-passed, dco-passed

#38973 enhance: update opensource etcd version
  deployments/docker/dev/docker-compose.yml
  deployments/docker/gpu/standalone/docker-compose.yml
  deployments/docker/standalone/docker-compose.yml
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass, kind/branch-feature

#38974 fix: [10kcp] Fix concurrent scheule
  internal/querycoordv2/task/scheduler.go
Labels: size/XS

#38950 fix: text match panics when enable_match is set be false
  internal/core/src/common/EasyAssert.h
  internal/core/src/segcore/SegmentGrowingImpl.cpp
  internal/core/src/segcore/SegmentInterface.cpp
  internal/parser/planparserv2/parser_visitor.go
  internal/parser/planparserv2/plan_parser_v2_test.go
  pkg/util/typeutil/schema.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#38887 enhance: delete one pod pipeline in nightly and open mmap in standalone
  ci/jenkins/Nightly2.groovy
  tests/_helm/values/e2e/standalone-kafka-mmap
  tests/_helm/values/nightly/standalone
Labels: kind/enhancement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#38942 enhance: Update Knowhere version
  internal/core/thirdparty/knowhere/CMakeLists.txt
  tests/go_client/testcases/groupby_search_test.go
  tests/python_client/testcases/test_search.py
Labels: kind/enhancement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed, area/compilation

#38932 enhance: [2.5] Bump golang/x/net to v0.33 fixing security alarm (#38850)
  go.mod
  go.sum
  pkg/go.mod
  pkg/go.sum
  tests/go_client/go.mod
  tests/go_client/go.sum
Labels: kind/enhancement, area/dependency, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#38888 enhance: delete one pod pipeline in nightly and open mmap in standalone(2.5)
  ci/jenkins/Nightly2.groovy
  tests/_helm/values/e2e/standalone
  tests/_helm/values/nightly/distributed-pulsar
Labels: kind/enhancement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#38941 enhance: Fix using wrong pool for warmup
  internal/querynodev2/segments/segment.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#38940 enhance: [GoSDK] Support Resource Group Controlling APIs
  client/entity/resource_group.go
  client/milvusclient/resource_group.go
  client/milvusclient/resource_group_option.go
  client/milvusclient/resource_group_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#38929 fix: [2.4] expression with capital AND and OR are not recognized
  Makefile
  internal/parser/planparserv2/Plan.g4
  internal/parser/planparserv2/generate.sh
  internal/parser/planparserv2/generated/PlanLexer.interp
  internal/parser/planparserv2/generated/plan_lexer.go
  internal/parser/planparserv2/plan_parser_v2_test.go
Labels: kind/bug, size/XL, approved, lgtm, ci-passed, dco-passed, area/compilation

#38957 enhance: Increase the buffer capacity of notifyIndexChan to support concurrency
  internal/datacoord/server.go
Labels: kind/enhancement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#38918 enhance: [2.5]Return collection not loaded rather than not found on querynode (#38593)
  internal/querynodev2/services.go
  internal/querynodev2/services_test.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#38927 fix: expression with capital AND and OR are not recognized
  Makefile
  internal/parser/planparserv2/Plan.g4
  internal/parser/planparserv2/generate.sh
  internal/parser/planparserv2/generated/PlanLexer.interp
  internal/parser/planparserv2/generated/plan_lexer.go
  internal/parser/planparserv2/plan_parser_v2_test.go
Labels: kind/bug, size/XL, approved, lgtm, ci-passed, dco-passed, area/compilation, manual-pass

#38920 enhance: [2.4]Return collection not loaded rather than not found on querynode (#38593)
  internal/querynodev2/services.go
  internal/querynodev2/services_test.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#38995 doc: Update typo in "Welcome to Milvus"
  cmd/milvus/run.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass, kind/doc

#38980 enhance: Use mvcc timestamp as guarantee ts if set
  internal/proxy/task_query.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#38622 fix: Fix panic caused by removing directory
  internal/core/src/index/InvertedIndexTantivy.cpp
  internal/core/src/storage/LocalChunkManager.cpp
  internal/core/thirdparty/tantivy/tantivy-wrapper.h
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#38939 test: Refactor pymilvus client v2 testbase and add a test for search hint
  tests/python_client/base/client_base.py
  tests/python_client/base/client_v2_base.py
  tests/python_client/base/high_level_api_wrapper.py
  tests/python_client/check/func_check.py
  tests/python_client/milvus_client/test_milvus_client_alias.py
  tests/python_client/milvus_client/test_milvus_client_alter.py
  tests/python_client/milvus_client/test_milvus_client_collection.py
  tests/python_client/milvus_client/test_milvus_client_delete.py
  tests/python_client/milvus_client/test_milvus_client_index.py
  tests/python_client/milvus_client/test_milvus_client_insert.py
  tests/python_client/milvus_client/test_milvus_client_partition.py
  tests/python_client/milvus_client/test_milvus_client_query.py
  tests/python_client/milvus_client/test_milvus_client_rbac.py
  tests/python_client/milvus_client/test_milvus_client_search.py
  tests/python_client/requirements.txt
  tests/python_client/testcases/async_milvus_client/test_e2e_async.py
  tests/python_client/testcases/test_high_level_api.py
Labels: sig/testing, size/XXL, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#38892 enhance:[Cherry-pick] report restful and grpc auth info to hook
  client/go.mod
  client/go.sum
  go.mod
  go.sum
  internal/distributed/proxy/httpserver/handler_v2.go
  internal/distributed/proxy/httpserver/utils.go
  internal/distributed/proxy/service.go
  internal/proxy/authentication_interceptor.go
  internal/util/hookutil/default.go
  pkg/go.mod
  pkg/go.sum
  tests/integration/minicluster_v2.go
Labels: kind/enhancement, area/dependency, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed, test/integration

#38991 fix: fix query incorrect in case of concurrent delete
  internal/core/src/segcore/DeletedRecord.h
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#39006 test: [cp2.5]Refactor pymilvus client v2 testbase and add a test for search hint
  tests/python_client/base/client_base.py
  tests/python_client/base/client_v2_base.py
  tests/python_client/base/high_level_api_wrapper.py
  tests/python_client/check/func_check.py
  tests/python_client/milvus_client/test_milvus_client_alias.py
  tests/python_client/milvus_client/test_milvus_client_alter.py
  tests/python_client/milvus_client/test_milvus_client_collection.py
  tests/python_client/milvus_client/test_milvus_client_delete.py
  tests/python_client/milvus_client/test_milvus_client_index.py
  tests/python_client/milvus_client/test_milvus_client_insert.py
  tests/python_client/milvus_client/test_milvus_client_partition.py
  tests/python_client/milvus_client/test_milvus_client_query.py
  tests/python_client/milvus_client/test_milvus_client_rbac.py
  tests/python_client/milvus_client/test_milvus_client_search.py
  tests/python_client/requirements.txt
  tests/python_client/testcases/async_milvus_client/test_e2e_async.py
  tests/python_client/testcases/test_high_level_api.py
Labels: sig/testing, size/XXL, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#38999 fix: [2.5]Remove valid expressions from invalid expressions
  internal/datacoord/server.go
  tests/go_client/common/utils.go
Labels: kind/bug, kind/enhancement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed

#39012 fix: [skip-e2e] Remove valid expressions from invalid expressions
  tests/go_client/common/utils.go
Labels: kind/bug, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed, manual-pass

#39021 enhance: [2.4] Fix go mod conflict
  go.mod
  go.sum
Labels: kind/enhancement, area/dependency, size/XS, approved, lgtm, ci-passed, dco-passed, kind/branch-feature

#39004 enhance: Accelerate `find_first` by utilizing bitset simd methods
  internal/core/src/segcore/ChunkedSegmentSealedImpl.cpp
  internal/core/src/segcore/SegmentSealedImpl.cpp
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#38747 enhance: [2.5]Add missing delete metrics (#38634)
  internal/datanode/compaction/clustering_compactor.go
  internal/datanode/compaction/compactor_common.go
  internal/datanode/compaction/compactor_common_test.go
  internal/datanode/compaction/merge_sort.go
  internal/datanode/compaction/mix_compactor.go
  internal/datanode/compaction/mix_compactor_test.go
  internal/proto/data_coord.proto
  pkg/metrics/datanode_metrics.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#38808 enhance: refine array view to optimize memory usage(#38736)
  internal/core/src/common/Array.h
  internal/core/src/common/Chunk.cpp
  internal/core/src/common/ChunkWriter.cpp
  internal/core/src/mmap/ChunkData.h
  internal/core/src/mmap/ChunkVector.h
  internal/core/src/mmap/Column.h
  internal/core/src/mmap/Utils.h
  internal/core/src/segcore/SegmentSealedImpl.cpp
  internal/core/src/storage/MmapChunkManager.cpp
  internal/core/unittest/test_array.cpp
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed, area/compilation

#39008 fix: Fix Milvus build error
  internal/core/src/bitset/bitset.h
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#39037 enhance: Use bitset or instead of bitwise set
  internal/core/src/exec/expression/TermExpr.cpp
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#39007 enhance: move streaming coord from datacoord to rootcoord
  internal/coordinator/coordclient/registry.go
  internal/datacoord/server.go
  internal/distributed/datacoord/service.go
  internal/distributed/rootcoord/service.go
  internal/distributed/rootcoord/service_test.go
  internal/mocks/mock_datacoord.go
  internal/mocks/mock_rootcoord.go
  internal/rootcoord/root_coord.go
  internal/streamingcoord/client/client.go
  internal/streamingcoord/server/balancer/balancer_impl.go
  internal/streamingcoord/server/builder.go
  internal/streamingcoord/server/resource/resource.go
  internal/streamingcoord/server/resource/test_utility.go
  internal/streamingcoord/server/server.go
  internal/streamingcoord/server/service/discover/discover_server.go
  internal/streamingcoord/server/service/discover/discover_server_test.go
  internal/streamingcoord/server/service_test.go
  internal/types/types.go
  internal/util/streamingutil/service/discoverer/session_discoverer.go
  internal/util/streamingutil/service/discoverer/session_discoverer_test.go
  internal/util/streamingutil/service/resolver/builder.go
  pkg/log/fields.go
  pkg/log/global.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#38944 enhance: Add log for case which target not update as expected
  internal/querycoordv2/utils/util.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#39041 enhance: [2.5] Optimize retrieve performance utilizing bitset SIMD methods
  internal/core/src/exec/expression/TermExpr.cpp
  internal/core/src/segcore/ChunkedSegmentSealedImpl.cpp
  internal/core/src/segcore/SegmentSealedImpl.cpp
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#39009 enhance: move streaming coord from datacoord to rootcoord
  internal/coordinator/coordclient/registry.go
  internal/datacoord/server.go
  internal/distributed/datacoord/service.go
  internal/distributed/rootcoord/service.go
  internal/distributed/rootcoord/service_test.go
  internal/mocks/mock_datacoord.go
  internal/mocks/mock_rootcoord.go
  internal/rootcoord/root_coord.go
  internal/streamingcoord/client/client.go
  internal/streamingcoord/server/balancer/balancer_impl.go
  internal/streamingcoord/server/builder.go
  internal/streamingcoord/server/resource/resource.go
  internal/streamingcoord/server/resource/test_utility.go
  internal/streamingcoord/server/server.go
  internal/streamingcoord/server/service/discover/discover_server.go
  internal/streamingcoord/server/service/discover/discover_server_test.go
  internal/streamingcoord/server/service_test.go
  internal/types/types.go
  internal/util/streamingutil/service/discoverer/session_discoverer.go
  internal/util/streamingutil/service/discoverer/session_discoverer_test.go
  internal/util/streamingutil/service/resolver/builder.go
  pkg/log/fields.go
  pkg/log/global.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#39019 enhance: [2.5] Use mvcc timestamp as guarantee ts if set (#38980)
  internal/proxy/task_query.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#39048 test: Add search with hints on different expressions
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#39052 enhance: refactor the streaming node log
  internal/streamingnode/server/resource/resource.go
  internal/streamingnode/server/resource/test_utility.go
  internal/streamingnode/server/service/handler/consumer/consume_server.go
  internal/streamingnode/server/service/handler/producer/produce_server.go
  internal/streamingnode/server/wal/adaptor/opener.go
  internal/streamingnode/server/wal/adaptor/scanner_adaptor.go
  internal/streamingnode/server/wal/adaptor/wal_adaptor.go
  internal/streamingnode/server/wal/interceptors/segment/builder.go
  internal/streamingnode/server/wal/interceptors/segment/inspector/impls.go
  internal/streamingnode/server/wal/interceptors/segment/manager/partition_manager.go
  internal/streamingnode/server/wal/interceptors/segment/manager/partition_managers.go
  internal/streamingnode/server/wal/interceptors/timetick/timetick_sync_operator.go
  internal/streamingnode/server/wal/interceptors/txn/txn_manager.go
  internal/streamingnode/server/walmanager/manager_impl.go
  internal/streamingnode/server/walmanager/wal_lifetime.go
  internal/streamingnode/server/walmanager/wal_lifetime_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#38924 fix: Return io error other than `NotExist` refreshing config
  pkg/config/config.go
  pkg/config/file_source.go
  pkg/config/manager_test.go
  pkg/config/refresher.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#39033 fix: set iterative filter hint to false when no expr specified
  internal/core/src/query/PlanProto.cpp
  internal/core/unittest/test_iterative_filter.cpp
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#39034 fix: [2.5] set iterative filter hint to false when no expr specified
  internal/core/src/query/PlanProto.cpp
  internal/core/unittest/test_iterative_filter.cpp
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#38979 fix: not add index name in alter index properties
  internal/distributed/proxy/httpserver/handler_v2.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#39042 enhance: [2.4] Use bitset or instead of bitwise set (#39037)
  internal/core/src/exec/expression/TermExpr.cpp
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#38848 enhance: clean compaction task in compactionHandler (#38170)
  internal/datacoord/compaction.go
  internal/datacoord/compaction_task.go
  internal/datacoord/compaction_task_clustering.go
  internal/datacoord/compaction_task_clustering_test.go
  internal/datacoord/compaction_task_l0.go
  internal/datacoord/compaction_task_l0_test.go
  internal/datacoord/compaction_task_mix.go
  internal/datacoord/compaction_test.go
  internal/datacoord/handler.go
  internal/datacoord/meta.go
  internal/datacoord/partition_stats_meta.go
  internal/datacoord/partition_stats_meta_test.go
  pkg/util/merr/errors.go
  pkg/util/merr/utils.go
Labels: kind/enhancement, size/XL, approved, lgtm, ci-passed, dco-passed

#39062 test: [cp2.5]Add search with hints for different expressions
  tests/python_client/testcases/test_search.py
Labels: size/L, approved, lgtm, ci-passed, dco-passed, kind/test

#39054 fix: fix query incorrect in case of concurrent delete (#38991)
  internal/core/src/segcore/DeletedRecord.h
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#39046 enhance: Add log for case which target not update as expected (#38944)
  internal/querycoordv2/utils/util.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#38885 enhance: Add resource group api on Restful
  internal/distributed/proxy/httpserver/constant.go
  internal/distributed/proxy/httpserver/handler_v2.go
  internal/distributed/proxy/httpserver/request_v2.go
  internal/distributed/proxy/httpserver/resource_group_handler_v2.go
  internal/distributed/proxy/httpserver/resource_group_handler_v2_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#39082 enhance: update the expr static web page
  internal/http/static/index.html
Labels: kind/enhancement, kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#39089 enhance: [2.4] update the expr static web page
  internal/http/static/index.html
Labels: kind/enhancement, kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#39091 enhance: [2.5] update the expr static web page
  internal/http/static/index.html
Labels: kind/enhancement, kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#39070 fix: build text index when loading field data
  internal/core/src/index/TextMatchIndex.cpp
  internal/core/src/index/TextMatchIndex.h
  internal/core/src/segcore/SegmentGrowingImpl.cpp
  internal/core/unittest/test_text_match.cpp
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#39076 fix: Remove duplicated Macro definition
  internal/core/src/common/File.h
  internal/core/src/mmap/Utils.h
Labels: kind/bug, kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#39092 enhance: Add resource group api on Restful (#38885)
  internal/distributed/proxy/httpserver/constant.go
  internal/distributed/proxy/httpserver/handler_v2.go
  internal/distributed/proxy/httpserver/request_v2.go
  internal/distributed/proxy/httpserver/resource_group_handler_v2.go
  internal/distributed/proxy/httpserver/resource_group_handler_v2_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#39020 enhance: add broadcast for streaming service
  internal/.mockery.yaml
  internal/distributed/streaming/append.go
  internal/distributed/streaming/streaming.go
  internal/distributed/streaming/streaming_test.go
  internal/distributed/streaming/wal.go
  internal/distributed/streaming/wal_test.go
  internal/metastore/catalog.go
  internal/metastore/kv/streamingcoord/constant.go
  internal/metastore/kv/streamingcoord/kv_catalog.go
  internal/metastore/kv/streamingcoord/kv_catalog_test.go
  internal/mocks/distributed/mock_streaming/mock_WALAccesser.go
  internal/mocks/mock_metastore/mock_StreamingCoordCataLog.go
  internal/mocks/streamingcoord/mock_client/mock_BroadcastService.go
  internal/mocks/streamingcoord/mock_client/mock_Client.go
  internal/mocks/streamingcoord/server/mock_broadcaster/mock_AppendOperator.go
  internal/streamingcoord/client/broadcast/broadcast_impl.go
  internal/streamingcoord/client/client.go
  internal/streamingcoord/client/client_impl.go
  internal/streamingcoord/server/broadcaster/append_operator.go
  internal/streamingcoord/server/broadcaster/broadcaster.go
  internal/streamingcoord/server/broadcaster/broadcaster_impl.go
  internal/streamingcoord/server/broadcaster/broadcaster_test.go
  internal/streamingcoord/server/broadcaster/task.go
  internal/streamingcoord/server/builder.go
  internal/streamingcoord/server/resource/resource.go
  internal/streamingcoord/server/server.go
  internal/streamingcoord/server/service/broadcast.go
  internal/streamingnode/server/flusher/flusherimpl/flusher_impl.go
  internal/streamingnode/server/resource/resource.go
  internal/streamingnode/server/resource/test_utility.go
  internal/streamingnode/server/service/handler/producer/produce_server.go
  internal/streamingnode/server/wal/adaptor/wal_test.go
  internal/streamingnode/server/wal/interceptors/segment/manager/pchannel_manager_test.go
  internal/streamingnode/server/wal/interceptors/timetick/timetick_message.go
  internal/util/idalloc/allocator.go
  internal/util/idalloc/allocator_test.go
  internal/util/idalloc/basic_allocator.go
  internal/util/idalloc/basic_allocator_test.go
  internal/util/idalloc/mallocator.go
  internal/util/idalloc/test_mock_root_coord_client.go
  pkg/streaming/proto/messages.proto
  pkg/streaming/proto/streaming.proto
  pkg/streaming/util/message/builder.go
  pkg/streaming/util/message/message.go
  pkg/streaming/util/message/message_impl.go
  pkg/streaming/util/message/properties.go
  pkg/streaming/util/types/streaming_node.go
  pkg/util/contextutil/context_util.go
  pkg/util/typeutil/backoff_timer.go
Labels: kind/enhancement, size/XXL, approved, lgtm, ci-passed, dco-passed

#39108 fix: Fix in filter search result is empty if pk type is varchar
  internal/core/src/segcore/ChunkedSegmentSealedImpl.cpp
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#38876 test: update cases for search params support and groupby issue fix
  tests/go_client/testcases/groupby_search_test.go
  tests/go_client/testcases/query_test.go
  tests/go_client/testcases/search_test.go
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, manual-pass, kind/test

#39063 fix: Bulk insert failed when the nullable/default_value field is not exist
  internal/util/importutilv2/json/row_parser.go
  internal/util/importutilv2/json/row_parser_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#39111 fix: Bulk insert failed when the nullable/default_value field is not exist(#39063)
  internal/util/importutilv2/json/row_parser.go
  internal/util/importutilv2/json/row_parser_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#39113 fix: build text index when loading field data (#39070)
  internal/core/src/index/TextMatchIndex.cpp
  internal/core/src/index/TextMatchIndex.h
  internal/core/src/segcore/SegmentGrowingImpl.cpp
  internal/core/unittest/test_text_match.cpp
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed, kind/branch-feature

#38672 enhance: add db name in replica
  internal/datacoord/compaction_task_clustering.go
  internal/datacoord/compaction_task_l0.go
  internal/datacoord/compaction_task_meta.go
  internal/datacoord/compaction_task_mix.go
  internal/datacoord/index_meta.go
  internal/datacoord/metrics_info.go
  internal/datacoord/server.go
  internal/datanode/data_node.go
  internal/flushcommon/pipeline/flow_graph_manager.go
  internal/flushcommon/pipeline/flow_graph_manager_test.go
  internal/flushcommon/pipeline/mock_fgmanager.go
  internal/metastore/model/segment_index.go
  internal/proto/index_coord.proto
  internal/proto/query_coord.proto
  internal/proxy/http_req_impl.go
  internal/proxy/impl.go
  internal/querycoordv2/handlers.go
  internal/querycoordv2/job/job_load.go
  internal/querycoordv2/meta/channel_dist_manager.go
  internal/querycoordv2/meta/channel_dist_manager_test.go
  internal/querycoordv2/meta/collection_manager.go
  internal/querycoordv2/meta/dist_manager.go
  internal/querycoordv2/meta/dist_manager_test.go
  internal/querycoordv2/meta/leader_view_manager.go
  internal/querycoordv2/meta/leader_view_manager_test.go
  internal/querycoordv2/meta/mock_target_manager.go
  internal/querycoordv2/meta/replica_manager.go
  internal/querycoordv2/meta/replica_manager_test.go
  internal/querycoordv2/meta/segment_dist_manager.go
  internal/querycoordv2/meta/target.go
  internal/querycoordv2/meta/target_manager.go
  internal/querycoordv2/meta/target_manager_test.go
  internal/querycoordv2/server.go
  internal/querycoordv2/utils/meta.go
  internal/querynodev2/metrics_info.go
  internal/querynodev2/metrics_info_test.go
  internal/querynodev2/pipeline/manager.go
  internal/querynodev2/server.go
  pkg/util/metricsinfo/metric_request.go
  pkg/util/metricsinfo/metrics_info.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, area/internal-api, dco-passed

#38673 enhance: add db name in replica description
  internal/datacoord/compaction_task_clustering.go
  internal/datacoord/compaction_task_l0.go
  internal/datacoord/compaction_task_meta.go
  internal/datacoord/compaction_task_mix.go
  internal/datacoord/index_meta.go
  internal/datacoord/metrics_info.go
  internal/datacoord/server.go
  internal/datanode/data_node.go
  internal/flushcommon/pipeline/flow_graph_manager.go
  internal/flushcommon/pipeline/flow_graph_manager_test.go
  internal/flushcommon/pipeline/mock_fgmanager.go
  internal/metastore/model/segment_index.go
  internal/proto/index_coord.proto
  internal/proto/query_coord.proto
  internal/proxy/http_req_impl.go
  internal/proxy/impl.go
  internal/querycoordv2/handlers.go
  internal/querycoordv2/job/job_load.go
  internal/querycoordv2/meta/channel_dist_manager.go
  internal/querycoordv2/meta/channel_dist_manager_test.go
  internal/querycoordv2/meta/collection_manager.go
  internal/querycoordv2/meta/dist_manager.go
  internal/querycoordv2/meta/dist_manager_test.go
  internal/querycoordv2/meta/leader_view_manager.go
  internal/querycoordv2/meta/leader_view_manager_test.go
  internal/querycoordv2/meta/mock_target_manager.go
  internal/querycoordv2/meta/replica_manager.go
  internal/querycoordv2/meta/replica_manager_test.go
  internal/querycoordv2/meta/segment_dist_manager.go
  internal/querycoordv2/meta/target.go
  internal/querycoordv2/meta/target_manager.go
  internal/querycoordv2/meta/target_manager_test.go
  internal/querycoordv2/server.go
  internal/querycoordv2/utils/meta.go
  internal/querynodev2/metrics_info.go
  internal/querynodev2/metrics_info_test.go
  internal/querynodev2/pipeline/manager.go
  internal/querynodev2/server.go
  pkg/util/metricsinfo/metric_request.go
  pkg/util/metricsinfo/metrics_info.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, area/internal-api, dco-passed

#38821 enhance: excessive disk usage logs generated if the path does not exist
  pkg/util/hardware/hardware_info.go
  pkg/util/hardware/hardware_info_test.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#38867 test: add test cases for template param
  tests/go_client/base/milvus_client.go
  tests/go_client/testcases/helper/data_helper.go
  tests/go_client/testcases/index_test.go
  tests/go_client/testcases/query_test.go
  tests/go_client/testcases/search_test.go
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, manual-pass, kind/test

#39122 test: add more varchar expressions for query
  tests/python_client/common/common_func.py
  tests/python_client/testcases/test_mix_scenes.py
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#39137 fix: Refine the err msg of alter index invalid
  internal/proxy/task_index.go
  tests/python_client/common/code_mapping.py
  tests/python_client/milvus_client/test_milvus_client_alter.py
  tests/python_client/testcases/test_index.py
Labels: kind/bug, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#39081 enhance: remove compaction parallelism control
  configs/milvus.yaml
  internal/datacoord/compaction.go
  internal/datacoord/compaction_test.go
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#39132 fix: Clustering compaction ignoring deltalogs
  internal/datanode/compaction/clustering_compactor.go
  internal/datanode/compaction/clustering_compactor_test.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#39133 fix: Clustering compaction ignoring deltalogs
  internal/datanode/compaction/clustering_compactor.go
  internal/datanode/compaction/clustering_compactor_test.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#39072 fix: [2.5] Return io error other than `NotExist` refreshing config (#38924)
  pkg/config/config.go
  pkg/config/file_source.go
  pkg/config/manager_test.go
  pkg/config/refresher.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#39073 fix: [2.4] Return io error other than `NotExist` refreshing config (#38924)
  pkg/config/config.go
  pkg/config/file_source.go
  pkg/config/manager_test.go
  pkg/config/refresher.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#39000 fix: Prevent leader checker from generating excessive duplicate leader tasks
  internal/querycoordv2/checkers/leader_checker.go
  internal/querycoordv2/checkers/leader_checker_test.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#39146 fix: [2.5] fix chunk cache madvise when sparse raw data is mmaped
  internal/core/src/mmap/ChunkedColumn.h
Labels: kind/bug, size/XS, approved, lgtm, dco-passed

#39118 fix: use the object heap to keep the min ddl ts order
  internal/rootcoord/scheduler.go
  internal/rootcoord/scheduler_test.go
  internal/rootcoord/task.go
  pkg/util/typeutil/heap.go
  pkg/util/typeutil/heap_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#38805 enhance: keylock object background recycling
  pkg/go.mod
  pkg/go.sum
  pkg/util/lock/key_lock.go
  pkg/util/lock/key_lock_test.go
Labels: kind/enhancement, area/dependency, size/M, approved, lgtm, ci-passed, dco-passed

#39162 fix: unstable ut in leader_vew_manager.go file
  internal/querycoordv2/meta/leader_view_manager.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#38982 test: add text match negative test case
  tests/python_client/testcases/test_query.py
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#39139 test: update reatful api timeout
  tests/restful_client_v2/api/milvus.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#38948 enhance: add intent ctx to rootcoord init
  cmd/roles/roles.go
  internal/rootcoord/dml_channels.go
  internal/rootcoord/mock_test.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
  internal/rootcoord/timeticksync.go
  internal/rootcoord/timeticksync_test.go
  pkg/log/global.go
  pkg/log/mlogger_test.go
  pkg/mq/msgstream/common_mq_factory.go
  pkg/mq/msgstream/mq_msgstream.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed, do-not-merge/missing-related-pr

#38869 feat: support phrase match query
  internal/core/src/common/EasyAssert.h
  internal/core/src/exec/expression/UnaryExpr.cpp
  internal/core/src/expr/ITypeExpr.h
  internal/core/src/index/TextMatchIndex.cpp
  internal/core/src/index/TextMatchIndex.h
  internal/core/src/query/PlanProto.cpp
  internal/core/thirdparty/tantivy/tantivy-binding/include/tantivy-binding.h
  internal/core/thirdparty/tantivy/tantivy-binding/src/index_reader_text.rs
  internal/core/thirdparty/tantivy/tantivy-binding/src/index_reader_text_c.rs
  internal/core/thirdparty/tantivy/tantivy-wrapper.h
  internal/core/unittest/test_array_expr.cpp
  internal/core/unittest/test_exec.cpp
  internal/core/unittest/test_expr.cpp
  internal/core/unittest/test_retrieve.cpp
  internal/core/unittest/test_text_match.cpp
  internal/parser/planparserv2/Plan.g4
  internal/parser/planparserv2/generated/Plan.interp
  internal/parser/planparserv2/generated/Plan.tokens
  internal/parser/planparserv2/generated/PlanLexer.interp
  internal/parser/planparserv2/generated/PlanLexer.tokens
  internal/parser/planparserv2/generated/plan_base_visitor.go
  internal/parser/planparserv2/generated/plan_lexer.go
  internal/parser/planparserv2/generated/plan_parser.go
  internal/parser/planparserv2/generated/plan_visitor.go
  internal/parser/planparserv2/parser_visitor.go
  internal/parser/planparserv2/plan_parser_v2_test.go
  internal/parser/planparserv2/show_visitor.go
  pkg/proto/plan.proto
  pkg/proto/planpb/plan.pb.go
Labels: kind/feature, size/XXL, approved, lgtm, ci-passed, dco-passed

#39144 enhance: Use template to remove unittest duplication
  internal/core/src/common/VectorTrait.h
  internal/core/unittest/test_c_api.cpp
  internal/core/unittest/test_c_stream_reduce.cpp
  internal/core/unittest/test_float16.cpp
  internal/core/unittest/test_query.cpp
  internal/core/unittest/test_utils/DataGen.h
  internal/core/unittest/test_utils/c_api_test_utils.h
Labels: kind/enhancement, size/XXL, approved, lgtm, ci-passed, dco-passed, manual-pass

#39141 fix: restore rbac with empty meta panic
  internal/metastore/kv/rootcoord/kv_catalog.go
  internal/proxy/impl.go
  tests/integration/rbac/rbac_backup_test.go
Labels: kind/bug, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed, test/integration

#39142 fix: [2.4] restore rbac with empty meta panic
  internal/metastore/kv/rootcoord/kv_catalog.go
  internal/proxy/impl.go
  tests/integration/rbac/rbac_backup_test.go
Labels: kind/bug, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed, test/integration

#39145 fix: fix chunk cache madvise when sparse raw data is mmaped
  internal/core/src/mmap/ChunkedColumn.h
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#38971 fix: channel unbalance during stopping balance progress
  internal/querycoordv2/balance/balance.go
  internal/querycoordv2/balance/rowcount_based_balancer.go
  internal/querycoordv2/balance/score_based_balancer.go
  internal/querycoordv2/balance/score_based_balancer_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#39151 fix: data race when accessing field_ when retrieving
  internal/core/src/segcore/SegmentSealedImpl.cpp
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#39152 fix: data race when accessing field_ when retrieving
  internal/core/src/segcore/SegmentSealedImpl.cpp
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#39164 fix: rbac custom group privilege level check
  internal/proxy/impl.go
  internal/proxy/util.go
  internal/rootcoord/meta_table.go
  internal/rootcoord/rbac_task.go
  internal/rootcoord/root_coord.go
  pkg/util/constant.go
  pkg/util/paramtable/rbac_config_test.go
  pkg/util/paramtable/rbac_param.go
  tests/integration/rbac/privilege_group_test.go
  tests/integration/rbac/rbac_backup_test.go
  tests/python_client/testcases/test_utility.py
Labels: kind/bug, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, test/integration

#39143 fix: [2.5] fix restore rbac empty meta crash
  internal/metastore/kv/rootcoord/kv_catalog.go
  internal/proxy/impl.go
  tests/integration/rbac/rbac_backup_test.go
Labels: kind/bug, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed, test/integration

#39198 enhance: Bump milvus & proto version to v2.5.3
  client/go.mod
  client/go.sum
  go.mod
  go.sum
  pkg/common/version.go
  pkg/go.mod
  pkg/go.sum
  tests/go_client/go.mod
  tests/go_client/go.sum
Labels: kind/enhancement, area/dependency, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed, manual-pass, kind/branch-feature

#39194 fix: [2.4] rbac custom group privilege level check
  internal/proxy/impl.go
  internal/proxy/util.go
  internal/rootcoord/meta_table.go
  internal/rootcoord/root_coord.go
  pkg/util/constant.go
  pkg/util/paramtable/rbac_config_test.go
  pkg/util/paramtable/rbac_param.go
  tests/integration/rbac/privilege_group_test.go
  tests/integration/rbac/rbac_backup_test.go
Labels: kind/bug, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, test/integration

#39155 fix: fail to get empty index num rows
  internal/core/src/index/ScalarIndexSort.cpp
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#39106 fix: Fix in filter search result is empty if pk type is varchar
  internal/core/src/segcore/ChunkedSegmentSealedImpl.cpp
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#39182 fix: Make KeyLock obj pool size unlimited
  pkg/util/lock/key_lock.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#39209 enhance: [2.4] Bump golang/x/net to v0.33 fixing security alarm
  client/go.mod
  client/go.sum
  go.mod
  go.sum
  pkg/go.mod
  pkg/go.sum
Labels: kind/enhancement, area/dependency, size/S, approved, lgtm, ci-passed, dco-passed

#38813 fix: Fix incorrect memory estimation for small segments
  internal/querynodev2/segments/segment_loader.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed, 10kcp

#38909 fix: [2.5] Fix incorrect memory estimation for small segments
  internal/querynodev2/segments/segment_loader.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#38910 fix: [2.4] Fix incorrect memory estimation for small segments
  internal/querynodev2/segments/segment_loader.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#39176 enhance: [bitset] extend op_find() to be able to search both 0 and 1
  internal/core/src/bitset/CMakeLists.txt
  internal/core/src/bitset/bitset.h
  internal/core/src/bitset/detail/bit_wise.h
  internal/core/src/bitset/detail/element_vectorized.h
  internal/core/src/bitset/detail/element_wise.h
  internal/core/src/bitset/detail/proxy.h
  internal/core/unittest/test_bitset.cpp
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed, area/compilation

#39212 enhance: update knowhere version
  internal/core/thirdparty/knowhere/CMakeLists.txt
  internal/core/unittest/test_indexing.cpp
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed, area/compilation

#39218 enhance: update knowhere version
  internal/core/thirdparty/knowhere/CMakeLists.txt
  internal/core/unittest/test_indexing.cpp
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed, area/compilation, kind/branch-feature

#39210 fix:[2.5] fail to get empty index num rows(#39155)
  internal/core/src/index/ScalarIndexSort.cpp
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#39229 enhance: Utilize "find0" in segment.find_first
  internal/core/src/segcore/ChunkedSegmentSealedImpl.cpp
  internal/core/src/segcore/SegmentSealedImpl.cpp
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#39193 fix: [2.4] use the object heap to keep the min ddl ts order
  internal/rootcoord/scheduler.go
  internal/rootcoord/scheduler_test.go
  internal/rootcoord/task.go
  pkg/util/typeutil/heap.go
  pkg/util/typeutil/heap_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#39195 fix: [2.5] use the object heap to keep the min ddl ts order
  internal/rootcoord/scheduler.go
  internal/rootcoord/scheduler_test.go
  internal/rootcoord/task.go
  pkg/util/typeutil/heap.go
  pkg/util/typeutil/heap_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#39119 enhance: add broadcast operation for msgstream
  cmd/roles/roles.go
  configs/milvus.yaml
  internal/distributed/streaming/streaming.go
  internal/distributed/streaming/streaming_test.go
  internal/distributed/streaming/util.go
  internal/distributed/streaming/wal.go
  internal/rootcoord/broadcast_task.go
  internal/rootcoord/dml_channels.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
  internal/streamingcoord/client/client.go
  internal/streamingcoord/client/client_impl.go
  internal/streamingcoord/server/broadcaster/broadcaster.go
  internal/streamingcoord/server/broadcaster/broadcaster_impl.go
  internal/streamingcoord/server/broadcaster/broadcaster_test.go
  internal/streamingcoord/server/broadcaster/registry/append_operator.go
  internal/streamingcoord/server/broadcaster/registry/test_utility.go
  internal/streamingcoord/server/broadcaster/task.go
  internal/streamingcoord/server/server.go
  internal/util/streamingutil/util/wal_selector.go
  internal/util/streamingutil/util/wal_selector_test.go
  pkg/streaming/util/message/adaptor/broadcast_message.go
  pkg/streaming/util/types/responses.go
  pkg/streaming/util/types/streaming_node.go
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/component_param_test.go
  tests/integration/coorddownsearch/search_after_coord_down_test.go
  tests/integration/coordrecovery/coord_recovery_test.go
  tests/integration/suite.go
Labels: kind/enhancement, sig/testing, size/XL, approved, lgtm, area/test, ci-passed, dco-passed, test/integration

#39040 enhance: add broadcast operation for msgstream
  cmd/roles/roles.go
  configs/milvus.yaml
  internal/distributed/streaming/streaming.go
  internal/distributed/streaming/streaming_test.go
  internal/distributed/streaming/util.go
  internal/distributed/streaming/wal.go
  internal/rootcoord/broadcast_task.go
  internal/rootcoord/dml_channels.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
  internal/streamingcoord/client/client.go
  internal/streamingcoord/client/client_impl.go
  internal/streamingcoord/server/broadcaster/broadcaster.go
  internal/streamingcoord/server/broadcaster/broadcaster_impl.go
  internal/streamingcoord/server/broadcaster/broadcaster_test.go
  internal/streamingcoord/server/broadcaster/registry/append_operator.go
  internal/streamingcoord/server/broadcaster/registry/test_utility.go
  internal/streamingcoord/server/broadcaster/task.go
  internal/streamingcoord/server/server.go
  pkg/streaming/util/message/adaptor/broadcast_message.go
  pkg/streaming/util/types/responses.go
  pkg/streaming/util/types/streaming_node.go
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/component_param_test.go
  tests/integration/coorddownsearch/search_after_coord_down_test.go
  tests/integration/coordrecovery/coord_recovery_test.go
  tests/integration/suite.go
Labels: kind/enhancement, sig/testing, size/XL, approved, lgtm, area/test, ci-passed, dco-passed, test/integration

#39222 enhance: Add primary field name in SearchResult and QueryResults
  client/go.mod
  client/go.sum
  go.mod
  go.sum
  internal/proxy/task_query.go
  internal/proxy/task_search.go
  pkg/go.mod
  pkg/go.sum
  tests/go_client/go.mod
  tests/go_client/go.sum
Labels: kind/enhancement, area/dependency, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#39244 doc: Update tools info
  docs/design_docs/segcore/scripts_and_tools.md
Labels: size/XS, approved, lgtm, ci-passed, dco-passed, kind/doc

#39237 enhance: [2.5][bitset] extend op_find() to be able to search both 0 and 1
  internal/core/src/bitset/CMakeLists.txt
  internal/core/src/bitset/bitset.h
  internal/core/src/bitset/detail/bit_wise.h
  internal/core/src/bitset/detail/element_vectorized.h
  internal/core/src/bitset/detail/element_wise.h
  internal/core/src/bitset/detail/proxy.h
  internal/core/src/segcore/ChunkedSegmentSealedImpl.cpp
  internal/core/src/segcore/SegmentSealedImpl.cpp
  internal/core/unittest/test_bitset.cpp
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed, area/compilation

#39200 fix: channel unbalance during stopping balance progress (#38971)
  internal/querycoordv2/balance/balance.go
  internal/querycoordv2/balance/rowcount_based_balancer.go
  internal/querycoordv2/balance/score_based_balancer.go
  internal/querycoordv2/balance/score_based_balancer_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#38907 enhance: [2.5] Optimize GetLocalDiskSize and segment loader mutex
  internal/querynodev2/segments/disk_usage_fetcher.go
  internal/querynodev2/segments/segment.go
  internal/querynodev2/segments/segment_loader.go
  internal/querynodev2/segments/segment_loader_test.go
  internal/querynodev2/server.go
  internal/util/segcore/cgo_util.go
  internal/util/segcore/cgo_util_test.go
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/component_param_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#38990 feat: Support Int8Vector in go
  client/entity/field.go
  go.mod
  go.sum
  internal/core/src/common/Types.h
  internal/core/src/index/IndexFactory.cpp
  internal/core/src/index/Utils.cpp
  internal/core/src/index/Utils.h
  internal/core/src/index/VectorMemIndex.cpp
  internal/core/src/indexbuilder/IndexFactory.h
  internal/core/src/indexbuilder/index_c.cpp
  internal/core/src/indexbuilder/index_c.h
  internal/core/src/segcore/vector_index_c.cpp
  internal/proxy/task_index.go
  internal/proxy/validate_util.go
  internal/proxy/validate_util_test.go
  internal/storage/data_codec.go
  internal/storage/data_codec_test.go
  internal/storage/insert_data.go
  internal/storage/insert_data_test.go
  internal/storage/payload.go
  internal/storage/payload_reader.go
  internal/storage/payload_writer.go
  internal/storage/utils.go
  internal/storage/utils_test.go
  internal/util/clustering/clustering.go
  internal/util/indexcgowrapper/codec_index_test.go
  internal/util/indexcgowrapper/dataset.go
  internal/util/indexcgowrapper/index.go
  internal/util/indexcgowrapper/index_test.go
  internal/util/indexparamcheck/constraints.go
  internal/util/indexparamcheck/vector_index_checker.go
  internal/util/indexparamcheck/vector_index_checker_test.go
  internal/util/testutil/test_util.go
  internal/util/typeutil/result_helper_test.go
  internal/util/typeutil/schema.go
  internal/util/typeutil/schema_test.go
  internal/util/typeutil/storage.go
  internal/util/vecindexmgr/vector_index_mgr.go
  pkg/go.mod
  pkg/go.sum
  pkg/util/funcutil/func.go
  pkg/util/funcutil/func_test.go
  pkg/util/funcutil/placeholdergroup.go
  pkg/util/funcutil/placeholdergroup_test.go
  pkg/util/paramtable/autoindex_param.go
  pkg/util/testutils/gen_data.go
  pkg/util/typeutil/convension.go
  pkg/util/typeutil/gen_empty_field_data.go
  pkg/util/typeutil/schema.go
  pkg/util/typeutil/schema_test.go
Labels: kind/feature, area/dependency, sig/testing, size/XXL, approved, lgtm, area/test, ci-passed, dco-passed, area/compilation

#38908 enhance: [2.4] Optimize GetLocalDiskSize and segment loader mutex
  internal/querynodev2/segments/disk_usage_fetcher.go
  internal/querynodev2/segments/segment.go
  internal/querynodev2/segments/segment_loader.go
  internal/querynodev2/segments/segment_loader_test.go
  internal/querynodev2/server.go
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/component_param_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#38219 enhance: Reduce mutex contention in datacoord meta
  internal/datacoord/compaction_policy_clustering.go
  internal/datacoord/compaction_policy_single.go
  internal/datacoord/compaction_policy_single_test.go
  internal/datacoord/compaction_trigger.go
  internal/datacoord/compaction_trigger_test.go
  internal/datacoord/meta.go
  internal/datacoord/meta_test.go
  internal/datacoord/segment_info.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed, 10kcp

#38129 enhance: Reduce memory usage of BF in DataNode and QueryNode
  internal/flushcommon/writebuffer/l0_write_buffer.go
  internal/flushcommon/writebuffer/l0_write_buffer_test.go
  internal/querynodev2/segments/segment.go
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/component_param_test.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed, 10kcp

#39216 enhance: fix inconsistenty of alias and db for query iterator(#39045)
  internal/proxy/search_util.go
  internal/proxy/task.go
  internal/proxy/task_query.go
  internal/proxy/task_query_test.go
  internal/proxy/task_search.go
  internal/proxy/task_search_test.go
Labels: kind/enhancement, area/dependency, size/L, approved, lgtm, ci-passed, dco-passed, area/compilation

#38925 fix: Record a map to avoid repeatedly traversing the CompactionFrom
  internal/datacoord/handler.go
  internal/datacoord/handler_test.go
  internal/datacoord/index_service.go
Labels: kind/bug, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#38926 fix: [2.5] Record a map to avoid repeatedly traversing the CompactionFrom
  internal/datacoord/handler.go
  internal/datacoord/handler_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#39248 enhance: fix inconsistenty of alias and db for query iterator(#39045)
  internal/proxy/search_util.go
  internal/proxy/task.go
  internal/proxy/task_query.go
  internal/proxy/task_query_test.go
  internal/proxy/task_search.go
  internal/proxy/task_search_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#39261 fix: wrong streaming mockery package name
  internal/streamingcoord/client/assignment/assignment_test.go
  internal/streamingcoord/server/service/discover/discover_server_test.go
  internal/streamingnode/client/handler/consumer/consumer_test.go
  internal/streamingnode/client/handler/handler_client_test.go
  internal/streamingnode/client/handler/producer/producer_test.go
  internal/streamingnode/client/manager/manager_test.go
  internal/streamingnode/server/service/handler/consumer/consume_server_test.go
  internal/streamingnode/server/service/handler/producer/produce_server_test.go
  pkg/mocks/proto/mock_streamingpb/mock_StreamingCoordAssignmentServiceClient.go
  pkg/mocks/proto/mock_streamingpb/mock_StreamingCoordAssignmentService_AssignmentDiscoverClient.go
  pkg/mocks/proto/mock_streamingpb/mock_StreamingCoordAssignmentService_AssignmentDiscoverServer.go
  pkg/mocks/proto/mock_streamingpb/mock_StreamingNodeHandlerServiceClient.go
  pkg/mocks/proto/mock_streamingpb/mock_StreamingNodeHandlerService_ConsumeClient.go
  pkg/mocks/proto/mock_streamingpb/mock_StreamingNodeHandlerService_ConsumeServer.go
  pkg/mocks/proto/mock_streamingpb/mock_StreamingNodeHandlerService_ProduceClient.go
  pkg/mocks/proto/mock_streamingpb/mock_StreamingNodeHandlerService_ProduceServer.go
  pkg/mocks/proto/mock_streamingpb/mock_StreamingNodeManagerServiceClient.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#39204 fix: Add scalar index engine version for compatibility
  internal/datacoord/index_engine_version_manager.go
  internal/datacoord/index_engine_version_manager_test.go
  internal/datacoord/index_meta.go
  internal/datacoord/mock_index_engine_version_manager.go
  internal/datacoord/task_index.go
  internal/indexnode/indexnode.go
  internal/indexnode/indexnode_service.go
  internal/indexnode/indexnode_test.go
  internal/indexnode/task_index.go
  internal/indexnode/taskinfo_ops.go
  internal/metastore/model/segment_index.go
  internal/querynodev2/server.go
  internal/util/sessionutil/session_util.go
  pkg/common/common.go
  pkg/proto/index_cgo_msg.proto
  pkg/proto/index_coord.proto
  pkg/proto/indexcgopb/index_cgo_msg.pb.go
  pkg/proto/indexpb/index_coord.pb.go
  pkg/proto/worker.proto
  pkg/proto/workerpb/worker.pb.go
Labels: kind/bug, size/XXL, approved, lgtm, ci-passed, area/internal-api, dco-passed

#39161 fix: unstable ut in leader_vew_manager.go file
  internal/querycoordv2/meta/leader_view_manager.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#39051 enhance: Remove mutex from SegmentManger in querynode
  internal/querynodev2/segments/manager.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#38913 enhance: [2.5] Reduce memory usage of BF in DataNode and QueryNode
  internal/flushcommon/writebuffer/l0_write_buffer.go
  internal/flushcommon/writebuffer/l0_write_buffer_test.go
  internal/querynodev2/segments/segment.go
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/component_param_test.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#39121 enhance: simplify compaction tasks to reduce their memory overhead
  internal/datacoord/compaction.go
  internal/datacoord/compaction_task.go
  internal/datacoord/compaction_task_clustering.go
  internal/datacoord/compaction_task_l0.go
  internal/datacoord/compaction_task_l0_test.go
  internal/datacoord/compaction_task_mix.go
  internal/datacoord/compaction_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#38599 enhance: Optimize GetLocalDiskSize and segment loader mutex
  internal/querynodev2/segments/disk_usage_fetcher.go
  internal/querynodev2/segments/segment.go
  internal/querynodev2/segments/segment_loader.go
  internal/querynodev2/server.go
  internal/util/segcore/cgo_util.go
  internal/util/segcore/cgo_util_test.go
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/component_param_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed, 10kcp

#39260 fix: wrong streaming mockery package name
  internal/streamingcoord/client/assignment/assignment_test.go
  internal/streamingcoord/server/service/discover/discover_server_test.go
  internal/streamingnode/client/handler/consumer/consumer_test.go
  internal/streamingnode/client/handler/handler_client_test.go
  internal/streamingnode/client/handler/producer/producer_test.go
  internal/streamingnode/client/manager/manager_test.go
  internal/streamingnode/server/service/handler/consumer/consume_server_test.go
  internal/streamingnode/server/service/handler/producer/produce_server_test.go
  pkg/mocks/proto/mock_streamingpb/mock_StreamingCoordAssignmentServiceClient.go
  pkg/mocks/proto/mock_streamingpb/mock_StreamingCoordAssignmentService_AssignmentDiscoverClient.go
  pkg/mocks/proto/mock_streamingpb/mock_StreamingCoordAssignmentService_AssignmentDiscoverServer.go
  pkg/mocks/proto/mock_streamingpb/mock_StreamingNodeHandlerServiceClient.go
  pkg/mocks/proto/mock_streamingpb/mock_StreamingNodeHandlerService_ConsumeClient.go
  pkg/mocks/proto/mock_streamingpb/mock_StreamingNodeHandlerService_ConsumeServer.go
  pkg/mocks/proto/mock_streamingpb/mock_StreamingNodeHandlerService_ProduceClient.go
  pkg/mocks/proto/mock_streamingpb/mock_StreamingNodeHandlerService_ProduceServer.go
  pkg/mocks/proto/mock_streamingpb/mock_StreamingNodeManagerServiceClient.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#39120 test:Add search Iterator v2 test case for milvus client
  tests/python_client/base/client_v2_base.py
  tests/python_client/milvus_client/test_milvus_client_rbac.py
  tests/python_client/milvus_client/test_milvus_client_search_interator.py
Labels: sig/testing, size/XL, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#39208 enhance: Add logs for check health failed
  internal/datacoord/server.go
  internal/datacoord/services.go
  internal/http/healthz/healthz_handler.go
  internal/querycoordv2/server.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#39279 enhance: Add try-catch and return CStatus for NewCollection
  internal/core/src/segcore/collection_c.cpp
  internal/core/src/segcore/collection_c.h
  internal/util/segcore/collection.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#39258 enhance: refactor delete mvcc function (#38066)
  internal/core/src/segcore/DeletedRecord.h
  internal/core/src/segcore/SegmentGrowingImpl.cpp
  internal/core/src/segcore/SegmentGrowingImpl.h
  internal/core/src/segcore/SegmentInterface.h
  internal/core/src/segcore/SegmentSealed.h
  internal/core/src/segcore/SegmentSealedImpl.cpp
  internal/core/src/segcore/SegmentSealedImpl.h
  internal/core/src/segcore/Utils.h
  internal/core/unittest/test_c_api.cpp
  internal/core/unittest/test_delete_record.cpp
  internal/core/unittest/test_growing.cpp
  internal/core/unittest/test_sealed.cpp
  internal/core/unittest/test_utils.cpp
Labels: kind/enhancement, size/XXL, approved, lgtm, ci-passed, dco-passed, kind/branch-feature
