Repository milvus-io/milvus, pull requests merged in 2025-08, with the labels that each got.

#43652 enhance: enable storage v2 by default
  configs/milvus.yaml
  internal/core/CMakeLists.txt
  internal/datanode/compactor/clustering_compactor_test.go
  internal/datanode/compactor/mix_compactor_test.go
  internal/datanode/compactor/sort_compaction_test.go
  internal/storage/serde.go
  tests/integration/compaction/clustering_compaction_null_data_test.go
  tests/integration/compaction/clustering_compaction_test.go
  tests/integration/compaction/mix_compaction_test.go
  tests/integration/datanode/struct_array_test.go
  tests/integration/import/binlog_test.go
  tests/integration/stats_task/stats_task_test.go
Labels: kind/enhancement, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed, area/compilation, test/integration

#43669 enhance: Ignore entry with same ts when DeleteRecord search pks
  internal/core/src/segcore/ChunkedSegmentSealedImpl.cpp
  internal/core/src/segcore/ChunkedSegmentSealedImpl.h
  internal/core/src/segcore/InsertRecord.h
  internal/core/src/segcore/SegmentGrowingImpl.cpp
  internal/core/src/segcore/SegmentGrowingImpl.h
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#43546 enhance: unlink mmap file when chunk and index are destructed
  internal/core/src/common/Chunk.h
  internal/core/src/common/ChunkWriter.cpp
  internal/core/src/common/ChunkWriter.h
  internal/core/src/common/File.h
  internal/core/src/index/BitmapIndex.cpp
  internal/core/src/index/Index.h
  internal/core/src/index/StringIndexMarisa.cpp
  internal/core/src/index/VectorMemIndex.cpp
  internal/core/src/mmap/Column.h
  internal/core/src/segcore/ChunkedSegmentSealedImpl.cpp
  internal/core/src/segcore/SegmentSealedImpl.cpp
  internal/core/src/storage/ChunkCache.cpp
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#43674 fix: fix miss loading index for storagev2
  internal/querynodev2/segments/segment_loader.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#43685 fix: fix disk path sent to cachinglayer
  internal/querynodev2/server.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#43679 fix: increment offset for null data rows in JsonKeyStats
  internal/core/src/index/JsonKeyStatsInvertedIndex.cpp
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#43699 fix: Fix compaction failed due to ID exhausted
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/component_param_test.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#43323 enhance: tiered storage: estimate segment loading resource usage while considering eviction
  configs/milvus.yaml
  internal/querynodev2/delegator/delegator_data.go
  internal/querynodev2/segments/manager.go
  internal/querynodev2/segments/manager_test.go
  internal/querynodev2/segments/mock_segment_manager.go
  internal/querynodev2/segments/retrieve_test.go
  internal/querynodev2/segments/search_test.go
  internal/querynodev2/segments/segment.go
  internal/querynodev2/segments/segment_loader.go
  internal/querynodev2/segments/segment_test.go
  internal/querynodev2/server_test.go
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#43675 enhance: add internal writer without session lock
  go.mod
  go.sum
  pkg/go.mod
  pkg/go.sum
Labels: kind/enhancement, area/dependency, size/S, approved, lgtm, ci-passed, dco-passed

#43695 enhance: Pass callback in search batch pks to void large result
  internal/core/src/segcore/ChunkedSegmentSealedImpl.cpp
  internal/core/src/segcore/ChunkedSegmentSealedImpl.h
  internal/core/src/segcore/DeletedRecord.h
  internal/core/src/segcore/SegmentGrowingImpl.cpp
  internal/core/src/segcore/SegmentGrowingImpl.h
  internal/core/unittest/bench/bench_applyhits.cpp
  internal/core/unittest/bench/bench_filewrite.cpp
  internal/core/unittest/bench/bench_findfirst.cpp
  internal/core/unittest/bench/bench_search_pk.cpp
  internal/core/unittest/test_chunked_segment.cpp
  internal/core/unittest/test_delete_record.cpp
  internal/core/unittest/test_utils.cpp
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#43688 fix: increment offset for invalid data rows in JsonKeyStatsInvertedIndex
  internal/core/src/index/JsonKeyStatsInvertedIndex.cpp
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#43300 enhance: [2.5] Remove collection name validation from DescribeCollection
  internal/proxy/task.go
  internal/proxy/task_test.go
  tests/go_client/testcases/search_test.go
  tests/python_client/milvus_client/test_milvus_client_collection.py
  tests/python_client/milvus_client/test_milvus_client_insert.py
Labels: kind/enhancement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed, do-not-merge/need-merge-master-first

#43705 fix: try to get span raw data for variable length data type(#43544)
  internal/core/src/common/Chunk.h
  internal/core/src/exec/expression/Expr.h
  internal/core/src/exec/expression/JsonContainsExpr.cpp
  internal/core/src/mmap/ChunkedColumn.h
  internal/core/src/mmap/ChunkedColumnGroup.h
  internal/core/src/mmap/ChunkedColumnInterface.h
  internal/core/src/segcore/ChunkedSegmentSealedImpl.cpp
  internal/core/src/segcore/ChunkedSegmentSealedImpl.h
  internal/core/src/segcore/SegmentGrowingImpl.cpp
  internal/core/src/segcore/SegmentGrowingImpl.h
  internal/core/src/segcore/SegmentInterface.h
  internal/querynodev2/segments/segment.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#43367 test: add more testcase for analyzer
  tests/python_client/milvus_client/test_milvus_client_analyzer.py
Labels: kind/improvement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#43703 fix: try to get span raw data for variable length data type(#43544)
  internal/core/src/common/Chunk.h
  internal/core/src/exec/expression/Expr.h
  internal/core/src/exec/expression/JsonContainsExpr.cpp
  internal/core/src/mmap/ChunkedColumn.h
  internal/core/src/mmap/Column.h
  internal/core/src/segcore/ChunkedSegmentSealedImpl.cpp
  internal/core/src/segcore/ChunkedSegmentSealedImpl.h
  internal/core/src/segcore/SegmentGrowingImpl.cpp
  internal/core/src/segcore/SegmentGrowingImpl.h
  internal/core/src/segcore/SegmentInterface.h
  internal/core/src/segcore/SegmentSealedImpl.cpp
  internal/core/src/segcore/SegmentSealedImpl.h
  internal/querynodev2/segments/segment.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#43686 enhance: Bump milvus & proto version to v2.5.16
  client/go.mod
  client/go.sum
  go.mod
  go.sum
  pkg/common/version.go
  pkg/go.mod
  pkg/go.sum
  tests/go_client/go.mod
  tests/go_client/go.sum
Labels: kind/enhancement, area/dependency, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed, kind/branch-feature

#43713 enhance: [StorageV2] Update enablev2 default param value
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#43727 test: add rust to source code megrify rule
  .github/mergify.yml
Labels: size/XS, approved, lgtm, ci-passed, dco-passed, kind/test

#43718 fix: jieba tokenizer cause panic when dict word was empty string (#43337)
  internal/core/thirdparty/tantivy/tantivy-binding/src/analyzer/tokenizers/jieba_tokenizer.rs
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#43720 fix: skip load raw data when loading index for storagev2
  internal/querynodev2/segments/segment_loader.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#43723 enhance: update cachinglayer default cache ratio to 0.3
  configs/milvus.yaml
  internal/querynodev2/segments/segment.go
  internal/querynodev2/segments/segment_loader.go
  internal/querynodev2/server.go
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#43717 test: update partial load case due to server behavior changing
  tests/go_client/testcases/load_release_test.go
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, manual-pass, kind/test

#43735 fix: Reorder worker proto fields to ensure compatibility
  configs/milvus.yaml
  internal/datanode/index_services.go
  pkg/proto/worker.proto
  pkg/proto/workerpb/worker.pb.go
  pkg/util/paramtable/component_param.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#43730 enhance: Add test target to Makefile and test script
  Makefile
  scripts/run_go_unittest.sh
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed, area/compilation

#43732 enhance: [GoSDK] Support limit for search iterator
  client/milvusclient/iterator.go
  client/milvusclient/iterator_option.go
  client/milvusclient/iterator_test.go
  client/milvusclient/results.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#43736 enhance: Add assertion preventing reload same field
  internal/core/src/segcore/ChunkedSegmentSealedImpl.cpp
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#43684 test: add create collection V2 cases for milvus client
  tests/python_client/milvus_client/test_milvus_client_collection.py
  tests/python_client/testcases/test_collection.py
Labels: sig/testing, size/XXL, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#43747 enhance: Add timestamp filtering support to L0Reader
  internal/datanode/data_node_test.go
  internal/datanode/importv2/task_l0_import.go
  internal/datanode/importv2/task_l0_preimport.go
  internal/util/importutilv2/binlog/filter.go
  internal/util/importutilv2/binlog/l0_reader.go
  internal/util/importutilv2/binlog/l0_reader_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#43769 test: bump standalone_embed.bat
  .github/workflows/bump-version-only-for-standalone-embed-milvus.yaml
Labels: size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass, kind/test

#43772 enhance: [skip e2e] Enhance standalone_embed add DEPLOY_MODE=STANDALONE
  scripts/standalone_embed.bat
  scripts/standalone_embed.sh
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#43768 enhance: Improve delegator serviceable check logic in PinReadableSegments
  internal/querynodev2/delegator/distribution.go
  internal/querynodev2/delegator/distribution_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#43774 enhance: [GoSDK] Add param static check for search iterator
  client/milvusclient/iterator.go
  client/milvusclient/iterator_option.go
  client/milvusclient/iterator_test.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#43790 enhance: [StorageV2] Avoid create local parent dir if fs remote
  internal/core/thirdparty/milvus-storage/CMakeLists.txt
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed, area/compilation

#43231 enhance: make segcore params effective without restarting milvus
  internal/core/src/common/Common.cpp
  internal/core/src/common/Common.h
  internal/core/src/common/Slice.cpp
  internal/core/src/common/init_c.cpp
  internal/core/src/common/init_c.h
  internal/core/src/exec/QueryContext.h
  internal/core/src/exec/expression/Expr.cpp
  internal/core/src/segcore/memory_planner.cpp
  internal/core/src/storage/DiskFileManagerImpl.cpp
  internal/core/src/storage/ThreadPools.cpp
  internal/core/unittest/test_exec.cpp
  internal/core/unittest/test_expr.cpp
  internal/datanode/index/init_segcore.go
  internal/querynodev2/server.go
  pkg/util/paramtable/autoindex_param_test.go
  pkg/util/paramtable/base_table.go
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/param_item.go
  pkg/util/paramtable/param_item_callback_test.go
  pkg/util/paramtable/util.go
Labels: kind/enhancement, size/XL, approved, lgtm, ci-passed, dco-passed

#43766 enhance: add file resource api
  go.mod
  go.sum
  internal/allocator/global_id_allocator.go
  internal/coordinator/mix_coord.go
  internal/datacoord/import_checker_test.go
  internal/datacoord/import_inspector_test.go
  internal/datacoord/import_util_test.go
  internal/datacoord/meta.go
  internal/datacoord/meta_test.go
  internal/datacoord/mock_test.go
  internal/datacoord/services.go
  internal/datacoord/services_test.go
  internal/distributed/mixcoord/client/client.go
  internal/distributed/mixcoord/service.go
  internal/distributed/proxy/service.go
  internal/metastore/catalog.go
  internal/metastore/kv/datacoord/constant.go
  internal/metastore/kv/datacoord/kv_catalog.go
  internal/metastore/kv/rootcoord/kv_catalog.go
  internal/metastore/mocks/mock_datacoord_catalog.go
  internal/metastore/mocks/mock_rootcoord_catalog.go
  internal/metastore/model/resource.go
  internal/mocks/mock_datacoord.go
  internal/mocks/mock_datacoord_client.go
  internal/mocks/mock_mixcoord.go
  internal/mocks/mock_mixcoord_client.go
  internal/mocks/mock_proxy.go
  internal/proxy/impl.go
  internal/proxy/impl_test.go
  internal/proxy/rootcoord_mock_test.go
  pkg/go.mod
  pkg/go.sum
  pkg/proto/data_coord.proto
  pkg/proto/datapb/data_coord.pb.go
  pkg/proto/datapb/data_coord_grpc.pb.go
Labels: kind/enhancement, area/dependency, size/XXL, approved, lgtm, ci-passed, dco-passed

#43789 enhance: update nightly helm chart version to 5.0.0[2.6]
  ci/jenkins/Nightly2.groovy
  ci/jenkins/PR-Arm.groovy
  ci/jenkins/PR-for-go-sdk.groovy
  ci/jenkins/PR.groovy
  ci/jenkins/PRGPU.groovy
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed, manual-pass, do-not-merge/need-milestone

#43805 test: add create collection V2 cases for milvus client
  tests/python_client/milvus_client/test_milvus_client_collection.py
  tests/python_client/testcases/test_collection.py
Labels: sig/testing, size/XL, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#43792 enhance: [2.5][GoSDK] Cherry pick commits for v2.5.6 and bump version
  client/common/version.go
  client/milvusclient/iterator.go
  client/milvusclient/iterator_option.go
  client/milvusclient/iterator_test.go
  client/milvusclient/results.go
  tests/go_client/base/milvus_client.go
  tests/go_client/common/consts.go
  tests/go_client/common/response_checker.go
  tests/go_client/common/utils.go
  tests/go_client/testcases/helper/read_helper.go
  tests/go_client/testcases/search_iterator_test.go
Labels: kind/enhancement, sig/testing, size/XXL, approved, lgtm, area/test, ci-passed, dco-passed

#43827 test: add testcases for import enhancement in 2.6
  tests/restful_client_v2/requirements.txt
  tests/restful_client_v2/testcases/test_jobs_operation.py
Labels: kind/improvement, sig/testing, size/XL, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#43832 fix: [2.5] Use `proto.Equal` to compare default value of field (#43813)
  internal/metastore/model/field.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#43855 fix: fix delete consumer bug for cocurrency R-W (#43831)
  internal/core/src/monitor/prometheus_client.cpp
  internal/core/src/monitor/prometheus_client.h
  internal/core/src/segcore/DeletedRecord.h
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#43829 enhance: Implement rewatch mechanism for etcd failure scenarios
  internal/datacoord/cluster.go
  internal/datacoord/cluster_test.go
  internal/datacoord/index_engine_version_manager.go
  internal/datacoord/index_engine_version_manager_test.go
  internal/datacoord/server.go
  internal/datacoord/server_test.go
  internal/datacoord/session/mock_node_manager.go
  internal/datacoord/session/node_manager.go
  internal/datacoord/session/node_manager_test.go
  internal/querycoordv2/dist/dist_handler.go
  internal/querycoordv2/dist/dist_handler_test.go
  internal/querycoordv2/server.go
  internal/querycoordv2/server_test.go
  internal/querycoordv2/services_test.go
  pkg/metrics/querycoord_metrics.go
Labels: kind/enhancement, size/XXL, approved, lgtm, ci-passed, dco-passed

#43808 fix: Metrics with collectionName but no databaseName label are causing name conflicts and confusion (#43277)
  go.sum
  internal/proxy/impl.go
  internal/rootcoord/quota_center.go
  pkg/metrics/grpc_stats_handler.go
  pkg/metrics/proxy_metrics.go
  pkg/metrics/restful_middleware.go
  pkg/metrics/rootcoord_metrics.go
  pkg/util/paramtable/component_param.go
Labels: kind/bug, area/dependency, size/L, approved, lgtm, ci-passed, dco-passed

#43779 enhance: [StorageV2] zero copy for packed writer record batch
  internal/core/src/segcore/packed_writer_c.cpp
  internal/core/src/segcore/packed_writer_c.h
  internal/core/unittest/test_packed_c.cpp
  internal/storagev2/packed/packed_writer.go
  tests/integration/getvector/array_struct_test.go
Labels: kind/enhancement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, area/compilation, test/integration

#43874 enhance: Add downgrade tsafe switch param item
  internal/querynodev2/delegator/delegator.go
  internal/querynodev2/delegator/delegator_test.go
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#43877 test: remove skip for fixed case
  tests/restful_client_v2/testcases/test_vector_operations.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#43833 enhance: better auto-detect of SVE options for the bitset library
  internal/core/src/bitset/CMakeLists.txt
  internal/core/src/bitset/detail/platform/arm/sve-inst.cpp
  internal/core/src/bitset/detail/platform/dynamic.cpp
  internal/core/unittest/CMakeLists.txt
  internal/core/unittest/test_bitset.cpp
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed, area/compilation

#43824 enhance: Support streaming read and write of vector index files
  internal/core/src/index/VectorDiskIndex.cpp
  internal/core/src/segcore/DeletedRecord.h
  internal/core/src/storage/ChunkManager.h
  internal/core/src/storage/DiskFileManagerImpl.cpp
  internal/core/src/storage/DiskFileManagerImpl.h
  internal/core/src/storage/FileManager.h
  internal/core/src/storage/LocalChunkManager.h
  internal/core/src/storage/MemFileManagerImpl.cpp
  internal/core/src/storage/MemFileManagerImpl.h
  internal/core/src/storage/MinioChunkManager.h
  internal/core/src/storage/RemoteInputStream.cpp
  internal/core/src/storage/RemoteInputStream.h
  internal/core/src/storage/RemoteOutputStream.cpp
  internal/core/src/storage/RemoteOutputStream.h
  internal/core/src/storage/ThreadPool.h
  internal/core/src/storage/azure/AzureChunkManager.h
  internal/core/src/storage/gcp-native-storage/GcpNativeChunkManager.h
  internal/core/src/storage/opendal/OpenDALChunkManager.h
  internal/core/thirdparty/CMakeLists.txt
  internal/core/thirdparty/knowhere/CMakeLists.txt
  internal/core/thirdparty/milvus-common/CMakeLists.txt
  internal/core/unittest/test_disk_file_manager_test.cpp
  internal/core/unittest/test_exec.cpp
Labels: kind/enhancement, size/XL, approved, lgtm, ci-passed, dco-passed, area/compilation

#43879 test: new cases for goclient nullable and default value
  tests/go_client/common/response_checker.go
  tests/go_client/testcases/collection_test.go
  tests/go_client/testcases/database_test.go
  tests/go_client/testcases/full_text_search_test.go
  tests/go_client/testcases/helper/collection_helper.go
  tests/go_client/testcases/helper/data_helper.go
  tests/go_client/testcases/helper/field_helper.go
  tests/go_client/testcases/helper/helper.go
  tests/go_client/testcases/helper/rows_helper.go
  tests/go_client/testcases/index_test.go
  tests/go_client/testcases/nullable_default_value_test.go
  tests/go_client/testcases/phrase_match_test.go
  tests/go_client/testcases/search_iterator_test.go
  tests/go_client/testcases/text_embedding_test.go
  tests/go_client/testcases/upsert_test.go
Labels: sig/testing, size/XXL, approved, lgtm, area/test, ci-passed, dco-passed, manual-pass, kind/test

#43835 enhance: Improve error message when query vector and dim mismatch
  internal/core/src/query/Plan.cpp
Labels: kind/enhancement, kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#43811 fix: add segment lock in LoadTextIndex and LoadJSONKeyIndex
  internal/querynodev2/segments/segment.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#43881 enhance: support util template generation for messages
  Makefile
  internal/streamingnode/server/flusher/flusherimpl/msg_handler_impl_test.go
  internal/streamingnode/server/wal/interceptors/shard/shard_interceptor.go
  internal/streamingnode/server/wal/recovery/recovery_storage_impl.go
  internal/streamingnode/server/wal/recovery/vchannel_recovery_info_test.go
  pkg/go.mod
  pkg/go.sum
  pkg/mocks/streaming/util/mock_message/mock_BroadcastMutableMessage.go
  pkg/mocks/streaming/util/mock_message/mock_ImmutableMessage.go
  pkg/mocks/streaming/util/mock_message/mock_ImmutableTxnMessage.go
  pkg/mocks/streaming/util/mock_message/mock_MutableMessage.go
  pkg/streaming/util/message/adaptor/ts_msg_newer.go
  pkg/streaming/util/message/builder.go
  pkg/streaming/util/message/codegen/codegen_test.go
  pkg/streaming/util/message/codegen/main.go
  pkg/streaming/util/message/codegen/reflect_info.json
  pkg/streaming/util/message/marshal_log_object.go
  pkg/streaming/util/message/message.go
  pkg/streaming/util/message/message_impl.go
  pkg/streaming/util/message/message_test.go
  pkg/streaming/util/message/message_type.go
  pkg/streaming/util/message/reflect_info.go
  pkg/streaming/util/message/specialized_message.go
  pkg/streaming/util/message/utils.go
Labels: kind/enhancement, area/dependency, size/XXL, approved, lgtm, ci-passed, dco-passed, area/compilation

#43786 feat:add BatchDescribeCollection interface
  client/go.mod
  client/go.sum
  client/milvusclient/mock_milvus_server_test.go
  go.mod
  go.sum
  internal/distributed/proxy/service.go
  internal/distributed/proxy/service_test.go
  internal/mocks/mock_proxy.go
  internal/proxy/database_interceptor.go
  internal/proxy/database_interceptor_test.go
  internal/proxy/impl.go
  internal/proxy/impl_test.go
  internal/proxy/task.go
  internal/rootcoord/show_collection_task.go
  internal/rootcoord/show_collection_task_test.go
  pkg/go.mod
  pkg/go.sum
  tests/go_client/go.mod
  tests/go_client/go.sum
Labels: kind/feature, area/dependency, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#43926 fix: empty error returned on append timeout when MinIO is unavailable
  go.mod
  go.sum
  pkg/go.mod
  pkg/go.sum
  pkg/streaming/walimpls/impls/wp/wal.go
Labels: kind/bug, area/dependency, size/S, approved, lgtm, ci-passed, dco-passed

#43916 enhance: upgrade aws-sdk from 1.9.234 to 1.11.352
  internal/core/conanfile.py
  internal/core/src/storage/AliyunSTSClient.cpp
  internal/core/src/storage/TencentCloudSTSClient.cpp
  internal/core/thirdparty/milvus-storage/CMakeLists.txt
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed, area/compilation

#43903 enhance: [2.5] avoid frequent LoadWithPrefix etcd calls in ShowCollections and DescribeCollections
  internal/rootcoord/describe_collection_task_test.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/show_collection_task_test.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#43891 test: add rerank function testcases in go client
  client/entity/function.go
  client/entity/function_test.go
  tests/go_client/testcases/helper/test_setup.go
  tests/go_client/testcases/reranker_function_test.go
Labels: kind/improvement, sig/testing, size/XL, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#43868 feat: support use score function on segment search and use filter
  internal/core/src/exec/Driver.cpp
  internal/core/src/exec/operator/RescoresNode.cpp
  internal/core/src/exec/operator/RescoresNode.h
  internal/core/src/exec/operator/Utils.h
  internal/core/src/plan/PlanNode.h
  internal/core/src/query/PlanProto.cpp
  internal/core/src/query/PlanProto.h
  internal/core/src/rescores/Scorer.h
  internal/parser/planparserv2/plan_parser_v2.go
  internal/parser/planparserv2/plan_parser_v2_test.go
  internal/proxy/task_search.go
  internal/util/exprutil/expr_checker_test.go
  internal/util/function/rerank/decay_function.go
  internal/util/function/rerank/function_score.go
  internal/util/function/rerank/function_score_test.go
  internal/util/function/rerank/model_function.go
  internal/util/function/rerank/rrf_function.go
  internal/util/function/rerank/weighted_function.go
  pkg/proto/plan.proto
  pkg/proto/planpb/plan.pb.go
  pkg/util/funcutil/func.go
Labels: kind/feature, size/XL, approved, lgtm, ci-passed, dco-passed

#43928 enhance: Cp sve support for bitset
  internal/core/src/bitset/CMakeLists.txt
  internal/core/src/bitset/detail/platform/arm/sve-inst.cpp
  internal/core/src/bitset/detail/platform/dynamic.cpp
  internal/core/unittest/CMakeLists.txt
  internal/core/unittest/test_bitset.cpp
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed, area/compilation

#43795 fix: Fix L0 segment loading delegator selection in QueryCoord
  internal/querycoordv2/task/executor.go
  internal/querycoordv2/task/executor_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed, kind/branch-feature

#43906 enhance: Bump milvus & proto version to v2.5.17
  client/go.mod
  client/go.sum
  go.mod
  go.sum
  pkg/common/version.go
  pkg/go.mod
  pkg/go.sum
  tests/go_client/go.mod
  tests/go_client/go.sum
Labels: kind/enhancement, area/dependency, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed, kind/branch-feature

#43949 enhance: Fix template declaration order for ArithHelperF32 in SVE implementation
  internal/core/src/bitset/detail/platform/arm/sve-impl.h
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#43950 enhance: remove duplicate code in ArithHelperF32 in SVE for bitset
  internal/core/src/bitset/detail/platform/arm/sve-impl.h
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#43951 enhance: remove duplicate code in ArithHelperF32 in SVE for bitset
  internal/core/src/bitset/detail/platform/arm/sve-impl.h
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#43953 enhance: Fix ArithHelperI64 for SVE in bitset
  internal/core/src/bitset/detail/platform/arm/sve-impl.h
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#43366 enhance: report field name when text match or pharse match failed because field not enable match
  internal/parser/planparserv2/parser_visitor.go
  internal/parser/planparserv2/plan_parser_v2_test.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#43865 enhance: Implement dynamic interval updates for ticker components
  internal/querycoordv2/checkers/controller.go
  internal/querycoordv2/dist/dist_handler.go
  internal/querycoordv2/observers/collection_observer.go
  internal/querycoordv2/observers/target_observer.go
  internal/querycoordv2/server.go
  internal/querycoordv2/session/cluster.go
  internal/querynodev2/segments/disk_usage_fetcher.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#43154 enhance: optimize compare expr performance for pk field
  internal/core/src/common/Chunk.h
  internal/core/src/exec/expression/UnaryExpr.cpp
  internal/core/src/exec/expression/UnaryExpr.h
  internal/core/src/exec/expression/Utils.h
  internal/core/src/segcore/ChunkedSegmentSealedImpl.cpp
  internal/core/src/segcore/ChunkedSegmentSealedImpl.h
  internal/core/src/segcore/InsertRecord.h
  internal/core/src/segcore/SegmentGrowingImpl.h
  internal/core/src/segcore/SegmentInterface.h
  internal/core/unittest/test_chunk.cpp
  internal/core/unittest/test_chunked_segment.cpp
Labels: kind/enhancement, size/XL, approved, lgtm, ci-passed, dco-passed

#43935 feat: temporarily disable Timestamptz collection creation
  client/go.mod
  client/go.sum
  go.mod
  go.sum
  internal/proxy/task.go
  internal/proxy/util.go
  pkg/go.mod
  pkg/go.sum
  tests/go_client/go.mod
  tests/go_client/go.sum
Labels: kind/feature, area/dependency, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#43976 fix: remove panic for message type in recovery storage and marshal log
  internal/streamingnode/server/wal/recovery/recovery_storage_impl.go
  pkg/streaming/util/message/marshal_log_object.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#43955 fix: ngram index is mistakenly used for unsopported operations
  internal/core/src/exec/expression/UnaryExpr.cpp
  internal/core/unittest/test_ngram_query.cpp
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#43969 enhance: support balancer interface for streaming client to fetch streaming node information
  internal/.mockery.yaml
  internal/distributed/streaming/balancer.go
  internal/distributed/streaming/balancer_test.go
  internal/distributed/streaming/streaming.go
  internal/distributed/streaming/test_streaming.go
  internal/distributed/streaming/wal.go
  internal/mocks/distributed/mock_streaming/mock_WALAccesser.go
  internal/mocks/streamingcoord/mock_client/mock_AssignmentService.go
  internal/mocks/streamingcoord/server/mock_balancer/mock_Balancer.go
  internal/streamingcoord/client/assignment/assignment_impl.go
  internal/streamingcoord/client/assignment/assignment_test.go
  internal/streamingcoord/client/assignment/watcher.go
  internal/streamingcoord/client/client.go
  internal/streamingcoord/server/balancer/balancer.go
  internal/streamingcoord/server/balancer/balancer_impl.go
  internal/streamingcoord/server/balancer/balancer_test.go
  internal/streamingcoord/server/balancer/request.go
  internal/streamingcoord/server/service/assignment.go
  pkg/mocks/proto/mock_streamingpb/mock_StreamingCoordAssignmentServiceClient.go
  pkg/proto/streaming.proto
  pkg/proto/streamingpb/streaming.pb.go
  pkg/proto/streamingpb/streaming_grpc.pb.go
  pkg/streaming/util/types/balance_config.go
  pkg/streaming/util/types/streaming_node.go
  pkg/util/paramtable/param_item.go
Labels: kind/enhancement, size/XXL, approved, lgtm, ci-passed, area/internal-api, dco-passed

#43990 test: add tests for ngram and fix invalid collection name mag
  tests/python_client/common/common_type.py
  tests/python_client/milvus_client/test_milvus_client_partition.py
  tests/python_client/milvus_client/test_milvus_client_search_iterator.py
  tests/python_client/milvus_client_v2/test_milvus_client_search_v2.py
  tests/python_client/testcases/indexes/idx_ngram.py
  tests/python_client/testcases/indexes/test_ngram.py
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#43991 test: Increase PyMilvus version to 2.5.15rc4
  tests/python_client/requirements.txt
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed, kind/branch-feature, kind/test

#43979 enhance: Use function def determine field `IsFunctionOutput` only
  internal/proxy/util.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#43975 enhance: [GoSDK] Support IvfRabitQ & MinHashLSH index
  client/index/common.go
  client/index/index_test.go
  client/index/ivf.go
  client/index/ivf_test.go
  client/index/minhash.go
  client/index/minhash_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#44006 enhance: [2.5] Use `RLock` for `ListPrivilegeGroups` (#43998)
  internal/rootcoord/meta_table.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#43967 enhance: Add request stats interceptor collecting req metrics
  internal/distributed/proxy/request_interceptor.go
  internal/distributed/proxy/request_interceptor_test.go
  internal/distributed/proxy/service.go
  internal/proxy/impl.go
  pkg/metrics/metrics.go
Labels: kind/enhancement, size/XL, approved, lgtm, ci-passed, dco-passed

#44008 test: add collection V2 cases for milvus client
  tests/python_client/milvus_client/test_milvus_client_collection.py
  tests/python_client/testcases/test_collection.py
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#44009 enhance: [2.5] Use function def determine field `IsFunctionOutput` only (#43979)
  internal/proxy/util.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#44026 enhance: add IsRebalanceSuspended interface for wal balancer
  internal/distributed/streaming/balancer.go
  internal/distributed/streaming/balancer_test.go
  internal/distributed/streaming/streaming.go
  internal/distributed/streaming/test_streaming.go
  internal/mocks/streamingcoord/mock_client/mock_AssignmentService.go
  internal/mocks/streamingcoord/server/mock_balancer/mock_Balancer.go
  internal/streamingcoord/client/assignment/assignment_impl.go
  internal/streamingcoord/client/assignment/assignment_test.go
  internal/streamingcoord/client/client.go
  internal/streamingcoord/server/balancer/balancer.go
  internal/streamingcoord/server/balancer/balancer_impl.go
  internal/streamingcoord/server/balancer/balancer_test.go
  internal/streamingcoord/server/balancer/request.go
  internal/streamingcoord/server/service/assignment.go
  pkg/proto/streaming.proto
  pkg/proto/streamingpb/streaming.pb.go
  pkg/streaming/util/types/balance_config.go
Labels: kind/enhancement, size/XXL, approved, lgtm, ci-passed, area/internal-api, dco-passed

#43939 enhance: Make build ratio of interim index configurable
  configs/milvus.yaml
  internal/core/src/segcore/IndexConfigGenerator.cpp
  internal/core/src/segcore/IndexConfigGenerator.h
  internal/core/src/segcore/SegcoreConfig.h
  internal/core/src/segcore/segcore_init_c.cpp
  internal/core/src/segcore/segcore_init_c.h
  internal/util/initcore/init_core.go
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#43938 enhance:[2.5] Make build ratio of interim index configurable
  configs/milvus.yaml
  internal/core/src/segcore/IndexConfigGenerator.cpp
  internal/core/src/segcore/IndexConfigGenerator.h
  internal/core/src/segcore/SegcoreConfig.h
  internal/core/src/segcore/segcore_init_c.cpp
  internal/core/src/segcore/segcore_init_c.h
  internal/util/initcore/init_core.go
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#44003 enhance: support trace log level for segcore
  cmd/roles/roles.go
  configs/milvus.yaml
  pkg/log/log.go
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#44037 test: fix dependabot alerts
  .github/workflows/main.yaml
  tests/benchmark/requirements.txt
  tests/python_client/requirements.txt
  tests/restful_client/requirements.txt
  tests/restful_client_v2/requirements.txt
Labels: kind/improvement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#43923 enhance: support cache result cache for expr
  configs/milvus.yaml
  internal/core/src/common/init_c.cpp
  internal/core/src/common/init_c.h
  internal/core/src/exec/expression/BinaryRangeExpr.cpp
  internal/core/src/exec/expression/ExistsExpr.cpp
  internal/core/src/exec/expression/Expr.h
  internal/core/src/exec/expression/ExprCache.cpp
  internal/core/src/exec/expression/ExprCache.h
  internal/core/src/exec/expression/JsonContainsExpr.cpp
  internal/core/src/exec/expression/TermExpr.cpp
  internal/core/src/exec/expression/UnaryExpr.cpp
  internal/core/src/index/BitmapIndex.cpp
  internal/core/src/index/BitmapIndex.h
  internal/core/src/index/HybridScalarIndex.h
  internal/core/src/index/InvertedIndexTantivy.cpp
  internal/core/src/index/InvertedIndexTantivy.h
  internal/core/src/index/JsonFlatIndex.h
  internal/core/src/index/JsonInvertedIndex.cpp
  internal/core/src/index/JsonInvertedIndex.h
  internal/core/src/index/JsonKeyStatsInvertedIndex.h
  internal/core/src/index/ScalarIndex.h
  internal/core/src/index/ScalarIndexSort.cpp
  internal/core/src/index/ScalarIndexSort.h
  internal/core/src/index/StringIndexMarisa.cpp
  internal/core/src/index/StringIndexMarisa.h
  internal/core/src/segcore/segment_c.cpp
  internal/core/src/segcore/segment_c.h
  internal/core/unittest/CMakeLists.txt
  internal/core/unittest/test_expr_cache.cpp
  internal/core/unittest/test_text_match.cpp
  internal/querynodev2/segments/segment.go
  internal/querynodev2/server.go
  internal/util/initcore/init_core.go
  internal/util/initcore/util.go
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/XL, approved, lgtm, ci-passed, dco-passed, area/compilation

#43911 enhance: returning collection metadata from cache (#42823)
  configs/milvus.yaml
  internal/proxy/impl.go
  internal/proxy/impl_test.go
  internal/proxy/meta_cache.go
  internal/proxy/service_provider.go
  internal/proxy/service_provider_test.go
  pkg/util/paramtable/component_param.go
  tests/python_client/testcases/test_utility.py
Labels: kind/enhancement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#44029 test: Add ngram tests and expression tests
  tests/python_client/milvus_client/expressions/README.md
  tests/python_client/milvus_client/expressions/test_milvus_client_scalar_expression_filtering_optimized.py
  tests/python_client/testcases/indexes/idx_ngram.py
  tests/python_client/testcases/indexes/test_ngram.py
Labels: sig/testing, size/XXL, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#43960 feat: impl StructArray -- miscellaneous staffs for struct array
  internal/core/src/common/Chunk.h
  internal/core/src/common/Types.h
  internal/core/src/common/VectorTrait.h
  internal/core/src/index/VectorMemIndex.cpp
  internal/core/src/mmap/ChunkedColumn.h
  internal/core/src/mmap/ChunkedColumnGroup.h
  internal/core/src/mmap/ChunkedColumnInterface.h
  internal/core/src/query/Plan.cpp
  internal/core/src/segcore/ChunkedSegmentSealedImpl.cpp
  internal/core/src/segcore/ChunkedSegmentSealedImpl.h
  internal/core/src/segcore/SegmentGrowingImpl.cpp
  internal/core/src/segcore/SegmentGrowingImpl.h
  internal/core/src/segcore/SegmentInterface.h
  internal/core/unittest/CMakeLists.txt
  internal/core/unittest/test_chunked_segment_storage_v2.cpp
  internal/core/unittest/test_utils/DataGen.h
  internal/core/unittest/test_vector_array_storage_v2.cpp
  internal/flushcommon/syncmgr/pack_writer_v2.go
  internal/flushcommon/syncmgr/pack_writer_v2_test.go
  internal/proxy/proxy_test.go
  internal/proxy/search_util.go
  internal/proxy/task_test.go
  internal/proxy/validate_util.go
  internal/proxy/validate_util_test.go
  internal/querynodev2/segments/segment_loader.go
  internal/querynodev2/tasks/search_task.go
  internal/rootcoord/create_collection_task.go
  internal/storage/schema.go
  internal/storage/serde_events_v2.go
  internal/storagecommon/column_group_splitter.go
  internal/util/importutilv2/parquet/field_reader_test.go
  internal/util/importutilv2/parquet/reader_test.go
  internal/util/importutilv2/parquet/util.go
  pkg/util/typeutil/gen_empty_field_data.go
  tests/integration/datanode/struct_array_test.go
  tests/integration/getvector/array_struct_test.go
  tests/integration/import/util_test.go
  tests/integration/util_index.go
  tests/integration/util_query.go
Labels: kind/feature, sig/testing, size/XXL, approved, lgtm, area/test, ci-passed, dco-passed, area/compilation, test/integration

#44042 fix: boost panic if search return empty result
  internal/core/src/exec/operator/RescoresNode.cpp
  internal/core/src/query/PlanProto.cpp
  internal/core/unittest/CMakeLists.txt
  internal/core/unittest/test_rescore.cpp
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed, area/compilation

#44057 fix: Hide sensitive items for restful get configs
  internal/proxy/http_req_impl.go
  internal/proxy/http_req_impl_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#44068 fix: Fix retry state with palyload is not nil
  internal/datacoord/session/cluster.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#44083 fix: Using bucket name in storage config for bulk writer v2
  internal/flushcommon/syncmgr/pack_writer_v2.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#44100 test: Increase PyMilvus version to 2.7.0rc21 for master branch
  tests/python_client/requirements.txt
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#44084 fix: use tbb::concurrent_unordered_map for ChunkedSegmentSealedImpl::fields_
  internal/core/src/segcore/ChunkedSegmentSealedImpl.cpp
  internal/core/src/segcore/ChunkedSegmentSealedImpl.h
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#44099 fix: use query node label check if streamingnode
  internal/querycoordv2/balance/channel_level_score_balancer_test.go
  internal/querycoordv2/balance/rowcount_based_balancer_test.go
  internal/querycoordv2/balance/score_based_balancer_test.go
  internal/querycoordv2/checkers/channel_checker_test.go
  internal/querycoordv2/checkers/controller_base_test.go
  internal/querycoordv2/checkers/controller_test.go
  internal/querycoordv2/checkers/index_checker_test.go
  internal/querycoordv2/checkers/leader_checker_test.go
  internal/querycoordv2/checkers/segment_checker_test.go
  internal/querycoordv2/dist/dist_controller_test.go
  internal/querycoordv2/dist/dist_handler_test.go
  internal/querycoordv2/handlers_test.go
  internal/querycoordv2/job/job_test.go
  internal/querycoordv2/meta/channel_dist_manager.go
  internal/querycoordv2/meta/channel_dist_manager_test.go
  internal/querycoordv2/meta/dist_manager.go
  internal/querycoordv2/meta/dist_manager_test.go
  internal/querycoordv2/observers/collection_observer_test.go
  internal/querycoordv2/observers/replica_observer_test.go
  internal/querycoordv2/observers/target_observer_test.go
  internal/querycoordv2/ops_service_test.go
  internal/querycoordv2/server.go
  internal/querycoordv2/server_test.go
  internal/querycoordv2/services_test.go
  internal/querycoordv2/task/task_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#44112 fix: unrecoverable if lease expire when standby mode
  internal/util/sessionutil/session_util.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#43859 enhance: [DataCoord] Remove full-collection index work from metrics
  internal/datacoord/index_meta.go
  internal/datacoord/meta.go
  internal/datacoord/meta_test.go
  internal/datacoord/metrics_info.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#44126 test: Increase PyMilvus version to 2.7.0rc24 for master branch
  tests/python_client/requirements.txt
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#44086 test: remove import case xfail mark after fix
  tests/restful_client_v2/testcases/test_jobs_operation.py
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed, kind/test
