Repository milvus-io/milvus, pull requests merged in 2025-02, with the labels that each got.

#39626 enhance : remove unnessary logs in lock chain
  internal/rootcoord/task.go
Labels: kind/improvement, size/XS, approved, dco-passed, do-not-merge/missing-related-pr, do-not-merge/invalid-pr-format

#39544 fix: unsafe concurrent consuming api of rocksmq
  internal/rootcoord/dml_channels_test.go
  pkg/mq/mqimpl/rocksmq/client/client_impl.go
  pkg/mq/mqimpl/rocksmq/server/rocksmq_impl.go
  pkg/mq/mqimpl/rocksmq/server/rocksmq_retention.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#39593 fix: segment stats may be inconsistent after wal closing
  internal/streamingcoord/client/assignment/assignment_test.go
  internal/streamingcoord/client/assignment/discoverer.go
  internal/streamingcoord/server/balancer/balancer_impl.go
  internal/streamingnode/server/wal/interceptors/segment/inspector/impls.go
  internal/streamingnode/server/wal/interceptors/segment/manager/partition_manager.go
  internal/streamingnode/server/wal/interceptors/segment/manager/pchannel_manager.go
  internal/streamingnode/server/wal/interceptors/segment/stats/stats_manager.go
  internal/streamingnode/server/wal/interceptors/segment/stats/stats_manager_test.go
  internal/streamingnode/server/walmanager/manager_impl.go
  internal/streamingnode/server/walmanager/wal_lifetime.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#39536 enhance: Remove unnecessary collection and partition label from the metrics
  internal/datacoord/compaction_task_clustering.go
  internal/datacoord/import_checker.go
  internal/datacoord/import_checker_test.go
  internal/querynodev2/metrics_info.go
  internal/querynodev2/segments/manager.go
  internal/querynodev2/services_test.go
  pkg/metrics/datacoord_metrics.go
  pkg/metrics/datanode_metrics.go
  pkg/metrics/metrics.go
  pkg/metrics/querynode_metrics.go
Labels: kind/enhancement, kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#39452 enhance: use rated logger for high frequency log in dist handler
  internal/querycoordv2/balance/channel_level_score_balancer.go
  internal/querycoordv2/balance/score_based_balancer.go
  internal/querycoordv2/dist/dist_handler.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#39641 fix: unstable UT pack_writer_test
  internal/flushcommon/syncmgr/pack_writer_test.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#39459 fix: Restore the compacting state for stats task during recovery
  internal/datacoord/compaction.go
  internal/datacoord/compaction_task.go
  internal/datacoord/compaction_task_clustering.go
  internal/datacoord/compaction_task_clustering_test.go
  internal/datacoord/compaction_task_l0.go
  internal/datacoord/compaction_task_mix.go
  internal/datacoord/compaction_test.go
  internal/datacoord/compaction_trigger_test.go
  internal/datacoord/job_manager.go
  internal/datacoord/meta.go
  internal/datacoord/mock_compaction_meta.go
  internal/datacoord/mock_compaction_plan_context.go
  internal/datacoord/segment_info.go
  internal/datacoord/server.go
  internal/datacoord/server_test.go
  internal/datacoord/stats_task_meta.go
  internal/datacoord/task_analyze.go
  internal/datacoord/task_index.go
  internal/datacoord/task_scheduler.go
  internal/datacoord/task_scheduler_test.go
  internal/datacoord/task_stats.go
  internal/datacoord/task_stats_test.go
  internal/datacoord/types.go
Labels: kind/bug, size/XL, approved, lgtm, ci-passed, dco-passed

#39543 enhance: [2.5]Only check L0 compaction with same channel when stating
  internal/datacoord/compaction.go
  internal/datacoord/compaction_trigger_test.go
  internal/datacoord/mock_compaction_plan_context.go
  internal/datacoord/task_scheduler.go
  internal/datacoord/task_scheduler_test.go
  internal/datacoord/task_stats.go
  internal/datacoord/task_stats_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#39573 enhance: update knowhere version and IsAdditionalScalarSupported interface
  internal/core/src/index/VectorDiskIndex.cpp
  internal/core/src/index/VectorMemIndex.cpp
  internal/core/thirdparty/knowhere/CMakeLists.txt
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed, area/compilation

#39299 fix: check utf-8 format for varchar with analyzer open
  internal/proxy/task_insert.go
  internal/proxy/task_upsert.go
  internal/proxy/util.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#39568 enhance: reduce stats task cost by skipping ser/de
  internal/datanode/compaction/merge_sort.go
  internal/datanode/compaction/segment_reader_from_binlogs.go
  internal/datanode/compaction/segment_record_reader.go
  internal/indexnode/task_stats.go
  internal/indexnode/task_stats_test.go
  internal/storage/binlog_iterator_test.go
  internal/storage/binlog_reader.go
  internal/storage/serde.go
  internal/storage/serde_events.go
  internal/storage/serde_events_test.go
  internal/storage/serde_test.go
  internal/storage/sort.go
  internal/storage/sort_test.go
Labels: kind/enhancement, size/XXL, approved, lgtm, ci-passed, dco-passed

#39078 enhance: skip load bm25 sparse row data
  internal/querynodev2/segments/segment.go
  internal/querynodev2/segments/segment_loader.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#39598 enhance: [2.5] Add dsl log field for HybridSearch (#39584)
  internal/proxy/impl.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#39636 fix: [2.5] Use param item formatter to avoid SetConfig to overlay (#39597)
  internal/util/indexparamcheck/utils_test.go
  pkg/util/paramtable/autoindex_param.go
  pkg/util/paramtable/autoindex_param_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#39662 fix: [GoSDK] Use client config db name when connect
  client/milvusclient/client.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed, component/gosdk

#39665 fix: [GoSDK] Unify AnnRequest creation and fix nil map
  client/milvusclient/read_options.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed, component/gosdk

#39466 enhance: expose more metrics data
  deployments/docker/standalone/docker-compose.yml
  internal/datacoord/compaction_task_meta.go
  internal/datacoord/import_meta.go
  internal/datacoord/index_meta.go
  internal/datacoord/job_manager_test.go
  internal/datacoord/task_scheduler.go
  internal/flushcommon/syncmgr/sync_manager.go
  internal/proxy/impl.go
  internal/querycoordv2/task/scheduler.go
  pkg/config/config_test.go
  pkg/config/manager.go
  pkg/config/manager_test.go
  pkg/util/metricsinfo/metrics_info.go
  pkg/util/paramtable/base_table.go
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/param_item.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#39456 enhance: expose more metrics data
  deployments/docker/standalone/docker-compose.yml
  internal/datacoord/compaction_task_meta.go
  internal/datacoord/import_meta.go
  internal/datacoord/index_meta.go
  internal/datacoord/job_manager_test.go
  internal/datacoord/task_scheduler.go
  internal/datacoord/task_stats.go
  internal/flushcommon/syncmgr/sync_manager.go
  internal/proxy/impl.go
  internal/querycoordv2/task/scheduler.go
  pkg/config/config_test.go
  pkg/config/manager.go
  pkg/config/manager_test.go
  pkg/util/metricsinfo/metrics_info.go
  pkg/util/paramtable/base_table.go
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/param_item.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#39673 enhance: [2.5]update knowhere version
  internal/core/thirdparty/knowhere/CMakeLists.txt
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed, area/compilation, kind/branch-feature

#39096 enhance: Add schema update time verification for insert and upsert to use cache
  go.mod
  go.sum
  internal/metastore/model/collection.go
  internal/proxy/impl.go
  internal/proxy/meta_cache.go
  internal/proxy/task.go
  internal/proxy/task_insert.go
  internal/proxy/task_insert_test.go
  internal/proxy/task_upsert.go
  internal/proxy/task_upsert_test.go
  internal/rootcoord/alter_collection_task.go
  internal/rootcoord/alter_collection_task_test.go
  internal/rootcoord/create_collection_task.go
  internal/rootcoord/root_coord.go
  pkg/go.mod
  pkg/go.sum
  pkg/proto/etcd_meta.proto
  pkg/proto/etcdpb/etcd_meta.pb.go
  pkg/util/merr/errors.go
  pkg/util/merr/errors_test.go
  pkg/util/merr/utils.go
Labels: kind/enhancement, area/dependency, size/L, approved, lgtm, ci-passed, dco-passed

#39656 fix: Fix flowgraph leak
  pkg/mq/msgdispatcher/client.go
  pkg/mq/msgdispatcher/manager.go
  pkg/mq/msgdispatcher/manager_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#39358 fix: sparse: add inverted_index_algo and dim_max_score_ratio config
  internal/core/src/segcore/IndexConfigGenerator.cpp
  internal/core/src/segcore/IndexConfigGenerator.h
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#39687 fix: [2.4] Fix flowgraph leak
  pkg/mq/msgdispatcher/client.go
  pkg/mq/msgdispatcher/manager.go
  pkg/mq/msgdispatcher/manager_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#39676 fix: [skip e2e] update web ui tasks and query segments list
  internal/http/webui/assets/index-Cxslai7T.css
  internal/http/webui/assets/index-DH8a4Gc3.js
  internal/http/webui/assets/index-fggaDIOF.css
  internal/http/webui/assets/index-n1BPvvPj.js
  internal/http/webui/index.html
Labels: kind/bug, size/XXL, approved, lgtm, ci-passed, dco-passed

#39693 fix: [skip e2e] update web ui tasks and query segments list
  internal/http/webui/assets/index-Cxslai7T.css
  internal/http/webui/assets/index-DH8a4Gc3.js
  internal/http/webui/assets/index-fggaDIOF.css
  internal/http/webui/assets/index-n1BPvvPj.js
  internal/http/webui/index.html
Labels: kind/bug, size/XXL, approved, lgtm, ci-passed, dco-passed

#39253 enhance: update tantivy version
  internal/core/thirdparty/tantivy/tantivy-binding/Cargo.lock
  internal/core/thirdparty/tantivy/tantivy-binding/Cargo.toml
  internal/core/thirdparty/tantivy/tantivy-binding/src/index_reader.rs
  internal/core/thirdparty/tantivy/tantivy-binding/src/index_writer.rs
Labels: kind/enhancement, size/XL, approved, lgtm, ci-passed, dco-passed, area/compilation

#38216 fix: [2.4] Fix timeout when listing meta
  internal/metastore/kv/datacoord/kv_catalog.go
  internal/metastore/kv/datacoord/kv_catalog_test.go
  internal/metastore/kv/querycoord/kv_catalog.go
  internal/metastore/kv/querycoord/kv_catalog_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#39674 test: [skip e2e]add streaming node chaos test
  tests/python_client/chaos/chaos_objects/pod_failure/chaos_streamingnode_pod_failure.yaml
  tests/python_client/chaos/chaos_objects/pod_kill/chaos_streamingnode_pod_kill.yaml
Labels: kind/improvement, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed, manual-pass, kind/test

#39433 test: update test cases and sdk version[2.4]
  tests/python_client/conftest.py
  tests/python_client/milvus_client/test_milvus_client_partition.py
  tests/python_client/requirements.txt
  tests/python_client/testcases/async_milvus_client/test_e2e_async.py
  tests/python_client/testcases/test_index.py
  tests/python_client/testcases/test_insert.py
  tests/python_client/testcases/test_partition.py
  tests/python_client/testcases/test_utility.py
  tests/python_client/utils/util_pymilvus.py
Labels: sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#39686 fix: [2.5] Fix flowgraph leak
  pkg/mq/msgdispatcher/client.go
  pkg/mq/msgdispatcher/manager.go
  pkg/mq/msgdispatcher/manager_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#38215 enhance: [2.4] Reduce memory usage of BF in DataNode and QueryNode
  internal/datanode/writebuffer/l0_write_buffer.go
  internal/datanode/writebuffer/l0_write_buffer_test.go
  internal/querynodev2/segments/segment.go
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/component_param_test.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#38916 fix: [2.4] Fix consume blocked due to too many consumers
  configs/milvus.yaml
  internal/datanode/flow_graph_dmstream_input_node.go
  internal/util/pipeline/stream_pipeline.go
  internal/util/pipeline/stream_pipeline_test.go
  pkg/mq/msgdispatcher/client.go
  pkg/mq/msgdispatcher/client_test.go
  pkg/util/merr/errors.go
  pkg/util/merr/errors_test.go
  pkg/util/merr/utils.go
  pkg/util/paramtable/service_param.go
  pkg/util/paramtable/service_param_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#38903 fix: [2.4] Fix rootcoord meta mutex contention
  internal/metastore/model/collection.go
  internal/metastore/model/collection_test.go
  internal/rootcoord/meta_table.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#39661 enhance: Enable to observe write amplification
  internal/datanode/compaction/executor.go
  internal/flushcommon/syncmgr/task.go
  pkg/metrics/datanode_metrics.go
  pkg/metrics/metrics.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#39570 test: add go-sdk cases for full text search
  tests/go_client/README.md
  tests/go_client/common/consts.go
  tests/go_client/common/utils.go
  tests/go_client/testcases/full_text_search_test.go
  tests/go_client/testcases/helper/data_helper.go
  tests/go_client/testcases/helper/field_helper.go
  tests/go_client/testcases/helper/function_helper.go
  tests/go_client/testcases/helper/helper.go
  tests/go_client/testcases/helper/index_helper.go
  tests/go_client/testcases/helper/read_helper.go
  tests/go_client/testcases/helper/schema_helper.go
Labels: kind/improvement, sig/testing, size/XL, approved, lgtm, area/test, ci-passed, dco-passed, manual-pass, kind/test

#39703 enhance: remove useless memory copies on type conversion during sync operations
  internal/storage/utils.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#39720 enhance: keep consistent of memory and meta of broadcaster
  internal/streamingcoord/server/broadcaster/broadcast_task.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#39734 fix: [2.4] Fix compile error
  pkg/mq/msgdispatcher/client.go
Labels: kind/bug, kind/improvement, size/XS, do-not-merge/missing-related-issue, dco-passed

#39721 enhance: keep consistent of memory and meta of broadcaster
  internal/streamingcoord/server/broadcaster/broadcast_task.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#38912 enhance: [2.4] Skip creating partition rate limiters when not enable
  internal/rootcoord/quota_center.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#39739 fix: [skip e2e] update the collection detail page logic
  internal/http/webui/assets/index-C87SjVfH.js
  internal/http/webui/index.html
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#38906 fix: [2.4] Fix slow dist handle and slow observe
  internal/querycoordv2/dist/dist_handler.go
  internal/querycoordv2/meta/target.go
  internal/querycoordv2/meta/target_manager.go
  internal/querycoordv2/meta/target_manager_test.go
  internal/querycoordv2/observers/collection_observer.go
  internal/querycoordv2/task/action.go
  internal/querycoordv2/task/scheduler.go
  internal/querycoordv2/task/task.go
  internal/querycoordv2/task/task_test.go
  internal/querycoordv2/utils/util.go
  pkg/metrics/querycoord_metrics.go
Labels: kind/bug, size/XL, approved, lgtm, ci-passed, dco-passed

#39664 enhance: Optimize the result format of GetQueryNodeDistribution
  internal/proxy/management.go
  internal/proxy/management_test.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#39741 enhance: [2.4] Speed up meta recovery
  internal/metastore/kv/datacoord/kv_catalog.go
  internal/metastore/kv/querycoord/kv_catalog.go
  internal/metastore/kv/rootcoord/suffix_snapshot.go
  pkg/util/paramtable/service_param.go
  pkg/util/paramtable/service_param_test.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#39275 enhance: make pchannel level flusher
  internal/.mockery.yaml
  internal/flushcommon/pipeline/data_sync_service.go
  internal/flushcommon/syncmgr/sync_manager.go
  internal/flushcommon/util/checkpoint_updater.go
  internal/metastore/catalog.go
  internal/metastore/kv/streamingnode/constant.go
  internal/metastore/kv/streamingnode/kv_catalog.go
  internal/mocks/mock_metastore/mock_StreamingNodeCataLog.go
  internal/mocks/mock_storage/mock_ChunkManager.go
  internal/mocks/streamingnode/server/mock_flusher/mock_Flusher.go
  internal/querycoordv2/balance/channel_level_score_balancer.go
  internal/querycoordv2/observers/replica_observer_test.go
  internal/rootcoord/meta_table.go
  internal/streamingnode/server/builder.go
  internal/streamingnode/server/flusher/flusher.go
  internal/streamingnode/server/flusher/flusherimpl/channel_lifetime.go
  internal/streamingnode/server/flusher/flusherimpl/data_service_wrapper.go
  internal/streamingnode/server/flusher/flusherimpl/flusher_components.go
  internal/streamingnode/server/flusher/flusherimpl/flusher_impl.go
  internal/streamingnode/server/flusher/flusherimpl/flusher_impl_test.go
  internal/streamingnode/server/flusher/flusherimpl/pchannel_checkpoint.go
  internal/streamingnode/server/flusher/flusherimpl/pchannel_checkpoint_test.go
  internal/streamingnode/server/flusher/flusherimpl/util.go
  internal/streamingnode/server/flusher/flusherimpl/vchannel_checkpoint.go
  internal/streamingnode/server/flusher/flusherimpl/vchannel_checkpoint_test.go
  internal/streamingnode/server/flusher/flusherimpl/wal_flusher.go
  internal/streamingnode/server/flusher/flusherimpl/wal_flusher_test.go
  internal/streamingnode/server/resource/resource.go
  internal/streamingnode/server/resource/resource_test.go
  internal/streamingnode/server/server.go
  internal/streamingnode/server/wal/adaptor/builder.go
  internal/streamingnode/server/wal/adaptor/scanner_adaptor.go
  internal/streamingnode/server/wal/adaptor/scanner_adaptor_test.go
  internal/streamingnode/server/wal/adaptor/wal_adaptor.go
  internal/streamingnode/server/wal/adaptor/wal_adaptor_test.go
  internal/streamingnode/server/wal/adaptor/wal_test.go
  internal/streamingnode/server/wal/interceptors/ddl/builder.go
  internal/streamingnode/server/wal/interceptors/ddl/ddl_interceptor.go
  internal/streamingnode/server/wal/interceptors/flusher/builder.go
  internal/streamingnode/server/wal/interceptors/flusher/flusher_interceptor.go
  internal/streamingnode/server/wal/interceptors/segment/inspector/impls.go
  internal/streamingnode/server/wal/interceptors/timetick/timetick_interceptor.go
  internal/streamingnode/server/wal/registry/registry.go
  internal/streamingnode/server/wal/scanner.go
  internal/streamingnode/server/walmanager/manager_impl.go
  internal/streamingnode/server/walmanager/manager_impl_test.go
  internal/streamingnode/server/walmanager/wal_lifetime.go
  internal/streamingnode/server/walmanager/wal_lifetime_test.go
  pkg/proto/streaming.proto
  pkg/proto/streamingpb/streaming.pb.go
  pkg/streaming/util/message/adaptor/handler.go
  pkg/streaming/util/message/message_id.go
  pkg/streaming/util/message/test_case.go
  tests/integration/minicluster_v2.go
Labels: kind/enhancement, sig/testing, size/XXL, approved, lgtm, area/test, ci-passed, area/internal-api, dco-passed, test/integration

#38230 enhance: [2.4] Reduce mutex contention in datacoord meta
  internal/datacoord/compaction_policy_clustering.go
  internal/datacoord/compaction_policy_single.go
  internal/datacoord/compaction_policy_single_test.go
  internal/datacoord/compaction_trigger.go
  internal/datacoord/compaction_trigger_test.go
  internal/datacoord/meta.go
  internal/datacoord/meta_test.go
  internal/datacoord/segment_info.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#39738 fix: [2.4] channel unbalance during stopping balance progress
  internal/querycoordv2/balance/balance.go
  internal/querycoordv2/balance/rowcount_based_balancer.go
  internal/querycoordv2/balance/score_based_balancer.go
  internal/querycoordv2/balance/score_based_balancer_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#39740 fix: [skip e2e] update the collection detail page logic
  internal/http/webui/assets/index-C87SjVfH.js
  internal/http/webui/index.html
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#39746 fix: phrase match return more readable error msg with invalid slop parameter
  internal/parser/planparserv2/Plan.g4
  internal/parser/planparserv2/generated/Plan.interp
  internal/parser/planparserv2/generated/plan_parser.go
  internal/parser/planparserv2/parser_visitor.go
  internal/parser/planparserv2/plan_parser_v2_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#39777 fix: [2.4] Fix concurrent map
  pkg/util/typeutil/map.go
  pkg/util/typeutil/map_test.go
Labels: kind/bug, kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#39714 fix: [2.5] root check the role list if `rootShouldBindRole` is true
  configs/milvus.yaml
  internal/rootcoord/list_db_task.go
  internal/rootcoord/list_db_task_test.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
  internal/rootcoord/show_collection_task.go
  internal/rootcoord/show_collection_task_test.go
  pkg/util/paramtable/component_param.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#39715 fix: [2.4] root check the role list if `rootShouldBindRole` is true
  configs/milvus.yaml
  internal/rootcoord/list_db_task.go
  internal/rootcoord/list_db_task_test.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
  internal/rootcoord/show_collection_task.go
  internal/rootcoord/show_collection_task_test.go
  pkg/util/paramtable/component_param.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#39762 fix: Return early when skip load pk index
  internal/querynodev2/segments/segment.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#39763 fix: [2.5] Return early when skip load pk index
  internal/querynodev2/segments/segment.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#39537 test: add go-sdk cases for collection related APIs
  tests/go_client/base/milvus_client.go
  tests/go_client/common/consts.go
  tests/go_client/common/utils.go
  tests/go_client/testcases/client_test.go
  tests/go_client/testcases/collection_test.go
  tests/go_client/testcases/groupby_search_test.go
  tests/go_client/testcases/helper/collection_helper.go
  tests/go_client/testcases/helper/data_helper.go
  tests/go_client/testcases/helper/helper.go
  tests/go_client/testcases/insert_test.go
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, manual-pass, kind/test

#39765 test: add phrase match in chaos test
  tests/python_client/chaos/checker.py
  tests/python_client/chaos/testcases/test_concurrent_operation.py
  tests/python_client/chaos/testcases/test_single_request_operation.py
Labels: kind/improvement, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#38776 fix: [2.4] Remove frequently updating metric to avoid mutex contention
  internal/datacoord/index_meta.go
  internal/querycoordv2/task/scheduler.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#39702 fix: uneven distribution caused by executing task delta cache leak
  internal/querycoordv2/balance/utils.go
  internal/querycoordv2/checkers/index_checker.go
  internal/querycoordv2/checkers/segment_checker.go
  internal/querycoordv2/handlers.go
  internal/querycoordv2/task/action.go
  internal/querycoordv2/task/scheduler.go
  internal/querycoordv2/task/task_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#39759 fix: [2.5]uneven distribution caused by executing task delta cache leak
  internal/querycoordv2/balance/utils.go
  internal/querycoordv2/checkers/index_checker.go
  internal/querycoordv2/checkers/segment_checker.go
  internal/querycoordv2/handlers.go
  internal/querycoordv2/task/action.go
  internal/querycoordv2/task/scheduler.go
  internal/querycoordv2/task/task_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#39701 fix: load collection stucks if compaction/gc happens
  internal/querycoordv2/observers/target_observer.go
  internal/querycoordv2/task/scheduler.go
  internal/querycoordv2/task/task_test.go
  tests/integration/replicas/load/load_test.go
  tests/integration/util_collection.go
Labels: kind/bug, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, test/integration

#39761 fix: [2.5] load collection stucks if compaction/gc happens
  internal/querycoordv2/observers/target_observer.go
  internal/querycoordv2/task/scheduler.go
  internal/querycoordv2/task/task_test.go
  tests/integration/replicas/load/load_test.go
  tests/integration/util_collection.go
Labels: kind/bug, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, test/integration

#39623 fix: Remove getModTime() to use ModTime() from os.FileInfo directly
  internal/storage/local_chunk_manager.go
  internal/storage/local_chunk_manager_test.go
Labels: kind/bug, size/M, lgtm, do-not-merge/missing-related-issue, dco-passed

#39796 fix: Resolve conflict on qc task test
  internal/querycoordv2/task/task_test.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#39443 test: update test cases and sdk version
  tests/python_client/conftest.py
  tests/python_client/milvus_client/test_milvus_client_partition.py
  tests/python_client/requirements.txt
  tests/python_client/testcases/async_milvus_client/test_e2e_async.py
  tests/python_client/testcases/test_collection.py
  tests/python_client/testcases/test_index.py
  tests/python_client/testcases/test_insert.py
  tests/python_client/testcases/test_mix_scenes.py
  tests/python_client/testcases/test_partition.py
  tests/python_client/testcases/test_utility.py
  tests/python_client/utils/util_pymilvus.py
Labels: sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#39797 fix: [2.5] Resolve conflict on qc task test
  internal/querycoordv2/task/task_test.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#39766 fix: [2.4] load collection stucks if compaction/gc happens
  internal/querycoordv2/observers/target_observer.go
  internal/querycoordv2/task/task_test.go
  tests/integration/replicas/load/load_test.go
  tests/integration/util_collection.go
Labels: kind/bug, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, test/integration

#39722 fix: Fix modulo for long type
  internal/core/src/bitset/common.h
  internal/core/src/exec/expression/BinaryArithOpEvalRangeExpr.h
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#39776 fix: [2.5] Fix concurrent map
  pkg/util/typeutil/map.go
  pkg/util/typeutil/map_test.go
Labels: kind/bug, kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#39811 fix: [skip e2e] pr conflict cause ut failed
  internal/querycoordv2/task/task_test.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#39804 fix: [2.4] Fix module for long type
  internal/core/src/bitset/common.h
  internal/core/src/exec/expression/BinaryArithOpEvalRangeExpr.cpp
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#39691 test: Add sparse invert index algo check tests
  tests/python_client/common/common_type.py
  tests/python_client/testcases/test_full_text_search.py
  tests/python_client/testcases/test_index.py
  tests/python_client/testcases/test_search.py
  tests/python_client/utils/util_pymilvus.py
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#39789 fix: [2.5] Segments return both growing&sealed result
  internal/querynodev2/segments/manager.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#39751 enhance: [GoSDK] Add range & sparse ann param
  client/index/ann_param.go
  client/index/sparse.go
  tests/go_client/testcases/search_test.go
Labels: kind/enhancement, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed, component/gosdk

#39685 enhance: improve sort performance by writing with batch record
  internal/datacoord/segment_info.go
  internal/datanode/compaction/merge_sort.go
  internal/indexnode/task_stats.go
  internal/storage/arrow_util.go
  internal/storage/sort.go
  internal/storage/sort_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#38348 enhance: [2.4] Add secondary index for querynode segment manager (#38311)
  internal/querynodev2/segments/collection.go
  internal/querynodev2/segments/manager.go
  internal/querynodev2/segments/segment_filter.go
  pkg/util/metautil/channel.go
Labels: kind/enhancement, size/XL, approved, lgtm, ci-passed, dco-passed

#39679 fix: [2.5]not pass the indexname when drop properties
  internal/distributed/proxy/httpserver/handler_v2.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#39286 enhance[2.5]: move GetVector_EmptySparseVector ut to growing test
  internal/core/unittest/test_growing_index.cpp
  internal/core/unittest/test_indexing.cpp
  internal/core/unittest/test_utils/DataGen.h
Labels: size/L, approved, lgtm, ci-passed, dco-passed, do-not-merge/invalid-pr-format

#39512 enhance: Add configs for compaction schedule (#39010)
  configs/milvus.yaml
  internal/datacoord/compaction.go
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#39824 test: supplementary json expr go-sdk test cases
  tests/go_client/testcases/helper/data_helper.go
  tests/go_client/testcases/index_test.go
  tests/go_client/testcases/query_test.go
  tests/go_client/testcases/search_test.go
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, manual-pass, kind/test

#39771 enhance: enable write ahead buffer for streaming service
  configs/milvus.yaml
  internal/.mockery.yaml
  internal/mocks/streamingnode/server/wal/interceptors/mock_wab/mock_ROWriteAheadBuffer.go
  internal/mocks/streamingnode/server/wal/interceptors/timetick/mock_inspector/mock_TimeTickSyncOperator.go
  internal/querycoordv2/balance/streaming_query_node_channel_helper_test.go
  internal/streamingnode/server/flusher/flusherimpl/flusher_components.go
  internal/streamingnode/server/flusher/flusherimpl/util.go
  internal/streamingnode/server/wal/adaptor/scanner_adaptor.go
  internal/streamingnode/server/wal/adaptor/scanner_adaptor_test.go
  internal/streamingnode/server/wal/adaptor/scanner_switchable.go
  internal/streamingnode/server/wal/adaptor/wal_adaptor.go
  internal/streamingnode/server/wal/adaptor/wal_adaptor_test.go
  internal/streamingnode/server/wal/adaptor/wal_test.go
  internal/streamingnode/server/wal/interceptors/timetick/ack/ack_test.go
  internal/streamingnode/server/wal/interceptors/timetick/ack/detail.go
  internal/streamingnode/server/wal/interceptors/timetick/ack/detail_test.go
  internal/streamingnode/server/wal/interceptors/timetick/ack/last_confirmed.go
  internal/streamingnode/server/wal/interceptors/timetick/inspector/inspector.go
  internal/streamingnode/server/wal/interceptors/timetick/inspector/notifier.go
  internal/streamingnode/server/wal/interceptors/timetick/inspector/notifier_test.go
  internal/streamingnode/server/wal/interceptors/timetick/timetick_interceptor.go
  internal/streamingnode/server/wal/interceptors/timetick/timetick_sync_operator.go
  internal/streamingnode/server/wal/interceptors/timetick/timetick_sync_operator_test.go
  internal/streamingnode/server/wal/interceptors/wab/pending_queue.go
  internal/streamingnode/server/wal/interceptors/wab/pending_queue_test.go
  internal/streamingnode/server/wal/interceptors/wab/reader.go
  internal/streamingnode/server/wal/interceptors/wab/write_ahead_buffer.go
  internal/streamingnode/server/wal/interceptors/wab/write_ahead_buffer_test.go
  internal/streamingnode/server/wal/metricsutil/timetick.go
  internal/streamingnode/server/wal/utility/context_test.go
  internal/streamingnode/server/wal/utility/pending_queue_test.go
  internal/streamingnode/server/wal/utility/reorder_buffer.go
  internal/streamingnode/server/wal/utility/reorder_buffer_test.go
  pkg/streaming/util/message/adaptor/handler.go
  pkg/streaming/util/message/builder.go
  pkg/streaming/util/message/message_handler.go
  pkg/streaming/util/message/message_impl.go
  pkg/streaming/util/message/properties.go
  pkg/streaming/util/message/version.go
  pkg/streaming/walimpls/impls/rmq/scanner.go
  pkg/streaming/walimpls/impls/walimplstest/scanner.go
  pkg/streaming/walimpls/scanner.go
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/component_param_test.go
Labels: kind/enhancement, size/XXL, approved, lgtm, ci-passed, dco-passed

#39180 enhance: [2.5]intermin index support different index type and more data type(fp16/bf16)
  configs/milvus.yaml
  internal/core/src/common/type_c.h
  internal/core/src/index/VectorMemIndex.cpp
  internal/core/src/index/VectorMemIndex.h
  internal/core/src/mmap/ChunkVector.h
  internal/core/src/query/SearchOnGrowing.cpp
  internal/core/src/segcore/ChunkedSegmentSealedImpl.cpp
  internal/core/src/segcore/ConcurrentVector.h
  internal/core/src/segcore/FieldIndexing.cpp
  internal/core/src/segcore/FieldIndexing.h
  internal/core/src/segcore/IndexConfigGenerator.cpp
  internal/core/src/segcore/IndexConfigGenerator.h
  internal/core/src/segcore/InsertRecord.h
  internal/core/src/segcore/SegcoreConfig.h
  internal/core/src/segcore/SegmentGrowingImpl.cpp
  internal/core/src/segcore/SegmentGrowingImpl.h
  internal/core/src/segcore/SegmentSealedImpl.cpp
  internal/core/src/segcore/segcore_init_c.cpp
  internal/core/src/segcore/segcore_init_c.h
  internal/core/src/segcore/vector_index_c.cpp
  internal/core/src/storage/Types.h
  internal/core/src/storage/storage_c.cpp
  internal/core/unittest/test_binlog_index.cpp
  internal/core/unittest/test_growing_index.cpp
  internal/querynodev2/segments/segment.go
  internal/querynodev2/segments/segment_loader.go
  internal/querynodev2/server.go
  internal/util/initcore/init_core.go
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/component_param_test.go
Labels: kind/enhancement, size/XXL, approved, lgtm, ci-passed, dco-passed, area/compilation

#39805 fix: [2.4] remove the mmap.enable param in the type param when creating index
  internal/datacoord/index_meta.go
  internal/datacoord/index_meta_test.go
  internal/datacoord/index_service.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#39806 fix:[2.5] remove the mmap.enable param in the type param when creating index
  internal/datacoord/index_meta.go
  internal/datacoord/index_meta_test.go
  internal/datacoord/index_service.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#39787 fix: Segments return both growing&sealed result
  internal/querynodev2/segments/manager.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#39803 fix: remove the mmap.enable param in the type param when creating index
  internal/datacoord/index_meta.go
  internal/datacoord/index_meta_test.go
  internal/datacoord/index_service.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#39579 test: add go-sdk cases for hybrid search
  tests/go_client/base/milvus_client.go
  tests/go_client/testcases/database_test.go
  tests/go_client/testcases/delete_test.go
  tests/go_client/testcases/hybrid_search_test.go
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, manual-pass, kind/test

#39724 enhance: iterative download data during compaction to reduce memory cost
  internal/datanode/compaction/clustering_compactor.go
  internal/datanode/compaction/compactor_common.go
  internal/datanode/compaction/mix_compactor.go
  internal/datanode/compaction/mix_compactor_test.go
  internal/indexnode/task_stats.go
  internal/storage/binlog_iterator_test.go
  internal/storage/serde_events.go
  internal/storage/serde_events_test.go
  internal/storage/serde_events_v2_test.go
  internal/storage/serde_test.go
  internal/storage/sort_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#39706 test: add some async cases
  tests/python_client/base/async_milvus_client_wrapper.py
  tests/python_client/milvus_client/test_milvus_client_database.py
  tests/python_client/testcases/async_milvus_client/test_collection_async.py
  tests/python_client/testcases/async_milvus_client/test_index_async.py
  tests/python_client/testcases/async_milvus_client/test_partition_async.py
Labels: kind/improvement, sig/testing, size/XXL, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#39834 fix: [2.4] Remove load field & schema column size check
  internal/core/src/segcore/SegmentGrowingImpl.cpp
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#39835 fix: [2.5] Remove load field & schema column size check #39834
  internal/core/src/segcore/SegmentGrowingImpl.cpp
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#39760 enhance: [2.5] dump pprof info if component stop progress timeout
  cmd/components/util.go
  configs/milvus.yaml
  internal/distributed/proxy/service_test.go
  internal/distributed/utils/util.go
  pkg/util/paramtable/grpc_param.go
  pkg/util/paramtable/grpc_param_test.go
  pkg/util/paramtable/service_param.go
  pkg/util/paramtable/service_param_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#39726 enhance: dump pprof info if component stop progress timeout
  cmd/components/util.go
  configs/milvus.yaml
  internal/distributed/proxy/service_test.go
  internal/distributed/utils/util.go
  pkg/util/paramtable/grpc_param.go
  pkg/util/paramtable/grpc_param_test.go
  pkg/util/paramtable/service_param.go
  pkg/util/paramtable/service_param_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#39837 enhance: [GoSDK] Add WithEnableMatch syntactic sugar
  client/entity/field.go
  client/entity/field_test.go
  client/entity/schema.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#39764 enhance: [2.4] dump pprof info if component stop progress timeout
  cmd/components/util.go
  configs/milvus.yaml
  internal/distributed/proxy/service_test.go
  internal/distributed/utils/util.go
  pkg/util/paramtable/grpc_param.go
  pkg/util/paramtable/grpc_param_test.go
  pkg/util/paramtable/service_param.go
  pkg/util/paramtable/service_param_test.go
  tests/integration/replicas/load/load_test.go
Labels: kind/enhancement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, test/integration

#39842 fix: [2.4] Check collection released before target checks
  internal/querycoordv2/observers/target_observer.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#39581 feat: Add cohere text embedding
  internal/util/function/cohere_embedding_provider.go
  internal/util/function/cohere_embedding_provider_test.go
  internal/util/function/common.go
  internal/util/function/mock_embedding_service.go
  internal/util/function/models/cohere/cohere_text_embedding.go
  internal/util/function/models/cohere/cohere_text_embedding_test.go
  internal/util/function/text_embedding_function.go
  internal/util/function/text_embedding_function_test.go
Labels: kind/feature, size/XL, approved, lgtm, ci-passed, dco-passed

#39723 enhance: support run analyzer
  go.mod
  go.sum
  internal/distributed/proxy/service.go
  internal/mocks/mock_proxy.go
  internal/proxy/impl.go
  internal/proxy/impl_test.go
  pkg/go.mod
  pkg/go.sum
Labels: kind/enhancement, area/dependency, size/L, approved, lgtm, ci-passed, dco-passed

#39853 enhance: [2.5][GoSDK] Add WithEnableMatch syntactic sugar (#39837)
  client/entity/field.go
  client/entity/field_test.go
  client/entity/schema.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#39793 fix: rootcoord graceful stop failed and limit resource of ci
  internal/distributed/rootcoord/service.go
  internal/distributed/rootcoord/service_test.go
  internal/rootcoord/root_coord.go
  internal/streamingcoord/client/broadcast/watcher_resuming.go
  internal/streamingcoord/server/balancer/balancer.go
  internal/streamingcoord/server/balancer/balancer_impl.go
  internal/streamingcoord/server/balancer/balancer_test.go
  internal/types/types.go
  tests/_helm/values/e2e/distributed
  tests/_helm/values/e2e/distributed-streaming-service
  tests/go_client/testcases/helper/helper.go
Labels: kind/bug, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#39843 fix: [2.5] Check collection released before target checks
  internal/querycoordv2/observers/target_observer.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#39713 fix: root check the role list if `rootShouldBindRole` is true
  configs/milvus.yaml
  internal/rootcoord/list_db_task.go
  internal/rootcoord/list_db_task_test.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
  internal/rootcoord/show_collection_task.go
  internal/rootcoord/show_collection_task_test.go
  pkg/util/paramtable/component_param.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#39730 enhance: improve bloomfilter performance
  configs/milvus.yaml
  internal/storage/pk_statistics.go
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/component_param_test.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#39870 fix: ReEnqueue L0 compaction task when preCheck failed
  internal/datacoord/compaction.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#39858 enhance:[2.4] return topks when search in restful v2
  internal/distributed/proxy/httpserver/constant.go
  internal/distributed/proxy/httpserver/handler_v2.go
  tests/restful_client_v2/testcases/test_vector_operations.py
Labels: kind/enhancement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#39859 enhance: Bump milvus version to 2.4.22
  pkg/common/version.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass, kind/branch-feature

#39857 fix: Add and use lifetime context for compaction trigger
  internal/datacoord/compaction_policy_clustering.go
  internal/datacoord/compaction_policy_clustering_test.go
  internal/datacoord/compaction_policy_single.go
  internal/datacoord/compaction_policy_single_test.go
  internal/datacoord/compaction_trigger_v2.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#39472 enhance: add workaround for concurrent tantivy reload and directory removal (#39441)
  internal/core/src/storage/LocalChunkManager.cpp
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#39839 enhance: [2.5]return topks when search in restful v2
  internal/distributed/proxy/httpserver/constant.go
  internal/distributed/proxy/httpserver/handler_v2.go
  tests/restful_client_v2/testcases/test_vector_operations.py
Labels: kind/enhancement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#39841 fix: Check collection released before target checks
  internal/querycoordv2/observers/target_observer.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#38656 enhance: unmashall ts msg in dispatcher instead in msgstream
  internal/core/src/clustering/analyze_c.cpp
  internal/core/src/indexbuilder/index_c.cpp
  internal/core/src/segcore/vector_index_c.cpp
  internal/flushcommon/pipeline/data_sync_service_test.go
  internal/flushcommon/pipeline/flow_graph_dmstream_input_node_test.go
  internal/proxy/mock_test.go
  internal/querynodev2/delegator/delegator_data.go
  internal/querynodev2/delegator/delegator_data_test.go
  internal/querynodev2/services_test.go
  internal/rootcoord/alter_collection_task_test.go
  internal/rootcoord/alter_database_task_test.go
  internal/rootcoord/dml_channels_test.go
  internal/rootcoord/mock_test.go
  internal/util/flowgraph/input_node_test.go
  internal/util/flowgraph/message_test.go
  internal/util/flowgraph/node_test.go
  pkg/mq/common/message.go
  pkg/mq/msgdispatcher/dispatcher.go
  pkg/mq/msgdispatcher/dispatcher_test.go
  pkg/mq/msgdispatcher/manager_test.go
  pkg/mq/msgstream/factory_stream_test.go
  pkg/mq/msgstream/mock_msgstream.go
  pkg/mq/msgstream/mq_kafka_msgstream_test.go
  pkg/mq/msgstream/mq_msgstream.go
  pkg/mq/msgstream/mq_msgstream_test.go
  pkg/mq/msgstream/mq_rocksmq_msgstream_test.go
  pkg/mq/msgstream/msg.go
  pkg/mq/msgstream/msgstream.go
  pkg/mq/msgstream/msgstream_util.go
  pkg/mq/msgstream/trace.go
  pkg/mq/msgstream/wasted_mock_msgstream.go
Labels: kind/enhancement, size/XXL, approved, lgtm, ci-passed, dco-passed

#39871 fix: [2.5] ReEnqueue L0 compaction task when preCheck failed
  internal/datacoord/compaction.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#39880 fix: [2.5] Add and use lifetime context for compaction trigger (#39857)
  internal/datacoord/compaction_policy_clustering.go
  internal/datacoord/compaction_policy_clustering_test.go
  internal/datacoord/compaction_policy_single.go
  internal/datacoord/compaction_policy_single_test.go
  internal/datacoord/compaction_trigger_v2.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#39372 enhance: Sync multipleChunkEnabled default value & milvus yaml
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#39678 fix: not pass the indexname when drop properties
  internal/distributed/proxy/httpserver/handler_v2.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#39884 test: fix hybrid search limit case
  tests/go_client/testcases/hybrid_search_test.go
Labels: sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed, manual-pass, kind/test

#39802 fix: [2.5] Fix module for long type
  internal/core/src/bitset/common.h
  internal/core/src/exec/expression/BinaryArithOpEvalRangeExpr.h
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#39891 enhance: [skip e2e] Bump actions/download-artifact to v4.1.3 fixing security issue
  .github/workflows/main.yaml
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#39850 enhance: add tantivy collector for i64
  internal/core/src/bitset/common.h
  internal/core/src/exec/expression/BinaryArithOpEvalRangeExpr.h
  internal/core/thirdparty/tantivy/tantivy-binding/include/tantivy-binding.h
  internal/core/thirdparty/tantivy/tantivy-binding/src/array.rs
  internal/core/thirdparty/tantivy/tantivy-binding/src/docid_collector.rs
  internal/core/thirdparty/tantivy/tantivy-binding/src/index_reader.rs
  internal/core/thirdparty/tantivy/tantivy-binding/src/lib.rs
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#39154 enhance: Add trigger interval config for auto balance
  configs/milvus.yaml
  internal/querycoordv2/checkers/balance_checker.go
  internal/querycoordv2/checkers/balance_checker_test.go
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/component_param_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#39221 enhance: [2.5]update raft to cuvs
  internal/core/thirdparty/knowhere/CMakeLists.txt
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed, area/compilation

#37784 enhance: Add management api to check querycoord balance status
  internal/distributed/querycoord/client/client.go
  internal/distributed/querycoord/client/client_test.go
  internal/distributed/querycoord/service.go
  internal/distributed/querycoord/service_test.go
  internal/http/router.go
  internal/mocks/mock_querycoord.go
  internal/mocks/mock_querycoord_client.go
  internal/proxy/management.go
  internal/proxy/management_test.go
  internal/querycoordv2/ops_service_test.go
  internal/querycoordv2/ops_services.go
  internal/util/mock/grpc_querycoord_client.go
  pkg/proto/query_coord.proto
  pkg/proto/querypb/query_coord.pb.go
  pkg/proto/querypb/query_coord_grpc.pb.go
Labels: kind/enhancement, size/XXL, approved, lgtm, ci-passed, area/internal-api, dco-passed

#39747 enhance: add unit test and benchmark for check varchar format
  internal/proxy/util_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#39886 fix: Fix import failed due to 0 row num
  internal/datanode/importv2/task_import.go
  internal/datanode/importv2/util.go
  internal/datanode/importv2/util_test.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#39887 fix: [hotfix-2.5.4] Fix import failed due to 0 row num
  internal/datanode/importv2/task_import.go
  internal/datanode/importv2/util.go
  internal/datanode/importv2/util_test.go
Labels: size/S, ci-passed, manual-pass

#39708 fix: AlterCollection unable to modify ConsistencyLevel
  internal/rootcoord/alter_collection_task.go
  internal/rootcoord/alter_collection_task_test.go
  internal/rootcoord/create_collection_task.go
  internal/rootcoord/create_collection_task_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#39695 enhance: optimize expr performace for some points
  internal/core/src/exec/expression/BinaryArithOpEvalRangeExpr.cpp
  internal/core/src/exec/expression/BinaryArithOpEvalRangeExpr.h
  internal/core/src/exec/expression/BinaryRangeExpr.cpp
  internal/core/src/exec/expression/BinaryRangeExpr.h
  internal/core/src/exec/expression/Element.h
  internal/core/src/exec/expression/JsonContainsExpr.cpp
  internal/core/src/exec/expression/JsonContainsExpr.h
  internal/core/src/exec/expression/TermExpr.cpp
  internal/core/src/exec/expression/TermExpr.h
  internal/core/src/exec/expression/UnaryExpr.cpp
  internal/core/src/exec/expression/UnaryExpr.h
Labels: kind/enhancement, size/XL, approved, lgtm, ci-passed, dco-passed

#39903 fix: Fix import failed due to 0 row num
  internal/datanode/importv2/task_import.go
  internal/datanode/importv2/util.go
  internal/datanode/importv2/util_test.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#39904 fix: Fix import failed due to 0 row num (#39887)
  internal/datanode/importv2/task_import.go
  internal/datanode/importv2/util.go
  internal/datanode/importv2/util_test.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#39902 fix: [2.5]AlterCollection unable to modify ConsistencyLevel
  internal/rootcoord/alter_collection_task.go
  internal/rootcoord/alter_collection_task_test.go
  internal/rootcoord/create_collection_task.go
  internal/rootcoord/create_collection_task_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed, component/rootcoord

#39511 enhance: Add configs for compaction schedule (#39010)
  configs/milvus.yaml
  internal/datacoord/compaction.go
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#39812 enhance: return topks when search in restful v2
  internal/distributed/proxy/httpserver/constant.go
  internal/distributed/proxy/httpserver/handler_v2.go
  tests/restful_client_v2/testcases/test_vector_operations.py
Labels: kind/enhancement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#39890 fix: delegator doesn't follow with wal if streaming enabled
  internal/querycoordv2/balance/score_based_balancer.go
  internal/querycoordv2/checkers/leader_checker.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#39798 test: update sdk version and cases
  tests/python_client/milvus_client/test_milvus_client_search.py
  tests/python_client/requirements.txt
  tests/python_client/testcases/test_collection.py
  tests/python_client/testcases/test_high_level_api.py
  tests/python_client/testcases/test_mix_scenes.py
  tests/python_client/testcases/test_search.py
  tests/python_client/testcases/test_utility.py
Labels: sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#39816 test: Cherry pick sparse invert index algo tests
  tests/python_client/check/func_check.py
  tests/python_client/common/common_type.py
  tests/python_client/milvus_client/test_milvus_client_collection.py
  tests/python_client/milvus_client/test_milvus_client_search.py
  tests/python_client/requirements.txt
  tests/python_client/testcases/async_milvus_client/test_e2e_async.py
  tests/python_client/testcases/test_full_text_search.py
  tests/python_client/testcases/test_index.py
  tests/python_client/testcases/test_search.py
  tests/python_client/utils/util_pymilvus.py
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#39799 enhance: generate guaranteets at delegator if local wal
  internal/distributed/streaming/streaming.go
  internal/distributed/streaming/wal.go
  internal/distributed/streaming/wal_test.go
  internal/mocks/distributed/mock_streaming/mock_WALAccesser.go
  internal/mocks/streamingnode/client/mock_handler/mock_HandlerClient.go
  internal/mocks/streamingnode/server/mock_wal/mock_WAL.go
  internal/mocks/streamingnode/server/wal/interceptors/timetick/mock_inspector/mock_TimeTickSyncOperator.go
  internal/proxy/task.go
  internal/proxy/task_query.go
  internal/proxy/task_search.go
  internal/querynodev2/delegator/delegator.go
  internal/streamingnode/client/handler/handler_client.go
  internal/streamingnode/client/handler/handler_client_impl.go
  internal/streamingnode/client/handler/handler_client_test.go
  internal/streamingnode/server/wal/adaptor/wal_adaptor.go
  internal/streamingnode/server/wal/adaptor/wal_test.go
  internal/streamingnode/server/wal/interceptors/timetick/inspector/inspector.go
  internal/streamingnode/server/wal/interceptors/timetick/mvcc/mvcc_manager.go
  internal/streamingnode/server/wal/interceptors/timetick/mvcc/mvcc_manager_test.go
  internal/streamingnode/server/wal/interceptors/timetick/timetick_interceptor.go
  internal/streamingnode/server/wal/interceptors/timetick/timetick_sync_operator.go
  internal/streamingnode/server/wal/wal.go
  pkg/proto/internal.proto
  pkg/proto/internalpb/internal.pb.go
Labels: kind/enhancement, size/XXL, approved, lgtm, ci-passed, area/internal-api, dco-passed

#39900 fix: ignore growing option is lost at hibridsearch
  internal/proxy/task.go
  internal/proxy/task_query.go
  internal/proxy/task_search.go
  internal/querynodev2/delegator/delegator.go
  pkg/proto/internal.proto
  pkg/proto/internalpb/internal.pb.go
Labels: kind/bug, size/XXL, approved, lgtm, ci-passed, area/internal-api, dco-passed

#39919 fix: AlterCollection modify ConsistencyLevel test confict
  internal/rootcoord/alter_collection_task_test.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass, component/rootcoord

#39645 enhance: [2.5] Limit the speed of the generating stats task
  internal/datacoord/job_manager.go
  internal/datacoord/task_scheduler.go
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/component_param_test.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#39935 fix: Use `text_log` prefix for TextMatchIndex null offset file
  internal/core/src/exec/expression/UnaryExpr.cpp
  internal/core/src/index/TextMatchIndex.cpp
  internal/core/src/storage/MemFileManagerImpl.cpp
  internal/core/src/storage/MemFileManagerImpl.h
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#39908 fix:reset default auto index for varchar
  internal/proxy/task_index_test.go
  pkg/util/paramtable/autoindex_param.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#39327 enhance: optimize delete init construct code
  internal/core/src/segcore/ChunkedSegmentSealedImpl.cpp
  internal/core/src/segcore/DeletedRecord.h
  internal/core/src/segcore/SegmentGrowingImpl.h
  internal/core/src/segcore/SegmentSealedImpl.cpp
  internal/core/unittest/test_delete_record.cpp
  internal/core/unittest/test_utils.cpp
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#39926 enhance: [2.5] Optimize the result format of GetQueryNodeDistribution (#39664)
  internal/proxy/management.go
  internal/proxy/management_test.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#39929 enhance: [2.4] use rated logger for high frequency log in dist handler (#39452)
  internal/querycoordv2/balance/channel_level_score_balancer.go
  internal/querycoordv2/balance/score_based_balancer.go
  internal/querycoordv2/dist/dist_handler.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#39838 test: [GoSDK][2.5] Sync gosdk test commits from master branch
  client/milvusclient/database.go
  client/milvusclient/database_test.go
  tests/go_client/README.md
  tests/go_client/base/milvus_client.go
  tests/go_client/common/consts.go
  tests/go_client/common/utils.go
  tests/go_client/testcases/client_test.go
  tests/go_client/testcases/collection_test.go
  tests/go_client/testcases/database_test.go
  tests/go_client/testcases/delete_test.go
  tests/go_client/testcases/full_text_search_test.go
  tests/go_client/testcases/groupby_search_test.go
  tests/go_client/testcases/helper/collection_helper.go
  tests/go_client/testcases/helper/data_helper.go
  tests/go_client/testcases/helper/field_helper.go
  tests/go_client/testcases/helper/function_helper.go
  tests/go_client/testcases/helper/helper.go
  tests/go_client/testcases/helper/index_helper.go
  tests/go_client/testcases/helper/read_helper.go
  tests/go_client/testcases/helper/schema_helper.go
  tests/go_client/testcases/hybrid_search_test.go
  tests/go_client/testcases/index_test.go
  tests/go_client/testcases/insert_test.go
  tests/go_client/testcases/main_test.go
  tests/go_client/testcases/query_test.go
  tests/go_client/testcases/search_test.go
Labels: sig/testing, size/XXL, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#39943 enhance: make compatitle with old msgstream for new streaming service
  internal/datacoord/services.go
  internal/streamingnode/server/resource/resource.go
  internal/streamingnode/server/resource/resource_test.go
  internal/streamingnode/server/service/handler/producer/produce_server.go
  internal/streamingnode/server/wal/adaptor/old_version_message.go
  internal/streamingnode/server/wal/adaptor/old_version_message_test.go
  internal/streamingnode/server/wal/adaptor/scanner_switchable.go
  internal/streamingnode/server/wal/interceptors/wab/pending_queue.go
  internal/streamingnode/server/wal/vchantempstore/vchannel_temp_storage.go
  internal/streamingnode/server/wal/vchantempstore/vchannel_temp_storage_test.go
  pkg/mq/common/message.go
  pkg/mq/common/message_test.go
  pkg/streaming/util/message/adaptor/broadcast_message.go
  pkg/streaming/util/message/adaptor/handler.go
  pkg/streaming/util/message/adaptor/message.go
  pkg/streaming/util/message/version.go
Labels: kind/enhancement, size/XL, approved, lgtm, ci-passed, dco-passed, feature/streaming node

#39939 test: Enable more test cases for auto index
  tests/python_client/milvus_client/test_milvus_client_index.py
Labels: test/ut, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, python, kind/test

#39928 enhance: [2.5] use rated logger for high frequency log in dist handler (#39452)
  internal/querycoordv2/balance/channel_level_score_balancer.go
  internal/querycoordv2/balance/score_based_balancer.go
  internal/querycoordv2/dist/dist_handler.go
Labels: kind/enhancement, area/logging, size/M, approved, lgtm, ci-passed, dco-passed

#39507 fix: Adjust segment loader's memory estimate for intermin indexes
  internal/querynodev2/segments/segment_loader.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#39846 fix: [skip e2e] [2.5]data race in load test
  tests/integration/replicas/load/load_test.go
Labels: kind/bug, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed, manual-pass, test/integration

#39845 fix: [skip e2e] data race in load test
  tests/integration/replicas/load/load_test.go
Labels: kind/bug, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed, manual-pass, test/integration
