Repository milvus-io/milvus, pull requests merged in 2025-04, with the labels that each got.

#41007 fix: fix a 404 bug of WebUI when http.enablePprof is false
  internal/http/server.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed, go

#40951 fix: fix a 404 bug of WebUI when http.enablePprof is false
  internal/http/server.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed, go

#41015 fix: Fix passing wrong json_cast_type in e2e
  tests/python_client/milvus_client_v2/test_milvus_client_search_v2.py
Labels: kind/bug, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed, python

#40877 enhance: add proxy and datanode checker when wal balance startup
  internal/mocks/util/streamingutil/service/mock_discoverer/mock_Discoverer.go
  internal/mocks/util/streamingutil/service/mock_resolver/mock_Resolver.go
  internal/streamingcoord/client/client.go
  internal/streamingcoord/server/balancer/balancer_impl.go
  internal/streamingcoord/server/balancer/balancer_test.go
  internal/streamingnode/client/manager/manager_client.go
  internal/streamingnode/client/manager/manager_client_impl.go
  internal/streamingnode/client/manager/manager_test.go
  internal/util/streamingutil/service/discoverer/channel_assignment_discoverer.go
  internal/util/streamingutil/service/discoverer/channel_assignment_discoverer_test.go
  internal/util/streamingutil/service/discoverer/discoverer.go
  internal/util/streamingutil/service/discoverer/session_discoverer.go
  internal/util/streamingutil/service/discoverer/session_discoverer_test.go
  internal/util/streamingutil/service/resolver/builder.go
  internal/util/streamingutil/service/resolver/builder_test.go
  internal/util/streamingutil/service/resolver/resolver.go
  internal/util/streamingutil/service/resolver/resolver_with_discoverer.go
  internal/util/streamingutil/service/resolver/resolver_with_discoverer_test.go
  pkg/mq/msgstream/mq_msgstream.go
  pkg/streaming/util/message/message_test.go
  pkg/streaming/util/message/properties.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed, feature/streaming node

#40694 enhance: Add UTF-8 string validation for import
  internal/util/importutilv2/common/util.go
  internal/util/importutilv2/csv/row_parser.go
  internal/util/importutilv2/csv/row_parser_test.go
  internal/util/importutilv2/json/row_parser.go
  internal/util/importutilv2/json/row_parser_test.go
  internal/util/importutilv2/numpy/field_reader.go
  internal/util/importutilv2/numpy/field_reader_test.go
  internal/util/importutilv2/parquet/field_reader.go
  internal/util/importutilv2/parquet/field_reader_test.go
  internal/util/importutilv2/parquet/util.go
  pkg/util/typeutil/string_util.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed, go

#40666 fix: add log for object storage operation fail
  internal/core/src/storage/MinioChunkManager.h
  internal/core/src/storage/azure/AzureChunkManager.h
  internal/core/src/storage/gcp-native-storage/GcpNativeChunkManager.h
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#40898 enhance: add documents in batch for json key stats
  internal/core/src/index/JsonKeyStatsInvertedIndex.cpp
  internal/core/src/index/JsonKeyStatsInvertedIndex.h
  internal/core/thirdparty/tantivy/tantivy-binding/Cargo.lock
  internal/core/thirdparty/tantivy/tantivy-binding/Cargo.toml
  internal/core/thirdparty/tantivy/tantivy-binding/include/tantivy-binding.h
  internal/core/thirdparty/tantivy/tantivy-binding/src/index_reader.rs
  internal/core/thirdparty/tantivy/tantivy-binding/src/index_writer.rs
  internal/core/thirdparty/tantivy/tantivy-binding/src/index_writer_c.rs
  internal/core/thirdparty/tantivy/tantivy-wrapper.h
Labels: kind/enhancement, area/performance, size/L, approved, lgtm, ci-passed, dco-passed, do-not-merge/missing-related-pr

#40912 enhance: increate tantivy index worker and memory budget for json key stats for buliding index
  internal/core/src/index/JsonKeyStatsInvertedIndex.cpp
Labels: kind/enhancement, area/performance, size/XS, approved, lgtm, ci-passed, dco-passed

#41036 enhance: Use %v for missing id log
  internal/proxy/task_search.go
Labels: kind/enhancement, area/logging, size/XS, approved, lgtm, ci-passed, dco-passed

#41031 fix:fix format error for json
  internal/core/src/common/Utils.h
  internal/core/src/exec/Driver.cpp
  internal/core/src/index/VectorMemIndex.cpp
  internal/core/unittest/test_sealed.cpp
  scripts/core_build.sh
  tests/python_client/testcases/test_search.py
Labels: kind/bug, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, do-not-merge/missing-related-pr

#40903 enhance: weighted reranker to allow skip score normalization
  internal/proxy/reScorer.go
  internal/proxy/reScorer_test.go
  internal/proxy/task.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#40956 fix: Get all children deltalogs for segment to load
  internal/datacoord/services.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#41013 fix: [2.5]Add bypass thread pool mode to avoid growing indexes blocking insert/load
  internal/core/src/index/IndexFactory.cpp
  internal/core/src/index/IndexFactory.h
  internal/core/src/index/VectorMemIndex.cpp
  internal/core/src/index/VectorMemIndex.h
  internal/core/src/segcore/ChunkedSegmentSealedImpl.cpp
  internal/core/src/segcore/FieldIndexing.cpp
  internal/core/src/segcore/SegmentSealedImpl.cpp
  internal/core/thirdparty/knowhere/CMakeLists.txt
  internal/core/unittest/test_growing_index.cpp
  internal/core/unittest/test_utils/DataGen.h
  internal/core/unittest/test_utils/indexbuilder_test_utils.h
Labels: kind/bug, test/ut, area/knowhere, size/L, approved, lgtm, ci-passed, dco-passed, area/compilation

#40905 enhance: [2.5] weighted reranker to allow skip score normalization
  internal/proxy/reScorer.go
  internal/proxy/reScorer_test.go
  internal/proxy/task.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#41058 fix: fix arm64 compile issue
  internal/core/thirdparty/tantivy/tantivy-binding/src/index_writer.rs
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed, area/compilation, kind/branch-feature

#41052 fix:[2.5]Inserting null and non-null array at the same time will cause milvus crash when growing mmap open
  internal/core/src/mmap/ChunkData.h
Labels: kind/bug, severity/critical, size/XS, approved, lgtm, ci-passed, dco-passed

#41027 fix: array is null failed(#40686)
  internal/core/src/exec/expression/Expr.h
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#41056 fix: Align brute force search with json index for exists expr
  internal/core/src/common/Json.h
  internal/core/src/index/JsonInvertedIndex.cpp
  internal/core/unittest/test_expr.cpp
  internal/core/unittest/test_json_index.cpp
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#41040 test: add coo format for sparse vector import and some negative case
  tests/restful_client_v2/testcases/test_jobs_operation.py
Labels: kind/improvement, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#41047 test: [cherry-pick][2.4]using pytest_tagging to replace pytest_tags
  tests/python_client/requirements.txt
Labels: area/dependency, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed, PR | need cherry-pick, kind/test

#41054 fix: fix compare two column move cursor bug
  internal/core/src/segcore/SegmentChunkReader.h
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed, do-not-merge/missing-related-pr

#41073 fix: segv if the LoadArrowReaderFromRemote run at the exception path
  internal/core/src/segcore/Utils.cpp
Labels: kind/bug, size/XS, approved, lgtm, dco-passed

#41075 fix: jsonstats check if cache schema is nil lazy describecollection
  internal/core/src/segcore/Utils.cpp
  internal/querycoordv2/checkers/index_checker.go
  internal/querycoordv2/meta/collection_manager.go
Labels: kind/bug, size/S, approved, lgtm

#41076 fix: [hotfix-2.5.8] Address manual balance and balance check issues
  configs/milvus.yaml
  internal/querycoordv2/checkers/balance_checker.go
  internal/querycoordv2/checkers/balance_checker_test.go
  internal/querycoordv2/handlers.go
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/component_param_test.go
Labels: kind/bug, area/performance, size/M, approved, lgtm, ci-passed

#41068 fix: jsonstats check if cache schema is nil lazy describecollection
  internal/querycoordv2/checkers/index_checker.go
  internal/querycoordv2/meta/collection_manager.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#41038 fix: [2.5] Address manual balance and balance check issues
  configs/milvus.yaml
  internal/querycoordv2/checkers/balance_checker.go
  internal/querycoordv2/checkers/balance_checker_test.go
  internal/querycoordv2/handlers.go
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/component_param_test.go
Labels: kind/bug, kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#41071 fix: segv if the LoadArrowReaderFromRemote run at the exception path
  internal/core/src/segcore/Utils.cpp
Labels: kind/bug, severity/critical, size/XS, approved, lgtm, ci-passed, dco-passed

#41069 fix: segv if the LoadArrowReaderFromRemote run at the exception path
  internal/core/src/segcore/Utils.cpp
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#41016 test: Add test cases for part of json path index
  tests/python_client/common/bulk_insert_data.py
  tests/python_client/common/common_func.py
  tests/python_client/common/common_type.py
  tests/python_client/milvus_client/test_milvus_client_alias.py
  tests/python_client/milvus_client/test_milvus_client_collection.py
  tests/python_client/milvus_client/test_milvus_client_compact.py
  tests/python_client/milvus_client/test_milvus_client_delete.py
  tests/python_client/milvus_client/test_milvus_client_hybrid_search.py
  tests/python_client/milvus_client/test_milvus_client_index.py
  tests/python_client/milvus_client/test_milvus_client_insert.py
  tests/python_client/milvus_client/test_milvus_client_partition.py
  tests/python_client/milvus_client/test_milvus_client_query.py
  tests/python_client/milvus_client/test_milvus_client_search.py
  tests/python_client/milvus_client/test_milvus_client_search_iterator.py
  tests/python_client/milvus_client_v2/test_milvus_client_search_diskann.py
  tests/python_client/milvus_client_v2/test_milvus_client_search_group_by.py
  tests/python_client/milvus_client_v2/test_milvus_client_search_text_match.py
  tests/python_client/milvus_client_v2/test_milvus_client_search_v2.py
  tests/python_client/requirements.txt
  tests/python_client/testcases/test_bulk_insert.py
Labels: sig/testing, size/XXL, approved, lgtm, area/test, ci-passed, dco-passed, python, kind/test

#41074 test: [cherry-pick-2.5] Add test cases for json path index
  tests/python_client/base/client_v2_base.py
  tests/python_client/check/func_check.py
  tests/python_client/common/bulk_insert_data.py
  tests/python_client/common/common_func.py
  tests/python_client/common/common_type.py
  tests/python_client/milvus_client/test_milvus_client_alias.py
  tests/python_client/milvus_client/test_milvus_client_collection.py
  tests/python_client/milvus_client/test_milvus_client_compact.py
  tests/python_client/milvus_client/test_milvus_client_database.py
  tests/python_client/milvus_client/test_milvus_client_delete.py
  tests/python_client/milvus_client/test_milvus_client_hybrid_search.py
  tests/python_client/milvus_client/test_milvus_client_index.py
  tests/python_client/milvus_client/test_milvus_client_insert.py
  tests/python_client/milvus_client/test_milvus_client_partition.py
  tests/python_client/milvus_client/test_milvus_client_query.py
  tests/python_client/milvus_client/test_milvus_client_search.py
  tests/python_client/milvus_client/test_milvus_client_search_iterator.py
  tests/python_client/requirements.txt
  tests/python_client/testcases/test_bulk_insert.py
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/XXL, approved, lgtm, area/test, ci-passed, dco-passed, python, PR | need cherry-pick, kind/test

#41083 test: [cp] add more varchar expressions for query
  tests/python_client/common/common_func.py
  tests/python_client/testcases/test_mix_scenes.py
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#41037 fix: Address manual balance and balance check issues
  configs/milvus.yaml
  internal/datanode/compactor/clustering_compactor_storage_v2_test.go
  internal/datanode/compactor/mix_compactor_storage_v2_test.go
  internal/querycoordv2/checkers/balance_checker.go
  internal/querycoordv2/checkers/balance_checker_test.go
  internal/querycoordv2/handlers.go
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/component_param_test.go
Labels: kind/bug, area/performance, kind/improvement, size/M, approved, lgtm, ci-passed, dco-passed

#41079 test: add import corner testcase
  tests/restful_client_v2/testcases/test_jobs_operation.py
Labels: kind/improvement, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#41080 test: update test cases
  tests/python_client/testcases/test_search.py
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed, kind/branch-feature, kind/test

#41082 test: add negative case when field name is reserved keywords
  tests/python_client/testcases/test_collection.py
Labels: kind/improvement, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#41090 enhance: [2.5] Use `%v` for missing id log (#41036)
  internal/proxy/task_search.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed, PR | need cherry-pick

#40959 enhance: vchannel fair balance policy for streaming
  configs/milvus.yaml
  internal/distributed/datacoord/service_test.go
  internal/distributed/querycoord/service_test.go
  internal/distributed/rootcoord/service_test.go
  internal/proxy/proxy_test.go
  internal/rootcoord/constrant_test.go
  internal/rootcoord/meta_table.go
  internal/rootcoord/meta_table_test.go
  internal/rootcoord/root_coord_test.go
  internal/streamingcoord/server/balancer/balancer_impl.go
  internal/streamingcoord/server/balancer/balancer_test.go
  internal/streamingcoord/server/balancer/channel/manager.go
  internal/streamingcoord/server/balancer/channel/manager_test.go
  internal/streamingcoord/server/balancer/channel/metrics.go
  internal/streamingcoord/server/balancer/channel/pchannel.go
  internal/streamingcoord/server/balancer/channel/pchannel_stats.go
  internal/streamingcoord/server/balancer/channel/pchannel_test.go
  internal/streamingcoord/server/balancer/channel/pchannel_view.go
  internal/streamingcoord/server/balancer/channel/pchannel_view_test.go
  internal/streamingcoord/server/balancer/channel/test_utility.go
  internal/streamingcoord/server/balancer/metrics.go
  internal/streamingcoord/server/balancer/policy/init.go
  internal/streamingcoord/server/balancer/policy/pchannel_count_fair.go
  internal/streamingcoord/server/balancer/policy/pchannel_count_fair_test.go
  internal/streamingcoord/server/balancer/policy/vchannelfair/builder.go
  internal/streamingcoord/server/balancer/policy/vchannelfair/expected_layout.go
  internal/streamingcoord/server/balancer/policy/vchannelfair/pchannel_affinity.go
  internal/streamingcoord/server/balancer/policy/vchannelfair/pchannel_count_fair_test.go
  internal/streamingcoord/server/balancer/policy/vchannelfair/vchannel_fair_policy.go
  internal/streamingcoord/server/balancer/policy/vchannelfair/vchannel_fair_policy_test.go
  internal/streamingcoord/server/balancer/policy_registry.go
  internal/streamingcoord/server/server.go
  internal/util/testutil/reset_env.go
  pkg/metrics/streaming_service_metrics.go
  pkg/streaming/util/types/pchannel_info.go
  pkg/streaming/util/types/streaming_node.go
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/component_param_test.go
  pkg/util/syncutil/future.go
  tests/integration/coorddownsearch/search_after_coord_down_test.go
  tests/integration/coordrecovery/coord_recovery_test.go
  tests/integration/minicluster_v2.go
Labels: kind/enhancement, sig/testing, size/XXL, approved, lgtm, area/test, ci-passed, dco-passed, test/integration, feature/streaming node

#40982 fix: create collection task check failed after restart
  internal/metastore/model/field.go
  internal/metastore/model/field_test.go
  internal/metastore/model/partition.go
  internal/metastore/model/partition_test.go
  internal/proxy/proxy_test.go
  internal/proxy/task_test.go
  tests/integration/jsonexpr/json_expr_test.go
  tests/integration/meta_watcher_test.go
Labels: kind/bug, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed, test/integration

#41026 fix:fix format error for json
  internal/core/src/common/Utils.h
  internal/core/src/index/VectorMemIndex.cpp
  internal/core/unittest/test_sealed.cpp
  tests/python_client/milvus_client_v2/test_milvus_client_search_invalid.py
Labels: kind/bug, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#41045 enhance: Deprecate disk params about indexing
  configs/milvus.yaml
  internal/datacoord/index_service.go
  internal/datacoord/index_service_test.go
  internal/datacoord/server.go
  internal/datacoord/session/indexnode_manager.go
  internal/datacoord/session/indexnode_manager_test.go
  internal/datanode/index/task_index.go
  internal/datanode/index_services.go
  internal/util/sessionutil/session_util.go
  pkg/proto/worker.proto
  pkg/proto/workerpb/worker.pb.go
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/component_param_test.go
Labels: kind/enhancement, kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#41078 enhance: [2.5]Deprecate disk params about indexing
  configs/milvus.yaml
  internal/datacoord/index_service.go
  internal/datacoord/index_service_test.go
  internal/datacoord/server.go
  internal/datacoord/session/indexnode_manager.go
  internal/datacoord/session/indexnode_manager_test.go
  internal/indexnode/indexnode.go
  internal/indexnode/indexnode_service.go
  internal/indexnode/task_index.go
  internal/util/sessionutil/session_util.go
  pkg/proto/worker.proto
  pkg/proto/workerpb/worker.pb.go
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/component_param_test.go
Labels: kind/enhancement, kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#40968 fix: Add the field index lock for getSegmentsIndexStates
  internal/datacoord/index_meta.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#41094 enhance: add formatter for serveral types to remove compile warning
  internal/core/src/common/Types.h
  internal/core/src/index/JsonInvertedIndex.h
  internal/core/src/storage/ThreadPools.h
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#40895 fix:add operator type for some operator
  internal/core/src/exec/operator/CountNode.cpp
  internal/core/src/exec/operator/GroupByNode.cpp
  internal/core/src/exec/operator/MvccNode.cpp
  internal/core/src/exec/operator/Operator.h
  internal/core/src/exec/operator/VectorSearchNode.cpp
Labels: kind/bug, kind/improvement, size/S, approved, lgtm, ci-passed, dco-passed

#40827 fix: Offline segment block delegator recovery
  internal/querycoordv2/utils/util.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#41116 fix: Align brute force search with json index for exists expr
  internal/core/src/common/Json.h
  internal/core/src/index/JsonInvertedIndex.cpp
  internal/core/unittest/test_expr.cpp
  internal/core/unittest/test_json_index.cpp
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#41127 fix: [2.5] Avoid update original search/query request
  internal/proxy/task_query.go
  internal/proxy/task_search.go
  internal/proxy/task_search_test.go
Labels: kind/bug, size/M, approved, lgtm, dco-passed, PR | need cherry-pick

#41130 fix: Ignore growing segment without start pos for seal policy
  internal/datacoord/segment_allocation_policy.go
  internal/datacoord/segment_allocation_policy_test.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#41010 fix: [2.5] Correctly parse the minimum value of int64
  internal/parser/planparserv2/Plan.g4
  internal/parser/planparserv2/generated/Plan.interp
  internal/parser/planparserv2/generated/plan_parser.go
  internal/parser/planparserv2/parser_visitor.go
  internal/parser/planparserv2/plan_parser_v2_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed, go

#41131 fix: [2.5] Ignore growing segment without start pos for seal policy
  internal/datacoord/segment_allocation_policy.go
  internal/datacoord/segment_allocation_policy_test.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed, PR | need cherry-pick

#41135 fix: Fix the bug that null data can not filtered by null expr
  internal/core/src/exec/expression/EvalCtx.h
  internal/core/src/exec/expression/ExistsExpr.cpp
  internal/core/src/exec/expression/LogicalUnaryExpr.cpp
  internal/core/unittest/test_expr.cpp
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#40007 enhance: process batch of strings within one tantivy_index_add_string call
  internal/core/thirdparty/tantivy/tantivy-binding/include/tantivy-binding.h
  internal/core/thirdparty/tantivy/tantivy-binding/src/index_reader.rs
  internal/core/thirdparty/tantivy/tantivy-binding/src/index_writer.rs
  internal/core/thirdparty/tantivy/tantivy-binding/src/index_writer_c.rs
  internal/core/thirdparty/tantivy/tantivy-binding/src/index_writer_v5/index_writer.rs
  internal/core/thirdparty/tantivy/tantivy-binding/src/index_writer_v7/index_writer.rs
  internal/core/thirdparty/tantivy/tantivy-wrapper.h
Labels: kind/enhancement, kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#41109 fix: keep the last persisted message in writeaheadbuffer to fix the never catch up
  internal/streamingnode/server/wal/interceptors/wab/pending_queue.go
  internal/streamingnode/server/wal/interceptors/wab/pending_queue_test.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#41093 fix: assigning the correct storage version in sync and index tasks
  internal/datacoord/meta.go
  internal/datacoord/services.go
  internal/datacoord/task_index.go
  internal/datacoord/task_stats.go
  internal/datanode/compactor/segment_writer.go
  internal/datanode/index/task_stats.go
  internal/flushcommon/metacache/actions.go
  internal/flushcommon/metacache/segment.go
  internal/flushcommon/syncmgr/meta_writer.go
  internal/flushcommon/writebuffer/l0_write_buffer.go
  internal/flushcommon/writebuffer/manager.go
  internal/flushcommon/writebuffer/manager_test.go
  internal/flushcommon/writebuffer/mock_manager.go
  internal/flushcommon/writebuffer/mock_write_buffer.go
  internal/flushcommon/writebuffer/write_buffer.go
  internal/storage/rw_test.go
  internal/storage/serde_events.go
  internal/storage/serde_events_v2.go
  internal/storage/sort.go
  internal/streamingnode/server/flusher/flusherimpl/msg_handler_impl.go
  pkg/proto/worker.proto
  pkg/proto/workerpb/worker.pb.go
  tests/integration/compaction/mix_compaction_test.go
  tests/integration/insert/insert_test.go
Labels: kind/bug, sig/testing, size/XXL, approved, lgtm, area/test, ci-passed, dco-passed, test/integration

#41089 enhance: Rectify client_request_id logic
  pkg/util/logutil/grpc_interceptor.go
  pkg/util/logutil/grpc_interceptor_test.go
Labels: kind/enhancement, kind/improvement, area/logging, size/S, approved, lgtm, ci-passed, dco-passed

#41132 test: Fix test cases for part of json path index
  tests/python_client/milvus_client/test_milvus_client_database.py
  tests/python_client/milvus_client/test_milvus_client_index.py
  tests/python_client/testcases/test_collection.py
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, python, kind/test

#41049 fix: remove metrics reset calls to ensure accurate reporting
  internal/querynodev2/metrics_info.go
Labels: kind/bug, area/monitoring, size/XS, approved, lgtm, ci-passed, dco-passed, component/querynode

#41081 fix: remove metrics reset calls to ensure accurate reporting
  internal/querynodev2/metrics_info.go
Labels: kind/bug, area/monitoring, size/XS, approved, lgtm, ci-passed, dco-passed

#40975 enhance: Optimize log output for L0 segment deletions
  internal/querynodev2/delegator/delegator_data.go
Labels: kind/enhancement, area/logging, size/M, approved, lgtm, ci-passed, dco-passed, component/querynode

#41126 fix: Avoid update original search/query request
  internal/proxy/task_query.go
  internal/proxy/task_search.go
  internal/proxy/task_search_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#39854 enhance: support use jieba tokenizer with costum dictionary
  internal/core/thirdparty/tantivy/tantivy-binding/src/analyzer/analyzer.rs
  internal/core/thirdparty/tantivy/tantivy-binding/src/analyzer/build_in_analyzer.rs
  internal/core/thirdparty/tantivy/tantivy-binding/src/analyzer/tokenizers/jieba_tokenizer.rs
  internal/core/thirdparty/tantivy/tantivy-binding/src/analyzer/tokenizers/tokenizer.rs
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#40179 fix: create multiple idential indexes by accident
  go.mod
  internal/datacoord/compaction_task_clustering_test.go
  internal/datacoord/handler_test.go
  internal/datacoord/index_meta.go
  internal/datacoord/index_meta_test.go
  internal/datacoord/index_service.go
  internal/datacoord/server_test.go
  internal/datacoord/services_test.go
Labels: kind/bug, area/dependency, size/L, approved, lgtm, ci-passed, dco-passed

#41124 fix: Fix the bug that null data can not be filtered by null expr
  internal/core/src/exec/expression/EvalCtx.h
  internal/core/src/exec/expression/ExistsExpr.cpp
  internal/core/src/exec/expression/LogicalUnaryExpr.cpp
  internal/core/unittest/test_expr.cpp
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#40124 enhance: process tantivy document add by batch
  internal/core/thirdparty/tantivy/tantivy-binding/src/index_reader_text.rs
  internal/core/thirdparty/tantivy/tantivy-binding/src/index_reader_text_c.rs
  internal/core/thirdparty/tantivy/tantivy-binding/src/index_writer.rs
  internal/core/thirdparty/tantivy/tantivy-binding/src/index_writer_c.rs
  internal/core/thirdparty/tantivy/tantivy-binding/src/index_writer_v5/index_writer.rs
  internal/core/thirdparty/tantivy/tantivy-binding/src/index_writer_v7/index_writer.rs
  internal/core/unittest/test_text_match.cpp
Labels: kind/enhancement, area/performance, size/L, approved, lgtm, ci-passed, test/benchmark, dco-passed

#39084 enhance: Support slot for index task and stats task
  configs/milvus.yaml
  internal/datacoord/index_service.go
  internal/datacoord/job_manager.go
  internal/datacoord/session/indexnode_manager.go
  internal/datacoord/session/indexnode_manager_test.go
  internal/datacoord/session/mock_worker_manager.go
  internal/datacoord/task_analyze.go
  internal/datacoord/task_index.go
  internal/datacoord/task_scheduler.go
  internal/datacoord/task_scheduler_test.go
  internal/datacoord/task_stats.go
  internal/datacoord/task_stats_test.go
  internal/datacoord/types.go
  internal/datacoord/util.go
  internal/datanode/data_node.go
  internal/datanode/index/scheduler.go
  internal/datanode/index/scheduler_test.go
  internal/datanode/index/task.go
  internal/datanode/index/task_analyze.go
  internal/datanode/index/task_index.go
  internal/datanode/index/task_stats.go
  internal/datanode/index/util.go
  internal/datanode/index_services.go
  internal/datanode/index_services_test.go
  pkg/proto/worker.proto
  pkg/proto/workerpb/worker.pb.go
  pkg/util/paramtable/component_param.go
  tests/_helm/values/e2e/distributed
  tests/_helm/values/e2e/standalone
  tests/_helm/values/e2e/standalone-kafka-mmap
  tests/_helm/values/e2e/standalone-one-pod
Labels: kind/enhancement, sig/testing, size/XXL, approved, lgtm, area/test, ci-passed, dco-passed

#41163 fix: fix remove index type failed when remote storage is local mode
  internal/core/src/index/InvertedIndexTantivy.cpp
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#41157 fix: Use element_type for Array is null operator
  internal/core/src/exec/expression/ExistsExpr.cpp
  internal/core/src/exec/expression/ExistsExpr.h
  internal/core/src/exec/expression/Expr.h
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#41055 enhance: update packed reader api
  internal/core/src/segcore/packed_reader_c.cpp
  internal/core/thirdparty/milvus-storage/CMakeLists.txt
  internal/core/unittest/test_packed_c.cpp
  internal/storage/schema.go
  internal/storagev2/packed/constant.go
  internal/storagev2/packed/packed_test.go
Labels: kind/enhancement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed, area/compilation, test/integration

#41149 enhance: [2.5] Rectify client_request_id logic (#41089)
  pkg/util/logutil/grpc_interceptor.go
  pkg/util/logutil/grpc_interceptor_test.go
Labels: kind/enhancement, area/logging, size/S, approved, lgtm, ci-passed, dco-passed, PR | need cherry-pick

#41161 fix: [GoSDK] Fill collection schema for query resultset
  client/milvusclient/read.go
  client/milvusclient/read_test.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed, component/gosdk

#39220 enhance: Add primary field name in SearchResult and QueryResults
  client/go.mod
  internal/proxy/task_query.go
  internal/proxy/task_search.go
Labels: kind/enhancement, area/dependency, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed

#41165 fix:add clear bitmap for batch skip mode
  internal/core/src/exec/expression/ConjunctExpr.cpp
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#41166 fix:add clear bitmap for batch skip mode
  internal/core/src/exec/expression/ConjunctExpr.cpp
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#41173 just for test: Go core dump test
  internal/core/src/segcore/segment_c.cpp
  internal/core/src/segcore/segment_c.h
  internal/querynodev2/segments/cgo_util.go
  internal/querynodev2/segments/retrieve_test.go
Labels: size/S, dco-passed, do-not-merge/missing-related-pr, do-not-merge/invalid-pr-format

#41164 fix: fix remove index type failed when remote storage is local mode
  internal/core/src/index/InvertedIndexTantivy.cpp
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#41064 test: update run analyzer test
  tests/python_client/milvus_client/test_milvus_client_analyzer.py
  tests/python_client/requirements.txt
Labels: kind/improvement, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed, test/integration, kind/test

#41137 test: Add more json value expression tests
  tests/python_client/common/common_func.py
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#41170 test: [E2e Refactor]gen collection name by testcase name and update search pagination test
  tests/python_client/base/client_base.py
  tests/python_client/base/client_v2_base.py
  tests/python_client/common/common_func.py
  tests/python_client/milvus_client_v2/test_milvus_client_e2e.py
  tests/python_client/milvus_client_v2/test_milvus_client_search_pagination.py
  tests/python_client/testcases/test_e2e.py
Labels: sig/testing, size/XL, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#41184 fix: [2.5][RESTFUL] Return error when writer body closed
  internal/distributed/proxy/httpserver/timeout_middleware.go
Labels: kind/bug, size/XS, approved, lgtm, dco-passed, manual-pass, PR | need cherry-pick

#41159 fix: remove single segment logic in V7
  internal/core/thirdparty/tantivy/tantivy-binding/include/tantivy-binding.h
  internal/core/thirdparty/tantivy/tantivy-binding/src/index_writer.rs
  internal/core/thirdparty/tantivy/tantivy-binding/src/index_writer_c.rs
  internal/core/thirdparty/tantivy/tantivy-binding/src/index_writer_v5/analyzer/analyzer.rs
  internal/core/thirdparty/tantivy/tantivy-binding/src/index_writer_v5/analyzer/filter.rs
  internal/core/thirdparty/tantivy/tantivy-binding/src/index_writer_v5/analyzer/tokenizers/lindera_tokenizer.rs
  internal/core/thirdparty/tantivy/tantivy-binding/src/index_writer_v5/analyzer/tokenizers/tokenizer.rs
  internal/core/thirdparty/tantivy/tantivy-binding/src/index_writer_v5/index_writer.rs
  internal/core/thirdparty/tantivy/tantivy-binding/src/index_writer_v5/index_writer_text.rs
  internal/core/thirdparty/tantivy/tantivy-binding/src/index_writer_v7/index_writer.rs
  internal/core/thirdparty/tantivy/tantivy-binding/src/index_writer_v7/index_writer_text.rs
  internal/core/thirdparty/tantivy/tantivy-binding/src/tokenizer_c.rs
  internal/core/thirdparty/tantivy/tantivy-wrapper.h
  internal/core/unittest/CMakeLists.txt
  internal/core/unittest/test_build_inverted_index_with_single_segment.cpp
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed, area/compilation, manual-pass

#41192 fix: [2.5] Revert add a sign (positive or negative) to constants
  internal/parser/planparserv2/Plan.g4
  internal/parser/planparserv2/generated/Plan.interp
  internal/parser/planparserv2/generated/plan_parser.go
  internal/parser/planparserv2/parser_visitor.go
  internal/parser/planparserv2/plan_parser_v2_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#41189 fix: [2.5] get replicate channel position
  internal/proxy/impl.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#41193 test: [cherry-pick] gen collection name by testcase name
  tests/python_client/base/client_base.py
  tests/python_client/base/client_v2_base.py
  tests/python_client/common/common_func.py
  tests/python_client/milvus_client_v2/test_milvus_client_e2e.py
  tests/python_client/testcases/test_e2e.py
Labels: sig/testing, size/XL, approved, lgtm, area/test, ci-passed, dco-passed, PR | need cherry-pick, kind/test

#41096 test: add JsonQueryChecker in test
  tests/python_client/chaos/checker.py
  tests/python_client/chaos/testcases/test_concurrent_operation.py
  tests/python_client/chaos/testcases/test_single_request_operation.py
  tests/python_client/common/common_func.py
Labels: kind/improvement, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#41204 fix: [2.5] show collections support custom privilege groups granted objects
  internal/rootcoord/show_collection_task.go
  internal/rootcoord/show_collection_task_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#41186 fix: Use int32 when creating array index for element type int8/int16
  internal/core/src/index/InvertedIndexTantivy.cpp
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#41203 fix: show collections support custom privilege groups granted objects
  internal/rootcoord/show_collection_task.go
  internal/rootcoord/show_collection_task_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#41183 fix: [RESTFUL] Return error when writer body closed
  internal/distributed/proxy/httpserver/timeout_middleware.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#41188 fix: get replicate channel position
  internal/proxy/impl.go
  pkg/mq/msgdispatcher/manager_test.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#41196 fix: balance checker may enter infinite normal balance loop after balance suspension
  internal/querycoordv2/checkers/balance_checker.go
  internal/querycoordv2/checkers/balance_checker_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#41195 fix: balance checker may enter infinite normal balance loop after balance suspension
  internal/querycoordv2/checkers/balance_checker.go
  internal/querycoordv2/checkers/balance_checker_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#41211 enhance: [Restful] Make default timeout configurable
  internal/distributed/proxy/httpserver/constant.go
  internal/distributed/proxy/httpserver/timeout_middleware.go
  internal/http/constant.go
  pkg/util/paramtable/http_param.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#41221 fix: [2.5] Remove noexcept from `CacheIndexToDiskInternal`
  internal/core/src/storage/DiskFileManagerImpl.cpp
  internal/core/src/storage/DiskFileManagerImpl.h
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass, kind/branch-feature

#41171 enhance: Refine logs in compaction trigger
  internal/datacoord/compaction.go
  internal/datacoord/compaction_policy_clustering.go
  internal/datacoord/compaction_trigger.go
Labels: kind/enhancement, kind/improvement, area/logging, size/M, approved, lgtm, ci-passed, dco-passed

#41201 fix: catchup cannot work if using StartAfter
  internal/distributed/streaming/internal/consumer/consumer_impl.go
  internal/streamingnode/server/flusher/flusherimpl/wal_flusher.go
  internal/streamingnode/server/wal/adaptor/scanner_switchable.go
  internal/streamingnode/server/wal/interceptors/wab/pending_queue.go
  internal/streamingnode/server/wal/interceptors/wab/write_ahead_buffer.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#40545 fix: avoid segmentation faults caused by retrieving empty vector datasets
  internal/core/src/index/VectorDiskIndex.cpp
  internal/core/src/index/VectorMemIndex.cpp
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#41177 enhance: remove not inused util/* in datanode
  internal/datanode/data_node.go
  internal/datanode/util/cache.go
  internal/datanode/util/cache_test.go
  internal/datanode/util/meta_util.go
Labels: kind/enhancement, kind/improvement, size/L, approved, lgtm, ci-passed, dco-passed

#40965 fix: correct typo `kvmetestore` -> `kvmetastore`
  internal/rootcoord/root_coord.go
Labels: kind/bug, kind/enhancement, kind/improvement, size/S, approved, lgtm, ci-passed, do-not-merge/missing-related-issue, dco-passed, manual-pass

#41217 fix: CreateStatsRequest change storage_version to 25 consistent with 2.5
  internal/datacoord/task_stats.go
  pkg/proto/worker.proto
  pkg/proto/workerpb/worker.pb.go
Labels: kind/bug, size/M, approved, lgtm, dco-passed

#41225 enhance: [2.5][Restful] Make default timeout configurable (#41211)
  internal/distributed/proxy/httpserver/constant.go
  internal/distributed/proxy/httpserver/timeout_middleware.go
  internal/http/constant.go
  pkg/util/paramtable/http_param.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#41185 fix: Use int32 when creating array index for element type int8/int16
  internal/core/src/index/InvertedIndexTantivy.cpp
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#41234 enhance: [GoSDK] Add more example for godoc
  client/entity/schema_example_test.go
  client/index/auto_example_test.go
  client/milvusclient/collection_example_test.go
  client/milvusclient/index_example_test.go
  client/milvusclient/rbac_example_test.go
  client/milvusclient/read_example_test.go
  client/milvusclient/write_example_test.go
Labels: kind/enhancement, size/XL, approved, lgtm, ci-passed, dco-passed

#41228 enhance: add documents in batch for json key stats
  internal/core/src/exec/expression/UnaryExpr.cpp
  internal/core/src/index/InvertedIndexTantivy.cpp
  internal/core/src/index/JsonKeyStatsInvertedIndex.cpp
  internal/core/src/index/JsonKeyStatsInvertedIndex.h
  internal/core/thirdparty/tantivy/tantivy-binding/Cargo.lock
  internal/core/thirdparty/tantivy/tantivy-binding/Cargo.toml
  internal/core/thirdparty/tantivy/tantivy-binding/include/tantivy-binding.h
  internal/core/thirdparty/tantivy/tantivy-binding/src/index_writer.rs
  internal/core/thirdparty/tantivy/tantivy-binding/src/index_writer_c.rs
  internal/core/thirdparty/tantivy/tantivy-binding/src/index_writer_v5/index_writer.rs
  internal/core/thirdparty/tantivy/tantivy-binding/src/index_writer_v7/index_writer.rs
  internal/core/thirdparty/tantivy/tantivy-wrapper.h
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#41237 enhance: Fill dbname for AddCollectionFieldRequest
  internal/proxy/database_interceptor.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#39249 enhance: Remove single chunk segment related codes
  configs/milvus.yaml
  internal/core/src/common/Types.h
  internal/core/src/common/type_c.h
  internal/core/src/exec/expression/Expr.h
  internal/core/src/exec/expression/UnaryExpr.cpp
  internal/core/src/exec/operator/Utils.h
  internal/core/src/exec/operator/groupby/SearchGroupByOperator.cpp
  internal/core/src/exec/operator/groupby/SearchGroupByOperator.h
  internal/core/src/index/InvertedIndexTantivy.cpp
  internal/core/src/mmap/Column.h
  internal/core/src/mmap/Types.h
  internal/core/src/segcore/ChunkedSegmentSealedImpl.cpp
  internal/core/src/segcore/ChunkedSegmentSealedImpl.h
  internal/core/src/segcore/InsertRecord.h
  internal/core/src/segcore/SegmentChunkReader.cpp
  internal/core/src/segcore/SegmentSealedImpl.cpp
  internal/core/src/segcore/SegmentSealedImpl.h
  internal/core/src/segcore/segment_c.cpp
  internal/core/src/storage/ChunkCache.cpp
  internal/core/src/storage/ChunkCache.h
  internal/core/src/storage/Util.h
  internal/core/unittest/test_array_inverted_index.cpp
  internal/core/unittest/test_binlog_index.cpp
  internal/core/unittest/test_c_api.cpp
  internal/core/unittest/test_chunk_cache.cpp
  internal/core/unittest/test_chunked_segment.cpp
  internal/core/unittest/test_delete_record.cpp
  internal/core/unittest/test_exec.cpp
  internal/core/unittest/test_expr.cpp
  internal/core/unittest/test_expr_materialized_view.cpp
  internal/core/unittest/test_group_by.cpp
  internal/core/unittest/test_iterative_filter.cpp
  internal/core/unittest/test_query.cpp
  internal/core/unittest/test_regex_query.cpp
  internal/core/unittest/test_sealed.cpp
  internal/core/unittest/test_utils/DataGen.h
  internal/querynodev2/segments/segment.go
  internal/util/segcore/segment.go
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/XXL, approved, lgtm, ci-passed, dco-passed

#41244 fix: remove dead config queryNode.grouping.enabled
  configs/milvus.yaml
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/component_param_test.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#41267 fix: change log info to debug for collection ref
  internal/querynodev2/segments/collection.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#41249 test: add go cases for upsert autoid row
  tests/go_client/testcases/upsert_test.go
Labels: sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed, manual-pass, kind/test

#40839 enhance: Optimize index format for improved load performance(#40838)
  internal/core/src/index/BitmapIndex.cpp
  internal/core/src/index/HybridScalarIndex.cpp
  internal/core/src/index/InvertedIndexTantivy.cpp
  internal/core/src/index/ScalarIndexSort.cpp
  internal/core/src/index/StringIndexMarisa.cpp
  internal/core/src/index/TextMatchIndex.cpp
  internal/core/src/index/Utils.cpp
  internal/core/src/index/Utils.h
  internal/core/src/index/VectorMemIndex.cpp
  internal/core/src/storage/BinlogReader.h
  internal/core/src/storage/DataCodec.cpp
  internal/core/src/storage/DataCodec.h
  internal/core/src/storage/DiskFileManagerImpl.cpp
  internal/core/src/storage/Event.cpp
  internal/core/src/storage/Event.h
  internal/core/src/storage/IndexData.cpp
  internal/core/src/storage/IndexData.h
  internal/core/src/storage/InsertData.cpp
  internal/core/src/storage/InsertData.h
  internal/core/src/storage/MemFileManagerImpl.cpp
  internal/core/src/storage/MemFileManagerImpl.h
  internal/core/src/storage/PayloadReader.cpp
  internal/core/src/storage/PayloadReader.h
  internal/core/src/storage/Types.h
  internal/core/src/storage/Util.cpp
  internal/core/src/storage/Util.h
  internal/core/unittest/test_array_bitmap_index.cpp
  internal/core/unittest/test_bitmap_index.cpp
  internal/core/unittest/test_chunk.cpp
  internal/core/unittest/test_data_codec.cpp
  internal/core/unittest/test_disk_file_manager_test.cpp
  internal/core/unittest/test_hybrid_index.cpp
  internal/core/unittest/test_inverted_index.cpp
  internal/core/unittest/test_json_key_stats_index.cpp
  internal/core/unittest/test_kmeans_clustering.cpp
  internal/core/unittest/test_utils/storage_test_utils.h
Labels: kind/enhancement, kind/improvement, size/XL, approved, lgtm, ci-passed, dco-passed, area/compilation

#41283 fix: Initialize streaming coordinator during mixCoord initialization
  internal/coordinator/mix_coord.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#41284 fix:Add debug memory freeing in sortStats
  internal/datanode/index/task_stats.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#41253 fix: Close client before remove worker client
  internal/datacoord/server_test.go
  internal/datacoord/session/indexnode_manager.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#41125 enhance: Get compaction params from request
  internal/compaction/params.go
  internal/compaction/params_test.go
  internal/datacoord/compaction_task_clustering.go
  internal/datacoord/compaction_task_l0.go
  internal/datacoord/compaction_task_mix.go
  internal/datacoord/compaction_trigger_test.go
  internal/datanode/compactor/clustering_compactor.go
  internal/datanode/compactor/clustering_compactor_storage_v2_test.go
  internal/datanode/compactor/clustering_compactor_test.go
  internal/datanode/compactor/merge_sort.go
  internal/datanode/compactor/mix_compactor.go
  internal/datanode/compactor/mix_compactor_storage_v2_test.go
  internal/datanode/compactor/mix_compactor_test.go
  internal/datanode/compactor/segment_writer.go
  internal/datanode/data_node.go
  pkg/proto/data_coord.proto
  pkg/proto/datapb/data_coord.pb.go
Labels: kind/enhancement, size/XXL, approved, lgtm, ci-passed, dco-passed

#41254 fix: [2.5] Close client before remove worker client
  internal/datacoord/session/indexnode_manager.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#41281 test: add alter collection checker
  tests/python_client/chaos/checker.py
  tests/python_client/chaos/testcases/test_single_request_operation.py
  tests/python_client/common/common_func.py
  tests/python_client/conftest.py
Labels: kind/improvement, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#41242 fix: Add save field schema log for kv_catalog.AlterCollection
  internal/metastore/kv/rootcoord/kv_catalog.go
  internal/metastore/kv/rootcoord/kv_catalog_test.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#41269 fix: [2.5] change log info to debug for collection ref
  internal/querynodev2/segments/collection.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass

#41309 enhance: use scan mode for like although inverted index exists
  internal/core/src/exec/expression/Expr.h
  internal/core/src/exec/expression/UnaryExpr.cpp
  internal/core/src/index/InvertedIndexTantivy.h
  internal/core/src/index/ScalarIndex.h
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed, manual-pass, do-not-merge/missing-related-pr

#41025 enhance: support binary range expression for json path index
  internal/core/src/exec/expression/BinaryRangeExpr.cpp
  internal/core/src/exec/expression/BinaryRangeExpr.h
  internal/core/unittest/test_expr.cpp
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#41315 fix: [2.5] update knowhere version to fix mac build
  internal/core/thirdparty/knowhere/CMakeLists.txt
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed, area/compilation, manual-pass, do-not-merge/missing-related-pr

#41328 enhance: Bump milvus & proto version to v2.5.10
  client/go.mod
  client/go.sum
  go.mod
  go.sum
  pkg/common/version.go
  pkg/go.mod
  pkg/go.sum
  tests/go_client/go.mod
  tests/go_client/go.sum
Labels: kind/enhancement, area/dependency, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed, manual-pass, kind/branch-feature

#41198 enhance: update tantivy for removing "doc_id" fast field
  internal/core/src/index/JsonKeyStatsInvertedIndex.cpp
  internal/core/thirdparty/tantivy/tantivy-binding/Cargo.lock
  internal/core/thirdparty/tantivy/tantivy-binding/include/tantivy-binding.h
  internal/core/thirdparty/tantivy/tantivy-binding/src/index_json_key_stats_writer.rs
  internal/core/thirdparty/tantivy/tantivy-binding/src/index_json_key_stats_writer_c.rs
  internal/core/thirdparty/tantivy/tantivy-binding/src/index_reader.rs
  internal/core/thirdparty/tantivy/tantivy-binding/src/index_reader_text.rs
  internal/core/thirdparty/tantivy/tantivy-binding/src/index_writer.rs
  internal/core/thirdparty/tantivy/tantivy-binding/src/index_writer_c.rs
  internal/core/thirdparty/tantivy/tantivy-binding/src/index_writer_v5/index_writer.rs
  internal/core/thirdparty/tantivy/tantivy-binding/src/index_writer_v5/index_writer_json_key_stats.rs
  internal/core/thirdparty/tantivy/tantivy-binding/src/index_writer_v5/index_writer_text.rs
  internal/core/thirdparty/tantivy/tantivy-binding/src/index_writer_v5/mod.rs
  internal/core/thirdparty/tantivy/tantivy-binding/src/index_writer_v7/index_writer.rs
  internal/core/thirdparty/tantivy/tantivy-binding/src/index_writer_v7/index_writer_json_key_stats.rs
  internal/core/thirdparty/tantivy/tantivy-binding/src/index_writer_v7/index_writer_text.rs
  internal/core/thirdparty/tantivy/tantivy-binding/src/index_writer_v7/mod.rs
  internal/core/thirdparty/tantivy/tantivy-binding/src/lib.rs
  internal/core/thirdparty/tantivy/tantivy-binding/src/milvus_id_collector.rs
  internal/core/thirdparty/tantivy/tantivy-wrapper.h
Labels: kind/enhancement, size/XL, approved, lgtm, ci-passed, dco-passed

#41330 fix:fix skip autoindex like expr
  internal/core/src/index/HybridScalarIndex.h
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#41329 fix: [2.5] skip dim check for non-vector fields in PreCheck (#41287)
  internal/datacoord/task_index.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#41340 test: [skip e2e]fix mixcoord label selectors
  tests/python_client/chaos/chaos_objects/pod_failure/chaos_mixcoord_pod_failure.yaml
  tests/python_client/chaos/chaos_objects/pod_kill/chaos_mixcoord_pod_kill.yaml
Labels: kind/improvement, sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed, manual-pass, kind/test

#41001 feat: Storage v2 growing segment load
  internal/core/src/common/ChunkWriter.cpp
  internal/core/src/common/ChunkWriter.h
  internal/core/src/common/FieldData.cpp
  internal/core/src/common/FieldData.h
  internal/core/src/common/FieldDataInterface.h
  internal/core/src/common/Schema.cpp
  internal/core/src/common/Schema.h
  internal/core/src/common/Types.h
  internal/core/src/segcore/ChunkedSegmentSealedImpl.cpp
  internal/core/src/segcore/SegmentGrowingImpl.cpp
  internal/core/src/segcore/SegmentGrowingImpl.h
  internal/core/src/segcore/memory_planner.cpp
  internal/core/src/segcore/memory_planner.h
  internal/core/src/storage/ChunkCache.cpp
  internal/core/thirdparty/milvus-storage/CMakeLists.txt
  internal/core/unittest/CMakeLists.txt
  internal/core/unittest/test_chunk.cpp
  internal/core/unittest/test_chunked_segment.cpp
  internal/core/unittest/test_growing.cpp
  internal/core/unittest/test_growing_storage_v2.cpp
  internal/core/unittest/test_memory_planner.cpp
  internal/core/unittest/test_types.cpp
  internal/core/unittest/test_utils/DataGen.h
Labels: kind/feature, size/XXL, approved, lgtm, ci-passed, dco-passed, area/compilation

#41251 enhance: optimize error log message for list policy
  internal/rootcoord/root_coord.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#41289 fix: skip dim check for non-vector fields in PreCheck (#41287)
  internal/datacoord/task_index.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed, do-not-merge/missing-related-pr

#41337 fix: update MixCoord registration in MilvusRoles
  cmd/roles/roles.go
  internal/proxy/proxy_test.go
  pkg/metrics/metrics_test.go
  pkg/metrics/rootcoord_metrics.go
Labels: kind/bug, size/S, approved, lgtm, dco-passed

#41297 fix: Fix panic with nil pointer dereference when get indexed segment
  internal/datacoord/index_meta.go
Labels: kind/bug, size/XS, approved, lgtm, dco-passed

#41346 fix: solve incompitable problem for none-encoding index
  internal/core/src/index/Meta.h
  internal/core/src/indexbuilder/index_c.cpp
  internal/core/src/storage/IndexData.cpp
  internal/core/src/storage/PayloadReader.h
  internal/core/src/storage/Types.h
  internal/core/src/storage/Util.cpp
  internal/datacoord/index_engine_version_manager.go
  internal/datacoord/index_engine_version_manager_test.go
  internal/datacoord/mock_index_engine_version_manager.go
  internal/datacoord/server.go
  internal/datacoord/session/mock_worker_manager.go
  internal/datacoord/task_index.go
  internal/querynodev2/server.go
  internal/util/sessionutil/session_util.go
  pkg/common/common.go
Labels: kind/bug, size/L, approved, lgtm, dco-passed

#41344 fix: correct wrong querynode metric labels
  internal/querynodev2/pipeline/filter_node.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#41358 enhance: Adapt hyphen in grpc metadata header
  pkg/util/logutil/grpc_interceptor.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#41350 fix: errorous deadlock report in unittests
  pkg/util/lock/mutex_deadlock.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#41370 test: Update binary pagination search assertion for more stable
  tests/python_client/check/func_check.py
  tests/python_client/common/common_func.py
  tests/python_client/milvus_client_v2/test_milvus_client_search_pagination.py
Labels: sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#41383 fix: Fix json index does not work for string filter
  internal/core/src/common/Types.h
Labels: kind/bug, size/XS, approved, lgtm, dco-passed

#40174 test: add concurrent index creation verification
  tests/restful_client_v2/testcases/test_index_operation.py
Labels: kind/improvement, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#41377 fix: errorous deadlock report in unittests (#41350)
  pkg/util/lock/mutex_deadlock.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#41372 enhance: [2.5] Adapt hyphen in grpc metadata header (#41358)
  pkg/util/logutil/grpc_interceptor.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#41382 fix: Fix json index does not work for string filter
  internal/core/src/common/Types.h
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#41374 fix: revert batch add
  internal/core/thirdparty/tantivy/tantivy-binding/include/tantivy-binding.h
  internal/core/thirdparty/tantivy/tantivy-binding/src/index_reader_text.rs
  internal/core/thirdparty/tantivy/tantivy-binding/src/index_writer.rs
  internal/core/thirdparty/tantivy/tantivy-binding/src/index_writer_c.rs
  internal/core/thirdparty/tantivy/tantivy-binding/src/index_writer_v5/index_writer.rs
  internal/core/thirdparty/tantivy/tantivy-binding/src/index_writer_v7/index_writer.rs
  internal/core/thirdparty/tantivy/tantivy-wrapper.h
  internal/core/unittest/test_text_match.cpp
Labels: kind/bug, size/XL, approved, lgtm, ci-passed, dco-passed

#41313 enhance: support nullable group by keys
  internal/core/src/common/QueryResult.h
  internal/core/src/common/Types.h
  internal/core/src/exec/operator/groupby/SearchGroupByOperator.cpp
  internal/core/src/exec/operator/groupby/SearchGroupByOperator.h
  internal/core/src/segcore/ReduceUtils.cpp
  internal/core/src/segcore/SegmentInterface.cpp
  internal/core/unittest/test_cached_search_iterator.cpp
  internal/core/unittest/test_expr.cpp
  internal/core/unittest/test_group_by.cpp
  internal/proxy/search_util.go
  internal/proxy/task_search_test.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#41294 feat: Ignore reporting index metrics for non-existent indexes
  internal/datacoord/metrics_info.go
Labels: kind/feature, size/XS, approved, lgtm, ci-passed, dco-passed

#41368 enhance: optimize error log message for list policy (#41251)
  internal/rootcoord/root_coord.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#41388 fix: [2.5]support infix and suffix match types in JsonStats
  internal/core/src/exec/expression/UnaryExpr.cpp
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#41326 fix: close of wal is block when recovery
  internal/streamingnode/server/wal/adaptor/ro_wal_adaptor.go
  internal/streamingnode/server/wal/adaptor/wal_adaptor.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#41095 enhance: Support Woodpecker as a WAL storage option for Milvus
  cmd/tools/config/generate.go
  configs/milvus.yaml
  go.mod
  go.sum
  internal/streamingnode/server/server.go
  internal/util/dependency/factory.go
  internal/util/dependency/factory_test.go
  internal/util/streamingutil/util/wal_selector.go
  internal/util/streamingutil/util/wal_selector_test.go
  pkg/go.mod
  pkg/go.sum
  pkg/mq/msgstream/mq_factory.go
  pkg/mq/msgstream/mq_factory_test.go
  pkg/mq/msgstream/mqwrapper/wp/wp_id.go
  pkg/streaming/util/message/adaptor/message_id.go
  pkg/streaming/util/message/adaptor/message_id_test.go
  pkg/streaming/walimpls/impls/wp/builder.go
  pkg/streaming/walimpls/impls/wp/message_id.go
  pkg/streaming/walimpls/impls/wp/message_id_test.go
  pkg/streaming/walimpls/impls/wp/opener.go
  pkg/streaming/walimpls/impls/wp/scanner.go
  pkg/streaming/walimpls/impls/wp/wal.go
  pkg/streaming/walimpls/impls/wp/wp_test.go
  pkg/util/paramtable/service_param.go
  pkg/util/paramtable/service_param_test.go
Labels: kind/enhancement, area/dependency, size/XXL, approved, lgtm, ci-passed, dco-passed, feature/streaming node

#41379 fix: transaction should retry if transaction is expired
  internal/distributed/streaming/util.go
  internal/distributed/streaming/wal_test.go
  internal/util/streamingutil/status/streaming_error.go
  internal/util/streamingutil/status/streaming_error_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#41236 fix: add node id check to avoid double flush at most time
  internal/coordinator/snmanager/streaming_node_manager.go
  internal/datacoord/services.go
  internal/mocks/streamingcoord/server/mock_balancer/mock_Balancer.go
  internal/streamingcoord/server/balancer/balancer.go
  internal/streamingcoord/server/balancer/balancer_impl.go
  internal/streamingcoord/server/balancer/channel/manager.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#41369 fix: solve incompitable problem for none-encoding index(#40838)
  internal/core/src/index/Meta.h
  internal/core/src/indexbuilder/index_c.cpp
  internal/core/src/storage/IndexData.cpp
  internal/core/src/storage/PayloadReader.h
  internal/core/src/storage/Types.h
  internal/core/src/storage/Util.cpp
  internal/datacoord/index_engine_version_manager.go
  internal/datacoord/index_engine_version_manager_test.go
  internal/datacoord/mock_index_engine_version_manager.go
  internal/datacoord/server.go
  internal/datacoord/session/mock_worker_manager.go
  internal/datacoord/task_index.go
  internal/querynodev2/server.go
  internal/util/sessionutil/session_util.go
  pkg/common/common.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed
