Repository milvus-io/milvus, pull requests merged in 2025-09, with the labels that each got.

#43900 enhance: make immutable message as the param of ack operation for cdc
  internal/datacoord/server.go
  internal/datacoord/server_test.go
  internal/distributed/streaming/broadcast.go
  internal/distributed/streaming/streaming.go
  internal/distributed/streaming/test_streaming.go
  internal/distributed/streaming/wal_test.go
  internal/mocks/distributed/mock_streaming/mock_Broadcast.go
  internal/mocks/streamingcoord/mock_client/mock_BroadcastService.go
  internal/proxy/proxy_test.go
  internal/streamingcoord/client/broadcast/broadcast_impl.go
  internal/streamingcoord/client/broadcast/broadcast_test.go
  internal/streamingcoord/client/client.go
  internal/streamingcoord/client/client_test.go
  internal/streamingcoord/server/balancer/balancer_test.go
  internal/streamingcoord/server/broadcaster/broadcast_manager.go
  internal/streamingcoord/server/broadcaster/broadcast_task.go
  internal/streamingcoord/server/broadcaster/broadcaster.go
  internal/streamingcoord/server/broadcaster/broadcaster_impl.go
  internal/streamingcoord/server/broadcaster/broadcaster_test.go
  internal/streamingcoord/server/broadcaster/registry/ack_message_callback.go
  internal/streamingcoord/server/broadcaster/registry/ack_message_callback_test.go
  internal/streamingcoord/server/broadcaster/registry/check_message_callback.go
  internal/streamingcoord/server/broadcaster/registry/check_message_callback_test.go
  internal/streamingcoord/server/broadcaster/registry/specialized_callback.go
  internal/streamingcoord/server/service/broadcast.go
  internal/streamingnode/client/handler/consumer/consumer_test.go
  internal/streamingnode/client/manager/manager_test.go
  internal/streamingnode/server/service/handler/consumer/consume_server.go
  internal/streamingnode/server/service/handler/consumer/consume_server_test.go
  internal/streamingnode/server/wal/recovery/recovery_storage_impl.go
  internal/util/streamingutil/service/discoverer/session_discoverer_test.go
  pkg/proto/streaming.proto
  pkg/proto/streamingpb/streaming.pb.go
  pkg/streaming/util/types/responses.go
Labels: kind/enhancement, size/XXL, approved, lgtm, ci-passed, area/internal-api, dco-passed

#44128 enhance: Add mutex and range check preventing concurrent del
  internal/querynodev2/segments/segment.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#44131 fix:expand lock range for dump_snapshot
  internal/core/src/segcore/DeletedRecord.h
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#44095 test: add field case about reranker and analyzer
  tests/python_client/milvus_client/test_add_field_feature.py
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#44143 enhance: support cchannel for streaming service
  internal/coordinator/snmanager/streaming_node_manager.go
  internal/coordinator/snmanager/streaming_node_manager_test.go
  internal/coordinator/snmanager/test_utility.go
  internal/datacoord/compaction_task_mix_test.go
  internal/distributed/streaming/append.go
  internal/distributed/streaming/msgstream_adaptor.go
  internal/distributed/streaming/wal.go
  internal/metastore/catalog.go
  internal/metastore/kv/streamingcoord/constant.go
  internal/metastore/kv/streamingcoord/kv_catalog.go
  internal/metastore/kv/streamingcoord/kv_catalog_test.go
  internal/mocks/mock_metastore/mock_StreamingCoordCataLog.go
  internal/mocks/streamingcoord/server/mock_balancer/mock_Balancer.go
  internal/querycoordv2/balance/streaming_query_node_channel_helper_test.go
  internal/querycoordv2/observers/replica_observer_test.go
  internal/rootcoord/garbage_collector_test.go
  internal/streamingcoord/client/assignment/discoverer.go
  internal/streamingcoord/server/balancer/balancer.go
  internal/streamingcoord/server/balancer/balancer_impl.go
  internal/streamingcoord/server/balancer/balancer_test.go
  internal/streamingcoord/server/balancer/channel/manager.go
  internal/streamingcoord/server/balancer/channel/manager_test.go
  internal/streamingcoord/server/service/discover/discover_grpc_server_helper.go
  internal/streamingcoord/server/service/discover/discover_server_test.go
  internal/streamingnode/server/wal/recovery/recovery_storage_impl.go
  internal/util/streamingutil/service/discoverer/session_discoverer_test.go
  pkg/proto/streaming.proto
  pkg/proto/streamingpb/streaming.pb.go
  pkg/streaming/util/message/utils.go
  pkg/streaming/util/types/streaming_node.go
Labels: kind/enhancement, size/XXL, approved, lgtm, ci-passed, area/internal-api, dco-passed

#44063 enhance: add configuration to allow custom characters in names (#42417)
  configs/milvus.yaml
  internal/proxy/util.go
  internal/proxy/util_test.go
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#44169 test: Add more ngram tests, including mmap and utf8 characters
  tests/python_client/milvus_client/expressions/test_milvus_client_scalar_filtering.py
  tests/python_client/testcases/indexes/idx_ngram.py
  tests/python_client/testcases/indexes/test_ngram.py
Labels: sig/testing, size/XL, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#44167 test: update nightly cases
  tests/python_client/milvus_client/test_milvus_client_collection.py
  tests/python_client/milvus_client/test_milvus_client_database.py
Labels: sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#44168 test: Increase PyMilvus version to 2.7.0rc25 for master branch
  tests/python_client/requirements.txt
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#44151 feat: Support enabling dynamic schema on existing collection
  internal/core/src/segcore/SegmentInterface.cpp
  internal/rootcoord/add_field_task.go
  internal/rootcoord/alter_dynamic_schema_task.go
  internal/rootcoord/alter_dynamic_schema_task_test.go
  internal/rootcoord/root_coord.go
  internal/rootcoord/root_coord_test.go
  internal/rootcoord/task.go
  internal/rootcoord/util.go
  pkg/common/common.go
  pkg/common/common_test.go
Labels: kind/feature, size/XL, approved, lgtm, ci-passed, dco-passed

#44155 fix: Fix panic when upsert with partial_update=true on empty table
  internal/proxy/task_upsert.go
  pkg/util/typeutil/schema.go
  pkg/util/typeutil/schema_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#44158 enhance: Fix operator apply in UpdateSegment
  internal/datacoord/meta.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#44144 enhance: update knowhere version
  internal/core/thirdparty/knowhere/CMakeLists.txt
  internal/core/thirdparty/milvus-common/CMakeLists.txt
  internal/core/unittest/test_sealed.cpp
  internal/core/unittest/test_vector_array_storage_v2.cpp
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed, area/compilation

#43962 feat: Add namespace prop
  configs/milvus.yaml
  internal/distributed/proxy/httpserver/utils.go
  internal/proxy/task.go
  internal/rootcoord/create_collection_task.go
  internal/rootcoord/create_collection_task_test.go
  internal/rootcoord/field_id.go
  pkg/common/common.go
  pkg/util/paramtable/component_param.go
Labels: kind/feature, size/L, approved, lgtm, ci-passed, dco-passed

#44178 enhance: removed unused VectorFunction
  internal/core/src/exec/expression/Element.h
  internal/core/src/exec/expression/Expr.h
  internal/core/src/exec/expression/VectorFunction.h
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#44181 test: add cohere, voyageai and siliconflow reranker testcases and some lints
  tests/python_client/milvus_client/test_milvus_client_search.py
Labels: kind/improvement, sig/testing, size/XL, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#44157 fix: ngram index for json rejects type of non-varchar field
  internal/util/indexparamcheck/ngram_index_checker.go
  internal/util/indexparamcheck/ngram_index_checker_test.go
  tests/python_client/testcases/indexes/idx_ngram.py
Labels: kind/bug, sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed

#44186 enhance: add autoindex config for deduplication case
  internal/proxy/task_index.go
  internal/util/indexparamcheck/constraints.go
  internal/util/indexparamcheck/utils.go
  pkg/util/paramtable/autoindex_param.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#43932 enhance: move c++ unit test file to aside of the production code
  internal/core/cmake/Utils.cmake
  internal/core/src/common/BitmapTest.cpp
  internal/core/src/common/ProtobufUtilsTest.cpp
  internal/core/src/common/SpanTest.cpp
  internal/core/src/common/UtilsTest.cpp
  internal/core/src/index/BitmapIndexTest.cpp
  internal/core/src/index/UtilsTest.cpp
  internal/core/src/query/SubSearchResultTest.cpp
  internal/core/src/query/UtilsTest.cpp
  internal/core/src/segcore/ReduceStructureTest.cpp
  internal/core/src/segcore/UtilsTest.cpp
  internal/core/src/storage/ThreadPoolsTest.cpp
  internal/core/unittest/CMakeLists.txt
  internal/core/unittest/test_utils.cpp
Labels: kind/enhancement, size/XL, approved, lgtm, ci-passed, dco-passed, area/compilation

#44202 enhance: [2.5] Add mutex and range check preventing concurrent del (#44128)
  internal/querynodev2/segments/segment.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#44179 test: migrate test_query V2 cases for milvus client
  tests/python_client/milvus_client/test_milvus_client_query.py
  tests/python_client/testcases/test_query.py
Labels: sig/testing, size/XXL, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#44208 fix: retry old session existence in ProcessActiveStandBy
  internal/util/sessionutil/session_util.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#44207 enhance: Reduce compaction task cleanup tolerance time
  configs/milvus.yaml
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#43742 enhance: optimize access log format when print kv params
  internal/proxy/accesslog/info/util.go
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#44223 fix: adjust params to make CPP UT run faster
  internal/core/unittest/test_binlog_index.cpp
  internal/core/unittest/test_c_api.cpp
  internal/core/unittest/test_c_stream_reduce.cpp
  internal/core/unittest/test_growing_index.cpp
  internal/core/unittest/test_index_c_api.cpp
  internal/core/unittest/test_index_wrapper.cpp
  internal/core/unittest/test_indexing.cpp
  internal/core/unittest/test_sealed.cpp
  internal/core/unittest/test_utils/c_api_test_utils.h
  internal/core/unittest/test_utils/indexbuilder_test_utils.h
  internal/core/unittest/test_vector_array_storage_v2.cpp
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#44245 enhance: add build(deps) as a valid pr format
  .github/mergify.yml
Labels: kind/enhancement, kind/improvement, size/XS, approved, lgtm, ci-passed, dco-passed

#44220 fix: add utf8 check before bm25 functoin run
  internal/util/function/bm25_function.go
  internal/util/function/multi_analyzer_bm25_function.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#44135 enhance: forbid panic when tantivy index path not exist
  internal/core/thirdparty/tantivy/tantivy-binding/src/util.rs
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#44256 fix: Fix MultiSegmentWrite only write one segment
  internal/datanode/compactor/multi_segment_writer_test.go
  internal/storage/serde_events_v2.go
Labels: kind/bug, size/XL, approved, lgtm, ci-passed, dco-passed, manual-pass

#44258 enhance: [StorageV2] Add configurable split policy
  internal/storagecommon/column_group_splitter.go
  internal/storagecommon/split_policy.go
  internal/storagecommon/split_policy_test.go
Labels: kind/enhancement, size/XL, approved, lgtm, ci-passed, dco-passed

#44222 fix: deduce metric type from non-empty search result
  internal/proxy/search_util.go
Labels: kind/bug, size/XS, approved, lgtm, dco-passed

#44198 feat: Auto add namespace field data if namespace is enabled
  go.mod
  go.sum
  internal/mocks/mock_proxy.go
  internal/proxy/impl.go
  internal/proxy/task_insert.go
  internal/proxy/task_insert_test.go
  internal/proxy/task_upsert.go
  internal/proxy/util.go
  internal/rootcoord/create_collection_task.go
  pkg/common/common.go
Labels: kind/feature, area/dependency, size/L, approved, lgtm, ci-passed, dco-passed

#44283 test: decrease ccache size to save github cache
  .github/workflows/mac.yaml
Labels: size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass, kind/test

#44142 fix: ngram index is mistakenly used for unsopported operations 2
  internal/core/src/exec/expression/BinaryArithOpEvalRangeExpr.h
  internal/core/src/exec/expression/BinaryRangeExpr.cpp
  internal/core/src/exec/expression/ExistsExpr.cpp
  internal/core/src/exec/expression/Expr.h
  internal/core/src/exec/expression/JsonContainsExpr.cpp
  internal/core/src/exec/expression/NullExpr.cpp
  internal/core/src/exec/expression/TermExpr.cpp
  internal/core/src/exec/expression/UnaryExpr.cpp
  internal/core/src/exec/expression/UnaryExpr.h
  internal/core/src/index/NgramInvertedIndexTest.cpp
  internal/core/unittest/test_utils/GenExprProto.h
Labels: kind/bug, size/XL, approved, lgtm, ci-passed, dco-passed, manual-pass

#44221 fix: [2.5] add utf8 check for bm25 functoin run
  internal/util/function/bm25_function.go
  internal/util/function/multi_analyzer_bm25_function.go
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#44285 test: fix stream node panic caused by ctx canceled
  internal/proxy/proxy_test.go
Labels: size/XS, approved, lgtm, ci-passed, dco-passed, kind/test

#44248 test: update nightly case
  tests/python_client/milvus_client/test_milvus_client_query.py
  tests/python_client/requirements.txt
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#44229 enhance: get cchannel before build message
  internal/distributed/streaming/append.go
  internal/distributed/streaming/msgstream_adaptor.go
  internal/distributed/streaming/streaming.go
  internal/distributed/streaming/test_streaming.go
  internal/distributed/streaming/wal.go
  internal/mocks/distributed/mock_streaming/mock_WALAccesser.go
  internal/streamingnode/server/flusher/flusherimpl/wal_flusher.go
  internal/streamingnode/server/wal/interceptors/txn/session.go
  internal/streamingnode/server/wal/recovery/recovery_storage_impl.go
  pkg/streaming/util/message/adaptor/message.go
  pkg/streaming/util/message/builder.go
  pkg/streaming/util/message/txn.go
  pkg/streaming/util/message/utils.go
  pkg/util/funcutil/func.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#44266 fix: idf oracle use wrong dir
  internal/querynodev2/delegator/delegator.go
  internal/querynodev2/delegator/idf_oracle.go
  internal/querynodev2/delegator/idf_oracle_test.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#44253 feat: add a namespace compactor
  internal/datanode/compactor/merge_sort.go
  internal/datanode/compactor/mix_compactor.go
  internal/datanode/compactor/mix_compactor_test.go
  internal/datanode/compactor/namespace_compactor.go
  internal/datanode/compactor/namespace_compactor_test.go
  internal/datanode/services.go
Labels: kind/feature, size/L, approved, lgtm, ci-passed, dco-passed, manual-pass

#44197 enhance: Optimize partial update merge logic by unifying nullable format
  internal/proxy/task_upsert.go
  internal/proxy/validate_util.go
  pkg/util/typeutil/schema.go
  pkg/util/typeutil/schema_test.go
  tests/python_client/common/common_func.py
  tests/python_client/milvus_client_v2/test_milvus_client_partial_update.py
Labels: kind/enhancement, sig/testing, size/XXL, approved, lgtm, area/test, ci-passed, dco-passed

#44360 fix: add init fs check for querynode and streaming node
  internal/querynodev2/server.go
  internal/streamingnode/server/server.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#44355 test: add case about enable dynamic schema
  tests/python_client/milvus_client/test_add_field_feature.py
  tests/python_client/milvus_client/test_milvus_client_alter.py
  tests/python_client/milvus_client/test_milvus_client_index.py
Labels: sig/testing, size/L, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#44350 fix: Fix invalid pre-allocated segment IDs
  internal/datacoord/compaction_task_meta.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#44136 enhance: [2.5] forbid panic when tantivy index path not exist
  internal/core/thirdparty/tantivy/tantivy-binding/src/util.rs
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#44271 fix: [2.5] Fix GetCompactionTo return empty results when segment was GCed
  internal/datacoord/segment_info.go
  internal/datacoord/segment_info_test.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#44277 enhance: Remove timeout for compaction task
  internal/datacoord/compaction_inspector_test.go
  internal/datacoord/compaction_task.go
  internal/datacoord/compaction_task_clustering.go
  internal/datacoord/compaction_task_clustering_test.go
  internal/datacoord/compaction_task_l0.go
  internal/datacoord/compaction_task_mix.go
  internal/datacoord/compaction_task_mix_test.go
  internal/datacoord/compaction_trigger.go
  internal/datacoord/compaction_trigger_test.go
  internal/datacoord/compaction_trigger_v2.go
  internal/datacoord/import_util.go
  internal/datanode/compactor/clustering_compactor_test.go
  internal/datanode/compactor/mix_compactor.go
  internal/datanode/compactor/mix_compactor_test.go
  internal/datanode/compactor/sort_compaction.go
  internal/datanode/compactor/sort_compaction_test.go
  pkg/proto/data_coord.proto
  pkg/proto/datapb/data_coord.pb.go
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/XXL, approved, lgtm, ci-passed, dco-passed, manual-pass

#44335 fix: [AddField] Forbid delete `dynamicfield.enable` property
  internal/rootcoord/alter_collection_task.go
  internal/rootcoord/alter_collection_task_test.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#44351 fix: [2.5] Fix invalid pre-allocated segment IDs
  internal/datacoord/compaction_task_meta.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed, manual-pass

#44201 feat: impl StructArray -- support import for CSV/JSON/PARQUET/BINLOG
  internal/datanode/importv2/util.go
  internal/storage/payload_writer.go
  internal/storage/serde_events.go
  internal/storage/utils.go
  internal/util/importutilv2/binlog/reader.go
  internal/util/importutilv2/binlog/reader_test.go
  internal/util/importutilv2/binlog/util.go
  internal/util/importutilv2/csv/row_parser.go
  internal/util/importutilv2/csv/row_parser_test.go
  internal/util/importutilv2/json/row_parser.go
  internal/util/importutilv2/json/row_parser_test.go
  internal/util/importutilv2/parquet/field_reader.go
  internal/util/importutilv2/parquet/reader.go
  internal/util/importutilv2/parquet/reader_test.go
  internal/util/importutilv2/parquet/util.go
  internal/util/testutil/test_util.go
  pkg/util/parameterutil/get_max_len.go
  pkg/util/typeutil/schema.go
  tests/integration/import/binlog_test.go
  tests/integration/import/vector_array_test.go
Labels: kind/feature, area/dependency, sig/testing, size/XXL, approved, lgtm, area/test, ci-passed, area/internal-api, dco-passed, area/compilation, manual-pass, test/integration

#44386 enhance: clean up vcpkg build
  DEVELOPMENT.md
  build/docker/builder/cpu/amazonlinux2023/Dockerfile
  build/docker/builder/cpu/rockylinux8/Dockerfile
  build/docker/builder/cpu/ubuntu20.04/Dockerfile
  build/docker/builder/cpu/ubuntu22.04/Dockerfile
  build/docker/builder/gpu/ubuntu20.04/Dockerfile
  build/docker/builder/gpu/ubuntu22.04/Dockerfile
  scripts/azure_build.sh
  scripts/core_build.sh
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#44382 enhance: base images use https to install apt package
  build/docker/milvus/gpu/ubuntu22.04/Dockerfile
  build/docker/milvus/ubuntu20.04/Dockerfile
  build/docker/milvus/ubuntu22.04/Dockerfile
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#44372 enhance: [StorageV2] Include partition & clustering key to sys group
  internal/storagecommon/column_group_splitter.go
  internal/storagecommon/split_policy.go
  internal/storagecommon/split_policy_test.go
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#44374 fix: pooling datanode upload without rootpath in L0 compaction
  internal/datanode/compactor/compactor_common.go
  internal/datanode/compactor/l0_compactor.go
  internal/datanode/compactor/l0_compactor_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#44381 feat: Add RESTful api for rolling upgrade support
  internal/coordinator/mix_coord.go
  internal/coordinator/restful_mgr_routes.go
  internal/coordinator/snmanager/streaming_node_manager.go
  internal/datacoord/garbage_collector.go
  internal/datacoord/mock_test.go
  internal/datacoord/services.go
  internal/distributed/streaming/balancer.go
  internal/distributed/streaming/balancer_test.go
  internal/distributed/streaming/streaming.go
  internal/distributed/streaming/test_streaming.go
  internal/http/router.go
  internal/querycoordv2/meta/resource_manager.go
  internal/querycoordv2/ops_services.go
  internal/querycoordv2/session/node_manager.go
  internal/querynodev2/segments/mock_segment.go
  internal/streamingcoord/client/client.go
  internal/streamingcoord/server/balancer/balancer_impl.go
  internal/streamingcoord/server/balancer/channel/manager.go
  internal/streamingcoord/server/service/discover/discover_grpc_server_helper.go
  internal/streamingcoord/server/service/discover/discover_server_test.go
  pkg/proto/data_coord.proto
  pkg/proto/datapb/data_coord.pb.go
  pkg/proto/streaming.proto
  pkg/proto/streamingpb/streaming.pb.go
  pkg/proto/streamingpb/streaming_grpc.pb.go
  scripts/start_cluster.sh
Labels: kind/feature, size/XXL, approved, lgtm, ci-passed, area/internal-api, dco-passed

#44402 enhance: [StorageV2] Use compressed size as log file size
  internal/core/src/segcore/packed_writer_c.cpp
  internal/core/src/segcore/packed_writer_c.h
  internal/flushcommon/syncmgr/pack_writer_v2.go
  internal/storage/serde_events_v2.go
  internal/storagev2/packed/util.go
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed

#44392 enhance: Support gis filter operator st_dwithin
  internal/core/src/common/Geometry.h
  internal/core/src/exec/expression/GISFunctionFilterExpr.cpp
  internal/core/src/expr/ITypeExpr.h
  internal/core/src/query/PlanProto.cpp
  internal/core/unittest/test_expr.cpp
  internal/parser/planparserv2/Plan.g4
  internal/parser/planparserv2/generated/Plan.interp
  internal/parser/planparserv2/generated/Plan.tokens
  internal/parser/planparserv2/generated/PlanLexer.interp
  internal/parser/planparserv2/generated/PlanLexer.tokens
  internal/parser/planparserv2/generated/plan_base_visitor.go
  internal/parser/planparserv2/generated/plan_lexer.go
  internal/parser/planparserv2/generated/plan_parser.go
  internal/parser/planparserv2/generated/plan_visitor.go
  internal/parser/planparserv2/parser_visitor.go
  internal/parser/planparserv2/plan_parser_v2_test.go
  internal/parser/planparserv2/utils.go
  pkg/proto/plan.proto
  pkg/proto/planpb/plan.pb.go
  tests/go_client/testcases/geometry_test.go
Labels: kind/enhancement, sig/testing, size/XXL, approved, lgtm, area/test, ci-passed, dco-passed, kind/branch-feature

#44280 enhance: compaction task metric bug
  internal/datacoord/compaction.go
Labels: kind/bug, kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed, manual-pass, kind/branch-feature

#44377 fix: turn on azure by default
  internal/core/src/CMakeLists.txt
  internal/core/src/storage/CMakeLists.txt
  internal/core/src/storage/azure/AzureBlobChunkManagerTest.cpp
  internal/core/src/storage/azure/AzureChunkManagerTest.cpp
  internal/core/unittest/CMakeLists.txt
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed, area/compilation

#44412 enhance: segment not flush at coord after schema change
  internal/flushcommon/pipeline/flow_graph_dd_node.go
Labels: kind/enhancement, priority/critical-urgent, size/S, approved, lgtm, ci-passed, dco-passed

#44421 fix:fix unescaped bug for json stats
  internal/core/src/exec/expression/UnaryExpr.cpp
  internal/core/src/index/json_stats/JsonKeyStats.cpp
  internal/core/src/index/json_stats/utils.h
  internal/core/unittest/test_json_stats/test_traverse_json_for_build_stats.cpp
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed, manual-pass

#44407 enhance: add all ddl message into messages
  Makefile
  internal/cdc/replication/replicatemanager/channel_replicator.go
  internal/datacoord/server.go
  internal/mocks/streamingcoord/server/mock_balancer/mock_Balancer.go
  internal/streamingcoord/server/balancer/balancer.go
  internal/streamingcoord/server/balancer/balancer_impl.go
  internal/streamingcoord/server/balancer/channel/manager.go
  internal/streamingcoord/server/balancer/channel/replicate_config.go
  internal/streamingcoord/server/broadcaster/registry/ack_message_callback_test.go
  internal/streamingcoord/server/broadcaster/registry/check_message_callback_test.go
  internal/streamingcoord/server/broadcaster/registry/specialized_callback.go
  internal/streamingcoord/server/service/assignment.go
  pkg/mocks/streaming/util/mock_message/mock_BroadcastMutableMessage.go
  pkg/mocks/streaming/util/mock_message/mock_ImmutableMessage.go
  pkg/mocks/streaming/util/mock_message/mock_ImmutableTxnMessage.go
  pkg/proto/etcd_meta.proto
  pkg/proto/etcdpb/etcd_meta.pb.go
  pkg/proto/internal.proto
  pkg/proto/internalpb/internal.pb.go
  pkg/proto/messages.proto
  pkg/proto/messagespb/messages.pb.go
  pkg/proto/streaming.proto
  pkg/proto/streamingpb/streaming.pb.go
  pkg/streaming/util/message/adaptor/message.go
  pkg/streaming/util/message/adaptor/message_type.go
  pkg/streaming/util/message/adaptor/ts_msg_newer.go
  pkg/streaming/util/message/broadcast.go
  pkg/streaming/util/message/ce/cache_expiration_builder.go
  pkg/streaming/util/message/ce/cache_expiration_builder_test.go
  pkg/streaming/util/message/ce/proxy_legacy_cache_builder.go
  pkg/streaming/util/message/codegen/main.go
  pkg/streaming/util/message/codegen/reflect_info.json
  pkg/streaming/util/message/marshal_log_object.go
  pkg/streaming/util/message/message.go
  pkg/streaming/util/message/message_impl.go
  pkg/streaming/util/message/message_test.go
  pkg/streaming/util/message/reflect_info.go
  pkg/streaming/util/message/resource_key.go
  pkg/streaming/util/message/resource_key_test.go
  pkg/streaming/util/message/specialized_message.go
Labels: kind/enhancement, size/XXL, approved, lgtm, ci-passed, area/internal-api, dco-passed, area/compilation

#44418 enhance: [StorageV2] Make datanode use non-singleton fs
  internal/core/src/segcore/SegmentGrowingImpl.cpp
  internal/core/src/segcore/SegmentGrowingStorageV2Test.cpp
  internal/core/src/segcore/memory_planner.cpp
  internal/core/src/segcore/memory_planner.h
  internal/core/src/segcore/packed_reader_c.cpp
  internal/core/src/segcore/packed_writer_c.cpp
  internal/core/src/segcore/storagev2translator/GroupChunkTranslator.cpp
  internal/core/src/storage/StorageV2FSCache.cpp
  internal/core/src/storage/StorageV2FSCache.h
  internal/core/src/storage/Util.cpp
  internal/core/thirdparty/milvus-storage/CMakeLists.txt
  internal/core/unittest/test_storage.cpp
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed, area/compilation

#44458 enhance: Move c API unittest aside to src files
  internal/core/src/index/UtilsTest.cpp
  internal/core/src/segcore/collection_c_test.cpp
  internal/core/src/segcore/load_field_data_c_test.cpp
  internal/core/src/segcore/load_index_c_test.cpp
  internal/core/src/segcore/plan_c_test.cpp
  internal/core/src/segcore/reduce_c_test.cpp
  internal/core/src/segcore/segment_c_test.cpp
  internal/core/src/segcore/vector_index_c_test.cpp
  internal/core/unittest/CMakeLists.txt
  internal/core/unittest/test_c_api.cpp
  internal/core/unittest/test_utils/c_api_test_utils.h
Labels: kind/enhancement, size/XXL, approved, lgtm, ci-passed, dco-passed, area/compilation

#44476 Revert FillPrimaryKeys
  internal/core/src/segcore/SegmentInterface.cpp
Labels: size/S

#44479 fix: Fix inserting geometry data bug by restful
  internal/distributed/proxy/httpserver/utils.go
  internal/distributed/proxy/httpserver/utils_test.go
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed, manual-pass, kind/branch-feature

#44468 enhance: Bump milvus & proto version to v2.5.18
  client/go.mod
  client/go.sum
  go.mod
  go.sum
  pkg/common/version.go
  pkg/go.mod
  pkg/go.sum
  tests/go_client/go.mod
  tests/go_client/go.sum
Labels: kind/enhancement, area/dependency, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed, kind/branch-feature

#44477 enhance: [h25] Add param item for hybrid search requery policy
  internal/proxy/search_reduce_util.go
  internal/proxy/task_search.go
  pkg/util/paramtable/component_param.go
Labels: size/M, approved

#44496 test: Increase PyMilvus version to 2.7.0rc34 for master branch
  tests/python_client/requirements.txt
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#44430 fix: Fix load config parsing using wrong parameters for dynamic replica
  internal/rootcoord/alter_collection_task.go
  tests/integration/replicas/load/load_test.go
Labels: kind/bug, sig/testing, size/S, approved, lgtm, area/test, ci-passed, dco-passed, test/integration

#44465 fix: LoadSegment failed for dup field mmap.enabel props
  internal/querycoordv2/task/utils.go
  internal/querycoordv2/task/utils_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#44499 enhance: Remove annoying warning log
  internal/util/hookutil/cipher.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#44459 enhance: Use std::shared_lock and std::unique_lock for mutexes
  internal/core/src/index/InvertedIndexTantivy.cpp
  internal/core/src/index/JsonInvertedIndex.cpp
  internal/core/src/index/JsonInvertedIndex.h
  internal/core/src/index/TextMatchIndex.cpp
Labels: kind/enhancement, size/S, approved, lgtm, ci-passed, dco-passed

#44433 enhance: tiered index updates
  configs/milvus.yaml
  internal/core/src/segcore/segcore_init_c.cpp
  internal/core/src/segcore/segcore_init_c.h
  internal/core/src/segcore/storagev1translator/SealedIndexTranslator.cpp
  internal/core/src/segcore/storagev1translator/SealedIndexTranslator.h
  internal/core/thirdparty/milvus-common/CMakeLists.txt
  internal/core/unittest/init_gtest.cpp
  internal/util/initcore/init_core.go
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed, area/compilation

#44535 fix: [StorageV2] Make DiskFileManager use fs from context
  internal/core/src/index/json_stats/JsonKeyStats.cpp
  internal/core/src/storage/DiskFileManagerImpl.cpp
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#44548 fix: upsert error for timestamptz
  internal/datacoord/compaction_trigger_v2.go
  internal/proxy/task_insert.go
  internal/proxy/task_upsert.go
  internal/proxy/util.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#44516 fix: set mmap_file_raii_ to nullptr when mmap is disabled
  internal/core/src/common/ChunkWriter.cpp
  internal/core/src/common/ChunkWriter.h
  internal/core/src/index/IndexFactory.cpp
  internal/core/src/index/StringIndexMarisa.cpp
  internal/core/unittest/test_loading.cpp
Labels: kind/bug, size/M, approved, lgtm, ci-passed, dco-passed

#44531 fix: Fix replicator cannot stop and enhance replicate config validator
  internal/cdc/replication/replicatemanager/replicate_manager.go
  internal/cdc/replication/replicatemanager/replicate_manager_test.go
  internal/cdc/replication/replicatestream/msg_queue.go
  internal/cdc/replication/replicatestream/msg_queue_test.go
  internal/cdc/replication/replicatestream/replicate_stream_client_impl.go
  internal/metastore/kv/streamingcoord/kv_catalog.go
  internal/streamingcoord/server/service/assignment.go
  pkg/util/replicateutil/config_validator.go
  pkg/util/replicateutil/config_validator_test.go
Labels: kind/bug, size/XL, approved, lgtm, ci-passed, dco-passed

#44467 enhance: [2.5] Add param item for hybrid search requery policy
  internal/proxy/search_reduce_util.go
  internal/proxy/task_search.go
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/M, approved, lgtm, ci-passed, dco-passed

#44508 enhance: broadcaster will lock resource until message acked
  internal/.mockery.yaml
  internal/coordinator/snmanager/streaming_node_manager.go
  internal/coordinator/snmanager/streaming_node_manager_test.go
  internal/coordinator/snmanager/test_utility.go
  internal/datacoord/server.go
  internal/datacoord/server_test.go
  internal/distributed/streaming/balancer_test.go
  internal/metastore/kv/streamingcoord/kv_catalog.go
  internal/metastore/kv/streamingcoord/kv_catalog_test.go
  internal/mocks/streamingcoord/server/mock_balancer/mock_Balancer.go
  internal/mocks/streamingcoord/server/mock_broadcaster/mock_BroadcastAPI.go
  internal/mocks/streamingcoord/server/mock_broadcaster/mock_Broadcaster.go
  internal/querycoordv2/balance/streaming_query_node_channel_helper_test.go
  internal/querycoordv2/observers/replica_observer_test.go
  internal/rootcoord/garbage_collector_test.go
  internal/streamingcoord/server/balancer/balance/singleton.go
  internal/streamingcoord/server/balancer/balance/test_utility.go
  internal/streamingcoord/server/balancer/balancer.go
  internal/streamingcoord/server/balancer/balancer_impl.go
  internal/streamingcoord/server/balancer/channel/manager.go
  internal/streamingcoord/server/broadcaster/ack_callback_scheduler.go
  internal/streamingcoord/server/broadcaster/broadcast/singleton.go
  internal/streamingcoord/server/broadcaster/broadcast/test_utility.go
  internal/streamingcoord/server/broadcaster/broadcast_manager.go
  internal/streamingcoord/server/broadcaster/broadcast_scheduler.go
  internal/streamingcoord/server/broadcaster/broadcast_task.go
  internal/streamingcoord/server/broadcaster/broadcaster.go
  internal/streamingcoord/server/broadcaster/broadcaster_test.go
  internal/streamingcoord/server/broadcaster/broadcaster_with_rk.go
  internal/streamingcoord/server/broadcaster/pending_broadcast_task.go
  internal/streamingcoord/server/broadcaster/registry/ack_message_callback.go
  internal/streamingcoord/server/broadcaster/registry/ack_message_callback_test.go
  internal/streamingcoord/server/broadcaster/resource_key_locker.go
  internal/streamingcoord/server/broadcaster/resource_key_locker_test.go
  internal/streamingcoord/server/broadcaster/tombstone_scheduler.go
  internal/streamingcoord/server/builder.go
  internal/streamingcoord/server/server.go
  internal/streamingcoord/server/service/assignment.go
  internal/streamingcoord/server/service/broadcast.go
  internal/streamingcoord/server/service/broadcast_test.go
  internal/streamingnode/client/handler/producer/producer_impl.go
  internal/streamingnode/client/handler/producer/producer_test.go
  internal/streamingnode/server/service/handler/producer/produce_server_test.go
  internal/streamingnode/server/wal/adaptor/wal_adaptor.go
  internal/streamingnode/server/wal/interceptors/timetick/timetick_interceptor.go
  internal/streamingnode/server/wal/metricsutil/append.go
  internal/streamingnode/server/wal/utility/context.go
  internal/streamingnode/server/wal/utility/context_test.go
  internal/util/testutil/reset_env.go
  pkg/kv/reliable_write_meta_kv.go
  pkg/kv/reliable_write_meta_kv_test.go
  pkg/streaming/util/message/broadcast.go
  pkg/streaming/util/message/broadcast_test.go
  pkg/streaming/util/types/responses.go
  pkg/streaming/util/types/responses_test.go
  pkg/util/lock/key_lock.go
  pkg/util/lock/key_lock_test.go
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/component_param_test.go
Labels: kind/enhancement, size/XXL, approved, lgtm, ci-passed, dco-passed

#44533 enhance: Don't start CDC by default in standalone mode
  cmd/milvus/util.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#44431 enhance: [2.5] Add granular flush targets support for FlushAll operation
  client/go.mod
  client/go.sum
  go.mod
  go.sum
  internal/datacoord/broker/coordinator_broker.go
  internal/datacoord/broker/coordinator_broker_test.go
  internal/datacoord/broker/mock_broker.go
  internal/datacoord/services.go
  internal/datacoord/services_test.go
  internal/distributed/datacoord/client/client.go
  internal/distributed/datacoord/client/client_test.go
  internal/distributed/datacoord/service.go
  internal/mocks/mock_datacoord.go
  internal/mocks/mock_datacoord_client.go
  internal/proxy/impl.go
  internal/proxy/impl_test.go
  internal/proxy/task.go
  internal/proxy/task_flush.go
  internal/proxy/task_flush_all.go
  internal/proxy/task_flush_all_streaming.go
  internal/proxy/task_flush_all_streaming_test.go
  internal/proxy/task_flush_all_test.go
  internal/proxy/task_flush_streaming.go
  pkg/go.mod
  pkg/go.sum
  pkg/proto/data_coord.proto
  pkg/proto/datapb/data_coord.pb.go
  pkg/proto/datapb/data_coord_grpc.pb.go
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/component_param_test.go
  scripts/run_go_codecov.sh
  scripts/run_go_unittest.sh
  tests/go_client/go.mod
  tests/go_client/go.sum
Labels: kind/enhancement, area/dependency, sig/testing, size/XXL, approved, lgtm, area/test, ci-passed, dco-passed

#44559 enhance: enable default json stats
  configs/milvus.yaml
  pkg/util/paramtable/component_param.go
Labels: kind/enhancement, size/XS, approved, lgtm, ci-passed, dco-passed

#44543 fix: Fix compaction task blocking due to executor loop exit
  internal/datanode/compactor/executor.go
  internal/datanode/compactor/executor_test.go
  internal/datanode/compactor/pool.go
  internal/datanode/compactor/pool_test.go
  internal/datanode/compactor/priority_queue.go
  internal/datanode/compactor/priority_queue_test.go
  internal/datanode/services.go
  internal/datanode/services_test.go
  internal/flushcommon/pipeline/data_sync_service.go
  internal/flushcommon/pipeline/flow_graph_dd_node.go
  internal/flushcommon/pipeline/flow_graph_dd_node_test.go
  internal/flushcommon/util/util.go
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/component_param_test.go
Labels: kind/bug, size/L, approved, lgtm, ci-passed, dco-passed

#44561 enhance: [go-sdk]allow users to insert pk data if autoid is enabled
  client/milvusclient/write_options.go
  client/row/data.go
  client/row/data_test.go
  tests/go_client/testcases/insert_test.go
Labels: kind/enhancement, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#44588 enhance: [2.5] Refactor balance checker with priority queue (#43992)
  internal/querycoordv2/balance/priority_queue.go
  internal/querycoordv2/balance/priority_queue_test.go
  internal/querycoordv2/balance/rowcount_based_balancer.go
  internal/querycoordv2/balance/score_based_balancer.go
  internal/querycoordv2/checkers/balance_checker.go
  internal/querycoordv2/checkers/balance_checker_test.go
  pkg/util/paramtable/component_param.go
  pkg/util/paramtable/component_param_test.go
Labels: kind/enhancement, size/XXL, approved, lgtm, ci-passed, dco-passed

#44579 test: Increase PyMilvus version to 2.7.0rc38 for master branch
  tests/python_client/requirements.txt
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed, kind/test

#44562 enhance: [go-sdk]allow users to insert pk data if autoid is enabled
  client/milvusclient/write_options.go
  client/row/data.go
  client/row/data_test.go
  tests/go_client/testcases/insert_test.go
Labels: kind/enhancement, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#44606 fix: Skip empty loop for process growing segment
  internal/core/src/exec/expression/Expr.h
Labels: kind/bug, size/XS, approved, lgtm, ci-passed, dco-passed

#44613 fix: don't use logical resource for metrics of quota center on streaming node
  internal/querynodev2/metrics_info.go
Labels: kind/bug, size/S, approved, lgtm, dco-passed

#44612 fix: Get R-Tree index correct for growing segment
  internal/core/src/segcore/SegmentGrowingImpl.h
Labels: kind/bug, size/S, approved, lgtm, dco-passed

#44512 enhance: add storage usage for delete/upsert/restful
  internal/distributed/proxy/httpserver/constant.go
  internal/distributed/proxy/httpserver/handler_v2.go
  internal/proxy/impl.go
  internal/proxy/task_delete.go
  internal/proxy/task_upsert.go
  internal/proxy/task_upsert_test.go
  internal/proxy/util.go
  internal/proxy/util_test.go
  pkg/metrics/proxy_metrics.go
Labels: kind/enhancement, size/XL, approved, lgtm, ci-passed, dco-passed, area/compilation

#44640 fix: [skip e2e] Wait eventch in `TestUpdateSessions`
  internal/util/sessionutil/session_util_test.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed

#44644 Revert "enhance: enable default json stats (#44559)"
  configs/milvus.yaml
  pkg/util/paramtable/component_param.go
Labels: size/XS, lgtm, ci-passed, dco-passed, manual-pass, do-not-merge/invalid-pr-format

#44618 enhance: Use dbName in error message
  internal/metastore/catalog.go
  internal/metastore/kv/rootcoord/kv_catalog.go
  internal/metastore/mocks/mock_rootcoord_catalog.go
  internal/rootcoord/meta_table.go
  internal/rootcoord/meta_table_test.go
  tests/python_client/milvus_client/test_milvus_client_alias.py
Labels: kind/enhancement, sig/testing, size/M, approved, lgtm, area/test, ci-passed, dco-passed

#44605 enhance: move tracer test to milvus-common
  internal/core/thirdparty/knowhere/CMakeLists.txt
  internal/core/thirdparty/milvus-common/CMakeLists.txt
  internal/core/unittest/CMakeLists.txt
  internal/core/unittest/test_tracer.cpp
Labels: kind/enhancement, size/L, approved, lgtm, ci-passed, dco-passed, area/compilation

#44626 fix: [GoSDK] Handle row->column input dynamic column
  client/milvusclient/write_options.go
Labels: kind/bug, size/S, approved, lgtm, ci-passed, dco-passed, component/gosdk

#44163 fix: resolve CVE-2020-25576, WS-2023-0223
  internal/core/thirdparty/tantivy/tantivy-binding/Cargo.lock
  internal/core/thirdparty/tantivy/tantivy-binding/Cargo.toml
  internal/core/thirdparty/tantivy/tantivy-binding/include/tantivy-binding.h
  internal/core/thirdparty/tantivy/tantivy-binding/src/analyzer/tokenizers/icu_tokneizer.rs
  pkg/proto/root_coord.proto
Labels: kind/bug, size/XXL, approved, lgtm, ci-passed, area/internal-api, dco-passed

#44649 test:Skip unstable test
  tests/python_client/milvus_client/test_milvus_client_query.py
Labels: sig/testing, size/XS, approved, lgtm, area/test, ci-passed, dco-passed, manual-pass, kind/test
